### ISSUE TITLE
TypeError: Cannot read property 'nodeType' of undefined" 

### ISSUE THREAD

**Issue by WolfForest** [ueberdosis/tiptap#1001]
https://github.com/ueberdosis/tiptap/blob/fffdb358a97ca2b79b51d72036576a158c28799b/examples/Components/Routes/Suggestions/index.vue#L78

If you specify one word an error appears
![image](https://user-images.githubusercontent.com/4728356/111388239-fad3eb80-86bf-11eb-9636-17ff77003cfe.png)

I can't understand why this problem is only if there is one word there

**Comment by Jordan-T** [comment]
I have the same issue!

**Comment by leobia** [comment]
Same issue

**Comment by hanspagel** [comment]
Thanks for reporting! Seems to be a duplicate of #932 so I’m closing this here. ✌️
