### ISSUE TITLE
Chrome page translation breaks the editor

### ISSUE THREAD

**Issue by do-web** [ueberdosis/tiptap#1002]
If a user translates the page with the chrome page translation feature then the editor did not work anymore, no more characters can be entered.

**Comment by hanspagel** [comment]
Thanks for reporting! Unfortunately, the Chrome translator breaks content editables. That breaks all editors and there’s no chance we can fix that.

**Comment by ff0041** [comment]
This may have been fixed with https://github.com/ProseMirror/prosemirror-view/commit/40ee2ef9882e352d7dde191f9e24fdeb8276cd88.
