### ISSUE TITLE
add  `markStore` in  `updateMark`

### ISSUE THREAD

**Issue by herrdu** [ueberdosis/tiptap#1005]
嗨，我看到了 Prosemirror 里面有一个关于 `toogleMark.js `  上面有一段关于 state.EditorState.storedMarks 的使用。

在 `updateMark.js` 里面没有，请问这里是否应该加上？

```
updateMark.js 

```
![image](https://user-images.githubusercontent.com/6762269/111935872-64f4f200-8aff-11eb-9574-f5bea2282731.png)

```
toggleMark.js in Prosemirror
```
![image](https://user-images.githubusercontent.com/6762269/111935918-78a05880-8aff-11eb-9537-66b576330060.png)

**Comment by hanspagel** [comment]
Thanks for reporting! Unfortunately, I fail to translate your report.

That said, we’re about to release tiptap v2 and won’t introduce breaking changes to v1. Thanks for your understanding!
