### ISSUE TITLE
Clear formatting option

### ISSUE THREAD

**Issue by ilicmarko** [ueberdosis/tiptap#101]
Is there a way to add a clear formatting button? I am trying to build a plugin but to be honest I don't know where to start.

Here is an example from [vue-wysiwyg](https://github.com/chmln/vue-wysiwyg)

https://chmln.github.io/vue-wysiwyg/

**Comment by dmitrybelyakov** [comment]
That would be really helpful. +1

**Comment by obuhhh** [comment]
+1

**Comment by xkubow** [comment]
+1

**Comment by ilicmarko** [comment]
@xkubow No workaround. This has to get implemented at the "core" level. Unfortunately, I am really busy thanks to my project manager. Maybe some other maintainers can focus on this.

**Comment by philippkuehn** [comment]
This should be possible with a custom command right now. What would you expect? Only clear marks (bold, italic, etc.) or also convert everything to plain text (headline to paragraph, etc.)? Links are marks too, so when removing all marks, links would also be removed.

**Comment by xkubow** [comment]
Probably could be there some options for this, but I would like to get plain text.

**Comment by holtwick** [comment]
@philippkuehn for me clearing just the marks and leaving everything else in place would be perfect. An option for leaving links in place or even better define a subset of marks that should be removed would be super awesome. Thanks.

**Comment by xkubow** [comment]
@philippkuehn by custom commands you mean extension? I didn't find any custom commands in documentations. Where could I find out how to do it?

**Comment by ilicmarko** [comment]
I am willing to tackle this. But I am swamped, probably will do it in October.

**Comment by git-mischa** [comment]
Is there an update on this?

**Comment by pmanikas** [comment]
+1

**Comment by llaurenz** [comment]
+1

**Comment by honsa** [comment]
@Leecason has done something in his version of tiptap, you can easy copy and paste the solution to your tiptap setup.

https://github.com/Leecason/element-tiptap/blob/master/src/utils/format_clear.ts

**Comment by philippkuehn** [comment]
Will come in v2

**Comment by hanspagel** [comment]
It’s added to tiptap 2, so I’m closing this here for now. 🙃

**Comment by doits** [comment]
@hanspagel can you please provide a link to the docs or give an example how to clear formatting in tiptap 2?

**Comment by philippkuehn** [comment]
There are two commands `clearNodes` and `unsetAllMarks`. Two reset nodes and marks you can do the following:

```js
editor
  .chain()
  .focus()
  .clearNodes()
  .unsetAllMarks()
  .run()
```

**Comment by doits** [comment]
Thanks!

**Comment by Sjoerd82** [comment]
> There are two commands `clearNodes` and `unsetAllMarks`. To reset both nodes and marks you can do the following:
> 
> ```js
> editor
>   .chain()
>   .focus()
>   .clearNodes()
>   .unsetAllMarks()
>   .run()
> ```

Good to know that it is possible. But how to do this in my Vue editor? Do I need to create a new extension for this somehow?

**Comment by hallucinogenizer** [comment]
> There are two commands `clearNodes` and `unsetAllMarks`. To reset both nodes and marks you can do the following:
> 
> ```js
> editor
>   .chain()
>   .focus()
>   .clearNodes()
>   .unsetAllMarks()
>   .run()
> ```

If someone wants to clear all formatting from the entire document, i.e. not just from the current selected section, then just add a `.selectAll()` to this chain of commands by [philippkuehn](https://github.com/philippkuehn).

**Comment by Shamoyeeta** [comment]
> There are two commands `clearNodes` and `unsetAllMarks`. To reset both nodes and marks you can do the following:
> 
> editor
>   .chain()
>   .focus()
>   .clearNodes()
>   .unsetAllMarks()
>   .run()

There seems to be an issue with the above approach when using nested lists, it fails to remove the nodes which have nested children. Any workarounds for the same?

https://github.com/user-attachments/assets/5fdfa49b-692d-4c43-b4ad-34fc9e5d0839
