### ISSUE TITLE
Link suggestions

### ISSUE THREAD

**Issue by jsmitsams** [ueberdosis/tiptap#1015]
Apart from tiptap being awesome one feature I'm missing it the ability to add link suggestions. It would be great if we can add a search bar to links the similar to the way suggestions are working (https://www.tiptap.dev/suggestions). This would allow internal links to being created a lot more easily.

**Comment by philippkuehn** [comment]
I’m not sure what you mean with "link suggestions". Internal links to linked headings?

**Comment by jsmitsams** [comment]
> I’m not sure what you mean with "link suggestions". Internal links to linked headings?

No, I mean for linking to internal pages. So when adding a hyperlink you can search an API endpoint to autosuggest urls. Similar to wordpress is doing this. As you can see you can add a link to a page easily or just fill in a manual URL.

![Image of WP editor](https://i.imgur.com/WhfQkOD.png)

**Comment by philippkuehn** [comment]
Ah ok. You can do this already now. There is an example for implementing [slash commands](https://www.tiptap.dev/experiments/commands). This may help for the first steps. Since this is a very specific feature, I’m closing this here.
