### ISSUE TITLE
Is is possible to realize spoiler?

### ISSUE THREAD

**Issue by Winexcel** [ueberdosis/tiptap#1018]
**Is your feature request related to a problem? Please describe.**
I try to realise a spoiler component which can show and hide text by click on the button
![Безымянный](https://user-images.githubusercontent.com/18466364/114751334-3a552c80-9d7f-11eb-9abd-d5d4465e31e7.png)

This is an extension:

![Безымянный](https://user-images.githubusercontent.com/18466364/114753393-9caf2c80-9d81-11eb-90c4-c7ae71942c06.png)

**Describe the solution you'd like**
I want to show/hide text then i click by the button "Show content"

How is it possible to achieved?

**Comment by Winexcel** [comment]
I managed to do this thing with this approach:
![image](https://user-images.githubusercontent.com/18466364/115122156-ab474f00-9fe0-11eb-9e40-1fed4093fc27.png)

This component just update attr "show", but there is a problem, i don't know how to add caption for my spoiler, because i can't add another "content" ref, is it possible to add another "content" ref to this component or realize it in another way? @hanspagel 

![image](https://user-images.githubusercontent.com/18466364/115122222-07aa6e80-9fe1-11eb-9989-c019f542dadf.png)

**Comment by hanspagel** [comment]
Thanks for sharing! 🙌

We’ve built something pretty similar with the native `<details>` and `<summary>` tags for tiptap v2:
https://www.tiptap.dev/experiments/details

I’m closing this here for now, but feel free to comment.

**Comment by Winexcel** [comment]
Oh my godness! This is incredible! Great thanks for this thing! It seems it cured my pain.

**Comment by Winexcel** [comment]
> Thanks for sharing! 🙌
> 
> We’ve built something pretty similar with the native `<details>` and `<summary>` tags for tiptap v2:
> https://www.tiptap.dev/experiments/details
> 
> I’m closing this here for now, but feel free to comment.

I have just tested this extension, it seems this have many bugs.

Therefore I have a question - How can i use my custom component in tiptap 2.0 like above component which was be written for tiptap 1.0?

**Comment by philippkuehn** [comment]
> I have just tested this extension, it seems have many bugs.

That’s why it’s still listed as experiment.

> Therefore I have a question - How can i use my custom component in tiptap 2.0 like above component which was be written for tiptap 1.0?

There is an upgrade guide: https://www.tiptap.dev/overview/upgrade-guide
