### ISSUE TITLE
Specific interaction where bubble menu fails to open

### ISSUE THREAD

**Issue by Deckluhm** [ueberdosis/tiptap#1038]
**What happens?**

If you start selecting text from the "outside" of the editor, it fails to open bubble menu.
It's probably not that clear so please check the small video I made below.

Note that the issue is present on both tiptap 1 and 2.

**How can others reproduce the issue?**

1. Go to https://next.tiptap.dev/guide/menus/#bubble-menu
2. Start selecting text just before the first letter (so "outside" of the actual editor)
3. It should open the bubble menu but doesn't

**What behavior did you expect?**

Bubble menu should open even if you do what's described above.

**Do you have a screenshot?**

You can see a working example first then a failing one: https://imgur.com/a/Eu4BcT8

**What’s your environment?**

 - Operating system: Ubuntu 20.10
 - Browser: Firefox 87.0
 - Mobile/desktop: Desktop

**Comment by philippkuehn** [comment]
This seems to be different browser behavior where we can't really do anything :(
