### ISSUE TITLE
Marks not splitting when combining attributes

### ISSUE THREAD

**Issue by cpauwels** [ueberdosis/tiptap#1039]
**What happens?**
It's hard to explain, but here is a screen recording of the issue, including with the desired behavior in Google Docs:

![Screen Recording 2021-04-13 at 11 58 38 AM](https://user-images.githubusercontent.com/4594196/114534982-d849d980-9c4f-11eb-8d2e-1fb134862490.gif)

I created a "Style" mark (source in the CSB below) that allows me to set the `color` and `font-style` on a `span`. It works great when only setting one of the two attributes, or when setting multiple attributes to a same selection, but when the selection spans two "Style" marks, the whole selection gets included in the left-most mark, instead of setting the attributes separately on each mark, or creating a third mark if needed.

Is there a way to get to my mark to behave similar to Google Docs? I couldn't figure it out from the docs.

Thanks

**How can others reproduce the issue?**
I created a codesandbox here: 
https://codesandbox.io/s/tiptap-issue-template-forked-sjflo?fontsize=14&hidenavigation=1&theme=dark&file=/src/tiptap-style.js

You can try it out here:
https://sjflo.csb.app/

**Comment by philippkuehn** [comment]
hey, with the latest release, this should now work as expected!
