### ISSUE TITLE
Dynamic id on each node

### ISSUE THREAD

**Issue by flaviouk** [ueberdosis/tiptap#1041]
Hi does anyone know how to get a dynamically generated id on nodes?
I got the ids to show in the attributes but they keep the same value for all nodes

![image](https://user-images.githubusercontent.com/8357327/114031749-93026200-9873-11eb-8374-af817e739dbd.png)

I've tried:
* https://github.com/ueberdosis/tiptap/issues/252
* https://next.tiptap.dev/guide/node-views/examples/#table-of-contents

Ideally I want something like `defaultOnCreate: uuid()` instead of `default: uuid()`

Having to mess around with editor.state.doc.descendants feels so wrong

**Comment by philippkuehn** [comment]
I’m working on an official unique id extension.

**Comment by YousefED** [comment]
Cool to hear @philippkuehn !

fwiw, I prototyped something similar yesterday:

```typescript
appendTransaction: (transactions, oldState, newState) => {
          if (newState.doc === oldState.doc) {
            // no changes
            return;
          }
          const tr = newState.tr;

          // Automatically assign ids to nodes that are:
          // - a direct child of the root document
          // - a direct child of a list (e.g.: <ul>, <ol>)

          // We can probably optimize this for performance
          newState.doc.descendants((node, pos, parent) => {
            if (node.isBlock && (parent === newState.doc || isList(parent))) {
              if (!node.attrs["block-id"]) {
                tr.setNodeMarkup(pos, undefined, {
                  ...node.attrs,
                  "block-id": uniqueId(),
                });
              }
            } else {
              // remove id
              if (node.attrs["block-id"]) {
                tr.setNodeMarkup(pos, undefined, {
                  ...node.attrs,
                  "block-id": undefined,
                });
              }
            }
          });
          return tr;
        },
      }),
```

I don't expect it to be, but perhaps its helpful for you now you're getting started on this. Note that you can see in my scenario that I don't want to give all blocks an id.

**Comment by philippkuehn** [comment]
@YousefED Thanks but I’m having an almost finished version already. What I can say is that it’s way more complex :) You will be able to add ids to a specific list of nodes and get some events for added, removed or updated nodes.

**Comment by YousefED** [comment]
Awesome 🔥

**Comment by pvamshi** [comment]
Everything was perfect until I decided to save each node to database :D . @philippkuehn can you please share your status. 🙏🏼

**Comment by flaviouk** [comment]
Any update on this feature? 🙏🏻

**Comment by arnogramatke** [comment]
I would like to use this extension as well. Any news on this? 😀

**Comment by marbiano** [comment]
This feature is what literally is preventing me from ditching Sanity and building my own experience. Is there any ETA on this?

**Comment by flaviouk** [comment]
I got it working with this in case anyone needs it.

- rendered is so that when you copy-paste the ids are not copied as well
- keepOnSplit is so that when you create a new line, it doesn't reuse the same id

```ts
const types = {
  [Type.HEADING]: true,
}

export const BlockId = Node.create({
  name: 'blockId',

  addGlobalAttributes() {
    return [
      {
        types: Object.keys(types),
        attributes: {
          blockId: {
            default: null,
            rendered: false,
            keepOnSplit: false,
          },
        },
      },
    ]
  },

  addProseMirrorPlugins() {
    return [
      new Plugin({
        appendTransaction: (_transactions, oldState, newState) => {
          // no changes
          if (newState.doc === oldState.doc) {
            return
          }
          const tr = newState.tr

          newState.doc.descendants((node, pos, parent) => {
            if (
              node.isBlock &&
              parent === newState.doc &&
              !node.attrs.blockId &&
              types[node.type.name]
            ) {
              tr.setNodeMarkup(pos, undefined, {
                ...node.attrs,
                blockId: pushid(),
              })
            }
          })

          return tr
        },
      }),
    ]
  },
})

```

**Comment by hanspagel** [comment]
Thanks for sharing the code @flaviouk! Our official package, which handles a few more cases, is now available to all sponsors and pro subscribers:
https://tiptap.dev/api/extensions/unique-id

✌️

**Comment by ollyde** [comment]
@hanspagel how do we reload the same IDs from the database? For example comment popup nodes.

I'm using nodes

```
  const HighlightedText = Mark.create({
    name: "comment",
    toDOM: () => {
      return ["span", { class: "highlighted-text", id: () => generateSafeHtmlId() }, 0];
    },
    renderHTML({ HTMLAttributes }) {
      return ["span", mergeAttributes({ class: "highlighted-text" }, HTMLAttributes), 0];
    },
    
    parseHTML() {
      return [
        {
          tag: "span.highlighted-text",
          getAttrs: (node: string | HTMLElement) => {
            if (typeof node === "string") {
              return {};
            } else {
              // If it's an HTMLElement
              return {
                id: node.getAttribute("id"),
              };
            }
          },
        },
      ];
    },
  });
```

**Comment by ollyde** [comment]
Ok, I figured it out, but I get id=[Object] when getting it back from the database, it's not stored as object, but as ID hmm.


```
  /**
   * Comment highlighting with unquie id for popout.
   */
  const HighlightedText = Mark.create({
    name: "comment",
    toDOM: () => {
      return ["span", { class: "highlighted-text" }, 0];
    },
    renderHTML({ HTMLAttributes }) {
      return ["span", mergeAttributes({ class: "highlighted-text" }, HTMLAttributes), 0];
    },
    addGlobalAttributes() {
      return [
        {
          types: ["comment"],
          attributes: {
            id: {
              default: generateSafeHtmlId(),
              parseHTML: (element: HTMLElement) => {
                return {
                  id: element.getAttribute("id") ?? generateSafeHtmlId(),
                };
              },
              renderHTML: (attributes: { id: string }) => {
                return {
                  id: attributes?.id ?? generateSafeHtmlId(),
                };
              },
            },
          },
        },
      ];
    },
    parseHTML() {
      return [
        {
          tag: "span.highlighted-text",
          getAttrs: (node: string | HTMLElement) => {
            if (typeof node === "string") {
              return {};
            } else {
              const id = node.getAttribute("id");
              return {
                id: id,
              };
            }
          },
        },
      ];
    },
  });
```

**Comment by ollyde** [comment]
For anyone else stuck, I needed to do this funky stuff

```
renderHTML({ HTMLAttributes }) {
    let id = null;

    if (typeof HTMLAttributes["id"] === "string") {
      id = HTMLAttributes["id"];
    } else if (typeof HTMLAttributes["id"]["id"] === "string") {
      id = HTMLAttributes["id"]["id"];
    } else {
      id = generateSafeHtmlId();
    }

    return ["span", { class: "highlighted-text", id: id }, 0];
  },
```

**Comment by Madd0g** [comment]
has anyone dealt with this in the recent versions? No matter how I try, `keepOnSplit` doesn't work.

I'm trying to do a `CustomParagraph` that writes/reads the id from the html. This seems to work until I hit enter in the middle of the paragraph, then it's split with the same id, regardless of `keepOnSplit`. I try assigning my own id on renderHTML, it's visible in the HTML but when I do editor.getJSON, I get the same old id duplicated twice, not the one I assigned in renderHTML (which make sense, sort of, such things should be in transactions).

So I tried playing with `appendTransaction`, it's not called on creation, which is ok, I guess, the ids  seem to work at creation time. But also, if at the time of transaction, it doesn't respect `keepOnSplit`, I have no way of knowing which node to assign the new id to, I just know there are 2 nodes with the same id.

Any ideas?

**Comment by xiangshu233** [comment]
How does the official uid extension add `data-id` to a custom node?
```js
UniqueID.configure({
  types: ['heading', 'paragraph', 'custom-question'],
})
```
It doesn't work
![image](https://github.com/ueberdosis/tiptap/assets/49575330/62b3dd96-aa20-4820-a6dd-afcd45ca0480)
It seems that only the default nodes are added?

![image](https://github.com/ueberdosis/tiptap/assets/49575330/f325a5b1-bbc9-466f-bd45-4f313959905b)

**Comment by denyramandaa** [comment]
> How does the official uid extension add `data-id` to a custom node?
> 
> ```js
> UniqueID.configure({
>   types: ['heading', 'paragraph', 'custom-question'],
> })
> ```
> 
> It doesn't work ![image](https://private-user-images.githubusercontent.com/49575330/338916734-62b3dd96-aa20-4820-a6dd-afcd45ca0480.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNjM5ODUsIm5iZiI6MTcyMTM2MzY4NSwicGF0aCI6Ii80OTU3NTMzMC8zMzg5MTY3MzQtNjJiM2RkOTYtYWEyMC00ODIwLWE2ZGQtYWZjZDQ1Y2EwNDgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA0MzQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMzk4ODhjMTA5MjRmYzgwZmVmMGUyZGYyODlkZTI2M2QyOTcyZjQ3ZmQ3M2Y5M2Q2NGNkNzg5NmY2ZTRmNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gfmyuhw76IyQJ1Vkecj3J-JQuRf0KzTtpwGPML_lVtA) It seems that only the default nodes are added?
> 
> ![image](https://private-user-images.githubusercontent.com/49575330/338917060-f325a5b1-bbc9-466f-bd45-4f313959905b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNjM5ODUsIm5iZiI6MTcyMTM2MzY4NSwicGF0aCI6Ii80OTU3NTMzMC8zMzg5MTcwNjAtZjMyNWE1YjEtYmJjOS00NjZmLWJkNDUtNGYzMTM5NTk5MDViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA0MzQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiM2Q0YzViMDgyMjdlYjE5NTY5NDJmMTBjNWU2NTI0MmE2ODA2YWQzMjE3MzEyMzU2ZTc2NmZmY2UyY2VhZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XMiA0FWk-nsMHGQC2ASGurG5sCAzyGy2gantESx9O_o)

Waiting for the answer also

**Comment by MagnetoLee** [comment]
> has anyone dealt with this in the recent versions? No matter how I try, `keepOnSplit` doesn't work.
> 
> I'm trying to do a `CustomParagraph` that writes/reads the id from the html. This seems to work until I hit enter in the middle of the paragraph, then it's split with the same id, regardless of `keepOnSplit`. I try assigning my own id on renderHTML, it's visible in the HTML but when I do editor.getJSON, I get the same old id duplicated twice, not the one I assigned in renderHTML (which make sense, sort of, such things should be in transactions).
> 
> So I tried playing with `appendTransaction`, it's not called on creation, which is ok, I guess, the ids seem to work at creation time. But also, if at the time of transaction, it doesn't respect `keepOnSplit`, I have no way of knowing which node to assign the new id to, I just know there are 2 nodes with the same id.
> 
> Any ideas?



remove tiptap UniqueID extension, keepOnSplit works

**Comment by alexgorbatchev** [comment]
This seems to work pretty well

https://github.com/MoltenCoffee/tiptap-unique-id/tree/main
