### ISSUE TITLE
HTML to JSON?

### ISSUE THREAD

**Issue by zeljko-bulatovic** [ueberdosis/tiptap#1042]
**Is your feature request related to a problem? Please describe.**
I need functionality to convert html to the yDoc so that i can store it in the database, for later load in the editor.

**Describe the solution you’d like**
Like we have generateHTML() method from @tiptap/html package, i would like to have opposite function, say generateJSONFromHtml()

Maybe such functionality exists, but i am not able to find it.
Thank you!

**Comment by tylerforesthauser** [comment]
> I need it because i have api endpoint that accepts html from other sources, which can be later open and edited in the editor. Sure, i can make some workaround to temporary save html in the database, then open it on the front end and use front end to do the conversion and then update database again with the JSON, but i am not sure that is the right path.

+1
I'm in the same boat. I would love this sort of functionality!

**Comment by jaexplorer** [comment]
This is preventing me from going from Slate JS to this editor. I need to convert from HTML and back to it to store.

**Comment by BrianHung** [comment]
A rough sketch to do this could be to use the ProseMirror [DOMParser](https://github.com/ProseMirror/prosemirror-model/blob/master/src/from_dom.js) class along with a `DOM` workaround in node.js such as jsdom (?).

**Comment by philippkuehn** [comment]
We’ve added a `generateJSON` method: https://www.tiptap.dev/api/utilities/html/#generate-json-from-html

I’m closing this but I’m sure that we’ll rename the `@tiptap/html` package in the near future because that name doesn’t really make sense anymore currently. Any suggestions? 

I’ll keep you updated!

**Comment by OwenianWodicus** [comment]
Same issue as @philippkuehn

**Comment by ryanjafari** [comment]
> @philippkuehn
> 
> ```
> [2023-01-07 09:56:28.693] error: window is not defined
> ReferenceError: window is not defined
>     at elementFromString (C:\Users\...\...\node_modules\@tiptap\core\dist\tiptap-core.cjs.js:1563:5)
> ```

Make sure you are importing generateJSON from @tiptap/html, not @tiptap/core - that was my problem.
