### ISSUE TITLE
Enabling / disabling extensions after initializations

### ISSUE THREAD

**Issue by YousefED** [ueberdosis/tiptap#1044]
I don't think it's currently possible to remove / add new extensions after the editor has been initialised, correct?

My scenario is that I want the end-user to control the behaviour of the editor, and part of that would be to enable / disable / load extensions. 

Is this something you're considering?

**Comment by deathg0d** [comment]
Hi @YousefED, did you solve this? I am also trying to provide a button that the user can click to enable and disable features like these: https://www.tiptap.dev/examples/savvy/

**Comment by YousefED** [comment]
> Hi @YousefED, did you solve this? I am also trying to provide a button that the user can click to enable and disable features like these: https://www.tiptap.dev/examples/savvy/

Haven't been able to look into this unfortunately

**Comment by kwarc-star** [comment]
@philippkuehn Any other way to achieve this? Enabling disabling dynamically would be pretty useful for many extensions.

**Comment by philippkuehn** [comment]
It’s difficult to solve with ProseMirror. In the end, I would also have to reinitialize the editor under the hood, which only makes things more complicated. If you need this feature, the easiest way is to manually destroy and mount the editor.

**Comment by vadimdemedes** [comment]
I've just ran into this limitation too. I have a mark extension that conditionally applies a class in `renderHTML` based on the `this.options` field. However, there seems to be no way to update options of an extension or reinitialize an extension.

ProseMirror allows reconfiguring options via [`reconfigure`](https://prosemirror.net/docs/ref/#state.EditorState.reconfigure) function, but TipTap doesn't expose anything like that.

Is there at least a workaround we can use, if it's not possible to support that natively in TipTap?

> I do wonder however why a rerender is such an issue?

To answer an earlier question, recreating an editor loses user's selection, cursor position in the editor and unfocuses the editor. If this happens while user is typing, it's a pretty bad user experience to suddenly prevent them from typing.

**Comment by Slapbox** [comment]
I think a hypothetical `unregisterExtension` or something like it should be allowed for any extension which doesn't modify the schema - which would be a lot of them I think.

**Comment by Kasheftin** [comment]
Is it possible to reconfigure tiptap extension? For example, I'm using `@tiptap/extension-placeholder` like this (vue3):
````
const editor = useEditor({
  ...
  extensions: [
    Placeholder.configure({
      placeholder: i18n.t('tiptap.placeholder')
    })
  ]
})
````
If a user changes the locale I want placeholder text to be updated. How to do this?

**Comment by hyanmandian** [comment]
> Is it possible to reconfigure tiptap extension? For example, I'm using `@tiptap/extension-placeholder` like this (vue3):
> 
> ```
> const editor = useEditor({
>   ...
>   extensions: [
>     Placeholder.configure({
>       placeholder: i18n.t('tiptap.placeholder')
>     })
>   ]
> })
> ```
> 
> If a user changes the locale I want placeholder text to be updated. How to do this?

I face the same issue and I did this:

```tsx
useEffect(() => {
      if (!editor) return;

      for (const extension of editor.extensionManager.extensions) {
        if (extension.name === ExtensionPlaceholder.name) {
          extension.options.placeholder = placeholder;
        }
      }

      // Trigger an update
      editor.setOptions();
    }, [editor, placeholder]);
``

ugly but it works, another way to solve it is using the second parameter of `useEditor` (deps) but it destroys and recreate the editor :(

**Comment by hyanmandian** [comment]
Quickly update over my implementation. I found this https://codesandbox.io/p/sandbox/suggestion-mention-update-list-xypnd3?file=%2Fsrc%2FEditor.js%3A60%2C18 on Tiptap discord and I applied the same approach for placeholder and it works nicely :D
