### ISSUE TITLE
A11y: focus styles for links and buttons (docs & demos)

### ISSUE THREAD

**Issue by mariohamann** [ueberdosis/tiptap#1047]
https://github.com/ueberdosis/tiptap-next/blob/3cf22b02c6cfba27b13f21422546f9076d5653e7/docs/src/layouts/App/base.scss#L12

In TipTap's docs and demos outlines for  `:focus` are disabled, but there is no fallback or alternative for links and buttons. Therefore the website is unusable for keyboard users.

→ I'm currently building a Pull Request which handles this issue with some basic styling.

EDIT: This issue should have the `documentation` and not the `bug` label, I'm sorry...

**Comment by bdbch** [comment]
Hey @mariohamann thanks! I forwarded this into our documentation ticket board so we'll double check this on our current iteration of the docs website and if it's missing we'll add it.
