### ISSUE TITLE
Emoji example

### ISSUE THREAD

**Issue by KonstantinVlasov** [ueberdosis/tiptap#1048]
Hi, tiptap team! Thanks for your work!
Is there any emoji picker example or docs? Maybe you have something that will already be useful? :)

**Comment by hanspagel** [comment]
I’m closing this in favor of #198. ✌️

**Comment by raihan-ramadhan** [comment]
Hey, I built a package for this: [@raihancodes/tiptap-extension-twemoji-react](https://www.npmjs.com/package/@raihancodes/tiptap-extension-twemoji-react). It adds Twemoji support in Tiptap with custom emoji + picker. Might help anyone looking for this.
