### ISSUE TITLE
Find and mark/decorate text (grammer checking) 

### ISSUE THREAD

**Issue by appinteractive** [ueberdosis/tiptap#1050]
Hi, I would like to build an editor with grammar checking. Therefore I would need to find words or sentences and mark or replace them with suggestions, underline decorations etc. like on https://languagetool.org/

I get a list of words (start and end postiontions plus the text) and the suggestions. 

Any idea how to tackle that kind of problem?

**Comment by philippkuehn** [comment]
There are some hints for tackling this issue. Closing here.
