### ISSUE TITLE
Can an example be provided for using Emitter.io as the Pubsub service for collaboration?

### ISSUE THREAD

**Issue by gmlewis** [ueberdosis/tiptap#1052]
**Which part of the documentation have you read?**
I've searched through the documentation and could not find any information about using Emitter.io as the Pubsub/MQTT service provider. Could an example please be provided for doing this?

**Did you find the content helpful?**
Yes, thank you.

**What was hard to understand, missing or misleading?**
n/a

**What else?**
n/a

**Comment by hanspagel** [comment]
I’ve looked into this, but it’s out of scope for us. ✌️
