### ISSUE TITLE
[RFC] Move chain/can under commands

### ISSUE THREAD

**Issue by philippkuehn** [ueberdosis/tiptap#1054]
I keep stumbling over the use of commands with and without `chain`/`can`:

```js
// unchained
editor.commands.setBold()

// chained
editor.chain().setBold().run()

// unchained can
editor.can().setBold()

// chained can
editor.can().chain().setBold().run()
```

I’m thinking about whether `chain`/`can` should only available under commands:

```js
// unchained
editor.commands.setBold()

// chained
editor.commands.chain().setBold().run()

// unchained can
editor.commands.can().setBold()

// chained can
editor.commands.can().chain().setBold().run()
```

What do you think? Or do you have other ideas?

**Comment by hanspagel** [comment]
I’m closing this here as it feels like a non-issue for people. @philippkuehn feel free to reopen it, if you think we should  change that.
