### ISSUE TITLE
Using Vue store inside a component for mentions?

### ISSUE THREAD

**Issue by cnicodeme** [ueberdosis/tiptap#1056]
**Which part of the documentation have you read?**
https://next.tiptap.dev/api/nodes/mention/

**Did you find the content helpful?**
Yes, the code sample is great to get started

**What was hard to understand, missing or misleading?**
But it would be nice to be able to import data from the store. Typically, for the "Mention" system, it's highly probable that the list of people to mentions are available via a store (typically vue JS though), but it appears that the $store is not available inside the `MentionList.vue`.

I tried to load the store from Vue, from the component or even the plugin directly, but without any luck. I'd love some directions here. (The filter would be done via the query parameter directly at the component level, rather than on the plugin level).

**Comment by bdbch** [comment]
I'll close this issue as it's quite stale and no discussion happened since Sep of 2021. @cnicodeme feel free to reopen if this still bothers you and you think we need to have a fix for that behaviour.
