### ISSUE TITLE
Handling Image drop with cursor?

### ISSUE THREAD

**Issue by cnicodeme** [ueberdosis/tiptap#1057]
**Is your feature request related to a problem? Please describe.**
Right now, you can import the "Image" extension on Tiptap2 that allows to add images, but it does not work with drag and dropping images into the editor at a specific place.

**Describe the solution you’d like**
Ideally, it would be possible to drag and drop an external image (from the computer) at a place chosen by the cursor on the editor.

**Describe alternatives you’ve considered**
I was doing this in previous Tiptap version by calling the `props.handleDOMEvents.drop` of a custom plugin (without the possibility ty select the place of drop though).

**Additional context**
I've tried to catch the `drop` event in the Image extension, but without much luck.

I'm willing to post here an extension of the Image tag if anyone can point me in the right direction for both handling the "drop" event, and how to handle the cursor positioning.

Thanks!

**Comment by jonathanmach** [comment]
Is it possible to handle the `handleDOMEvents: {drop} ` event on TipTap 2?

**Comment by HZ-labs** [comment]
@cnicodeme why you set - `if (event.dataTransfer?.files?.length !== 1) `?
I have a problem with that. I try insert image from `Copy Image` browser dialog menu.
<img width="391" alt="image" src="https://user-images.githubusercontent.com/1663933/133302631-52c637ed-f4c7-428c-86db-d8d7bb95bca0.png">

`event.dataTransfer.files.length -> 4` and one of they - `file`, How I can upload to server only `file` and disable default insert with blob: `blob:http://localhost:3000/ef4eb6ca-bd0a-464d-9704-dacc09a74a1f`?

@jonathanmach you can use 
```
handleDOMEvents: {
            drop(view, event) {...}
}
```

**Comment by philippkuehn** [comment]
Drop support for images has been removed in tiptap v2 because we don’t want to embed images as base64 stringy anymore. At some point we’ll maybe provide an extension with support for image upload but this will take some time. Closing for now.
