### ISSUE TITLE
.isActive() and nested nodes

### ISSUE THREAD

**Issue by samwillis** [ueberdosis/tiptap#1058]
Currently `.isActive` checks to see if the node is active at any point in a nested tree of nodes, this is slightly problematic with nested list of different types. So ,for example, I have a toolbar with both `ul` and `ol` buttons and use `isActive` to set the active state of the button, if you nest a ul within an ol both are technically active and so both buttons show as active.

Would it be possible to have a `depth` argument or 'isActiveTop()' so that we can check if only is the top level node matches?

Additionally `isActive('paragraph')` returns true with most other node types as they almost all nest a paragraph within them (list, tables, blockquotes ect.), could there be a `exclusive` argument or a `isActiveOnly()` option?

**Comment by philippkuehn** [comment]
Currently, I don’t have plans to add this to the core. But thanks again for the code. I’m sure it will help some people 👍
