### ISSUE TITLE
feat(extension-tables): Resizing columns sometimes changes the previous column

### ISSUE THREAD

**Issue by oodavid** [ueberdosis/tiptap#1060]
**What happens?**
If you drag a cell border, occasionally the previous border is resized.

**How can others reproduce the issue?**
https://next.tiptap.dev/examples/tables/

**Do you have a screenshot?**
![tiptap-tables-resize](https://user-images.githubusercontent.com/46879/106267414-8208f500-6221-11eb-8ab2-eeb4d300a1a6.gif)

**What’s your environment?**
 - MacOs
 - Chrome
 - Desktop

**What else?**
From first-glance it looks like it selects the previous border when hovering over the middle-pixel in the table border.

**Comment by philippkuehn** [comment]
Closing because this is an issue with prosemirror-tables itself.
