### ISSUE TITLE
Auto-linking typed urls (have working code)

### ISSUE THREAD

**Issue by samwillis** [ueberdosis/tiptap#1061]
I have managed to get auto linking typed urls working (something that seems to have been difficult with TipTap v1 and Prosemirror). Working code at the end after my explanation.

There are two issues that people have come up against when trying to get typed auto linking working:

1. Missing trailing character (final space):

   What people have found it that when you add a space '\s' to the end of the regex although it will match and apply the input rule after the space, the space itself does not appear. This is because the input rule is replacing the transaction from that final character input and missing it off. To fix this we need to manually add the final trailing character at the end of the trasaction. I have done this in `markInputRuleKeepTrailingChar` below.

   Although this works as a one off, It may be cleaner to add it as an option that can be turned on in the standard `markInputRule`. I'm also adding it at the end of the transaction after applying the mark, so it is outside the mark (which we want for links). There may be a situation where it should be inside the mark, in which case it should be applied earlier in the transaction - but this needs further thought and may need changes to the way regex match groups are used.

2. Not applying the input rule on enter/newline:

   This super helpful comment solved it: https://discuss.prosemirror.net/t/trigger-inputrule-on-enter/1118/5

   So rather than using the core tiptap inputRules plugin we use a custom one. Rather than copy pasting (as in the suggestion in the comment) I modify the standard prosemirror inputRules plugin and add it in `addProseMirrorPlugins` on the link mark node with enter/newline support.

   Again it could be good to add this support into the core tiptap inputRules plugin as there are other input rules that could benefit from being applied on a new line, for example a code input rule: `'''` followed by enter.

This all supports the standard behaviour of undoing the mark if you hit backspace immediately after typing a link:

https://user-images.githubusercontent.com/31130/106264895-2d17af80-621e-11eb-9736-6862074d966f.mov

I'm still working on a couple of additional features that I'm after:
1. Editing the link href by editing the display text (when a links display text matches that of the href, as in after auto linking)
2. Option to hide the protocol from the displayed link

## Working implementation:

``` typescript

import { markInputRule } from '@tiptap/core';
import { Link } from '@tiptap/extension-link/src/link';
import { InputRule, inputRules } from 'prosemirror-inputrules'
import { MarkType } from 'prosemirror-model'

// These are almost the same as pasteRegex and pasteRegexWithBrackets but with
// additional [\s\n] at the end so they apply after adding white space or a new line
export const linkInputRegex = /(https?:\/\/(?:www\.)?[-a-zA-Z0-9@:%._+~#=]{1,256}\.[a-zA-Z]{2,}\b(?:[-a-zA-Z0-9@:%._+~#=?!&/]*)(?:[-a-zA-Z0-9@:%._+~#=?!&/]*))[\s\n]$/gi
export const linkInputRegexWithBrackets = /(?:\()https?:\/\/(?:www\.)?[-a-zA-Z0-9@:%._+~#=]{1,256}\.[a-zA-Z]{2,}\b(?:[-a-zA-Z0-9@:%._+~#=?!&/()]*)(?:\))[\s\n]$/gi

function markInputRuleKeepTrailingChar(regexp: RegExp, markType: MarkType, getAttributes?: Function): InputRule {
  // version of markInputRule that adds the missing trailing char 
  const standardMarkInputRule = markInputRule(regexp, markType, getAttributes);
  return new InputRule(regexp, (state, match, start, end) => {
    const tr = (standardMarkInputRule as any).handler(state, match, start, end)
    if (tr) {
      // If the mark has been applied add the trailing char at the end of the edit
      tr.insertText(match[0].slice(-1), end)
    }
    return tr
  })
}

export const CustomLink = Link.extend({
  addProseMirrorPlugins() {
    const rules = [
      markInputRuleKeepTrailingChar(linkInputRegex, this.type),
      markInputRuleKeepTrailingChar(linkInputRegexWithBrackets, this.type),
    ];
    const plugin: any = inputRules({rules})
    const run = plugin.props.handleTextInput;
    // Add 'enter'/newline support to input rule - Based on:
    // https://discuss.prosemirror.net/t/trigger-inputrule-on-enter/1118/5
    plugin.props.handleKeyDown = (view: any, event: any) => {
      if (event.key !== "Enter") return false;
      const { $cursor } = view.state.selection
      if ($cursor) return run(view, $cursor.pos, $cursor.pos, "\n")
      return false;
    }
    return [plugin]
  }
})

```

---

This alternative version has working on enter/newline and also doesn't have missing trailing space/newline. However it breaks the undo on backspace. Here it lets the original transaction through and so we get the trailing space/newline for free but that additional transaction breaks the undo behaviour. So the previous version it what is needed.

``` typescript
export const CustomLink = Link.extend({
  addProseMirrorPlugins() {
    const rules = [
      markInputRule(linkInputRegex, this.type),
      markInputRule(linkInputRegexWithBrackets, this.type),
    ];
    const plugin: any = inputRules({rules})
    const run = plugin.props.handleTextInput;
    plugin.props.handleTextInput = (view: any, from: any, to: any, text: any) => {
      run(view, from, to, text);
      return false  // Always return false to keep space
    },
    // Based on:
    // https://discuss.prosemirror.net/t/trigger-inputrule-on-enter/1118/5
    plugin.props.handleKeyDown = (view: any, event: any) => {
      if (event.key !== "Enter") return false;
      const { $cursor } = view.state.selection
      if ($cursor) run(view, $cursor.pos, $cursor.pos, "\n")
      return false;  // Always return false to keep new line
    }
    return [plugin]
  }
})
```

**Comment by philippkuehn** [comment]
Closing in favor of #1209
