### ISSUE TITLE
Examples in native JS / HTML

### ISSUE THREAD

**Issue by lofcz** [ueberdosis/tiptap#1062]
TipTap 2 is presented with strong emphasis on being framework agnostic. For me and possibly many other users this is the selling point (no dependency on Vue). Currently, most of examples are using Vue and there is no native JS counterpart available. While it is possible for us to use the library and do the same things in native JS / HTML this makes using docs for us _unnecessary_ hard. 

Proposed solution is to include native JS / HTML counterpart for each example in the documentation. 

 Risks are minimal but this would require nontrivial amount of time to do. It is therefore for consideration, whether investing time here is reasonable or not (and probably for other members of the community to voice their opinion on).

**Comment by fbaube** [comment]
Even having the [Default text editor](https://www.tiptap.dev/examples/default) in plain JS would be a great help.
