### ISSUE TITLE
Nested content islands using Vue component slots and Prosemirror Sub-views

### ISSUE THREAD

**Issue by enjibby** [ueberdosis/tiptap#1063]
**Is your feature request related to a problem? Please describe.**
Should I transition [uberdosis/tiptap#868](https://github.com/ueberdosis/tiptap/issues/868) across to this project?

**Describe the solution you’d like**
I've managed to get this v2 alpha running in my dev environment so I would like to fork or branch then look at how to implement the node-slot functionality in this new project.

**Describe alternatives you’ve considered**
Alternatively, I could keep working on v1.

**Additional context**
as per issue and PR in v1.

**Comment by philippkuehn** [comment]
Closing in favor of #868
