### ISSUE TITLE
Editor almost unusable after replacing everything with a horizontal line

### ISSUE THREAD

**Issue by mariohamann** [ueberdosis/tiptap#1081]
**What happens?**

I selected the editor's content and replaced it with a horizontal rule. The "text-cursor" disappeared, I couldn't write anything and therefore the editor wasn't usable anymore. (CMD-Z helped – and the cursors of other users in collaboration mode...)

**How can others reproduce the issue?**
1. Go to next.tiptap.dev
2. Replace the whole content with a horizontal rule

![CleanShot 2021-04-05 at 09 59 37](https://user-images.githubusercontent.com/26542182/113552026-d780ca00-95f5-11eb-8387-c4dc9e8cea93.gif)

**Comment by sh-winter** [comment]
By looking at the source code, I found that the type of node inserted after the horizontal line is determined by `tr.selection.$from.parent.type.contentMatch.defaultType`, which leads to the return of non paragraph type in some cases

**Comment by sh-winter** [comment]
for example:
![GIF](https://user-images.githubusercontent.com/48613217/123221360-7506de00-d501-11eb-8e49-7fad4d7816f0.gif)
