### ISSUE TITLE
Can I use like motion call characters to display floating menu?

### ISSUE THREAD

**Issue by ruibaby** [ueberdosis/tiptap#1082]
**Is your feature request related to a problem? Please describe.**

When I use floating menu, I often need to use the mouse to select the menu, which is very inconvenient. I hope to use a special character (such as /) to display the floating menu, and use the up and down keys to select the menu.

**Describe the solution you’d like**

Like Ghost Editor:

![2021-04-09 00 56 41](https://user-images.githubusercontent.com/21301288/114066665-8eb76280-98ce-11eb-8e90-4592cf30da6f.gif)

**Describe alternatives you’ve considered**

I found that extension-mention is very similar to this function, but the main function of this extension seems to be for input

**Additional context**

This is very useful for writing things quickly, almost no need to use the mouse, unless you modify the previous content.

**Comment by kobe651jp** [comment]
I have the same need, but the link on https://next.tiptap.dev/experiments/commands is broken.

where is this page?

**Comment by ruibaby** [comment]
@kobe651jp https://tiptap.dev/experiments/commands
