### ISSUE TITLE
Vue3 starting instructions need one more step when using yarn

### ISSUE THREAD

**Issue by gmlewis** [ueberdosis/tiptap#1097]
**Which part of the documentation have you read?**
I’ve been to the following page of the documentation:
https://next.tiptap.dev/installation/vue3

**Did you find the content helpful?**
The whole page is excellent and easy to read.  Thank you!

**What was hard to understand, missing or misleading?**
But when following the instructions with an existing project (using the Composition API) and then typing `yarn serve`,
it says:

```
$ yarn serve
yarn run v1.22.5
$ vue-cli-service serve --mode development
 INFO  Starting development server...
(node:30288) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
98% after emitting CopyPlugin

 ERROR  Failed to compile with 20 errors                                                                       11:19:16 AM

These dependencies were not found:

* @tiptap/core in ./node_modules/@tiptap/extension-blockquote/dist/tiptap-extension-blockquote.esm.js, ./node_modules/@tiptap/extension-bold/dist/tiptap-extension-bold.esm.js and 17 others
* prosemirror-commands in ./node_modules/@tiptap/extension-hard-break/dist/tiptap-extension-hard-break.esm.js

To install them, you can run: npm install --save @tiptap/core prosemirror-commands
```

**What else?**
I ran: `yarn add @tiptap/core prosemirror-commands` to see if it works, and that seemed to do the trick, so maybe the instructions can be updated to include this.  Now I'm running into other issues, but I'll submit this one.

**Comment by Demivan** [comment]
`@tiptap/core` dependency was fixed but not `prosemirror-commands`. This part of report: 
`* prosemirror-commands in ./node_modules/@tiptap/extension-hard-break/dist/tiptap-extension-hard-break.esm.js`

Probably `starter-kit` should depend on `prosemirror-commands` to fulfill `hard-break` peer-dependency.
But this still does not fix use case when user imports `@tiptap/extension-hard-break` directly. User will need to install `prosemirror-commands` themselves.

Another solution would be to expose everything from `prosemirror-commands` in `@tiptap/core` and have `@tiptap/extension-hard-break` depend only on `@tiptap/core`
