### ISSUE TITLE
Input Rules not recognized for code blocks

### ISSUE THREAD

**Issue by itsnwa** [ueberdosis/tiptap#1107]
I'm trying to type ``` to create a code block, but it doesn't get recognized, while creating code blocks with the keyboard shortcut works as expected.

Using Vue 3 with Composition API.

<img width="397" alt="CleanShot 2021-03-11 at 11 03 24@2x" src="https://user-images.githubusercontent.com/19958806/110770272-6ef23780-8259-11eb-8d6a-2de82937429a.png">

**Comment by fengzilong** [comment]
@itsnwa I just send a PR that will solve your problem( support `enter`, heading to the PR link above )
