### ISSUE TITLE
tip tap does not render

### ISSUE THREAD

**Issue by ski** [ueberdosis/tiptap#1110]
**What happens?**
I have the most basic of markup to render tip tap but I get a three warnings and the component refuses to render.  

**How can others reproduce the issue?**
1. Create a new Quasar v2.0.0-beta.9 project using defaults 
2. Install TipTap Next
3. Use the composition API example mentioned here https://next.tiptap.dev/installation/vue3 to create a demo app. 
4. Start Quasar dev
5. You will see a blank main page. But if you look in the developer console you will see the following warnings:
`
[Vue warn]: onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.
warn @ webpack-internal:///./node_modules/@tiptap/vue-3/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:160
2webpack-internal:///./node_modules/@tiptap/vue-3/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:160 [Vue warn]: onBeforeUnmount is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.
warn @ webpack-internal:///./node_modules/@tiptap/vue-3/node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:160
webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:159 [Vue warn]: Missing ref owner context. ref cannot be used on hoisted vnodes. A vnode with ref must be created inside the render function. 
  at <EditorContent editor=undefined > 
  at <Tiptap> 
  at <App onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <QPageContainer> 
  at <QLayout view="lHh Lpr lFf" > 
  at <MainLayout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>
`

**What behavior did you expect?**
I expect to see a simple TipTap editor displayed in the main content area

**What’s your environment?**
 - Windows 10
 - Chrome
 - Desktop

**Comment by datduyng** [comment]
In my case, I had `document` properties in StarterKit extension as false but didn't append my custom Document component in my Editor extensions object which caused the issue. Removing `document: false,` or adding the Document extension works for me

```
StarterKit
  .configure({
    document: false,
  })

```

**Comment by sarahsga** [comment]
As @philippkuehn pointed out, you need to add the defaultExtensions to the editor. 
In my case, I did not want all the default extensions. So the bare minimum you need to make it work are `document`, `text`, and `paragraph`. So you can turn all others off except the aforementioned three.

```
[defaultExtensions.configure({
      blockquote: false,
      bold: false,
      bulletList: false,
      code: false,
      codeBlock: false,
      // document: false,
      dropcursor: false,
      gapcursor: false,
      hardBreak: false,
      heading: false,
      history: false,
      horizontalRule: false,
      italic: false,
      listItem: false,
      orderedList: false,
      // paragraph: false,
      strike: false,
      // text: false,
})]
```
