### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by cnicodeme** [ueberdosis/tiptap#1146]
**Is your feature request related to a problem? Please describe.**
Oddly, I've searched on the whole "tiptap-next" repository about how to display a placeholder, but the word "placeholder" is not present in neither the code, the issues or the commit. (Not anymore, #meta).

**Describe the solution you’d like**
Having a way to show a custom, greyed message when the editor is empty.

I'm posting this here in case I'm not the first to try this, but if I find anything, I'll update this ticket.

**Comment by kikky7** [comment]
How to override default options now? In v1 I just passed overrides as object in Placeholder extension, but now I can't with an error Object is not a function - because the extension exports const...

This doesn't work in v2
```
extensions: [
  ...defaultExtensions({
    heading: {
      levels: [3, 4],
    },
  }),
  Placeholder({
    placeholder: this.placeholder, // prop
  }),
],
```

This worked in v1
```
extensions: [
  new Placeholder({
    emptyClass: "is-empty",
    emptyNodeText: this.placeholder, // prop
    showOnlyWhenEditable: true,
  }),
]
```

**Comment by philippkuehn** [comment]
use `Placeholder.configure({ ... })`

**Comment by iamraphson** [comment]
@philippkuehn Do anyone know how to fix the below error?

```
export 'isNodeEmpty' (imported as 'isNodeEmpty') was not found in '@tiptap/core' (possible exports: Editor, Extension, Mark, Node, callOrReturn, extensions, findParentNodeClosestToPos, generateHTML, getHTMLFromFragment, getMarkAttributes, getSchema, isActive, isMarkActive, isNodeActive, isNodeSelection, isTextSelection, markInputRule, markPasteRule, mergeAttributes, nodeInputRule)
```

`isNodeEmpty` seems not to be in the `@tiptap/core`.

**Comment by philippkuehn** [comment]
@iamraphson update you dependencies. seems like you have an older version of `@tiptap/core` installed.

**Comment by vedmant** [comment]
> use Placeholder.configure({ ... })

This is something that should be in documentation, I also had to search issues to find how to actually pass placeholder text.
