### ISSUE TITLE
Need help on Marks

### ISSUE THREAD

**Issue by KevinNTH** [ueberdosis/tiptap#1151]
**Which part of the documentation have you read?**
https://next.tiptap.dev/api/marks

**Did you find the content helpful?**
List of supported mark

**What was hard to understand, missing or misleading?**
The documentation of marks is missing

**What else?**

I'd like to create `textCls` from `textStyle` mark but I fail. Here's my implementation.

```js
import { Mark, mergeAttributes } from '@tiptap/core'

export const TextCls = Mark.create({
  name: 'textCls',

  defaultOptions: {
    HTMLAttributes: {},
  },

  parseHTML() {
    return [
      {
        tag: 'span',
        getAttrs: (element) => {
          return element.getAttribute('class') ? {} : false
        },
      },
    ]
  },

  renderHTML({ HTMLAttributes }) {
    return [
      'span',
      mergeAttributes(this.options.HTMLAttributes, HTMLAttributes),
      0,
    ]
  },
})
```

The class attributes are still thrown away using this `mark` loaded in the `extensions` of the `editor`. I guess there is something to do with the `mergeAttributes` in the `renderHTML` function. But when I take a look to the `textStyle` mark, I don't see anything relevant.

Also, I'd like to create an extension with command `addCls` from `FontFamily` extension but I struggle to understand how this is working.

So far, I only succeed to create a placeholder extension. I find it's very difficult to build a custom editor since the documentation is hard to understand to me.

Thanks in advance for the support 🙏

**Comment by scallywag** [comment]
The following is working, based on the [Highlight extension](https://github.com/ueberdosis/tiptap/blob/main/packages/extension-highlight/src/highlight.ts):

```js
import { Mark } from '@tiptap/core';

// Inspired by https://github.com/ueberdosis/tiptap/blob/main/packages/extension-highlight/src/highlight.ts
const SpanClass = Mark.create({
  name: 'SpanClass',

  addOptions() {
    return {
      validClasses: [
        // List the classes allowed on span elements here.
        'foo',
      ],
    };
  },

  addAttributes() {
    return {
      class: {
        default: null,
        parseHTML: (element) => this.options.validClasses.includes(element.getAttribute('class'))
          && element.getAttribute('class'),
        renderHTML: (attributes) => {
          if (!attributes.class || !this.options.validClasses.includes(attributes.class)) {
            return {};
          }
          return {
            class: attributes.class,
          };
        },
      },
    };
  },

  parseHTML() {
    return [
      {
        tag: 'span',
      },
    ];
  },

  renderHTML({ HTMLAttributes }) {
    return ['span', HTMLAttributes, 0];
  },

  addCommands() {
    return {
      setSpanClass: (attributes) => ({ commands }) => commands.setMark(this.name, attributes),
      toggleSpanClass: (attributes) => ({ commands }) => commands.toggleMark(this.name, attributes),
      unsetSpanClass: () => ({ commands }) => commands.unsetMark(this.name),
    };
  },
});
```

Then use `editor.chain().focus().setSpanClass({ class: 'foo' }).run()` to set the style on selected text.

**Comment by ngekoding** [comment]
> The following is working, based on the [Highlight extension](https://github.com/ueberdosis/tiptap/blob/main/packages/extension-highlight/src/highlight.ts):
> 
> ```js
> import { Mark } from '@tiptap/core';
> 
> // Inspired by https://github.com/ueberdosis/tiptap/blob/main/packages/extension-highlight/src/highlight.ts
> const SpanClass = Mark.create({
>   name: 'SpanClass',
> 
>   addOptions() {
>     return {
>       validClasses: [
>         // List the classes allowed on span elements here.
>         'foo',
>       ],
>     };
>   },
> 
>   addAttributes() {
>     return {
>       class: {
>         default: null,
>         parseHTML: (element) => this.options.validClasses.includes(element.getAttribute('class'))
>           && element.getAttribute('class'),
>         renderHTML: (attributes) => {
>           if (!attributes.class || !this.options.validClasses.includes(attributes.class)) {
>             return {};
>           }
>           return {
>             class: attributes.class,
>           };
>         },
>       },
>     };
>   },
> 
>   parseHTML() {
>     return [
>       {
>         tag: 'span',
>       },
>     ];
>   },
> 
>   renderHTML({ HTMLAttributes }) {
>     return ['span', HTMLAttributes, 0];
>   },
> 
>   addCommands() {
>     return {
>       setSpanClass: (attributes) => ({ commands }) => commands.setMark(this.name, attributes),
>       toggleSpanClass: (attributes) => ({ commands }) => commands.toggleMark(this.name, attributes),
>       unsetSpanClass: () => ({ commands }) => commands.unsetMark(this.name),
>     };
>   },
> });
> ```
> 
> Then use `editor.chain().focus().setSpanClass({ class: 'foo' }).run()` to set the style on selected text.

Hi, thanks for the awesome extension.

How can we make it support for multiple classes?

**Comment by charlesroelli** [comment]
@ngekoding yes, just add to the list in the code, located after the line `// List the classes allowed on span elements here.`.

**Comment by ngekoding** [comment]
> @ngekoding yes, just add to the list in the code, located after the line `// List the classes allowed on span elements here.`.

Sorry for the late reply.

Can we make the class name dynamic, so without defining the allowed classes?

**Comment by ngekoding** [comment]
@charlesroelli Thank you
