### ISSUE TITLE
Support a literal Tab

### ISSUE THREAD

**Issue by samwillis** [ueberdosis/tiptap#1153]
TipTap currently does not support a literal tab charicter when you press tab (particularly annoying in a code block), the browser will move focus to the next input on the page. This should probably be the default behaviour, see:

https://discuss.prosemirror.net/t/tab-stops/225
https://discuss.prosemirror.net/t/parsedom-for-tab/723

However maybe include a standard extension (such as below) to add support, note that due to https://github.com/ueberdosis/tiptap-next/issues/115 this would need to be after the list extensions as you would want the standard tab indent behaviour for them.

``` typescript
import { Extension } from '@tiptap/core';

export const LiteralTab = Extension.create({
  name: 'literalTab',

  addKeyboardShortcuts() {
    return {
      Tab: () => {
        console.log('test');
        return this.editor.commands.insertText('\t')
      }
    }
  }

})
```

**Comment by ocavue** [comment]
@hanspagel Hi. Have you started developing the CodeMirror extension yet? If you haven't yet, I can try to submit a PR to implement it.

**Comment by hanspagel** [comment]
Nope, haven’t looked into it.

Here is an example with ProseMirror + CodeMirror 5:
https://prosemirror.net/examples/codemirror/

But we’d definitely go with the new CodeMirror:
https://codemirror.net/6/

It’s pretty complex to get all the things right, but feel free to give it a try!

**Comment by philippkuehn** [comment]
This should be a good start with CodeMirror 6: https://gist.github.com/BrianHung/06000918ea955e52a595fa42c601c593

**Comment by amursky** [comment]
Here is my solution that allows to insert tabs while editing the text in code block:

```typescript
import BaseCodeBlock from "@tiptap/extension-code-block";

export const CodeBlock = BaseCodeBlock.extend({
  addKeyboardShortcuts() {
    return {
      Tab: () => {
        if (this.editor.isActive("codeBlock")) {
          return this.editor.commands.insertContent("\t");
        }
      },
    };
  },
});
```

**Comment by rchasman** [comment]
https://github.com/ueberdosis/tiptap/issues/457#issuecomment-2285456957

**Comment by LucasBardoux** [comment]
```ts
import { Extension } from "@tiptap/core";

export default Extension.create({
  name: "tabInCodeBlock",
  addKeyboardShortcuts() {
    return {
      Tab: () => {
        const { state, dispatch } = this.editor.view;
        const { selection } = state;
        const { $from, to } = selection;
        const node = $from.node($from.depth);

        if (node.type.name === "codeBlock") {
          // Insert a tab character at the current cursor position
          dispatch(state.tr.insertText("\t", to, to));
          return true; // Prevent default tab behavior
        }
        return false; // Allow default tab behavior for other nodes
      },
    };
  },
});
```
