### ISSUE TITLE
New line added on text deletion

### ISSUE THREAD

**Issue by nucleartux** [ueberdosis/tiptap#1197]
Chrome Version 89.0.4389.128 (Official Build) (x86_64)

**Steps to reproduce the bug**
1. Go to https://www.tiptap.dev/guide/node-views/react/#adding-a-content-editable
2. Delete all text from "React component" box
3. Type any letter and then delete it (with backspace)
4. Extra new line created

**Expected behavior**
No new line created

**Screenshot, video, or GIF**

https://user-images.githubusercontent.com/199706/115677129-dd4a0f80-a358-11eb-9b72-378f8037a211.mov

**Comment by hanspagel** [comment]
Thanks for reporting! 🙌
