### ISSUE TITLE
Cursor disappears when task item content is empty

### ISSUE THREAD

**Issue by egoist** [ueberdosis/tiptap#1198]
**Description**

**Steps to reproduce the bug**
1. Go to https://www.tiptap.dev/examples/tasks/
2. Press enter to create a new task
3. No cursor, but if you start typing, cursor shows agains

**Expected behavior**
Show cursor for empty task too.

**Screenshot, video, or GIF**

https://user-images.githubusercontent.com/8784712/115696763-8dd60480-a395-11eb-8dd0-2c17e22c3bcb.mp4

**Environment?**
 - operating system:
 - browser:
 - mobile/desktop:
 - tiptap version: ^2.0.0-beta.22

**Additional context**

**Comment by philippkuehn** [comment]
Yeah, this happens in Chrome and Safari (desktop only). Firefox is working fine.

**Comment by philippkuehn** [comment]
This is a CSS rendering issue in webkit/blink when using `display: flex` on the list item. I can fix it with adding a hair space within a pseudo element but this is kind of weird 😅

```css
li::before {
  content: '\200A';
}
```

**Comment by philippkuehn** [comment]
oh, this seems to be fixed with [this commit](https://github.com/ueberdosis/tiptap/commit/6e205d3dbeb3a9711e37a63830451a9f724e3b13).
