### ISSUE TITLE
Image example does not work on mobile Safari

### ISSUE THREAD

**Issue by mathislucka** [ueberdosis/tiptap#1203]
Hi there,

while browsing your (beautiful) new documentation, I realized that the upload image from URL example does not work on iOS/Safari 14.4.2. Nothing happens when I‘m clicking the button even after disabling Pop-up blocker.

**Comment by philippkuehn** [comment]
Hmm, it’s working fine for me. (I’m using AdGuard Pro as content blocker)

https://user-images.githubusercontent.com/2500670/115826429-32def480-a40b-11eb-9294-fc755c25ff04.MP4

**Comment by mathislucka** [comment]
Hm, it‘s working for me too now. Closing this, maybe a glitch on my side.
