### ISSUE TITLE
Single image tag ignored inside paragraph tags

### ISSUE THREAD

**Issue by deathg0d** [ueberdosis/tiptap#1206]
**Description**
We are moving to tiptap from another editor. However, we stumbled upon an issue. We have existing html that looks like this:
```
<p>
    <img src="url"/>
</p>
```
Whenever, image is inside a `p` tag, it is simply ignored. Tiptap only takes image tags when there is no `p` tag around it:
```
<img src="url"/>
```

**Steps to reproduce the bug**
Provide the following html as initial data for the editor. The image tag is ignored.
```
<p>
    <img src="url"/>
</p>
```

**Comment by hanspagel** [comment]
Thanks for reporting! This is how the Paragraph extension is configured: to only allow inline content, and images are configured as block content.

https://github.com/ueberdosis/tiptap/blob/main/packages/extension-paragraph/src/paragraph.ts#L29

Try setting the `Image` node to inline:

```js
new Editor({
  extensions: [
    Image.configure({ inline: true }),
  ],
})
```

I’m not sure if this is the behaviour you’d like to keep then, that depends on your use case, but it should help with the import.

**Comment by philippkuehn** [comment]
There is a limitation of ProseMirror which can’t mix block and inline nodes.[ More about this here.](https://discuss.prosemirror.net/t/how-to-deal-with-with-nodes-being-dropped-during-parsing/1962)

The default doc shows only block nodes. A paragraph shows only inline nodes. With the image node you have to decide it should be rendered between blocks (default) or within blocks (with `inline: true`).

The former is probably more the intended result. If you are working existing markup it may makes sense to migrate your HTML before using tiptap (remove `<p>` around images).

**Comment by deathg0d** [comment]
Thanks for the replies. Inline seems the right option for me - because 1. it works well with my previous format and 2. without `p` tags around image, I cannot seem to add hyperlink to the images.

**Comment by duhaime** [comment]
@philippkuehn @hanspagel is it possible to change schemas after initialization? e.g. set the schema to parse images as inline when initializing the editor, then switch images to block to prevent users from typing text inline with the images once the editor is initialized?

**Comment by hanspagel** [comment]
No, the schema must not change after initialization.

**Comment by duhaime** [comment]
Ah blast, thanks for the follow up

**Comment by johanobergman** [comment]
In case anyone is interested, I made a small conversion utility that takes an HTML-string and tries to convert elements that would otherwise be ignored into a format that TipTap allows. This way, images inside paragraphs are preserved even when using block mode.

Currently handles images in paragraphs, links with images inside, links outside paragraphs and YouTube videos.

https://gist.github.com/johanobergman/ce9178b8669fc05fefd4aedaa93403d8

**Comment by manuelkoch98** [comment]
I have quite the same problem. I would like to be able to simply copy a Google document with everything in it (images, text) and then paste it. I have tried this with Image.configure( inline: true), but then I have problems with old Helpcenter articles that I can no longer insert a paragraph and get this error.

`Called contentMatchAt on a node with invalid content`

Can somebody help me? :)

**Comment by yusukeyamane** [comment]
@manuelkoch98 
The only way I can solve that problem was  setting the Image node to block.....

**Comment by paraslamsong** [comment]
@yusukeyamane 
how to do that?
