### ISSUE TITLE
Autolink

### ISSUE THREAD

**Issue by maccman** [ueberdosis/tiptap#1209]
It would be great to have some kind of autolinking support for the link component. In other words typing `google.com` automatically turns it into a url.

You can see how Remirror does that here:
https://github.com/remirror/remirror/blob/beta/packages/remirror__extension-link/src/link-extension.ts#L356

Regexwise, I suggest using this package which has hard-coded TLDs.
https://www.npmjs.com/package/url-regex-safe

**Comment by philippkuehn** [comment]
Yes, this is already on our list and I think it will land in stable 2.0 ✌️

**Comment by philippkuehn** [comment]
Hey, it’s coming. Last week I merged [a massive PR](https://github.com/ueberdosis/tiptap/pull/1997) for inputrules and pasterules. This also included the integration of [linkify](https://github.com/Hypercontext/linkifyjs) (on paste). After some research, this seems to be the most stable library for the best URL detection.

This is the basis for writing a method to set attributes live as you type. The same technique will also be necessary for a hashtag extension. So sorry it’s probably going to take a little longer. But it will come!

**Comment by rfgamaral** [comment]
@philippkuehn Just wondering, what's missing for this to be possible with Tiptap?

**Comment by philippkuehn** [comment]
Nothing is missing. I just need to find time and build it 😅 On a feature basis, it's definitely a [high priority](https://github.com/ueberdosis/tiptap/issues/2087).

**Comment by philippkuehn** [comment]
There is an open PR for it now: https://github.com/ueberdosis/tiptap/pull/2226
Happy to get any feedback!

**Comment by lfantone** [comment]
Nice to have the auto-link feature!
I noticed that the automatically created links are not possible to be removed with the `unsetLink` command.
Looks like when the editor is updated without the link, this feature runs again and keeps adding them.

**Comment by philippkuehn** [comment]
@lfantone oh, you are right. [this patch](https://github.com/ueberdosis/tiptap/commit/ea10ffbc6a0f447c33680dcc6f6dc2fa6337c4c2) should help.

**Comment by peihk2** [comment]
Hi @philippkuehn, I noticed your comment regarding the hashtag extension. I'm currently in need of this feature for my project, but I couldn't find it in the Tiptap documentation. Could you please point me in the right direction, or provide an example of how I can customize a hashtag extension for my project? Thank you!
