### ISSUE TITLE
nuxt-2 with composition api

### ISSUE THREAD

**Issue by productfrontenddeveloper** [ueberdosis/tiptap#1212]
**Steps to reproduce the bug**
1. first screen

**CodeSandbox**
https://codesandbox.io/s/zealous-tu-2jsuh?file=/pages/index.vue

**Screenshot, video, or GIF**
<img width="1430" alt="Screen Shot 2021-04-24 at 09 48 14" src="https://user-images.githubusercontent.com/38668796/115950147-32655d00-a4e2-11eb-9b69-0c6f9f0cb1f4.png">

**Comment by philippkuehn** [comment]
Make sure to use the latest versions of all tiptap packages. But this error has nothing to with tiptap itself which can be seen in your error stack trace.

**Comment by productfrontenddeveloper** [comment]
This error comes when I just use tiptap.
