### ISSUE TITLE
Support access to editor selection

### ISSUE THREAD

**Issue by mtlynch** [ueberdosis/tiptap#1218]
**The problem I am facing**

v1 offered access to the editor selection via `editor.selection`. It doesn't seem like equivalent functionality is available in v2.

**The solution I would like**

The ability to detect whether text is selected (to know whether to activate the Link button) and to deselect text, placing the cursor at selection end.

**Alternatives I have considered**

Trying to access prosemirror APIs directly.

**Additional context**

None.

**Comment by AveryBibeau** [comment]
The current selection should be accessible via `editor.state.selection`

**Comment by philippkuehn** [comment]
yes, use `editor.state.selection` instead.
