### ISSUE TITLE
$attrs is readonly.

### ISSUE THREAD

**Issue by mohsinmdl** [ueberdosis/tiptap#1219]
Not able to view editor after importing the basic template from the documentation. [https://www.tiptap.dev/installation/vue2](documentaion).

in the console the following errors come up:

```
[Vue warn]: $attrs is readonly.

found in

---> <EditorContent>
       <TiptapTest> at app/javascript/components/notes/tiptap_test.vue
         <Notes> at app/javascript/components/notes.vue
           <Root>
           
vue.esm.js:648 [Vue warn]: $listeners is readonly.
```

```
found in

---> <EditorContent>
       <TiptapTest> at app/javascript/components/notes/tiptap_test.vue
         <Notes> at app/javascript/components/notes.vue
           <Root>
           
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "editor"
```
```
found in

---> <EditorContent>
       <TiptapTest> at app/javascript/components/notes/tiptap_test.vue
         <Notes> at app/javascript/components/notes.vue
           <Root>
```

**Comment by zcuric** [comment]
👍🏻 Same here.

**Comment by zcuric** [comment]
I have the same issue. My use case scenario is that I have multiple editors on the same page as blocks and also side effect is that the page gets extremely slow, which was not the case in `v1`.

**Comment by philippkuehn** [comment]
@zcuric can you provide a demo for that performance issue anywhere?

**Comment by philippkuehn** [comment]
@mohsinmdl these are only warnings but you are not able to *view* the editor? can you provide a codesandbox for your issue?

**Comment by zcuric** [comment]
@philippkuehn I'm not 100% sure it's related to `tiptap` itself or in the relation of the app that I'm working in. I'll investigate more and report back. But the thing is the more warnings I get mentioned in the issue, the more app get slower until the point it freezes.

**Comment by philippkuehn** [comment]
@zcuric Do you use certain features very intensively? Like node views or something?

**Comment by zcuric** [comment]
@zcuric I've built basically complete editor in v1, and started update with basic extensions and just started using code and history. Simple lorem ipsum paragraphs with images and marks like links.

**Comment by zcuric** [comment]
@philippkuehn Recently I had a similar slowdown effect when using `Vue.extend`. I've noticed that EditorContent is now built that way. Is there any particular reason to why? TS? Or?

**Comment by philippkuehn** [comment]
Hmm, `Vue.extend` is only used for TypeScript support.

**Comment by mohsinmdl** [comment]
hey @philippkuehn thank you for your response, here is the [codesandbox link ](https://codesandbox.io/s/vuejs-cdn-forked-jj129?file=/src/index.js) of the above mentioned issue.

please try to edit the default content... you will see the the app getting slower as you keep editing and eventually it stops.

Here are something also wanna share with you.

- I am using vue via CDN in my project.
- In my case the issue appeared when I was upgrading to tiptap v2.

**Comment by philippkuehn** [comment]
@mohsinmdl Hmm I can confirm the issue but I'm not sure what is going on here. Maybe it has something to do with the CDN version of Vue, or parcel or something else. The tiptap issue template runs smooth (https://codesandbox.io/s/tiptap-issue-template-b83rr?file=/src/main.js:17-21)

**Comment by zcuric** [comment]
@philippkuehn I have the same warnings as @mohsinmdl and I'm using webpack build. My guess is that Vue.extend is the problem. Vue.component could be used as well here I think. I'll try to contribute.

**Comment by philippkuehn** [comment]
There must be a difference between your setup and our official issue template. our docs are also running fine (gridsome + webpack). strange.

**Comment by zcuric** [comment]
@philippkuehn Looks like the same problem here: https://stackoverflow.com/a/54361699/1287762

**Comment by zcuric** [comment]
@philippkuehn I'll fork, try to fix it. If I do, PR will be up.

**Comment by hanspagel** [comment]
Additional context
https://stackoverflow.com/questions/53206078/vue-warn-listeners-and-attrs-is-readonly/59265173#59265173
