### ISSUE TITLE
Drag and drop does not work when using Vue2 for node view

### ISSUE THREAD

**Issue by kavadas** [ueberdosis/tiptap#1234]
**Description**
Drag and drop does not work when using Vue2 for node view. Haven't tried with other options, so I am not sure if this is related with Vue integration only.

**Steps to reproduce the bug**
1. Create a custom node using Vue 2 for it's node view.
2. Try to drag the node in the editor.
3. You will notice that the node is not draggable no matter what options you use (draggable: true for example).

I have not created a sandbox since you can see the issue in the documentation site:

* Working - Using vanilla JS : https://www.tiptap.dev/guide/node-views/js
* Not working - Using Vue2: https://www.tiptap.dev/guide/node-views/vue

Just try to drag the node view on the above pages and you will see the issue.

Regards

**Comment by philippkuehn** [comment]
We provide drag handle support for our node view implementations (vue, react). This isn’t well documented right now.
demo: https://www.tiptap.dev/guide/node-views/examples/#drag-handles

Add `data-drag-handle` to any element within you node view to make it draggable.

**Comment by kavadas** [comment]
@philippkuehn Apologies for missing that. Thank you for clarifying. I confirm that this works as expected. Added a handle with the data-drag-handle attribute in my custom node and it is now draggable. 

Regards
