### ISSUE TITLE
Let setContent ignore editable flag.

### ISSUE THREAD

**Issue by sugoidesune** [ueberdosis/tiptap#1239]
**The problem I am facing**
I want to display content through tiptap ,with editing disabled.
I use `setContent`, because the content arrives async.

**The solution I would like**
I think it would be safe to let `setContent` ignore the `editable` flag, since editability usually is for users of the editor, not the programmers.

**Alternatives I have considered**
Additional method/ parameter to overrride

**Additional context**
currently i have this hack going:

```js
       this.editor.setEditable(true)
      this.editor.commands.setContent(this.value, false)
      this.editor.setEditable(false)
```

**Comment by philippkuehn** [comment]
> I use setContent, because the content arrives async.

Create the editor when the content arrives is not an option?

**Comment by sugoidesune** [comment]
Yes of course, there's many ways to go around it. I chose the way that makes it behave the way I expected it would.

Interestingly it's happening in a loop.
It shouldn't loop before array is loaded. And when it's loaded it is there with content.
```html
<template v-for="content in loadedContent" >
      <TipTapRender v-bind="content" />
    </template>
```

This also means, that waiting for content would make it a little bit slower. This way, the editor is rendered, the content appears shortly after.

I am also using the editor as a non-editable preview. Which also has to make use of this hack, since the preview get's updated everytime the user types.

**Comment by jinyang1994** [comment]
I agree with @sugoidesune.
Not only in the preview case, at collaborative editing, Only viewing feature is also required.
We need disable editable and sync content allow users to view it

**Comment by philippkuehn** [comment]
> I agree with @sugoidesune.
> 
> Not only in the preview case, at collaborative editing, Only viewing feature is also required.
> 
> We need disable editable and sync content allow users to view it

https://www.tiptap.dev/api/editor/#editable

**Comment by jinyang1994** [comment]
> > I agree with @sugoidesune.
> > Not only in the preview case, at collaborative editing, Only viewing feature is also required.
> > We need disable editable and sync content allow users to view it
> 
> https://www.tiptap.dev/api/editor/#editable

You can try it, the content can't sync when editable set false and use collaborative editing extension

**Comment by philippkuehn** [comment]
ooops 😬

**Comment by jinyang1994** [comment]
@philippkuehn You're going to fix this it, right?

**Comment by philippkuehn** [comment]
@jinyang1994 Yeah I have to look at it. Not sure about a solution yet.
