### ISSUE TITLE
Text field border going out of bounds when pressing carriage return

### ISSUE THREAD

**Issue by jonleopard** [ueberdosis/tiptap#1242]
**Description**
Content box is going out of bounds when I press carriage return, but works properly when I use the `setHardBreak` button. I’m styling everything with [twin.macro](https://github.com/ben-rogerson/twin.macro), and have used the node-views set-up from the [docs](https://www.tiptap.dev/guide/node-views/react/). I've posted a screenshot and a codesandbox below.

**CodeSandbox**
https://codesandbox.io/s/tiptap-bug-g9bfw?file=/pages/index.js

**Screenshot, video, or GIF**

https://user-images.githubusercontent.com/2111234/116379426-475c2c00-a813-11eb-89e1-5138ffa15c60.mov

**Environment?**
 - browser: firefox/chrome
 - tiptap version: latest

**Comment by philippkuehn** [comment]
This works as expected. There is a custom node called `reactComponent` which allows *inline* content only. So if you press enter, you will leave this node and create a block node (paragraph) below your `reactComponent` node. I'm not sure why you are using this node at all.

**Comment by jonleopard** [comment]
>  I'm not sure why you are using this node at all.

Over at the discord channel I asked how to style tiptap with [twin.macro](https://github.com/ben-rogerson/twin.macro) and was told to use [node-views](https://www.tiptap.dev/guide/node-views/react/) to do so. I followed the tutorial over there and it includes `content: "inline*",` in the `Extension.js` file.

Should I be using `content:"paragraph"` instead?  I tried searching the docs and nothing shows up for what options I can use here.

Thanks for your help and sorry for the confusion.

**Comment by philippkuehn** [comment]
Depends of what your node view should contain. if you want to use multiple block nodes inside of your component you want probably  `content: "block+"`. `content:"paragraph"` means that your component can only contain one single paragraph.

**Comment by jonleopard** [comment]
Thanks! Closing now
