### ISSUE TITLE
Insert a mention on button click with tiptap v2

### ISSUE THREAD

**Issue by treefung** [ueberdosis/tiptap#1248]
Hey @ilicmarko, this is a good feature request. It's fixed in the latest version! 👍 I've also added such a button to the [example page](https://tiptap.scrumpy.io/suggestions).

![nov-22-2018 23-02-06](https://user-images.githubusercontent.com/2500670/48922989-e0502580-eeaa-11e8-9df5-a049a9673b9a.gif)

_Originally posted by @philippkuehn in https://github.com/ueberdosis/tiptap/issues/100#issuecomment-441126545_

**Comment by treefung** [comment]
Insert a mention on button click with tiptap v2 
it jusk like 
https://github.com/ueberdosis/tiptap/issues/100

but the tiptap 1.x demo is lost

**Comment by tcitworld** [comment]
The 1.x demo is here https://v1.tiptap.dev/suggestions

**Comment by philippkuehn** [comment]
You can use the [insertContent](https://www.tiptap.dev/api/commands/insert-content/#insertcontent) command for that. I don’t want to add a button for this in the example.

**Comment by tcitworld** [comment]
I did exactly that for reference:
```ts
this.editor
  .chain()
  .focus()
  .insertContent({
    type: "mention",
    attrs: {
      id: username,
    },
  })
  .insertContent(" ") // add an extra space after the mention
  .run();
```

**Comment by AlonMiz** [comment]
worth adding this example in the mentions docs
https://tiptap.dev/docs/editor/extensions/nodes/mention

**Comment by AlonMiz** [comment]
> I did exactly that for reference:
> 
> this.editor
>   .chain()
>   .focus()
>   .insertContent({
>     type: "mention",
>     attrs: {
>       id: username,
>     },
>   })
>   .insertContent(" ") // add an extra space after the mention
>   .run();

worth adding this example in the mentions docs
https://tiptap.dev/docs/editor/extensions/nodes/mention
