### ISSUE TITLE
Angular support

### ISSUE THREAD

**Issue by dkrusenstrahle** [ueberdosis/tiptap#1250]
**The problem I am facing**
There is native support for most major frameworks like Vue and React but not Angular. 

**The solution I would like**
I, and many with me, would love an Angular renderer like there is for Vue and React so that I can use my Angular modules in the editor. 

**Alternatives I have considered**
I works fine with vanilla JS but support for Angular would give a much better developer experience. 

**Additional context**
Love the library and I am proud to be a supporter!

**Comment by sibiraj-s** [comment]
I have just published `ngx-tiptap`. Checkout https://github.com/sibiraj-s/ngx-tiptap

**Comment by dkrusenstrahle** [comment]
Brilliant, well done! Have you found a way to insert dynamic Angular components into the editor too?

**Comment by sibiraj-s** [comment]
Yes It is possible with Prosemirror, See for example https://github.com/sibiraj-s/ngx-editor/tree/master/projects/ngx-editor/src/lib/components/image-view. But haven't explored that with tiptap. I can try adding something sooner, If possible. 

Let's continue the discussion related to `ngx-tiptap` [here](https://github.com/sibiraj-s/ngx-tiptap/discussions). Let's leave this issue for official discussion/talks, don't wan't to spam here 😅 .

**Comment by dkrusenstrahle** [comment]
Discussion continued in https://github.com/sibiraj-s/ngx-tiptap/issues/2#issue-873970080

**Comment by hanspagel** [comment]
Wow, this is awesome! Thanks for working on it @sibiraj-s! 🙌

We’ve never worked with Angular and don’t plan to add official Angular support to tiptap. With our limited knowledge we could never bring it to the same level, let alone maintain it. But we really hoped someone from the community will jump in and build Angular bindings. Looks like that happened pretty quickly! ✨

I’ll leave this open until I added a link to it somewhere in the official README and/or docs.

**Comment by sibiraj-s** [comment]
Thanks @hanspagel

**Comment by HuiiBuh** [comment]
The approach of sibiraj-s looks very nice.  
For People who don't want to create the UI themselves I created a customizable Editor with a default UI, which could be replaced if you want to at [huiibuh/ngx-tiptap-editor](https://github.com/huiibuh/ngx-tiptap-editor)
