### ISSUE TITLE
How to get it to work with a wrapper component while being reactive?

### ISSUE THREAD

**Issue by dark-red** [ueberdosis/tiptap#126]
I'm trying to create a reusable wrapper component with 'tiptap' passing props with: content etc.
However I can't get it to to work seamlessly while being reactive. Is there anyway to use clearContent() and setContent without losing the text focus position?

Setting focus causes it to start at index 0. Is there a way to set focus where the user was typing? 

```
export default {
  ...
  props: {
    content:  {
      type: String,
      default: '',
  },
  data() {
    localHtml: '',
    return {
      editor: new Editor({
        content: this.content,
        onUpdate: ({ getHTML }) => {
          this.contentHtml = getHTML();
          this.$emit('input', this.localHtml);
        },
      }),
    };
  },
  watch: {
    content: {
      immediate: true,
      handler(val) {
        if (this.content && this.editor) {
          this.editor.clearContent();
          this.editor.setContent(this.content);
          this.$nextTick(() => {
            this.editor.focus();
          });
        }
      },
    },
  },
  ...
}

**Comment by antimodern** [comment]
Omg, this package is so confusing. No DOcs. No help. I have the same issue and there's like at least 3 similiar issues that I found. This one is month old. I think I pass...

**Comment by antimodern** [comment]
https://github.com/scrumpy/tiptap/issues/150
https://github.com/scrumpy/tiptap/issues/155

I wonder, will we get help here?

**Comment by philippkuehn** [comment]
Hey @dark-red and @antimodern. Tracking the cursor is more complex than you might expect.

Just think of this content (cursor is after Hello):
`<p>Hello| world.</p>`

Then you call `editor.setContent('<p>Goodbye world.<p>')`. Where is your cursor now?

Here:
`<p>Goodb|ye world.</p>`

Or here
`<p>Goodbye| world.</p>`

**Comment by antimodern** [comment]
@philippkuehn thanks for response and I am sorry of being emotional. 

My usecase is different and much simpler that you are describing. I have `UpdateArticle.vue` component and I want to edit preloaded data. The only way I found to preload data is to use one-time watcher, which is kinda unintuitive

```js
mounted () {
    this.unwatch = this.$watch('value', this.setInitialContent)
  },
methods: {
    setInitialContent (content) {
      this.editor.setContent(content)
      this.html = this.editor.getHTML()
      this.unwatch()
    }
  }
```

Cursor is jumping for other reason that you describe. It's jumping to the start of the editor because it setsContent on every key input! Is there other native way to handle this without one-time watcher?

**Comment by exnihilo-creatio** [comment]
@philippkuehn The problem is that currently there exist no way to wrap tiptap into our own component and use it with a reactive property. Watching the reactive property will always call the `this.editor.setContent(content)` line, and therefore, the cursor will always jumps to the start of the editor. 

It is the same problem found in issue #133.

**Comment by haexhub** [comment]
Is there any method to get the current position of the cursor? If I want, for example, to insert anything after the current cursor position, I need to know, where to place it.

**Comment by crosskpixel** [comment]
Thanks, I had the same problem, I implemented a solution similar to the @exnihilo-creatio worked very well for me, I will explain how I did to help future friends, when I instantiated my editor and set the initial value whenever a dialog is opened In my application, it happened that the cursor was only at the beginning, and implementing the following routine worked for me. The cursor went to the end.

```
setConfigEditor({ content, editable, extensions }) {
      if(typeof this.editorProps == 'object') {
        this.editorProps.destroy();
      }
      const editor = new Editor({
        extensions: [
          ...extensions,
          new Heading({ levels: [1, 2, 3] }),
          new BulletList(),
          new ListItem(),
          new TodoItem(),
          new TodoList(),
          new Bold(),
          new Italic(),
        ],
        onUpdate:(args) => {
          this.product.details= args.getHTML();
        },
        content,
        editable
      });

      this.$nextTick(() => {
        editor.setContent(content);
      }, 3000);

      return editor;
    }
```

I had to put my editor content twice, when instantiated and after intended to reposition the cursor, clearly there is a better way to declare this construct, but so far we're fine.

tiptap 1.25.0
tiptap extensions 1.27.0
vue 2.6.10
