### ISSUE TITLE
TextAlign attributes are not resetting when switching node type

### ISSUE THREAD

**Issue by luislpv22** [ueberdosis/tiptap#1261]
**Description**
When you select some paragraph and apply a text alignment, then you switch the paragraph to a different node type, like f.e. a listItem (which is not allowed under text align extension) it'll keep the alignment attribute in the listItem node, so you'll have a right aligned list item.

**Steps to reproduce the bug**
1. Open the sandbox below
2. Select the center aligned paragraph
3. Click on 'list' or 'blockquote' button
4. See a center aligned list item or blockquote.

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:
https://codesandbox.io/s/determined-shape-0kypy

**Expected behavior**
It should reset the alignment attribute when you switch to a non-allowed node type.

**Screenshot, video, or GIF**
![image](https://user-images.githubusercontent.com/1518226/117051662-1732f280-ad17-11eb-82ea-fbfe81ab36fe.png)

**Additional context**
I used the example from the docs to reproduce the bug in my sandbox:
https://www.tiptap.dev/api/extensions/text-align

**Comment by philippkuehn** [comment]
`listItem` contains a `paragraph` which is [defined here](https://github.com/ueberdosis/tiptap/blob/ab3261e12bac18da29caaef5132ff8a8cb6ee7ba/packages/extension-list-item/src/list-item.ts#L14) so this is expected behavior.
