### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by asenju** [ueberdosis/tiptap#1263]
**Description**

**Steps to reproduce the bug**
1. Go to …
2. Type in …
3. Click on …
4. See error message

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:

* Vue: https://codesandbox.io/s/tiptap-issue-template-b83rr?file=/src/components/Tiptap.vue
* React: https://codesandbox.io/s/tiptap-react-08yxr

**Expected behavior**

**Screenshot, video, or GIF**

**Environment?**
 - operating system:
 - browser:
 - mobile/desktop:
 - tiptap version:

**Additional context**

**Comment by philippkuehn** [comment]
@asenju What is the issue here?
