### ISSUE TITLE
Incorrect cursor position after mentions in Safari 14.1

### ISSUE THREAD

**Issue by robbertbrak** [ueberdosis/tiptap#1264]
**Description**

In Safari 14.1, when there is no text after a mention, it is impossible to place the cursor after the mention to insert text.

**Steps to reproduce the bug**

To reproduce:
1. Open Safari 14.1 (16611.1.21.161.6)
2. Go to https://www.tiptap.dev/examples/suggestions/, which has an example editor with the text "What do you all think about the new Winona Ryder movie?"
3. Put the cursor at the end of the text and press backspace 6 times, until the word "movie?" has been deleted.
4. Press backspace one more time.

Result: the cursor jumps to the beginning of the text.
Expected: the cursor should now be directly after the mention.

5. Click after the end of the mention

Result: nothing happens. The cursor stays at the beginning of the text.
Expected: the cursor should now be directly after the mention.

6. Press the right arrow key

Result: nothing happens. The cursor stays at the beginning of the text.
Expected: the cursor should now be after the second character of the text (between the "W" and "h")

7. Press the left arrow key

Result: the cursor is now directly before the mention
Expected: since the cursor apparently was at the beginning of the text, it should stay there.

8. Press the right arrow key

Result: the cursor again jumps to the beginning of the text.
Expected: the cursor should jump to the end of the mention.

9. Press the spacebar

Result: a space is inserted after the mention, which seems to indicate that the cursor actually was after the mention all along, but incorrectly displayed.

**Expected behavior**
See above.

**Screenshot, video, or GIF**

https://user-images.githubusercontent.com/734581/117103975-a2de6a80-ad7b-11eb-9ae5-ab1e7243bef8.mov

**Environment?**
 - operating system: MacOS Big Sur, 11.3.1
 - browser: Safari 14.1 (16611.1.21.161.6)
 - mobile/desktop: mobile and desktop
 - tiptap version: latest

**Comment by pedropalhari** [comment]
I've been changing Draft.js to tiptap for a new production ready server and we're facing a lot of quirks with Mentions, specially on Mobile and obviously the f'up Android keyboard.

Give it a check on this CodeSandbox. It was this experiment that validated it for us:
https://codesandbox.io/s/eager-resonance-kjw98?file=/src/Mention.ts

Unfortunately, we lose a lot of performance because we're relying on `onUpdate` for now, but just being able to *use* it is enough for now.

**Comment by philippkuehn** [comment]
Hey, this seems to be related to ProseMirror itself and I’m not sure if we can see a fix for it because contenteditable on mobile devices is buggy. But I created an issue for it in the ProseMirror repo: https://github.com/ProseMirror/prosemirror/issues/1165

**Comment by robbertbrak** [comment]
@philippkuehn: thank you! I didn't realize it was also a problem in ProseMirror itself. 

Be aware that this is not just an issue on mobile: It also happens in Safari 14.1 on desktop.

(I see that I accidentally marked this issue as "mobile", but it should be "mobile and desktop" . I'll update the referenced ProseMirror issue accordingly.)

**Comment by philippkuehn** [comment]
@robbertbrak Thanks! I’ve updated the issue.

**Comment by kek7198** [comment]
Thanks for posting this; was wondering what was going on.

**Comment by philippkuehn** [comment]
Should be fixed in the latest release.
