### ISSUE TITLE
Backspace button does not work as expected in numbered list

### ISSUE THREAD

**Issue by zeljko-bulatovic** [ueberdosis/tiptap#1265]
**Description**
Strange behavior when deleting text using "backspace" button and cursor remains at wrong position.

**Steps to reproduce the bug**
Enter some text using numbered list that contains empty node in between. For example:

1. This line will be removed
  1.
    1. Put cursor just before "P" in this line
    2. You must have few items here, so keep this line as well
    3. Press few times backspace button, but make sure that cursor is positioned just before "P" on 1.1.1

After few presses (4 i think), "This line will be removed" is going to be cleared and your cursor would remain on line 1.1.1

**Expected behavior**
Nodes / Text should be removed when key is pressed

**Environment?**
 - operating system: OSX
 - browser: Chrome
 - tiptap versions: 
 - "@tiptap/core": "^2.0.0-beta.43",
 - "@tiptap/starter-kit": "^2.0.0-beta.39",
 - "@tiptap/vue-2": "^2.0.0-beta.22"

![Backspace](https://user-images.githubusercontent.com/17200131/117121471-ed201580-ad94-11eb-801e-bfb909a84b3e.gif)

**Comment by philippkuehn** [comment]
Same as described in #1266. This is intended behavior by ProseMirror. If you think this is an issue, please create an issue at ProseMirror.

https://user-images.githubusercontent.com/2500670/117126062-90bff480-ad9a-11eb-8925-fc803f071810.mp4
