### ISSUE TITLE
After updating to beta-44 of core there is an error when trying to add a new line in the editor.

### ISSUE THREAD

**Issue by dkrusenstrahle** [ueberdosis/tiptap#1274]
**Description**
After updating to beta-44 of core there is an error when trying to add a new line in the editor.

The error is:

core.js:6210 ERROR RangeError: Can not convert <> to a Fragment (looks like multiple versions of prosemirror-model were loaded)
    at Function.from (index.es.js:324)
    at NodeType.create (index.es.js:1966)
    at Transaction.push.CsC6.Transform.split (index.es.js:814)
    at tiptap-core.esm.js:1828
    at Object.splitBlock (tiptap-core.esm.js:345)
    at Array.<anonymous> (tiptap-core.esm.js:2315)
    at tiptap-core.esm.js:1201
    at Object.method [as first] (tiptap-core.esm.js:274)
    at Enter (tiptap-core.esm.js:2311)
    at tiptap-core.esm.js:810

**Steps to reproduce the bug**
1. Open editor
2. Put cursor in the editor and hit enter

**Expected behavior**
There should be a new line done when hitting enter not an error.

**Environment?**
 - operating system: MacOS
 - browser: Chrome
 - mobile/desktop: Dessktop
 - tiptap version: 2.00-beta44

**Additional context**
Happened after update to latest (from beta-38 to beta-44).

**Comment by philippkuehn** [comment]
This is an issue with your dependencies. Try to remove your `yarn.lock` and `node_modules` folder and do a fresh install as described here https://github.com/ueberdosis/tiptap/issues/577

**Comment by dkrusenstrahle** [comment]
I am using NPM, any solution for that?

**Comment by jamesgibson14** [comment]
Don't be so hasty closing issues please, I am having this issue as well, here is a reproduction: https://codepen.io/jamesgibson14/pen/dyvyWMm?editors=0011
Check the error in the console: `RangeError: Adding different instances of a keyed plugin (plugin$)`

**Comment by jamesgibson14** [comment]
I am using the SkyPack CDN, and it is loading in multiple versions of Prosemirror-state, it seems.

**Comment by jamesgibson14** [comment]
In the codepen hitting the "Enter" key does nothing.  I have also seen the `ERROR RangeError: Can not convert <> to a Fragment (looks like multiple versions of prosemirror-model were loaded)`

**Comment by philippkuehn** [comment]
@jamesgibson14 Yeah as you found out, this is a limitation of skypack right now :( https://github.com/skypackjs/skypack-cdn/issues/159#issuecomment-833358466

**Comment by housefrommars** [comment]
I have the same issue version 2 of tiptap. When hitting enter I get the following error:

```
Uncaught RangeError: Can not convert <> to a Fragment (looks like multiple versions of prosemirror-model were loaded)
```
Removing node_modules and reinstalling modules does not fix the issue.

**Comment by philippkuehn** [comment]
@housefrommars you have to rebuild your lock file too. sometimes yarn doesn’t update it correctly.

**Comment by jamesgibson14** [comment]
@philippkuehn yes after looking into it some more, I saw it was probably something with skypack. Thanks for leaving a comment on that issue.

**Comment by rosnaib11** [comment]
Same issue, my old version still work. I also tried fresh install didn't work

**Comment by sugoidesune** [comment]
had same issue after upgrading from beta 35. Here is what worked:

Delete any mention of TipTap & Prosemirror inside `package-lock.json` , delete `node_modules`, `npm install`

Now it works again.

**Comment by markusmo** [comment]
> had same issue after upgrading from beta 35. Here is what worked:
> 
> Delete any mention of TipTap & Prosemirror inside `package-lock.json` , delete `node_modules`, `npm install`
> 
> Now it works again.

I think this should be in some kind of FAQ. I had the same issue and it worked fine.
