### ISSUE TITLE
Example code in link should show how to get the URL when editing an existing link

### ISSUE THREAD

**Issue by unikitty37** [ueberdosis/tiptap#1277]
**Part of the documentation?**
I’ve read the following page of the documentation: https://www.tiptap.dev/api/marks/link/#usage

**Really helpful parts**
I think this part is really good: everything except the bit I've mentioned below.

**Hard to understand, missing or misleading**
But you really need to improve the example code so that, when the user tries to edit an existing link, the default value of the `window.prompt()` is the URL of that link rather than being blank.

**Additional context**
If a user is editing HTML that already has a link in it, they can't see where the link is going when `openOnClick` is `false` without using the inspector. Presumably their status bar will show it when `openOnClick` is `true` (but that is the default, and the example code doesn't seem to change it, and yet the links don't open on click or show the URL in the docs page…).

But even if they can get the existing URL that way, expecting them to do that in order to edit an existing URL is a bit much :) It would be much better for the dialog to be pre-populated with that URL — but it's not clear from the docs how to *get* that value. Looking at `editor.state` doesn't seem to show anything obvious, but even if it's documented somewhere else, the page for Link should probably point to that part of the docs, as that would seem to be the first place to look.

**Comment by philippkuehn** [comment]
BTW: you can use [`getMarkAttributes`](https://www.tiptap.dev/api/editor/#methods) to get the current link url.

```js
const url = editor.getMarkAttributes('link').href
```

**Comment by gerardojbaez** [comment]
Thanks to @philippkuehn, I was able to implement edit on existing links. This is how I'm handling link/unlink; the prompt always opens regardless. To remove a link, the user submits the prompt with a blank input. Not sure if this will be intuitive enough for all users, though. 

```javascript
toggleLink() {
    const existingHref = props.editor.isActive('link') ? props.editor.getAttributes('link').href : ''
    const href = window.prompt('URL', existingHref)

    if (href.trim()) {
        props.editor.chain().focus().setLink({href: href.trim()}).run()
    } else if (props.editor.isActive('link')) {
        props.editor.chain().focus().unsetLink().run()
    }
}
```

Also, `editor.getMarkAttributes()` is deprecated, use `editor.getAttributes()` instead.

**Comment by hanspagel** [comment]
I think you can remove the if/else. setLink with an empty href should remove the link too.

**Comment by pkariz** [comment]
I would like for link-edit to work also when your cursor is on a link but no character is selected (similar to how unset works). How can i achieve that?

**Comment by robertvanhoesel** [comment]
Use [extendMarkRange](https://www.tiptap.dev/api/commands/extend-mark-range/) to select the entire mark. I.e. `props.editor.chain().focus().extendMarkRange('link').setLink(..)`

**Comment by hanspagel** [comment]
Thanks @unikitty37! I improved the exampled according to your suggestion. ✌️
