### ISSUE TITLE
Ability to summarize content for displaying teasers or any subset of the document

### ISSUE THREAD

**Issue by treystout** [ueberdosis/tiptap#1279]
**The problem I am facing**
I want to show teaser text on display cards that is a subset of TipTap edited content

**The solution I would like**
a method on TipTap such as `generateSummary(charLength int, allowedTags=['strong', 'em', 'h4', etc...]) -> html string` that is smart enough to strip nodes and give a non-breaking text summary of the TipTap document

**Alternatives I have considered**
wrapping generateHTML and doing horrible DOM voodoo

**Comment by jelleroorda** [comment]
Hi, just a suggestion, you could use the text content of the document to generate a short summary. [See the docs on counting words and emoji's/letters (at the bottom of the page)](https://www.tiptap.dev/api/extensions/character-count/#count-words-emojis-letters-)

Example implementation (truncate function [from here](https://www.codegrepper.com/code-examples/javascript/javascript+limit+words)):

```js
const truncate = function(string, max, suffix) {
    if (string.length < max) {
        return string;
    }

    const lastSpaceIndex = string.substr(0, max - suffix.length).lastIndexOf(' ');

    return `${string.substr(0, lastSpaceIndex)}${suffix}`
};

const summary = truncate(this.editor.state.doc.textContent, 90, '...')
```

**Comment by treystout** [comment]
Posting my solution for posterity.... I opted to use a generated column of type text on my tables that were already storing full tiptap documents in a jsonb field called `body` or `description` in my tables. The function def is followed by a simple script to go add generated columns using the function. Interested parties may uncomment the `RAISE NOTICE` in the function to watch it recurse through your doc, you could also pretty easily add extended node handling, I just needed plain text.

```sql
-- brain-dead simple recursive function to walk the tiptap json looking for `text` nodes
CREATE OR REPLACE FUNCTION tiptap_json_to_text(_doc jsonb, _level int = 0)
  RETURNS text
  LANGUAGE plpgsql IMMUTABLE
  AS $$
DECLARE
  _text text := ''; -- return val
  e jsonb; -- loop val
BEGIN
  FOR e IN
    SELECT * FROM jsonb_array_elements($1->'content')
  LOOP
    --RAISE NOTICE '+++ LEVEL % at tag:%', _level, e->>'type';
    IF LENGTH(e->>'text') > 0 THEN
      _text := _text || (e->>'text') || '\n\n';
    END IF;

    IF e ? 'content' AND jsonb_array_length(e->'content') > 0 THEN
      _text := _text || tiptap_json_to_text(e, _level + 1); -- miles to go before we sleep
    END IF;

  END LOOP;

  RETURN _text;
END;
$$;

-- run through existing tiptap tables that store jsonb in their `body` columns
-- add a new col to each table listed called `body_text` that stores a flat
-- text representation of the json in `body`
DO
$$
DECLARE
  t text;
  tables_with_tiptap_bodies text[] := '{'
    'forums.categories, '
    'forums.forums, '
    'forums.topics, '
    'forums.posts, '
    'challenges.challenges, '
    'challenges.prompts, '
    'challenges.submissions '
  '}';
BEGIN
  FOREACH t IN ARRAY tables_with_tiptap_bodies
  LOOP
    RAISE NOTICE 'adding body_text to %', t;
    EXECUTE FORMAT('ALTER TABLE %s '
      'ADD COLUMN body_text text '
      'GENERATED ALWAYS AS (tiptap_json_to_text(body)) STORED', t);
  END LOOP;

  -- now do older tables that have names other than `body` for their tiptap cols
  ALTER TABLE public.events ADD COLUMN description_text text GENERATED ALWAYS AS (tiptap_json_to_text(description)) STORED;
  ALTER TABLE public.event_templates ADD COLUMN description_text text GENERATED ALWAYS AS (tiptap_json_to_text(description)) STORED;
END;
$$;
```

**Comment by Bessonov** [comment]
Very similar request: https://github.com/ueberdosis/tiptap/issues/1428

@treystout great, thanks for db example!

**Comment by philippkuehn** [comment]
This seems to be out of scope for tiptap itself. You can try to generate something based on the HTML or JSON.
