### ISSUE TITLE
Getting wrong textContent and characterCounts when i press enter

### ISSUE THREAD

**Issue by csainath07** [ueberdosis/tiptap#1281]
**Description**
I'm trying to calculate characters and word count but whenever I press Enter my last word and new word are `concatenate` which causes the wrong word counts and every time I press Enter my `characterCount` incremented by 2 which should be 1 (I think so)

**Steps to reproduce the bug**
1. write `n number` of words and press `Enter`
2. start writing again 

**CodeSandbox**
I created a CodeSandbox to help you debug the issue: [Code Sand Box](https://codesandbox.io/s/frosty-pond-186xf?file=/src/App.js:1486-1503)

**Expected behavior**
when I press `Enter` it should consider as space (the last word should not `concatenate` with the new word)

**Screenshot, video, or GIF**
<img width="591" alt="image" src="https://user-images.githubusercontent.com/25398452/117333484-99a5e880-aeb6-11eb-9e3c-30f93b5f1c2d.png">

**Environment?**
 - operating system: mac0s - big sur
 - browser: firefox
 - mobile/desktop: desktop
 - tiptap version: v2 beta

**Additional context**
I'm referring to this
[@tiptap Doc](https://www.tiptap.dev/api/extensions/character-count/#count-words-emojis-letters-)

**Comment by atulmy** [comment]
Same here:
<img width="393" alt="Screenshot 2021-05-18 at 4 13 41 PM" src="https://user-images.githubusercontent.com/685786/118638102-1d839d00-b7f4-11eb-80cf-2ca591726c33.png">

blocks should be appended in `textContent` beginning with a space.

**Comment by martinthenth** [comment]
I have the character count problem too, described in #1049

**Comment by philippkuehn** [comment]
There is [another way](https://prosemirror.net/docs/ref/#model.Node.textBetween) of getting text content

```js
const from = 0
const to = editor.state.doc.content.size
const text = editor.state.doc.textBetween(from, to, ' ')
```
