### ISSUE TITLE
Ability to control a plugin from outside (e.g. from an extension).

### ISSUE THREAD

**Issue by tobiasfuhlroth** [ueberdosis/tiptap#1282]
**The problem I am facing**
I'm implementing a `Mention`-like Extension using the `Suggestion`-Plugin and would like to access its internal state and/or trigger its methods. In my case i would like to use an `Escape`-`KeyboardShortCut` to close the `Suggestion` if it's active.

**The solution I would like**
A way to access the internal state and/or methods of the plugin.

**Alternatives I have considered**
Implementing the functionality inside the render function of the `Suggestion` – but i think that function should really only be handling the visual representation of the `Suggestion`.

**Additional context**
Internal state is accessible on `state.suggestion$`, but i don't think that it is meant to be accessed directly (https://github.com/ueberdosis/tiptap/blob/main/packages/suggestion/src/suggestion.ts#L130).

```javascript
addKeyboardShortcuts () {
  return {
    Escape: () => this.editor.commands.command(({ tr, state }) => {
      // How to access `active` on the internal state? 
      // How to 'close' the suggestion if active?
    }),
  }
},
```

**Comment by philippkuehn** [comment]
I’ve added a `pluginKey` option to the suggestion plugin (that you also can set in the mention extension). So you can now access the plugin state like [described above](https://github.com/ueberdosis/tiptap/issues/1282#issuecomment-837673380).

The easiest way to close the tippy tooltip is by using the `onKeyDown` handler.

```diff
onKeyDown(props) {
+  if (props.event.key === 'Escape') {
+    popup[0].hide()
+
+    return true
+  }

  return reactRenderer.ref?.onKeyDown(props)
}
```

I’ve added that code to all our tippy examples in our docs.
