### ISSUE TITLE
Setting HTMLAttributes to an empty object in Link.configure does not remove the defaults and generate a plain link

### ISSUE THREAD

**Issue by unikitty37** [ueberdosis/tiptap#1287]
**Description**
When configuring Link with an empty HTMLAttributes, the default attributes are added rather than no attributes.

**Steps to reproduce the bug**
Steps to reproduce the behaviour:
1. Create an Editor with `Link.configure({ HTMLAttributes: {} })` in the extensions
2. Attempt to create a link in the editor

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:

* Vue: https://codesandbox.io/s/tiptap-issue-template-forked-1jvj8?file=/src/components/Tiptap.vue (I hope this persists, as there doesn't seem to be a way to create a CodeSandbox account without giving access to either my GitHub or Google account, rather than just using an email and password. Would Codepen be a better choice here?)

**Expected behaviour**
Creating a link to https://example.com should generate the HTML `<a href="https://example.com">…</a>`, but instead it generates `<a target="_blank" rel="noopener noreferrer nofollow" href="https://example.com">…</a>`. The way to do this is undocumented.

**Environment?**
 - operating system: macOS 10.14.6 (18G9028)
 - browser: Vivaldi 3.8.2259.37
 - mobile/desktop: Desktop
 - tiptap version: core 2.0.0-beta.53, vue-2 2.0.0-beta.27, link 2.0.0-beta.15

**Additional context**
Using  `Link.configure({ HTMLAttributes: { target: undefined, rel: undefined } })` gives the expected result, but this is not documented. This seems to be rather verbose, especially if other attributes get added to the defaults in the future.

It makes sense that just passing `{ target: undefined }` shouldn't affect the `rel` attribute, but perhaps passing an empty object could be treated as meaning "just create a plain link"?

**Comment by philippkuehn** [comment]
At the moment, `configure` is doing a deep merge with the `defaultOptions` so `Link.configure({ HTMLAttributes: { target: undefined, rel: undefined } })` is the way to reset an attribute for now. But passing an empty object to overwrite could be a nice addition.

**Comment by philippkuehn** [comment]
Closing because the workaround seems to be okay for now.
