### ISSUE TITLE
setNodeMarkup function to update the node ATTRS, but this will cause the node views to be re-rendered

### ISSUE THREAD

**Issue by SGAMERyu** [ueberdosis/tiptap#1293]
**problem**
When I build Interactive node views with svelte, I update ATTRS with setNodeMarkup, which will cause the addNodeView function to be called again. 

![image](https://user-images.githubusercontent.com/17926105/117527337-ce708780-affd-11eb-9943-4cc5b0934635.png)

![image](https://user-images.githubusercontent.com/17926105/117527344-d6c8c280-affd-11eb-8655-8c17f67a2ad6.png)

**solution**
I want to be able to save the first instance created and just update ATTRS

**Comment by philippkuehn** [comment]
Since you are using a plain node view you should read the ProseMirror node view docs. There is an update method to control of your node view should be rerendered 

https://prosemirror.net/docs/guide/

https://prosemirror.net/docs/ref/#view.NodeView.update
