### ISSUE TITLE
Cannot switch focus from editor to an outside element in certain scenarios

### ISSUE THREAD

**Issue by zcuric** [ueberdosis/tiptap#1299]
**Description**
When adding link or image through custom form menu, cannot switch focus to the input field from editor. Focus is stuck on editor, which wasn't the case in tiptap@1

**Steps to reproduce the bug**
1. Create an form that will activate on button click with input field
2. Try to change focust with `this.$refs.input.focus`

**Expected behavior**
Focus should be switched to input

**Screenshot, video, or GIF**
![image](https://user-images.githubusercontent.com/1560102/117640080-7dfe4480-b139-11eb-9fbf-56ae12fe10d9.png)

**Environment?**
 - operating system: MacOS
 - browser: Chrome
 - mobile/desktop: Desktop
 - tiptap version: 2

**Comment by zcuric** [comment]
After checking this out of my working environment [in an isolated sandbox](https://codesandbox.io/s/tiptap-issue-template-forked-p5sny), this seems to be an issue with my environment.

**Comment by oliviermills** [comment]
I am having the same issue. What was the issue with your environment that caused it?

**Comment by oliviermills** [comment]
> I am having the same issue. @zcuric What was the issue with your environment that caused it?

In my case I was overusing the .focus() in my menu bar items.

**Comment by uveshnizam043** [comment]
[sdcdcdsc](https://github.com/ueberdosis/tiptap/issues/1299)
