### ISSUE TITLE
Interactivity with Svelte 

### ISSUE THREAD

**Issue by sondh0127** [ueberdosis/tiptap#1300]
**The problem I am facing**
There is no Svelte package for interactivity. (dynamic content) for https://www.tiptap.dev/examples/interactivity

**The solution I would like**
There is a way to import Svelte component from .svelte component

**Comment by sibiraj-s** [comment]
I was able to make it work. This is the following snippet I used. I just modified the existing ReactNodeViewRenderer
```ts
import { NodeView, NodeViewRenderer, Editor } from '@tiptap/core'
import type { Decoration, NodeView as ProseMirrorNodeView } from 'prosemirror-view'
import type { Node as ProseMirrorNode } from 'prosemirror-model'

interface SvelteNodeViewRendererOptions {
  stopEvent: ((event: Event) => boolean) | null,
  update: ((node: ProseMirrorNode, decorations: Decoration[]) => boolean) | null,
}

class SvelteNodeView extends NodeView<any, Editor> {
  renderer!: HTMLElement
  svelteComponent: any

  mount() {
    const props = {
      editor: this.editor,
      node: this.node,
      decorations: this.decorations,
      selected: false,
      extension: this.extension,
      getPos: () => this.getPos(),
      updateAttributes: (attributes = {}) => {
        this.updateAttrs(attributes)
      },
    }

    this.renderer = document.createElement('div')

    const Component = this.component
    this.svelteComponent = new Component({
      target: this.renderer,
      props
    })
  }

  get dom() {
    return this.renderer
  }

  updateAttrs(attributes = {}) {
    this.updateAttributes(attributes)
    this.svelteComponent.$set({ node: this.node })
  }

  update(node: ProseMirrorNode, decorations: Decoration[]) {
    if (typeof this.options.update === 'function') {
      return this.options.update(node, decorations)
    }

    if (node.type !== this.node.type) {
      return false
    }

    if (node === this.node && this.decorations === decorations) {
      return true
    }

    this.node = node
    this.decorations = decorations
    this.updateAttrs({ node, decorations })

    return true
  }

  selectNode() {
    this.svelteComponent.$set({ selected: true })
  }

  deselectNode() {
    this.svelteComponent.$set({ selected: false })
  }

  destroy() {
    this.svelteComponent.$destroy()
    this.renderer = null
  }
}

export function SvelteNodeViewRenderer(component: any, options?: Partial<SvelteNodeViewRendererOptions>): NodeViewRenderer {
  return (props) => {
    return new SvelteNodeView(component, props, options) as ProseMirrorNodeView
  }
}

```

**Comment by sondh0127** [comment]
> I was able to make it work. This is the following snippet I used. I just modified the existing ReactNodeViewRenderer
> 
> ```ts
> import { NodeView, NodeViewRenderer, Editor } from '@tiptap/core'
> import type { Decoration, NodeView as ProseMirrorNodeView } from 'prosemirror-view'
> import type { Node as ProseMirrorNode } from 'prosemirror-model'
> 
> interface SvelteNodeViewRendererOptions {
>   stopEvent: ((event: Event) => boolean) | null,
>   update: ((node: ProseMirrorNode, decorations: Decoration[]) => boolean) | null,
> }
> 
> class SvelteNodeView extends NodeView<any, Editor> {
>   renderer!: HTMLElement
>   svelteComponent: any
> 
>   mount() {
>     const props = {
>       editor: this.editor,
>       node: this.node,
>       decorations: this.decorations,
>       selected: false,
>       extension: this.extension,
>       getPos: () => this.getPos(),
>       updateAttributes: (attributes = {}) => {
>         this.updateAttrs(attributes)
>       },
>     }
> 
>     this.renderer = document.createElement('div')
> 
>     const Component = this.component
>     this.svelteComponent = new Component({
>       target: this.renderer,
>       props
>     })
>   }
> 
>   get dom() {
>     return this.renderer
>   }
> 
>   updateAttrs(attributes = {}) {
>     this.updateAttributes(attributes)
>     this.svelteComponent.$set({ node: this.node })
>   }
> 
>   update(node: ProseMirrorNode, decorations: Decoration[]) {
>     if (typeof this.options.update === 'function') {
>       return this.options.update(node, decorations)
>     }
> 
>     if (node.type !== this.node.type) {
>       return false
>     }
> 
>     if (node === this.node && this.decorations === decorations) {
>       return true
>     }
> 
>     this.node = node
>     this.decorations = decorations
>     this.updateAttrs({ node, decorations })
> 
>     return true
>   }
> 
>   selectNode() {
>     this.svelteComponent.$set({ selected: true })
>   }
> 
>   deselectNode() {
>     this.svelteComponent.$set({ selected: false })
>   }
> 
>   destroy() {
>     this.svelteComponent.$destroy()
>     this.renderer = null
>   }
> }
> 
> export function SvelteNodeViewRenderer(component: any, options?: Partial<SvelteNodeViewRendererOptions>): NodeViewRenderer {
>   return (props) => {
>     return new SvelteNodeView(component, props, options) as ProseMirrorNodeView
>   }
> }
> ```

**Comment by sondh0127** [comment]
Thank you @sibiraj-s, I also wondering that can we use svelte <slot/> to replace 
```
 <NodeViewWrapper className="react-component-with-content">
      <span className="label" contentEditable={false}>React Component</span>

      <NodeViewContent className="content" />
    </NodeViewWrapper>
```

**Comment by sibiraj-s** [comment]
Yes it is possible.

**Comment by giosifelis** [comment]
Nice Work @sibiraj-s.  quick question.  what are you using for NodeViewWrapper in svelte?

**Comment by sibiraj-s** [comment]
I am not actively using it. I just modified the react wrapper a little and posted an example.

**Comment by sibiraj-s** [comment]
@giosifelis . I am not a heavy svelte user. I tried my best to put together this. https://github.com/sibiraj-s/svelte-tiptap.

**Comment by sibiraj-s** [comment]
@hanspagel can we add this to the docs somewhere?

**Comment by andreavaccari** [comment]
> I tried my best to put together this. https://github.com/sibiraj-s/svelte-tiptap.

@sibiraj-s Your repo is great. Thank you for this!

**Comment by philippkuehn** [comment]
We don’t plan official svelte support for now. Closing it.

**Comment by einarpersson** [comment]
@philippkuehn This was 2021, now Svelte is much more popular. As I look on your page it seems to be that you have tutorials on Svelte indicating some official support.

Could you please consider official support for svelte node views?
![image](https://github.com/ueberdosis/tiptap/assets/6043691/c4c13c5a-2aa5-41e0-bfab-433c8db944bc)

(Also: I see that there is a unofficial contribution https://github.com/sibiraj-s/svelte-tiptap - but for my company it would feel much much better if this was a official support)

**Comment by alexgipi** [comment]
I think this is important! You already have documentation on how to install with Svelte, but it seems like you're not giving it the support I think it deserves. There are some examples with Svelte, but there's no clear way to use BubbleMenu, NodeView, etc. I think accepting @sibiraj-s contribution would be great!
