### ISSUE TITLE
Custom mark documentation 

### ISSUE THREAD

**Issue by sarahpai** [ueberdosis/tiptap#1304]
**Part of the documentation?**
I’ve read the following page of the documentation on how to create a custom mark here https://www.tiptap.dev/guide/custom-extensions/#create-a-mark 

**Hard to understand, missing or misleading**
https://www.tiptap.dev/guide/custom-extensions/#create-a-mark
There are no examples on how to create a new mark. It would be useful if there were some code examples.

**Comment by sarahpai** [comment]
I would like to create a mark when a text is selected and a button on the menu is pressed, it adds a class to the element. 
so for example: 

Normal text on editor : `<p>This is an example text thats selected</p>`
After pressing one of the custom buttons on menu. `<p class="drop-cap">This is an example text thats selected</p>`

**Comment by alancwoo** [comment]
Unfortunately finding myself in a bit of the same boat too, I tried looking at [this custom example on codepen](https://codesandbox.io/embed/vue-template-9x8fr) and also simply working off of [the bold extension](https://github.com/ueberdosis/tiptap/tree/main/packages/extension-bold) which seems to be the way to go, but I'm unsure how to correctly build/transpile this.

@hanspagel - it would be truly amazing if you could nudge me in the right direction as it's something fairly simple and I imagine very commonly needed! It's just about how the puzzle pieces fit together. (Really, thank you and all the other contributors for such a truly amazing piece of software)

**Comment by hanspagel** [comment]
@alancwoo What do you want to build? Maybe I can use it as an example to further explain it in the documentation.

**Comment by DannyFeliz** [comment]
@hanspagel @philippkuehn any idea about do to accomplish this?

**Comment by alancwoo** [comment]
@sarahpai @DannyFeliz have a look here - I think we finally have a nice solution: https://github.com/ueberdosis/tiptap/issues/819#issuecomment-861422382

**Comment by alancwoo** [comment]
@hanspagel actually this isn't necessarily solved unfortunately: https://github.com/ueberdosis/tiptap/issues/819#issuecomment-874057216

**Comment by ollyde** [comment]
How do we add the id? I'm doing popup comments which needs a div/span id.

```
const HighlightedText = Mark.create({
    name: "comment",
    toDOM: () => {
      return ["span", { class: "highlighted-text", id: generateSafeHtmlId() }, 0];
    },
    renderHTML({ HTMLAttributes }) {
      return ["span", mergeAttributes({ class: "highlighted-text" }, HTMLAttributes), 0];
    },
    parseHTML() {
      return [{ tag: "span.highlighted-text" }];
    },
  });
```
