### ISSUE TITLE
Backspacing the last character in a paragraph in a nodeview inserts indestructible BR or empties the entire node

### ISSUE THREAD

**Issue by thatsjonsense** [ueberdosis/tiptap#1311]
**Description**
I'm using a NodeView with block content via <NodeViewContent>. When I backspace in a paragraph with only one character, one of two things will happen:
(1) The entire parent node gets erased and replaced with a BR tag
(2) Just the paragraph node gets replaced by a BR tag, which can't be deleted or navigated past via the cursor

**Steps to reproduce the bug**
Please see https://gamma-editor-prototype-git-jon-nodeviewbug-gamma-app.vercel.app/nodeviewbug2. In the second line, or on any line you add, try backspacing the last character on a line.

Oddly enough, the exact same issue doesn't repro when I put the exact same code in a codesandbox: https://codesandbox.io/s/node-view-bug-simplified-b3m2k?file=/src/App.tsx

The rendered HTML is the same. I can't figure out what the difference could be. Some hypotheses:
- We're using NextJS, could it be adding something that changes behavior?
- Are we on a different ProseMirror version than what Codesandbox is getting? See below
- Some kind of other CSS or JS we're using is impacting the behavior. I've tried removing all of these and the issue still happens locally.

It sounds similar to https://github.com/ProseMirror/prosemirror-view/blob/c6ed7c2af3ff9f1eb9b1b2ef1e288eb92269b92a/src/domchange.js#L23 and https://github.com/ProseMirror/prosemirror/issues/930, but those appear to already be fixed and the issue doesn't seem to be browser specific. I've [cross-posted this issue to ProseMirror](https://github.com/ProseMirror/prosemirror/issues/1168), but I'm not sure if the problem is in Tiptap or Prosemirror. The issue only happens when using a NodeView. When I remove the nodeviews, it works perfectly.

**CodeSandbox**
I created a CodeSandbox to help you debug the issue: https://codesandbox.io/s/node-view-bug-simplified-b3m2k?file=/src/App.tsx
But see above - I actually can't get it to repro here!

**Screenshot, video, or GIF**
https://www.loom.com/share/3e8f5d83a006409195bf005306edc3ae

**Environment?**
 - operating system: OSX
 - browser: Chrome
 - mobile/desktop: Desktop
 - tiptap version:
 - $ yarn workspace editor-client list --pattern tiptap
├─ @tiptap/core@2.0.0-beta.32
├─ @tiptap/extension-blockquote@2.0.0-beta.3
├─ @tiptap/extension-bold@2.0.0-beta.3
├─ @tiptap/extension-bubble-menu@2.0.0-beta.7
├─ @tiptap/extension-bullet-list@2.0.0-beta.3
├─ @tiptap/extension-code-block@2.0.0-beta.5
├─ @tiptap/extension-code@2.0.0-beta.3
├─ @tiptap/extension-collaboration-cursor@2.0.0-beta.7
├─ @tiptap/extension-collaboration@2.0.0-beta.6
├─ @tiptap/extension-document@2.0.0-beta.3
├─ @tiptap/extension-dropcursor@2.0.0-beta.4
├─ @tiptap/extension-floating-menu@2.0.0-beta.4
├─ @tiptap/extension-gapcursor@2.0.0-beta.7
├─ @tiptap/extension-hard-break@2.0.0-beta.3
├─ @tiptap/extension-heading@2.0.0-beta.3
├─ @tiptap/extension-history@2.0.0-beta.3
├─ @tiptap/extension-horizontal-rule@2.0.0-beta.4
├─ @tiptap/extension-image@2.0.0-beta.1
├─ @tiptap/extension-italic@2.0.0-beta.3
├─ @tiptap/extension-link@2.0.0-beta.2
├─ @tiptap/extension-list-item@2.0.0-beta.3
├─ @tiptap/extension-mention@2.0.0-beta.33
├─ @tiptap/extension-ordered-list@2.0.0-beta.3
├─ @tiptap/extension-paragraph@2.0.0-beta.4
├─ @tiptap/extension-placeholder@2.0.0-beta.4
├─ @tiptap/extension-strike@2.0.0-beta.4
├─ @tiptap/extension-table-cell@2.0.0-beta.1
├─ @tiptap/extension-table-header@2.0.0-beta.3
├─ @tiptap/extension-table-row@2.0.0-beta.1
├─ @tiptap/extension-table@2.0.0-beta.5
├─ @tiptap/extension-task-item@2.0.0-beta.2
├─ @tiptap/extension-task-list@2.0.0-beta.3
├─ @tiptap/extension-text-align@2.0.0-beta.3
├─ @tiptap/extension-text@2.0.0-beta.3
├─ @tiptap/extension-typography@2.0.0-beta.1
├─ @tiptap/extension-underline@2.0.0-beta.1
├─ @tiptap/react@2.0.0-beta.21
├─ @tiptap/starter-kit@2.0.0-beta.28
└─ @tiptap/suggestion@2.0.0-beta.33

Thanks in advance for your help!

**Comment by philippkuehn** [comment]
Hey, you are using some old versions of all tiptap packages.

Please update all packages with: `yarn upgrade-interactive --latest` and try again.

**Comment by thatsjonsense** [comment]
This worked! Thank you @philippkuehn

**Comment by raulpopadineti** [comment]
I get the same issue with the `@tiptap/react` package. The placeholder doesn't get displayed due to the `<p><br/</p>` once the editor is emptied. 

```typescript
import * as React from "react";
import { useEditor, EditorContent } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";

type Props = {
  placeholder: string;
  initialValue: null | undefined | string;
  className: string;
  onChange: (newValue: string) => void;
};

export const TiptapEditor = ({
  placeholder,
  initialValue,
  className,
  onChange,
}: Props & Omit<React.HTMLAttributes<HTMLDivElement>, "onChange">) => {
  const editor = useEditor({
    extensions: [StarterKit],
    editorProps: {
      attributes: {
        class: className,
        placeholder: placeholder,
      },
    },
    parseOptions: {
      preserveWhitespace: "full",
    },
    autofocus: true,
    injectCSS: false,
    content: initialValue,
    onUpdate({ editor }) {
      onChange(editor.getHTML());
    },
  });

  return <EditorContent editor={editor} />;
};

```

I've installed tiptap a few minutes ago so I'm on the latest version. I've also tried to set the `preserveWhitespace` to `false`, but it did not help. Any ideas on how to fix it?

**Comment by philippkuehn** [comment]
@raulpopadineti can you create a sandbox reproducing the error please?

**Comment by raulpopadineti** [comment]
@philippkuehn here it is: https://codesandbox.io/s/awesome-water-jk9pq

**Comment by philippkuehn** [comment]
@raulpopadineti this is expected. the <br> is needed by ProseMirror to render an empty paragraph. otherwise a paragraph would have a height of 0px. but this <br> is not in your editor state. of you want to render a placeholder you should use the Placeholder extension: https://www.tiptap.dev/api/extensions/placeholder

**Comment by raulpopadineti** [comment]
Ah, makes sense. Thanks for the help! 😁

**Comment by raulpopadineti** [comment]
@philippkuehn is it possible to register a custom node, besides the paragraph node, to toggle the `is-empty` CSS class and add the placeholder? (e.g.: for a `figcaption`)

**Comment by raulpopadineti** [comment]
Ended up extending the `Placeholder` extension with some custom logic inside the decorations props to match my `Figure` node. All good 🙌🏻
