### ISSUE TITLE
error while using @tiptap/extension-link extansion.

### ISSUE THREAD

**Issue by Zicrael** [ueberdosis/tiptap#1312]
**Description**
Bump in error when install @tiptap/extension-link

**Steps to reproduce the bug**
1. Install package and use it in extansions
2. Call command this.editor.chain().focus().setLink({ href: this.url }).run();
3. See error message: "Uncaught TypeError: this.editor.getAttributes is not a function" inside link extansion on next line: 
4. const attrs = this.editor.getAttributes('link');

**Expected behavior**
Should insert link as usual.

**Environment?**
 - Ubuntu:
 - Chrome:
 - desktop:
 - tiptap v2:

**Comment by philippkuehn** [comment]
Please update your version of @tiptap/core. getAttributes is a new methods introduced in one of the latest versions.
