### ISSUE TITLE
Custom Attributes for Mentions

### ISSUE THREAD

**Issue by christopher4lis** [ueberdosis/tiptap#1316]
Right now, it seems you can only use the default attribute of "id" for mentions. Previously, you could insert both an id attribute as well as an attribute for a label.

**The solution I would like**
I'd like to have the ability to use a different piece of data for the mention's id attribute, so the id attribute and actual mention label display something different.

For instance:

Rather than 
   ` <span class="mention" data-mention="8" contenteditable="false">@8</span>`

I'd like to see
    `<span class="mention" data-mention-id="8" contenteditable="false">@John Doe</span>`

Checked the source code and it doesn't seem like this is possible at the moment, but let me know if I'm wrong, thanks.

**Comment by hanspagel** [comment]
Try to extend the Mention node and overwrite addAttributes and parseHTML with the code from the original extension, but replace data-mention with data-mention-id.

Does that work?

https://github.com/ueberdosis/tiptap/blob/main/packages/extension-mention/src/mention.ts#L46

https://www.tiptap.dev/guide/custom-extensions#attributes

**Comment by christopher4lis** [comment]
Came up with a workaround, but I think that should do it. At some point would be nice to have the attr: {} option similar to tiptap v1 mentions, but happy to have a solution rn. Thanks for all you do and your help.

**Comment by mmachatschek** [comment]
I just created a small codesandbox example how working with a UUID could look like:

https://codesandbox.io/s/bold-voice-l58oq

Adding an additional 'data-mention' attribute would be helpful if its provided from the server side to immediately display the name of a user and not having to wait for the client request to get the needed data to render the mention

**Comment by philippkuehn** [comment]
This initial issue should be fixed with #1322
