### ISSUE TITLE
Iframe mark throws "Content hole not allowed error"

### ISSUE THREAD

**Issue by gmendez-soldai** [ueberdosis/tiptap#1321]
**Description**
Hello, i need your help, when the editor contains iframe, a "Content hole not allowed in mark or leaf node spec" error is thrown when the editor.getHTML() method is called, in my case use this method in onUpdate.

```
editor: new Editor({
        extensions: [
          StarterKit,
          Underline,
          Iframe,
          Link,
          Image,
        ],
        disableInputRules: true,
        content: self.content,
        editable: self.editable,
        onUpdate: function() {
          console.log('content', this.getHTML());
        },
      }),
```

vue.esm.js?a026:628 [Vue warn]: Error in v-on handler: "RangeError: Content hole not allowed in a leaf node spec"

I'm not sure if is a bug or is configuration, i'm using the example  https://www.tiptap.dev/experiments/embeds

**Steps to reproduce the bug**
1. Go to https://www.tiptap.dev/experiments/embeds
2. Configure onUpdate in new Editor config with a console.log('content', this.getHTML()) for example,
3. Click on add iframe
4. See error message on console

**Comment by philippkuehn** [comment]
Oh, there are two issues in our demo. Should work with this fix: https://github.com/ueberdosis/tiptap/commit/8169eef27c15ccccf59b06970a58931ea137f990

**Comment by gmendez-soldai** [comment]
Thanks @philippkuehn, this worked!

**Comment by henryobiaraije** [comment]
> Thanks [@philippkuehn](https://github.com/philippkuehn), this worked!

This fixed it for me too. Removing 0 in renderHtml.
