### ISSUE TITLE
Algolia's search is not very useful

### ISSUE THREAD

**Issue by unikitty37** [ueberdosis/tiptap#1324]
I just tried to find documentation for the `onUpdate()` event. I would expect https://www.tiptap.dev/api/events to be the first result, but Algolia has decided that my search for `onupdate` should instead be a search for `outdate`.

![image](https://user-images.githubusercontent.com/139183/118392679-ace15280-b632-11eb-839c-8b84e55468c8.png)

Searching for vague matches to a term might be OK for a general purpose search of articles, but it's lousy for documentation. Could it be configured to return *exact* matches first? (including not changing hyphens to spaces — try searching for `editor-content` in the hope of getting documentation on the `<editor-content>` tag…)

**Comment by philippkuehn** [comment]
I configured algolia to search in code blocks now but this is probably a bad idea:

<img width="585" alt="VzJcusOyKJ" src="https://user-images.githubusercontent.com/2500670/121931856-72a7c580-cd44-11eb-8ae6-5a0d57a9150d.png">
