### ISSUE TITLE
Lists not being joined on toggleList

### ISSUE THREAD

**Issue by YousefED** [ueberdosis/tiptap#1329]
When you use toggleList, the new list is not joined with lists above / below.

Bug demonstration:
![list bug](https://user-images.githubusercontent.com/368857/118444240-2d648980-b6ed-11eb-82fe-c476b26c86c7.gif)

I'd expect it to behave similar to when I type the "- " shortcut to create a list:
![list ok](https://user-images.githubusercontent.com/368857/118444340-440ae080-b6ed-11eb-8d6e-940c4e2f7592.gif)

The WrappingInputRule takes this scenario into account (https://github.com/ProseMirror/prosemirror-inputrules/blob/master/src/rulebuilders.js), but toggleList does not.

I think this should happen automatically (join with lists above / below), or be an option for the toggleList command.

**Comment by philippkuehn** [comment]
Ah yeah that makes sense!

**Comment by YousefED** [comment]
Related; ProseMirror WrappingInputRule actually only joins with items above. I think it might also make sense to join with items below (when typing "-" above an existing list). Let me know if you'd like me to open a separate issue for this
