### ISSUE TITLE
BubbleMenu throws error in Svelte REPL

### ISSUE THREAD

**Issue by caschbre** [ueberdosis/tiptap#1333]
**Description**
I can get TipTap to function inside the Svelte REPL without issue, however once I follow the [BubbleMenu instructions](https://www.tiptap.dev/api/extensions/bubble-menu) I notice a "process is not defined" issue and the components fail to load. It looks like it is the import statement that is causing the issue.

`import BubbleMenu from '@tiptap/extension-bubble-menu'`

**Steps to reproduce the bug**
1. Go to https://svelte.dev/repl/be2a7886b58e4ccaa33b9c286255bf1f?version=3.38.2
2. Uncomment the BubbleMenu import statement.
3. See error message

**Svelte REPL**
https://svelte.dev/repl/be2a7886b58e4ccaa33b9c286255bf1f?version=3.38.2

**Expected behavior**
The BubbleMenu as demonstrated in the documentation.

**Additional context**
I have only attempted this in the Svelte REPL so I'm not exactly sure if this is a BubbleMenu issue or Svelte REPL issue. I was attempting to build the BubbleMenu example in the REPL to evaluate using TipTap on a project.

**Comment by philippkuehn** [comment]
Seems like tippy can’t be imported. `import tippy from 'tippy.js'` throws the same error.

I’m not sure if I can do something here. Seems like a bug/limitation in Svelte REPL.

**Comment by caschbre** [comment]
Thanks for looking into this! I use tippy in my project already so assuming this is just a REPL issue, I should be able to get the BubbleMenu working.

**Comment by brucou** [comment]
@philippkuehn maybe copy the whole bundled tippy.js into a svelte tab? That worked sometimes for me when I had these kind of issues with the REPL. Thinking out loud :-)

**Comment by philippkuehn** [comment]
Since this is a bug in svelte REPL we can’t do anything here.
