### ISSUE TITLE
 There is a problem when typing Chinese in the editor

### ISSUE THREAD

**Issue by Landy0524** [ueberdosis/tiptap#1335]
**Description**

When typing Chinese in the editor, the first letter will appear which is not  normal

E.g： If I want to enter the "测试(ceshi)", in the editor is : "c俄式(eshi)", the first letter is not the part of chinese

![image](https://user-images.githubusercontent.com/44955388/118596913-95df6380-b7de-11eb-9ec0-09af55d1ac6b.png)

vue: 2.6.11
tiptap: 1.29.6

**Comment by Landy0524** [comment]
https://user-images.githubusercontent.com/44955388/118597048-bf988a80-b7de-11eb-92a8-ab03b27fb30e.mov

**Comment by philippkuehn** [comment]
Can you reproduce this on https://prosemirror.net/ as well?

**Comment by Landy0524** [comment]
Can't reproduce

**Comment by philippkuehn** [comment]
Then you could try updating your dependencies.

**Comment by hangaoke1** [comment]
不要设置容器高度，`.ProseMirror`
