### ISSUE TITLE
textContent doesn't contain mention extension's text.

### ISSUE THREAD

**Issue by HoosLab** [ueberdosis/tiptap#1336]
**Description**
textContent doesn't contain mention extension's text.
When I selected whole text, copied and pasted, there are text contained mention's text.
(ex. What do you all think about the new @Winona Ryder movie?)
But I accessed from "editor.view.state.doc.textContent", there are text not contained mention's text.
(ex. What do you all think about the new movie?)

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:
* React: https://codesandbox.io/s/tiptap-mention-plugin-rc3br?file=/src/Editor.jsx

**Expected behavior**
textContent should contain node's text if node has text attribute.

**Environment?**
 - operating system: macOS Big Sur 11.2.3
 - browser: chrome 90.0.4430.93
 - mobile/desktop: desktop
 - tiptap version: 2.0.0

**Comment by shadow-light** [comment]
Related to this, if a line only contains a mention the editor thinks the line is blank and shows the floating menu (if you are using floating menus)

**Comment by sessionboy** [comment]
Hope to fix this issue soon @shadow-light

**Comment by philippkuehn** [comment]
It’s not possible to overwrite `textContent` because it’s a core method of ProseMirror and it’s how ProseMirror handles atom nodes. I think we will add a way to get a custom textContent for nodes. You can follow up here: #1428
