### ISSUE TITLE
Wrong or Missing Link for Collaboration Annotation

### ISSUE THREAD

**Issue by nadar** [ueberdosis/tiptap#1338]
**Part of the documentation?**

https://www.tiptap.dev/experiments/collaboration-annotation/

**Additional context**

The link to the source code (`https://github.com/ueberdosis/tiptap/blob/main/packages/extension-collaboration-annotation/` results in a 404) and the package `yarn add @tiptap/extension-collaboration-annotation` does not exists.

Yes i saw the state is `Experiment` but its listed in the docs, so i we thought we could at least try out the example code, because the feature its really what we are looking for :-)

Great work! :+1:

**Comment by hanspagel** [comment]
Oops! I have to just copy what’s on the overview of the experiments section though:

> Congratulations! You’ve found our playground with a list of experiments. Be aware that nothing here is ready to use. Feel free to play around, but please, don’t open an issue for a bug you’ve found here or send pull requests. :-)

BTW, we hope to get dedicated funding to finish the CollaborationAnnotation extension, that’s why it’s just half done. We’re publishing those things as experiment, so people see what’s the state and maybe take it from there on their own (or help to fund the development). 🙃

**Comment by nadar** [comment]
Yes, sure we would like to donate some money for that feature. Maybe a one time donation of 400€, sth like that? 

In the mean time i got the extension running on my system, but takes time to dig into y.js in order to understand the mapping system and so on.

**Comment by nadar** [comment]
I have made a forum thread regarding this, in the hope someone could help https://github.com/ueberdosis/tiptap/discussions/1445
