### ISSUE TITLE
can not delete mention

### ISSUE THREAD

**Issue by llorz-o** [ueberdosis/tiptap#1343]
**Description**
I cannot delete the mention in the mobile chrome browser.
When I delete the mention, the browser will first lose focus and then focus again, the phone’s soft keyboard will pop up, and the cursor will move to before the mention. Even if I select all the text and delete the text, the mention still exists

**Steps to reproduce the bug**
1. Go to Mentions demo, use mobile chrome
2. type a mention `@some`
3. delete mention you can see the bug

**Expected behavior**
remoce mentions

**Environment?**
 - operating system:android
 - browser:chrome
 - mobile/desktop:mobile
 - tiptap version:v2

**Comment by obj63mc** [comment]
I see that this bug was closed but I don't see any PRs or updates that have resolved this issue. It's still broken when testing the current demo site

**Comment by veesahni** [comment]
I can reproduce this one.  Given up to date Android 11 / Chrome:
* Open the [tiptap mentions example](https://tiptap.dev/examples/suggestions/)
* Move cursor directly after the @mention
* Hit backspace
* Instead to removing the mention, it adds characters:
![image](https://user-images.githubusercontent.com/705483/135936145-bc87f6c5-d637-453b-93a5-8799d59ef702.png)

**Comment by veesahni** [comment]
On further digging, this appears to be a bug in Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=612446

**Comment by philippkuehn** [comment]
Since this is a browser bug, we can’t do anything here :(

**Comment by veesahni** [comment]
@philippkuehn  workaround may be possible?

For example, in https://github.com/ProseMirror/prosemirror/issues/565 they talk of placing a hidden character after the mention and removing the mention when it is deleted.

**Comment by veesahni** [comment]
For anyone encountering stumbling upon this one:

https://github.com/ueberdosis/tiptap/issues/1264#issuecomment-833099584 pointed to [this sample](https://codesandbox.io/s/eager-resonance-kjw98?file=/src/Mention.ts) which is working properly on android / chrome. Here, the code is removing the mention if the character directly after the mention is removed.  It also seems to inject a non-visible character directly after the mention when you select a mention.

There's also some discussion in this other issue: https://github.com/ueberdosis/tiptap/issues/677

**Comment by barbatus** [comment]
Another one fix that seems working (based on discussions in https://github.com/ProseMirror/prosemirror/issues/565 https://github.com/ProseMirror/prosemirror/issues/903)
```
beforeinput: (view, event) => {
  if (isAndroid() && event.inputType === 'deleteContentBackward') {
    const { $cursor } = view.state.selection;
    view.dom.blur();
    view.focus();
    view.state.doc.nodesBetween($cursor.pos - 1, $cursor.pos,
      (node) => {
         view.dispatch(
           view.state.tr.delete($cursor.pos - 1, $cursor.pos).scrollIntoView(),
         );
      },
    );
  }
}
```
