### ISSUE TITLE
Passing editor to EditorContent is a type error

### ISSUE THREAD

**Issue by bartenra** [ueberdosis/tiptap#1344]
**Description**
It seems that it's not possible to pass an instance of `Editor` to `EditorContent`. It's a type error:

```vue
<template>
  <editor-content :editor="editor" v-if="editor" />
</template>

<script lang="ts">
import { Editor, EditorContent } from '@tiptap/vue-3'
import StarterKit from '@tiptap/starter-kit'
import { defineComponent } from '@vue/runtime-core'
export default defineComponent({
  components: {
    EditorContent,
  },
  data() {
    return {
      editor: null,
    } as { editor: Editor | null }
  },
  mounted() {
    this.editor = new Editor({
      content: '<p>I’m running tiptap with Vue.js. 🎉</p>',
      extensions: [
        StarterKit,
      ],
    })
  },
  beforeUnmount() {
    this.editor?.destroy()
  },
});
</script>
```

**Steps to reproduce the bug**
1. Copy component above or check out repo below
2. Run `npx vue-tsc --noEmit` (official type checker for Vue templates)
3. This results in the following error:

```
src/components/Tiptap.vue:2:20 - error TS2740: Type '{ vueRenderers: Map<string, VueRenderer>; contentComponent: { uid: number; type: FunctionalComponent<{}, any> | { [x: string]: any; setup?: ((this: void, props: {}, ctx: SetupContext<...>) => any) | undefined; ... 39 more ...; __file?: string | undefined; }; ... 17 more ...; ctx: ComponentPublicInstance<...>; } | nu...' is missing the following properties from type 'Editor': reactiveState, commandManager, css, injectCSS, and 9 more.

2   <editor-content :editor="editor" v-if="editor" />
                     ~~~~~~

  node_modules/@tiptap/vue-3/dist/packages/vue-3/src/EditorContent.d.ts:13:5
    13     editor: Editor;
           ~~~~~~
    The expected type comes from property 'editor' which is declared here on type 'Partial<{ editor: Editor; }> & Omit<Readonly<{ editor: Editor; }> & VNodeProps & AllowedComponentProps & ComponentCustomProps, "editor"> & Omit<...> & Record<...>'


Found 1 error.
```

**Repro**
I created a repo: https://github.com/bartenra/tiptap-typescript-error-repro

**Expected behavior**
No type error

**Screenshot, video, or GIF**
![image](https://user-images.githubusercontent.com/77667589/118778160-19a25a00-b88a-11eb-8e20-b2430bedd745.png)

**Environment?**
 - tiptap version: @tiptap/vue-3": "^2.0.0-beta.37"

**Comment by bartenra** [comment]
Note that the Composition API equivalent does not have the same problem (see below).

So I think it has something to do with Typescript support of the Options API...

Feel free to close this.

```vue
<template>
  <editor-content :editor="editor" v-if="editor" />
</template>

<script lang="ts">
import { Editor, EditorContent, useEditor } from '@tiptap/vue-3'
import StarterKit from '@tiptap/starter-kit'
import { defineComponent } from '@vue/runtime-core'

export default defineComponent({
  components: {
    EditorContent,
  },
  setup() {
    const editor = useEditor({
      content: '<p>I’m running tiptap with Vue.js. 🎉</p>',
      extensions: [
        StarterKit,
      ],
    })
    return {
      editor
    }
  }
});
</script>
```

**Comment by chasinhues** [comment]
Had a similar issue in tiptap for react. Importing `Editor` from "@tiptap/core" worked for me.

### Error
import { Editor, EditorContent } from "@tiptap/react";

### No error
import { EditorContent } from "@tiptap/react";
import { Editor } from "@tiptap/core";

**Comment by philippkuehn** [comment]
Can’t reproduce this. It’s probably fixed already.

**Comment by raarts** [comment]
Still a problem for me. Importing Editor from @tiptap/react gives me the following error:

```
Property 'contentComponent' is missing in type 
'import("/Users/xxx/work/project/node_modules/@tiptap/core/dist/packages/core/src/Editor").Editor'
but required in type
'import("/Users/xxx/work/project/node_modules/@tiptap/react/dist/packages/react/src/Editor").Editor'.
```

importing Editor from @tiptap/core instead fixed it. I checked and all my other source files imported Editor from @tiptap/react without problem.

This happened inside the onFocus function on the useEditor function. Maybe that's where the problem lies? 
Is inFocus typed with the wrong Editor?

**Comment by mohkoma** [comment]
Same problem! here

**Comment by mohkoma** [comment]
Same problem but I found a quick solution to fix that using the `ShallowRef` type from the vue core.

```
import { defineComponent, PropType, ShallowRef } from 'vue'
export default defineComponent({
    data() {
        return {
            editor: null as unknown as ShallowRef<Editor>,
        }
    }
}
```
This way it will work as it should same as using `useEditor` 🎉

**Comment by ryanscottaudio** [comment]
same issue here, all of my `@tiptap` stuff is set to `^2.0.3`
