### ISSUE TITLE
image extension enhancements, drag-to-resize, caption

### ISSUE THREAD

**Issue by acidjazz** [ueberdosis/tiptap#1350]
- [ ] ability to drag the corners of an image in order to resize it
- [ ] ability to set a caption for an image that gets stored - maybe store it as the alt tag?

**Comment by hanspagel** [comment]
Thanks! Would you mind creating separate issues for separate feature requests, for example create a new request just fo the caption? That’s way easier to discuss, assign, resolve and so on.

**Comment by acidjazz** [comment]
drag-to-resize issue https://github.com/ueberdosis/tiptap/issues/1354

**Comment by acidjazz** [comment]
and a third extension feature request for reference https://github.com/ueberdosis/tiptap/issues/1356

**Comment by hanspagel** [comment]
Thanks! Closing this here then. ✌️

**Comment by XinChou16** [comment]
I am looking forward to the implementation of such a function, zoom, rotate function is a very common function of the picture.
