### ISSUE TITLE
Generate HTML from JSON tree on server-side (no JS)

### ISSUE THREAD

**Issue by treystout** [ueberdosis/tiptap#1351]
**The problem I am facing**
We store tiptap json trees in our postgres db as `jsonb` colums. Our server-side scripts have no way to render those trees in things like email notifications or static SEO templates.

**The solution I would like**
A server-side program that can render HTML from tiptip's json representation. Language doesn't matter as long as we can throw it in docker. Python?

**Alternatives I have considered**
Storing both the HTML and jsonb representation for all fields in the db, but that's a waste of space and un normalized.

**Comment by hanspagel** [comment]
Would you mind sharing why JS not an option? https://www.tiptap.dev/api/utilities/html

Would PHP work for you? We have a PHP package to render JSON as HTML: https://github.com/ueberdosis/prosemirror-to-html

(I’m working on a rewrite that’s even better and compatible with tiptap v2 out of the box.)

**Comment by treystout** [comment]
The main reason is the scripts that need the HTML version are currently implemented in Python. So I was hoping that maybe someone had already implemented something in python. So the python scripts that process messages would need to shell out to node to get the html, or spin up some express server and make it HTTP based. None of that sounds good. Any other ideas?

I wonder if trying to get the db to do it is too much of a stretch. Something like https://github.com/plv8/plv8 + TipTap in a postgres function that returns the HTML as `text`.

**Comment by hanspagel** [comment]
Maybe that helps then: https://pypi.org/project/tiptapy/

An official Python library or Postgres extension feels out of scope, so I’m closing this here.
