### ISSUE TITLE
image extension enhancement - ability to caption an image

### ISSUE THREAD

**Issue by acidjazz** [ueberdosis/tiptap#1355]
- [ ] show an indication of the current captions value/label
- [ ] ability to change that caption
- [ ] store the caption as the alt tag?

**Comment by hanspagel** [comment]
Thanks! I think we could add a figure/figcaption extension to tiptap. Would that help?

```html
<figure>
    <img src="example.jpg" alt="Photo of someone writing code">
    <figcaption>Me, writing an example</figcaption>
</figure>
```

**Comment by LaravelFreelancerNL** [comment]
Sounds like a plan. Adding srcset would make it responsive as well which will help with SEO.

**Comment by acidjazz** [comment]
@hanspagel how would that work exactly? I'm mainly concerned about them being able to specify and edit the caption, would that be part of the extension?

**Comment by hanspagel** [comment]
I’ve added an experiment: https://www.tiptap.dev/experiments/figure

It’s not finished, but should give you a good idea how that could work. What do you think?

**Comment by manogi** [comment]
I would use that!
