### ISSUE TITLE
table extension - ability to display and specify a caption

### ISSUE THREAD

**Issue by acidjazz** [ueberdosis/tiptap#1356]
- [ ] show an indication of the current captions value/label
- [ ] ability to change that caption
- [ ] store the caption as a title tag?

**Comment by hanspagel** [comment]
I gave this a shot, but it’s pretty complex to add soemthing inside the table. I’m afraid this is far from an easy task. As a workaround I’d suggest a wrapper extension, that would produce something like the following:

```html
<p>Example Text</p>
<div class="tableWrapper">
  <p>My Table</p>
  <table>
    <!-- … -->
  </table>
</div>
<p>More text</p>
```

Would that help?

**Comment by Brand2** [comment]
Hi @hanspagel,

Obviously not the original author, but I think such a wrapper would be useful for people. Would it be something like the below, or am I way off-base here?

```typescript
import {mergeAttributes} from '@tiptap/core'
import {Table} from '@tiptap/extension-table'

declare module '@tiptap/core' {
  interface Commands<ReturnType> {
    captionedTable: {
      /**
       * Set a captioned table
       */
      insertCaptionedTable: (attributes: {
        caption: string
        rows?: number
        cols?: number
        withHeaderRow?: boolean
      }) => ReturnType
    }
  }
}

export const CaptionedTable = Table.extend({
  name: 'captionedTable',

  parseHTML() {
    return [
      {
        tag: 'div',
        contentElement: 'p',
        getAttrs: (node) => {
          return (node as HTMLElement).className === 'captioned-table' && null
        }
      }
    ]
  },

  renderHTML({HTMLAttributes}) {
    return [
      'div',
      mergeAttributes(this.options.HTMLAttributes, {class: 'captioned-table'}),
      ['table', HTMLAttributes, ['tbody', 0]],
      ['p', 0]
    ]
  },

  addCommands() {
    return {
      insertCaptionedTable:
        ({caption, rows = 3, cols = 3, withHeaderRow = true}) => ({chain}) => {
          return chain()
            .insertContent({
              type: this.name,
              content: [{type: 'text', text: caption}]
            })
            .command(({tr, commands}) => {
              const {doc, selection} = tr
              const tablePositionStart = doc.resolve(selection.to - 1).start()
              // Select embedded table, and replace with a table node
              commands.setNodeSelection(tablePositionStart)
              return commands.insertTable({
                rows: rows,
                cols: cols,
                withHeaderRow: withHeaderRow
              })
            })
            .run()
        }
    }
  }
})
```

**Comment by hanspagel** [comment]
Looks good! An alternative approach would be a new TableWrapper extension with `content: 'block table'` (one block node = paragraph by default, followed by a table), but chances are your approach works better. 👌 Didn’t test it.

**Comment by Brand2** [comment]
Thanks for the response, I'm still playing around with it, when I get something working I'll hopefully report back =)

**Comment by Zac-Zajdel** [comment]
> Thanks for the response, I'm still playing around with it, when I get something working I'll hopefully report back =)

Hello. Any progress made on that?

**Comment by jamesg-rimsys** [comment]
@hanspagel When we are extending the table, it gave errors like `RangeError: Adding different instances of a keyed plugin (plugin$1)`. When we are trying to create a new node, the table loses its functionality in tiptap.  We are in dire need of some feedback on how to make this work to ensure that the Caption is associated to the table.

**Comment by hanspagel** [comment]
The range error comes when loading multiple extensions with the same `name` (we should improve this error message). 

Did you try Brad2’s approach?

Maybe you take inspiration from the figure experiment:
https://www.tiptap.dev/experiments/figure

If you could provide a CodeSandbox maybe we or someone else could have a look.

**Comment by shawn-rimsys** [comment]
> The range error comes when loading multiple extensions with the same `name` (we should improve this error message).
> 
> Did you try Brad2’s approach?
> 
> Maybe you take inspiration from the figure experiment:
> https://www.tiptap.dev/experiments/figure
> 
> If you could provide a CodeSandbox maybe we or someone else could have a look.

I'm trying to mock up Brad2's approach in this sandbox: https://codesandbox.io/s/table-caption-bucm8
it shows an error not identifying the insertCaptionedTable error, could you help me check this, thank you.

**Comment by jamesg-rimsys** [comment]
Thanks @shawn-rimsys.  @hanspagel it looks like when adding the table.extend, it loses its functionality.  Could really use some help on this one if you or someone can take a look.

**Comment by philippkuehn** [comment]
@jamesg-rimsys what do you mean by `loses its functionality`? One issue of using [the solution of @Brand2](https://github.com/ueberdosis/tiptap/issues/1356#issuecomment-870507580) is that all table commands gets overwritten. You can prevent that by calling `this.parent()` within `addCommands`.

```js
export const CaptionedTable = Table.extend({
  addCommands() {
    return {
      // register all previous commands
      ...this.parent?.(),
      // register new commands
      insertCaptionedTable: // ...
    }
  },
})
```

**Comment by shawn-rimsys** [comment]
> @jamesg-rimsys what do you mean by `loses its functionality`? One issue of using [the solution of @Brand2](https://github.com/ueberdosis/tiptap/issues/1356#issuecomment-870507580) is that all table commands gets overwritten. You can prevent that by calling `this.parent()` within `addCommands`.
> 
> ```js
> export const CaptionedTable = Table.extend({
>   addCommands() {
>     return {
>       // register all previous commands
>       ...this.parent?.(),
>       // register new commands
>       insertCaptionedTable: // ...
>     }
>   },
> })
> ```

@philippkuehn Thank you for your response. When I wrote code like Table.extend, we got an error message like RangeError: Adding different instances of a keyed plugin (plugin$1).

**Comment by jamesg-rimsys** [comment]
> > @jamesg-rimsys what do you mean by `loses its functionality`? One issue of using [the solution of @Brand2](https://github.com/ueberdosis/tiptap/issues/1356#issuecomment-870507580) is that all table commands gets overwritten. You can prevent that by calling `this.parent()` within `addCommands`.
> > ```js
> > export const CaptionedTable = Table.extend({
> >   addCommands() {
> >     return {
> >       // register all previous commands
> >       ...this.parent?.(),
> >       // register new commands
> >       insertCaptionedTable: // ...
> >     }
> >   },
> > })
> > ```
> 
> @philippkuehn Thank you for your response. When I wrote code like Table.extend, we got an error message like RangeError: Adding different instances of a keyed plugin (plugin$1).

@philippkuehn to further clarify on the losing functionality: when we are trying to extend the table in a new component, we used Node.create and then defined the initiated table in an extra vue file, just like what we did for Figure Captionss. But when we tried this method, the table could not be recognized by tiptap's editor, which makes it lose all its functionality

**Comment by philippkuehn** [comment]
I don't think it makes sense to have that built into the table, since it’s complex enough as it is.

But after thinking about it a bit, it probably makes sense to use a generic figure node, as well as a separate figcaption node. This generic figure node can be used to display different nodes in it (e.g. images or tables). I have [created an experiment for it](https://www.tiptap.dev/experiments/generic-figure).

What do you think about it?

**Comment by jamesg-rimsys** [comment]
Looks promising @philippkuehn and thank you for the support.  How would you delete the table and caption at the same time.  With the current delete table function, it would orphan the caption.  Would this be a custom command we would need to create?

**Comment by philippkuehn** [comment]
I've added buttons for adding and removing these figures. Hope this helps!

(Added a new `deleteNode` command to the core package so you have to update your packages to use it).

**Comment by jamesg-rimsys** [comment]
@philippkuehn this is great!  one final question.  We tried to put the caption above the table; however, if we put the caption above the table and hit enter, the functionality breaks as shown in.  Any thoughts?

![image](https://user-images.githubusercontent.com/73393377/127407336-2befa08b-5f08-4f5c-848d-c640de3c632e.png)

**Comment by philippkuehn** [comment]
[I moved the caption to top](https://github.com/ueberdosis/tiptap/commit/040a539f0f6bac92be010e1b54dc755465def6cf) but can’t see anything broken.
