### ISSUE TITLE
New event - track and respond to cursors current location

### ISSUE THREAD

**Issue by acidjazz** [ueberdosis/tiptap#1358]
I have some areas where my editor has menus on the side that I want to keep in line w/ the current cursor location.  I have a sort of "hack" I'm currently using that doesn't work too well (vue2).

1. on `mounted()` i bind a method to the `transaction` event.

```js
    this.editor.on('transaction', this.cursorLocate)
```

2. Here is the current method I'm using.
```ts
    cursorLocate () {
      if (!this.focused) return
      const r = document.getSelection()?.getRangeAt(0)
      const node = r?.startContainer
      const offset = r?.startOffset
      const pageOffset = {x:window.pageXOffset, y:window.pageYOffset}
      let rect,  r2;

      if (node && offset && offset > 0) {
        r2 = document.createRange()
        r2.setStart(node, (offset - 1))
        r2.setEnd(node, offset)
        rect = r2.getBoundingClientRect()
        const full = this.$refs.TipTapFull as HTMLElement
        this.$emit('cursor', {
          left:rect.right + pageOffset.x,
          top:rect.bottom + pageOffset.y,
          rect: full.getBoundingClientRect(),
        } as Cursor)
      }
    },

```

I'm not getting an update or proper location when zero text is selected or the cursor is moved by hitting `<enter>`

It would be cool to have a more proper event I could bind to, maybe something like

```ts
this.editor.on('cursoor', ({x, y }) => ...)
```

**Comment by philippkuehn** [comment]
You probably searching for [coordsAtPos](https://prosemirror.net/docs/ref/#view.EditorView.coordsAtPos)

```js
editor.on('selectionUpdate', ({ editor }) => {
   const from = editor.view.coordsAtPos(editor.state.selection.from)
   const to = editor.view.coordsAtPos(editor.state.selection.to)
})
```

**Comment by acidjazz** [comment]
@philippkuehn works beautifully, might be pretty helpful in the docs!

**Comment by SF-Simon** [comment]
@acidjazz 
Hi, can you provide a complete method?  Because we are also fulfilling this requirement, please provide us with reference if possible.  Thank you so much.
