### ISSUE TITLE
Pasted `code` marks are wrapped in non-breakable spaces.

### ISSUE THREAD

**Issue by cadars** [ueberdosis/tiptap#1364]
1. Copy some HTML with `<code>` elements, for example the first paragraph here: https://www.tiptap.dev/api/marks/code/#code
2. Paste in the editor of the same page.
3. Inspect the pasted paragraph to see the code elements wrapped in `&nbsp;`

![image](https://user-images.githubusercontent.com/467112/119263553-cc065400-bbdf-11eb-815d-1c9f152129c8.png)

Environment: macOS 10.13.6, Chromium (MS Edge)

**Comment by philippkuehn** [comment]
I can't reproduce this with the latest version of Edge (91.0.864.37)

**Comment by cadars** [comment]
Might be related to my _antique_ version of macOS then. It also affects <a> marks.
I tried in Chromium.app with the same results,
