### ISSUE TITLE
Allow width and height attributes for image

### ISSUE THREAD

**Issue by Nick-Mazuk** [ueberdosis/tiptap#1365]
**The problem I am facing**

It's good practice to include `height` and `width` attributes on images to prevent layout shift as they load. The current plugin does not allow you to set these attributes.

Soon, metrics like cumulative layout shift are going to be a factor in Google search rankings, which means this is about to become critical.

**The solution I would like**

To be able to do

```ts
editor.chain().focus().setImage({ src, width, height }).run()
```

**Alternatives I have considered**

- Unlike attributes like `loading="lazy"` which can be set with `HTMLAttributes`, width and height are specific to each image and need to be set with `setImage`.
- Create my own version of the plugin

**Comment by philippkuehn** [comment]
You can extend the node for that:


```js
import Image from '@tiptap/extension-image'

export const CustomImage = Image.extend({
  addAttributes() {
    return {
      ...this.parent?.(),
      width: {
        default: null,
      },
      height: {
        default: null,
      },
    }
  },
})

```
