### ISSUE TITLE
Placeholder doesn't render when editor content includes empty paragraph with not empty id attribute

### ISSUE THREAD

**Issue by kamilbedalaboratorium** [ueberdosis/tiptap#1371]
**Description**
Placeholder doesn't render when editor content includes empty paragraph with not empty id attribute.

**Steps to reproduce the bug**
1. Use JSON format
2. Add paragraph and placeholder extension to editor
2. Add `id` attribute to Paragraph extension
3. Set default editor content to
```
content: {
        type: "doc",
        content: [{ type: "paragraph", attrs: { id: "anything" } }],
      }
```

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:

* Vue: https://codesandbox.io/s/tiptap-issue-template-forked-txfq1?file=/src/components/Tiptap.vue

**Expected behavior**
Placeholder rendering when paragraph has no content (ignoring attrs value)

**Environment**
 - operating system: Ubuntu
 - browser: Chrome
 - mobile/desktop: both
 - tiptap version: latest

**Comment by BrianHung** [comment]
Look's like an issue with how editor determines if its empty or not:

https://github.com/ueberdosis/tiptap/blob/42c0ca85b3a94be40d23da19b5213afe59ac067e/packages/extension-placeholder/src/placeholder.ts#L48-L50

https://github.com/ueberdosis/tiptap/blob/42c0ca85b3a94be40d23da19b5213afe59ac067e/packages/core/src/Editor.ts#L401-L406

https://github.com/ueberdosis/tiptap/blob/42c0ca85b3a94be40d23da19b5213afe59ac067e/packages/core/src/helpers/isNodeEmpty.ts#L3-L8

`isEditorEmpty` compares whether the current content is equal to the empty doc, not whether current content equals default content.

**Comment by softmarshmallow** [comment]
Can we expect a fix for this? (or slot for providing custom isNodeEmpty logic func)

**Comment by malko** [comment]
Any update regarding this bug ?

**Comment by kamilbedalaboratorium** [comment]
Lol as far as I know this is not completed. 
Forgotten is a better word for that 😉
