### ISSUE TITLE
Mark attributes not changeable unless entire mark is encased in selection in editor 

### ISSUE THREAD

**Issue by brettins** [ueberdosis/tiptap#1378]
**Description**
Mark attributes are not changeable unless entire mark is selected in the editor, otherwise it attempts to create a new mark, and fails if there is no text selected via the caret/cursor. 

**Steps to reproduce the bug**
https://codesandbox.io/s/tiptap-issue-template-forked-ymxiq
1. Select some text
2. Click `Toggle Info Mark` button - this will create the Info mark, which is a span with the attribute "info"
3. Click somewhere else in the editor
4. Click anywhere within the info text you selected before 
5. Click `Change Color To Red`
6. Observe that the text does not change to red. 

### And, to confirm that the attribute changes work properly
7. Select all of the text that you previously changed into a mark
8. Click `Change Color To Red` and observe that the text does change to red. 

### To confirm that a new mark will be created on attribute update,
9. Select a portion of the original mark that was created. 
10. Click `Change Color To Red`
11. Observe that only the selected text is changed to red, a new info `span` was created instead of the entire mark that was initially created. 

### To confirm the editor knows that you are within a mark and can modify that mark without a selection: 
12. Click anywhere with a mark you've created.
13. Click `Toggle Info Mark`
14. Observe that the Info mark is removed. 

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:

https://codesandbox.io/s/tiptap-issue-template-forked-ymxiq

**Expected behavior**
When the cursor is inside the mark and the editor recognizes this, making editor calls to update attributes should affect the whole mark instead of trying to create a new mark (and failing if there is nothing selected)

**Screenshot, video, or GIF**

**Environment?**
 - tiptap version: 2

```javascript
// info.js - Mark extension
import { Mark, mergeAttributes } from "@tiptap/core";

export default Mark.create({
  name: "info",

  addAttributes() {
    return {
      info: {
        default: "start",
        renderHTML: (attributes) => {
          return {
            info: attributes.info
          };
        }
      },
      color: {
        default: "blue",
        renderHTML: (attributes) => {
          return {
            style: `color: ${attributes.color}`
          };
        }
      },
      underline: {
        default: "underline",
        renderHTML: () => {
          return {
            style: `text-decoration: underline`
          };
        }
      }
    };
  },

  parseHTML() {
    return [
      {
        tag: "span[info]"
      }
    ];
  },

  renderHTML({ HTMLAttributes }) {
    return [
      "span",
      mergeAttributes(this.options.HTMLAttributes, HTMLAttributes),
      0
    ];
  },

  addCommands() {
    return {
      setInfo: () => ({ commands }) => {
        return commands.setMark("info");
      },
      toggleInfo: () => ({ commands }) => {
        return commands.toggleMark("info");
      },
      unsetInfo: () => ({ commands }) => {
        return commands.unsetMark("info");
      },
      setInfoValue: (value) => ({ commands }) => {
        commands.updateAttributes(this.name, { info: value });
      },
      setColor: () => ({ commands }) => {
        commands.updateAttributes(this.name, { color: "red" });
      }
    };
  }
});
```

**Comment by philippkuehn** [comment]
You probably want to call `extendMarkRange()` (https://www.tiptap.dev/api/commands/extend-mark-range/#extendmarkrange) before updating your mark.

**Comment by brettins** [comment]
That worked, thank you!

The behaviour seems unexpected to me.

**Comment by jelling** [comment]
+1 for this being unexpected, although I understand on a technical level why it's necessary.
