### ISSUE TITLE
"TypeError: extensions.map(...).flat is not a function" for editor initialization in old Samsung Internet Browser

### ISSUE THREAD

**Issue by xjimdim** [ueberdosis/tiptap#1382]
Tiptap2 is not working for old (Android < 10) Samsung Internet browser (version 1 used to work fine).
I know this is a minor issue but there are still users using that browser. 

When I try to initialize the editor I get this error (tested on Android 9 Samsung Internet Browser):
`TypeError: extensions.map(...).flat is not a function `

<details>
  <summary>Click for error stack (weird formatting - sorry) </summary>
  TypeError: extensions.map(...).flat is not a function at Function.flatten (webpack-internal:///./node_modules/@tiptap/core/dist/tiptap-core.esm.js:834:14) at Function.resolve (webpack-internal:///./node_modules/@tiptap/core/dist/tiptap-core.esm.js:818:55) at new ExtensionManager (webpack-internal:///./node_modules/@tiptap/core/dist/tiptap-core.esm.js:767:44) at Editor.createExtensionManager (webpack-internal:///./node_modules/@tiptap/core/dist/tiptap-core.esm.js:2573:33) at new Editor (webpack-internal:///./node_modules/@tiptap/core/dist/tiptap-core.esm.js:2459:14) at Editor.eval (webpack-internal:///./node_modules/@tiptap/vue-2/dist/tiptap-vue-2.esm.js:38:263) at new Editor (webpack-internal:///./node_modules/@tiptap/vue-2/dist/tiptap-vue-2.esm.js:109:21) at _callee$ (webpack-internal:///./node_modules/babel-loader/lib/index.js?!./node_modules/ts-loader/index.js?!./node_modules/vue-loader/lib/index.js?!./components/carzilla/widgets/CarzillaRichTextEditor/CarzillaRichTextEditor.vue?vue&type=script&lang=ts&:84:32) at tryCatch (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:45:40) at Generator.invoke [as _invoke] (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:274:22) at Generator.prototype.(anonymous function) [as next] (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:97:21) at asyncGeneratorStep (webpack-internal:///./node_modules/babel-loader/lib/index.js?!./node_modules/ts-loader/index.js?!./node_modules/vue-loader/lib/index.js?!./components/carzilla/widgets/CarzillaRichTextEditor/CarzillaRichTextEditor.vue?vue&type=script&lang=ts&:12:103) at _next (webpack-internal:///./node_modules/babel-loader/lib/index.js?!./node_modules/ts-loader/index.js?!./node_modules/vue-loader/lib/index.js?!./components/carzilla/widgets/CarzillaRichTextEditor/CarzillaRichTextEditor.vue?vue&type=script&lang=ts&:14:194)
</details>

I have tried transpiling all my tiptap packages with babel through my nuxt/build config like this:
 
```
transpile: [
    '@tiptap/extension-image',
    '@tiptap/extension-link',
    '@tiptap/extension-placeholder',
    '@tiptap/extension-underline',
    '@tiptap/starter-kit',
    '@tiptap/vue-2'
]
```

but with no luck

I found the problem using browserstack on an Android 9 samsung device and Samsung Internet browser (I dont know any other way of recreating it for now).

Is there a solution for this?

**Comment by philippkuehn** [comment]
tiptap 2 is using this browserslist config:

```json
"browserslist": [
    "defaults",
    "not IE 11",
    "maintained node versions"
],
```

`default` means:
Browserslist’s default browsers (> 0.5%, last 2 versions, Firefox ESR, not dead).

Right now I have no plans to change that.
