### ISSUE TITLE
`findSuggestionMatch`， There should be a configuration to configure whether to match the prefix

### ISSUE THREAD

**Issue by Akimotorakiyu** [ueberdosis/tiptap#1384]
`findSuggestionMatch`， There should be a configuration to configure whether to match the prefix:

below function should have a switch configuration:

https://github.com/ueberdosis/tiptap/blob/6990012a7b4ca20f44d8bbbe3293ffbf366a65fe/packages/suggestion/src/findSuggestionMatch.ts#L28

https://github.com/ueberdosis/tiptap/blob/6990012a7b4ca20f44d8bbbe3293ffbf366a65fe/packages/suggestion/src/findSuggestionMatch.ts#L45-L51

**Comment by way-jm** [comment]
I also think it well, if i want use mention ,  I must  input a space before '@', it looks not elegant
