### ISSUE TITLE
How to prevent the addition of marks on a Mention ? 

### ISSUE THREAD

**Issue by GitHubish** [ueberdosis/tiptap#1387]
I am trying to prevent the addition of marks (such as bold) on my mention type. I have extended the type that Tiptap offers by trying to specify : 

```
marks: '',

addAttributes() {
    ...
}
```

![2021-05-27_17-15-24](https://user-images.githubusercontent.com/7701833/119853352-692ef880-bf10-11eb-9456-bb6c9f241618.gif)

But it doesn't work. What am I missing?
Thanks

**Comment by philippkuehn** [comment]
It’s probably just a styling issue on your side. What’s the rendered markup?

**Comment by GitHubish** [comment]
Here is the rendered markup and the JSON :

![chrome_2021-05-27_17-54-06](https://user-images.githubusercontent.com/7701833/119858457-c75dda80-bf14-11eb-8a15-b195b602f3b2.png)
![chrome_2021-05-27_17-54-26](https://user-images.githubusercontent.com/7701833/119858461-c7f67100-bf14-11eb-8851-c0febcdc70ce.png)

**Comment by philippkuehn** [comment]
Since this is how HTML/CSS works you have to reset styling for your mentions.

```css
.mention {
  font-weight: normal;
}
```

**Comment by GitHubish** [comment]
@philippkuehn but isn't it possible that the JSON output does not include the marks on the Mention ? I have specified on the Mention extension that I do not allow marks with `marks: ''`. My problem is not graphic but in the model.

**Comment by philippkuehn** [comment]
marks are controlled by the parent node. in your case the paragraph.

related: https://discuss.prosemirror.net/t/nodespec-marks-not-work-at-inline-node/2414

**Comment by GitHubish** [comment]
Thank you for this clarification. I understand better why it didn't work. Is there a clean and efficient way to control this? Because more problematic, so it is possible to add a link on a content that has text and a Mention. While in my case the mention implements a click behavior to redirect to a page ? Thanks @philippkuehn !

**Comment by aliasliao** [comment]
@GitHubish You can use [appendTransaction](https://prosemirror.net/docs/ref/#state.PluginSpec.appendTransaction) to achieve this.

Here's the code I'm using to automatically clean up marks of mention elements:

```ts
import { Transaction, Plugin } from 'prosemirror-state';

function clearMentionMarks(
  tr: Transaction, // An old transaction
  newTr: Transaction, // The latest transaction
): boolean {
  let cleared = false;

  tr.doc.descendants((node, pos) => {
    if (node.type.name === 'mention' && node.marks.length > 0) {
      const mappedPos = newTr.mapping.map(pos);
      newTr.setNodeMarkup(mappedPos, node.type, node.attrs, []);
      cleared = true;
    }
  });

  return cleared;
}

/**
 * Remove marks from mention element.
 * */
export class ClearMentionMarksPlugin extends Plugin {
  constructor() {
    super({
      appendTransaction(transactions, oldState, newState) {
        // Create a new transaction.
        const newTr = newState.tr;

        let cleared = false;
        for (const transaction of transactions) {
          const anotherClear = clearMentionMarks(transaction, newTr);
          cleared = anotherClear || cleared;
        }
        if (cleared) {
          return newTr;
        }
      },
    });
  }
}

```
