### ISSUE TITLE
 If I include code, I cannot cancel the style I set earlier (such as bold).

### ISSUE THREAD

**Issue by akirarika** [ueberdosis/tiptap#1388]
**Description**
Thank you for creating this great editor framework! I have a problem. I don't know if it is a bug:

**Screenshot, video, or GIF**
![录屏_选择区域_20210528152800](https://user-images.githubusercontent.com/33272184/119947401-45c88400-bfca-11eb-9d74-cbdab5148dc6.gif)

**Steps to reproduce the bug**
1. Open [Tiptap Demo](https://www.tiptap.dev/examples/default/)
2. Set a piece of text as code
3. Click bold (or italic, strike..)
4. Click again
5. Style not cancelled as expected

**Environment?**
 - operating system: Debian10
 - browser: Chrome v90
 - mobile/desktop: Desktop
 - tiptap version: Latest

**Comment by philippkuehn** [comment]
hey, can you reproduce this on another operating system/browser too?

**Comment by akirarika** [comment]
This is recorded in the Chrome browser I am friends under Windows10 20H2:

https://user-images.githubusercontent.com/33272184/120058462-88976400-c07d-11eb-8d93-42f2d887a493.mp4

This is Chrome under Android 10:

https://user-images.githubusercontent.com/33272184/120058588-95688780-c07e-11eb-81ef-f01b7e2a034a.mp4

@philippkuehn Sorry, I don't have Apple-related devices around me, I can only provide Linux, Windows and Android videos 😥

**Comment by akirarika** [comment]
It seems that there will be the same problem on Firefox:

https://user-images.githubusercontent.com/33272184/120058697-643c8700-c07f-11eb-8b66-b8e24f6fd855.mp4

**Comment by philippkuehn** [comment]
ah, this only happens if there is a code mark within the selection.

**Comment by akirarika** [comment]
> ah, this only happens if there is a code mark within the selection.

Yes😥. Sorry, my native language is not English, before may not have described clearly
