### ISSUE TITLE
[extension-heading] allow id/custom attributes

### ISSUE THREAD

**Issue by atulmy** [ueberdosis/tiptap#1390]
**The problem I am facing**
extension-heading at the moment only accepts `level` as attribute

**The solution I would like**
If there was an option to allow us to set any custom attribute like `id` on header tag eg: `<h1 id="title">Title</h1>` that would help to link to specific section of blog post using hash anchor links.

**Alternatives I have considered**
Creating custom extension

**Comment by hanspagel** [comment]
Not everbody wants an id attribute, but we have API to add attributes to an existing extension.

https://www.tiptap.dev/guide/custom-extensions#attributes

https://www.tiptap.dev/guide/node-views/examples#table-of-contents
