### ISSUE TITLE
Click on Margin between the two lines, the cursor will move to the top of the next line

### ISSUE THREAD

**Issue by akirarika** [ueberdosis/tiptap#1391]
**Description**

Thank you for creating this great editor framework! I have a problem. I don't know if it is a bug:

If I click on `margin` between the two lines, the cursor will move to the top of the next line, please watch the video and pay attention to the cursor position:

**Screenshot, video, or GIF**

https://user-images.githubusercontent.com/33272184/120072881-78f13d00-c0c8-11eb-9dc2-b15e6c87d61a.mp4

**Environment?**
 - operating system: Debian10
 - browser: Chrome v90
 - mobile/desktop: Desktop
 - tiptap version: Latest

**Additional context**

Anyway, thank you again for creating this great editor framework!

**Comment by philippkuehn** [comment]
That’s how contenteditable works in browsers. I think we can’t do anything here.

I think a workaround could be to avoid margins.
