### ISSUE TITLE
Tiptap demo in playground does not compile

### ISSUE THREAD

**Issue by brucou** [ueberdosis/tiptap#1398]
**Description**
The [tiptap demo in the playground](https://svelte.dev/repl/798f1b81b9184780aca18d9a005487d2?version=3.31.2) does not work. The error message is `process is not defined.` (in the `Result` tab on the right window):

**Steps to reproduce the bug**
1. Go to https://svelte.dev/repl/798f1b81b9184780aca18d9a005487d2?version=3.31.2
You should see:

**Expected behavior**
Should see the editor in action.

**Screenshot, video, or GIF**
![Imgur](https://imgur.com/xM4Uc8N.png)

**Environment?**
 - operating system: windows 10
 - browser: chrome, edge
 - tiptap version: I don't know!

**Additional context**
Original link here: https://www.tiptap.dev/installation/svelte#take-a-shortcut-svelte-repl-with-tiptap

**Comment by philippkuehn** [comment]
we have to remove the bubble menu from the svelte playground because tippy.js is not working with svelte REPL.

**Comment by philippkuehn** [comment]
ruplicate of #1333
