### ISSUE TITLE
Cannot read property 'pmViewDesc' of null

### ISSUE THREAD

**Issue by amursky** [ueberdosis/tiptap#1401]
**Description**
When table is the last element in the document, holding an arrow down key causes an error:
`TypeError: Cannot read property 'pmViewDesc' of null`

**Steps to reproduce the bug**
1. Copy [tables](https://www.tiptap.dev/examples/tables/) code example.
2. Press and hold an arrow down key until the error appears.

**Screenshot, video, or GIF**
![2021-06-01 12 29 51](https://user-images.githubusercontent.com/33891482/120259968-49b11a80-c2d8-11eb-8be4-bd4e676ab6d8.gif)

**Environment**
 - operating system: MacOS Big Sur 11.4
 - browser: Google Chrome 91.0.4472.77 (arm64)
 - tiptap version: ^2.0.0-beta (latest)

**Comment by philippkuehn** [comment]
Hmm, for some reason I can’t reproduce this on our tables demo page.
