### ISSUE TITLE
Blanks are removed on firefox

### ISSUE THREAD

**Issue by MousMakes** [ueberdosis/tiptap#1402]
**Description**
I tested this on safari, chrome (vivaldi) and firefox. If i type into the editor and there is a blank before the cursor, the blank is being removed. This results in all typed words being joined together. The blank is not removed immediately, but when ou type in the next character

**Steps to reproduce the bug**
1. Create an editor with `EditorContent` from `@tiptap/vue-2` with this config: 
```
this.editor = new Editor({
  extensions: [
    StarterKit,
    Highlight,
    Typography,
    Underline,
    TextAlign,
    Link,
    Placeholder.configure({
      placeholder: 'Write something...'
    })
  ],
  content: this.value || null,
  injectCSS: false,
  onUpdate: () => {
    this.$emit('input', this.editor.isEmpty ? null : this.editor.getHTML());
  }
});
```
2. Open editor in firefox
3. Type in something
4. See error message

I tried to create use the sandbox in firefox for reproduction, but the editor was not rendered in there.

**Expected behavior**
Words can be spaced with a blank.

**Screenshot, video, or GIF**
![Blank_bug](https://user-images.githubusercontent.com/60437467/120275168-30e13e80-c2b1-11eb-9277-f5e4dad22025.gif)

**Environment?**
 - operating system: Windows 10
 - browser: Firefox
 - mobile/desktop: -
 - tiptap version: 
```
"@tiptap/extension-highlight": "^2.0.0-beta.13",
"@tiptap/extension-link": "^2.0.0-beta.17",
"@tiptap/extension-placeholder": "^2.0.0-beta.21",
"@tiptap/extension-text-align": "^2.0.0-beta.17",
"@tiptap/extension-typography": "^2.0.0-beta.12",
"@tiptap/extension-underline": "^2.0.0-beta.14",
"@tiptap/starter-kit": "^2.0.0-beta.70",
"@tiptap/vue-2": "^2.0.0-beta.34",
```

**Comment by amursky** [comment]
Typography extension is already included in StarterKit:
[https://github.com/ueberdosis/tiptap/blob/main/packages/starter-kit/src/index.ts](https://github.com/ueberdosis/tiptap/blob/main/packages/starter-kit/src/index.ts)

**Comment by philippkuehn** [comment]
You should not set `injectCSS` to `false`.

**Comment by ninofiliu** [comment]
@philippkuehn I have the same issue without `inhectCSS` set to `false`

**Comment by raulpopadineti** [comment]
Setting `.ProseMirror { white-space: break-spaces; }` fixed the issue for me in Firefox.
