### ISSUE TITLE
Editor crashes when creating a lowlight code block (with lowlight v1.20.0)

### ISSUE THREAD

**Issue by pvunderink** [ueberdosis/tiptap#1409]
**Description**
Currently when working with the code-block-lowlight extension in combination with lowlight version `1.20.0`, the following error is thrown whenever a new code block is created:
```
Cannot read property 'map' of undefined
at parseNodes (https://d7z0c.csb.app/node_modules/
tiptap/extension-code-block-lowlight/dist/tiptap-extension-code-block-lowlight.esm.js:1630:16
    at eval (https://d7z0c.csb.app/node_modules/
tiptap/extension-code-block-lowlight/dist/tiptap-extension-code-block-lowlight.esm.js:1648:5
    at getDecorations (https://d7z0c.csb.app/node_modules/
tiptap/extension-code-block-lowlight/dist/tiptap-extension-code-block-lowlight.esm.js:1643:70
    at Plugin.apply (https://d7z0c.csb.app/node_modules/
tiptap/extension-code-block-lowlight/dist/tiptap-extension-code-block-lowlight.esm.js:1680:18
EditorState.applyInner
https://d7z0c.csb.app/node_modules/prosemirror-state/dist/index.es.js:749:37
EditorState.applyTransaction
https://d7z0c.csb.app/node_modules/prosemirror-state/dist/index.es.js:700:39
EditorState.apply
https://d7z0c.csb.app/node_modules/prosemirror-state/dist/index.es.js:679:15
    at Editor.dispatchTransaction (https://d7z0c.csb.app/node_modules/
tiptap/core/dist/tiptap-core.esm.js:2548:30
EditorView.dispatch
https://d7z0c.csb.app/node_modules/prosemirror-view/dist/index.es.js:4934:25
    at Object.run (https://d7z0c.csb.app/node_modules/
tiptap/core/dist/tiptap-core.esm.js:533:14
```

I found that the problem lies in [these](https://github.com/ueberdosis/tiptap/blob/main/packages/extension-code-block-lowlight/src/lowlight-plugin.ts#L37-L39
) line(s) of code. When debugging I found that the field `children` does not exist on the object returned from `lowlight.highlightAuto(...)` or `lowlight.highlight(...)`. At least not in lowlight version `1.20.0`.

**Proposed solution**
Use `value` instead of `children` in lines 37-39 in `lowlight-plugin.ts`.

**Steps to reproduce the bug**
* Use the environment as described in this issue
* Create a new code block in the editor
* Watch the editor crash with the above error
* **Note:** the issue only seems to arise when lowlight is explicitly installed in the project.

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:

* React: [this sandbox](https://codesandbox.io/s/tiptap-lowlight-bug-d7z0c?file=/src/TipTap.tsx)

**Expected behavior**
I expect the editor not to crash when creating a (lowlight) code block

**Environment?**
 - operating system: Windows 10
 - browser: Chrome
 - mobile/desktop: Desktop
 - tiptap version: 2.0.0-beta.60
 - lowlight: 1.20.0

**Comment by philippkuehn** [comment]
It’s because we updated to lowlight v2. But this introduced new issues so I reverted the change.
