### ISSUE TITLE
Heading node type errors when inserting newline at the beginning

### ISSUE THREAD

**Issue by jamesopti** [ueberdosis/tiptap#1411]
**Description**
When a `Heading` node is positioned in the middle/end of a document, pressing Enter at the beginning of it's line causes an error.

<img width="1167" alt="Screen Shot 2021-06-03 at 1 37 10 PM" src="https://user-images.githubusercontent.com/3718812/120708737-ce36a100-c470-11eb-9fcb-3349f59133b6.png">

**Steps to reproduce the bug**
1. Go to https://codesandbox.io/s/simplest-tiptap-issue-knscq?file=/src/App.tsx
2. Put your cursor at the beginning of `Heading`
3. Hit enter twice
4. See error message

**Expected behavior**
The `Heading` content is moved down.

**Additional context**
We noticed this issue with StarterKit v70 as well.

**Comment by philippkuehn** [comment]
It seems like this is an issue with ProseMirror itself. Created an issue there: https://github.com/ProseMirror/prosemirror/issues/1179
