### ISSUE TITLE
JetBrainsMono font transforms `!=` in a confusing way

### ISSUE THREAD

**Issue by shadow-light** [ueberdosis/tiptap#1412]
**Part of the documentation?**
I’ve read the following page of the documentation
https://www.tiptap.dev/api/extensions/typography

**Hard to understand, missing or misleading**
In the typography docs it is explaining how different character sequences get transformed. The font used on the page is `JetBrainsMono` which appears to itself transform `!=` into `≠` such that the explanation on the page becomes meaningless because `!=` is not itself displayed.

**Additional context**

![image](https://user-images.githubusercontent.com/42055707/120739033-339f9600-c534-11eb-931e-f44761ab6768.png)

Disable the font in dev tools to see the difference.

**Comment by philippkuehn** [comment]
Good catch! Should be fixed now.
