### ISSUE TITLE
Update attributes when non-editable

### ISSUE THREAD

**Issue by Winexcel** [ueberdosis/tiptap#1415]
I wrote my own spoiler extension, it works like a charm, but when I set my editor to non-editable, my spoiler doesn't work, button which update "show" attribute doesn't work.

I set editor to non-editable mode like this:
this.editor.setEditable(false);

My spoiler works very easy, I just update "show" attribute when click by the button.

Is it possible to update attributes and react to DOM events in non-editable mode?

**Comment by Winexcel** [comment]
I add a github repo for this problem, i solved this by replacing show attribute, i just duplicate show in my component and toogle this data property, but i also dispatch this property to tiptap. https://github.com/Winexcel/tiptap-spoiler

I think this approach might be bad, therefore i need some feedback from core team about this problem.

**Comment by Winexcel** [comment]
And another problem which i have with this approach - i can't nested one spoiler to another, i don't know why it doesn't work, but if i set content with nested spoilers - it works! Magic!)

![image](https://user-images.githubusercontent.com/18466364/120927699-faba1980-c70b-11eb-83a6-b64c6409abdf.png)

Why i can't add spoiler into another from commands?

**Comment by philippkuehn** [comment]
As discussed in https://github.com/ueberdosis/tiptap/issues/1239 I also removed the `editable` check in `updateAttributes`.
