### ISSUE TITLE
ListItem and TaskItem components not rendering correctly when used together

### ISSUE THREAD

**Issue by christopher4lis** [ueberdosis/tiptap#1417]
**Description**
Importing both the ListItem and TaskItem components at the same time causes one list item to render as a bulleted list, with the second to render as a task item, even though both should be rendered as a task item with the following HTML:

    <ul data-type="task_list">
          <li data-type="taskItem" data-checked="true">A list item</li>
          <li data-type="taskItem" data-checked="false">And another one</li>
    </ul>

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:

* Vue: https://codesandbox.io/s/tiptap-issue-template-forked-x062y?file=/src/components/Tiptap.vue:673-862

**Steps to reproduce the bug**
1. Bug appears by default in sandbox
2. Remove the ListItem and BulletedList components and the task items will render correctly

**Comment by philippkuehn** [comment]
This was an issue in the docs. You have to use `data-type="taskList"`  instead of `data-type="task_list"`.

**Comment by christopher4lis** [comment]
Solved for now by creating a custom TaskItem with the attribute inserted by default:

    const CustomTaskItem = TaskItem.extend({
      addAttributes() {
        return {
          ...this.parent?.(),
          'data-type': {
            default: 'taskItem'
          }
        }
      }
    })

**Comment by philippkuehn** [comment]
No, it’s not an issue at all because task items are rendered as a node view: https://github.com/ueberdosis/tiptap/blob/dcc1093db412efd4c63610fe7344173b1740efd0/packages/extension-task-item/src/task-item.ts#L73-L145

When exporting HTML with `editor.getHTML()` the `data-type="taskItem"` prop should exist.
