### ISSUE TITLE
Bug with TextAlign not inheriting defaultOptions of types

### ISSUE THREAD

**Issue by acidjazz** [ueberdosis/tiptap#1430]
I'm not sure why this an issue but text alignment has never worked for us in v2, I finally did some messing with the extension and got it to work by specifying the types:

```ts
TextAlign.configure({
  types: ['paragraph', 'heading'],
})
```

I saw these were already in the defaultOptions so I don't know why this fixes our issue, are the options somehow dynamically decided?

**Comment by philippkuehn** [comment]
Can you create a reproducable demo please because text align is working fine here: https://www.tiptap.dev/api/extensions/text-align/#textalign

**Comment by sh-winter** [comment]
> 您能否创建一个可重现的演示，因为文本对齐在这里工作正常：[https](https://www.tiptap.dev/api/extensions/text-align/#textalign) : [//www.tiptap.dev/api/extensions/text-align/#textalign](https://www.tiptap.dev/api/extensions/text-align/#textalign)

In this example, heading can adjust the alignment normally, but paragraph can't

**Comment by hanspagel** [comment]
@philippkuehn Tests fail too. ✌️

**Comment by philippkuehn** [comment]
@sh-winter @hanspagel oh no. but this bug was introduced by this fix yesterday https://github.com/ueberdosis/tiptap/commit/ddb9a4bf186b766477f21102dae6eb1299ea425a

**Comment by philippkuehn** [comment]
There are no default types for TextAlign extension anymore. You have to configure them by yourself. Usually something like:

```js
TextAlign.configure({
  types: ['heading', 'paragraph'],
})
```
