### ISSUE TITLE
Not able to see or update custom attributes in custom node and nodeviewcontent

### ISSUE THREAD

**Issue by arunjoseph** [ueberdosis/tiptap#1431]
**Description**
I am trying to create a custom node, and I have achieved one in the following sandboxcod, but in the following code the blockId is not generating a new ID rather same id is being used in next items also, need help in the same and also when using ReactNodeViewRenderer I am not able to see any custom attributes. How does it work, can anyone please help

**Steps to reproduce the bug**
- N/A

**CodeSandbox**
I have created a CodeSandbox to help you debug the issue:

* React: https://codesandbox.io/s/lucid-clarke-v52l8

**Expected behaviour**
- Should be able to see attributes in the DOM
- Should be able update attribute items for each item processed

**Screenshot, video, or GIF**

**Environment?**
 - operating system: Macintosh; Intel Mac OS X 10_15_7
 - browser: Chrome
 - mobile/desktop: Desktop
 - tiptap version: ^2.0.0-beta.80

**Comment by philippkuehn** [comment]
DOM attributes are not added to node views by default. You have to do this by yourself if I want to (but you probably really won't need it).

But your attributes are stored in the `node.attrs` so your code of adding a `blockId` is working fine. You can see your id with something like this:

```jsx
const MeetingItemView = (props) => (
  <NodeViewWrapper className="draggable-item">
    <div
      className="drag-handle"
      contentEditable={false}
      draggable={true}
      data-drag-handle={true}
    />
    id: {props.node.attrs.blockId}
    <NodeViewContent className="content" />
  </NodeViewWrapper>
);
```

**Comment by arunjoseph** [comment]
@philippkuehn ok that solves the view but what about the unique id for every item created? Same id is getting generated for all the nodes

**Comment by philippkuehn** [comment]
There is a `keepOnSplit` option for attributes.

```js
addAttributes() {
    return {
      blockId: {
        default: null,
        keepOnSplit: false,
      },
    };
  },
```

But this handles only the case when splitting items (pressing enter) at the end of the line. If you split in the middle of an item, both items will keep the same id.

But I’m working on a unique id extension which will handle all these edge cases (split, copy, cut, paste, move): https://github.com/ueberdosis/tiptap/issues/1041

**Comment by arunjoseph** [comment]
@philippkuehn thank you so very much for your help and I appreciate it and also thanks a lot for helping me with a issue id as it solved my requirement.

Thanks again
