### ISSUE TITLE
Clicking twice on floating menu prevents it from hiding when focus lost

### ISSUE THREAD

**Issue by shadow-light** [ueberdosis/tiptap#1433]
**Description**
The floating menu can be stuck in some cases where it stays visible even when the editor is no longer focused. This is especially problematic when using Placeholder as they overlap each other.

**Steps to reproduce the bug**
1. Go to https://codesandbox.io/s/tiptap-issue-template-b83rr?file=/src/components/Tiptap.vue
2. Click on an empty line so that floating menu appears
3. Click on the floating menu again and then click outside the editor
4. See that floating menu is still visible after editor loses focus

**CodeSandbox**
I created a CodeSandbox to help you debug the issue [default sandbox already shows it]:

* Vue: https://codesandbox.io/s/tiptap-issue-template-b83rr?file=/src/components/Tiptap.vue

**Expected behavior**
Floating menu should disappear whenever editor loses focus, in all situations

**Screenshot, video, or GIF**
![image](https://user-images.githubusercontent.com/42055707/121174829-b2cafc00-c89d-11eb-8d58-f741a7ecc435.png)
An example that shows placeholder and floating menu overlapping when editor is not focused.

**Environment?**
 - operating system: Ubuntu
 - browser: Chrome 91
 - mobile/desktop: Desktop
 - tiptap version: 2.0.0-beta.75

**Additional context**
n/a

**Comment by shadow-light** [comment]
I suspect it has to do with this: https://github.com/ueberdosis/tiptap/blob/7387eaf51b71a435c039a57e66e2e1a6da887ef2/packages/extension-floating-menu/src/floating-menu-plugin.ts#L44

**Comment by shadow-light** [comment]
Related to this, I was having a problem with the floating menu receiving focus, as I have some non-button text in the floating menu. So when the text (within the floating menu) is clicked it gets focus and then the user can't enter any actual text into the editor. I solved this by focusing the editor whenever that text is clicked, via:

`<floating-menu @click.native='editor.commands.focus()'>`

This also then solved the above issue. Because the floating menu will no longer receive focus (as when clicked it focuses the editor instead) then it no longer becomes stuck when focusing something else on the page.

**Comment by shadow-light** [comment]
So maybe my workaround above should be integrated into the default TipTap FloatingMenu components for Vue and React?

**Comment by theazgra** [comment]
@shadow-light  Your solution saved me! Thanks a lot. It seems, that this wasn't merged to tiptap afterall. I am using version 2.1.12 in Nuxt (Vue2) project.

**Comment by ValJed** [comment]
Hello, I can confirm this "bug" still exists, your solution @shadow-light is handy but doesn't covert all cases, for example it won't work properly when using a select in the bubble menu (that will close itself immediately when opened).

If someone could say why this behavior exists, is it necessary, is it something we can try to fix?

Thanks!

**Comment by Chrys-code** [comment]
We found that the Bubble toolbar extension overrides the default Tippy settings. The Tippy options has a prop called `hideOnClick` which is set to `toggle` by Bubble toolbar. 

Our issue was that having an input field in the toolbar that has received a double click from the users would make the toolbar stay in place even if the focus was set to something else than the editor.

Changing `hideOnClick` to `true` solved this issue for us.

`<BubbleMenu editor={editor} tippyOptions={{ hideOnClick: true }}>`
