### ISSUE TITLE
Autocomplete block level menu

### ISSUE THREAD

**Issue by holtwick** [ueberdosis/tiptap#144]
The following feature request is probably behind the scope of TipTap, but since it is Christmas ante portas I'll submit it anyway ;)

In [notion.so](https://www.notion.so) and [nuclino](https://nuclino.com) (the later uses Prosemirror too) it is possible to type ahead to apply a block style to a fresh (thus empty) paragraph by typing `/`.

This is a GIF animation showing the feature:
![2018-12-21 16_05_43](https://user-images.githubusercontent.com/49557/50348862-4c6d8a00-053a-11e9-868d-7cf2672ef9fa.gif)

**Comment by philippkuehn** [comment]
In v2 there is an [experiment for this](https://www.tiptap.dev/experiments/commands) so I’m closing this.
