### ISSUE TITLE
Missing mention when get plain text

### ISSUE THREAD

**Issue by sessionboy** [ueberdosis/tiptap#1442]
**Description**
I tried the official mention example.
I need to save plain text instead of json or html. I tried the following methods to get the plain text content:
```js
const text = editor.state.doc.textContent;
console.log(text);
```
But it does not contain mention, the mention is missing.

```js
// input
hello，@Alyssa Milano 

// output
hello，
```
Is there any other way to get the plain text accurately ?

**Comment by shadow-light** [comment]
Duplicate of https://github.com/ueberdosis/tiptap/issues/1336

**Comment by hanspagel** [comment]
Thanks to both of you! Yes, we’ll follow up in the other issue. ✌️
