### ISSUE TITLE
Bubble menu should hide during drag

### ISSUE THREAD

**Issue by shadow-light** [ueberdosis/tiptap#1443]
**Description**
When dragging text the bubble menu is still visible and prevents dragging text to areas under the bubble menu.

**Steps to reproduce the bug**
1. Go to: https://www.tiptap.dev/examples/menus/
2. Select some text (bubble menu shows up)
3. Try to drag text to a place where the bubble menu is

**CodeSandbox**
Evident in the menu example: https://www.tiptap.dev/examples/menus/

**Expected behavior**
The bubble menu should hide during drag.

**Screenshot, video, or GIF**
The dragged text doesn't show during screen capture, but you can see the menu is still visible during drag.
![image](https://user-images.githubusercontent.com/42055707/121442324-c1650080-c9ce-11eb-9716-645e085fc196.png)

**Environment?**
 - operating system: Ubuntu
 - browser: Chrome 91
 - mobile/desktop: Desktop
 - tiptap version: 2.0.0-beta.75

**Additional context**
n/a

**Comment by chshouyu** [comment]
+1, and there is a demo from dropbox paper

![2021-06-10 15 48 24](https://user-images.githubusercontent.com/1304342/121486223-87fab800-ca03-11eb-9b68-9d1f913dcb42.gif)
