### ISSUE TITLE
BubbleMenu should show when selected an atom node

### ISSUE THREAD

**Issue by DanSnow** [ueberdosis/tiptap#1446]
**Description**
When select on an atom node, the bubble menu won't display if there is no other text in editor

I believe that this is cause by the follow line in`bubble-menu-plugin`:
https://github.com/ueberdosis/tiptap/blob/main/packages/extension-bubble-menu/src/bubble-menu-plugin.ts#L100

Here try to prevent from showing bubble menu on empty paragraph with `!$anchor.parent.textContent`. When select on an atom node, the selection will become a node selection and the parent is not the node itself (it's doc in the below example, so the menu will popup when there is some texts).

**Possible fixes**
Only check for the `textContent` when `$anchor.parent.isTextblock` is `true`

**Steps to reproduce the bug**
1. Open the below sandbox
2. Try to select the atom node and see the bubble menu won't show
3. Type some text in anywhere in the editor
4. Try to select the atom node again and the bubble menu will show

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:
https://codesandbox.io/s/1f8z7

**Expected behavior**
The bubble menu should show whenever there is any text in the editor

**Screenshot, video, or GIF**
https://user-images.githubusercontent.com/5575082/121491353-72d45800-ca08-11eb-839b-4947fcfac6d6.mp4

**Environment?**
 - operating system: Linux
 - browser: Chrome 91
 - mobile/desktop: Desktop
 - tiptap version: 2.0.0-beta.81

**Comment by DannyFeliz** [comment]
I'm having this issue too :/
