### ISSUE TITLE
Lazy Load Extension Solution

### ISSUE THREAD

**Issue by FauconFan** [ueberdosis/tiptap#1447]
I am currently using tiptap in my company, and I have facing one simple issue.
In some of my pages, I could have tens of different tiptap editors loaded. 
I am searching a solution to lazy load all extensions, but I didn't find anything useful in the documentation or in the issues.

So I came to this nodejs solution: 

```javascript
[...]
mounted: function () {
  Promise.all([
    import('@tiptap/extension-document'),
    import('@tiptap/extension-bold'),
    import('@tiptap/extension-italic'),
    import('@tiptap/extension-underline'),
    import('@tiptap/extension-strike'),
    import('@tiptap/extension-paragraph'),
    import('@tiptap/extension-text'),
    import('@tiptap/extension-heading'),
    import('@tiptap/extension-list-item'),
    import('@tiptap/extension-bullet-list'),
    import('@tiptap/extension-ordered-list'),
    import('@tiptap/extension-code-block'),
    import('@tiptap/extension-blockquote'),
    import('@tiptap/extension-history'),
    import('@tiptap/extension-text-align'),
    import('@tiptap/extension-typography')
  ])
    .then((modules) => {
      const extensions = modules.map(m => {
        const extension = m.default
        if (extension.name === 'heading') {
          return extension.configure({ level: [1, 2, 3, 4] })
        }
        return extension
      })
      this.editor = new Editor({
        content: '',
        extensions: extensions
      })
    })
)
[...]
```

I don't know if lazy load is planned for the next release of tiptap, but this solution may be used in the documentation as a temporary solution.

Just sharing :)

**Comment by FauconFan** [comment]
If someone wants to use this solution, there are some issues when you're rerendering your component... What I did is storing my extensions in my data, and watching change to finally create the Editor object.

**Comment by hanspagel** [comment]
Thanks for sharing!
