### ISSUE TITLE
ignoreMutation and atom nodes

### ISSUE THREAD

**Issue by YousefED** [ueberdosis/tiptap#1448]
I'm not (yet) an expert on prosemirror and how atom / leaf nodes work, but I noticed the following line in TipTap:

https://github.com/ueberdosis/tiptap/blob/main/packages/core/src/NodeView.ts#L186

```
// a leaf/atom node is like a black box for ProseMirror    
// and should be fully handled by the node view    
if (this.node.isLeaf) {      return true    }
```

Based on the comments, it seems unexpected for me that you only check for `isLeaf`, and not whether the node is an atom.

**Comment by philippkuehn** [comment]
as far as I know `isLeaf` is always true for atom nodes.

**Comment by YousefED** [comment]
From prosemirror docs:

> isAtom: bool
> True when this is an atom, i.e. when it does not have directly editable content. This is usually the same as isLeaf, but can be configured with the leaf property on a node's spec (typically when the node is displayed as an uneditable node view).

Though not super explicit, I'm fairly sure you can define a nodeview with content (which would make it not a leaf), but define it as atom (to indicate PM should not handle editing)

**Comment by YousefED** [comment]
This confirms it's possible (@philippkuehn ):

![image](https://user-images.githubusercontent.com/368857/121557022-ae751f00-ca14-11eb-99b6-dd8b652f5082.png)

**Comment by philippkuehn** [comment]
Hmm you are right. But I’m still not sure about a use case for this configuration? 🤔

**Comment by YousefED** [comment]
@philippkuehn this is a relevant example:

https://prosemirror.net/examples/codemirror/

Let's say you want to embed an editor (could also be a textarea) inside tiptap. You want to store the editor contents in the tiptap document, but want to handle interactions yourself (or in the above example, by codemirror. In that case the element should be an atom (it should be opaque to tiptap / prosemirror), but not a leaf (it should be capable of containing text contents)

**Comment by philippkuehn** [comment]
Ah makes totally sense! Fixed it.

**Comment by YousefED** [comment]
> Ah makes totally sense! Fixed it.

Cool. Just to be clear; I based my feedback on your original comment in the code, which indicated it seemed erroneous. I don't know whether there are any real-life bugs that are prevented by this, for this I don't know enough about how `ignoreMutation` works. Although I'm working on a project which has a scenario similar to the codemirror-in-prosemirror example, I did not (yet) run into an issue that was caused exactly by this.

Do you know what ignoreMutation actually prevents from happening on the PM side when it returns true?

**Comment by philippkuehn** [comment]
`ignoreMutation` is a handler to decide if ProseMirror should re-render the node on any DOM mutations by itself. Like changes on node attributes or node content. For node views you probably don’t want to re-render the node for these kind of changes.
