### ISSUE TITLE
extension-heading & BulletList doesn't work with vue3

### ISSUE THREAD

**Issue by czarkom** [ueberdosis/tiptap#1455]
**Description**
After installing and importing extension-heading to my editor I discovered it's fine with adding < h1> (etc.) tags to my string (bound by v-model) but I can't see any effect in my editor. Same issue with BulletList

**Screenshot, video, or GIF**
![obraz](https://user-images.githubusercontent.com/45783529/121668382-85ec3400-caab-11eb-9255-245a0d4a8481.png)
Text after "Tytuł szablonu" is representing my model value which is bound to editor (we can see < h1> tags, but without any effect in editor)

**Environment?**
 - operating system: Windows 10
 - browser: Firefox/Chrome
 - tiptap version: v2
 - Vue version: 3

**JS Fiddle link to my tiptap component snippet**
https://jsfiddle.net/ekb9ysdg/1/

**Comment by philippkuehn** [comment]
I can't reproduce this because your fiddle demos seems to be broken.
