### ISSUE TITLE
Maybe mention milkdown in the document's markdown section?

### ISSUE THREAD

**Issue by Saul-Mirone** [ueberdosis/tiptap#1456]
**Part of the documentation?**
I’ve read the following page of the documentation …

https://www.tiptap.dev/guide/output/#not-an-option-markdown

**Really helpful parts**
I think this part is really good: …

You make a very good point about why tiptap don't support markdown.

**Hard to understand, missing or misleading**
But you really need to improve …

I think the [milkdown](https://saul-mirone.github.io/milkdown/) editor is a really good supplement about markdown part. Could you please consider mention it in the document? 

**Additional context**
Add any other context or screenshots here.

- [Milkdown Editor](https://saul-mirone.github.io/milkdown/)

**Comment by hanspagel** [comment]
Thanks, Milkdown looks amazing! I only recommend things I’ve used in a project though. 

Also I don’t see it as our job to recommend other editors and fear to open that door. Other teams already reached out wanting to pay us for placing recommendations to their editors.

Keep up the good work though!
