### ISSUE TITLE
Suggestions depend on caret position

### ISSUE THREAD

**Issue by gambolputty** [ueberdosis/tiptap#1458]
**Description**
Not sure if a bug, but possibly non-intended/strange behaviour:
When moving the caret inside a suggestion node, the Suggestion utility is not taking the entire string into account when querying for entries. Instead, the search query is changing according to the caret position.

**Steps to reproduce the bug**
1. Go to the [Docs page for "Mention"](https://www.tiptap.dev/api/nodes/mention)
2. Type in '@mad'.
3. Move the caret to the left.
4. The suggested items change based on the caret position.

**Expected behavior**
The suggested items should be the same, independent from caret position.

**Screenshot, video, or GIF**

https://user-images.githubusercontent.com/8270488/121780260-d6dd5480-cb9f-11eb-8f86-5bbb06a9745a.mov

**Environment?**
 - operating system: macOS, latest
 - browser: Chrome, latest
 - mobile/desktop: Desktop
 - tiptap version: latest

**Comment by philippkuehn** [comment]
This is intended and helps to insert mentions between existing text.

https://user-images.githubusercontent.com/2500670/121894474-770db780-cd1f-11eb-8d03-7484a74e86bb.mov
