### ISSUE TITLE
Editor selectionUpdate event fires when another user moves their cursor (via CollaborationCursor)

### ISSUE THREAD

**Issue by jamesopti** [ueberdosis/tiptap#1461]
**Description**
When using the CollaborationCursor extension, the `selectionUpdate` event fires when another user is moving their cursor around in the doc.

```ts
editor.on('selectionUpdate', () => {
  // This will fire if another user clicks around the doc in their own browser 
})
```

**Steps to reproduce the bug**
1. Setup the basic CollaborationCursor demo
2. Add a listener for `editor.on('selectionUpdate', onSelectionUpdate)`
3. Open 2 browsers and click around in 1
4. Observe both clients firing the event handler

**Expected behavior**
While it may technically be true that the selection is changing, it would be nice to know if the event is firing due to this client or another.

Suggested API - If there is a notion of this client's id, passing that along would allow filtering. Otherwise, just `isThisClient` would suffice

`editor.on('selectionUpdate', ({ editor, clientId or isThisClient }) => ...)`

**Additional context**

**Comment by philippkuehn** [comment]
I’ve added the current `transaction` to the `selectionUpdate` event so you can check for remote changes now.

```js
import { ySyncPluginKey } from 'y-prosemirror'

new Editor({
  onSelectionUpdate: ({ transaction }) => {
    // ignore changes made by y.js
    if (transaction.getMeta(ySyncPluginKey)) {
      return
    }

    console.log('selection update')
  }
})
```
