### ISSUE TITLE
maxthon browser 

### ISSUE THREAD

**Issue by glavdir** [ueberdosis/tiptap#1466]
**Description**
tiptap2 not worked in maxthon browser

**Environment?**
 - operating system:
 - browser: maxthon 5
 - tiptap version: 2

**Comment by hanspagel** [comment]
Thanks for reporting. It’s working in all major browsers, I don’t see us to extend the support to other browsers that seem to not adhere to standards. Or at least that’s what I have to assume without seeing an error message.
