### ISSUE TITLE
On android mobile, the second mention @ on the same line is not triggering the suggestions

### ISSUE THREAD

**Issue by aizaiz** [ueberdosis/tiptap#1468]
**Description**
On android mobile, the second mention @ on the same line is not triggering the suggestions

**Steps to reproduce the bug**
1. Go to https://www.tiptap.dev/examples/suggestions/
2. Type in the first mention "@"
3. Then type in another mention "@" on the same line. must be on the same line without dot separation or new line
4. The suggestions is not triggered, only after added a space, then backspace it triggered the suggestions again

**Expected behavior**
The suggestions should be triggered like the one in desktop

**Screenshot, video, or GIF**

https://user-images.githubusercontent.com/33613919/121909605-c1e6f980-cd36-11eb-9472-7a17b4d8870c.mp4

**Environment?**
 - operating system: Android version 9
 - mobile/desktop: Chrome mobile
 - tiptap version: tiptap 2

**Comment by veesahni** [comment]
I can reproduce this in up to date Android 11 / Chrome.
