### ISSUE TITLE
Documentation for upgrading custom extensions could be improved

### ISSUE THREAD

**Issue by arthurmcgregor** [ueberdosis/tiptap#1472]
**Part of the documentation?**
I’ve read the following page of the documentation …
https://www.tiptap.dev/overview/upgrade-guide which linked to:
https://www.tiptap.dev/guide/custom-extensions
https://www.tiptap.dev/guide/node-views
https://www.tiptap.dev/guide/node-views/vue

**Really helpful parts**
The upgrade guide was useful and most things were obvious and straightforward :-D (the new version + docs are awesome btw!)

**Hard to understand, missing or misleading**
The thing I struggled with was converting my custom extensions to use the new API. Although the upgrade-guide redirects to the custom-extension page, it took me a long time to realise how to map my old extension to the new API, especially regarding getting/setting attributes and converting parseDOM and toDOM to their new equivalents. It would be useful adding some more guidance to the upgrade guide. 

Perhaps the following? (Although I could have misunderstood things! And this might be quite specific to my upgrade use case....)

> - `parseDOM` and `toDOM` functions have been replaced with the `parseHTML` and `renderHTML` functions
> - `addAttributes()` is used to define the attributes and will also get/set them automatically (unless you want custom attribute names - see below)
>     - `HTMLAttributes` is available inside `renderHTML` so no need to get every attribute explicitly from `node.attrs` like before
>     - `addAttributes` will get the attributes from the html automatically, so no need to have `getAttrs` from the `parseDOM`
>     - If you want to have custom attribute names in the html, you can set `parseHTML` and/or `renderHTML` functions on each attribute individually

**Additional context**
This was my v1 iframe extension
```js
import { Node } from 'tiptap'
import TipTapIframe from './IframeNodeView'

export default class Iframe extends Node {
  get name () {
    return 'iframe'
  }

  get schema () {
    return {
      attrs: {
        src: {
          default: null,
        },
      },
      group: 'block',
      selectable: false,
      parseDOM: [{
        tag: 'iframe',
        getAttrs: dom => ({
          src: dom.getAttribute('src'),
        }),
      }],
      toDOM: node => ['iframe', {
        src: node.attrs.src,
        frameborder: 0,
        allowfullscreen: 'true',
      }],
    }
  }

  commands ({ type }) {
    return attrs => (state, dispatch) => {
      const { selection } = state
      const position = selection.$cursor ? selection.$cursor.pos : selection.$to.pos
      const node = type.create(attrs)
      const transaction = state.tr.insert(position, node)
      dispatch(transaction)
    }
  }

  get view () {
    return TipTapIframe
  }
}
```

and here is my v2 iframe extension - similar to the iframe experiment
```js
import { VueNodeViewRenderer } from '@tiptap/vue-2'
import { Node } from '@tiptap/core'
import IframeNodeView from './IframeNodeView'

export default Node.create({
  name: 'iframe',
  group: 'block',
  atom: true,

  addAttributes () {
    return {
      src: {
        default: null,
      },
    }
  },

  parseHTML () {
    return [{
      tag: 'iframe',
    }]
  },

  renderHTML ({ HTMLAttributes }) {
    return ['iframe', HTMLAttributes]
  },

  addCommands () {
    return {
      setIframe: (options) => ({ tr, dispatch }) => {
        const { selection } = tr
        const node = this.type.create(options)

        if (dispatch) {
          tr.replaceRangeWith(selection.from, selection.to, node)
        }

        return true
      },
    }
  },

  addNodeView () {
    return VueNodeViewRenderer(IframeNodeView)
  },
})
```

**Comment by philippkuehn** [comment]
Closing this because most users are using v2 now.
