### ISSUE TITLE
Bubble menu does not appear when selection starts from empty paragraph node

### ISSUE THREAD

**Issue by atulmy** [ueberdosis/tiptap#1474]
**Description**
Bubble menu does not appear when selection starts from empty paragraph node

**Steps to reproduce the bug**
1. https://www.tiptap.dev/api/extensions/bubble-menu
2. Press enter after default text
3. Start selection from bottom empty paragraph and select all text by dragging
4. Bubble menu won't appear

**Expected behavior**
Bubble menu should open when there are nodes selected with some content in it.

**Screenshot, video, or GIF**
Video:
https://user-images.githubusercontent.com/685786/122056545-4dc85680-ce07-11eb-90d5-d655a7b32c4a.mov

**Comment by philippkuehn** [comment]
Oh no, this fix introduced this bug:
https://github.com/ueberdosis/tiptap/commit/a3a76507844cefc28111b9636c511ad9ef52ad28

**Comment by atulmy** [comment]
I think it was there before that fix as well. I was on older version (before 2.0.0-beta.83) and was still facing that issue.

**Comment by philippkuehn** [comment]
ah good to know!

**Comment by atulmy** [comment]
Thank you for swift response! 💪
