### ISSUE TITLE
Request: optional shouldShow parameter for FloatingMenu and BubbleMenu

### ISSUE THREAD

**Issue by thatsjonsense** [ueberdosis/tiptap#1480]
**The problem I am facing**
In both the FloatingMenu and BubbleMenu, I wish I could customize the logic for when the menu displays.

Two specific use cases:
- In BubbleMenu, I want to trigger even when the selection is empty if you click inside a link
- In FloatingMenu, I want to trigger at depth 2 instead of depth 1 because my schema is a document with multiple sections

**The solution I would like**
An optional `shouldShow` function I can pass in the options to these menus where I can write my own logic. This would be consumed in the `update` method of each plugin. If you don't provide your own, it would use the default. Ideally, you could also access the default method from your custom one to do an OR.

**Alternatives I have considered**
Right now I've forked both menus just to change 1 line of logic in each one, which means it's hard to stay up to date with future improvements.

bubble-menu-plugin:
```
    if (empty || isEmptyTextBlock) {
      // OUR CUSTOM LOGIC STARTS HERE
      const isLink = selection.$anchor
        .marks()
        .some((mark) => mark.type.name === 'link')
      if (!isLink) {
        this.hide()
        return
      }
      // END OUR CUSTOM LOGIC
    }
```

floating-menu-plugin:
```
const isRootDepth = $anchor.depth === 2 // Was 1
```

**Comment by philippkuehn** [comment]
Yes, this is something I want to add! Additionally it would be great to add multiple instances of the menus with different configuration.
