### ISSUE TITLE
Can't seem to set image alignment

### ISSUE THREAD

**Issue by Figments** [ueberdosis/tiptap#1481]
**Description**
I'm currently unable to set any alignment on images, and I don't quite know why.

**Expected behavior**
Highlighting an image and then selecting an alignment option should set the image's alignment.

**Screenshot, video, or GIF**

https://user-images.githubusercontent.com/2677783/122266872-1ef5c300-ce8f-11eb-9278-db50d6f2716d.mov

**Environment?**
 - operating system: macOS Big Sur 11.4
 - browser: Microsoft Edge
 - mobile/desktop: Desktop
 - tiptap version: v2.0.0-beta.81

**Additional context**
Moving the image between nodes works fine, it's just alignment that refuses to work.

**Comment by oliviermills** [comment]
Further to your issue:

`TextAlign` can be configure with 'image' but this doesn't solve it as TextAlign adds an e.g.,`text-align: center` style to the element which doesn't work on `img`.

```
TextAlign.configure({
          types: ['heading', 'paragraph', 'image'],
}),
```
Will generate a  `<img src="..." style="text-align:center;"...` which does nothing. One way would be to wrap the image in a `div` block which has the text-align:center to it but that doesn't feel right(?) and the parser seems to ignore `div` elements.

If you try and put the `img` in a `p` .. the parsed html will remove the image. Not sure why.

My dirty fix is to `updateAttributes('image', { style: 'display:flex;margin:auto' })` for centering the image, but I DO NOT RECOMMEND this as likely blows up any extension that uses the style. Idea anyone?

**Can anyone advise on the best way to handle images and alignment?**

**Comment by philippkuehn** [comment]
As the name suggests, the `TextAlign` extension only adds align for text. 

You can try to overwite the `renderHTML` method for images to add a wrapping element.

**Comment by filt3rek** [comment]
Hej,

Why don't use `inline : true` image's attribute and then use textAlign as for text ? I use that and it works fine.

**Comment by lizy0329** [comment]
```
Image.configure({
    inline: true,
}),
```
