### ISSUE TITLE
Node view is rendered differently inside and outside the editor

### ISSUE THREAD

**Issue by zsid** [ueberdosis/tiptap#1485]
**Description**
I would expect to see the same html inside and outside the editor when having an interactive node view - https://www.tiptap.dev/guide/node-views. Is the current implementation expected behaviour?

**Steps to reproduce the bug**
1. Open the console and inspect the htm in the editor and outside it. 

**CodeSandbox**

* React: https://codesandbox.io/s/autumn-morning-wbcne

**Expected behavior**
I would expect to see the same html both inside and outside the editor - i.e. `react-component` to be replaced by `<div class="react-rendered"> etc`

**Screenshot, video, or GIF**
![Screenshot 2021-06-17 at 10 32 28](https://user-images.githubusercontent.com/11786608/122352445-ce966800-cf57-11eb-87d2-074db3abfe60.png)

**Comment by philippkuehn** [comment]
this is expected and [described here](https://www.tiptap.dev/guide/node-views#markup). you can use `editor.view.dom.innerHTML` for getting the full HTML.
