### ISSUE TITLE
Highlight required extensions

### ISSUE THREAD

**Issue by khylias** [ueberdosis/tiptap#1486]
**Part of the documentation?**
I’ve read the following page of the documentation about extensions.

**Hard to understand, missing or misleading**
But you really need to improve required extensions for a working editor. After getting caught up on JS errors, I saw that extensions were required. But only by going to the page of the extension in question.
Why not add a tag in the left menu with the mention Required?

**Comment by philippkuehn** [comment]
*No* extension is really required. But for a classical editor, a document, a block node (classically paragraph) and text are needed and we provide some extensions for it. That’s why we added a minimal setup example here: https://www.tiptap.dev/examples/minimal

**Comment by khylias** [comment]
It's not really required but my minimal configuration with Bold, Italic, Strike, Underline and Text didn't work without Document extension.
I have seen the minimum configuration. But in the end, when I went to see the description of the Document, the extension is well noted as required. 
I just submit the feedback and the idea of highlighting this Required mention.

**Comment by philippkuehn** [comment]
Yeah I think we could maybe find a better wording in the docs for this issue @hanspagel.

**Comment by hanspagel** [comment]
Not really sure what to do. There are numerous places where I explain the importance.

For that case, a more meaningful error message would probably be more helpful than anything I can do in the docs. 🤔

**Comment by hanspagel** [comment]
@philippkuehn Do you think it’s feasible to output a console warning when a required extension is missing?

**Comment by philippkuehn** [comment]
We can throw something when there is no toplevel node (doc) or text node. But in both cases a ProseMirror error will be thrown anyway so I'm not sure if that helps.

**Comment by hanspagel** [comment]
Sorry, I talked about cases like a missing ListItem for the BulletList - forgot to mention this.

**Comment by philippkuehn** [comment]
Unfortunately this is currently not possible, because as soon as the extensions are loaded, the schema is also built and throws an error before I can search for missing extensions by myself. But I find that the ProseMirror error messages are currently enough, e.g.:

> SyntaxError: No node type or group 'listItem' found

Closing for now.
