### ISSUE TITLE
How to get the default text style without initializing TextStyle?

### ISSUE THREAD

**Issue by sh-winter** [ueberdosis/tiptap#1489]
### Discussed in https://github.com/ueberdosis/tiptap/discussions/1488

<div type='discussions-op-text'>

<sup>Originally posted by **sh-winter** June 18, 2021</sup>
The basic principle of TextStyle is to apply the style attribute to < span > elements. Before using this tag, how can I get the default text size of a piece of content?

Paragraphs also have font size, so can I apply the font size property to paragraphs to use the fontsize provided by paragraphs as the default value when fontsize mark is not used explicitly</div>

**Comment by hanspagel** [comment]
We don’t have a FontSize extension, but if you copied the FontFamily extension you can pass `types: ['paragraph']` to the extension.
