### ISSUE TITLE
improve UX on bubble menu when selecting text

### ISSUE THREAD

**Issue by michelson** [ueberdosis/tiptap#1493]
When users selects text on multiple lines the bubble menu gets repositioned on every selection change, this is not optimal because the bubble menu will jump because the selection will overlap the menu and jump around as the selection will be toggled (focus/blur). to illustrate:

https://user-images.githubusercontent.com/11976/122631079-cee94d00-d096-11eb-9d43-2a1dd4279cdc.mp4

In my implementation I've changed the behavior on how the mouseup should be handled, this will only reposition the menu when the user text selection stops

https://user-images.githubusercontent.com/11976/122631064-a5c8bc80-d096-11eb-80ec-47211410bdfd.mp4

 
Please check this behavior on medium or discord editor's bubble menu to check how it should work, also check my implementation https://www.dante-editor.dev/ 😄

the code changes of menu bubble on dante3 can be seen at https://github.com/michelson/Dante/blob/master/packages/dante3/src/popovers/bubble-menu/bubble-menu-extension/bubble-menu-plugin.ts

**Comment by michelson** [comment]
this is somewhat related with #1313

**Comment by sereneinserenade** [comment]
I don't know which event handler/function/method is changing the position of the bubble menu, but if the position is being changed when the selection is changed, could debouncing that function help in this case?

**Comment by robertvanhoesel** [comment]
I agree with this, had to work around it as well. See https://github.com/ueberdosis/tiptap/discussions/1522

Happy to implement this and make this my first PR if you see the merit. @hanspagel

**Comment by robertvanhoesel** [comment]
#1556

**Comment by charesbast** [comment]
Hello everyone,

Just found about that bug: the cause is that when the cursor comes inside the bubble, the focus modify text selection. You can try to set the property: `interactive: false` to tippy options of `BubbleMenu` component, the selection works well.
I've tried to update the `interactive` option with a local state but tippy does not update. Not sure if it's intended or if it's a bug. (I think it's a bug). 

**The best solution for me** would be to always display the bubble menu, but make it interactive (with `pointer-events`) only when `mouseup` event if fired (and text selection finished).

What do you think ? :)

**Comment by michelson** [comment]
it seems this is still an issue.

**Comment by bdbch** [comment]
Thanks @sereneinserenade for the idea. I created a pull request that implements a debounce on default (250ms) which is overwriteable (or deactivateable by setting the delay to 0).

**Comment by sereneinserenade** [comment]
@bdbch Glad to know my solution could be of help.

**Comment by tsl1127** [comment]
> Hello everyone,
> 
> Just found about that bug: the cause is that when the cursor comes inside the bubble, the focus modify text selection. You can try to set the property: `interactive: false` to tippy options of `BubbleMenu` component, the selection works well. I've tried to update the `interactive` option with a local state but tippy does not update. Not sure if it's intended or if it's a bug. (I think it's a bug).
> 
> **The best solution for me** would be to always display the bubble menu, but make it interactive (with `pointer-events`) only when `mouseup` event if fired (and text selection finished).
> 
> What do you think ? :)

i agree!  the bubble menu  display only when `mouseup` event
