### ISSUE TITLE
Bug with text highlighting tiptap v1/v2

### ISSUE THREAD

**Issue by Dinver** [ueberdosis/tiptap#1494]
**Description**
When highlighting a word and opening a menu, the entire paragraph is highlighted.

**Steps to reproduce the bug**
1. Mouse double left click 
2. Mouse right click 

**Current behavior**
v1
![demo_v1](https://user-images.githubusercontent.com/36528841/122636405-c5d99980-d0f1-11eb-8306-5a0d2243552e.gif)
v2
![demo_v2](https://user-images.githubusercontent.com/36528841/122636411-ce31d480-d0f1-11eb-9f7a-e2edeea64904.gif)

**Expected behavior**
![demo_normal](https://user-images.githubusercontent.com/36528841/122636382-acd0e880-d0f1-11eb-86ee-6322661721ea.gif)

**Screenshot, video, or GIF**

**Environment?**
Tested on multiple devices.
Windows 10 x64, FireFox 89.0.1 (64 bit),  Google Chrome 91.0.4472.106 (64 bit)

**Comment by pat-son** [comment]
Seems to only happen when right clicking immediately after the double left click, so there's probably some timeout in the selection code that isn't accounting for the difference between right and left click.

You can reproduce the issue by clicking left, then right, then left again in quick succession.

**Comment by philippkuehn** [comment]
Since this happens on https://prosemirror.net/ too, I don’t think I can do anything here. Please create an issue at ProseMirror if you think this is an issue.

**Comment by Dinver** [comment]
> Since this happens on https://prosemirror.net/ too, I don’t think I can do anything here. Please create an issue at ProseMirror if you think this is an issue.

Thanks for quick response. I created issuse:
https://github.com/ProseMirror/prosemirror/issues/1184
Problem should already be solved.

**Comment by philippkuehn** [comment]
Thanks! I've released a new tiptap version.
