### ISSUE TITLE
Svelte & tiptap-extension-code-block-lowlight: Cannot read property 'map' of undefined at parseNodes

### ISSUE THREAD

**Issue by thousandsofraccoons** [ueberdosis/tiptap#1495]
**Description**
I getting error during the initial setup with Svelte

**Steps to reproduce the bug**
https://github.com/thousandsofraccoons/svelte-tiptap-codeblock-lowlight

**Screenshot, video, or GIF**
![image](https://user-images.githubusercontent.com/33694447/122668546-746ef000-d16d-11eb-8f5e-3e50e8be3d1b.png)

**Comment by philippkuehn** [comment]
tiptap ist not compatible with lowlight v2. please use lowlight v1 for now.

**Comment by thousandsofraccoons** [comment]
@philippkuehn thank you, it did the trick. One question - is there any way to restrict language imports? Or gotta import all those languages?

**Comment by philippkuehn** [comment]
you can see that in our example.

**Comment by thousandsofraccoons** [comment]
@philippkuehn thank you, it works. Could you please help with one more question - how can I enable CodeblokLowligh on the fly, after the Editor is instantiated. I'd prefer to load `lowlight` asynchronously only if `codeblock` was added.

**Comment by philippkuehn** [comment]
I don’t think this is possible right now.

**Comment by thousandsofraccoons** [comment]
https://bundlephobia.com/package/@tiptap/extension-code-block-lowlight@2.0.0-beta.30

https://bundlephobia.com/package/highlight.js@11.0.1

@philippkuehn it could save quite a lot of loading time

**Comment by philippkuehn** [comment]
We can’t load lowlight asynchronously. Closing this.
