### ISSUE TITLE
Any way to retain styles/formats (color, font size, etc) on empty text content?

### ISSUE THREAD

**Issue by pat-son** [ueberdosis/tiptap#1501]
**The problem I am facing**
In our data model, we have text fields that can have an empty string as the text value, but still have styles saved for that field such as color, font family, etc. When the user clicks on the rich text area and starts typing, the text should have those saved formats already applied

**The solution I would like**
If I pass in empty content (e.g. `content: '<p"><strong></strong></p>'`), then when the user focuses the text field and starts typing, the text should be formatted (in this example, the text should already be bold)

**Alternatives I have considered**
We've considered inserting a zero-width space when the text is empty so it isn't ever "empty" as far as ProseMirror is concerned, but managing that is too much of a hassle (when to add the zero-width space, when to delete it, etc)

**Additional context**
Demo: https://stackblitz.com/edit/pson-tiptap-styles?file=index.ts

Given the initialization of
```ts
new Editor({
  element: document.querySelector('.element'),
  extensions: [
    StarterKit,
  ],
  content: '<p"><strong></strong></p>',
})
```
When the user starts typing in the text area, the text should be bold.

**Comment by philippkuehn** [comment]
This doesn’t seem to be supported by ProseMirror. So unfortunately we can’t do anything here.

**Comment by fantasticit** [comment]
How about using prosemirror.widget and zero--width-space?
