### ISSUE TITLE
Can I save undo and redo actions?

### ISSUE THREAD

**Issue by HeebeLee** [ueberdosis/tiptap#1502]
We want to save the user's editing behavior of the content so that users can undo or redo content in different documents at any time.

Is there any such interface and method available?

**Comment by ashutoshrishi** [comment]
Check out https://github.com/ProseMirror/prosemirror-history

**Comment by philippkuehn** [comment]
We are using the prosemirror history plugin and there is no such a feature right now. [There is a feature request for that](https://discuss.prosemirror.net/t/save-and-apply-reuse-history/2522) but I don’t think this will come anytime soon.
