### ISSUE TITLE
List Items causing error when loading in JSON content

### ISSUE THREAD

**Issue by vissr** [ueberdosis/tiptap#1504]
**Description**
When using Tiptap, apart from saving the HTML, i also save the JSON (taken from editor.getJSON()) so that users can easily edit the content without having issues parsing back HTML. Using Bullet Lists works fine in the either, and the content is also saved correctly. However, when loading the content back in in order to edit it, the console shows the following error:

`[tiptap warn]: Invalid content. Passed value: Object Error: RangeError: Unknown node type: list_item`

**Steps to reproduce the bug**
1. Use the BulletList in the Editor
2. Get the JSON output of the editor via editor.getJSON()
3. Clear the content or set the content via editor.commands.setContent(json)
4. The content stays completely empty
5. See error message

Not sure if related, but this is the JSON I get when I create a simple BulletList:

`{"type":"doc","content":[{"type":"bullet_list","content":[{"type":"list_item","content":[{"type":"paragraph","content":[{"type":"text","text":"sdf"}]}]},{"type":"list_item","content":[{"type":"paragraph","content":[{"type":"text","text":"sdf"}]}]},{"type":"list_item","content":[{"type":"paragraph","content":[{"type":"text","text":"sdf"}]}]},{"type":"list_item","content":[{"type":"paragraph","content":[{"type":"text","text":"sdf"}]}]},{"type":"list_item","content":[{"type":"paragraph","content":[{"type":"text","text":"sdf"}]}]},{"type":"list_item","content":[{"type":"paragraph","content":[{"type":"text","text":"sdf"}]}]}]}]}`

Configuring this code directly under "content" while initializing the editor gives the same error.
Note: I don't have this issue when setting content through the HTML methods.

**Code**
I'm using a Vue3 implementation.

```
<script>
import { Editor, EditorContent } from '@tiptap/vue-3'
import StarterKit from '@tiptap/starter-kit'
import Image from '@tiptap/extension-image'
import Link from '@tiptap/extension-link'
import Blockquote from '@tiptap/extension-blockquote'
import CodeBlock from '@tiptap/extension-code-block'
import BulletList from '@tiptap/extension-bullet-list'
import OrderedList from '@tiptap/extension-ordered-list'
import ListItem from '@tiptap/extension-list-item'

export default {
    components: {
        EditorContent
    },
    data() {
        return {
            editor: null,
            editor_active: false
        }
    },
    methods: {
        init() {
          if(!this.editor) {
              this.editor = new Editor({
                  content: '',
                  extensions: [
                      StarterKit,
                      Image,
                      Link,
                      Blockquote,
                      CodeBlock,
                      BulletList,
                      OrderedList,
                      ListItem
                  ],
                  autofocus: true,
                  preserveWhiteSpace: true,
                  height: 250
              });

              this.editor_active = true;
              this.$parent.composing = true;
          }
        }
        ......
    }
</script>
```

**Environment?**
 - operating system: OSX Catalina 10.15.7
 - browser: Google Chrome 91.0.4472.106
 - mobile/desktop: Desktop
 - tiptap version: 2.0.0-beta.85 (vue3 implementation)
 - tiptap/extension-list-item version: 2.0.0-beta.13
 - tiptap/extension-bullet-list version: 2.0.0-beta.14

**Comment by philippkuehn** [comment]
Your content seems to be outdated. Is that JSON from an older version of v2 or v1? In v2 we changes some type names. `bullet_list` should  be `bulletList` and `list_item` should  be `listItem` now.

**Comment by vissr** [comment]
> Your JSON content seems to be outdated. Is that JSON from an older version of v2 or v1? In v2 we changes some type names. `bullet_list` should be `bulletList` and `list_item` should be `listItem` now.

You are absolutely right. It wasn't JSON from an older version. In my backend I was converting them back to list_item. I think I might have implemented this while this was in transition to being changed in v2. At some point I think I was getting the errors the other way around. Doh!

**Comment by ralphschindler** [comment]
@philippkuehn do you have a document upgrade guide or similar? Or even a list of renamings?

I just ran into this issue and am wondering what other extensions had a renaming I have to look out for.
