### ISSUE TITLE
Multiple successive insertions of horizontal lines insert additional random nodes

### ISSUE THREAD

**Issue by sh-winter** [ueberdosis/tiptap#1505]
**Description**

Multiple successive insertions of horizontal lines insert additional random nodes.

**Steps to reproduce the bug**
1. Install and use @ tippap / extension horizontal rule extension
2. Call the sethorizontalrule command continuously at the end of the content
3. If you look at the editor, you will find that every time you insert a horizontal line at the end, a new paragraph will be attached. If you introduce other nodeview, you may attach it instead

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:

* https://codesandbox.io/s/tiptap-horizontal-line-bug-demo-n8gyi?file=/src/components/Editor/index.js

**Expected behavior**
No additional nodes are added

**Screenshot, video, or GIF**

**Environment?**
 - operating system: windows 10
 - browser: chrome 93
 - mobile/desktop: desktop
 - tiptap version: 2

**Additional context**
Vue3 + Vite2

**Comment by philippkuehn** [comment]
This is intended behavior and was introduced here: https://github.com/ueberdosis/tiptap/issues/1081

A paragraph is added after a hr if added at the end of the document because otherwise it’s not easily possible to add content after the hr. Adding multiple horizontal rules is not a common use case at all.

**Comment by sh-winter** [comment]
By looking at the source code, I found that the type of node inserted after the horizontal line is determined by tr.selection.$from.parent.type.contentMatch.defaultType, which leads to the return of non paragraph type in some cases

**Comment by sh-winter** [comment]
for example:
![image](https://user-images.githubusercontent.com/48613217/123221906-ff4f4200-d501-11eb-8e06-76839a6d8a1e.png)

**Comment by sh-winter** [comment]
By looking at the source code, I found that the type of node inserted after the horizontal line is determined by tr.selection.$from.parent.type.contentMatch.defaultType, which leads to the return of non paragraph type in some cases

**Comment by sh-winter** [comment]
for example:
![image](https://user-images.githubusercontent.com/48613217/123222086-2ad22c80-d502-11eb-9a3e-780de550acf1.png)

**Comment by philippkuehn** [comment]
yeah it should create the default block (which is a paragraph in most cases)

**Comment by philippkuehn** [comment]
is there an issue for you with calculating the default block? (can’t see that in your gif without knowing your schema)

**Comment by sh-winter** [comment]
this is a custom nodeViews
```js
export default Node.create({
  name: 'enclosure',
  defaultOptions: {
    HTMLAttributes: {},
  },
  inline: true,
  group: 'inline',
  draggable: true,
  addAttributes() {
    return {
      src: {
        default: null,
      },
      filename: {
        default: null,
      },
      fileSize: {
        default: null
      }
    }
  },
  parseHTML() {
    return [
      {
        tag: 'enclosure',
      },
    ]
  },
  renderHTML({ HTMLAttributes }) {
    return ['enclosure', mergeAttributes(this.options.HTMLAttributes, HTMLAttributes)]
  },
  addNodeView() {
    return VueNodeViewRenderer(Enclosure)
  },
})
```

**Comment by sh-winter** [comment]
The default type seems to be constantly changing

**Comment by lordinkavu** [comment]
Hello,
In my case I have extended the Document  schema to `"heading block+"`. This has resulted in a heading node being created after every `hr`. I can of course extend the horizontal rule module and change this behaviour. But isn't inserting a paragraph node a better default behaviour ?
