### ISSUE TITLE
Configuring html attributes for individual levels of Headings

### ISSUE THREAD

**Issue by jchan18** [ueberdosis/tiptap#1514]
**The problem I am facing**
When configuring the heading extension, it's only possible to add HTMLAttributes for headings overall making it impossible to configure individual the individual levels

**The solution I would like**
Returning a method that allows us to do something like this:
```js
StarterKit.configure({
  heading: {
    levels: [1, 2, 3],
    HTMLAttributes(node) {
      if (node.attrs.level === 1) {
        return {
          class: 'text-4xl font-bold text-gray-800'
        }
      }
      // ...
    }
  },
}),
```

**Comment by hanspagel** [comment]
I think that could be great solution.

While this is not supported, you can write that logic in the renderHTML function to have the same result.

**Comment by flaviouk** [comment]
That works, thanks @hanspagel, for reference:
```tsx
import BaseHeading from '@tiptap/extension-heading'
import { mergeAttributes } from '@tiptap/core'

type Levels = 1 | 2 | 3

const classes: Record<Levels, string> = {
  1: 'text-4xl',
  2: 'text-3xl',
  3: 'text-2xl',
}

export const Heading = BaseHeading.configure({ levels: [1, 2, 3] }).extend({
  renderHTML({ node, HTMLAttributes }) {
    const hasLevel = this.options.levels.includes(node.attrs.level)
    const level: Levels = hasLevel ? node.attrs.level : this.options.levels[0]

    return [
      `h${level}`,
      mergeAttributes(this.options.HTMLAttributes, HTMLAttributes, {
        class: `${classes[level]}`,
      }),
      0,
    ]
  },
})

```

**Comment by jarandmi** [comment]
This would also be great to to in the suggestion plugin, where renderHTML don't exist. I want to style the node based on the data of the select item.

**Comment by hanspagel** [comment]
It does exist there too:
https://github.com/ueberdosis/tiptap/blob/main/packages/extension-mention/src/mention.ts#L107-L116

Here is described how you can extend existing extensions:
https://www.tiptap.dev/guide/custom-extensions#extend-existing-extensions

**Comment by dospunk** [comment]
This would make working with Headings and tailwind together so much easier!

**Comment by ZarbaliyevOzal** [comment]
> That works, thanks @hanspagel, for reference:
> 
> ```tsx
> import BaseHeading from '@tiptap/extension-heading'
> import { mergeAttributes } from '@tiptap/core'
> 
> type Levels = 1 | 2 | 3
> 
> const classes: Record<Levels, string> = {
>   1: 'text-4xl',
>   2: 'text-3xl',
>   3: 'text-2xl',
> }
> 
> export const Heading = BaseHeading.configure({ levels: [1, 2, 3] }).extend({
>   renderHTML({ node, HTMLAttributes }) {
>     const hasLevel = this.options.levels.includes(node.attrs.level)
>     const level: Levels = hasLevel ? node.attrs.level : this.options.levels[0]
> 
>     return [
>       `h${level}`,
>       mergeAttributes(this.options.HTMLAttributes, HTMLAttributes, {
>         class: `${classes[level]}`,
>       }),
>       0,
>     ]
>   },
> })
> ```

I use it like this
```
<script setup>
import { useEditor, EditorContent } from '@tiptap/vue-3'
import StarterKit from '@tiptap/starter-kit'
import { ref } from 'vue'
import Heading from '@tiptap/extension-heading'
import { mergeAttributes } from '@tiptap/core'

const editor = useEditor({
  content: '',
  editorProps: {
    attributes: {
      class: 'prose prose-sm sm:prose lg:prose-lg xl:prose-2xl mx-auto focus:outline-none p-2 border border-gray-300 shadow-sm rounded-b-md h-32 overflow-y-auto',
    },
  },
  extensions: [
    StarterKit.configure({
      heading: false
    }),
    Heading.configure({ levels: [1, 2] }).extend({
      levels: [1, 2],
      renderHTML({ node, HTMLAttributes }) {
        const level = this.options.levels.includes(node.attrs.level) 
          ? node.attrs.level 
          : this.options.levels[0]
        const classes = {
          1: 'text-4xl',
          2: 'text-2xl',
        }
        return [
          `h${level}`,
          mergeAttributes(this.options.HTMLAttributes, HTMLAttributes, {
            class: `${classes[level]}`,
          }),
          0,
        ]
      },
    })
  ]
})
</script>
```

**Comment by upview** [comment]
This previous implementation was allowing other header sizes to be activated using markdown shortcuts. This change fixes that behavior (and typescript error) :

```
        Heading.extend({
          levels: [1, 2],
          renderHTML({ node, HTMLAttributes }) {
            const level = this.options.levels.includes(node.attrs.level)
              ? node.attrs.level
              : this.options.levels[0];
            const classes: { [index: number]: string } = {
              1: 'text-2xl',
              2: 'text-xl',
            };
            return [
              `h${level}`,
              mergeAttributes(this.options.HTMLAttributes, HTMLAttributes, {
                class: `${classes[level]}`,
              }),
              0,
            ];
          },
        }).configure({ levels: [1, 2] }),
```
