### ISSUE TITLE
Selection with dragging that drag event started from outside of editable area

### ISSUE THREAD

**Issue by softmarshmallow** [ueberdosis/tiptap#1517]
Dragging text & custom node with custom selection view.

https://user-images.githubusercontent.com/16307013/123632202-a0b3fc00-d852-11eb-8e0e-f66897900655.mov

1. we can currently modify the selection's view with custom component wrap.
2. we can't detect if the selection is started or the dragging cursor is in which position (x,y)
3. we can't tell if the target node is considered as "selected"

Another reference: editor.js - https://editorjs.io/

https://user-images.githubusercontent.com/16307013/123774738-ac61fa00-d908-11eb-82b1-9d13ac82b632.mov

**Comment by hanspagel** [comment]
Not really sure what you’re reporting or asking for, but an official extension that adds this behaviour is in the works. Will take some time though.
