### ISSUE TITLE
Pasting ignores certain text alignment styles

### ISSUE THREAD

**Issue by jelib3an** [ueberdosis/tiptap#1530]
**Description**
When pasting text, the first node is rendered with the default text alignment rather than what is set by the element style.

**Steps to reproduce the bug**
1. Use the text-align extension and configure it to work with paragraph type
2. Change the alignment to center
3. Type a few paragraphs (they will all be center aligned)
4. Copy the contents of the editor
5. Clear the editor contents
6. Set the current alignment to left
7. Paste the contents
8. Notice the first paragraph will be left aligned while the rest are center

**CodeSandbox**
https://codesandbox.io/s/text-align-pasting-bug-5sqr2?file=/src/components/Tiptap.vue

**Expected behavior**
The pasted content should match the formatting of the original copied content.

**Environment?**
 - browser: Chrome Version 91.0.4472.114 (Official Build) (64-bit)
 - mobile/desktop: Desktop
 - tiptap version:
   - @tiptap/core: 2.0.0-beta.82
   - @tiptap/extension-text-align: 2.0.0-beta.20

**Additional context**
I was able to workaround this by overriding the default paste handler on the editor. Since the extension parses the html correctly, it leads me to believe the issue not with the extension but with Prose or some paste handling logic somewhere.
```js
handlePaste: (view, event: ClipboardEvent) => {
  const html = event.clipboardData.getData('text/html');
  if (!html) {
    return false;
  }
  editor.commands.insertContent(html);
  return true;
},
```

**Comment by philippkuehn** [comment]
This works with the latest version.

**Comment by jelib3an** [comment]
@philippkuehn Sorry, but this still doesn't appear to be working. I updated the sandbox with the latest versions of core and the text-align extension. Would you please take a look to see if I'm missing anything? Thanks!

https://codesandbox.io/s/text-align-pasting-bug-forked-6j6cq5?file=/src/components/Tiptap.vue
