### ISSUE TITLE
Can't delete taskList content when content is selected all by cmd + a

### ISSUE THREAD

**Issue by chshouyu** [ueberdosis/tiptap#1531]
**Description**
If taskList is in the first line, select all content use keyboard cmd + a, and then hit delete, nothing happen. And the arrow key has no response too.
If taskList not in the first line, it will work.
But if you select all content by mouse, it will work too. It's so weird.

**CodeSandbox**
https://www.tiptap.dev/api/nodes/task-list

**Screenshot, video, or GIF**
![2021-07-01 03 00 28](https://user-images.githubusercontent.com/1304342/124016934-b7a44b00-da18-11eb-91ee-b97542868a19.gif)

**Environment?**
 - operating system: macOS Big Sur
 - browser: Chrome 91.0.4472.114
 - mobile/desktop: desktop
 - tiptap version: 
 "@tiptap/react": "^2.0.0-beta.52"
"@tiptap/extension-task-item": "^2.0.0-beta.16"
"@tiptap/extension-task-list": "^2.0.0-beta.16"

**Comment by philippkuehn** [comment]
This seems to be a browser bug when calculating the selection if there are some unselectable elements like checkboxes in your node. adding `user-select: none;` [helped](https://github.com/ueberdosis/tiptap/commit/31b269dd5aac8bfbd8078cb9772a02c3a77d74cb).
