### ISSUE TITLE
Caret not shown between two custom Nodes in Firefox but in Chrome

### ISSUE THREAD

**Issue by Aless55** [ueberdosis/tiptap#1533]
Hello everyone

I created a custom inline node to mimic the use of the "TAB" button in MS Word. I also used the key bind on the TAB key to insert the Node in my editors. So far so good, I am now pressing two times the TAB button, to get the following HTML structure in my code.

```html
<p>
<tab contenteditable="false"></tab>
<tab contenteditable="false"></tab>
</p>
```

This is the expected behavior as seen in latest Google Chrome:
![Image of Google Chrome Editor](https://i.ibb.co/crCKts2/Bildschirmfoto-von-2021-07-02-08-52-25.png)

It is hard to see because of the empty spaces, but the caret is between the two tabs. In Firefox I am unable to see the caret, but I am able to click between them. If I for example write some characters they appear at the right position. But it is very hard to tell if the right spot is chosen. Other things such as normal texts, links, headers are all working fine.

I reproduced a minimal example in this code sandbox. 

https://codesandbox.io/s/eloquent-jang-mwb4l?file=/src/components/HelloWorld.vue

I am using the latest Tiptap version vor Vue 2, latest Vue 2,  and am on Ubuntu 20.04 with latest Firefox and latest Chrome. I did not try other browsers, it might also (not) work somewhere else.

**Comment by philippkuehn** [comment]
Seems like a firefox bug so we can't do here anything. https://github.com/ProseMirror/prosemirror/issues/1091
