### ISSUE TITLE
Bad performance in `createView` method

### ISSUE THREAD

**Issue by Priestch** [ueberdosis/tiptap#1536]
**Description**
tiptap v2 has bad performance in `createView` method.

```javascript
private createView(): void {
    this.view = new EditorView(this.options.element, {
      ...this.options.editorProps,
      dispatchTransaction: this.dispatchTransaction.bind(this),
      state: EditorState.create({
        doc: createDocument(this.options.content, this.schema, this.options.parseOptions),
      }),
    })

    // `editor.view` is not yet available at this time.
    // Therefore we will add all plugins and node views directly afterwards.
    const newState = this.state.reconfigure({
      plugins: this.extensionManager.plugins,
    })

    this.view.updateState(newState)

    this.createNodeViews()

    // Let’s store the editor instance in the DOM element.
    // So we’ll have access to it for tests.
    const dom = this.view.dom as HTMLElement
    dom.editor = this
  }
```
`this.view.updateState(newState)` and `this.createNodeViews` will call `updateStateInner`, which is very slow, see below scrennshot. 

![image](https://user-images.githubusercontent.com/2059801/124269179-25fa2200-db6d-11eb-9a3b-67b5a4b00677.png)

In my project, I move `plugins `to function call `EditorState.create`, and set node views when create an editor view,
the performance back to normal.

**Comment by BrianHung** [comment]
Yeah, in general you want to avoid reconfiguring the `EditorState` with new plugins because within `updateStateInner`, all the plugin views are tore down and reconstructed: https://github.com/ProseMirror/prosemirror-view/blob/master/src/index.js#L203-L216

**Comment by Priestch** [comment]
@philippkuehn We use the editor to show word document, so the document size sometimes is huge, about 10, 000 node are rendered use node views.

We found node views suffer from performance issue compared to normal node, so we replaced node view with decoration for better performance.

**Comment by philippkuehn** [comment]
However, this is then related to ProseMirror or to the fact that thousands of node views can’t be that fast at all. Node views are expensive. I don’t think we can do anything here.

**Comment by Priestch** [comment]
> However, this is then related to ProseMirror or to the fact that thousands of node views can’t be that fast at all. Node views are expensive. I don’t think we can do anything here.

Node views is expensive, but tiptap2 can do better, if node views can be created and passed to constructor of EditorView, the performance will be better.
