### ISSUE TITLE
HelloWorld CDN example fails with RangeError: Adding different instances of a keyed plugin (plugin$)

### ISSUE THREAD

**Issue by mekterovic** [ueberdosis/tiptap#1537]
HelloWorld example from https://www.tiptap.dev/installation/cdn fails with: RangeError: Adding different instances of a keyed plugin (plugin$)...

**Steps to reproduce the bug**
1. Go to https://www.tiptap.dev/installation/cdn 
2. Copy paste the example to new index.html file
3. Open with Chrome or Firefox
4. See error message

**Comment by eltonlin1998** [comment]
I'm getting the same error but with the Vue 2 installation guide

**Comment by hanspagel** [comment]
This error appears when multiple versions of the ProseMirror dependencies are loaded. Unfortunately, that’s an issue with Skypack: https://github.com/skypackjs/skypack-cdn/issues/159

A workaround is to use a specific version for all tiptap packages, like shown on the frontpage of Skypack:
https://www.skypack.dev/

I’m not sure if we should:
a) remove the example or look for an alternative to Skypack
b) wait for a fix
c) pin all to URLs to specific versions and try to keep them up to date with every new release (or live with outdated versions in that example)

**Comment by mekterovic** [comment]
So there is no workaround for the time being?
Is it possible to link to specific versions or download manually files from tiptap repo and host locally?

**Comment by eltonlin1998** [comment]
The workaround (#305) worked - it's conflicting versions of some underlying dependencies so you need to delete node modules and all that

**Comment by tlaedre** [comment]
The workaround from #305 is irrelevant here - there's no local cache to delete in the case of loading directly from CDN.

Given that two different distribution systems produce an identical error, is it completely unreasonable to think that maybe tiptap could change something in the way packages and their dependencies are published?

Right now the situation is a bit frustrating in that there doesn't seem to be anywhere online to get a set of working modules and the only workaround seems to be to setup a local project with some build tool just for the purpose of extracting said modules.

**Comment by mekterovic** [comment]
Can't someone from the tiptap team build the project from the source and host it on the github until the matter is resolved?
This is actually a showstopper for anyone who is not using Vue or React...

**Comment by tlaedre** [comment]
@mekterovic a workaround that seems to be working for me - knock on wood, and all that - is grabbing the modules through unpkg.com

**Comment by mekterovic** [comment]
@tlaedre but there is no version 2 on unpkg, or am I missing something?
https://unpkg.com/browse/tiptap@1.32.2/

**Comment by tlaedre** [comment]
@mekterovic the 2.x packages are @tiptap/something, so e.g. https://unpkg.com/@tiptap/core?module

**Comment by mekterovic** [comment]
@tlaedre Still can't get it to work, I'm probably missing something trivial.
I've modified the code from https://www.tiptap.dev/installation/cdn to pull the js files from unpkg:
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
</head>
<body>
  <div class="element"></div>
  <script type="module">
    import { Editor } from 'https://unpkg.com/@tiptap/core?module'
    import StarterKit from 'https://unpkg.com/@tiptap/starter-kit?module'
    const editor = new Editor({
      element: document.querySelector('.element'),
      extensions: [
        StarterKit,
      ],
      content: '<p>Hello World!!!</p>',
    })
  </script>
</body>
</html>
```
when I run it I get a suspiciously bad looking "editor" with no errors in the console.
However, when I try to edit I get:
```
Uncaught RangeError: Can not convert <> to a Fragment (looks like multiple versions of prosemirror-model were loaded)
    from https://unpkg.com/prosemirror-model@^1.14.2?module:324
```

**Comment by tlaedre** [comment]
```
import { Editor } from 'https://unpkg.com/@tiptap/core?module'
import StarterKit from 'https://unpkg.com/@tiptap/starter-kit?module'
```

Is literally what I pull in atm. Maybe I'm just being lucky.. (I did double check that I was not getting multiple copies of the same module with different hashes imported, though)

**Comment by philippkuehn** [comment]
We can’t do anything here because it’s an issue with [skypack itself](https://github.com/skypackjs/skypack-cdn/issues/159). Closing.

**Comment by smalos** [comment]
@philippkuehn 
The example at https://tiptap.dev/installation/cdn should be removed, as it's not working and confusing for anyone who is going to try it.

**Comment by panphora** [comment]
I was frustrated by this, so I made a version of the Tiptap `Editor` and `StarterPack` that runs in the browser.

You can use it like this:

```
<script src="https://cdn.jsdelivr.net/gh/panphora/tiptap-for-browser@2.0.0-beta.166/tiptap-for-browser.min.js"></script>
<script>
  const Editor = Tiptap.Core.Editor;
  const StarterKit = Tiptap.StarterKit;

  new Editor({
    element: document.querySelector('.container'),
    extensions: [
      StarterKit,
    ],
    content: '<p>Hello World!</p>',
  })
</script>
```

All I did was make [a project](https://github.com/panphora/tiptap-for-browser) that imports Tiptap `Core` and `StarterKit` and attaches them to the global `window` object.

Then I bundled it with `esbuild`, tagged it with the matching Tiptap core version, and grabbed it from jsDelivr!

**Comment by TrieBr** [comment]
I was getting this problem even without using a CDN. It seems like an issue in webpack. Thanks @panphora for suggesting esbuild. Switching to esbuild solved the issue for me.
