### ISSUE TITLE
Bug: keyboard shortcuts fire in reverse order based on priority

### ISSUE THREAD

**Issue by thatsjonsense** [ueberdosis/tiptap#1547]
**Description**
If I have two extensions that both register the same shortcut, the one with the _lower_ priority takes precedence. The docs say it should be higher.

The issue is with this line: https://github.com/ueberdosis/tiptap/blob/28737b1631719315cebc354f7cb5a1d924b0b543/packages/core/src/ExtensionManager.ts#L209

I don't understand why it's reversing. The extensions are sorted from highest priority to low, but this reverses them for adding plugins.

According to [ProseMirror keymap docs](https://prosemirror.net/docs/ref/#keymap):
> The order in which they appear determines their precedence (the ones early in the array get to dispatch first).

Because we're reversing, the highest priority extensions are dispatching last.

**Comment by HeebeLee** [comment]
I was also misled by this at that time. Later, when I looked at other components, I found that the smaller the more advanced it was.

However, at present, if it is to be executed in reverse order, I believe it should not be necessary, but the documents should be updated in time.
