### ISSUE TITLE
Cannot set text align when excluding StarterKit

### ISSUE THREAD

**Issue by PokeMutt** [ueberdosis/tiptap#1548]
**Description**
Hi there! Im unsure if this is an issue due to incorrectly setting up the editor on my part, I cannot seem to find this behaviour in the docs. When trying to use the @tiptap/extension-text-align^2.0.0-beta.20 extension, text is not aligned when the StarterKit extension isnt included in the editor. However, when StarterKit is included, it works just fine. Is this intended? Thank you for taking the time to check this out!

**CodeSandbox**
Reproduceable example here in codesandbox:
https://codesandbox.io/s/tiptap-justify-text-issue-0fhgb?file=/src/components/Tiptap.vue

**Steps to reproduce the bug**
1. Select text inside editor
2. Click one of the alignment buttons
3. Text is not aligned. However, if StarterKit is included as part of the extensions, alignment works.

**Expected behavior**
When clicking the text align buttons, the text is aligned to the left, center or right.

**Environment?**
 - operating system: Windows 10 19041
 - browser: Google Chrome v91.0.4472.124
 - mobile/desktop: desktop
 - tiptap version: 2.0.0-beta.85

**Comment by hanspagel** [comment]
You pass heading but don’t load the heading extension.
