### ISSUE TITLE
Table resizable when editor's editable is false

### ISSUE THREAD

**Issue by pkariz** [ueberdosis/tiptap#1549]
**Description**
You can resize table when editor's `editable` is set to `false`.

**Steps to reproduce the bug**

1. Create an Editor instance which has `editable: false` and extension:
```js
Table.configure({
  resizable: true,
}),
```
2. Resize the table (it changes the editor's content)

**Expected behavior**
You shouldn't be able to resize the table when editor's `editable` is set to `false`.

**Comment by jelleroorda** [comment]
We also encountered this issue, however, it didn't actually resize the table. It does allow you to resize the columns, but after that it snaps back to the original position. Here's a small video to explain what I mean:

https://user-images.githubusercontent.com/9193686/125916878-34f1763f-7dc2-4153-b8ed-277629ec402b.mov
