### ISSUE TITLE
How to set async content data?

### ISSUE THREAD

**Issue by bdrtsky** [ueberdosis/tiptap#155]
I have data that loaded async after Tiptap is mounted. I can't set content

For now the only way I found is to watch data loaded, but this way I have the issue that it's setting after every charachter I type

```js
watch: {
    value () {
      if (this.value) {
        this.editor.setContent(this.value)
        // this.html = this.editor.getHTML()
      }
    }
  }
```

Where and how to set data?

**Comment by philippkuehn** [comment]
I'm not sure what you mean with `I can't set content`? Do you have some error? What do you expect?

Here is a [sandbox](https://codesandbox.io/s/0m265yypjw) with async setting content.

**Comment by antimodern** [comment]
@philippkuehn hey, thanks for response. 

My issue is little bit different - https://codesandbox.io/s/o7k25m8q7z

**Comment by bernhardh** [comment]
I had the same problem. The only solution to this is the following:

```
        watch: {
            value() {
                if(this.editor.getHTML() == '<p></p>' && this.value) {
                    this.editor.setContent(this.value);
                }
            }
        },
```

Its an ugly solution, but it works. Would love to see a better one.

**Comment by bdrtsky** [comment]
@bernhardh thank you for solution, it works like I expect. Also wonder if there's better way?

**Comment by bdrtsky** [comment]
@bernhardh here's suggestion how to get rid of this watcher (it is working on every key stroke)

```js
mounted () {
    this.unwatch = this.$watch('value', this.setInitialContent)
  },
methods: {
    setInitialContent (content) {
      if(this.editor.getHTML() == '<p></p>') {
        this.editor.setContent(content)
        this.unwatch()
      }
    }
  }
```
this way watcher will triggered only once!

**Comment by afwn90cj93201nixr2e1re** [comment]
Where is facepalm icon?

in mounted value already setted. Watch is never called.
If you provide prop which already initialized you should use v-bind.
```js
in data:
data() {
            console.log('editor created in data')
            return {
				/* html: '', */
				editor: new Editor({
					extensions: [
						new Blockquote(),new BulletList(),new CodeBlock(),new HardBreak(),new Heading({ levels: [1, 2, 3] }),
						new ListItem(),new OrderedList(),new Image(),
						new TodoItem(),new TodoList(),new Link(),
						new Bold(),new Code(),new Italic(),new Strike(),new HorizontalRule(),
						new Underline(),new History(),new Table({resizable: true,}),
						new TableHeader(),new TableCell(),new TableRow(),new TrailingNode({node: 'paragraph',notAfter: ['paragraph']}),
					],
					onUpdate: /* debounce( */({ getHTML }) => {//maybe we should make it debounce?
						/* this.html=getHTML(); */
						/* if (this.html === '<p></p>')this.html = ''; */
						this.$emit('input', getHTML());
					}/* , 500) */
				}),
			}
		},

in mounted:
mounted () {
            this.editor.setContent(this.value)
        }

```

@philippkuehn maybe we should provide initial_content prop into editor contstructor?

**Comment by haacked** [comment]
For those who are finding this search result now, I don't recommend checking empty content this way:

```js
if(this.editor.getHTML() == '<p></p>' && this.value) {
    //...
}
```

It won't be correct if you've customized the paragraph classes. I'm currently using TipTap 2.0.3 which has the `isEmpty` property. So my solution to populating the editor with fetched content is:

```ts
const { error, data } = useFetch<JSONContent>('/some-url');

const editor = useEditor({...}); // Don't set content!

if(data && editor.isEmpty) {
    editor.commands.setContent(data);
}
```

Hope that helps the next person. :smile:

**Comment by jonahallibone** [comment]
> For those who are finding this search result now, I don't recommend checking empty content this way:
> 
> ```js
> if(this.editor.getHTML() == '<p></p>' && this.value) {
>     //...
> }
> ```
> 
> It won't be correct if you've customized the paragraph classes. I'm currently using TipTap 2.0.3 which has the `isEmpty` property. So my solution to populating the editor with fetched content is:
> 
> ```ts
> const { error, data } = useFetch<JSONContent>('/some-url');
> 
> const editor = useEditor({...}); // Don't set content!
> 
> if(data && editor.isEmpty) {
>     editor.commands.setContent(data);
> }
> ```
> 
> Hope that helps the next person. 😄

This is the correct solution I believe
