### ISSUE TITLE
Not reconnecting if hocuspocus restarts in between

### ISSUE THREAD

**Issue by hardiksondagar** [ueberdosis/tiptap#1551]
Editor keeps connected to older socket connection and doesn’t communicate to server after restart. Need to use incognito to load fresh data.

Steps
- Start hocuspocus server
- Load tiptap editor with some data from server side and keep it open
- Stop hocuspocus server
- Delete rocksdb directory (quick hack to force reload data from mysql)
- Start hocuspocus server

Client won't communicated to server after restart. No on connect event.

It works If I open editor in incognito.

**Comment by hanspagel** [comment]
Please create an issue in the hocuspocus repository.
