### ISSUE TITLE
Links can't be updated in link extension

### ISSUE THREAD

**Issue by LaravelFreelancerNL** [ueberdosis/tiptap#1564]
**Description**
It seems to be impossible to update an existing link without removing the link and creating a new one.

**Steps to reproduce the bug**
1. Go to https://www.tiptap.dev/api/marks/link/#link
2. Click on the world wide web link in the example; wikipedia will open in a new tab.
3. Click in the link example on a non-link tekst, move the cursor within the same link
4. Click on the link button
5. Enter a different url (e.g. https://test.com) and submit
6. Click on the same link; wikipedia opens again
7. You can confirm this with browser dev tools; the link has not been updated.

**Expected behavior**
I expect the anchor to be set to the new href (and contain any other relevant state changes such as the target or rel tags)

**Environment?**
 - operating system: W10
 - browser: Edge
 - mobile/desktop: desktop
 - tiptap version: @tiptap/core@^2.0.0-beta.85, @tiptap/extension-link@^2.0.0-beta.18

**Additional context**
[The official example](https://www.tiptap.dev/api/marks/link/#link) has this problem, as well as my local environment described above.

**Comment by hanspagel** [comment]
Thanks! You’re updating the URL only for the selected text, seems like you didn’t select the text.

Those usage demos on the extension detail pages are intended to be very raw to give a better impression of how they work. Anyway, I think a few people were stuck there already, so I added a `extendMarkRange` command to the chain. This applies the update to the whole `Link` mark. ✌️ The resulting command chain looks like that:

```diff
this.editor
  .chain()
  .focus()
+ .extendMarkRange('link')
  .setLink({ href: url })
  .run()
```

Read more about `extendMarkRange`: https://www.tiptap.dev/api/commands/extend-mark-range/#extendmarkrange

**Comment by volarname** [comment]
how to prepopulate input by current url?

**Comment by pradel** [comment]
@volarname https://github.com/ueberdosis/tiptap/issues/1277#issuecomment-861906555
