### ISSUE TITLE
Issue with @tiptap/extension-code-block-lowlight in react.js

### ISSUE THREAD

**Issue by coderinblack08** [ueberdosis/tiptap#1565]
### Discussed in https://github.com/ueberdosis/tiptap/discussions/1560

<div type='discussions-op-text'>

<sup>Originally posted by **coderinblack08** July  8, 2021</sup>

The code block lowlight extension fails when you click the code button while on a new line. I think this has something to do with Starterkit.
[Here's the Code Sanbox](https://codesandbox.io/s/hopeful-grass-wonmq)

![image](https://user-images.githubusercontent.com/41022901/124997982-6d1a6400-e000-11eb-88bc-a81a90c998a9.png)
</div>

**Comment by coderinblack08** [comment]
This could be a react-only issue. Everything works fine in vue, even with starterkit: https://codesandbox.io/s/compassionate-firefly-nn4gg?file=/src/App.vue

**Comment by mint-minsoo** [comment]
#1520 
probably the same problem

**Comment by hanspagel** [comment]
Thanks for reporting! Yes, I think that’s a duplicate. I’m closing this here in favor of the other issue.
