### ISSUE TITLE
TaskItem does not update data-checked attribute

### ISSUE THREAD

**Issue by giorgiopogliani** [ueberdosis/tiptap#1566]
**Description**
Checking and unchecking a task item does not update `data-checked` attribute to true/false in real time

**Steps to reproduce the bug**
Create a taskItem and with the dev tools the attribute does not change in real time

**CodeSandbox**
The docs have this problem too: https://www.tiptap.dev/api/nodes/task-item/#taskitem

**Expected behavior**
I would like to style the text of a marked `taskItem`, it works if the content is refreshed but does not work in real time.

**Comment by giorgiopogliani** [comment]
I still have this issue also the docs still doesn't work.  In the console I get:
```
Uncaught RangeError: Index 8 out of range for
```

**Comment by philippkuehn** [comment]
@giorgiopogliani The demo is working for me. Maybe a browser extension is causing this issue. See #2372

**Comment by giorgiopogliani** [comment]
Thanks for the quick reply! 

You are right! It was the extension for my password keychain.. 😶
