### ISSUE TITLE
[Vue2] Warning: Do not use built-in or reserved HTML elements as component id: a

### ISSUE THREAD

**Issue by yellow1912** [ueberdosis/tiptap#1568]
**Description**

When I pack my project with webpack (v5), I get this error on the browser when loading the code:

[Vue warn]: Do not use built-in or reserved HTML elements as component id: a

**Steps to reproduce the bug**

I did not see this error when I packed with webpack 4, I'm unsure what happens here that leads to the issue. I did not change anything on my code, but I did have to mess around with webpack to upgrade to latest version.

**CodeSandbox**

The project is huge I cannot create the sandbox yet but if it is needed I will try to see if can do anything.

**Expected behavior**

**Screenshot, video, or GIF**

![image](https://user-images.githubusercontent.com/374134/125153631-5ea68680-e17f-11eb-9f01-a3ff8ba33ce4.png)

**Environment?**
 - operating system: Window 10
 - browser: Chrome (latest)
 - mobile/desktop: desktop
 - tiptap version: 

```
"@tiptap/extension-character-count": "^2.0.0-beta.12",
    "@tiptap/extension-dropcursor": "^2.0.0-beta.17",
    "@tiptap/extension-mention": "^2.0.0-beta.61",
    "@tiptap/extension-subscript": "^2.0.0-beta.3",
    "@tiptap/extension-superscript": "^2.0.0-beta.3",
    "@tiptap/extension-text-align": "^2.0.0-beta.20",
    "@tiptap/extension-underline": "^2.0.0-beta.15",
    "@tiptap/starter-kit": "^2.0.0-beta.82",
    "@tiptap/vue-2": "^2.0.0-beta.39",
```

**Comment by hanspagel** [comment]
Are you sure this error is in tiptap? Your stack trace mentions a `vue.js`.

**Comment by yellow1912** [comment]
@hanspagel The warning is emitted by vue, but according the to the tracelog it seems to come from the tiptap vue 2 file.

That file belongs to the tiptap package:

```
class VueRenderer {
    constructor(component, props) {
        const Component = Vue.extend(component);
        this.ref = new Component(props).$mount();
    }
    get element() {
        return this.ref.$el;
    }
    updateProps(props = {}) {
        if (!this.ref.$props) {
            return;
        }
        // prevents `Avoid mutating a prop directly` error message
        const originalSilent = Vue.config.silent;
        Vue.config.silent = true;
        Object
            .entries(props)
            .forEach(([key, value]) => {
            this.ref.$props[key] = value;
        });
        Vue.config.silent = originalSilent;
    }
    destroy() {
        this.ref.$destroy();
    }
}
```

Line 144: const Component = Vue.extend(component);

I will check for more information to see where this comes from, it's probably due to issue on my end but I will update this issue when I find out.

**Comment by hanspagel** [comment]
I don’t think we’re using `a` or any other reserved HTML element as a component id, so I’m closing this for now. ✌️
