### ISSUE TITLE
Possible bug in the SvelteKit installation instructions

### ISSUE THREAD

**Issue by SamuelEarl** [ueberdosis/tiptap#1571]
**SvelteKit Installation Instructions**
The [SvelteKit installation instructions](https://www.tiptap.dev/installation/svelte) might have a bug in them. I reported the bug and a possible solution [here](https://github.com/ueberdosis/tiptap/issues/1570).

If that bug and the solution I posted can be reproduced, then should the docs be updated with the solution?

Thank you!

**Comment by hanspagel** [comment]
I don’t have that error when I create a fresh project and follow the instructions. Have you chosen TypeScript? It’s possible that you’d need to remove that in a TypeScript setup.
