### ISSUE TITLE
Is there an event feedback method?

### ISSUE THREAD

**Issue by HeebeLee** [ueberdosis/tiptap#1573]
I use tiptap in Windows applications. The toolbars are system controls, so it can't get the class attribute by binding attributes like Vue.

So when the cursor in the editor changes, we need to judge all the attributes, and then tell windows window which content has changed, and the toolbar will react.

Now I don't know how to execute a JS code when the `editor. Isactive ('xxxx')` changes.

How can I realize this idea?

thx.

**Comment by hanspagel** [comment]
Use the update event ✌️

https://www.tiptap.dev/api/events/#events
