### ISSUE TITLE
How to check and correct the expired information in the mentioned components?

### ISSUE THREAD

**Issue by HeebeLee** [ueberdosis/tiptap#1576]
The user mentioned is stored in the JSON format with his ID, but with the user modifying the user name, the label displayed in the stored JSON is no longer accurate.

In this way, do we have any means to check it and correct it in the future?

Or do we have a way to read all the mentioned tags and then check and correct them?

**Comment by philippkuehn** [comment]
There are 2 ways of solving this:

1. store only the id of a mention in your JSON. render the mention as a node view to load the user name asynchronously.
2. store id and user name and migrate your data on the server side if a user name has changed
