### ISSUE TITLE
TypeError: Cannot read property 'addExtensions' of undefined

### ISSUE THREAD

**Issue by devgeni** [ueberdosis/tiptap#1580]
**Description**
Error while trying to convert html string to json object with node using tiptap/html

**Steps to reproduce the bug**
1. `npm install @tiptap/extension-document @tiptap/extension-paragraph @tiptap/extension-text @tiptap/html`
2. Create file `test.js` and put the code below inside it:
```js
const Document = require("@tiptap/extension-document");
const Paragraph = require("@tiptap/extension-paragraph");
const Text = require("@tiptap/extension-text");

const generateJSON = require("@tiptap/html").generateJSON;

const html = "<p>Hello World</p>";
const json = generateJSON(html, [Document, Paragraph, Text]);

console.log(json);
```
3. `node index.js`
4. See error message in the console

**Expected behavior**
It should output `{ type: 'doc', content: [ { type: 'paragraph', content: [Array] } ] }` in the console.

**Additional context**
Here is how the error looks llike:
```
if (extension.config[field] === undefined && extension.parent) {
                        ^

TypeError: Cannot read property 'addExtensions' of undefined
    at getExtensionField (../node_modules/@tiptap/core/dist/tiptap-core.cjs.js:427:25)
    at ../node_modules/@tiptap/core/dist/tiptap-core.cjs.js:816:35
    at Array.map (<anonymous>)
    at Function.flatten (../node_modules/@tiptap/core/dist/tiptap-core.cjs.js:811:14)
    at Function.resolve (../node_modules/@tiptap/core/dist/tiptap-core.cjs.js:807:55)
    at Object.getSchema (../node_modules/@tiptap/core/dist/tiptap-core.cjs.js:3273:49)
    at generateJSON (../node_modules/@tiptap/html/dist/tiptap-html.cjs.js:26:25)
    at ../test.js:8:14
```
Here is the link to the source where it happens: 
[https://github.com/ueberdosis/tiptap/blob/main/packages/core/src/ExtensionManager.ts#L143](https://github.com/ueberdosis/tiptap/blob/main/packages/core/src/ExtensionManager.ts#L143)

**Comment by marco-scoppetta-qatalog** [comment]
Hey @devgeni - what was the solution which made it work for you?

**Comment by hanspagel** [comment]
Update your dependencies ✌️

**Comment by marco-scoppetta-qatalog** [comment]
We have the latest version of TipTap core and all the extensions - but still stuck on this issue. Anything else we could check?

**Comment by philippkuehn** [comment]
default export in node doesn’t work. you have to do:

```js
const { Document } = require("@tiptap/extension-document")
```

instead of

```js
const Document = require("@tiptap/extension-document")
```
