### ISSUE TITLE
Type Error: CollaborationCursorOptions.onUpdate clientId should be a number

### ISSUE THREAD

**Issue by jamesopti** [ueberdosis/tiptap#1582]
**Description**
The type for the awareness `CollaborationCursorOptions.onUpdate` argument for `clientId` is string. It should be `number`

Type: https://github.com/ueberdosis/tiptap/blob/main/packages/extension-collaboration-cursor/src/collaboration-cursor.ts#L8

Source: https://github.com/yjs/y-protocols/blob/master/awareness.js#L49

**Additional context**
This is causing trouble for us when consuming the awareness `onUpdate` function.

**Comment by hanspagel** [comment]
Oh, yes! ✌️
