### ISSUE TITLE
How to refresh the editor after modifying the plug-in configuration.

### ISSUE THREAD

**Issue by HeebeLee** [ueberdosis/tiptap#1609]
hello everyone.

I'm localizing the editor, and I haven't found a way to refresh the configuration.
I have done a lot of plug-ins, some of which need to be localized. I need to update the plug-in configuration through the `XXX. Configure()` method.

After I configure it, I hope the undo and redo functions remain unchanged.

I tried the following, but it didn't work:

```
      placeholder.configure({
        placeholder: {
          heading: "aaa",
          default: "bbb"
        },
      });

      app.editor.view.updateState(app.editor.view.state); // here updateState
```

I don't know how to do it now. Is there no such requirement and support for tiptap? If so, please tell me how to do it. Thank you.

**Comment by philippkuehn** [comment]
That is not supported. You have to destroy and recreate the editor for doing this.

BTW: you can add a dynamic placeholder:

```js
Placeholder.configure({
  placeholder: ({ node }) => {
    return 'dynamic text'
  },
})
```
