### ISSUE TITLE
Rtl Support dynamically when user type first char 

### ISSUE THREAD

**Issue by pooooriya** [ueberdosis/tiptap#1621]
**The problem I am facing**
when I want to type persian like "سلام"
I Cant change direction 
**The solution I would like**
dynamically change dir and added to classname list of that element 
because when I saved my work and use dangerouslyhtml then without any side effects I show my persian language with dir="rtl"

**Alternatives I have considered**
nothing

**Additional context**
nothing and thanks for this cool package

**Comment by cadars** [comment]
See: https://github.com/ueberdosis/tiptap/issues/116

Still, it would be nice to have `dir="auto"` as a simple setting.

**Comment by cadars** [comment]
I came up with a quick and dirty extension, it works(?) for paragraphs and headings, not sure how to make it happen for lists.

```javascript
import { Extension } from '@tiptap/core'

const AutoDir = Extension.create({
  addGlobalAttributes() {
    return [   
      {
        types: [
          'heading',
          'paragraph',
        ],
        attributes: {
          autoDir: {
            renderHTML: attributes => ({
              dir: 'auto',
            }),
            parseHTML: element => ({
              autoDir: element.dir.autoDir || 'auto',
            }),
          },
        },
      },
    ]
  },
})
```

**Comment by cadars** [comment]
Update: to make blockquotes and lists work, `dir="auto"` should only be added to parent nodes… I’m not sure how to make that happen in the extension.

Here is a test for this issue: https://codepen.io/cadars/pen/poeXMXZ?editors=1100

**Comment by cadars** [comment]
Updated to work with the `parseHTML` [method change](https://github.com/ueberdosis/tiptap/issues/1863):

```js
import { Extension } from '@tiptap/core'

const AutoDir = Extension.create({
  name: 'AutoDir',
  addGlobalAttributes() {
    return [   
      {
        types: [
          'heading',
          'paragraph',
          'bulletList',
          'orderedList',
          'blockquote',
        ],
        attributes: {
          autoDir: {
            renderHTML: attributes => ({
              dir: 'auto',
            }),
            parseHTML: element => element.dir || 'auto',
          },
        },
      },
    ]
  },
})
```

**Comment by philippkuehn** [comment]
For now, [adding a custom extension](https://github.com/ueberdosis/tiptap/issues/1621#issuecomment-918990408) is the preferred way.

**Comment by amirhhashemi** [comment]
Hey everyone. I wrote a small extension that automatically adds dir="rtl" or dir="ltr" based on the node's content. You might find it useful: https://github.com/amirhhashemi/tiptap-text-direction
