### ISSUE TITLE
Backspace/Delete not working for RTL characters in shadowDOM

### ISSUE THREAD

**Issue by genadis** [ueberdosis/tiptap#1622]
**Description**
After typing RTL text, pressing backspace does not delete the text, instead the cursor position is lost and editor becomes not usable.

This happens only if the editor is placed inside shadowDOM.

**Steps to reproduce the bug**
1. render tiptap editor inside shadowDOM
2. Type text in RTL language
3. press Backspace

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:

* React: https://codesandbox.io/s/tiptap-react-forked-7ky68?file=/src/index.tsx

(It's not specific to React)

**Expected behavior**
Backspace should work for RTL characters same as for LTR.

**Environment?**
 - operating system: any
 - browser: tested on chrome and safari (probably any)
 - mobile/desktop: desktop
 - tiptap version: "@tiptap/core": "^2.0.0-beta.86"

**Comment by genadis** [comment]
Fixed by https://github.com/ProseMirror/prosemirror-view/pull/102 in https://github.com/ProseMirror/prosemirror-view/releases/tag/1.19.0

**Comment by philippkuehn** [comment]
ah great. the latest version of tiptap is already using prosemirror-view@1.19
