### ISSUE TITLE
Click the blank space outside the editor, and the editor will not get the focus.

### ISSUE THREAD

**Issue by HeebeLee** [ueberdosis/tiptap#1631]
I set a minimum height for the editor. If I have less content, I click the blank space at the bottom (or right) of the editor with the mouse, and the editor does not get the focus.

My idea is that it should be consistent with the behavior of other editors (such as textview on the client), that is, clicking blank will focus on the nearest character.

**Comment by cadars** [comment]
Not sure if I understand: if you click outside an element in HTML, it is normal that it loses focus.

If you're looking for a full page experience, (like IA Writer for example) a cheap solution would be to make the editable element 100% in width and height in CSS (with a little padding), and then a max-width for direct child elements. This way clicking in the margins will focus on the nearest line/character.

```css
.ProseMirror {
    padding: 1em;
}

.ProseMirror > * {
    width: 100%;
    max-width: 40em;
    margin: 0 auto;
}

**Comment by HeebeLee** [comment]
> Not sure if I understand: if you click outside an element in HTML, it is normal that it loses focus.
> 
> If you're looking for a full page experience, (like IA Writer for example) a cheap solution would be to make the editable element 100% in width and height in CSS (with a little padding), and then a max-width for direct child elements. This way clicking in the margins will focus on the nearest line/character.
> 
> ```css
> .ProseMirror {
>   padding: 1em;
> }
> 
> .ProseMirror > * {
>   width: 100%;
>   max-width: 40em;
>   margin: 0 auto;
> }
> ```
imageURL: https://imgtu.com/i/WywQGF
![avatar](https://z3.ax1x.com/2021/07/23/WywQGF.png)

Maybe I didn't explain my problem clearly. I mean that when you click on the area of these red boxes, the editor will get the focus state.

**Comment by cadars** [comment]
I can't see where the containing `.Prosemirror` div is on this screenshot, but still, I invite you to try my solution.

**Comment by BrianHung** [comment]
I agree with cadars I don't think this is a tiptap or a ProseMirror issue. To have the editor focus on click, you need to be clicking on the editor in the first place. To adjust the editor height to minimum height regardless of content height, I would try using having the parent container `display: flex` then having `.ProseMirror { flex-grow: 1; }`, or something similar.

**Comment by philippkuehn** [comment]
It’s not a tiptap issue at all. You have to increase the editor element somehow with CSS.
