### ISSUE TITLE
Edit a SuperStarterKit to avoid adding to much extensions to package.json

### ISSUE THREAD

**Issue by LaurentNoyon** [ueberdosis/tiptap#1644]
**The problem I am facing**
Currently only some common extensions are present in the StarterKit. It can be annoying to add missing extensions manually.

**The solution I would like**
Would it be possible to get a "SuperStarterKit" which will supports all the known extensions ?

**Comment by philippkuehn** [comment]
Sorry, but I don’t have plans to support multiple starter kits for now.

**Comment by LaurentNoyon** [comment]
I understand, why not adding all the available extensions in the starter kit ? I understand some users don't want to install a large package of extensions and I find it great that you can now pick what you need. Installing a starter kit with a pool of popular extensions is convenient, but you'll always miss some extensions that are not in the pack and you will surely not use all of the extensions that are in the pack. I was just finding it more neat in tiptap v1 when you would only have to install tiptap and tiptap-extensions to get all the features.

**Comment by hanspagel** [comment]
With all extensions and their dependencies more and more dependency conflicts would appear in more and more projects which would cause more and more created issues which would lead to our burnout. 😅
