### ISSUE TITLE
blank spaces disappear when combining formatting and JSON saving

### ISSUE THREAD

**Issue by pbi7521** [ueberdosis/tiptap#1654]
When I apply formatting to a text in tiptap (e.g. putting a word in bold), then save the JSON output from the editor, and then later restore it, the white spaces before and after the formatting have disappeared.

So, if I use the string "the quick brown fox" as an example, if I format it to "the **quick** brown fox", then save the JSON string from the editor and later restore it, it will be restored as "the**quick**brown fox". Notice : there is no space between "the" and "quick", nor between "quick" and brown. 

The same happens with any formatting I tried.

**Comment by philippkuehn** [comment]
I can’t reproduce this. please provide a codesandbox.

**Comment by martink635** [comment]
I have the same issue, will try to make codesanbox for easier debugging.

Basically, when I call `onUpdate` and use the `getJSON` to save it in the database, on load it's without the space around highlights, bold,  italics etc.

**Comment by martink635** [comment]
Was not an issue on tiptap, since it sends out the correct JSON with the whitespace.

(In my case it was the TrimStrings middleware in Laravel, which I had to remove)
