### ISSUE TITLE
Custom attribute is persistent when creating a new line

### ISSUE THREAD

**Issue by SebTota** [ueberdosis/tiptap#1657]
**Description**
When extending an existing extensions to support custom attributes, the attributes persist beyond the element to which they should be assigned to. In other words, if a new paragraph is added and it has a custom attribute assigned to it, the next line should default to not having that custom attribute value. 

**CodeSandbox**
https://codesandbox.io/s/tiptap2-vue2-forked-ux08o?file=/src/App.vue

**Steps to reproduce the bug**
* Open Developer Console
* Click the `addElement` button
* Compare attributes, taking note that the inserted text has the `testAttr` attribute assigned
* Add a new line after the newly added line, `this is yet another test` and take note that the new line has the previously assigned `testAttr` attribute and value
* Add a new line after `Hi there,` and take note that the new line does not have the `testAttr` value assigned (this is the desired result)

**Expected behavior**
The added content should contain the custom attribute, but the next line should not retain that set attribute. It should instead default to the default value which in this case is null.  

**Screenshot, video, or GIF**
https://user-images.githubusercontent.com/25122511/127363899-3a9a8b09-ccaf-45d2-9a90-c4226edbcc3d.mov

**Environment?**
 - operating system: MacOS
 - browser: Firefox
 - mobile/desktop: Desktop
 - tiptap version: 2.0.0-beta.90

**Additional context**
While the code sandbox uses the `insertHTML` api call, the same issue occurs when using the `insertContentAt` api call.

**Comment by philippkuehn** [comment]
Hey,

you can set keepOnSplit to false.

```js
Paragraph.extend({
  addAttributes() {
    return {
      ...this.parent?.(),
      testAttr: {
        default: null,
        keepOnSplit: false,
      }
    }
  }
})
```

**Comment by SebTota** [comment]
Thank you so much! I can't believe I missed this. Thank you!

**Comment by Pigzhuyao** [comment]
@philippkuehn  Thank you so much! I can't believe I missed this. Thank you!
