### ISSUE TITLE
After upgrading @tiptap/core to v2.0.0-beta.92, toggle buttons will lose focus from selected text

### ISSUE THREAD

**Issue by atulmy** [ueberdosis/tiptap#1658]
**Description**
When clicking on any toggle button with text selected, the action will happen (for example bold) but the cursor will either jump to end of word/paragraph or at the start of paragraph. 

I upgraded to v2.0.0-beta.92 from v2.0.0-beta.86 (issue was not present in v.86).

**Expected behavior**
When toggling, text selection should be preserved so that user can apply multiple actions like underline, bold etc without selecting text again and again.

**Comment by philippkuehn** [comment]
Can you reproduce this somehow? I can’t see that in our examples in the docs.

**Comment by cadars** [comment]
It happens with the bubble menu example: https://www.tiptap.dev/guide/menus#bubble-menu

**Comment by atulmy** [comment]
Thanks for the quick fix! Really appreciate the help :)
