### ISSUE TITLE
@tiptap/vue-3 uses an isolated version of Vue

### ISSUE THREAD

**Issue by disarticulate** [ueberdosis/tiptap#1667]
**Description**
Multiple import component bugs when using Tiptap in Quasar v2, which both upgrade to Vue3. Problem explained here: https://github.com/quasarframework/quasar/issues/9952

**Steps to reproduce the bug**
Follow: https://github.com/quasarframework/quasar/issues/9952

**Expected behavior**
```import { Editor, EditorContent } from '@tiptap/vue-3'```

Should 'just work'

Actual solution/work around in quasar/hot fix appears to be resolving webpack for vue to a single package:
```
  const runtimeVue = ctx.dev
    ? './node_modules/vue/dist/vue.runtime.esm-browser.js'
    : './node_modules/vue/dist/vue.runtime.esm-browser.prod.js'
... // webpack configuration, add alias
{
  resolve: {
    alias: {
        'vue$', runtimeVue
    }
  }
```

Although this seems like a Quasar issue, I'm willing to bet its a mutal conflict with how Vue3 needs to be a peer dependency in or otherwise slotted into the whole. Obviously, other people are going to be importing tiptap into their framework of choice and expect it to _just work_ ^^tm

**Comment by LaravelFreelancerNL** [comment]
#1110
I had the same problem in combination with InertiaJS. 

The tip at the end worked for me. Set it to the version of Vue3 that you are using (3.2 in my case).

**Comment by philippkuehn** [comment]
Closing because of https://github.com/ueberdosis/tiptap/issues/1606#issuecomment-985503582
