### ISSUE TITLE
Draggable custom node view - unable to focus cursor in `textarea` or `input` elements in Firefox

### ISSUE THREAD

**Issue by engram-design** [ueberdosis/tiptap#1668]
**Description**
There's a strange issue which is only happening in Firefox (Chrome and Safari are fine), in that in my custom node view, which has inputs, textarea's (and more), Firefox is unable to insert the cursor (caret) at the point you click. Double-clicking to highlight entire words also doesn't work. The cursor just stays at the start of the field. Using the keyboard is the only way to get the cursor to move. Typing in the field works, but only insert at the cursor, which when clicked is only at the start.

As a test, I can move the cursor via the keyboard, then click in the input/textarea again, and it doesn't reset the cursor, so it's plain not capturing the click event (just in case the bug was it just moving the cursor to the start of the input on each click).

Have a look at the example here: https://codesandbox.io/s/tiptap-firefox-inputs-forked-gekin?file=/src/components/CustomNode.js

The only way to make it work is by commenting out `draggable: true` for the custom node view class which is eerily similar to my other, slightly related issue https://github.com/ueberdosis/tiptap/issues/1403. But this bug in particular is fine on Safari.

There seems to be maybe some weird things with custom nodes being draggable?

**Environment?**
 - operating system: Mac OS Catalina
 - browser: Firefox (Chrome and Safari fine)
 - mobile/desktop: Desktop
 - tiptap version: 2.0.0-beta.93

**Comment by philippkuehn** [comment]
Hmm, since I’ve seen something very similar [here](https://discuss.prosemirror.net/t/nested-draggable-editors-behave-differently-in-all-browsers/3807) I think this is related to ProseMirror itself.

**Comment by engram-design** [comment]
Any thoughts on this, and would it be better to post something to ProseMirror directly? I just didn't want to post a Tiptap example reproduction to ProseMirror in case they didn't like that (I'm not quite sure how to use custom node views with straight ProseMirror)

**Comment by engram-design** [comment]
Looks like this was a [browser bug](https://bugzilla.mozilla.org/show_bug.cgi?id=739071), more than anything

I’ve kept the custom view using `draggable: true` as without it, we’d lose dragging functionality. Instead, after initialization, I’m removing the `draggable="true"` attribute from the DOM element. This doesn’t seem to affect draggability, but does fix Firefox’s inability to select text.

I'm wondering if there could be an option to enable draggable nodes, but disable the attribute on the DOM?

https://github.com/verbb/vizy/commit/b0622b271aa2a3fa5bbaedf5e9fa96760a07312e
