### ISSUE TITLE
Isolating not working with combination of atom

### ISSUE THREAD

**Issue by volarname** [ueberdosis/tiptap#1670]
**Description**
When you set isolating and atom to true, backspace after or delete before the node will delete it (VUE)
`  group: 'block',
  isolating: true,
  atom: true,`

**Steps to reproduce the bug**
1. create a new instance and node
2. set schema settings to isolating true and atom true

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:
https://codesandbox.io/s/tiptap-issue-template-forked-dlxpp?file=/src/Extension.js

**Expected behavior**
it should prevent the removal of the node, as on version 1, because of isolating set to true

**Environment?**
 - @tiptap/vue-2: ^2.0.0-beta.41
 - @tiptap/core: ^2.0.0-beta.92

**Comment by tobiasfuhlroth** [comment]
Can confirm that this was working properly with `@tiptap/core": "^2.0.0-beta.86`. Just upgraded to the latest package versions and the behaviour completely changed. It now selects the previous `Node` instead of staying inside the current `Node`.

**Comment by philippkuehn** [comment]
Hmm, sounds like an issue with ProseMirror itself. Can’t think of anything that tiptap is doing special here.

**Comment by philippkuehn** [comment]
@tobiasfuhlroth can you please check at which exact version the issue has been introduced? that would help a lot.

**Comment by volarname** [comment]
I have added codesandbox link

**Comment by tobiasfuhlroth** [comment]
@philippkuehn I distilled my setup down to this Sandbox: https://codesandbox.io/s/tiptap-issue-template-forked-0p117?file=/src/components/Tiptap.vue

**Currently i can't reproduce the issue i'm having inside my project.**

Will drill down further on this once i'm back from holidays.

**Comment by petertoth** [comment]
Experiencing the same issue. I want to implement nodes(with a vue view) which don't get deleted by a backspace but I'm not sure how to do it/whether it is possible. Anyhow, thanks for reporting and all the work!

**Comment by philippkuehn** [comment]
The `isolating` option is not there to prevent a node from being deleted. If this was once the case, it was probably a bug of ProseMirror.
