### ISSUE TITLE
Inline marks don't clear themselves correctly on clearing the line

### ISSUE THREAD

**Issue by yash-deepsource** [ueberdosis/tiptap#1672]
**Description**
---

Inline marks such as inline code blocks, bold, italics and strikethrough (not an exhaustive list as I haven't tested for others) don't clear themselves when I fully empty the current line. On adding characters again to the same line, the previous inline mark reappears.

If this bug occurs in lines except the first line in the editor, the bug can be resolved by deleting the line  itself and creating it again. But, if it occurs in the first line, it becomes impossible to remove it without refreshing the editor.

**Steps to reproduce the bug**
---

Ensure that the editor is fully empty. Steps to reproduce the behavior, using inline code block as a case:
1. Start an inline code block as the first character in the first line and add some characters. E.g. : 

    ```
    `test`
    ```
2. Clear it in an unconventional way, E.g. `CTRL + A` -> `DEL` or `Left Arrow` -> `Delete` -> `Backspace`.
3. Try typing in new characters normally.
4. The inline mark (inline code block in this case) appears again.

> Note: In cases like  `Left Arrow` -> `Delete` -> `Backspace`, the code block also follows down to the next lines without getting cleared.

**CodeSandbox**
---

https://codesandbox.io/s/tiptap-issue-template-forked-6nqe9?file=/src/components/Tiptap.vue

**Expected behavior**
---

The inline mark gets cleared on emptying the line and doesn't re-appear on adding characters to it again.

**Screenshot, video, or GIF**
---

https://user-images.githubusercontent.com/87606277/127856618-dd7a6836-7143-4f2b-a6fa-2f7a063215a3.mp4

**Environment?**
---

 - operating system: Windows 10 and Mac OS Big Sur
 - browser: Edge v92 and Firefox Dev edition v91
 - mobile/desktop: Desktop
 - tiptap version:  2.0.0-beta.39

**Additional context**
---

The given list of inline marks I could reproduce it for isn't exhaustive and I have been able to reproduce it for Bold, Italic, Strikethrough and Inline code blocks till now.

**Comment by philippkuehn** [comment]
Since this is the default behavior of ProseMirror I don’t have plans to change that.
