### ISSUE TITLE
Interactive node views issues

### ISSUE THREAD

**Issue by volarname** [ueberdosis/tiptap#1679]
**Description**
- I am using custom group and content is paragraph*
- Not possbile to exit from node view, tried any compination of enter, double enter etc
- When I have 2 same nodes/components next to each other, I cant insert content between them, or after/before sometimes
- If I have this custom node in editor and I try to insert same node before, it will totally break, no error, but new node is inserted on incorrect place. Also any action from this broken node component will run same action on all of them, like they are same instance or something. Hitting delete button will open modal multiple times.

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:
https://codesandbox.io/s/tiptap-issue-template-forked-euw0i?file=/src/App.vue

**Expected behavior**
- It should be possible to exit from node view using keys (double enter for example)
- it should be possible to put content between 2 these nodes or after last node or before first node when there is no paragraph
- when I insert node before same node type it should work, it should be placed on right place and order and components should work separately, no action in one should do action on another

**Comment by philippkuehn** [comment]
This is because you have set `isolating` to `true` for your node. It’s the expected behavior with that configuration.

**Comment by volarname** [comment]
i suggest to add more description to documentation about isolating.

**Comment by volarname** [comment]
> This is because you have set `isolating` to `true` for your node. It’s the expected behavior with that configuration.

I have removed isolating: true from my extension
https://codesandbox.io/s/tiptap-issue-template-forked-euw0i?file=/src/Extension.js

I have still same issue = when I insert more embeds above first one, and hit remove on one of them, it will open multiple modals to delete instead of one (sometimes)
