### ISSUE TITLE
Notion-like horizontal alignment

### ISSUE THREAD

**Issue by softmarshmallow** [ueberdosis/tiptap#1680]
Smooth interaction & DnD Off the table, let's talk about static layout only.

Doe prosmirror support smooth horizontal layout management & will tiptap be targetting to support feature like this?
I understand that DnD feature is under preview & cursor / handle should be implemented first before this gets usabe. thous, I'm curious if Layout managing will be a valid option with using html syntax!

https://user-images.githubusercontent.com/16307013/128179175-6aecfc3f-1f42-483b-98cf-35d3a334a9c4.mov

**Comment by hanspagel** [comment]
Drag’n’drop support comes, but something like the described horizontal layout feature feels out of scope. ✌️
