### ISSUE TITLE
Cannot read property 'nodeType' of null

### ISSUE THREAD

**Issue by wangkui1991** [ueberdosis/tiptap#1689]
**Description**
Click the button to add a custom component, an error occurs

**Steps to reproduce the bug**
1. Use nodeview to implement custom components
2. Control with one button
3. Click and error occurs

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:

* React: https://codesandbox.io/s/musing-dubinsky-ziwhw?file=/src/App.tsx

**Expected behavior**
click button and create the custom components

**Screenshot, video, or GIF**
![image](https://user-images.githubusercontent.com/19390707/128358857-a8074250-ac96-4c77-9511-283260dd51f2.png)

**Environment?**
 - operating system: mac
 - browser: google
 - mobile/desktop: desktop
 - tiptap version:
![image](https://user-images.githubusercontent.com/19390707/128358982-b037c6ee-96bd-45c0-ac15-8ca84f0d1c8d.png)

**Comment by philippkuehn** [comment]
seems to be the same issue as #1520
