### ISSUE TITLE
Editor is stealing click events of Nodeview contents

### ISSUE THREAD

**Issue by jetacpp** [ueberdosis/tiptap#1694]
**Description**
I am using tiptap editor with `@tiptap/vue-2` Nodeview components. For simple elements like `button` they emit `click` events fine. However, for elements like dropdown menu, the dropdown items won't emit `click` events when clicked. When clicked, it seems the click event goes straight to the editor, making it in focus. Interestingly, in the example I created where a button is a dropdown menu item, it is possible for it to emit `click` event if you just click `right at the border` of the button.

Edit 1: I tried setting z-index, various css classes, etc.. but couldn't make this behavior goes away.

Edit 2: If I set the editor to `readonly` then the click events on dropdown menu are emitted as expected.

**CodeSandbox**
https://codesandbox.io/s/kind-kilby-p53lf

**Expected behavior**
When dropdown menu item is clicked, a message should be logged to the console.

**Versions**
    "@tiptap/starter-kit": "2.0.0-beta.89",
    "@tiptap/vue-2": "2.0.0-beta.42",
    "@vue/cli-plugin-babel": "4.1.1",
    "bootstrap-vue": "2.21.2",
    "vue": "^2.6.11"

**Comment by philippkuehn** [comment]
Try adding `contenteditable="false"` to your `<b-dropdown>` tag.

**Comment by jetacpp** [comment]
`contenteditable="false"` has solved the issue. Thank you very much @ :)
