### ISSUE TITLE
Editor state inconsistent if calling command from BubbleMenu?

### ISSUE THREAD

**Issue by sabetAI** [ueberdosis/tiptap#1696]
**Description**
I'm trying to set the current selection in the editor with `editor.commands.setTextSelection(to)`. The editor's `state.selection.from` successfully updates if I click on `complete` from the menu bar, but from the bubble menu. For some reason, the editor state is inconsistent inside my `eventListener` callback when I call it from the bubble menu.

**Steps to reproduce the bug**
1. Select text
2. Tap 'complete' button in BubbleMenu and selection is replaced (unexpected behaviour). 
3. Tap 'complete' in the menu bar, and text is appended after the selection (expected behaviour).

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:

* React: https://codesandbox.io/s/zen-wildflower-rf07g?file=/src/index.js

**Expected behavior**
Selection is changed, text is appended after selection (as when tapping complete button in menu bar with selection)

**Environment?**
 - operating system: windows
 - browser: chrome
 - mobile/desktop: desktop
 - tiptap version: 2.0.0

**Comment by philippkuehn** [comment]
Strange, I’m not sure what the exact problem is but it’s working fine if you use `editor?.commands.focus(to);` instead of `editor?.commands.setTextSelection(to)` 🤔

**Comment by sabetAI** [comment]
Strange indeed. `focus` does work much better, but where could the bug be coming from? Also when I move `setTextSelection` more locally, ie 
```
eventSource.onopen = (e: any) => {
  editor?.commands.setTextSelection(to);
};
```
it sometimes doesn't perform the selection change properly.

**Comment by philippkuehn** [comment]
Can you please test again with the latest package versions? [That patch](https://github.com/ueberdosis/tiptap/commit/956566eaad0a522d6bc27d44594aa36d6c33f8b3) should fix some react related issues.

**Comment by sabetAI** [comment]
Bug is still there after updating, I tried both @tiptap/core@2.0.0-beta.96 and beta.99.

**Comment by philippkuehn** [comment]
This seems to be working fine in the latest version.
