### ISSUE TITLE
setContent emits update always when there is a node view

### ISSUE THREAD

**Issue by dstoyanoff** [ueberdosis/tiptap#1715]
**Description**
I have an initial content that I set asynchronously using setContent. According to the doc, the emitUpdate is equal to false by default. I have tried omitting or setting it to false, but it both cases I actually get the update event. 

**Additional context**
Similar issue is reported here, so it might be related - https://github.com/ueberdosis/tiptap/issues/1608

**Comment by philippkuehn** [comment]
can you please a codesandbox for it?

**Comment by dstoyanoff** [comment]
Can't really reproduce anymore. Seems it got fixed.
