### ISSUE TITLE
Provide methods to easily convert extensions to/from a JSON serializable version

### ISSUE THREAD

**Issue by jamesopti** [ueberdosis/tiptap#1718]
**The problem I am facing**
I’m always frustrated when … I need access to my Tiptap extension schema on the server (Hocuspocus or my own API) when the extensions all live in my client package.

The goal is to be able to create documents on the server side with some initial content, which leverages the `prosemirrorJSONToYDoc` utility, which requires the schema.

**The solution I would like**
A method like `getSchemaJSON(extensions)` and `extensionsFromJSON(jsonSchema)`.

These methods would still need to be run in a browser environment, but having them would make it easy to checkin a copy of the JSON or serve it from an endpoint and then consume it somewhere else.

**Alternatives I have considered**
We've implemented this by hand and it works, but it feels a little brittle:

```ts
import { getSchema } from '@tiptap/core'

export const getSchemaJSON = (extensions) => {
  const { spec } = getSchema(extensions)
  const marks: any[] = []
  const nodes: any[] = []

  spec.marks?.forEach((key: string, value: any) => {
    marks.push({
      name: key,
      ...value,
    })
  })

  spec.nodes?.forEach((key: string, value: any) => {
    nodes.push({
      name: key,
      ...value,
    })
  })
  return {
    topNode: spec.topNode,
    marks,
    nodes,
  }
}
```

```ts
import { Node, Mark } from '@tiptap/core'

export const extensionsFromJSON = (jsonSchema) => {
  return [
      ...jsonSchema.marks.map((mark) => Mark.create(mark)),
      ...jsonSchema.nodes.map((node) => {
        const { attrs = {}, ...rest } = node
        return Node.create({ ...rest, addAttributes: () => attrs })
      }),
    ]
}
```

**Comment by hanspagel** [comment]
Thanks for sharing! The problem with this is, that it’ll never be a full schema export. I’l keep this in my mind, but for now we don’t plan to add this to the core because we’re afraid to confuse people with it and it doesn’t feel complete.

I know you need this for the collaborative editing part, and I’ll definitely provide a proper solution for that problem at some point.
