### ISSUE TITLE
[Vue warn]: injected property "decorationClasses" is a ref and will be auto-unwrapped

### ISSUE THREAD

**Issue by jloganolson** [ueberdosis/tiptap#1719]
**Description**
Using node view wrapper with Vue 3.2 (just released) and get this warning:

> [Vue warn]: injected property "decorationClasses" is a ref and will be auto-unwrapped and no longer needs `.value` in the next minor release. To opt-in to the new behavior now, set `app.config.unwrapInjectedRef = true` (this config is temporary and will not be needed in the future.

**Steps to reproduce the bug**
1. Upgrade to latest view
2. Use node view wrapper

**Expected behavior**
No warning

**Comment by philippkuehn** [comment]
This is a generel warning of your Vue app. Follow its instructions to disable it. When Vue 3.3 is out I’ll make the necessary changes.

**Comment by emmanuelgeoffray** [comment]
It's fixed by adding the line in `src/main.ts` 

```
const app = createApp(App)

app.mount('#app')

// fix warning injected property "decorationClasses" is a ref and will be auto-unwrapped
// https://github.com/ueberdosis/tiptap/issues/1719
app.config.unwrapInjectedRef = true
```

**Comment by segevfiner** [comment]
@philippkuehn Vue 3.3 is out. Can you make sure that the code is correct for it?
