### ISSUE TITLE
Keyboard shortcuts do not work for non-latin languages

### ISSUE THREAD

**Issue by Zanzavar** [ueberdosis/tiptap#172]
I noticed that when my keyboard language is set to Greek, the default shortcuts for marks (e.g. Ctr+B, Ctr+U, Ctr+I) do not apply. The default contenteditable html element supports these shortcuts in all languages. Also popular text editors (Google docs, Word e.t.c) support this behavior. Would it make sense to bind to a key code instead of a character to avoid this issue?

See also:
https://discuss.prosemirror.net/t/key-bindings-for-non-english-keyboard-layouts/963

**Comment by inpakeo** [comment]
+++++
