### ISSUE TITLE
Emoji extensions with images and copy/paste support

### ISSUE THREAD

**Issue by Pavel-Son** [ueberdosis/tiptap#1723]
### Discussed in https://github.com/ueberdosis/tiptap/discussions/1722

<div type='discussions-op-text'>

<sup>Originally posted by **Pavel-Son** August 12, 2021</sup>
Hi there! I would like to make an extension with emojis as picture support and already got some progress but, there are many issues I'm facing.

Here is emoji extension now.
``` javascript
let emojiService: EmojiService
export default Node.create({
  onBeforeCreate() {
    emojiService = getEmojiService()
  },
  name: 'emoji',
  group: 'inline',
  inline: true,
  selectable: false,
  atom: true,
  content: 'text*',

  addAttributes() {
    return {
      text: {},
      emoji: {}
    }
  },

  parseHTML() {
    return [
      {
        tag: 'span[text]',
      },
    ]
  },

  renderHTML({ HTMLAttributes }): any {
    if (!HTMLAttributes.text) {
      return [
        'span', {}, ''
      ]
    }
    const emoji = emojiService.findEmoji(HTMLAttributes.text)
    if (!emoji) {
      return [
        'span', 0
      ]
    }
    return [
      'span',
      {
        class: 'tm-emoji',
        style: `
          padding: 2px;
          background-position: ${emoji.getPosition()}
        `,
        text: emoji.native,
      },
      emoji.native,
    ]
  },

  addCommands(): any {
    return {
      setEmoji: (emoji: any) => ({ commands }: any) => {
        commands.insertContent(
          {
            type: 'emoji',
            attrs: {
              emoji,
              text: emoji.native
            }
          }
        )
      },
    }
  },

  addInputRules() {
    return [
      nodeInputRule(
        emojiService.getEmojiShortnameRegexp(true),
        this.type,
        match => emojiService.inputRuleHandler(match)
      ),
      nodeInputRule(
        emojiService.getEmojiRegexp(true),
        this.type,
        match => emojiService.inputRuleHandler(match)
      ),
    ]
  },

  addPasteRules() {
    return [
      nodePasteRule(
        emojiService.getEmojiShortnameRegexp(false, true),
        this.type,
        (match: string[]) => emojiService.emojiPasteRule(match),
        (match: string) => {
          return !!emojiService.findEmoji(match)
        }
      ),
      nodePasteRule(
        emojiService.getEmojiRegexp(false, true),
        this.type,
        (match: string[]) => emojiService.emojiPasteRule(match),
        (match: string) => {
          return !!emojiService.findEmoji(match)
        }
      )
    ]
  }

})
```

1. I get pretty well working input/paste rules but, when you type something like :qweqweqweqw: it would be an empty emoji
2. Emojis wouldn't copy and paste in any other source but could be pasted
3. cursor might fall into emoji sometimes
4. when you add emoji as last symbol there is no way to click on line below to activate editor</div>

**Comment by philippkuehn** [comment]
1. you have to allow only a set of names
2. you can define a [`renderText` method](https://github.com/ueberdosis/tiptap/blob/812c49bcb1de0c461edcfb069904faa23117a0d4/packages/extension-mention/src/mention.ts#L113-L118) so your atom node could be copied as plain text.
3. not sure about this one
4. maybe you can append a space or something with [appendTransaction](https://prosemirror.net/docs/ref/#state.PluginSpec.appendTransaction) if a emoji is the last node in a document. maybe a decoration could help too.

**Comment by Pavel-Son** [comment]
> 3\. sure

Hi, @philippkuehn Thanks for your help!
Point 2 works just perfectly here. Also it fix point 3 somehow
Could you please clarify a bit about point 1?

**Comment by philippkuehn** [comment]
There is an [offical emoji extension](https://tiptap.dev/api/nodes/emoji) with these features so I'm closing this.
