### ISSUE TITLE
List on backspace lift into the previous element 

### ISSUE THREAD

**Issue by castroCrea** [ueberdosis/tiptap#1735]
**Description**
On backspace below the list, the current children are inserted into the list on top of it

https://user-images.githubusercontent.com/20707343/129735110-55e1e412-5341-4372-b050-bc5a8ff91af2.mov

**Steps to reproduce the bug**
1. Start a list
2. Enter
3. Backspace
4. Enter

**CodeSandbox**
https://tiptap.dev

**Expected behavior**
The content of the children below is merged with the content of the last child on the list.

The actual behavior is more a TAB behavior

**Comment by philippkuehn** [comment]
That’s the default behavior of [`joinBackward` in ProseMirror](https://prosemirror.net/docs/ref/#commands.joinBackward). You can add a custom command for that but I have no plans to overwrite that ProseMirror core command for now.
