### ISSUE TITLE
Issue with v-model example in docs

### ISSUE THREAD

**Issue by bensoutendijk** [ueberdosis/tiptap#1736]
I was looking over [this line](https://github.com/ueberdosis/tiptap/blob/0488479d6801bac7964a0e05e90cacf7a6bb11c8/docs/src/demos/Guide/GettingStarted/VModel/Editor.vue#L33) in the docs and found that it always will evaluate to `true` since the `toString()` method will just return `[object Object]` for both sides of the comparison. This will break the v-model since it will never update editor content.

I found that there is no need to compare if the new value and the current value are equal. The watch function used for the value when setting up v-model can simply be

```
value(value) {
  this.editor.commands.setContent(value, false);
},
```

If for some reason we did want to perform a comparison one should probably use the lodash libraries `_.isEqual()` function

**Comment by julesjanssen** [comment]
In my testing, the `isSame` check definitely is needed. Otherwise, the editor content would constantly be set by the watcher, which would position the cursor at the end of the content on every change.

**Comment by philippkuehn** [comment]
You are right. You have to use `JSON.stringify` instead of `toString`. Fixed it in the docs.
