### ISSUE TITLE
If multiple paragraphs are selected, consecutive blockquote commands nest, they don't toggle

### ISSUE THREAD

**Issue by boutell** [ueberdosis/tiptap#175]
As seen here:

https://tiptap.scrumpy.io/

If you clear the editor and type a few lines of text (with breaks), i.e. paragraphs, then select all of the text and click the blockquote icon twice, the blockquotes are nested.

If you do this with just one line of text, the blockquote toggles on and off.

There appears to be no way to un-nest once you nest blockquotes, so my assumption is that this is not intentional behavior.

The code block icon appears to toggle properly in this situation. This may be because blockquote uses `toggleWrap` and code block uses `toggleBlockType`. I can see why it needs to wrap, since the paragraphs need to continue to be paragraphs while inside the blockquote.

**Comment by boutell** [comment]
(Thank you very much for creating Tiptap! We just finished a sprint integrating it into version 3.x of ApostropheCMS, an all-js open source CMS that will use Vue for the admin interface in this forthcoming 3.x release.)

**Comment by Chrissi2812** [comment]
This seem to only happen if you select all (CTRL + A) if manually selecting text via drag the toggle works.
So when state.selection is `AllSelection` it doesn't work but with `TextSelection` it works.

**Comment by hanspagel** [comment]
Thanks for reporting @boutell! We (finally) fixed this in the upcoming [tiptap v2](https://blog.ueber.io/post/our-plan-for-tiptap-2/). 🙌
