### ISSUE TITLE
Allow wildcards when checking attributes in isActive 

### ISSUE THREAD

**Issue by jamesmoss** [ueberdosis/tiptap#1752]
**The problem I am facing**
We're using `TextStyle` as a base to build our own custom font color plugin and picker. It looks like this:

![](https://p192.p3.n0.cdn.getcloudapp.com/items/NQuYgro8/9d4d9d47-260c-458d-bd8d-46ec87f18a49.jpg?v=7ed951e04375efa0be011d799a42d94e)

If any color is set on some text, we want to show the color icon as active on the bubble toolbar. Right now when using `isActive`, the attributes are only tested for equality. e.g `editor.isActive('textStyle', { fontColor: 'red' })`

We're also using `TextStyle` as a base for a few other custom plugins so just checking `editor.isActive('textStyle')` isn't specific enough.

**The solution I would like**
It'd be great if we could pass a regex here, and do something like:

```
editor.isActive('textStyle', { fontColor: /.*/ })
```

**Alternatives I have considered**
Right now we'll have to do something like:

```
editor.isActive('textStyle', { fontColor: 'red' })
  && editor.isActive('textStyle', { fontColor: 'blue' })
  && editor.isActive('textStyle', { fontColor: 'green' })
  ...etc
```

But I'm not sure what the performance implications are, and it doesn't scale well if you have more than a handful of attributes to check.

**Comment by hanspagel** [comment]
Thanks for the feature request!

Just so you know, you can probably switch out your custom extension with our official extension (released today):

https://www.tiptap.dev/api/extensions/color/

**Comment by jamesmoss** [comment]
@hanspagel I saw that and looked at using it but we have some other more custom requirements, e,g we don't save the hex codes on the mark, instead we use a named constant than can render differently depending on the situation.

**Comment by philippkuehn** [comment]
I think that’s a great feature request. I’ve added support for regex.

**Comment by domnantas** [comment]
It is also possible with 
```js
const isColorSer = !!editor.getAttributes('textStyle').color
```

But I agree `isActive()` with regex might be a cleaner solution
