### ISSUE TITLE
After shouldShow parameter for FloatingMenu and BubbleMenu fix, the BubbleMenu is mounted on load

### ISSUE THREAD

**Issue by atulmy** [ueberdosis/tiptap#1765]
**The problem I am facing:**
After recent upgrade to latest "@tiptap/react" and "@tiptap/core", when the editor loads, the bubble menu is not by default hidden.

Even with following code, it is mounted for a split second on load of editor:
```
<BubbleMenu
  shouldShow={({ editor }) => {
    return editor &&
      editor.state &&
      editor.state.selection &&
      editor.state.selection.content()
      ? editor.state.selection.content().size > 0
      : false
  }}
/>
```

**The solution I would like:**
By default `shouldShow` should return false to make it hidden until the value is computed.

**Dependencies:**
"@tippyjs/react": "^4.2.5",
"@tiptap/core": "^2.0.0-beta.99",
"@tiptap/extension-bubble-menu": "^2.0.0-beta.29",
"@tiptap/react": "^2.0.0-beta.60",

**Comment by philippkuehn** [comment]
I can’t reproduce this on https://www.tiptap.dev/examples/menus.

Can you create a codesandbox for this issue please?

**Comment by atulmy** [comment]
Thanks for looking into it, I was able to for now find a naive work around (due to lack in knowledge of internal workings of Tiptap/Codemirror) by moving BubbleMenu after the Editor in the DOM sequence:

From:
```
<BubbleMenu />
<Editor editor={editor} />
```

To:
```
<Editor editor={editor} />
<BubbleMenu />
```

😅
