### ISSUE TITLE
generateHTML() doesn't escape all special characters

### ISSUE THREAD

**Issue by andy-zhou** [ueberdosis/tiptap#1767]
**Description**
`generateHTML()` function only escapes three of the five special XML characters, `>`, `<`, and `&`. It does not escape `'` and `"`.

**Steps to reproduce the bug**
See CodeSandbox

**CodeSandbox**
https://codesandbox.io/s/dazzling-mirzakhani-yfy8o?file=/src/index.ts

**Expected behavior**
- `'` is escaped as `&#39`.
- `"` is escaped as `&quot`.
- `>` is escaped as `&gt`.
- `<` is escaped as `&lt`.
- `&` is escaped as `&amp`.

**Comment by philippkuehn** [comment]
What problem have you encountered? Tiptap uses the native `innerHTML` to return the HTML. I think you should escape that string by yourself, according to your requirements.

**Comment by andy-zhou** [comment]
Thanks for the reply!

I'm uploading the generated HTML text into a system that requires all text nodes have the above special characters escaped.

I first tried to escape them by extending the text extension, but ran into trouble because the escape string would in turn be escaped. So `'` gets escaped to `&#39;` which in turn gets escaped to `&amp;#39;`.

I also can't do a direct replace because they have semantic meaning within XML - a direct string replacement on `<tag html-attribute='foo' />` creates nonsense.

My current workaround is to parse the generated HTML, traverse the tree, and modify all the text nodes. This felt like a lot of hoops to jump through for something relatively simple.

Note, this only applies to special XML characters, since they have semantic meaning. Anything else can just be directly replaced.

**Comment by hanspagel** [comment]
The function outputs perfectly valid HTML and that’s all I’d say is in the scope of our project.

Like Philipp said, that’s a special requirement of your setup and unfortunately it’s on you to find a solution to that special requirement. ✌️

**Comment by Haraldson** [comment]
I have the opposite problem right now in the Link extension, where those characters _are_ being replaced with htmlentities inside of href attributes. Will continue investigating – but please do let me know if this is a known issue.
