### ISSUE TITLE
Resizable Editor

### ISSUE THREAD

**Issue by alexanderkraemer** [ueberdosis/tiptap#1774]
**The problem I am facing**
One thing that I'm really missing is a resizable editor. E.g. Being able to drag the botton of the editor and make the textarea bigger.

**The solution I would like**
This can be done IMHO like Githubs Editor. Simple corner dragging like the default textarea of html5 is also able to do.
Thanks!! :) 

**Alternatives I have considered**
I've tried around with multiple classes declaring the size of the editor, but it's not a nice UX in any way.

Thank you for this great product!

**Comment by cadars** [comment]
Something like this? https://developer.mozilla.org/en-US/docs/Web/CSS/resize

**Comment by alexanderkraemer** [comment]
yep exactly!
