### ISSUE TITLE
Cursor working incorrectly with string nodes in Firefox

### ISSUE THREAD

**Issue by Pavel-Son** [ueberdosis/tiptap#1778]
**Description**
If you have node like mention without any text before or after it you would be able to move cursor before the node if the first case and after node in second

**Steps to reproduce the bug**
1. Go to https://www.tiptap.dev/examples/suggestions/
2. Delete all text **before** mention
3. Try to move cursor to the left

1. Go to https://www.tiptap.dev/examples/suggestions/
2. Delete all text **after** mention
3. Try to move cursor to the right

**Comment by philippkuehn** [comment]
This is a bug in firefox. See: https://github.com/ProseMirror/prosemirror/issues/1091

**Comment by rfgamaral** [comment]
I've left a comment in the upstream issue, but I'll leave it here as well:

I was not able to reproduce the upstream issue (following the upstream issue "steps to reproduce") on my Firefox v94 (beta), but I can't say the same for tiptap, that one I can successfully reproduce with the official suggestions example.

Not sure if some sort of workaround was implemented on ProseMirror...
