### ISSUE TITLE
Collaboration Extension Removes Entire Document On Undo

### ISSUE THREAD

**Issue by SebTota** [ueberdosis/tiptap#1786]
**Description**
When using the Collaboration extension, the history allows the user to undo the entire documents text.

**Steps to reproduce the bug**
1. Go to https://codesandbox.io/s/sbdbm
2. Click in the first (top) editor and do not type anything
3. Click (CMD/Ctrl + Z) to undo
4. Issue: Entire document text is deleted

**CodeSandbox**
An existing CodeSandbox from hanspagel: https://codesandbox.io/s/sbdbm

**Expected behavior**
When setting the content of the editor as it is being created, the undo history should not include the initial setting of the editor text. It should instead work like the regular History extension that does not allow a user to undo past the initial content set when creating the editor. 

**Screenshot, video, or GIF**

https://user-images.githubusercontent.com/25122511/130623223-d4aad61b-3c66-4408-9131-ee999d2b9bba.mov

**Environment?**
 - operating system: Mac OS
 - browser: Safari/Chrome
 - mobile/desktop: Desktop
 - tiptap version: 2.0.0

**Additional context**
This issue can cause a complete loss of text that neither user can redo to add it back (as shown in the video). For example if
User 2: Starts typing
User 1: Click undo (this will undo the initial document content)
User 2: Keeps trying

Result: The entire document is deleted and the history will not allow you to redo the deleted text due to User 2's new addition of text.

**Comment by BrianHung** [comment]
In production usage, try https://discuss.yjs.dev/t/exclude-initial-loading-step-from-transcript-history/519.

**Comment by SebTota** [comment]
Thanks for the reply @BrianHung. That solution seems to be right in line with [this](https://github.com/yjs/yjs-demos/issues/16) solution discussed on the yjs demo GitHub repo. Unfortunately I'm limited by this solution and wouldn't be able to use it because, at least from my understanding and testing, I wouldn't be able to save/load the content as HTML which is a requirement for me.

**Comment by BrianHung** [comment]
You might be able to do: `HTML` -> Prosemirror `Node` -> yjs, and then `yjs` -> Prosemirror `Node` -> `HTML`.

**Comment by SebTota** [comment]
@BrianHung That was a great idea and exactly what solved it for me! Thank you!

**Comment by Mickls** [comment]
This is how I solved it, maybe it can help other friends who have the same problem
```typescript
onCreate: ({ editor }) => {
  xxx...
  const undoManager = yUndoPluginKey.getState(editor.state).undoManager;
  undoManager.clear();
}
```
