### ISSUE TITLE
Array.flat is not supported on older versions of safari

### ISSUE THREAD

**Issue by Druthi** [ueberdosis/tiptap#1793]
**Description**
You have used `Array.flat` in your code which is breaking in older versions of safari which is resulting in the editor instance not being created. 

**Steps to reproduce the bug**
1. Open Safari version 11.1
1. Go to quizizz.com/admin
2. Click on `Create` button and create a lesson
3. When you get to the lesson editor, try to edit the input text. It will not be possible because ProseMirror was not created.
 

**CodeSandbox**
This is a SodeSandbox which I found which did not work on safari 11.1 as well. 
https://codesandbox.io/s/nested-blocks-tkicz?file=/src/components/Tiptap.vue

**Expected behavior**
Should be able to edit the text in the lesson editor

**Environment?**
 - browser:Safari 11.1
 - mobile/desktop:Desktop
 - tiptap version:^2.0.0-beta.85

**Comment by philippkuehn** [comment]
With tiptap we are following the [best practices of browserlist](https://github.com/browserslist/browserslist#best-practices) for browser support. Safari 11 seems to be too old so you have to add some polyfills by yourself.
