### ISSUE TITLE
Nested node be able to read parent (Not extended) node attributes

### ISSUE THREAD

**Issue by guihig** [ueberdosis/tiptap#1807]
**The problem I am facing**
I can't render a Mention like node items based on parent node (its inside an Vue Node View) attribute.

Maybe i just dont find any way to do this.

**The solution I would like**
What i'm trying to do is to create a node similar to Mention that renders one list of suggestions when it is on the topNode and another list of suggestions when its inside another node (in this case a Vue Node View), and this list of suggestions is based on the Vue Node View attributes.

**Alternatives I have considered**
For now i'm stuck, maybe ill have to create a global state that changes based on the editor focus, but i dont know.

**Additional context**
Add any other context or screenshots here.

**Comment by philippkuehn** [comment]
The [array of items can be async](https://tiptap.dev/api/utilities/suggestion#items) so you can render different items based on the parent node.
