### ISSUE TITLE
Dynamic attributes addition at run time to the editor 

### ISSUE THREAD

**Issue by mahendrushivam** [ueberdosis/tiptap#1814]
I am trying to build a query builder using tiptap as vase wrapper over prossmirror , wanted to know if u can share some example wrt the adding dynamic span entries to the editor when a user selects something from the popper menu , and a way of using ur wrapper around this to create dynamic html attributes entries.

**Comment by hanspagel** [comment]
Would you mind to elaborate what you try to achieve? I don’t really understand what you need.

Registering new attributes is changing the schema and is basically the same request as #1044.

But maybe reading this is all you need: https://www.tiptap.dev/guide/custom-extensions#attributes

**Comment by philippkuehn** [comment]
Out of scope for now.
