### ISSUE TITLE
It doesn't seem possible to add twice the mention extension on the editor 

### ISSUE THREAD

**Issue by GitHubish** [ueberdosis/tiptap#1816]
Until today I added to Tiptap twice the Mention extension configured differently (@ and #, the first with spaces allowed, not for the second). But since the update of the package ("@tiptap/core": "^2.0.0-beta.102")  when I add the plugin twice, I get this message: 
`ERROR RangeError: Adding different instances of a keyed plugin (mention$)`

How is this possible? How else?
Thanks

**Comment by GitHubish** [comment]
Here is an example with the Angular Framework implementation (by @sibiraj-s ) where the problem occurs :  [stackblitz example](https://stackblitz.com/edit/ngx-tiptap-mentions-owzctg?file=src%2Fapp%2Fapp.component.ts)

**Comment by hanspagel** [comment]
You can add `pluginKey` to the suggestion utility to separate those two.

https://prosemirror.net/docs/ref/#state.PluginKey

**Comment by GitHubish** [comment]
@hanspagel Ah great thanks indeed it was just that. I didn't see that I could change it. Thanks for your responsiveness for this really cool editor!
