### ISSUE TITLE
isActive can not use in a custom node

### ISSUE THREAD

**Issue by adou2236** [ueberdosis/tiptap#1819]
I registered a custom-node(inline:false), but isActive('custom-node) is true only focusing, it will become invalid when the editor unFocus,but like image or table is fine

**Comment by hanspagel** [comment]
Provide a codesandboc please

**Comment by adou2236** [comment]
> Provide a codesandboc please

http://8.131.54.184:8080/demo/index.html

**Comment by adou2236** [comment]
> Provide a codesandboc please

like this http://8.131.54.184:8080/demo/index.html
chart message can show only when it focused not like table or image
