### ISSUE TITLE
updateAttributes error

### ISSUE THREAD

**Issue by adou2236** [ueberdosis/tiptap#1828]
**Description**
it report "RangeError: Invalid content for node type custom-chart"
![image](https://user-images.githubusercontent.com/57088340/131772055-d38fcaae-9c6f-4061-8e9d-435afe68695e.png)

**Steps to reproduce the bug**
1. regist a custom-chart node
2. update it's attrs

but editor.isActive('custom-chart') is return true

**Comment by hanspagel** [comment]
codesandbox please
