### ISSUE TITLE
TypeScript Error: Declaration or statement expected.

### ISSUE THREAD

**Issue by Newtchuck** [ueberdosis/tiptap#1835]
**Description**
I have a Typescript error when I try to run my app. 

```Declaration or statement expected.  TS1128

    1 | import { StarterKit } from './starter-kit';
  > 2 | export type { StarterKitOptions } from './starter-kit';
      | ^
    3 | export default StarterKit;
    4 |
```

**Steps to reproduce the bug**
1. Go to …
2. Type in …
3. Click on …
4. See error message

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:

* Vue: https://codesandbox.io/s/tiptap-issue-template-b83rr?file=/src/components/Tiptap.vue
* React: https://codesandbox.io/s/tiptap-react-08yxr

**Expected behavior**

**Screenshot, video, or GIF**
<img width="465" alt="Capture d’écran 2021-09-02 à 15 20 52" src="https://user-images.githubusercontent.com/11087638/131850994-4ad435b7-8a1e-4a51-9490-3288c3e01d1e.png">

**Environment?**
 - operating system: MacOS
 - browser: Chrome
 - mobile/desktop: Desktop
 - tiptap version: V2

**Additional context**

**Comment by hanspagel** [comment]
Looks like you have an old TypeScript version that doesn’t support that type export. Try upgrading to 3.8 or newer.
