### ISSUE TITLE
The HardBreak extensions does not preserve line breaks in format text/plain

### ISSUE THREAD

**Issue by damingo** [ueberdosis/tiptap#1842]
**Steps to reproduce the bug**
1. Go to https://www.tiptap.dev/api/nodes/hard-break/#hardbreak and select & copy the text in the example editor.
2. Inspect the content of the clipboard by pasting it here: https://evercoder.github.io/clipboard-inspector/
3. The clipboard content for format text/plain is 
> Thisisasingleparagraphwithlinebreaks.

**Comment by philippkuehn** [comment]
Hey, it’s the same behavior at https://prosemirror.net/ so it’s not a bug with tiptap itself. 

What you can do for now is to define a custom `renderText` method for the `HardBreak` extension:

```js
const CustomHardBreak = HardBreak.extend({
  renderText() {
    return '\n'
  },
})
```

**Comment by damingo** [comment]
That's an elegant solution. Thank you!

**Comment by philippkuehn** [comment]
I decided to put that into the extension!

**Comment by jonjieviduya** [comment]
> I decided to put that into the extension!

@philippkuehn How can we use it now in the extension? it says "Duplicate extension names found [hardBreak]"
