### ISSUE TITLE
How to use method getMarkAttrs to get URL of a link in tiptapV2 ?

### ISSUE THREAD

**Issue by Cephou** [ueberdosis/tiptap#1843]
In tiptap V1, I used to import a method "getMarkAttrs" in a v-slot and use it to get properties of a mark (href of a link in order to modify it for example). In the current documentation ([Links](https://www.tiptap.dev/api/marks/link) for example), I haven't found examples to do that. Is is something that has been removed in tiptapV2 ?

Thanks in advance for your help.

**Comment by philippkuehn** [comment]
use `editor.getAttributes('link')` for that.

**Comment by Cephou** [comment]
Thanks for the advice, philipp ! :)
