### ISSUE TITLE
Editor deletes \t character on given html

### ISSUE THREAD

**Issue by ElHex** [ueberdosis/tiptap#1844]
**Description**
I'm importing into the editor a custom html I had from quill, on this html I use the \t character to allow the user to use tabs, the tabs dissapear.

**Steps to reproduce the bug**
1. Load editor
2. Set HTML with \t characters on it
3. See results

**Expected behavior**
\t character is on the DOM and its affected by CSS tab-size property.

**Screenshot, video, or GIF**
![image](https://user-images.githubusercontent.com/52222397/132140239-8c98a3f4-c5db-42f8-a84c-563306d4859a.png)

**Environment?**
 - operating system: Windows 10
 - browser: Chrome
 - mobile/desktop: Desktop
 - tiptap version:  2.0.0-beta.102

**Comment by philippkuehn** [comment]
Try using custom parse options:

```js
new Editor({
  parseOptions: {
    preserveWhitespace: 'full',
  },
  // ...
})
```

**Comment by EvitanRelta** [comment]
Btw, for anyone having this problem with `editor.commands.setContent` like me, 
you also need to pass `preserveWhitespace: 'full'` in the optional `parseOptions` 3rd argument of `setContent`:

```js
editor.commands.setContent(
  ...,
  ...,
  { preserveWhitespace: 'full' }
)
```
