### ISSUE TITLE
CollaborationCursor: disable highlighting

### ISSUE THREAD

**Issue by hanspagel** [ueberdosis/tiptap#1852]
### Discussed in https://github.com/ueberdosis/tiptap/discussions/1851

<div type='discussions-op-text'>

<sup>Originally posted by **wagnerpaz** September  6, 2021</sup>
Hey guys!

I need to modify the collaboration cursors to accomplish some business requirements.
What I need is to disable the highlighting for users without permission.
I managed to disable cursor caret and cursor label, by overwriting the render function of CollaborationCursor plugin, but looking in the source I can't find where it handles highlighting.

Can you help me? thanks!</div>

**Comment by nc** [comment]
+1 related I would like to customise the exact colour used by the highlighting. I too couldn't find where the highlighting happens in the source btw.

**Comment by jpobley** [comment]
`CollaborationCursor` passes the value of its `user` option directly to the Yjs awareness provider [here](https://github.com/ueberdosis/tiptap/blob/main/packages/extension-collaboration-cursor/src/collaboration-cursor.ts#L73). After that, the highlighting is an [inline decoration](https://prosemirror.net/docs/ref/#view.Decoration^inline) created by [`y-prosemirror/cursor-plugin`](https://github.com/yjs/y-prosemirror/blob/master/src/plugins/cursor-plugin.js#L62).

Yjs Awareness is flexible enough to put pretty much any value into the state, but nothing will happen unless `y-prosemirror/cursor-plugin` knows to look for it. At the moment, it only looks for `user.color` and `user.name`. 

A PR for `y-prosemirror` that adds support for a `user.highlight` attribute, falling back to `user.color`, would be straightforward enough to put together. Something like:

```diff
diff --git a/cursor-plugin.js b/cursor-plugin.js
index ce7bb39..30badb9 100644
--- a/cursor-plugin.js
+++ b/cursor-plugin.js
@@ -50,6 +50,9 @@ export const createDecorations = (state, awareness, createCursor) => {
       if (user.name == null) {
         user.name = `User: ${clientId}`
       }
+      if (user.highlight == null) {
+        user.highlight = `${user.color}70`
+      }
       let anchor = relativePositionToAbsolutePosition(y, ystate.type, Y.createRelativePositionFromJSON(aw.cursor.anchor), ystate.binding.mapping)
       let head = relativePositionToAbsolutePosition(y, ystate.type, Y.createRelativePositionFromJSON(aw.cursor.head), ystate.binding.mapping)
       if (anchor !== null && head !== null) {
@@ -59,7 +62,7 @@ export const createDecorations = (state, awareness, createCursor) => {
         decorations.push(Decoration.widget(head, () => createCursor(user), { key: clientId + '', side: 10 }))
         const from = math.min(anchor, head)
         const to = math.max(anchor, head)
-        decorations.push(Decoration.inline(from, to, { style: `background-color: ${user.color}70` }, { inclusiveEnd: true, inclusiveStart: false }))
+        decorations.push(Decoration.inline(from, to, { style: `background-color: ${user.highlight}` }, { inclusiveEnd: true, inclusiveStart: false }))
       }
     }
   })
```

Then customization via TipTap is as easy as:

```js
// Custom highlight color
CollaborationCursor.configure({
    provider, // defined somewhere above here
    user: {
        name: 'Oprah Whiskers',
        color: '#1e90ff',
        highlight: 'rgba(255, 99, 71, .44)',
    }
});

// No highlight color
CollaborationCursor.configure({
    provider, // defined somewhere above here
    user: {
        name: 'Oprah Whiskers',
        color: '#1e90ff',
        highlight: 'transparent',
    }
});
```

**Comment by jpobley** [comment]
There's  actually an already open PR related to this topic: https://github.com/yjs/y-prosemirror/pull/55/files
