### ISSUE TITLE
drop `export * from '@tiptap/core';` from `@tiptap/vue-3`

### ISSUE THREAD

**Issue by fyeeme** [ueberdosis/tiptap#1857]
when build  a warning will occur:

 re-exports "Editor" from both "@tiptap+vue-3@2.0.0-beta.57 " and " @tiptap/core" (will be ignored)

I think `export * from '@tiptap/core';`' can be delete from @tiptap/vue-3, if some one need Editor ,can import from @tiptap/core, and also we can free to use useEditor in @tiptap/vue-3

**Comment by philippkuehn** [comment]
We can’t remove that import for now. The framework packages (vue & react) extend the `Editor` class, so you should not use the `Editor` export of `@tiptap/core`.
