### ISSUE TITLE
Want to add change tracking in the editor

### ISSUE THREAD

**Issue by pdmwxy** [ueberdosis/tiptap#1862]
**The problem I am facing**
It is necessary to develop the function of tracking revision similar to that in word. At present, the editor has no similar function. I hope this function can be added.

Or tell me how to implement this function

**The solution I would like**
You can track the operations of adding, modifying and deleting content in the editor:

New content: mark color

Modified content: the original content is added with a delete line and marked with color, and the new content is marked with color to indicate which original content is modified to the existing content

Delete content: instead of really deleting content, mark the deleted content with color and add a delete line.

**Additional context**
See the example
![微信截图_20210908191620](https://user-images.githubusercontent.com/29848359/132500120-1b661ddb-e143-4906-9408-b562a3fd99fb.png)

**Comment by pimmee** [comment]
I would really like this feature also. Prosemirror has [an example](https://prosemirror.net/examples/track/) of how this can be achieved.

**Comment by jamesg-rimsys** [comment]
Upvote

**Comment by pdmwxy** [comment]
> I would really like this feature also. Prosemirror has [an example](https://prosemirror.net/examples/track/) of how this can be achieved.

At present, there is no research on how to realize this function. I'm very distressed ~ ~ I hope to add this function in the new version

**Comment by Harvey-Mushman** [comment]
I too would love to see this feature added to TipTap for VueJS 3.  I have looked at the Prosemirror example, there is a lot of code there all of which is generic JavaScript... not exactly plug and play!

**Comment by pdmwxy** [comment]
Can you reply whether this function can be added?

**Comment by joppehoekstra** [comment]
Interested in this as well!

Perhaps this research could help implement this feature:
https://www.cs.ru.nl/bachelors-theses/2018/Aucke_Bos___4591496___Visulizing_differences_between_HTML_documents.pdf
https://github.com/yunabe/hdiff

**Comment by jan-schweiger** [comment]
Any updates on this one? I know a lot of people who are looking for this feature.

**Comment by Shadowfita** [comment]
This community extension exists and is a minimum viable product version of tracked changes.

https://github.com/chenyuncai/tiptap-track-change-extension

**Comment by mariatahler** [comment]
https://github.com/chenyuncai/tiptap-track-change-extension is awesome, but unfortunately not actively maintained.

@nperez0111 is there maybe a way to produce a static difference between two content versions by comparing its html?

The result should look like https://track-change.onrender.com, but just static. It would be great if this could work outside Tiptap Cloud.

**Comment by mariatahler** [comment]
Thanks a lot for your support @nperez0111. Hopefully we will see a simpler html/json version of this as a Tiptap Pro plugin in the future, so everyone can benefit from it.

**Comment by Shadowfita** [comment]
I plan on expanding upon the community extension linked above. I'll share here once I make progress.

**Comment by jan-schweiger** [comment]
I agree with @mariatahler just diffing the html would be totally enough for our use case. Unfortunately, a lot of Tiptap users don't run on Tiptap cloud right now, so this really would make a great Pro Plugin @nperez0111.

**Comment by nperez0111** [comment]
FWIW, if you plan to do this:

I would strongly recommend doing the diff in JSON rather than HTML, not only easier to traverse, but nested diffing is a difficult problem. Even diff-match-patch (the original Google Docs diff algorithm) would just ignore the structure & attempt to recreate it afterward. There just aren't many algorithms to do this sort of diffing.


Yea, understand it would be a good pro extension, our use case just didn't fit. I built it in a way that we can build a JSON only diff later & it would still work.

**Comment by jan-schweiger** [comment]
@nperez0111 I might not be much, but I would sponsor $500 personally to have an official JSON-Diff Tiptap pro extension. Traceability is super important for so many use cases.

**Comment by nperez0111** [comment]
Appreciate the desire here. We have a lot of other projects we are working on at the moment but I did bring it up with my PM. 

So don't hold your breath on it.

**Comment by jan-schweiger** [comment]
Thank you @nperez0111 for considering it. Hopefully your PM sees the importance of this feature :)
