### ISSUE TITLE
Simplify `parseHTML` method of attributes to return the value itself

### ISSUE THREAD

**Issue by philippkuehn** [ueberdosis/tiptap#1863]
**The problem I am facing**
At the moment it’s kind of repetitive to return an object within `parseHTML`.

```js
addAttributes() {
  return {
    id: {
      default: null,
      parseHTML: element => {
        return {
          id: element.getAttribute('id'),
        }
      },
      renderHTML: attributes => {
        return {
          id: attributes.id,
        }
      },
    },
  }
}
```

**The solution I would like**
It would be great to just return the value because it’s already clear that it’s all about the attribute itself.

```js
addAttributes() {
  return {
    id: {
      default: null,
      parseHTML: element => element.getAttribute('id'),
      renderHTML: attributes => {
        return {
          id: attributes.id,
        }
      },
    },
  }
}
```

**Additional context**
The initial idea was to be able to set multiple attributes within `parseHTML` but this some kind of unexpected and wasn’t needed until now so I think we can safely remove that feature.

But anyway, **this would be a breaking change** but I don't think it makes sense to build a fallback to the old behavior.

**Comment by hanspagel** [comment]
I think that’s fine. 👍️

This breaking change would probably lead to issues that are not visible at the first glance. I think we should at least add a `console.warn` when an object is returned.

**Comment by rajatsingla** [comment]
@philippkuehn Love ❤️  the work you guys are doing, can we have better notifications on breaking changes.

**Comment by igor-ye** [comment]
Hope you will not remove this feature in future versions. We also use objects stored as attributes for storing custom Vue components properties. So we have only one custom node (componentNode) rendered as <component> tag with only two attributes - is and v-bind. And only one wrapping ComponentNodeEditor.vue for choosing editor type from the list:
`<template>
	<node-view-wrapper class="component-editor">
		<a-select v-if="!componentName" :value="componentName" @change="componentSelected" placeholder="Select a block">
			<a-select-option v-for="e in blockEditors" :value="e">{{ e }}</a-select-option>
		</a-select>
		<component v-else :is="componentName" class="instance" :bindings="componentBindings" :updateProps="updateProps" />
	</node-view-wrapper>
</template>
`
So you don't need to write repetitive code in Node.create for every new component editor. Just one new MyNewCustomNodeEditor.vue which saves all props at once passing an object to updateProps.
