### ISSUE TITLE
Command to select current word, apply Bold/Link/etc on current word without it being highlighted by user.

### ISSUE THREAD

**Issue by goamn** [ueberdosis/tiptap#1864]
**The problem I am facing**
Text cursor/caret is not highlighting any text, it is in the middle of a word. I want to programmatically select the current word in order to apply Bold, Create Hyperlink, etc on it. If I can apply the Bold/Link/etc to the current word without highlighting that would be even better.

**The solution I would like**
A "selectWord()" command, similiar to "selectParentNode()"

**Alternatives I have considered**
I have tried: selectNodeForward, selectNodeBackward, createParagraphNear, setTextSelection. None of them seemed to do what I want.

**Comment by cadars** [comment]
Relevant for this use case, this discussion on the ProseMirror forum: https://discuss.prosemirror.net/t/how-to-select-whole-words/2651

**Comment by philippkuehn** [comment]
I’ll mark this as out of scope for now. You have to create a custom command for it.
