### ISSUE TITLE
Make Editor Content "splittable"

### ISSUE THREAD

**Issue by rezaffm** [ueberdosis/tiptap#1870]
**The problem I am facing**
I am currently migration from Tinymce and once I started to work on Long text versions, I realized that spellchecker tools (such as LanguageTool) go totally crazy if there are too many suggestions, mistakes et cetera. Actually, the editor becomes more or less unusable.

**The solution I would like**
I follow the "never re-invent a wheel rule" so I had a look at Google Docs to understand how they solve the issue.

Well, basically the Spellchecking is spread over the several pages. Please see screenshot below:

![image](https://user-images.githubusercontent.com/40648929/132656145-9bed7632-611e-4235-af3f-951fe0676897.png)

So, I wondered if it would be possible to make the editor content component "splittable", e.g. you only pass a flexible number of nodes to the editor content component (I hope that makes sense).

However, the component then needs to be smart enough to add (and obviously) removes pages.

If I missed something and there is a nice way to solve this without changing the Editor Content Component, I would appreciate any explanations.

**Comment by philippkuehn** [comment]
there is this package [prosemirror-pagination](https://github.com/todorstoev/prosemirror-pagination#readme).
not sure if this works with tiptap somehow.

**Comment by philippkuehn** [comment]
it’s out of scope for now.

**Comment by rajajatayu** [comment]
does [prosemirror-pagination](https://github.com/todorstoev/prosemirror-pagination#readme). works with tiptap?

**Comment by aehlke** [comment]
note google docs is moving to a continuous scroll experience

**Comment by Yab1** [comment]
Is this issue solved am working on implementing the same feature described above?

**Comment by nperez0111** [comment]
Pagination is still something we do not want to approach yet

**Comment by Yab1** [comment]
> Pagination is still something we do not want to approach yet

I understand that pagination is currently not being approached, but I am interested in exploring possible solutions for integrating pagination with TipTap. Do you have any suggestions or best practices for implementing pagination in this context? Any guidance or alternative approaches to handle large datasets with TipTap would be greatly appreciated.

Thank you!

**Comment by nperez0111** [comment]
Sorry we don't have a good answer for this, we have seen several implementations but most compromise on performance especially for larger documents. That is why we have not tried to support this yet. Editing in the web is very different from editing documents and it is very difficult to force the web to act in such a way.

Even Google with their thousands of engineers gave up on a contenteditable approach & now just use canvas for rendering Google Docs. I wish you luck, it is not an easy problem to address

**Comment by aehlke** [comment]
I hope the org considers investing in a canvas based approach even as an alternative in the future as it fits many popular requirements. I understand that's a new project but there is existing expertise.
