### ISSUE TITLE
Switch Between Bullet List To Heading

### ISSUE THREAD

**Issue by Gopigk** [ueberdosis/tiptap#1871]
I added my list after that, I try to change it to 'Heading" format. But, I couldn't change that.  Can you do this feature? It would help us to switching between List to Heading

**Comment by philippkuehn** [comment]
A list contains several nodes (ul -> li -> p). 

1. What do you expect when converting a "list" to a heading?
2. What if there are multiple list items?
3. What if there are nested lists?

**Comment by Gopigk** [comment]
If I add upto 3 or 4 bullet list items. After adding that, I'll select all the bullet list items and select Heading option button. It couldn't convert to heading with bullet list. So, I want like google docs does.

**Comment by hanspagel** [comment]
I don’t think it’s very useful what Google Docs does. 😅

![CleanShot 2021-09-10 at 17 55 24](https://user-images.githubusercontent.com/1577992/132882379-7c238f63-1057-47cb-b06b-f64ef983e7e3.png)

**Comment by Gopigk** [comment]
In tiptap, I wish to add title with bullet icon, so, what should I do for that? Do you have any idea? If you have can you share that with me? 🤝

**Comment by hanspagel** [comment]
You can configure the ListItem to allow any type of block:

```js
import ListItem from '@tiptap/extension-list-item'

const CustomListItem = ListItem.extend({
  content: '(paragraph|heading) block*',
})
```

That would mimic that part of the Google Docs behaviour, which I still don’t find very useful. Keep in mind that pressing `Enter` would still create a new list item, not a paragraph after the heading (same with Google Docs). So you would end up with a bullet list of headings.

Generally speaking, you are free to create whatever list behaviour you wish to have. Everything is there to customize that. We can just provide one way to handle lists though, that’s why I’m closing this for now as I don’t think that’s an issue with tiptap. ✌️

**Comment by Gopigk** [comment]
@hanspagel thanks for you help
