### ISSUE TITLE
Accessing extension options from editor instance

### ISSUE THREAD

**Issue by domnantas** [ueberdosis/tiptap#1873]
**The problem I am facing**
I'm trying to build heading controls. I would like it to be dynamic – if I set 6 levels in Heading options, I want 6 buttons, if I set 3 levels, I want to render 3 buttons.

**The solution I would like**
Is there any way to access Heading options from `this.editor`?

**Alternatives I have considered**
I found it's possible using
```js
this.editor.extensionManager.extensions.find(
	(extension) => extension.name === "heading"
).options.levels;
```
but it seems way too cumbersome.

**Additional context**
Here's a minimal codesandbox explaining the issue
https://codesandbox.io/s/tiptap-heading-levels-rh1sz

**Comment by philippkuehn** [comment]
Since this is a rather special requirement, I would not like to introduce another method for that. Moving that logic to its own helper method on the user side looks fine to me.

```js
function getExtensionOptions(editor, name) {
  const extension = editor.extensionManager.extensions.find(extension => extension.name === name)

  return extension.options
}
```
