### ISSUE TITLE
activeNodeOrMark() 

### ISSUE THREAD

**Issue by rezaffm** [ueberdosis/tiptap#1874]
**The problem I am facing**
I built a wonderful Editor with tiptap that replaces my old tinymce 4 editor. In that context, I use quite a lot isActive() on the Menus.

However, for long texts, this functionality drastically slows down the editor. This starts at texts with a word count of 1,000.

**The solution I would like**
So, a possible solution would be an alternative function that just returns the active node or mark type (same as isActive() without calling the function with the node or mark type).

For the moment, I reduced the isActive() call to the Menu Items that I want to have at least marked, but that's obviously not optimal.

It would be great if that call would also include the attributes.

Then, you could call this function once and pass the result to all Menu Items.

I looked at the isActive() function, and I had the impression this would (could) be possible.

**Comment by philippkuehn** [comment]
I think you are using vue 2, right? With that, there are performance issues with large documents. With vue 3 or react it is much faster.

**Comment by rezaffm** [comment]
btw, since today I am a proud sponsor of tiptap, but I always get the error "Add labels: All jobs have failed. Add labels / is-spon-label".

Not a big deal, just you know.

**Comment by philippkuehn** [comment]
I pushed [some fixes](https://github.com/ueberdosis/tiptap/commit/fcca1e6f4db273ee2f3c0a543c44738c395193a8) for that. Follow up at #1930

**Comment by rezaffm** [comment]
Thanks
