### ISSUE TITLE
Add empty svg image while pasting bulk data along with image

### ISSUE THREAD

**Issue by Gopigk** [ueberdosis/tiptap#1880]
Description
I just copy the bulk data from random browser and paste it in tiptap editor. After pasting, I can see huge space above the image.

Steps to reproduce the bug
1. Go to some random website
2. Copy the content along with image 
3. Paste it in editor you can see the space above an image file

I inspect that element and try to understand what was an issue. But, I found empty svg file. I'll attach the screenshot below

![image](https://user-images.githubusercontent.com/49271376/132952551-a5851422-e06a-464d-9ec5-20a63a631244.png)

The first image tag is empty space. The second imp tag is actual image. Looking forward for you reply and your solution

App version : 2.0.0-beta.55

**Comment by philippkuehn** [comment]
No, I can’t reproduce this with any random website. Please provide a reproducable codesandbox.

**Comment by Gopigk** [comment]
Do you want codesandbox or tiptap integrated site? Below I add the website, where I tested and integrated the tiptap 
https://tip-tap-test.vercel.app  - Here you can reproduce an error.

Else you want codesandbox, I'll work on it and send a code sandbox link also

**Comment by philippkuehn** [comment]
Can’t reproduce it. I’ve done the following:

1. open https://unsplash.com/
2. cmd+a
3. cmd+c
4. open https://tip-tap-test.vercel.app
5. cmd+v

Everything is as expected. No space above images. I’ve tried Chrome and Firefox on macOS.
