### ISSUE TITLE
Multiple locally synced editors causes schema errors

### ISSUE THREAD

**Issue by cameronmbell** [ueberdosis/tiptap#1883]
**Description**
With two or more editor instances, when trying to transpose transactions between them, the following prosemirror error is generated `Invalid content for node`. I have set up a demo to show this, when you delete content it works fine but insertion causes the error. I suspect this owes to the different schema on the editors despite the fact that they share the same editor props. [Note this error was seen here but not addressed](https://github.com/ueberdosis/tiptap/issues/74#issuecomment-434783563).  

**Steps to reproduce the bug**
1. Create two editors with the same props
2. Register a transaction listener that forwards steps between them
3. Add content
4. See error message  `Invalid content for node`

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:

* React: https://codesandbox.io/s/intelligent-currying-pmwhu?file=/src/App.js

**Expected behavior**
The transformation should succeed without error

**Screenshot, video, or GIF**
![bad-tiptap](https://user-images.githubusercontent.com/16931162/132996764-6230a862-cb20-483c-b8d3-0f5aa38a5c6a.gif)

**Environment?**
 - operating system: MS Windows 10
 - browser: Chrome 92.0.4515.159
 - mobile/desktop: Desktop
 - tiptap version: 2.0.0-beta.105

**Comment by philippkuehn** [comment]
Hey!

> Note this error was seen here but not addressed.

Yeah, there is also [a solution](https://github.com/ueberdosis/tiptap/issues/74#issuecomment-460206175) in there. With that small change [it’s working fine](https://codesandbox.io/s/prod-cherry-b47hb?file=/src/App.js).

**Comment by cameronmbell** [comment]
Thank you! I can't believe I missed that.

**Comment by sudofix** [comment]
> Hey!
> 
> > Note this error was seen here but not addressed.
> 
> Yeah, there is also an explanation and [solution](https://github.com/ueberdosis/tiptap/issues/74#issuecomment-460206175) in there. With that small change [it’s working fine](https://codesandbox.io/s/prod-cherry-b47hb?file=/src/App.js).

Thanks for this! been trying the same idea but my only problem is that if editorA has pure text and editorB has marks, textStyle and stuff like that, updating B based on adding new character to A always inserts the new char without any marks, is there a way to just include that inserted char in the same mark the last text in B?

**Comment by ewarrenG** [comment]
Is there an example that uses EditorProvider instead of EditorContent?
