### ISSUE TITLE
no color init

### ISSUE THREAD

**Issue by xuedongwang** [ueberdosis/tiptap#1884]
**Description**
no color init

![image](https://user-images.githubusercontent.com/25864625/133014022-5ec6d21c-cb57-44ec-b43c-bdfdc990c57a.png)

![image](https://user-images.githubusercontent.com/25864625/133014054-a1546c4d-4313-4602-87b1-52e301412271.png)

expected

![image](https://user-images.githubusercontent.com/25864625/133014102-13d2d387-e9cc-41f7-b75f-833afde25bf5.png)

**Comment by philippkuehn** [comment]
provide a codesandbox.

**Comment by sereneinserenade** [comment]
This is same as #1818
