### ISSUE TITLE
Keyboard shortcut for adding a link

### ISSUE THREAD

**Issue by hermann-san** [ueberdosis/tiptap#1886]
**The problem I am facing**
I often use links in text and there appears to be no keyboard shortcut for this by default, according to the [docs](https://www.tiptap.dev/api/keyboard-shortcuts/#text-selection).

**The solution I would like**
Microsoft Office, LibreOffice and some browser based editors use the control + k  keyboard shortcut to add a hyperlink to a text or word. I think that would be a good choice to have it available by default.
I'm aware that one could also customize the keyboard shortcuts in tiptap, but I find this one a rather common shortcut that would benefit many users.

**Comment by philippkuehn** [comment]
tiptap comes without any UI. that’s why there is no shortcut for adding links by default. There is also a hint at the link extension page.

https://www.tiptap.dev/api/marks/link#keyboard-shortcuts
