### ISSUE TITLE
Don't apply typography when inside the Code mark

### ISSUE THREAD

**Issue by neongreen** [ueberdosis/tiptap#1889]
When I'm inside a `<code>` mark, I usually don't want to replace `--` with a dash, or have curly quotes, etc. It would be nice to disable typography there.

The CodeBlock node already features this behavior.

**Comment by philippkuehn** [comment]
I'm currently working on a rewrite of inputrules/pasterules and keep that in mind! ✌️

**Comment by philippkuehn** [comment]
Do you mean the `Code` mark or `CodeBlock` node?

**Comment by neongreen** [comment]
The Code mark.
