### ISSUE TITLE
 SyntaxError: Mixing inline and block content (in content expression 'paragraph* inline*')

### ISSUE THREAD

**Issue by fyeeme** [ueberdosis/tiptap#1890]
**Description**
I want the  tiptap render full syle of the rich html content ,but seams it's  not support, 
if I  custom tiptap's  Paragraph like this 
```js 
import Paragraph from '@tiptap/extension-paragraph'

const CustomParagraph = Paragraph.extend({
  priority: 100,
  draggable: true, //support draggable
  content: 'paragraph* inline*',  //support both nested <section> and inline content,

  addAttributes() { // support full feature of the style 
    return {
      style: {
        default: null,
        parseHTML: (element) => element.getAttribute('style'),
        renderHTML: (attributes) => {
          console.log(attributes)
          return {
            style: attributes.style,
          }
        },
      },
    }
  },
  parseHTML() {
    return [
      {
        tag: 'section',
        getAttrs: (node) => node.style && null,
      },
    ]
  },
  renderHTML({ HTMLAttributes }) {
    return ['section', HTMLAttributes, 0]
  },
})
export default CustomParagraph

```
some of the cases I'v try:

`content: 'inline*', ` // not support nested tag <p> or <section>

`content: 'paragraph* ', ` // not render  text[words]

hear is the sereenshot:
![image](https://user-images.githubusercontent.com/6078758/133191097-29673242-0166-4747-906c-6f9c79a4f541.png)

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:
https://codesandbox.io/s/tiptap-issue-template-forked-kne1t?file=/src/components/style-paragraph.js

**Environment?**
 - operating system: macos 11.5.0
 - browser: chrome 93
 - mobile/desktop: desktop
 - tiptap version:  2.0.0-beta.105

**Comment by philippkuehn** [comment]
As the error suggests, mixing block and inline nodes are not supported.
