### ISSUE TITLE
Nuxt 3 support

### ISSUE THREAD

**Issue by productfrontenddeveloper** [ueberdosis/tiptap#1894]

**Comment by philippkuehn** [comment]
Please provide more context.

**Comment by productfrontenddeveloper** [comment]
> Please provide more context.

https://www.tiptap.dev/installation/nuxt

I don't know what to do. There is no documentation on nuxt 3 + vite on your site. That's why I opened it to remind him here.

**Comment by philippkuehn** [comment]
Have you tried using tiptap with nuxt 3? What are the problems?

**Comment by productfrontenddeveloper** [comment]
> Have you tried using tiptap with nuxt 3? What are the problems?

I thought you might have early access and test your library. That's why I opened this thread. Is there any preparation? We'll test it tonight. :)
