### ISSUE TITLE
Multiple Placeholders example?

### ISSUE THREAD

**Issue by upendra-web** [ueberdosis/tiptap#190]
First of all, Thank you for making such an awesome WYSIWYG editor.

Can anyone give me an example where we can use multiple placeholders, like for example placeholder text for a list item saying 'Enter what to do', something like an input?

Thanks in advance.

Something like the below example:
![screenshot 92](https://user-images.githubusercontent.com/43108965/52310997-64ef1200-29cb-11e9-9c10-f24909e17df4.jpg)

**Comment by swuecho** [comment]
Hi @upendra-web, 

Did you find the solution? Thanks.

**Comment by upendra-web** [comment]
Nope, dude. I couldn't find a solution.

**Comment by AldrinSalazar** [comment]
Any solution for this?
