### ISSUE TITLE
Table selection needs 2 clicks

### ISSUE THREAD

**Issue by wmonecke** [ueberdosis/tiptap#1900]
**Description**
I felt that the table selection was a bit clunky. Currently you need to click 3 times rapidly to select a table cell (so that you could add rows or columns adjacent to the selected one). I feel this is a bit unintuitive. A double click should trigger table selection.

**Comment by sereneinserenade** [comment]
In most of the places, double click is for selecting a word, and being habituated with that, selecting a cell on double click might turn out to be counterintuitive for some people.

**Comment by philippkuehn** [comment]
A triple click is used by prosemirror-tables to create a cell selection:

https://github.com/ProseMirror/prosemirror-tables/blob/6b16ed3cf306886f2c169aebbe60701e1ac2deac/src/input.js#L88-L93

You can create your own click handler to do the same at a double click.
I don’t want to change that behavior by default for now.

BTW: cmd+doubleClick also works for a cell selection.
