### ISSUE TITLE
Performance issues on Chrome

### ISSUE THREAD

**Issue by rezaffm** [ueberdosis/tiptap#1901]
Hi guys,

I cannot really create a sandbox for this, but I will try to explain.

I use tiptap with LanguageTools. Our texts typically have around 2.000 words (but some go up to 4.000 words). They include tables et cetera.

I noticed that when using Chrome, around 1.000 words or so, it starts to get laggy, and it gets worse the more words I write (surprise...).

When I switch off spellcheck, like so:

```javascript
editorProps: {
  attributes: {
    spellcheck: 'false',
  },
```

Then I am fine on Chrome, all good.

I tested the same on Firefox (Linux, Ubuntu) **with spellcheck on,** no probs. 

**So, it is clearly related to Chrome.**

I noticed here https://discuss.prosemirror.net/t/performance-issues-with-prosemirror-and-chrome/2498/21 it seems to be some kind of known issues. 

The discussed solution with "content-visibility of CSS, only available in Chrome 85." I have no clue how to implement in tiptap.

So, I was wondering if you came across this issue in the past, and how did you solve this one in the past? Switching off spellcheck is not a feasible option, but maybe you have some clever idea?

**Chrome: Version 92.0.4515.131 (Official Build) (64-bit)
Firefox: 92.0 (64-bit)**

**Comment by philippkuehn** [comment]
Since this is an issue with Chrome itself, we unfortunately can’t do anything here. disabling spellcheck works fine for most users.

`content-visibility` is a CSS feature so just add to your styles and see what happens. I’ve not any experience with that property.

**Comment by philippkuehn** [comment]
I'm not sure which version you are using but the vue-2 package has some performance issues. vue-3 and react is much faster!

**Comment by rezaffm** [comment]
Hi Philipp, I am using Vue 2, I am waiting for Vuetify to make the change from boostrap-vue to Vue 3, actually.

I wondered indeed if it is only related to Chrome, as I tested with some simple contentEditables very long texts without any issues at all with Chrome.

Isn't there any chance to get it working with Vue 2?

Or to put it differently, if you use a 4.000 words text from here https://www.loremipsum.de/ - do you any lags at all with a vue3 set up?

**Comment by rezaffm** [comment]
Actually, I just tried something.

I have the Editor in an Editor.vue file, like so:

```javascript
    mounted() {
      this.editor = new Editor({
        extensions: [
          Blockquote,
          Bold,
          CustomBulletList,
          Code,
          CodeBlock,
          Document,
          Dropcursor,
          Gapcursor,
          HardBreak,
          Heading,
          Highlight,
          History,
          CustomHorizontalRule,
          Italic,
          ListItem,
          OrderedList,
          CustomParagraph,
          Strike,
          Text,
          TextAlign.configure({
            types: ['heading', 'paragraph', 'image'],
          }),
          Table.configure({
            HTMLAttributes: {
              class: 'table-responsive',
            },
            cellMinWidth: 100,
            resizable: true,
          }),
          TableRow,
          TableHeader,
          CustomTableHeader,
          CustomTableCell,
          CustomLink.configure({
            HTMLAttributes: {
              target: null,
              rel: null
            },
            openOnClick: false
          }),
          CustomImage.configure({
            inline: true
          }),
          ExternalVideoExtension,
          ExternalIframeExtension,
          BoxExtension,
          HeadingsId
        ],
        content: this.value,
        /*editorProps: {
          attributes: {
            spellcheck: 'true',
          },
        },*/
        onUpdate: () => {
          this.$emit('input', this.editor.getHTML())
        },
      })
      // Load Editor CSS
      this.loadCss()
    },
    beforeDestroy() {
      this.editor.destroy()
    },
    destroyed() {
      window.removeEventListener('keydown', this.toggleFullScren);
    }
  }
```

I follwed the instructions on https://tiptap.dev/installation/vue2/#5-use-v-model-optional

However, there you should how to use v-model with vue-3 so I found out that this won't work:

```javascript
onUpdate: () => {
  // HTML
  this.$emit('update:modelValue', this.editor.getHTML())

  // JSON
  // this.$emit('update:modelValue', this.editor.getJSON())
},
```

So I replacec with:

```javascript
  onUpdate: () => {
    this.$emit('input', this.editor.getHTML())
  },
```

When I actually comment the onUpdate function (and basically disable two-model binding for v-model) interestingly, the lag goes away.

So am I went into the wrong direction?

**Comment by rezaffm** [comment]
Okay, I have been playing around, so what I did is the following:

```javascript
import { debounce } from 'lodash'
```

```javascript
onUpdate: () => {
  //this.$emit('input', this.editor.getHTML())
  this.debounceInput()
},
```

```javascript
created() {
  this.debounceInput = debounce(() => {
    this.$emit('input', this.editor.getHTML())
  }, 300)
```

and now the lagging is completely gone....

I experience this the first time, so it must be some kind of performance issue between v-model binding with vue, or am I wrong?

**Comment by rezaffm** [comment]
okay, I can now really confirm that this solved all laggs on Vue 2... I dunno why, but it works, maybe nice to know for you.
