### ISSUE TITLE
Cannot delete or copy-paste when top-level block node (fix in description)

### ISSUE THREAD

**Issue by nokola** [ueberdosis/tiptap#1908]
**Description**
Creating a custom block node, adding it to a doc and trying to delete it is a no-op.

**Steps to reproduce the bug**
1. Open https://codesandbox.io/s/tiptap-issue-template-forked-ijlnk?file=/src/components/Tiptap.vue
2. Click in editor example, press Ctrl+A to select all
3. Press del to delete everything

**Expected behavior**
Everything is deleted from editor

**Actual**
Step 2 does not select all, step 3 is a no-op. Also affects copy-paste.

**Environment?**
 - operating system:
 - browser:
 - mobile/desktop:
 - tiptap version:

**Additional context**
The issue is that TipTap does not import the default ProseMirror KeyMap, and Ctrl+A is handled by the browser incorrectly.

In sandbox above, uncomment this line to fix:
```ts
// Keys, // !!!!!!!! uncomment to fix bug
```

Importing this would fix it:
```ts
import { baseKeymap } from "prosemirror-commands";
import { keymap } from "prosemirror-keymap";

const Keys = Extension.create<{}>({
    name: 'keys',
    addProseMirrorPlugins() {
        return [keymap(baseKeymap)];
    }
});
```
Also, here's the date schema for reference:
```ts
    date: {
      inline: false,
      group: "block",
      selectable: true,
      atom: true,
      toDOM() {
        return ["date", "♥"];
      },
      parseDOM: [{ tag: "date" }]
    },
```

**Comment by philippkuehn** [comment]
You are right. At the moment we don’t create an `AllSelection` on `cmd+a`: https://github.com/ueberdosis/tiptap/blob/fe47c388ce5ef49c286302a7b771a680c2f0c239/packages/core/src/extensions/keymap.ts#L32-L33

This leads also to this issue: https://github.com/ueberdosis/tiptap/issues/1531

I have in mind that there were some strange situations when you wanted to convert nodes within an `AllSelection`. But I can’t reproduce them now so maybe they got fixed somehow 😅

So maybe it makes sense to re-enable the `AllSelection`.

**Comment by philippkuehn** [comment]
Hmm no, the issues with `AllSelection` are still there. Most commands are not working as expected anymore. Like toggling lists:

https://user-images.githubusercontent.com/2500670/134249803-04003e17-f6af-4a71-a4a5-e7d639d4a593.mp4

Have to think about it…

**Comment by philippkuehn** [comment]
Instead of an `AllSelection`, we set a `TextSelection` for the whole doc on `cmd+a` which is working fine without the weird side effects of `AllSelection`.

**Comment by nokola** [comment]
Thank you! This is super helpful! Especially finding and fixing the tricky bug with bullet list! I'm relieved I didn't have to investigate this, would take me days maybe.
