### ISSUE TITLE
Suggestion Extension - Pass additional data to the render methods

### ISSUE THREAD

**Issue by jamesopti** [ueberdosis/tiptap#1909]
**The problem I am facing**
We're using the @tiptap/suggestion extension to power a floating menu (Following the example from the docs for @mentions https://tiptap.dev/api/nodes/mention)

Were noticing that whenever another doc editor types above the current user, the tippy instance is recreated due to both `onExit` and then immediately after `onStart` being called: 
https://github.com/ueberdosis/tiptap/blob/main/packages/suggestion/src/suggestion.ts#L135

### Collaborative Editing

It's a little weird that `onExit` gets called anytime someone else types above you earlier in the doc. There may be a better way to handle this case, but I'm not sure what that is.

The proposed change here will allow consumers implementing `onExit` to check if the new state of the plugin is still `active` (and decide to no-op in that case)

**The solution I would like**
Additional props passed to the suggestion render methods (`SuggestionProps`) to provide more insight into the current state of the plugin instance.

**Alternatives**

With the addition of the PluginKey option for Suggestion, I realized I can work around this by providing my own key and looking up the state myself. I think the suggested method of passing the props would still be preferred though.

**_Note that `onStart` lazily creates the popup/renderer_**

```ts
  onExit(props: SuggestionProps) {
    const next = MenuKey.getState(props.editor.view.state)
    if (next.active !== true) {
      popup?.destroy()
      reactRenderer?.destroy()

      popup = null
      reactRenderer = null
    }
  },
```

**Comment by jamesopti** [comment]
I'll create a pull request for this now.

**Comment by philippkuehn** [comment]
Hey, would it be possible that you could create a codesandbox where I can reproduce the issue? Maybe I can fix it in the package itself.

**Comment by philippkuehn** [comment]
ping 👀

**Comment by Haraldson** [comment]
@jamesopti Did you ever solve this?
