### ISSUE TITLE
Error dependent version 

### ISSUE THREAD

**Issue by fyeeme** [ueberdosis/tiptap#1913]
![image](https://user-images.githubusercontent.com/6078758/133981094-e89335d8-ac2f-41a5-969f-885336a6a972.png)

`@tiptap/vue-3`'s dependent @tiptap/extension-floating-menu is beta.28, but published ant  npmjs.org is beta.27, when install it ,Error will occur
![image](https://user-images.githubusercontent.com/6078758/133981309-3a7d9da1-aaa3-4ec8-9d57-7106a0df014c.png)

```json
"dependencies": {
    "@tiptap/extension-bubble-menu": "^2.0.0-beta.34",
    "@tiptap/extension-floating-menu": "^2.0.0-beta.28",
    "prosemirror-state": "^1.3.4",
    "prosemirror-view": "^1.20.1"
  },
```

**Comment by philippkuehn** [comment]
Super strange. This seems like an issue with npm itself.

I can’t upload v28:
<img width="965" alt="OlGeoJi5OV" src="https://user-images.githubusercontent.com/2500670/133982587-4efc0780-32bd-40d7-8bc1-4907133d0916.png">

Overview shows v27 as latest:
<img width="517" alt="EfLcg1OW45" src="https://user-images.githubusercontent.com/2500670/133982399-0a8eca5d-6629-416a-ae6b-fe1f5b224cac.png">

But on the package page it’s v28
<img width="388" alt="lnRHN1JFs0" src="https://user-images.githubusercontent.com/2500670/133982458-bb342a39-cafd-44d7-8ff2-44d76360f8b9.png">

**Comment by fyeeme** [comment]
May directly upgrade to v 29?

**Comment by philippkuehn** [comment]
maybe this was just a temporary problem? v28 is uploaded at npm:
https://npm.runkit.com/@tiptap/extension-floating-menu/package.json?t=1632136305776

**Comment by fyeeme** [comment]
Yes, solved, thanks.
