### ISSUE TITLE
Barebones core editor

### ISSUE THREAD

**Issue by flaviouk** [ueberdosis/tiptap#1920]
**The problem I am facing**
I'm not able to get a barebones editor, the current base editor (without any extensions) still adds a few core extensions regardless. I need this to have more control over what event listeners are being started
https://github.com/ueberdosis/tiptap/blob/main/packages/core/src/Editor.ts#L222

**The solution I would like**
An option flag to disable this.

**Alternatives I have considered**
Fork @tiptap/core

I can do this myself, just wanted to know if you'd welcome a PR and what the name for that flag would be?

**Comment by philippkuehn** [comment]
Do you want to disable *all* core extensions or just a few some specific ones?
And can I ask why you want to disable them? The clipboardTextSerializer, focus events or the default keymap?

**Comment by flaviouk** [comment]
Pretty much all core extensions yes, I want to be able to pick exactly what I need for performance reasons in my application. eg. Because I have many editors in the page, having a centralised place with all the keymap/paste events is necessary. I think focus events are fine? Just having issues with too many keymap/paste firing

**Comment by philippkuehn** [comment]
what about core commands? these are registered by an extension too. maybe it would make sense to export the core extensions, so you could use them if needed.

**Comment by flaviouk** [comment]
The ones I've been using is set/toggle node and focus, but I agree exporting the core extensions and then I can pick and chose what I need
