### ISSUE TITLE
WebRTC collaboration only rarely working on some Android phones

### ISSUE THREAD

**Issue by carlobeltrame** [ueberdosis/tiptap#1921]
**Description**
On my Android phone (Sony Xperia H8314), the collaboration extension with the WebRTC provider works neither in Firefox for Android, nor in Firefox Nightly, nor in Chrome.

**Steps to reproduce the bug**
1. On an affected Android device, go to the deployed sandbox: https://flmrr.csb.app/
2. On another device, also go to https://flmrr.csb.app/
3. Typing doesn't sync between the two, and no cursors are displayed on the mobile phone (and the phone's cursor isn't displayed on the other device). Sync and cursor display works consistently between two desktop browsers on different machines though.

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:
https://codesandbox.io/s/tiptap-issue-template-forked-flmrr?file=/src/components/Tiptap.vue

**Expected behavior**
Collaboration works on all devices using the WebRTC provider.

**Screenshot, video, or GIF**
WebRTC itself is working, as I could verify on https://test.webrtc.org:
![Screenshot_20210921-154740](https://user-images.githubusercontent.com/7566995/134189862-8a3dc37b-e6c1-4b24-946a-a991246c9969.png)

Also, some of the YJS demos work, e.g. this one:
https://demos.yjs.dev/prosemirror-versions/prosemirror-versions.html

Some WebRTC messages are exchanged with the signaling servers, and they seem to be correlated somewhat on all devices (they appear at the same time, and most but not all of the messages are either uploaded from one of the connected devices):
![Screenshot from 2021-09-21 16-38-05](https://user-images.githubusercontent.com/7566995/134191684-da7479b6-c9e1-42a8-afd6-db987e14bcab.png)

**Environment?**
 - operating system: Android 9 on Sony Xperia H8314, trying to communicate with Ubuntu and Windows on desktops
 - browser: Firefox for Android, Firefox Nightly, Chrome Android app, trying to communicate with Firefox and Chromium
 - mobile/desktop: Both
 - tiptap version: 2

**Additional context**
The issue happens regardless of whether I'm using a room password or not with the WebRTC provider. But the messages on the yjs prosemirror demo look different (meaning: contain binary data) compared to the tiptap collaboration ones (which are JSON), not sure why that is...

Actually, while writing this issue, it started working once, after I had had the page open for several minutes. But it was a one-time phenomenon, I can consistently reproduce it not working.

**Comment by carlobeltrame** [comment]
No, that one doesn't work on my phone either. Syncing between the two editor areas works, but I'm not recieving or sending any external changes. It also doesn't work across two browsers on the same phone, but I'm not sure if it's supposed to work like that.

It's kind of good and bad to hear at the same time that it works for you, because it means not all Android phones are affected, which also means it's going to be harder to reproduce.
I'm on Android 9 and Firefox 89.1.1, and just updated to Firefox 92.1.1, no difference. Same problem on the same phone on Chrome 91.0.4472.101, and I updated to 93.0.4577.82, no difference.

When remote debugging my phone's Chrome, the JS console shows nothing suspicious, only a few unrelated warnings:
```
DevTools failed to load source map: Could not load content for https://cdn.jsdelivr.net/npm/@docsearch/index.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
[Violation] Forced reflow while executing JavaScript took 50ms
DevTools failed to load source map: Could not load content for https://cdn.jsdelivr.net/npm/@docsearch/index.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
[iFrameSizer][iFrameResizer0] Unexpected message ([iFrameSizer]iFrameResizer0:192:292:init)
[iFrameSizer][iFrameResizer1] Unexpected message ([iFrameSizer]iFrameResizer0:192:292:init)
[iFrameSizer][iFrameResizer1] Unexpected message ([iFrameSizer]iFrameResizer0:0:0:mouseenter:331:47)
```

The Websocket connection to the signaling servers is quite busy though:
![tiptap-webrtc.mp4](https://user-images.githubusercontent.com/7566995/134219015-8e7781fe-905b-483b-ae59-4fd26acf557a.mp4)

Any other ideas what I can try or what type of logs I could supply to help debug this?

**Comment by carlobeltrame** [comment]
If you can give me a few pointers where to start I can also try to debug this myself. It's just that there's so much magic involved that it's hard to know what is executed why. Maybe you can tell me the answers to the following questions:
* Why is the format of the WebRTC messages plain JSON, as opposed to the binary data from the yjs-prosemirror demo? Aren't they both based on yjs-prosemirror?
* Since some messages clearly arrive on my phone, what code is supposed to transform them into changes on the document? What's the general flow of information / flow of logic / architecture that is used to make this work?
* Is there any specific logic tiptap does, rather than just wrapping the yjs and prosemirror APIs?

**Comment by hanspagel** [comment]
1) I don’t have much experience with WebRTC, but you’re looking into the signaling process where peers are connected. Not into the Y.js updates sent to/received from other peers. Those are binary.

2) Once changes come in, they should be applied to the Y.js document. You can observe/observeDeep on that document to verify that. But this is the providers work.

tiptap uses y-prosemirror and that observes the Y.js document too.

3) No

Hope that helps a little bit! Generally speaking this sounds like a browser flaw that we can’t do much about. Check if tiptap/ProseMirror receives changes with the onUpdate event, check if those changes are applied to the Y.js document with observe/observeDeep.
