### ISSUE TITLE
chain.focus() is unable in some (inline = true) customNode

### ISSUE THREAD

**Issue by adou2236** [ueberdosis/tiptap#1924]

**Comment by adou2236** [comment]
codebox is here
https://codesandbox.io/s/elegant-banzai-tvgv2?file=/src/components/Editor.vue
step1:type some words
step2:insert a picture
if the customImage inline = false it can focus(bubbleMenu show) after commands but set inline = true it can't

**Comment by adou2236** [comment]
who can help me

**Comment by philippkuehn** [comment]
Can’t run the codesandbox because of a syntax error. Feel free to re-open if I’m able to reproduce the issue.
