### ISSUE TITLE
Page pagination

### ISSUE THREAD

**Issue by Satomeister** [ueberdosis/tiptap#1927]
Hi

**The problem I am facing**
I want to realize page breaker (page pagination) in my React tiptap editor. I tried to make it changing js DOM, but it did not work well. And if i use React, changing DOM is bad practice.

**The solution I would like**
I would like to know the good way to realize page pagination.

**Comment by rezaffm** [comment]
Related to my feature Request: https://github.com/ueberdosis/tiptap/issues/1870

**Comment by philippkuehn** [comment]
yeah closing because of #1870. please follow up there.

**Comment by Cassielxd** [comment]
You can refer to this implementation https://github.com/Cassielxd/CassieEditor
