### ISSUE TITLE
Link extension doesn't work properly

### ISSUE THREAD

**Issue by vedmant** [ueberdosis/tiptap#1928]
**Description**

There are few issues that reproducible on the documentation page https://tiptap.dev/api/marks/link 

**Steps to reproduce the bug**

First issue:
1. Clear editor
2. Click setLink button
3. Type any URL
4. Click Ok
5. Type any link text
It will only create a link for the first character, then it becomes a normal text:
<img width="382" alt="Screenshot at Sep 22 12-25-44" src="https://user-images.githubusercontent.com/5052406/134318433-5ff3fcfb-4442-4beb-8505-0653017499e9.png">

Second issue:
1. Create any link
2. Try to append or prepend text to a link
It will allow to add a text only if cursor is between the last and first character, this makes it tricky to edit link text:
https://monosnap.com/file/gUNN9RvUP0WyL9XtuY7KYMT89aqetS

**CodeSandbox**
You can just use docs page https://tiptap.dev/api/marks/link

**Expected behavior**
Fist issue:
It should allow to type more than one character.

Second issue: 
It should allow to append or prepend text to a link as a link. Probably stop being a link on space, comma, dot, etc...

**Screenshot, video, or GIF**
See above

**Environment?**
 - operating system: MacOs 11.4
 - browser: Chrome Version 93.0.4577.82
 - mobile/desktop: Desktop
 - tiptap version: Latest as in docs https://tiptap.dev/api/marks/link

**Comment by philippkuehn** [comment]
about the second issue: this is intended. you can change this by extending the Link mark but this makes it hard to exit a link:

 ```js
Link.extend({
  inclusive: true,
})
```

**Comment by vedmant** [comment]
@philippkuehn Thanks, is there a way to specify on what characters it will exit the link editing? In case of `inclusive: true,` it just keeps being a link even or return. I think the most logical way is to stop editing link text on space comma, dot, etc.. Also exiting/entering link editing can be done by pressing arrow keys (like https://ckeditor.com/docs/ckeditor5/latest/examples/builds/classic-editor.html or https://www.tiny.cloud/docs/demo/full-featured/)

**Comment by philippkuehn** [comment]
> I think the most logical way is to stop editing link text on space comma, dot, etc

Unfortunately it’s not that easy 😅 Dot and comma are valid characters within an url.
For example: http://example.com/docs/2.0.x/foo?bar=baz,meh

But yeah, maybe some arrow key navigation would be great. Something [like this](https://github.com/ueberdosis/tiptap/pull/1200) can be a good starting point.

**Comment by philippkuehn** [comment]
There is a new [autolink feature](https://github.com/ueberdosis/tiptap/pull/2226) which changes the behavior for links in some situations. Closing this for now.
