### ISSUE TITLE
Insert a hard break without loosing formatting.

### ISSUE THREAD

**Issue by philippkuehn** [ueberdosis/tiptap#1934]
### Discussed in https://github.com/ueberdosis/tiptap/discussions/1933

<div type='discussions-op-text'>

<sup>Originally posted by **hans-pragt** September 23, 2021</sup>
If I enable the hardbreak extension and extend it to listen for the enter key, starting a paragraph in bold, pressing enter, and further typing will result in:
```
<p><strong>This is a test</strong><br>this is also a test</p>
```
Even though the bolding was never explicitly turned off. How do I prevent this behavior and keep bold enabled across lines?</div>

**Comment by philippkuehn** [comment]
The `setHardBreak`command now keeps splittable marks by default. Splittable marks are based on the `keepOnSplit` option for marks.

```js
SomeMark.extend({
  keepOnSplit: false,
})
```

You can disable that feature at all with a new `keepMarks` option on the `HardBreak` extension.

```js
HardBreak.configure({
  keepMarks: false,
})
```

**Comment by hans-pragt** [comment]
Thank you!
