### ISSUE TITLE
Placeholder text is not reactive 

### ISSUE THREAD

**Issue by lyle45** [ueberdosis/tiptap#1935]
**Description**
This is a duplicate of #153 but for tiptap v2
solution there does not work with tiptap 2 and placeholder extension is not reactive to i18n changes. need solution

**Steps to reproduce the bug**
1. Have placeholder extension
2. update i18n language
3. placeholder doesn't update automatically and there is no way to let it know there was an update

**Expected behavior**
Placeholder should either connect to vue's reactivity system and update on i18n update, or should have a mechanism for setting new placeholder (or simply telling tiptap, content updated call function again)

**Comment by philippkuehn** [comment]
Use a callback function for `placeholder`.

**Comment by lyle45** [comment]
@philippkuehn doesn't work... it only works when further interacting with the editor. how would the editor would otherwise know the result of the callback has changed?

**Comment by lyle45** [comment]
![image](https://user-images.githubusercontent.com/17912606/134506274-07a7460c-99ea-42b4-8a10-d21d4b9e9ef6.png)

![image](https://user-images.githubusercontent.com/17912606/134506358-d932c81d-4c5c-4d9a-b22f-3374a1cd06da.png)

**Comment by philippkuehn** [comment]
Ah, I understand! You can try to trigger an update of the editor with a noop transaction when changing the language.

```js
editor.view.dispatch(editor.state.tr)
```

That should call the placeholder plugin again.

**Comment by lyle45** [comment]
@philippkuehn works thank you.

maybe this calls to mind that the editor needs a method like, refresh() or update() that triggers this noop update?

**Comment by lyle45** [comment]
@philippkuehn This is a pretty hacky solution. should there not be a refreshState method?

**Comment by paulm17** [comment]
@philippkuehn Using react, I'm unable to get the placeholder to change

```
function Editor({ type, placeholder, userId }: editorProps) {

const editor = useEditor({
    extensions: [
    Placeholder.configure({
        emptyEditorClass: "is-editor-empty",
        placeholder: placeholder,
   }),
],

useEffect(() => {
    if (editor !== null && placeholder !== "") {
      editor.view.dispatch(editor.state.tr)
    }
  }, [editor, placeholder])
```

**Comment by paulm17** [comment]
Following up.  I now have the placeholder reactive.

I'm using valtio as a global state and I'm able to listen to changes.

By going into the editor object and defining the placeholder directly, I'm able to change it at will.

Hopefully this is useful to anyone else who comes against this.

```
subscribeKey(useStore.ux.chatPane, "id", () => {
    if (editor !== null) {
      editor.extensionManager.extensions.forEach((extension) => {
        if (extension.name === "placeholder") {
          let text = ""
          if (type === "channel") {
            text = `Message in #${useStore.ux.chatPane.name}`
          } else if (type === "thread") {
            text = `Message ${useStore.ux.chatPane.name}`
          } else if (type === "private") {
            text = `Message @${useStore.ux.chatPane.name}`
          }

          extension.options["placeholder"] = text
        }
      })
    }
  })
```

**Comment by steven-tey** [comment]
> I combined the snippets from two comments above and made it work in React:
> 
> ```
>   useEffect(() => {
>     if (editor !== null && placeholder !== "") {
>       editor.extensionManager.extensions.filter(
>         (extension) => extension.name === "placeholder"
>       )[0].options["placeholder"] = placeholder;
>       editor.view.dispatch(editor.state.tr);
>     }
>   }, [editor, placeholder]);
> ```

You, sir/ma'am, are a life-saver! Thank you!

**Comment by amm834** [comment]
> I combined the snippets from two comments above and made it work in React:
> 
> ```
>   useEffect(() => {
>     if (editor !== null && placeholder !== "") {
>       editor.extensionManager.extensions.filter(
>         (extension) => extension.name === "placeholder"
>       )[0].options["placeholder"] = placeholder;
>       editor.view.dispatch(editor.state.tr);
>     }
>   }, [editor, placeholder]);
> ```

thank bro, you saved my eyes 😵‍💫

**Comment by Rieranthony** [comment]
You saved my life @hyunwoona , I'll name my first child "hyunwoona"

**Comment by EduardoNGomes** [comment]
> I combined the snippets from two comments above and made it work in React:
> 
> ```
>   useEffect(() => {
>     if (editor !== null && placeholder !== "") {
>       editor.extensionManager.extensions.filter(
>         (extension) => extension.name === "placeholder"
>       )[0].options["placeholder"] = placeholder;
>       editor.view.dispatch(editor.state.tr);
>     }
>   }, [editor, placeholder]);
> ```

Thanks, you save me life
