### ISSUE TITLE
Text Alignment cannot be set

### ISSUE THREAD

**Issue by HuiiBuh** [ueberdosis/tiptap#1936]
**Description**
Setting the text alignment in the editor does not work

**Steps to reproduce the bug**
1. Create Editor
2. Set text alignment
3. Nothing happens

**CodeSandbox**
I created a CodeSandbox to help you debug the issue:
https://codesandbox.io/s/tiptap-react-forked-ss80z?file=/src/App.tsx

**My TipTap Wrapper with the same issue**
https://github.com/HuiiBuh/ngx-tiptap-editor

**Expected behavior**
Text alignment can be set

**Environment?**
 - operating system: linux
 - browser: firefox and chrome
 - mobile/desktop: desktop
 - tiptap version: 
 	- 2.0.0-beta.112 (core) 
 	- 2.0.0-beta.23 (text-align)

**Comment by philippkuehn** [comment]
You have to configure which nodes should have text align. Probably something like this:

```js
TextAlign.configure({
  types: ['paragraph', 'heading'],
})
```
