### ISSUE TITLE
Pasting empty lines are collapsed

### ISSUE THREAD

**Issue by nokola** [ueberdosis/tiptap#1941]
**Description**
Copy-pasting empty lines from Notepad to tiptap collapses them.

**Steps to reproduce the bug**
1. Open tiptap.dev
2. Copy from here and paste in TipTap:
```
line1



line5
```

**Expected behavior**
I expect line1 and line5 to be separated by 3 empty lines

**Actual**
No line separation between line1 and line5:

**Screenshot, video, or GIF**
![image](https://user-images.githubusercontent.com/6869225/134800090-485e7ee6-dff1-4e7e-9893-b076e54c95dd.png)

**Environment?**
 - operating system: Win10
 - browser: Chrome
 - mobile/desktop: Desktop
 - tiptap version: latest on tiptap.dev

**Comment by philippkuehn** [comment]
Since it’s the same behavior at https://prosemirror.net this is not an issue with tiptap itself. As suggested [here](https://discuss.prosemirror.net/t/please-change-the-rules-for-pasting-plain-text/3996) you have to implement a custom `clipboardTextParser` for it.
