### ISSUE TITLE
Vue JSON v-model Example

### ISSUE THREAD

**Issue by patrickcorrigan** [ueberdosis/tiptap#1944]
https://github.com/ueberdosis/tiptap/blob/main/demos/src/GuideGettingStarted/VModel/Vue/Editor.vue

Line 33

Should this be JSON.stringify instead of .toString()? 

When doing the comparison you just get [object object] otherwise?

**Comment by hanspagel** [comment]
Thanks! Seems to be a duplicate of #1736. ✌️
