### ISSUE TITLE
3rd Party Embed

### ISSUE THREAD

**Issue by matbrgz** [ueberdosis/tiptap#1950]
**The problem I am facing**
I’m always frustrated when creating documents that need to show documents that isn't possible to bring to tiptap.

**The solution I would like**
Embed means to integrate external content into another website or page. You embed something when you place a block of code — called an embed code — into the HTML editor of another website.

![image](https://user-images.githubusercontent.com/23284276/135104526-5a3aa8bf-e6fc-4250-802f-8f9b14da4e9f.png)

**Suggestion to Embed**
- [ ] [Google Knowledge Graph Search API](https://en.wikipedia.org/wiki/Knowledge_Graph)
- [ ] Abstract
- [ ] Adobe Dimension
- [ ] Adobe Spark 
- [ ] Adobe XD
- [ ] AirTable
- [ ] Any URL
- [ ] ArcGIS StoryMap
- [ ] Asana
- [ ] BambooHR
- [ ] Behance
- [ ] ClickUp (https://docs.clickup.com/en/articles/3714856-public-sharing)
- [ ] CodePen
- [ ] DailyMotion
- [ ] Descript
- [ ] Diagrams.Net
- [ ] embed.ly
- [ ] Facebook Post
- [ ] Figma
- [ ] Flickr
- [ ] Framer
- [ ] Giphy
- [ ] GitHub Gist
- [ ] Google 
- [ ] Google Analytics
- [ ] Google Calendar
- [ ] Google Colaboratory
- [ ] Google Docs
- [ ] Google Maps
- [ ] Google Slides
- [ ] Google Spreedsheet
- [ ] iframely
- [ ] Instagram HashTag Feed
- [ ] Instagram Post
- [ ] Instagram Profile Feed
- [ ] Instagram Profile Grid
- [ ] InVision
- [ ] ion interactive
- [ ] jsFiddle
- [ ] Kickstarter Campaign
- [ ] Kickstater Catalogue
- [ ] Leanboard
- [ ] LinkedIn Post
- [ ] Linkedin SlideShare
- [ ] Looker
- [ ] Lucidchart
- [ ] Marvel
- [ ] Metabase (https://www.metabase.com/docs/latest/administration-guide/13-embedding.html)
- [ ] Microsoft PowerBI
- [ ] Mindmeister
- [ ] Miro
- [ ] Notion
- [ ] Overflow.io
- [ ] Pastebin.com
- [ ] Plunker
- [ ] Prezi
- [ ] RunKit
- [ ] Scribd
- [ ] Snipit
- [ ] Speakerdeck
- [ ] Spotify Playlist
- [ ] StackShare
- [ ] Taiga
- [ ] TED
- [ ] TikTok
- [ ] Tiled
- [ ] Trello
- [ ] Trello Board
- [ ] Trello Card
- [ ] Tumblr
- [ ] TuneUp
- [ ] Twitter HashTag Timeline
- [ ] Twitter Profile Feed
- [ ] Twitter Tweet
- [ ] TypeForm
- [ ] Visual.ly
- [ ] Whimsical or Mermaid
- [ ] Wikimedia
- [ ] Wikipedia
- [ ] WordPress Blog Post
- [ ] Wordpress Blog Post Catalogue
- [ ] Yelp
- [ ] YouTube

**Comment by cadars** [comment]
Have you tried the Embed experiment? It’s a good starting point: https://tiptap.dev/experiments/embeds

**Comment by hanspagel** [comment]
Yes, there is an experiment that should give you a starting point. We’ll add an official embed extension at some point, but I don’t think that will be very soon. Thanks for the extensive list of services though. ✌️
