### ISSUE TITLE
Image in editor won't be focused on pointer events

### ISSUE THREAD

**Issue by tomosterlund** [ueberdosis/tiptap#1962]
### What’s the bug you are facing?

 Using **@tiptap/vue-2**, we have the problem in our editor that Images won't be focused upon triggered pointer events, also meaning that any attempts to update the attributes of an image fail, because the editor won't know which element to update. Only once we click and drag an image, **editor.state.selected.node** is set to the currently dragged image, and then we can update it.

### How can we reproduce the bug on our side?

Click any image in the editor.

### What did you expect to happen?

The image to be focused upon clicking, as well as editor.state.selected.node to be set.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
By default a `NodeSelection` is only created on `cmd+click`. If you want to do this for images on click, you have to add a custom click handler.

**Comment by tomosterlund** [comment]
Thanks a lot!

**Comment by BrianHung** [comment]
@tomosterlund I'm curious; is your use-case different from https://tiptap.dev/examples/images? Because that has default NodeSelection on click without a custom click handler iirc.
