### ISSUE TITLE
Remove Mentions by characters

### ISSUE THREAD

**Issue by starostin** [ueberdosis/tiptap#197]
Hello. 
First  of all I want thank you for your work! I really appreciate it and it seems that it's the best editor (especially for Vue).
I use the tags and mentions and they work fine. 
But I have just one question: for now when I click backspace - the whole mention removes (so it removes completely but not just one character). Could you please share what I do wrong and if it's possible to delete just 1 character from mention by taping backspace?

**Comment by hanspagel** [comment]
Sounds like a feature, not a bug.

**Comment by starostin** [comment]
I have just thought that may be exist some magic option which turn on this feature)).  But yes, seems it is feature request. Thanks
