### ISSUE TITLE
Wrong size for custom Node

### ISSUE THREAD

**Issue by mrddter** [ueberdosis/tiptap#1970]
### What’s the bug you are facing?

Hi all,

I created a custom Node, and to render it I use a "span" element. All works well but the length of the text is wrong. It always seems to use 1 instead of real content length. 

Where am I wrong?

### How can we reproduce the bug on our side?

I prepared a case on Sandbox

### Can you provide a CodeSandbox?

https://codesandbox.io/s/tiptap-node-size-issue-f6zeh

### What did you expect to happen?

If in the html I have an element like this

`<p><span data-type="anchor" class="place" data-id="1" data-label="Torino">Torino</span></p>`

return a size of 6 instead 1 

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
You created an [atom node](https://prosemirror.net/docs/ref/#model.NodeSpec.atom) which has no text representation. That means the text of your node is not part of the document. But I see you also define a `renderText` method in your node. With that you can use `editor.getText()` instead which contains the missing text.

**Comment by mrddter** [comment]
Nice to know and sorry for this, thank you so much!!!
