### ISSUE TITLE
Loading the editor on iOS (when isiOS=true) causes content to be wiped

### ISSUE THREAD

**Issue by jamesopti** [ueberdosis/tiptap#1971]
### What’s the bug you are facing?

All our content was disappearing when it was loaded on any device where the [isiOS](https://github.com/ueberdosis/tiptap/blob/main/packages/core/src/utilities/isiOS.ts#L1) function returned `true`

We tracked it down to the core [NodeView `ignoreMutation` function](https://github.com/ueberdosis/tiptap/blob/main/packages/core/src/NodeView.ts#L199-L214)

### How can we reproduce the bug on our side?

For us this was instantly reproducible in the chrome debugger by just choosing any device that matches the `isiOS` check (like iPad)

I haven't been able to reproduce in an isolated sandbox but I'll keep trying and update here if I can. I suspect it may only be an issue with nested NodeViews

### What did you expect to happen?

Content would not be erased and load as normal.

### Anything to add? (optional)

We worked around this with a fork of tiptap react that overrides the `ignoreMutation` logic above to check if the editor is focused:

```ts
if (
      this.dom.contains(mutation.target) &&
      mutation.type === 'childList' &&
      isiOS() &&
      this.editor.isFocused // --- GAMMA CHANGE HERE
    ) {
...
```

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Is this still happening with the latest version of `@tiptap/react`? Sounds a bit like #1747 which already has been fixed.

**Comment by jamesopti** [comment]
> Is this still happening with the latest version of `@tiptap/react`? Sounds a bit like #1747 which already has been fixed.

Well I feel silly for not verifying this on the current version before reporting.

I can't reproduce it anymore! Thanks for double checking I did the obvious @philippkuehn  (because I didnt 🤦 )

I'll close this now and reopen if were able to trigger it again.
