### ISSUE TITLE
Can not add 3rd Embed

### ISSUE THREAD

**Issue by wiwat-p** [ueberdosis/tiptap#1977]
### What problem are you facing?

I can't add blockquote  embed

### What’s the solution you would like to see?

I need to add this into content
`<blockquote class="twitter-tweet"><p lang="th" dir="ltr">หลักการทำงานของ <a href="https://twitter.com/hashtag/%E0%B8%AB%E0%B8%A1%E0%B8%AD%E0%B8%A3%E0%B8%B4%E0%B8%97%E0%B8%8A%E0%B9%88%E0%B8%A7%E0%B8%A2%E0%B9%82%E0%B8%84%E0%B8%A7%E0%B8%B4%E0%B8%94?src=hash&amp;ref_src=twsrc%5Etfw">#หมอริทช่วยโควิด</a> คือ "ส่งยาต้านไวรัสให้ถึงมือคนไข้ให้ไวที่สุด" เพื่อลดการนอน รพ. และลดการตาย เพราะฉะนั้นอาสาส่งยาจึงมีบทบาทสำคัญมากครับ ซึ่งตอนนี้เรามีอาสาประมาณ 30 คน แต่ต้องส่งยาประมาณ 300 - 500 บ้านต่อวัน<br>ปล. ทำเฉพาะเวลาว่าง หรือ โซนพื้นที่ที่สะดวกได้ครับ <a href="https://t.co/KyuwwI86cm">http://pic.twitter.com/KyuwwI86cm </a></p>&mdash; Ritz Rueangritz S. (@MhorRitz) <a href="https://twitter.com/MhorRitz/status/1421822050449039361?ref_src=twsrc%5Etfw">August 1, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>`
, I can add only iframe embed

### What alternatives did you consider?

Have many social use this embed template.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
closing because of #1976
