### ISSUE TITLE
Feature req: emojis 🙏

### ISSUE THREAD

**Issue by andreasvirkus** [ueberdosis/tiptap#198]
Hi there,

Firstly, thanks for an amazing text editor for Vue!
A thing that our team is really missing atm is a way to integrate an emoji picker with tiptap.
Is this something you'd be willing to consider supporting?

If not, then what'd be the best way to integrate something like [v-emoji-picker](https://www.npmjs.com/package/v-emoji-picker) with tiptap?

Best,
andreas

**Comment by bartroodzant** [comment]
Can't you use the emoji menu's that are integrated in Windows 10 or Mac OSX? On Windows 10 this is activated by pressing **Windows key** + **;** and on Mac OSX this is done by pressing **ctrl** + **cmd** + **space**.

**Comment by andreasvirkus** [comment]
I'm aware of this, but my app's end-users aren't/might not be (most non power users aren't).
That's also why most UIs present the user with an emoji picker.

Or maybe you could suggest how to achieve the GitHub/Slack approach where after typing in a `:`, I'm presented with a searchable list of emojis?

**Comment by andreasvirkus** [comment]
Bump; any plans to include this under the examples (or some help regarding my `:heart:` pattern question? 🙏 )

**Comment by philippkuehn** [comment]
Hey Andreas! This should be already possible. You can use input rules to register emojis with something like `:heart:`. You can use the suggestions plugin (from the mentions example) to render a dropdown with a searchable list of emojis when typing `:`.

**Comment by andreasvirkus** [comment]
Yeah, realised that when I found the `emoji-to-short-name` package 🤦‍♂

**Comment by andreasvirkus** [comment]
I've created a basic example with an emoji picker in the toolbar. I'll update the example once we have a working text-search as well.

https://codesandbox.io/s/tiptap-editor-k9r2e

**Comment by hanspagel** [comment]
How cool is that! 😊 

I have no experience with the Suggestion extension, so I’m not sure if I’m able to help here, but I reopened the issue to give it more visibility.

Also I see us adding an emoji extension to v2 (won’t be a top priority, but would be a cool example to show the possibilities of a Suggestion extension).

Anyway, thanks for your work and thanks for sharing! I hope someone can help here.

**Comment by andreasvirkus** [comment]
I got it working by tweaking the custom class. This is what I ended up with

```

export class EmojiSearch extends Mention {
  options!: {
    matcher: {
      char: string
    }
    mentionClass: string
  }

  get name() {
    return 'emoji-search'
  }

  getLabel(dom: HTMLElement) {
    return dom.innerText.split(this.options.matcher.char).join('')
  }

  get schema() {
    return {
      attrs: {
        id: {},
        label: {},
      },
      group: 'inline',
      inline: true,
      content: 'inline*',
      selectable: false,
      atom: true,
      toDOM: (node) => ['span', {}, node.attrs.label],
      parseDOM: [
        {
          tag: 'span[data-mention-id]',
          getAttrs: (dom: HTMLElement) => {
            const id = dom.getAttribute('data-mention-id')
            const label = this.getLabel(dom)
            return { id, label }
          },
          getContent: (dom: HTMLElement, schema) => {
            const label = this.getLabel(dom)
            return Fragment.fromJSON(schema, [
              {
                type: 'text',
                text: `${this.options.matcher.char}${label}`,
              },
            ])
          },
        },
      ],
    }
  }
}
```

The important bit is `toDOM: (node) => ['span', {}, node.attrs.label],` (looking at it now, `parseDom` could be trimmed down as well I believe). 

I'll look into making the Codesandbox fully functional, although I don't have much confidence there - the same `prosemirror-model` version conflict also exists on the official Tiptap bug repl sandbox.

**Comment by dbalas** [comment]
> The 1 Mention per paragraph is the only issue left. This is what I currently have:
> 
> ```
> export class EmojiSearch extends Mention {
>   options!: {
>     matcher: {
>       char: string
>     }
>     mentionClass: string
>   }
> 
>   get name() {
>     return 'emoji-search'
>   }
> 
>   getLabel(dom: HTMLElement) {
>     return dom.innerText.split(this.options.matcher.char).join('')
>   }
> 
>   get schema() {
>     return {
>       attrs: {
>         id: {},
>         label: {},
>       },
>       group: 'inline',
>       inline: true,
>       content: 'inline*',
>       selectable: false,
>       atom: true,
>       toDOM: (node) => ['span', {}, node.attrs.label],
>       parseDOM: [
>         {
>           tag: 'span[data-mention-id]',
>           getAttrs: (dom: HTMLElement) => {
>             const id = dom.getAttribute('data-mention-id')
>             const label = this.getLabel(dom)
>             return { id, label }
>           },
>           getContent: (dom: HTMLElement, schema) => {
>             const label = this.getLabel(dom)
>             return Fragment.fromJSON(schema, [
>               {
>                 type: 'text',
>                 text: `${this.options.matcher.char}${label}`,
>               },
>             ])
>           },
>         },
>       ],
>     }
>   }
> }
> ```
> 
> The important bit is `toDOM: (node) => ['span', {}, node.attrs.label],` (looking at it now, `parseDom` could be trimmed down as well I believe 🤔 ).
> 
> I'll look into making the Codesandbox fully functional, although I don't have much confidence there - the same `prosemirror-model` version conflict also exists on the official Tiptap bug repl sandbox.
> 
> Edit: also added an intergration with the Giphy API, will try to update the sandbox
> 
> Recording of the 3 features/extensions:
> https://drive.google.com/file/d/13mrMADIpEf5C5YyJLd7lFT_99PhHs9uv/view?usp=sharing

Hi @andreasvirkus, I'm trying to develop same features. It would be great if you could share your progress!

thank you :)

**Comment by andreasvirkus** [comment]
Hey @dbalas - are you using Tiptap v2 or v1? then i'd know which version of our code to share. Here's our current plugin that's used in tiptap@2

```javascript
export const EmojiSearch = Mention.extend({
  name: 'emoji-search',
  defaultOptions: {
    HTMLAttributes: {},
    suggestion: {
      command: ({ editor, range, props }) => {
        editor.chain().focus().replaceRange(range, 'emoji-search', props).insertContent(' ').run()
      },
      allow: ({ editor, range }) => {
        if (range.to > editor.state.doc.content.size) return false // TO-DO: remove if pasting "ok :)" doesn't fail
        return editor.can().replaceRange(range, 'emoji-search')
      },
    },
  },
  addAttributes() {
    return {
      label: {
        default: null,
      },
    }
  },
  renderHTML({ node, HTMLAttributes }) {
    return ['span', mergeAttributes(this.options.HTMLAttributes, HTMLAttributes), `${node.attrs.label}`]
  },
  renderText({ node }) {
    return `${node.attrs.label}`
  },
  addKeyboardShortcuts() {
    return {}
  },
})
```

And on the editor-side
```javascript
EmojiSearch.configure({
  mentionClass: 'emoji',
  suggestion: {
    char: ':',
    items: (q) => {
      if (!q) {
        this.destroySuggestionPopup()
        return []
      }
      return this.emojiIndex.search(q)
    },
    render: () => ({
      onStart: (args) => {
        this.suggestionType = 'emoji'
        this.onStartSuggestions(args)
      },
      onUpdate: this.onUpdateSuggestions,
      onExit: async () => {
        await this.$nextTick()
        this.resetMentions()
      },
      onKeyDown: this.onKeyDownHandler,
    }),
  },
})
```

And the EmojiPicker component is largely the same as in the gist

**Comment by hognevevle** [comment]
Hey @andreasvirkus  - great work! In fact, [your recording](https://drive.google.com/file/d/13mrMADIpEf5C5YyJLd7lFT_99PhHs9uv/view?usp=sharing) shows exactly what we want to implement (including the Giphy part). If this is also made using v2, is there any way you could share the remaining parts as well? 🥺

**Comment by andreasvirkus** [comment]
Hey @hognevevle! I'll discuss this with my team and see if we can open-source those easily as plugins 🤙 Will get back to you shortly 🤞

**Comment by AxelBriche** [comment]
https://tiptap.dev/api/nodes/emoji

**Comment by philippkuehn** [comment]
There is an offical package now! 🎉
