### ISSUE TITLE
Image extension not working with Base64 images (migrating `v1` to `v2`)

### ISSUE THREAD

**Issue by timelytree** [ueberdosis/tiptap#1981]
### What’s the bug you are facing?

This isn't so much a bug (I don't think) as much as a regression in the previous feature set. In tiptap v1, it was possible to drag/drop an image from your desktop onto the editor and have it converted to an inline `<img>` tag with the Base64 string automatically set as the URL. This was very useful because we would simply save the field output as a string in our database and therefore we were able to get around the need for building up an image uploading service.

### How can we reproduce the bug on our side?

This can be reproduced in two ways:

**1. Tiptap documented example**

Follow the instructions as defined in the documentation for the Image node [here](https://tiptap.dev/api/nodes/image). You will find that if you drag/drop an image from your desktop onto the editor, the image opens in the browser tab rather than being inputted into the editor.

**2. Using `setContent()`**

Upon doing the following:

```
import Image from '@tiptap/extension-image'

...

this.editor = new Editor({
  content: '<p>Lorem ipsum dolor sit amet</p><p><img src=\"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQA..."></p>',
  extensions: [
    StarterKit,
    Image
  ]
})
```

you will find that the image is entirely stripped out of the HTML that ultimately makes it into the tiptap editable field.

### What did you expect to happen?

The expectation was that upon migrating from tiptap v1 to v2, the Image extension would continue to support inline Base64 image drag and dropping.

### Anything to add? (optional)

Just wanted to say that tiptap is otherwise incredible and I appreciate all your efforts! 😊 

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
base64 images are not supported anymore. you can add the plugin from v1 to add support for it https://github.com/ueberdosis/tiptap/blob/570a1dafd3ad1e5a351a20441e1986b70b93a259/packages/tiptap-extensions/src/nodes/Image.js#L73-L113

**Comment by Slapbox** [comment]
@philippkuehn is Base64 really and still not supported? There's an open discussion about this where it seems that even the workaround doesn't really work? https://github.com/ueberdosis/tiptap/discussions/3391

**Comment by uccmen** [comment]
what worked for me was I needed to set `allowInline: true` as well

```
Image.configure({ inline: true, allowBase64: true })
```

**Comment by niltonvaz** [comment]
> o que funcionou para mim foi que eu precisava definir `allowInline: true`também
> 
> ```
> Image.configure({ inline: true, allowBase64: true })
> ```

Em qual arquivo vc configura e passa essa linha?
