### ISSUE TITLE
Table - Copy and past on notepad only past last selected cell content

### ISSUE THREAD

**Issue by jigneshsuvariya** [ueberdosis/tiptap#1982]
### What’s the bug you are facing?

When we use table extension, select multiple cells and when do copy with ctrl+c and past it into notepad or notepad++ or anywhere it just past last selected table cell content only.

But when we past in same table or another instance on the table (tiptap table), It's working fine.
Even working well if we directly past in tiptap editor itself.

But when we do plain text past it adds only the last cell text.

### How can we reproduce the bug on our side?

https://tiptap.dev/examples/tables

Select 2 or more cells and copy them and then past them somewhere else (in notepad or anywhere else).

Even do ctrl+shift+v (plain text past) in the editor itself will past only the last cell text only.

### What did you expect to happen?

Past in another notepad or anywhere else should be past content of all cells we selected.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Confirmed. There seems to be an issue with our custom [clipboardTextSerializer](https://github.com/ueberdosis/tiptap/blob/main/packages/core/src/extensions/clipboardTextSerializer.ts).
