### ISSUE TITLE
Continuously refreshed table with tiptap v1

### ISSUE THREAD

**Issue by emendo-web** [ueberdosis/tiptap#1983]
Hello,

### What’s the bug you are facing?

I have a problem with the tables on version 1 of tiptap.

When we have a link in the table, the table is continuously refreshed.

We see it especially when there is an image in the same table. The image disappears and reappears in a loop.

### How can we reproduce the bug on our side?

You can see the code with this link: [https://codesandbox.io/s/tiptap-table-k391z](https://codesandbox.io/s/tiptap-table-k391z).

To reproduce the bug, you must display the result of the codesandbox in a new tab with chrome and open the element inspector. [https://k391z.csb.app/](https://k391z.csb.app/)

### What did you expect to happen?

The contents of the table should not loop reload.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

Deniz.

**Comment by philippkuehn** [comment]
Sorry, I can’t reproduce this in any of my browsers. Maybe the issue comes from a browser extension?
