### ISSUE TITLE
Export to a `docs` or `pdf`

### ISSUE THREAD

**Issue by BroJenuel** [ueberdosis/tiptap#1996]
### What problem are you facing?

Writing in a text editor is fine, but what if the user wants to export it as a doc or pdf.

### What’s the solution you would like to see?

Users can able to export to docs or pdf file format.

### What alternatives did you consider?

using this https://github.com/curvenote/prosemirror-docx but I am not sure if this will work since its still on its development.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Sorry but I have to mark this as out of scope for tiptap itself.
