### ISSUE TITLE
Add some code to suggestions example in doc

### ISSUE THREAD

**Issue by sotaan** [ueberdosis/tiptap#201]
Hey👋,
First, I wanted to say I really like this package a lot. It saved me tons of time and efforts so many thx for this. 👏 

By tweaking around _Suggestions plugin_ a little bit, I came around a use case not documented in the example that might be useful (I think...).
I wanted to trigger the required character insertion at the cursor position and give focus back to the editor (in order to implement the same behavior as the user actually typed).
This allowed me to associate a button in my toolbar (using `editor-menu-bar`)

Here is the code I use in my component wrapping business logic:
```js
<template>
...
<editor-menu-bar :editor="editor">
...
  <button
              class="menubar__button"
              @click="triggerSuggestion"
            >
    <icon name="suggestion" />
  </button>
</editor-menu-bar>
</editor>
</template>

<script>
import { insertText } from 'tiptap-command'

...

methods: {
 triggerSuggestion () {
    const { view } = this.editor
    // inserts char programmatically
    insertText('@')(view.state, view.dispatch, view)
    // give focus back to editor
    this.editor.focus()
  }
}
</script>
```
### Questions
1. Is this OK or I shall break something?
2. I can't find the better way to insert extension's `matched.char` value. What should I do? 

*Note:* I edited a lot, I'm sorry

**Comment by sotaan** [comment]
I found a problem with my solution: `onEnter` handler is called with an empty array as value for `items`.
If I trigger suggestions popup manually using the keyboard, then both usages begin to work

**Comment by sotaan** [comment]
More infos: the `onFilter` function is called with `query === ""` but `query.length === 1` 😮 .
When I inspect the string in a debugger: `query.charCodeAt(0) === 0`.
For me there can be two causes: 
1. the source of my content is full of dangerous characters. I changed my text by something typed and no problems yet...
2. `br` /HardBreak is the next character after the suggestion element inside editor

**Comment by sotaan** [comment]
Update: my content might have been polluted. You can skip the two last comments ⬆️

**Comment by hanspagel** [comment]
Thanks for sharing! Your use case is part of the example now: https://tiptap.dev/suggestions
