### ISSUE TITLE
React highlight extension (TypeError: rules[i].match.exec is not a function)

### ISSUE THREAD

**Issue by novikov1337danil** [ueberdosis/tiptap#2013]
### What’s the bug you are facing?

First, thanks for great lib!

i am facing a bug in react when using the Highlight extension

### How can we reproduce the bug on our side?

[codesandbox](https://codesandbox.io/s/jovial-firefly-9ldfb?file=/src/App.js)

**Comment by philippkuehn** [comment]
update to the latest versions.
