### ISSUE TITLE
Image input rule leaves erroneous text behind

### ISSUE THREAD

**Issue by nokola** [ueberdosis/tiptap#2016]
### What’s the bug you are facing?

Typing in markdown image shows this extra text:
![image](https://user-images.githubusercontent.com/6869225/136760127-ce6d0af4-fdf6-41d8-a789-e893d68c41ae.png)

### How can we reproduce the bug on our side?

1. https://codesandbox.io/s/tiptap-after-paste-bug2-dataloss-forked-gclpv?file=/src/App.vue
2. Type: `![test](url)`

### Can you provide a CodeSandbox?

See repro

### What did you expect to happen?

Image shows up without extra text around it

### Anything to add? (optional)

Happens after the new update-after-paste changes to tiptap core.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Oh, this error seems to be caused [by your PR](https://github.com/ueberdosis/tiptap/pull/1574) :D

**Comment by nokola** [comment]
Checked all uses of nodeInputRule() - all look good! It's only used in `image` and `hr`.
![image](https://user-images.githubusercontent.com/6869225/136837924-f2c74bd7-44b3-40b6-90a7-de871b57d159.png)
