### ISSUE TITLE
Data loss: pasting newlines sometimes lost

### ISSUE THREAD

**Issue by nokola** [ueberdosis/tiptap#2017]
### What’s the bug you are facing?

Sometimes when pasting new lines, they are lost. See repro steps.

### How can we reproduce the bug on our side?

1. https://codesandbox.io/s/tiptap-after-paste-bug2-dataloss-forked-gclpv
2. Paste:
```
test

test
xyz
```

Result: 
![image](https://user-images.githubusercontent.com/6869225/136763142-8183e2a6-4773-4889-994d-013d93ff17ed.png)

### Can you provide a CodeSandbox?

https://codesandbox.io/s/tiptap-after-paste-bug2-dataloss-forked-gclpv

### What did you expect to happen?

new line to be preserved between "test" and "xyz"
Note that pasting this works:
```
test
xyz
```

![image](https://user-images.githubusercontent.com/6869225/136763191-bf91e955-c0e3-4a14-a26c-95835278d5de.png)

### Anything to add? (optional)

Was working OK before the input/paste rules change

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by nokola** [comment]
I figured out the issue with the `testxyz` merged together! It only happens when copying from VS code.
I used [Clipboard Inspector online](https://evercoder.github.io/clipboard-inspector/) and found that VS code sends the text as `<div>`-s instead of `<p>`-s. ProseMirror does not convert the `<div>`-s to paragraphs, and the text is munged together. 

I couldn't reproduce above because I was copy-pasting sometimes from Notepad sometimes from VS code assuming they are the same.

Special case for VS code has to be handled if there's a `vscode-editor-data` section. I'll open a feature request to keep track.

```
<html>
<body>
<!--StartFragment--><div style="color: #d4d4d4;background-color: #1e1e1e;font-family:  'Iosevka SS08', 'Cascadia Code SemiLight', 'Fira Code', Consolas, 'Courier New', monospace, Consolas, 'Courier New', monospace;font-weight: normal;font-size: 14.5px;line-height: 20px;white-space: pre;"><div><span style="color: #6a9955;">hello</span></div><br><div><span style="color: #6a9955;">test</span></div><div><span style="color: #6a9955;">xyz</span></div></div><!--EndFragment-->
</body>
</html>
```

![image](https://user-images.githubusercontent.com/6869225/136897050-abcb7602-a3a3-4e04-aa25-0ea0a00a9a4a.png)

**Comment by nokola** [comment]
> Note: still having further problems with pasting nodes, e.g. in my custom project:
> 
> ```
> test *bold*[[date]]
> xyz
> 
> [[date]]
> 
> [[date]]
> Y[[date]]x
> ```
> 
> Results in some significant data loss (last two lines are completely missing)
> 
> ![image](https://user-images.githubusercontent.com/6869225/136763665-fde21d1a-5961-4d48-8b0f-4c29cc6d7fbf.png)
> 
> I'll open that bug if needed after this one is fixed. Maybe the above issue will be fixed too. This also worked OK before the input/paste rule updates.

Figured it out - all because of copy-paste from VS code! Does not reproduce from Notepad.

Note: before it used to work, because I handled the plain text in onBeforePaste(). 
Opened tracking feature request #2021

**Comment by danlyke** [comment]
Finding that newlines are correctly preserved when pasting from Apple's TextEdit app *and* the document in that app is rich text. If the document in that app has been converted to plain text, extra newlines between paragraphs get swallowed, so everything ends up single-spaced.
