### ISSUE TITLE
After pasting a block, should select pasted block

### ISSUE THREAD

**Issue by forresto** [ueberdosis/tiptap#2029]
### What’s the bug you are facing?

After pasting a block, the next block is selected. I expect it to select the pasted block.

### How can we reproduce the bug on our side?

I noticed this with our own custom blocks, but it's also reproducible with the image example: https://tiptap.dev/api/nodes/image

1. Select first image
2. Cut
3. Focus end of first paragraph
4. Paste
5. Second image is selected

### What did you expect to happen?

I expect it to select the pasted block.

### Anything to add? (optional)

Walkthrough screenshot with audio:

https://user-images.githubusercontent.com/395307/137098288-0c0045fd-d473-4179-a51f-7b9b0eb412ea.mov

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by cadars** [comment]
FWIW, this also happens with `<hr>` nodes.
