### ISSUE TITLE
Write more tests

### ISSUE THREAD

**Issue by hanspagel** [ueberdosis/tiptap#2033]
### What problem are you facing?

There are a few examples that don’t have any tests:

- [ ] [demos/src/Examples/Book/Vue/index.spec.js](https://github.com/ueberdosis/tiptap/blob/main/demos/src/Examples/Book/Vue/index.spec.js)
- [ ] [demos/src/Examples/CollaborativeEditing/Vue/index.spec.js](https://github.com/ueberdosis/tiptap/blob/main/demos/src/Examples/CollaborativeEditing/Vue/index.spec.js)
- [ ] [demos/src/Examples/Community/Vue/index.spec.js](https://github.com/ueberdosis/tiptap/blob/main/demos/src/Examples/Community/Vue/index.spec.js)
- [ ] [demos/src/Examples/CustomDocument/Vue/index.spec.js](https://github.com/ueberdosis/tiptap/blob/main/demos/src/Examples/CustomDocument/Vue/index.spec.js)
- [ ] [demos/src/Examples/Formatting/Vue/index.spec.js](https://github.com/ueberdosis/tiptap/blob/main/demos/src/Examples/Formatting/Vue/index.spec.js)
- [ ] [demos/src/Examples/Images/Vue/index.spec.js](https://github.com/ueberdosis/tiptap/blob/main/demos/src/Examples/Images/Vue/index.spec.js)
- [x] [demos/src/Examples/Menus/React/index.spec.js](https://github.com/ueberdosis/tiptap/blob/main/demos/src/Examples/Menus/React/index.spec.js)
- [x] [demos/src/Examples/Menus/Vue/index.spec.js](https://github.com/ueberdosis/tiptap/blob/main/demos/src/Examples/Menus/Vue/index.spec.js)
- [x] [demos/src/Examples/Minimal/Vue/index.spec.js](https://github.com/ueberdosis/tiptap/blob/main/demos/src/Examples/Minimal/Vue/index.spec.js)
- [x] [demos/src/Examples/Savvy/Vue/index.spec.js](https://github.com/ueberdosis/tiptap/blob/main/demos/src/Examples/Savvy/Vue/index.spec.js)
- [ ] [demos/src/Examples/Tables/Vue/index.spec.js](https://github.com/ueberdosis/tiptap/blob/main/demos/src/Examples/Tables/Vue/index.spec.js)
- [ ] [demos/src/Examples/Tasks/Vue/index.spec.js](https://github.com/ueberdosis/tiptap/blob/main/demos/src/Examples/Tasks/Vue/index.spec.js)
- [ ] [demos/src/Extensions/Collaboration/Vue/index.spec.js](https://github.com/ueberdosis/tiptap/blob/main/demos/src/Extensions/Collaboration/Vue/index.spec.js)
- [ ] [demos/src/Extensions/CollaborationCursor/Vue/index.spec.js](https://github.com/ueberdosis/tiptap/blob/main/demos/src/Extensions/CollaborationCursor/Vue/index.spec.js)
- [ ] [demos/src/Extensions/Dropcursor/Vue/index.spec.js](https://github.com/ueberdosis/tiptap/blob/main/demos/src/Extensions/Dropcursor/Vue/index.spec.js)
- [ ] [demos/src/Extensions/FontFamily/Vue/index.spec.js](https://github.com/ueberdosis/tiptap/blob/main/demos/src/Extensions/FontFamily/Vue/index.spec.js)
- [ ] [demos/src/Extensions/Gapcursor/Vue/index.spec.js](https://github.com/ueberdosis/tiptap/blob/main/demos/src/Extensions/Gapcursor/Vue/index.spec.js)
- [ ] [demos/src/GuideContent/GenerateHTML/Vue/index.spec.js](https://github.com/ueberdosis/tiptap/blob/main/demos/src/GuideContent/GenerateHTML/Vue/index.spec.js)
- [ ] [demos/src/GuideContent/GenerateJSON/Vue/index.spec.js](https://github.com/ueberdosis/tiptap/blob/main/demos/src/GuideContent/GenerateJSON/Vue/index.spec.js)
- [ ] [demos/src/GuideContent/GenerateText/Vue/index.spec.js](https://github.com/ueberdosis/tiptap/blob/main/demos/src/GuideContent/GenerateText/Vue/index.spec.js)
- [ ] [demos/src/GuideGettingStarted/VModel/Vue/index.spec.js](https://github.com/ueberdosis/tiptap/blob/main/demos/src/GuideGettingStarted/VModel/Vue/index.spec.js)
- [ ] [demos/src/Marks/TextStyle/Vue/index.spec.js](https://github.com/ueberdosis/tiptap/blob/main/demos/src/Marks/TextStyle/Vue/index.spec.js)
- [ ] [demos/src/Nodes/Mention/Vue/index.spec.js](https://github.com/ueberdosis/tiptap/blob/main/demos/src/Nodes/Mention/Vue/index.spec.js)
- [ ] [demos/src/Nodes/TaskItem/Vue/index.spec.js](https://github.com/ueberdosis/tiptap/blob/main/demos/src/Nodes/TaskItem/Vue/index.spec.js)

### What’s the solution you would like to see?

 It would be great to change this. Maybe some people would like to help with that?

### What alternatives did you consider?

We have a few hundred tests already, so maybe it’s fine to leave them empty. But on the other side examples break from time to time, and having more tests feels just better and should make contributing easier.

### Anything to add? (optional)

1. There is no need to reinvent the wheel. We already have a ton of tests and a lot of them can probably be copied and just slightly modified.
2. If you’re up to contribute tests, make sure to file PRs for a single test file only. That makes looking through them and merging them way easier.

### How to write tests

1. Fork the repo, clone it to your machine.
2. Install everything with `yarn install`
3. Open the test console with `yarn test:open`
4. Start writing tests in one of the above mentioned files
5. Push your changes and create a PR 🙌

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by donovanglover** [comment]
Thanks for this opportunity! It's a good way to practice using cypress in a real project.

**Comment by hanspagel** [comment]
Added this for hacktoberfest, so closing this for now.
