### ISSUE TITLE
Add option to pass PluginKey to mention extension

### ISSUE THREAD

**Issue by jamesopti** [ueberdosis/tiptap#2034]
### What problem are you facing?

We're implementing a reusable render function for the suggestion plugin, and when using it with the mention extension, we'd like to be able to reference the plugin key for the instance of the extension.

Right now, it's hardcoded at the top of the file.

### What’s the solution you would like to see?

A pluginKey option similar to [BubbleMenu](https://github.com/ueberdosis/tiptap/blob/e37639ac6d2131bee0e3cd640e5f45499ab7c529/packages/extension-bubble-menu/src/bubble-menu.ts#L25)

### What alternatives did you consider?

Forking

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
The `MentionPluginKey` already gets exported. 

Or you can also pass a custom key via `suggestion.pluginKey`.
