### ISSUE TITLE
Links issue

### ISSUE THREAD

**Issue by dan-danciu** [ueberdosis/tiptap#204]
Adding links works very nicely when used as in the example.
However if I make this one tiny change it stops working:

original:
```
<template v-else>
          <button 
              @click="showLinkMenu(getMarkAttrs('link'))" 
              :class="{ 'is-active': isActive.link() }">
            <span>Link</span>
          </button>
</template>
```

to:
```
<template v-else>
          <div 
              @click="showLinkMenu(getMarkAttrs('link'))" 
              :class="{ 'is-active': isActive.link() }">
            <span>Link</span>
          </div>
</template>
```

The result is that when clicking on the "div" the menu bubble dissapears completely and then if you select a bunch of text again the linkUrl input appears directly.

I can not see any reason for this at the moment. (maybe I should actually check the code but... some other day)
What I am actually trying to accomplish is to change the buttons with some svg which worked well so far but I can not make it work with the Link functionality because of this behaviour.

**Comment by dan-danciu** [comment]
I presume it has something to do with how somehow the default onclick of the button is different from the div v-on:click that vue adds but I am too new at tis stuff to figure that out on my own yet.
I tried adding all kinds of event modifiers like .native .stop .prevent (without really understanding them all that well) but nothing seems to make it work as a div.

I worked around the problem by putting my svg icon inside the button and making the button like this:
```
.invisibutton {
  border: none;
  background: none;
  margin: 0px;
  padding: 0px;
}
```

It's a bit wonky but it works and I can still manipulate the svg inside.
I would still like to find out why the div tag (or <a> for that matter) does not work, if possible.

Thanks,
Dan

**Comment by sotaan** [comment]
I believe your behavior might come from this: https://github.com/scrumpy/tiptap/blob/master/packages/tiptap/src/Plugins/MenuBubble.js#L30

if your selection changes, tooltip might hide if it became empty. I guess clicking on the button might cause a loose of focus for the editor which ultimately cause this.
Try to call `event.preventDefault()` or do a `@click.prevent` and hope for the best 😄 🤞

**Comment by dan-danciu** [comment]
That is exactly what I think as well.
One of the first things I tried was @click.prevent but alas, it is not working :|

I wish I knew the difference between a button @click and a div @click events :)

**Comment by erickwilder** [comment]
@dan-danciu 
> I wish I knew the difference between a button @click and a div @click events :)

I would advise you to _not use `div` as buttons because this makes it pretty unusable from an accessibility point of view. Screen readers, for example, will have a hard time to identify a button that is actually a `div`.

Buttons have a lot more than a `div` and it is the _correct_ markup because:
* They can be focused
* They are accessible with a keyboard (tab, and arrow keys)
* They naturally respond to key presses (not only clicks)

A good one to help you decide is on [CSS tricks](https://css-tricks.com/use-button-element/) and also on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button)
