### ISSUE TITLE
How to handle flicker on mount

### ISSUE THREAD

**Issue by kylesuss** [ueberdosis/tiptap#2040]
### What’s the bug you are facing?

Hi! We are working to integrate TipTap into our app & are pretty early in the process. Thanks for the hard work on the lib.

When first rendering the editor, we notice that there is a period of time where nothing is rendered. Taking the [CodeSandbox](https://codesandbox.io/s/brave-thunder-7h41n?file=/src/App.js) (also linked below), I can toggle the editor & see that when the editor is meant to be shown, the first render cycle is empty.

Is this expected? Can it be fixed?

**Before toggle**
----
![data_image_jpg;base… (1)](https://user-images.githubusercontent.com/3035355/137371183-9bfb3515-f7b0-4f20-a69e-d0a01715c86e.jpeg)

**After toggle**
----
![data_image_jpg;base… (2)](https://user-images.githubusercontent.com/3035355/137371185-c0d32bc0-9c49-4754-9629-9b24281db487.jpeg)

**Editor now visible ("test")**
----
![data_image_jpg;base… (3)](https://user-images.githubusercontent.com/3035355/137371186-5937d074-52e6-4551-902d-a319bbb4b485.jpeg)

### How can we reproduce the bug on our side?

I was using the Chrome devtools Performance tab to record the behavior and capture screenshots.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/brave-thunder-7h41n?file=/src/App.js

### What did you expect to happen?

I would expect there to be a way to avoid this flicker situation & have the editor visible on mount, but perhaps I am missing something in my setup?

### Anything to add? (optional)

I am using the React lib & `useEditor`.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by Miloshinjo** [comment]
Having the same issue in React with `useEditor`. Editor shows empty before showing text, causing the screen flicker.

**Comment by philippkuehn** [comment]
I had to revert the last change. If you want to prevent that flicker you can use a [custom `useEditor`](https://gist.github.com/ryanto/4a431d822a98770c4ca7905d9b7b07da) hook.

**Comment by ospfranco** [comment]
![Screen Recording 2022-01-18 at 19 46 49](https://user-images.githubusercontent.com/1634213/150000015-272a3077-e560-4712-893f-a99da52d60d6.gif)

I'm seeing crazy amounts of flicker in my next.js app, any idea who to mitigate this issue? it happens every time I change any of the props

**Comment by ospfranco** [comment]
just realized it not only flickers but actually completely resets itself, when I type the cursor moves back to the first position

**Comment by hanspagel** [comment]
I can read the code on the screenshot, so without that it’s hard to say. :)

**Comment by ospfranco** [comment]
Trying to debug several issues right now, my entire code is here:

https://github.com/ueberdosis/tiptap/issues/2403

whenever adding a dependency to the useEditor hook the entire instance is destroyed which is not what I want

**Comment by Miloshinjo** [comment]
Has anyone found at least a workaround for this issue?

**Comment by ospfranco** [comment]
Only load the instance once, then you have to use internal methods to reset the content and any handlers you have passed, here you can see some code on how to reset the handlers:

https://github.com/ueberdosis/tiptap/issues/2403

For the content there are other calls like `editor.commands.setContent`

That is the only way you will avoid flickers, trying to change them via the hook results in the internal editor instance being completely destroyed and re-mounted, so no way to use that

**Comment by Miloshinjo** [comment]
> Only load the instance once, then you have to use internal methods to reset the content and any handlers you have passed, here you can see some code on how to reset the handlers:
> 
> #2403
> 
> For the content there are other calls like `editor.commands.setContent`
> 
> That is the only way you will avoid flickers, trying to change them via the hook results in the internal editor instance being completely destroyed and re-mounted, so no way to use that without having flickers

How do you load the instance only once?

**Comment by rfgamaral** [comment]
> Just want to say that I used a custom hook that Phillip suggested and UI flicker is gone now. Edited it a bit to suit my case, but essentially it worked.

@Miloshinjo Would you mind sharing your edited version and explain your changes? Maybe it can be useful to others :)

**Comment by Miloshinjo** [comment]
> > Just want to say that I used a custom hook that Phillip suggested and UI flicker is gone now. Edited it a bit to suit my case, but essentially it worked.
> 
> @Miloshinjo Would you mind sharing your edited version and explain your changes? Maybe it can be useful to others :)

hello, it's this gist https://gist.github.com/ryanto/4a431d822a98770c4ca7905d9b7b07da, but I just removed 2 calls to `requestsAnimationFrame` and in my case, flickers were gone.

Also the option I'm using on the editor is `editable: false` , not sure if it matters, but I wanted to give u the full picture.

**Comment by rfgamaral** [comment]
@Miloshinjo Thank you 👍

**Comment by benkingcode** [comment]
This is driving me crazy, is there really no fix coming for this? I have a very simple use case, an editor with the Collaboration extension, and I cannot switch documents without a jarring flicker.

**Comment by Nantris** [comment]
This issue should not be closed.
