### ISSUE TITLE
Task list ignores HTMLAttributes from its options

### ISSUE THREAD

**Issue by martindzejky** [ueberdosis/tiptap#2042]
### What’s the bug you are facing?

TaskList ignores HTMLAttributes from its options. This seems to be because `this.options.HTMLAttributes` is not used in its `renderHTML` function here:

https://github.com/ueberdosis/tiptap/blob/0a5d4b6658e02cda045c866056c23c4e2091a4cb/packages/extension-task-list/src/task-list.ts#L39

### How can we reproduce the bug on our side?

Specify `HTMLAttributes` for a TaskList. Those attributes do not appear in the HTML.

### What did you expect to happen?

Configured `HTMLAttributes` appear in the rendered HTML.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
@andycarrell Hmm this is another issue because `taskItem` is using a node view by default which ignores the default render method. But I think we should add `HTMLAttributes` to the node view element too. Could you please create an issue for that?
