### ISSUE TITLE
Question: the best way to add tooltip for an image node?

### ISSUE THREAD

**Issue by alotex** [ueberdosis/tiptap#205]
I'm trying to create a tooltip for an image and also I want to keep tooltip for Link nodes. Is it possible through EditorBubble?
Thanks

**Comment by sotaan** [comment]
Do you mean `EditorMenuBubble`?
If you check out the example here: https://github.com/scrumpy/tiptap/blob/master/examples/Components/Routes/Links/index.vue
you must find a good codebase to starts with.
If your use case is different, then explains it to me simply, maybe I can help you adapt...

**Comment by alotex** [comment]
Hi [sotaan](/sotaan)
thanks for the response. I've already checked the source code the link tooltip. I was wondering about how to hide a link related controls and show only image related controls. Also, I've noticed a weid issue - please see the attached screenshot. 
![image](https://user-images.githubusercontent.com/47648493/53194610-f7371d00-363d-11e9-8d32-2ad2bdba2d98.png)

dependencies are
```
"dependencies": {
    "tiptap": "^1.7.0",
    "tiptap-extensions": "^1.7.0",
    "bulma": "^0.7.1",
    "vue": "^2.5.17"
  },

```

**Comment by sotaan** [comment]
Here is what I did in my project. I coded this method: 
```
/**
     * Determines if the user has its cursor inside a link
     *
     * @param {object} markAttrs  The Mark instance attrs state
     * @returns {boolean} Whether or not the cursor is inside a link
     */
    cursorIsOnLink(markAttrs) {
      const keys = Object.keys(markAttrs)

      return Boolean(keys.length && keys.indexOf('href') !== -1)
    },
```
The you can use it in your `editor-bubble-menu` to do a `v-if` to determine if a link is on current caret/cursor
