### ISSUE TITLE
Possibility to inject styles in custom place (e.g. ShadowRoot, scoped styles)

### ISSUE THREAD

**Issue by Sharsie** [ueberdosis/tiptap#2066]
### What problem are you facing?

Hello, I am trying to render the editor inside a shadow root due to other functionality on the page that alters styles of html elements by tag name and this messes with the editor styles.

For that reason, we are closing most libraries inside a shadow root on custom element and separating them away from the rest of the page.

### What’s the solution you would like to see?

I would like to see an option to specify either a style DOM element, or a parent element where to inject the style element as an extension to `injectCss: false`.

In order to prevent global pollution, [createStyleTag](https://github.com/ueberdosis/tiptap/blob/main/packages/core/src/utilities/createStyleTag.ts) could operate on the provided dom element instead of `document`.

### What alternatives did you consider?

I am currently solving this using custom style import as such:

```javascript
import { Editor } from "@tiptap/core";
import style from "@tiptap/core/src/style";

// component creation and then the following

// Create style tag
const styleElement = document.createElement('style');
styleElement.innerHTML = style;

// Create wrapper that will be injected into the DOM
const divWrapper = document.createElement("div");
// Attach the shadow root to the wrapper
const shadowRoot = divWrapper.attachShadow({ mode: "open" });
// Attach the style tag to the shadow root
shadowRoot.appendChild(styleElement);

// We need to put the editor deeper in the tree for some extensions to work
// e.g. bubble menu uses a condition of editorElement.parentElement to determine
// whether the editor is attached. If it is not (parent is ShadowRoot), it stops execution
// Also the editor cannot attach to shadow root
const shadowWrapper = document.createElement('div');
shadowRoot.appendChild(shadowWrapper);
const bindTo = document.createElement("div");
shadowWrapper.appendChild(bindTo);

// Instantiate the editor
const editor = new Editor({
  element: bindTo,
  injectCSS: false,
  //...
});
```

### Anything to add? (optional)

Would you consider a PR?
Also some functionalities might not work when attached directly in the shadow root (see comment in the code above) but this is out of scope of this issue, just stumbled on this by accident.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by gwidonw** [comment]
That's a nice proposal. +1 for it!

**Comment by Sharsie** [comment]
Due to issues with the combination of shadow root and contentEditable (and the fact that contentEditable is not officially supported inside shadow root in some browsers) I would consider my proposal void. I am not sure if this would find any use outside of the shadow root.
