### ISSUE TITLE
DOMException caused in NodeView with image

### ISSUE THREAD

**Issue by jpdigital** [ueberdosis/tiptap#2076]
### What’s the bug you are facing?

I created a interactive node view for inserting images inside a figure block. The node view works fine, but when loading a document with a block already in the document a DOMException is thrown somewhere inside Tiptap. The HTML of the inserted block looks like this:

```
<figure data-align="center" data-size="50" data-type="librecms-image-node">
  <img alt="some alt text" src="/path/to/image">
  <figcaption>Some caption</figcaption>
</figure
```

Unfortunately, the stack trace of the `DomException` does not give a hint about the problem, the name is `InvalidStateError` and the message is `An exception was thrown`. But if there is no URL in the `src` attribute of the `img` element, no exception is thrown. Any hints how to debug this? 

### How can we reproduce the bug on our side?

Creating a node view with an image should be enough.

### Can you provide a CodeSandbox?

The editor and the node itself are unfortunately very tightly  integrated with an application, therefore I can't provide a code example.

### What did you expect to happen?

No exception.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by rezaffm** [comment]
difficult to comment or add anything without any code. But would be highly interested in this.

**Comment by jpdigital** [comment]
I actually found out what the problem was, by stepping through the code with the debugger. It was only a small typo... In the `renderHTML` function of my node view I had this (slightly shortened, in the node view there are also some attributes for the figure element):

```
renderHTML({ node, HTMLAttributes }) {
    return [
        "figure",
        [
            "img",
            {
                alt: node.attrs.altText,
                src: node.attrs.imgSrc,
            },
        ],
        ["figcaption", [node.attrs.figCaption]],
    ];
},
```

When `node.attrs.figCaption` was an empty string, the problem occurred. I solved this now by simply removing the braces around `node.attrs.figCaption`:

```
renderHTML({ node, HTMLAttributes }) {
    return [
        "figure",
        [
            "img",
            {
                alt: node.attrs.altText,
                src: node.attrs.imgSrc,
            },
        ],
        ["figcaption", node.attrs.figCaption],
    ];
},
```
