### ISSUE TITLE
how to pass dynamic options to a mark

### ISSUE THREAD

**Issue by xerosanyam** [ueberdosis/tiptap#208]
while declaring editor, I add plugin bold and pass options as:
```
new Bold({'visibility':this.visibility}
```

inside bold mark, I have a dynamic class that I want to toggle based on property visibility
```
get view () {
    return {
      props: ['node', 'updateAttrs', 'options'],
      template: `
        <span :class="[options.visible?'deleted':'hide']">
        </span>
      `
    }
  }
```
but options.visibility is not getting updated.

How to pass a reactive property to a mark ?

**Comment by Chrissi2812** [comment]
You have to setup a watcher that updates the plugin options.

```js
export default {
  data() {
    return {
      visibilty: false,
      editor: new Editor({
        extensions: [
          new Bold(),
        ],
      }),
    }
  },
  watch: {
    visibilty(newValuel) {
      // Find the Plugin we want to update, maybe there is a better way to reference it.
      const BoldExt = this.editor.extensions.extensions.find(ext => ext.name === 'bold')
      BoldExt.options.visible = newValuel
    },
  },
}
```

**Comment by emanuelgsouza** [comment]
Hey, I am facing this same problem in this moment. I think it should be good to add a method in the editor, for example `updateExtension(extensionName: string, options: any)` (I don't know too much Typescript, so ignores the any here), which will handle with this, maybe executing the same logic above - searching for the extension and updating the options.

Anyway, you have done a great job

**Comment by hanspagel** [comment]
Thanks! I’m closing this here as it doesn’t seem to bug too many people and a workaround exists. ✌️
