### ISSUE TITLE
Placeholder not showing up

### ISSUE THREAD

**Issue by Harvey-Mushman** [ueberdosis/tiptap#2080]
### What’s the bug you are facing?

I've installed placeholder extension and followed all the instructions but can't get the text to be displayed.  I can see the <p> element with class="is-empty is-editor-empty" and data-placeholder="Write something _" but nothing is being displayed.

No clue where to go looking at this point...?

Do these two classes need to be configured and if so what would the CSS need to be?

Any help would be very appreciated!

### How can we reproduce the bug on our side?

I have no clue, I would have assumed it just worked.  And I assume you tested it before releasing, so I really need help to know where to start to track down the problem.

### What did you expect to happen?

Expected tot see placeholder text in the area where content will be entered by the user.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by AxelBriche** [comment]
I have a problem with placeholder inside paragraph, when I remove all the text, the placeholder is displayed, if I click on the editor, a "<br class="ProseMirror-trailingBreak">" is added and the placeholder is not displayed because <p><br></p> is not considered like empty.
