### ISSUE TITLE
[React][ext-placeholder]: The Placeholder extension doesn't work with React+TypeScript

### ISSUE THREAD

**Issue by Iipal** [ueberdosis/tiptap#2092]
### What’s the bug you are facing?

![image](https://user-images.githubusercontent.com/31858171/139051382-c7d0e420-eaa0-416b-a4b4-2c30a4fca544.png)

### How can we reproduce the bug on our side?

- create-react-app with TypeScript template ("react": "^17.0.2" + "typescript": "^4.1.2")
- install TipTap packages and Placeholder extension
- import it to your component (from "@tiptap/extension-placeholder" as shown in the docs) to the extensions list in useEditor config
- none

### What did you expect to happen?

Placeholder to be displayed

### Anything to add? (optional)

all the TipTap packages installed:
```json
{
    "@tiptap/extension-code": "^2.0.0-beta.21",
    "@tiptap/extension-document": "^2.0.0-beta.13",
    "@tiptap/extension-link": "^2.0.0-beta.24",
    "@tiptap/extension-paragraph": "^2.0.0-beta.18",
    "@tiptap/extension-placeholder": "^2.0.0-beta.37",
    "@tiptap/extension-text": "^2.0.0-beta.13",
    "@tiptap/extension-typography": "^2.0.0-beta.17",
    "@tiptap/react": "^2.0.0-beta.86",
    "@tiptap/starter-kit": "^2.0.0-beta.131",
}
```

useEditor config:
```ts
  const editor = useEditor({
    content: undefined,
    extensions: [
      StarterKit,
      Typography,
      Paragraph,
      Document,
      Text,
      Link,
      Placeholder.configure({
        placeholder: placeholder,
      }),
      Code.configure({
        HTMLAttributes: {
          class: `app-common-cmp-rich-input-code ${schema}`,
        },
      }),
      SmilieReplacer,
    ],
  });
  ```

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by dhythm** [comment]
I'm also facing the same issue for React + TypeScript environment.
In my case, I've put CSS stuff but the placeholder isn't shown.

dependencies are here.
```
    "@tiptap/extension-placeholder": "^2.0.0-beta.38",
```

code is here.
```
  const editor = useEditor({
    extensions: [
      Placeholder.configure({
        placeholder: ({ node }) => {
          console.log({ node });
          if (node.type.name === "heading") {
            return "What’s the title?";
          }

          return "Can you add some further context?";
        },
      }),
      StarterKit,
      Document,
    ],
    content: `
      <p>
        … if you pass a custom document. That’s the beauty of having full control over the schema.
      </p>
    `,
  });
```

CSS is here.
```
/* Basic editor styles */
.ProseMirror {
  > * + * {
    margin-top: 0.75em;
  }

  padding: 8px;
  p,
  h1,
  h2,
  h3 {
    margin: 0;
    line-height: 1.5;
  }

  .is-empty::before {
    content: attr(data-placeholder);
    float: left;
    color: #ced4da;
    pointer-events: none;
    height: 0;
  }
}

.ProseMirror p.is-editor-empty:first-child::before {
  content: attr(data-placeholder);
}
```

![image](https://user-images.githubusercontent.com/10891318/140013760-b0150be5-5920-4271-b135-5144ef359b82.png)

**Comment by dhythm** [comment]
Just resolved.
The [doc](https://tiptap.dev/api/extensions/placeholder#settings) tells both `emptyEditorClass` and `emptyNodeClass` have default value.
So, I didn't put those configs to `Placeholder.configure({ ... })`.
Now, I add either `emptyEditorClass` or `emptyNodeClass`, or both of them to `Placeholder.configure({ ... })`, then the placeholder works well 🎉

![image](https://user-images.githubusercontent.com/10891318/140015512-1f19bfce-2b1e-44e5-846a-af2668eb5152.png)

![image](https://user-images.githubusercontent.com/10891318/140015546-82b39486-0201-4b59-bb2b-c0945251c2b5.png)
