### ISSUE TITLE
TypeError: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by ionTea** [ueberdosis/tiptap#2107]
### What’s the bug you are facing?

# The issue
When calling `editor.getJSON()`, the result isn't serialisable. It seems like some objects don't have prototypes.

For example, this means we can't directly put the result from `editor.getJSON()` into redux without disabling redux error warnings.

I have tried a few block types, and so far only headings seem to be broken in this way, but I haven't tested them all.

Here's a sandbox showing the issue: https://codesandbox.io/s/green-hill-ybcgn?file=/src/App.js

## Example:
```
import "./styles.css";
import { useEditor, EditorContent } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";

export default function App() {
  const editor = useEditor({
    content: "<h1>hello</h1>",
    extensions: [StarterKit]
  });

  const explode = () => {
    const data = editor.getJSON();

    const attrs = data.content?.[0]?.attrs;

    console.log(data);
    console.log(`type: ${typeof attrs}`);
    // It looks like attrs is missing a prototype
    console.log(`attrs: ${attrs}`);
  };

  return (
    <div className="App">
      <h1>Hello Tiptap</h1>
      <h2>Click the button to see how it breaks</h2>
      <EditorContent editor={editor}></EditorContent>
      <button onClick={explode}>Explode</button>
    </div>
  );
}
```

## Work around

you can wrap the results like this:
```
const data = JSON.parse(JSON.stringify(editor.getJSON()))
```
It will clean up the result data. 

### How can we reproduce the bug on our side?

Create an editor with a heading, and the call `console.log(editor.getJSON());`

### Can you provide a CodeSandbox?

https://codesandbox.io/s/green-hill-ybcgn?file=/src/App.js

### What did you expect to happen?

I expect the result from `editor.getJSON()` to be valid and serializable.  

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by rkoleci** [comment]
can you assign this to me ?

**Comment by philippkuehn** [comment]
Hey, `getJSON()` is a simple method to call `state.doc.toJSON()`. This is a [ProseMirror method](https://prosemirror.net/docs/ref/#model.Node.toJSON). Maybe you can create an issue there? Because I don’t want to change the default behavior.
