### ISSUE TITLE
How to insert a table wrapped in a div?

### ISSUE THREAD

**Issue by rezaffm** [ueberdosis/tiptap#2109]
### What’s the URL to the page you’re sending feedback for?

https://tiptap.dev/api/nodes/table#insert-table

### What part of the documentation needs improvement?

I checked the insert table documentation and think it would be great if there would be an explanation about how to wrap / insert a table with a div. 

### What is helpful about that part?

The rest is quite comprehensive I believe.

### What is hard to understand, missing or misleading?

I am trying to overwrite the following command

```javascript
            insertTable: ({ rows = 3, cols = 3, withHeaderRow = true } = {}) => ({ commands, tr, dispatch, editor }) => {
                const node = createTable(editor.schema, rows, cols, withHeaderRow);
                if (dispatch) {
                    const offset = tr.selection.anchor + 1;
                    tr.replaceSelectionWith(node)
                        .scrollIntoView()
                        .setSelection(TextSelection.near(tr.doc.resolve(offset)));
                }
                return true;
            },
```
However, I am not smart enough to adjust the command in a way that when the table gets created it is wrapped in a div with a class, e.g. 'table-responsive'

**Comment by rezaffm** [comment]
and in case anyone stumbles around this issue...it is even simpler with:

```javascript
const node = editor.schema.node('div', { class: 'table-responsive'}, createTable(editor.schema, rows, cols, withHeaderRow))
```

I don't know, maybe it is just me, but any time I work with Prosemirror directly I feel idiotic after (sometimes) hours of debugging I find out how easy the solutions are.

I know this is tiptap, but sometimes there is no other way then working directly with Prosemirror.

What is really missing on Prosemirror side is kind of an intensive "recipies book" that just shows hot to solve some common issues, like:

- Wrapping nodes in other nodes
-  Lifting nodes out of nodes (like getting out all the p's from a div)
- How to set the selection to the next paragraph or end of the paragraph
- How to add classes et cetera

If the tiptap was open for such a thing, I am happy to add the first examples because I am getting tired of it.

**Comment by hanspagel** [comment]
Thanks for sharing! At least there’s this: https://github.com/PierBover/prosemirror-cookbook

Unfortunately, it’s not on our list to put together “prosemirror recipes”. Everyone has different issues/requirements. We’re following closely what people struggle with and if we see a pattern, we make sure to add it as a feature to Tiptap. I think that’s what we should focus on. ✌️

**Comment by rezaffm** [comment]
Actually, I still have to write this guide about how to migrate from tinymce to tiptap. Just need to find some time.

I really like what you re guys are doing, proud sponsor. ;-)

**Comment by hanspagel** [comment]
🙌 

That would be awesome! If you’re stuck, send the draft (PR or humans@tiptap.dev). I’ll see what I can do.

**Comment by codemzy** [comment]
Another option if you want every table to have that div wrapper, you can [extended the table extension](https://tiptap.dev/guide/custom-extensions)...

```js
export const CustomTable = Table.extend({

    renderHTML({ HTMLAttributes }) {
        return ['div', { class: 'table-responsive' }, ['table', HTMLAttributes, ['tbody', 0]]];
    },
});
```

Then when you add a table the normal way... `editor.commands.insertTable({ rows: 3, cols: 3, withHeaderRow: true })` you will always get that wrapper around your tables.

**Comment by rezaffm** [comment]
Indeed, that is what I came up first.

However, I have another extension that uses the "div" tag (to wrap paragraphs, ul, ols whatever in a  list), so what basically happened is that after reloading some content, it then got double-wrapped in a div.

If you have an idea how to handle that, please share :-)

**Comment by codemzy** [comment]
It sounds like your other extension is parsing all div tags, and now your table is wrapped in a div, it also gets included in your other extension and wrapped again? If I have that right, and you wanted to use this method, you could be more specific about what kind of divs your other extension parses.. either add an attribute to those other divs and then only parse those divs like...

```js
parseHTML() {
  return [
    {
      tag: 'div[data-type="wrapper"]',
    },
   ]
},
```

Or you could exclude the table div based on it's attributes ([see the docs here](https://tiptap.dev/guide/custom-extensions#using-get-attrs)) but I haven't tried this yet. If I run into this myself and go down this route, I'll update this issue. I was thinking something like this might work just based on the class?

```js
parseHTML() {
  return [
    {
      tag: 'div',
      getAttrs: element => {
        element.getAttribute('class') !== "table-responsive"
      },
    },
  ]
},
```

**Comment by rezaffm** [comment]
Yes, that could work, I think.

It is good to know for a coming similar issue, but will keep my current solution.

Here is why (I guess you might find it interesting, so just sharing it with you for your information):

I use the div component kind of as "box" to wrap certain elements in highlight boxes (success, danger, info, ... and so on). But I also wrap some iframes (like embedded videos and simple iframes) and tables in divs.

It was an easy task for the iframes, as I had to come up with custom extensions anyways, but then I got a bit stuck with the table element (which was fairly easy actually...).

What then give me a super hard time was to "force" some html correctness. E.g. I didn't want the divs to wrap other elements than the iframes and tables.

I basically solved it with an "onUpdate" function that makes sure, the specific divs will not wrap any other elements or actually will lift them if necessary.

Also, as sometimes I copy tables from Google docs, I wanted to make sure they are always wrapped in a div. It is also part of the code.

I copy it here for you, so maybe that is interesting for you (once you come across this issue) as well.

```javascript
import { Node, mergeAttributes } from '@tiptap/core';

const Div = Node.create({
    name: 'div',
    defaultOptions: {
        HTMLAttributes: {},
    },
    content: 'block*',
    group: 'block',
    defining: true,
    parseHTML() {
        return [
            { tag: 'div' },
        ];
    },
    renderHTML({ HTMLAttributes }) {
        return ['div', mergeAttributes(this.options.HTMLAttributes, HTMLAttributes), 0];
    },
    addCommands() {
        return {
            setDiv: (attributes) => ({ commands }) => {
                return commands.wrapIn('div', attributes);
            },
            toggleDiv: (attributes) => ({ commands }) => {
                return commands.toggleWrap('div', attributes);
            },
            unsetDiv: (attributes) => ({ commands }) => {
                return commands.lift('div');
            },
        };
    },
    onUpdate() {
      const classes = ['table-responsive', 'aspect-w-16 aspect-h-9', 'resp-container']
      const transaction = this.editor.state.tr
      let needsToWrapTables = false

      this.editor.state.doc.descendants((node, pos) => {
        if (node.type.name === 'div' && node.firstChild !== null) {
          if (node.firstChild.type.name !== 'table') return;
          if (node.attrs.class == null) {
            needsToWrapTables = true
            transaction.setNodeMarkup(pos, undefined, {
              ...node.attrs,
              class: 'table-responsive'
              })
            return true
          }
        }
        return false
      })

      if (needsToWrapTables) {
        transaction.setMeta('preventUpdate', true)
        this.editor.view.dispatch(transaction)
        transaction.setMeta('preventUpdate', false)
      }

      this.editor.state.doc.descendants((node, pos) => {
        if (node.type.name === 'div' && classes.includes(node.attrs.class)) {

          if (node.firstChild !== null && node.content.lastChild.type.name == 'paragraph') {
            transaction.replaceWith(pos, pos + node.nodeSize, node.content.lastChild)
            this.editor.view.dispatch(transaction)
            return true
          }

          if (node.firstChild !== null && node.firstChild.type.name == 'paragraph') {
            transaction.replaceWith(pos, pos + node.nodeSize, node.content)
            this.editor.view.dispatch(transaction)
            return true
          }

          if (node.childCount == 0) {
            transaction.deleteRange(pos, pos + node.nodeSize)
            this.editor.view.dispatch(transaction)
            return true
          }
          return false
        }
      })
    }
});

export default Div;
export { Div };
```

**Comment by hanspagel** [comment]
Thanks for sharing!

**Comment by codemzy** [comment]
> Another option if you want every table to have that div wrapper, you can [extended the table extension](https://tiptap.dev/guide/custom-extensions)...
> 
> ```js
> export const CustomTable = Table.extend({
>     renderHTML({ HTMLAttributes }) {
>         return ['div', { class: 'table-responsive' }, ['table', HTMLAttributes, ['tbody', 0]]];
>     },
> });
> ```
> 
> Then when you add a table the normal way... `editor.commands.insertTable({ rows: 3, cols: 3, withHeaderRow: true })` you will always get that wrapper around your tables.

A little update (with an alternative) - this added a `div` in the HTML output, but if all you want is to render the extra div around the table in tiptap (and not get the extra div in your HTML output) - I've switched to a custom node view:

```js
export const CustomTable = Table.extend({
    // REMOVE THIS
    // renderHTML({ HTMLAttributes }) {
    //     return ['div', { class: 'table-responsive' }, ['table', mergeAttributes(this.options.HTMLAttributes, HTMLAttributes), ['tbody', 0]]];
    // },

    // ADD THIS so that div output is not in html
    addNodeView() {
        return ({ editor, node, getPos, HTMLAttributes, decorations, extension }) => {
            // responsive div container
            const dom = document.createElement('div');
            dom.classList.add('table-responsive');
            // the table
            const table = document.createElement('table');
            dom.append(table);
            const tbody = table.appendChild(document.createElement('tbody'));
            return {
                dom,
                contentDOM: tbody,
            }
        }
    },
});
```
