### ISSUE TITLE
Trailing white space after mention on new line

### ISSUE THREAD

**Issue by josmfred** [ueberdosis/tiptap#2114]
### What’s the bug you are facing?

If you create a mention on an empty line by clicking instead of enter, the insertion point is placed after the mention but before a trailing space.

### How can we reproduce the bug on our side?

On chrome, on the [mention example page]https://tiptap.dev/examples/suggestions):
- Clear the content in the editor
- Type `@` into the editor
- Choose an option from the drop-down with the mouse instead of the keyboard

### What did you expect to happen?

Creating a mention with the mouse should match creating a mention with the keyboard, meaning the insertion point should be placed after the added white space.

### Anything to add? (optional)

https://user-images.githubusercontent.com/26757800/139719259-c23cc8f6-66ff-438e-9b18-17cf2e01f1a9.mp4

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by aliasliao** [comment]
Have the same problem. Is there any workaround solution?

**Comment by rfgamaral** [comment]
FYI, I wasn't able to reproduce this issue on Firefox, only Chromium based browsers.

**Comment by aliasliao** [comment]
https://github.com/ueberdosis/tiptap/blob/ab4a0e2507b4b92c46d293a0bb06bb00a04af6e0/packages/extension-mention/src/mention.ts#L39-L53

After calling the `insertContentAt` function, somehow EditorView's selection no longer synchronizes with the browser's selection.
My workaround solution is to call `window.getSelection().collapseToEnd()` after mention and space are inserted:

```diff
   editor 
     .chain() 
     .focus() 
     .insertContentAt(range, [ 
       { 
         type: this.name, 
         attrs: props, 
       }, 
       { 
         type: 'text', 
         text: ' ', 
       }, 
     ]) 
     .run()
+
+  window.getSelection().collapseToEnd()
 }, 
```

Hope this helps.

**Comment by sukechris** [comment]
Have the same problem in Chrome

**Comment by bdbch** [comment]
Nice one @aliasliao !

**Comment by bdbch** [comment]
@aliasliao I added your solution to the package to hopefully avoid this issue in the future. Nice work.
https://github.com/ueberdosis/tiptap/commit/163de4e1876000a88117da8a02b1f62cd4a2cfb0

**Comment by benkroeger** [comment]
the empty `window.getSelection()` seems to be caused by how the DOM looks like, but I couldn't get to the bottom of it. However, in general we're also using tippy to show the selections list and handle the click event. In general our implementation is very similar to the sample page in the tiptap docs.

I solved that by replacing 

```js
window.getSelection().collapseToEnd()
```

with 

```js
// this causes invalid state exception in Safari when selecting the item via mouse-click
// it appears as if the focus leaves the editor when clicking - and then window.getSelection
// a selection object with `rangeCount` = 0 - which then leads to an invalid state error
const selection = window.getSelection();
if (selection?.rangeCount) {
  selection.collapseToEnd();
}
```

**Comment by nickiepucel** [comment]
Saw the same issue as @benkroeger, the fix suggested worked for me
