### ISSUE TITLE
Error on Next.js installation doc

### ISSUE THREAD

**Issue by otaldonunes** [ueberdosis/tiptap#2115]
### What’s the URL to the page you’re sending feedback for?

https://tiptap.dev/installation/nextjs

### What part of the documentation needs improvement?

![2021-11-01-16-54-tiptap dev](https://user-images.githubusercontent.com/61764144/139733052-d01126b7-f9ef-40b6-9cc2-fb1675972007.png)

`...@tiptap/react and @**tipta**/starter-kit which includes all the extensions you need to get started quickly.`

### What is helpful about that part?

In Step 2 description:

change `@tipta/starter-kit`

to  `@tiptap/starter-kit`

### What is hard to understand, missing or misleading?

wrong package name.

**Comment by hanspagel** [comment]
Thanks! 🙌
