### ISSUE TITLE
Support lowlight v2 in code block extension

### ISSUE THREAD

**Issue by tn** [ueberdosis/tiptap#2116]
### What’s the bug you are facing?

Looks like lowlight changed module exports and extension-code-block-lowlight can't find listLanguages function

### How can we reproduce the bug on our side?

Just install lowlight at least v2.4.0
Use official example

### Can you provide a CodeSandbox?

https://codesandbox.io/s/elastic-goldwasser-7pkjp?file=/src/CodeBlockComponent.tsx

### What did you expect to happen?

It should work

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by cadars** [comment]
This is how you have to import lowlight:
```js
import { lowlight } from "lowlight";
```

And if only the “common” languages:
```js
import { lowlight } from 'lowlight/lib/common.js';
```

**Comment by aquibbaig** [comment]
@cadars Any thoughts on why does the sandbox show `Module '"lowlight"' has no exported member 'lowlight'.`

**Comment by cadars** [comment]
Not really, but it looks like the error disappears when importing this way instead:
```javascript
import { lowlight } from "lowlight/lib/all.js";
```
Personally I only import the most common languages:
```javascript
import { lowlight } from "lowlight/lib/common.js";
```

**Comment by aquibbaig** [comment]
I think the solution to this problem is to register languages by installing highlight.js first.

**Comment by aquibbaig** [comment]
@cadars I think that solves it, thanks!

**Comment by valueerrorx** [comment]
i just ran into a similar problem.
lowlight languages didn't show up in my "electron" build. (without any error messages and it did work in the test environment)

so i used @cadars way to import lowlight
`import { lowlight } from "lowlight/lib/common.js";`
and it worked.
thx!

**Comment by shellscape** [comment]
Looking into the usage, there doesn't seem to be any compelling reason not to upgrade. This is an inconvenience for users to be sure in both extra code to override the lowlight version and in bundling to assert that only one version is packaged. For a light lift like this, could the maintainers comment on what is holding this upgrade up?

**Comment by EvitanRelta** [comment]
> @cadars Any thoughts on why does the sandbox show `Module '"lowlight"' has no exported member 'lowlight'.`

It's because its using an outdated type-declaration from `@types/lowlight` instead of from `lowlight` itself _(lowlight declares its own types)_.

Currently `@types/lowlight` is required by `@tiptap/extension-code-block-lowlight` package, and definitely needs to be removed from the extension's dependency, else it can't be uninstalled.

**Comment by svenadlung** [comment]
This is a test. Please ignore me.

**Comment by Ako-Mawlood** [comment]
I am facing the same issue, there is no {lowlight}  from "lowlight" to import
