### ISSUE TITLE
text-align version 2.0.0-beta.25 not working

### ISSUE THREAD

**Issue by GonzaloHirschToptal** [ueberdosis/tiptap#2118]
### What’s the bug you are facing?

I just tried to implement text align exactly as shown in the [docs](https://tiptap.dev/api/extensions/text-align) but alignment didn't work when clicking the buttons. I tried changing the version to an older one, and it worked perfectly.

### How can we reproduce the bug on our side?

Versions `2.0.0-beta.25` through `2.0.0-beta.20` don't work, version `2.0.0-beta.19` does. Just take the sample from the docs and run it using any of those versions.

### What did you expect to happen?

Alignment should work.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Since this is working in the docs (which uses the latest version) I can’t do here anything. Please feel free to reopen if you can provide a reproducing demo.

**Comment by gwynncausing** [comment]
Same for me, I used Vue 2, copy pasted the code from here: https://tiptap.dev/examples/formatting, also used tiptap/vue-2

**Comment by GonzaloHirschToptal** [comment]
UPDATE: In my case `2.0.0-beta.19` suddenly stopped working and when I upgraded to `2.0.0-beta.25` it started working again, so it's quite inconsistent the behavior on my end.

**Comment by gwynncausing** [comment]
Currently Using `2.0.0-beta.25` but it is showing this error now

`[Vue warn]: Error in v-on handler: "TypeError: _vm.editor.chain(...).focus(...).setTextAlign is not a function"`

updated all of my tiptap dependencies to latest

**Comment by MrAlekhin** [comment]
Hello, I think I still experience the same issue for the `setTextAlign` function. Looks like that `this.options.alignments` is undefined 

<img width="210" alt="Screen Shot 2021-12-01 at 11 19 14 AM" src="https://user-images.githubusercontent.com/24749983/144271849-aec30c1a-b43f-4e50-9bf9-482022c45ca4.png">

**Comment by MrAlekhin** [comment]
Hmm interesting the way how i was able to fix it is by specifying alignments, however, in documentation, it says that it defaults. 

```
TextAlign.configure({
          types: ['heading', 'paragraph'],
          alignments: ['left', 'right', 'center', 'justify'],
        }),
```
