### ISSUE TITLE
Add one line of defensive CSS to prevent Firefox typing bugs

### ISSUE THREAD

**Issue by jcmorrow** [ueberdosis/tiptap#2120]
### What problem are you facing?

Hello! This is my first adventure in contributing to TipTap, and I first just want to say THANK YOU! 🙌 

I've been [working on adding](https://github.com/RecordReplay/devtools/pull/4088) TipTap to [Replay Devtools](https://replay.io), and my first thought after learning how to use it was "Oh right, of course this is how an editor should work"! I'm raising this issue because I recently spent an embarrassing amount of time tracking down [this bug](https://github.com/RecordReplay/devtools/issues/4053). The bug itself, as it turns out, has nothing to do with TipTap, or ProseMirror even. It's a Firefox bug which seems to bite [lots](https://github.com/telerik/kendo-angular/issues/2900) [of](https://stackoverflow.com/questions/69296163/contenteditable-removes-trailing-whitespaces-on-firefox-but-not-on-chrome) [text](https://bugzilla.mozilla.org/show_bug.cgi?id=681626) [editors](https://github.com/bmcmahen/react-wysiwyg/issues/34).

### What’s the solution you would like to see?

 In [this issue](https://github.com/bmcmahen/react-wysiwyg/issues/34) (and several other places) there seems to be a pretty good solution, which I have tested and works well for my case:

```
white-space: -moz-pre-wrap;
```

My proposition is that, even though this is not actually a TipTap issue, maybe TipTap can add some CSS to at least make it less likely that users with the default TipTap setup will hit this problem. Now, I am no text editor guru, so maybe there are drawbacks here that this introduces. I leave that to y'all's seasoned instincts, but if there's anything I can do to help out, please let me know!

### What alternatives did you consider?

I don't know of any other easy fixes here. Certainly the best thing would be for all browsers to "just work", or at least, all work basically the same, but that is definitely out of scope, while adding a single line of CSS feels manageable 😄 

### Anything to add? (optional)

P.S. If you want to see my tracking down where this happens, check out the [Replay](https://app.replay.io/recording/1ff86cd1-38bb-43df-99b3-cbf9e2696852) ⏯️ 

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
This is already part of the default styles: https://github.com/ueberdosis/tiptap/blob/main/packages/core/src/style.ts#L7

Unless you’ve set `injectCSS` to `false`.

**Comment by jcmorrow** [comment]
Ah, sorry @philippkuehn, I realized that I typed the wrong value. I meant `-moz-pre-space`, you are totally correct that `pre-wrap` is already in! I can edit the original post to clarify or leave it there, whichever is less confusing.

**Comment by philippkuehn** [comment]
Hmm, I can’t reproduce this. The issue you describe is getting fixed by setting `white-space` to `pre-wrap` or `break-spaces` (what tiptap does) in firefox for me. 

Can you provide a reproducable codesandbox for me?

**Comment by jcmorrow** [comment]
Yeah, I didn't realize that `pre-wrap` would also fix it for that code sandbox. I am 99% sure that there is a scenario where `-moz-pre-space` is required, and I will ping you when I get that nailed down. Thanks for your patience 🙏

**Comment by philippkuehn** [comment]
Yes I’m very curious about it!

**Comment by jcmorrow** [comment]
Alright! I have *more* of a root cause than I had earlier, though it was not as satisfying as I hoped it would be! It is *not* a matter of which CSS property we use, but actually a matter of the CSS disappearing altogether in certain states when removing editors from the page! It seems like the first editor to get added injects CSS, and then all other editors *don't*, and if that first editor gets removed for some reason, the others lose all tiptap injected CSS. [Here's a loom of me walking through the above Replay to explain in detail!](https://www.loom.com/share/756946d15f684e419056b1a7caf5211d)
