### ISSUE TITLE
Placeholder extension adds empty class to all nodes

### ISSUE THREAD

**Issue by cadars** [ueberdosis/tiptap#2126]
### What’s the bug you are facing?

When using the Placeholder extension, all nodes get an empty `class` attribute.
(It's nothing major but thought you’d like to know)

### How can we reproduce the bug on our side?

1. Go to the Placeholder demo: https://embed.tiptap.dev/preview/Extensions/Placeholder
2. Type some content and inspect it, all nodes get an empty `class`:
```html
<div contenteditable="true" translate="no" class="ProseMirror" tabindex="0">
  <h1 class>some words</h1>
  <p class>more words</p>
</div>
```

### What did you expect to happen?

No class attribute should be added.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Strange. This seems to be an issue with ProseMirror itself because the decorations are definitely destroyed.

**Comment by philippkuehn** [comment]
Fixed with the latest version of prosemirror-view.
