### ISSUE TITLE
There is a regular expression compatibility problem in Google browser version 60

### ISSUE THREAD

**Issue by ferqx** [ueberdosis/tiptap#2128]
### What’s the bug you are facing?

Browser version：Chrome 60
Dependent version：
```
"@tiptap/extension-highlight": "^2.0.0-beta.25",
"@tiptap/extension-image": "^2.0.0-beta.19",
"@tiptap/extension-task-item": "^2.0.0-beta.22",
"@tiptap/extension-task-list": "^2.0.0-beta.18",
"@tiptap/vue-2": "^2.0.0-beta.60",
```

`@tiptap/extension-code-block/src/code-block.ts`
```
export const backtickInputRegex = /^```(?<language>[a-z]*)?[\s\n]$/
export const tildeInputRegex = /^~~~(?<language>[a-z]*)?[\s\n]$/
```
The two regular expressions have compatibility problems
Our project runs in Google browser version 60 after packaging. There is an error
![image](https://user-images.githubusercontent.com/23183225/140278506-99e0c039-8d79-4e57-adc4-d4768931e5b5.png)

At the same time, we also found some problems by checking the regular syntax of [regulex](https://github.com/CJex/regulex)
![image](https://user-images.githubusercontent.com/23183225/140278940-6dee2381-91e5-41ec-8f84-949e04cc85d6.png)

### How can we reproduce the bug on our side?

https://jex.im/regulex/#!flags=&re=%5E%60%60%60(%3F%3Clanguage%3E%5Ba-z%5D*)%3F%20%24

### What did you expect to happen?

I hope we can handle the project as soon as possible to help us run normally. Thank you

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Chrome V60 is over 4 years old. Please do yourself a favor and update Chrome.
This is our [list of supported browsers](https://browserslist.dev/?q=ZGVmYXVsdHMsIG5vdCBJRSAxMQ%3D%3D).

**Comment by ferqx** [comment]
Please help me, because we have been used in production projects, the number of users is relatively large, and it is unlikely to accept the upgrade

**Comment by ferqx** [comment]
Or can you tell me the meaning of that regular expression? We can handle it ourselves, mainly because we don't understand the meaning of this regular expression

**Comment by rfgamaral** [comment]
@philippkuehn We are getting hit by this issue, as one of our users has an enterprise policy to use Firefox v77 (which breaks with those RegExp).

If this is not something you are interested in supporting (given your supported browsers list), can you please clarify for me what's the purpose of `<language>` in the RegExps? Why something simple like `/^```([a-z]+)?[\s\n]$/` isn't sufficient?

**Comment by rfgamaral** [comment]
@philippkuehn After further research and testing, I realized that `(?<language>)` refers to named capturing groups.

Although the original issue mentioned Chrome 60 (a 4-year-old browser), Firefox 77, on the other hand, is only 1.5 years old. I understand you have your list of supported browsers, but it looks to me that the official extension could easily use standard capturing groups instead without breaking anything or introducing any major hindrance to code maintenance.

In the meantime, we've stopped using the official `CodeBlock` extension, and instead copy/paste the original source code and made the following changes:

```diff
- export const backtickInputRegex = /^```(?<language>[a-z]*)?[\s\n]$/
+ export const backtickInputRegex = /^```([a-z]+)?[\s\n]$/
- export const tildeInputRegex = /^~~~(?<language>[a-z]*)?[\s\n]$/
+ export const tildeInputRegex = /^~~~([a-z]+)?[\s\n]$/
```

```diff
 addInputRules() {
   return [
     textblockTypeInputRule({
       find: backtickInputRegex,
       type: this.type,
-      getAttributes: ({ groups }) => groups,
+      getAttributes: (match) => ({ language: match[1] }),
     }),
     textblockTypeInputRule({
       find: tildeInputRegex,
       type: this.type,
-      getAttributes: ({ groups }) => groups,
+      getAttributes: (match) => ({ language: match[1] }),
     }),
   ]
 },
```

Could you consider making this change to the official extension? 🙏 It would be better if we could just keep using the official extension (and get updates on that), than having to maintain our own fork of this, just for a simple RegExp tweak.

Happy new year 🥳

**Comment by ferqx** [comment]
So far, we have solved this problem. The solution is to compile the module again when the project is packaged. After compilation, the regular expression will change and it will run normally in Chrome 60.

**Comment by philippkuehn** [comment]
I removed these named capturing groups in the latest version.

**Comment by rfgamaral** [comment]
Awesome, @philippkuehn, thanks for that, really appreciated 🤗
