### ISSUE TITLE
hosticDom.createHTMLDocument is not a function when using NUXT + tiptap-html

### ISSUE THREAD

**Issue by BobTheShoplifter** [ueberdosis/tiptap#2131]
### What’s the bug you are facing?

Hello! I've recently upgraded from v1 --> v2 and also started to use the SSR features, using [https://tiptap.dev/api/utilities/html](https://tiptap.dev/api/utilities/html.) Following the example on the page I got it to work, however, a hard reload of the page makes my server log the following error:
```js
 ERROR  hosticDom.createHTMLDocument is not a function

  at getHTMLFromFragment (node_modules/@tiptap/html/dist/tiptap-html.cjs.js:13:0)
  at generateHTML (node_modules/@tiptap/html/dist/tiptap-html.cjs.js:22:0)
  at a.output (pages/blog/_postId/_slug.vue:86:0)
  at a.output (node_modules/vue/dist/vue.runtime.common.prod.js:6:0)
  at a.render (pages/blog/_postId/_slug.vue)
  at a.module.exports.t._render (node_modules/vue/dist/vue.runtime.common.prod.js:6:0)
  at node_modules/vue-server-renderer/build.prod.js:1:70854
  at eo (node_modules/vue-server-renderer/build.prod.js:1:67418)
  at oo (node_modules/vue-server-renderer/build.prod.js:1:70830)
  at no (node_modules/vue-server-renderer/build.prod.js:1:70461)
```

The page in question is [https://websecured.io/blog/607dd4f3e9d9280014063f77/lets-not-trust-the-frontend](https://websecured.io/blog/607dd4f3e9d9280014063f77/lets-not-trust-the-frontend), you can see it will error out on a direct load but if you load it via [https://websecured.io/blog](https://websecured.io/blog) it will load just fine.

I've tried different stuff with no luck, the error seems to be in generateHTML, just not sure where.

### How can we reproduce the bug on our side?

Here is my nuxt/vue page

```vue
<template>
  <div class="fill-height">
    <div>
      <v-img :src="post.banner" height="350px" cover>
        <v-container class="fill-height">
          <v-row class="fill-height mx-2" align="center" justify="center">
            <v-sheet
              class="rounded-bl-xl rounded-tr-xl text-subtitle-1 text-sm-h5 text-md-h4 font-weight-medium text-center px-4 px-md-12 py-2 py-sm-5"
            >
              {{ post.title }}
            </v-sheet>
          </v-row>
        </v-container>
      </v-img>
      <v-container>
        <v-row align="center">
          <v-col
            class="d-flex align-center justify-center justify-sm-start"
            cols="12"
            sm="6"
          >
            <v-avatar class="rounded-bl-lg rounded-tr-lg" size="60px" tile>
              <v-img :src="post._author.avatar" />
            </v-avatar>
            <div class="blog--text text--lighten-2 ml-5">
              <div
                class="text-subtitle-2 text-sm-subtitle-1 font-weight-medium"
              >
                {{ $t("blog.articleBy") }}
                <span class="blog--text">{{ post._author.username }}</span>
              </div>
              <div
                class="text-subtitle-2 font-weight-medium"
                v-if="post._editor && post._author._id !== post._editor._id"
              >
                {{ $t("blog.editedBy") }}
                <span class="blog--text">{{ post._editor.username }}</span>
              </div>
            </div>
          </v-col>
          <v-col
            class="blog--text text--lighten-2 text-subtitle-2 text-sm-subtitle-1 text-center text-sm-right"
            cols="12"
            sm="6"
          >
            {{ formatDate(post.created) }}
            -
            {{ $t("blog.estimatedRead", { time: post.estimatedTime }) }}
          </v-col>
          <v-card
            class="v-card v-card--flat v-sheet transparent blog-content"
            v-html="output"
          ></v-card>
          <v-btn
            :aria-label="$t('blog.backToBlog')"
            class="rounded-bl-xl rounded-tr-xl px-10 mx-auto"
            color="#c7c5d0"
            to="/blog"
            x-large
            depressed
            dark
            nuxt
          >
            {{ $t("blog.backToBlog") }}
          </v-btn>
        </v-row>
      </v-container>
    </div>
  </div>
</template>

<script>
import StarterKit from "@tiptap/starter-kit";
import Link from "@tiptap/extension-link";

import { format } from "date-fns";
import { generateHTML } from "@tiptap/html";

export default {
  name: "BlogPost",

  data: () => ({}),

  computed: {
    output() {
      return generateHTML(this.post.blogcontent, [StarterKit, Link]);
    }
  },

  methods: {
    formatDate(value, short) {
      if (!value) return "Invalid date";
      if (short) return format(new Date(value), "MMM, yyyy");
      else return format(new Date(value), "MMMM do, yyyy");
    }
  },

  async asyncData({ params, $axios }) {
    const post = await $axios.$get(`/blog/post/${params.postId}`);
    return { post };
  }
};
</script>

<style lang="scss" scoped>
Removed
</style>
```

### What did you expect to happen?

I expected the rendered HTML to Server-side render, but it resulted in an error.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by BobTheShoplifter** [comment]
Might it be the install instructions are wrong? I only need it for HTML rendering as my tiptap editor itself is on a diffrent site.

**Comment by philippkuehn** [comment]
we moved from [hostic-dom to zeed-dom](https://github.com/ueberdosis/tiptap/pull/2151) in the latest version. it's pretty much the same API but can you check if the issue still exists please?

**Comment by BobTheShoplifter** [comment]
Well i can verify its been updated to zeed-dom but the same issue happens with a new name
![image](https://user-images.githubusercontent.com/22559547/141005635-8eb0179b-4e95-4ceb-a390-06eef19e9247.png)

` at getHTMLFromFragment (node_modules/@tiptap/html/dist/tiptap-html.cjs.js:13:0)
  at generateHTML (node_modules/@tiptap/html/dist/tiptap-html.cjs.js:21:0)
  at a.output (pages/blog/_postId/_slug.vue:86:0)
  at a.output (node_modules/vue/dist/vue.runtime.common.prod.js:6:0)
  at a.render (pages/blog/_postId/_slug.vue)
  at a.module.exports.t._render (node_modules/vue/dist/vue.runtime.common.prod.js:6:0)
  at node_modules/vue-server-renderer/build.prod.js:1:70854
  at eo (node_modules/vue-server-renderer/build.prod.js:1:67418)
  at oo (node_modules/vue-server-renderer/build.prod.js:1:70830)
  at no (node_modules/vue-server-renderer/build.prod.js:1:70461)`

**Comment by BobTheShoplifter** [comment]
Soo, i used to build with `yarn build --standalone` this resulted in this issue happening, after removing it loading via SSR seems to work just fine! https://websecured.io/blog/607dd4f3e9d9280014063f77/lets-not-trust-the-frontend
