### ISSUE TITLE
FloatingMenu in v2 & vue-3 does not emit v-slots like { menu }

### ISSUE THREAD

**Issue by madebyfabian** [ueberdosis/tiptap#2135]
### What’s the bug you are facing?

Hey there, first of all, thank you so much for your work on tiptap. It's amazing! One thing though I am courius:

In v1, I was able to do the following:

```vue
<editor-floating-menu :editor="editor" v-slot="{ menu }">
  <div :class="{ 'is-active': menu.isActive }">
    <button>
       ...
    </button>
  </div>
</editor-floating-menu>
```

which enabled me to use custom classes & therefore animations for the floating menu.

In V2, when I want to write 
```vue
<FloatingMenu 
  v-if="editor"
  :editor="editor"
  v-slot="{ menu }">
  <div :class="{ 'is-active': menu.isActive }">
    <button>
       ...
    </button>
  </div>
</FloatingMenu>
```

I get an error saying that v-slot values I try to access are undefined. So nothing is being emitted. How am I able to get the menu object out of the floating menu?

### How can we reproduce the bug on our side?

Import the FloatingMenu and use it on any v2 tiptap vue enviroinment, trying to use `v-slot="{ menu }"` on the `<FloatingMenu>` component.

### Can you provide a CodeSandbox?

Not needed for this case.

### What did you expect to happen?

I expect `v-slot...` to emit the `menu` object like it was in v1, or that it provides an alternative in the docs on using the menu object.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Syntax for menus has changed in v2. Look at the [docs](https://tiptap.dev/api/extensions/floating-menu).

**Comment by madebyfabian** [comment]
@philippkuehn thanks for your answer, I know it changed and I looked at the docs before creating this ticket. Although I haven’t found a way to implement the v1 behavior in the v2 docs, I just wanted to know if that’s intentionally not possible or if it’s just not documented/a bug.

**Comment by philippkuehn** [comment]
The API has changed. So of course you have to update your code.
