### ISSUE TITLE
Configure on extended extension does not work

### ISSUE THREAD

**Issue by jbmolle** [ueberdosis/tiptap#2136]
### What’s the bug you are facing?

Hi,
When I use .configure({}) on an extension extended from another extension, it doesn't work.

### How can we reproduce the bug on our side?

I create a TextAlign extension:
```
const myTextAlign = TextAlign.extend({
  newElement: 'new element in TextAlign config'
})
```
Then if I add it to my editor extensions like this: myTextAlign, it works.
But if I do
```
myTextAlign.configure({ types: ['paragraph'] })
```
it doesn't work, I have a TextAlign without newElement.
I think the problem comes from the configure function. We currently have:
```
const extension = this.extend()
```
And we should probably have something like
```
const extension = this.extend(this.config)
```
Best,
JB

### What did you expect to happen?

I expect the configure to keep the extended extension config

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Adding custom values like `newElement` to the extension config is not supported.
What do you want to do with that?

**Comment by jbmolle** [comment]
Ok, thanks for the quick answer!
Actually newElement was just an example.
What I'm currently doing is adding
```
menuBtnView (editor: Editor) {
  return {
    component: MyComponent,
    componentProps: {}
  }
}
```
Like this I can customize the component in the menu bar that will enable this extension.
So I can have a generic menu bar in my application and everytime I create a Tiptap editor, the bar will show only the buttons of the needed extensions.
JB

**Comment by jbmolle** [comment]
But you're right, there is no need to mix UI with extension logic. I can simply create a Map of Components to Extension and it's working fine.
Thanks!
