### ISSUE TITLE
menu bubble show not correctly 

### ISSUE THREAD

**Issue by FA-NhaLCT** [ueberdosis/tiptap#2139]
### What’s the bug you are facing?

The menu bubble not showing at the "link" but at previous state.
I think the issue is related with [https://github.com/ueberdosis/tiptap/issues/1986](url)
But the point I facing here is the position of menu bubble not the "isActive" function.

### How can we reproduce the bug on our side?

1. Click on a link text: the bubble menu showing at position of last state
![image](https://user-images.githubusercontent.com/63585235/140601921-8e219af8-bde5-46a4-aab5-ca01b500b24b.png)

2. Click on a link text again: the bubble menu showing at position of a link
![image](https://user-images.githubusercontent.com/63585235/140601900-4d51fd58-7f42-4fc3-a592-8654ba5d0f17.png)

Same behavior when i move by button 

### What did you expect to happen?

The bubble showing correctly at middle of the link node

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Please provide a reproducable codesandbox or some code you are using and feel free to reopen then.
