### ISSUE TITLE
Extension Link: open link on click 

### ISSUE THREAD

**Issue by StuartMorris0** [ueberdosis/tiptap#2140]
### What’s the bug you are facing?

Using the tiptap/extension-link.

``` Link.configure({ openOnClick: false })```

### How can we reproduce the bug on our side?

Using the Link with openOnClick set to false. Click on a link and it will still open from the editor.

### What did you expect to happen?

Links not to open when this flag is set to false.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Can’t reproduce this. Feel free to re-open with a reproducable demo.

**Comment by StuartMorris0** [comment]
That was quick @philippkuehn. Unfortunately I cannot reproduce on a sandbox, it all seems to work.

I have a project with the same package versions for tiptap/extensions, but one works differently to the other. The links in our main application all load when clicked regardless of the setting

**Comment by StuartMorris0** [comment]
It was a config issue, we were adding the extension twice and the second time without the configure flag 😖

**Comment by ahbk** [comment]
svelte will trigger this issue unless link reload is disabled for the editor element, it's not obvious for beginners and I couldn't find any information so I'll post it here for fellow passers by:

`<div data-sveltekit-preload-data="off" data-sveltekit-reload="" class="editor" bind:this={element} />`

**Comment by MarcJose** [comment]
We are just having the same issue on NextJs 15 where links open inside the editor despite having this config:

```shell
Link.configure({
  protocols: [
    'file', // File URI scheme
    'ftp', // File URI scheme
    'http', // Hypertext Transfer Protocol
    'https', // Hypertext Transfer Protocol Secure
    'mailto', // Email addresses
    'tel', // Telephone numbers
    'imap', // Internet Message Access Protocol
    'irc', // Internet Relay Chat
    'nntp', // Network News Transfer Protocol
    'jdbc', // Java Database Connectivity
    'msteams', // Microsoft Teams
    'ms-access', // Microsoft Office applications
    'ms-excel',
    'ms-infopath',
    'ms-powerpoint',
    'ms-project',
    'ms-publisher',
    'ms-spd',
    'ms-visio',
    'ms-word',
    'odbc', // Open Database Connectivity
    's3', // Amazon S3 bucket
    'zoommtg', // Zoom conferencing software
    'zoomus',
  ],
  autolink: true,
  openOnClick: false,
  linkOnPaste: true,
  defaultProtocol: 'https',
  enableClickSelection: true,
  HTMLAttributes: {
    rel: null,
    target: null,
  },
})
```

We double checked to see if we do import the extension twice but that does not seem to be the case.
This is particulary annoying as we have a check for external links and warn users when clicking on them and the editor seems to circumvent it and open it in a new tab anyways while also showing the warning..

**Comment by IsaacAbrahamson** [comment]
The docs didn't make this clear, so in case it helps someone else in the future, `StarterKit` has the link extension already configured, so if you do something like this it will not work.

```ts
const editor = useEditor({
  extensions: [
    StarterKit,
    Link.configure({ openOnClick: false })
  ],
});
```

You have to configure link inside the starter kit and it will work as expected.

```ts
const editor = useEditor({
  extensions: [
    StarterKit.configure({
      link: { openOnClick:  false },
    }),
  ],
});
```
