### ISSUE TITLE
Global styles get removed when destroying editor even if there are other editors alive

### ISSUE THREAD

**Issue by pie6k** [ueberdosis/tiptap#2143]
### What’s the bug you are facing?

Global styles (https://github.com/ueberdosis/tiptap/blob/main/packages/core/src/style.ts) are added to `<head>` when editor is created and removed when editor is destroyed.

This works fine if using only one editor on the page. 

However, if using multiple editors, if one of them is removed, but others are still alive - those styles are still removed causing slight layout changes.

Thus I think there should be some sort of global counter that counts remaining alive instances and removes the styles only if there are no alive editors left.

### How can we reproduce the bug on our side?

Create 2 react editors.

Perform react update that removes one of them.

Expected result: global styles are still present
Actual result `<style data-tiptap-style>` tag is removed from head.

### What did you expect to happen?

Have global styles alive as long as any editor instance is running

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Ah yes, I think this issue is related to #2120

**Comment by dominik-stagtech** [comment]
What is the solution for this? I have a very similar issue where the `data-tiptap-style` style tag is disappearing when I change input variables/rerender my editor.
