### ISSUE TITLE
Code format cannot work with link

### ISSUE THREAD

**Issue by FA-NhaLCT** [ueberdosis/tiptap#2149]
### What’s the bug you are facing?

When I use toggle code it clear my link, and if i have existing code format it cannot be apply the link.

### How can we reproduce the bug on our side?

I use 2 method:
- editor.chain().focus().toggleCode().run() for code.
- editor.commands.setLink for link.

Also i have set the priority of the link bigger but it not work.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/rough-worker-lmyfy?file=/src/App.vue

### What did you expect to happen?

the link tag can be wrap outside the code tag

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
This is a feature of the code mark. But you can disable by extending the Code extension:

```js
Code.extend({
  excludes: null,
})
```
