### ISSUE TITLE
Task list items rendered HTML doesn't look right

### ISSUE THREAD

**Issue by rfgamaral** [ueberdosis/tiptap#2157]
### What’s the bug you are facing?

The current `renderHTML` for the `@tiptap/extension-task-item` produces the following HTML:

```html
<ul data-type="taskList">
    <li data-checked="false" data-type="taskItem">
        <label>
            <input type="checkbox" />
            <span></span>
        </label>
        <div><p>Item</p></div>
    </li>
</ul>
```

This doesn't look right to me... A few observations:

* The `<label>` and the empty `<span>` are not really doing anything
  * If this is for accessibility purposes, it's missing some attributes/data
* The `<div>` surrounding `<p>Item</p>` doesn't seem to be necessary

This changed was introduced with https://github.com/ueberdosis/tiptap/commit/c94d2b0517e62afea84cb9dd6999874abf0bf3cd.

### How can we reproduce the bug on our side?

N/A

### What did you expect to happen?

A more simplified HTML output:

```html
<ul data-type="taskList">
    <li data-checked="false" data-type="taskItem">
        <input type="checkbox" />
        <p>Item</p>
    </li>
</ul>
```

I'm starting with the basics first, and skipping accessibility for now.

### Anything to add? (optional)

I tried to extend `TaskItem` and write my own `renderHTML`, but the best I could do was this:

```js
renderHTML({ node, HTMLAttributes }) {
    return [
        'li',
        mergeAttributes(this.options.HTMLAttributes, HTMLAttributes, {
            'data-type': 'taskItem',
        }),
        [
            'input',
            {
                type: 'checkbox',
                checked: node.attrs.checked ? 'checked' : null,
            },
        ],
        ['span', 0],
    ]
},
```

Which results in the following HTML:

```html
<ul data-type="taskList">
    <li data-checked="false" data-type="taskItem">
        <input type="checkbox">
        <span>
            <p>Item</p>
        </span>
    </li>
</ul>
```

Ideally there would be no `<span>` surrounding the `<p>`, but I don't think the `renderHTML` function allows for this.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Hey, this is intended.

We provide markup that can be used to easily style a custom checkbox. This markup is a common way for doing this:

```html
<label>
  <input type="checkbox" />
  <span></span>
</label>
```

With that we can use the `span` to render a custom checkbox:

```css
input + span {
 /* some styles for a unchecked checkbox */
}

input:checked + span {
 /* some styles for a checked checkbox */
}
```

The wrapping `label` makes the `span` act like a click on the input itself.

The wrapping `div` around the ProseMirror hole (0) is needed because a hole must the only child within an element.

If you want to use a more simple markup you can overwrite the `renderHTML` method but I don’t want to change this at the moment ✌️
