### ISSUE TITLE
Problem combining CodeBlock with addNodeView configuration.

### ISSUE THREAD

**Issue by Toubat** [ueberdosis/tiptap#2163]
### What’s the bug you are facing?

I want to create a customized CodeBlock that utilizes the default one, but the style does not apply.

### How can we reproduce the bug on our side?

I've set up the code sandbox, and all the necessary files. The complete code can be found here: [https://codesandbox.io/s/sad-matsumoto-x2603?file=/src/App.vue](https://codesandbox.io/s/sad-matsumoto-x2603?file=/src/components/HelloWorld.vue)

### Can you provide a CodeSandbox?

[https://codesandbox.io/s/sad-matsumoto-x2603?file=/src/App.vue](https://codesandbox.io/s/sad-matsumoto-x2603?file=/src/components/HelloWorld.vue)

### What did you expect to happen?

The customized CodeBlock is wrapped in a Draggable Block through a Vue component. Here's what I tried:
(all customized file can be found in code sandbox)
1. I try to add a new node view directly in CodeBlock like this:
```javascript
const NotexCodeBlock = CodeBlockLowlight.extend({
  name: "notexCodeBlock",
  addNodeView() {
    return VueNodeViewRenderer(DraggableBlock);
  },
  addCommands() {
    return {
      setNotexCodeBlock: (attributes) => ({ commands }) => {
        return commands.setNode("notexCodeBlock", attributes);
      },
      toggleNotexCodeBlock: (attributes) => ({ commands }) => {
        return commands.toggleNode("notexCodeBlock", "paragraph", attributes);
      },
    };
  },
});
```
which does not work, because the entire block disappears after I click on it.

2. I create a button, and clicking it will create a wrapped structure of draggableBlock with codeBlock:
```javascript
setNotexCodeBlock() {
      this.editor
        .chain()
        .focus()
        .insertContent({
          type: "draggableBlock",
          content: [
            {
              type: "codeBlock",
              attrs: {
                language: null,
              },
              content: [],
            },
          ],
        })
        .run();
    },
```
This method would work in a very elegant way. But one problem is that when I want to delete the whole nested structure. (say code block is empty and I press backspace), it only deletes the outer draggableBlock. But I want it to delete both.

### Anything to add? (optional)

I appreciate it if anyone knows how I can solve this issue properly. I know I must miss some parts regarding Node configuration, but since I'm relatively new, I had no way to solve this on my own.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by Toubat** [comment]
I figured it out, so basically I forgot to add as="pre" in <node-view-content />. After adding that attribute with some customed styles, it would work as expected.
```Vue
<node-view-content
  class="notex-code-block__content"
  :class="`${textAlign} my-2 mr-2`"
  as="pre"
/>
```
```css
.notex-code-block__content {
  padding: 0.5rem;
  width: calc(100% - 25px);
  display: inline;
  color: #fff;
  background: #1e1e1e;
  border-radius: 0.3rem;
  font-size: 0.8rem;
  font-family: "JetBrains Mono", monospace;
}
```

**Comment by hanspagel** [comment]
Thanks for sharing!
