### ISSUE TITLE
Cannot overwrite predefined keyboard shortcuts

### ISSUE THREAD

**Issue by mjabl** [ueberdosis/tiptap#2165]
### What’s the bug you are facing?

I'd like to overwrite the Mod-Shift-V keyboard shortcut by creating a custom extension. However, this does not have any effect.

### How can we reproduce the bug on our side?

Create a minimum editor and add an extension like this:

```
const CustomPaste = Extension.create({
  name: "customPaste",

  addKeyboardShortcuts() {
    return {
      "Mod-Shift-V": () => console.log("hello"),
    };
  },
});
```

Then test by hitting Mod-Shift-V. The default action (paste as plain text) is performed and nothing gets logged to the console.

### What did you expect to happen?

The default action (paste as plain text) should be overwritten with the action specified in the extension.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by cadars** [comment]
I think `Mod-Shift-v` (lowercase) should work, but I'm not sure it’s possible to override copy/paste commands?

**Comment by hanspagel** [comment]
If `Mod-Shift-v` doesn’t work, it’s not allowed by the browser. But you probably want to hook into the events to do whatever you’d like to achieve.

https://tiptap.dev/guide/custom-extensions/#access-the-prosemirror-api

**Comment by mjabl** [comment]
Mod-Shift-v (lowercase) allows the overwrite. thanks @cadars .
 @hanspagel  yeah, I'm already using the Prosemirror API to build majority of my CustomPaste functionality.
