### ISSUE TITLE
[React][TS] Node conditional creation from FloatingMenu not working.

### ISSUE THREAD

**Issue by Iipal** [ueberdosis/tiptap#2167]
### What’s the bug you are facing?

Can't create a CustomNode from FloatingMenu
![image](https://user-images.githubusercontent.com/31858171/141791396-91238754-2736-4981-a2c4-23cf7c454581.png)

### How can we reproduce the bug on our side?

call `editor.commands.setNode("CustomNodeName")` from FloatingMenu component with `CustomNodeExtenstion` created with `useEditor`

### Can you provide a CodeSandbox?

https://codesandbox.io/s/thirsty-stonebraker-jmhoi?file=/src/App.tsx

### What did you expect to happen?

Expect to see the custom component in Editor just as shown in documentation: https://tiptap.dev/guide/node-views/react

### Anything to add? (optional)

Or any other solution for my problem ? To being abble create custom component even between text and draggable as well.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by hanspagel** [comment]
Your extension is an atom node (without text content) and it’s not clear how a paragraph (potentially with text) should be transformed to an atom node. Try `insertContent` instead!

https://tiptap.dev/api/commands/insert-content

**Comment by Iipal** [comment]
@hanspagel Thanks, removing `atom: true` and using `insertContent` like this:
```js
editor.commands.insertContent(`<${AttachmentComponentExtensionName} />`);
```
fixes my issue.
