### ISSUE TITLE
BubbleMenu opening on click

### ISSUE THREAD

**Issue by IgorZanellaDev** [ueberdosis/tiptap#2171]
### What problem are you facing?

I would like to show the bubble menu on click when the editor is already focused. But I can't, I also tried with ProseMirror editorProps handleClick, but BubbleMenu shouldShow is not recalled on onclick if you don't change cursor position.

### What’s the solution you would like to see?

I would like that shouldShow would be recalled on click of the view, and I would like something on history or state (oldState), to understand if editor was already focused. So I can use the state to understand if user clicks on editor already focused.

### What alternatives did you consider?

No alternatives.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Closing in favor of #2305
