### ISSUE TITLE
Multiple Instances...

### ISSUE THREAD

**Issue by ashfaq-shamsudeen** [ueberdosis/tiptap#2173]
### What’s the bug you are facing?

Thanks for the wonderful TipTap v2 and very interested in the new TipTap v2.

I'm developing a TipTap (v2 beta) extension to handle the toolbar, set priority to 99 one less than the default, and added as the last element to the extensions array. The idea is that this extension shall be responsible for all toolbar rendering together and other extensions supply menu items details (dom & commands - inspired by https://prosemirror.net/examples/menu/) which are related to specific extensions. The toolbar extension shall also render all the basic menu items like Bold, Italic, etc.

One of my extensions looks like this:
```
onUpdate() {
    if(this.options.mItems) {
      this.options.mItems[1].dom.textContent = '?#';
      // Can make any change to dom here
    }
  },

  defaultOptions: {
      mItems: [],
  },

  getMenuItems(schema) {
      // This shall be invoked by Toolbar extension from it's addProseMirrorPlugins method
      // Here each menu item's dom shall be created...      
      return this.defaultOptions.mItems;
  },
```

 _addProseMirrorPlugins_ of Toolbar extension has:
```
    this.editor.extensionManager.extensions.forEach((extension) => {
      if (extension.config.getMenuItems) {
        items = items.concat(extension.config.getMenuItems(schema));
      }
    });
```

In my test app, I am using the Vue component where the TipTap editor is instantiated. So far good and was able to achieve the desired result. When I included the second instance of this Vue component in the same page, it rendered fine there too, but the dynamic modification of the toolbar didn't happen as it is holding the toolbar of the first instance. I realize that Extensions are not classes and thus behave like a single instance and perhaps can't behave like a component. Is that designed so? How can I achieve my desired result? I have played around the _tiptap-standalone-collab-vue2_ source code. We have several prosemirror plugins to integrate. Please guide me through the right path. Thanks for considering!

### How can we reproduce the bug on our side?

[src-relevant-files.zip](https://github.com/ueberdosis/tiptap/files/7562737/src-relevant-files.zip)

### What did you expect to happen?

- If extension can't be used in a multiple instance scenario, please fix that.
- If my investigation is wrong, please guide me to the right path to achieve my desired result. 
Thanks!

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by hanspagel** [comment]
You can read the guide on menus and use one of our provided menus. 

https://tiptap.dev/guide/menus

To add multiple instances add different plugin keys.

https://tiptap.dev/api/extensions/bubble-menu#plugin-key

Using different plugin keys should help you when adding multiple instances of other ProseMirror plugins, too.

Hope that helps!

**Comment by ashfaq-shamsudeen** [comment]
@hanspagel Thanks for your reply! But that doesn't meet my requirements, maybe I didn't express all those correctly.

I am trying to create an extension to set up the toolbar like shown in the example https://tiptap.dev/examples/collaborative-editing/. There are several prosemirror plugins developed by us and some of them are creating dom to display dropdown (with 100+ entries and each entry having edit, delete option). Those shall be wrapped with TipTap extension and the only thing we want to do is to register those extensions with the editor and in the toolbar, those menus should auto appear, that is something outside of the prosemirror editor. Hope this clarifies. Thanks!

Should I reopen this?

**Comment by ashfaq-shamsudeen** [comment]
Further I have created the sandbox for this:
https://codesandbox.io/s/vue2-tiptap-multiple-instances-uli2j

If you click on the "H2" on the Right side TipTap, the text is replaced with "?#". The same is expected with the Left side TipTap as well, but that doesn't happen. This is where I was mentioning about extension working only like a single instance and not as multiple instances, as I have two instances of the TipTap component.
