### ISSUE TITLE
Can I Get Unique Ids at getJSON export?

### ISSUE THREAD

**Issue by sadiksa** [ueberdosis/tiptap#2177]
### What problem are you facing?

I wanna add unique ids to every block of editor. And i wanna export it with getJSON method. But i cant understand the library structure. Is there anybody give me some advice?

### What’s the solution you would like to see?

Adding id to every block

### What alternatives did you consider?

I dunno

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
There is an official [unique id extension](https://tiptap.dev/api/extensions/unique-id) for exactly doing this.

**Comment by sadiksa** [comment]
Thanks how i couldnt see that :)
