### ISSUE TITLE
Collaboration example setup does not work with image node 

### ISSUE THREAD

**Issue by abasse** [ueberdosis/tiptap#2178]
### What problem are you facing?

Could you please add an example how to add an image node to the collaboration example. Collaboration works great for me for all basic text nodes, but the image node does not show up when collaboration is enabled in tiptap.

### What’s the solution you would like to see?

Example of the tiptap collaboration with image node or any other non text node.

### What alternatives did you consider?

Non yet.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
I can’t reproduce this. Feel free to re-open with a reproducable codesandbox.
