### ISSUE TITLE
autofocus "select all"

### ISSUE THREAD

**Issue by dusty-phillips** [ueberdosis/tiptap#2181]
### What problem are you facing?

In some cases when I initialize an editor, I want to immediately focus and select all the content.

### What’s the solution you would like to see?

The `autofocus` property of `editor` accepts several parameters for what position in the text should be selected: `start`, `end`, or a number. I would like a new possible value of `all` or `selectAll` to be an option.

```javascript
  const editor = useEditor({
    autofocus: "all"
    ...
  })

```

### What alternatives did you consider?

I currently do this in a `useEffect` hook:

```javascript
  useEffect(() => {
    if (editor) {
      setTimeout(() => {
        editor().focus().selectAll().run()
      })
    }
  }, [editor])
```

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
added and released!
