### ISSUE TITLE
Multiple Instances And Extensions...

### ISSUE THREAD

**Issue by ashfaq-shamsudeen** [ueberdosis/tiptap#2183]
### What’s the bug you are facing?

Since I didn't I see further comments from https://github.com/ueberdosis/tiptap/issues/2173, opening new issue here...

I am trying to create an extension to set up the toolbar like shown in the example https://tiptap.dev/examples/collaborative-editing/. There are several prosemirror plugins developed by us and some of them are creating dom to display dropdown (with 100+ entries and each entry having edit, delete option). Those shall be wrapped with TipTap extension and the only thing we want to do is to register those extensions with the editor and in the toolbar, those menus should auto appear, that is something outside of the prosemirror editor. Hope this clarifies. Thanks!

### How can we reproduce the bug on our side?

With reference to CodeSandbox:

If you click on the "H2" on the Right side TipTap, the text is replaced with "?#". The same is expected with the Left side TipTap as well, but that doesn't happen. This is where I was mentioning about extension working only like a single instance and not as multiple instances, as I have two instances of the TipTap component.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/vue2-tiptap-multiple-instances-uli2j

### What did you expect to happen?

Extensions don't work with multiple TipTap instances on the same page. Looking for a solution for that. Thanks for considering!

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
It’s not supported to mutate `this.options` or `this.defaultOptions`. You have to find another solution. You can probably use `addStorage` for it: https://tiptap.dev/guide/custom-extensions#storage

**Comment by kongweiying2** [comment]
@ashfaq-shamsudeen Did you ever resolve this? I think I'm getting a similar issue where extension commands don't work in secondary TipTap editor instances.
