### ISSUE TITLE
tiptap.dev website is down

### ISSUE THREAD

**Issue by shash7** [ueberdosis/tiptap#2192]
### What’s the bug you are facing?

Nothing much to say here. Can't access the tiptap.dev domain. Chrome says its DNS_PROBE_FINISHED_NXDOMAIN

### How can we reproduce the bug on our side?

Go to [tiptap.dev](https://tiptap.dev)

### What did you expect to happen?

I expect the website to open up

### Did you update your dependencies?

- [x] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by hanspagel** [comment]
Thanks! External monitoring doesn’t see any issues though:
https://status.tiptap.dev/

**Comment by shash7** [comment]
![Screen Shot 2021-11-24 at 7 28 02 pm](https://user-images.githubusercontent.com/3054413/143201974-caed810e-42c1-4958-b944-35d88191683a.png)

bruh

**Comment by hanspagel** [comment]
Then it seems to be a DNS issue, probably with the DNS server you’re using. Check if it works from your mobile device.

**Comment by shash7** [comment]
Yep, that's right. Switching to cloudflare dns fixed it.

Weird how my office network spazzes out on this one website.

**Comment by hanspagel** [comment]
And a bunch of users are on it, no decrease in traffic to see.

https://plausible.io/tiptap.dev?period=realtime

I’m closing this here as it seems to be something on your end.
