### ISSUE TITLE
Allow alternative to CMD+Enter to escape a CodeBlock

### ISSUE THREAD

**Issue by kylesuss** [ueberdosis/tiptap#2195]
### What problem are you facing?

https://tiptap.dev/api/nodes/code-block

> Press Command/Ctrl + Enter to leave the fenced code block and continue typing in boring paragraphs.

CMD+Enter is a common keyboard shortcut to submit a form. Many services (GitHub is an easy example with commenting blocks -- even this issue description can be submitted this way) allow you to submit a form this way. By making the CodeBlock only escapable via this shortcut, TipTap creates a collision that is not easily handled.

### What’s the solution you would like to see?

My preference would be to have a different keyboard combination to get out of the CodeBlock, but I would be ok with being allowed to override the default as well.

Alternatively, other services (such as Slack) allow you to escape a CodeBlock via Shift+Enter -- if you do that several times with empty lines, you break out of the fenced area.

### What alternatives did you consider?

I can check if the active node is a `codeBlock` via `editor.isActive('codeBlock')` before allowing form submission but I would prefer to have different shortcuts for these distinct actions.

Perhaps there is a way to do this that I am not aware of?

### Anything to add? (optional)

Happy to submit a PR, but I can't figure out where the CMD+Enter stuff happens. I only see this:

https://github.com/ueberdosis/tiptap/blob/b37b0921dd7a958c79cacbd29020967cbc7b3a3e/packages/extension-code-block/src/code-block.ts#L102-L122

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
> Happy to submit a PR, but I can't figure out where the CMD+Enter stuff happens. I only see this:

Right now, it’s defined in the default keymap: https://github.com/ueberdosis/tiptap/blob/62197ce4597fa05f59c09cba0a1680ff2b0988a5/packages/core/src/extensions/keymap.ts#L27

`exitCode` is a command that can leave not only the `CodeBlock` node, but all nodes that have set `code` to `true`: https://prosemirror.net/docs/ref/#model.NodeSpec.code

I have just written the logic for double-enter for another extension. I think I can reuse some of it for code blocks (which work a little differently).

**Comment by cadars** [comment]
I’m a little confused about this issue because it’s actually possible to escape a code block with Shift+Enter in the default demo: https://embed.tiptap.dev/preview/Examples/Default

What would be the difference? The fact that it’s using StarterKit?

**Comment by philippkuehn** [comment]
@cadars ah, you are right. there is also a handler in the hard break extension:
https://github.com/ueberdosis/tiptap/blob/7a04a32f1a11de0bc2e39d9c6d15626e158a4e39/packages/extension-hard-break/src/hard-break.ts#L49-L95

**Comment by philippkuehn** [comment]
you can now escape code blocks with triple enter (like slack)

**Comment by timnehring** [comment]
> you can now escape code blocks with triple enter (like slack)

Is there also a way to deactivate this feature? 
Currently I just copied the source code of the CodeBlock and commented out the corresponding part of the code. 
Is there a more elegant way of doing it?

**Comment by philippkuehn** [comment]
@timnehring I added some options for it in [this patch](https://github.com/ueberdosis/tiptap/commit/a35b7fbe2cee0390895aaeb358503b5ead116b64).
