### ISSUE TITLE
Custom extension node not working with input rules 

### ISSUE THREAD

**Issue by TheAussieStew** [ueberdosis/tiptap#2196]
### What’s the bug you are facing?

When I try to make a custom extension node, that takes in "```" and parses it into a node extension, I get this error. 
```
RangeError: Type given to setBlockType should be a textblock
(anonymous function)
src/structure.js:117
  114 | // Set the type of all textblocks (partly) between `from` and `to` to
  115 | // the given node type with the given attributes.
  116 | Transform.prototype.setBlockType = function(from, to = from, type, attrs) {
> 117 |   if (!type.isTextblock) throw new RangeError("Type given to setBlockType should be a textblock")
  118 |   let mapFrom = this.steps.length
  119 |   this.doc.nodesBetween(from, to, (node, pos) => {
  120 |     if (node.isTextblock && !node.hasMarkup(type, attrs) && canChangeType(this.doc, this.mapping.slice(mapFrom).map(pos), type)) {
  ```
  
  I've based my extension off the behaviour exhibited in the code-block extension.

### How can we reproduce the bug on our side?

https://codesandbox.io/s/patient-fog-1hji5

If you place the cursor at the end of the first sentence, press "Enter" to create a new line, type "```" and then press "Enter", the error is thrown and visible in the console.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/patient-fog-1hji5

Refer to the files BubbleExtension.tsx, Bubble.tsx, TipTap.tsx and Main.tsx.

Bubble is the ordinary React component I'd like to embed in-line. BubbleExtension is the Tiptap Node Extension wrapper, TipTap.tsx is where the editor is configured and Main.tsx is the entry point of the app. 

### What did you expect to happen?

I would expect the "```" to be parsed into a small bubble circle, like the one that already appears in-between the two sentences.

### Anything to add? (optional)

Strangely, when I search the TipTap codebase on GitHub for the thrown error, nothing comes up.

Also, appreciate all the amazing work you've put into making TipTap. Truly an artisan editor!

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
For some reason it’s not possible for me to open your codesandbox. I see just a loader.

**Comment by TheAussieStew** [comment]
Strange, I just tested it out on Safari (non-incognito) and it works. But I also do get a loader on Chrome (non-incognito). Would you like me to try and resolve the issue on Chrome, or would trying it on Safari be okay? I don't think this bug has any relation to CodeSandbox not loading on Chrome.

**Comment by philippkuehn** [comment]
It’s because you are using the `textblockTypeInputRule` for an atom node (not a text block node). Try to use `nodeInputRule` instead.

**Comment by TheAussieStew** [comment]
Perfect, thank you for the clarification!
