### ISSUE TITLE
MentionList events in Table

### ISSUE THREAD

**Issue by MaxAntonsson** [ueberdosis/tiptap#2200]
### What’s the bug you are facing?

With extensions `Table` and `Mention`:

If positioned on the first/last row of a table cell and triggering the mention menu/list. Pressing arrow up/down seems to prioritize the table cell navigation over the mention menu/list. It works however if not positioned on first/last row of the table cell.

### How can we reproduce the bug on our side?

1. Use the example code for extensions `Table` and `Mention`
2. Position cursor at first/last row of a table cell
3. Trigger mention menu
4. Try to navigate the mention menu using arrow up/down keys

### Can you provide a CodeSandbox?

https://codesandbox.io/s/blazing-sea-t66kn?file=/src/App.vue

### What did you expect to happen?

Exptected pressing arrow keys up/down to traverse the mention menu/list (when opened) over navigating to next/previous table cells.

### Anything to add? (optional)

I've tried adding `stopProgapagtion` etc, to the keydown-handler in the mention menu. But this function in the prosemirror-plugin used for tables seem to run first:
https://github.com/ProseMirror/prosemirror-tables/blob/6b16ed3cf306886f2c169aebbe60701e1ac2deac/src/input.js#L38
It works for example if pressing a modifier key like `alt` and then arrow up/down.

I'm not sure what the right approach would be here either. How can I override this behaviour while keeping most of the defaults, without having to fork or copy a bunch of prosemirror/tiptap code?

ie. maybe something along the lines of? 🤔 
```
addProseMirrorPlugins() {
  return [
    new Plugin({
      // ... keep most defaults
      props: {
        ...
        handleKeyDown: {
          // ... keep defaults
          "ArrowUp": // TODO
          "ArrowDown": // TODO
        }
      }
    })
  ]
}
```

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
This is a priority issue. You have to make sure that the event handler for the mention extension runs first. You can do that by moving the `Mention` extension below the `Table` extension in the extension list or by setting a higher priority at the mention extension: 

```js
Mention.extend({
  priority: 1000, // default is 100
}).configure({
  // ...
})

**Comment by fridaystreet** [comment]
Any other ideas on this? I'm trying to send a message in chat input on pressing enter key. No matter which way round I put the extension (or which priority) with the addProseMirrorPlugins to capture the Enter key press it always fires before my mention plugin.

onReturnHandler
```
export const OnReturnHandler = Extension.create({
  name: 'onReturnHandler',
  priority: 1,
  addProseMirrorPlugins() {
    return [
      new Plugin({
        key: new PluginKey('onReturnHandler'),
        props: {
          options: this.options,
          editor: this.editor,
          handleDOMEvents: { 
            keypress: function(view, event) {
              return onKeyDown(event, this.props.editor, this.props.options)
            }
          }    
        }
      })
    ]
  }
})
```

editor extensions setup
```
 extensions: [
      OnReturnHandler,
      StarterKit,
      Mention.configure({
        HTMLAttributes: {
          class: classes.mention,
        },
        suggestion
      }),
]
```

Cheers

**Comment by fridaystreet** [comment]
*Update*

Anyone landing here and still needing a fix. It may not be the correct way, but I found by having the onReturnHandler listen to the keyup event instead of the keydown, it fires after the keydowns in any extensions based on native javascript priority of events

**Comment by Saidfatah** [comment]
@fridaystreet have you found a work around for the Enter key issue you mentioned ?

**Comment by fridaystreet** [comment]
@Saidfatah we did, but can't remember off top of my head. I'll have a look through code tomorrow and let you know.

**Comment by fridaystreet** [comment]
Seems don't use handleDOMEvents, use handleKeyDown as per below. Load plugin before anything else you want the plugin to block enter key for, then return true in the onReturn function when you want to stop enter key press propagating to the next plugin

```
export const OnReturnHandler = Extension.create({
  name: 'onReturnHandler',

  addProseMirrorPlugins() {
    return [
      new Plugin({
        key: new PluginKey('onReturnHandler'),
        props: {
          editor: this.editor,
          options: this.options,
          handleKeyDown: (view, event) => onReturn(event, this.editor, this.options)
        }
      })
    ]
  }
})
```

**Comment by Saidfatah** [comment]
@fridaystreet did you use this with suggestions extension ? if so how ?
