### ISSUE TITLE
Confusion around Pro extensions

### ISSUE THREAD

**Issue by beingflo** [ueberdosis/tiptap#2202]
### What’s the URL to the page you’re sending feedback for?

https://tiptap.dev/examples/tables

### What part of the documentation needs improvement?

Pro extension labeling in particular for tables but probably also others.

### What is helpful about that part?

Generally documentation is very high quality :)

### What is hard to understand, missing or misleading?

The communication around Pro extensions is confusing to me. Under nodes, `Tables` is not listed as a pro extension, but in the examples for tables there is a 'commercial use' banner. Is this just a suggestion? I would appreciate clearer documentation on this and it's implication on licensing.

### Anything to add? (optional)

Thank you for creating and maintaining tiptap, it's really a joy to use!

PS: I fully intend to pay for access to the Pro extensions, just need the product to start making some money first 😉 
In the meantime I would like to avoid violating licenses.

**Comment by hanspagel** [comment]
Thanks for the feedback! Just removed this suggestion. 👌
