### ISSUE TITLE
Table width and colwidth for each col

### ISSUE THREAD

**Issue by Aless55** [ueberdosis/tiptap#2203]
### What problem are you facing?

I want to export the whole html file into a docx document. Because of that I will need to know at least the col width for each of the columns. Now this value is only set after resizing the cols and also only for the tcol that was resized. 
To display the columns correctly I need to know how much the width is for each column. 

I tried to look through the source code and also ProseMirror but can't find a hint where to start. 

### What’s the solution you would like to see?

I would like to know where and when the width value is set and if there might be a possibility that I could rewrite the table extension to make it work. 
I don't really need the exact code, maybe some hint in the right direction/to the right docs will help.

### What alternatives did you consider?

Sadly there is no good alternative for my problem.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by hanspagel** [comment]
I wrote this to set the table width when a single column width is modified. Maybe that gives you a starting point.

https://gist.github.com/hanspagel/de6cd0c30ece7afb3f2ba663768f373f

**Comment by philippkuehn** [comment]
This is out of scope for tiptap itself so I'm closing this. You should probably write some logic of your own, similar to the example from above.
