### ISSUE TITLE
how to disable the default extension (prosemirror-dropcursor) and import it manually? 

### ISSUE THREAD

**Issue by Auxxxxlx** [ueberdosis/tiptap#221]
I rewrite the `dropcursor`,  but do not know how to disable built-in plugins(`prosemirror-dropcursor`).

**Comment by Alecyrus** [comment]
Or is there some way to rewrite the dropCursor style?
```javascript
...
    // no way to change default cursor style (border-radius? :after? :before?)
    this.element.style.left = (rect.left - parentRect.left) + "px"
    this.element.style.top = (rect.top - parentRect.top) + "px"
    this.element.style.width = (rect.right - rect.left) + "px"
    this.element.style.height = (rect.bottom - rect.top) + "px"
...
```

**Comment by Chrissi2812** [comment]
You can pass options to the the dropCursor Plugin

```js
new Editor({
  dropCursor: {
    color: '#f00',
    width: 5,
  },
});
```

A class on the dropcursor would be better but thats an issue of  [prosemirror-dropcursor](https://github.com/ProseMirror/prosemirror-dropcursor)

**Comment by Alecyrus** [comment]
@Chrissi2812 Thank you. I notice the options of `dropCursor`, but I want to disable it and use the modified version of `dropCursor` extension.

**Comment by christosnc** [comment]
https://github.com/scrumpy/tiptap/pull/705

**Comment by hanspagel** [comment]
Merged. 👍  Will be part of the next version.
