### ISSUE TITLE
`generateHTML` utility not working on version `2.0.0-beta.142`

### ISSUE THREAD

**Issue by GonzaloHirschToptal** [ueberdosis/tiptap#2210]
### What’s the bug you are facing?

We are implementing the conversion between the JSON output from the Tiptap editor and HTML in an Eleventy site, but the conversion never returns and generates our pages to fail.

### How can we reproduce the bug on our side?

<details>
<summary>The sample JSON we are using is this:</summary>
<pre><code>
{
  "type": "doc",
  "content": [
      {
          "type": "paragraph",
          "content": [
              {
                  "type": "text",
                  "text": "Lorem ipsum dolor sit, amet consectetur adipisicing elit."
              }
          ]
      },
      {
          "type": "bulletList",
          "content": [
              {
                  "type": "listItem",
                  "content": [
                      {
                          "type": "paragraph",
                          "content": [
                              {
                                  "type": "text",
                                  "text": "Hic voluptate fugiat reprehenderit"
                              }
                          ]
                      }
                  ]
              },
              {
                  "type": "listItem",
                  "content": [
                      {
                          "type": "paragraph",
                          "content": [
                              {
                                  "type": "text",
                                  "text": "Et quae vitae commodi harum"
                              }
                          ]
                      }
                  ]
              },
              {
                  "type": "listItem",
                  "content": [
                      {
                          "type": "paragraph",
                          "content": [
                              {
                                  "type": "text",
                                  "text": "Animi dolor reiciendis deleniti"
                              }
                          ]
                      }
                  ]
              }
          ]
      },
      {
          "type": "paragraph",
          "content": [
              {
                  "type": "text",
                  "text": "Ratione "
              },
              {
                  "type": "text",
                  "marks": [
                      {
                          "type": "bold"
                      }
                  ],
                  "text": "doloremque"
              },
              {
                  "type": "text",
                  "text": " voluptatem. Repellendus "
              },
              {
                  "type": "text",
                  "marks": [
                      {
                          "type": "italic"
                      }
                  ],
                  "text": "accusantium"
              },
              {
                  "type": "text",
                  "text": " eum "
              },
              {
                  "type": "text",
                  "marks": [
                      {
                          "type": "underline"
                      }
                  ],
                  "text": "quidem"
              },
              {
                  "type": "text",
                  "text": " consequatur "
              },
              {
                  "type": "text",
                  "marks": [
                      {
                          "type": "link",
                          "attrs": {
                              "href": "https://midnightrevolta.com",
                              "target": "_blank"
                          }
                      }
                  ],
                  "text": "quibusdam"
              },
              {
                  "type": "text",
                  "text": "."
              }
          ]
      }
  ]
}
</code></pre>
</details>

### Can you provide a CodeSandbox?

I don't have a reproduction repo or CodeSandbox to reproduce this.

### What did you expect to happen?

I expect it to make the conversion between JSON and HTML or at least fail with an error we can debug.

### Anything to add? (optional)

We are importing the modules using `require` (in case it makes a difference).

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
I can’t help without any code or a reproducable demo here. Maybe [this is the issue](https://github.com/ueberdosis/tiptap/issues/1174#issuecomment-746490934).

**Comment by GonzaloHirschToptal** [comment]
> I can’t help without any code or a reproducable demo here. Maybe [this is the issue](https://github.com/ueberdosis/tiptap/issues/1174#issuecomment-746490934).

@philippkuehn I looked for hours and couldn't find this. The issue you mentioned solved it. Thank you so much!
