### ISSUE TITLE
Text align is misaligned when aligning to the right.

### ISSUE THREAD

**Issue by gillisig** [ueberdosis/tiptap#2211]
### What’s the bug you are facing?

When you align a paragraph that spans multiple lines to the right. The right edge ends up being misaligned with the last line. 

### How can we reproduce the bug on our side?

Simply go to your documentation for  TextAlign here: https://tiptap.dev/api/extensions/text-align#alignments

Paste in something like "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum"

See how the last line is further to the right than the rest, unless it ends with a space.

### What did you expect to happen?

The right align should be completely aligned from top to bottom, which is usually the case in other editors.

### Anything to add? (optional)

Screenshot I took at https://tiptap.dev/api/extensions/text-align#alignments

![image](https://user-images.githubusercontent.com/5390864/143938240-96a0c6a3-d8e7-4a9b-a3e6-22525db8d443.png)

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by cadars** [comment]
This is due to `white-space: break-spaces;` in ProseMirror’s CSS, which fixes an issue in Firefox: https://discuss.prosemirror.net/t/putting-many-white-spaces-at-end-of-a-line-with-marks-bug/2300/3

**Comment by gillisig** [comment]
Thanks @cadars. Looks like I was able to override it to fit my needs. I'll close this since it seems to be by design.
