### ISSUE TITLE
generateHTML in @tiptap/html doesn't escape html properly

### ISSUE THREAD

**Issue by aliasliao** [ueberdosis/tiptap#2217]
### What’s the bug you are facing?

When the input in the editor starts with `<`, the `generateHTML` funtion in `@tiptap/html` won't escape the content.

For example, when typing:
```html
this is <strong>hello</strong>
```
the output of `generateHTML` is:
```plain
<p>this is &lt;strong&gt;hello&lt;/strong&gt;</p>
```
which is what we expect.

However, when typing:
```html
<strong>hello</strong>
```
the output of `generateHTML` is:
```plain
<p><strong>hello</strong></p>
```

That is, the function does not escapte the html at all.

### How can we reproduce the bug on our side?

Install `@tiptap/html@2.0.0-beta.142`, which depends on `zeed-dom@0.9.16`. I believe the problem is with `zeed-dom@0.9.16`.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/tiptap-generate-html-issue-l6mk2

### What did you expect to happen?

`generateHTML` should escape all html entities.

### Anything to add? (optional)

The problem lies in `zeed-dom@0.9.16`.

It has already been fixed here: https://github.com/holtwick/zeed-dom/commit/e5e1c400167b2c39aa8d02818d9c7dc464fefb2a#diff-86fe84b457508e0156e89b33424a861a2e689cae804dd33b13f663eb7d3af41aL111

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Not sure why you created an issue if it’s already fixed in zeed-dom. Do a fresh install of your dependencies and it should load the latest version of zeed-dom.

**Comment by aliasliao** [comment]
> Not sure why you created an issue if it’s already fixed in zeed-dom. Do a fresh install of your dependencies and it should load the latest version of zeed-dom.

You are right. Re-install `@tiptap/html` can solve the issue. I guess the merge request #2218 is unnecessary too, I'll close it.
