### ISSUE TITLE
Multiple Mention Plugin Instances Don't Work

### ISSUE THREAD

**Issue by Rykuno** [ueberdosis/tiptap#2219]
### What’s the bug you are facing?

I have use case where multiple mentions are needed. Such as you should be able to type `u/user` for mentioning a user and `g/guild` for mentioning a guild. 

I have replicated the code in [the example repo for mentions](https://github.com/ueberdosis/tiptap/tree/main/demos/src/Nodes/Mention/React) and added a unique `pluginKey` within each `suggestion` file as you can view in the CodeSandbox repo.

Both mentions will trigger the popup with their respective `char` triggers, problem is only one of the mentions will render, which is the last initialized within `useEditor`

For example. Within the CodesandBox typing and selecting a mention upon`g/...` will always render as a `u/...`.

### How can we reproduce the bug on our side?

Refer to Codesandbox.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/laughing-mclaren-cbe3t?file=/src/index.js

### What did you expect to happen?

A mention triggered upon `u/...` should render as `u/...`

A mention triggered upon `g/...` should render as `g/...`

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by BrianHung** [comment]
I would try copying and pasting the [source code from mentions](https://github.com/ueberdosis/tiptap/blob/main/packages/extension-mention/src/mention.ts), and create different nodes for each type. Alternatively, use one plugin but store in `attrs` whether a node is a user or guild mention, then modify `renderLabel` to change output based on that.

The problem right now is that the both mention nodes that you created share the same extension / node name; as a result, the last mention passed in will be the one used by the editor to render the node.

**Comment by philippkuehn** [comment]
With [this patch](https://github.com/ueberdosis/tiptap/commit/6c34dec33ac39c9f037a0a72e4525f3fc6d422bf) I removed some magic strings to extending should be easier now. To use multiple instances of the mention extension you’ll need unique names, chars and pluginKeys.

```js
const CustomMentionOne = Mention
  .extend({
    name: 'customMentionOne',
  })
  .configure({
    suggestion: {
      char: "@",
      pluginKey: new PluginKey("suggestionOne")
      // ...
    }
  }),

const CustomMentionTwo = Mention
  .extend({
    name: 'customMentionTwo',
  })
  .configure({
    suggestion: {
      char: "$",
      pluginKey: new PluginKey("suggestionTwo")
      // ...
    }
  })
```

**Comment by Rykuno** [comment]
> 

I've added the `.extend` to the Mention plugins and updated the packages to latest. 

As of now the mention triggers are not working with the `.extend` function. See forked sandbox to test 

https://codesandbox.io/s/affectionate-edison-0g5zi?file=/src/TipTap/index.jsx

**Comment by philippkuehn** [comment]
You are right. There is another issue. Let me take a look.

**Comment by philippkuehn** [comment]
I released a new version of `@tiptap/core` which fixes the issue 👍

**Comment by abhijit-chikane** [comment]
> With [this patch](https://github.com/ueberdosis/tiptap/commit/6c34dec33ac39c9f037a0a72e4525f3fc6d422bf) I removed some magic strings to extending should be easier now. To use multiple instances of the mention extension you’ll need unique names, chars and pluginKeys.
> 
> ```js
> const CustomMentionOne = Mention
>   .extend({
>     name: 'customMentionOne',
>   })
>   .configure({
>     suggestion: {
>       char: "@",
>       pluginKey: new PluginKey("suggestionOne")
>       // ...
>     }
>   }),
> 
> const CustomMentionTwo = Mention
>   .extend({
>     name: 'customMentionTwo',
>   })
>   .configure({
>     suggestion: {
>       char: "$",
>       pluginKey: new PluginKey("suggestionTwo")
>       // ...
>     }
>   })
> ```

Thanks 
You saved my day!💓💓
