### ISSUE TITLE
Editor breaking plugins that use mark comparison (e.g. prosemirror-codeblock

### ISSUE THREAD

**Issue by nokola** [ueberdosis/tiptap#2227]
### What’s the bug you are facing?

I found an issue while using https://github.com/curvenote/prosemirror-codemark that I believe is due to TipTap.

The `prosemirror-codemark` plugin needs a schema mark to compare with to know when "inside code block". In order to work with TipTap, since the schema is created when new Editor() is called, I use getSchema([extensions ...]) to get it beforehand. However, the schema returned has marks that are never equal to any marks of the new schema if compared with prosemirror's markType.isInSet(anotherMark).

more info in repro: https://codesandbox.io/s/tiptap-schema-breaking-mark-isinset-ifyi6?file=/src/App.vue

### How can we reproduce the bug on our side?

1. Open https://codesandbox.io/s/tiptap-schema-breaking-mark-isinset-ifyi6?file=/src/App.vue
2. Click to the left of `code`
3. Move back and forth with left/right arrows
Expected:
Cursor moves around left edge in and out of the code block
![correct](https://user-images.githubusercontent.com/6869225/144503759-e7b3266f-58dd-4d76-aa06-412fe84b4de5.gif)

Actual:
Cursor jumps inside code block skipping a character (same as if the prosemirror-codeblock extension was not used)
![buggycode](https://user-images.githubusercontent.com/6869225/144503545-aac8c9cb-988b-4ff8-b448-01b09ef7fa3f.gif)

### Can you provide a CodeSandbox?

https://codesandbox.io/s/tiptap-schema-breaking-mark-isinset-ifyi6?file=/src/App.vue

### What did you expect to happen?

Cursor moves around left edge in and out of the code block
![correct](https://user-images.githubusercontent.com/6869225/144503759-e7b3266f-58dd-4d76-aa06-412fe84b4de5.gif)

### Anything to add? (optional)

* See this comment in `src/App.vue` to fix bug:
```
// UNCOMMNENT here and COMMENT below line to fix bug
```

* Also see the `// ISSUE: ...` comment in App.vue for more info.

* If this is fixed, I think it will help other plugins that need schema before Editor is created to work and save a lot of time in debugging.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
It’s way more easier. You don’t want to create another instance of the schema. Use `this.editor.schema` instead. Working demo: https://codesandbox.io/s/tiptap-schema-breaking-mark-isinset-forked-eswr9?file=/src/App.vue

**Comment by nokola** [comment]
Nice! I didn't realize `this` is bound and schema is constructed in addExtensions()! Thanks for the prompt response!
