### ISSUE TITLE
How should first line indentation be implemented?

### ISSUE THREAD

**Issue by SF-Simon** [ueberdosis/tiptap#2229]
### What problem are you facing?

We want to insert an indented character into a new line when the user presses enter, such as \t.

### What’s the solution you would like to see?

Can there be relevant cases for our reference or relevant plug-ins.

### What alternatives did you consider?

```
  addKeyboardShortcuts() {
    return {
      Enter: () => {
        const { selection } = this.editor.view.state;
        const { $anchor } = selection;

        return this.editor.commands.insertContentAt($anchor.pos, "\n\t");
      },
    };
  },
```

We tried to do it with a low priority plug-in. Just like the code above.

But after we insert "\n\t", we enter new characters again and find that \n has disappeared. Then we don't know how to finish the work.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by hanspagel** [comment]
This sounds like something that should be done with CSS, did you consider that as an alternative?

**Comment by SF-Simon** [comment]
Unfortunately, our product requirement is to insert characters.

Hans Pagel ***@***.***>于2021年12月3日 周五下午4:27写道：

**Comment by philippkuehn** [comment]
There is no newline in ProseMirror. You have to insert a `<br>` instead. This should work:

```js
insertContentAt($anchor.pos, '<br>\t')
```

**Comment by SF-Simon** [comment]
> There is no newline in ProseMirror. You have to insert a `<br>` instead. This should work:
> 
> ```js
> insertContentAt($anchor.pos, '<br>\t')
> ```

I'm really stupid. I was amused by myself....

thank you. This is the right way.
