### ISSUE TITLE
editable property is not working with Node(Vue component)

### ISSUE THREAD

**Issue by Auxxxxlx** [ueberdosis/tiptap#223]
![image](https://user-images.githubusercontent.com/13865581/53864840-7a864480-4028-11e9-8fe0-f75659037dbb.png)

```javascript
 watch: {
    editable(newValue, oldValue) {
      this.editor.setOptions({
        editable: newValue
      });
    }
  },
```

```javascript
 props: ['node', 'updateAttrs', 'editable'],
```

**Comment by philippkuehn** [comment]
I removed the `editable` prop, because it's already available and reactive (!) via `view.editable`. So please use the `view` prop instead.

**Comment by techouse** [comment]
Spent an hour debugging this 🚬 Good thing I stumbled upon this. Was already wondering if my computed property abuse got the best of me 💃

**Comment by philippkuehn** [comment]
@techouse Ah thanks! Fixed it!

**Comment by A-d-o-n-i-s** [comment]
Did this change? It doesn't work with `this.editor.view.editable` for me, but `this.editor.options.editable` works..

As an aside:
Is there a way to bind this to my custom Vue component that includes the Tiptap Editor component? I cannot get a parent component to control the edibility of the embedded Tiptap Editor through prop binding in Vue.js :-( Thanks!
