### ISSUE TITLE
Contextual Table UI

### ISSUE THREAD

**Issue by holtwick** [ueberdosis/tiptap#2230]
### What problem are you facing?

Table UI is a complex task. 

A UI should only show options that make sense in the context of the current selection.

### What’s the solution you would like to see?

I would love to see a sample for best practice integration. Similar to the context bubble feature for inline styles. 

I think Evernote is doing a great job here:

https://user-images.githubusercontent.com/49557/144574702-aa8e829b-14b3-420c-88d2-ad9f5ba8cb89.mp4

### What alternatives did you consider?

The sample: https://tiptap.dev/api/nodes/table

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Oh, there are some missing disabled states in that example. There is another table example which shows commands that doesn’t have any effect but there are still a lot. Does that help?

<img width="778" alt="CleanShot 2021-12-03 at 10 06 31@2x" src="https://user-images.githubusercontent.com/2500670/144576055-cd792a28-e9a9-46b5-8d3a-afce1febd6dc.png">

**Comment by holtwick** [comment]
The functionalities are already great and nothing is missing so far. 

In the examples the actions are placed in a global toolbar. I just wondered if functionalities that consider the context as shown in the video are worth implementing on your side. I'm in particular refering to:

- Add rows/cols in between existing cells (the blue + in the video)
- Removing rows/cols

I know, this is probably beyond the goal of a headless editor, but since you are providing similar example for bubble menu, I've got some hope ;) https://tiptap.dev/api/extensions/bubble-menu

**Comment by hanspagel** [comment]
I think that would be great. I keep refusing everything that’s related to tables, though.

Tables are complex. And there are tons of feature requests. But our extensions is 100 % based on `prosemirror-tables`, which isn’t maintained anymore (Marijn is looking for a new maintainer).

I think the only way to go is a complete Table rewrite for Tiptap. Until then, we’ll collect all ideas and see what we can integrate with a new Table extension. Things I have in my mind already:

* Maybe the mentioned UI
* Maybe an API to access and modify the content of specific cells
* Maybe based on CSS Grid for the in-editor experience
* Maybe, but probably not, based on a powerful table library (https://handsontable.com/ is amazing, but we’d pick something free)

I think I’m closing this for now. But once we decide to pick up the fricking-huge-table-rewrite-project, I’ll make sure to look through issues before we start.

**Comment by holtwick** [comment]
Ok, I see. 

Just a last one I found along my research: https://www.npmjs.com/package/@remirror/extension-react-tables

I know it is the competitor ;) But it is also using ProseMirror and the functionality comes close to what I would love to see in TipTap (with Vue of course) Maybe something to consider once you get to it.

**Comment by fantasticit** [comment]
<img width="840" alt="截屏2022-03-22 13 22 22" src="https://user-images.githubusercontent.com/26452939/159413435-5262dc22-adbb-4dd0-ab51-c9218207a81d.png">

Maybe we can use the `Decoration`(`prosemirror-view`) to make a table. Example code is [here](https://github.com/fantasticit/think/blob/main/packages/client/src/components/tiptap/extensions/tableCell.tsx).

**Comment by lzxlzxlzxl** [comment]
How to set the border color of the table？
