### ISSUE TITLE
Link Extension Broken w/ Multiple Mentions 

### ISSUE THREAD

**Issue by Rykuno** [ueberdosis/tiptap#2231]
### What’s the bug you are facing?

When utilizing multiple mentions then adding a link to the same editor, the last character(even if it has a space between) becomes part of the link.

In the GIF referenced below, you can see the `d` in `and` right before the link is now encapsulated within the `<a>` tag.

I tested this and it only appears to be an issue when multiple mentions are involved. A single mention works just fine.

### How can we reproduce the bug on our side?

Utilize multiple mentions(can be of same type) then add a link. (Refer to codesandbox)

### Can you provide a CodeSandbox?

https://codesandbox.io/s/affectionate-edison-0g5zi?file=/src/TipTap/index.jsx%3C/a%3E%3C/p%3E

### What did you expect to happen?

The `d` in the last `and` within the codesandbox example should not be encapsulated within the `<a>` tag for the link plugin

### Anything to add? (optional)

http://www.giphy.com/gifs/dv6T4C2cmYAtV2YqGt

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Oh, you're right. The link position is calculated incorrectly when atom nodes are rendered in the same text block.
