### ISSUE TITLE
Error when link extension autolink is true.

### ISSUE THREAD

**Issue by HeinKoZin** [ueberdosis/tiptap#2233]
### What’s the bug you are facing?

I got an error like this: 

```
Unhandled Runtime Error
TypeError: (0 , _tiptap_core__WEBPACK_IMPORTED_MODULE_0__.combineTransactionSteps) is not a function
```

### How can we reproduce the bug on our side?

Can somebody fix for me?

### What did you expect to happen?

The link will be auto-embed but I got an error whenever I type.

![Screenshot 2021-12-04 212751](https://user-images.githubusercontent.com/28890199/144714407-a2c2179b-ca0b-468c-a9bd-4352de6e8b95.png)

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
please update @tiptap/core to the latest version! that should fix the error.
