### ISSUE TITLE
In Vue3, an error occurred while destroying and recreating the editor.

### ISSUE THREAD

**Issue by SF-Simon** [ueberdosis/tiptap#2234]
### What’s the bug you are facing?

[Error] Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'component.emitsOptions')
	logError (runtime-core.esm-bundler.js:784)
	handleError (runtime-core.esm-bundler.js:6849)
	callWithErrorHandling (runtime-core.esm-bundler.js:6803)
	flushJobs (runtime-core.esm-bundler.js:7036)
	promiseReactionJob
[Warning] [Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/vue-next (2)
"
"
" at <App>"

### How can we reproduce the bug on our side?

```
      if (app.editor) {
        app.editor.destroy();
        app.editor = null;
      }
      // recreate
      app.editor = new Editor({....
```

In vue3, because we want the editor to be a new object, we intend to destroy and create a new object.

However, when we use the above code, there is a prompt error of Vue3.

### What did you expect to happen?

We want to rebuild the editor on the current page and load new content to make the status of history and plug-ins new.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Can’t reproduce [this here](https://codesandbox.io/s/focused-dawn-cneui?file=/src/App.vue). Seems to be an issue with your setup.
