### ISSUE TITLE
How to add some attrs in table element

### ISSUE THREAD

**Issue by adou2236** [ueberdosis/tiptap#2237]
### What’s the bug you are facing?

How to add some attrs in table element

### How can we reproduce the bug on our side?

123

### What did you expect to happen?

123

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Look at the docs: https://tiptap.dev/guide/custom-extensions#attributes

There is also an example of adding a background color attribute to table cells: https://tiptap.dev/examples/tables
