### ISSUE TITLE
A single @ will cause the content to become empty (yDoc)

### ISSUE THREAD

**Issue by iojanis** [ueberdosis/tiptap#2246]
### What’s the bug you are facing?

https://user-images.githubusercontent.com/12971934/145040059-9733f3b6-55df-405e-a524-7a60030278ad.mov

If I enter an @ and do not select an item, then close the editor and open it again, I get the error 'RangeError: Position 10 out of range' and the complete content of the yXMLFragment is deleted. 

### How can we reproduce the bug on our side?

Since I changed the Mention plugin, I don't know for sure if the problem is created by me. I will create a sandbox and post it as soon as I am back home. Nevertheless, I wanted to ask if anyone knows what the problem could be. 

The editor is configured using the collaboration plugin, a yDoc and field.

### Can you provide a CodeSandbox?

later

### What did you expect to happen?

Don't clear the content if a @ is found.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Any news on this sandbox?

**Comment by hanspagel** [comment]
I’m pretty sure this is a y-prosemirror bug, maybe even a Y.js bug. I’ll try to look into it.
