### ISSUE TITLE
Can't unset links generated by autolink

### ISSUE THREAD

**Issue by Aarjente** [ueberdosis/tiptap#2251]
### What’s the bug you are facing?

I noticed that calling `commands.unsetLink` or `commands.toggleLink` or even `commands.unsetMark("link")` doesn't seem to do anything on links that were created via autolink. It appears to go through and perform the prosemirror transaction, but the mark persists. Works fine if the link was set via `setLink`.

### How can we reproduce the bug on our side?

It's reproducible on the link extension example here: https://tiptap.dev/api/marks/link

- Type out a link, google.com for example, in the tiptap instance under the Usage section
- Move the text selection anywhere inside the link text
- Click on the unsetLink button

### What did you expect to happen?

Expected the link to be unset and the text to appear as plaintext. 

### Anything to add? (optional)

https://user-images.githubusercontent.com/6392992/145096299-2aaa42e1-7ffc-459d-a60a-afc7980315a4.mp4

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 

💖

**Comment by philippkuehn** [comment]
This isn’t supported right now and I don’t have plans to store if it’s a "regular" link or an "autolink". So this is by design. You can set `autolink` to `false` on the links extension if this an issue for you.

What kind of links do you want to remove?

**Comment by Aarjente** [comment]
Ah, that's good to know - thanks for clarifying. 

In my use case I have UI that allows users to modify or unset any link that's captured by the current text selection, and I was hoping that the autolinks would be behave the same as the other links. Can be easily done manually though!

**Comment by schwemmer** [comment]
I have the same issue. When a user drags a file into the editor, I create a link to the file. This link can then no longer be edited (e.g. to set target blank or self). If I set `autolink: false`, the link can be edited but it is no longer has an href to the inserted file. Not sure what I am supposed to do and why it doesn't work with autolink.

**Comment by obedparla** [comment]
I think this is supported now. It works for me both in my code and in the example:

https://user-images.githubusercontent.com/10674462/150649072-9fba5882-c8d0-4385-ba8c-771c4e1bd391.mp4
