### ISSUE TITLE
Custom Vue component extensions are re-mounted when dragging them down

### ISSUE THREAD

**Issue by caroillemann** [ueberdosis/tiptap#2253]
### What’s the bug you are facing?

Hi,

First of all thanks for an amazing rich-text editor :)

I've created a custom Vue TipTap-extension. The issue I'm facing is that when I drag my Vue component up everything works as expected but when I drag it down the Vue component is recreated and remounted.

What I would expect is that the component never gets destroyed and thereafter recreated when dragging it down.

Here you can see a screen recording of the issue (note the info messages):
https://user-images.githubusercontent.com/32357241/145207467-69fb009a-8f27-43ff-b1cd-084cfb43652b.mp4

### How can we reproduce the bug on our side?

1. Follow the TipTap guide for setting up a new Vue project.
2. Create a custom extension that renders a Vue component. The extension should have dragging enabled, and the Vue component should log something in the created() and mounted() events.
3. Open the console and see the logged output when dragging the Vue component up and down.

### Can you provide a CodeSandbox?

Vue: https://codesandbox.io/s/tiptap-vuecomponentdraggingbug-w7m7f

### What did you expect to happen?

I expect that the component isn't created or mounted when dragging either up or down.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
This is a limitation of ProseMirror so we can’t do anything here.

Somehow related to #372 where I try to implement a nodeview cache. But I have not found a solution so far, unfortunately.

**Comment by caroillemann** [comment]
Ah okay, thanks for the quick reply :)
