### ISSUE TITLE
Emoticon support

### ISSUE THREAD

**Issue by hognevevle** [ueberdosis/tiptap#2254]
### What problem are you facing?

With the [emoji](https://tiptap.dev/api/nodes/emoji) extension, you currently have to start typing `slightly` to get the simple smiling emoji (`:slightly_smiling_face:`). 

It would be great to be able to define emoji aliases, so that e.g. `:)`, `:D` etc. could be transformed to their preferred equivalents.

### What’s the solution you would like to see?

Slack handles this very nicely:

![CleanShot 2021-12-08 at 14 40 19](https://user-images.githubusercontent.com/2721188/145218189-b8475ea7-fe88-4218-beef-f158a1a171ff.gif)

### What alternatives did you consider?

 I guess I could register them as `customEmojis`, but Is suppose that would basically mean duplicating those emojis?

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Do you talk about emoticon support in general? So a predefined list of supported emotions would be fine?

**Comment by hognevevle** [comment]
Yes, that sounds like exactly what I'd be looking for :)

**Comment by philippkuehn** [comment]
There is a new option called `enableEmoticons` https://tiptap.dev/api/nodes/emoji#enable-emoticons (defaults to `false`)
Our data is based on [emojibase](https://emojibase.dev/) which supports the most common emoticons.
