### ISSUE TITLE
vite + vue2 'BubbleMenuPluginKey' is not exported

### ISSUE THREAD

**Issue by thejsbaguette** [ueberdosis/tiptap#2255]
### What’s the bug you are facing?

when running `npm run build` with `vite 2.7.0` have this warning

some pictures:

my usage:

<img width="577" alt="Screen Shot 2021-12-08 at 9 39 48 AM" src="https://user-images.githubusercontent.com/11556276/145227346-215375d5-7efd-442d-88b0-bb7070404ed8.png">

the deps:

<img width="648" alt="Screen Shot 2021-12-08 at 9 50 51 AM" src="https://user-images.githubusercontent.com/11556276/145229294-0378575b-9805-4a56-aa0b-3e990a76127e.png">

the warning:

<img width="965" alt="Screen Shot 2021-12-08 at 9 49 23 AM" src="https://user-images.githubusercontent.com/11556276/145229038-5211650a-72ea-4be2-8593-41efd2c8f2de.png">

### How can we reproduce the bug on our side?

install the version with my `vite.config.js`

```
import { createVuePlugin } from 'vite-plugin-vue2'

export default {
  plugins: [
    createVuePlugin(/* options */)
  ],
}
```

### What did you expect to happen?

it should npm run build without issue

` "build": "vite build",`

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Seems like the image of your error message is not uploaded correctly.

**Comment by thejsbaguette** [comment]
thanks @philippkuehn . After updated the deps I don't have the error anymore but now this warning.

**Comment by hanspagel** [comment]
We don’t provide a calender or date picker though, so most of the warnings aren’t related to Tiptap at all.

The first warning "conflicting namespaces" is known, but we can’t really do something about it (without making everything more complex for us).

**Comment by thejsbaguette** [comment]
Why you closed it ? @hanspagel the warning is not about calendar here. Check the namespace conflict error in the log please

**Comment by philippkuehn** [comment]
It’s described above and a duplicate of #1857
