### ISSUE TITLE
[@tiptap/extension-link] Attempted import error

### ISSUE THREAD

**Issue by jdckl** [ueberdosis/tiptap#2257]
### What’s the bug you are facing?

Installing and importing this extension into a create-react-app project fails the compiler and throws:

```
./node_modules/@tiptap/extension-link/dist/tiptap-extension-link.esm.js
Attempted import error: 'combineTransactionSteps' is not exported from '@tiptap/core'.
```

All other extensions work.

### How can we reproduce the bug on our side?

Not exactly sure, I'm on CRA + craco. Code Sandbox cant reproduce the issue.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/muddy-forest-bupt3

### What did you expect to happen?

The module importing succesfuly.

### Anything to add? (optional)

App uses Craco for run/build, with tailwind css and autoprefixer in style plugins. **combineTransactionSteps** doesn't even seem to exist. @tiptap/react is 2.0.0-beta.98, @tiptap/extension-link is 2.0.0-beta.33, react at 17.0.2

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Update `@tiptap/core` to the latest version.
