### ISSUE TITLE
The white space characters before and after each paragraph disappear?

### ISSUE THREAD

**Issue by SF-Simon** [ueberdosis/tiptap#2265]
### What’s the bug you are facing?

```
      app.editor = new Editor({
        editable: true
        autofocus: false,
        extensions: [
          StarterKit.configure({
            heading: {
              levels: [1, 2, 3],
            },
          }),
        ],
        content: "<h1>    1111111   </h1><h3>   2222 </h3><p>   33333  </p>",
```

### How can we reproduce the bug on our side?

Under MacOS, both chrome and safari have problems. I looked at the HTML code and found that there were no white space characters in the code.

### What did you expect to happen?

Keep anything entered by the user.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by cadars** [comment]
See https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Whitespace

**Comment by SF-Simon** [comment]
I finished typing in the editor, then stored the HTML, and then read it out
and it changed.  So, do I need to pay attention to this?

**Comment by cadars** [comment]
Maybe ProseMirror's ParseOptions are what you're after? https://tiptap.dev/api/editor#parse-options

**Comment by philippkuehn** [comment]
Yes, change the [`parseOptions`](https://tiptap.dev/api/editor#parse-options) option or store your data as JSON.
