### ISSUE TITLE
How to check whether the content is valid?

### ISSUE THREAD

**Issue by martindzejky** [ueberdosis/tiptap#2268]
### What problem are you facing?

Looking through the documentation, I did not find any way how to check whether the content I passed to the Tiptap editor is valid (conforms to the schema).

The only thing I see is an empty editor and a warning in the console. Any way to catch this warning in code?

### What’s the solution you would like to see?

Either a function to check whether some content conforms to the schema (defined by extensions), or some `editor.isValid` getter.

### What alternatives did you consider?

I tried constructing the schema using `getSchema` but could not figure out a way to validate it against a content. I also looked through the ProseMirror docs to no avail.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
There is a `check()` method for nodes: https://prosemirror.net/docs/ref/#model.Node.check

So `editor.state.doc.check()` should do the trick.

**Comment by martindzejky** [comment]
Thanks a lot :heart_eyes:

**Comment by martindzejky** [comment]
@philippkuehn unfortunately it does not work. I'm trying to do this: 

```
const editor = useEditor({
  content: '<something invalid here>',
  
  onCreate({ editor }) {
    editor.state.doc.check(); // does nothing
  },
});
```

But the check always passes. The editor prints a warning into the console but then replaces its content with a valid one (in my case a single empty paragraph), and the call to `check()` passes.

**Comment by philippkuehn** [comment]
There are two cases. 

If you put in an HTML string, it will be parsed by the rules of the nodes. No error is thrown if content is converted. This is also not possible. In fact, this is one of the strengths of ProseMirror. The only thing you can do is to compare the input content with `editor.getHTML()`.

If you put in JSON content, it will not be validated. The `check()` method can be used to check if the content matches the schema.

**Comment by martindzejky** [comment]
Actually, I'm putting in JSON content. :thinking: I'll take a closer look into what data is flowing into the editor instance and how it behaves.
