### ISSUE TITLE
@tiptap/extension-character-count version 2.0.0-beta.22 broken

### ISSUE THREAD

**Issue by suits-at** [ueberdosis/tiptap#2276]
### What’s the bug you are facing?

After updating @tiptap/extension-character-count to the newest version (2.0.0-beta.22) the editor does not work anymore. It is not possible to type anything. There are no errors during build and no errors during runtime. Downgrading to the version I used before (2.0.0-beta.18) fixed the problem. 

### How can we reproduce the bug on our side?

This are the other packages which are used:
```
"@tiptap/core": "^2.0.0-beta.153",
"@tiptap/extension-bullet-list": "^2.0.0-beta.25",
"@tiptap/extension-document": "^2.0.0-beta.15",
"@tiptap/extension-heading": "^2.0.0-beta.24",
"@tiptap/extension-list-item": "^2.0.0-beta.20",
"@tiptap/extension-paragraph": "^2.0.0-beta.23",
"@tiptap/extension-text": "^2.0.0-beta.15",
"@tiptap/vue-2": "^2.0.0-beta.71",
```

### Can you provide a CodeSandbox?

https://codesandbox.io/s/wispy-paper-z15x4?file=/package.json

### What did you expect to happen?

Work like before, with version 2.0.0-beta.18.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
`undefined` was not a valid value for `limit`. this is fixed now.
