### ISSUE TITLE
Can't clear formatting of first line if it's a block node

### ISSUE THREAD

**Issue by rfgamaral** [ueberdosis/tiptap#2281]
### What’s the bug you are facing?

If the first line in the editor is a block node (like a heading), there's no way to clear formatting without a toolbar.

### How can we reproduce the bug on our side?

* Got to the editor on https://tiptap.dev front page
* Type `# Test` to turn the paragraph into a heading
* Select all text with `Mod+A` and delete it
   * Alternative, use `Backspace` to delete everything
* Observe that the heading node is not cleared, and it's not possible to reset to a normal paragraph without a formatting toolbar

### What did you expect to happen?

The block node (the heading) to be reset to a paragraph if ALL the node text was deleted.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
I created a [PR](https://github.com/ueberdosis/tiptap/pull/2284) for it. Any feedback? Here is a [preview](https://deploy-preview-2284--tiptap-embed.netlify.app/preview/Examples/Default).

**Comment by rfgamaral** [comment]
@philippkuehn Looks great, thanks for fixing this.

**Comment by cadars** [comment]
This is awesome, thanks much!
