### ISSUE TITLE
More graceful unknown node handling

### ISSUE THREAD

**Issue by kaspnilsson** [ueberdosis/tiptap#2283]
### What problem are you facing?

I've introduced a node type that I've saved to my DB, and now I want to remove it without breaking the rendering of all of my content. This is something relatively normal that happens during product development.

Currently, removing a node type produces a warning `[tiptap warn]: Invalid content. Passed value: {content: Array(17), type: 'doc'} Error: RangeError: Unknown node type: myNodeType` and stops the content from rendering.

Is it possible for me to just ignore or prune unknown nodes?

Repro:

(1) Add a node of an unknown type to your content array
(2) watch the entirety of the content not render

### What’s the solution you would like to see?

Some ability to ignore or prune unknown nodes, or some other way to migrate content without a full DB migration

### What alternatives did you consider?

DB migration -- painful!

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
No, this is not possible if you are using the JSON content. If it’s an option you can use the HTML content instead because an HTML string is parsed each time and unsupported nodes are converted if necessary. Otherwise, you should migrate your JSON content.

**Comment by Zzombiee2361** [comment]
Why is this not possible? You literally only need to skip rendering it. My use case is to sanitize html output from `generateHTML()`. For example I deliberately omit `Link` extension on a comment section to prevent malicious user to post a link. A malicious user could post a json with a link mark and it would appear, if I register the extension, or if I don't his comment won't render at all and it's flooding our logs with error.

The alternative could be sanitizing every json for unregistered node before rendering but I'd rather not do that

**Comment by kee-oth** [comment]
My team would like the feature to skip rendering an unknown block as well. Hard to see why crashing the program is more useful than just not rendering the block.

**Comment by kongweiying2** [comment]
@philippkuehn Is this being looked at by the team at all currently? With respect, I've run into this problem multiple times, each time because I had to delete or add new extension. If I modify the renderHTML behaviour or change from Mark to Node, and try and revert a change then the file is essentially corrupted. There's no way to go back to a valid state. This also makes the doc which is synced with the new Collab backend unusable. Since there's no way to modify docs on Collab, one has to manually delete the doc and start all over with a completely new doc.

**Comment by nadar** [comment]
This issue should be reopened, its a real problem. There also other reports: https://github.com/ueberdosis/tiptap/issues/3437

**Comment by grahamplace** [comment]
Agree with the above folks who want to gracefully ignore nodes in e.g. "old" data. I would use this feature if supported

**Comment by jbhaywood** [comment]
+1000 to the above comments. I know this is a complicated system and I appreciate that it exists, but with how popular and widely used TipTap is, this seems like basic error handling functionality that should be included by default. Just the ability to ignore unknown types would be a big improvement.

**Comment by nperez0111** [comment]
We are working on a fix with: https://github.com/ueberdosis/tiptap/pull/5178
