### ISSUE TITLE
HTML output of React node view

### ISSUE THREAD

**Issue by thefinnomenon** [ueberdosis/tiptap#2289]
### What problem are you facing?

I created a React node view component and it works perfectly in the editor but it doesn't render right when using `generateHTML()`. For now, I am setting `editable` to `false` as suggested in the [documentation](https://tiptap.dev/guide/node-views#render-java-scriptvuereact) but, ideally, I would be able to display the editor output as static HTML.

### What’s the solution you would like to see?

I would love to be able to use my React Component definition in `renderHTML()`, have the attributes and editable content merged in, and the HTML for the component be returned. I am trying to get more familiar with ProseMirror's HTML rendering process but I feel like something like this should be possible.

### What alternatives did you consider?

So far, I have tried to convert the React component with attributes to HTML using `ReactDOMServer.renderToStaticMarkup(<MyComponent node={node}/>) with the plan to inject the node content into the `node-view-content` div(s). 

```
renderHTML(props) {
    const { HTMLAttributes, node } = props;

    const componentHTML = ReactDOMServer.renderToStaticMarkup(
      <MyComponent
        node={{ attrs: HTMLAttributes }}
      />
    );

    return [
      'div',
      mergeAttributes(HTMLAttributes, { 'data-type': 'my-component' }),
      componentHTML,
    ];
  },
```

The HTML ends up getting encoded so I decode it before setting it to the div's HTML,
`<div dangerouslySetInnerHTML={{ __html: decodeHtml(previewContent) }} />`. This renders my component correctly but seems hacky and I'm not sure how to properly include the node view content.

I'm probably going to just use the editor with `editable` set to `false` for now but I think this would be handy.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Hey, you can also provide an object with `dom` and `contentDOM` within `renderHTML`. The content of the node is rendered inside `contentDOM`. That might help.

```js
renderHTML() {
  const dom = document.createElement('div')
  const contentDOM = document.createElement('div')

  dom.append(contentDOM)

  return {
    dom,
    contentDOM,
  }
}
```

But keep in mind that this method must be rendered synchronously. I think React can only render asynchronously since v17, right?

**Comment by thefinnomenon** [comment]
This isn't working for me. I tried setting background colors on the wrapping divs but the content is rendered unstyled, without the wrapping divs.

```js
renderHTML({ HTMLAttributes }) {
    const dom = document.createElement('div');
    const contentDOM = document.createElement('div');

    dom.style.cssText = 'background-color: red;';
    contentDOM.style.cssText = 'background-color: blue;';

    dom.append(contentDOM);

    return {
      dom,
      contentDOM,
    };
  },
```

**Comment by thefinnomenon** [comment]
Thanks, that worked perfectly! One more question, is it possible to have multiple NodeViewContent sections in one NodeViewWrapper? For example, say I wanted to make a quiz component with an editable question section and four editable answer boxes? How would I dictate to render specific content where when I only have the ability to pass one contentDOM? Would the only approach to this be to define multiple extensions?

**Comment by hanspagel** [comment]
Yes, you can create an AnswerBox node to achieve that. 👌 Think of it like a BulletList with ListItems.

**Comment by thefinnomenon** [comment]
Cool, thanks!

**Comment by srsudar** [comment]
I couldn't replicate this. Do you happen to have an example repo somewhere?

**Comment by Dari4sho** [comment]
For anyone working on SSR and therefore can't use document as of https://github.com/ueberdosis/tiptap/issues/2289#issuecomment-996552932, I vibecoded this function that helps transforming the htmlstring generated from the react component to a tiptap node:

```
import ReactDOMServer from "react-dom/server";
import { parseDocument } from "htmlparser2";
import React from "react";

function htmlStringToTipTapFormat(htmlString: string): any[] {
  const doc = parseDocument(htmlString);

  function convertNode(node: any): any {
    if (node.type === 'text') {
      return node.data;
    }

    if (node.type === 'tag') {
      const result: any[] = [node.name];

      // Add attributes if they exist
      if (node.attribs && Object.keys(node.attribs).length > 0) {
        result.push(node.attribs);
      }

      // Add children
      if (node.children && node.children.length > 0) {
        const children = node.children.map(convertNode).filter((child: any) => child !== null);
        result.push(...children);
      }

      return result;
    }

    return null;
  }

  // Return the first element's conversion, or fallback to the original structure
  if (doc.children && doc.children.length > 0) {
    const firstElement = doc.children.find(child => child.type === 'tag');
    if (firstElement) {
      return convertNode(firstElement);
    }
  }

  // Fallback if parsing fails
  return ['div', {}, htmlString];
}
``` 

Usage:
```
    renderHTML(props) {
      const { options, node } = props;

      // Render React component to HTML string
      const componentHTML = ReactDOMServer.renderToStaticMarkup(
        React.createElement(UserElement, {
          node: node,
          updateAttributes: () => {} // Not needed for static rendering
        })
      );

      // Convert HTML string to TipTap's expected format
      const convertedHTML = htmlStringToTipTapFormat(componentHTML);

      // Merge with options and return
      return [
        convertedHTML[0], // tag name
        mergeAttributes(convertedHTML[1] || {}, options.HTMLAttributes, { 'data-type': 'user-mention' }),
        ...convertedHTML.slice(2) // children
      ];
    },
```

It might have some limits, but for my basic components it works so far.
