### ISSUE TITLE
Scroll on drag?

### ISSUE THREAD

**Issue by codemzy** [ueberdosis/tiptap#2291]
### What problem are you facing?

When I try to drag an item (for example an image) to reorder, if the editor (or browser) is shorter than the content, once you get to the bottom of the viewable area it's not possible to keep dragging the item down further in your content. 

You can see this in the docs here [https://tiptap.dev/examples/images](https://tiptap.dev/examples/images) if you try and drag the top image down to re-order, you can't without scrolling down first.

### What’s the solution you would like to see?

It would be nice if the editor scrolled down (or up) with the drag. This would mean for long content, or large images, it's easier to re-arrange content by dragging it where you want it anywhere in the editable content - even it's out of view.

Hope this makes sense, it's hard to explain.

### What alternatives did you consider?

I haven't figured this out yet, but I will see if I can come up with a work around.

### Anything to add? (optional)

You are doing an awesome job on Tiptap! I love using it. I'm not sure how easy this would be to implement, but I wanted to but the suggestion forward 😄 

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Hmm, this should work because it uses the native HTML5 drag&drop feature. This seems to be a limitation of our demos (nested iframes). I can’t reproduce it in a separated tab.

https://user-images.githubusercontent.com/2500670/146584147-fe99a9fd-00e5-4f4a-87ca-7c90f51aaf96.mp4

**Comment by codemzy** [comment]
Thanks so much, I've now narrowed this down to a browser specific issue in Safari, which for some reason isn't scrolling on drag. But I've checked in Chrome and Firefox and it works like you have shown. Not sure why I'm having issues in Safari but at least it's working in other browsers. Thanks again 😄
