### ISSUE TITLE
appendTo to document.body makes BubbleMenu noninteractive

### ISSUE THREAD

**Issue by tkulpa** [ueberdosis/tiptap#2292]
### What’s the bug you are facing?

Adding `tippyOptions={{  appendTo:  () => document.body }}` to `BubbleMenu ` causes that BubbleMenu buttons become unclickable and I need tippy to be portaled outside of parent

### How can we reproduce the bug on our side?

See CodeSandbox below

### Can you provide a CodeSandbox?

https://codesandbox.io/s/tiptap-react-editor-forked-umehj

### What did you expect to happen?

Things inside `BubbleMenu` after it being appended to body is still clickable

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
This is not supported because rendering an element outside of the react scope breaks interactivity. this is a limitation of react.

**Comment by sjdemartini** [comment]
fyi @tkulpa I have an alternate BubbleMenu component example here https://github.com/ueberdosis/tiptap/issues/2305#issuecomment-1020665146 which is relatively simple but uses a Portal so should presumably work for your use-case.
