### ISSUE TITLE
Mentions not working with Safari

### ISSUE THREAD

**Issue by paulm17** [ueberdosis/tiptap#2298]
### What’s the bug you are facing?

When I use the mentions extension in my own code using Safari.  I see:

```
text.matchAll is not a function. (In 'text.matchAll(regexp)', 'text.matchAll' is undefined).
```

Trying your own examples at: https://tiptap.dev/examples/suggestions

I get in the tools:

```
TypeError: t.matchAll is not a function. (In 't.matchAll(q)', 't.matchAll' is undefined)
```

### How can we reproduce the bug on our side?

Open safari, navigate to https://tiptap.dev/examples/suggestions and you'll find the mentions don't show up when doing @... and look at the console for errors.

### Can you provide a CodeSandbox?

No need to.  Seems internal to tiptap.

### What did you expect to happen?

Mentions should show and no console.log errors.

### Anything to add? (optional)

https://i.imgur.com/mjjip5a.png

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
You are probably using an old version of Safari.

tiptap 2 is using this browserslist config of supported browsers:

```json
"browserslist": [
    "defaults",
    "not IE 11"
],
```

`default` means:
Browserslist’s default browsers (> 0.5%, last 2 versions, Firefox ESR, not dead).

Right now we don’t have plans to change that.
