### ISSUE TITLE
ItemList console error on click

### ISSUE THREAD

**Issue by estarossa0** [ueberdosis/tiptap#2299]
### What’s the bug you are facing?

when using ItemList trying to click on the checkbox output an error in console
`Uncaught RangeError: Index 1 out of range for <taskList(taskItem(paragraph))>`
is there is a way to prevent this console output from happening ?

### How can we reproduce the bug on our side?

just create a Itemlist and click on the checkbox (or just use the example in the docs, as outputs the same)

### What did you expect to happen?

no the checkbox getting checked since docs say nothing about it, but at least no console error

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
I can’t reproduce this in our demos with latest chrome/firefox/safari. Feel free to reopen with a reproducable demo.

**Comment by jaulz** [comment]
@philippkuehn just stumbled across the same while trying your demos. You can reproduce it by clicking any checkbox in the demo here:
https://tiptap.dev/api/nodes/task-item

**Comment by philippkuehn** [comment]
@jaulz Then it’s maybe a duplicate of #2372

**Comment by jaulz** [comment]
@philippkuehn thanks a lot for your prompt response! it's indeed Bitwarden...

**Comment by philippkuehn** [comment]
Still not sure why it only causes problems with this extension 🤷‍♂️

**Comment by jaulz** [comment]
@philippkuehn it will probably happen with every interaction on an input that is in the within the editor itself because Bitwarden adds a `data-com.bitwarden.browser.user-edited="yes"`to the input element once it's touched and then the schema does not fit to the output anymore?

**Comment by hanspagel** [comment]
Probably! Related:
https://github.com/bitwarden/browser/issues/725

**Comment by jaulz** [comment]
Yep, that's what I also found but unfortunately there doesn't seem to be an option to disable this behaviour. Even checked the code of the extension itself...

Even `checkbox.removeAttribute('data-com.bitwarden.browser.user-edited')` in the change handler does not work... 🤔

**Comment by philippkuehn** [comment]
The only thing you can do is to extend the taskItem extension and add a custom node view without native inputs.
