### ISSUE TITLE
Can not use any extension after HardBreak newline

### ISSUE THREAD

**Issue by JonathanKolnik** [ueberdosis/tiptap#2302]
### What’s the bug you are facing?

If you use the HardBreak extension you can't immediately enter a code or codeblock after the new line. My colleague @kylesuss and I are having trouble finding a workaround for this.  

Turns out this applies to any styling directly after the new line.

### How can we reproduce the bug on our side?

in the default text editor https://tiptap.dev/examples/default:
1. Type "hello world"
2. Shift+enter
3. Try to enter `Code` by typing "`" 

### What did you expect to happen?

I expected to see the code preview.

This works if you "Shift+Enter" then type a space and then "`".

### Anything to add? (optional)

[![Image from Gyazo](https://i.gyazo.com/d345eee26ca6664821fd9e446d8d453e.gif)](https://gyazo.com/d345eee26ca6664821fd9e446d8d453e)

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by JonathanKolnik** [comment]
🎉 Thank you @philippkuehn

**Comment by kylesuss** [comment]
Thanks for this @philippkuehn . I think there may still be an issue, though it appears to apply selectively to certain extensions:

**CodeBlock**

![hardbreak-codeblock](https://user-images.githubusercontent.com/3035355/147162975-dddea010-c045-4d46-82cf-77f8ffd23110.gif)

**BulletList**

![hardbreak-list](https://user-images.githubusercontent.com/3035355/147163268-47db4c06-0b8c-4b09-a27c-5310dfb3f0a0.gif)


## Whereas these work now:

**Bold**

![hardbreak-bold](https://user-images.githubusercontent.com/3035355/147163007-71d10885-d7d6-4583-a159-235db669ccdc.gif)

**Code**

![hardbreak-code](https://user-images.githubusercontent.com/3035355/147163024-782ad7ef-230c-481b-ab34-039a99fdaf14.gif)

Any ideas? Thanks 🙇

**Comment by philippkuehn** [comment]
It’s because an input rule is looking at the current block. in this case the block is the whole paragraph. A line break does not create a new block. It is just an inline node within the block. So the input rules gets this content `first line<br>second line` instead of `second line`.

Some input rules are working within a block like adding marks but some input rules are working only at a start of a block like converting to a list or code block. That’s why this isn’t working here. Also, if the input rules worked, they would convert the entire block instead of just the second line. I would therefore not change anything here.

**Comment by kylesuss** [comment]
Ok @philippkuehn , thanks for the explanation. We can work with that & adjust our setup based on that idea 👍

**Comment by kylesuss** [comment]
For anyone interested, we wanted to use HardBreak as more of a block level node so we went with this extension:

```js
const CustomHardBreak = HardBreak.extend({
  group: 'block',
  content: 'text*',
  inline: false,
  addCommands() {
    return {
      setHardBreak:
        () =>
        ({ commands, editor }) => {
          const { state } = editor;
          const { selection } = state;
          const { $head } = selection;

          const position = $head.after();
          return commands.insertContentAt({ from: position, to: position }, { type: this.name });
        },
    };
  },
});
```

Will take feedback on better approaches 😆  but so far it is doing the trick 🪄

**Comment by rfgamaral** [comment]
@kylesuss I'm curious about the use case for that custom extension? Can you provide an example and explain how different it behaves from the standard extension?

**Comment by kylesuss** [comment]
@rfgamaral Sure thing. In terms of the JSON structure, it takes us from here:
```js
{
  type: 'doc',
  content: [
    {
      type: 'paragraph',
      content: [
        { type: 'text', text: 'line 1' },
        { type: 'hardBreak' },
        { type: 'hardBreak' },
        { type: 'text', text: 'line 3' },
      ]
    },
  ]
}
```

To here:

```js
{
  type: 'doc',
  content: [
    { type: 'paragraph', content: [{ type: 'text', text: 'line 1' }] },
    {type: 'hardBreak'},
    { type: 'paragraph', content: [{ type: 'text', text: 'line 3' }] }
  ]
}
```

We are using TipTap for a commenting form. We want people to be able to use any shortcode that our extensions support after pressing shift+enter so from what I gathered from @philippkuehn 's comment, the way to do that was to render `hardBreak` as a block level node. That's what I came up with to get there 🤷

**Comment by rfgamaral** [comment]
@kylesuss Okay, thanks for the clarification. Happy holidays everyone :)

**Comment by kylesuss** [comment]
Actually there was a bit of a bug with our previous implementation. We decided to just rip out `HardBreak` altogether and replicate the functionality we wanted with a custom extension:

```js
import { Node } from '@tiptap/core';
import Paragraph from '@tiptap/extension-paragraph';

const ShiftEnter = Node.create({
  name: 'shiftEnter',
  addCommands() {
    return {
      setNewParagraph:
        () =>
        ({ commands, editor }) => {
          const { state } = editor;
          const { selection } = state;
          const { $head } = selection;
          const position = $head.after();

          return commands.insertContentAt(
            { from: position, to: position },
            { type: Paragraph.name } // Note this is adding a paragraph
          );
        },
    };
  },
  addKeyboardShortcuts() {
    return {
      'Shift-Enter': () => this.editor.commands.setNewParagraph(),
    };
  },
});
```

This gets us what we want in terms of behavior for breaking out of various nodes & also accepting all keyboard shortcuts thereafter. & it more closely replicates the behavior in terms of the underlying JSON structure for just hitting "enter" in the editor (vs shift+enter).


```js
{
  type: 'doc',
  content: [
    { type: 'paragraph', content: [{ type: 'text', text: 'line 1' }] },
    { type: 'paragraph' },
    { type: 'paragraph', content: [{ type: 'text', text: 'line 3' }] }
  ]
}
```
