### ISSUE TITLE
Selecting last line of text and replacing with something else on a "plain-text mode" has unexpected behaviour

### ISSUE THREAD

**Issue by rfgamaral** [ueberdosis/tiptap#2304]
### What’s the bug you are facing?

We are using Tiptap to build both a rich-text and plain-text editor, and while we are very happy with the results we get from a rich-text editor, the plain-text one has one small issue that we haven't figured out how to fix.

The plain-text mode is built with a small subset of the `StarterKit` extensions, like this:

```ts
const PlainTextDocument = Document.extend({
    content: 'paragraph',
})

const PlainTextHardBreak = HardBreak.extend({
    addKeyboardShortcuts() {
        return {
            ...this.parent?.(),
            Enter: () => this.editor.commands.setHardBreak(),
        }
    },
})

const editor = useEditor({
      extensions: [PlainTextDocument, PlainTextHardBreak, Paragraph, Text, History]
})
```

### How can we reproduce the bug on our side?

Take the CodeSandbox provided below and:

1. Select the last line of text (i.e. `Fourth line`), the whole line!
2. Press `x` (any character will do)
3. Observe that `x` was placed in the third line, and not the selected/fourth line as expected

This does not happen if any other line is selected, only on the last one in the document.

![tiptap-plain-text-issue](https://user-images.githubusercontent.com/96476/146963874-2add14f9-dc21-4b64-aa4b-ad5264fb0bb1.gif)

### Can you provide a CodeSandbox?

https://codesandbox.io/s/focused-engelbart-7t7m9?file=/src/App.js:694-772

### What did you expect to happen?

I expected that replacing text of the last selected line in the document doesn't move the replacement text to the previous line.

### Anything to add? (optional)

I understand that a "plain-text mode" is something unusual for Tiptap, but we're leveraging the power of Tiptap/ProseMirror to provide our users the choice of a powerful Markdown editor or a WYSIWYG experience, and although this is not a dealbreaker, it's a bit annoying, but still an edge case.

I don't think a workaround on our side is possible... At least I tried to hook into ProseMirror's `handleTextInput` and it doesn't fire when I try to replace the text on the last line, but it works for the others though (so I'm thinking this is an issue with either Tiptap or ProseMirror itself).

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
This only happen in Firefox but also with plain ProseMirror. It’s probably some bug with the CSS `white-space` setting. I don’t think Tiptap can do here anything :/

**Comment by rfgamaral** [comment]
Oh, right, I remember what bug this is. Thanks for looking into it.

Do you think there's any CSS workaround that could be applied to Firefox only, perhaps?

**Comment by philippkuehn** [comment]
I don’t think so. If you find something let me know.
