### ISSUE TITLE
Can't 'setOptions' in order to update the class of an element

### ISSUE THREAD

**Issue by ruben00001** [ueberdosis/tiptap#2307]
### What’s the bug you are facing?

I want to dynamically update the style of 'paragraph' elements within the editor. Please correct me if I'm wrong, but it seems the way to dynamically update the editor is to use `editor.setOptions` - this works to e.g. set 'editable' to false but doesn't work e.g. when trying to do something like below.

`editor.setOptions({
   extensions: [
      StarterKit.configure({
         paragraph: {
            HTMLAttributes: {
               class: "bg-red-500'',
            },
         },
     }),
   ],
})`

### How can we reproduce the bug on our side?

To reproduce the bug, simply try to use `editor.setOptions({extensions.configure({...`.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/xenodochial-sunset-hypt7?file=/src/TextEditor.js

### What did you expect to happen?

I expect to be able to dynamically update the class of an element within the editor.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
updating extension options is not supported. you have to re-create the editor or use some custom commands for it. see #1044
