### ISSUE TITLE
For YJS and collaboration users it might be helpful to have xmlToJSON or xmlToHTML utilities

### ISSUE THREAD

**Issue by milesingrams** [ueberdosis/tiptap#2310]
### What problem are you facing?

I am using YJS to collaborate on multiple Y.XMLFragments on a page using the TipTap collaboration extension. The Y.XMLFragments are persisted to a database. If I want to server side render the XML fragments I have no utility method to convert them into HTML from the stored XML.

### What’s the solution you would like to see?

I'd love to have either xmlToHTML and/or xmlToJSON utilities in the `@tiptap/html` package

### What alternatives did you consider?

I tried using the editor instances to retrieve and persist the HTML or JSON alongside the YJS doc. This forces duplicate data on the server as well as risks the possibility of inconsistency in the data. It is also difficult if not impossible to do if you are using an intermediate YJS socket server to persist to the database.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by hanspagel** [comment]
https://github.com/yjs/y-prosemirror#utilities

**Comment by milesingrams** [comment]
Awesome! Didn't realize those functions existed on y-prosemirror. Will definitely use them to convert to TipTap readable JSON and then to HTML.
