### ISSUE TITLE
The parseOptions parameter of setContent does not work.

### ISSUE THREAD

**Issue by SF-Simon** [ueberdosis/tiptap#2315]
### What’s the bug you are facing?

We want to replace everything in the editor with spaces. Therefore, we use the parseOptions parameter for configuration.

But it didn't work.

### How can we reproduce the bug on our side?

```
          this.editor
            .chain()
            .setContent(newContent, false, {
              parseOptions: {
                preserveWhitespace: "full",
              },
            })
            .focus(focusPosition)
            .run();
```
Execute the above code, the content of the editor is replaced, but there are no white space characters.

### What did you expect to happen?

As the document says, it can keep all spaces in the new content.

### Anything to add? (optional)

It is normal for me to use the code below, but it is an insert, not a replacement.

```
          this.editor
            .chain()
            .insertContent(newContent, {
              parseOptions: {
                preserveWhitespace: "full",
              },
            })
            .focus()
            .run();
```

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Right now, parseOptions is the third parameter of the `setContent` command. So this should work:

```js
this.editor
  .chain()
  .setContent(newContent, false, {
    preserveWhitespace: "full",
  })
  .focus(focusPosition)
  .run();
```

This may change in the future if we refactor some commands as part of https://github.com/ueberdosis/tiptap/issues/2087
