### ISSUE TITLE
Custom extension cuts text after first match of custom block

### ISSUE THREAD

**Issue by stanislav-grin** [ueberdosis/tiptap#2321]
### What’s the bug you are facing?

I'm trying to create a custom Tag extension - just like the Mention ext, but for another purpose (some kind of special values inside the simple text that should be highlighted).
Similar to how Zapier or Integromat services have their inputs:
<img width="809" alt="Name your zap | Zapier 2021-12-27 14-49-14" src="https://user-images.githubusercontent.com/16938843/147473284-96e6b9f2-da6f-44f1-afd1-7d758f2b014d.png">

I have created a custom Tag extension, it parses all span's with `data-type="tag"`, have included it as other extensions, but when I put some value that contains these spans in editor's content, in UI it cuts the text right after the first matched span. And I don't understand why so.

### How can we reproduce the bug on our side?

1. Create a custom extension that parses spans with a specific `data-type`, e.g. `"tag"` (I have provided code below in the CodeSandbox section)
2. Include extension to the editor
3. Set editor content to the following:
```
`Simple message with 
      <span contenteditable="false" data-type="tag" data-label="tag content"/> 
      here 
      <span contenteditable="false" data-type="tag" data-label="another tag"/>
      another simple text
      `
```

**Actual Result:**
`Simple message with tag content`

**Expected Result:**
`Simple message with tag content here another tag another simple text`

### Can you provide a CodeSandbox?

https://codesandbox.io/s/smoosh-platform-2m805

### What did you expect to happen?

I expect to see all the text content I've provided to the editor

### Anything to add? (optional)

Using following versions:
```
"@tiptap/core": "2.0.0-beta.159",
"@tiptap/react": "2.0.0-beta.102",
```

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [x] Yes, I’m a sponsor. 💖

**Comment by hanspagel** [comment]
Don’t use self-closing tags. 👌

https://discuss.prosemirror.net/t/custom-empty-element-used-as-pagebreak-visual-tab/3129/2
