### ISSUE TITLE
[table collaboration]The collaborator cannot see the correct display of the selection of other people's table

### ISSUE THREAD

**Issue by yinran100** [ueberdosis/tiptap#2323]
### What’s the bug you are facing?

The collaborator cannot see the correct display of the selection of other people's table

### How can we reproduce the bug on our side?

![2021-12-28 16 49 57](https://user-images.githubusercontent.com/38638816/147547999-27bac405-2c4d-4d8c-9b1c-bc449ad3dfe8.gif)
![2021-12-28 16 50 27](https://user-images.githubusercontent.com/38638816/147548001-b42072d3-4519-4da9-b4ac-9b7e4b6c6caa.gif)

### What did you expect to happen?

The collaboration plugin is best to support the styles selected in the table cells, or don't show cursor

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by BrianHung** [comment]
This is because y-prosemirror which underlies the collaboration plugin doesn't support syncing selections beyond simple text selections: https://github.com/yjs/y-prosemirror/blob/master/src/plugins/sync-plugin.js.

**Comment by hanspagel** [comment]
Thanks! Yes, it’s a combination of two other packages, prosemirror-tables and y-prosemirror, so nothing we’d can do about it with a reasonable amount of work.
