### ISSUE TITLE
Placeholder shown when editor has Vue node view

### ISSUE THREAD

**Issue by minhlt-fa** [ueberdosis/tiptap#2329]
### What’s the bug you are facing?

I have issue when I type text in first line of the editor. Then I insert Node view below and clear the first line. The placeholder will show but editor doesn't empty.

### How can we reproduce the bug on our side?

1. Type text at first line
2. Add node view below the text
3. Clear text in first line

### Can you provide a CodeSandbox?

https://codesandbox.io/s/issue-placeholder-uk8sy?file=/src/App.vue

### What did you expect to happen?

Placeholder will show if the editor is really empty. If have any node view, the placeholder don't have to show.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
You are probably looking for `.ProseMirror p.is-editor-empty:first-child::before`
instead of `.ProseMirror p.is-empty:first-child::before`
