### ISSUE TITLE
create node from json?

### ISSUE THREAD

**Issue by swuecho** [ueberdosis/tiptap#233]
How should I create a Node from json content? 

for example: for the todo list example. I want to insert a todo list of 3 todo item with prefixed content.

my current roadmap is to get the json of todo lists and then create a todolist node from it then insert that node to the editor.

but I did not find a road to create a node from the json.  

Thanks!

**Comment by philippkuehn** [comment]
You can do something like this: 

```js
const doc = this.editor.getJSON()

doc.content.push({
  type: 'custom_node',
  attrs: {}, 
  content: [{
    type: 'paragraph',
  }],
})

this.editor.setContent(doc)
```

**Comment by victorvianaom** [comment]
I found 2 ways of accomplishing this, both with same output:

First:
```js
import { Node } from "prosemirror-model"
const node = Node.fromJSON(
    editor.schema,
    json
  );
```

Second:
```js
const node = editor.schema.nodeFromJSON(json);
```
