### ISSUE TITLE
tableCell inline & gapcursor

### ISSUE THREAD

**Issue by drop1down** [ueberdosis/tiptap#2335]
### What’s the bug you are facing?

Combination of tableCell content: "inline" & gapcursor do not work as expected.

### How can we reproduce the bug on our side?

Check codesandbox.
Click into one cell and move cursor with keys.
You should see gap cursor between (!) tableCells.

If i change from inline* to paragraph, it work.
I do not need paragraphs in table cells.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/charming-davinci-qsluo?file=/src/App.js

```js
import React from "react";
import { useEditor, EditorContent } from "@tiptap/react";
import "./styles.css";

import Document from "@tiptap/extension-document";
import Text from "@tiptap/extension-text";
import Gapcursor from "@tiptap/extension-gapcursor";

import Table from "@tiptap/extension-table";
import TableRow from "@tiptap/extension-table-row";
import TableHeader from "@tiptap/extension-table-header";
import TableCell from "@tiptap/extension-table-cell";

const CustomTableCell = TableCell.extend({
  content: "inline*"
});

export default () => {
  const editor = useEditor({
    extensions: [
      Document,
      Text,
      Gapcursor,
      Table,
      TableRow,
      TableHeader,
      CustomTableCell
    ],
    content: `
	  <table>
	  <tr>
	  <td>1</td>
	  <td>2</td>
	  </tr>
	  <tr>
	  <td>3</td>
	  <td>4</td>
	  </tr>
	  </table>    
    `
  });

  return (
    <>
      <EditorContent editor={editor} />
    </>
  );
};
```

### What did you expect to happen?

no gap cursor between cells

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
This is probably an issue with `prosemirror-gapcursor` or `prosemirror-tables` itself. As a workaround you can disable gapcursors within table rows at all.

```js
TableRow.extend({
  allowGapCursor: false,
}),
```
