### ISSUE TITLE
Cursor moves to beginning when double clicking at end of React custom node view

### ISSUE THREAD

**Issue by TheSociologist** [ueberdosis/tiptap#2337]
### What’s the bug you are facing?

When double clicking at the end of a custom node view (e.g. a paragraph) rendering using React, the cursor jumps to beginning instead of selecting the line.

https://user-images.githubusercontent.com/13248542/147865178-3d0f19a1-6f19-45ef-9c48-53be77431b76.mov

 

### How can we reproduce the bug on our side?

This can be demonstrated using the react custom node view contenteditable example - https://tiptap.dev/guide/node-views/react#adding-a-content-editable. 

### What did you expect to happen?

The double click should select the line on a double click the same as if the view had been rendered using a regular contenteditable. This behavior is seen in the Vue Custom Node View example. 

https://user-images.githubusercontent.com/13248542/147865182-bb03ff99-fdfb-4f23-b7d3-f7754e31f5e1.mov

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Strange. This also seems to happen only in Firefox.

**Comment by TheSociologist** [comment]
Just tried it out on Chrome, the cursor doesn't jump but it still doesn't select the text until the third consecutive click just like on Firefox. 

Do you have any ideas on what could be causing this? Definitely interested in contributing a solution but I'm not sure where to get started.

Would manually handling this behavior through event listeners (double click) be a good idea?
