### ISSUE TITLE
toggleBulletList in nested divs

### ISSUE THREAD

**Issue by rezaffm** [ueberdosis/tiptap#2344]
### What’s the bug you are facing?

If I have three paragraphs like:

```html
<p>Test</p><p>Test</p><p>Test</p>
```

I can toggle these to unordered lists (uls) easily by using the following command

```javascript
this.editor.chain().focus().toggleBulletList().run()
```

However, once I have the same paragraphs in a div like:

```html
<div class="alert-info"><p>Test</p><p>Test</p><p>Test</p></div>
```

I get the following error, using the same command:

![image](https://user-images.githubusercontent.com/40648929/147928496-d18ae11d-fea5-422f-b6c9-103a4ac80eae.png)

However, I noticed, when I use

```javascript
this.editor.commands.wrapInList('bulletList')
```

it works as expected. But then I use the functionality to undo the list.

Either I am too stupid to get this working or the toggleBulletList command needs some adjustments.

### How can we reproduce the bug on our side?

I am happy to create a sandbox but I believe with the given informaiton you can easily recreate this bug.

That's my extension for the "divs":

```javascript
import { Node, mergeAttributes } from '@tiptap/core';

const Div = Node.create({
    name: 'div',
    addOptions() {
        return {
          HTMLAttributes: {},
        };
    },
    content: 'block*',
    group: 'block',
    defining: true,
    parseHTML() {
        return [
            { tag: 'div' },
        ];
    },
    renderHTML({ HTMLAttributes }) {
        return ['div', mergeAttributes(this.options.HTMLAttributes, HTMLAttributes), 0];
    },
    addCommands() {
        return {
            setDiv: (attributes) => ({ commands }) => {
                return commands.wrapIn('div', attributes);
            },
            toggleDiv: (attributes) => ({ commands }) => {
                return commands.toggleWrap('div', attributes);
            },
            unsetDiv: (attributes) => ({ commands }) => {
                return commands.lift('div');
            },
        };
    },
    onUpdate() {
      const classes = ['table-responsive', 'aspect-w-16 aspect-h-9', 'resp-container']
      const transaction = this.editor.state.tr
      let needsToWrapTables = false

      this.editor.state.doc.descendants((node, pos) => {
        if (node.type.name === 'div' && node.firstChild !== null) {
          if (node.firstChild.type.name !== 'table') return;
          if (node.attrs.class == null) {
            needsToWrapTables = true
            transaction.setNodeMarkup(pos, undefined, {
              ...node.attrs,
              class: 'table-responsive'
              })
            return true
          }
        }
        return false
      })

      if (needsToWrapTables) {
        transaction.setMeta('preventUpdate', true)
        this.editor.view.dispatch(transaction)
        transaction.setMeta('preventUpdate', false)
      }

      this.editor.state.doc.descendants((node, pos) => {
        if (node.type.name === 'div' && classes.includes(node.attrs.class)) {

          if (node.firstChild !== null && node.content.lastChild.type.name == 'paragraph') {
            transaction.replaceWith(pos, pos + node.nodeSize, node.content.lastChild)
            this.editor.view.dispatch(transaction)
            return true
          }

          if (node.firstChild !== null && node.firstChild.type.name == 'paragraph') {
            transaction.replaceWith(pos, pos + node.nodeSize, node.content)
            this.editor.view.dispatch(transaction)
            return true
          }

          if (node.childCount == 0) {
            transaction.deleteRange(pos, pos + node.nodeSize)
            this.editor.view.dispatch(transaction)
            return true
          }
          return false
        }
      })
    }
});

export default Div;
export { Div };

```

### Can you provide a CodeSandbox?

If wanted, happy to do so.

### What did you expect to happen?

It would be great if the toggling of the ordered (and unordered) list would work also when the paragraphs are in divs.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
In a quick test I can’t reproduce this. Can you please create a codesandbox for it?

**Comment by rezaffm** [comment]
well, I actually created a sandbox with a minimum version of our editor: https://codesandbox.io/s/editor-sandbox-pj3ki

...and guess what? I noticed in the sandbox it works as expected.

I then checked for differences in current versions, and it seems (again) I lost track of updating dependencies.

![image](https://user-images.githubusercontent.com/40648929/147936261-c2685a15-142d-4286-9011-6ff656f6b779.png)

After I updated all dependencies, it  works again as expected.

**Comment by philippkuehn** [comment]
Great!

**Comment by rezaffm** [comment]
Hi, sorry, I cannot really explain why, but it seems like the issue is back.

If you visit: https://codesandbox.io/s/editor-sandbox-pj3ki

When you then create a simple list, e.g.:

```html
<ul><li><p>Test1</p></li><li><p>Test2</p></li><li><p>Test3</p></li></ul>
````

and then you try to wrap it in a div (you can pick whatever div you like, e.g. "Summary Box", it basically does nothing, also no error message is shown in console.

**Comment by rezaffm** [comment]
...just adding to this.

If you have the following, then wrapping and unwrapping works:

```javascript
<div class="summary-box"><p>Test</p><ul><li><p>Test1</p></li><li><p>Test2</p></li><li><p>Test3</p></li></ul></div>
```

It seems like it is somehow related to the "list structure"
