### ISSUE TITLE
Cannot add number in the front of heading text

### ISSUE THREAD

**Issue by tuan3w** [ueberdosis/tiptap#2348]
### What’s the bug you are facing?

You can't type number in the front of a heading text.

### How can we reproduce the bug on our side?

Step 1: Visit https://tiptap.dev/ and open the editor
Step 2: Add a H1 text '# 1. Some text'
Step 3: The output: 'Some text'

### What did you expect to happen?

The output should be '1. Some text'.

### Anything to add? (optional)

I think the root problem is a bug in  `wrappingInputRule` function. The matched text range is deleted but isn't recover correctly when we can't wrap the new element into the parent node.
https://github.com/ueberdosis/tiptap/blob/e07a5b625d90c77fc5820e5eefa093d3cfb96512/packages/core/src/inputRules/wrappingInputRule.ts#L41-L43
Some solutions:
- Recover the deleted range
- Only apply the input rules that have transactions like in the merge: https://github.com/ueberdosis/tiptap/pull/2225
Personal, I think the second approach is better because may not know what actions are needed to reverse the old actions.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Ah, this is indeed the issue described in #2225. I’ll try to find a solution.
