### ISSUE TITLE
How to render a empty text

### ISSUE THREAD

**Issue by adou2236** [ueberdosis/tiptap#2353]
### What’s the bug you are facing?

if i have a empty text node,the whole page can not render

### How can we reproduce the bug on our side?

a

### What did you expect to happen?

a

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by hanspagel** [comment]
Can’t reproduce "a". 🙃

**Comment by adou2236** [comment]
it warning "Empty text nodes are not allowed",i want igore it rather than throw an error

**Comment by philippkuehn** [comment]
This is not supported by ProseMirror. You have to remove these empty nodes.

**Comment by adou2236** [comment]
> This is not supported by ProseMirror. You have to remove these empty nodes.

ok,thank you
