### ISSUE TITLE
Table Placeholders

### ISSUE THREAD

**Issue by thefinnomenon** [ueberdosis/tiptap#2356]
### What problem are you facing?

I am using the table extension and can't figure out how to set placeholders for the headers and cells. I am using the placeholder extension but the node types show as `paragraph` so I can't distinguish table cells in order to properly set the placeholder.

### What’s the solution you would like to see?

Add an attribute to the `th` and `tr` paragraph nodes so I can properly identify them in the placeholder extension. 

### What alternatives did you consider?

I haven't been able to find an alternative.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by cadars** [comment]
The placeholder text is ultimately displayed with CSS:
```css
p.is-editor-empty:first-child::before {
    content: attr(data-placeholder);
}
```
so I guess you could overwrite it like this?
```css
td p.is-editor-empty:first-child::before {
    content: "placeholder text for table cells";
}

**Comment by thefinnomenon** [comment]
Thanks @cadars, didn’t know that! I had tried targeting empty but it didn’t work since the content is never really empty. I’ll try it when I get back to my laptop.

**Comment by cadars** [comment]
You might need to use a different CSS selector, maybe `td p br.ProseMirror-trailingBreak::before`, knowing that an empty cell markup looks like this:
```html
<td>
  <p><br class="ProseMirror-trailingBreak"></p>
</td>

**Comment by thefinnomenon** [comment]
@cadars Unfortunately it isn't working because the `is-empty` class is not being properly set on the table's paragraph elements.

<img width="367" alt="Screen Shot 2022-01-06 at 4 20 56 PM" src="https://user-images.githubusercontent.com/3837369/148454012-ca4d307e-8172-4152-b0e9-7598c96d7801.png">

**Comment by thefinnomenon** [comment]
Whoops nevermind, just realized I needed to set `includeChildren: true`. Thanks!
