### ISSUE TITLE
editor.onUpdate not called after editor.commands.setContent

### ISSUE THREAD

**Issue by justinmoon** [ueberdosis/tiptap#2359]
### What’s the bug you are facing?

Title fully describes it

### How can we reproduce the bug on our side?

Run [this repo](https://github.com/justinmoon/tiptap-markdown-demo) and comment out [line 193](https://github.com/justinmoon/tiptap-markdown-demo/blob/5c0697d63738c796fab01f8bfeba7e1facd7d19b/src/Tiptap.jsx#L193), then paste some markdown into the <textarea/> labeled "Markdown → TipTap". It will show up in the "TipTap editor" area but not in the "TipTap → Markdown" which is set by `onUpdate`. If that line isn't commented out, it will show up in "TipTap → Markdown".

### Can you provide a CodeSandbox?

https://codesandbox.io/s/vigorous-frost-u15wg

### What did you expect to happen?

`editor.onUpdate` should always be called after TipTap state changes.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
There is an `emitUpdate` option for this command.

https://tiptap.dev/api/commands/set-content
