### ISSUE TITLE
Demo is resource intensive (crashes mobile browser)

### ISSUE THREAD

**Issue by mathieuprog** [ueberdosis/tiptap#2360]
### What’s the bug you are facing?

The demo is very slow to load and may not respond for a while on a mobile device (using a Google Pixel 3).
![Screenshot_20220107-112757](https://user-images.githubusercontent.com/5883963/148491851-23eaf94d-4a06-4dfc-84ba-8dcaa6d2bd05.png)

### How can we reproduce the bug on our side?

View demo on a mobile device here:
https://tiptap.dev/examples/default

### What did you expect to happen?

Smooth experience

**Comment by hanspagel** [comment]
That’s an issue with Android Chrome and the syntax highlighting and even occurs here on GitHub with larger code blocks. I don’t think we can do anything about it (except removing the code or the syntax highlighting).
