### ISSUE TITLE
Ability to get Node position?

### ISSUE THREAD

**Issue by zacharykatsnelson** [ueberdosis/tiptap#2365]
### What problem are you facing?

I want to have a title at all times within the document where I can apply the placeholder and [enforce](https://stackoverflow.com/questions/67358648/how-to-enforce-first-node-to-be-heading-h1-in-tiptap-editor) it's type. This title would only be on the very first node of the document.

### What’s the solution you would like to see?

I would like it to be possible to get the position of the node. The reason why this could be useful is for several use cases. For instance, in the [Force a Title example](https://tiptap.dev/examples/custom-document) we can make the placeholder return "Enter a title" if it is an **H1** but this also does this for _all other_ H1 Headers. 

Instead with node position you could do something like this: 
```
Placeholder.configure({
        placeholder: ({ node }) => {
          if (node.type.name === 'heading' && node.position === 0) {
//I.e. ensuring that this only applies to the very first line, then
            return 'Enter a title...';
          }
          return 'Further context...';
        },
      }),

```
This could also be helpful for those who want to enforce the initial text to be a certain way (an H1).

### What alternatives did you consider?

Combining two editors into one...
So the top editor concatenates with the bottom editor; however the top editor only has the ability to write headers.
I'm not sure if this will work, and it would probably be too ugly of a solution even if it did :sweat_smile:  

### Are you sponsoring us?

- [x] Yes, I’m a sponsor. 💖

**Comment by zacharykatsnelson** [comment]
I've found that just creating multiple editors actually solves all the problems quite elegeantly.
For anyone who might come across such a problem where they want to enforce a title, just create a seperate component called Title.tsx and give it properties like this: 
```
const TitleDocument = Document.extend({
  content: 'heading',
});

const Title = () => {
  const editor = useEditor({
    extensions: [
      TitleDocument,
      Heading.configure({
        levels: [1],
      }),
      Text,
      Placeholder.configure({
        placeholder: ({ node }) => {
          const headingPlaceholders = {
            1: 'Enter a title...',
          };
          if (node.type.name === 'heading') {
            // @ts-ignore
            return headingPlaceholders[node.attrs.level];
          }
          return '';
        },
      }),
    ],
```

Than you can just put it right on top of the main editor you have set up :grin:

**Comment by aliasmac** [comment]
@zacharykatsnelson trying to solve the same problem, the issue with having 2 instances of the editor is that I can' then press enter to move the cursor to the next line, did you also have this issue?

**Comment by shu8** [comment]
Just wanted to add another potential solution (which is still slightly hacky IMO, but it works for me), which is to just check if the editor contents starts with `<h1></h1>`, like this:

```
Placeholder.configure({
	placeholder: ({ node, editor }) => {
		if (node.type.name === 'heading' && editor.getHTML().startsWith('<h1></h1>')) {
			return "What's the title?";
		}

		return '';
	}
})
```

`.startsWith` is important if you want the placeholder to show if the user edits the title after already writing content in the rest of the doc. You could change it to `===` if you only want the placeholder to show at the very beginning when the doc is empty.
