### ISSUE TITLE
CodeBlock Lowlight loses styling when rendering HTML

### ISSUE THREAD

**Issue by thefinnomenon** [ueberdosis/tiptap#2371]
### What’s the bug you are facing?

The codeblock-lowlight extension works perfectly in the editor but when I render the editor contents as HTML, it changes the code content to plain html text.

<img width="439" alt="Screen Shot 2022-01-10 at 3 12 17 PM" src="https://user-images.githubusercontent.com/3837369/148836219-bbad8c30-318f-4d37-b748-c96b7b033bc4.png">
<img width="433" alt="Screen Shot 2022-01-10 at 3 12 29 PM" src="https://user-images.githubusercontent.com/3837369/148836232-daf4c2ed-309c-4d34-a75c-c1658b0575c2.png">

### How can we reproduce the bug on our side?

Use the normal setup from the docs and render the editor output as HTML.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/dazzling-nash-mledg

### What did you expect to happen?

I expect the styling to be present on the HTML output.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by hanspagel** [comment]
That’s actually intended. Tiptap stores the structured and semantic content, not the representation.

You can use Tiptap in read-only mode if you’d like to have the same rendering, or take care of the rendering yourself (for example with lowlight, or whatever library fits your requirements).

**Comment by thefinnomenon** [comment]
@hanspagel Ahh okay, thanks, that makes sense. I will just load lowlight on my page to handle the rendering.

**Comment by Dellysn** [comment]
> https://codesandbox.io/s/dazzling-nash-mledg

how did you resolve this issue @thefinnomenon

**Comment by thefinnomenon** [comment]
@Dellysn Sorry, I don't 100% remember at this point but I open sourced my project if you want to look through the code.
https://github.com/thefinnomenon/creatorkitchen/blob/main/components/TipTap.tsx

**Comment by Dellysn** [comment]
Thank you.
I will go through the code

**Comment by Dellysn** [comment]
Is the app live?

**Comment by kamalesh-d** [comment]
I had the similar problem, and solved it like this:

```
    const codeTag = document.getElementsByTagName("code");
    for (let i = 0; i < codeTag.length; i++) {
      const element = codeTag[i];
      element.classList.add('language-html');
    }
    const hljs = require('highlight.js');
    hljs.highlightAll();
```
Basically, while rendering the html content from tiptap, I am fetching all the Tags with <code>, and appending the 'language-html' class to it. Then I am importing highlightjs and enabling the code highlight. These informations can be referred from highlight.js [github](https://github.com/highlightjs/highlight.js/) page.

Additional tip: I am working with vue, so I was using a single component reused everywhere whenever I render the html content from tiptap. So, I just have to write this code once, and always the code is displayed appropriately with highlighted.  So consider reusing the code in your preferred framework. 

Hope this helps!

**Comment by alexjbush** [comment]
You can make it render using `renderHTML` on server-side (SSR using SvelteKit in this case) or not with something like the following:
```typescript
import { createHTMLDocument } from 'zeed-dom'
import hljs from 'highlight.js'
import { browser } from "$app/environment";

CodeBlockLowlight.configure({
        lowlight,
    }).extend({
        renderHTML({ node, HTMLAttributes }) {
            let gen = hljs.highlight(node.textContent, { language: node.attrs.language }).value
            let doc = browser ? document : createHTMLDocument();
            let pre = doc.createElement('pre')
            let preAttrs = mergeAttributes(this.options.HTMLAttributes, HTMLAttributes)
            for (let key in preAttrs) {
                pre.setAttribute(key, preAttrs[key])
            }
            let code = doc.createElement('code')
            if (node.attrs.language) {
                code.classList.add(this.options.languageClassPrefix + node.attrs.language)
            }
            // @ts-nocheck
            pre.appendChild(code)
            code.innerHTML = gen
            return pre as HTMLElement
        }
    })]
```

**Comment by half0wl** [comment]
Here's how I did it:

```typescript
export const CodeBlock = CodeBlockLowlight.extend({
  addNodeView() {
    return ReactNodeViewRenderer(CodeBlockComponent);
  },

  renderHTML({ node, HTMLAttributes }) {
    const highlighted = node.attrs.language
      ? lowlight.highlight(node.attrs.language, node.textContent)
      : lowlight.highlightAuto(node.textContent);
    const html = toHtml(highlighted); // https://github.com/syntax-tree/hast-util-to-html

    return [
      "div",
      { class: codeBlockClassNames },
      ["pre", HTMLAttributes, ["code", { html }]],
    ];
  },
}).configure({ lowlight });
```

This solution doesn't require you to have access to the DOM so it works in server-rendering natively, and lets you re-use lowlight (without hljs).

**Comment by zszepczynski** [comment]
@alexjbush your solution makes pre element contenteditable=false and I'm unable to edit it in the editor. How did you workaround it?
@half0wl It doesn't seem to work in my case. What is CodeBlockComponent? I'm getting error when passing { html } to code attribute (something with invalid spec)

**Comment by half0wl** [comment]
> [@alexjbush](https://github.com/alexjbush) your solution makes pre element contenteditable=false and I'm unable to edit it in the editor. How did you workaround it? [@half0wl](https://github.com/half0wl) It doesn't seem to work in my case. What is CodeBlockComponent? I'm getting error when passing { html } to code attribute (something with invalid spec)

This is my full code:

```typescript
// src/components/tiptap/nodes/code-block.tsx
import CodeBlockLowlight from "@tiptap/extension-code-block-lowlight";
import {
  NodeViewContent,
  NodeViewWrapper,
  ReactNodeViewRenderer,
} from "@tiptap/react";
import { toHtml } from "hast-util-to-html";
import { common, createLowlight } from "lowlight";
import { VStack } from "@/components/ui/stack";

const lowlight = createLowlight(common);
const lowlightLangs = lowlight.listLanguages();
const isSupportedLang = (lang: string) =>
  lowlightLangs.includes(lang) || lowlight.registered(lang);

const codeBlockClassNames =
  "codeblock relative rounded-md border border-gray-100 p-3 text-sm text-gray-800!important overflow-y-auto";

const CodeBlockComponent = () => {
  return (
    <NodeViewWrapper className={codeBlockClassNames}>
      <VStack>
        <pre>
          <NodeViewContent as="code" />
        </pre>
      </VStack>
    </NodeViewWrapper>
  );
};

export const CodeBlock = CodeBlockLowlight.extend({
  addNodeView() {
    return ReactNodeViewRenderer(CodeBlockComponent);
  },

  renderHTML({ node, HTMLAttributes }) {
    const lang = node.attrs.language;
    const highlighted = isSupportedLang(lang)
      ? lowlight.highlight(lang, node.textContent)
      : lowlight.highlightAuto(node.textContent);
    const html = toHtml(highlighted);

    return [
      "div",
      { class: codeBlockClassNames },
      ["pre", HTMLAttributes, ["code", { html }]],
    ];
  },
}).configure({ lowlight });
```

Hope it helps!

**Comment by amirrezabahramy** [comment]
I've found a very clean way:

```ts

import { toHtml } from "hast-util-to-html";
import { all, createLowlight } from "lowlight";

const lowlight = createLowlight(all);

function highlightHTMLWithLowlight(html: string): string {
  if (typeof window === "undefined") return html;

  const parser = new DOMParser();
  const doc = parser.parseFromString(html, "text/html");

  const codeBlocks = doc.querySelectorAll("pre code");

  codeBlocks.forEach((code) => {
    const className = code.className || "";
    const match = className.match(/language-(\w+)/);
    const language = match?.[1];

    const text = code.textContent || "";

    let tree;

    try {
      tree = language
        ? lowlight.highlight(language, text)
        : lowlight.highlightAuto(text);
    } catch {
      return;
    }

    const highlighted = toHtml(tree);

    code.innerHTML = highlighted;
  });

  return doc.body.innerHTML;
}

const extensions = [
  StarterKit.configure({ codeBlock: false }),
  TextStyleKit,
  Placeholder.configure({ placeholder: "Start writing your article..." }),
  TextAlign.configure({
    types: ["heading", "paragraph"],
  }),
  CodeBlockLowlight.configure({
    lowlight,
    enableTabIndentation: true,
  }),
];
```


And the content is passed to the Preview component this way:

```ts
import { generateHTML } from "@tiptap/react";

const [previewState, setPreviewState] = useState({
    open: false,
    editorResult: {},
  });

<PreviewComponent
          onCloseAction={() => setPreviewState((prev) => ({ ...prev, open: false }))}
          isOpen={previewState.open}
          content={highlightHTMLWithLowlight(
            generateHTML(previewState.editorResult, extensions),
          )}
/>
```

`previewState.editorResult` is the result of `editor.getJSON()`. If you use `editor.getHTML()`, You can skip wrapping the result with `generateHTML` function. Below is the example code.

```ts
const [previewState, setPreviewState] = useState({
    open: false,
    editorResult: "",
  });

<PreviewComponent
          onCloseAction={() => setPreviewState((prev) => ({ ...prev, open: false }))}
          isOpen={previewState.open}
          content={highlightHTMLWithLowlight(previewState.editorResult)}
/>
```
