### ISSUE TITLE
Error when check taskItem

### ISSUE THREAD

**Issue by Morgbn** [ueberdosis/tiptap#2372]
### What’s the bug you are facing?

An error occurs when trying to check/uncheck a task item : 
`Uncaught RangeError: Index 1 out of range for <taskList(taskItem(paragraph("A list item")), taskItem(paragraph("And another one")))>`
getPos() return undefined in [task-item.ts#L123](https://github.com/ueberdosis/tiptap/blob/main/packages/extension-task-item/src/task-item.ts#L123)

### How can we reproduce the bug on our side?

Try this [doc example](https://tiptap.dev/api/nodes/task-item#usage).

### What did you expect to happen?

Being able to check / uncheck a task.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Sorry, but I can’t reproduce this in Chrome, Firefox or Safari 🤷‍♂️

**Comment by Morgbn** [comment]
Very weird 🤔. I use Chrome (Version 97.0.4692.71 (Build officiel) (64 bits)), no problem in private navigation, but otherwise :

https://user-images.githubusercontent.com/25689856/148923133-42ddfc78-0481-4012-8898-00c5874eb342.mp4

the pull request fixes my issue

**Comment by philippkuehn** [comment]
Maybe it’s one of your browser extensions then.

**Comment by Morgbn** [comment]
Yes, definitely, in my case it's the Bitwarden extension that in cause. It may interfere with the prosemirror function `getPos` 🤔

**Comment by philippkuehn** [comment]
If it’s this extension we can’t do anything here. ProseMirror does not work well with extensions that hook into contenteditable.
