### ISSUE TITLE
[@tiptap/extension-link] import error

### ISSUE THREAD

**Issue by Akashs991** [ueberdosis/tiptap#2375]
### What’s the bug you are facing?

When using @tiptap/extension-link error is thrown on import of Link

`
﻿
tiptap-extension-link.esm.js:1 Uncaught SyntaxError: The requested module '../../../../../node_modules/@tiptap/core/dist/tiptap-core.esm.js' does not provide an export named 'combineTransactionSteps'`

@tiptap/extension-link@2.0.0-beta.35

### How can we reproduce the bug on our side?

Add below import

import Link from '@tiptap/extension-link';

Check browser console for the error.

### What did you expect to happen?

Dependencies should be resolved without any error.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
You have to update `@tiptap/core`
