### ISSUE TITLE
The placeholder extension is not updated until the second change occurs

### ISSUE THREAD

**Issue by sh-winter** [ueberdosis/tiptap#2379]
### What’s the bug you are facing?

When the editor gets the focus, click the center button, and the placeholder will not be in real time

### How can we reproduce the bug on our side?

[click me](https://codesandbox.io/s/frosty-tamas-ddjkr?file=/src/App.vue)

### What did you expect to happen?

Placeholder real-time update

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Using `@click` instead of `@mousedown.prevent` on your button fixes the issue.
