### ISSUE TITLE
Tiptap on Vue 3 takes too long to create

### ISSUE THREAD

**Issue by cnicodeme** [ueberdosis/tiptap#2382]
### What’s the bug you are facing?

Hi!

I'm migrating from Vue 2 to Vue 3 and as part of the migration process, I'm upgrading TipTap to match the new Vue 3.

Now, opening a new page that contains an editor takes about 2/3 seconds to load. It is specifically the editor that takes that time.

I tried reproducing the issue, and the following code reproduces it - at least on my end.

I've removed many of the extensions and if I only keep `Document, Paragraph, Text`, it still takes ~3 seconds to load.

### How can we reproduce the bug on our side?

```
import { Editor, EditorContent } from '@tiptap/vue-3'

import Document from '@tiptap/extension-document'
import Paragraph from '@/components/editor/extensions/Paragraph'
import Text from '@tiptap/extension-text'

import Bold from '@tiptap/extension-bold'
import Italic from '@tiptap/extension-italic'
import Underline from '@tiptap/extension-underline'
import Strike from '@tiptap/extension-strike'

export default {
    data () {
        return {
            editor: null
        }
    },
    created () {
        setTimeout(() => {
            console.time('editor')
            this.editor = new Editor({
                extensions: [
                    Document,
                    Paragraph,
                    Text,
                    Bold,
                    Italic,
                    Underline,
                    Strike
                ],
                onBeforeCreate () {
                    console.log('before create')
                },
                onCreate () {
                    console.timeEnd('editor')
                }
            })
            console.log('process done')
        })
    },
    ...
}
```

Here's the output in the console:

> before create
> process done
> editor: 3047.726318359375 ms (the timer)

### What did you expect to happen?

The editor should load in a few ms (around 200ms in normal condition from what I've seen) but instead takes about 3000ms to load, which is abnormal

## Versions

Chrome 95.0.4638.69 (Build officiel) (64 bits)
Vue: 3.2.26

Tiptap:

    "@tiptap/core": "^2.0.0-beta.162",
    "@tiptap/extension-blockquote": "^2.0.0-beta.26",
    "@tiptap/extension-bold": "^2.0.0-beta.25",
    "@tiptap/extension-bullet-list": "^2.0.0-beta.26",
    "@tiptap/extension-code": "^2.0.0-beta.26",
    "@tiptap/extension-code-block": "^2.0.0-beta.35",
    "@tiptap/extension-document": "^2.0.0-beta.15",
    "@tiptap/extension-dropcursor": "^2.0.0-beta.25",
    "@tiptap/extension-gapcursor": "^2.0.0-beta.34",
    "@tiptap/extension-history": "^2.0.0-beta.21",
    "@tiptap/extension-image": "^2.0.0-beta.24",
    "@tiptap/extension-italic": "^2.0.0-beta.25",
    "@tiptap/extension-link": "^2.0.0-beta.35",
    "@tiptap/extension-list-item": "^2.0.0-beta.20",
    "@tiptap/extension-mention": "^2.0.0-beta.91",
    "@tiptap/extension-ordered-list": "^2.0.0-beta.27",
    "@tiptap/extension-paragraph": "^2.0.0-beta.23",
    "@tiptap/extension-strike": "^2.0.0-beta.27",
    "@tiptap/extension-text": "^2.0.0-beta.15",
    "@tiptap/extension-typography": "^2.0.0-beta.19",
    "@tiptap/extension-underline": "^2.0.0-beta.22",
    "@tiptap/starter-kit": "^2.0.0-beta.170",
    "@tiptap/vue-3": "^2.0.0-beta.88",

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by cnicodeme** [comment]
The wrapping in `setTimeout` ensure the page doesn't freeze when creating the editor, allowing the rest of the page to be loaded.

**Comment by philippkuehn** [comment]
I can’t reproduce this in any of your demos or in the [codesandbox starter template](https://codesandbox.io/s/tiptap-vue-3-issue-template-tnlpv?file=/src/App.vue) (all based on vue 3). So something seems so be wrong with your setup. Feel free to re-open if you are able to create a reproducable codesandbox.

**Comment by cnicodeme** [comment]
:o that was fast! I'll see if I can find how to reproduce it! Thank you
