### ISSUE TITLE
Suggestions doesn't work when "char" contains a word because of specific chars

### ISSUE THREAD

**Issue by cnicodeme** [ueberdosis/tiptap#2385]
### What’s the bug you are facing?

I'm trying to make the Mention/suggestion system work when calling "/article" but it doesn't trigger the onStart method.

I noticed that this is caused by a few chars in the "char" property that doesn't work.

For instance, if you include "n", "r", "t", "c" in the char, for some reason, the trigger stop working.

### How can we reproduce the bug on our side?

Here's a sample:

https://codesandbox.io/s/loving-kalam-wyw6b?file=/src/App.vue

### What did you expect to happen?

It should show the "on start" in the console when the full "/article" is written. Instead, it doesn't do anything.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
should be fixed in the latest release!

**Comment by cnicodeme** [comment]
Thanks for the fast response. Latest as "already published" or "soon to be published"? ;)
