### ISSUE TITLE
Node's attributes only updating on hover

### ISSUE THREAD

**Issue by maguirekrist** [ueberdosis/tiptap#2386]
### What’s the bug you are facing?

I've managed to write some code that updates attributes for a specific node(s). However, there seems to be an issue with how to doc is recognizing these changes, for, these changes are not reflected in the node's view until I hover over the node itself. 

### How can we reproduce the bug on our side?

Using react, you can see this bug in action by created a new react extension, in the react component referencing a attribute in jsx for display, then try this code....

`
editor?.state.doc.forEach(node => {
        node.content.forEach(ele => {
          if(ele.attrs["fieldName"] == props.item?.fieldName) {
            ele.attrs = item;
            editor.state.apply(editor.state.tr);
    }
  });
});
`

### What did you expect to happen?

I expect that the nodes would reflect the attributes when they are being referenced as a visual property, i.e. I am referencing the "fieldName" attribute in the nodes text content. 

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
It’s not allowed to mutate nodes. You have to use commands/transactions for it.
