### ISSUE TITLE
Endless loop when calling updateAttributes inside mounted/created in Vue

### ISSUE THREAD

**Issue by tuanalumi** [ueberdosis/tiptap#2387]
### What’s the bug you are facing?

I am following this example: https://tiptap.dev/guide/node-views/vue#access-node-attributes, with a little modification that I will update the `count` inside `created`/`mounted`. But there is an endless loop of rendering the component, even if there is a check for `count` value.

If I uncomment `setTimeout` in `HelloWorld.vue`, it works fine.

### How can we reproduce the bug on our side?

Check the CodeSandBox link.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/festive-lovelace-emr8n?file=/src/components/HelloWorld.vue

### What did you expect to happen?

This should update the node attributes and re-render the component once, without using `setTimeout` (just like what it does in `increase` method)

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by hanspagel** [comment]
Does what you expect on Android Chrome. Any info about the browser you are using?

**Comment by tuanalumi** [comment]
Ah, I am sorry. I forgot the part about `setTimeout`. Updated the description.

**Comment by tuanalumi** [comment]
bump

**Comment by tuanalumi** [comment]
not stale
