### ISSUE TITLE
Pasted headline becomes bold

### ISSUE THREAD

**Issue by felix-berlin** [ueberdosis/tiptap#2389]
### What’s the bug you are facing?

When i paste a copied headline from else where the headline is not only formatted as headline she also becomes bold.

### How can we reproduce the bug on our side?

Not a CodeSandbox but your own docu page:

https://tiptap.dev/examples/default

Copy the H1 headline on the page and paste it to the editor below.

### What did you expect to happen?

I expect the copied headline to be formatted as a headline only. Not additionally bold.

### Anything to add? (optional)

https://user-images.githubusercontent.com/17964384/149550725-5ceeab00-eac3-4322-b9e2-1745b69b5802.mov

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by cadars** [comment]
This comes from ProseMirror I think, the demo on their website behaves the same.

As a workaround you can extend the Heading extension and specify which marks are allowed in headings:
`marks: 'italic link … ',`

**Comment by hanspagel** [comment]
You can disallow marks in headings like this:

```js
Heading.extend({
  marks: ''
})
```

https://tiptap.dev/api/schema#marks

**Comment by felix-berlin** [comment]
Thank you guys for your suggestions. But this is't exactly what i'm looking for. When i disallow all marks, I'm not able to format the headings after pasting.

I'm only want to change this pasting behavior. Maybe there is an pasting rule a something similar?

**Comment by hanspagel** [comment]
By default, pasted headings aren’t inserted as bold, so that’s specific to the content you’re copying.

If you want to hook into the pasting, look at `editorProps` and `handlePaste`:
https://tiptap.dev/api/editor#editor-props
https://prosemirror.net/docs/ref/#view.EditorProps.handlePaste
