### ISSUE TITLE
Multiple BubbleMenu documentation

### ISSUE THREAD

**Issue by mackmm145** [ueberdosis/tiptap#2392]
### What’s the URL to the page you’re sending feedback for?

https://tiptap.dev/api/extensions/bubble-menu

### What part of the documentation needs improvement?

under #multiple menus it shows the adding of two BubbleMenu extensions using different pluginKeys and elements. 

### What is helpful about that part?

Configuration seems dead simple once I realized that I needed to use the extension version of BubbleMenu instead of the one included with the StarterKit.

### What is hard to understand, missing or misleading?

i'm lost on how to render them.

I'm working with Vue3. I've tried created two <bubble-menu> tags with different ids set, but they don't show when they should. It'll show if I use just a single bubbleMenu ( with div's inside to control what shows under what node types).

Would someone be able to point me towards how the rendering/template side should be structured?

**Comment by mackmm145** [comment]
my apologies. i've have figured it out and realized that i needed to create an component based off the extension.

**Comment by kongweiying2** [comment]
@mackmm145 I'm running into the same problem, can you share the code you used to get this working?

**Comment by mackmm145** [comment]
@kongweiying2 here's the snippet of the bubblemenus ended up adding. 

https://gist.github.com/mackmm145/32e07de8a552d686a6290830548e61a4

hope it helps.
