### ISSUE TITLE
CollaborationCursor not working

### ISSUE THREAD

**Issue by steFanBzh** [ueberdosis/tiptap#2395]
### What’s the bug you are facing?

Hello guys, first of all I want to congratulate you on the great product and the amazing work you have done on it. Impressive!
In my case, unfortunately, the collaboration cursor doesn't work. Gives the following error in the mounted hook: 
[Vue warn]: Error in mounted hook: "TypeError: this.storage is undefined"
and chrome is loging: 
[Vue warn]: Error in mounted hook: "TypeError: Cannot set properties of undefined (setting 'users')"
Тhis is an error in tiptap-extension-collaboration-cursor.esm.js:63
'this.storage.users = awarenessStatesToArray(this.options.provider.awareness.states);'

If I set the storage manualy like:
yCursorPlugin((() => {
        **let storage = [ ]**
        this.options.provider.awareness.setLocalStateField('user', this.options.user)
        **storage.users** = awarenessStatesToArray(this.options.provider.awareness.states)
        this.options.provider.awareness.on('update', () => {
          **storage.users** = awarenessStatesToArray(this.options.provider.awareness.states)
      })
   return this.options.provider.awareness
})(),

then i get the following error: Error in mounted hook: **"TypeError: ystate is undefined"**
this is coming from webpack:///node_modules/y-prosemirror/src/plugins/cursor-plugin.js?bbe7

export const createDecorations = (state, awareness, createCursor) => {
  **const ystate = ySyncPluginKey.getState(state)**
  const y = ystate.doc

I am using following setup:

import Collaboration from '@tiptap/extension-collaboration'
import CollaborationCursor from '@tiptap/extension-collaboration-cursor'
import { WebsocketProvider } from 'y-websocket'
import * as Y from 'yjs'

mounted () {
      const user = {
        name: this.account.email,
        color: this.getRandomColor()
      }
      this.ydoc = new Y.Doc()
      const url = 'ws://localhost:8085'
      const room = 'some test room'
      const provider = new WebsocketProvider(url, room, this.ydoc, { params: { some params } })
      this.provider = provider
      const editor = new Editor({
        extensions: [
          Collaboration.configure({
            document: this.ydoc,
            field: 'doc'
          }),
          CollaborationCursor.configure({
            provider: provider,
            user: user
          }),
          StarterKit.configure({
            history: false
          }),
etc...

I am using vue-2
Do you have any idea why this is happening?
Many thanks in advance!

### How can we reproduce the bug on our side?

Like in the description above

### Can you provide a CodeSandbox?

at the moment no

### What did you expect to happen?

working cursor

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
You should update your tiptap packages to the latest version.

**Comment by steFanBzh** [comment]
Well that's where I started. Everything is updated to the latest version. Any guesses? Sorry to bother you, but I'm not making any progress here...

**Comment by hanspagel** [comment]
Remove node_modules and run npm install again

**Comment by steFanBzh** [comment]
Great! It worked...now error is gone and editor.storage is there...I still don't see the cursor but I am sure this is a quick fix. Many thanks!

**Comment by hanspagel** [comment]
Don’t forget to add the CSS as shown in the docs.

https://gist.github.com/mackmm145/f100a62de841464872785e3d041be13f

**Comment by steFanBzh** [comment]
Brilliant, everything works. The problem was in forgotten code from a previous bug fix attempt. By the way, I am very happy with the render function, which gives de facto endless possibilities for customization. You're great!
