### ISSUE TITLE
UniqueId extension doesn't trigger on paste

### ISSUE THREAD

**Issue by tekacs** [ueberdosis/tiptap#2398]
### What’s the bug you are facing?

The UniqueId extension often requires some perturbation in order to cause it to generate IDs.

For example, pasting content triggers this issue.

### How can we reproduce the bug on our side?

When using the UniqueId extension on a TipTap instance with the configuration:

```js
UniqueId.configure({types: ["listItem"]})
```

... and then pasting content in, no IDs initially generate on the pasted nodes -- there's a tree of nodes with IDs set to null, which only resolve into IDs after typing a character and erasing it, or another similar editing transaction.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/withered-bird-jtrgf?file=/src/App.js

This will probably show the issue in question if you cut/paste the content back and forth with the actual UniqueId extension, rather than the... presumable stub which is on public NPM.

See the JSON values here: https://gist.github.com/tekacs/56f59e2c2d0e6c4d9097def3649aec07

### What did you expect to happen?

On pasting content, I would expect the UniqueId extension to populate genuine unique IDs to all pasted nodes.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by hanspagel** [comment]
Doesn’t seem to happen with the official extension. Follow the instructions here:

https://tiptap.dev/api/extensions/unique-id

The official package is installed from a private registry.

**Comment by philippkuehn** [comment]
You are using the version published on npm. This version is deprecated. All of our pro extensions are published at our private registry: https://tiptap.dev/api/extensions/unique-id#installation

I can’t reproduce this issue with the latest version of `@tiptap-pro/extension-unique-id` from our private registry so I think this is already fixed ✌️

**Comment by tekacs** [comment]
Hmm, you're right that I was using `@tiptap/extension-unique-id` on the CodeSandbox (because the sandbox doesn't have 
access to the private registry), but unfortunately I am able to replicate this using `@tiptap-pro/extension-unique-id` set to `^2.0.0-beta.11` locally I'm afraid @philippkuehn.

I might yet be missing something, but I'm finding the same behaviour, where pasting doesn't immediately create IDs (once again, there /is a key for attrs->id/, it's just set to null...

**Comment by philippkuehn** [comment]
Ah, there was another issue on your side. Instead of this:

```js
onUpdate: ({ transaction }) => setDoc(transaction.doc)
```

you should do this:

```js
onUpdate: ({ editor }) => setDoc(editor.state.doc)
```

**Comment by tekacs** [comment]
Ah amazing, that's the fault and makes total sense @philippkuehn -- thanks so much! 🙏
