### ISSUE TITLE
UniqueID extension adds extra empty paragraphs when used with HocusPocus

### ISSUE THREAD

**Issue by bkempe** [ueberdosis/tiptap#2400]
### What’s the bug you are facing?

If the `UniqueId` extension (`2.0.0-beta.11`) is enabled with collaborative editing (via HocusPocus), TipTap adds an _empty paragraph_ (sometimes in different locations) on every page reload.

### How can we reproduce the bug on our side?

TipTap editor setup:
```js
export const Tiptap = () => {
  const websocketProvider = useMemo(() => new HocuspocusProvider({
    url: 'ws://localhost:1234',
    name: 'unique-id-test-01',
  }), []);

  const editor = useEditor({
    extensions: [
      StarterKit.configure({
        history: false
      }),
      UniqueID.configure({
        types: ['paragraph'],
        // seems to happen with any filterTransaction,
        // whether returning true or false
        filterTransaction: isChangeOrigin,
      }),
      Collaboration.configure({
        document: websocketProvider.document,
      }),
    ],
  }, [websocketProvider]);

  return (
      <div style={{ border: '1px solid blue'}}>
        <EditorContent editor={editor} />
      </div>
  );
};
```

HocusPocus setup:
```js
const server = Server.configure({
  port: 1234,
  extensions: [
    new RocksDB()
  ]
});
server.listen();
```

Steps to reproduce:
* open the app
* refresh the browser
* see that it added an empty paragraph

### What did you expect to happen?

No empty paragraphs should be added.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by hanspagel** [comment]
Thanks for reporting! We found the cause, but don’t have an idea for a fix yet.

@philippkuehn Would it make sense/be possible to give the ID in an "empty" editor only after someone started to type?

**Comment by philippkuehn** [comment]
@hanspagel I removed the check when using collab for now. This check was built only to better migrate existing content. This usually works differently with collab anyway. So that shouldn't really be a problem.

@bkempe I released a new version with a fix tor this. There was also a bug in the docs. You have to pass `!isChangeOrigin` instead of `isChangeOrigin` for `filterTransaction`.

**Comment by bkempe** [comment]
@philippkuehn Thank you for fixing this!! Would it be possible to add a little more information in the docs about `filterTransaction`, `isChangeOrigin` and when one should filter what?

**Comment by philippkuehn** [comment]
I can’t think of a case where this would be needed outside of collab. Therefore, only this example is currently shown in the docs.

**Comment by bkempe** [comment]
@philippkuehn But in collab, one _should_ use `filterTransaction: !isChangeOrigin`, correct?

**Comment by philippkuehn** [comment]
In collab you have to use this. Otherwise, new IDs are constantly generated when changes are made by other users.

**Comment by tekacs** [comment]
@philippkuehn in this context, should it be `filterTransaction: !isChangeOrigin` (where `isChangeOrigin` is a function, so `!f === false`), or `filterTransaction: t => !isChangeOrigin(t)`?

**Comment by philippkuehn** [comment]
oh stupid me 🤦‍♂️

`filterTransaction: t => !isChangeOrigin(t)` is correct!

I fixed it in the docs.

**Comment by bkempe** [comment]
@philippkuehn @hanspagel I think the change made for this has some side-effects: when using collaboration/HocusPocus, the first paragraph you start on won't have the attribute from UniqueId until you type at least one letter.

**Comment by linkaiqiyi** [comment]
![image](https://user-images.githubusercontent.com/87741822/212016671-2bc57892-13fc-4be7-afb2-c4a33374aac6.png)

I helped with this by annotating the `onCreate` method in UniqueId, and `filterTransaction: t => !isChangeOrigin(t)`

**Comment by chenyuncai** [comment]
it seems happend again in latest version @tiptap/core 2.14.0 and @tiptap-pro/extension-unique-id 2.21.0, and remove the onCreate Hook is correct.

Maybe the refresh action should be decided by developer accroding to his custom  scene

**Comment by 01101101** [comment]
It's because of this line https://github.com/ueberdosis/tiptap/blob/072b110a93862ccf95219fc8ca45f6961bddd904/packages/extension-unique-id/src/unique-id.ts#L59 add a `provider` options when configuring the `Collaboration` extension and it will fix the issue
