### ISSUE TITLE
When a table is the last node in the document and its last cell is empty, Ctrl+A fails to select anything but the first node of the document.

### ISSUE THREAD

**Issue by andriisharshakov** [ueberdosis/tiptap#2401]
### What’s the bug you are facing?

When:
* a table is the last node in the document
* that table's last cell is empty

Ctrl+A will select the first node of the document.
![image](https://user-images.githubusercontent.com/45874869/149985699-a43ae253-9593-4f98-91d3-2406acd8c7c6.png)

If the last cell of that table has any content, Ctrl+A will select everything as expected.
![image](https://user-images.githubusercontent.com/45874869/149985745-90e10b4d-700f-4810-b70f-10b3b01c63de.png)

### How can we reproduce the bug on our side?

* open the document
* add any paragraphs or other nodes
* add a table as the last node
* hit Ctrl+A to ensure "select all" works
* leave the table blank OR only leave table's last (= bottom right) cell empty
* hit Ctrl+A again to ensure "select all" will only select the first node in the document

### Can you provide a CodeSandbox?

https://codesandbox.io/s/suspicious-swartz-xfx53?file=/src/App.js

### What did you expect to happen?

I expect Ctrl+A to select all the nodes in the document, but it doesn't depending on table node's contents.

### Anything to add? (optional)

First, I wanted to ensure where this behavior is coming from. So, I've tried to reproduce this on the clean demo of prosemirror-tables extension - but it works fine.

Though on this [tiptap demo](https://tiptap.dev/api/nodes/table/) it works exactly as in my project, i.e. "select all" is broken for the described scenario.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by jpobley** [comment]
Updating the `selectAll` command to use the `AllSelection` class from `prosemirror-state` fixes this issue, but I don't know why: https://github.com/jpobley/tiptap/commit/61794def2fc7c1bafb2663897a9ff12abf2ca8e4.

Something about how `setTextSelection` is resolving the range of the doc, but I can't understand why the `TextSelection` jumps to the first node in the doc.

I'm happy to open a PR but would love to understand what's causing the issue and even write a test about it if possible.

**Comment by philippkuehn** [comment]
@jpobley `AllSelection` leads to some other strange bugs. See #1908

Not sure, what’s going on her right now. I'm looking into it.

**Comment by jpobley** [comment]
Oooooooh, yeah, I thought there might be dragons elsewhere. Thanks for the education, @philippkuehn.

**Comment by philippkuehn** [comment]
I had to revert these changes because of #2491
I haven't found another fix yet and think it's a ProseMirror bug.

**Comment by philippkuehn** [comment]
The issue is within the `prosemirror-tables` plugin. 

https://github.com/ProseMirror/prosemirror-tables/blob/6b16ed3cf306886f2c169aebbe60701e1ac2deac/src/cellselection.js#L290-L292

Unfortunately this packages isn’t maintained anymore :(

**Comment by Moondas** [comment]
I removed these lines, and solves issue for me:
https://github.com/ueberdosis/tiptap/blob/main/packages/extension-table/src/table.ts#L240-L242

**Comment by jpobley** [comment]
I updated my dependencies recently and noticed that the table extension is now using a fork at `@_ueberdosis/prosemirror-tables`. Does this mean the TipTap team is moving towards being able to fix this issue on their fork?
