### ISSUE TITLE
Provide API to use alternatives to `tippy.js` in menus

### ISSUE THREAD

**Issue by jaulz** [ueberdosis/tiptap#2404]
### What problem are you facing?

Currently, `BubbleMenu` and `FloatingMenu` are using `tippy.js`. Since i am already using another alternative it would be great to use that instead.

### What’s the solution you would like to see?

Instead of hard coding the `tippy.js` instance it would be nice to see an API that allows developers to use their own solution. I think it would be fairly easy to implement:
1. Set `tippy.js` add optional dependency
2. Add new option to constructor, e.g. 
```typescript
create({ editor, content }: { editor: Element, content: Element }) => { 
  inner: Element, 
  show: () => void, 
  hide: () => void, 
  destroy: () => void, 
  update({ rect }: { rect: DOMRect }) => void 
}
```
3. The default implementation for the new option would look like this:
```typescript
create({ editor, content }: { editor: Element, content: Element }) => {
  const instance = tippy(editor, {
      duration: 0,
      getReferenceClientRect: null,
      content,
      interactive: true,
      trigger: 'manual',
      placement: 'right',
      hideOnClick: 'toggle',
      ...this.tippyOptions, // We can keep `tippyOptions` for compatibility reasons
    })

   return {
     inner: instance.popper,
     show: instance.show.bind(instance),
     hide: instance.hide.bind(instance),
     destroy: instance.destroy.bind(instance),
     update: ({ rect }) => instance.setProps({
       getReferenceClientRect: () => rect,
     }),
   } 
}
```

Let me know if you would be open for a PR 😊 

### What alternatives did you consider?

n/a

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Hey, this is a really complex topic and I'm not absolutely happy with the current situation either. Nevertheless, I don’t want to abstract it any further because I think this overcomplicates everything.

There is a [new lightweight library](https://floating-ui.com/) from the makers of tippy. It looks exciting, which is why I might want to switch to it out in the future. Because of the small size, it shouldn't be so bad if you use two different libraries. 

There is also the option of building a completely custom bubble menu, as this doesn’t contain a lot of code either.

**Comment by jaulz** [comment]
Okay, no worries 😊  And thanks for that pointer to that library!

**Comment by duhaime** [comment]
@philippkuehn do you by any chance have any super barebones examples of building a custom menu? Seeing one of those would be great for my team!

**Comment by philippkuehn** [comment]
@duhaime There is a [minimal example](https://prosemirror.net/examples/tooltip/) at the ProseMirror docs. Otherwise, it is probably helpful to have a look at the [tiptap bubble menu](https://github.com/ueberdosis/tiptap/blob/main/packages/extension-bubble-menu/src/bubble-menu-plugin.ts).

**Comment by duhaime** [comment]
This is super helpful, thank you!

**Comment by rfgamaral** [comment]
> This is super helpful, thank you! 

Hey @duhaime, I'm curious, what's you team use case to build a "bubble menu" from scratch? Are you using a library different from Tippy?

**Comment by duhaime** [comment]
@rfgamaral we'd like to use React for everything. Right now tippy mounts in a scrollable context, so we can't bind tippy to `document.body` but must instead bind to an element that prevents scrolls from making tippy out of sync with the text. That binding happens in a `document.querySelector` call, which seems brittle, so we'd like to just remove tippy and render with React...

**Comment by rfgamaral** [comment]
@duhaime Couldn't you use a `ref` instead of `querySelector`?

Anyway, wondering if you could share your approach when done. I'm curious to see how exactly that React-only approach works.

**Comment by duhaime** [comment]
Yes, I'm using a ref :) for tippy. I think I'll stick with that approach for the short term, and if time permits move to React only rendering...
