### ISSUE TITLE
onFocus does not fire when using TaskList extension

### ISSUE THREAD

**Issue by ospfranco** [ueberdosis/tiptap#2405]
### What’s the bug you are facing?

I'm using the task list extension, on some of the screens in my application I display a tiptap field, but I don't want it to be fully editable, just want to be able to check the checkboxes inside.

In order to prevent the user from editing but still allow the checkbox editing I'm using the following workaround:

```ts
<Tiptap
  onFocus={({ editor }) => {
    console.log("Tiptap has gained focus")
    editor.commands.blur()
  }}
  initialContent={project.notes ? JSON.parse(project.notes) : null}
  placeholder="You can add a default checklist in the settings."
  className="md:max-w-2xl lg:max-w-none"
  onUpdateRef={tiptapOnUpdateRef}
  ref={tiptapRef}
/>
```

When the editor receives focus the onFocus function is called and the editor blured, this works fine for normal interactions, but the TaskList plugin somehow does not fire this callback, it just marks the checkbox and then immediately focuses the editor

### How can we reproduce the bug on our side?

Use a tiptap editor with the TaskList extension

### What did you expect to happen?

the `onFocus` callback should be fired for all focus events not only those initiated by the user

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
I can’t reproduce this. For me the editor gets blurred when calling `editor.commands.blur()` within a `focus` hook. Even when clicking on the checkboxes. Maybe it helps to run the blur asynchronously.

```js
setTimeout(() => {
  editor.commands.blur()
}, 0)
```

Otherwise create a reproducable codesandbox and feel free to reopen.

**Comment by ospfranco** [comment]
https://user-images.githubusercontent.com/1634213/150354519-eca9dc7c-b4b8-4b80-afda-706c2391e243.mov

I have now tried everything, I basically stripped down Tiptap to passing the content and harcoding the onFocus function and still, whenever I click on the checkbox the editor is focused, I even tried calling blur on every render via a useEffect hook:

```ts
useEffect(() => {
    const editor: Editor = tiptapRef.current?.getEditorInstance()
    if (editor) {
      editor.commands.blur()
    }
  })
```

Still not working :(

**Comment by ospfranco** [comment]
aha! I just discovered that on chrome it is working

**Comment by philippkuehn** [comment]
Hmm, this only seems to be an issue with safari. Every other browser works as expected.

**Comment by ospfranco** [comment]
yeah, the callback looks like it is correct, so maybe it is a problem with the `blur()` call? kinda relieved to find the issue... I thought I was going crazy haha

**Comment by philippkuehn** [comment]
ok, [I found a workaround](https://github.com/ueberdosis/tiptap/commit/9d317128a08a66f18c4d51385b6a9fccc5cd66f4) for safari.

**Comment by ospfranco** [comment]
thanks a lot @philippkuehn! Any word on which release will I be able to test this?

**Comment by philippkuehn** [comment]
Update to the latest :)

**Comment by ospfranco** [comment]
I don't see any new version for @tiptap/react already on latest (also for tasklist and taskitem)
<img width="370" alt="Screen Shot 2022-01-21 at 19 46 19" src="https://user-images.githubusercontent.com/1634213/150583115-6fefa486-26e7-4822-b1e3-c137ba3453b7.png">

**Comment by philippkuehn** [comment]
This was fixed in `@tiptap/core`.
