### ISSUE TITLE
insertContent command should retain marks on the current selection when a text string is passed

### ISSUE THREAD

**Issue by SamDuvall** [ueberdosis/tiptap#2406]
### What problem are you facing?

I was expecting the `insertContent` command below to insert the text like `insertText` in ProseMirror where marks on the current selection are preserved.

```
editor.commands.insertContent('Example Text')
```

### What’s the solution you would like to see?

Perhaps we should modify `insertContent` command to retain marks on the current selection or add a new command `insertText` that maps to ProseMirror?

### What alternatives did you consider?

I'll just create my own `insertText` command in my project for now.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Ah, should now work more as expected :)
