### ISSUE TITLE
Storage not typed outside of extension

### ISSUE THREAD

**Issue by Deckluhm** [ueberdosis/tiptap#2407]
### What’s the bug you are facing?

When accessing the storage of any extension outside of it, I don't get any typing.

I read both https://tiptap.dev/guide/custom-extensions#storage and https://tiptap.dev/guide/typescript#storage-types while trying to create my own extension with storage but I realized even the official "Characters Count" extension (which is using storage) has the same issue.

### How can we reproduce the bug on our side?

See CodeSandbox and check last line and associated comment.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/morning-smoke-xlq76?file=/src/storage.ts

### What did you expect to happen?

It would be great to have storage typing when used outside of the extension itself.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Due to the type system you have to manually set the type. I’ve updated to the docs for that.
