### ISSUE TITLE
Dropped content isn't parsed since input/paste rules are into core

### ISSUE THREAD

**Issue by Deckluhm** [ueberdosis/tiptap#2408]
### What’s the bug you are facing?

Drag & dropped content used to be correctly parsed by Tiptap but it's no longer the case (and I think it started happening after this PR: https://github.com/ueberdosis/tiptap/pull/1997).

Here is a short video where you can see me:
1. Copy/pasting content from outside the document into it (it works as expected)
2. Drag & dropping content from outside the document into it (markdown isn't parsed as it should be) 

https://user-images.githubusercontent.com/2947925/150316518-604bba94-e016-4bbc-967a-dde3cdb6beee.mp4

### How can we reproduce the bug on our side?

Easiest way to reproduce the issue is to:

1. Go to the following page: https://tiptap.dev/examples/markdown-shortcuts
2. Edit the title with markdown content like `*Markdown* _content_`
3. Drag & drop title into the editor below

If you use the following versions of packages, it works as expected:
- `@tiptap/core` version `2.0.0-beta.118` (issue started with `2.0.0-beta.119`)
- `@tiptap/vue-3` version `2.0.0-beta.69`
- `@tiptap/starter-kit` version `2.0.0-beta.117`

### Can you provide a CodeSandbox?

https://codesandbox.io/s/cranky-mountain-zo2sw?file=/src/App.vue

### What did you expect to happen?

Drag & dropped content should be treated like copy/pasted content (like it used to be).

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by Deckluhm** [comment]
Thank you for the quick fix, it works perfectly! :ok_hand:

**Comment by hanspagel** [comment]
Thanks for the report!
