### ISSUE TITLE
Specify starter-kit is not required

### ISSUE THREAD

**Issue by deadcoder0904** [ueberdosis/tiptap#2409]
### What’s the URL to the page you’re sending feedback for?

https://tiptap.dev/installation/nextjs

### What part of the documentation needs improvement?

Under Next.js, its written that you have to install `@tiptap/react` & `@tiptap/starter-kit` but there isn't a warning that you don't require `starter-kit`.

But I intuitively thought I don't need it but then it gave me an error without `starter-kit`:

> Schema is missing its top node type ('doc')

A link to a special section called [Starter Kit](https://tiptap.dev/api/extensions/starter-kit) where you can just get away with using `Text` extension would be great.

### What is helpful about that part?

This makes sure you don't need the entire starter kit & shows you how to go about without using it.

### What is hard to understand, missing or misleading?

I thought empty `extensions` array would work out just fine but that isn't the case.

### Anything to add? (optional)

While writing this issue, I realised even adding just the `Text` doesn't work. I still get:

> RangeError: Schema is missing its top node type ('doc')

I'll open an issue but I think this would be a common question for those that don't want to use `starter-kit` but just plain `text` like `textarea` component

**Comment by hanspagel** [comment]
Most people use the starter kit, them there is this: https://tiptap.dev/examples/minimal and similar things are mentioned everywhere. I think thats fine.

**Comment by deadcoder0904** [comment]
so `document`, `paragraph`, & `text` (all 3) are needed, right?

i still feel like it should be pointed out from installation as examples are kinda hidden (i mean it takes 2-clicks)

**Comment by philippkuehn** [comment]
It depends.

A `topNode` extension is required and a `text` node is required.

By default the `document` extension contains the `topNode` and `text` extension contains the `text` node.

The `document` extension is using `block+` as a content extension for its content so you’ll also need a `block` node. For most people the `paragraph` node is used as a default `block` node but it’s totally fine to use another block node.

You can also read about it here https://tiptap.dev/api/schema#how-a-schema-looks-like

**Comment by deadcoder0904** [comment]
cool thanks @philippkuehn that makes sense. started reading the docs :)
