### ISSUE TITLE
Lazy load lowlight.js

### ISSUE THREAD

**Issue by thousandsofraccoons** [ueberdosis/tiptap#2418]
### What problem are you facing?

Hello, I have a codeblock in my implementation. The problem I facing is low lighthouse score due to high volume of highlight.js. is there any way to lazy load highlight JS only in case codeblock is actually used? How can I avoid loading 1.9mb for nothing?
Would be great to lazy load everything until it is used, now library loads a lot of bytes that user potentially might not need. To be fair, user don't even need the library to be loaded as critical resource.

### What’s the solution you would like to see?

Lazy load for plugins

### What alternatives did you consider?

Quill, but it's looks inactive now

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by thousandsofraccoons** [comment]
For now I achieve SSR and lazy load with conditional rendering of saved tiptap content / initialized tiptap editor. It still far from perfect, because in many cases, tiptap rendered content has just paragraph and bold text style, but user still forced to load lists, headings, codeblock, quote, etc.

**Comment by rezaffm** [comment]
Hi,

I think you want to use the create and update event, you can learn more about them here: https://tiptap.dev/api/events#list-of-available-events

In both cases, you want to loop over all descendant of the editor's content, like

```javascript
      this.editor.state.doc.descendants((node, pos) => {
        // if it is a code block, then...
        if (node.type.name === '...') {
          // check if highlight js is not already loaded
            // if not, load it
        }
      })
```

Well, at least that would be the first solution that would come to my mind (not sure if works).

**Comment by philippkuehn** [comment]
The rendering in ProseMirror works synchronously. Therefore, it is not \*that\* easy to load code asynchronously and re-render nodes.

The docs show how to load only certain languages to reduce the file size. Currently there are no plans to extend this further.

**Comment by omridevk** [comment]
@philippkuehn Care to share which docs you are referring to? I can't find anything indicating how to load less languages in tiptap

**Comment by arily** [comment]
Hi @thousandsofraccoons,
I've running in to same problem and I achieved lazy-load by using this code
```typescript
import { lowlight } from 'lowlight/lib/core'
import { Editor } from '@tiptap/vue-3'

const editor = ref<Editor>()
const lazyLoadCodeBlock = ({ editor }: {editor: Editor}) => {
  const json = editor.getJSON()
  json.content?.forEach(async (node) => {
    if (node.type !== 'codeBlock') { return }
    const language = node.attrs?.language
    if (!language) { return }
    if (lowlight.registered(language)) { return }
    try {
      const hljs = await import(`../../../node_modules/highlight.js/es/languages/${language}.js`) // change me
      lowlight.registerLanguage(language, hljs.default)
    } catch (e) {
      console.error(e)
    }
  })
}

onBeforeMount(() => {
  editor.value = new Editor(/* config */)
  editor.value.on('beforeCreate', lazyLoadCodeBlock)
  editor.value.on('update', lazyLoadCodeBlock)
})
```
