### ISSUE TITLE
Incorrect node removal when using async suggestion items 

### ISSUE THREAD

**Issue by heydarm** [ueberdosis/tiptap#2431]
### What’s the bug you are facing?

Using async ```items``` key in ```@tiptap/extension-mention``` throws error

<img src="https://user-images.githubusercontent.com/56446558/150859584-1100a728-3b91-4709-acc0-5aaeaac616f5.png" height="400" />

and Tippy.js shows warning

<img src="https://user-images.githubusercontent.com/56446558/150859435-fe05aa5e-1d41-46f8-8db0-77e415f2e526.png" height="150" />

### How can we reproduce the bug on our side?

1. Open [codesandbox](https://codesandbox.io/s/kind-napier-jp2fg?file=/src/suggestion.js:1195-1200) example
2. Try to add ```@``` in the editor and then quickly remove it

### Can you provide a CodeSandbox?

https://codesandbox.io/s/kind-napier-jp2fg?file=/src/suggestion.js:1195-1200

### What did you expect to happen?

Correctly remove nodes from DOM

### Anything to add? (optional)

I am using code from example on https://tiptap.dev/examples/suggestions (source code https://github.com/ueberdosis/tiptap/tree/main/demos/src/Examples/Community/React)

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by heydarm** [comment]
I made workaround, but with [PopperJS](https://popper.js.org/) instead of [TippyJS](https://atomiks.github.io/tippyjs/):
[CodeSandbox](https://codesandbox.io/s/react-tiptap-mentions-with-popperjs-i8uii)
It is using positioning and data fetching inside ```MentionList``` component itself.

**Comment by amorriscode** [comment]
@heydarm I had the same issue as you but I resolved it by using the `onShow` method that `tippy` has:

```typescript
        popup = tippy("body", {
          getReferenceClientRect: props.clientRect,
          appendTo: () => document.body,
          content: component.element,
          showOnCreate: true,
          interactive: true,
          trigger: "manual",
          placement: "top-start",
          onShow: () => {
            // If a user deletes the @ symbol quickly after
            // typing it, the node we want to append the popup
            // to won't exist so we check to ensure it is there
            // prior to mounting the popup to the DOM
            try {
              props.clientRect?.();
            } catch {
              return false;
            }
          },
        });
```

Hope this helps!
