### ISSUE TITLE
markInputRule is preventing a trailing space 

### ISSUE THREAD

**Issue by JonathanKolnik** [ueberdosis/tiptap#2433]
### What’s the bug you are facing?

I have a inputRule that has the regex match completed by a non-capturing group of a space/newline 

However the input rule is swallowing up this trailing space resulting in having to type space twice to see 1 space

### How can we reproduce the bug on our side?

Please try type a url like www.google.com followed by a space (for bug)

Try again but type 2 spaces (for intended result)

### Can you provide a CodeSandbox?

https://codesandbox.io/s/dazzling-turing-96j26?file=/src/Link.js:620-633

### What did you expect to happen?

I expect that the first space after typing the url is visible and not part of the link

### Anything to add? (optional)

https://github.com/ueberdosis/tiptap/blob/6a813686f5e87cebac49a624936dbeadb5a29f95/packages/core/src/inputRules/markInputRule.ts#L32

seems like this is still considering the non capturing group

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by bblumenfelder** [comment]
Did you figure this out? I'm running into the same problem. 

I want to wrap every word that has been typed in `<w>`-Tags. 
The problem is I need to add two spaces after every word in order for this to work.

My input-regex: 
```
const inputRegex = /(?:^|\s)((?:\b)((?:[^\b]+))(?:\b))$/
``` 

Codesandbox:
https://codesandbox.io/s/elegant-wildflower-7hmnnr?file=/src/extensions/ext-custom-italic.js:0-620

Please reopen this issue.

**Comment by polhuang** [comment]
@bblumenfelder 

I believe I figured this out - I messaged you on StackOverflow but checking here as well.

I know it's been a while but I ran into the same problem. I ended up fixing it by adding one line of code to markInputRule.ts:

`state.tr.insertText(match, range.from, range.to)`

I realized that by the time markInputRule initially loads the Prosemirror state, it has already excluded the delimiter.

Therefore, you have to essentially re-insert the full matched text. This is actually what the core developers do for the extensions using textInputRule where strings are replaced (e.g. `typography-extension`).

Please feel free to reach out to me directly if you have any questions.

**Comment by siminino** [comment]
@bblumenfelder @polhuang 
I was running into the same problem.

I solved it by wrapping the InputRule handler to insert a whitespace in the end. I did the same for the paste rule.
```typescript
type MarkInputRuleFactory = typeof markInputRule
type MarkPasteRuleFactory = typeof markPasteRule

export const closedMarkInputRule: MarkInputRuleFactory = (config) => {
  const inputRule = markInputRule(config)
  const baseHandler = inputRule.handler
  inputRule.handler = (props) => {
    baseHandler(props)
    props.state.tr.insertText(' ')
  }
  return inputRule
}

export const closedMarkPasteRule: MarkPasteRuleFactory = (config) => {
  const inputRule = markPasteRule(config)
  const baseHandler = inputRule.handler
  inputRule.handler = (props) => {
    baseHandler(props)
    props.state.tr.insertText(' ')
  }
  return inputRule
}
```
