### ISSUE TITLE
extension-link: linkOnPaste has no effect

### ISSUE THREAD

**Issue by farin** [ueberdosis/tiptap#2441]
### What’s the bug you are facing?

hi

try to fix it https://github.com/ueberdosis/tiptap/pull/2427
I must say, from reply in PR I don't understand what is desired behavior then
but I pretty sure that current behavior is not correct

because, regardless on linkOnPaste value, link plugin works always same
pasting any value from following
`aaaa www.github.com`
`www.github.com`
`<a href="https://github.com/">GH</a>`

it's always linkified 

### How can we reproduce the bug on our side?

try paste with/wo linkOnPaste anabled as described above
I see no difference

### What did you expect to happen?

I would expect different behaviour or argument not exists.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by farin** [comment]
cc @philippkuehn

**Comment by farin** [comment]
sorry if I missing something, it's still possible then option should be better documented or not related to paste at all

**Comment by philippkuehn** [comment]
By default a link is added on paste if the clipboard contains only a link (instead of inserting the content as text).
With the `linkOnPaste` option you can disable this behavior. See a video here:

https://user-images.githubusercontent.com/2500670/151167076-d58d5ae3-11ee-4704-9e4b-e8cd79714aeb.mp4

**Comment by farin** [comment]
thanks, 
as I said, more detailed argument description would be much helpful.
