### ISSUE TITLE
Link element error after deployment

### ISSUE THREAD

**Issue by bingyu11** [ueberdosis/tiptap#2442]
### What’s the bug you are facing?

We are using the package in our vue2 project to allow users create and edit html text. Everything went well for localhost test. But after deployment using webpack, the link extension gives an error (see attached img) for previously created text.

<img width="431" alt="Screen Shot 2022-01-26 at 3 49 11 PM" src="https://user-images.githubusercontent.com/46343405/151185497-0b2705bf-b2b3-46a6-8d20-4e1cd591692d.png">

### How can we reproduce the bug on our side?

N/A

### What did you expect to happen?

Created html text with hyperlink can be edited as well after deployment

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by hanspagel** [comment]
I don’t think we any chance to help without a reproduction. Generally speaking, I assume it’s something in your setups because other Vue.js 2 Tiptap setups work.

**Comment by philippkuehn** [comment]
Feel free to re-open with a reproducable demo.
