### ISSUE TITLE
End key does not select end of text block

### ISSUE THREAD

**Issue by rosczja** [ueberdosis/tiptap#2446]
### What’s the bug you are facing?

When pressing the end key in an editor, the selection is not moved to the end of the text block.

### How can we reproduce the bug on our side?

There is a typo in keymap.ts, for `End` it should read `this.editor.commands.selectTextblockEnd()` and not `this.editor.commands.selectTextblockStart()`.

### What did you expect to happen?

Pressing the end key moves the selection to the end of the text block.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Fixed and released. Thanks!

**Comment by rosczja** [comment]
That was fast! Thank you very much.
