### ISSUE TITLE
Any plans to support the Block Protocol?

### ISSUE THREAD

**Issue by gmlewis** [ueberdosis/tiptap#2450]
### What problem are you facing?

This was just announced and it would be amazing if tiptap supported the Block Protocol:
https://www.joelonsoftware.com/2022/01/27/making-the-web-better-with-blocks/

### What’s the solution you would like to see?

Full support for the Block Protocol.

### What alternatives did you consider?

n/a

### Anything to add? (optional)

https://blockprotocol.org/

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
The data structure is defined in ProseMirror so we can’t do anything here. But this is an interesting topic and could become the starting point for some new editor.

**Comment by hanspagel** [comment]
I’ve read this post, but it left me very confused. Probably have to blog about it, but I don’t think this is a good approach for the problem he’s describing.
