### ISSUE TITLE
Drop base64 images still possible, how to prevent this?

### ISSUE THREAD

**Issue by tobischulz** [ueberdosis/tiptap#2455]
### What’s the bug you are facing?

While drop base64 images has to be removed in v2 its still possible through drag&drop from other websites.

### How can we reproduce the bug on our side?

- Open the website https://www.base64-image.de/ or any other page that has base64 images as our drag source.
- Open the TipTap2 documentation (https://tiptap.dev/api/nodes/image) with the Image node as our drop target.
- Drag the source image to the tiptap2 editor.
- Image was added and is shown.
- See the base64 encoded image in element inspector.

![CleanShot 2022-01-28 at 10 29 43](https://user-images.githubusercontent.com/576014/151522558-68ba3a2b-78a3-4eef-b24d-076fd4b83d14.gif)

### Can you provide a CodeSandbox?

The docs example is able to reproduce this https://tiptap.dev/api/nodes/image.

### What did you expect to happen?

On Paste and Drag base64 images should be removed and never added to the editor. If this is still a required feature, it would be awesome to have an extension feature for the Image node do disable or override this behaviour.

### Anything to add? (optional)

I sanitize all the HTML from tiptap on server-side but the user should never be able to drag or paste images like that as they will be removed on save which leads to frustrations.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by codemzy** [comment]
I had an issue where I wanted drag and drop images to be uploaded and inserted with the correct `src`. So I override the default drop behaviour when files are dropped in the editor, upload the image, and insert `<img src="thelocation" />`. I guess you could tweak the code to disable or override any type of drag/drop event.

Hope this helps...

```js
const editor = useEditor({
    extensions: extensions,
    editorProps: {
        // ...
        handleDrop: function(view, event, slice, moved) {
            if (!moved && event.dataTransfer && event.dataTransfer.files) { // if dropping external files
                // the addImage function checks the files are an image uploads, and returns the url
                addImage(event.dataTransfer.files[0], function(url) {
                    // this inserts the image with src url into the editor at the position of the drop
                    const { schema } = view.state;
                    const coordinates = view.posAtCoords({ left: event.clientX, top: event.clientY });
                    const node = schema.nodes.image.create({ src: url });
                    const transaction = view.state.tr.insert(coordinates.pos, node);
                    return view.dispatch(transaction);
                });
                return true; // drop is handled don't do anything else
            }
            return false; // not handled as wasn't dragging a file so use default behaviour
        }
    },
    
    content: content,
});
```

**Comment by philippkuehn** [comment]
I agree that base64 images should not be allowed by default. I updated the parse rule.

**Comment by tobischulz** [comment]
@codemzy thanks for that snipped. That could help.

@philippkuehn thanks, this is awesome! <3

**Comment by philippkuehn** [comment]
@deterralba Hey, I'm open for a PR! (But I think the default value of `allowBase64` should be `false`)

**Comment by georgemandis** [comment]
> https://github.com/ueberdosis/tiptap/issues/2455#issuecomment-1024117918

I'm late to this this thread, but why the decision to disallow base64 encoded images?

I actually landed here because we accidentally upgraded the image extension. Copying images from the clipboard was base64-encoded images was expected for us up until this point, and I thought something else I'd introduced had broken it! I was going in circles until I noticed we'd updated the package and eventually found this thread.

**Comment by philippkuehn** [comment]
@georgemandis Sorry to hear that. It will be easier to follow breaking changes when we officially reached the stable version (soon).

There is a new option `allowBase64`: https://tiptap.dev/api/nodes/image#allow-base64

**Comment by deterralba** [comment]
Nice, I was about to open the PR but you were too fast! :rocket:

**Comment by georgemandis** [comment]
@philippkuehn That's okay! I appreciate the fast reply :)
