### ISSUE TITLE
CollaborationCursor does not reflect new user values until selection changes

### ISSUE THREAD

**Issue by jamesopti** [ueberdosis/tiptap#2457]
### What’s the bug you are facing?

We've noticed that sometimes the default cursor name of `User: <clientId>` does not update on remote clients once we set our user's real name via `editor.commands.user({ name: "Denzel Washington" })`.

It appears that Prosemirror does not think the widget needs to be drawn again.

Through some debugging, I've confirmed that on each call to `.user`, this line in the cursor-plugin does get called: https://github.com/yjs/y-prosemirror/blob/master/src/plugins/cursor-plugin.js#L64

It's possible this bug should be filed in the y-prosemirror repo. Happy to do that if that is the proper place to do so.

### How can we reproduce the bug on our side?

This codesandbox reproduces the issue. The local `editor.commands.user` fires every 2 seconds to update the name (shown at the top with the colored background).

When viewed in 2 browser tabs, you can see that the updated username only reflects on the local browser (not the remote) until the cursor moves to another paragraph or the selection range changes.

Codesandbox: https://codesandbox.io/s/collab-cursor-update-user-olp3i?file=/src/Tiptap.tsx

Loom Recording: https://www.loom.com/share/7d808ee02ad94149a7645948af47af63?sharedAppSource=personal_library

### Can you provide a CodeSandbox?

Codesandbox: https://codesandbox.io/s/collab-cursor-update-user-olp3i?file=/src/Tiptap.tsx

### What did you expect to happen?

Any update to the awareness `user` field should cause the cursor label to redraw.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by Vaisakhkm2625** [comment]
Anybody looked into this?? or stalebot just closed ?

for anyone coming here in there future, i found that it's already supported in Tiptap collaboration with help of 'awareness'
https://tiptap.dev/docs/hocuspocus/guides/awareness

and is easy to implement (just wow, how awesome is tiptap) 

svelte example below
```js
	let provider = new HocuspocusProvider({
		url: 'ws://127.0.0.1:1234',
		name: 'example-document',
		document: ydoc,
		onAwarenessUpdate: ({ states }) => {
			console.log(states);
		}
	});
	
	 // simple custom util functions, implimentation doesn't matter, it's just return a random strings
	let random_name = getRandomName();
	let random_color = getRandomColor();

	function updateAwareness() {
		provider.setAwarenessField('user', {
			name: random_name,
			color: random_color
		});
	}
	
<input type="text" bind:value={random_name} on:change={updateAwareness} />



```
