### ISSUE TITLE
Link extension - Open link on Cmd Click

### ISSUE THREAD

**Issue by alexluong** [ueberdosis/tiptap#2463]
### What problem are you facing?

Hi, I'm using the `@tiptap/extension-link` and would like to allow users to open the link but not on click.

### What’s the solution you would like to see?

I'd like to configure the extension so that links are only opened on Cmd + click

### What alternatives did you consider?

N/A

### Anything to add? (optional)

I'm wondering if it's possible to modify this behavior depending on whether the editor is editable.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by jpobley** [comment]
You can call `Link.configure({openOnClick: false})`, which won't load the extension's click handler plugin, and then you can write your own ProseMirror plugin that checks for the right conditions using the [`handleClick`](https://prosemirror.net/docs/ref/#view.EditorProps.handleClick) prop.

**Comment by philippkuehn** [comment]
What @jpobley said. Write a custom Plugin for that. The default [clickHandler plugin](https://github.com/ueberdosis/tiptap/blob/main/packages/extension-link/src/helpers/clickHandler.ts) should be a good starting point.

**Comment by andreasvirkus** [comment]
I was quite surprised to learn that Tiptap doesn't support Cmd+Click or even mouse wheel (middle button) clicks for opening links in the background. Quite a big UX regression from native behaviour 🤔 

For anyone looking, this is one way to achieve it:

```ts
import { Plugin, PluginKey } from '@tiptap/pm/state';
import { Link } from '@tiptap/extension-link';

export const EnhancedLink = Link.extend({
  addProseMirrorPlugins() {
    return [
      new Plugin({
        key: new PluginKey('linkClickHandler'),
        props: {
          handleClick: (view, _pos, event) => {
            if (!view.editable) {
              return false;
            }

            let target = event.target as HTMLElement;
            while (target !== null && target.nodeName !== 'A' && target.nodeName !== 'DIV') {
              target = target.parentNode as HTMLElement;
            }

            if (target?.nodeName !== 'A') {
              return false;
            }

            const href = target.getAttribute('href');
            if (href === null) {
              return false;
            }

            if (event.button === 1 || (event.button === 0 && (event.metaKey || event.ctrlKey))) {
              window.open(href, '_blank', 'noopener noreferrer');
              return true;
            }

            // Regular left click - let TipTap handle it
            return false;
          },
        },
      }),
    ];
  },
});

```
