### ISSUE TITLE
Copy/pasting something with a table "swallows" content it is pasted next to

### ISSUE THREAD

**Issue by Deckluhm** [ueberdosis/tiptap#2464]
### What’s the bug you are facing?

Tricky bug here...

If you copy something with a table in it and paste it near some content, the content is kind of "swallow" into the last table cell.

My English is terrible and it's definitely simpler to understand what happens with the following video:

https://user-images.githubusercontent.com/2947925/152017519-28a8ed59-5084-482c-bbbe-0fc8bed06777.mp4

### How can we reproduce the bug on our side?

1. Go to the following documentation/example page: https://tiptap.dev/examples/tables
2. Copy everything from "Here is an example:" to the end of the table
3. Put your cursor at the beginning of the "Have you seen our tables? They are amazing!" line
4. Paste your content

You can see that the "Have you seen our tables? They are amazing!" is getting moved into the last cell of the table.

### Can you provide a CodeSandbox?

If reproduction steps + link to the documentation page isn't enough, I can provide one but it will basically be copying the source code of the page (https://github.com/ueberdosis/tiptap/blob/main/demos/src/Examples/Tables/Vue/index.vue).

### What did you expect to happen?

I'd say that content it is copied next to should stay untouched and pasted content (especially table) should appear on top of it.

Note that it works well if I only copy the table (without any additional content).

### Anything to add? (optional)

Just wanted to add some content about how we discovered the issue: one of our (non-tech) users encountered the issue while copying the content into what he thought was a new/empty line but he actually pressed `Shift + Enter` (which doesn't create a new node) instead of `Enter` (which does create a new node).

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
This is expected. It’s the same as pasting plain paragraphs.

https://user-images.githubusercontent.com/2500670/152357163-bb404462-10c1-4ece-b545-8b17a80d2a9e.mp4

In these situations it’s always better to create an empty block before pasting.

https://user-images.githubusercontent.com/2500670/152357305-dc94e96f-8887-4fa5-896b-245896adddf0.mp4

**Comment by remi-guan** [comment]
@philippkuehn Hello! Sorry for posting here, but may I know what's the tool you've used to record the keystrokes and clicks in the video you posted? It seems very useful for bug sharing.
