### ISSUE TITLE
editor.isActive shows both bulletList and orderedList active for a nested ordered list inside an unordered list

### ISSUE THREAD

**Issue by JonathanKolnik** [ueberdosis/tiptap#2475]
### What’s the bug you are facing?

When you have a nested list of ordered and unordered like
![image](https://user-images.githubusercontent.com/1164060/152252748-f93af71d-55de-412b-ad2a-3f5c9ce9385d.png)

and you select the nested line you end up with both `editor.isActive('bulletList')` and `editor.isActive('orderedList')` as `true`

![image](https://user-images.githubusercontent.com/1164060/152252637-00a47c8d-fd82-4491-b35c-72719c627ee5.png)

### How can we reproduce the bug on our side?

I made a sandbox

### Can you provide a CodeSandbox?

https://codesandbox.io/s/amazing-paper-mefbe?file=/src/App.js

### What did you expect to happen?

I expect that if I'm on a bulleted line then only isActive('bulletList') is true and it is not affected by the parent

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
This is expected and I don’t want to change that.

Lists are complex nested structures. In your case `isActive('bulletList')`, `isActive('orderedList')`, `isActive('listItem')` and `isActive('paragraph')` returns true. I could imagine that only the closest block node is checked in `isActive`, but this would be `paragraph` in this case, which you would also not expect.

You have to write your own method to handle these specific cases.

**Comment by inickvel** [comment]
There is a solution for this problem
https://github.com/ueberdosis/tiptap/issues/1058#issuecomment-778254557

**Comment by bkempe** [comment]
Or maybe
```ts
  const { extensionManager, state } = editor;
  const { extensions } = extensionManager;
  const { selection } = state;
  // see https://github.com/ueberdosis/tiptap/blob/10248f276320d39fb0fd0cc6786ae2de4d219ec7/packages/core/src/commands/toggleList.ts#L86
  const parentList = findParentNode(node => isList(node.type.name, extensions))(
    selection,
  );
  return parentList !== undefined && parentList.node.type.name === nodeType;
```
