### ISSUE TITLE
error using nuxt.js when get started

### ISSUE THREAD

**Issue by jhkim8406** [ueberdosis/tiptap#2479]
### What’s the bug you are facing?

This dependency was not found

* ~/components/TiptapEditor.vue in ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/index.vue?vue&type=script&lang=js&

### How can we reproduce the bug on our side?

just do it get started that on your https://tiptap.dev web site

### What did you expect to happen?

works normally

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Please create a codesandbox that reproduces the error and feel free to re-open then.
