### ISSUE TITLE
Table of contents breaks undo

### ISSUE THREAD

**Issue by codemzy** [ueberdosis/tiptap#2483]
### What’s the URL to the page you’re sending feedback for?

https://tiptap.dev/guide/node-views/examples#table-of-contents

### What part of the documentation needs improvement?

The table of contents node view given in the docs is really useful, and I am using it in my editor. The problem is it breaks the undo if you delete a header plus any other content (e.g. a paragraph). You can see this in the screen recorded I did in the docs 
1. delete a paragraph and undo works
2. delete a paragraph plus a header and undo doesn't work

https://user-images.githubusercontent.com/13764272/152551000-785db8ce-fd34-4569-ac1e-59bb0c9607c4.mp4

### What is helpful about that part?

It's really helpful to have a table of contents 🤩 

### What is hard to understand, missing or misleading?

I'm wondering if someone smarter than me can figure out why it breaks the undo.

### Anything to add? (optional)

I narrowed it down to this part of the component that breaks the undo

```js
          transaction.setNodeMarkup(pos, undefined, {
            ...node.attrs,
            id,
          })
```

But I can't figure out why 😢

**Comment by codemzy** [comment]
The behaviour doesn't happen if you delete the last header of the document, I don't know if that gives any more clues as to what could be causing the issue.

**Comment by hanspagel** [comment]
I think you could add meta data to the transaction to skip tracking a new history step.

tr.setMeta("addToHistory", false)

**Comment by codemzy** [comment]
Yes!!!! That's fantastic. I'm not going to pretend I understand why this works... but it does!

I added your line above the `preventUpdate` in the component and it seems to undo now with no issues.

```js
        transaction.setMeta("addToHistory", false); // the new line
        transaction.setMeta('preventUpdate', true);
        editor.view.dispatch(transaction);
        setItems(headings);
```

Thanks so much ⭐  - I'll submit a pull request with the update for the docs

**Comment by hanspagel** [comment]
Amazing! The prosemirror-history plugin (which we use) checks the attached meta data of transactions and ignores transactions having "addToHistory": false. Then it’s not appearing in the history.

I couldn’t find documentation on it, but I was able to find hints in the source code of the prosemirror-history package.

Glad it helped! Thanks for the PR!
