### ISSUE TITLE
Error: "parent is null" when using ReactNodeViewRenderer

### ISSUE THREAD

**Issue by elias94** [ueberdosis/tiptap#2500]
### What’s the bug you are facing?

I'm getting an error when I'm using a React component in a custom Node via `ReactNodeViewRenderer`.
**Error** `parent is null`

### How can we reproduce the bug on our side?

https://codesandbox.io/s/inspiring-gauss-90d4g?file=/src/TipTap.jsx

### Can you provide a CodeSandbox?

Above

### What did you expect to happen?

No error shown

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
You defined `content: "text*"` for your node. That’s why you have to render `<NodeViewContent />` within your `<NodeViewWrapper>` component.

```js
<NodeViewWrapper className="react-component">
  <span className="label">React Component</span>

  <div className="content">
    <button onClick={increase}>
      This button has been clicked {props.node.attrs.count} times.
    </button>
  </div>

  <NodeViewContent />
</NodeViewWrapper>
```

If you don’t want to render any content within your node you have to remove `content: "text*"`.

**Comment by elias94** [comment]
Thanks for the explanation and the quick reply!
