### ISSUE TITLE
Add Html attributes to ReactRenderer

### ISSUE THREAD

**Issue by danarish4** [ueberdosis/tiptap#2502]
### What problem are you facing?

I use table extension and I want to create `nodeView` for table-cell
currently my custom-cell extension code looks like this:

```
export const TableCell = Node.create<TableCellOptions>({
  name: 'tableCell',

  content: 'block+',

  addAttributes() { .... },

  tableRole: 'cell',

  isolating: true,

  parseHTML() {.... },

  renderHTML({ HTMLAttributes }) {..... },

  addNodeView() {
     return ReactNodeViewRenderer(Cell, { as: 'td' });
   },

```

I need to add to the wrapper inside ReactNodeViewRenderer that rendered as `td` also HTML attributes of `rowSpan` & `colSpan` otherwise span won't work

### What’s the solution you would like to see?

ReactNodeViewRenderer can get props to put on the Tag element (such as rowSpan\rowSpan...)

### What alternatives did you consider?

I copied your wrapper and made the changes I need
This is the change I made in reactRenderer constructor (I pass `attributes` prop inside `option` object)

```
  constructor(
    component: ComponentType<R, P>,
    {
      editor,
      props = {},
      as = 'div',
      className = '',
      attributes,
    }: ReactRendererOptions
  ) {
    this.id = Math.floor(Math.random() * 0xffffffff).toString();
    this.component = component;
    this.editor = editor as ExtendedEditor;
    this.props = props;
    this.element = document.createElement(as);
    this.element.classList.add('react-renderer');

    if (className) {
      this.element.classList.add(...className.split(' '));
    }

// here I put the attributes on the element
    if (attributes) {
      Object.keys(attributes).forEach((attrKey) =>
        this.element.setAttribute(attrKey, attributes[attrKey])
      );
    }

    this.render();
  }
```

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by wengtytt** [comment]
I found that the className is an available option when use ReactNodeViewRenderer, but it's not added to the wrapper.

**Comment by bdbch** [comment]
I created a PR for this (see #3812) which for now takes attributes in form of a `Record<string, string>`. I'd like to expand that one later to actually pick the props of the `as` element so adding attributes is even easier - but Typescript is one hell of a thing and I couldn't figure out a quick solution for that.
