### ISSUE TITLE
@tiptap-pro/extension-details is buggy

### ISSUE THREAD

**Issue by lostdesign** [ueberdosis/tiptap#2503]
### What’s the bug you are facing?

By adding a new detail node, opening it, and adding text directly into it without any element below, you won't be able to add more than one line, and tiptap crashes. You need to remove all contents in order to be able to use the editor again.

It appears to only happen when the summary title is a single word - multiple words don't cause this error. If you add a detail node, while not opening it and adding an empty paragraph below it, a single word can be used as a summary which then also can be filled by more content that won't break the extension.

### How can we reproduce the bug on our side?

1) go to https://tiptap.dev/api/nodes/details
2) clear the example
3) use the `setDetail` enter a _single word_
4) click the open icon
4) start writing inside the detail block
5) hit enter multiple times, you will see an error in the console and won't be able to add more than one linebreak

### What did you expect to happen?

A singular summary title should not crash the editor/extension.

### Anything to add? (optional)

```
vendor.6c1cb5ec.js:5 Uncaught RangeError: Index 1 out of range for <details(detailsSummary("test"), detailsContent(paragraph("asdf"), paragraph))>
    at A.child (vendor.6c1cb5ec.js:5:26763)
    at zt.matchFragment (vendor.6c1cb5ec.js:5:46178)
    at Ne.contentMatchAt (vendor.6c1cb5ec.js:5:42387)
    at Enter (index.9b6663f2.js:1:7286)
    at vendor.6c1cb5ec.js:16:7838
    at ur.<anonymous> (vendor.6c1cb5ec.js:13:41976)
    at vendor.6c1cb5ec.js:13:11631
    at dt.someProp (vendor.6c1cb5ec.js:13:36384)
    at Yt.keydown (vendor.6c1cb5ec.js:13:11587)
    at HTMLDivElement.e.dom.addEventListener.e.eventHandlers.<computed> (vendor.6c1cb5ec.js:13:10177)
```
    
    
![detail-summary-bugged](https://user-images.githubusercontent.com/5164617/152874715-def8a7f8-4152-4fe2-a75f-d01f068cf6b1.gif)

<img width="1731" alt="Bildschirmfoto 2022-02-07 um 22 27 22" src="https://user-images.githubusercontent.com/5164617/152874742-bc16714d-f4f1-46c4-ac23-b789813a0dfe.png">

    

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Ooops. Fixed in the latest release ✌️

(This only happened if there was a single details node in the document)

**Comment by lostdesign** [comment]
@philippkuehn thanks for fixing that so quickly - is there any way we can check the latest release versions of pro packages?

**Comment by philippkuehn** [comment]
what do you mean with "check"? searching for new versions with npm or yarn should be fine. we also plan to show the current version numbers of the pro extension in the docs.
