### ISSUE TITLE
Copy-pasting newline doesn't show in editor

### ISSUE THREAD

**Issue by deadcoder0904** [ueberdosis/tiptap#2504]
### What’s the bug you are facing?

When I copy-paste 2 paragraphs with a newline, the TipTap editor removes it.

I was reading https://nav.al/the-returns-to-entrepreneurship & copy-pasted first 2 highlighted paragraphs into TipTap editor:

<img width="1114" alt="Screenshot 2022-02-08 at 1 08 41 PM" src="https://user-images.githubusercontent.com/16436270/152940089-e9731671-7f52-4199-8792-0a84e7679222.png">

The result looked like:

<img width="491" alt="Screenshot 2022-02-08 at 1 09 52 PM" src="https://user-images.githubusercontent.com/16436270/152940252-88840b17-3ee0-44ea-ad09-631bf409f48c.png">

I tried to copy-paste the same thing in [Typefully](https://typefully.com) & it shows it with a newline, unlike TipTap.

### How can we reproduce the bug on our side?

```tsx
import * as React from 'react'
import { useEditor, EditorContent } from '@tiptap/react'
import Document from '@tiptap/extension-document'
import Paragraph from '@tiptap/extension-paragraph'
import Text from '@tiptap/extension-text'
import { EditorView } from 'prosemirror-view'

import './styles.css'

EditorView.prototype.updateState = function updateState(state) {
  if (!this.docView) return // This prevents the matchesNode error on hot reloads
  this.updateStateInner(state, this.state.plugins !== state.plugins)
}

const App = () => {
  const [writer, setWriter] = React.useState('')

  const editor = useEditor({
    extensions: [Document, Paragraph, Text],
    content: '',
    autofocus: true,
    injectCSS: false,
    editorProps: {
      attributes: {
        class: 'focus:outline-none'
      }
    },
    parseOptions: {
      preserveWhitespace: true
    }
  })

  React.useEffect(() => {
    const onUpdateHandler = () => {
      console.log('onUpdateHandler')
      if (editor) {
        const html = editor.getHTML()
        setWriter(html)
      }
    }

    editor?.commands.setContent(writer)
    editor?.on('update', onUpdateHandler)

    return () => {
      editor?.off('update', onUpdateHandler)
    }
  }, [writer, editor])

  return (
    <div className="flex items-center flex-col h-screen bg-gray-900">
      <h1 className="text-gray-400 text-2xl mb-2">TipTap Newline error</h1>
      <EditorContent
        className="z-10 min-h-84 w-96 flex-1 resize-none overflow-y-auto border-2 border-red-500 bg-transparent text-white shadow-none outline-none focus:ring-0"
        placeholder="Write your draft here..."
        editor={editor}
      />
    </div>
  )
}

export default App
```

### Can you provide a CodeSandbox?

https://codesandbox.io/s/tiptap-newline-error-kpgm8?file=/src/App.tsx

### What did you expect to happen?

Newline will appear.

### Anything to add? (optional)

I also added `preserveWhiteSpace` as `true` but I'm not sure if it's needed but I tried to see if there was `preserveNewline` but there isn't.

I also checked docs, issues, & discussions but didn't see something regarding a newline.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
I don’t know what do you mean with "newline". There is no newline in your article. These are just two paragraphs with some margin. You probably want to add some CSS to your editor.

**Comment by deadcoder0904** [comment]
newline means `\n` or `<br />` in html.

if u see the image of the article there's clearly a line break. when i paste it, it doesn't show a line break.

**Comment by philippkuehn** [comment]
Do you see any newline (`\n` or `<br />`) here?

<img width="1294" alt="CleanShot 2022-02-08 at 13 56 35@2x" src="https://user-images.githubusercontent.com/2500670/152991452-ee594471-ce3e-48b3-8c92-b368ff99f78d.png">

**Comment by deadcoder0904** [comment]
nope, that's why i am asking, how do i add it?

bcz obviously when u copy-paste 2 paragraphs that contain a newline between them then `tiptap` needs to add a `<br />` to it.

that is the issue.

it's how copy-paste works in other editors like vscode or typefully. is this a bug with tiptap or i need to add something? if so, what should i add?

**Comment by philippkuehn** [comment]
Again, there is no newline in your copied HTML. There are two paragraphs. If you paste it into Tiptap there are still two paragraphs. Tiptap won’t change the structure of your pasted HTML.

But if you paste a newline, Tiptap will render a newline.

**Comment by deadcoder0904** [comment]
Well, then how do I see it in other editors like Typefully which uses Prosemirror.

If I copy the same thing in Typefully app, I get shown `<p>....</p><p><br />....</p>`, that's exactly how I want it too bcz at the end of the day other editors like Google Docs work like that too :)

**Comment by deadcoder0904** [comment]
Oh just learned that Typefully also uses Tiptap, damn. So I'm guessing how do they put `<br />` in there?

**Comment by philippkuehn** [comment]
Typefully doesn’t even create a `<br />`. It creates an empty paragraph instead.
ProseMirror is rendering a `<br class="ProseMirror-trailingBreak">` within empty text blocks but this is not part of the document. It’s like a decoration to be able to type within an empty paragraph. It disappears when you type within this paragraph.

<img width="305" alt="CleanShot 2022-02-09 at 11 58 27@2x" src="https://user-images.githubusercontent.com/2500670/153184815-447df7d2-9360-46ac-8f74-d3ffddbb4129.png">

Not sure why Typefully is creating an empty paragraph like this but this definitely is some custom logic.

By default, some other editors like plain ProseMirror, CKEditor and TinyMCE are doing exactly the same. There are no plans to change this behavior.

**Comment by deadcoder0904** [comment]
@philippkuehn I understand that there are no plans to change this behavior but where can I implement this? Is there a prop to set to `true`?

Is it a CSS class change bcz i tried `word-break` like Typefully but that doesn't work. I'm out of ideas on this one so would appreciate any help :)

**Comment by ngekoding** [comment]
I need this also.
