### ISSUE TITLE
Can put editor compatible content into clipboard and bypass paste rules

### ISSUE THREAD

**Issue by Luminqi** [ueberdosis/tiptap#2514]
### What’s the bug you are facing?

When I copied content from editor, I noticed that it actually copied the HTML and add special attribute data-pm-slice to mark this content copied from editor. 

Then I can programmatically put content with the same data-pm-slice attribute into the clipboard, then paste content to editor. It will not trigger extension paste rules, but will trigger parseHTML function.

Users can also do the same thing from the console panel in browser DevTool. So I need to write repetitive rules in parseHTML function to verify everything is right. 

### How can we reproduce the bug on our side?

Open DevTool Console Panel in Chrome and execute following codes:

```
function setClipboard(html) {
    const type = "text/html";
    const blob = new Blob([text], { type });
    const data = [new ClipboardItem({ [type]: blob })];
    navigator.clipboard.write(data).then(
        function () {
          console.log('success');
        },
        function (e) {
            console.log('failed', e);
        }
    );
}

setTimeout(() => setClipboard(`<meta charset='utf-8'><p data-pm-slice="">{{ your content }}</p>`), 3000)

Focus current window

Paste to editor
```

### What did you expect to happen?

I expect only content actually copied from editor will bypass paste rules. And when user mock the content programmatically, it should not be recognized as content copied from editor.

I am not sure if this is an issue or not. But it cause complex verify logic in parseHTML function. Because this content might come from user in an unexpected way.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
I'm not fully unterstand the issue. Paste rules ignores any HTML content that contains `data-pm-slice` since this is the only indication that this is copied from a ProseMirror editor, that’s correct.

If you want to mock the content programmatically, you can remove `data-pm-slice`, so paste rules will be triggered.

> But it cause complex verify logic in parseHTML function.

Can you explain what you need to do here and why?

**Comment by Luminqi** [comment]
@philippkuehn thank you for you reply. I mean if user programmatically mock the editor content and contains `data-pm-slice`, then we can not distinguish between the content actually copied from editor and the mock content. So if I render the custom `Node` like something `<span data-special="true">{{ complex content }}</span>`. And in parseHTML, I only check the `data-special` attribute is exist. Then the user can mock the node HTML but with the underlying content changed. And If I don't add extra verify logic. This will be rendered as the custom `Node` with wrong content.

**Comment by philippkuehn** [comment]
But why not removing that `data-pm-slice` in your programmatically created content?

**Comment by Luminqi** [comment]
User can do this kind of thing in console panel in DevTool which I can not control

**Comment by philippkuehn** [comment]
You can do even more bad things in the console. I don't think there is anything we can do about it.
