### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'characters')

### ISSUE THREAD

**Issue by ijcnvv** [ueberdosis/tiptap#2515]
### What’s the bug you are facing?

"@tiptap/starter-kit": "^2.0.0-beta.183",
"@tiptap/vue-3": "^2.0.0-beta.90",
"vue": "^3.2.30",

hey, I had got the tiptap warning `"editor.getCharacterCount()" is deprecated. Please use "editor.storage.characterCount.characters()" instead`, but when i tried to use it, I got `TypeError: Cannot read properties of undefined (reading 'characters')`

### How can we reproduce the bug on our side?

use "editor.storage.characterCount.characters()"  to get character count

### What did you expect to happen?

it works without errors

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by hanspagel** [comment]
You probably didn’t update all your dependencies. Would you mind to check that?

**Comment by philippkuehn** [comment]
I think you don’t have installed the `CharacterCount` extension: https://tiptap.dev/api/extensions/character-count
