### ISSUE TITLE
How to preserve editor state? 

### ISSUE THREAD

**Issue by sbcarp** [ueberdosis/tiptap#2522]
### What problem are you facing?

I'm making a chat app with tiptap editor, like Microsoft Teams.

Since there are more than one chat room in the app, I want to save current editor state when switching to another chat room.

Editor state is more than just content, it should also include history for undo and redo, state of extensions etc..

### What’s the solution you would like to see?

Is there a simple way to do it?

### What alternatives did you consider?

I've tried two methods in React

- Save `editor.view.state` and reapply it using `editor.view.updateState(props.editorState);`
It does work, but sometimes I get "Applying a mismatched transaction" and "Position X out of range" errors, couldn't figure it out
- Save the entire editor and reapply it in `<EditorContent editor={this.editor}>`
This doesn't work and always create a new editor in addition to existing one when I change `this.editor`

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by sbcarp** [comment]
> It is recommended to destroy and re-create the editor in such cases.

I tried to destroy and re-create the editor but still getting mismatched transaction errors sometimes.
Is this the right way doing it?
```
recreateEditor = () => {
    this.editor?.destroy();
    this.editor = new Editor({
      extensions: [
        StarterKit,
        Placeholder.configure({
          placeholder: this.props.placeholder,
        }),
        ...(this.props.extensions || []),
      ],
    });
    if (this.props.editorState) {
      this.editor.view.updateState(this.props.editorState);
    }
    this.editor.on('update', this.onChange);
    this.onChange();
  }

componentDidUpdate(prevProps: Readonly<IInputEditorProps>): void {
    if (prevProps.referenceId !== this.props.referenceId && this.editor.view.state !== this.props.editorState) {
      this.recreateEditor();
    }
 }

render() {
    return <EditorContent editor={this.editor} />;
  }
```

**Comment by philippkuehn** [comment]
Why do you want to store the `editorState` instead of the document?

**Comment by dannileb** [comment]
> Why do you want to store the `editorState` instead of the document?

I assume saving `editorState` instead of the document is necessary in order to also save the state of extensions

Is there currently any way to pass the existing state to the editor in tiptap?

Saving the state and then passing it to `editor.view.updateState()` in vanilla ProseMirror works without errors
