### ISSUE TITLE
Dragging a Custom Node creates a duplicate

### ISSUE THREAD

**Issue by jappyjan** [ueberdosis/tiptap#253]
I created a custom Image Node (with a Vue Component) to be able to create resizable images.
It all works fine, but when dragging / moving the image to another location in the document it creates a duplicate instead of moving the original...

`import {Node, Plugin} from 'tiptap';
import ResizableImageComponent from '@/components/Editor/ResizableImageComponent.vue';

export default class ResizableImage extends Node {
    public get name() {
        return 'resizableImage';
    }

    public get schema() {
        return {
            attrs: {
                src: {
                    default: null,
                },
                width: {
                    default: '400px',
                },
            },
            group: 'inline',
            inline: true,
            draggable: true,
            selectable: false,
            // parseDOM and toDOM is still required to make copy and paste work
            parseDOM: [{
                tag: 'img',
                getAttrs: (dom: any) => ({
                    src: dom.getAttribute('src'),
                    width: dom.getAttribute('width'),
                }),
            }],
            toDOM: (node: any) => ['img', {
                src: node.attrs.src,
                width: node.attrs.width,
            }],
        };
    }

    public commands({type}: { type: any }) {
        return (attrs: any) => (state: any, dispatch: any) => {
            const {selection} = state;
            const position = selection.$cursor ? selection.$cursor.pos : selection.$to.pos;
            const node = type.create(attrs);
            const transaction = state.tr.insert(position, node);
            dispatch(transaction);
        };
    }

    public get plugins() {
        return [
            new Plugin({
                props: {
                    handleDOMEvents: {
                        drop(view: any, event: any) {
                            const hasFiles = event.dataTransfer
                                && event.dataTransfer.files
                                && event.dataTransfer.files.length;

                            if (!hasFiles) {
                                return;
                            }

                            const images = (Array
                                .from(event.dataTransfer.files) as File[])
                                .filter((file) => (/image/i).test(file.type));

                            if (images.length === 0) {
                                return;
                            }

                            event.preventDefault();

                            const {schema} = view.state;
                            const coordinates = view.posAtCoords({left: event.clientX, top: event.clientY});

                            images.forEach((image) => {
                                const reader = new FileReader();

                                reader.onload = (readerEvent) => {
                                    const node = schema.nodes.resizableImage.create({
                                        src: (readerEvent.target as any).result,
                                    });
                                    const transaction = view.state.tr.insert(coordinates.pos, node);
                                    // noinspection JSIgnoredPromiseFromCall
                                    view.dispatch(transaction);
                                };
                                reader.readAsDataURL(image);
                            });
                        },
                    },
                },
            }),
        ];
    }

    // return a vue component
    // this can be an object or an imported component
    public get view() {
        return ResizableImageComponent;
    }
   }

`

**Comment by laurensiusadi** [comment]
I'm making custom TodoItem node, and experiencing same issue

**Comment by InevitableCuriosity** [comment]
How did you add the custom node to the project? Do you use some sort of a button bind, or call it programmatically?

**Comment by laurensiusadi** [comment]
@InevitableCuriosity is the question for me?
You can see my code here
Editor: https://github.com/laurensiusadi/vue-tiptap/blob/master/src/components/Editor.vue
Custom node: https://github.com/laurensiusadi/vue-tiptap/tree/master/src/components/editor

**Comment by Simon-Renault** [comment]
Faced the same issue with custom image by adding it through a custom button.

**Comment by philippkuehn** [comment]
Please provide a codesandbox

**Comment by jappyjan** [comment]
i add the image either through dragging it inside the editor from file explorer, or via a custom button and calling the command of the node.

both ways the behaviour stays the same...

**Comment by jappyjan** [comment]
i don't think it is a problem related to the way of how the node is beeing created, because the problem exists even after saving the editor content and reloading it in a new instance (no active node-creation)...

**Comment by pa-bouly** [comment]
Facing the same issue, any update on this ? :)

**Comment by zachzoup** [comment]
Here is a codesandbox for the issue, the image component is pretty much copied from the tiptap-extensions/image node - https://codesandbox.io/s/vue-f7ggr

Hopefully this isn't confusing, but I'm able to reproduce it pretty consistently by dragging the image slightly to the right, releasing the mouse button, and then clicking to the right of the image (not actually on the image) and immediately dragging in any direction. This is doing the same thing when dragging the Image node from tiptap-extensions as well.

**Comment by Sakessonholm** [comment]
I can reproduce it in the same way you describe above @zachzoup using the sandbox. @philippkuehn a dropbox has been provided by zachsoup above as you requested. Could you have a look?

**Comment by laurensiusadi** [comment]
@zachzoup @Sakessonholm I was unable to replicate. Can you make a screen recording?

**Comment by Sakessonholm** [comment]
Sure @laurensiusadi 
[https://screencast-o-matic.com/watch/cYVQlJvyHr](url)

**Comment by zachzoup** [comment]
@laurensiusadi hereis another recording [https://screencast-o-matic.com/watch/cYVQIMvysz](https://screencast-o-matic.com/watch/cYVQIMvysz)

**Comment by hanspagel** [comment]
The provided codesandbox doesn’t work at all for me. Probably it’s too old. I’m closing this here for now.

**Comment by henribru** [comment]
In our case this appears to have been caused by calling `editor.setContent` while the node was being dragged (i.e. after it was picked up and before it was dropped)

**Comment by markbulingit** [comment]
2024 bug still exists

**Comment by core-admin** [comment]
> I've been struggling with the same issue for several days! Can't find any solution. For the sandbox, you can even see the same behaviour in the official TipTap example using the custom vue component with drag and drop. I've shown the behavior in the video too. https://tiptap.dev/docs/editor/extensions/custom-extensions/node-views/vue#dragging
> 
>  Screencast.From.2025-03-03.16-35-22.webm

When dragging nodes, it should be a move, but in fact, a new element is created. I have been studying this problem all day today, and finally located that it is necessary to add the attribute 'data-drag-handle'. Adding this attribute has helped me solve this problem.

![Image](https://github.com/user-attachments/assets/c1a1b4fe-a53d-4a7f-ace6-bd8b52a7d16c)

**Comment by core-admin** [comment]
https://angelika.me/2023/02/26/how-to-add-editing-image-alt-text-tiptap/

**Comment by kamerat** [comment]
Thank you @core-admin for pointing me in the right direction 🙌 
As I did not extend the image component as you did, I found out you have to add `draggable: true` to the node options as well as the `data-drag-handle`
```js
export const CustomImage = Node.create({
  name: 'customImage',
  draggable: true, // <-- Add this line
...
```

**Comment by Philipinho** [comment]
Adding `data-drag-handle` to the nodeview as suggested by @core-admin fixed it for me.
