### ISSUE TITLE
Mention is missing trailing space in a empty editor

### ISSUE THREAD

**Issue by sbcarp** [ueberdosis/tiptap#2536]
### What’s the bug you are facing?

Mention is missing trailing space on the first click in a empty editor

### How can we reproduce the bug on our side?

1. Go to mention doc react/vue example: https://tiptap.dev/api/nodes/mention
2. Use Ctrl+A to select and delete all content
3. Type @ to show the mention list, use **Mouse** to select any mention
4. You will see there's no trailing space attached to the rendered mention node

### What did you expect to happen?

A trailing space should present

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by rfgamaral** [comment]
@sbcarp I was curious about this one, and I wasn't able to reproduce it myself:

![firefox_nMJJpaHtdP](https://user-images.githubusercontent.com/96476/154247912-7ef6e83e-19f3-42a5-a48a-c691f60ed03f.gif)

**Comment by rfgamaral** [comment]
Also, this might be a duplicate of https://github.com/ueberdosis/tiptap/issues/2114

**Comment by sbcarp** [comment]
> @sbcarp I was curious about this one, and I wasn't able to reproduce it myself:
> 
> ![firefox_nMJJpaHtdP](https://user-images.githubusercontent.com/96476/154247912-7ef6e83e-19f3-42a5-a48a-c691f60ed03f.gif) (Firefox)

That's interesting, looks like it's on Chrome only, yeah, it's duplicate sry
