### ISSUE TITLE
Can not parse multiple bold marks、italic marks in the same block ...

### ISSUE THREAD

**Issue by ljxok2001** [ueberdosis/tiptap#2543]
### What’s the bug you are facing?

Manually input more than one bold string  in the same block,  with the markdown syntax like `this is a line with **bold one** and  **bold two** !`, will see that only the first one `**bold one**` got parsed, and the second `**bold two**` would keep the raw string.

### How can we reproduce the bug on our side?

Manually input more than one bold string  in the same block,  with the markdown syntax like `this is a line with **bold one** and  **bold two** !`, will see that only the first one `**bold one**` got parsed, and the second `**bold two**` would keep the raw string.

### What did you expect to happen?

Should be able to parse multiple marks in the same block

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
I can't reproduce this in our demos. Feel free to re-open with a reproducable demo.
