### ISSUE TITLE
Side buttons on every node

### ISSUE THREAD

**Issue by ThomasKleinhans** [ueberdosis/tiptap#2548]
### What problem are you facing?

I'm trying to implement a Notion like side button system.  

Like this : 
![image](https://user-images.githubusercontent.com/34307673/154718274-d15bf442-b640-4e40-a9cc-42cee2275cd5.png)

I created a Vue component with a node-view-wrapper and a node-view-content with those buttons based on the example in the documentation. I extended every nodes in custom extensions that I want to have this little menu (Paragraph, Heading, List ...) and add the addNodeView method on each node with my custom component in it. It perfectly working with the paragraph node but it completly erase Heading and other nodes HTML when passing in it.

Example :
![image](https://user-images.githubusercontent.com/34307673/154719056-5e3a704a-7c33-4e9b-98d5-765014568b47.png)

Is that a tiptap limitation or did I do something wrong ?

### What’s the solution you would like to see?

Add a wrapper around a node (maybe add a method for that ?)

### What alternatives did you consider?

The alternative that i saw is to develop each node from scratch with this menu on it. But it seems very complicated for such a little feature.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
In this thread you can find some more inspiration for an alternative solution: https://github.com/ueberdosis/tiptap/issues/323
