### ISSUE TITLE
TextAlign justify doesn't work in Safari

### ISSUE THREAD

**Issue by ryanb** [ueberdosis/tiptap#2549]
### What’s the bug you are facing?

The TextAlign extension doesn't work in Safari (v14.1.1) for justify alignment. There's a note at the top of the extension docs mentioning an incompatibility with Firefox and `white-space: pre-wrap`, but no mention of Safari.

### How can we reproduce the bug on our side?

Go to the example at https://tiptap.dev/api/extensions/text-align in Safari, add some long text then click Justify.

### What did you expect to happen?

I expected text to be justified or for the documentation to be updated to mention Safari.

Is it possible to override the `white-space` style for the justify alignment in the Text Align extension?

### Anything to add? (optional)

<img width="745" alt="Screen Shot 15" src="https://user-images.githubusercontent.com/161/154748927-c6ad0ab1-6b2a-44c4-9ccb-7ce43809c2b6.png">

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by ryanb** [comment]
It looks like there are other issues with removing the `white-space` styling so that may not be an option. See further discussion here: https://github.com/ProseMirror/prosemirror/issues/857

**Comment by philippkuehn** [comment]
Oh this isn’t working in firefox too. Unfortunately these are browser bugs so we can’t do here anything :(

**Comment by ryanb** [comment]
@philippkuehn perhaps mention Safari near the top of [the documentation](https://tiptap.dev/api/extensions/text-align) like you do with Firefox?


<img width="754" alt="Screen Shot" src="https://user-images.githubusercontent.com/161/160443054-a909546c-11b6-4d67-a315-cd371e60d334.png">
