### ISSUE TITLE
Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by BrianHung** [ueberdosis/tiptap#2551]
### What’s the bug you are facing?

> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

### How can we reproduce the bug on our side?

Create a tiptap instance, and then hide it. Conceptually what happens is:

- `componentWillUnmount` in `EditorContent` removes `view.dom` from document, triggering a blur event which tiptap then creates a transaction for.
- Transaction is caught by `useEditor` and calls `forceUpdate`.

### Can you provide a CodeSandbox?

**Not** reproducible in https://codesandbox.io/s/serene-ully-dv2lhv

I think this is because the double `requestAnimationFrame` makes this bug extremely dependent on timing and code execution, making it hard to reproduce.

### What did you expect to happen?

Unsure of a correct answer here. The blur event is correct as an input element is removed from dom, but this conflicts with react as a component being unmounted should not update react state (call `forceUpdate`).

Possible solutions
- in `componentWillUnmount`, call `view.destroy()` before ProseMirror's `view.dom` is removed by tiptap. I believe this is the correct solution, even if the whole view construction process has to reoccur on show and hide, as we are using cleanup methods from ProseMirror.

### Anything to add? (optional)

![image](https://user-images.githubusercontent.com/15721634/154778393-05152fe5-4b3b-44f4-bf3d-1c522ae117e5.png)

https://github.com/ueberdosis/tiptap/blob/ab4a0e2507b4b92c46d293a0bb06bb00a04af6e0/packages/react/src/EditorContent.tsx#L70-L96

https://github.com/ProseMirror/prosemirror-view/blob/8f246f320801f8e3cac92c97f71ac91e3e327f2f/src/input.js#L41-L48

https://github.com/ueberdosis/tiptap/blob/e5c765c8e4a61f050d8b72cf550688cf890f0632/packages/core/src/extensions/focusEvents.ts#L26-L35

https://github.com/ueberdosis/tiptap/blob/ab4a0e2507b4b92c46d293a0bb06bb00a04af6e0/packages/react/src/useEditor.ts#L20-L26

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by BrianHung** [comment]
Having thought about this more, I believe initializing and destroying the editor within `useEditor` is the wrong approach with React. Initialization and destruction should instead occur within the `EditorContent` component, tying the editor with `view.dom`. 

`useEditor` under this approach would be a simple context hook, like in [slate](https://github.com/ianstormtaylor/slate/blob/main/packages/slate-react/src/hooks/use-slate.tsx).

**Comment by codemzy** [comment]
I just wanted to say thanks, as I was occasionally getting this error message and I figured it was somewhere in `useEditor` but you narrowing it down to the blur event helped me to fix it.

Now, before I know the editor will get removed from the dom, I call `editor.destroy()` (or you can call `view.destroy()` if you haven't saved the editor variable yet) and this destroys the editor first and stops the error.

Here's an example where I have multiple editors and I am deleting an editor when backspace is used and the editor is empty.

```js
editorProps: {
    handleKeyDown: function(view, event) {
        if (event.key === "Backspace" && view.state.doc.textContent.length === 0) {
            view.destroy(); // added this
            deleteEditor(id);
            return true;
        };
    }
},
```

Just thought I'd share incase it helps anyone else!
