### ISSUE TITLE
Can not set Bold or Italic in Code

### ISSUE THREAD

**Issue by minhlt-fa** [ueberdosis/tiptap#2563]
### What’s the bug you are facing?

Hi team, I have an issue when I use Extention Code to set a paragraph. Then I can not set Bold or Italic in Code

### How can we reproduce the bug on our side?

1. Highline a paragraph
2. Set block
3. Highline a text in that paragraph 
4. Set bold or set Italic

### Can you provide a CodeSandbox?

https://codesandbox.io/s/format-bold-and-inline-in-code-6en521?file=/src/App.vue

### What did you expect to happen?

The paragraph that I set code can set Bold or Italic

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by cadars** [comment]
You can extend the `code` mark with `code: false`:
https://tiptap.dev/api/schema#code

Then you could define the excludes attribute yourself:
https://tiptap.dev/api/schema#excludes

**Comment by gjdame** [comment]
@cadars 👋  This is something we would like to explore supporting in our editor as well, but Im unable to extend the mark to override the existing excludes using your suggestion above. Do I need to extend other marks that interact with the code as well?

**Comment by cadars** [comment]
> Do I need to extend other marks that interact with the code as well?

I don‘t think so… do you have an example in a CodeSandbox or else?

**Comment by gjdame** [comment]
@cadars ah okay go it working. 
`      Code.extend({
          excludes: "",
          code: false,
      }),`
      
      Needed specifically override the `excludes` instead of adding all marks to it (`marks: '_'`). The font size does not change when updating the heading, but I think I can solve that by updating the `parseHTML` function

**Comment by philippkuehn** [comment]
This is intended. By default we don’t support other marks within code marks. You can change that with extending the extension:

```js
Code.extend({ excludes: null })
```

**Comment by josephp27** [comment]
> This is intended. By default we don’t support other marks within code marks. You can change that with extending the extension:
> 
> ```js
> Code.extend({ excludes: null })
> ```

Is there a way to do this with CodeBlockLowlight? I dont believe theres an excludes when i extend

**Comment by evnp** [comment]
> This is intended. By default we don’t support other marks within code marks. You can change that with extending the extension:
> ```Code.extend({ excludes: null })```

As of v2.1.12 this causes at type error, `excludes: ""` is needed:
```javascript
Code.extend({ exitable: true, excludes: null })

2322: Type 'null' is not assignable to type 'string | ((this: { name: string; options: any; storage: any; parent: string | ... | undefined; editor?: Editor | undefined; }) => str
ing | undefined) | undefined'.
```
