### ISSUE TITLE
Fallback node for unsupported HTML tags

### ISSUE THREAD

**Issue by kristijan97** [ueberdosis/tiptap#2576]
### What’s the bug you are facing?

When I provide HTML string to the editor, it removes the unsupported HTML tags like img, script, (event custom tags in case of frontend frameworks).

### How can we reproduce the bug on our side?

Provide any HTML string which contains unsupported tags like img, script.

### What did you expect to happen?

I expected that those unsupported tags are NOT removed from the editor (because the same data is used to edit raw HTML in textarea). It should be either not displayed or display text if available inside that tag.

### Anything to add? (optional)

Maybe some sort of wildcard/fallback node?

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
This is by design. Tiptap (ProseMirror) is a semantic text editor and not an HTML editor. You can try to create something like a wildcard extension but this is nothing we will provide.

**Comment by kristijan97** [comment]
@philippkuehn do you have somewhere an example how to make wildcard extension? Thanks!

**Comment by kazzkiq** [comment]
> This is by design. Tiptap (ProseMirror) is a semantic text editor and not an HTML editor.

Not sure what *semantic* means in this context?

90%+ of internet users interact with social networks on a daily basis. Social posts are linked into many news websites, blogs, and CMS editors. And many of those social embeds make use of `<script>` tags.

It is really important for Tiptap to actually provide a way to embed such posts (or giving the devs low-level APIs to do so). Simply ignoring this behemoth of a need doesn't seems the right approach.
