### ISSUE TITLE
onUpdate fires before onCreate when using extension-collaboration

### ISSUE THREAD

**Issue by jamesopti** [ueberdosis/tiptap#2583]
### What’s the bug you are facing?

`onUpdate` fires before `onCreate` making it hard to know when the editor is truly initialized.

### How can we reproduce the bug on our side?

See this codesandbox: https://codesandbox.io/s/collab-cursor-update-user-olp3i?file=/src/Tiptap.tsx

### Can you provide a CodeSandbox?

https://codesandbox.io/s/collab-cursor-update-user-olp3i?file=/src/Tiptap.tsx

### What did you expect to happen?

I would expect that `onCreate` always fires first.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by jamesopti** [comment]
This is still an issue that I think should be fixed. Can we re-open?

**Comment by jamesschwindt** [comment]
Agreed, I'm experiencing this issue as well
