### ISSUE TITLE
Text selection misleading after applying style through bubble menu

### ISSUE THREAD

**Issue by VicFunas** [ueberdosis/tiptap#2585]
### What’s the bug you are facing?

When doing some action through bubble menu, the text selection afterwards seems wrong (extending towards the beginning)
- Only noticed when editor is not editable
- Only noticed when the selected text already had some "style" (bold, italic, color, mark, strikethrough, ...)

On tests, it's more visual, misleading the user, but the styling works fine (applies on the right text selection)

Is this a known issue?

https://user-images.githubusercontent.com/33663511/155712555-deb739ef-9822-4f90-8558-ca3438fb1b7e.mp4

### How can we reproduce the bug on our side?

Open the [sandbox](https://codesandbox.io/s/reverent-brown-3yskld?file=/src/App.vue)

- Select a snippet of text and apply style (for example, bold) to it
- Select a new snippet of text. The previous snippet must be included in this new snippet
- Apply style to this new snippet (for exemple, italic)
  - The text selection (visual) seems longer
- Remove the applied style
  - The text selection (visual) seems misplaced

### Can you provide a CodeSandbox?

https://codesandbox.io/s/reverent-brown-3yskld?file=/src/App.vue

### What did you expect to happen?

I would expect the text selection (visual) to be on the snippet I actually selected

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by rfgamaral** [comment]
> Only noticed when editor is not editable

I'm curious, why are you even allowing one to format text if the editor is not editable? I would simply disable the popover toolbar if `ediable: false`.

**Comment by VicFunas** [comment]
> > Only noticed when editor is not editable
> 
> I'm curious, why are you even allowing one to format text if the editor is not editable? I would simply disable the popover toolbar if `editable` = `false`.

@rfgamaral 
Hi Ricardo, 
In fact, I think I missed on passing the reason.

So, a little about our context:

We actually want to allow users to highlight the text.
- Each user can mark, highlight the snippet they consider more useful, interesting
- But none of them can change the content of the text
  - They would be more like readers, not contributors or owners of the content


Does it make sense?

**Comment by rfgamaral** [comment]
It does make sense, but I'm not sure how to help you any further. Good luck 👍

**Comment by VicFunas** [comment]
@rfgamaral (mentioning since you are marked as a contributor)

We've made a workaround by forcing clearing the text selection when applying a mark (highlight):
```
export const clearWindowSelection = () => {
  if (window.getSelection) {
    if (window.getSelection().empty) {
      // Chrome
      window.getSelection().empty()
    } else if (window.getSelection().removeAllRanges) {
      // Firefox
      window.getSelection().removeAllRanges()
    }
  } else if (document.selection && document.selection.empty) {
    // IE
    document.selection.empty()
  }
}
```

Does it make sense? Suggestion of another way?
