### ISSUE TITLE
Type of number is not allowed in text node

### ISSUE THREAD

**Issue by Duncank** [ueberdosis/tiptap#2586]
### What’s the bug you are facing?

We are using json content in the editors that we save via our API. When getting data from our API, all strings that are only numbers will be converted to numbers, which is causing `invalid text node` problems in the editor.

I am aware that this is primarily caused by the transformation of data types in our API, but we were wondering if this is something that possibly could be supported in tiptap.

### How can we reproduce the bug on our side?

This works
```js
{
    type: 'paragraph',
    content: [
        {
            type: 'text',
            text: '1 lorem ipsum',
         },
    ],
},
```

This doesn't. It logs `invalid content. passed value: .... Error: RangeError: Invalid text node in JSON` to the console.
```js
{
    type: 'paragraph',
    content: [
        {
            type: 'text',
            text: 123,
         },
    ],
},
```

### Can you provide a CodeSandbox?

Codesandbox was giving me errors so here is an example on Stackblitz:  
https://stackblitz.com/edit/vue-fby5cw?file=src%2FApp.vue

### What did you expect to happen?

I expected the numbers to show as text.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
No, this isn’t supported by ProseMirror. You must use strings for that.
