### ISSUE TITLE
`setContent()` doesn't allow for inserting of images

### ISSUE THREAD

**Issue by jianmin-chen** [ueberdosis/tiptap#2587]
### What problem are you facing?

I'm currently using `setContent()` to upload HTML to the editor. However, `setContent()` can't parse images and creates a trailing break for them instead.

### What’s the solution you would like to see?

Is it possible to change the configuration settings of `setContent()` so that it can parse `<img>` tags?

### What alternatives did you consider?

There's no other alternative for `setContent()` that allows for the parsing of `<img>` tags as far as I'm aware.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
It’s probably this limitation: https://github.com/ueberdosis/tiptap/issues/1206

**Comment by paraslamsong** [comment]
Any solution?
I am working with base64 image and am not able to populate editor with image.
Do I need to use url instead of base64?

**Comment by paraslamsong** [comment]
For me using innerHtml solved the issue but this is not ideal solution

  ```
 <EditorContent
            editor={editor}
            dangerouslySetInnerHTML={{
              __html: content,
            }}
          />
```
