### ISSUE TITLE
No cursor before and after inline nodes

### ISSUE THREAD

**Issue by cseufert** [ueberdosis/tiptap#2591]
### What’s the bug you are facing?

Unable to place cursor before or after inline nodes (or between). I have tried all combinations of settings for atom, inline, draggable, allowGapCursor. I don't think this is an underlying issue with prose-mirror itself.

### How can we reproduce the bug on our side?

Both the gapcursor demo and the image demo have this problem in Google Chrome. Try and cursor to before the image on the same paragraph as the image. And if you cursor down/right you cant get to the end of the document reliably.

https://tiptap.dev/api/extensions/gapcursor
https://tiptap.dev/api/nodes/image

### Can you provide a CodeSandbox?

The example code on the docs has the very same issue

### What did you expect to happen?

The cursor should be able to go before or after inline nodes, if you look at https://bangle.dev/ (another prosemirror based editor framework) the image blocks there can have the cursor before or after, or even in between.

It's a little hard to see, but you can cursor into the image and out of it no problems.

### Anything to add? (optional)

![demo-gif](https://user-images.githubusercontent.com/1734519/156079096-2904962c-14b9-40e4-af60-6a88340ccd4a.gif)

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Bangle is using inline images by default. You can do this with Tiptap too:

```js
Image.configure({ inline: true })
```

Cursor handling is sometimes a bit tricky with atom nodes in some browsers ([there are some browser bugs](https://github.com/ProseMirror/prosemirror/issues?q=is%3Aissue+is%3Aopen+cursor)).

**Comment by xmsz-stu** [comment]
Node with inline=true no working
![image](https://github.com/ueberdosis/tiptap/assets/139225486/11400cc6-180d-4746-b34b-379cfd0b558b)
no cursor
