### ISSUE TITLE
Typography: Allow overriding replacements

### ISSUE THREAD

**Issue by Haraldson** [ueberdosis/tiptap#2598]
### What problem are you facing?

In order to support multiple languages and their individual typographic rules, it would be nice to be able to override replacements. Straight double quotes (`"`) to curly double quotes (`“`) makes sense in English, but in Norwegian I would prefer the straight opening quote to turn into double angle quotes (`«`) instead.

### What’s the solution you would like to see?

I tried reading available documentation, then look through the source code, and discovered an existing prop/option named `replaceWith`. It would be nice if that prop could be sent in using `Typography.configure()` somehow. Below is a couple of ways this could be achieved:

```javascript
Typography.configure({
    openDoubleQuote: {
        replaceWith: formatMessage({
            id: 'quote_double_open',
            defaultMessage: '“'
        })
    },
    closeDoubleQuote: formatMessage({
        id: 'quote_double_close',
        defaultMessage: '”'
    })
})
```

### What alternatives did you consider?

I guess I could roll my own extension, but I’d much prefer a Typography extension to be language-aware, since typography is tied to languages and not a global standard.

### Are you sponsoring us?

- [x] Yes, I’m a sponsor. 💖

**Comment by Haraldson** [comment]
I still need this.

**Comment by bdbch** [comment]
Hey @Haraldson! I'll take it into our list of features planned for the future. Thanks for your request.
