### ISSUE TITLE
Saving doc with only image from clipboard

### ISSUE THREAD

**Issue by ArZargaryan** [ueberdosis/tiptap#2609]
### What’s the bug you are facing?

Editor returns an empty string as value, if there is only an image(pasting from clipboard).
But if you add any character, then everything is OK, the editor sees the image.

![image](https://user-images.githubusercontent.com/70432795/157845629-eec09e9b-c597-42c2-9885-8228ba5a9dad.png)
![image](https://user-images.githubusercontent.com/70432795/157845734-ccd183f1-0d09-4c65-ae7a-4c4a55800d66.png)

### How can we reproduce the bug on our side?

Sandbox: https://codesandbox.io/s/zen-currying-gkiegs?file=/src/App.vue

### What did you expect to happen?

I want that the editor will see pasted images without any character

### Anything to add? (optional)

Thank you.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
This is an issue within your `onUpdate` method. You check for `text.trim()` which is always empty if there is a single image in the document.
