### ISSUE TITLE
`prosemirror-model` is fully included `extension-table` dist files

### ISSUE THREAD

**Issue by aguingand** [ueberdosis/tiptap#2624]
(Fixed by https://github.com/ueberdosis/tiptap/pull/2622)

### What’s the bug you are facing?

In `extension-table/dist/tiptap-extension-table.*.js` files, `prosemirror-model` is fully included in the file and not as external import.

### How can we reproduce the bug on our side?

Look at  `extension-table/dist/tiptap-extension-table.*.js` files.

### What did you expect to happen?

Expect `prosemirror-model` to be imported as as external dependency (e.g `import * from 'prosemirror-model`).

### Anything to add? (optional)

I think  it's because `extension-table` has `"prosemirror-model"` missing in the package.json.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by cadars** [comment]
This PR would fix it?  https://github.com/ueberdosis/tiptap/pull/2622

**Comment by aguingand** [comment]
this issue is fixed with https://github.com/ueberdosis/tiptap/commit/d2e00ad7827fcc5ae6af8edbd79043c6f74f866e, thank you.
