### ISSUE TITLE
Visible caret and text selection in scrollable div with contenteditable="true" on iOS Safari in the hidden content part

### ISSUE THREAD

**Issue by martinkomitsky** [ueberdosis/tiptap#2629]
### What’s the bug you are facing?

There is a case when the editor is used with some defined `max-height` and `overflow-y: auto` which causes the editor's div to become scrollable. On iOS Safari (both real device and simulator) the caret and the text selection becomes visible even after the content is hidden after a scroll. I guess, this is a native iOS bug as I was able to reproduce this behaviour on plain div without any editor lib.

The easiest and most obvious thing any developer would do is add a `overflow: hidden;` to the parent container, but sadly, this is not working there. Unfortunately, there is no info on the net about this bug and possible workarounds, so I would be glad to see any idea how to solve this.

<img width="487" alt="image" src="https://user-images.githubusercontent.com/14847018/158799368-1f5d3058-d215-4f53-ab12-65f978ac9387.png">

<img width="469" alt="image" src="https://user-images.githubusercontent.com/14847018/158799658-a11f8e66-bd8b-4663-ac76-1941f9fc192b.png">

### How can we reproduce the bug on our side?

https://user-images.githubusercontent.com/14847018/158798870-fc98108e-b11c-4e19-92c0-9f28250e9607.mov

### Can you provide a CodeSandbox?

https://tiptap.dev/ – It reproduces on the live demo

### What did you expect to happen?

Not to see the caret and the text selection in the hidden part of the content.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Yeah, the caret is kind of buggy on iOS. And the demo is also very hacky (nested iframes). In a "normal" app you probably don't have these problems.
