### ISSUE TITLE
Unable to disable paste rules for images

### ISSUE THREAD

**Issue by smbenedetti** [ueberdosis/tiptap#2630]
### What’s the bug you are facing?

I'm trying to disable pasting images directly in the editor. I've tried both:
```
disableInputRules: [Image, 'image'],
disablePasteRules: [Image, 'image'],
```

and tried also to configure the image extension, and to handle it inside 

```
handleDOMEvents: {
  paste: (view, e) => {
  },
  },
```

the latest was the closest I got from a success, but I couldn't find any property that would help to recognize when it's an image being pasted.

### How can we reproduce the bug on our side?

- Install starterKit & image extension;
- Disable paste rules;
- Try to paste any image from computer or internet

### Can you provide a CodeSandbox?

https://codesandbox.io/s/muddy-fog-kw49ym?file=/src/App.vue

### What did you expect to happen?

I'd expect nothing to happen. So that users could paste other content and use the menu item to actually insert images.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by rfgamaral** [comment]
Would be nice if you could share your solution so anyone with the same/similar problem could draw inspiration from.

**Comment by tramng2** [comment]
how can you solve this?

**Comment by santutu** [comment]
my solution

```js
import {Extension} from '@tiptap/core'
import {Plugin, PluginKey} from 'prosemirror-state'
import {articleImageClient} from "../../Libraries/Clients/ArticleImageClient";

function getFileFromClipboardEvent(e: ClipboardEvent): File[] {
    let items = e.clipboardData?.items;
    let files: File[] = []
    if (items) {
        for (let i = 0; i < items.length; i++) {
            const file = items[i].getAsFile();
            if (!file) continue
            files.push(file)
        }
    }

    return files;
}

export const EventHandler = Extension.create({
    name: 'eventHandler',
    addProseMirrorPlugins(this) {
        const self = this;
        return [
            new Plugin({
                key: new PluginKey('eventHandler'),
                props: {
                    handleClick(view, pos, event) { /* … */
                    },
                    handleDoubleClick(view, pos, event) { /* … */
                    },
                    handlePaste(view, event, slice) {

                        const images = getFileFromClipboardEvent(event).filter((file) => file.type.indexOf('image') !== -1)
                        if (images.length === 0) return

                        //interact your server
                        articleImageClient.upload(images).then(articleImages => {
                            for (const articleImage of articleImages) {
                                self.editor.commands.setImage({src: articleImage.url, title: articleImage.id})
                            }

                        })

                    },
                    // … and many, many more.
                    // Here is the full list: https://prosemirror.net/docs/ref/#view.EditorProps
                },
            }),
        ]
    },
})

```
 allowBase64 : false in your tiptap image extention.
```js

 Image.configure({
            allowBase64: false,
            inline: true,
            HTMLAttributes: {
                class: 'hover:border hover:border-accent cursor-pointer'
            }
        }),
```

**Comment by codemzy** [comment]
For the original issue of disabling paste rules for images, I found this works in [editorProps](https://tiptap.dev/api/editor#editor-props)

```js
editorProps: {
  transformPastedHTML(html) {
    return html.replace(/<img.*?>/g, "");
  },
},
```

This will remove any images pasted in from html content (this will also stop you being able to duplicate images in the editor which is what I needed but might not be ideal if you do want to be able to do that).
