### ISSUE TITLE
Cannot paste the text over limit

### ISSUE THREAD

**Issue by FA-NganNTV** [ueberdosis/tiptap#2642]
### What’s the bug you are facing?

I have a issue of Character count:
 - When I paste 1 text over limit, the editor not import

### How can we reproduce the bug on our side?

1. I limit editor is imported 100,000 characters.
2. I paste text over 100,000 character, the editor not import.
Note: You can use textExample for debug.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/character-count-isse-elm2gz?file=/src/App.vue

### What did you expect to happen?

I expect when I paste one text over limit, editor import the correct character limit and cuts the remainder at the back

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by broom9** [comment]
We encountered this issue as well. Pasting a long text over size limit appears as if the editor is not working. Please consider this improvement for the character count extension.
