### ISSUE TITLE
Unset Header Function

### ISSUE THREAD

**Issue by CBusta182** [ueberdosis/tiptap#2643]
### What problem are you facing?

Currently, in the Header extension, there is no way for us to unset the header of some selected text without using the toggleHeader() method. This becomes a problem when a user is trying to go back to the default paragraph settings but doesn't know the level of header they're using. 

### What’s the solution you would like to see?

Can you make an unsetHeader() function where it would set the header tags back to a simple <p> tag?

### What alternatives did you consider?

Allow for a level 0 in the header extension which would unset the header tags. 

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by deathg0d** [comment]
It would be nice to have the feature. But for the time being here's how I solved it:

```
onClick={() => {
  const level = editor.getAttributes("heading").level;
  level && level > 0
    ? editor
        .chain()
        .focus()
        .toggleHeading({
          level: level,
        })
        .run()
    : "";
}}
```

**Comment by FayazRafeek** [comment]
I was able to worked around this issue by using the **setParagraph()** function.

`   const setHeading = (level: HeaderLevel) => {
		if(level === 0) {
			editor.chain().focus().setParagraph().run();
			return;
		}

		editor.chain().focus().toggleHeading({ level }).run();
	};
`
