### ISSUE TITLE
Placeholder not rendering

### ISSUE THREAD

**Issue by sellsjonathan** [ueberdosis/tiptap#2659]
### What’s the bug you are facing?

When the editor is empty, either initially, or after deletion, no placeholder is displayed to the user.

A paragraph node is added with the appropriate classes, and a `data-placeholder` as set by my configuration, however, there is no displayed placeholder for the user.  The Paragraph tag just contains an empty `<br/>`

![image](https://user-images.githubusercontent.com/8787299/160528186-a3337f09-4de2-4f2f-b512-3ed09db1f0ce.png)

### How can we reproduce the bug on our side?

Set up basic editor, use `@tiptap/extension-placeholder` as per docs

### What did you expect to happen?

The placeholder text gets displayed when there is no content.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by cadars** [comment]
Placeholder text is displayed via a pseudo element in CSS, have a look at the demo setup: https://embed.tiptap.dev/preview/Extensions/Placeholder

**Comment by KarolMilewski** [comment]
add some CSS to your component
```css
/* Placeholder (at the top) */
.ProseMirror p.is-editor-empty:first-child::before {
  content: attr(data-placeholder);
  float: left;
  color: #adb5bd;
  pointer-events: none;
  height: 0;
}

/* Placeholder (on every new line) */
/*.ProseMirror p.is-empty::before {
  content: attr(data-placeholder);
  float: left;
  color: #adb5bd;
  pointer-events: none;
  height: 0;
}*/
```

**Comment by sellsjonathan** [comment]
Oh wow, I was trying to hack it via this type of approach, didn't realize it's how they want us to actually render it.

Does this seem a little hacky though at first glance? What benefit does this have vs, a default display through just the `PlaceHolder.configure`.

At the very least I feel this should be made a little more clear in the docs.  I completely missed the styles tab in the example myself at 1am last night.

Appreciate the replies everyone.  Thanks.

**Comment by drummerjolev** [comment]
Any guidance on how to style the placeholder with Tailwind?

I'm using this:
```javascript
Placeholder.configure({
  placeholder,
  emptyNodeClass:
    'first:before:text-gray-400 first:before:float-left first:before:content-[attr(data-placeholder)] first:before:pointer-events-none',
}),
```

The placeholder works but the cursor isn't placed at the beginning of the placeholder text:
<img width="401" alt="Screenshot 2022-05-02 at 17 40 42" src="https://user-images.githubusercontent.com/5412193/166290875-916e7064-4219-4a5d-a79e-aacb9e0988e1.png">

**Comment by larsdjursner** [comment]
> Any guidance on how to style the placeholder with Tailwind?
> 
> I'm using this:
> 
> ```js
> Placeholder.configure({
>   placeholder,
>   emptyNodeClass:
>     'first:before:text-gray-400 first:before:float-left first:before:content-[attr(data-placeholder)] first:before:pointer-events-none',
> }),
> ```
> 
> The placeholder works but the cursor isn't placed at the beginning of the placeholder text: <img alt="Screenshot 2022-05-02 at 17 40 42" width="401" src="https://user-images.githubusercontent.com/5412193/166290875-916e7064-4219-4a5d-a79e-aacb9e0988e1.png">

Did you manage to find a solution? 
Adding "first:before:h-0" to emptyNodeClass worked for me.

**Comment by sellsjonathan** [comment]
I've seen a few people with this issue but for me with standard config, cursor shows up at beginning of the input.

![image](https://user-images.githubusercontent.com/8787299/169118363-d9096654-a0fb-436e-81b2-f55db9468525.png)

```
/* Placeholder (at the top) */
.part3-rich-text p.is-editor-empty:first-child::before {
	color: #adb5bd;
	content: attr(data-placeholder);
	float: left;
	height: 0;
	pointer-events: none;
}
```

**Comment by drummerjolev** [comment]
> > Any guidance on how to style the placeholder with Tailwind?
> > I'm using this:
> > ```js
> > Placeholder.configure({
> >   placeholder,
> >   emptyNodeClass:
> >     'first:before:text-gray-400 first:before:float-left first:before:content-[attr(data-placeholder)] first:before:pointer-events-none',
> > }),
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The placeholder works but the cursor isn't placed at the beginning of the placeholder text: <img alt="Screenshot 2022-05-02 at 17 40 42" width="401" src="https://user-images.githubusercontent.com/5412193/166290875-916e7064-4219-4a5d-a79e-aacb9e0988e1.png">
> 
> Did you manage to find a solution? Adding "first:before:h-0" to emptyNodeClass worked for me.

I haven't but I'll try your method! Thanks @larsdjursner. In the meantime I dropped the Tailwind approach and added the relevant classes to the vanilla CSS file.

**Comment by lucasmotta** [comment]
Just sharing my tailwind fix - I'm using absolute positioning :

```js
Placeholder.configure({
  placeholder,
  emptyEditorClass:
    'cursor-text before:content-[attr(data-placeholder)] before:absolute before:top-2 before:left-2 before:text-mauve-11 before:opacity-50 before-pointer-events-none',
})

**Comment by rizkimcitra** [comment]
> Just sharing my tailwind fix - I'm using absolute positioning :
> 
> ```js
> Placeholder.configure({
>   placeholder,
>   emptyEditorClass:
>     'cursor-text before:content-[attr(data-placeholder)] before:absolute before:top-2 before:left-2 before:text-mauve-11 before:opacity-50 before-pointer-events-none',
> })
> ```

thanks man, I was confused why my tailwind style `(inside tailwind.css)` doesn't work, but applying it to `emptyEditorClass` works fine

**Comment by koffietiger** [comment]
> add some CSS to your component
> 
> ```css
> /* Placeholder (at the top) */
> .ProseMirror p.is-editor-empty:first-child::before {
>   content: attr(data-placeholder);
>   float: left;
>   color: #adb5bd;
>   pointer-events: none;
>   height: 0;
> }
> 
> /* Placeholder (on every new line) */
> /*.ProseMirror p.is-empty::before {
>   content: attr(data-placeholder);
>   float: left;
>   color: #adb5bd;
>   pointer-events: none;
>   height: 0;
> }*/
> ```

To add to this, if you just wanted to show all available placeholders by default, you could use the following CSS selector:
```
.ProseMirror [data-placeholder]::before
```

**Comment by coolcorexix** [comment]
> Oh wow, I was trying to hack it via this type of approach, didn't realize it's how they want us to actually render it.
> 
> Does this seem a little hacky though at first glance? What benefit does this have vs, a default display through just the `PlaceHolder.configure`.
> 
> At the very least I feel this should be made a little more clear in the docs. I completely missed the styles tab in the example myself at 1am last night.
> 
> Appreciate the replies everyone. Thanks.

this should be mentioned in the doc, the scss file in the example is easy to skip 🤦

**Comment by koffietiger** [comment]
@coolcorexix Agreed! Submitted a PR. #3711 👍

**Comment by rlawrence89** [comment]
Just Add the the custom css to the global css file for tailwinds.


```css
@tailwind base;
@tailwind components;
@tailwind utilities;



/* Custom CSS Needed for TipTap PlaceHolder */
.ProseMirror p.is-editor-empty:first-child::before {
  color: #adb5bd;
  content: attr(data-placeholder);
  float: left;
  height: 0;
  pointer-events: none;
}
```

**Comment by akselipalmer** [comment]
> Just sharing my tailwind fix - I'm using absolute positioning :
> 
> ```js
> Placeholder.configure({
>   placeholder,

>   emptyEditorClass:
>     'cursor-text before:content-[attr(data-placeholder)] before:absolute before:top-2 before:left-2 before:text-mauve-11 before:opacity-50 before-pointer-events-none',
> })
> ```
# Cursor Positioning looks off... (Tailwind)
![Screenshot (72)](https://github.com/ueberdosis/tiptap/assets/16160255/fda5cbb1-a7b1-4e11-9e57-1fb15dd318da)

### Fix by changing `before:top-2 before:left-2` to `before:top-3 before:left-3`

![Screenshot (73)](https://github.com/ueberdosis/tiptap/assets/16160255/e5e4b378-6659-4627-a677-a3dc1877b27f)

### your class should now look like this: 
 ```js
Placeholder.configure({
   placeholder: "add your placeholder text here",
   emptyEditorClass:
      'cursor-text before:content-[attr(data-placeholder)] before:absolute before:top-3 before:left-3 before:text-mauve-11 
      before:opacity-50 before-pointer-events-none',
})
```

**Comment by mateusPPinh** [comment]
> add some CSS to your component
> 
> ```css
> /* Placeholder (at the top) */
> .ProseMirror p.is-editor-empty:first-child::before {
>   content: attr(data-placeholder);
>   float: left;
>   color: #adb5bd;
>   pointer-events: none;
>   height: 0;
> }
> 
> /* Placeholder (on every new line) */
> /*.ProseMirror p.is-empty::before {
>   content: attr(data-placeholder);
>   float: left;
>   color: #adb5bd;
>   pointer-events: none;
>   height: 0;
> }*/
> ```

thank you babe!!! you save my life

**Comment by hadiqaiser** [comment]
> ```js
> before:content-[attr(data-placeholder)]
> ```

I used this and i face no weird issues like all other are facing. It is basically conversion of this style into classes

`"before:text-muted before:content-[attr(data-placeholder)] before:float-left before:pointer-events-none before:h-0"`

**Comment by happyrw** [comment]
> add some CSS to your component
> 
> ```css
> /* Placeholder (at the top) */
> .ProseMirror p.is-editor-empty:first-child::before {
>   content: attr(data-placeholder);
>   float: left;
>   color: #adb5bd;
>   pointer-events: none;
>   height: 0;
> }
> 
> /* Placeholder (on every new line) */
> /*.ProseMirror p.is-empty::before {
>   content: attr(data-placeholder);
>   float: left;
>   color: #adb5bd;
>   pointer-events: none;
>   height: 0;
> }*/
> ```

thanks

**Comment by ethantrang** [comment]
<img width="445" alt="Image" src="https://github.com/user-attachments/assets/6bcb7712-6280-4897-9696-b2bd928ef8fd" />

Anyone getting this issue with nodes like bullet lists, checkboxes, etc 

```
const placeholder = Placeholder.configure({
  placeholder: ({ node, pos }) => {
    if (node.type.name === 'heading') {
      if (pos === 0) {
        return 'Untitled Document'
      }
      return 'Heading'
    }

    return 'Start writing or type / or highlight text...'
  },
  emptyNodeClass:
    'cursor-text before:content-[attr(data-placeholder)] before:absolute before:left-1 before:text-gray-300 before-pointer-events-none',
})
```

**Comment by waynesbrain** [comment]
In v3 with the trailingBreak extension enabled, I wasn't able to get the Placeholder extension working at all - it wouldn't even add the data attribute required for the styling to work.

I think it was because of the trailing break, since the `<p>` is not really empty since it contains a `<br class="ProseMirror-trailingBreak">`, so I removed Placeholder completely and got this working instead:

```scss
:global(.tiptap > p:first-child:has(br.ProseMirror-trailingBreak:first-child)::before) {
  color: #adb5bd;
  content: "Add your text here...";
  float: left;
  height: 0;
  pointer-events: none;
}
```

**Comment by ScorpyG** [comment]
@ethantrang for the duplicated placeholder text. Have you found the solution for that? I'm experiencing the same issue. I don't think TailwindCSS v4 is playing well with this.
