### ISSUE TITLE
Algolia seems to have an empty index

### ISSUE THREAD

**Issue by jonassiewertsen** [ueberdosis/tiptap#2660]
### What’s the bug you are facing?

The search is not showing any results. I would guess that there is a problem with the indexing.

![Bildschirmfoto 2022-03-29 um 08 29 57](https://user-images.githubusercontent.com/38906163/160547901-3020d5d6-331f-4486-b9a1-96a76aea4a71.png)

### How can we reproduce the bug on our side?

1. Command + K
2. Type anything into the search

### What did you expect to happen?

I would love to see search results 😊

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by psychonetic** [comment]
Having the same issue. But it seems like there is a config issue, because the agolia url has an undefined:

 https://undefined-1.algolianet.com/
 
 that's what I am seeing in the console.

**Comment by amursky** [comment]
up

**Comment by scottsidwell** [comment]
It looks like the `@docsearch/js` integration is missing the `appId`, hence why the URL includes undefined.

**Comment by mkriegeskorte** [comment]
Thanks for reporting this issue. We’re looking into it.

**Comment by patrickbaber** [comment]
@scottsidwell Thanks for the hint. Fixed
