### ISSUE TITLE
Attribute defaults as functions

### ISSUE THREAD

**Issue by dougalg** [ueberdosis/tiptap#2661]
### What problem are you facing?

I would like to be able to provide a generator function for the `default` property when defining an attribute for an extension. Once possible usage would be if you wanted to have a unique `id` added to a certain mark.

### What’s the solution you would like to see?

The ability to provide a generator function as a default for attributes. For example:

```
Link.extend({
	addAttributes() {
		return {
			id: {
				default: UUID.v4(),
				parseHTML: (el: HTMLElement) => el.id || getLinkId(),
			},
		};
	},
});
```

### What alternatives did you consider?

I can't think of any useful alternatives at the moment.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
This is a limitation of ProseMirror. But there is a [Unique ID extension](https://tiptap.dev/api/extensions/unique-id) you can use.

**Comment by dougalg** [comment]
Hi @philippkuehn thanks for the update!

**Comment by jasontlouro** [comment]
This is really the accepted solution? Use a paid plugin just to be able to have a generator function for attribute defaults?
