### ISSUE TITLE
BubbleMenu prop "tippyOptions.delay" is not work

### ISSUE THREAD

**Issue by Darmody** [ueberdosis/tiptap#2662]
### What’s the bug you are facing?

We want to prevent bubble menu from showing too quickly when selection is changing.

We tried  adding `delay` to `tippyOptions`, but it wasn't work.

### How can we reproduce the bug on our side?

```tsx
    <TiptapBubbleMenu
      tippyOptions={{ placement: 'top-start', maxWidth: '500px', delay: [1000, 0] }}
      shouldShow={shouldShow}
      editor={editor}>
        {... menu content}
    </TiptapBubbleMenu>
```

### Can you provide a CodeSandbox?

https://codesandbox.io/s/dazzling-dawn-j1uvc4?file=/src/App.js

### What did you expect to happen?

`delay` prop works correctly.

### Anything to add? (optional)

I'm a member of Brickdoc which is the sponsor.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by svenadlung** [comment]
Since BubbleMenu uses `trigger: 'manual'` some tippy options are not working as expected.

**Comment by varun-r-boop** [comment]
Will we be addressing this issue ? 🥲

**Comment by ipranay** [comment]
I'm looking for a fix for this as well. Any workarounds?

**Comment by benjang032** [comment]
Also looking for a fix to this

**Comment by benjang032** [comment]
found somewhat of a workaround: in case useful

        <FloatingMenu
            editor={editor}
            tippyOptions={{
                duration: 100,
                onMount: (instance) => {
                    instance.popper.style.opacity = '0'
                },
                onShow: (instance) => {
                    setTimeout(() => {
                        instance.popper.style.opacity = '1'
                        instance.popper.style.transition = 'opacity 100ms'
                    }, 1000)
                }
            }}
        >

uses onMount and onShow to control opacity
