### ISSUE TITLE
Character Count Editing over the Limit

### ISSUE THREAD

**Issue by jhull** [ueberdosis/tiptap#2674]
### What problem are you facing?

Just updated to TipTap2 to be able to use CharacterCount extension - absolutely love it! Beautiful improvements all around.

The problem is that I can't add text to content (from an API request) and still allow the user to edit. Edits are dead until they get under the limit.

### What’s the solution you would like to see?

Is there a way we could allow users to write passed the limit, but then still be able to edit (similar to Twitter where you can go over, but then can't save without).

I guess I could do this manually, but wondering if there's a way to do it with the extension...

### What alternatives did you consider?

Manually, I guess I would remove the extension, and just check the count on my own, then when it goes over, add in warnings, etc. Which is likely what I'll do unless there's some cool TipTap version of this.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Hey, thanks for this feature request. I think this is out of scope of this package since saving the editor state is very individual. Best way to do this is some custom logic because right now the biggest part of the extension is preventing the input over the limit.
