### ISSUE TITLE
NodeViewContent generates an unnecessary div

### ISSUE THREAD

**Issue by anton-liubushkin** [ueberdosis/tiptap#2675]
### What’s the bug you are facing?

I'm using React and working on a custom extension for tables and encountered that the NodeViewContent component always creates a nested div element.

![Screen Shot 2022-04-04 at 12 54 24 AM](https://user-images.githubusercontent.com/5649032/161450336-4e078246-245f-44e2-932c-98a6a5294c5c.png)

↓

![Screen Shot 2022-04-04 at 12 55 04 AM](https://user-images.githubusercontent.com/5649032/161450352-dea65c6b-8c3d-4ada-9296-0aaf9e60a171.png)

### How can we reproduce the bug on our side?

1. [Create a node view with React](https://tiptap.dev/guide/node-views/react) or add the Node view to a table extension
3. Use `NodeViewContent` to render child content

```
export const TableComponent: FC<NodeViewProps> = (props) => {
 /* Some sort of code */
  return (
    <table>
      <NodeViewContent as="tbody" />
    </table>
  )
}
```

### What did you expect to happen?

I would like to avoid unnecessary elements in the DOM.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
Duplicate of https://github.com/ueberdosis/tiptap/issues/1527

**Comment by anton-liubushkin** [comment]
@philippkuehn, if I understand correctly, there is no way to get rid of the internal div element?

`<NodeViewContent as="table">`
converts into
```javascript
<table as="table" data-node-view-content="" style="white-space: pre-wrap;">
  <div style="white-space: inherit;"> // <-- This ugly wrapper
    /* content */
  </div>
</table>
```

**Comment by henrykuzmick** [comment]
@philippkuehn I don't think this should be closed? #2213 doesn't seem to fix the unnecessary div problem.

This causes a number of issues.

Let's say I want to add some controls around a table. I could extend the Table plugin and add `addNodeView`.

Inside of the component used I'd render some control handles and `<NodeViewContent as="table" />` in the middle.

This in turn breaks the structure of the table and most of the commands from the Table extension.

**Comment by sradu** [comment]
I'm running into too. Any chance this will get merged soon?

**Comment by levi-putna** [comment]
Beyond tables, this also creates issues when you want to use a CSS grid layout on the children.

You develop an extension and add some controls that enable you to manage the grid layout of your component. You apply your grid class to the NodeViewContent, <NodeViewContent className="grid grid-cols-12 gap-4" />.

Then, an inner div is added, and instead of the grid classes applying to the children, they are applied to the inner div breaking the layout. 

<div class="grid grid-cols-12 gap-4" data-node-view-content="" style="white-space: pre-wrap;">
    <div style="white-space: inherit;"> // <-- This ugly div wrapper again.
        <h1 padding="0" span="10" class="col-span-10">Sample Heading</h1>
        <p padding="0" span="10" class="col-span-2">This is some placeholder text...</p>
    </div>
</div>

**Comment by ludusrusso** [comment]
@levi-putna I have a similar problem, did you find a way to fix this?

**Comment by Index24** [comment]
@levi-putna hi! I'm faced with exactly the same problem. Need to manage dynamically spacing between children, but double wrappers pretending. 
How did you solve the problem?

**Comment by mweidner037** [comment]
> Beyond tables, this also creates issues when you want to use a CSS grid layout on the children.
> 
> You develop an extension and add some controls that enable you to manage the grid layout of your component. You apply your grid class to the NodeViewContent, `<NodeViewContent className="grid grid-cols-12 gap-4" />`.
> 
> Then, an inner div is added, and instead of the grid classes applying to the children, they are applied to the inner div breaking the layout.
> 
> ```
> <div class="grid grid-cols-12 gap-4" data-node-view-content="" style="white-space: pre-wrap;">
>     <div style="white-space: inherit;"> // <-- This ugly div wrapper again.
>         <h1 padding="0" span="10" class="col-span-10">Sample Heading</h1>
>         <p padding="0" span="10" class="col-span-2">This is some placeholder text...</p>
>     </div>
> </div>
> ```

I also encountered this when I switched from using a plain node (renderHTML output) to a ReactNodeView. A workaround is to apply the grid settings with a child combinator.

```tsx
// React node view...
// This gets rendered as a <div className="column-container"> containing ANOTHER div.
<NodeViewContent className="column-container" />
```

```css
/* Apply grid settings to the interior div. */
.column-container > div {
  display: grid;
  grid-template-columns: minmax(0, 1fr) minmax(0, 1fr);
  gap: 1rem;
}
```
