### ISSUE TITLE
'/r/n' and '/n' not works as expected

### ISSUE THREAD

**Issue by oliver1chen** [ueberdosis/tiptap#2683]
### What’s the bug you are facing?

Since I already define a custom paragraph node and set 'whitespace' to 'pre'.
Also, for the parseHTML section in the node and the paresOption in the Tiptap initialization, I use the 'preserveWhitespace' : 'full'.
In my editor, I set the initial content to `<p>aaa \n aaa \r\n aaa</p>`. It looks fine at first.
But when I type update the editor content by entering any key at the end of the content, The newline from the '\n' and '\r\n' disappear. 

### How can we reproduce the bug on our side?

Follow the CodeSandbox link

### Can you provide a CodeSandbox?

https://codesandbox.io/s/thirsty-solomon-617muq?file=/src/components/Tiptap.vue

### What did you expect to happen?

I expect the newline will always keep.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by philippkuehn** [comment]
That’s not supported. You should use hardbreaks instead (`<p>aaa <br> aaa <br> aaa</p>`)

**Comment by oliver1chen** [comment]
I wonder why the newline is displayed at first but it vanishes after update the content?

**Comment by oliver1chen** [comment]
Update the codeSandBox.
[https://codesandbox.io/s/thirsty-solomon-617muq?file=/src/components/Tiptap.vue](https://codesandbox.io/s/thirsty-solomon-617muq?file=/src/components/Tiptap.vue)
In the paragraph node declaration, I set 'whitespace' to 'pre'.
But it shows 'normal' from the editor schema.
Why is the setting for 'whitespace' is changed?

**Comment by tsl1127** [comment]
> That’s not supported. You should use hardbreaks instead (`<p>aaa <br> aaa <br> aaa</p>`)

1、have the same problem
2、In the process of using 'insertContentAt', if there is \n\n in the parameter value, how to solve it? @philippkuehn
