### ISSUE TITLE
Home/End buttons don't move the cursor to the start/end of the text line

### ISSUE THREAD

**Issue by rfgamaral** [ueberdosis/tiptap#2685]
### What’s the bug you are facing?

A GIF is worth a thousand words...

Here's the correct behavior on ProseMirror when I press the Home/End buttons:
![PowerToys_nLzUakpn1o](https://user-images.githubusercontent.com/96476/161796409-6c3a5d0d-ca30-4f2a-ae29-82512fcc772c.gif)

### How can we reproduce the bug on our side?

If you try the same thing on Tiptap's default example, Home/End sends you to the start/end of the paragraph node, not the text like like ProseMirror does:
![PowerToys_B535p4Lsa9](https://user-images.githubusercontent.com/96476/161796860-7e8f8aa6-8c01-43bf-a249-7394255a7318.gif)

### What did you expect to happen?

I expect Home/End buttons to work like in the ProseMirror demo.

That's how the browser `<textarea>` works, that's how Microsoft Word / Google Docs / Dropbox Paper works, and probably many other editors like Tiptap (I tried Slate, and it worked as expected).

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖 _(on behalf of Doist)_

**Comment by BrianHung** [comment]
https://github.com/ProseMirror/prosemirror-commands/commit/20371c58b83945a7504aa04c05b4a55b9b004af7

Relatively simple fix: just remove Home and End keybindings in the pcKeymap as ProseMirror did.

https://github.com/ueberdosis/tiptap/blob/ab4a0e2507b4b92c46d293a0bb06bb00a04af6e0/packages/core/src/extensions/keymap.ts#L61-L65

**Comment by rfgamaral** [comment]
Hum... Now I'm wondering why this behavior was introduced in Tiptap? It's not the standard behavior anywhere...

However, those keybindings are built-in, what's the best way to remove them from my side? 🤔

**Comment by BrianHung** [comment]
> However, those keybindings are built-in, what's the best way to remove them from my side? 🤔

Copy paste https://github.com/ueberdosis/tiptap/blob/main/packages/core/src/extensions/keymap.ts but remove those two lines, then include that file in the `Extensions` prop. Set `enableCoreExtensions=false` and include the other core extensions.

**Comment by rfgamaral** [comment]
Thank you, I'll look into it soon. Although I was hoping for a less intrusive workaround. I'll do a more deep investigation tomorrow. Thanks once again.

**Comment by philippkuehn** [comment]
It seems like ProseMirror removed that binding a few weeks ago: https://github.com/ProseMirror/prosemirror-commands/commit/20371c58b83945a7504aa04c05b4a55b9b004af7

**Comment by rfgamaral** [comment]
@philippkuehn The current Tiptap behavior doesn't seem like the standard behavior for any other editor that I've tried, even for word processing editors like Google Docs, Dropbox Paper, and Microsoft Word. Do you think we could have those bindings removed from Tiptap as well?

For more context, we have **a lot** of user reports saying that Home/End buttons no longer work as they expect, so this is definitely an issue for users. But only for Windows users, because the issue does not exist for macOS users. Although typical Apple keyboards don't have Home/End buttons, Apple users with PC keyboards don't have this problem because the Home/End keybindings are only being overwritten for PC users, which is inconsistent.

What do you think?

**Comment by scottsidwell** [comment]
In an attempt to drive this bug to resolution, I've created a PR that mirrors the ProseMirror change and removes the Home/End keybindings from the pc keymaps.

Users that relied on this behaviour can use the exported `this.editor.commands.selectTextblockStart()` / `this.editor.commands.selectTextblockEnd()` and a custom extension to achieve this non-standard behaviour.

If we haven't reached consensus on this change, then feel free to ignore. Just raising the PR in case this is all that's missing to resolve the issue.

**Comment by bdbch** [comment]
Thanks @scottsidwell!
