### ISSUE TITLE
can() and commands returns true inside a codeBlock when they shouldn't

### ISSUE THREAD

**Issue by clibu** [ueberdosis/tiptap#2702]
### What’s the bug you are facing?

When you have text inside a codeBlock node, commands such as bold, italic et.all. return true for ``editor.can().toggleBold()`` and ``editor.commands.toggleBold()`` et.all. when in fact they cannot be used. 

It seems to me that these restrictions inside codeBlock nodes are unnecessary and unwanted. That is you should be able to use Bold, set a Link etc. inside codeBlocks. 

This maybe an unfortunate Prosemirror restriction. Either ``editor.can().xyz()`` etc. need to return false, or preferably these commands work as expected.

### How can we reproduce the bug on our side?

Start a codeBlock, enter some text, select a word and press Mod-B and nothing happens.

### What did you expect to happen?

Commands such as Bold etc. to work inside codeBlock's or can() to return false.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by clibu** [comment]
HTML does not prevent you from having formatting or links inside <code> tags so why should we here.

I often include links inside code comments and these are currently lost. And as for formatting the code block with syntax highlighting uses formatting.

**Comment by animify** [comment]
We could add a preference in the configuration for code blocks themselves to cover both scenarios, but for now wouldn't the easiest fix be to return `false` for `can()` commands inside the code block? Currently facing the exact same issue building a bubble menu to show/hide options such as bold when selecting text in a code block

**Comment by clibu** [comment]
@rfgamaral I've dug into this a bit more and it appears to me the issue is that ``setMark()`` does not check whether the specified mark can in fact be set. 

Until this is resolved I'm using the following code to disable marks commands that can't be used inside a code block.
````
        if ( schema.nodes?.codeBlock )      // if the codeBlock extension is present
            // if the `mark` is in the codeBlock schema's markSet then all good
            if ( !schema.nodes.codeBlock.markSet.find( markType => markType.name == name ) )
                // else if a codeBlock is active (cursor is within it) then disable the cmdItem.
                if ( editor.isActive( schema.nodes.codeBlock.name ) )
                    enabled = false

````

As for allowing certain marks in a code block that turned out to be as simple as:
````
const CustomCodeBlock = CodeBlock.extend( {
    marks: 'bold italic highlight link'    // enable whatever marks we want to allow. By default Pmr codeblock has no marks. ref: https://tiptap.dev/api/schema#marks
})
````

**Comment by rfgamaral** [comment]
@clibu Thanks for sharing. Quick question, where exactly are you adding that first piece of code? Can you share an example with more context, please?

**Comment by clibu** [comment]
@rfgamaral I have a function ``cmdState()`` that returns various bits of info about the various TipTap etc, commands I'm using. This code is part of that function. In turn it is called when a toolbar btn is clicked etc. 

The Toolbar is Prosemirror Plugin and it calls my ``update()`` function whenever the ``state`` changes. This ``update()`` function calls ``cmdState()`` and enables / disables buttons based on the code above along with the usual ``can()`` code.

ref: https://prosemirror.net/docs/ref/#state.PluginSpec.view^returns.update 

HTH.

**Comment by rfgamaral** [comment]
Thanks, your example code helped improve the formatting toolbar on our side 👍
