### ISSUE TITLE
RangeError: Adding different instances of a keyed plugin (plugin$)

### ISSUE THREAD

**Issue by hanye9895** [ueberdosis/tiptap#2706]
### What’s the bug you are facing?

tiptap load error when refresh page
but with open another router and forward to tiptap2 page, will not show this error

### How can we reproduce the bug on our side?

codesanbox seems work
only error in local env

### Can you provide a CodeSandbox?

codesanbox seems work

### What did you expect to happen?

load tiptap2 with no error when refresh the page

### Anything to add? (optional)

![111](https://user-images.githubusercontent.com/68373171/163029137-5f28ba37-cd3a-4a5c-bd1b-4f4c076815a7.png)
when I debug into it, seems plugin key duplicate to $6
and I simple trigger get will fix it
![Screen Shot 2022-04-13 at 2 22 21 AM](https://user-images.githubusercontent.com/68373171/163029317-25725482-3f0f-436f-ad4e-7c53321ba6b9.png)
but that seems not pretty

seems similar to #2150 #1473 #1274 , but not same exactly

operating system: macOS  10.13.6
browser: Chrome Version 100.0.4896.75 (Official Build) (x86_64)
mobile/desktop: Desktop
tiptap version: 2

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Could you provide a reproducible demo / example via CodeSandbox please?

**Comment by Miruzz** [comment]
I have very same bug

**Comment by hanye9895** [comment]
> Could you provide a reproducible demo / example via CodeSandbox please?

I've try for a while, but can't reproduce. Can I upload a local zip to reproduce?

**Comment by hanye9895** [comment]
Oh, I found that error can't appear any more (with previous code)
And plugin key no duplicate when init. So weird~

So I close this issue for now~

**Comment by SalahAdDin** [comment]
We are having this bug for `Gapcursor` extension.
How are the key calculated?

**Comment by CapitaineToinon** [comment]
> We are having this bug for `Gapcursor` extension. How are the key calculated?

I had the same issue with gap cursor, I wrote a possible solution in [#2150](https://github.com/ueberdosis/tiptap/issues/2150)

**Comment by andi23rosca** [comment]
For anyone still struggling, disabling drop and gap cursor works, but also check out the second fix I wrote here
https://github.com/andi23rosca/tiptap-solid/issues/1#issuecomment-1584294074
