### ISSUE TITLE
Focus/cursor lost on marks within links

### ISSUE THREAD

**Issue by mbrodala** [ueberdosis/tiptap#2708]
### What’s the bug you are facing?

Given there's a link with additional nested marks like bold or italic:

```
<p><a href="https://example.org">Regular, <strong>Bold</strong> and <em>Italic</em></p>
```

Clicking on **Bold** or _Italic_ here does a few things:

1. The focus of the content editable area is lost
2. There is no text cursor anymore
3. Toggling these marks is not possible, very likely due to the first two issues

### How can we reproduce the bug on our side?

Open the linked CodeSandbox, then put a link on/around the *tiptap* text:

![image](https://user-images.githubusercontent.com/5037116/163209198-ca1a10e5-fabd-40b9-a906-89e0bedd0ddf.png)

Now click on **tiptap** and see the focus being lost:

![image](https://user-images.githubusercontent.com/5037116/163209271-2df7772d-110b-4b7b-a7f0-059aaf526c26.png)

### Can you provide a CodeSandbox?

https://codesandbox.io/s/naughty-hopper-0lj11x

### What did you expect to happen?

The focus should stay unchanged on the contenteditable area, the text cursor should be placed where clicked.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
@mbrodala Do you use Firefox? Seems to be related to #2710 - thanks for reporting!

**Comment by mbrodala** [comment]
No, I'm using Vivaldi (thus Blink rendering engine).
