### ISSUE TITLE
Cursor disappears when ProseMirror placed in shadow DOM / slot

### ISSUE THREAD

**Issue by KonnorRogers** [ueberdosis/tiptap#2710]
### What’s the bug you are facing?

When TipTip / ProseMirror are placed in the ShadowDOM the cursor disappears when the editor runs an action.

### How can we reproduce the bug on our side?

Code sandbox can be found here: https://codesandbox.io/s/patient-fast-7ycsco?file=/src/index.js

Start editing and then click one of the toolbar buttons and the cursor will disappear.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/patient-fast-7ycsco?file=/src/index.js

### What did you expect to happen?

I expected the cursor to keep blinking at the end of the node.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
This seems to be an Firefox-only issue, right? Thanks for reporting this issue!

**Comment by ParamagicDev** [comment]
@bdbch I'm noticing editing as a whole appears to be borked. Would it be worth trying to recreate with ProseMirror itself? Or digging into prosemirror-view?

**Comment by bdbch** [comment]
@ParamagicDev it would help us to find out if it's a Tiptap or Prosemirror error. If you find time for that let me know!

**Comment by ParamagicDev** [comment]
@bdbch ill see what I can do!

I know this isn't the place, but I just put the final pieces on a tip-tap grab and go editor!

https://tip-tap-element.vercel.app/

(got a lot to cleanup source code wise, but finally got a demo out there)

**Comment by ParamagicDev** [comment]
Bump. Sorry, without a computer for a little bit and will hopefully get to be able to make a prose mirror version repro soon.

**Comment by ParamagicDev** [comment]
@bdbch as far as I can tell this may actually be a dupe.

https://github.com/ProseMirror/prosemirror/issues/1113

**Comment by KonnorRogers** [comment]
For anyone else who hits this heres the secret sauce:

https://github.com/KonnorRogers/ash-editor/blob/547927784e72990d0a1b0879c062ad3318bef94e/src/extensions/attachment.ts#L608-L628

**Comment by KonnorRogers** [comment]
> > For anyone else who hits this heres the secret sauce:
> > https://github.com/KonnorRogers/ash-editor/blob/547927784e72990d0a1b0879c062ad3318bef94e/src/extensions/attachment.ts#L608-L628
> 
> Awesome. Still works! Has this issue been fixed or are you still using this workaround? [@KonnorRogers](https://github.com/KonnorRogers)

For a number of reasons, the editor I created no longer uses the shadow DOM for Contenteditable for backwards compatibility reasons, so TLDR: I have no clue.
