### ISSUE TITLE
Floating menu shows when `editor.isEditable == false`

### ISSUE THREAD

**Issue by nitipit** [ueberdosis/tiptap#2715]
### What’s the bug you are facing?

Floating menu shows when `editor.isEditable == false`

### Which browser was this experienced in? Are any special extensions installed?

Google Chrome v100

### How can we reproduce the bug on our side?

Call `editor.setEditable(false)` then click on empty content, then the floating-menu will show up.

### Can you provide a CodeSandbox?

Condition check here in `public shouldShow`

https://github.com/ueberdosis/tiptap/blob/c9eb6a6299796450c7c1cfdc3552d76070c78c65/packages/extension-floating-menu/src/floating-menu-plugin.ts#L44

Should add `|| !editor.isEditable`
```
if (
    !view.hasFocus()
    || !empty
    || !isRootDepth
    || !isEmptyTextBlock
    || !editor.isEditable  // <- Add this line.
)
```

### What did you expect to happen?

Floating menu should not show when `editor.isEditable == false`

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by AlonBru** [comment]
If you need an urgent fix, try removing the suggestion props, this seems to be rid of the menu
```
 Mention.configure( {
          // suggestion: getSuggestion( members || [] ),
          HTMLAttributes: {
            class: 'mention',
          },

        } )
```

**Comment by nitipit** [comment]
Hi, is anyone here ?
The fixing code I've provided is straight forward, I can make a pull request if the maintainer of the project agree.

**Comment by bdbch** [comment]
Hey @nitipit I'll take a look at this issue asap. Sorry for the long wait time!

**Comment by nitipit** [comment]
@bdbch Thanks

**Comment by Nicolas-Dolan** [comment]
@bdbch I'm having a great time with tiptap and appreciate all the hardwork you guys have put into it. Unfortunately this fix has broken a feature in my build. Is there now any way to show the bubble menu if you do want to display it while the editor is not editable? Seems like the kind of feature that would be useful in many situations, not just while editing.

**Comment by bdbch** [comment]
@Nicolas-Dolan not really - could you create an issue so we can reimplement this as an option?
