### ISSUE TITLE
setmark 'fontSize' not working in vue

### ISSUE THREAD

**Issue by sk31park** [ueberdosis/tiptap#2730]
### What’s the bug you are facing?

I want to make font-size option button.
But there is no guide about this.
So I found solution in stackoverflow.
But It also not work..

this is my code.
```
this.editor.chain().focus().setMark('textStyle', { fontSize: `${item}px` }).run()
```
when I click fontSize button nothing happen..

https://user-images.githubusercontent.com/25639099/165530460-b26f4551-a4c8-4a7b-9f4d-3d84d8ff5446.mp4

How can I make this?

### Which browser was this experienced in? Are any special extensions installed?

I using edge browser.

### How can we reproduce the bug on our side?

...

### What did you expect to happen?

...

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by yaakov123** [comment]
You can follow this answer for things to work. That's how I'm doing it.

https://stackoverflow.com/a/70759102/5597242

**Comment by sk31park** [comment]
Now I'm use nuxt engine.
Are there any examples related to nuxt?

In nuxt, I use 'this.editor.chain().focus().setMark('textStyle', { fontSize: `${item}px` }).run()' function.
But It's not working..

**Comment by msahajwani** [comment]
Have you included the TextStyle extension in your editor?

Import the extension:

`import TextStyle from '@tiptap/extension-text-style'`

And then add it to your editor's list of extensions.

```
const editor = useEditor({
    extensions: [
      TextStyle,
      // your other extensions...
      ]
)}
```

**Comment by raarts** [comment]
@sk31park It works for me. As does the answer pointed to by @yaakov123 (after adding some typescript).

**Comment by sk31park** [comment]
I import TextStyle extentions.
But I'm still not working.

@raarts can you share me a nuxt example

It's my code.

```
//...
import TextStyle from '@tiptap/extension-text-style'
//...

export default {
  name: 'HtmlEditor',
  props: ['data'],
  components: {
    EditorContent
  },
  data() {
    return {
      editor: null,
    }
  },
  methods: {
    selectFont: function(item) {
      this.editor.chain().focus().setMark('textStyle', { fontSize: }).run()
    }
  },
  mounted() {
    this.editor = new Editor({
      content: `${this.data.value}`,
      extensions: [
        //...
        TextStyle,
       //...
      ]
    })
    this.editor.on('update', ({ editor }) => {
      this.data.value = editor.getHTML()
    })
  },
  beforeDestroy() {
    if(this.editor) this.editor.destroy()
  }
}

```

**Comment by msahajwani** [comment]
How are you calling the `selectFont `method? Can you create a codesandbox for this?

**Comment by raarts** [comment]
@sk31park I don't know use nuxt, I use React. But anyway, I implemented the extension as shown here: https://stackoverflow.com/a/72063300/1561489, and added  `TextStyle, FontSize,` to the extension list. 

After that I could call:  `editor.commands.setFontSize('44pt');` and it just worked. Though you need to select with the mouse first.

**Comment by sk31park** [comment]
@msahajwani 

this is my sample code

https://codesandbox.io/embed/morning-violet-58f64y?fontsize=14&hidenavigation=1&theme=dark

**Comment by msahajwani** [comment]
Hmm, you haven't created the FontSize extension. You need to create a custom font size extension and add it to the list of extensions for it to work. The code for the custom extension is given in the StackOverFlow link you shared above. 

https://stackoverflow.com/questions/70564092/tiptap-font-size-react/70759102#70759102

See the answer that is marked as correct.

**Comment by sk31park** [comment]
Wow! It work!
Thanks a lot everyone. 👍

@raarts @msahajwani

**Comment by gregveres** [comment]
> Hmm, you haven't created the FontSize extension. You need to create a custom font size extension and add it to the list of extensions for it to work. The code for the custom extension is given in the StackOverFlow link you shared above.
> 
> https://stackoverflow.com/questions/70564092/tiptap-font-size-react/70759102#70759102
> 
> See the answer that is marked as correct. Unfortunately, that code is for react. You will need to do a bit of rewriting for it to work in vue.

Can't the textStyle extension be used directly? I am trying the exact same thing as the original poster. I have added the TextStyle extension to my editor but when I use: 

```
<v-list-item
        v-for="size in sizes"
        :key="size"
        @click="
          editor
            .chain()
            .focus()
            .setMark('textStyle', {
              fontSize: `${size}px`
            })
            .run()
        "
        :class="{
          active: editor.isActive('textStyle', { fontSize: `${size}px` }),
        }"
      >
        <v-list-item-content>{{ size }}</v-list-item-content>
      </v-list-item>
```

the setMark does nothing. I know that TextStyle is installed correctly in the editor because I am using the exact same approach with the FontFamily  extension, except that instead of using the TextStyle extension directly in that case I am using the FontFamily call. 

I don't understand why the TextStyle doesn't work directly like this. It seems like overkill to have to create an extension for this. I was assuming that the TipTap authors didn't include FontSize because it was so easy to implement using TextStyle directly without having to create a custom extension. But if everybody has to create their own custom extension for font size, then why not include it?

**Comment by gregveres** [comment]
I have created a gist with the version of font-size that I am using. 
It is an exact copy of the current font-family extension with font-family changed to font-size. 

https://gist.github.com/gregveres/64ec1d8a733feb735b7dd4c46331abae
