### ISSUE TITLE
TipTap Extension: Error: There is no mark type named 'textStyle'.

### ISSUE THREAD

**Issue by msahajwani** [ueberdosis/tiptap#2733]
### What’s the bug you are facing?

I got a tiptap extension code to add classes and tried to replicate it in my react project. However, I keep getting the error "Error: There is no mark type named 'textStyle'. " I've added the code in this gist. Can you help with what I'm missing?

I've created a gist with the code:
https://gist.github.com/msahajwani/b9fdeac46e1db94d26af2306c1c49095

### Which browser was this experienced in? Are any special extensions installed?

Chrome

### How can we reproduce the bug on our side?

Gist for the code:
https://gist.github.com/msahajwani/b9fdeac46e1db94d26af2306c1c49095

### What did you expect to happen?

When the extension command is called from the menu.

### Did you update your dependencies?

- [x] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by msahajwani** [comment]
This is resolved.

**Comment by jambonn** [comment]
@msahajwani you can share solution?

**Comment by davidmr163** [comment]
@jambonn This happened to me, I only had to add the TextStyle import to the main editor extensions and started working! :)

**Comment by jambonn** [comment]
@davidmr163 Yes, I understand the problem. Thank you!
