### ISSUE TITLE
TipTap Custom Extension: Adding Multiple Classes

### ISSUE THREAD

**Issue by msahajwani** [ueberdosis/tiptap#2741]
### What’s the bug you are facing?

Adding Multiple Classes to a Node through custom extension.

### Which browser was this experienced in? Are any special extensions installed?

Chrome

### How can we reproduce the bug on our side?

I created a custom extension to add classes to nodes:

```
import { Extension } from '@tiptap/core'

export const NodeClass = Extension.create({
  name: 'nodeClass',
  addOptions() {
    return {
      types: ['heading','paragraph'],
    }
  },
  addGlobalAttributes() {
    return [
      {
        types: this.options.types,
        attributes: {
          nodeClass: {
            default: null,
            renderHTML: (attributes) => {
              if (!attributes.nodeClass) {
                return {};
              }
              return {
                class: attributes.nodeClass
              };
            },
            parseHTML: (element) => (
              element.classList.value
            )
          },
        },
      },
    ]
  },
  addCommands() {
    return {
      setNodeClass: (nodeClass) => ({commands}) => {
        return this.options.types.every(type => commands.updateAttributes(type, { nodeClass: nodeClass }))
      },
      unsetNodeClass: () => ({ commands }) => {
        return this.options.types.every(type => commands.resetAttributes(type, 'nodeClass'))
      }
    };
  },
})
```

With the extension, I can pass commands from menu such as the following to add classes to the paragraph node:

```
<button onClick={() => editor.chain().focus().setNodeClass("text-5xl").run()}>Big Size</button>

<button onClick={() => editor.chain().focus().setNodeClass("bg-gray-500").run()}>Gray BG</button>
```

The individual commands work fine, and the respective class is added to the node/paragraph. However, it's not appending the classes. Instead, it is overwriting the existing class. So, on click of the button, all the existing classes are deleted and the new class gets added. 

### What did you expect to happen?

So, if the p tag was like:

`<p class="my-custom-class font-bold">My Paragraph</p>`

And if I press the button to add the class text-5xl,

`<button onClick={() => editor.chain().focus().setNodeClass("text-5xl").run()}>Big Size</button>`

It is resulting in:

`<p class="text-5xl">My Paragraph</p>`

The actual output I want is:

`<p class="my-custom-class font-bold text-5xl">My Paragraph</p>`

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by msahajwani** [comment]
I was able to resolve this by getting the existing node attributes using the following command.

`editor.getAttributes('paragraph')`

Then it is just a matter of merging the classes with the new class.

**Comment by jambonn** [comment]
> I was able to resolve this by getting the existing node attributes using the following command.
> 
> `editor.getAttributes('paragraph')`
> 
> Then it is just a matter of merging the classes with the new class.

@msahajwani  You can share code resolve issue? Thank!
