### ISSUE TITLE
Omit default undefined attributes added in addGlobalAttributes 

### ISSUE THREAD

**Issue by schostac** [ueberdosis/tiptap#2744]
### What problem are you facing?

When I create a custom extension and use `addGlobalAttributes` to add an attribute with its default value `undefined`, nodes, e.g. in JSON output, still contain this attribute despite values being undefined.

### What’s the solution you would like to see?

I'd expect the same behaviour as for attributes with default value `undefined` specified in nodes. Namely, if value is `undefined` , attribute is omitted, in particular in JSON output.

### What alternatives did you consider?

Not using addGlobalAttributes and repeating the same attributes in each node type. 

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by LeeTommy916** [comment]
No sorry I'm.not a sponsor sorry I couldn't be
