### ISSUE TITLE
Backspacing through a nested list doesn't work properly

### ISSUE THREAD

**Issue by dilizarov** [ueberdosis/tiptap#2747]
### What’s the bug you are facing?

When backspacing through a list and not starting at the last item, it clears the current item and the text of it's parent... but that is about it.

Video provided

[https://www.loom.com/share/0dc205342dae40ecba2b73e715abf030](https://www.loom.com/share/0dc205342dae40ecba2b73e715abf030)

### Which browser was this experienced in? Are any special extensions installed?

Version 99.0.4844.51 (Official Build) (x86_64)

### How can we reproduce the bug on our side?

My video above demonstrates the bug.

This is done within your sandbox on tiptap.dev

### What did you expect to happen?

I expect to naturally backspace through the list.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by pcbowers** [comment]
@dilizarov I believe this is not an issue with tiptap as a product as it is an issue with documentation! I have used nested lists several times and am able to backspace appropriately.

I tried to recreate the error myself on the homepage and was unable to do so. Here is my own video for reference:

https://user-images.githubusercontent.com/41601975/166855981-03e0638e-f22e-4d36-8ace-d883178ee2a2.mp4

I both held the spacebar for the first two and then started tapping. On both, it handled it just fine.

Did you try reloading the page/refreshing cache/restarting the browser?

**Comment by dilizarov** [comment]
You're backspacing from _the very last item_

Notice in my video that I don't start from the very end of the list, but on a nested item somewhere in the middle of the list.

**Comment by pcbowers** [comment]
@dilizarov I somehow missed that on your first comment! Thanks for clarifying.

**Comment by dilizarov** [comment]
@bkempe Yeah, I think your issue is actually basically this.

I'm not sure I understand your workaround though - seems like a completely different text editor? I see it uses ProseMIrror under the hood though... Are you suggesting a ListItem extension plugin that handles backspacing like in your workaround?

I feel like that could work - but then I suppose I'll need to get OrderedList and BulletList to use the new extended listItem, yeah?

**Comment by dilizarov** [comment]
saw the bot closed this, but feels like it should stay open as its a bug, yeah?

**Comment by Slapbox** [comment]
Anyone following this should follow #3128 and/or #3819 instead.
