### ISSUE TITLE
Hotkeys for moving cursor to start/end of line

### ISSUE THREAD

**Issue by duhaime** [ueberdosis/tiptap#2752]
### What problem are you facing?

Is there any mechanism by which one can programmatically move the cursor to the start/end of the current line? 

We have a user who is accustomed to using HOME/END on a Windows (FN+right arrow and FN+left arrow on Mac) to jump to the start/end of the current line in Microsoft Word and we'd like to replicate that experience in tiptap if possible. 

### What’s the solution you would like to see?

Ideally it'd be awesome to have a [keyboard shortcut](https://tiptap.dev/api/keyboard-shortcuts) that sends the cursor to the start of the current line and another that sends the cursor to the end of the current line. 

### What alternatives did you consider?

I tried CTRL+A and CTRL+E on Mac but those jump to the start/end of the current paragraph, not the current line...

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by BrianHung** [comment]
> HOME/END on a Windows

> CTRL+A and CTRL+E on Mac but those jump to the start/end of the current paragraph

These are [native browser behaviors](https://discuss.prosemirror.net/t/shortcut-ctrl-a-ctrl-e-dont-work-on-macos-with-inline-node/4328/2). 

`Home` and `End` should work on Windows on the latest tiptap version: https://github.com/ueberdosis/tiptap/commit/d270419ad8dc6182a949c5d263c47e90ee4466ff

**Comment by duhaime** [comment]
@BrianHung many thanks for your follow up. Is that commit on NPM, or will it appear in a forthcoming release?

**Comment by BrianHung** [comment]
@duhaime I think that commit is part of the latest release? `2.0.0-beta.175` Would double check the source code. Note that the commit just allows for default native browser behavior, and doesn't actually implement a command.

**Comment by BrianHung** [comment]
Also came up with 

```ts
function selectTextblockLineSide(side: -1 | 1): Command {
  return function(state, dispatch, view) {
    let sel = state.selection, $pos = side < 0 ? sel.$from : sel.$to
    let depth = $pos.depth
    while ($pos.node(depth).isInline) {
      if (!depth) return false
      depth--
    }
    if (!$pos.node(depth).isTextblock) return false
    if (dispatch) {
      let posCoords = view.coordsAtPos($pos.pos)
      let domCoords = view.domAtPos($pos.pos).node.parentElement.getBoundingClientRect()
      let pos = view.posAtCoords({left: side < 0 ? domCoords.left : domCoords.right, top: posCoords.bottom})
      dispatch(state.tr.setSelection(TextSelection.create(
        state.doc, side < 0 ? pos.pos : pos.pos - 1)))
    }
    return true
  }
}

export const selectTextblockStartOfLine = selectTextblockLineSide(-1)
export const selectTextblockEndOfLine = selectTextblockLineSide(1)
```

based on [`selectTextblockSide`](https://github.com/ProseMirror/prosemirror-commands/blob/6fda4b50a13df239db73395c16eef5a1d2795609/src/commands.js#L441-L455).

There are some edge cases / bugs I found yesterday so don't consider it complete :) but its pretty close

**Comment by BrianHung** [comment]
Upon more digging https://discuss.prosemirror.net/t/visual-ambiguity-with-cursor-position/4601/5,

for this behavior its best to just fallback to the browser.

```js
function moveToTextblockLineBoundary(side: -1 | 1): Command {
  return function(state, dispatch, view) {
    let sel = state.selection, $pos = side < 0 ? sel.$from : sel.$to
    let depth = $pos.depth
    while ($pos.node(depth).isInline) {
      if (!depth) return false
      depth--
    }
    if (!$pos.node(depth).isTextblock) return false
    if (dispatch) {
      // Browser workaround lack of caret associativity
      // https://github.com/w3c/selection-api/issues/32
      let sel = view.root.getSelection()
      if (sel.modify) {
        sel.modify("move", side < 0 ? "backward" : "forward", "lineboundary")
        let newSel = selectionFromDOM(view, "pointer")
        if (newSel && !state.selection.eq(newSel)) {
          let tr = state.tr.setSelection(newSel)
          dispatch(tr)
        }
      } else {
        let coords = view.coordsAtPos($pos.pos)
        let blockRect = view.domAtPos($pos.pos).node.parentElement.getBoundingClientRect()
        let pos = view.posAtCoords({left: side < 0 ? blockRect.left + 1 : blockRect.right - 1, 
                                    top: ((coords.bottom + coords.top) / 2)})
        dispatch(state.tr.setSelection(TextSelection.create(state.doc, pos.pos)))
      }
    }
    return true
  }
}
```
