### ISSUE TITLE
NodeViewRenderer called twice

### ISSUE THREAD

**Issue by Arman19941113** [ueberdosis/tiptap#2763]
### What’s the bug you are facing?

The `NodeViewRenderer` returned by `addNodeView` called twice

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/35905177/167236509-62758b55-74a0-45ee-964d-7028beb6bf87.png">

<img width="600" alt="image" src="https://user-images.githubusercontent.com/35905177/167236549-2d962ccb-8cd3-4f3e-970d-db2d49c4d672.png">

### Which browser was this experienced in? Are any special extensions installed?

chrome  100.0.4896.127 (x86_64)

### How can we reproduce the bug on our side?

`nr start`

http://localhost:3000/src/GuideNodeViews/JavaScript/Vue/

### What did you expect to happen?

It should be called once

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
I checked out why this function is called two times and couldn't find a quick and easy solution. Short explanation:

The Editor class it self has a `createView` method, that calls `this.createNodeViews`, which in turn calls the nodeViews defined in the extensions.

Now when you use React or Vue (2 and 3), the `EditorContent` components also bring in a call to `editor.createNodeViews`, which causes the two calls. Removing those fixes it, but will break React and Vue nodes.

This seems to go a bit deeper than expected so I'll keep this one open but postpone it until we have time to dig deeper.

Thanks for the report.
