### ISSUE TITLE
Problem when using insertContent with a text node list

### ISSUE THREAD

**Issue by GitHubish** [ueberdosis/tiptap#2770]
### What’s the bug you are facing?

I just found a regression. When I paste text in my editor, I call the server so it can parse it. I just saw that it doesn't work anymore I had a result showing : 
<img width="224" alt="image" src="https://user-images.githubusercontent.com/7701833/167478313-6bb57b9f-6358-4015-bd8c-ca454f474859.png">

I thought the problem was coming from somewhere else but in fact when I execute this piece of code in a blank project I also have the problem. Before it was working. 

```
editor
              .chain()
              .insertContent([
                {
                  type: 'text',
                  text: 'Second paragraph',
                },
                {
                  type: 'text',
                  text: 'First paragraph',
                }
              ])
              .focus()
              .run();
```

Demo here : [https://codesandbox.io/s/tiptap-demo-tailwind-forked-ewe285?file=/src/index.js](https://codesandbox.io/s/tiptap-demo-tailwind-forked-ewe285?file=/src/index.js)

### Which browser was this experienced in? Are any special extensions installed?

Chrome 100, Safari, Firefox Latest

### How can we reproduce the bug on our side?

Use this code :

```
editor
              .chain()
              .insertContent([
                {
                  type: 'text',
                  text: 'Second paragraph',
                },
                {
                  type: 'text',
                  text: 'First paragraph',
                }
              ])
              .focus()
              .run();
```

### Can you provide a CodeSandbox?

https://codesandbox.io/s/tiptap-demo-tailwind-forked-ewe285?file=/src/index.js

### What did you expect to happen?

It used to insert the nodes without any problem.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by GitHubish** [comment]
@gazben It's hard to say, I couldn't necessarily find when it stopped working, it was a very specific part of my application for which the tests were not yet developed. Maybe version 2.0.0-beta.168 or 2.0.0-beta.170... In my tests the insertContent method does not crash but just does nothing. For example adding several Nodes in the paragraph where there is the cursor does not work although it was before.

My use case is a copy/paste. I intercept the event to send the text to the server so that it can parse it and send me back a rich content (JSON format). For example a text with an @mention will be automatically transformed by the server as Slack would do and thus send me back the necessary information to display the mention.

**Comment by gazben** [comment]
> he insertContent method does not crash but just does nothing

yepp same for me, I'll try older versions

**Comment by sebinemeth** [comment]
Hi all, I am working on the same issue as @gazben, and I found a fix:
Change the object syntax to the string param syntax: `editor.chain().insertContent({ type: 'text' text: 'foo' })` does not work but `editor.chain().insertContent('foo')` does, hope it helps. I could not find documentation for it though...

**Comment by GitHubish** [comment]
On my side, following the previous solution proposed by @sebinemeth I had to convert my JSON to HTML using the generateHTML method. Clearly not adapted...

I hope that the Tiptap team will consult this ticket to give us a feedback.

**Comment by bdbch** [comment]
Just pushed a fix for this

**Comment by Ankit-26** [comment]
i/m using Tiptap in react using tiptap/react, but the insertContentAt command is not working, I want to use it for copying some content from somewhere and paste it at the clicked position in the editor. Can anyone help me with that?
