### ISSUE TITLE
Chaining `focus` command throws error (tiptap/core)

### ISSUE THREAD

**Issue by konstantinmuenster** [ueberdosis/tiptap#2771]
### What’s the bug you are facing?

We recently updated to the latest Tiptap version and are experiencing issues with command chains we already had in place. 

The following chain results in an error, thrown by Prosemirror's `setSelection` method  (_Selection passed to setSelection must point at the current document_):

```ts
editor.chain().setBold().focus(editor.state.selection.to).run();
```

It works however if we split the actions in two separate calls like: 
```ts
editor.commands.setBold();
editor.commands.focus(editor.state.selection.to);
```

### Which browser was this experienced in? Are any special extensions installed?

Chrome

### How can we reproduce the bug on our side?

1. Open the codesandox
2. Select any text via mouse
3. Press shortcut `⌘B`
4. The error should occur

### Can you provide a CodeSandbox?

https://codesandbox.io/s/eloquent-haze-ghi364?file=/src/App.js

### What did you expect to happen?

The chain should run without any issues.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by konstantinmuenster** [comment]
After some quick investigation, I think it was introduced by this change in tiptap/core: https://github.com/ueberdosis/tiptap/commit/de39853026ee63bb558ed59b1dab3899c07ae073

If you set the tiptap/core version back to .147, the chain runs without any issues.

**Comment by bdbch** [comment]
Thanks! We'll take a look asap.

**Comment by bdbch** [comment]
This commit should fix this issue:
https://github.com/ueberdosis/tiptap/commit/5b0b7d91023c87e9ddb85ff3a776273d12a22d16

It'll be included in the next release of Tiptap
