### ISSUE TITLE
Cursor jumps back and indents text when typing comments in Japanese

### ISSUE THREAD

**Issue by keitongstar** [ueberdosis/tiptap#2778]
### What’s the bug you are facing?

When using the Todoist app, users using a non-default IME keyboard to type a comment to a task experiences this issue. 

### Which browser was this experienced in? Are any special extensions installed?

Browser: Chrome
OS: Windows 10, Linux

### How can we reproduce the bug on our side?

1. Input: "te(て)", "su(す)", "to(と)", and hit Space
2. Some suggestions will show up to convert these what we call Hiragana letters to others.
3. Confirm the first option, for example by hitting Enter
4. The cursor goes to the front instead of after the text you just input.

### What did you expect to happen?

The cursor stays where it is.

### Anything to add? (optional)

Here is one video - https://drive.google.com/file/d/1UUCfbA4qc0cQZiCC3iti5hv9Dhvu0ZnI/view?usp=sharing

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by frankieyan** [comment]
Hi there 👋  according to some of our users, this can be reproduced with the demo on the [Tiptap homepage](https://tiptap.dev/). This seems to only happen when they are using 3rd party IME's like: [ATOK](https://atok.com/windows/) and [mozc](https://launchpad.net/ubuntu/+source/mozc), but it wasn't something we can reproduce with the OS-default IMEs when typing Japanese.

**Comment by bdbch** [comment]
Hi there 👋!

I just was able to use my phone to test this issue via the Google Hiragana keyboard typing in tesuto which worked fine. I'll take a look to see if I can install ATOK and mozc as @frankieyan explained to see this issue first hand.

@keitongstar was it the default IME for Windows? What Distro did you use to test this on Linux?

**Comment by bdbch** [comment]
I tried replicating this with the default Windows 11 IME for Hiragana. Is this what you were testing on @keitongstar?

For me after accepting a suggestion, the cursor jumped right after the last characters as I would expect?

https://user-images.githubusercontent.com/6538827/168246647-bae85264-e16d-470b-8e5b-7bfe439c6673.mp4

**Comment by keitongstar** [comment]
Hi @bdbch 
Thanks for looking into this.

So one user uses: ATOK for Windows
https://atok.com/windows/
and another is using citx-mozc from package management tool(apt) on Linux - Ubuntu 20.04

> For me after accepting a suggestion, the cursor jumped right after the last characters as I would expect?

Yes, this is expected. But our users using these non-default IMEs are reporting that the cursor jumps back instead. 

Sorry, I do not have an environment to test this so if you need additional information, I will reach out to our users.

**Comment by bdbch** [comment]
Hey @keitongstar - thanks for the fast reply!

I'll download ATOK and see if I can figure the tool out. My japanese knowledge is failing me here! 😄
Maybe I can reproduce it and find a way to fix it. Thanks for helping me out clarifying the issue.

**Comment by bdbch** [comment]
Setting up Windows Sandbox now! Will update you guys when I find something!

**Comment by bdbch** [comment]
Alright - sitting in my Sandbox right now but it seems like ATOK is a paid tool right? I've seen that they provide a free trial.

Sadly it seems like the download server or my sandbox is really slow when it comes to the download:
![image](https://user-images.githubusercontent.com/6538827/168311691-6353cded-9aae-4097-a545-8b3239845346.png)

If someone wants to help with this issue I would be happy to get some help here.💪
But for now it's quite hard to resolve, sorry.

**Comment by bdbch** [comment]
@keitongstar were you able to resolve this issue on your hand? I wasn't able to reproduce it for now. I'll set this to low priority in the meantime.

**Comment by bdbch** [comment]
Sure thing!

**Comment by keitongstar** [comment]
I have 2 users now.

One is sending me more details with a video.

Another shared as below:

Windows 10
Browser: Chrome

This user is using ATOK.

Steps:
1. Write a comment and hit Enter to go to the next line
2. Start typing Japanese and hit Space to change characters from Hiragana to Kanji
3. These texts now overwrap in the first comment.


![1](https://user-images.githubusercontent.com/37155922/175935930-06e056e8-6c47-43e3-83b7-686c56a1d847.png)
![2](https://user-images.githubusercontent.com/37155922/175935934-48351297-39d9-40f9-aa42-4154104c25f8.png)
![3](https://user-images.githubusercontent.com/37155922/175935938-4e770367-c21c-429c-9cca-ef8e55d0b5e6.png)
