### ISSUE TITLE
Expose Linkify validate method in Link extension

### ISSUE THREAD

**Issue by georgemandis** [ueberdosis/tiptap#2779]
### What problem are you facing?

The autolink attribute on the Link extension is a nice idea, but in practice it's less useful due to the long list of TLDs included by Linkify. We regularly get feedback asking why our editor turns certain word combinations into links when a user forgets to enter a "space" after a period.

I recognize hamster.vodka is a valid gTLD, but we're a little tired of explaining that 😂 

### What’s the solution you would like to see?

I also realize this behavior is powered by Linkify. Would it be possible to amend the Link extension and expose the `validate` method it provides?
https://linkify.js.org/docs/options.html#validate

That should allow us to write our own regex and just look for com|net|org.

### What alternatives did you consider?

The alternative is disabling autolink, which we'll probably do in the meantime. We'd like to keep it for some of the more common gTLDs though.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by georgemandis** [comment]
@bdbch I think so! That looks pretty good :)

**Comment by bdbch** [comment]
Great! Looking forward for the merge!
