### ISSUE TITLE
Copy/Paste HTML with Bullets and different size text breaks

### ISSUE THREAD

**Issue by casesandberg** [ueberdosis/tiptap#2783]
### What’s the bug you are facing?

We are seeing a weird bug when sometimes copy/pasting bullet points from Google Docs the formatting gets messed up occasionally. When copying a list of bullets and you don't select the entire final line of bullets, if the final line has text with different formatting in it (in my included example its slightly smaller text) then it breaks out of the bullet formatting on paste. 
https://www.loom.com/share/e061d4b4409a449b9fade02d65a6019f

### Which browser was this experienced in? Are any special extensions installed?

Google Chrome, no specific extensions. 

### How can we reproduce the bug on our side?

1. Use any TipTap Editor: https://codesandbox.io/s/tiptap-react-issue-template-b4hmi?file=/src/App.js
2. Copy bullets from Google Docs (https://docs.google.com/document/d/13IH4Jn4iKjAvscbrTVEoGbn-GKKzJiIO_yx0bnyqjeo/edit#) but only copy up to the pipe. 
3. Past into a TipTap Editor

### What did you expect to happen?

When copying only a partial final line, it should remain in bullets. It does this if there is no custom test formatting on that final line, however it breaks when there is. 

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Hey @casesandberg thanks for your bug report and nice find. Great idea btw. to provide a video example, helps a lot to understand the issue.

I'll pick this up when I find time and try to find out what's happening here. I'll keep you updated!

**Comment by bdbch** [comment]
This seems to be an issue with ProseMirror itself as the ProseMirror demo editor shows the same problem.

https://prosemirror.net/

If you try this out on the demo, you'll see the thing happening. I will create a issue for this linking to this issue. Thanks 👍

**Comment by bdbch** [comment]
@casesandberg this is the response from one of the prosemirror maintainers:
https://github.com/ProseMirror/prosemirror/issues/1269#issuecomment-1127628367

It seems like Google is actually not providing correct HTML - could you double check this if possible? If Google is not providing the correct HTML we obv. can't predict what kind of element was pasted.

**Comment by casesandberg** [comment]
Sounds good, thank you for cross-posting it there.

If that is the case (that Google Docs isn't providing accurate HTML) than it does handle it correctly. I will do some more checks on my end to double verify, but very strange. Oddly enough the Notion editor does not have this problem so they must handle it as an edge case.

**Comment by bdbch** [comment]
I'll close this for now. @casesandberg let me know if you would like to keep it open.
