### ISSUE TITLE
Show suggestions only first time (don't show on cursor move)

### ISSUE THREAD

**Issue by softmarshmallow** [ueberdosis/tiptap#2784]
### What’s the bug you are facing?

Using suggestion api, configured with "/" char.

https://tiptap.dev/api/utilities/suggestion

I suggest to add new option called `onlyOnFirstShot` which will trigger suggestion on first entry, when typing `"/"`, and not on revisiting the character with cursor move.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
This sounds similar to #2680. Thanks for opening.
