### ISSUE TITLE
React View for Marks

### ISSUE THREAD

**Issue by danielyogel** [ueberdosis/tiptap#2797]
### What problem are you facing?

I try to implement a React view to the "Link" mark

### What’s the solution you would like to see?

Allowing specifying a React view for marks - just as allowed for Nodes

### What alternatives did you consider?

Using a new Node (instead of a Mark) for a "link" element.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by BrianHung** [comment]
What are you trying to do with a custom Markview? Usually there's a better solution with a plugin view.

https://tiptap.dev/overview/upgrade-guide#marks-dont-support-node-view-anymore

**Comment by danielyogel** [comment]
@BrianHung I try to implement a custom view for links, for example a menu (with open/closed state) instead of a simple <a/> tag. I would like to implement this using react.
What are my options?
One direction I'm thinking about, is converting all <a/> tags (before render, and after onChange) to a different element, then using a custom react view.
Thanks!

**Comment by bdbch** [comment]
Could you elaborate a bit more? I think I'm not understanding exactly why you'd need a Custom Mark View for that.

**Comment by hdoro** [comment]
To follow up, I have a use-case similar to @danielyogel : how would I go about creating a link that, when clicked, opens a popover (using `tippy.js`) for editing it? Here's an example UI for this:

<img width="498" alt="2022-10-04-Firefox Developer Edition@2x" src="https://user-images.githubusercontent.com/27744332/193878570-842abb30-e265-4b48-ba00-e87ba4cb7247.png">

`Mark.create`'s `renderHTML` doesn't seem to support ReactRenderer or anything other than `DOMOutputSpec`, so I'm unsure how to proceed 🤔

**Comment by BrianHung** [comment]
Use a plugin view that registers a `onClick` listener, check if selection or position is above a link mark, then open a popover using attrs from that mark.
