### ISSUE TITLE
Ability to detect multiple text styles for selected text

### ISSUE THREAD

**Issue by coderrahul** [ueberdosis/tiptap#2800]
### What problem are you facing?

Let's say part of my selected text is Bold and part is Italic. Currently, I couldn't find a way to know if there are multiple styles/marks applied to the text.

### What’s the solution you would like to see?

I would like to know that my currently selected text has multiple text styles

### What alternatives did you consider?

Is this something that I could achieve by writing some custom extensions or something of that sort.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by BrianHung** [comment]
Try

https://github.com/ProseMirror/prosemirror-example-setup/blob/f84ad32ec79f9884709f5b50f4668bf34597a2b5/src/menu.ts#L58-L62

https://prosemirror.net/docs/ref/#model.ResolvedPos.marks

https://prosemirror.net/docs/ref/#model.ResolvedPos.marksAcross

**Comment by BrianHung** [comment]
```
import type { EditorState } from "prosemirror-state"

function activeMarks(state: EditorState) {
  let {$from, $to, empty} = state.selection
  if (empty) return state.storedMarks || $from.marks()
  else return $from.marksAcross($to)
}
```

**Comment by coderrahul** [comment]
Thanks, @BrianHung for the suggestion but the above suggestion also doesn't work. It's not able to return me all the marks present in the selected text

**Comment by bdbch** [comment]
@coderrahul does this help you?
https://codesandbox.io/s/tiptap-multiple-mark-detection-d91rfz?file=/README.md
