### ISSUE TITLE
Does not support CDN introduction？

### ISSUE THREAD

**Issue by XinLau1996** [ueberdosis/tiptap#2802]
### What problem are you facing?

Does not support CDN introduction

### What’s the solution you would like to see?

Does not support CDN introduction

### What alternatives did you consider?

Does not support CDN introduction

### Anything to add? (optional)

Does not support CDN introduction

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Could you please add further information on what the problem exactly is? Your issue is not really describing what kind of issues you're experiencing.

**Comment by bdbch** [comment]
Closing this for now until we have more information.
