### ISSUE TITLE
Using a custom NodeView with a resizable Table

### ISSUE THREAD

**Issue by Ovyerus** [ueberdosis/tiptap#2815]
### What problem are you facing?

Currently I'm trying to implement a custom node view for the Table extension using `VueNodeViewRenderer` and `addNodeView`, and allow it to be resizable as well. With `resizable: false`, the node view works as expected with no issues, but turning on the `resizable` brings some issues.

The resize handles appear as expected but dragging them results in the columns not changing and a `Uncaught TypeError: Cannot read properties of undefined (reading 'width')` in the console. It looks like the logic for the original table is running alongside my node view from what I gathered.

I took a look at the code for the table extension and sure enough, there's a [TableView](https://github.com/ueberdosis/tiptap/blob/main/packages/extension-table/src/TableView.ts) which is getting passed in a (to me, at least) non-orthodox way to the resize plugin.
https://github.com/ueberdosis/tiptap/blob/13a03425b36dedb1697caba396203d68d22554e1/packages/extension-table/src/table.ts#L85-L96
https://github.com/ueberdosis/tiptap/blob/13a03425b36dedb1697caba396203d68d22554e1/packages/extension-table/src/table.ts#L228-L239

I've also done some looking at the Vue node view renderer and some other parts of the code to try and figure out a way to pass my custom VueNodeView into this `View` option on the table extension, but I cannot figure out what would be the correct way to do so, if there is one at all.

### What’s the solution you would like to see?

I'd like to be able to have a way to have a resizable table with a custom Vue node view, either by being able to somehow pass it to the options of the Table node, or some kind of hook into my component, or even some other way that I haven't thought of.

### What alternatives did you consider?

Using a native JS `NodeView`, but considering the logic I want to add to my tables, I would much rather be able to use a Vue component as it would be way easier to work with.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Hey @Ovyerus sorry for the late answer. Could you provide a CodeSandbox with your TableNodeView?
