### ISSUE TITLE
Render topNode

### ISSUE THREAD

**Issue by wenerme** [ueberdosis/tiptap#2816]
### What problem are you facing?

Redefined the doc like

```js
import { mergeAttributes, Node } from '@tiptap/core';

export const Document = Node.create({
  name: 'doc',
  topNode: true,
  content: 'block+',

  addOptions() {
    return {
      HTMLAttributes: {},
    };
  },

  parseHTML() {
    return [{ tag: 'article' }];
  },

  renderHTML({ HTMLAttributes }) {
    return ['article', mergeAttributes(this.options.HTMLAttributes, HTMLAttributes)];
  },
});
```

Hope to render 

```html
<article><p>text</p></article>
```

but the article not render. by doing this can apply global style for article

### What’s the solution you would like to see?

topNode not render

### What alternatives did you consider?

wrap the getHTML restult

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Prosemirror topNodes are never rendered which is why the default Document node doesn't have any parse or render functions. You can wrap your editor in an article tag if you need the semantics or stylings.

The rendered `div.ProseMirror` comes from `prosemirror-view`.
