### ISSUE TITLE
Drag content from outside to the editor

### ISSUE THREAD

**Issue by Cuimc** [ueberdosis/tiptap#2817]
### What problem are you facing?

First of all, thank you very much for tippap
I'm writing an editor. Now I need to drag external content into the editor to form a reference relationship
But I thought of many ways, but I didn't come up with them
So I can only come here to ask for help
Can you provide me with an idea? I'm really going to collapse
Like it ...
<img width="653" alt="image" src="https://user-images.githubusercontent.com/64002336/169768421-420ccd6f-7b63-4bf1-8ffe-306edb528172.png">

The method I tried：
- Drag and drop and add through insertcontent    However, it can only be added to the cursor. You can't add to where you drag
- Use JS Api appendChild or innerHtml，The problems are not easy to describe
- Now I want to use the draggableitem instance provided by tiptap to implement it, but I haven't made any progress yet

### What’s the solution you would like to see?

Drag external content into the editor
for example：
<img width="818" alt="image" src="https://user-images.githubusercontent.com/64002336/169769623-86cbe4b1-1aba-48d7-826a-e5d47c390114.png">

### What alternatives did you consider?

The method I tried：
- Drag and drop and add through insertcontent    However, it can only be added to the cursor. You can't add to where you drag，That is, I cannot get the position of the current mouse placement
- Use JS Api appendChild or innerHtml，The problems are not easy to describe
- Now I want to use the draggableitem instance provided by tiptap to implement it, but I haven't made any progress yet

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Hey @Cuimc - Tiptap already supports drag and dropping content into the editor. (You can try it by dragging content from for example an messenger into the editor - should work fine).

Now I don't know if you want to copy the exact type of content over? Not really sure what you are trying to do.

As long as the dragged content contains valid text content, Tiptap and ProseMirror should be able to parse it.

**Comment by RabbitRab6it** [comment]
I had the same problem. I need to drag in a node from outside the editor and create it. But the created position is the last focus position of the editor, not the position after the drag is completed.

**Comment by aehlke** [comment]
@RabbitRab6it can you post that as a bug with a sandbox demo?

**Comment by RabbitRab6it** [comment]
I want to add a date selection box to a certain cell by dragging, but when I drag the above date box directly into a cell, it is not adding to the specified cell correctly. I have to first select the cell that needs to increase the date box.
[sandbox demo](https://codesandbox.io/s/dreamy-glade-82z6wz?file=/src/App.vue)
[dreamy-glade-82z6wz---CodeSandbox.webm](https://user-images.githubusercontent.com/26115614/190890871-eded767d-fa9b-4c55-a4fb-9e44897d189d.webm)

**Comment by RabbitRab6it** [comment]
@aehlke

**Comment by tsl1127** [comment]
I had the same problem

**Comment by ZHocean123** [comment]
@RabbitRab6it @tsl1127 
use`posAtCoords`function

```javascript
handleDrop: (view, event, slice, moved) => {
      const position = view.posAtCoords({ left: event.pageX, top: event.pageY })

      // .......
}
```
