### ISSUE TITLE
[Mention] - writing mention character right after character and not space doesn't trigger mention

### ISSUE THREAD

**Issue by gaspergrom** [ueberdosis/tiptap#2821]
### What’s the bug you are facing?

I have mentions implemented with character @ as a trigger character.
if i type @ after space it works:
example:  this is some text @Tiptap

if i type it after a character it doesn't work
example: this is some text (@TipTap)

i need to create space after ( for mention to work.

### Which browser was this experienced in? Are any special extensions installed?

Browser: Chrome
OS: MacOS
Extentions: vue devtools and adblock

### How can we reproduce the bug on our side?

Write character to trigger mention right after ( without spaces after parenthesis

### Can you provide a CodeSandbox?

You can reproduce on your demo mention app on documentation page
https://tiptap.dev/api/nodes/mention
<img width="489" alt="image" src="https://user-images.githubusercontent.com/15195228/169816105-d5c799fc-85de-4841-aae4-aed22169e8d8.png">

### What did you expect to happen?

That mention will be triggered after ( sign so i can put mentions also in parenthesis

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by evestorm** [comment]
I’ve encountered the same issue. Unless the mention is used at the beginning or after a line break, I have to insert a space before using the mention for it to work properly. Is there a good solution for this?
