### ISSUE TITLE
textAlign attribute not generated with generateHTML() function

### ISSUE THREAD

**Issue by cameronrdecker** [ueberdosis/tiptap#2822]
### What’s the bug you are facing?

the textAlign attribute does not get added to any elements when converting JSON to HTML using generateHTML()

### Which browser was this experienced in? Are any special extensions installed?

Chrome Version 101.0.4951.67

### How can we reproduce the bug on our side?

See codesandbox, a reproduction of your code [here](https://tiptap.dev/api/utilities/html#generate-html-from-json), but with the TextAlign extension added and the textAlign: "center" attribute added to the paragraph

### Can you provide a CodeSandbox?

https://codesandbox.io/s/tiptap-no-textalign-xutffh

### What did you expect to happen?

generateHTML() should have added a text-align: center style to the paragraph tag, as far as I understand.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by codemzy** [comment]
[TextAlign](https://tiptap.dev/api/extensions/text-align) does work with `generateHTML()`, I think you have the extension configured wrong in Line 46 `TextAlign.configure(["left", "center", "right", "justify"])`. You haven't configured the extension to work on paragraphs. It should be..

```js
TextAlign.configure({
  types: ['paragraph'],
})
```

Or if you want the text align to work with other nodes, like headings...

```js
TextAlign.configure({
  types: ['heading', 'paragraph'],
})
```

See the [docs here](https://tiptap.dev/api/extensions/text-align) for more configuration options.
