### ISSUE TITLE
Deleting the first bullet point with an indented bullet point shouldn't delete the previous block element

### ISSUE THREAD

**Issue by rfgamaral** [ueberdosis/tiptap#2829]
### What’s the bug you are facing?

Take a look at the following example:

https://user-images.githubusercontent.com/96476/170479758-41ef9066-9ff4-4061-a54f-092a9e30a8b3.mp4

When the cursor is between the first bullet point and the item in a bulleted list, pressing `Backspace` once moves the cursor to the previous block element (in this case a header) - as you can see from the toolbar buttons changing - and pressing `Backspace` once again deletes the header. The same is true for ordered list items (it's not exclusive to bulleted lists).

Here's another example:

https://user-images.githubusercontent.com/96476/170480272-3caa95e1-4799-4121-9b0c-671c3514e2d4.mp4

You can't really see it, but I'm constantly pressing the `Backspace` key, and nothing happens.

This **only happens when a bulleted list contains indented list items**, otherwise it works as expected:

https://user-images.githubusercontent.com/96476/170480669-31dad029-3153-4be7-8f56-13a2fc6b3e8e.mp4

https://user-images.githubusercontent.com/96476/170480736-a3c52bf5-ede9-46ca-a335-c1c7e5ba81b0.mp4

### Which browser was this experienced in? Are any special extensions installed?

It happens on any browser. No special extensions.

### How can we reproduce the bug on our side?

Follow the examples above in the [default example](https://tiptap.dev/examples/default).

### What did you expect to happen?

In both examples above, the bullet point should be deleted without deleting any previous block elements (if any).

One question that might arise from attempting to do fix this is: what to do with the indented list item in this case? In my opinion, CKEditor is the editor that handles this the best way:

https://user-images.githubusercontent.com/96476/170481149-3bdd30bb-0286-40f6-b2e9-a6cb56884c33.mp4

You can see that the sub-list item was "unindented" (i.e. it becomes the root bullet list), and this works independently of the number of indented or sub-indented items in the list:

https://user-images.githubusercontent.com/96476/170481531-ae546630-edc2-42a2-9d8d-1fc8c85e508f.mp4

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖 _(on behalf of Doist)_

**Comment by rfgamaral** [comment]
@bdbch This issue still exists, do you think this could be reopened, and possibly some attention?

**Comment by KevinTss** [comment]
We (as CycleApp sponsor) also having some trouble with this bug and wanted to manifest our interest for this one instead of create a new one.

[Here](https://codesandbox.io/s/tiptap-react-forked-7zj43u?file=/src/App.tsx) is a sandbox were is reproductible. Also adding a [stackblitz](https://stackblitz.com/edit/react-ts-rlhd4s?file=App.tsx) since sometime the sandbox failed.

https://user-images.githubusercontent.com/39580007/198237277-9c16d8a5-6265-4c16-82ef-0bbb8e8f9256.mov

Thank you for you work and consideration 🙌

**Comment by boehm-e** [comment]
Getting same error here. :+1:

**Comment by hamflx** [comment]
The schema for `listItem` is defined as `paragraph block*`. When the backspace key is pressed, the `joinBackward` method attempts to lift the paragraph out of the bulletList, which causes the content of the listItem to no longer match the schema. As a result, the `canCut` function in the `liftTarget` fails.

I don't know how to fix it, but I have a workaround that can solve this problem:

```javascript
export const MyOrderedList = OrderedList.extend({
  addKeyboardShortcuts () {
    return {
      Backspace: () => {
        return this.editor.commands.command(({ tr }) => {
          const { selection, doc } = tr
          const { $cursor } = selection
          const depth = $cursor?.depth

          if ($cursor &&
            depth >= 3 && // 至少是 doc -> orderedList/bulletList -> listItem -> paragraph 结构
            $cursor.parent.type.name === 'paragraph' && // 光标在段落内。
            $cursor.parentOffset === 0 && // 光标位于段落的开始处。
            $cursor.node(depth - 1).type.name === 'listItem' && // 段落位于 listItem 内。
            $cursor.index(depth - 1) === 0 && // 段落位于 listItem 的开始处。
            $cursor.index(depth - 2) === 0 // listItem 位于 list 的开始处。
          ) {
            const listItemNode = $cursor.node(depth - 1)
            const listItemPos = $cursor.before(depth - 1)
            const $contentBegin = doc.resolve(listItemPos + 1)
            const $contentEnd = doc.resolve(listItemPos + listItemNode.nodeSize - 1)
            const range = $contentBegin.blockRange($contentEnd)
            const target = liftTarget(range)
            if (target != null) {
              tr.lift(range, target)
              return true
            }
          }
          return false
        })
      },
      'Mod-Shift-[': () => this.editor.commands.toggleOrderedList()
    }
  }
})
```

This code will check for this situation and lift all the content of the listItem.

**Comment by rfgamaral** [comment]
All of these issues should be fixed by using `@tiptap/extension-list-keymap`.
