### ISSUE TITLE
[Mention] allowSpaces issue

### ISSUE THREAD

**Issue by mdembna** [ueberdosis/tiptap#2831]
### What’s the bug you are facing?

I've encountered an issue when using mention with the `allowSpaces: true` option. 
When I write a message and use @ character but without mentioning anyone I can easily escape suggestions with ESC. The problem occurs when I go back and edit the message - immediately when I focus text editor, the plugin tries to get suggestion list using all characters which were typed after `@`.
So if my message looks like this:
`I really like @ sign and I use it everywhere without <b>any</b> reason` the plugin will try to get suggestions for ` sign and I use it everywhere without <b>any</b> reason` which is not very convenient.

Does anyone have a solution for it?

### Which browser was this experienced in? Are any special extensions installed?

Chrome, Vue.js, Mention plugin

### How can we reproduce the bug on our side?

Edit a message which has a loose `@` char and mention plugin with `allowSpaces: true` option.

### What did you expect to happen?

For me, the best thing would be an option to remember escaped mentions for the editor to ignore.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by CamJN** [comment]
Bad bot, this is still an issue

**Comment by cayasso** [comment]
Still an issue

**Comment by nperez0111** [comment]
@cayasso I just released a patch version today for this can you upgrade and tell me if you still see this issue
