### ISSUE TITLE
Collaborative editing changes outside the viewport push content down

### ISSUE THREAD

**Issue by jamesopti** [ueberdosis/tiptap#2835]
### What’s the bug you are facing?

Another user types in the same document and pushes my view of content down, even though their editing content thats way out of my viewport.

### Which browser was this experienced in? Are any special extensions installed?

Chrome Version 101.0.4951.64
(Official Build) (arm64)

### How can we reproduce the bug on our side?

See this codesandbox https://codesandbox.io/s/ocfs29

1. Open the sandbox with 2 different windows side by side
2. Turn "Simulate typing" on in window 1
3. Scroll down to the middle of the content in window 2
4. Observe window 2 content getting pushed down

https://www.loom.com/share/446da21daa5f434f94940323234d2fef

### Can you provide a CodeSandbox?

See this codesandbox https://codesandbox.io/s/ocfs29

### What did you expect to happen?

The browser native scroll anchoring should keep the current paragraph fixed in the viewport as changes to elements outside of it are made (see https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-anchor/Guide_to_scroll_anchoring)

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Thanks, good find!
