### ISSUE TITLE
Nuxt.js - Tiptap - Class constructor Transform cannot be invoked without 'new'

### ISSUE THREAD

**Issue by kriss145** [ueberdosis/tiptap#2837]
### What’s the bug you are facing?

When I installed again all packages I've got errors like "Class constructor Transform cannot be invoked without 'new'"
This error does not happen earlier. I've removed my old yarn.lock, set yarn install and that's it.

Probably the sub-package was updated but I don't know which was. It's difficult to find the problem.

Maybe someone knows why it's happened?

### Which browser was this experienced in? Are any special extensions installed?

It's happened in all browsers

### How can we reproduce the bug on our side?

It's difficult to reproduce. 

### What did you expect to happen?

I would not have this error.

### Anything to add? (optional)

Console error:

```
index.es.js?5313:525 Uncaught TypeError: Class constructor Transform cannot be invoked without 'new'
    at new Transaction (index.es.js?5313:525:1)
    at EditorState.prototypeAccessors$1.tr.get (index.es.js?5313:875:1)
    at CommandManager.get commands [as commands] (tiptap-core.esm.js?9980:1963:1)
    at Editor.get commands [as commands] (tiptap-core.esm.js?9980:3280:1)
    at eval (tiptap-core.esm.js?9980:3266:1)
```

index.es.js?5313:525

```
var Transaction = /*@__PURE__*/(function (Transform) {
  function Transaction(state) {
    Transform.call(this, state.doc);
```

Packages:
```
    "tiptap": "^1.27.1",
    "tiptap-extensions": "^1.29.1",
```

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by tobychidi** [comment]
Me too. Any fix for this?

**Comment by jasonvarga** [comment]
Possible workaround in #2836
