### ISSUE TITLE
TextSelection warning from prosemirror-state 1.4.0

### ISSUE THREAD

**Issue by andy1li** [ueberdosis/tiptap#2846]
### What’s the bug you are facing?

Tiptap (or more precisely, prosemirror-state 1.4.0) throws out a warning in my tests, when using tiptap's `editor.commands.setContent()`:

`TextSelection endpoint not pointing into a node with inline content (doc)`

<img width="868" alt="warning" src="https://user-images.githubusercontent.com/1450947/171995002-dc4a90a5-d3ca-4d6f-94fc-9dbc7c9c3f0c.png">

### Which browser was this experienced in? Are any special extensions installed?

It's not in the browser, but in the `happy-dom` environment of `vitest`.

### How can we reproduce the bug on our side?

I made this minimal repo:

https://github.com/andy1li/text-selection-test-warning

`npm run test`

### Can you provide a CodeSandbox?

https://stackblitz.com/github/andy1li/text-selection-test-warning

### What did you expect to happen?

No TextSelection warning should appear. Can we do something in tiptap to make it go away?

### Anything to add? (optional)

The warning seems to be from `checkTextSelection()` in prosemirror-state 1.4.0 (released at the end of May):

https://github.com/ProseMirror/prosemirror-state/blob/f1c2ff98a397aa05b9ccf5ee23642bb7e44f05a7/src/selection.ts#L221

It seems that prosemirror-state 1.3.4 from more than a year ago does not have the new `checkTextSelection()` function.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by andy1li** [comment]
Temporarily solved the problem, by using [the method](https://github.com/ueberdosis/tiptap/issues/2836#issuecomment-1143528033) from tgv1975.

**Comment by andy1li** [comment]
Just saying: the https://github.com/ueberdosis/tiptap/pull/2854 pr did not fix the problem described above.

**Comment by bdbch** [comment]
I'll investigate this issue when I find some time, thanks for bringing it up

**Comment by bdbch** [comment]
Can you reproduce this issue in the browser? It's not a test but I tried to replicate that warning in this sandbox:
https://1pvl9b.csb.app/

I can't see any comparable warning message - no matter if the editor has initial content or not. As far as I understood this is a warning that was introduced in prosemirror-state 1.4.0.

**Comment by andy1li** [comment]
Sure, @bdbch. Thank you for your time~

I've modified my minimal repo a bit. Now the warning should appear in the browser console.

https://stackblitz.com/github/andy1li/text-selection-test-warning?file=src%2Fmain.ts

---

Perhaps it's because my use case is not typical:

Tiptap is used in a normal fashion on my backend to do some custom markups.

On my frontend, tiptap is only used to parse the custom markups into JSON and then render them with custom components.

**Comment by bdbch** [comment]
Hey @andy1li I created a PR (see #2934) that should fix this issue.
