### ISSUE TITLE
Editable state isn't reactive

### ISSUE THREAD

**Issue by chrispiech** [ueberdosis/tiptap#2850]
### What’s the bug you are facing?

Changing the editor state (for example):
editor.setEditable

Doesn't creative a reactive change to 
props.editor.isEditable

Which prevents Nodes from reacting to a change to the editable state

### Which browser was this experienced in? Are any special extensions installed?

all!

### How can we reproduce the bug on our side?

Create an editor
Create a custom Node 
editor.setEditable(false)
Notice that code in the Node
useEffect(()=> {
   alert('test')
}, [props.editor.isEditable])
is not fired

### What did you expect to happen?

I expected it to have a reactive state change

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by Dreched** [comment]
A CodeSandbox reproducing the issue is located [here](https://codesandbox.io/s/ecstatic-kare-zukv3b?file=/src/NodeTags.jsx).

**Comment by bdbch** [comment]
Hey @chrispiech @Dreched 

While the isEditable value is not reactive by default, I pushed a change (see #2935) that should allow you to track the state of the editors editable state on your own.

It could look something like this:

```js
const [isEditable, setIsEditable] = useState(false)

const editor = useEditor(
  ...
  onUpdate(props) {
    setIsEditable(props.editor.isEditable)
  }
)
```

You can then use that state to make all of your components reactive (for example via context or any other state management solution).

**Comment by i-am-the-slime** [comment]
Is this meant to work now or did this just get closed because it was stale for a week?

**Comment by damien-schneider** [comment]
This issue shouldn't be closed imo because the problem isn't solve, as we expect the isEditable to trigger rerender as a state would do, the change help to have a workaround but it is still a workaround.

**Comment by bdbch** [comment]
Imho the properties of the editor instance should **not** be reactive by nature. It's a simple object property on the Editor instance, that you can get by accessing it on the editor.

Otherwise the question would be which properties would need to be reactive as well? I'd better let the developers integrate reactivity themselves.
