### ISSUE TITLE
TypeScript error for all Editor Menu buttons "Property 'toggleBold' does not exist on type 'ChainedCommands'"

### ISSUE THREAD

**Issue by edoPenneo** [ueberdosis/tiptap#2867]
### What’s the bug you are facing?

In the docs for React (https://tiptap.dev/installation/react) there's a sample menu for the editor, in JSX. Using the same code in a .TSX file throws an error for all chained methods, fx. toggleBold()

![image](https://user-images.githubusercontent.com/100683087/173016598-35005dbc-283b-4e35-b2eb-b932d6b89ba6.png)

### Which browser was this experienced in? Are any special extensions installed?

Chrome 102

### How can we reproduce the bug on our side?

Use the menu code from https://tiptap.dev/installation/react in a .TSX file

### What did you expect to happen?

This example should be type safe

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
@edoPenneo could you verify if this is still occuring and reopen this issue if it does?

**Comment by edoPenneo** [comment]
Got the latest version and TS is VERY happy. Thanks fort he fix @bdbch !

**Comment by Yeatlife** [comment]
Hello, i have THIS same problem, in the latest version
```
"@tiptap/react": "2.0.0-beta.209",
```

Any idea?

**Comment by joe-pomelo** [comment]
@Yeatlife I'm getting this error as well on `2.0.0-beta.209`. Reverting every package back to `2.0.0-beta.208` seems to be a temporary work around.

Similar issue here: #2898

cc @bdbch should I open a new issue for this?

**Comment by bdbch** [comment]
I already have a fix for this ready. We had to pin Typescript to a fixed version for now since the new Typescript version doesn't seem to resolve those types correctly. Should come in the following days.

**Comment by joe-pomelo** [comment]
Amazing, thank you so much!

**Comment by nperez0111** [comment]
@gethari it is unlikely that this issue has cropped up again, make sure that the extension is installed to your editor and being imported properly, typescript will only pick up on it if it is being imported a dependency of your project

**Comment by gethari** [comment]
@nperez0111 I am able to reproduce this issue in [Codesandbox](https://codesandbox.io/p/sandbox/nngxr9) on a fresh vanilla React+Typescript project. Can you please check this ?

**Comment by nperez0111** [comment]
@gethari Like I said, you don't have the extension installed, it is not included as part of the starter kit https://tiptap.dev/docs/editor/extensions/functionality/textalign#page-title

**Comment by gethari** [comment]
ah, okay okay understood, I had to do  `extensions: [StarterKit, TextAlign.configure()],` previously even without adding any extension config to the editor the TYPES would resolve automatically, now looks like something has been changed
