### ISSUE TITLE
The button doesn't react to the current mouse click word style ? 

### ISSUE THREAD

**Issue by shezhangzhang** [ueberdosis/tiptap#2868]
### What’s the bug you are facing?

Vue2
I copyed [this example](https://tiptap.dev/examples/default) in my vue2 project. And when I click the `bold` word, the `B` button didn't react to the current mouse click word style. BTW, how can I remove the blue border ? why the example doesn't have it ?
<img width="327" alt="image" src="https://user-images.githubusercontent.com/26793777/173019200-d6f030f2-563d-4864-9a81-3431327beaab.png">
<img width="358" alt="image" src="https://user-images.githubusercontent.com/26793777/173019556-e3e2afb8-c9cf-4053-b7bb-33f5144e412d.png">
Look at the Bold button👆

### Which browser was this experienced in? Are any special extensions installed?

Chrome latest

### How can we reproduce the bug on our side?

https://tiptap.dev/examples/default

VUE 2

### What did you expect to happen?

The button react to the current mouse click word style ?

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by shezhangzhang** [comment]
About the blue line, I figure it out :
```css
.ProseMirror {
  &:focus {
    outline: none;
  }
}
```
But the example code doesn't have it. I think:
If the user doesn't get the same result after copying and pasting, that's not a good example.

**Comment by shezhangzhang** [comment]
I got it, I need to add is-active css styles by myself.

Sorry, I'm a new user. Another quesion: 
H1
<img width="492" alt="image" src="https://user-images.githubusercontent.com/26793777/173035470-9d329699-8b22-4b4a-b9b4-29f9b764532d.png">

H2
<img width="486" alt="image" src="https://user-images.githubusercontent.com/26793777/173035553-3cee4ec1-b145-4be5-ae86-4c99d87323f1.png">

H3
<img width="480" alt="image" src="https://user-images.githubusercontent.com/26793777/173035619-5a9ae418-8cf6-482b-92ef-a5aec86d8f43.png">

Code:
<img width="611" alt="image" src="https://user-images.githubusercontent.com/26793777/173035775-3b502001-f061-43fe-a775-571e4a5ee3dd.png">


The font size is wrong, why ?

**Comment by shezhangzhang** [comment]
Does this repo still maintained?

**Comment by bdbch** [comment]
@shezhangzhang could you verify if this is still occuring and reopen this issue if it does? We pushed a fix start of this week.
