### ISSUE TITLE
Please add a setStyle/setClass command for selected node

### ISSUE THREAD

**Issue by Arturexe** [ueberdosis/tiptap#2869]
### What problem are you facing?

I need to add styles to an image.

### What’s the solution you would like to see?

`editor.commands.setStyle('ProseMirror-selectednode', { 'margin-inline': 'auto 0' })`

This style would align the node/image to the `right` in a very convenient way. Same thing could be done for `float` or `width`. It's kind of a loss, that `tiptap` doesn't provide a more convenient approach to utilize the power of `CSS`. It already has a clean `html` structure.

### What alternatives did you consider?

Fiddling around with custom extensions and custom vue components, all off which could be prevented by this command.

### Anything to add? (optional)

I love TipTap.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by dvago** [comment]
I have the same issue, it would be good to either describe how to achieve the above request or implement some extra methods.

It is also very appreciated if you could put some love in your official documentation 'cause it's really dreadful to understand what to expect from each exposed method.

**Comment by Haze272** [comment]
Same problem. I've seen that image extension has a ProseMirror selection style, but I still can't implement it to my custom nodes
+1

**Comment by ChetTheDev** [comment]
I was able to add classes to img following the instructions from this comment.
https://github.com/ueberdosis/tiptap/issues/586#issuecomment-836466931
