### ISSUE TITLE
[Help Needed] Propagating events from the extensions to Vue App

### ISSUE THREAD

**Issue by kshitizshankar** [ueberdosis/tiptap#288]
Hey - I am trying to explore how to write custom extensions to achieve my use cases but I am a bit stuck (seems I am missing something basic).

Use Case for me is - Creating Annotations on the text (Select Text - Create Annotations [Add styles, etc to represent them]).

I've been playing around with the Link.js Marks extension and have been able to get most of it working. 

<img width="498" alt="Annotation Created" src="https://user-images.githubusercontent.com/2092104/57215063-71acf180-701e-11e9-9fa5-eee2fdee4685.png">

What I am struggling with is how to propagate the click event on the annotation back to the Vue App. For example - the following code from the Link extension goes over opening the link in a new tab -

```
get plugins() {
    return [
      new Plugin({
        props: {
          handleClickOn(view, pos, node, nodePos, event) {
            const { schema } = view.state
            const attrs = getMarkAttrs(view.state, schema.marks.link)

            if (attrs.href && event.target instanceof HTMLAnchorElement) {
              event.stopPropagation()
              window.open(attrs.href)
            }
          },
        },
      }),
    ]
  }
```
instead of that if I had to say open a custom menu outside of the Editor - How should I go about that? How do I pass this event back to my Vue App to say open a settings panel?

Right now, I am using a hack around with the editor props where I am checking for the target for the click event and then executing the actions needed in my Vue App.

Thanks!!

**Comment by philippkuehn** [comment]
Maybe it helps you to create a node view (vue component) for this node and handle the click event in there. Or you can use a global event bus.
