### ISSUE TITLE
Remove `@types/lowlight` from `@tiptap/extension-code-block-lowlight` dependencies

### ISSUE THREAD

**Issue by EvitanRelta** [ueberdosis/tiptap#2880]
### What’s the bug you are facing?

Outdated type-declaration from `@types/lowlight` package, which is a dependency for `@tiptap/extension-code-block-lowlight`.
The `lowlight` package already declares its own types, thus, the outdated `@types/lowlight` should be removed from the extension's dependencies.

![image](https://user-images.githubusercontent.com/35413456/173502033-88665336-83ef-439f-a322-1fee0b136355.png)

### Which browser was this experienced in? Are any special extensions installed?

-

### How can we reproduce the bug on our side?

Install the `@tiptap/extension-code-block-lowlight`, which installs `@types/lowlight` as a dependency.
Then do:
```js
import { lowlight } from 'lowlight'
```
And you'll notice an error saying `Module '"lowlight"' has no exported member 'lowlight'.`

### Can you provide a CodeSandbox?

Not my codesandbox, but taken from another issue: https://github.com/ueberdosis/tiptap/issues/2116#issuecomment-957797324
https://codesandbox.io/s/trusting-lake-22hls

Notice the error on the lowlight import:
![image](https://user-images.githubusercontent.com/35413456/173503488-4eb53766-e152-45d1-bd53-dc07ab392102.png)

### What did you expect to happen?

To import the updated type-declaration from `lowlight` package instead of the outdated `@types/lowlight` package.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by autumninflab** [comment]
I have same issue

**Comment by rohitchouhan8** [comment]
If anyone is coming to look at this later. I'm using `"lowlight": "^3.1.0"`. The following code worked for me:

```tsx
import { createLowlight, common } from "lowlight";
const lowlight = createLowlight(common);

...

  CodeBlockLowlight.configure({
    lowlight,
    defaultLanguage: null,
  })
```
