### ISSUE TITLE
Prevent hard break from being created when shift + enter keys are pressed

### ISSUE THREAD

**Issue by sebpowell** [ueberdosis/tiptap#2881]
### What problem are you facing?

In our app, we'd like to allow the user to save the document they're working on by hitting 'shift + enter'. 

'Enter' would be used as normal to create new paragraphs. 

The above is working, but anytime the document is saved, a hard break is created at the same time. 

I was wondering if there's a way of preventing this from happening. Here's what I've tried so far:

```JSX
 <EditorContent
    editor={editor}
    onKeyDown={(event) => {
      if (event.shiftKey && event.key === "Enter") {
        event.stopPropagation();
        event.preventDefault();
        handleCreateItem();
        return false;
      }
      return false;
    }}
/>
```

I would have expected the `event.preventDefault()` line from stopping this from happening, but it doesn't, so wondering if it's possible at all?

### What’s the solution you would like to see?

Nothing to add here.

### What alternatives did you consider?

Nothing to add here.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
@sebpowell did you try @bpinto 's solution? this should work as you can just extend the already existing HardBreak extension. Closing this for now - feel free to reopen.

**Comment by sebpowell** [comment]
@bpinto @bdbch apologies for the late reply to this, I didn't get a chance to test it until the other day – but it works perfectly! 

Thank you very much @bpinto, greatly appreciated.
