### ISSUE TITLE
Add isBlank method for checking whether or not there is visible content (non-whitespace)

### ISSUE THREAD

**Issue by fergul** [ueberdosis/tiptap#2886]
### What problem are you facing?

It would be useful to be able to check if the document contains any visible content or is just whitespace. 

We currently have to use `editor.state.doc.textContent.length === 0` to check, which is both undocumented and breaks the nice abstraction Tiptap provides.

### What’s the solution you would like to see?

I've seen the previous discussion on isEmpty and it's history #2111. I think having both is valuable, but perhaps a method named `isBlank` or similar, which signals there's no visible content.

Happy to create the corresponding PR.

### What alternatives did you consider?

Continue to use `editor.state.doc.textContent.length === 0`.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Feel free to send in a PR for this issue @fergul. We'll rank this new feature at low priority for now since we have a working workaround.
