### ISSUE TITLE
@tiptap/starter-kit@2.0.0-beta.188 is published on npm but broken

### ISSUE THREAD

**Issue by fzaninotto** [ueberdosis/tiptap#2893]
### What’s the bug you are facing?

When installing @tiptap/starter-kit with a permissive version number, npm installs the last version available (https://www.npmjs.com/package/@tiptap/starter-kit/v/2.0.0-beta.188), and the app fails with a cryptic tiptap error message:

> Module build failed: Error: ENOENT: no such file or directory, open '/sandbox/node_modules/@tiptap/starter-kit/dist/tiptap-starter-kit.esm.js'

Please unpublish that version from npm and/or publish a newer version without the bug. 

### Which browser was this experienced in? Are any special extensions installed?

Codesandbox

### How can we reproduce the bug on our side?

Run the codesandbox

### Can you provide a CodeSandbox?

https://codesandbox.io/s/gallant-lederberg-9f9bu2?file=/src/index.tsx

### What did you expect to happen?

the build should not fail

### Anything to add? (optional)

Last version without error: beta-185

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by francoism90** [comment]
Same issue here:
```Module not found: Error: Can't resolve '@tiptap/starter-kit'```

**Comment by bastienmoulia** [comment]
No dist folder

**Comment by drellert** [comment]
Same issue with @tiptap/vue-2@2.0.0-beta.82

` ERROR  Failed to compile with 2 errors
These dependencies were not found:

* @tiptap/starter-kit in ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/TipTap.vue?vue&type=script&lang=js&
* @tiptap/vue-2 in ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/TipTap.vue?vue&type=script&lang=js&

To install them, you can run: npm install --save @tiptap/starter-kit @tiptap/vue-2`

Build works just fine with @tiptap/vue-2@2.0.0-beta.79

**Comment by bdbch** [comment]
Hey, thanks for your issues. We're aware of those issues and are working on a quick fix!

**Comment by Ophuscado** [comment]
I temporarily solved the issue by downgrading to `@tiptap/starter-kit@2.0.0-beta.185`.

**Comment by fzaninotto** [comment]
Thanks! Could you deprecate version 188 on npm?
