### ISSUE TITLE
@tiptap/vue-3@2.0.0-beta.94 not exist dist file

### ISSUE THREAD

**Issue by beliefgp** [ueberdosis/tiptap#2894]
### What’s the bug you are facing?

@tiptap/vue-3@2.0.0-beta.94 not exist dist file

### Which browser was this experienced in? Are any special extensions installed?

none

### How can we reproduce the bug on our side?

npm i @tiptap/vue-3@2.0.0-beta.94

### What did you expect to happen?

exist dist

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by beliefgp** [comment]
![image](https://user-images.githubusercontent.com/12657964/174282620-eb576a95-7ed7-4960-b61c-d10f58fdc237.png)

**Comment by Brianggalvez** [comment]
I can confirm 'Im having the same issue, also with StarterKit.

https://unpkg.com/@tiptap/vue-3@2.0.0-beta.94/dist/tiptap-vue-3.cjs.js 

Last valid version is https://unpkg.com/@tiptap/vue-3@2.0.0-beta.91/dist/tiptap-vue-3.cjs.js

and for StarterKit https://unpkg.com/@tiptap/starter-kit@2.0.0-beta.185/dist/tiptap-starter-kit.cjs.js

**Comment by masiorama** [comment]
I can confirm  @Brianggalvez suggested last valid working package versions

**Comment by SimonPrague** [comment]
Well, this broke our build completely. It would be nice if it could get fixed so that we can upgrade to the latest version. :) I appreciate all the hard work behind this package. Thanks a ton!

**Comment by rezaffm** [comment]
Fix (for the moment): https://github.com/ueberdosis/tiptap/issues/2895

**Comment by bdbch** [comment]
@beliefgp this should be resolved with the latest versions of our packages. Please update and try again. If you still experience problems reopen this issue and let me know.
