### ISSUE TITLE
@tiptap/vue-2@2.0.0-beta.82 missing dist-folder

### ISSUE THREAD

**Issue by drellert** [ueberdosis/tiptap#2895]
### What’s the bug you are facing?

Error when building project containing @tiptap/vue-2@2.0.0-beta.82:

```
ERROR  Failed to compile with 2 errors
These dependencies were not found:

* @tiptap/starter-kit in ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/TipTap.vue?vue&type=script&lang=js&
* @tiptap/vue-2 in ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/TipTap.vue?vue&type=script&lang=js&

To install them, you can run: npm install --save @tiptap/starter-kit @tiptap/vue-2
```

### Which browser was this experienced in? Are any special extensions installed?

N/A

### How can we reproduce the bug on our side?

Install @tiptap/vue-2@2.0.0-beta.82

### Can you provide a CodeSandbox?

See sandbox in https://github.com/ueberdosis/tiptap/issues/2893

### What did you expect to happen?

Build completed.

### Anything to add? (optional)

Build works just fine with @tiptap/vue-2@2.0.0-beta.79.

Same issue occurring with newest versions of @tiptap/starter-kit (https://github.com/ueberdosis/tiptap/issues/2893) and @tiptap/vue-3 (https://github.com/ueberdosis/tiptap/issues/2894)

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by boutell** [comment]
Same here. I believe we are sponsors. It looks like the "dist" folder didn't get built for all of your new releases, I've seen this so far for "vue-2" and "starter-kit", educated guess says probably some automated process for all didn't fire perhaps.

**Comment by bdbch** [comment]
Hey @boutell @drellert

exactly! We're already working on a fix and try out what went wrong on this release. It seems like the build process didn't create all dist folders but still published the package.

We'd suggest to use the version prior to the one released today - we'll close those issues when we released a new working version.

**Comment by rezaffm** [comment]
..jeez have the same - guys...

**Comment by rezaffm** [comment]
As mentioned by @bdbch 

```javascript
npm install @tiptap/vue-2@2.0.0-beta.79
```

is the temporary solution, for anyone on vue 3 it should be

```javascript
npm install @tiptap/vue-3@2.0.0-beta.91
```

**Comment by bdbch** [comment]
@drellert this should be resolved by our latest release. Could you update please and try again? Reopen the issue if you still have problems. Thanks.

**Comment by rezaffm** [comment]
hey... while the vue thing is fixed, a new bug comes up, mentioned here: https://github.com/ueberdosis/tiptap/issues/2905
