### ISSUE TITLE
React 18.2 and tiptap has missing property and modules

### ISSUE THREAD

**Issue by Crocsx** [ueberdosis/tiptap#2898]
### What’s the bug you are facing?

When using `react: 18.2.0` I get prompted with a lot of missing stuff from `tiptap`

for exemple 

`Cannot find module '@tiptap/starter-kit' or its corresponding type declarations.`

or 

```Property 'toggleBold' does not exist on type 'ChainedCommands'. Did you mean 'toggleNode'?ts(2551)```

This do not happen when using react: 17

### Which browser was this experienced in? Are any special extensions installed?

I am using 

```
    "@tiptap/extension-image": "^2.0.0-beta.27",
    "@tiptap/extension-table": "^2.0.0-beta.49",
    "@tiptap/extension-table-cell": "^2.0.0-beta.20",
    "@tiptap/extension-table-header": "^2.0.0-beta.22",
    "@tiptap/extension-table-row": "^2.0.0-beta.19",
    "@tiptap/extension-text-align": "^2.0.0-beta.29",
    "@tiptap/extension-underline": "^2.0.0-beta.23",
    "@tiptap/react": "^2.0.0-beta.109",
    "@tiptap/starter-kit": "^2.0.0-beta.185",
    "react": "18.2.0",
    "react-dom": "18.2.0",
```

also tried with latest tiptap

### How can we reproduce the bug on our side?

If you check the file App.tsx in this codesandbox

https://codesandbox.io/s/area-chart-in-responsive-container-forked-mbdybx?file=/src/App.tsx

### Can you provide a CodeSandbox?

If you check the file App.tsx in this codesandbox

react 18 => errors
https://codesandbox.io/s/area-chart-in-responsive-container-forked-yschmj?file=/src/App.tsx

react 17 => no problems
https://codesandbox.io/s/area-chart-in-responsive-container-forked-mbdybx?file=/src/App.tsx

### What did you expect to happen?

It should not have those compilation error in react 18

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by raRaRa** [comment]
Same issue here, using React 18.2.0

**Comment by yoniakabecky** [comment]
Had the same issue. For me, removing `^` fixes it.
`“@tiptap/starter-kit”: “2.0.0-beta.185"`

**Comment by bdbch** [comment]
We had a faulty build which lead to dist-folders not being built correctly. We just merged a fix for this so this should be gone with the next release.
