### ISSUE TITLE
Multiple Editors generate "Unexpected case" error when rendered iteratively (instead of each rendered imperatively)

### ISSUE THREAD

**Issue by ifandelse** [ueberdosis/tiptap#2899]
### What’s the bug you are facing?

I am attempting to use the Collaboration plugin to enable "sub-documents". The [multiple editors](https://tiptap.dev/experiments/multiple-editors) example shows this working, but the 3 editors/sub-documents are known ahead of time and instantiated imperatively in the mounted hook. In a real world scenario, it's likely you'd have a document, and a list of "fields" (sub doc names) that exist in the document and then need to render n-number of editors (1 for each field). in my use case, I need to render them in a list, much like a scrollable journal stream. 

To determine the feasibility of this, I took the existing "multiple editors" example and moved the state specific to each editor (the title, the css class applied to it and the editor instance) and put them in a computed array member, and then iterated over that list in the template to render each one. You can see this example approach in [this gist](https://gist.github.com/ifandelse/8c0176d9487e49165273050617b99f69). (I've tried several approaches to rendering subdocuments that involve iterating over a list of field names, or even allowing the user to click a button to add a new subdocument (since the collaboration extension is just calling `getXmlFragment` when a field name is passed). All result in the same error, so I tried to provide the simplest possible example to minimize confusion).

The moment I move the editor instantiation into an array like this, I start seeing the following error:
<img width="509" alt="image" src="https://user-images.githubusercontent.com/197026/174446922-707c08f3-6073-4a2f-bc57-b05b0f6f78c6.png">

### Which browser was this experienced in? Are any special extensions installed?

I don't think the browser is the culprit, but I'm seeing it in latest Firefox (no add-ins installed) and latest Chrome (Vue dev tools installed.

### How can we reproduce the bug on our side?

- Take the contents of [my gist](https://gist.github.com/ifandelse/8c0176d9487e49165273050617b99f69) and paste them into the `tiptap/demos/src/Experiments/MultipleEditors/Vue/index.vue` file (replacing the contents of the file)
- `npm run build:demos`
- `npm start`
- browse to http://localhost:3000/preview/Experiments/MultipleEditors
- view the browser console for the errors

### Can you provide a CodeSandbox?

Apologies - no, the existing code sandbox link above is broken due to an error `Could not find module in path: '@tiptap/vue-3' relative to '/src/App.vue'`.

The alternative I provided above should be as easy as the sandbox idea - just paste in my gist to that one example and run the example demos.

### What did you expect to happen?

I expected the 3 editors to render, much like the original example, without the need for each editor to be declaratively provided separately (i.e. - multiple `editor-content` components declared ahead of time instead of being able to `v-for` over the collection to render them)

### Anything to add? (optional)

The error appears to be coming from yjs via the sync-plugin call stack, though I'm not sure that either of those libs are the culprit. 

UPDATE: I've discovered that if I move the editors' instantiation out into a method (instead of using a computed property), and then wrap everything in a try/catch, and have the catch attempt to re-invoke the method to try again, it works. It's acting as if there is either an async race condition present, or some bit of state not initialized correctly the first time, but attempting again after the error path has been reached results in it working.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Now the question would be:

- Do you need your editorInstances to be computed by some other value?
- Do you need access to your YDoc? For example with my gist, you could save the ydoc constant from the mounted method to `this.doc` afterwards so the editors are initialized without a Proxy but the VueComponent still has access to the document afterwards.

**Comment by bdbch** [comment]
I'll close this for now - if you still have issues let me know and feel free to reopen this issue!
