### ISSUE TITLE
Module not found: Can't resolve '@tiptap/extension-code-block'

### ISSUE THREAD

**Issue by hoyuenkim** [ueberdosis/tiptap#2901]
### What’s the bug you are facing?

This is my environment.

"react": "^18.1.0",
"next": "^12.1.6",

    "@tiptap/react": "^2.0.0-beta.112",
    "@tiptap/starter-kit": "^2.0.0-beta.185",

To solve starter-kit issue. I downgrade it from beta.188 to beta.185

But after I change the version.

Module not found: Can't resolve '@tiptap/extension-code-block'

happens and when I access the folder. There is nothing in it.

Please check this,

### Which browser was this experienced in? Are any special extensions installed?

No special extensions.

Chrome Version 102.0.5005.115 (Official Build) (64-bit)

### How can we reproduce the bug on our side?

This is my environment.

"react": "^18.1.0",
"next": "^12.1.6",

    "@tiptap/react": "^2.0.0-beta.112",
    "@tiptap/starter-kit": "^2.0.0-beta.185",

Do it in same environment

### What did you expect to happen?

Just want to import the package. And want to use it.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by jinjinyun** [comment]
There is no dist folder in node_modules/@tiptap/vue-2.
@tiptap/vue-2 and @tiptap/starter-kit also have the same bug

**Comment by bdbch** [comment]
Hey @jinjinyun we just merged a fix for that. We had a faulty build which should hopefully be gone with the next release! We'll release ASAP.

**Comment by bdbch** [comment]
This should be resolved with the latest release of the packages. Please try updating.
