### ISSUE TITLE
Error: Must use import to load ES Module - @tiptap/extension-table

### ISSUE THREAD

**Issue by tiendatleo** [ueberdosis/tiptap#2905]
### What’s the bug you are facing?

After I upgraded to new tiptap version, an error occured:

`Must use import to load ES Module: /Users/datnguyen/Documents/Projects/sapp-enduser/node_modules/prosemirror-tables-contently/dist/index.js require() of ES modules is not supported. require() of /Users/datnguyen/Documents/Projects/sapp-enduser/node_modules/prosemirror-tables-contently/dist/index.js from /Users/datnguyen/Documents/Projects/sapp-enduser/node_modules/@tiptap/extension-table/dist/tiptap-extension-table.cjs.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules. Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/datnguyen/Documents/Projects/sapp-enduser/node_modules/prosemirror-tables-contently/package.json.`

### Which browser was this experienced in? Are any special extensions installed?

MacOS 12.3.1
Chrome Version 102.0.5005.115 (Official Build) (arm64)
Node v14.18.3
NPM 6.14.15

```
{
"@tiptap/extension-color": "^2.0.0-beta.9",
"@tiptap/extension-image": "^2.0.0-beta.24",
"@tiptap/extension-link": "^2.0.0-beta.35",
"@tiptap/extension-table": "^2.0.0-beta.46",
"@tiptap/extension-table-cell": "^2.0.0-beta.20",
"@tiptap/extension-table-header": "^2.0.0-beta.22",
"@tiptap/extension-table-row": "^2.0.0-beta.19",
"@tiptap/extension-text-align": "^2.0.0-beta.29",
"@tiptap/extension-text-style": "^2.0.0-beta.23",
"@tiptap/extension-underline": "^2.0.0-beta.22",
"@tiptap/starter-kit": "^2.0.0-beta.189",
"@tiptap/vue-2": "^2.0.0-beta.83",
}
```

### How can we reproduce the bug on our side?

Install the same package versions above.

### What did you expect to happen?

Don't throw the error.

### Anything to add? (optional)

![Uploading image.png…]()

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by tiendatleo** [comment]
![Untitled](https://user-images.githubusercontent.com/25786110/174781924-ab18b396-0494-4d38-bd54-333b9e5fc276.png)

I guess the error come from here.

**Comment by bdbch** [comment]
Seems like the prosemirror-tables-contently package is not exporting commonjs files, see here:
https://github.com/ProseMirror/prosemirror-tables/issues/96#issuecomment-1162151390

@mbostler could you implement a commonjs solution for those who are using cjs?

**Comment by rootlinux2** [comment]
I'm facing the same issue

**Comment by tiendatleo** [comment]
> 

The error throwed although I don't use cjs

**Comment by tiendatleo** [comment]
> Seems like the prosemirror-tables-contently package is not exporting commonjs files, see here: [ProseMirror/prosemirror-tables#96 (comment)](https://github.com/ProseMirror/prosemirror-tables/issues/96#issuecomment-1162151390)
> 
> @mbostler could you implement a commonjs solution for those who are using cjs?


The error throwed although I don't use cjs

**Comment by bdbch** [comment]
That's weird since in your screenshot, the error comes from the `tiptap-extension-table.cjs.js` which is the commonjs variant of this extension (and since it's not using import there but require it's failing).

@rootlinux2 could you explain a bit more what kind of bug you're experiencing? In the PR you linked we switched from `prosemirror-tables` to `prosemirror-tables-contently` as a workaround until prosemirror moves away from buble to babel. I guess it's originating from there?

**Comment by simllll** [comment]
We are experience exactly the same thing:
`require() of ES Module /home/simon/Dev/hokify/hokify-server/node_modules/prosemirror-tables-contently/dist/index.js from /home/simon/Dev/hokify/hokify-server/node_modules/@tiptap/extension-table/dist/tiptap-extension-table.cjs.js not supported. index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules. Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /home/simon/Dev/hokify/hokify-server/node_modules/prosemirror-tables-contently/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).`

I guess prosemirror-tables-contently is an ESM module, but exstension-table is not?

**Comment by tylerstephens814** [comment]
Also have this issue

**Comment by tiendatleo** [comment]
> 



> We are experience exactly the same thing: `require() of ES Module /home/simon/Dev/hokify/hokify-server/node_modules/prosemirror-tables-contently/dist/index.js from /home/simon/Dev/hokify/hokify-server/node_modules/@tiptap/extension-table/dist/tiptap-extension-table.cjs.js not supported. index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules. Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /home/simon/Dev/hokify/hokify-server/node_modules/prosemirror-tables-contently/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).`
> 
> I guess prosemirror-tables-contently is an ESM module, but exstension-table is not?
> 
> We are using nuxt2 with vue2, which uses webpack and esm modules under the hood actually. so maybe the issue is even that tiptap-exstension-table.cjs is loaded insteda of the es version? not sure what's going on, but it's defintility related to the latest release.
> 
> **# Possbile fix 1** removing "type": module from prosemirror-tables-contently's package.json fixes the issue on my side
> 
> **# possible fix 2 - the nuxt way** ~adding prosemirror-tables-contently to transpile config optoins in nuxt fixes the issue too! Which actually lets me believe that the nuxt webpack4 setup is not really using es modules.. my fault ;)~ nope sorry, the file cache played me wrong here, it was still the "type": "module" removable that let this thing working
> 
> **# real possible fix 2 - the nuxt way** adding borth '@tiptap/extension-table' and 'prosemirror-tables-contently' to transpile config option in nuxt fixes it (for now ;-))! nuxt.config.js: ![image](https://user-images.githubusercontent.com/5757263/175073583-6c05d568-ee40-4773-90e7-0227fbc0ccb9.png)

![image](https://user-images.githubusercontent.com/25786110/175192019-d9bf3bce-6526-4b23-8b2f-02b7fa7dc787.png)
I tried the 3rd solution but it was not resolve my issue.
We all waiting for the official fix.

**Comment by tiendatleo** [comment]
> @bdbch I'm using the TipTap library to create a custom Rich Text Editor, I have been using this text editor for a year, but yesterday my CI/CD fails to deploy the platform, and after a time checking the logs I just figured it out is related to this issue.
> 
> This is the error message,
> 
> > 
> 
> (node:44199) UnhandledPromiseRejectionWarning: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/rootlinux2/Documents/Front10/apexedge-widgets/node_modules/prosemirror-tables-contently/dist/index.js require() of ES modules is not supported. require() of /home/rootlinux2/Documents/Front10/apexedge-widgets/node_modules/prosemirror-tables-contently/dist/index.js from /home/rootlinux2/Documents/Front10/apexedge-widgets/node_modules/@tiptap/extension-table/dist/tiptap-extension-table.cjs.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules. Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/rootlinux2/Documents/Front10/apexedge-widgets/node_modules/prosemirror-tables-contently/package.json.
> 
> ```
> at new NodeError (internal/errors.js:322:7)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
> at Module.load (internal/modules/cjs/loader.js:950:32)
> at Function.Module._load (internal/modules/cjs/loader.js:790:12)
> at Module.require (internal/modules/cjs/loader.js:974:19)
> at require (internal/modules/cjs/helpers.js:101:18)
> at Object.<anonymous> (/home/rootlinux2/Documents/Front10/apexedge-widgets/node_modules/@tiptap/extension-table/dist/tiptap-extension-table.cjs.js:7:34)
> at Module._compile (internal/modules/cjs/loader.js:1085:14)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
> at Module.load (internal/modules/cjs/loader.js:950:32)
> ```
> 
> (Use `node --trace-warnings ...` to show where the warning was created)

**Comment by tiendatleo** [comment]
> We are experience exactly the same thing: `require() of ES Module /home/simon/Dev/hokify/hokify-server/node_modules/prosemirror-tables-contently/dist/index.js from /home/simon/Dev/hokify/hokify-server/node_modules/@tiptap/extension-table/dist/tiptap-extension-table.cjs.js not supported. index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules. Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /home/simon/Dev/hokify/hokify-server/node_modules/prosemirror-tables-contently/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).`
> 
> I guess prosemirror-tables-contently is an ESM module, but exstension-table is not?
> 
> We are using nuxt2 with vue2, which uses webpack and esm modules under the hood actually. so maybe the issue is even that tiptap-exstension-table.cjs is loaded insteda of the es version? not sure what's going on, but it's defintility related to the latest release.
> 
> **# Possbile fix 1** removing "type": module from prosemirror-tables-contently's package.json fixes the issue on my side
> 
> **# possible fix 2 - the nuxt way** ~adding prosemirror-tables-contently to transpile config optoins in nuxt fixes the issue too! Which actually lets me believe that the nuxt webpack4 setup is not really using es modules.. my fault ;)~ nope sorry, the file cache played me wrong here, it was still the "type": "module" removable that let this thing working
> 
> **# real possible fix 2 - the nuxt way** adding borth '@tiptap/extension-table' and 'prosemirror-tables-contently' to transpile config option in nuxt fixes it (for now ;-))! nuxt.config.js: ![image](https://user-images.githubusercontent.com/5757263/175073583-6c05d568-ee40-4773-90e7-0227fbc0ccb9.png)

![image](https://user-images.githubusercontent.com/25786110/175192019-d9bf3bce-6526-4b23-8b2f-02b7fa7dc787.png)
I tried the 3rd solution but it was not resolve my issue.
We all waiting for the official fix.

**Comment by bdbch** [comment]
We weren't able to publish a release yet. I'll be away on vacation from next week until the the 5th of July so I won't be able to respond. My colleagues @svenadlung @montapro or @mkriegeskorte will assist you in behalf of me!

I'll try to keep track from my phone when I'm away.

**Comment by tiendatleo** [comment]
Just removed ./node_modules and package-lock.json then no error occurred.

My tiptap packages:
    "@tiptap/core": "^2.0.0-beta.180",
    "@tiptap/extension-color": "^2.0.0-beta.9",
    "@tiptap/extension-image": "^2.0.0-beta.24",
    "@tiptap/extension-link": "^2.0.0-beta.35",
    "@tiptap/extension-table": "^2.0.0-beta.46",
    "@tiptap/extension-table-cell": "^2.0.0-beta.20",
    "@tiptap/extension-table-header": "^2.0.0-beta.22",
    "@tiptap/extension-table-row": "^2.0.0-beta.19",
    "@tiptap/extension-text-align": "^2.0.0-beta.29",
    "@tiptap/extension-text-style": "^2.0.0-beta.23",
    "@tiptap/extension-underline": "^2.0.0-beta.22",
    "@tiptap/starter-kit": "^2.0.0-beta.189",
    "@tiptap/vue-2": "^2.0.0-beta.83",

**Comment by svenadlung** [comment]
We just published a new release yesterday. Could you please reinstall node modules and give it another try?

**Comment by tiendatleo** [comment]
> We just published a new release yesterday. Could you please reinstall node modules and give it another try?

Resolved. Thank you

**Comment by rootlinux2** [comment]
> We just published a new release yesterday. Could you please reinstall node modules and give it another try?

Works for me! Thanks
