### ISSUE TITLE
Focus extension for marks

### ISSUE THREAD

**Issue by joppehoekstra** [ueberdosis/tiptap#2909]
### What problem are you facing?

When a user's cursor is inside a link, and the user changes the link, there is no visual indication this will be applied to the whole link. I would like the whole link to be highlighted when a cursor is placed inside.

### What’s the solution you would like to see?

I would like a .has-focus class to be applied to focussed marks in addition to the focussed nodes.

### What alternatives did you consider?

A more advanced Link extension that not only adds a .has-focus class when a cursor is placed inside, but also has gap cursor that can move from within the link to outside the link. This would solve the issue where a line ends with a link, and it becomes impossible to type on that line without making it all a link. I've made a [video](https://www.youtube.com/watch?v=irTtMGbsYSU) of what this could look like.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
So you would like this on any mark? Not only the link extension?

**Comment by joppehoekstra** [comment]
> So you would like this on any mark? Not only the link extension?

Right now, I can only think of a use case for the link extension.
