### ISSUE TITLE
Conflict between tiptap and loadingio/loading-bar

### ISSUE THREAD

**Issue by PedroJBrito** [ueberdosis/tiptap#2917]
### What’s the bug you are facing?

Hi,

I'm using nextjs and I have a page wich displays a chart using the library loadingio/loading-bar. Then I have a button to display an editor, where tiptap comes in, and that's when the problem appears. In isolation both libraries works fine, however when I have the chart already displayed and then I add the tiptap on that page the app brokes.

### Which browser was this experienced in? Are any special extensions installed?

Chrome

### How can we reproduce the bug on our side?

I have this simple demo where you can reproduce the problem by clicking on the button, which is a similar approach to what I have in my app.

https://codesandbox.io/s/tiptap-loadingio-fr4fj1

### Can you provide a CodeSandbox?

https://codesandbox.io/s/tiptap-loadingio-fr4fj1

### What did you expect to happen?

N/A

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
This seems to be an issue with `@loadingio/loading-bar` as it's trying to do something with the react editor. I don't quite understand what it's doing there.

From the repository I'd suggest to look for an alternative as `@loadingio/loading-bar` was last maintained 3 years ago and could even break other libraries.
