### ISSUE TITLE
add soft hyphen

### ISSUE THREAD

**Issue by ag-coder** [ueberdosis/tiptap#2923]
### What’s the bug you are facing?

I did a custom button to add the soft hyphen &shy;  with` .insertContent('&shy;')`
But the editor renders of course `&amp;shy;`

How can I prevent the plus sign from being converted to HTML?

### Which browser was this experienced in? Are any special extensions installed?

all default

### How can we reproduce the bug on our side?

try with with .insertContent('&shy;')

### What did you expect to happen?

keep &shy; in editor and text

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Could you spin up a quick sandbox with an example for this issue?

**Comment by ag-coder** [comment]
i solved the problem with the unicode for the  soft hyphen `.insertContent('\u00ad')`
