### ISSUE TITLE
Pressing `Delete` on an empty paragraph clears the node afterwards

### ISSUE THREAD

**Issue by rfgamaral** [ueberdosis/tiptap#2924]
### What’s the bug you are facing?

This is better explained with a short demo:

![firefox_4DBYnuFKvn](https://user-images.githubusercontent.com/96476/175537376-c451095b-7c62-496c-bbbf-a0b8d740d3f8.gif)

### Which browser was this experienced in? Are any special extensions installed?

All of them. No special extensions.

### How can we reproduce the bug on our side?

Use the [default example](https://tiptap.dev/examples/default) editor, and replicate what you see in the GIF above.

### What did you expect to happen?

Pressing `Delete` on an empty paragraph (or `Shift + Backspace` on macOS, I believe), should delete the empty paragraph where the text cursor is located (and not clear the node that comes afterwards).

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖 _(on behalf of Doist)_

**Comment by bdbch** [comment]
Thanks, set the priority to high in our project board! Should definitely be fixed as soon as we get all those typing issues fixed.

**Comment by rfgamaral** [comment]
@bdbch This issue still exists, do you think this could be reopened, and possibly some attention?

**Comment by bdbch** [comment]
Hey @rfgamaral I'm looking into it now

**Comment by bdbch** [comment]
It seems like it's not happening with all nodes. From what I've seen lists and blockquotes are effected, but code blocks and headlines stay the same.

**Comment by bdbch** [comment]
It also seems like this bug is introduced by Prosemirror as it also happens on their examples site. I created an issue there: https://github.com/ProseMirror/prosemirror/issues/1309

Would be nice if you could bump it. Is it okay for you if we close this issue and hope this problem gets resolved within Prosemirror? I'm not sure if we can intercept that behavior on our side.

**Comment by rfgamaral** [comment]
@bdbch Do you think this is something that you'll want to fix on Tiptap, or leave it as-is?

The current behaviour is not very common, and I couldn't find any other non ProseMirror based editors that would behave in the same way. IMO, pressing delete should delete the empty paragraph, and not "unwrap the node ahead".

**Comment by bdbch** [comment]
As it seems this behaviour is intended by marijnh I'd say we should look into it again.
Do you think it should be configurable or should we change the "default" from Prosemirror on the editor behaviour here?

Also I think this happens for different types of nodes so we would need to do this handling for everything, right?

**Comment by rfgamaral** [comment]
> Do you think it should be configurable or should we change the "default" from Prosemirror on the editor behaviour here?

In a way, this is already configurable, by overriding the `Delete` keyboard shortcut.

So, if you want to keep the current behaviour the default, I can work around this on my side (although I'm having some difficulty finding out the right set of commands to run to achieve this). But IMO, a more natural and common behaviour would be to do this built-in

> Also I think this happens for different types of nodes so we would need to do this handling for everything, right?

Not exactly sure what you mean, but tweaking the `Delete` keyboard shortcut should do the trick for all types of nodes.
