### ISSUE TITLE
chore: the key is selected in the props of the nodeview is invalid when clicked collaboratively

### ISSUE THREAD

**Issue by HondryTravis** [ueberdosis/tiptap#2927]
### What’s the bug you are facing?

In collaborative mode, we know that prosemirror achieves collaboration through rebase, so this selected attribute [vue2 nodeview] has been rebase all the time, so multiple clients have been updating this attribute, which makes us unable to render the current nodeview because the selected attribute is true Some operations done at the time, because selected has been calculated and delayed. how to solve this problem。

It has been updated and calculated under the coordination, and the selected state of our nodeview cannot be preserved

i mean selected props from `tiptap/packages/vue-2/src/VueNodeViewRenderer.ts`
```ts
export const nodeViewProps = {
  editor: {
    type: Object as PropType<NodeViewProps['editor']>,
    required: true as const,
  },
  node: {
    type: Object as PropType<NodeViewProps['node']>,
    required: true as const,
  },
  decorations: {
    type: Object as PropType<NodeViewProps['decorations']>,
    required: true as const,
  },
  selected: { // this props
    type: Boolean as PropType<NodeViewProps['selected']>,
    required: true as const,
  },
  extension: {
    type: Object as PropType<NodeViewProps['extension']>,
    required: true as const,
  },
  getPos: {
    type: Function as PropType<NodeViewProps['getPos']>,
    required: true as const,
  },
  updateAttributes: {
    type: Function as PropType<NodeViewProps['updateAttributes']>,
    required: true as const,
  },
  deleteNode: {
    type: Function as PropType<NodeViewProps['deleteNode']>,
    required: true as const,
  },
}

```

### Which browser was this experienced in? Are any special extensions installed?

chorm/edge 102  all the same，browser independent

### How can we reproduce the bug on our side?

just useing nodeview[vue-2] selected attribute to do some state selection effects of nodeview，it's not working

### What did you expect to happen?

fix or a suggestion?

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Hey @HondryTravis thanks for your issue and describing it in english.

I'm trying to understand the problem you're explaining. As far as I understood - when used in collaborative editing the `selected` property is behaving weird because other clients are updating this property as well?

Could you show us an example on how you setup your editor so I can replicate your problem?

**Comment by HondryTravis** [comment]
thanks for your reply @bdbch. : )

yep, but unable to provide online examples。I try to reproduce my operation

1. A user [foucs event]foucs this picture，selected will trrgger `true`, so we actions displayed for selections on image wrappers, just look like this
<img width="713" alt="image" src="https://user-images.githubusercontent.com/24218012/175759871-67e19fdb-9c99-4ba0-b25d-d7fb7a621787.png">

2.[client At B]B user input somthing words, okey fine, [client At A ]this focus event not working(delayed execution) A user clicks on this image and cannot be selected(focus event -> selected - true) and wrap a selection state

**Comment by HondryTravis** [comment]
It's also a problem with my implementation method, but this isn't actually a bug : )

**Comment by bdbch** [comment]
Ah I understand. Did you find a solution as you just said it's your implementation method? Otherwise I'll try to setup my own collaboration editor as soon as I find time to figure out how to avoid this issue.

**Comment by HondryTravis** [comment]
method 1: add new click event In the global event(not delayed execution), also need to try to reproduce
method 2: record this selected  props, store it in nodeview data `data-selected="true"` like this

I will close this question, thank you so so so much @bdbch ~ ❤️
