### ISSUE TITLE
The 'data-drag-handle' drags inappropriate element

### ISSUE THREAD

**Issue by GergoMiklos** [ueberdosis/tiptap#2930]
### What’s the bug you are facing?

I created my own wrapped version of the `BulletList` and `ListItem` extensions to add a drag handle `span` element to them:

```
const dragHandleAttrs = {
  class: "drag-handle",
  contenteditable: "false",
  "data-drag-handle": ""
};

// draggable list item
const CustomListItem = ListItem.extend({
  draggable: true,
  parseHTML() {
    return [{ tag: "dli" }];
  },
  renderHTML: ({ HTMLAttributes }) => {
    return [
      "dli",
      mergeAttributes(HTMLAttributes, { }),
      ["span", dragHandleAttrs],
      ["li", 0]
    ];
  }
});

// draggable unordered list
const CustomBulletList = BulletList.extend({
  draggable: true,
  parseHTML() {
    return [{ tag: "dul" }];
  },
  renderHTML: ({ HTMLAttributes }) => {
    return [
      "dul",
      mergeAttributes(HTMLAttributes, { }),
      ["span", dragHandleAttrs],
      ["ul", 0]
    ];
  }
});
```
It seems to be good, but after dragging the whole list by its handle, each of the item handles also drag the whole list and not the separated items as I would expect. After editing an item, it works correctly again.

### Which browser was this experienced in? Are any special extensions installed?

CodeSandbox, Chrome

### How can we reproduce the bug on our side?

See the [CodeSandbox](https://codesandbox.io/s/tiptap-draggable-wrapper-pi3xhc?file=/src/App.js) with instructions:

1. Drag an item: ok
2. Drag the whole list: ok
3. Drag an item again: not ok, drags the whole list
4. Edit an item: ok
5. Drag an item: ok

It can fail in the other way also:

1. Drag the first item: ok
2. Drag the whole list: not ok, only the first item is moved

### Can you provide a CodeSandbox?

[CodeSandbox](https://codesandbox.io/s/tiptap-draggable-wrapper-pi3xhc?file=/src/App.js)

### What did you expect to happen?

The element with data-drag-handler always drags its closest element with draggable=true or its parent

### Anything to add? (optional)

I like TipTap, thank you!

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Hey! I could imagine this being a focus or state issue as you don't really need to edit anything but just change your focus inside the editor to somewhere else except a drag handler.
