### ISSUE TITLE
I want to delete the package but extension-code-block prevents delete it.

### ISSUE THREAD

**Issue by hoyuenkim** [ueberdosis/tiptap#2933]
### What’s the bug you are facing?

There was an issue at the former version so I want to update or remove the package but

C:\Users\***\OneDrive - Infobip Ltd\Documents\dev\project 1\frontend\node_modules
\@tiptap\extension-code-block' -> 'C:\Users\***\OneDrive - Infobip Ltd\Documents\dev\project 1\frontend\node_modules\@tipt
ap\.extension-code-block-gvwSsOgv'

It says that I have to change the name of the folder but it is not possible.

Also, I can not delete it by using force or any way.

Please Kindly check this issue.

### Which browser was this experienced in? Are any special extensions installed?

No

### How can we reproduce the bug on our side?

    "@tiptap/react": "^2.0.0-beta.112",
    "@tiptap/starter-kit": "^2.0.0-beta.185",

### What did you expect to happen?

remove the package folder

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
This seems to be a problem with Windows file permissions. Could you see if any NPM process is hanging, if so close it and try again? Or try to delete the folder with administrator permissions? Otherwise we can't really do anything here.
