### ISSUE TITLE
NodeViewContent was initially empty with nodeInput.

### ISSUE THREAD

**Issue by aleversn** [ueberdosis/tiptap#2936]
### What’s the bug you are facing?

I am trying to build a task item reference to the tiptap taskitem, and it seems to work well on the old version.
However, when I used the input rule "[ ] " to create a task item, the `node-view-content` is empty.

Then I type one `Enter` and several `Backspace` keys, the `node-view-content` seems to be re-rendered and inserts a paragraph with a `<br>`:
```html
<p><br class="ProseMirror-trailingBreak"></p>
``` 

I wonder if it is a bug of the `node-view-content`? If not, is there any way to define the initial content into `node-view-content`?

Right now I can only use the `insertContent` function with `content` to solve the issue.
```javascript
            this.editor
                .chain()
                .focus()
                .insertContent({
                    type: 'powerTaskItem',
                    content: [
                        {
                            type: 'paragraph',
                        },
                    ],
                })
                .run();
```

### Which browser was this experienced in? Are any special extensions installed?

Edge 103 and Chrome 103.

### How can we reproduce the bug on our side?

My project's sandbox is in here:

- taskItem.vue
https://codesandbox.io/s/infallible-sanderson-rzuj73?file=/src/modules/editor/src/components/custom/source/taskItem.vue

- taskItem.js
https://codesandbox.io/s/infallible-sanderson-rzuj73?file=/src/modules/editor/src/components/custom/extension/taskItem.js

### Can you provide a CodeSandbox?

Yes

### What did you expect to happen?

The taskItem component works well without layout issues when initially created.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by yellow1912** [comment]
Hello,

You ever got your issue resolved? I think I may have the same issue.

**Comment by aleversn** [comment]
Not yet, I made a new issue in #2974 with simpler description, you can subscribe to that issue for the latest progress.
