### ISSUE TITLE
Input rules seem completely broken

### ISSUE THREAD

**Issue by rfgamaral** [ueberdosis/tiptap#2937]
### What’s the bug you are facing?

I don't know what changed, but inline code marks were working before, and now they aren't:

https://user-images.githubusercontent.com/96476/176157179-7552db5d-d890-4ea6-9841-367975d9bf27.mp4

EDIT: Just noticed that this problem is not exclusive to inline code marks, but all other input rules as well. For instance, open the default editor, and try to type `**` before a word, you'll quickly realize there's an issue (and you won't be able to type `**` after the word, to turn the word bold).

### Which browser was this experienced in? Are any special extensions installed?

All of them. No special extensions.

### How can we reproduce the bug on our side?

Use the [default text editor](https://tiptap.dev/examples/default), and try to use backticks to applied inline code marks.

### What did you expect to happen?

Inline code marks with backticks should work without issues, as they did in the past.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖 _(on behalf of Doist)_

**Comment by svenadlung** [comment]
@rfgamaral I made a PR yesterday. I tried to put you as a reviewer but I failed. Feel free to try my changes: https://github.com/ueberdosis/tiptap/pull/2941
