### ISSUE TITLE
Incorrect content range  in PasteRule find, returning non-pasted content, creating invalid links etc.

### ISSUE THREAD

**Issue by Billiam** [ueberdosis/tiptap#2939]
### What’s the bug you are facing?

When pasting content, the rules generated by MarkPasteRule will use an incorrect range when returning text for the `find` method, and return non-pasted adjacent text in addition.

In my app, this is breaking URL pasting, as unrelated content is included in the pasted URL, which ends up in both the link text and href.

Using chrome's debugger, I can see that the text passed to the `find` method includes the next character after the cursor on paste.

Since this code is used in a number of other places, I believe it may be affecting of other extensions and/or internals, but the first place I've run into (obvious) issues is with the Link extension, when autolink is disabled (autolink disguises the issue).

This issue is unrelated to the linkifyjs code itself, since the content which is passed to it is already incorrect.

### Which browser was this experienced in? Are any special extensions installed?

Using Chrome 103, also occurring in Firefox, and Safari, on multiple machines/OSes.

### How can we reproduce the bug on our side?

1. Visit https://codesandbox.io/s/tiptap-link-paste-bz73kv
2. Paste a URL (like `https://tiptap.dev`) at the beginning of the existing text
3. Observe that the first character of the existing text is included in the resulting link text and href (ex: `<a href="https://tiptap.devP">https://tiptap.devP</a>`)

More insidiously, if the next character isn't plain text, but is instead a hard break, the link will be created like this:

`<a href="https://tiptap.dev/￼">https://tiptap.dev/<br></a>`, where the last character will be the unicode Object Replacement Character, and then get URL encoded to `%EF%BF%BC` when clicked. It won't be visually obvious this has occurred, but the link will be broken.

### Can you provide a CodeSandbox?

Yep! https://codesandbox.io/s/tiptap-link-paste-bz73kv

### What did you expect to happen?

Text passed to the paste rule's `find` method only includes pasted content, rather than any existing/surrounding content.

### Anything to add? (optional)

The autolink behavior in the Link extension obscures some of this, since (when enabled) any adjacent text is also linkified.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by Billiam** [comment]
I believe this is an issue with [PasteRule's appendTransaction method](https://github.com/ueberdosis/tiptap/blob/main/packages/core/src/PasteRule.ts#L213-L234).

The `to` and `from` positions represent the position of the first changed character (from the start or end of the document). When passing those positions to the handler, it passes `from: Math.max(0, from - 1)`, but no similar operation for the `to`.

With a document with a single character (like `a`), if you paste a single character at the beginning (so that the new document state is `za`), this would pass `{from: 0, to: 2}` to the handler, which will be two characters long, and include both `a` and `z`.

**Comment by bdbch** [comment]
Good find! Thanks for that. I'm looking into your PR right now.
