### ISSUE TITLE
nodePasteRule adds the Node at the end of the editor

### ISSUE THREAD

**Issue by edlb** [ueberdosis/tiptap#2942]
### What’s the bug you are facing?

When using `nodePasteRule` the Node is added at the end of the editor instead of at the `range.from` position

### Which browser was this experienced in? Are any special extensions installed?

The issue is new in `2.0.0-beta.181` because `nodePasteRule` wasn’t exposed before.

I’ve had the issue when trying to add a rule to transform `@something` into mentions (by extending @tiptap/extension-mention) when pasting plain text.

### How can we reproduce the bug on our side?

- Extend the Mention extension with `addPasteRules`
- Add a `nodePasteRule` using
  ```js
  nodePasteRule({
    find: /@([^\s@]+)/g,
    getAttributes: ([_, id]) => ({ id }),
    type: this.type,
  })
  ```
- Paste plain text in the editor with `@someting` in the middle (e.g. `Hello @user, how are you today?`)
- The `@something` will be transformed into a mention but moved to the end (e.g. `Hello , how are you today?@user`)

### Can you provide a CodeSandbox?

Vue: https://codesandbox.io/s/tiptap-nodepasterule-dg1f04?file=/src/App.vue

If you copy/paste directly the example in the CodeSandbox, you need to use `Cmd/Ctrl+Shift+V` to trigger the transformation.

### What did you expect to happen?

I expected the mention to be added at the same place as the matching text

### Anything to add? (optional)

Replacing `.insertContent({` with `.insertContentAt(range.from, {` [here](https://github.com/ueberdosis/tiptap/blob/main/packages/core/src/pasteRules/nodePasteRule.ts#L32) seems to resolve the issue but I might be missing something.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by svenadlung** [comment]
@edlb Pretty good find. Thanks a lot for your PR. We will have a look asap.

**Comment by eshengsky** [comment]
+1.
and, `nodeInputRule` has problems too
