### ISSUE TITLE
After pasting the link and typing a full-angle character, multiple characters will appear

### ISSUE THREAD

**Issue by hamflx** [ueberdosis/tiptap#2949]
### What’s the bug you are facing?

When I paste a link and then type a full-angle character "，", it appears as two characters "，，".

dependencies:
@tiptap/core@2.0.0-beta.181
@tiptap/extension-link@2.0.0-beta.43
@tiptap/starter-kit@2.0.0-beta.190

### Which browser was this experienced in? Are any special extensions installed?

chrome 103.0.5060.66 x64, no special extensions.

### How can we reproduce the bug on our side?

reproduction repo: <https://github.com/hamflx/input-dup-after-paste-link>

1. Copy http://localhost:3000/
2. Click on the editor area
3. Paste http://localhost:3000/
4. Enter the full-angle character ","
5. It will show two characters, if not, try again

### Can you provide a CodeSandbox?

<https://codesandbox.io/s/compassionate-ride-1deq9k?file=/src/App.vue>

### What did you expect to happen?

Enter a full-angle character and it appears as a character.

### Anything to add? (optional)

![gif](https://user-images.githubusercontent.com/13356747/177082152-d775b246-321a-4caa-b170-812318cf8a4f.gif)

![image](https://user-images.githubusercontent.com/13356747/177081998-5bf6719b-f3a7-41b5-bd81-019fcbb188a2.png)

It looks like MutationObserver triggered twice.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by hamflx** [comment]
fixed by https://github.com/ProseMirror/prosemirror/issues/1296

**Comment by StanislavMaiorov** [comment]
Why when i paste somethink like this it always a link       
like this " 1.open" or "a.open"?
so to fix it i write Link.configure({
        autolink: false, 
 }),

but now when i want create my link only 1 characters like link
