### ISSUE TITLE
Table's are rendered as defined in renderHTML with the node view not being constructed when isResizable evaluates to false

### ISSUE THREAD

**Issue by Brand2** [ueberdosis/tiptap#2966]
### What’s the bug you are facing?

When a table node is encountered , the table is inserted in the rendered DOM (after TipTap does its parse and re-render) as it is defined in the `renderHTML` method, i.e.:

```html
<table>
  <tbody>
  ...
  </tbody>
</table>
```

However, my understanding is that the `Table` extension should result in a structure like the following, where the table element is wrapped in a `<div class="tableWrapper">`:

```html
<div class="tableWrapper">
  <table>
    <tbody>
    </tbody>
  <table>
</div>
```

Due to the `TableView` (which implements ProseMirror's `NodeView` interface) not being constructed. I found through testing that after `2.0.0-beta.27` of `extension-table`, the node view is no longer being constructed if the `isResizable` check (see below) returns `false` during editor construction. This has some implications which I noticed as we actually extend the view to add some DOM elements based on some custom attributes, which were then never constructed, as the `NodeView` is never instanced. This also means that the col group and other additional DOM created by the default `TableView` class (https://github.com/ueberdosis/tiptap/blob/main/packages/extension-table/src/TableView.ts) are also not added to the rendered DOM in the case of the `isResizable` check returning `false`.

It is also worth noting that I first noticed this behaviour when the `editable` property of the `Editor` instance was first set to `false` and then later changed to `true`. I suspect this is because `addProseMirrorPlugins` evaluates exactly once at `Editor` instancing, but I am not too sure how to confirm this.

### Which browser was this experienced in? Are any special extensions installed?

This occurs in both Chrome and Firefox (tested in both), no special extensions were installed.

### How can we reproduce the bug on our side?

Instance an editor with some table content inside, and add the table-related extensions. If you use any of the following combinations, you will note that the node view is not rendered, and instead the DOM is rendered per the `renderHTML` method:

1. Set the `resizable` option of the `Table` extension to `false` and the `editable` option of the `Editor` as `true`;
2. Set the `resizable` option of the `Table` extension to `true` and the `editable` option of the `Editor` as `false`;
3. Set the `resizable` option of the `Table` extension *and* the `editable` option of the `Editor` as `false`.

### Can you provide a CodeSandbox?

Yes, see below:

https://codesandbox.io/s/table-view-rendering-w2zxdf?file=/src/App.js

### What did you expect to happen?

My expectation was that the node view should always be rendered, as this is the "true" view of the node in the DOM, executing the logic necessary. This would mean that any additional DOM which is necessary will be added by the node view.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by mhemmings** [comment]
Has this been resolved, or closed without triage?

**Comment by husseinalaedin** [comment]
same question:
Has this been resolved, or closed without triage?

**Comment by mattpodolak** [comment]
Also seeing this issue
