### ISSUE TITLE
placeholder extension bug report

### ISSUE THREAD

**Issue by Matrixbirds** [ueberdosis/tiptap#2970]
## Case: 
Typing a character in the editable tiptap editor section and press backspace once the placeholder not show.

### Which browser was this experienced in? Are any special extensions installed?

Chrome Version 103.0.5060.114 (Official Build) (arm64).
Just offical main branch code with offical demo.

## Reproduce Steps:
1. checkout tiptap code from main branch.
2. run the placeholder demo.

### Can you provide a CodeSandbox?

Use main branch code, you will reproduce it.

### What did you expect to happen?

**Expected**: When the editor state is empty, should show the placeholder.
**Actually**: The editor state is already being empty and the DOM structure updated with class `is-empty` in `<p>` element, but no placeholder show. I need trigger blur or press backspace again the `is-editor-empty` class will be added.

## Reproduce & Behaviour
![Screen Recording 2022-07-09 at 10 43 27_](https://user-images.githubusercontent.com/9990676/178090463-506f9383-bd3d-47a7-9aef-1f2808bc83e3.gif)

## Workaround
I check the placeholder's code, i don't really understand what is design, In my case i just need the global empty state, so i did workaround to add class in `<editor-content/>` component, and change the css selector pattern to fixed it.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by O4epegb** [comment]
It works here https://tiptap.dev/api/extensions/placeholder#placeholder

Is it fixed for you now or not?

**Comment by Matrixbirds** [comment]
> https://tiptap.dev/api/extensions/placeholder#placeholder

No, it still has the problme.
You can find the `is-editor-empty` will not be added when editor 's caret is visible on the editor view.

**Comment by O4epegb** [comment]
> > https://tiptap.dev/api/extensions/placeholder#placeholder
> 
> No, the problem still here. You can find the `is-editor-empty` will not be added when editor 's caret is visible on the editor view.

I've tried to reproduce it the same way you do in the gif and it works

**Comment by Matrixbirds** [comment]
> O4epegb

Can you share me your browser version?

**Comment by O4epegb** [comment]
Chrome Version 103.0.5060.134 (Official Build) (x86_64)

Video:

https://user-images.githubusercontent.com/12836237/182600355-99fc243c-512a-44d8-82dc-3229172c9937.mov

I saw other cases where placeholder is a bit bugged, I might post it later with a reproduction, but your case works for me. Or am I doing something wrong?

**Comment by Matrixbirds** [comment]
> 

Okay, I used the same react demo and follow your video, it works. I think tried to use vue demo, can reproduce it. My browser is 103.0.5060.134 (Official Build) (arm64)

**Comment by O4epegb** [comment]
Oh, I see, yes, Vue demo needs additional backspace keypress for some reason to show the placeholder

**Comment by robertmylne** [comment]
Same issue here. Using vuejs.
