### ISSUE TITLE
Content "text" set to null on OUTPUT; causes rendering error on INPUT

### ISSUE THREAD

**Issue by CynosureEPR** [ueberdosis/tiptap#2975]
### What’s the bug you are facing?

A scenario where the following `"text": null` can occur in the content array:

`{"type": "paragraph", "content": [{"text": null, "type": "text"}]}`

This `"text": null` specifically seems to be the problem child and prevents tiptap from rendering anything within the editor.  It is the result of `editor.getJSON()` and I have not formatted or altered said getter's data in any way.

It triggers a warning:

> [tiptap warn]: Invalid content. Passed value: {type: 'doc', content: Array(1)} Error: RangeError: Invalid text node in JSON

and will not render the remainder of the valid content elements if is present anywhere in the JSON object.  Attempting to replace this manually with an empty string results in:

> [tiptap warn]: Invalid content. Passed value: {type: 'doc', content: Array(1)} Error: RangeError: Empty text nodes are not allowed

so the only option for me currently is to manually parse the entire object out before storing it in the database.. but I am unsure of how/why it's in there in the first place.

### Which browser was this experienced in? Are any special extensions installed?

All and any Safari, Chrome/Brave, Firefox, and mobile variations (as well was the webkit views)  - I have about 30 cases of it so far with my user using various browsers (most are mobile versions).

### How can we reproduce the bug on our side?

I am unsure of the specific cause at this point as it appears randomly within their JSON responses.  I am not using custom buttons or methods and have not yet been able to track it down to a specific user action.  I am attempting to gather more information here by logging all instances before I filter it out for saving.. but thus far I am not seeing a pattern.

### What did you expect to happen?

The parser to not create it in the first place or treat it as an empty text node when rendering it back out.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

Edits: fixing misinformation + typos

**Comment by huwcarwyn** [comment]
Are you sure that there is nothing else you're doing other than editor.getJSON()? I ran into the exact same issue, my issue was with something within my environment trimming strings composed of only spaces so that I ended up with the null value on the text node (specifically the laravel TrimStrings middleware).

**Comment by ChipNeedham** [comment]
@huwcarwyn thank you, just saved me a headache
