### ISSUE TITLE
Floating menu not displayed after inserting horizontal rule 

### ISSUE THREAD

**Issue by essential-randomness** [ueberdosis/tiptap#2976]
### What’s the bug you are facing?

When adding a block node that inserts a new, empty paragraph after itself (for example Horizontal Rule inserted in the last text block) the floating menu is not displayed as expected, even if the selected paragraph is empty.

### Which browser was this experienced in? Are any special extensions installed?

Chrome Version 103.0.5060.114 (Official Build) (arm64)

### How can we reproduce the bug on our side?

1. Install horizontal rule (HR)
2. Install floating menu
3. Add button to insert HR from floating menu
4. Position cursor at the end of the last paragraph in the editor
5. Press enter, floating menu should appear
6. Click button on floating menu to enter HR
7. HR is created, new (empty) paragraph is inserted after it, selection is set to the paragraph, **but floating menu does not appear**

### Can you provide a CodeSandbox?

Here it is: https://codesandbox.io/s/stupefied-visvesvaraya-7y4673?file=/src/App.js

### What did you expect to happen?

Floating menu appears correctly after insertion.

### Anything to add? (optional)

In another plugin I've been creating, I've fixed the issue by writing this code (based on the HR's code). No guarantee that this is correct:
```ts
const maybeAddNewTrailingParagraph = (tr: Transaction) => {
  const { $to } = tr.selection;
  const posAfter = $to.end();

  if ($to.nodeAfter) {
    return TextSelection.create(tr.doc, $to.pos);
  } else {
    const node = $to.parent.type.contentMatch.defaultType?.create();
    if (node) {
      tr.insert(posAfter, node);
     // IMPORTANT: ADDED + 1 HERE
      return TextSelection.create(tr.doc, posAfter + 1);
    }
  }
};

addCommands() {
    return {
      setHorizontalRule: () => ({ chain }) => {
        return chain()
          .insertContent({ type: this.name })
          // set cursor after horizontal rule
          .command(({ tr, dispatch }) => {
            if (dispatch) {
                const selection = maybeAddNewTrailingParagraph(tr);
                // Request animation frame is necessary or the focus won't actually happen.
                // see: https://github.com/ueberdosis/tiptap/issues/1520
                requestAnimationFrame(() => {
                  if (!editor.isDestroyed && !editor.isFocused && selection) {
                    editor.view.focus();
                    // IMPORTANT: MADE SELECTION IN requestAnimationFrame
                    editor.commands.setTextSelection(selection);
                    editor.commands.scrollIntoView();
                  }
                });
           }
            return true
          })
          .run()
      },
    }
  },
```

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by robertu7** [comment]
Same issue, any workaround?
