### ISSUE TITLE
Allow ReactNodeViewRenderer to receive additional props to pass down to rendered component

### ISSUE THREAD

**Issue by essential-randomness** [ueberdosis/tiptap#2986]
### What problem are you facing?

I want my plugin to display a completely different DOM tree in editable vs read-only mode. I can't figure out how to get the current editor state from within `NodeViewWrapper`, and I can't  pass a prop indicating the state from `addNodeView` because `ReactNodeViewRenderer` doesn't allow passing props downstream.

Would also help with #2502 AFAICT.

Clarifying example, and how I currently got this to work:
```tsx
const EditModeComponent = (props) => (
    <NodeViewWrapper data-type={PLUGIN_NAME}>{editModeDom}</NodeViewWrapper />);
  
const ViewModeComponent = (props) => (
    <NodeViewWrapper data-type={PLUGIN_NAME}>{viewModeDom}</NodeViewWrapper />);

export const Plugin = Node.create<ImageOptions>({
   // ....more code
   addNodeView() {
      return ReactNodeViewRenderer(
        this.editor.isEditable ? EditModeComponent : ViewModeComponent
      );
   },
   // ....more code
}
```
 

### What’s the solution you would like to see?

I'd like to take a page out of [`React.cloneElement`](https://reactjs.org/docs/react-api.html#cloneelement)'s book and allow a second argument with props to pass on to the wrapped component.

Example rewrite of above code:
```tsx
const GenericComponent = (props) => (
    <NodeViewWrapper data-type={PLUGIN_NAME}>{props.editable ? editModeDom : viewModeDom}</NodeViewWrapper />);

export const Plugin = Node.create<ImageOptions>({
   // ....more code
   addNodeView() {
      return ReactNodeViewRenderer(GenericComponent, {
        props: {
          editable: this.editor.isEditable
        }
      });
   },
   // ....more code
}
```

### What alternatives did you consider?

See the issue description for the current code. Potentially there is already a way to get that information from within `NodeViewWrapper`, but I couldn't find it. Regardless, this is likely to come out handy in many different situations.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by vastava** [comment]
Sharing my workaround in case it helps others looking for a solution — when you create the node extension, implement the "addOptions" method and use the options as a proxy for props. So for the given example, the implementation might look like:

```
export const Plugin = Node.create<ImageOptions>({
   // ....more code

   addOptions() {
      return {
         editable: false //whatever you want the default value to be
      }
   }

   addNodeView() {
      return ReactNodeViewRenderer(GenericComponent)
   },
   // ....more code
}
```

You can then set the option values for GenericComponent when initializing the Tiptap editor. Dependency Arrays work with the useEditor hook so you can re-render the component anytime the editable option changes, just like if it was a prop. For example:

```
const editor = useEditor({
   extensions: [
      StarterKit,
      Plugin.configure({ editable: editableState })
      ... etc
   ]
}, [editableState]) // We've passed editableState in the dependency array, so the editor will re-render if this variable changes
```

From within GenericComponent, you can access the option value in props. If, like me, you're using this component in multiple places and need to be able to access the value from props, and the nested extension object within props, you can retrieve the values like so:

```
const editable = props.editable || props.extension.options.editable
```

Hope that helps!
