### ISSUE TITLE
Generating html from server: RangeError: Schema is missing its top node type ('doc')

### ISSUE THREAD

**Issue by rickyxiaoyang** [ueberdosis/tiptap#2994]
### What’s the bug you are facing?

Per documentation, I'm using `generateHTML` from `@tiptap/html` to convert the prosemirror JSON to HTML on the server. 

Running into this error message: 
```RangeError: Schema is missing its top node type ('doc')```

### Which browser was this experienced in? Are any special extensions installed?

Node server

### How can we reproduce the bug on our side?

Install @tiptap/html and convert a sample JSON to html using `generateHTML()`

### What did you expect to happen?

An error should not have been thrown since the prosemirror JSON was valid. The corresponding HTML should've been returned.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by rickyxiaoyang** [comment]
Closing this. The problem was because I wasn't passing in any extensions into the array.

**Comment by Mihailoff** [comment]
@rickyxiaoyang could you please share a snippet? running into the same problem

**Comment by Mihailoff** [comment]
```javascript
import StarterKit from '@tiptap/starter-kit'
import { generateHTML } from '@tiptap/html'

generateHTML({ type: 'doc', content: [] }, [StarterKit])
```

Leads to `TypeError: Cannot read properties of undefined (reading 'addExtensions')` 🤯

@tiptap/html": "^2.0.0-beta.199
@tiptap/starter-kit": "^2.0.0-beta.199

**Comment by emil14** [comment]
@Mihailoff did you ever figure that out?
