### ISSUE TITLE
Mention.extend() breaks the Suggestion behavior

### ISSUE THREAD

**Issue by tarngerine** [ueberdosis/tiptap#2995]
### What’s the bug you are facing?

As soon as you try to extend Mention, the core functionality breaks

### Which browser was this experienced in? Are any special extensions installed?

Following the Mention example from the docs, no special extensions besides that

### How can we reproduce the bug on our side?

https://codesandbox.io/s/elegant-diffie-erg9uv?file=/src/App.tsx

### Steps

1. Go to codesandbox above
2. Go to line 17, see `.extend()` called to extend Mention
3. Go to editor, type @, expect list of suggestions to show up immediately
4. Remove `.extend()` from App.tsx line 17
5. Go to editor, type @, see list of suggestions showing up as expected

### Can you provide a CodeSandbox?

https://codesandbox.io/s/elegant-diffie-erg9uv?file=/src/App.tsx

### What did you expect to happen?

.extend() should not break the core behavior

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by O4epegb** [comment]
You need to call `extend` before `configure`

**Comment by tarngerine** [comment]
oh! i see. didn't expect that, since i didnt expect it to be "Activated" until the editor reads it as an extension, but glad it's resolved! thanks
