### ISSUE TITLE
Page layout

### ISSUE THREAD

**Issue by DioNNiS** [ueberdosis/tiptap#2996]
### What problem are you facing?

Some of our customers are old school... and what to work with page layout.
Is it possible to implement page layout in the editor?

### What’s the solution you would like to see?

It's like Word or Google Docs layout

### What alternatives did you consider?

Word or Google Docs

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by sereneinserenade** [comment]
This might help https://github.com/todorstoev/prosemirror-pagination

**Comment by andrzejdzirba** [comment]
Very good question - I guess you can create additional node page in schema, but then there is plenty of calculating rearding elements heights and breaking and gluing nodes together on change

**Comment by sheoak** [comment]
@DioNNiS did you manage to implement it? I also want to implement this. Not for "old school" but for texts where pagination is important (screenplays).

**Comment by bdbch** [comment]
We already discussed this feature in the team and decided to not do it for now but we'll look forward to look for easier solutions allowing users to add pagination to Tiptap editors. Feel free to give out more informations on how you solved your issue @DioNNiS
