### ISSUE TITLE
Using chakra provider breaks styling

### ISSUE THREAD

**Issue by pulkitvyas08** [ueberdosis/tiptap#2999]
### What’s the bug you are facing?

Been using Tiptap for a couple of projects and every time I face the issue that my headings and a couple of other elements are not rendered properly. This time while using the NextJS framework I finally found that this is because I always use Chakra UI as part of my projects and when I removed the `ChakraProvider` tag headings were rendered as headings instead of the usually wrong regular text

### Which browser was this experienced in? Are any special extensions installed?

Firefox Version 102.0.1 (64-bit)

### How can we reproduce the bug on our side?

Wrap your top level container (<App> in case of ReactJS, <Components ...> in case of NextJS) with <CharkaProvider>

### What did you expect to happen?

Too have headings rendered as headings and other components too such as code blocks and quotes to also be rendered properly.

### Anything to add? (optional)

Screenshot of editor without adding `ChakraProvider`:
![image](https://user-images.githubusercontent.com/54947769/179529349-64eb6de8-ae9c-4fd4-8afd-6b8dbac5a27f.png)

Screenshot of editor after adding `ChakraProvider`:
![image](https://user-images.githubusercontent.com/54947769/179529514-ad677c02-634c-49e9-af16-cee47cc1a8df.png)

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by Nithur-M** [comment]
Hey, did you manage to solve this? I am facing this issue. Thanks.

**Comment by bdbch** [comment]
Hey. We'll look into this but with a lower priority for now as this is a conflict with a third party package. When we have time I'll look into this issue and try to find out what is causing this. In the meantime you could try to find out what the ChakraProvider exactly is doing and report in here. Maybe there is a super quick fix for this.

**Comment by bdbch** [comment]
@pulkitvyas08 @Nithur-M 

I just took a look at this again. I guess ChakraUI is adding a base styling for typography elements so you can use https://chakra-ui.com/docs/components/heading/usage without side effects.

Maybe this helps:
https://chakra-ui.com/community/recipes/prose

I'll close it for now
