### ISSUE TITLE
@tiptap/extension-table use a dependency with an invalid scope (start with an underscore)

### ISSUE THREAD

**Issue by picpicpic** [ueberdosis/tiptap#3000]
### What’s the bug you are facing?

Tiptap is using the dependency @_ueberdosis/prosemirror-tables

The scope of this dependency start with a underscore which doesn't follow npm rules : https://docs.npmjs.com/cli/v8/using-npm/scope

On impact is that tools checking npm rules prevent the usage of such dependency.
ie : https://community.sonatype.com/t/illegalargumentexception-scope-starts-with-or-ueberdosis/8920

### Which browser was this experienced in? Are any special extensions installed?

not related to browser

### How can we reproduce the bug on our side?

1. Download Nexus repository.
2. Add a proxy on the npm registry.
3. Try to donwload the @tiptap/extension-table in version 2.0.0-beta.54

### What did you expect to happen?

1. republish the library @_ueberdosis/prosemirror-tables without the underscore character. 
2. update the dependency in https://github.com/ueberdosis/tiptap/blob/main/packages/extension-table/package.json
3. republish the library @tiptap/extension-table

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by everythinginjs** [comment]
I am having the same issue on deployment.

**Comment by elboukhari** [comment]
any update for this issue please ?
In my case the latest "valid" version is : 
`"@tiptap/extension-table": "2.0.0-beta.53"`

**Comment by splincode** [comment]
any update?

**Comment by splincode** [comment]
<img width="775" alt="image" src="https://user-images.githubusercontent.com/12021443/195533793-323c3d67-b70f-4a2a-9c15-40bdf30dcd40.png">

**Comment by serge-name** [comment]
Actual for me. Sonatype Nexus refuses to serve packages with invalid scope names: (8920)[https://community.sonatype.com/t/illegalargumentexception-scope-starts-with-or-ueberdosis/8920]. And that is correct behavior.

Please eliminate that underscore.

**Comment by bdbch** [comment]
I'll look into this tomorrow and resolve this issue.
