### ISSUE TITLE
TextSelection warning with Horitzontal Rule

### ISSUE THREAD

**Issue by jakedolan** [ueberdosis/tiptap#3003]
### What’s the bug you are facing?

There is a console warning when executing the command `setHorizontalRule()`.

Related to #2846 but not resolved by the fix in @tiptap/core 2.0.0-beta.182.

### Which browser was this experienced in? Are any special extensions installed?

Tested in Chrome, Firefox, Opera. Reproducible in minimal install with STR below.

### How can we reproduce the bug on our side?

1. See linked codesandbox.
2. Click 'Add HR' button.
3. See warning in console.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/priceless-tdd-34begx

### What did you expect to happen?

No warning is displayed.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by Pareder** [comment]
This issue is still reproduced, who can take a look?

**Comment by Slapbox** [comment]
This should not be closed. Simply calling `editor.commands.setHorizontalRule()` produces this warning and results in an invalid selection.

@bdbch could we get this re-opened?

**Comment by sjdemartini** [comment]
Bump, this should be reopened @bdbch

**Comment by bdbch** [comment]
Added to the backlog

**Comment by bdbch** [comment]
Fix is in PR (#4319) - will release in the next RC version later this day.
