### ISSUE TITLE
HTML output of complex React Node View 

### ISSUE THREAD

**Issue by seeARMS** [ueberdosis/tiptap#3007]
### What problem are you facing?

I have a TipTap editor that lets users publish content online, as well as send it via email (similar to Substack).

I'm using `editor.getHTML()` to produce HTML from the editor, and using this HTML directly in emails.

This works well for basic extensions, but I'm running into an issue with a complex ReactNodeView that performs data fetching.

I'm creating a Tweet extension using the [react-static-tweets](https://github.com/transitive-bullshit/react-static-tweets#readme) package. [This](https://gist.github.com/seeARMS/e41f35064ba3a6550420e5f2b27b2e84) is my node. Whenever a user enters a tweet URL, it fetches data from the Twitter API then displays the tweet statically. The final end result of the static tweet is what I'd like to retrieve HTML for.

This works great within the TipTap editor, but I can't find any solution to produce HTML _from the final, rendered output of the Tweet_. In my `renderHTML` function, by default it outputs `<tweet-embed tweetId="123" />`, which is expected. It seems I'm unable to modify it to output the fully rendered, static HTML of the tweet.

### What’s the solution you would like to see?

I don't think I'm well versed enough in TipTap to propose a solution.

Ideally, having a flag or some mechanism in the `renderHTML` function to indicate to TipTap that we'd like to use the fully rendered component's HTML would be great. 

### What alternatives did you consider?

I've considered just using TipTap to render the output (as per the [docs](https://tiptap.dev/guide/node-views#render-java-scriptvuereact)), but this is not possible to use in email.

I've tried #2289 (using `renderToStaticMarkup` in the `renderHTML` function to produce HTML from the component) but that only works for simple components that function on the server-side (ie, not any components using `useEffect`, like the tweet component).

I'm currently trying #2848:
* Every time the editor data is changed, loop through the editor JSON and get the node using `editor.view.nodeDOM(position)` and retrieve the HTML via innerHTML, then replacing the entry in the HTML output with this. This seems like a hacky solution. 

Another hacky solution is to get the entire innerHTML of the editor (`editor.view.dom.innerHTML`) whenever the post is ready to be published. This HTML can be sent via email (as it displays the full tweet). 

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by seeARMS** [comment]
I came up with a workaround in the meantime.

* Create an attribute on the `Node` called `html`
* Within the Tweet React component, wait until it's fully rendered, then update the `html` attribute with the component's `innerHTML`:

```
    const staticHtml = props.editor.view.nodeDOM(props.getPos()).innerHTML
    props.updateAttributes({ html: staticHtml })
```

That's all! Now I can keep the `renderHTML` function like very basic, and everything works:
`return ["tweet-embed", mergeAttributes(props.HTMLAttributes)]`

I didn't realize that the `html` attribute is the ACTUAL HTML of the Node. That makes things a lot easier.

**Comment by srsudar** [comment]
@seeARMS , can you provide your full working code? I'm trying something similar but am confused. When I do:

```
renderHTML() { 
  return ["tweet-embed", mergeAttributes(props.HTMLAttributes)];
}
```

And then I call `generateHTML(doc, , [...])`, I get an actual `<tweet-embed />` tag in my HTML--the node view doesn't get applied.
