### ISSUE TITLE
nextSibling exception

### ISSUE THREAD

**Issue by dudif91** [ueberdosis/tiptap#3012]
### What’s the bug you are facing?

Hi i'm getting "Cannot read properties of null (reading 'nextSibling')" when working with the tiptap editor in my app.

<img width="766" alt="image" src="https://user-images.githubusercontent.com/57500905/180207697-d66828ab-a77a-47fa-8536-fb98f8f0b459.png">

### Which browser was this experienced in? Are any special extensions installed?

chrome with no special extensions using vue 2

### How can we reproduce the bug on our side?

added new line with text
jump to new line 
add ordered list
enter data
jump to new line 
enter data
jump to new line 
jump to new line  to leave the list boom exception 

### What did you expect to happen?

just work as usual with no exceptions

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by Sherby1988** [comment]
+1 I am also experiencing the same error.
In my case it is when I split a paragraph in 2

**Comment by IBM51OO** [comment]
+1 Same problem

**Comment by marcreichel** [comment]
+1

**Comment by sidler** [comment]
+1

**Comment by Beenheed** [comment]
+1

**Comment by WouterSchoofs** [comment]
+1

**Comment by zacharyhall** [comment]
+1

**Comment by webm0fe** [comment]
+1

**Comment by paulkarpenko** [comment]
+1

**Comment by paulkarpenko** [comment]
@bdbch hi, Dominik — is there any movement on this issue? We're seeing it in `2.0.0-beta.209` as well as `1.32.2`.

**Comment by YassineBouzeya** [comment]
+1

**Comment by bdbch** [comment]
Could someone provide me with a Codesandbox which results in this bug so I can replicate it? From this issue it is not really clear what exactly leads to this issue (since there are multiple issues reported here).

**Comment by bdbch** [comment]
Bump - would like to figure out what's going wrong. I wasn't able to reproduce.

Feel free to use this sandbox and fork it:
https://codesandbox.io/s/keen-snowflake-hxs5u5?file=/src/App.js

It's running the most recent version of Tiptap but I can't seem to reproduce the issue by the given steps in here.

**Comment by empty916** [comment]
+1

**Comment by empty916** [comment]
my solution is to remove the vue-fragment package.

**Comment by Draccano** [comment]
> my solution is to remove the vue-fragment package.

this saved my day, works!

**Comment by lixiaowei11111** [comment]
> my solution is to remove the vue-fragment package.

very useful

**Comment by webm0fe** [comment]
I recommend - https://www.npmjs.com/package/vue-frag

**Comment by webm0fe** [comment]
> my solution is to remove the vue-fragment package.

I recommend - https://www.npmjs.com/package/vue-frag
