### ISSUE TITLE
Tab doesn't ident text/bullets - it unfocus the editor instead

### ISSUE THREAD

**Issue by phemartin** [ueberdosis/tiptap#3018]
### What’s the bug you are facing?

Hitting `tab` doesn't ident text/bullets as expected. It unfocus the editor instead

### Which browser was this experienced in? Are any special extensions installed?

Chrome, Brave

### How can we reproduce the bug on our side?

📹 **Please watch the loom (3-min)**:  https://www.loom.com/share/48bad8fb1f4f424387f8354e2656f920

### What did you expect to happen?

- `tab` on a bullet list, nest the item
- `tab` on text to ident it
- `shift + tab` to undo identation

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by jasonvarga** [comment]
@phemartin are you using windows?

**Comment by stuartcusackie** [comment]
Tested on Chrome Windows 10 & 11 - Tab navigates to next field in tabindex.

**Comment by teuf22** [comment]
Check https://github.com/ueberdosis/tiptap/issues/1153 and https://github.com/ueberdosis/tiptap/issues/2364 for solutions.
