### ISSUE TITLE
Cannot read properties of undefined (reading 'highlight')

### ISSUE THREAD

**Issue by caleadrian** [ueberdosis/tiptap#3027]
### What’s the bug you are facing?

I tried implementing Code Block Highlighting with this example ...
https://embed.tiptap.dev/preview/Examples/CodeBlockLanguage

 and I'm having this error.

**Unhandled Runtime Error**
TypeError: Cannot read properties of undefined (reading 'highlight')

Call Stack
eval
node_modules\@tiptap\extension-code-block-lowlight\dist\tiptap-extension-code-block-lowlight.esm.js (56:0)
Array.every
<anonymous>LowlightPlugin
node_modules\@tiptap\extension-code-block-lowlight\dist\tiptap-extension-code-block-lowlight.esm.js (56:0)
Object.addProseMirrorPlugins
node_modules\@tiptap\extension-code-block-lowlight\dist\tiptap-extension-code-block-lowlight.esm.js (127:0)

### Which browser was this experienced in? Are any special extensions installed?

I currently using Chrome without any  special extensions

### How can we reproduce the bug on our side?

Follow this example 
https://embed.tiptap.dev/preview/Examples/CodeBlockLanguage

Dependencies: 
```
"dependencies": {
    "@tiptap/extension-code-block-lowlight": "^2.0.0-beta.73",
    "@tiptap/react": "^2.0.0-beta.114",
    "@tiptap/starter-kit": "^2.0.0-beta.191",
    "lowlight": "^2.7.0",
    "next": "12.2.3",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "tiptap": "^1.32.2"
  },
  "devDependencies": {
    "autoprefixer": "^10.4.7",
    "eslint": "8.20.0",
    "eslint-config-next": "12.2.3",
    "postcss": "^8.4.14",
    "tailwindcss": "^3.1.6"
  }
```

### What did you expect to happen?

I expect the output looks like the example link I've mentioned above

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by HengCC** [comment]
Is there a temporary solution?

**Comment by gustavotoyota** [comment]
How are you importing lowlight?
I had a similar error here and the problem was that I was not loading lowlight correctly.
I was doing `import { lowlight } from 'lowlight'` when I should be doing `import { lowlight } from 'lowlight/lib/common'`

**Comment by caleadrian** [comment]
I solved the issue by changing the import to
`import { lowlight } from 'lowlight'`

The example I've mentioned above should also be updated.

**Comment by gustavotoyota** [comment]
I'm having this problem now, it's only happening occasionally in production.

**Comment by tiavina-mika** [comment]
I'm facing this issue, is there any fix?

**Comment by andyfelder16** [comment]
Solved it by doing this:
```
import { common, createLowlight } from "lowlight";
const lowlight = createLowlight(common);
```

[This](https://www.npmjs.com/package/lowlight) is the package page where are all the docs.
