### ISSUE TITLE
Suggestion didn't work in some Chinese IME

### ISSUE THREAD

**Issue by ununian** [ueberdosis/tiptap#3031]
### What’s the bug you are facing?

In some Chinese IME ( QQ Pinyin , Rime ), there is no response when type @.

### Which browser was this experienced in? Are any special extensions installed?

chrome firefox

### How can we reproduce the bug on our side?

In https://tiptap.dev/examples/suggestions
Use QQ Pinyin (http://qq.pinyin.cn/) ，in Chinese Mode， Type '@'

### Can you provide a CodeSandbox?

https://tiptap.dev/examples/suggestions

### What did you expect to happen?

work fine

### Anything to add? (optional)

I wrote it this way and it works fine
```tsx
//  packages\suggestion\src\suggestion.ts

// ...

function waitForElm(selector: string) {
  return new Promise<Element | null>(resolve => {
    if (document.querySelector(selector)) {
      resolve(document.querySelector(selector))
      return
    }
    const observer = new MutationObserver(() => {
      if (document.querySelector(selector)) {
        resolve(document.querySelector(selector))

        observer.disconnect()
      }
    })

    observer.observe(document.body, {
      childList: true,
      subtree: true,
    })
  })
}

// ...
view() {
      return {
        update: async (view, prevState) => {
        // ... this line
        const decorationNode = handleExit ? null : await waitForElm(`[data-decoration-id="${state.decorationId}"]`)
        // ...
```

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by codeingforcoffee** [comment]
bump
