### ISSUE TITLE
attribute.isRequired throws error when attribute is initialized with null

### ISSUE THREAD

**Issue by githubbob42** [ueberdosis/tiptap#3032]
### What’s the bug you are facing?

We have some custom nodes/extensions that define attributes with null as their initial value:
```js
const DataTable = CustomTable.extend({
  addAttributes() {
    return {
      ...this.parent?.(),
      sobject: null,
      relationship: null,
      intent: null,
      sortField: null,
      sortDirection: null,
      hasFooterRow: null
    };
  },
  ...
```

This has all worked well up until I did an npm update and my `@tiptap/core` updated from 2.0.0-beta.176 to 2.0.0-beta.182.

* Offending line: https://github.com/ueberdosis/tiptap/blob/main/packages/core/src/helpers/getAttributesFromExtensions.ts#L96
* Commit/Diff: https://github.com/ueberdosis/tiptap/commit/23483d5e1a8717b9672e449c07ab1bebde2a292d#diff-2896448bd75dac8ea3518e007f080db134e41e0656113c15840fa85355465abeR96

My thoughts are that this should have a null coalescing operator/check to ensure that the attribute has a value: 
```js
if (attribute?.isRequired && attribute?.default === undefined) {
``` 

Perhaps I've missed it, but I haven't seen any documentation that states that the initial value of custom attributes must be set with a value.  

I also don't know what sort of initial value it should be set to, if we are expecting it to be set to a string value.

### Which browser was this experienced in? Are any special extensions installed?

All

### How can we reproduce the bug on our side?

Create a custom node or extension with an attribute set to `null`:

```js
const customNode = Node.create({
  name: 'customNode',
  ...
  addAttributes() {
    return {
      sobject: null
    }
  },
  ...
});
```

### What did you expect to happen?

I expected the code to perform some sort of null check before just assuming there was a value set.

Perhaps I've missed it, but I haven't seen any documentation that states that the initial value of custom attributes must be set with a value.  I also don't know what sort of value it should be set to, if we are expecting it to be set to a string value.

So this seems to be a bug to me.

### Anything to add? (optional)

Love the library so far, especially now that we are getting more experienced with it.

Yes, I’ve updated my dependencies to use the latest version of all packages - that's when the issue started happening.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by albertogiunta** [comment]
Hello, I have opened a PR against this issue. We at Typefully (www.typefully.com, +50k users) are happily using TipTap for a core feature of the product. We're now in the midst of a library update effort, and I've encountered this issue (#3032) as well while updating TipTap. 

I feel like this is a breaking change for an undocumented behavior, and it's really blocking for us. 
I'd appreciate a review for #3245 by you guys so that we can move this forward asap.

Thanks a lot, really appreciate your work on this wonderful lib.

cc @bdbch

**Comment by albertogiunta** [comment]
Meanwhile, if you need to have this bug fixed while my PR is not yet merge, you can:
- go inside your `node_modules/@tiptap/core/dist/tiptap-core-esm.js`
- apply the fix locally
- follow the instructions here: https://github.com/ds300/patch-package
- run: `yarn add patch-package postinstall-postinstall`
- run: `npx patch-package "@tiptap/core"`
- add `"postinstall": "patch-package"` to your package.json scripts
- remove build caches (e.g. `.next` folder)

The package will then be patched with this fix every time you run a `yarn install`
