### ISSUE TITLE
 Does tiptap has a method to get fontSize value and fontFamily value?  ( some style )

### ISSUE THREAD

**Issue by HZZformGD** [ueberdosis/tiptap#3042]
### What problem are you facing?

I have a  list of font-family. and i put it into a select component.  I know how to set font-family, but i don't know how to get current family (i want set a default value for select)

### What’s the solution you would like to see?

```javascript
const value = editor.getTextStyle(‘font-family’)


```

### What alternatives did you consider?

none

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by HZZformGD** [comment]
I found the solution.
```javascript
const { fontFamily = '', fontSize = '16px', color = '#000' } = editor?.getAttributes('textStyle')

```

**Comment by SarathSantoshDamaraju** [comment]
> I found the solution.
> 
> ```js
> const { fontFamily = '', fontSize = '16px', color = '#000' } = editor?.getAttributes('textStyle')
> ```

This wont work always. When you copy paste a content from external source. this wont work. any way to handle that @HZZformGD
