### ISSUE TITLE
`getAttributes('heading').level` incorrectly returning `1` after all content deleted

### ISSUE THREAD

**Issue by jameslesliewatts** [ueberdosis/tiptap#3044]
### What’s the bug you are facing?

I have a custom Doc extension with `content: 'heading+'` and to the Heading extension options I am only passing levels `[3, 4, 5]`. (This is an element that only allows headings and never h1 or h2).

If I select all the text and delete it, the document resets to `<h3></h3>` - getHTML() verifies this and adding text makes it visually obvious that it's correct. This is exactly what I expected!

**The issue:**
If I run `getAttributes('heading').level` on that line, it will always return `1`.

Nothing I can think of will trigger it to read correctly except rerunning the `setHeading` command on that line. 

This is Tiptap 2 and Vue 2. (additional package version and environment info available if needed).

Thanks in advance for any help! 

### Which browser was this experienced in? Are any special extensions installed?

Chrome v103

### How can we reproduce the bug on our side?

https://codesandbox.io/s/tiptap-issue-template-forked-fi4nrv?file=/src/components/Tiptap.vue

If you go the sandbox above, select all the editor content and hit Backspace - you will see the HTML is correct but the attributes is wrong. 

### Can you provide a CodeSandbox?

https://codesandbox.io/s/tiptap-issue-template-forked-fi4nrv?file=/src/components/Tiptap.vue

### What did you expect to happen?

I expected `getAttributes('heading').level` to return `3`

### Anything to add? (optional)

I love Tiptap - thanks for all you do!

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by jameslesliewatts** [comment]
I was able to workaround this issue by adding the below to a custom heading extension. I'm still curious if it isn't automatically detecting the correct heading from the html or if I'm actually misunderstanding the problem.

```javascript
addAttributes() {
    return {
      ...this.parent?.(),
      level: {
        default: this.options.levels[0] || 1,
        rendered: false,
      },
    };
  },
```

**Comment by ziudeso** [comment]
Great @jameslesliewatts it works perfectly
