### ISSUE TITLE
Strange behaviour when 2 mention nodes are next to each other

### ISSUE THREAD

**Issue by nathos94** [ueberdosis/tiptap#3045]
### What’s the bug you are facing?

Not sure if this needs to be 2 seperate bug reports, there are 2 different behaviours experienced on different browsers when 2 or more mention nodes have no space between them.

Chrome (103.0.5060.134):
- Cursor indicator visually jumps to end of line, but input still shows between mentions as expected
<img width="835" alt="Screen Shot 2022-08-01 at 11 46 17 am" src="https://user-images.githubusercontent.com/2274951/182057403-1a81b6af-a2b7-4092-8d2b-601c1ec93b3b.png">

Firefox (103.0)
- Cursor positions jumps to the line above
- Can't enter text between mentions
<img width="571" alt="Screen Shot 2022-08-01 at 11 50 27 am" src="https://user-images.githubusercontent.com/2274951/182057416-982db40e-847e-4b81-b228-c6114877cd41.png">

### Which browser was this experienced in? Are any special extensions installed?

Bug happens in latest Chrome and Firefox at the time of this report

### How can we reproduce the bug on our side?

Add 2 mentions, remove default space between mentions, try moving cursor between mentions

### Can you provide a CodeSandbox?

Bug shows in preview and with just the example code in the documentation
https://tiptap.dev/api/nodes/mention

Tested locally with all the latest packages and bug persists 

### What did you expect to happen?

Cursor displays between mentions and text input is normal

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by segevfiner** [comment]
Bump

**Comment by nathos94** [comment]
Seems to be not an issue anymore

Tested on latest chrome (112.0.5615.137)

**Comment by Sharsie** [comment]
@nathos94 It's still an issue on Firefox 112.0.2
Besides that, if the mention is the last item in the line, it's not possible to move cursor using left arrow at all
