### ISSUE TITLE
When deleting the last character of a NodeView, the entire previous block is deleted

### ISSUE THREAD

**Issue by cobbvanth** [ueberdosis/tiptap#3050]
### What’s the bug you are facing?

When deleting the last character of a NodeView, the entire previous block is deleted

### Which browser was this experienced in? Are any special extensions installed?

Chrome 103, no extensions

### How can we reproduce the bug on our side?

- Create a simple, inline text nodeview (react component) node
- Delete the final part of the nodeview
- The entire previous paragraph (or any other node), will be deleted

### What did you expect to happen?

The Nodeview should simply be deleted, and the selection should be moved the end of the previous node.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by rfgamaral** [comment]
I think this might be a duplicate of: https://github.com/ueberdosis/tiptap/issues/2924
