### ISSUE TITLE
InputRules does not work for ranges containing multiple text nodes.

### ISSUE THREAD

**Issue by hamflx** [ueberdosis/tiptap#3071]
### What’s the bug you are facing?

When markdown tags cover multiple text nodes, they will not work. See GIF:

![动画](https://user-images.githubusercontent.com/13356747/183801132-349e2c85-bf7d-4297-937a-5359fceeb286.gif)

The initial problem was #2937, fixed by #2941.

But if a paragraph contains multiple text nodes within it, and InputRule needs to span those nodes, it will not work.

I'm using the latest code from the main branch.

### Which browser was this experienced in? Are any special extensions installed?

Chrome/103.0.0.0. No special extensions.

### How can we reproduce the bug on our side?

1. type 'A   B   C'
2. make 'B' bold
3. type '*' at the begining
4. type '*' at the end

correct result: *A **B** C*
incorrect result: \*A **B** C\*

### Can you provide a CodeSandbox?

No CodeSandbox, but there is a "Deploy Preview" provided by #2941

<https://deploy-preview-2941--tiptap-embed.netlify.app/>

### What did you expect to happen?

InputRule should work between multiple text nodes.

### Did you update your dependencies?

- [x] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by revidee** [comment]
Also faced this issue in our installment of tiptap, dug deep and found the exact same broken LOCs as you did. Your fix seems very reasonable and should be pulled in the near future IMHO.
