### ISSUE TITLE
Paste image from clipboard twice

### ISSUE THREAD

**Issue by autumninflab** [ueberdosis/tiptap#3073]
### What’s the bug you are facing?

Paste event handler runs twice when the clipboard data type is image.

### Which browser was this experienced in? Are any special extensions installed?

Chrome 103.0.5060.114

### How can we reproduce the bug on our side?

1. take a screenshot using shortcut `cmd + ctrl + shift + 4` in macOS for copy image into clipboard.
2. paste image to tiptap editor (`cmd + v`)
3. paste event handler runs twice and duplicated image appears.

### Can you provide a CodeSandbox?

1.
https://codesandbox.io/s/tiptap-paste-image-from-clipboard-1-busloz?file=/src/Tiptap.js

2. using `Image.extend`
https://codesandbox.io/s/tiptap-paste-image-from-clipboard-2-4wk2vs

### What did you expect to happen?

paste image once

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by kobe651jp** [comment]
In the end put "return true;",works for me.

```
  editor?.setOptions({
    editorProps: {
      handlePaste: () => {
        console.log("handlePaste");

        void (async () => {
          ...
            } catch (e) {
              console.error("유효하지 않는 이미지입니다.");
            }
          }
        })();
        return true;
      }
    }
  });

```

**Comment by autumninflab** [comment]
@kobe651jp Thanks a lot :) It works.

**Comment by autumninflab** [comment]
I wonder why the event handler runs twice when return value is undefined(void).
