### ISSUE TITLE
How can I insert icon tag in editor

### ISSUE THREAD

**Issue by sk31park** [ueberdosis/tiptap#3075]
### What’s the bug you are facing?

I want to add icon tag html in editor.

and I tried below

this.editor.commands.insertContent(`<i class="${this.icon}"></i>`)

but It's not work...
(there is no tag in editor)

It's work.. (simple thing like below)

`this.editor.commands.insertContent('<span>hello</span>')`

What's different?

### Which browser was this experienced in? Are any special extensions installed?

chrome

### How can we reproduce the bug on our side?

.

### Can you provide a CodeSandbox?

.

### What did you expect to happen?

.

### Anything to add? (optional)

.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by xiaweiss** [comment]
It's not a bug. you need to create a custom extension.
