### ISSUE TITLE
[iOS, React] Pressing "Enter" in an interactive node view freezes the whole page

### ISSUE THREAD

**Issue by fenok** [ueberdosis/tiptap#3084]
### What’s the bug you are facing?

On an iOS device, pressing "Enter" in an interactive node view makes the page unresponsive. The issue exists only for React components. Vue and plain JavaScript work fine.

### Which browser was this experienced in? Are any special extensions installed?

- Safari on iPhone 7 (15.6)
- Safari on some iPad Pro (15.6)

### How can we reproduce the bug on our side?

1. Open https://tiptap.dev/guide/node-views/react#adding-a-content-editable on an iOS device.
2. Place the cursor inside the interactive node view and press "Enter".

### Can you provide a CodeSandbox?

Doesn't seem to be necessary.

### What did you expect to happen?

Pressing "Enter" in an interactive node view should not freeze the whole page.

### Anything to add? (optional)

The issue is also reproducible in the latest version of tiptap.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by tobiaslins** [comment]
Seems to be related with #3100

**Comment by albertogiunta** [comment]
@fenok should be fixed here: https://github.com/ueberdosis/tiptap/pull/3269

**Comment by fenok** [comment]
@albertogiunta Thank you! I patched your fix into our application, and the freezing is indeed gone. However, now pressing "Enter" leads to an extra non-deletable newline inside the interactive node view. So I guess some form of this removed hack is still needed.

**Comment by kasem-sm** [comment]
Unfortunately for me, The issue still exists

**Comment by kasem-sm** [comment]
> Unfortunately for me, The issue still exists

@fenok laughing 🥲

**Comment by fenok** [comment]
Looks like it has been fixed!
