### ISSUE TITLE
emptyEditorClass placeholder is not rendered when @tiptap-pro/extension-unique-id is used

### ISSUE THREAD

**Issue by yuyuyukie** [ueberdosis/tiptap#3109]
### What’s the bug you are facing?

When I use `@tiptap-pro/extension-unique-id` with `@tiptap/extension-placeholder`, placeholder shown when the editor is empty doesn't rendered.
Strictly speaking, [emptyEditorClass](https://tiptap.dev/api/extensions/placeholder#empty-editor-class) is not added to the paragraph element.

![2022-08-22 (3)](https://user-images.githubusercontent.com/64625150/185864117-84a9de9d-a031-461e-87ff-2aee16254aee.png)

### Which browser was this experienced in? Are any special extensions installed?

Any browsers.

### How can we reproduce the bug on our side?

In React,
```javascript
  const editor = useEditor({
    extensions: [
      Document,
      Paragraph,
      Text,
      UniqueID.configure({
        types: ['paragraph'],
      }),
      Placeholder,
    ],
  })
```
style is same as https://tiptap.dev/api/extensions/placeholder#usage

### What did you expect to happen?

Placeholder is rendered properly.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by aldinezi** [comment]
We are having the same issue when using pro extension `UniqueID`. Is there any way of getting around this bug?

**Comment by aldinezi** [comment]
@bdbch do you mind looking into this issue, or providing some assistance on a workaround?

Problem is, when using UniqueId extension, editor will not get editor-empty class.

**Comment by xiaohanyu** [comment]
I have the same issue with the following setup:

```javascript
  const editor = useEditor({
    extensions: [
      StarterKit.configure({
        document: false,
        paragraph: false,
      }),
      Underline,
      Link,
      Placeholder.configure({ placeholder: 'Highlights' }),
      Document.extend({
        // the document can only have one or more paragraphs, or lists (if lists
        // are used), no headings, codeblocks, blockquotes, etc.
        content: '(paragraph|list?)+',
      }),
      Paragraph.extend({
        // allows only the 'bold', 'italic', 'underline' and 'link' marks
        marks: 'bold italic underline link',
      }),
    ],
  })
```

I did some customizations and the generated HTML is:

```html
<p data-placeholder="Highlights" class="is-empty"><br class="ProseMirror-trailingBreak"></p>
```

There is no `is-empty-editor` class here.

Part of my `package.json`:

```json
    "@mantine/tiptap": "^6.0.13",
    "@tiptap/extension-link": "^2.0.3",
    "@tiptap/extension-placeholder": "^2.0.3",
    "@tiptap/extension-underline": "^2.0.3",
    "@tiptap/pm": "^2.0.3",
    "@tiptap/react": "^2.0.3",
    "@tiptap/starter-kit": "^2.0.3",
```
```

**Comment by xiaohanyu** [comment]
BTW I have come up with an workaround for this. The core idea:

- Set `position: relative` to `<RichTextEditor>`
- Come up with a new `<Placeholder>` component and set its position to `absolute` and adjust `top` and `left` properties to make it appear inside `<RichTextEditor.Content>`
- Hide or show the `<Placeholder>` based on whether `editor.getText() === ''`

Pseudo code:

```typescript
type PlaceholderProps = {
  placeholder: string
  hide: boolean
}

function Placeholder({ placeholder, hide }: PlaceholderProps) {
  const useStyles = createStyles((theme) => ({
    placeholder: {
      color: theme.colors.gray[6],
      position: 'absolute',
      fontSize: theme.fontSizes.sm,
      fontWeight: 500,
      // 53 = 42 (toolbar height) + 1 (toolbar bottom border width) + 10
      // (content editor's top padding)
      top: '53px',
      left: '10px',
      display: hide ? 'none' : 'unset',
      pointerEvents: 'none',
    },
  }))

  const { classes } = useStyles()

  return <Text className={classes.placeholder}>{placeholder}</Text>
}

function TextEditor(...) {
  const editor = useEditor(...)
  return (
    <RichTextEditor
      editor={editor}
      styles={styles}
      // Set `position: relative` to make the placeholder's absolute position
      // work, this is a workaround for tiptap's bug:
      // https://github.com/ueberdosis/tiptap/issues/3109
      style={{ position: 'relative' }}
    >
      <RichTextEditor.Toolbar>
        <RichTextEditor.ControlsGroup>
          <TextEditorLabel label={label} required={required} />
        </RichTextEditor.ControlsGroup>
        <RichTextEditor.ControlsGroup>
          <RichTextEditor.Bold />
          <RichTextEditor.Italic />
          <RichTextEditor.Underline />
          <RichTextEditor.ClearFormatting />
          <RichTextEditor.BulletList />
          <RichTextEditor.OrderedList />
          <RichTextEditor.Link />
          <RichTextEditor.Unlink />
        </RichTextEditor.ControlsGroup>
      </RichTextEditor.Toolbar>
      <RichTextEditor.Content />
      <Placeholder
        placeholder={'Write somethine here...'}
        hide={!isEmptyValue(editor?.getText())}
      />
    </RichTextEditor>
  )
}
```

Hope this helps @yuyuyukie @aldinezi 

https://github.com/ueberdosis/tiptap/assets/1164623/79000d0d-d6f3-414e-826c-a9b6a65ee821

----

BTW, the method in https://github.com/ueberdosis/tiptap/issues/2659 wouldn't work as the DOM structure is wrong, it doesn't generate the `is-empty-editor` class here.
