### ISSUE TITLE
Blockquote keyboard shortcut triggers bold

### ISSUE THREAD

**Issue by apaar97** [ueberdosis/tiptap#3119]
### What’s the bug you are facing?

When using both Bold and Blockquote plugins, the [blockquote keyboard shortcut](https://github.com/ueberdosis/tiptap/blob/main/packages/extension-blockquote/src/blockquote.ts#L70) (Ctrl Shift B) instead triggers bold keyboard shortcut (Ctrl B). Note that this does not happen in docs [example](https://tiptap.dev/api/nodes/blockquote#usage), since Bold plugin is not included, and hence does not present a conflict

### Which browser was this experienced in? Are any special extensions installed?

Chrome, using officially supported tiptap plugins

### How can we reproduce the bug on our side?

Reproducible in the live example on https://tiptap.dev/

### What did you expect to happen?

Blockquote shortcut should also work in presence of Bold mark

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by rfgamaral** [comment]
You can change the priority for the Blockquote extension to `101`, and then it will take precedence over the Bold extension.

**Comment by bdbch** [comment]
As @rfgamaral explained most of our extensions are using `100` as the default priority - otherwise mixing up extensions would get complicated if there are to many priority jumps.

https://tiptap.dev/guide/custom-extensions/#priority

I'll close this ticket for now, if you have further questions, let me know @apaar97

**Comment by caschbre** [comment]
@bdbch I think this ticket should remain open. This issue is present when using the StarterKit (see the [default example](https://tiptap.dev/examples/default)).

While I get that you can configure the priority, the starterkit should have the priority set so that the keyboard shortcuts work.
