### ISSUE TITLE
tiptap vue3 :class="{ 'is-active': editor.isActive('bold') }"  application freezes

### ISSUE THREAD

**Issue by rendomnet** [ueberdosis/tiptap#3120]
### What’s the bug you are facing?

tiptap vue3 :class="{ 'is-active': editor.isActive('bold') }" causes whole application freeze

### Which browser was this experienced in? Are any special extensions installed?

Chrome

### How can we reproduce the bug on our side?

<button :class="{ 'is-active': editor.isActive('bold') }" @click="editor.chain().focus().toggleBold().run()">
  Bold
</button>

### What did you expect to happen?

button class changes

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by rendomnet** [comment]
Resolved by adding v-if="editor" to menu wrapper

**Comment by arquirupim** [comment]
Really Thanks! I was faced same problem! and solve it
