### ISSUE TITLE
 table extensions

### ISSUE THREAD

**Issue by lzxlzxlzxl** [ueberdosis/tiptap#3121]
### What problem are you facing?

Don't know how to set table size, border color, table name。

### What’s the solution you would like to see?

Add some table extensions，like border-color

### What alternatives did you consider?

Add some table extensions

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Could you give any more information? You can style the table inserted via Tiptap just as usual via CSS. I'll close this ticket for now and wait for more information.

**Comment by bdbch** [comment]
Not really sure what you mean @JohnMica - could you create a new issue for your problem and describe a bit in depth?
