### ISSUE TITLE
How delete content when drop to other editor use dropcursor, in multiple editors

### ISSUE THREAD

**Issue by songispm** [ueberdosis/tiptap#3133]
### What problem are you facing?

I have multiple editors, when I use dropcursor to drop content to other editor, the content still there in source editor.

![image](https://user-images.githubusercontent.com/38745323/187059484-077e5f61-48f5-4380-bcf8-ff6106f8da4d.png)

![image](https://user-images.githubusercontent.com/38745323/187059231-1ed818c4-83d0-4373-9fcd-4011532fbf27.png)

![image](https://user-images.githubusercontent.com/38745323/187059245-0a556903-d705-4ace-9526-8a93ee8dd5ba.png)

### What’s the solution you would like to see?

Tell me how delete it

### What alternatives did you consider?

Have not

### Anything to add? (optional)

example:

[https://codesandbox.io/s/dropcursor-multiple-editors-m0iti5](https://codesandbox.io/s/dropcursor-multiple-editors-m0iti5)

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Thanks for the issue, this seems to be a bug we should look into at some point.

**Comment by LuchoCateura** [comment]
Hello, I would like to help resolve this issue @bdbch

**Comment by LuchoCateura** [comment]
https://github.com/ueberdosis/tiptap/pull/3279

**Comment by bdbch** [comment]
I'm looking into your PR! Thanks for your submission ✌️

**Comment by bdbch** [comment]
When I'm done with the PR for sure!

**Comment by bdbch** [comment]
Fixed by https://github.com/ueberdosis/tiptap/pull/5893
