### ISSUE TITLE
Tsc Error --downlevelIteration

### ISSUE THREAD

**Issue by herzaislad** [ueberdosis/tiptap#3134]
### What’s the bug you are facing?

Halo

I'm using Tiptap on nextjs.
I'm creating Tiptap component to show the menu buttons:
```
import type { EditorEvents } from "@tiptap/core/dist/packages/core/src/types";
import { EditorContent, useEditor } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";

import MenuBar from "./MenuBar";
import { styTiptap } from "./styles";

interface ItfArgsOnUpdate {
  editor: EditorEvents;
}

interface ItfPropsTiptap {
  menu?: string[];
  content: string;
  onUpdate?: (_args: ItfArgsOnUpdate) => void;
}

function Tiptap(props: ItfPropsTiptap) {
  const { menu, content } = props;

  const editor = useEditor({
    extensions: [StarterKit],
    content,
  });

  return (
    <div className={styTiptap}>
      <MenuBar editor={editor} menu={menu} />
      <EditorContent editor={editor} />
    </div>
  );
}

export default Tiptap;

```

When I commit that component with hushky precommit action on terminal
`yarn tsc --noEmit --pretty`
I got this blocking error from it
```
node_modules/@tiptap/react/src/EditorContent.tsx:59:25 - error TS2802: Type 'NodeListOf<ChildNode>' can only be iterated through when using the '--downlevelIteration' flag or with a '--target' of 'es2015' or higher.
node_modules/@tiptap/react/src/EditorContent.tsx:92:26 - error TS2802: Type 'NodeListOf<ChildNode>' can only be iterated through when using the '--downlevelIteration' flag or with a '--target' of 'es2015' or higher.
```

My packages `tsconfig.json` has already excluded node_modules, but the issue persists
```
{
  "compilerOptions": {
    "allowJs": true,
    "baseUrl": ".",

    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "incremental": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "lib": ["dom", "dom.iterable", "esnext"],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "paths": {
      "@components/*": ["components/*"],
      "@firebase/*": ["firebase/*"],
      "@images/*": ["public/images/*"],
      "@lib/*": ["lib/*"],
      "@pages/*": ["pages/*"],
      "@posts/*": ["posts/*"],
      "@styles/*": ["styles/*"]
    },
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "es5",
    "tsBuildInfoFile": "./node_modules/tsbuildinfo/cache"
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "**/*.d.ts"],
  "exclude": ["node_modules"]
}
```

### Which browser was this experienced in? Are any special extensions installed?

It's on terminal, not browser

### How can we reproduce the bug on our side?

Just follow the issue explanation I've written above

### What did you expect to happen?

`yarn tsc --noEmit --pretty` should pas that <Tiptap /> component I created

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
I think this is more of a Typescript issue as the downlevelIteration problem has to do with spreadOperators and iteration handling when downleveling (building for older versions). See: https://www.typescriptlang.org/tsconfig#downlevelIteration

For more information:
https://mariusschulz.com/blog/downlevel-iteration-for-es3-es5-in-typescript

As the error explains you could try to enable iteration implementation for ES5 and lower or adjust your target to ES2015.

**Comment by bdbch** [comment]
Feel free to open again if you need assistance or the issue still exists.

**Comment by herzaislad** [comment]
Halo, thank you very much @bdbch for the reply.

Based on you conclusion, you are correct, it's typescript issue in nextjs.
In case any other developers experience the same, below is the solution (that works for me).

In `tsconfig.json`:
```
{
  "compilerOptions": {
    "allowJs": true,
    "baseUrl": ".",
    "types": [],
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "incremental": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "lib": ["dom", "dom.iterable", "esnext"],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "paths": {
      "@components/*": ["components/*"],
      "@firebase/*": ["firebase/*"],
      "@images/*": ["public/images/*"],
      "@lib/*": ["lib/*"],
      "@pages/*": ["pages/*"],
      "@posts/*": ["posts/*"],
      "@styles/*": ["styles/*"]
    },
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "es5",
    "tsBuildInfoFile": "./node_modules/tsbuildinfo/cache",
    "downlevelIteration": true
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "**/*.d.ts"],
  "exclude": ["node_modules"]
}
```

- add `downlevelIteration` to true
- clear the cache file in the `tsBuildInfoFile`
- clear .eslintcache if you have any (I'm not sure if it's involved, but give it a try)
