### ISSUE TITLE
BubbleMenuPlugin interferes with React unmounting

### ISSUE THREAD

**Issue by fwouts** [ueberdosis/tiptap#3135]
### What’s the bug you are facing?

When a `<BubbleMenu />` is rendered in React, unmounting the React root crashes:

```
Uncaught DOMException: Node.removeChild: The node to be removed is not a child of this node
```

### Which browser was this experienced in? Are any special extensions installed?

All browsers (tested on Firefox and Chrome)

### How can we reproduce the bug on our side?

- Clone https://github.com/fwouts/tiptap-react-unmount-bug
- Run `pnpm install` (or `yarn install` or `npm install`)
- Run `pnpm dev` (or `yarn dev` or `npm run dev`)
- Check the console logs for the error

### Can you provide a CodeSandbox?

https://stackblitz.com/github/fwouts/tiptap-react-unmount-bug

### What did you expect to happen?

The node should be unmounted cleanly.

### Anything to add? (optional)

I believe I understand the source of the bug:
- BubbleMenu passes a `<div>` managed by React to its BubbleMenuPlugin: https://github.com/ueberdosis/tiptap/blob/5844a8893c1d0b888b3a338ce3fb3994383a9eef/packages/react/src/BubbleMenu.tsx#L28
- BubbleMenuPlugin detaches it from its parent, breaking React's expectations: https://github.com/ueberdosis/tiptap/blob/5844a8893c1d0b888b3a338ce3fb3994383a9eef/packages/extension-bubble-menu/src/bubble-menu-plugin.ts#L81

Perhaps the solution is to create the `div` with plain DOM APIs?

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by ssalka** [comment]
Hi, I'm also experiencing this bug, and can repro the issue from @fwouts' stackblitz link – in my application, it seems to happen whenever the Editor component itself unmounts, eg in a SPA if you have the editor rendered on 1 page, and then you click away to another page that doesn't have it, the unmounting of the editor results in this crash.

Would be great to see a fix for this, as I'm currently having to use react-error-boundary to cover up this behavior. Thanks Tiptap team!

**Comment by Xiang-Zuo** [comment]
Face the same issue, my workaround solution is to use the tippyOptions prop that passed into BubbleMenu. Since BubbleMenu uses [tippy.js](https://atomiks.github.io/tippyjs/v6/all-props/). One of the tippy's options called onShow() can optionally return false to cancel a show. So instead of unmounting the menu, it hides the menu.

Code:

`  <BubbleMenu
            editor={editor}
            tippyOptions={{
                duration: 100,
                onShow: () => {
                    return false;
                },
            }}
        >{children}
    </BubbleMenu>
`

**Comment by Haraldson** [comment]
@Xiang-Zuo Do you have a more complete example? Where does the `shouldShow` variable come from? And is this fix based on always rendering `<BubbleMenu />` instead of, for instance, `return null` earlier in the editor wrapper component?

**Comment by ScottSavarie** [comment]
This feels like a hack, but I got around the issue by setting `shouldShow` on `BubbleMenu`

```
<BubbleMenu shouldShow={() => isVisible} editor={editor}>
```
