### ISSUE TITLE
When the number of ordered-lists exceeds 100, the text area overflows.

### ISSUE THREAD

**Issue by JeoungSulMo** [ueberdosis/tiptap#3142]
### What’s the bug you are facing?

![image](https://user-images.githubusercontent.com/50662170/187570319-cd8eeea7-3e28-428d-b280-4661d84291a8.png)

### How can we reproduce the bug on our side?

Create order list at least 100 times.

### Can you provide a CodeSandbox?

sorry

### What did you expect to happen?

![image](https://user-images.githubusercontent.com/50662170/187570552-bc464804-cec9-4487-bec5-6e982a350375.png)

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Hey @JeoungSulMo could you create a sandbox so we can reproduce this issue?
I created a demo for this and it works fine here I think:

https://codesandbox.io/s/sweet-lichterman-om9848?file=/src/App.js

**Comment by bdbch** [comment]
Feel free to reopen this if you have a replicatable demo
