### ISSUE TITLE
Bubble menu extension "document isn't defined" error in Nextjs 

### ISSUE THREAD

**Issue by Prottoy2938** [ueberdosis/tiptap#3143]
### What’s the bug you are facing?

**How to use titap bubble menu extension in nextjs?**

Bubble menu extension "document isn't defined" error in Nextjs when trying to initiate `useEditor`.

Tried running the `useEditor` function inside the useEffect function, but then get another error saying can't run a state hook on another state hook error or something similar.

How to solve this?

### Which browser was this experienced in? Are any special extensions installed?

Chrome. No special extensions are installed

### How can we reproduce the bug on our side?

```jsx
const Editor = () => {


const editor = new Editor({
  extensions: [
    BubbleMenu.configure({
      element: document.querySelector('.menu'), // ERROR HERE
    }),
  ],
content:`hello world`
})


return (
    <div>
      <MenuBar editor={editor} />
 {editor && (
        <FloatingMenu editor={editor} tippyOptions={{ duration: 100 }}>
          <button
            onClick={() =>
              editor.chain().focus().toggleHeading({ level: 1 }).run()
            }
            className={
              editor.isActive("heading", { level: 1 }) ? "is-active" : ""
            }
          >
            h1
          </button>
        </FloatingMenu>
      )}
      <EditorContent editor={editor} />
    </div>
  );

}
```

### What did you expect to happen?

..

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
> Bubble menu extension "document isn't defined" error in Nextjs when trying to initiate useEditor.

This sounds like Next.js SSR is having an issue with the document not existing on the server side? At least that would my shot in the dark as I don't have a demo project for Next.js setup for now.

> Tried running the useEditor function inside the useEffect function, but then get another error saying can't run a state hook on another state hook error or something similar.

Thats correct, using hooks in `useEffect` is not possible, as hooks are run on each re-render of the component. Move useEditor out of useEffect.

**Comment by Prottoy2938** [comment]
One possible solution would be to import the `Editor` component via **nextjs dynamic with no ssr**

Code the `Editor` component as usual, and then  when using the component to somewhere, import it like this:
Sortof like this:

```jsx
import dynamic from "next/dynamic";
const Editor = dynamic(
  () =>
    import(
      "./path/to/you-component"
    ),
  { ssr: false }
);
```

**Comment by bdbch** [comment]
Would this be a desired solution for your issue? @Prottoy2938
Otherwise I could try to setup an example Next.js app with an Tiptap editor to see if I encounter the same issues.

**Comment by bdbch** [comment]
I created a Stackblitz with Next.js and the latest Tiptap version:
https://stackblitz.com/edit/tiptap-nextjs-example-nvk1re?file=pages/index.js

Looks fine to me - is there something that is different to your solution?

**Comment by Prottoy2938** [comment]
Yes. My problem was with `Floating Menu`, not `Bubble Menu` (my mistake with the question.

In floating menu, you've got to use this in the `useEditor`:

```jsx
new Editor({
  extensions: [
    FloatingMenu.configure({
      element: document.querySelector('.menu'), // this is the part that causes problem in nextjs
    }),
  ],
})
```

So if you put this line in the stackblitz example above, you'd probably see the error.

Now, I bypassed this error by using the previous solution above that I've mentioned, by rendering the component during SSR

**Comment by bdbch** [comment]
You can also use the FloatingMenu component from the `@tiptap/react` library, see here:
https://stackblitz.com/edit/tiptap-nextjs-example-ndhvkn?file=components/Editor.jsx

**Comment by bdbch** [comment]
I'll close this issue for now as it seems like you found a solution for your issue.
