### ISSUE TITLE
Details extension: Error Duplicate use of selection JSON ID gapcursor

### ISSUE THREAD

**Issue by gmpetrov** [ueberdosis/tiptap#3157]
### What’s the bug you are facing?

Hi, I just installed the Details Pro ext and I'm getting the following error when I inject the extension. 
"Duplicate use of selection JSON ID gapcursor"
Has anyone encountered this error before?
"@tiptap/react": "^2.0.0-beta.115",
    "@tiptap-pro/extension-details": "^2.0.0-beta.5",
    "@tiptap-pro/extension-details-content": "^2.0.0-beta.5",
    "@tiptap-pro/extension-details-summary": "^2.0.0-beta.2",

### Which browser was this experienced in? Are any special extensions installed?

Chrome

### How can we reproduce the bug on our side?

"@tiptap/react": "^2.0.0-beta.115",
    "@tiptap-pro/extension-details": "^2.0.0-beta.5",
    "@tiptap-pro/extension-details-content": "^2.0.0-beta.5",
    "@tiptap-pro/extension-details-summary": "^2.0.0-beta.2",

### What did you expect to happen?

Use the extension without error 😅

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by nicholasareed** [comment]
I had the same issue, solved it by adding:
```
  "resolutions": {
    "prosemirror-gapcursor": "1.3.0"
  },
```
to my `package.json` and re-running yarn (clear node_modules too, for good measure)

**Comment by gmpetrov** [comment]
> 

Thx mate! It's working 😀
