### ISSUE TITLE
Non-text leaf nodes interfere with link extension paste rules, causing incorrect href attribute on paste

### ISSUE THREAD

**Issue by Billiam** [ueberdosis/tiptap#3158]
### What’s the bug you are facing?

The link extension can silently append Object Replacement Characters to its href attributes on paste, depending on clipboard content, causing the links to be broken.

If a user's clipboard contains `text/html` content, with a plain-text URL followed by a `<br>`, the BR will be treated as a "non-text leaf node" for the purposes of the [`node.textBetween` call](https://github.com/ueberdosis/tiptap/blob/5bcfb322ceb30575430bd8797f2787d65de80f2c/packages/core/src/PasteRule.ts#L116-L121), and replaced with an Object Replacement Character, which is then added to the href attribute of the pasted link.

This is causing issues when users paste links that happen to have come from somewhere with a trailing <br> characters. You'd need to inspect the link in browser devtools, or with a custom link UI in an editor, to see that the URL was incorrect.

The amount of trailing content added to the clipboard on copy can be pretty unpredictable, and depends a lot on browser and probably OS, and it's often not obvious (or at all visible) to the user, so it's not easy for the end user to prevent this issue either.

This issue does not occur on the tiptap.dev link example, because it uses `autolink: true`, which hides the problem.

### Which browser was this experienced in? Are any special extensions installed?

Chrome 104, Firefox 103. No relevant extensions.

### How can we reproduce the bug on our side?

Visit [Codesandbox link](https://codesandbox.io/s/tiptap-link-paste-forked-h5wy20), copy all content in second box, paste into editor above.

Observe that google link contains extra characters in href attribute, and that URL is not valid.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/tiptap-link-paste-forked-h5wy20

### What did you expect to happen?

Non-text nodes are not converted to ￼, or otherwise added to link hrefs on paste.

### Anything to add? (optional)

https://user-images.githubusercontent.com/242008/188714860-a5eea19a-f0b7-44de-b378-0556f4c19157.mp4

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by ryanmcgarvey** [comment]
I Just came across this issue - it's happening for me with Mentions _at the beginning of a document_

When the mention tag gets inserted, it gets picked up by the autolink, and then errors out.

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replace')
    at run$12 (linkify.module.js:2036:36)
    at tokenize (linkify.module.js:2914:38)
    at find2 (linkify.module.js:2925:16)
    at autolink.ts:94:11
    at Array.forEach (<anonymous>)
    at Plugin.appendTransaction (autolink.ts:34:15)
    at EditorState.applyTransaction (index.js:805:55)
    at EditorState.apply (index.js:770:21)
    at Editor2.dispatchTransaction (Editor.ts:339:30)
    at EditorView.dispatch (index.js:5176:33)`

Looking through the code it looks like "lastWordBeforeSpace" is undefined.

`          
const wordsBeforeWhitespace = textBeforeWhitespace.split(' ').filter(s => s !== '')
const lastWordBeforeSpace = wordsBeforeWhitespace[wordsBeforeWhitespace.length - 1]`

**Comment by chzeh** [comment]
I have got the same issue when inserting a custom node-view at the beginning of a empty line.
`runtime-core.esm-bundler.js:218 Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at run$1 (linkify.module.js:2036:36)
    at tokenize (linkify.module.js:2914:38)
    at find (linkify.module.js:2925:16)
    at autolink.ts:94:11
    at Array.forEach (<anonymous>)
    at Plugin.appendTransaction (autolink.ts:34:15)
    at EditorState.applyTransaction (index.js:805:55)
    at EditorState.apply (index.js:770:21)
    at Editor2.dispatchTransaction (Editor.ts:339:30)
    at EditorView.dispatch (index.js:5257:33)`
Autolink is activated at insertContent call and errors out since 'lastWordBeforeSpace' is undefined.
Does anyone have a workaround yet ?
