### ISSUE TITLE
Custom properties on nodes

### ISSUE THREAD

**Issue by thefinnomenon** [ueberdosis/tiptap#3160]
### What problem are you facing?

I am interested in adding custom properties to nodes as well as define their menus in the same file.

### What’s the solution you would like to see?

For example, it is awesome that you can make any node draggable by setting `draggable: true`. I would like the ability to do this with other common node properties like resizable, captionable, etc. In the same kind of idea, it would also be nice to be able to set a bubble menu in the node configuration as well,
```
export const Image = Node.create<ImageOptions>({
  name: 'image',
  draggable: true,
  resizable: true,
  captionable: true,
  bubbleMenu: ({ editor }) => <ImageBubbleMenu editor={editor} />
  ...
```

### What alternatives did you consider?

For the custom properties I just have to recreate the same functionality across the nodes and for the menus, I handle them external to the node & trigger them based upon if the relevant node is selected.

### Anything to add? (optional)

These abilities would make the custom nodes easier to develop and better self-contained.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by huzailhassan** [comment]
If I am getting this right, you are looking into [extending ](https://tiptap.dev/guide/custom-extensions#extend-existing-extensions
)an existing node extension.

**Comment by thefinnomenon** [comment]
Actually, it would be extending the Node class to include custom properties that you could use when creating or extending nodes. I am thinking it will require forking the library and digging through some of the core but wanted to see if anyone had explored it.
