### ISSUE TITLE
Audio tag inside editor

### ISSUE THREAD

**Issue by jonalxh** [ueberdosis/tiptap#3166]
### What problem are you facing?

I'm currently developing a test creation dashboard and sometimes we would like to add audio files between paragraphs. I was trying to add a custom command wich shows a dialog to upload the file and after that add the audio tag inside the tiptap editor, I've done everything but I found that the editor does not accept the audio tag and I'm unable achieve it.

### What’s the solution you would like to see?

It could be very cool to have an audio extension, but by now the most important thing for me is to render an audio tag inside the editor.

### What alternatives did you consider?

By the moment I'll add a custom text and will replace it with an audio tag when I render the content to the end user, another approach is to add the audio tags after the text editor content, but in my case it is necessary to add the tag after each paragraph.

### Anything to add? (optional)

Maybe do you have an idea of what to do to make it work? I've been looking for around the Prosemirror editor but found nothing.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Hey @jonalxh 

you should easily be able to create an Audio node (for example here: https://codesandbox.io/s/hopeful-sinoussi-dxyt6g?file=/src/App.js)

Let me know if you need help.

**Comment by jonalxh** [comment]
Thanks a lot, it works.

**Comment by jonalxh** [comment]
@bdbch I have a problem, when I re-render the editor passing the value with the audio tag inserted as above it is empty, if I render the code in another side with a v-html it works, but not in the editor, I think that the problem is because the fix you suggested me creates a source tag inside the audio tag and I am just generating the audio tag with a src attribute, but I've tried to change the insert code with audio and source and it does not work. Any idea?
