### ISSUE TITLE
Menu buttons require two clicks (double click) to take effect

### ISSUE THREAD

**Issue by n3dwards** [ueberdosis/tiptap#3171]
### What’s the bug you are facing?

So I've just started using TipTap (with React) and began with the documentation and basic example [here](https://tiptap.dev/installation/react). I was quickly able to get a basic WYSIWYG editor set up by pretty much just copying and pasting the example files from that page.

The issue arose when I first started interacting with the editor within my app. Clicking on any of the menu buttons a single time does nothing but remove focus from the editor. It does not invoke the onClick function for the menu button that you clicked. In order for it to actually take effect, it must be clicked twice. I have reproduced this issue with a minimal setup on [codesandbox](https://codesandbox.io/s/tiptap-double-click-7mkc38).

My own observations indicate that it doesn't actually require two _sequential_ clicks on the _same_ button. The first click just has to be somewhere outside of the editor box. After focus is removed from the editor box, the menu buttons only require a single click (their normal behavior). However, as soon as you click any of the buttons, the issue pops right back up immediately.

Am I missing something completely obvious here? I followed the basic setup instructions to a T and this issue popped up immediately, but I wasn't able to find anything that indicated this was a known issue and it is very clear that the example on the first page I linked (the documentation) is not suffering from this issue.

### Which browser was this experienced in? Are any special extensions installed?

I don't believe it's a browser issue, but I'll note that I have tested this in:

- Chrome Version 104.0.5112.101 (with some extentions)
- Firefox 104.0.2 (fresh install)

### How can we reproduce the bug on our side?

Follow the instructions on [this](https://tiptap.dev/installation/react) page. Alternatively, view the [codesandbox](https://codesandbox.io/s/tiptap-double-click-7mkc38) where I performed this and reproduced the issue.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/tiptap-double-click-7mkc38

### What did you expect to happen?

I expected the buttons to function the way they do on the [documentation example page](https://tiptap.dev/installation/react), where only a single click is required to invoke the menu button functions.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Hey @n3dwards 

Tiptap doesn't seem to be the issue here. The reason why that happens that your `<MenuBar />` component gets declared inside the `<TipTap />` component - which means on each rerender of TipTap the MenuBar component gets recreated.

That's why when you focus the editor, the MenuButton is recreated and you have to first click out of the editor and then click on a menu button (because then the state doesnt update).

https://codesandbox.io/s/tiptap-double-click-forked-bk99j0?file=/src/TipTap.js

Here you can see that it works as expected, when you are pulling the MenuBar out of the TipTap component.
