### ISSUE TITLE
v193 core is missing dist build - 

### ISSUE THREAD

**Issue by OliverGrimsley** [ueberdosis/tiptap#3179]
### What’s the bug you are facing?

On npm update, tip tap core .193 updated, but on vite build, got errors:

Failed to resolve entry for package "@tiptap/core". The package may have incorrect main/module/exports specified in its package.json

### Which browser was this experienced in? Are any special extensions installed?

no browser, on build of application

### How can we reproduce the bug on our side?

update an app to .193 core - build will fail

### Can you provide a CodeSandbox?

No

### What did you expect to happen?

My app to build

### Anything to add? (optional)

I installed npm i @tiptap/core@2.0.0-beta.183 to revert back, and app worked (vite ran fine).  You just forgot to build the dist folder...

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by maximemoreillon** [comment]
My Nuxt app, which uses tiptap, also doesn't build anymore, stating: 
```
Cannot find module '@tiptap/core'
```

**Comment by mauricior** [comment]
Same problem here: 

`error - Error: Cannot find module '.../node_modules/@tiptap/core/dist/tiptap-core.cjs.js'. Please verify that the package.json has a valid "main" entry

Module not found: Can't resolve '@tiptap/core'
`

**Comment by georgelucasgp** [comment]
Error in this version, it broke the AdminJS installation, I went back to the previous version and it worked.
Error: Cannot find module '/Users/gg/development/NODE/adminjs/node_modules/@tiptap/core/dist/tiptap-core.cjs.js'. Please verify that the package.json has a valid "main" entry

**Comment by corwinstephen** [comment]
Same

**Comment by pb0710** [comment]
Same, vite:
✘ [ERROR] [plugin vite:dep-pre-bundle] Failed to resolve entry for package "@tiptap/core". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@tiptap/core". The package may have incorrect main/module/exports specified in its package.json.

**Comment by bdbch** [comment]
Working on it

**Comment by bdbch** [comment]
I just released beta.194 which should have a functional bundle again.

**Comment by maximemoreillon** [comment]
I can confirm that my application now builds properly. Thank you so much for taking the time to fix this issue, especially on a sunday!
