### ISSUE TITLE
@tiptap/react: Changing the useEditor hook so that not all types of transactions causes a forced update.

### ISSUE THREAD

**Issue by yyjlincoln** [ueberdosis/tiptap#3181]
### What problem are you facing?

Hi,

In our application where we uses TipTap for both editing and displaying our content, we are facing some performance issues where the parent component rerenders unnecessarily when the cursor has moved or when the editor has been clicked. We had quite some wrappers and custom extensions, so we spent some time debugging it and we were able to reproduce it with the following code snippet:

```javascript
import React from "react";
import { EditorContent, useEditor } from "@tiptap/react";

import Document from "@tiptap/extension-document";
import Text from "@tiptap/extension-text";
import Paragraph from "@tiptap/extension-paragraph";

export default () => {
  const editor = useEditor({
    extensions: [Document, Text, Paragraph],
    content: {
      type: "doc",
      content: [
        {
          type: "paragraph",
          content: [
            {
              type: "text",
              text: "Hello World!",
            },
          ],
        },
      ],
    },
    editable: false,
  });

  console.log("Rerender");

  return (
    <div>
      <h1>Test</h1>
      <EditorContent editor={editor} />
    </div>
  );
};
```

_Note: You can replace the contents of demos/src/Examples/Default/React/index.jsx with the above code to quickly reproduce this._ 

By selecting the node in read-only mode, we would see "Rerender" being printed out multiple times, which impacts the performance if the parent page is complicated.

After some investigation, we realise that this was caused by useEditor.ts, in:

```typescript
instance.on('transaction', () => {
      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          if (isMounted) {
            forceUpdate()
          }
        })
      })
    })
```

Where the selection change is considered as a transaction (even if the doc has not changed and the editor is set to read-only), thus triggering the forceUpdate. The transaction looks something like this:

```javascript
const transaction = {
//    "doc": Omitted,
    "steps": [],
    "docs": [],
    "mapping": {
        "maps": [],
        "from": 0,
        "to": 0
    },
    "curSelectionFor": 0,
    "updated": 1,
    "meta": {
        "pointer": true
    },
    "time": 1662948837275,
    "curSelection": {
        "type": "text",
        "anchor": 13,
        "head": 13
    },
    "storedMarks": null,
    "docChanged": false,
    "isGeneric": false,
    "scrolledIntoView": false,
//    "selection": Omitted,
    "selectionSet": true,
    "storedMarkSet": false
}
```

I'm wondering whether capturing all transactions of all types is necessary, and if it does prove to be necessary, can we please implement a way to filter the transaction so that the parent component is not constantly being rerendered?

For example, the following changes may help, although I'm not too sure about the whole implication of this:

```
import { EditorOptions } from '@tiptap/core'
import { Transaction } from 'prosemirror-state'
import { DependencyList, useEffect, useState } from 'react'

import { Editor } from './Editor'

function useForceUpdate() {
  const [, setValue] = useState(0)

  return () => setValue(value => value + 1)
}

export const useEditor = (options: Partial<EditorOptions> = {}, deps: DependencyList = []) => {
  const [editor, setEditor] = useState<Editor | null>(null)
  const forceUpdate = useForceUpdate()

  useEffect(() => {
    let isMounted = true

    const instance = new Editor(options)

    setEditor(instance)

    const isQualifyingTransaction = (transaction: Transaction): boolean => {
      if (!instance.isEditable && !transaction.docChanged) {
        return false
      }
      return true
    }

    instance.on('transaction', ({ transaction }) => {
      requestAnimationFrame(() => {
        requestAnimationFrame(() => {
          if (isMounted && isQualifyingTransaction(transaction)) {
            forceUpdate()
          }
        })
      })
    })

    return () => {
      instance.destroy()
      isMounted = false
    }
  }, deps)

  return editor
}
```

Cheers,
Lincoln

### What’s the solution you would like to see?

A way to filter the transactions that would result in the parent component being rerendered, thus reducing unnecessary rerenders and improve the performance.

### What alternatives did you consider?

- The use of flags?
- A dedicated "readonly" version that acts like a controlled form element, which only rerenders in limited situations.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by C-Hess** [comment]
There are definitely use cases for triggering re-renders for selection changes. I'm curious if your specific performance issues can be resolved by breaking down your parent component more.

For example, instead of something like this:
```tsx
const MyComplexComponent = () => {
  const editor = useEditor();
  
  return <>
      My very complex page
      // Really complex stuff goes here
      <EditorContent editor={editor} />
  </>
}
```

Could you instead do this?
```tsx
const MyEditorWrapper = ({ onUpdate }) => {
  const editor = useEditor();
  return <EditorContent editor={editor} onUpdate={onUpdate} />
}

const MyComplexComponent = () => {
  const editor = useEditor();
  
  return <>
      My very complex page
      // Really complex stuff goes here
      <MyEditorWrapper  />
  </>
}
```

Doing so will ensure that only the editor wrapper component gets re-rendered on changes. the `onUpdate` event provided by TipTap already only fires when the content is changed, not the selection (the selection can be handled by the `onSelectionUpdate` event)
