### ISSUE TITLE
How can I import document into editor with URL?

### ISSUE THREAD

**Issue by Rnine-99** [ueberdosis/tiptap#3182]
### What problem are you facing?

My documents are stored on cloud, and I can access it by URL like [this](https://document-1310787519.cos.ap-beijing.myqcloud.com/document/6ae94b2e-18e5-43f2-ae07-c32c03eb0995.txt)
I want to import the document into the editor

### What’s the solution you would like to see?

I'd like a API that can import from different types of document like .txt .doc or even .md

### What alternatives did you consider?

.txt can be directly opened in browser, maybe you can try that first

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by huzailhassan** [comment]
From my understanding, you want to use the contents of a remote txt file to display into TipTap's HTML? Calling "editor.getHTML()" would show "<p>銝齿鱏憟𧢲��</p>" (the file you provided's content) 

So you can just make a GET request to "https://document-1310787519.cos.ap-beijing.myqcloud.com/document/6ae94b2e-18e5-43f2-ae07-c32c03eb0995.txt" (The file you mentioned), and then just pass the the text file into: 

```
    this.editor = new Editor({
      content: this.PASSEDINTXTFILECONTENT,
    })
```
