### ISSUE TITLE
Cannot open dev tools when using editor

### ISSUE THREAD

**Issue by jf908** [ueberdosis/tiptap#3191]
### What’s the bug you are facing?

The dev tools cannot be opened with the <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>i</kbd> shortcut while the editor is selected because it is overridden by the italic shortcut, not the biggest deal but it does happen quite frequently during development. 

### Which browser was this experienced in? Are any special extensions installed?

Windows 10/11, Chrome and Firefox

### How can we reproduce the bug on our side?

1. Highlight tiptap editor
2. Press <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>i</kbd>

### What did you expect to happen?

Dev tools opens

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by shahsagarmm** [comment]
@jf908 did you find any solution?

**Comment by jf908** [comment]
I've just been trying to remember to unfocus the editor before I try to open dev tools. I'm guessing you could manually override the shortcut but I haven't tried it yet.
