### ISSUE TITLE
Make Cypress tests more reliable and faster

### ISSUE THREAD

**Issue by bdbch** [ueberdosis/tiptap#3193]
### What’s the bug you are facing?

The Cypress tests have two major problems from what I can see:

1. They are super slow resulting in a slow response time to potential test failures. This could be maybe improved but we'll have to check how
2. The tests are sometimes failing because the chrome renderer didn't render in time. This causes tests to sometimes fail in between different runs without reason.

Both issues result in tests not being a reliable way to point out potential breaking bugs.

### Which browser was this experienced in? Are any special extensions installed?

-

### How can we reproduce the bug on our side?

-

### What did you expect to happen?

The tests should run faster - maybe by just running tests for changed files. I don't know if this is possible with Cypress but it's worth to investigate.

Tests should also run reliable - this is something where I'm not sure how to solve it. In the past I tried to push up the wait time which totally bloated test times.

If we can somehow combine both solutions (or maybe find a way to tell Cypress to always wait for the document to finish loading with a running Tiptap instance) would be great.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by mattvb91** [comment]
Not sure if its related but I am currently struggling trying to test my application:

```
CypressError: Timed out retrying after 4050ms: `cy.click()` failed because this element is detached from the DOM.
`<div contenteditable="true" translate="no" tabindex="0" class="ProseMirror">...</div>`
Cypress requires elements be attached in the DOM to interact with them.
```

Even when changing the selectors around the rerender is always causing cypress to fail. Really difficult to track down
