### ISSUE TITLE
Just importing Mention dependency causes site to crash

### ISSUE THREAD

**Issue by MEBonham** [ueberdosis/tiptap#3194]
### What’s the bug you are facing?

Hi, I have a React project based on Vite (not create-react-app), and I'm trying to add Tiptap Mention support to its rich text editor. The StarterKit and FloatingMenu and BubbleMenu and their components are working fine, but when I include the line
`import Mention from '@tiptap/extension-mention';`
the resultant website loads over and over again in an infinite loop; the Console says Gateway Timeout.

I've commented out all the code intended to actually USE the Mention extension and the error persists, but when I comment out the import line, the site goes back to stability.

### Which browser was this experienced in? Are any special extensions installed?

Microsoft Edge; no extensions that I think would be relevant.

### How can we reproduce the bug on our side?

I have reproduced the bug (or close to it, I'm getting a single crash instead of looping behavior) on a fresh, tiny Vite-React project, which you can clone from https://github.com/MEBonham/minimal-bug-demo

Run it on localhost by using
```
cd mention-bug-recreation
yarn
yarn dev
```
... and opening localhost to the port your terminal indicates (5173 for me).

In App.jsx is the troublesome import line of code, currently commented out, but if you un-comment it you'll see (if your browser has the same behavior as mine) that the Gateway Timeout error keeps the page from loading.

### What did you expect to happen?

I expect bugs to happen when I try to use imports, not when I merely import them! That's why I'm baffled and coming to Issues for help.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by MEBonham** [comment]
I have reproduced the bug on Firefox, where the Console error gives more information. It says (briefly, before the loop triggers again) that
`the extension was blocked because of a disallowed MIME type ("")`

**Comment by bdbch** [comment]
Could you try to install the Suggestion package via `yarn add @tiptap/suggestion`?

**Comment by MEBonham** [comment]
Yep, that seems to have fixed it. Does the documentation say that Mention needs Suggestion too, and I just missed it?

**Comment by bdbch** [comment]
In beta.193 we marked the suggestion package as a peer dependency. I'll update the documentation accordingly. Thanks for informing me on this issue!

**Comment by MEBonham** [comment]
Thanks for helping so promptly!
