### ISSUE TITLE
Unable to select Figure image

### ISSUE THREAD

**Issue by joppehoekstra** [ueberdosis/tiptap#3203]
### What’s the bug you are facing?

When using the experimental [Figure](https://tiptap.dev/experiments/figure) element, I am not able to select the entire node by clicking on the image. I can only focus it by dragging the element, or by editing the caption.

### Which browser was this experienced in? Are any special extensions installed?

Using the experimental Figure extension.

### How can we reproduce the bug on our side?

1. Insert an Figure with image and caption.
2. Click on the image.
3. The Figure node will not focus.

### What did you expect to happen?

I would like to see consistent behaviour with the Image node, where the user is able to select the image by clicking on it (for example, to delete it by pressing backspace).

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by GodsonAddy** [comment]
@joppehoekstra Please have you found another way of selecting the figure and at the same being able to edit the figcaption? I'm having the same issue and I will need your help. This is a link to my codesandbox [https://codesandbox.io/p/sandbox/confident-ully-rzths5](https://codesandbox.io/p/sandbox/confident-ully-rzths5)   Thanks
