### ISSUE TITLE
Placeholder extension doesn't work in html/generateHTML

### ISSUE THREAD

**Issue by harrisjose** [ueberdosis/tiptap#3204]
### What’s the bug you are facing?

The decorations added from the placeholder extension (`data-placeholder` and '.is-empty') seem to be missing when the content is rendered via the `generateHTML` function. Are decorations skipped during `generateHTML`?

To add more context: We only switch to the editor when the user goes into edit mode for a specific paragraph. Until then (and also during SSR) the content is rendered via generateHTML. If decorations are intentionally omitted during generateHTML, is there a way around this to show placeholders?

### Which browser was this experienced in? Are any special extensions installed?

Chrome

### How can we reproduce the bug on our side?

Configure the placeholder extension and the necessary css. Render the content via generateHTML in `@tiptap/html`. I use the following options in the placeholder extension to make placeholders visible always when the content is empty.
```
showOnlyWhenEditable: false,
showOnlyCurrent: false,
```

### Can you provide a CodeSandbox?

https://stackblitz.com/edit/react-ts-z54doy?file=App.tsx

### What did you expect to happen?

The decorations added by placeholder extension should be available on the generated html document

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
I'd have to test this to see if there is a way to manually add the decoration when rendering Prosemirror content via `generateHTML`. I'd assume that the default behavior should be to not render them as most of the time I'd guess people don't want placeholder content in their rendered HTML content.

**Comment by harrisjose** [comment]
Absolutely understand the reasoning for skipping this. If this can be controlled from the extension then I can just extend it and make the changes but it's not immediately obvious to me from the placeholder extension package 🤔
