### ISSUE TITLE
Don't apply other input rules while creating an inline code mark

### ISSUE THREAD

**Issue by philippkuehn** [ueberdosis/tiptap#321]
This gif best describes the problem:

![ohno](https://user-images.githubusercontent.com/2500670/58199436-bef0ba80-7cd0-11e9-8fb6-3d9c535e2fa7.gif)

I'm not sure how to solve this. I don't think it's a good idea to fix this within the italic input rule regex (`/(?:^|[^_])(_([^_]+)_)$/`), because it will mix logic between nodes/marks. 

And I'm not sure if it would be a good idea to prevent any input rule if there is a backtick anywhere before (in the current node).

Any ideas?

**Comment by christosnc** [comment]
IMO the proposed idea is wrong. Typing the first \` does not mean you intend to turn it into a code mark. Until you insert the second \` the whole section is considered as plain text, so other rules may apply.

What is the real problem though, is that we can't insert \`\` and then put the caret between the two backticks and type the code. We have to put the first \` then some text and then the second \` in order for the code mark to be activated.

**We should be able to do this:**
**1. Type: \`\`**
**2. Put the caret between the two backticks (left arrow or click)**
**3. Write something and transform into code**

**Comment by hanspagel** [comment]
@philippkuehn You fixed this in v2, so I’m closing this here. 👋
