### ISSUE TITLE
Typography: Add service mark symbol

### ISSUE THREAD

**Issue by georgemandis** [ueberdosis/tiptap#3219]
### What problem are you facing?

It's a small ask, but we would love to see the service mark subscript added to the Typography extension.

It is very similar to the trademark superscript symbol: ™

It looks like this: ℠

It's niche, but valid:
https://en.wikipedia.org/wiki/Service_mark_symbol

### What’s the solution you would like to see?

I would love to see (sm) converted to ℠ similar to how (tm) is converted to ™

### What alternatives did you consider?

We considered forking and extending the extension ourselves, but it makes sense to me as part of the existing Typography extension?

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by svenadlung** [comment]
@georgemandis Good idea, please have a look: https://deploy-preview-3220--tiptap-embed.netlify.app/src/extensions/typography/react/

**Comment by georgemandis** [comment]
@svenadlung Looks great!
