### ISSUE TITLE
Calling `editor.isActive('text')` always returns false

### ISSUE THREAD

**Issue by HydrofinLoewenherz** [ueberdosis/tiptap#3221]
### What’s the bug you are facing?

When i'm trying to show part of my bubble menu only when a text is selected with `isActive('text')`, it never shows.

### Which browser was this experienced in? Are any special extensions installed?

Google Chrome, Vue 3

### How can we reproduce the bug on our side?

Create a basic editor with document, paragraph and text extensions. Add a conditional element with `v-if="editor.isActive('text')"`.

### What did you expect to happen?

I would expect `editor.isActive('text')` to be true, when a text node (with or without marks) is selected. For example when a text node is used outside of a paragraph (im using it in a `figcaption`).

### Anything to add? (optional)

If it is technically not possible to check for the text node, because it is to special, then it would be nice to use `isActive` with a node group tag (or the like). It would be tedious to add every single node that uses text to my `isActive` check.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by Stalinko** [comment]
Any luck with this?
I'm experiencing the same with Vue2.
"isActive" acts completely crazy. Sometimes returns the status of the 1st node and not the selected one, sometimes just always "false".
