### ISSUE TITLE
The tr actions different in OnTransaction between @tiptap/vue-2 and vue-3

### ISSUE THREAD

**Issue by chenyuncai** [ueberdosis/tiptap#3224]
### What’s the bug you are facing?

I'am trying to add a custom extension to operate the tr when content being edited.

So I got the transaction in the OntransAction Event and try to add new steps.

And found that the tr cannot be applied to the current view state in vue2. So I have this hack

```
const isThisTrApplied = transaction.before !== editor.state.tr.doc
const trICanChange = isThisTrApplied ? editor.state.tr : transaction
```

So is this right in vue-3 and 2?

### Which browser was this experienced in? Are any special extensions installed?

Latest Chrome and Edge, no more special extensions, just a starterkit.

### How can we reproduce the bug on our side?

just setup the ontransaction event in editor options and check the transacion.before doc and current doc

### What did you expect to happen?

The transaction need to be sure whether been applied to the current doc. it decide the whole logic about a custom extension. 

### Anything to add? (optional)

I had been a sponsor once and try to learn this great project

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by 44096267** [comment]
我这边有也遇到了相同的问题
