### ISSUE TITLE
cursor position

### ISSUE THREAD

**Issue by dingshaohua-cn** [ueberdosis/tiptap#3226]
### What’s the bug you are facing?

Why is the cursor lost when inserting content?
If I insert the cursor manually, why do I need to wait 500 milliseconds before it takes effect?
How to obtain the current cursor position. Is this api provided
```
editor.commands.insertContent('hello word');
setTimeout(()=>{
   editor.commands.focus();
},500)
```

### Which browser was this experienced in? Are any special extensions installed?

chrome v105
chrome v105
chrome v105

### How can we reproduce the bug on our side?

use insertContent api
use insertContent api
use insertContent api

### Can you provide a CodeSandbox?

no

### What did you expect to happen?

no

### Anything to add? (optional)

no

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by hivokas** [comment]
@dingshaohua-cn try using command chain instead: `editor.chain().insertContent('hello word').focus().run();`. Not sure it'll solve the problem for you, but at least you can try.

**Comment by dingshaohua-cn** [comment]
> @dingshaohua-cn try using command chain instead: `editor.chain().insertContent('hello word').focus().run();`. Not sure it'll solve the problem for you, but at least you can try.

I found the reason: the mode window caused the cursor to lose focus. How to solve this problem

**Comment by dingshaohua-cn** [comment]
im resolve this problom
