### ISSUE TITLE
.can() returns false for extension-list even when the command is runnable

### ISSUE THREAD

**Issue by C-Hess** [ueberdosis/tiptap#3229]
### What’s the bug you are facing?

The `.can()` command is a bit overzealous for the list extension. If the cursor/selection is on an existing list or heading element, the `can()` command returns false for `toggleBulletList()` and `toggleOrderedList()` commands. However, these commands are still executable, and can/will replace the current node with the new list node type selected.

### Which browser was this experienced in? Are any special extensions installed?

- Chrome
- Bullet lists
- Ordered lists
- Headings

### How can we reproduce the bug on our side?

1. Open the sandbox
    1. The sandbox is similar to the demo. The only difference is that the buttons are disabled if the `can()` command for the corresponding controls returns false
3. Create a bullet or ordered list with one item in the list
4. Note that the other list type and heading are disabled
5. Create another list item at the same level
6. Note that if the second list item in a list is selected with the cursor, they are enabled again
7. Nest the second list item with the tab key
8. Note that if two list items exist, but the cursor is on the first list item, **the header is disabled**  :confused:

### Can you provide a CodeSandbox?

https://codesandbox.io/s/frosty-goldwasser-visq8r?file=/src/App.tsx

### What did you expect to happen?

The `.can()` command should accurately reflect whether a command is possible to run given the editor state. In this case, because it is totally possible to switch between lists or convert a list to a heading, the `.can()` command should return true for all of the described cases above.

### Anything to add? (optional)

It's possible that the heading being disabled when the nested list item is selected is a separate issue, but I figured I'd leave it here in case it's the same. Otherwise, let me know, and I can open another issue

This issue is related to #3223, but that `pr` fixes issues with the `.can()` command for marks

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by corbinschwartz** [comment]
Also running into this, repro steps in original description are accurate.

**Comment by Goodosky** [comment]
The same problem occurs with `setHeading()` and `toggleHeading()`

If the selection is on an existing list, both commands are runnable, but `.can()` returns false.

**Comment by gethari** [comment]
https://github.com/ueberdosis/tiptap/issues/4057#issuecomment-4021559366
