### ISSUE TITLE
General block dragging feature

### ISSUE THREAD

**Issue by holtwick** [ueberdosis/tiptap#323]
Dragging content blocks like headers, paragraphs, list items is a quite popular and useful feature. On hovering a block element a drag handle would show up to allow to initiate the drag operation.

**Question:** Is it planned to add such a feature to TipTap?

### Some examples

Recently the great nuclino project (based on Prosemirror as well) added such a feature: https://blog.nuclino.com/bringing-drag-and-drop-to-the-nuclino-editor

Notion is making heavy use of this feature: https://www.notion.so/

**Comment by philippkuehn** [comment]
There is a draggable option in the ProseMirror schema, so it's already possible. I added such a feature to Scrumpy a few weeks ago.
https://scrumpy.io/blog/copy-and-paste-all-your-tasks

**Comment by holtwick** [comment]
Great. So I guess you did it via the ideas presented here? https://discuss.prosemirror.net/t/make-only-part-of-a-nodeview-draggable/1145/5?u=holtwick

I just wondered if there would be a more general approach.

**Comment by holtwick** [comment]
I see, that makes sense. Thanks a lot!

**Comment by philippkuehn** [comment]
@holtwick you can define a drag handle with `data-drag-handle` inside your node view now.

**Comment by holtwick** [comment]
@philippkuehn This is awesome! Thanks!

I have also spent about a day to get this working and followed a different approach. My goal has been to make any block level element draggable by showing a drag handle in front of the line, as the mentioned examples of Nuclino and Notion do.

The problem with just setting e.g.  "paragraph" to `draggable` has been, that in Safari / WKWebKit the line was not selectable anymore. Therefore, I chose to create a plugin that uses a global drag handle and places it in front of the block the mouse is close to.

Video: https://holtwick.de/download/20190628-094238-drag.mov

I'll share my current code here in case you would like to proceed on this approach (it uses some custom DOM routines, but I think the general picture will become clear):

```js
import { absoluteRect, dom, removeNode } from '@/lib/utils/dom'
import { NodeSelection } from 'prosemirror-state'
import { serializeForClipboard } from 'prosemirror-view/src/clipboard'
import { Extension, Plugin } from 'tiptap'

export default class Drop extends Extension {

  get name() {
    return 'drop'
  }

  get plugins() {

    // function eventCoords(event) { return {left: event.clientX, top: event.clientY} }

    const brokenClipboardAPI = false // (browser.ie && browser.ie_version < 15) || (browser.ios && browser.webkit_version < 604)
    // const dragCopyModifier = false //  browser.mac ? "altKey" : "ctrlKey"

    function blockPosAtCoords(coords, view) {
      let pos = view.posAtCoords(coords)
      let node = view.domAtPos(pos.pos)

      node = node.node
      while (node && node.parentNode) {
        if (node.parentNode.classList.contains('ProseMirror')) { // todo
          break
        }
        node = node.parentNode
      }

      if (node && node.nodeType === 1) {
        let desc = view.docView.nearestDesc(node, true)
        if (!(!desc || desc === view.docView)) {
          return desc.posBefore
        }
      }
      return null
    }

    function dragStart(e, view) {
      if (!e.dataTransfer) return

      let coords = { left: e.clientX + 50, top: e.clientY }
      let pos = blockPosAtCoords(coords, view)
      if (pos != null) {
        view.dispatch(view.state.tr.setSelection(NodeSelection.create(view.state.doc, pos)))

        let slice = view.state.selection.content()
        let { dom, text } = serializeForClipboard(view, slice)

        e.dataTransfer.clearData()
        e.dataTransfer.setData(brokenClipboardAPI ? 'Text' : 'text/html', dom.innerHTML)
        if (!brokenClipboardAPI) e.dataTransfer.setData('text/plain', text)

        view.dragging = { slice, move: true }
      }
    }

    let dropElement
    const WIDTH = 24

    return [
      new Plugin({
        view(editorView) {
          dropElement = dom('div', {
            draggable: 'true',
            class: 'noteDragHandle',
            ondragstart: e => dragStart(e, editorView),
          }, ['⠿'])
          document.body.appendChild(dropElement)
          return {
            update(view, prevState) {
            },
            destroy() {
              removeNode(dropElement)
              dropElement = null
            },
          }
        },
        props: {
          handleDOMEvents: {
            drop(view, event) {
              setTimeout(() => {
                let node = document.querySelector('.ProseMirror-hideselection')
                if (node) {
                  node.classList.remove('ProseMirror-hideselection')
                }
              }, 50)
            },
            mousemove(view, event) {
              let coords = { left: event.clientX + WIDTH + 10, top: event.clientY }
              let pos = view.posAtCoords(coords)
              let node = view.domAtPos(pos.pos)

              node = node.node
              while (node && node.parentNode) {
                if (node.parentNode.classList.contains('ProseMirror')) { // todo
                  break
                }
                node = node.parentNode
              }

              let rect = absoluteRect(node)
              let win = node.ownerDocument.defaultView
              rect.top += win.pageYOffset
              rect.left += win.pageXOffset
              rect.width = WIDTH + 'px'

              dropElement.style.left = -WIDTH + rect.left + 'px'
              dropElement.style.top = rect.top + 'px'
            },
          },
        },
      }),
    ]
  }

}
```

Thanks for all the great work!

**Comment by philippkuehn** [comment]
@holtwick this looks great. thanks for sharing!

**Comment by jonasdumas** [comment]
Hi @holtwick 
Thanks for sharing your module. Very interesting. Would it be possible to share also your DOM routines (absoluteRect, dom, removeNode )?

**Comment by holtwick** [comment]
Sure, `absoluteRect` just returns some real world position info of an element:

```js
export function createRect(rect) {
  if (rect == null) {
    return null
  }
  let newRect = {
    left: rect.left + document.body.scrollLeft,
    top: rect.top + document.body.scrollTop,
    width: rect.width,
    height: rect.height,
    bottom: 0,
    right: 0,
  }
  newRect.bottom = newRect.top + newRect.height
  newRect.right = newRect.left + newRect.width 
  return newRect
}

export function absoluteRect(element: HTMLElement): ?ClientRect {
  return createRect(element.getBoundingClientRect())
}
```

`removeNode` is a helper to remove a DOM node:

```js
export function removeNode(node) {
  if (node && node.parentNode) {
    node.parentNode.removeChild(node)
  }
}
```

And `dom` is just an abstraction for the follwing code:

```js
let dropElement = document.createElement('div')
dropElement.setAttribute('draggable', 'true')
dropElement.className = 'noteDragHandle'
dropElement.addEventListener(e => dragStart(e, editorView))
dropElement.textContent = '⠿'
```

Hope this helps.

**Comment by jonasdumas** [comment]
Thank you so much ! Very helpful!

**Comment by RomainLanz** [comment]
Hey all 👋 

I didn't really get how to allow to drag all elements (also the one comming from `tiptap-extensions`) ?

**Comment by bdbch** [comment]
@RomainLanz see here:
https://tiptap.dev/guide/node-views/examples#drag-handles

**Comment by mcnaveen** [comment]
Hi @holtwick 
Can https://github.com/ueberdosis/tiptap/issues/323#issuecomment-506637799 work with BulletList? and TaskItem?

I have trouble integrating this with notitap by @sereneinserenade because he created something called dBlock. Which takes the whole ul as a block

**Comment by holtwick** [comment]
@mcnaveen sorry, I don't know. This is very old code and I currently don't use it myself anymore. Might be best to refer to https://tiptap.dev/guide/node-views/examples#drag-handles for drag drop related things.

**Comment by BurneoDanny** [comment]
Not working. please give more context

**Comment by cmayoracurzio** [comment]
@qantrepreneur thanks a lot for sharing this! Would you mind adding some more context or publishing a simple example repo? Can't seem to make it work...

**Comment by cmayoracurzio** [comment]
@arielweinberger @qantrepreneur thanks both! Turns out I was messing something else up.

**Comment by NiclasDev63** [comment]
Even though I am still quite new to tiptap/prosemirror, I have managed to develope a working drag handle based on the drag handle from https://github.com/steven-tey/novel. However, unlike with the drag handle in novel, it is possible to drag single list items or whole lists through the editor as expected. Furthermore, it is also possible to select several nodes of different types and drag them as well. I look forward to your feedback and any suggestions for improvement.
I have uploaded the drag handle as an [extension](https://www.npmjs.com/package/tiptap-extension-global-drag-handle) to npm and of course opensourced it on [github](https://github.com/NiclasDev63/tiptap-extension-global-drag-handle).

**Comment by rvishruth** [comment]
<p> I'm having some trouble getting @qantrepreneur solution to work in my project. When I add the DragHandles as an extension to my editor, it doesn't work as expected. <p>

- The drag handle stays at opacity-0
- The drag handle stays stuck to the top left

Wondering if anyone else had similar problems/if my implementation is incorrect. 


https://github.com/ueberdosis/tiptap/assets/79176273/7f610113-1f7b-49c8-bccb-ff7c99097af0


```
import type { NextPage } from "next";
import { useEditor, EditorContent } from '@tiptap/react'
import Document from '@tiptap/extension-document'
import Text from '@tiptap/extension-text'
import Paragraph from '@tiptap/extension-paragraph'
import { useRef } from 'react'
import History from '@tiptap/extension-history'
import DragHandles from '~/components/project/DragHandles'


const ProjectEditor: NextPage<unknown> = () => {
  return (
    <Tiptap />
  )
}

export default ProjectEditor;


const Tiptap = () => {
  const editor = useEditor({
    extensions: [
      Document,
      Text,
      Paragraph,
      History.configure({
        depth: 100,
        newGroupDelay: 100,
      }),
      DragHandles,
    ],
    content: `<p>Paragraph 1</p>
              <p>Paragraph 2</p>
              <p>Paragraph 3</p>
              <p>Paragraph 4</p>`,
  })
  const editorRef = useRef<HTMLDivElement | null>(null)

  return (
    <div className="flex flex-col items-center">
        <EditorContent className="max-w-[580px] w-full flex-1 p-4 m-4" editor={editor} ref={editorRef} />
    </div>
  )
}
```

**Comment by NiclasDev63** [comment]
> I'm having some trouble getting @qantrepreneur solution to work in my project. When I add the DragHandles as an extension to my editor, it doesn't work as expected.
> 
> * The drag handle stays at opacity-0
> * The drag handle stays stuck to the top left
> 
> Wondering if anyone else had similar problems/if my implementation is incorrect.
> 
>  tiptap_draggable_recording.mp4 
> ```
> import type { NextPage } from "next";
> import { useEditor, EditorContent } from '@tiptap/react'
> import Document from '@tiptap/extension-document'
> import Text from '@tiptap/extension-text'
> import Paragraph from '@tiptap/extension-paragraph'
> import { useRef } from 'react'
> import History from '@tiptap/extension-history'
> import DragHandles from '~/components/project/DragHandles'
> 
> 
> const ProjectEditor: NextPage<unknown> = () => {
>   return (
>     <Tiptap />
>   )
> }
> 
> export default ProjectEditor;
> 
> 
> const Tiptap = () => {
>   const editor = useEditor({
>     extensions: [
>       Document,
>       Text,
>       Paragraph,
>       History.configure({
>         depth: 100,
>         newGroupDelay: 100,
>       }),
>       DragHandles,
>     ],
>     content: `<p>Paragraph 1</p>
>               <p>Paragraph 2</p>
>               <p>Paragraph 3</p>
>               <p>Paragraph 4</p>`,
>   })
>   const editorRef = useRef<HTMLDivElement | null>(null)
> 
>   return (
>     <div className="flex flex-col items-center">
>         <EditorContent className="max-w-[580px] w-full flex-1 p-4 m-4" editor={editor} ref={editorRef} />
>     </div>
>   )
> }
> ```

Have a look at my  [extension](https://www.npmjs.com/package/tiptap-extension-global-drag-handle)

**Comment by xiangshu233** [comment]
@NiclasDev63 Does this extension support vue3 projects?

**Comment by aydinvivik** [comment]
> If anyone stumbles upon this thread, I created a plugin based on the example created by @holtwick and Steven Tey's [novel.sh](https://github.com/steven-tey/novel/blob/main/packages/headless/src/extensions/drag-and-drop.tsx). It's build for React, but you can easily change it to work with regular HTML.
> 
> Demo: https://twitter.com/qantrepreneur/status/1757077900270903605
> 
> ```ts
> import { NodeSelection, Plugin } from "@tiptap/pm/state";
> // @ts-ignore
> import { EditorView, __serializeForClipboard } from "@tiptap/pm/view";
> import { Editor, Extension, ReactRenderer } from "@tiptap/react";
> import { GripVertical } from "lucide-react";
> 
> export interface DragHandleOptions {
>   editor: Editor;
> 
>   dragHandleSpeed: number;
>   dragHandlePosition:
>     | "follow"
>     | "center"
>     | "top"
>     | "bottom"
>     | ((nodeRect: DOMRect, handleRect: DOMRect) => number);
> 
>   createDragHandleHTMLElement: (editor: Editor) => HTMLElement;
> }
> 
> const DragHandleComponent: React.FC = () => {
>   return <GripVertical size={20} />;
> };
> 
> function createDragHandle(editor: Editor) {
>   const handle = new ReactRenderer(DragHandleComponent, {
>     editor,
>     className:
>       "fixed top-0 left-0 will-change-transform transition-opacity ease-in-out cursor-grab text-muted-foreground p-1 rounded opacity-0 hover:bg-accent",
>     attrs: {
>       tabindex: "-1",
>       draggable: "",
>       "data-drag-handle": "",
>     },
>     as: "button",
>   });
> 
>   const htmlElement = handle.element as HTMLElement;
> 
>   htmlElement.draggable = true;
> 
>   return htmlElement;
> }
> 
> function getElementAndNodePos(
>   view: EditorView,
>   coords: { left: number; top: number } = { left: 0, top: 0 },
> ): {
>   element: Element;
>   pos: number;
> } | null {
>   const bounds = view.dom.getBoundingClientRect();
> 
>   const nodePos = view.posAtCoords({
>     top: Math.min(bounds.bottom, Math.max(bounds.top + 1, coords.top)),
>     left: Math.min(bounds.right, Math.max(bounds.left + 1, coords.left)),
>   })?.inside;
> 
>   if (nodePos == null || nodePos < 0) {
>     return null;
>   }
> 
>   const node = view.nodeDOM(nodePos);
> 
>   if (!node || !(node instanceof Element)) {
>     return null;
>   }
> 
>   if (!node.parentElement?.matches(".ProseMirror")) {
>     return null;
>   }
> 
>   return {
>     element: node,
>     pos: nodePos,
>   };
> }
> 
> function DragHandlePlugin(options: DragHandleOptions) {
>   let handle: HTMLElement | null = null;
> 
>   let targetLeft: number;
>   let prevTop: number;
>   let targetTop: number;
>   let prevTime: number;
> 
>   requestAnimationFrame(function animation(time) {
>     const delta = time - prevTime;
> 
>     if (handle) {
>       const distanceTop = targetTop - prevTop;
>       const nextTop =
>         prevTop + distanceTop / (Math.max(options.dragHandleSpeed, 1) * delta);
> 
>       handle.style.transform = `translate3d(calc(-100% - 0.5rem + ${targetLeft}px), ${nextTop}px, 0)`;
>       prevTop = nextTop;
>     }
> 
>     prevTime = time;
> 
>     requestAnimationFrame(animation);
>   });
> 
>   const createDragStartHandler = (view: EditorView) => (event: DragEvent) => {
>     view.focus();
> 
>     if (!event.dataTransfer) {
>       return;
>     }
> 
>     const data = getElementAndNodePos(view, {
>       left: event.clientX,
>       top: event.clientY,
>     });
> 
>     if (!data) {
>       return;
>     }
> 
>     view.dispatch(
>       view.state.tr.setSelection(
>         NodeSelection.create(view.state.doc, data.pos),
>       ),
>     );
> 
>     const slice = view.state.selection.content();
>     const { dom, text } = __serializeForClipboard(view, slice);
> 
>     event.dataTransfer.clearData();
>     // eslint-disable-next-line no-param-reassign
>     event.dataTransfer.effectAllowed = "copyMove";
>     event.dataTransfer.setData("text/html", dom.innerHTML);
>     event.dataTransfer.setData("text/plain", text);
>     event.dataTransfer.setDragImage(data.element, 0, 0);
> 
>     // eslint-disable-next-line no-param-reassign
>     view.dragging = { slice, move: event.ctrlKey };
>   };
> 
>   const createMouseMoveHandler = (view: EditorView) => (event: MouseEvent) => {
>     if (!view.editable || !handle) {
>       return;
>     }
> 
>     const data = getElementAndNodePos(view, {
>       left: event.clientX,
>       top: event.clientY,
>     });
> 
>     if (!data) {
>       return;
>     }
> 
>     const rect = data.element.getBoundingClientRect();
>     const handleRect = handle.getBoundingClientRect();
> 
>     // Drag handle follows cursor
>     if (options.dragHandlePosition === "follow") {
>       targetTop = Math.min(
>         rect.bottom - handleRect.height,
>         Math.max(rect.top, event.clientY - handleRect.height / 2),
>       );
>     }
> 
>     // Drag handle centers on node
>     else if (options.dragHandlePosition === "center") {
>       targetTop = (rect.top + rect.bottom) / 2 - handleRect.height / 2;
>     }
> 
>     // Drag handle anchors to top of node
>     else if (options.dragHandlePosition === "top") {
>       targetTop = rect.top;
>     }
> 
>     // Drag handle anchors to bottom of node
>     else if (options.dragHandlePosition === "bottom") {
>       targetTop = rect.bottom - handleRect.height;
>     }
> 
>     // Custom drag handle position
>     else {
>       targetTop = options.dragHandlePosition(rect, handleRect);
>     }
> 
>     targetLeft = view.dom.getBoundingClientRect().left;
> 
>     showDragHandle();
>   };
> 
>   const createClickHandler = (view: EditorView) => (event: MouseEvent) => {
>     view.focus();
> 
>     view.dom.classList.remove("dragging");
> 
>     const data = getElementAndNodePos(view, {
>       left: event.clientX,
>       top: event.clientY,
>     });
> 
>     if (!data) {
>       return;
>     }
> 
>     view.dispatch(
>       view.state.tr.setSelection(
>         NodeSelection.create(view.state.doc, data.pos),
>       ),
>     );
>   };
> 
>   const hideDragHandle = () => handle?.classList.add("opacity-0");
>   const showDragHandle = () => handle?.classList.remove("opacity-0");
> 
>   return new Plugin({
>     view: (view) => {
>       const parent = view.dom.parentElement;
> 
>       handle = options.createDragHandleHTMLElement(options.editor);
> 
>       const dragStartHandler = createDragStartHandler(view);
>       const clickHandler = createClickHandler(view);
>       const mouseMoveHandler = createMouseMoveHandler(view);
> 
>       handle.addEventListener("dragstart", dragStartHandler);
>       handle.addEventListener("click", clickHandler);
>       parent?.addEventListener("mousemove", mouseMoveHandler);
> 
>       parent?.addEventListener("mouseleave", hideDragHandle);
>       document.addEventListener("scroll", hideDragHandle);
> 
>       const { left = 0, top = 0 } =
>         getElementAndNodePos(view)?.element.getBoundingClientRect() ?? {};
> 
>       targetLeft = left;
>       // eslint-disable-next-line no-multi-assign
>       prevTop = targetTop = top;
> 
>       parent?.appendChild(handle);
> 
>       return {
>         destroy: () => {
>           handle?.removeEventListener("dragstart", dragStartHandler);
>           handle?.removeEventListener("click", clickHandler);
>           parent?.removeEventListener("mousemove", mouseMoveHandler);
> 
>           parent?.removeEventListener("mouseleave", hideDragHandle);
>           document.removeEventListener("scroll", hideDragHandle);
> 
>           handle?.remove?.();
>           handle = null;
>         },
>       };
>     },
>     props: {
>       handleDOMEvents: {
>         keydown: () => hideDragHandle(),
>         dragstart: (view) => view.dom.classList.add("dragging"),
>         drop: (view) => view.dom.classList.remove("dragging"),
>         dragend: (view) => view.dom.classList.remove("dragging"),
>       },
>     },
>   });
> }
> 
> const DragHandles = Extension.create<Omit<DragHandleOptions, "editor">>({
>   name: "draghandles",
> 
>   addOptions() {
>     return {
>       dragHandleSpeed: 3,
>       dragHandlePosition: "follow",
> 
>       createDragHandleHTMLElement(editor: Editor) {
>         const handle = createDragHandle(editor);
> 
>         handle.draggable = true;
> 
>         return handle;
>       },
>     };
>   },
> 
>   addProseMirrorPlugins() {
>     return [
>       DragHandlePlugin({
>         editor: this.editor as Editor,
>         ...this.options,
>       }),
>     ];
>   },
> });
> 
> export default DragHandles;
> ```

Thanks for sharing, this is exactly what I was looking for, but I get flushSync error and I can't figure out why?

`draggable.tsx:21 Warning: flushSync was called from inside a lifecycle method. React cannot flush when React is already rendering. Consider moving this call to a scheduler task or micro task.`

![Screenshot 2024-05-08 at 13 32 36](https://github.com/ueberdosis/tiptap/assets/5020002/b564866b-f9bf-45f1-bcb9-a460098cc1af)

**Comment by aydinvivik** [comment]
@qantrepreneur thank you, I will try.
