### ISSUE TITLE
`CodeBlockLowlight.configure` not working when building a SvelteKit app

### ISSUE THREAD

**Issue by JustinyAhin** [ueberdosis/tiptap#3234]
### What’s the bug you are facing?

I have a small SvelteKit app when I use the `CodeBlockLowlight` from `@tiptap/extension-code-block-lowlight` to have a code editor with syntax highlighting. 

It works properly in the local environment, but when I build the app and runs it, I get this error `CodeBlockLowlight.configure is not a function`.

### Which browser was this experienced in? Are any special extensions installed?

Chrome: Version 107.0.5304.10

Here are the extensions/packages I'm using:

"@tiptap/core": "^2.0.0-beta.196",
"@tiptap/extension-code-block-lowlight": "^2.0.0-beta.196",
"@tiptap/starter-kit": "^2.0.0-beta.196",
"highlight.js": "^11.6.0",
"lowlight": "^2.7.0"

### How can we reproduce the bug on our side?

Here is a minimal repository to reproduce the issue, https://github.com/JustinyAhin/codeblocklowlight.

The [`/lib/code-block.ts`](https://github.com/JustinyAhin/codeblocklowlight/blob/main/src/lib/code-block.ts) initialize the CodeBlockLowlight extensions:

```ts
import CodeBlockLowlight from '@tiptap/extension-code-block-lowlight';
import { lowlight } from 'lowlight/lib/core';

// Register languages.
import js from 'highlight.js/lib/languages/javascript';
import ts from 'highlight.js/lib/languages/typescript';

lowlight.registerLanguage('js', js);
lowlight.registerLanguage('ts', ts);

const CodeBlock = CodeBlockLowlight.configure({
	lowlight
});

export { CodeBlock };
```

which is used in the [`/lib/Editor.svelte`](https://github.com/JustinyAhin/codeblocklowlight/blob/main/src/lib/Editor.svelte) component:

```svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';

	import { Editor } from '@tiptap/core';
	import StarterKit from '@tiptap/starter-kit';

	import 'highlight.js/styles/github-dark.css';
	import { CodeBlock } from '$lib/code-block';

	let element: HTMLDivElement;
	let editor: Editor;

	onMount(() => {
		editor = new Editor({
			editorProps: {
				attributes: {
					class: 'prose prose-sm sm:prose lg:prose-lg xl:prose-2xl mx-auto focus:outline-none'
				}
			},
			element: element,
			extensions: [StarterKit, CodeBlock],
			content: `<pre><code class="language-typescript">console.log('Hello world!');</code></pre>`,
			onTransaction: () => {
				editor = editor;
			}
		});
	});

	onDestroy(() => {
		if (editor) {
			editor.destroy();
		}
	});
</script>

<div class="editor">
	<div class="editor-content" bind:this={element} />
</div>
```

### What did you expect to happen?

I was expecting the extension to work in build mode the same way it works in dev.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by arily** [comment]
I ran into similar problem with nuxt3,
![image](https://user-images.githubusercontent.com/10007589/199520015-1cb8906d-84f7-4b94-ab4e-550bc8d1bb64.png)
and weird enough change it to following code fixed the problem.
![image](https://user-images.githubusercontent.com/10007589/199520119-787d0b02-97c0-4156-b868-39d503b25f78.png)
maybe eslint is on to something..

**Comment by arily** [comment]
also this fix applies to your reproduction.
![image](https://user-images.githubusercontent.com/10007589/199522174-b8296144-a111-4aff-8acb-c7b43ea64f05.png)

**Comment by joshjhans** [comment]
I am experiencing the same issue with all extensions in production; I am using React, TypeScript and Webpack 5 🤔

**Comment by joshjhans** [comment]
> I am experiencing the same issue with all extensions in production; I am using React, TypeScript, Webpack 5, and tiptap beta 219 🤔

This may be the same issue?

https://stackoverflow.com/questions/74863927/nuxt-3-tiptap-2-0-0-beta-209-ssg-nuxt-generate-creates-error-starterkit-c
