### ISSUE TITLE
Error in consuming `handleDOMEvents` in the latest package

### ISSUE THREAD

**Issue by gethari** [ueberdosis/tiptap#3236]
### What’s the bug you are facing?

Here I have a `prosemirror-plugin` something like this....
```ts
return new Plugin({
props:{
    handleDOMEvents: {
        paste(view, event) {
          console.log("----on pasted something ---");
        }}
})
```

When compiling the app I get this error

```txt
 Property 'paste' is incompatible with index signature.
    Type '(view: EditorView, event: ClipboardEvent) => false' is not assignable to type '(view: EditorView, event: Event) => boolean | void'.
      Types of parameters 'event' and 'event' are incompatible.
        Property 'clipboardData' is missing in type 'Event' but required in type 'ClipboardEvent'.
```

![image](https://user-images.githubusercontent.com/20477956/192269333-4d74c42c-faf4-48fd-808a-e853f2d5b0d7.png)

On changing the TYPE of `paste` method's 2nd argument to `Event` the error is gone, but the code is not right. When pasting when we hover on the event without the TYPE, it shows `Clipboard Event`

![image](https://user-images.githubusercontent.com/20477956/192269553-624108ed-0e29-4b7c-8cc3-4150164e6ee5.png)

```ts
 paste(view, event:Event)
```

## Suggested Solution

- I noticed that this problem is solved in [1.26.4](https://github.com/ProseMirror/prosemirror-view/blob/master/CHANGELOG.md#1264-2022-07-04) version and I guess updating the dependency in the core package should solve the problem.
- The current `@tiptap/core` is dependent on `"prosemirror-view": "1.26.2"`

### Which browser was this experienced in? Are any special extensions installed?

Google Chrome (Version 105.0.5195.127)

### How can we reproduce the bug on our side?

-

### What did you expect to happen?

Expect the typescript compilation error to be gone

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
I created a PR upgrading Prosemirror to the most recent packages, see #3237 

I'll get it merged when the tests are done - so you could potentially reverify this issue again when my PR is merged.

**Comment by gethari** [comment]
@bdbch thank you so much for the quick response 🔥 . I'll keep an eye for the PR, and will try to fetch latest the moment it gets merged

**Comment by bdbch** [comment]
@gethari we released a new version. Could you check it?

**Comment by gethari** [comment]
@bdbch I have updated all the packages to latest version & the problem seems to have resolved. Thank you 👍
