### ISSUE TITLE
Can't create two customs marks with textTransform 

### ISSUE THREAD

**Issue by juquetquentin** [ueberdosis/tiptap#3242]
### What’s the bug you are facing?

I tried to create two marks ("lowercase" and "uppercase") but when I tried to use the first one that i add in the "extensions" at editor initiation, both styles are applied and the second one override the first one by default.

### Which browser was this experienced in? Are any special extensions installed?

Chrome, React Dev Tools

### How can we reproduce the bug on our side?

Example : 
I have setup UpperCase and LowerCase extensions in this order ! I write some text in the editor then I select it and try to apply UpperCase. It gives me :

`<p> <span style="text-transform: uppercase; text-transform: lowercase">DDD</span></p>`

And so the lowercase will override the uppercase + I did not ask for any lowercase actions (set or unset).

### Can you provide a CodeSandbox?

https://codesandbox.io/s/test-editeur-live-forked-wv8nue?file=/src/components/Tiptap/TiptapEditor.js

https://wv8nue.csb.app/

### What did you expect to happen?

I expect only the style that I add in my function to be applied not another mark that haven't been called.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by juquetquentin** [comment]
As an addition I tried multiple solutions to keep those custom marks separated : 

1. Add unsetMark before adding my custom one in addCommands
chain()
          .unsetMark("lowercase")
          .setMark("textStyle", { textTransform: "uppercase" })
          .run()
2. Add unsetAllMarks before adding mu custom one in addCommands
           chain()
           .unsetAllMarks()
          .setMark("textStyle", { textTransform: "uppercase" })
          .run();
3. Add unsetMark after setting the right one.
chain()
          .setMark("textStyle", { textTransform: "uppercase" })
          .unsetMark("lowercase")
          .run()

**Comment by muhammadhendrahaqq** [comment]
hi did you found solution for this @juquetquentin ?
