### ISSUE TITLE
Pressing Enter in DetailsSummary make extra details inside current details in android

### ISSUE THREAD

**Issue by yuyuyukie** [ueberdosis/tiptap#3243]
### What’s the bug you are facing?

https://user-images.githubusercontent.com/64625150/192529664-013bc504-4564-40e7-8682-cb3bd44105be.mp4

## Devices
- Galaxy A21
- Rakuten Mini C330
## Browsers
- Android Chrome
- Android Edge
- **Android Firefox works as expected**
## Extensions
- @tiptap-pro/extension-details
- @tiptap-pro/extension-details-summary
- @tiptap-pro/extension-details-content

### How can we reproduce the bug on our side?

1. Go to https://tiptap.dev/api/nodes/details in android.
2. Put the cursor at DetailSummary and press enter key.

### What did you expect to happen?

Get out of Details and break line.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Thanks for reporting. I'll try to find some time to test this on an Android device.
