### ISSUE TITLE
auto format not applied when typing tokens backwords

### ISSUE THREAD

**Issue by deep-wonder** [ueberdosis/tiptap#3244]
### What problem are you facing?

auto-formatting is not applied when the user tries to make a word bold by typing closing tokens before the opening tokens.
the same behavior happens with other format tokens like italics, strike, etc.

https://user-images.githubusercontent.com/99749130/192553552-4090ac36-f1b9-4b34-ad1b-50787cdfb813.mp4

### What’s the solution you would like to see?

order of typing tokens should not matter while applying auto-formats.

**hello** should be converted to bold no matter what is the typing order of ** tokens.

### What alternatives did you consider?

our approach is to go with the default behavior of the library because we don't want to introduce custom code.

Thank You.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
This could be implemented in a future release but may not happen soon as I think it's not high priority. Will add it to the board though! Thanks 👍
