### ISSUE TITLE
HorizontalRule "---" shortcut error

### ISSUE THREAD

**Issue by iamcarbon** [ueberdosis/tiptap#3252]
### What’s the bug you are facing?

An undefined reference exception occurs when typing three dash (-) characters in a row.

<img width="939" alt="Screen Shot 2022-09-28 at 3 03 17 PM" src="https://user-images.githubusercontent.com/7537/192897046-65a76b7f-4058-4a2a-a0a6-6c8b4677c732.png">

### Which browser was this experienced in? Are any special extensions installed?

Chrome 105

### How can we reproduce the bug on our side?

Enable the HorizontalRule extension, and type three dashes in a row. The error occurs when typing the third dash. This also occurs when typing three underscores (_).

--- 

### What did you expect to happen?

A horizontal rule should be created.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
This issue should be resolved in the most recent release (beta.199) - could you test this again and reopen if needed? Thanks!
