### ISSUE TITLE
addCommands(Command) How to call ReactNodeViewRenderer(react component) props

### ISSUE THREAD

**Issue by dingshaohua-cn** [ueberdosis/tiptap#3253]
### What’s the bug you are facing?

```js
import Cmp from "./cmp";

export const Formula = Node.create({  

 addNodeView() {
    return ReactNodeViewRenderer(Cmp);
  },

  addCommands() {
    return {
      openFormula(){
        const cmd = (arg)=>{
          console.log(123);
          // How to call  Cmp props？
        }
        return cmd;
      }
    }
})
```

### Which browser was this experienced in? Are any special extensions installed?

no

### How can we reproduce the bug on our side?

no

### Can you provide a CodeSandbox?

no

### What did you expect to happen?

no

### Anything to add? (optional)

no

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by jiwanovski87** [comment]
@dingshaohua-com Have you found any way to access your cmp?
