### ISSUE TITLE
[extension-link]  error

### ISSUE THREAD

**Issue by xiaweiss** [ueberdosis/tiptap#3254]
### What’s the bug you are facing?

`extension-link`  version 2.0.0-beta.197

when content is a empty p, and some block after, throw an error.

content is:
```html
<p></p><img src="https://avatars.githubusercontent.com/u/17960084?s=40&v=4" />
```

error is:
<img width="673" alt="image" src="https://user-images.githubusercontent.com/17960084/192930953-14c2fb03-29f3-4b94-b55b-17d52d6b194e.png">

### Which browser was this experienced in? Are any special extensions installed?

Chrome

### How can we reproduce the bug on our side?

Just use image and link extension。content is:

```html
<p></p><img src="https://avatars.githubusercontent.com/u/17960084?s=40&v=4" />
```

### Can you provide a CodeSandbox?

https://codesandbox.io/s/priceless-lamarr-foe94z?file=/src/App.vue:546-624

### What did you expect to happen?

no error

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by iamcarbon** [comment]
Possibility related: https://github.com/ueberdosis/tiptap/issues/3252 (similar stacktrace)

**Comment by benkroeger** [comment]
the updates in extension-link (specifically in the autolink plugin) cause the same issue for me in combination with the `extension-mention`.

Basically, the `mention` dispatches the following transaction:

```js
editor
  .chain()
  .focus()
  .insertContentAt(range, [
  {
      type: 'mention',
      attrs: {id: 'foo', label: 'bar'},
  },
  {
      type: 'text',
      text: ' ',
  },
])
```

When adding `setMeta('preventAutolink', true)` to the transaction, the mention is processed as expected (without autolinking)

**Comment by joshtrotter** [comment]
I have the same (or related) issue. With the Link extension added to the tiptap editor I cannot insert emojis (through the Emoji extension) and I also cannot insert images (through a custom extension that is based on the official image extension). If I configure the  link extension with `autolink: false` then both emojis and images can be inserted as expected but obviously it would be nice to have autolinking enabled.

Trying to insert an emoji I get the following error
![image](https://user-images.githubusercontent.com/3528045/193153467-671955dc-0487-4e23-9ceb-8da6e6f09ce9.png)

Trying to insert an image I get a slightly different error
![image](https://user-images.githubusercontent.com/3528045/193153613-a7101c3f-6821-49ee-9c3e-322f530cb5c4.png)

@benkroeger your suggestion about using `setMeta('preventAutolink', true)` sounds like it could be perfect. Is there a way I can configure an extension to apply that to every transaction? I tried the following but didn't seem to work for me
```
Emoji.extend({
  onTransaction: (props) => {
    props.transaction.setMeta('preventAutoLink', true)
  }
})
```

**Comment by bdbch** [comment]
Thanks. I'm looking into this issue right now. Seems like the autolinking feature is triggering false here.

**Comment by bdbch** [comment]
This should be solved with the most recent version (beta.199) - could you test this again and reopen if the issue still happens for you?

**Comment by xiaweiss** [comment]
It works fine. Thank you fix it so fast 🎉🎉🎉

**Comment by joshtrotter** [comment]
Works perfect. Tested with both Emoji and Image extensions and it's working great. Thanks so much 🙏
