### ISSUE TITLE
Unexptected cursor behaviour on custom TaskItem

### ISSUE THREAD

**Issue by borisdaenen** [ueberdosis/tiptap#3257]
### What’s the bug you are facing?

First of all, thanks for an amazing project. Very excited to implement this into my app!

I'm using a custom React component based on the TaskItem extension.
When I use the assigned keyboard shortcuts I get the expected result but the cursor isn't following into newly created nodes (see video below).

I'm basing my custom extension off the standard TaskItem extension but return this for addNodeView() instead:
`  addNodeView() {
    return ReactNodeViewRenderer(CustomAssignToComponent);
  }`

[https://codesandbox.io/s/condescending-roentgen-9qhb23?file=/src/App.js](url)

https://user-images.githubusercontent.com/14828061/193038744-bd04b1a3-27f2-49e4-bcbb-f93a8243bd22.mov

### Which browser was this experienced in? Are any special extensions installed?

Chrome 105

### How can we reproduce the bug on our side?

When I press any of the keyboard shortcuts ("Tab", "Shift-Tab" or "Enter") the cursor jumps to an unexpected position.

### Can you provide a CodeSandbox?

[https://codesandbox.io/s/condescending-roentgen-9qhb23?file=/src/App.js](url)

### What did you expect to happen?

I exptected the cursor to follow the behaviour of the standard TaskItem extension

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by vgrbr** [comment]
I have the same issue - If you downgrade @tiptap/react to .beta-194 it will work but you will get some console errors with flushSync.

From what I can see issue is with queueMicrotask introduced with: https://github.com/ueberdosis/tiptap/pull/3188/files
