### ISSUE TITLE
How to get attributes  of cursor position node?

### ISSUE THREAD

**Issue by ageeye-cn** [ueberdosis/tiptap#326]
I can only get the attributes of mark through getMarkAttrs，How to get node attributes？

**Comment by fibigerg** [comment]
+1, need help on this too, thanks

**Comment by gambolputty** [comment]
For example like this as a computed getter:

```js
  computed: {
    selectedNodeAttrs () {
      const { node } = this.editor.state.selection
      if (node && node.type.name === 'my_node_name') {
        return node.attrs
      }
      return null
    }
  },
```

**Comment by owardlaw** [comment]
Currently writing this rn

**Comment by Jayraj-R** [comment]
I want to get the current  node type(Paragraph, heading, table cell) on the basis of cursor position. Is that possible?

**Comment by alvarocastro** [comment]
> Currently writing some code to get all marks at a specific position (and or cursor position) will provide code if this is still needed

Hi, I would love to see how to do this since I need it for something I'm doing.
