### ISSUE TITLE
HardBreak with Link extension is not working (Vue 3)

### ISSUE THREAD

**Issue by bornemisza** [ueberdosis/tiptap#3263]
### What’s the bug you are facing?

In Vue 3 app using the StarterKit and Link extensions, trying to do a hard break. Nothing happens and got an error in console.
By default the editor's content is empty and when doing hard break, nothing happens. After typing one letter at least, everything works as expected.

The error I got  in console relates to the Link extension and linkify. If I remove the Link extension from config, then works perfectly the hard break.

Console error:
`Firefox: Uncaught TypeError: str is undefined (linkify.module.js:2036:17)`
`Chrome & Edge: Uncaught TypeError: Cannot read properties of undefined (reading 'replace')`

### Which browser was this experienced in? Are any special extensions installed?

Firefox, Chrome, Edge. In private mode without browser extensions happens the same. Not browser related in my opinion.

### How can we reproduce the bug on our side?

Install packages:
        "@tiptap/extension-link": "^2.0.0-beta.197",
        "@tiptap/starter-kit": "^2.0.0-beta.180",
        "@tiptap/vue-3": "^2.0.0-beta.90"
        
Edtior config:

this.editor = new Editor({
    extensions: [
        StarterKit,
        Link,
    ],
    content: '',
});

In an empty editor try to make a hard break (on windows/linux : SHIFT + ENTER or CTRL + ENTER). after that try it when you type at least one letter. When you have text, then works properly. The problem appers only in an empty editor.

### What did you expect to happen?

To be able to make a hard break in an empty editor.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by C-Hess** [comment]
@bornemisza You'll want to update all of your dependencies to 2.0.0-beta.180 (or at a minimum, the link extension)

That should resolve the issue

**Comment by bornemisza** [comment]
@C-Hess Thank you. The 2.0.0-beta.199 version from everything solved the problem. My bad sorry for the issues
