### ISSUE TITLE
Streamline documentation regarding extensions

### ISSUE THREAD

**Issue by tantebootsy** [ueberdosis/tiptap#3268]
### What’s the URL to the page you’re sending feedback for?

https://tiptap.dev/api/extensions#list-of-provided-extensions

### What part of the documentation needs improvement?

The list mentioned on the page seems not to be in sync with https://tiptap.dev/extensions I guess this could be improved by simply replacing the list with the following text: "You can find officially maintained extensions on our [Extensions page](https://tiptap.dev/extensions)."

And on your page https://tiptap.dev/pricing I recommend to link the text "Unlimited use of Pro extensions" to the page https://tiptap.dev/extensions?pro=true so that one can easily see which extensions are shipped "on top" when beoming a sponsor. 

And maybe cou want to move the page https://tiptap.dev/extensions to the main menu ob the website. Currently it's a bit hidden in the documentation, where it doesn't belong to be exact. 

### What is helpful about that part?

i don't understand this question. Do you want to know here what's helpful regarding my proposal? Well the newbies find the capabilities of your awesome Editor more easily :)

### What is hard to understand, missing or misleading?

see desc. above

**Comment by tantebootsy** [comment]
meow?

**Comment by bdbch** [comment]
bump
