### ISSUE TITLE
Link Extension, always adding target="_blank" when instatiating editor.

### ISSUE THREAD

**Issue by MichalKrakow** [ueberdosis/tiptap#3276]
### What’s the bug you are facing?

As stated in title, not sure why its happening, but with link extension enabled, when theres a link without target attribute its added there anyway with _blank value in it.

### Which browser was this experienced in? Are any special extensions installed?

Chrome

### How can we reproduce the bug on our side?

open editor with:
```
<p>
<a href="/jobs/new">jobs</a>
</p>
```
Interesting enough this is not passed on with value - just rendered inside editor content element.

### What did you expect to happen?

It would be great to have some configuration allowing to discard this behaviour

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by dargmuesli** [comment]
Hey there, it seems that `target` and `rel` attributes are now set by default. To not set them, you must use `null`. This is currently not allowed by the typing, so I've submitted a PR to fix this.
