### ISSUE TITLE
Documentation is 404

### ISSUE THREAD

**Issue by vigenere23** [ueberdosis/tiptap#3286]
### What’s the bug you are facing?

When trying to access the documentation, it returns a 404 on every page. 

### Which browser was this experienced in? Are any special extensions installed?

Any (not related to the product but to the business site).

### How can we reproduce the bug on our side?

Main site -> Documentation
Google -> any direct link (ex: Installation with Vue 3)

Ex: https://tiptap.dev/introduction

### Can you provide a CodeSandbox?

not needed

### What did you expect to happen?

Showing the documentation.

### Anything to add? (optional)

Worked as of yesterday

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by vigenere23** [comment]
Already resolved, thanks!

**Comment by bdbch** [comment]
Sorry for that. We're currently doing some server updates and because of that the documentation wasn't available for a short time. Thanks! :)
