### ISSUE TITLE
editor.setEditable should be allowed to omit update.

### ISSUE THREAD

**Issue by ZaymonFC** [ueberdosis/tiptap#3289]
### What problem are you facing?

After https://github.com/ueberdosis/tiptap/pull/3140 some behaviour broke in my app because I wasn't expecting the command to trigger `onUpdate()`.

### What’s the solution you would like to see?

I'd like an optional parameter `emitUpdate` similar to the API provided by `editor.commands.setContent`:

https://github.com/ueberdosis/tiptap/blob/c729810767d374e4324e7f3ea84e2a65df18d622/packages/core/src/commands/setContent.ts#L21

The parameter would gate the event emission here:

https://github.com/ueberdosis/tiptap/blob/c729810767d374e4324e7f3ea84e2a65df18d622/packages/core/src/Editor.ts#L170-L173

### What alternatives did you consider?
Maybe there's a way to look at the `editor` state or `transaction` state in the `onUpdate({editor, transaction}) => ...` callback to know when the `isEditable` property has been flipped but I couldn't think of anything.

### Anything to add? (optional)

I'm happy to implement this PR if you all don't see any issues with this. Adding an optional parameter is a non-breaking change and the default value should be `true`.

**Comment by Rhys-T** [comment]
Would it make sense for `setEditable` to have its own event type, rather than triggering `update`? That way, node views could always be sure that they were correctly following the `isEditable` status of the editor, but unrelated uses of `onUpdate` wouldn't get triggered unnecessarily. (On the other hand, that would be a breaking change for any code that's currently using `onUpdate` to watch `isEditable`…)

**Comment by ZaymonFC** [comment]
@Rhys-T Breaking an existing contract for the added functionality probably isn't worth it. Consuming code won't be affected by the suggested change and it's lower touch. If there's a case for what you are suggesting I think it would warrant it's own issue and discussion.

**Comment by ZaymonFC** [comment]
Resolved with the merge of https://github.com/ueberdosis/tiptap/pull/3301
