### ISSUE TITLE
Ability to insert variables, similar to suggestions

### ISSUE THREAD

**Issue by moltar** [ueberdosis/tiptap#329]
**Is your feature request related to a problem? Please describe.**

Ability to insert pre-defined "variables" into the text.

E.g. user could type "today is {{ today }}" or "today is $today".

The editor would provide a list of suggested variables that are pre-defined.

The editor would also decorate these variables somehow once they are inserted.

The editor would allow to backspace and erase them.

**Describe the solution you'd like**

Similar to how suggestions work. But ability to use multiple characters, I guess. Like "{{" to begin suggestions.

**Describe alternatives you've considered**

N/A

**Additional context**

Integromat has a similar looking feature, but does not provide a suggest dropdown when typing. Can only use a mouse. http://take.ms/HSf3l

Zapier also has a similar one http://take.ms/NhODH

---

Thanks!

**Comment by moltar** [comment]
I think I have figured out a work-around:

https://codesandbox.io/embed/vue-template-y0o5z

Notably:

```scss
.mention::after {
  content: "}}";
}
```

and

```js
          new Mention({
            matcher: {
              char: "{{"
            },
```

Seems to work!

If you have any better suggestions, please let me know.

If you think this is the best way, then please feel free to close this issue.

Thanks!

**Comment by asseti6** [comment]
@moltar this is completely possible similiar to how you are using the Mention class already by defining your own custom node and plugin or use the suggestions plugin already available.  As a working example your node would look something like:

```
import { Node } from "tiptap";
import { replaceText } from "tiptap-commands";
import VariableSuggestionPlugin from "../plugins/CustomSuggestions";

export default class Variables extends Node {
  get name() {
    return "variable";
  }

  get defaultOptions() {
    return {
      matcher: {
        char: "%%",
        allowSpaces: false,
        startOfLine: false
      },
      variableClass: "variable",
      suggestionClass: "variable-suggestion"
    };
  }

  get schema() {
    return {
      attrs: {
        id: {},
        label: {}
      },
      group: "inline",
      inline: true,
      selectable: false,
      atom: true,
      toDOM: node => [
        "span",
        {
          class: this.options.variableClass,
          "data-variable-id": node.attrs.id
        },
        `${this.options.matcher.char}${node.attrs.label}`
      ],
      parseDOM: [
        {
          tag: "span[data-variable-id]",
          getAttrs: dom => {
            const id = dom.getAttribute("data-variable-id");
            const label = dom.innerText
              .split(this.options.matcher.char)
              .join("");
            return { id, label };
          }
        }
      ]
    };
  }

  commands({ schema }) {
    return attrs => replaceText(null, schema.nodes[this.name], attrs);
  }

  get plugins() {
    return [
      VariableSuggestionPlugin({
        command: ({ range, attrs, schema }) =>
          replaceText(range, schema.nodes[this.name], attrs),
        appendText: " ",
        matcher: this.options.matcher,
        items: this.options.items,
        onEnter: this.options.onEnter,
        onChange: this.options.onChange,
        onExit: this.options.onExit,
        onKeyDown: this.options.onKeyDown,
        onFilter: this.options.onFilter,
        suggestionClass: this.options.suggestionClass
      })
    ];
  }
}
```

Further if you want true variable previews you can find the tags in the html output and replace them (adding a tooltip with the original variable name) if you want to get a touch more complex.  We have added a click event to that tooltip to allow it to be modified again.

`this.editor.setContent(this.editor.getHTML().replace(new RegExp(`<span class=("|"([^"]*))variable("|([^"]*)").*?([^<]+)##${variable.name}</span>`, "g"), variable.value));`

Hope that gives you or anyone else some further direction.

**Comment by softwareguy74** [comment]
I have opened a feature request for something like this.  I would like to also suggest this be extended to be able to drag and drop from an arbitrary source component (such as a TreeView node, for example) and drop into specific location in text and have it result in a predefined "Suggestion".    This suggestion could then be rearranged by dragging it around with the mouse or deleted by clicking an "X" icon in it.

**Comment by asseti6** [comment]
@softwareguy74 suggestions in the above example can be set to draggable as is within the document.  As for dragging from outside the editor itself, we currently support that in our application by having the dropped variable simply insert the proper text into the editor.

**Comment by douglasg14b** [comment]
Oh boy that's quite a bit! 

Would be great to see this supported directly, so it can be simply configured.

**Comment by hendrikgaffo** [comment]
@asseti6 I have tried to get it working with your solution, but unfortunately without success. I know it has been quite a while since you replied to this issue, but could you give us a CodeSandbox or Repo URL with a working example? I would really appreciate it.

**Comment by bbbford** [comment]
Thanks for the guidance @asseti6 !

I have successfully implemented a variable solution where the user selects the variable by name, and tiptap displays the variable value inside of the document. The variable display within the document is reactive.

For those wanting to display the value in the document, I would suggest - rather than doing a replace as below:

`this.editor.setContent(this.editor.getHTML().replace(new RegExp(`<span class=("|"([^"]*))variable("|([^"]*)").*?([^<]+)%%${variable.name}</span>`, "g"), variable.value));`

Use your vuex store instead:

```
  // return a vue component
  // this can be an object or an imported component
  get view() {
    return {
      // there are some props available
      // `node` is a Prosemirror Node Object
      // `updateAttrs` is a function to update attributes defined in `schema`
      // `view` is the ProseMirror view instance
      // `options` is an array of your extension options
      // `selected` is a boolean which is true when selected
      // `editor` is a reference to the TipTap editor instance
      // `getPos` is a function to retrieve the start position of the node
      // `decorations` is an array of decorations around the node
      props: [ 'node', 'updateAttrs', 'view', 'options' ],
      computed: {
        label: {
          get() {
             // Get your label from vuex store here
          },
          set(label) {
            this.updateAttrs({
              label: label
            });
          }
        },
      },
      template: `
          <span :class="options.variableClass" :data-variable-id="node.attrs.id">{{label}}</span>
      `
    }
```

**Comment by hendrikgaffo** [comment]
@bbbford Very neat that you managed to get it working. Would you mind sharing a repo with us? That would be very, very helpful.

**Comment by hanspagel** [comment]
Thanks for the suggestion! And thanks for the code snippets. It’s added to the list of community extensions in #819 and we consider to add it to the core in tiptap v2 at some point. I’m closing this here for now. ✌️

**Comment by andrews05** [comment]
@hanspagel Is this still under consideration for v2 core?

**Comment by andrews05** [comment]
TinyMCE has an excellent Merge Tags feature: https://www.tiny.cloud/docs/tinymce/6/mergetags/
Note that the input/output works with the raw text form of the variable without requiring spans etc, so you don't have to do any transformations yourself like what @bbbford showed.
This is exactly what I want for TipTap.

**Comment by AlonMiz** [comment]
> TinyMCE has an excellent Merge Tags feature: https://www.tiny.cloud/docs/tinymce/6/mergetags/ Note that the input/output works with the raw text form of the variable without requiring spans etc, so you don't have to do any transformations yourself like what @bbbford showed. This is exactly what I'd want for TipTap - afaik it's not currently possible for an extension to achieve this?

i have the exact same requirement as the mergetags. probably would have to move to TinyMCE just for this. really liked tiptap though :/

**Comment by asseti6** [comment]
I am going to need this same feature again for a new project.  I'll update the original code as a node extension along with @bbbford's improvements and share it with the community.  @hanspagel what the best way to share that for review and for the community?

It will be towards the end of the month before I get to it.

**Comment by Acetyld** [comment]
@asseti6 any progres =) <3

**Comment by aehlke** [comment]
@hanspagel is there a way to recommend this for consideration again? thanks... sorry for the ping

**Comment by geekyayush** [comment]
Hey @asseti6 , sorry for pinging. Have you released the code for it?

**Comment by joaomirandas** [comment]
Hey folks, 

I spend too much time creating this extension, thats an must have for a kind of application that i made to tiptap, after so many hours i decided to share what i've created. cheers 🚀

[@talqui-oss/tiptap-extension-variable](https://www.npmjs.com/package/@talqui-oss/tiptap-extension-variable) 

![Captura de Tela 2024-01-11 às 02 09 40](https://github.com/ueberdosis/tiptap/assets/29043431/8b6cd4a5-94a0-48d7-812e-03cbf7ab3887)

**Comment by Haraldson** [comment]
@joaomirandas Getting atom nodes to appear in the editor content isn’t really that hard – did you solve how to define the data source/values and get the values reflected?

**Comment by Roberson-Andrade** [comment]
The best way I found to write variables and reflect the corresponding values was with node views. 

Basically I extended the mention extension passing my React component (could be in vue also, check the [docs](https://tiptap.dev/docs/editor/guide/node-views)):

```tsx
export const VariablesExtension = MentionExtension.extend({
  addNodeView() {
    return ReactNodeViewRenderer(Variable);
  },
  parseHTML() {
    return [
      {
        tag: "variable-component",
      },
    ];
  },
  renderHTML({ HTMLAttributes }) {
    return ["variable-component", mergeAttributes(HTMLAttributes)];
  },
});
```

I also get the variables inside the VariableList to avoid using the `items` from suggestion utils extension:
```tsx
export const VariablesList = forwardRef<
  ReturnType<NonNullable<SuggestionOptions["render"]>>,
  SuggestionProps<VariableOption>
>(({ command }, ref) => {
  const [selectedIndex, setSelectedIndex] = useState(0);
  const { data, isLoading } = useQuery({
    queryKey: ["variable-options"],
    queryFn: getVariables,
  });

// component code
```

Finally, through a `ReactContext` I provided the respective values for the variables and also controlled the parsing: 

```tsx
// Provider
export function VariablesContextProvider({
  children,
  parseVariables,
}: {
  children: React.ReactNode;
  parseVariables: boolean;
}) {
  const { data: values } = useQuery({
    queryKey: ["variable-values"],
    queryFn: getVariablesValues,
  });

  return (
    <VariablesContext.Provider value={{ values, parseVariables }}>
      {children}
    </VariablesContext.Provider>
  );

// VariableNode
export function Variable(props: NodeViewProps) {
  const { parseVariables, values } = useVariablesContext();
  return (
    <NodeViewWrapper className="inline w-fit">
      <span
        className={cn(
          "rounded bg-neutral-700 px-1 py-0.5 text-custom-primary-100"
        )}
      >
        {parseVariables
          ? values?.find((value) => value.id === props.node.attrs.id)?.value ??
            `variable not found`
          : `@${props.node.attrs.label}`}
      </span>
    </NodeViewWrapper>
  );
}
``` 

The result:
[tiptap-variables.webm](https://github.com/ueberdosis/tiptap/assets/78360479/efcd8abf-9924-4f7d-95ed-fd1432494d48)

Here is the [working example](https://github.com/Roberson-Andrade/tiptap-playground/tree/master/variables), I hope it helps someone.

**Comment by phillipmohr** [comment]
As someone being new to TipTap I found this very hard to implement gave up. Would be awesome if this would become an official extension.

**Comment by aoleksyshyn-spscommerce** [comment]
Hello, has anyone successfully implemented extension for merge tags?

**Comment by Lau08** [comment]
This worked for me, thanks to all your ideas:
````
import { ReactRenderer } from "@tiptap/react";
import tippy from "tippy.js";
import { MentionList } from "./MentionList.jsx";

const getFilteredMentions = (query, listOfPromptVariables) => {
  return listOfPromptVariables
    .filter((item) => item.toLowerCase().startsWith(query.toLowerCase()))
    .slice(0, 5);
};

const suggestion = ({ listOfPromptVariables }) => ({
  char: "{{",
  allowedPrefixes: null,
  decorationClass: "variable-suggestion",
  items: ({ query }) => {
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve(getFilteredMentions(query, listOfPromptVariables));
      }, 1000);
    });
  },

  render: () => {
    let reactRenderer;
    let popup;

    return {
      onStart: (props) => {
        reactRenderer = new ReactRenderer(MentionList, {
          props,
          editor: props.editor,
        });

        popup = tippy("body", {
          getReferenceClientRect: props.clientRect,
          appendTo: () => document.body,
          content: reactRenderer.element,
          showOnCreate: true,
          interactive: true,
          trigger: "manual",
          placement: "bottom-start",
        });
      },

      onUpdate(props) {
        reactRenderer.updateProps(props);

        popup[0].setProps({
          getReferenceClientRect: props.clientRect,
        });
      },

      onKeyDown(props) {
        if (props.event.key === "Escape") {
          popup[0].hide();

          return true;
        }

        return reactRenderer.ref?.onKeyDown(props);
      },

      onExit() {
        popup[0].destroy();
        reactRenderer.destroy();
      },
    };
  },
});

export default suggestion;

**Comment by Lau08** [comment]
This worked for me thanks to all the ideas:
suggestion.js
```
import { ReactRenderer } from "@tiptap/react";
import tippy from "tippy.js";
import { MentionList } from "./MentionList.jsx";

const getFilteredMentions = (query, listOfPromptVariables) => {
  return listOfPromptVariables
    .filter((item) => item.toLowerCase().startsWith(query.toLowerCase()))
    .slice(0, 5);
};

const suggestion = ({ listOfPromptVariables }) => ({
  char: "{{",
  allowedPrefixes: null,
  decorationClass: "variable-suggestion",
  items: ({ query }) => {
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve(getFilteredMentions(query, listOfPromptVariables));
      }, 1000);
    });
  },

  render: () => {
    let reactRenderer;
    let popup;

    return {
      onStart: (props) => {
        reactRenderer = new ReactRenderer(MentionList, {
          props,
          editor: props.editor,
        });

        popup = tippy("body", {
          getReferenceClientRect: props.clientRect,
          appendTo: () => document.body,
          content: reactRenderer.element,
          showOnCreate: true,
          interactive: true,
          trigger: "manual",
          placement: "bottom-start",
        });
      },

      onUpdate(props) {
        reactRenderer.updateProps(props);

        popup[0].setProps({
          getReferenceClientRect: props.clientRect,
        });
      },

      onKeyDown(props) {
        if (props.event.key === "Escape") {
          popup[0].hide();

          return true;
        }

        return reactRenderer.ref?.onKeyDown(props);
      },

      onExit() {
        popup[0].destroy();
        reactRenderer.destroy();
      },
    };
  },
});

export default suggestion;
````

Editor.jsx

`````
import React, { useEffect } from "react";
import { useEditor, EditorContent } from "@tiptap/react";
import Document from "@tiptap/extension-document";
import Paragraph from "@tiptap/extension-paragraph";
import Text from "@tiptap/extension-text";
import Mention from "@tiptap/extension-mention";
import suggestion from "./EditorUtils/suggestion";

export default ({
  listOfPromptVariables,
  editorContent,
  onChangeContent,
}) => {
  const editorPrompt = useEditor({
    editorProps: {
      attributes: {
        class: "focus:outline-none",
      },
    },
    extensions: [
      Document,
      Paragraph,
      Text,
      Mention.configure({
        HTMLAttributes: {
          class: "variables",
        },
        suggestion: suggestion({ listOfPromptVariables }),
      }),
    ],
    content: editorContent,
    onUpdate: ({ editor }) => {
      const content = editor.getText();
      onChangeContent(content);
    },
  });

  useEffect(() => {
    if (!editorPrompt) return;
    let { from, to } = editor?.state?.selection;
    editorPrompt?.commands.setContent(editorContent, false, {
      preserveWhitespace: "full",
    });
    editorPrompt.commands.setTextSelection({ from, to });
  }, [editorPrompt, editorContent]);

  return (
    <EditorContent
      editor={editorPrompt}
      className="h-full"
    />
  );
};

**Comment by Lau08** [comment]
`````
import React, { useEffect } from "react";
import { useEditor, EditorContent } from "@tiptap/react";
import Document from "@tiptap/extension-document";
import Paragraph from "@tiptap/extension-paragraph";
import Text from "@tiptap/extension-text";
import Mention from "@tiptap/extension-mention";
import suggestion from "./EditorUtils/suggestion";

export default ({
  listOfPromptVariables,
  editorContent,
  onChangeContent,
}) => {
  const editorPrompt = useEditor({
    editorProps: {
      attributes: {
        class: "focus:outline-none",
      },
    },
    extensions: [
      Document,
      Paragraph,
      Text,
      Mention.configure({
        HTMLAttributes: {
          class: "variables",
        },
        suggestion: suggestion({ listOfPromptVariables }),
      }),
    ],
    content: editorContent,
    onUpdate: ({ editor }) => {
      const content = editor.getText();
      onChangeContent(content);
    },
  });

  useEffect(() => {
    if (!editorPrompt) return;
    let { from, to } = editor?.state?.selection;
    editorPrompt?.commands.setContent(editorContent, false, {
      preserveWhitespace: "full",
    });
    editorPrompt.commands.setTextSelection({ from, to });
  }, [editorPrompt, editorContent]);

  return (
    <EditorContent
      editor={editorPrompt}
      className="h-full"
    />
  );
};

**Comment by jon-spaeth** [comment]
Was able to generate something for this with v0.dev

It generated the tiptap plugin and everything.

https://v0.dev/chat/b/4QZUpwA

**Comment by Lau08** [comment]
> @Lau08 thanks for sharing your solution! Could you please also share MentionList.jsx to see how it all works together?

Here is the MentionList.jsx:
```
import React, {
  useState,
  useEffect,
  forwardRef,
  useImperativeHandle,
} from "react";

export const MentionList = forwardRef((props, ref) => {
  const [selectedIndex, setSelectedIndex] = useState(0);

  const selectItem = (index) => {
    const item = props.items[index];

    if (item) {
      props.command({ id: item + "}}" });
    }
  };

  const upHandler = () => {
    setSelectedIndex(
      (selectedIndex + props.items.length - 1) % props.items.length
    );
  };

  const downHandler = () => {
    setSelectedIndex((selectedIndex + 1) % props.items.length);
  };

  const enterHandler = () => {
    selectItem(selectedIndex);
  };

  useEffect(() => setSelectedIndex(0), [props.items]);

  useImperativeHandle(ref, () => ({
    onKeyDown: ({ event }) => {
      if (event.key === "ArrowUp") {
        upHandler();
        return true;
      }

      if (event.key === "ArrowDown") {
        downHandler();
        return true;
      }

      if (event.key === "Enter") {
        enterHandler();
        return true;
      }

      return false;
    },
  }));

  return (
    <>
      {props.items.length && (
        <div className="items">
          {props.items.map((item, index) => (
            <button
              className={`item ${index === selectedIndex ? "is-selected" : ""}`}
              key={index}
              onClick={() => selectItem(index)}
            >
              {item}
            </button>
          ))}
          : <></>
        </div>
      )}
    </>
  );
});

export default MentionList;
