### ISSUE TITLE
v1 docs does not work

### ISSUE THREAD

**Issue by piotrekfracek** [ueberdosis/tiptap#3299]
### What’s the URL to the page you’re sending feedback for?

https://v1.tiptap.dev/docs

### What part of the documentation needs improvement?

Whole. Docs does not work.
![image](https://user-images.githubusercontent.com/6226713/195069900-12563b20-4968-418e-8ed7-04ebccf790bd.png)

### What is helpful about that part?
.

### What is hard to understand, missing or misleading?
.

**Comment by patrickbaber** [comment]
The documentation of version 1 is now online again: https://v1.tiptap.dev/docs/
