### ISSUE TITLE
Styles with page-break-before or after break content in setHTML

### ISSUE THREAD

**Issue by asseti6** [ueberdosis/tiptap#330]
**Describe the bug**
When using `setHTML` if the style property page-break-before exists, the editor will error out when calling create

**Steps to Reproduce**
1. Create HTML with the page-break-before property
2. use setContent on the editor with this HTML

**Expected behavior**
Style should be applied in style tag without the mark trying to call create on null

**Screenshots**
<img width="416" alt="Screen Shot 2019-05-27 at 5 46 25 PM" src="https://user-images.githubusercontent.com/11465950/58440343-65f59d80-80a7-11e9-929b-f32d9bd05df9.png">

**Comment by hanspagel** [comment]
I’m quoting the author of ProseMirror (the editor tiptap is based on) here:

> this is definitely not something that ProseMirror supports—it tries to be an editor of semantic content, and paging is very much a presentation issue that, in my opinion, should be separated from the content editing process.

👍
