### ISSUE TITLE
Trigger suggestion list when clicking on Mention

### ISSUE THREAD

**Issue by benjaminprojas** [ueberdosis/tiptap#3303]
### What problem are you facing?

When I use the Mention extension, for the most part it works great. However I want to be able to change the mention that was selected as soon as a user clicks on it. Here is an example of how far I have gotten: https://a.supportally.com/uBIIev

### What’s the solution you would like to see?

to be able to change the mention by clicking on the mention and re-triggering the suggestion.

### What alternatives did you consider?

None

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by benjaminprojas** [comment]
I should mention I'm using a Vue component to render the mention in the editor. So the trigger can easily come from there, but it would need to bubble up to re-trigger the suggestion.

**Comment by thegaoqi** [comment]
Hi, have you figured this issue? I'm running into the same problem here. Thanks!

> I should mention I'm using a Vue component to render the mention in the editor. So the trigger can easily come from there, but it would need to bubble up to re-trigger the suggestion.

**Comment by ThomasStock** [comment]
was this ever solved?

**Comment by benjaminprojas** [comment]
Unfortunately, I never found the solution for this, although I ended up going in a different direction.

**Comment by jrnxf** [comment]
Trying to do the exact same thing!
