### ISSUE TITLE
[Mention Extension] module @tiptap/suggestion can not be found

### ISSUE THREAD

**Issue by tigatujuhlima** [ueberdosis/tiptap#3309]
### What’s the bug you are facing?

I have updated tiptap mention extension from version 2.0.0-beta.102 to the most current version 2.0.0-beta.199 and I now have the problem, that 

```
 Cannot find module '@tiptap/suggestion'  from '../../node_modules/@tiptap/extension-mention/dist/tiptap-extension-mention.cjs.js'
```

I also used SuggestionOptions as typing in my code before, which I can't get anymore.

### Which browser was this experienced in? Are any special extensions installed?

Not in browser, but in the file `@tiptap/extension-mention/dist/tiptap-extension-mention.cjs.js` should be investigated whether the import from `@tiptap/suggestion` works.

### How can we reproduce the bug on our side?

Using the current version 2.0.0-beta.199 for extension-mention.

### What did you expect to happen?

No mentioned "cannot find module" message.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by eat-happy** [comment]
Since 2.0.0-beta.193 we marked the @tiptap/suggestion as a peer dependency. That means, you will need to install it manually.

**Comment by tigatujuhlima** [comment]
Thank you for the comment! will do
