### ISSUE TITLE
Not working with SWR and NextJS

### ISSUE THREAD

**Issue by sdanfa** [ueberdosis/tiptap#3315]
### What’s the bug you are facing?

Hi,
I tried using SWR and NextJS with tiptap but it's not working. I'm getting the error: Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:

Please help about this.

Thanks.

### Which browser was this experienced in? Are any special extensions installed?

Waterfox

### How can we reproduce the bug on our side?

import { useEffect, useState } from 'react';
import { useEditor, EditorContent } from '@tiptap/react'
import StarterKit from '@tiptap/starter-kit'
import useSWR from 'swr'

const fetcher = (url) => fetch(url).then((res) => res.json());

const url = 'https://jsonplaceholder.typicode.com/posts';

export const useGetPosts = () => {
  const { data, error } = useSWR(url, fetcher);

  return { data, error };
};

const myFunction = async (t, d) => {
  if (!d) {
    return <div>Loading...</div>;
  }
  d.map((post) => (
   t = t + "<Post post=" + post +  "key=" + post.id + "/>")
  );
const editor = useEditor({
  extensions: [
    StarterKit,
  ],
  content: t,
})

return (
  <EditorContent editor={editor} />
)
}

const Tiptap = () => {
  var myPosts = useState(null);
  const { data , error } = useGetPosts();
  useEffect(() => {
    myFunction(myPosts, data);
});
}

export default Tiptap;

### What did you expect to happen?

Showing the tiptap text editor box with the content from swr fetch.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by mmagnusen** [comment]
I've just copied and pasted your code into a text editor, it doesn't compile. I'm using Next.js and it works fine on my app. 
In your example, `myFunction` is being called but nothing is being returned from your `Tiptap` component. 

Can you try the example from the docs and see if that works for you? https://tiptap.dev/installation/react#3-create-a-new-component

```
import { useEditor, EditorContent } from '@tiptap/react'
import StarterKit from '@tiptap/starter-kit'

const Tiptap = () => {
  const editor = useEditor({
    extensions: [
      StarterKit,
    ],
    content: '<p>Hello World!</p>',
  })

  return (
    <EditorContent editor={editor} />
  )
}

export default Tiptap
```

**Comment by sdanfa** [comment]
> I've just copied and pasted your code into a text editor, it doesn't compile. I'm using Next.js and it works fine on my app. In your example, `myFunction` is being called but nothing is being returned from your `Tiptap` component.
> 
> Can you try the example from the docs and see if that works for you? https://tiptap.dev/installation/react#3-create-a-new-component
> 
> ```
> import { useEditor, EditorContent } from '@tiptap/react'
> import StarterKit from '@tiptap/starter-kit'
> 
> const Tiptap = () => {
>   const editor = useEditor({
>     extensions: [
>       StarterKit,
>     ],
>     content: '<p>Hello World!</p>',
>   })
> 
>   return (
>     <EditorContent editor={editor} />
>   )
> }
> 
> export default Tiptap
> ```

Sorry for taking time to reply. I'm using Gatsby server instead right now and everything is working fine. Thanks for your help though.
