### ISSUE TITLE
Code blocks are not highlighted properly

### ISSUE THREAD

**Issue by gethari** [ueberdosis/tiptap#3321]
### What’s the bug you are facing?

When we have some text in the editor, and now if we copy paste a codeblock , eg: a `JSON` like this

```json
{
  "type": "initial",
  "maximumWarning": "2mb",
  "maximumError": "5mb"
}
```
It is not highlighted properly.

### Which browser was this experienced in? Are any special extensions installed?

Google Chrome
106.0.5249.119 (Official Build) (64-bit), no extensions installed

### How can we reproduce the bug on our side?

- Navigate to [CodeBlockLowLight](https://tiptap.dev/api/nodes/code-block-lowlight) page
- Clear all the existing code
- Now paste the `JSON`, it will work now.
- Now clear everything again.
- Type some text , & try pasting the same json again & it looks like this now

![image](https://user-images.githubusercontent.com/20477956/196336584-495937b5-6e94-493e-8130-3c010ca10500.png)

### What did you expect to happen?

Expect the code block to be highlighted properly.

### Anything to add? (optional)

I tried to debug it, & I am able to see that in [this line](https://github.com/ueberdosis/tiptap/blob/2b69f344c713befecd4ec606df5e9ba680aa2ce8/packages/extension-code-block-lowlight/src/lowlight-plugin.ts#L72) the `decorations` are returned as `[]` & hence the highlight is not working properly.

_No response_

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by aliasliao** [comment]
Looks like it's the same reason as this one https://github.com/ueberdosis/tiptap/issues/3604.
