### ISSUE TITLE
Mention's renderLabel should support HTML

### ISSUE THREAD

**Issue by igilham** [ueberdosis/tiptap#3325]
### What problem are you facing?

When configuring Mention and adding a `renderLabel` function, the library assumes the only acceptable type to return is a string, E.g.

```typescript
Mention.configure({
        renderLabel: ({ node }) => `some string using fields of ${node}`
})
```

HTML in this return string is escaped to avoid breaking the page but it is possible to return HTML if you override the type system, E.g.

```typescript
Mention.configure({
        renderLabel: ({ node }) => {
    return ['span', {}, node.someProperty] as unknown as string;
  }
})
```

It looks like this works because the node list gets transformed downstream from the Mention extension but Mention does not technically support this workflow.

### What’s the solution you would like to see?

I'd like support for HTML in the renderLabel function. This may be as simple as adjusting the type signature or there may be more complexity to it than that.

### What alternatives did you consider?

Supporting inline HTML in a string might be possible but carries a lot of risk. This could break the page: `<span class="someClass">${node.someProperty}</span>`.

### Anything to add? (optional)

Context: I'm new to Tiptap and don't really know how any of this is supposed to work.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by moham96** [comment]
Facing the same issue here

**Comment by quentin-decre** [comment]
Same issue
