### ISSUE TITLE
[BUG] Unable to install because of @_ueberdosis/prosemirror-tables

### ISSUE THREAD

**Issue by mtdvlpr** [ueberdosis/tiptap#3326]
### What’s the bug you are facing?

I can't install @tiptap/extension-table because it depends on a wrongly configured package: @_ueberdosis/prosemirror-tables. It does not conform to the [npm guidelines for scope name](https://docs.npmjs.com/cli/v8/using-npm/scope#description), namely that a scope name is not allowed to start with an underscore. This is preventing me from installing your package!

### Which browser was this experienced in? Are any special extensions installed?

All Browsers

### How can we reproduce the bug on our side?

Try to install the package.

### Can you provide a CodeSandbox?

No

### What did you expect to happen?

Install correctly

### Anything to add? (optional)

It's been addressed directly on the repo, but it has not been dealt with:

https://github.com/ueberdosis/prosemirror-tables/commit/99b9cfff25cd30081ed33232e636575f0ae767a2#commitcomment-77256922

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by gapipro** [comment]
I am facing same issue. Please address this ASAP.

**Comment by bdbch** [comment]
I'll look into this, thanks for reporting.

**Comment by mtdvlpr** [comment]
Bump

**Comment by mtdvlpr** [comment]
@bdbch, did you look into it?

**Comment by bdbch** [comment]
Is this still the case in the most recent version? This should be resolved with the new @tiptap/pm package

**Comment by mtdvlpr** [comment]
I see the change now. Thank you!

**Comment by bdbch** [comment]
top! thanks for checking again @mtdvlpr
