### ISSUE TITLE
editor.getJSON() ouput err or setContent err

### ISSUE THREAD

**Issue by myface-wang** [ueberdosis/tiptap#3333]
### What’s the bug you are facing?

1、
![image](https://user-images.githubusercontent.com/13325359/196896948-ea10b105-c0a7-4170-a4f2-4f2d06b8bcb5.png)

2、outputJSON = editor.getJSON()

3、
![image](https://user-images.githubusercontent.com/13325359/196897034-6fdcc294-e0f8-4bad-8b33-d9fe63e7605c.png)

4、editor.commands.setContent(outputJSON)

5、
![image](https://user-images.githubusercontent.com/13325359/196897491-7e2eb29f-fbf0-4421-9f52-5d33cdaaf406.png)

### Which browser was this experienced in? Are any special extensions installed?

chrome and edge

### How can we reproduce the bug on our side?

use editor.commands.setContent()

{
    "type": "heading",
    "attrs": {
        "level": 1
    },
    "content": [
        {
            "type": "text",
            "text": "test"
        },
        {
            "type": "text",
            "marks": [
                {
                    "type": "highlight",
                    "attrs": {
                        "color": ""
                    }
                }
            ],
            "text": "over"
        },
        {
            "type": "text",
            "text": ""
        },
        {
            "type": "text",
            "marks": [
                {
                    "type": "highlight",
                    "attrs": {
                        "color": ""
                    }
                }
            ],
            "text": "here"
        },
        {
            "type": "text",
            "text": ","
        },
        {
            "type": "text",
            "marks": [
                {
                    "type": "highlight",
                    "attrs": {
                        "color": ""
                    }
                }
            ],
            "text": "is"
        },
        {
            "type": "text",
            "text": "ok ?"
        }
    ]
}

### What did you expect to happen?

not err

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by myface-wang** [comment]
the empty text shoud be " ", not ""

**Comment by svenadlung** [comment]
Hi @myface-wang, empty text fragments are forbidden in ProseMirror by default. I guess you should clear them or prevent trimming spaces.
