### ISSUE TITLE
Using `/` as the trigger character for the suggestion utility is broken

### ISSUE THREAD

**Issue by rfgamaral** [ueberdosis/tiptap#3335]
### What’s the bug you are facing?

We have been using a custom extension for multiple suggestion extensions in one of our products, and one of those extensions uses the `/` as the trigger character.

For instance, imagine a simple paragraph like `before/after|` (`|` denotes where the cursor is), and then you press `Enter`. You expect a new paragraph to be created, but it's not, because the suggestion utility is active, and catching the `Enter` key pressed event (when it shouldn't).

I'm not sure which change introduced this annoying bug for us, but the last working version for us was `beta.196`, we then bumped to `beta.199`, and this problem appeared. Already looked through the Git history but can't really understand which one could've caused this, but it's getting very annoying.

### Which browser was this experienced in? Are any special extensions installed?

Any browser. Yes, custom extension with `/` as the trigger character, but it's also a problem with the built-in `Mention` extension if the trigger character is changed to `/`.

### How can we reproduce the bug on our side?

* Load the the CodeSandbox below
* Place the cursor next to `before/after`
* Observe how you'll get a `No result` dropdown (you shouldn't)
    * This does not allow you to press `Enter`

### Can you provide a CodeSandbox?

* https://codesandbox.io/s/tiptap-issue-3335-hedls8

### What did you expect to happen?

The suggestion utility should not be triggered if there's a `/` somewhere, this is especially problematic if the last thing you typed was a URL, you won't be allowed to press `Enter` to create a new paragraph. This should work as before.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖 _(on behalf of Doist)_

**Comment by rfgamaral** [comment]
After some debugging, this issue was caused by https://github.com/ueberdosis/tiptap/pull/3239. As @akrolsmir mentioned in a comment there, I also believe that the default behaviour should be `[' ']`, as it used to be, and not `null`.

Based on the original issue (https://github.com/ueberdosis/tiptap/issues/3238), I don't see any reasoning in there for the default to be `null`, it looks like @Matrixbirds, could've simply set `allowedPrefixes: null` on their side to fix their issue.

@bdbch What do you think? Could #3239 be reverted?

**Comment by lucasfischer** [comment]
Ran into the same issue. Thank you for digging this up and providing a solution.

**Comment by bdbch** [comment]
I'll check #3239 and revert the necessary changes. Thanks for bringing it up!

**Comment by bdbch** [comment]
I reverted #3239 and will release a new version today

**Comment by bdbch** [comment]
Feel free to open this issue if you still experience this issue in the new version
