### ISSUE TITLE
Pressing enter in TaskList inserts new line instead of Mention item

### ISSUE THREAD

**Issue by ZizhengTai** [ueberdosis/tiptap#3339]
### What’s the bug you are facing?

In a Paragraph, Ordered List or Bullet List, if I start searching for mentions by typing "@", I can select a candidate by pressing the Enter key. However, when I do this inside a Task List, a new line is inserted instead (creating a new Task Item).

### Which browser was this experienced in? Are any special extensions installed?

Latest Chrome and Edge

### How can we reproduce the bug on our side?

See the description above.

### What did you expect to happen?

The Mention candidate is inserted upon Enter.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by ZizhengTai** [comment]
It turned out adding the `Mention` extension after `TaskList` fixed it.

**Comment by ashraful19** [comment]
@ZizhengTai thank you so much for the solution :-D this just solved my problem.

**Comment by austinlangdon** [comment]
> @zizhengtai thank you so much for the solution :-D this just solved my problem.

This worked, so thank you as well!

**Comment by austinlangdon** [comment]
> It turned out adding the `Mention` extension after `TaskList` fixed it.

This worked, so thank you as well!
