### ISSUE TITLE
LaTeX math typing support

### ISSUE THREAD

**Issue by wouter-deen** [ueberdosis/tiptap#3347]
### What problem are you facing?

There is currently no extension for adding text in LaTeX format, which can be helpful when typing formulas, equations, calculations etc.

### What’s the solution you would like to see?

A new extension for entering a LaTeX-formatted piece of plain text into the editor, possibly using Mathjax or something proprietary.

Edit: Mathquill seems like an even better solution, as this also makes for easier input.

### What alternatives did you consider?

Other WYSIWYG text editors that have support for this and Mathjax.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by ar-to** [comment]
found this for vuejs https://karlomikus.com/blog/create-latex-math-node-and-mark-for-tiptap-2 but I plan to try something similar in react soon. Definitely a must have support for LaTeX!
