### ISSUE TITLE
Error when trying to add an Image

### ISSUE THREAD

**Issue by maxbro-bdev** [ueberdosis/tiptap#3352]
### What’s the bug you are facing?

If the Link and the Image extension are implemented I get an Error if I try to add an Image.

![image](https://user-images.githubusercontent.com/113350492/197712382-1c61ade9-ce63-422f-86fe-61ae3df10b1b.png)

Its only throwing this error if I try to add the Image in a blank Line.
If I add it in a Line with Bold text it adds the Image.

Any suggestions how to fix this?

### Which browser was this experienced in? Are any special extensions installed?

Chrome, no

### How can we reproduce the bug on our side?

Dont know

### Can you provide a CodeSandbox?

no

### What did you expect to happen?

Just add the Image

### Anything to add? (optional)

Only happens, if the Link extension is implemented.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by maxbro-bdev** [comment]
I ve found out that the problem is something else:
I can add images, but only if its not a blank line.
Also if I press space in a blank line it throws this error:
![image](https://user-images.githubusercontent.com/113350492/197719491-7bfe1f90-63e6-4172-bec5-aa358565c3b0.png)


I think this also causes the imange problem.

**Comment by maxbro-bdev** [comment]
@gethari Thanks a lot for this quick anwser! It works! Spend hours on this, you saved my day.

**Comment by autumninflab** [comment]
It seems to be fixed in v2.0.0-beta.197.
https://github.com/ueberdosis/tiptap/releases/tag/v2.0.0-beta.197
