### ISSUE TITLE
Focus events for non editable Editors

### ISSUE THREAD

**Issue by codewitch** [ueberdosis/tiptap#3357]
### What problem are you facing?

When the editor is set to be readonly `editable: false` then the focus state seem to be turned off. `editor.isFocused` or `view.hasFocus` both return false. 

### What’s the solution you would like to see?

I would like to detect focus state even when the editor is read only because my custom comments extension relies on focus state to detect whether to open the comments `BubbleMenu`. My app has users with non editor permissions that will still need to leave and see comments. 

Is there a way for non editable tiptap editors to tap into the focus events? 

### What alternatives did you consider?

I have tried adding custom plugins to see if the prosemirror dom events for focus kick in and it doesn't seem to. Is the underlying issue a Prosemirror technical limitation?

```
  addProseMirrorPlugins() {
    return [
      new Plugin({
        props: {
          handleDOMEvents: {
            focus: (view, event: Event) => {
              console.log("focus from comment extension");
              return false;
            },
          },
      }),
    ];     
```

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by codewitch** [comment]
I just found this 
https://github.com/ueberdosis/tiptap/commit/01411f8462e8a36f96e56cdba227a9e5bb3e1812
linked to https://github.com/ueberdosis/tiptap/issues/2458

that explicitly removed what i need. lol.

I added 
```
  addProseMirrorPlugins() {
    return [
      new Plugin({
        props: {
          attributes: { tabindex: "0" },
        },
      }), 
```
to a custom extension and that seemed to do the trick!

**Comment by sharno** [comment]
@codewitch Having the same issue. I've tried to add the plugin in `useEditor` extensions but it doesn't seem to work. May I know how you passed the extension for the editor?
