### ISSUE TITLE
Conflict between YouTube Extension / Div Extension

### ISSUE THREAD

**Issue by rezaffm** [ueberdosis/tiptap#3363]
### What’s the URL to the page you’re sending feedback for?

https://tiptap.dev/api/nodes/youtube

### What part of the documentation needs improvement?

Hi,

I have been just playing around with the YouTube Extension and I like it a lot.

As I need to have sometimes some content wrapped in "div" and apply classes and styles to them, I have a very simply Custom Extension like:

```js
import { Node, mergeAttributes } from '@tiptap/core';

const Div = Node.create({
    name: 'div',
    addOptions() {
        return {
          HTMLAttributes: {},
        };
    },
    content: 'block*',
    group: 'block',
    defining: true,
    parseHTML() {
        return [
            {
              tag: 'div',
              }
            },
        ];
    },
    renderHTML({ HTMLAttributes }) {
        return ['div', mergeAttributes(this.options.HTMLAttributes, HTMLAttributes), 0];
    },
    addCommands() {
        return {
            setDiv: (attributes) => ({ commands }) => {
                return commands.wrapIn('div', attributes);
            },
       ...
    },
});

export default Div;
export { Div };

```

When I now use the YouTube Extension on reload, the content get "wrapped" in another div... which is not wanted :-)

So, it looks like

```html
<div><div data-youtube-video=""><iframe></iframe></div></div></div>
```

After some playing around with this, I realized I can prevent this by doing this in my Div Extension:

```js
    parseHTML() {
        return [
            {
              tag: 'div',
              getAttrs: node => {
                // Basically, if is has this attribute, we ignore this div.
                if (node.hasAttribute('data-youtube-video')) return false
                return true && null
              }
            },
        ];
    },
```

And now it works as expected.

To be frank, I don't know 100% understand why the YouTube Extension with is div and iframe got wrapped, I guess it is related to the fact that it's a custom node that matches the "parseHTML"  of my DivExtension.

### What is helpful about that part?

It's overall very well documented, nothing to complain about really.

### What is hard to understand, missing or misleading?

The fact that the extension could compete with a custom Div extension :-) or maybe other Divs. Maybe you could add a hint with a short solution?

### Anything to add? (optional)

TipTap is great!

**Comment by bdbch** [comment]
keep open

I'll see when I find time to look into this issue.
