### ISSUE TITLE
Cannot see getting started video

### ISSUE THREAD

**Issue by brightertools** [ueberdosis/tiptap#3364]
### What’s the URL to the page you’re sending feedback for?

https://tiptap.dev/screencasts/installation/install-tiptap-with-create-react-app

### What part of the documentation needs improvement?

I heard about TipTap via a Youtube video

Went to watch the getting started video for React, literaly the second click and I have to be a sponsor to see it, very annoying barrier for interested users.

### What is helpful about that part?

Well I cant see it?

### What is hard to understand, missing or misleading?

I just want to see the video as I am not sure what the "startup kit" is going to install into my app

### Anything to add? (optional)

I am sceptical in starting to use this if I going to get paywalls at every step if I need any help.

The getting started video should be available for new users? This is not unreasonable.

**Comment by bdbch** [comment]
Hey @brightertools

Screencasts are a pro user only feature, sorry for that. You can find information about what Tiptap is, how Tiptap is used or what individual packages install/do with the following links:

- [Introduction](https://tiptap.dev/introduction)
- [React Installation](https://tiptap.dev/installation/react)
- [StarterKit + installed packages](https://tiptap.dev/api/extensions/starter-kit)

Let me know if you need assistance with that.

**Comment by brightertools** [comment]
Thanks for the reply, went with Lexical in the end.
