### ISSUE TITLE
Memory leak in BubbleMenuView and FloatingMenuView

### ISSUE THREAD

**Issue by MihirGH** [ueberdosis/tiptap#3365]
### What’s the bug you are facing?

There's a memory leak in the extensions-bubble-menu and extensions-floating-menu package.
We are [setting up event listener for blur event on firstChild of tippy](https://github.com/ueberdosis/tiptap/blob/main/packages/extension-bubble-menu/src/bubble-menu-plugin.ts#L152) but we are not removing that listener on destroy and hence it is retained even after editor is unmounted. 

Relevant snapshot traces:
![image](https://user-images.githubusercontent.com/48630359/198647094-625f8285-f055-419f-b8f6-e116783f2d1e.png)

### Which browser was this experienced in? Are any special extensions installed?

No, reproduced this in incognito tab of chrome without any extensions

### How can we reproduce the bug on our side?

Since the size of the leak depends on the closure chain I was not able to replicate it in isolation but adding a line to `removeEventListener` seemed to solve this particular leak for me. 

### What did you expect to happen?

Listener shouldn't be present after unmount of editor

### Anything to add? (optional)

Happy to raise the PR to fix this

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by gethari** [comment]
@bdbch would appreciate if this is getting merged 👍
