### ISSUE TITLE
`blockSeperator` in getTextBetween, will return double new line characters when call editor.getText()

### ISSUE THREAD

**Issue by Matrixbirds** [ueberdosis/tiptap#3369]
### What’s the bug you are facing?

I'd like to custom shortcut key with 'Enter'. When keypress `Enter`, it should splitBlock instead of using hardBreak to append <br/> in the current element: <p>.

### Which browser was this experienced in? Are any special extensions installed?

Chromium 107.0.5304.87 (Official Build) (arm64)
Offical Github repo. commit id: bbf0803a7722a5d1668559ff71c32515ba9bcfe7

Node version:
LTS
macOS
My setup scripts
```bash
npm install
npm run start
```

### How can we reproduce the bug on our side?

Step 1. Typing any character as below.
```javascript
// typing in content editor
abcdefg
```

Step 2. Run`splitBlock` by editor instance, then `<p>` tag in will be forked.
```javascript
editor.splitBlock({keepMarks: false}).focus().scrollIntoView().run();
```

Step 3. Keep typing any characters like this.
```javascript
// typing in content editor
abcdefg
hijkl
```

Step 4. Check the content editor html structure.
```html
<p>abcedfg</p>
<p>hijkl</p>
```
It looks like two paragraph element and it did correct when call `editor.getJSON()` then return value only contain two paragraph items.
But the `editor.getText()` will return `abcedfg\n\nhijkl`.

I'm digging in the implementation of getText. I find there is the code will serialize textNodes and it will add `blockSeparator = \n\n`. I don't know the blockSeparator works for what. But If we can modify assign as `\n`. Maybe it works for me. 

### What did you expect to happen?

The `getText` method should return single newline character whenever item has been splitBlock.
So In this case: `editor.getText` should return return `abcedfg\nhijkl`.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by HZZformGD** [comment]
i have the same confusion, why？
```
// typing in content editor
abcdefg
hijkl
// break 1
// break 2
// break 3
```
when  ```editor.getText()``` it will return ```abcedfg\n\nhijkl\n\n```
what i want is ```abcedfg\nhijkl\n\n\n```

**Comment by J-Yaleen** [comment]
any update？

**Comment by tecoad** [comment]
Same for me.

**Comment by hivokas** [comment]
@Matrixbirds @HZZformGD @J-Yaleen @tecoad you can use `editor.getText({ blockSeparator:'\n' });` to override default `blockSeparator`.

**Comment by hivokas** [comment]
I've submitted https://github.com/ueberdosis/tiptap/pull/5055 PR that tweaks `getTextBetween` to prepend `blockSeparator` to block node even if block node doesn't have any children (it means empty paragraphs won't be ignored like in @HZZformGD's comment).

@Matrixbirds @HZZformGD @J-Yaleen @tecoad

**Comment by luckrnx09** [comment]
> @Matrixbirds @HZZformGD @J-Yaleen @tecoad you can use `editor.getText({ blockSeparator: '\n' });` to override default `blockSeparator`.

It works for me! Thank you!
