### ISSUE TITLE
Link: Support `inputRules`

### ISSUE THREAD

**Issue by michalsnik** [ueberdosis/tiptap#337]
**Is your feature request related to a problem? Please describe.**
Currently `Link` node only supports pasting, that is when I paste link in the editor I get a nicely formatted <a> tag. It doesn't however work if I try to write the link myself, either directly or by using Markdown syntax.

**Describe the solution you'd like**
I would like to see two inputRules added in Link node:
- one that transforms typed URL automatically
- second that transforms markdown syntax to Link node (`[Example link](http://google.com)`)

**Additional context**
I tried to implement it myself in the project I'm working on, however it's not entirely clear for me if it's doable without additional changes in the underlying logic. Hence I'm asking for your help.

The first `inputRule` that I considered is as follows:
```js
const LINK_NODE_REGEX = /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._+~#=]{2,256}\.[a-zA-Z]{2,}\b([-a-zA-Z0-9@:%_+.~#?&//=]*)/;

// ...

inputRules({ type }) {
    return [
      markInputRule(LINK_NODE_REGEX, type, match => {
          return { src: match[0] };
      }),
      // second rule
    ]
}
```

I used `markInputRule` in order to just add mark around the matched text. This partially works, however after typing URL that matches the REGEX, I can't type more text - it immediately transforms the text to link and prevents me from finishing typing the proper URL. Adding white space at the end of the regex results in similar behavior. Do I miss something here?

For the second inputRule, I would use `nodeInputRule` to transform `[Text](http://google.com)` into Link node, however I don't see how this method would set innerText on the Link node. Is there a more proper method for achieving desired effect?

I'm not expecting you implementing all of it, guidance would be more than enough. I'm happy to contribute and help making this project even better :)

**Comment by MrBuggy** [comment]
Hi @michalsnik 
Kann you show us the whole code (also commands, schema etc.) and if possible the markup.
Cheers.

**Comment by rdlh** [comment]
Hi @michalsnik,

Could you please try with this regex:

```regexp
/https?:\/\/(www\.)?[-a-zA-Z0-9@:%._+~#=]{2,256}\.[a-zA-Z]{2,}\b([-a-zA-Z0-9@:%_+.~#?&//=]*)(\s|\n)$/g
```

The ending `$` is doing the trick in our own app code.

**Comment by Jevirs** [comment]
Hi @rdlh ,
I've tried your regex,but it does't work properly.
It only highlights the first letter when I input `space` to finish the url.
And it totally does't work when I input `enter`.
Would you please help with this matter. THX

![image](https://user-images.githubusercontent.com/8214869/82277344-2b70c900-99ba-11ea-8785-e0c9e3062ff5.png)

**Comment by dougalg** [comment]
For anyone else who comes here, I was able to get it to work with:

```
/https?:\/\/(www\.)?[-a-zA-Z0-9@:%._+~#=]{2,256}\.[a-zA-Z]{2,}\b([-a-zA-Z0-9@:%_+.~#?&//=]*)[\s\n]$/g
```

It seems like the final matching group must be empty, otherwise it will use the length of that group as the length of text to mark.

**Comment by hanspagel** [comment]
Thanks for sharing @rdlh and @dougalg! I’m closing this here for now, but plan to add this as an example to the new documentation. 🙌

**Comment by dougalg** [comment]
Thanks, @hanspagel ! Really looking forward to TipTap 2!

**Comment by 07akioni** [comment]
> Thanks for sharing @rdlh and @dougalg! I’m closing this here for now, but plan to add this as an example to the new documentation. 🙌

Has it been done?
