### ISSUE TITLE
Problem with History Plugin (Vue 3)

### ISSUE THREAD

**Issue by VictoriaAppDeveloper** [ueberdosis/tiptap#3372]
### What’s the bug you are facing?

An error occurs when connecting history to the tiptap editor. Error text:

`Uncaught (in promise) RangeError: Adding different instances of a keyed plugin (history$)`

### Which browser was this experienced in? Are any special extensions installed?

All browsers

### How can we reproduce the bug on our side?

Add `@tiptap/extension-history` by npm or yarn to project and run

### What did you expect to happen?

Working mechanism "undo" and "redo"

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Could you please add a Codesandbox as an example to your problem?

**Comment by VictoriaAppDeveloper** [comment]
I found the answer. Do not install `@tiptap/starter-kit`  and `@tiptap/extension-history` together
