### ISSUE TITLE
First line of the copied content is changing into heading if heading is already active in the editor

### ISSUE THREAD

**Issue by ashu12chi** [ueberdosis/tiptap#3373]
### What’s the bug you are facing?

When we are copy-pasting a paragraph in the editor and in the line where we are pasting the content any heading is already active then the first line of the pasted content becomes a heading automatically. The following GIF shows this:
![Animation](https://user-images.githubusercontent.com/45908393/199022649-c03f6c67-1c17-479e-86d5-c523760f22fb.gif)

All the marks are preserved even in the first line of the pasted content, the only issue is paragraph is converted into a heading.
![Animation1](https://user-images.githubusercontent.com/45908393/199023692-0062c9ee-7cd0-49c6-a9fd-857fa0a62cf0.gif)

### Which browser was this experienced in? Are any special extensions installed?

In all browsers.

### How can we reproduce the bug on our side?

It is visible here: https://tiptap.dev/examples/default

### Can you provide a CodeSandbox?

Not required

### What did you expect to happen?

If the first line of content is a paragraph it should remain a paragraph after pasting the content.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [x] Yes, I’m a sponsor. 💖

**Comment by C-Hess** [comment]
Does changing the "Heading" extension "defining" value to `false` fix this for you?

```typescript
extensions: [
  Heading.extend({ defining: false })
]
```

If so, I think this behavior is intentional (https://prosemirror.net/docs/ref/#model.NodeSpec.defining). However, note that changing `defining: false` means Headings are **NOT** automatically inserted when pasting in an empty paragraph

**Comment by ashu12chi** [comment]
Hi, 

Thanks for responding. Setting `defining` as `false` is not helping me. Can you suggest something else?

Thanks

**Comment by C-Hess** [comment]
Ahh, sorry, I think setting the Paragraph's "defining" option is actually what you'd want:
https://codesandbox.io/s/paragraph-should-replace-ciki0v?file=/src/App.tsx

Does that resolve this for you? Note that I don't know what other implications doing this might have though... (like pasting into elements like Bullet lists, tables, etc.)

**Comment by ashu12chi** [comment]
Hi, @C-Hess 
I tried setting `defining` as `true` in the Paragraph. It resolves the issue for me. I checked it is working fine with lists and tables as pointed out by you. I also tested for code-block and quotes, which are also working expectedly. 

Can you point out what else can go wrong?
