### ISSUE TITLE
Suggestion plugin doesn't respect `allowedPrefixes` in some situations if caret is placed near a node boundary

### ISSUE THREAD

**Issue by pedroalves0** [ueberdosis/tiptap#3375]
### What’s the bug you are facing?

Most of the time the prefixes set in the Suggestion plugin `allowedPrefixes` are correctly considered. However, if there are two adjacent nodes, the first ending with a disallowed prefix, and the editor caret is placed at the start of the right node, the plugin will only consider the caret node content and will disregard the disallowed prefix. The most relevant logic is defined here:

https://github.com/ueberdosis/tiptap/blob/main/packages/suggestion/src/findSuggestionMatch.ts#L34

This is problematic when the adjacent nodes are inline, which often happens when the nodes are divided due to having different marks. See the video below for an example of the issue happening.

### Which browser was this experienced in? Are any special extensions installed?

Any browser. The issue manifests even with only the mention and StartKit extension installed.

### How can we reproduce the bug on our side?

- Load the CodeSandbox below.
- Place the cursor at the end of the input, after the `/` char.
- Observe that the mentions dropdown is rendered (it shouldn't).

### Can you provide a CodeSandbox?

https://codesandbox.io/s/tiptap-suggestion-issue-bg4wn2

### What did you expect to happen?

The mentions dropdown is only rendered if the trigger character is preceded by an allowed prefixed. In the CodeSandbox example share above, the dropdown shouldn't be rendered as the character preceding the trigger character,`d`, is not a space.

### Anything to add? (optional)

https://user-images.githubusercontent.com/3800074/199060862-60097307-664e-4132-a93c-2f346f51723e.mp4

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖 _(on behalf of Doist)_

**Comment by rfgamaral** [comment]
@bdbch Can we reopen this issue and keep it open?

**Comment by bdbch** [comment]
Sure thing @rfgamaral
