### ISSUE TITLE
Copy Pasting a Retina (Mac) screenshot inside a Tiptap editor made it pasted in twice the size

### ISSUE THREAD

**Issue by cnicodeme** [ueberdosis/tiptap#3381]
### What’s the bug you are facing?

Hi,

If you make a screenshot on a Macbook with Retina, and paste it into Tiptap, the image displayed will be twice as big as the screenshot was done. (For instance when selecting a small area).

This makes sense since Retina is using the 2x size in pixel density, but it would be ideal to have Tiptap adjust the size based on the computer, if possible.

### Which browser was this experienced in? Are any special extensions installed?

No.

### How can we reproduce the bug on our side?

You'll need a Mac, but then selecting an area for a screenshot and pasting it on a Tiptap editor will show it.

### What did you expect to happen?

The size of the pasted image should be of the same size of the selected area for a screenshot.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
I don't think this is inside the scope of the image extension. As you said it's actually correct behavior since retina screenshots are adjusted to the pixel ratio. I'm not even sure if there is a valid way to determine if a picture was made from a different pixel density via base64. Feel free to reopen if you think this really should be done and you have a good idea how to solve it.

**Comment by cnicodeme** [comment]
Yeah, we tried on other editors, and found out that most of them did not handle the "retina" properly, but Figma does. This means there is a way to do this but I don't have a good solution right now.

It seems to be possible by calling this function

```javascript
function isRetinaDisplay() {
    if (window.matchMedia) {
        var mq = window.matchMedia("only screen and (min--moz-device-pixel-ratio: 1.3), only screen and (-o-min-device-pixel-ratio: 2.6/2), only screen and (-webkit-min-device-pixel-ratio: 1.3), only screen  and (min-device-pixel-ratio: 1.3), only screen and (min-resolution: 1.3dppx)");
        return (mq && mq.matches || (window.devicePixelRatio > 1)); 
    }
}
```

(source: [Stackoverflow](https://stackoverflow.com/a/19690464/330867))

And divide the height/width by two if it returns true.

_One issue that this might cause is that every images pasted would be half in size on a retina device_

I'm happy to run some tests but I haven't found where the paste of an image is handled.

**Comment by bdbch** [comment]
In that case you could resize the image via CSS yeah - but the base64 in the background would stay the doubled resolution. If that is fine for you that would work.

You'd just have to save this retina information inside the image somehow to keep this info packed with the retina image.

**Comment by philiparvidsson** [comment]
Could this be reopened? Adding width/height attributes to the image extension would fix this, or some other way to tag it when it is inserted as a node.

**Comment by cnicodeme** [comment]
Here's what I've implemented for [Fernand](https://getfernand.com).

You call `getRetinaDimensions` by passing the base64 content of the image, and you get back the width and height of the image, divided by two if it's using retina.

```javascript

const metersToInchMultiplies = 39.3701

// Retrieved from https://stackoverflow.com/a/37705109/330867
function stringAsUInt32BE (binString) {
    // This works only because we expect a 4 bytes string. A bigger one will fail.
    // Replace new DataView(Uint8Array.from(binString, c => c.charCodeAt(0)).buffer).getInt32(0, false)
    return binString.charCodeAt(0) * 16777216 + binString.charCodeAt(1) * 65536 + binString.charCodeAt(2) * 256 + binString.charCodeAt(3)
}

/**
 * This functions uses the pHYS property (http://www.libpng.org/pub/png/book/chapter11.html#png.ch11.div.8)
 * of a given PNG file (often used in paste, mostly at Apple's) and identifies the pixels density
 *
 * If it is superior than 144, it considers that it is Retina, and provides the width and height as half.
 *
 * @param Sring imgBase64
 * @returns Object
 */
function getRetinaDimensions (imgBase64) {
    const imgBin = window.atob(imgBase64)

    // Thanks to https://gist.github.com/jorilallo/23282a4887ab8ef166182c1dab1677f0 for the help!
    const physPos = imgBin.indexOf('pHYs')
    if (physPos > -1) {
        const phys = imgBin.substring(physPos + 4, physPos + 4 + 9)
        if (phys.charCodeAt(8) === 1) {
            // Unit is in metter, as expected!
            const xPpm = stringAsUInt32BE(phys.substring(0, 4))
            const xDpi = Math.round(xPpm / metersToInchMultiplies)

            const yPpm = stringAsUInt32BE(phys.substring(4, 8))
            const yDpi = Math.round(yPpm / metersToInchMultiplies)

            if (xDpi >= 144 && yDpi >= 144) {
                const ihdrPos = imgBin.substring(0, 30).indexOf('IHDR')
                if (ihdrPos > -1) {
                    const ihdr = imgBin.substring(ihdrPos + 4, ihdrPos + 4 + 8)
                    Uint8Array.from(ihdr, c => c.charCodeAt(0))
                    const width = stringAsUInt32BE(ihdr.substring(0, 4))
                    const height = stringAsUInt32BE(ihdr.substring(4, 8))
                    return {
                        width: Math.round(width / 2),
                        height: Math.round(height / 2)
                    }
                }
            }
        }
    }
    return null
}
```

You can load the images with the `paste` event like:

```javascript
paste (view, event) {
    const hasFiles =
        event.clipboardData &&
        event.clipboardData.files &&
        event.clipboardData.files.length

    if (!hasFiles) return

    const images = Array.from(event.clipboardData.files).filter(file => /image/i.test(file.type))
    if (images.length === 0) return

    event.preventDefault()
    event.stopImmediatePropagation()

    images.forEach(image => {
        const reader = new FileReader()

        reader.onload = readerEvent => {
            const options = {
                src: readerEvent.target.result
            }

            if (isRetina) {
                const dimensions = getRetinaDimensions(options.src.substring(options.src.indexOf(',') + 1))
                if (dimensions) {
                    options.width = dimensions.width
                }
            }

            // Do what you want here.
        }
        reader.readAsDataURL(image)
    })
}
```

Good luck :)
