### ISSUE TITLE
Issue with pasted text

### ISSUE THREAD

**Issue by MatteoGauthier** [ueberdosis/tiptap#3382]
### What’s the bug you are facing?

When I try to edit text that I pasted, I got some flickers

https://user-images.githubusercontent.com/32040951/199698836-02546f85-4e75-48b8-8ca3-9f37047ee0fb.mov

### Which browser was this experienced in? Are any special extensions installed?

Chrome 107

### How can we reproduce the bug on our side?

Copy this text : 
```

Acteur incontournable des métiers de l'ingénierie et travaux, le Groupe Ortec vous donne rendez-vous du 22 au 24 novembre pour sa campagne de recrutement en CDI, CDD, Stagiaires. 

Oil & Gas, Nucléaire, Aéronautique & Spatial, Défense, Chimie et Pharmacie, Industries lourdes, Automobile, Ferroviaire, Immobilier, Agroalimentaire, Administration & Collectivités : où que vous soyez, quel que soit votre secteur d'activité, nous avons des opportunités pour vous !
```

Paste here https://tiptap.dev/examples/default

### What did you expect to happen?

No flicker on text edit

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Hey @MatteoGauthier - could you try it again if it still happens with the latest release?

**Comment by MatteoGauthier** [comment]
> Hey @MatteoGauthier - could you try it again if it still happens with the latest release?

Just tried on the https://tiptap.dev/examples/default page and the issue still appearing
