### ISSUE TITLE
Link Extension: If openOnClick is false, open on Ctrl + LeftClick

### ISSUE THREAD

**Issue by maxbro-bdev** [ueberdosis/tiptap#3389]
### What problem are you facing?

I dont want to open Links on every Click. Instead I want to only open them if I press Ctrl and Click on it. Would be great to have this option.

### What’s the solution you would like to see?

Add a variable that the user can set.

### What alternatives did you consider?

I ve tried to set it manually on runtime, but I didnt get it to work.

### Anything to add? (optional)

Any suggestions for now, how I can make this work, so that Links only open on Ctrl + LeftClick (or when double clicking it would be fine aswell)?

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by ashu12chi** [comment]
Hi,

`openOnClick` is handled [here](https://github.com/ueberdosis/tiptap/blob/main/packages/extension-link/src/link.ts#L179). This basically uses a simple handler which is defined [here](https://github.com/ueberdosis/tiptap/blob/main/packages/extension-link/src/helpers/clickHandler.ts). You can [here](https://github.com/ueberdosis/tiptap/blob/main/packages/extension-link/src/helpers/clickHandler.ts#L17) add one more condition to check if ctrlKey is also pressed or not. (Make sure you handle it for both Windows and Mac)

Thanks

**Comment by schnuet** [comment]
I'll provide my workaround for anyone that is looking for it (like I was).

I extended the Link Mark and added the ctrl-click listener with a plugin, based on the functions that @ashu12chi linked. (Thanks for that.)

```javascript
import Link from "@tiptap/extension-link";
import { Plugin, PluginKey } from "@tiptap/pm/state";
import { getAttributes } from "@tiptap/core";

export const ControlClickLink = Link.extend({
  addOptions() {
    return {
      ...this.parent?.(),
      openOnClick: false
    };
  },
  addProseMirrorPlugins() {
    const plugins: Plugin[] = this.parent?.() || [];

    const ctrlClickHandler = new Plugin({
      key: new PluginKey("handleControlClick"),
      props: {
        handleClick(view, pos, event) {
          const attrs = getAttributes(view.state, "link");
          const link = (event.target as HTMLElement)?.closest("a");

          const keyPressed = event.ctrlKey || event.metaKey;

          if (keyPressed && link && attrs.href) {
            window.open(attrs.href, attrs.target);

            return true;
          }

          return false;
        }
      }
    });

    plugins.push(ctrlClickHandler);

    return plugins;
  }
});
```

Just use the extended Link in the places where you don't want the link to be clicked.
