### ISSUE TITLE
Custom renderText on editable node results in duplicate content copied to clipboard

### ISSUE THREAD

**Issue by mylesj** [ueberdosis/tiptap#3392]
### What’s the bug you are facing?

I've specified a custom `renderText` on an editable node expecting to be able to customise the serialisation that is shared with the tiptap clipboard handler, however copy-pasting the node as plain text results in the text selection being appended in addition to the output of `renderText`.

### Which browser was this experienced in? Are any special extensions installed?

N/A

### How can we reproduce the bug on our side?

 - Define a custom node with a "hole" for text content
 - Select a range of text inclusive of the custom node
 - Paste (Shift-Paste) the plain text content to another document

### Can you provide a CodeSandbox?

https://stackblitz.com/edit/react-ts-ysehpq?file=App.tsx

### What did you expect to happen?

I expected the output of `renderText` to be the only content copied in relation to the node.

### Anything to add? (optional)

I considered two ways of getting around this issue:
  - Extending the builtin text node in such away that I could nullify the `renderText` for text nodes contained within specific parents (this produced a number of other exotic outcomes and felt like a hack)
  - ProseMirror recently introduced a [`transformCopied`](https://prosemirror.net/docs/ref/#view.EditorProps.transformCopied) API option that lets you manipulate a slice of content before it is passed to the clipboard-serialiser. It seems that TipTap doesn't support this yet, as the [`clipboardTextSerializer` arguments are ignored](https://github.com/ueberdosis/tiptap/blob/8c6751f0c638effb22110b62b40a1632ea6867c9/packages/core/src/extensions/clipboardTextSerializer.ts#L15) in favour of a custom implementation.
  
This issue might be a feature request if supporting `transformCopied` is the better outcome.

### Video example

https://user-images.githubusercontent.com/2750352/200613826-dad46c17-79af-43b7-b4da-fb19fe528702.mov

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by mylesj** [comment]
Still an issue. Fix proposed.

**Comment by mylesj** [comment]
Still an issue. [Fix proposed](https://github.com/ueberdosis/tiptap/pull/3410).

**Comment by cvakodobro** [comment]
I'm experiencing the same issue, is there any update on this?

**Comment by msickpaler** [comment]
I am still having the same problem in 2024.
There seems to be no progress on this issue and PR, is the proposed PR not resolving the issue?

**Comment by mylesj** [comment]
I can also confirm that this is still an issue with `tiptap@2.2.4` and that the [proposed fix](https://github.com/ueberdosis/tiptap/pull/3410) still works. I don't know why this was never accepted but I've been using [patch-package](https://www.npmjs.com/package/patch-package) to address numerous issues locally. If it's any help, here is my patch file:

```diff
diff --git a/node_modules/@tiptap/core/dist/index.cjs b/node_modules/@tiptap/core/dist/index.cjs
index ffc83cc..03f31f7 100644
--- a/node_modules/@tiptap/core/dist/index.cjs
+++ b/node_modules/@tiptap/core/dist/index.cjs
@@ -1220,8 +1220,9 @@ function getTextBetween(startNode, range, options) {
                     range,
                 });
             }
+	    return false;
         }
-        else if (node.isText) {
+        if (node.isText) {
             text += (_a = node === null || node === void 0 ? void 0 : node.text) === null || _a === void 0 ? void 0 : _a.slice(Math.max(from, pos) - pos, to - pos); // eslint-disable-line
             separated = false;
         }
diff --git a/node_modules/@tiptap/core/dist/index.js b/node_modules/@tiptap/core/dist/index.js
index b6e061c..acf5a13 100644
--- a/node_modules/@tiptap/core/dist/index.js
+++ b/node_modules/@tiptap/core/dist/index.js
@@ -1216,8 +1216,9 @@ function getTextBetween(startNode, range, options) {
                     range,
                 });
             }
+	    return false;
         }
-        else if (node.isText) {
+        if (node.isText) {
             text += (_a = node === null || node === void 0 ? void 0 : node.text) === null || _a === void 0 ? void 0 : _a.slice(Math.max(from, pos) - pos, to - pos); // eslint-disable-line
             separated = false;
         }
```
