### ISSUE TITLE
`Mention` example - `popup` vs `popup[0]`

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [ueberdosis/tiptap#3403]
### What’s the URL to the page you’re sending feedback for?

https://tiptap.dev/api/nodes/mention#usage

### What part of the documentation needs improvement?

Vue example in `Usage` section

### What is helpful about that part?

Well, it's super useful, did my `mentions` functionality easy with that example, however...

### What is hard to understand, missing or misleading?

Example is using `popup[0].setProps(...)` and similar, it wasn't working for me though, I had to change it to `popup.setProps(...)` and I'm not really sure whether I did something wrong in my code or the provided example needs to be fixed

### Anything to add? (optional)

[reproduction in Vue 3 playground](https://t.ly/m2O1Q)  (works with `popup.setProps`, doesn't work with `popup[0].setProps`)

**Comment by bdbch** [comment]
bump
