### ISSUE TITLE
onCreate and similar extension event bindings do not have the correct typescript signature

### ISSUE THREAD

**Issue by L0laapk3** [ueberdosis/tiptap#3407]
### What’s the bug you are facing?

It appears that the `onCreate()`, etc bindings do not have the correct typescript signature, causing an error when trying to use the `editor` parameter supplied with the events.

If my understanding is correct, the missing declarations can be found in: https://github.com/ueberdosis/tiptap/blob/main/packages/core/src/Extension.ts#L180 . it looks like `onCreate` is not the only affected event.

### Which browser was this experienced in? Are any special extensions installed?

NA, core

### How can we reproduce the bug on our side?

`example.ts`: 
```js
Extension.create({
	onTransaction: ({ transaction }) => { // compiles as expected
		...
	},
	onCreate: ({ editor }) => { // ERROR TS2322: Type '({ editor }: { editor: any; }) => void' is not assignable to type '(this: { name: string; options: any; storage: any; editor: Editor; parent: () => void; }) => void'.
		...
	},
});
```

### What did you expect to happen?

`onCreate` compiles without errors, just like the `onTransaction` event in the provided example

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [x] Yes, I’m a sponsor. 💖

**Comment by L0laapk3** [comment]
Reopening as while you can trivially access `editor` trough `this`, the typescript declaration still does not match up with the docs

**Comment by L0laapk3** [comment]
D:

**Comment by adg29** [comment]
Same issue!
