### ISSUE TITLE
[implementation proposal provided] page-break

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [ueberdosis/tiptap#3408]
### What problem are you facing?

When editing printable documents you need sometimes to put the page break. Currently I'm now aware of any extension that allows it.

### What’s the solution you would like to see?

I've created my own extension. I'm not very familiar with TipTap or ProseMirror, so probably it could be improved, but it works for me. So maybe it's worth to put it in the core?

https://gist.github.com/jacekkarczmarczyk/79e8d741fe965770092091a8cd116a90

### What alternatives did you consider?

The alternative is using my own extension :)

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by amalshaji-dev** [comment]
Any update

**Comment by jacekkarczmarczyk** [comment]
It is intentional so that you could easily add more content before the page break. Imagine editing a book where you want each chapter start on a new page. So you write chapter one, page break, chapter two, and then you want to add some contents to the chapter one
What would be the use case for fixed position page break?

**Comment by xiangshu233** [comment]
@jacekkarczmarczyk As mentioned above, add a page break when a certain height is reached, for example, add a page break when the A4 page height is reached
Is your page break WYSIWYG?

**Comment by xiangshu233** [comment]
@jacekkarczmarczyk I hope to provide a page break automatically when the height reaches A4， thanks

**Comment by jacekkarczmarczyk** [comment]
That's not the purpose of this plugin

**Comment by xiangshu233** [comment]
@EricHasegawa Hello, have you found a WYSIWYG paging solution? I would like to ask for your advice.

**Comment by alexbennycodes** [comment]
http://39.101.177.50/#/page1 you take a look at this, tiptap with paging, our you can take a look at slatejs (another WYSIWYG editor)
