### ISSUE TITLE
The problem of copying data from a doc, docx

### ISSUE THREAD

**Issue by VictoriaAppDeveloper** [ueberdosis/tiptap#3418]
### What problem are you facing?

Hello! I have a task to copy the data from the document to the editor without losing the formatting. How can I do that?

### What’s the solution you would like to see?

If there is such a possibility, please tell us about it. If not, then something like 

```
const data = 'anything from clipboard'

commands.insertContent(data,
     {
        parseOptions: {
          type: 'doc'
    }
}
```

### What alternatives did you consider?

```
export const EventHandler = Extension.create({
    name: 'eventHandler',
    addProseMirrorPlugins() {
        return [
            new Plugin({
                key: new PluginKey('eventHandler'),
                props: {
                    handlePaste(view, event, slice) {
                        /* some code to paste data */
                        return true
                    },
                },
            }),
        ]
    },
})
```

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by Le0nX** [comment]
@VictoriaAppDeveloper hello! Have you found the solution? If I understand correctly, we can do it manually with help of some kind of `doc/docx` converter to `html`, and then feed this `html` into tiptap editor.
