### ISSUE TITLE
Highlight marks in codeblock disappear on pasting

### ISSUE THREAD

**Issue by TechSupportJosh** [ueberdosis/tiptap#3428]
### What’s the bug you are facing?

We use highlighting within code blocks to highlight content within them.

However, if we copy and paste the code blocks, they lose the highlighted content within them (see video).

### Which browser was this experienced in? Are any special extensions installed?

Latest version of Chrome with Vue debug extensions.

### How can we reproduce the bug on our side?

Here's a CodeSandbox to reproduce it: https://codesandbox.io/s/quirky-lichterman-dd5vmz?file=/src/App.vue

Note that within the "content" of creating the editor, the codeblock content contains the `<mark></mark>` but when the editor is rendered, the mark tags are removed.

You can then select some text and use the button to toggle highlighting, which works as expected.

If you then copy and paste this code block, the highlighting marks will be lost again.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/quirky-lichterman-dd5vmz?file=/src/App.vue

### What did you expect to happen?

The highlighting marks are not lost during copy/pasting of the code block.

### Anything to add? (optional)

![chrome_j8JrJnR5z6](https://user-images.githubusercontent.com/5190840/202695846-ea31cd64-b9e9-45ff-a9fb-71d6db9729e0.gif)

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by TechSupportJosh** [comment]
Still having trouble with this, any insight would be appreciated

**Comment by dominiczy** [comment]
Having a similar issue, any marks within a codeblock seem to appear fine when first editing, but then disappear on save, copy & load etc

**Comment by dominiczy** [comment]
I found out that when saving to/loading from JSON it actually works fine, but when using HTML all marks in codeblocks disappear (even when extending the `marks` option on the codeblock to support the mark)
