### ISSUE TITLE
Attribute `id` is getting discarded from all elements while setting content.

### ISSUE THREAD

**Issue by ankojh** [ueberdosis/tiptap#3458]
### What’s the bug you are facing?

While setting content to the editor, if I pass any element with the standard HTML attribute of `id`, the same won't be reflected on the editor instance. I needed this, particularly for the read-only mode (editable: false) of displaying the editor content. I have a set of styles which crucially depends on those ids. Please do respond on how we can get the `id` attribute to be available inside the editor.

It appears even `class` is not being persisted for a few elements

my dependencies:

"@tiptap/core": "2.0.0-beta.183"
"@tiptap/extension-heading": "2.0.0-beta.29"

### Which browser was this experienced in? Are any special extensions installed?

Google Chrome Version 107.0.5304.110 (Official Build) (64-bit) on Linux

### How can we reproduce the bug on our side?

When you try to set content which has elements with id.

`editor.commands.setContent('<h3 id="heading-3">Title of a section</h3>')`

### What did you expect to happen?

I would expect the `id` attribute should be retained by the editor. So that it can be used by custom styles.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by newboy2006hosur** [comment]
Need solution.
