### ISSUE TITLE
when I paste text and image to tiptap,  only text i inserted.

### ISSUE THREAD

**Issue by fEyebrow** [ueberdosis/tiptap#3476]
### What’s the bug you are facing?

when I paste text and images to tiptap,  only text i inserted.
when I only paste images，it's ok.

### Which browser was this experienced in? Are any special extensions installed?

chrome
Version 107.0.5304.62 (Official Build) (arm64)

### How can we reproduce the bug on our side?

https://tiptap.dev/api/nodes/image

you try it in your page.

### What did you expect to happen?

when I paste text and images to tiptap,  I want all content to be inserted. 

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by fEyebrow** [comment]
I turn image to inline , but it's wrong again

**Comment by nikhilnaik5** [comment]
> I found the solution

can you provide the solution. I need help too regarding the same issue
