### ISSUE TITLE
Drag from some source and Drop as "suggestion"?

### ISSUE THREAD

**Issue by softwareguy74** [ueberdosis/tiptap#349]
In building on the "Suggestions" feature (as shown here: [https://tiptap.scrumpy.io/suggestions](url)), I have a need to allow dragging an element from an arbitrary source component (such as a treeview, gridview, etc) and dropping into specific location (where cursor is) in the text editor and have it appear as a "Suggestion".

Is this possible?  If so, example code would be greatly appreciated.

**Comment by softwareguy74** [comment]
Looks like similar to request: [https://github.com/scrumpy/tiptap/issues/329](url)

**Comment by philippkuehn** [comment]
I do not full understand what you try to achieve but there is a `draggable` option in the ProseMirror schema. With a custom implementation of a mention extension you can do something like this.

![Jun-10-2019 23-18-22](https://user-images.githubusercontent.com/2500670/59227625-169a8b80-8bd6-11e9-9a51-3928a56a1999.gif)

**Comment by softwareguy74** [comment]
Yes, that's what I'm trying to achieve, but was hoping to not have to write something custom.

**Comment by hanspagel** [comment]
Nothing we can do here, so I’m closing this for now. ✌️
