### ISSUE TITLE
TextAlign requires Heading

### ISSUE THREAD

**Issue by raarts** [ueberdosis/tiptap#3509]
### What’s the URL to the page you’re sending feedback for?

https://tiptap.dev/api/extensions/text-align

### What part of the documentation needs improvement?

It needs to be specified that the TextAlign extension needs the Heading extension.

### What is helpful about that part?

Will prevent confusion, and debugging

### What is hard to understand, missing or misleading?

The requirement is missing (maybe there's more then one?)

### Anything to add? (optional)

Maybe other extension have requirements too?

**Comment by codemzy** [comment]
I think textAlign only needs the heading extension if you configure it to apply to headings as per the example from the docs...

```js
TextAlign.configure({
  types: ['heading', 'paragraph'],
})
```

If you only configure it on paragraphs you don't need the heading extension...

```js
TextAlign.configure({
  types: ['paragraph'],
})
```

**Comment by raarts** [comment]
You may be right, and although this might seem obvious, this never occurred to me, and there was no error or warning.
