### ISSUE TITLE
TaskList potentially broken by Bitwarden browser extension (maybe others as well)

### ISSUE THREAD

**Issue by parkersprouse** [ueberdosis/tiptap#3513]
### What’s the bug you are facing?

I recently switched from not using the password manager [Bitwarden](https://bitwarden.com/) to using it - specifically the browser extension.
Before I installed the extension, the TipTap `TaskList` / `TaskItem` was functioning as expected.
After installing it, the task list started throwing the following error when I would try to check off any `TaskItem`s:
```js
Uncaught RangeError: Index 1 out of range for <taskList(taskItem(paragraph))>
```

At first I had no idea why my task lists were suddenly broken. I updated all my TipTap dependencies to the latest version with no success.

I tried my app in a different browser (Chrome - no Bitwarden extension installed) and they worked. I also tried on my phone (mobile Firefox - no Bitwarden extension) and it worked. Then I tried on a different Firefox profile that does not have the Bitwarden extension installed... and it worked.

Looking at the DOM event that's fired as part of the `TaskItem` `change` event, I noticed the following difference between an event fired in a browser with the extension and one from a browser without:

With the Bitwarden extension:
```html
<input type="checkbox" data-com.bitwarden.browser.user-edited="yes">
```

Without the Bitwarden extension:
```html
<input type="checkbox" checked="checked">
```

Inspecting both elements shows that `checked` is `true`, but the `attributes` are different:
```js
{
  ...
  attributes: [ type="checkbox", data-com.bitwarden.browser.user-edited="yes" ],
  checked: true,
  ...
}
```
vs
```js
{
  ...
  attributes: [ type="checkbox", checked="checked" ],
  checked: true,
  ...
}
```

I guess somehow the Bitwarden extension is changing the element in a way that breaks the TipTap `TaskItem` toggling.

### Which browser was this experienced in? Are any special extensions installed?

I experienced the issue in `Firefox 107.0.1 (64-bit)` on `OSX Ventura 13.0` with the Bitwarden browser extension, version `2022.10.1`, installed.

The issue did not happen in the same version browser on the same OS without the Bitwarden browser extension, or on other browsers without the Bitwarden extension.

### How can we reproduce the bug on our side?

Install the `Bitwarden` browser extension and then try to check off a `TaskItem` within a `TaskList` in the browser.

### Can you provide a CodeSandbox?

I cannot due to the issue seemingly stemming from a browser extension.

### What did you expect to happen?

Browser extensions should not unexpectedly break TipTap functionality.

### Anything to add? (optional)

While I'm only currently experiencing this with the Bitwarden extension, that doesn't mean it wouldn't happen with other extensions as well.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
We had this issue already in the past here:
https://github.com/ueberdosis/tiptap/issues/2697

The problem here is that some password managers seem to freely modify input elements. While 1Password for example works just fine, Bitwarden and I think Dashlane had problems with Tiptap. Now would be the question if it's on our side to fix this.

If anyone wants to take a look into this issue feel free. We currently have some other issues we want to work on.

**Comment by parkersprouse** [comment]
Ah, thank you for the link. I tried searching for `TaskList` issues, but didn't think to look through closed issues.

After reading through that thread, I'm currently going to go with [this workaround](https://github.com/ueberdosis/tiptap/issues/2697#issuecomment-1109074136)

**Comment by bdbch** [comment]
No worries!

While it's not on a high priority, if some one wants to pick up on that feel free to contribute 🙂

**Comment by clibu** [comment]
@parkersprouse @bdbch From what I can see Bitwarden has now [fixed](https://github.com/bitwarden/clients/pull/4001) this issue. I was seeing an issue with my [work-around](https://github.com/ueberdosis/tiptap/issues/2697#issuecomment-1109074136) where the checkbox and strikethrough were out of sync which got me to revisit this.

I am seeing an issue with the Tiptap code + YJS where changing the taskitem state on the first item in a list changes the strikethrough but not the checkbox on another device. Taskitems after the first work as expected.
