### ISSUE TITLE
[vite]: Rollup failed to resolve import "@tiptap/prosemirror-tables"

### ISSUE THREAD

**Issue by Xor767** [ueberdosis/tiptap#3549]
### What’s the bug you are facing?

Hi guys! 
I can't build my sources with Vite 4.0.1 because of @tiptap/extension-table because of the following error: 

```
[vite]: Rollup failed to resolve import "@tiptap/prosemirror-tables" from "/Users/xxx/projects/www/project/node_modules/@tiptap/extension-table/dist/tiptap-extension-table.esm.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "@tiptap/prosemirror-tables" from "/Users/xxx/projects/www/project/node_modules/@tiptap/extension-table/dist/tiptap-extension-table.esm.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to build.rollupOptions.external
```

any idea?
cheers!

### Which browser was this experienced in? Are any special extensions installed?

no browser

### How can we reproduce the bug on our side?

just run the command: npx vite build

### Can you provide a CodeSandbox?

Please look here: https://codesandbox.io/s/white-star-5g3ono

### What did you expect to happen?

a complete build 

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Did you install the dependency via `npm i @tiptap/prosemirror-tables` or `yarn add @tiptap/prosemirror-tables`?

**Comment by Xor767** [comment]
Hi @bdbch, thank you for your help!
I didn't install this dependency, I just followed the documentation [here](https://tiptap.dev/api/nodes/table#installation)
and I only installed the dependencies:  
`npm install @tiptap/extension-table @tiptap/extension-table-row @tiptap/extension-table-header @tiptap/extension-table-cell`

The `@tiptap/prosemirror-tables` package is normally installed as a sub-dependency by the `@tiptap/extension-table` (in the file `node_modules/@tiptap/extension-table/package.json`) no?

**Comment by sh1okoh** [comment]
I am also facing the same issue.

**Comment by svenadlung** [comment]
We recently made changes to include ProseMirror packages as peer dependencies. Thus, in addition to the mentioned packages, you also need to install `@tiptap/prosemirror-tables` (this package gets a separate release in the Tiptap namespace for reasons).

Therefore, as @bdbch wrote above, please install the package. The documentation will be updated accordingly.

Please let me know if the problem still exists.

**Comment by Xor767** [comment]
Hello, when I had @tiptap/prosemirror-tables I got the following error: 
[vite]: Rollup failed to resolve import "prosemirror-keymap"

**Comment by svenadlung** [comment]
@Xor767 Did you add `prosemirror-keymap` to your project? It might be related to this: https://tiptap.dev/installation/peer-dependencies

**Comment by svenadlung** [comment]
Hi @Xor767, these ProseMirror dependencies are not only useful for `@tiptap/extension-table`, but also for many others. Since some conflicts have been reported in the past, we decided to keep them as peer deps everywhere.

We are working on a separate package for these dependencies. This should make the handling a bit easier in the future.
