### ISSUE TITLE
CI Build failing due dependency issue with '@tiptap/prosemirror-tables'

### ISSUE THREAD

**Issue by aliasmac** [ueberdosis/tiptap#3553]
### What’s the bug you are facing?

Getting error `Module not found: Error: Can't resolve '@tiptap/prosemirror-tables' in '/app/node_modules/@tiptap/extension-table/dist'` on CI build out of the blue where previous build worked with no error. 

Any ideas what could be causing it?

I'm using the following titap packages:

```
  "@tiptap/extension-document": "^2.0.0-beta.17",
    "@tiptap/extension-highlight": "^2.0.0-beta.35",
    "@tiptap/extension-image": "^2.0.0-beta.30",
    "@tiptap/extension-link": "^2.0.0-beta.43",
    "@tiptap/extension-placeholder": "^2.0.0-beta.53",
    "@tiptap/extension-table": "^2.0.0-beta.54",
    "@tiptap/extension-table-cell": "^2.0.0-beta.23",
    "@tiptap/extension-table-header": "^2.0.0-beta.25",
    "@tiptap/extension-table-row": "^2.0.0-beta.22",
    "@tiptap/extension-task-item": "^2.0.0-beta.37",
    "@tiptap/extension-task-list": "^2.0.0-beta.29",
    "@tiptap/extension-underline": "^2.0.0-beta.25",
    "@tiptap/react": "^2.0.0-beta.114",
    "@tiptap/starter-kit": "^2.0.0-beta.190",
    "@tiptap/suggestion": "^2.0.0-beta.97",
```

### Which browser was this experienced in? Are any special extensions installed?

Error occurring in Circle CI

### How can we reproduce the bug on our side?

I'm not 100% how you might be able to replicate as error is occurring in my CI build, open to suggestions.

### Can you provide a CodeSandbox?

Not really as it's happening on CI build

### What did you expect to happen?

I expect my build to pass.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by aliasmac** [comment]
Fixed by running `npm i @tiptap/prosemirror-tables`

**Comment by markhughes** [comment]
@aliasmac all your tiptap packages should be the same version, you have quite a mixture of versions there
