### ISSUE TITLE
Update typography 1/2 → ½ logic

### ISSUE THREAD

**Issue by georgemandis** [ueberdosis/tiptap#3570]
### What problem are you facing?

When I type something like a date, 1/2 will convert to ½ in ways that can be disruptive:

![image](https://user-images.githubusercontent.com/21219/209181036-d3c8534d-9a1c-4bb1-a967-39c7068a360f.png)

Would it be possible to update the regex logic so that 1/2 does not convert to ½ in the middle of a word?

### What’s the solution you would like to see?

I would like it so that typing 2/1/2 does not result in 2/½.

### What alternatives did you consider?

You can do a quick cmd-z, but in practice this one shows up so often I'm wondering if any fractional typography shortcuts should be reconsidered?

### Anything to add? (optional)

Something like this:

```
/[^\w](1\/2)/.test("1/2")
```

Except it would be nice if it also worked at the **beginning** of a line as well (I couldn't think of the regex off-hand)

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by wyc7758775** [comment]
How did you solve it？
