### ISSUE TITLE
All latest versions depends on 209 one !

### ISSUE THREAD

**Issue by elboukhari** [ueberdosis/tiptap#3572]
### What’s the bug you are facing?

Using this command `npm ls --all` results on : 

`
├─┬ @tiptap/extension-color@2.0.0-beta.197
`
`
│ ├── @tiptap/core@2.0.0-beta.209 deduped
`

So even if I need 197 version for a given package, the core package is 209 !

This **break** the build : 
`[INFO] Error: [vite]: Rollup failed to resolve import "prosemirror-keymap" from "node_modules/@tiptap/core/dist/tiptap-core.esm.js".
[INFO] This is most likely unintended because it can break your application at runtime.
[INFO] If you do want to externalize this module explicitly add it to
[INFO] "build.rollupOptions.external"
`

### Which browser was this experienced in? Are any special extensions installed?

All

### How can we reproduce the bug on our side?

install any package from 197 and above and after try  this :
`npm ls --all`

### What did you expect to happen?

having the same version between dependecies

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by jselmani** [comment]
@elboukhari you can follow this update [here](https://tiptap.dev/installation/peer-dependencies)

We're using yarn as our package manager and the newest version has moved from devDependencies to peerDependencies. Yarn and NPM 6 and below do not install these automatically when you run yarn install or npm install. 

Add the prosemirror dependencies separately or upgrade your npm to 7 or higher and this should work without issue. 

If this works for you, please go ahead and close this issue as solved. 

My apologies in advance for formatting as I'm writing this from my phone.

**Comment by elboukhari** [comment]
Thank you @jselmani ! 
Indeed, upgrading to the latest node/npm versions resolves the bug.
I close the issue.
