### ISSUE TITLE
Autopunctuation does not work on iOS Safari

### ISSUE THREAD

**Issue by josephdpurcell** [ueberdosis/tiptap#3578]
### What’s the bug you are facing?

The autopunctuation feature that is part of iOS does not work with Tiptap using Safari.

Here is a screen recording:

https://user-images.githubusercontent.com/778111/209809833-c35908f8-30b5-49f5-8307-ebd79f5edbb1.MOV

### Which browser was this experienced in? Are any special extensions installed?

Safari 15, no extensions

### How can we reproduce the bug on our side?

1. Go to the default example https://tiptap.dev/examples/default
2. Type in the word "The" then enter two spaces
3. Notice that the two spaces are not replaced by a period and a space

### Can you provide a CodeSandbox?

See https://tiptap.dev/examples/default.

### What did you expect to happen?

I expected autopunctuation to work, ie two spaces is replaced with a period and a space. This functionality works with ProseMirror on iOS 15 Safari using the example at https://prosemirror.net/.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by chrisdeeming** [comment]
This should be reopened. I can confirm this issue.

**Comment by chrisdeeming** [comment]
This seems to be an issue in ProseMirror so opened an issue there

https://github.com/ProseMirror/prosemirror/issues/1372
