### ISSUE TITLE
Accepting YouTube "shorts" urls

### ISSUE THREAD

**Issue by enkia** [ueberdosis/tiptap#3582]
### What problem are you facing?

Ensure that users can provide YouTube short urls as well.

ie https://www.youtube.com/shorts/1H5UPEnzLkQ 

### What’s the solution you would like to see?

A slight change to the regex would solve the issue. 

### What alternatives did you consider?

Currently using a custom extension. 

### Anything to add? (optional)

Changing line 70 in the extension's utils adds _shorts_ url support:

```javascript
const videoIdRegex = /(?:v=|shorts\/)([-\w]+)/gm
```

I'd submit a pull request, but it's such a tiny change and the contributing doc said to submit ideas first. 

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by EugeneJeonME** [comment]
Thanks a lot. :)
I'm also using a custom extension.
