### ISSUE TITLE
how can I check if current node is in the first row of table

### ISSUE THREAD

**Issue by coader** [ueberdosis/tiptap#3588]
### What problem are you facing?

now I  can only use edit.isActive('table') to get if it's in table, but can't the exact row index

### What’s the solution you would like to see?

edit.getCurrentNode()
then use parent to get the tr, then get it's index

### What alternatives did you consider?

.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by codemzy** [comment]
There's some [code snippets](https://github.com/ueberdosis/tiptap/issues/548#issuecomment-952043495) in #548 that check if the focused cell is in the first row of the table - that should help!
