### ISSUE TITLE
WebRTC Collaboration Example doesn't seem to work

### ISSUE THREAD

**Issue by kongweiying2** [ueberdosis/tiptap#3597]
### What’s the URL to the page you’re sending feedback for?

https://tiptap.dev/guide/collaborative-editing#web-rtc

### What part of the documentation needs improvement?

So when attempting to try the implementation of the WebRTC example, it looks like the variable provider isn't actually used in the example. So when I attempt to actually use the example to collaborate, as described, by opening two windows and changing the document in one window, the other one doesn't actually update. 

In contrast, the other example, the one which uses the WebSocket Hocuspocus backend seems to work fine when doing that split window editing.

Am I missing something here? 

### What is helpful about that part?

It's described quite clearly step by step.

### What is hard to understand, missing or misleading?

The example doesn't seem to work as described.

**Comment by fridaystreet** [comment]
got the same issue. can't get the demo code to work at all.
