### ISSUE TITLE
Text replacement feature in macOS is broken

### ISSUE THREAD

**Issue by craigcarlyle** [ueberdosis/tiptap#3602]
### What’s the bug you are facing?

There appears to be an issue when trying to use the text replacement feature built in to macOS with Tiptap. Attempting to do so will result in the following error:

![Screenshot 2023-01-06 at 4 22 29 PM](https://user-images.githubusercontent.com/1305500/211121400-ebe72750-2abe-4f91-95d1-8f1d6a27f298.png)

The error seems to be coming from [here](https://github.com/ueberdosis/tiptap/blob/62d42275c529aa3c819e85133b0ad0dd22cac934/packages/core/src/inputRules/markInputRule.ts#L64). This may be caused by an invalid `to` value 🤔 

![Screenshot 2023-01-06 at 4 02 58 PM](https://user-images.githubusercontent.com/1305500/211121548-65b5369d-939f-4c42-90ee-5b5d69231c8c.png)

### Which browser was this experienced in? Are any special extensions installed?

Chrome, Safari, Firefox

### How can we reproduce the bug on our side?

* Create a text replacement in macOS. For example, `[crd]` to `**[CARD]**`:
![Screenshot 2023-01-06 at 4 01 39 PM](https://user-images.githubusercontent.com/1305500/211121196-5f67115e-6c61-4f50-9e24-a998f5c0b9cb.png)
* Attempt to use the text replacement shortcut in Tiptap:

https://user-images.githubusercontent.com/1305500/211121301-086f4d9b-dda9-4ec7-8749-c4d8c9f49f7b.mov

### What did you expect to happen?

Expected text should be entered (like in this demo from another editor):

https://user-images.githubusercontent.com/1305500/211121065-3c909e12-f8c0-446f-9bda-e6462c55624f.mov

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [x] Yes, I’m a sponsor. 💖

**Comment by rfgamaral** [comment]
@bdbch This issue never ended up being fixed, can you please reopen? I have an upcoming PR to fix this 😊

**Comment by bdbch** [comment]
Thanks! Reopened the issue

**Comment by ElHex** [comment]
Same error, if you have the textStyle extension installed and using the ortho corrector you replace a word for the suggested one the marks dissapear.

**Comment by nperez0111** [comment]
This has been released with 2.7.0-pre.0 and will be released in tiptap 2.7.0 when this beta has been tested by more users
