### ISSUE TITLE
An error occurred when selecting table contents after adding attributes to the TableCell

### ISSUE THREAD

**Issue by nayaRoll** [ueberdosis/tiptap#3608]
### What’s the bug you are facing?

I used the **extend()** method to create a new TestTableCell extension based on the TableCell to add some attributes to the table.
However, when I select the contents in the table, the console has some errors.
The content of the error is 
`Uncaught RangeError: No cell with offset 18 found
    at TableMap.findCell (tablemap.js:85:11)
    at TableMap.rectBetween (tablemap.js:118:14)
    at new CellSelection (cellselection.js:33:20)
    at setCellSelection (input.js:194:21)
    at HTMLDocument.move (input.js:222:18)`

However, if  TestTableCell and TableCell  are added at the same time when creating the new Editor, the error will not be reported. Although there will be warnings like "Duplicate extension names found: ['tableCell']. This can lead to issues." in the console.

### Which browser was this experienced in? Are any special extensions installed?

Chrome，Safari

### How can we reproduce the bug on our side?

`const TestTableCell = TableCell.extend({
  addAttributes() {
    return {
     valign: {
        default: null,
        isRequired: false,
      },
      width: {
        default: null,
        isRequired: false,
      },
      align: {
        default: null,
        isRequired: false,
      },
      style: {
        default: null,
        isRequired: false,
      },
    };
  },
});

//[...]

const editor = new Editor({
  extensions: [
    StarterKit,
    TableHeader,
    Table,
    TableRow,
    TestTableCell,
    //TableCell,
    TextStyle,
    Color,
    Link,
  ],
  content: null,
});

//[...]

editor.chain().setContent(
`<table contenteditable="true" bordercolor="silver" cellspacing="0" cellpadding="0" border="1"><tbody><tr height="23"><td style="color:#000000" valign="top" width="75" align="left"><p><span style="FONT-SIZE: 10pt; FONT-FAMILY: Meiryo UI" >A</span></p></td><td style="color:#000000" valign="top" width="75" align="left"><p><span style="FONT-SIZE: 10pt; FONT-FAMILY: Meiryo UI" >B</span></p></td></tr><tr height="23"><td style="color:#000000" valign="top" width="75" align="left"><p><span style="FONT-SIZE: 10pt; FONT-FAMILY: Meiryo UI" >C</span></p></td><td style="color:#000000" valign="top" width="75" align="left"><p><span style="FONT-SIZE: 10pt; FONT-FAMILY: Meiryo UI" fontstyle="FONT-SIZE: 10pt; FONT-FAMILY: Meiryo UI">D</span></p></td></tr></tbody></table>`
).run();

`

### What did you expect to happen?

I guess this may be an internal problem of the ProseMirror control. Maybe a special response is required for the tableCell extension.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by Fankhauser-Dominik** [comment]
We faced the same issue, we resolved it with a **...this.parent?.(),** within the return of the addAttributes().

```const TestTableCell = TableCell.extend({
addAttributes() {
return {
...this.parent?.(),
valign: {
default: null,
isRequired: false,
},
width: {
default: null,
isRequired: false,
},
align: {
default: null,
isRequired: false,
},
style: {
default: null,
isRequired: false,
},
};
},
});
```

**Comment by shrihari-prakash** [comment]
> We faced the same issue, we resolved it with a **...this.parent?.(),** within the return of the addAttributes().
> 
> ```
> addAttributes() {
> return {
> ...this.parent?.(),
> valign: {
> default: null,
> isRequired: false,
> },
> width: {
> default: null,
> isRequired: false,
> },
> align: {
> default: null,
> isRequired: false,
> },
> style: {
> default: null,
> isRequired: false,
> },
> };
> },
> });
> ```

Man @Fankhauser-Dominik I don't know how many hours you've potentially saved me with this answer. Been stuck with this for several hours and this one helped me a ton!
