### ISSUE TITLE
Extensions list link seems to be down

### ISSUE THREAD

**Issue by SteakdeNiche** [ueberdosis/tiptap#362]
**Describe the bug**
Can't reach the tiptap-extensions list doc page

**Steps to Reproduce / Codesandbox Example**
1. Go to [](https://tiptap.scrumpy.io/docs/guide/extensions.html#installation)
2. Click on [extensions list](https://tiptap.scrumpy.io/docs/guide/built-in.html)

**Comment by Chrissi2812** [comment]
The Built-In extensions have been moved to the **Api Reference**
https://tiptap.scrumpy.io/docs/api/extensions.html

**Comment by douglasg14b** [comment]
Perhaps the link can be changed then?

**Comment by hanspagel** [comment]
Thanks for reporting! The link has been fixed.
