### ISSUE TITLE
Bubble Menu disappears for split second after clicking item

### ISSUE THREAD

**Issue by dominiczy** [ueberdosis/tiptap#3625]
### What’s the bug you are facing?

I'm using Vite + React + TipTap. I've added a minimal implementation of the Bubble Menu. However, when clicking any Bubble Menu item that executes an editor command, the bubble menu disappears while the command is executed, and then reappears.
This is a bad user experience. I believe it's a bug since it's not present in the [TipTap's own Bubble Menu example](https://tiptap.dev/api/extensions/bubble-menu).

Minimal reproduction of the bug: https://stackblitz.com/edit/vitejs-vite-vdekmz?file=src%2FApp.jsx

### Which browser was this experienced in? Are any special extensions installed?

Chrome, no extensions

### How can we reproduce the bug on our side?

Reproduction at https://stackblitz.com/edit/vitejs-vite-vdekmz?file=src%2FApp.jsx

### Can you provide a CodeSandbox?

https://stackblitz.com/edit/vitejs-vite-vdekmz?file=src%2FApp.jsx

### What did you expect to happen?

Bubble Menu stays visible all the time

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by dominiczy** [comment]
Not sure if this is a cause or a symptom, but I've noticed the `aria-expanded` attribute of the Tiptap editor div becomes `false` for a split second at the same time the bubble menu disappears. Again, that doesn't happen in Tiptap's own example

<img width="245" alt="image" src="https://user-images.githubusercontent.com/12720768/212222668-b04d1e71-ae7e-4fd8-9bc6-df71f36a8e98.png">

**Comment by popdo** [comment]
> 

The button on the bubble menu will not have such a problem if you use button

**Comment by kongweiying2** [comment]
I'm also getting this issue. If a command is run, then it does this disappearing and then reappearing. If the command is disabled, then it's fine. @dominiczy Did you manage to find a solution?

**Comment by kongweiying2** [comment]
> > 
> 
> The button on the bubble menu will not have such a problem if you use button

Actually this is strange, there's no flashing if I use an ordinary element like <button>. Not quite sure how to resolve this.

**Comment by jmtimko5** [comment]
I still see this when using ordinary button elements
