### ISSUE TITLE
Uploading an image from the computer

### ISSUE THREAD

**Issue by charlieschmitt** [ueberdosis/tiptap#3630]
### What problem are you facing?

Currently, when using the editor, it is possible to add an image via a url. 
However, it is not possible to upload an image directly from the computer.

### What’s the solution you would like to see?

Upload an image directly from the computer

### What alternatives did you consider?

Quill js

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by TanyaKulikovskaya** [comment]
@charlieschmitt I solved this issue locally in my Vue App by creating a file input field and converting the uploaded image to base64 prior to providing it to `setImage` command.
Don't forget to activate this feature in the Image extension by setting `allowBase64` to **true**.

**Comment by GodsonAddy** [comment]
@TanyaKulikovskaya  Please can you share your code if you don't mind?  Like how you went about it step by step. Thanks

**Comment by bhaviljain68** [comment]
@TanyaKulikovskaya I'd like to see the source code too.. please share it

**Comment by rfgamaral** [comment]
We have a [custom extension](https://github.com/Doist/typist/blob/main/src/extensions/rich-text/rich-text-image.ts) on [Typist](https://typist.doist.dev) that allows you to show an image with upload progress. The upload mechanism needs to be implemented on your side with your server, but we also have a working of example of using base64 [here](https://github.com/Doist/typist/blob/main/stories/typist-editor/rich-text.stories.tsx). There's a live demo available [here](https://typist.doist.dev/?path=/story/typist-editor-rich-text--default), just copy an image to the clipboard and paste it into the editor. Hope this helps.

**Comment by TanyaKulikovskaya** [comment]
@charlieschmitt, @bhaviljain68

...
`<button @click.stop="openChooseImageDialog">
    Upload Image
 </button>`
...
` methods: {
    openChooseImageDialog () {
            const input = document.createElement('input');
            input.type = 'file';
            input.accept = 'image/*';
            input.onchange = (event) => {
                this.uploadImage(event);
            };
            input.click();
        },
    async uploadImage (event) {
            const file = event.target.files[0];
            const base64 = await this.convertBase64(file);
            this.insertImage(base64);
        },
    convertBase64 (file) {
            return new Promise((resolve, reject) => {
                const fileReader = new FileReader();
                fileReader.readAsDataURL(file);

                fileReader.onload = () => {
                    resolve(fileReader.result);
                };

                fileReader.onerror = (error) => {
                    reject(error);
                };
            });
        },
    insertImage (url) {
            if (url) {
                this.editor
                    .chain()
                    .focus()
                    .setImage({ src: url })
                    .run();
            }
        },
`
...
` mounted () {
        this.editor = new Editor({
            extensions: [
                ...
                Image.configure({
                    allowBase64: true,
                 }),
                ...
            ],
        });
    },`

**Comment by TanyaKulikovskaya** [comment]
@rfgamaral @bhaviljain68 

`<button @click="openChooseImageDialog">Upload Image</button>`

```
<script>
export default {
    
    methods: {
        openChooseImageDialog () {
            const input = document.createElement('input');
            input.type = 'file';
            input.accept = 'image/*';
            input.onchange = (event) => {
                this.uploadImage(event);
            };
            input.click();
        },
        async uploadImage (event) {
            const file = event.target.files[0];
            const base64 = await this.convertBase64(file);
            this.insertImage(base64);
        },
        convertBase64 (file) {
            return new Promise((resolve, reject) => {
                const fileReader = new FileReader();
                fileReader.readAsDataURL(file);

                fileReader.onload = () => {
                    resolve(fileReader.result);
                };

                fileReader.onerror = (error) => {
                    reject(error);
                };
            });
        },
        insertImage (url) {
            if (url) {
                this.editor
                    .chain()
                    .focus()
                    .setImage({ src: url })
                    .run();
            }
        },
    },
};
</script>
```

```
Image.configure({
  allowBase64: true,
})
```
