### ISSUE TITLE
Gapcursor with CodeBlockLowLight extension

### ISSUE THREAD

**Issue by ashu12chi** [ueberdosis/tiptap#3636]
### What’s the bug you are facing?

Hey,

I want to have gap-cursor with CodeBlockLowLight extension. I was looking at an old https://github.com/ueberdosis/tiptap/issues/1195
On the issue, @philippkuehn commented that we should improve behavior. I wanted to know if we can have gap-cursor working for code-block or not?

### Which browser was this experienced in? Are any special extensions installed?

In all browsers.

### How can we reproduce the bug on our side?

Try CodeBlockLowlight here: https://tiptap.dev/api/nodes/code-block-lowlight

### Can you provide a CodeSandbox?

NA

### What did you expect to happen?

Gapcursor should work with CodeBlockLowlight like Table: https://tiptap.dev/api/nodes/table

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by ashu12chi** [comment]
Commenting as issue is still coming in latest release.

**Comment by nperez0111** [comment]
This adds nothing new, this is still going to be an issue with the current version since we do not have control of that package, bring it up stream if it is an issue
