### ISSUE TITLE
Use latest version of prosemirror-dropcursor package?

### ISSUE THREAD

**Issue by apaar97** [ueberdosis/tiptap#3639]
### What’s the bug you are facing?

Running into `UNMET_PEER_DEPENDENCY` warning on fresh installation:

```
@tiptap/extension-dropcursor
        └── ✕ unmet peer prosemirror-dropcursor@1.5.0: found 1.6.1
```

### Which browser was this experienced in? Are any special extensions installed?

Not relevant?

### How can we reproduce the bug on our side?

Reproducible by simply following guide: https://tiptap.dev/installation/peer-dependencies#tiptapextension-dropcursor
This installs the latest version of `prosemirror-dropcursor` (v1.6.1) which does not meet peer version (v1.5.0) specified by `@tiptap/extension-dropcursor`

### Can you provide a CodeSandbox?

Not required

### What did you expect to happen?

No unmet peer dep warnings on fresh installation 

### Anything to add? (optional)

While I can downgrade to v1.5.0, I want to understand why the prosemirror package version is fixed [here](https://github.com/ueberdosis/tiptap/blob/main/packages/extension-dropcursor/package.json#L33) and why not use `^` to automatically get next minor version. Also `prosemirror-dropcursor` [changelog](https://github.com/ProseMirror/prosemirror-dropcursor/blob/master/CHANGELOG.md#161-2022-10-25) doesn't provide any hint on why tiptap would use a fixed version, so I assume this is just a miss.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by svenadlung** [comment]
This should be fixed since introduction of @tiptap/pm package. Let me know if it still persists.
