### ISSUE TITLE
RangeError: Schema is missing its top node type ('doc')

### ISSUE THREAD

**Issue by erkhem42** [ueberdosis/tiptap#3660]
### What’s the bug you are facing?

I have to add `@tiptap/prosemirror-tables` package explicitly because `@tiptap/extension-table` requires it (it's declared as `peerDependency`)

```
error - ./node_modules/@tiptap/extension-table/dist/tiptap-extension-table.esm.js:2:0
Module not found: Can't resolve '@tiptap/prosemirror-tables'
```

But when I added `@tiptap/prosemirror-tables` explicitly, following error is shown:

<img width="789" alt="Screenshot 2023-01-26 at 13 16 22" src="https://user-images.githubusercontent.com/205824/214764038-22d50c28-bc1d-464b-9b86-fcfd8bbce6dd.png">

### Which browser was this experienced in? Are any special extensions installed?

`@tiptap/extension-table @tiptap/extension-table-row @tiptap/extension-table-header @tiptap/extension-table-cell`

### How can we reproduce the bug on our side?

yarn add @tiptap/extension-table @tiptap/extension-table-row @tiptap/extension-table-header @tiptap/extension-table-cell
yarn dev

### What did you expect to happen?

No error build

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
This seems to be an issue with your extension setup - do you have the starter kit setup correctly or did you install the `@tiptap/extension-document`, `@tiptap/extension-paragraph` and `@tiptap/extension-text` correctly and set it up?
