### ISSUE TITLE
Not create typography fractions mid-word?

### ISSUE THREAD

**Issue by georgemandis** [ueberdosis/tiptap#3674]
### What problem are you facing?

The TipTap Typography extension will auto-convert fractions into single-character entities:
- 1/2 → ½
- 1/4 → ¼

This is sometimes convenient, but it's very _inconvient_ when these shortcuts are triggered in the middle of a word.

Here is a video demonstrating how it inserts itself when typing a date:

https://user-images.githubusercontent.com/21219/215512332-2003e7eb-7ea3-48f0-8179-287c40e35034.mov

### What’s the solution you would like to see?

I would like to see these shortcuts triggered only when they are initiated at the beginning of a word-break and _not_ when they occur within the middle of a word.

### What alternatives did you consider?

I considered overriding and amending the regex myself, but thought it would be faster and more effective if this were the default behavior. It feels sensible?

The regex would have to be something like this I think:

```
/(^|\s)(1\/2)$/
```

Could we do that for fractions... and possibly most of the shortcuts?

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Hey @georgemandis good find! I'll see if I can take a quick look after I'm done with my current PR.
