### ISSUE TITLE
BubbleMenu jumps sideways on mouse up

### ISSUE THREAD

**Issue by airblade** [ueberdosis/tiptap#3684]
### What’s the bug you are facing?

I am using the bubblemenu extension along with a custom node which simply holds text.  I have configured the menu's placement to be `bottom-start`.

I have it set up so that when a user single-clicks in/on one of these custom nodes, the menu shows.

Expected: the menu appears below the left edge of the node (either on mouse down or mouse up, I don't mind).

Actual: the menu appears below where the mouse is, on mouse down, and then on mouse up jumps sideways to be aligned with the left edge of the node.

I have noticed that the `updateDelay` directly corresponds to the length of time between releasing the mouse button and the menu jumping sideways to the correct position.

This doesn't happen with the BubbleMenu examples on the TipTap website.  The main difference I can see is that the examples require double-clicking, which selects some text in a paragraph node, whereas my custom node just needs a single click (which is what I want).

### Which browser was this experienced in? Are any special extensions installed?

Chrome, Firefox, Safari.  All on MacOS 12.6.

### How can we reproduce the bug on our side?

I will try to put together a CodeSandbox.  However I'm using importmaps, Stimulus, and plain JavaScript rather than Vue or React so I can't use your templates as is :)

### Can you provide a CodeSandbox?

See above.

### What did you expect to happen?

The menu appears in the correct place, aligned to the node's edge, instead of appearing aligned to the cursor and then jumping to the correct place.

### Anything to add? (optional)

I'm not sure whether the problem lies in the Bubblemenu extension, Tippy, or Popper.

When I set the placement to `top-start`, I get the same problem with horizontal alignment – yet the menu is correctly placed above the custom node.

So the `placement` value is being read and applied; but for some reason the horizontal value is taken from the mouse on mouse down and then from the node on mouse up, even though the vertical value is correctly calculated first time.

Perhaps the menu should not show on mouse down, but only on mouse up?

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by airblade** [comment]
Here's my code:

```javascript
BubbleMenu.configure({
  element: ...,
  tippyOptions: {
    placement: 'bottom-start'
  },
  shouldShow: ({editor, view, state, oldState, from, to}) => {
    return editor.isActive('my-custom-node')
  },
})
```

**Comment by airblade** [comment]
Closing this because I found a solution to my problem, even though I don't understand it.

**Comment by xinghul** [comment]
hmm that's weird, how can you access `this.element` from the code snippet?

I think the issue is, overriding the method will override the existing logic, ideally it should `return this.super()` in the end

**Comment by airblade** [comment]
> ...how can you access this.element from the code snippet?

The code snippet above was in this context:

```javascript
BubbleMenu.configure({
    element: ...,
    shouldShow: ({editor, view, state, oldState, from, to}) => {
        // code snippet above
    }
})
```

So `this.element` referred to the element given in the constructor.

> I think the issue is, overriding the method will override the existing logic, ideally, we should be able to fallback to the default behavior in the end...

I agree but I couldn't get it to work.  I can't remember everything I tried but I'm sure `this.super()` would have been the first thing I tried.
