### ISSUE TITLE
beta-210 release broke builds on Next.js (and possibly others)

### ISSUE THREAD

**Issue by haardikk21** [ueberdosis/tiptap#3689]
### What’s the bug you are facing?

When using latest Tiptap version (beta-210 or 211) with `extension-collaboration`, it breaks on Next.js 13.

### Which browser was this experienced in? Are any special extensions installed?

Firefox

### How can we reproduce the bug on our side?

```
npx create-next-app tiptap-test
npm install @tiptap/core @tiptap/pm @tiptap/starter-kit
npm install @tiptap/extension-collaboration yjs
```

Create a Tiptap component that just sets up StarterKit and Collaboration

You will face the issue - Module not found - Can't resolve `perf_hooks`.

### What did you expect to happen?

Should've worked.

### Anything to add? (optional)

I tried using Next dynamic imports as well, to no avail.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by driaug** [comment]
The getting started guide for Next.js is now also broken. Resulting in a wrong Lodash import.

`Did you mean to import lodash/debounce.js?`

**Comment by svenadlung** [comment]
Experiencing the same with `lodash`. We will have a look – thanks for reporting!

**Comment by eminbasbayan** [comment]
> The getting started guide for Next.js is now also broken. Resulting in a wrong Lodash import originating from the bubble-menu extension.
> 
> `Did you mean to import lodash/debounce.js?`

I started getting this error too.

**Comment by rikta95** [comment]
Same here in react

"./node_modules/@tiptap/extension-bubble-menu/dist/index.js" contains a reference to the file "lodash/debounce"

**Comment by stepanjakl** [comment]
+1 Same issue as a dependency to the `@tiptap/vue-2` package. Downgrading to version `2.0.0-beta.209` helped. I just overode the peer dependency in the `package.json` file, like so:

```
"overrides": {
    "@tiptap/vue-2": {
      "@tiptap/extension-bubble-menu": "2.0.0-beta.209"
    }
  }
```

**Comment by NotTimTam** [comment]
Same in Next.js, went through the imports and exports of each file and nothing seems out of the ordinary. lodash/debounce exports as:
```js

module.exports = debounce;
```
And extension-bubble-menu imports using:
```js
import debounce from "lodash/debounce";
```

**Comment by acirinelli** [comment]
Broken for me on vue3. Even going back to beta-209 it will not compile, it wants `debounce.js`

**Comment by bdbch** [comment]
I just released a new version (beta.212) which should fix the Collaboration package issues. Let me know if that helped.

I'll look at the other issues tomorrow morning.

**Comment by bdbch** [comment]
@acirinelli could you try @stepanjakl 's fix while I work on this issue?
https://github.com/ueberdosis/tiptap/issues/3689#issuecomment-1414492414

I'll keep you updated.

**Comment by acirinelli** [comment]
> @acirinelli could you try @stepanjakl 's fix while I work on this issue? [#3689 (comment)](https://github.com/ueberdosis/tiptap/issues/3689#issuecomment-1414492414)
> 
> I'll keep you updated.

ok I tried it earlier and it didn't work, but in fact it does. Must delete both node_modules AND package-lock.json before `npm install` in order for it to work.

**Comment by Bessonov** [comment]
Not sure that it is the same error, but after update to beta.212 I get additionaly:

ERROR in ../../node_modules/.pnpm/@tiptap+core@2.0.0-beta.212/node_modules/@tiptap/core/dist/index.js 150:0-152:26
Module not found: Error: Can't resolve '@tiptap/pm/state' in '[...]/node_modules/.pnpm/@tiptap+core@2.0.0-beta.212/node_modules/@tiptap/core/
dist'

For:
- @tiptap/pm/state
- @tiptap/pm/view
- @tiptap/pm/keymap
- other @tiptap/pm/*
imports.

pnpm-lock.yaml and node_modules were deleted. Not tired to pin @tiptap/extension-bubble-menu yet.

**Comment by githubbob42** [comment]
I just updated my libraries (updated to `beta.211`) and now I get the following error:
```
ERROR in ./node_modules/@tiptap/extension-bubble-menu/dist/index.js 11:0-39
Module not found: Error: Can't resolve 'lodash/debounce' in '/Users/Bob.Roth/projects/svmx-dg-template-editor/node_modules/@tiptap/extension-bubble-menu/dist'
Did you mean 'debounce.js'?
BREAKING CHANGE: The request 'lodash/debounce' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

It seems to be a bug within tiptap that started with: https://github.com/ueberdosis/tiptap/pull/3501/files

I'm using `@tiptap/react`

**Comment by lolwuz** [comment]
I'm using **beta.212** on Nextjs. Getting this error on next build only.

`[ERR_MODULE_NOT_FOUND]: Cannot find module '/home/lolwuz/ostrapp-client/node_modules/lodash/debounce' imported from /home/lolwuz/ostrapp-client/node_modules/@tiptap/extension-bubble-menu/dist/index.js
Did you mean to import lodash/debounce.js?`

Using @NotTimTam quick fix for now.

**Comment by Ahsan-Ullah1871** [comment]
> Not sure that it is the same error, but after update to beta.212 I get additionaly:
> 
> ERROR in ../../node_modules/.pnpm/@tiptap+core@2.0.0-beta.212/node_modules/@tiptap/core/dist/index.js 150:0-152:26 Module not found: Error: Can't resolve '@tiptap/pm/state' in '[...]/node_modules/.pnpm/@tiptap+core@2.0.0-beta.212/node_modules/@tiptap/core/ dist'
> 
> For:
> 
> * @tiptap/pm/state
> * @tiptap/pm/view
> * @tiptap/pm/keymap
> * other @tiptap/pm/*
>   imports.
> 
> pnpm-lock.yaml and node_modules were deleted. Not tired to pin @tiptap/extension-bubble-menu yet.

Are you able to fix it any way ?
I am trying from last few hours  but still facing errors at deploying time  .

**Comment by Bessonov** [comment]
@Ahsan-Ullah1871 
> Are you able to fix it in any way? I've been trying for a few hours now, but I'm still getting errors during the deployment process.

No, unfortunately I'm not working on that. I think it can be workarounded by pinning the older version.

**Comment by Bessonov** [comment]
@Ahsan-Ullah1871 , oh I have found this comment: https://github.com/ueberdosis/tiptap/issues/3701#issuecomment-1416503614 . Not tried yet, but looks very promising.

**Comment by Bessonov** [comment]
@Ahsan-Ullah1871 just tested it. It works for me.

Webpack users can use following workaround for debounce until the next release: https://github.com/ueberdosis/tiptap/pull/3699#issuecomment-1416863942

**Comment by rdewolff** [comment]
Confirm this does not work on new setup.

**Comment by bdbch** [comment]
I released a quick fix for this with version `beta.213` - could you guys test this again?

**Comment by rdewolff** [comment]
this seems to fix it 🎉

**Comment by ionTea** [comment]
I still have an issue with `@tiptap/pm/state`:

```
error - ../node_modules/.pnpm/@tiptap+core@2.0.0-beta.213/node_modules/@tiptap/core/dist/index.js:150:0
Module not found: Can't resolve '@tiptap/pm/state'
```

**Comment by Bessonov** [comment]
> I still have an issue with `@tiptap/pm/state`:
> 
> ```
> error - ../node_modules/.pnpm/@tiptap+core@2.0.0-beta.213/node_modules/@tiptap/core/dist/index.js:150:0
> Module not found: Can't resolve '@tiptap/pm/state'
> ```

Did you saw https://github.com/ueberdosis/tiptap/issues/3701#issuecomment-1416503614 ?

**Comment by ionTea** [comment]
@Bessonov thank you, that solved the `@tiptap/p,/state` issue, but now I have the issue with the ESM build and lodash
```
Error [ERR_REQUIRE_ESM]: require() of ES Module <folder>/node_modules/.pnpm/lodash-es@4.17.21/node_modules/lodash-es/lodash.js from <folder>/node_modules/.pnpm/@tiptap+extension-bubble-menu@2.0.0-beta.213_7rz66h33fpkvqmmazdnqczeig4/node_modules/@tiptap/extension-bubble-menu/dist/index.cjs not supported.
Instead change the require of lodash.js in <folder>/node_modules/.pnpm/@tiptap+extension-bubble-menu@2.0.0-beta.213_7rz66h33fpkvqmmazdnqczeig4/node_modules/@tiptap/extension-bubble-menu/dist/index.cjs to a dynamic import() which is available in all CommonJS modules.
```

**Comment by Bessonov** [comment]
> @Bessonov thank you, that solved the `@tiptap/pm/state` issue, but now I have the issue with the ESM build and lodash
> 
> ```
> Error [ERR_REQUIRE_ESM]: require() of ES Module <folder>/node_modules/.pnpm/lodash-es@4.17.21/node_modules/lodash-es/lodash.js from <folder>/node_modules/.pnpm/@tiptap+extension-bubble-menu@2.0.0-beta.213_7rz66h33fpkvqmmazdnqczeig4/node_modules/@tiptap/extension-bubble-menu/dist/index.cjs not supported.
> Instead change the require of lodash.js in <folder>/node_modules/.pnpm/@tiptap+extension-bubble-menu@2.0.0-beta.213_7rz66h33fpkvqmmazdnqczeig4/node_modules/@tiptap/extension-bubble-menu/dist/index.cjs to a dynamic import() which is available in all CommonJS modules.
> ```

You're not alone: https://github.com/ueberdosis/tiptap/pull/3699#issuecomment-1420562078

**Comment by bdbch** [comment]
I just released `2.0.0-beta.214` which uses our old build process with a few minor changes and the new PM package. Would be nice to see if this fixes the issues introduced by the esbuild builds.

**Comment by canthis** [comment]
@bdbch Works fine again on my end with yarn and vue 2. Thanks!

**Comment by ionTea** [comment]
@bdbch yes I just tried `beta.215` and it works fine for me!

**Comment by stryaponoff** [comment]
I got this output in Vitest using beta.215 (beta.213 works ok). The output is related to node_modules/@tiptap/extension-bubble-menu/dist/index.js:3

import { debounce } from 'lodash';
         ^^^^^^^^
SyntaxError: Named export 'debounce' not found. The requested module 'lodash' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'lodash';
const { debounce } = pkg;

**Comment by bdbch** [comment]
`beta.216` is building right now and is going to be published afterwards. That should hopefully fix the lodash issue.

**Comment by upview** [comment]
new user here, followed the next.js tutorial with `beta.216` and still have the issue :
```
Error: Cannot find module '/Users/me/sources/mvp/node_modules/lodash/debounce' imported from /Users/me/sources/mvp/node_modules/@tiptap/extension-bubble-menu/dist/index.js
Did you mean to import lodash/debounce.js?
```
can I do something to help?

**Comment by acirinelli** [comment]
@bdbch unfortunately, 216 took us back to not working again.

**Comment by bdbch** [comment]
Could you update to `beta.217` and try again?

**Comment by bdbch** [comment]
Thanks for testing your build. Happy to hear that fixed it for you.

**Comment by bdbch** [comment]
I'll close this issue for now - if you still have build / dev issues with the most recent version `beta.217` let me know.

**Comment by harryyaprakov** [comment]
Hey, unfortunately, Im still reproducing this on my end.

With Nuxt 3.2.2 and @tiptap/vue-3 2.0.0-beta.217 im getting.

`[vite]: Rollup failed to resolve import "@tiptap/pm/state" from "/Users/Hristiyan.Yaprakov/Library/Mobile Documents/com~apple~CloudDocs/Projects/happ/node_modules/@tiptap/core/dist/index.js"`

**Comment by bdbch** [comment]
Can you find `@tiptap/pm` in your node_modules folder?

**Comment by CharlieDigital** [comment]
@bdbch I'm having the same issue as @harryyaprakov 

`@tiptap/pm` is not present in the `node_modules`.

**Comment by bdbch** [comment]
Yep since your bundler is complaining that `@tiptap/pm` is not resolvable, you should first check if it's installed correctly. Hope that also helps @harryyaprakov

**Comment by njdubois** [comment]
If you are having issues with `@tiptap/pm/state` in adminjs -> adminjs/design-systems, note that I've opened an issue here: https://github.com/SoftwareBrothers/adminjs-design-system/issues/88

**Comment by kaitnoone** [comment]
Has anyone else run into this while spinning up inside a Docker container? I've removed node_modules and package-lock several times, upgraded my NPM version to 8.3 (I inherited this codebase) and have reinstalled @tiptap/core and then @tiptap/pm but am still getting errors that @tiptap/pm dependencies don't exist in core. I'll attach more error information tomorrow. TIA!

**Comment by Sreesanth46** [comment]
+1
