### ISSUE TITLE
(beta-211) File "@tiptap/core/dist/index.d.ts" has error in class "NodeView"

### ISSUE THREAD

**Issue by ErikDCAlmeida** [ueberdosis/tiptap#3691]
### What’s the bug you are facing?

declare class NodeView<Component, Editor extends **Editor = Editor**, Options[...]

In the part "Editor = Editor" the following error is accused:
**Type parameter defaults can only reference previously declared type parameters.ts(2744)**
![imagem_2023-02-02_174710528](https://user-images.githubusercontent.com/53847844/216445861-4116cbae-5655-4391-b310-bd69da1c69af.png)

### Which browser was this experienced in? Are any special extensions installed?

The problem occurs when I build my project with tiptap "[...]beta-211" installed.

### How can we reproduce the bug on our side?

Installing the basic TipTap installation commands.

### What did you expect to happen?

I hoped the error didn't happen.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Thanks I will take a look

**Comment by bdbch** [comment]
What kind of setup do you have so I can replicate a broken build?

**Comment by bdbch** [comment]
I just released a new version (beta.212) which should fix this issue.

**Comment by ErikDCAlmeida** [comment]
I'm sorry for the delay in replying. Thank you for your attention! @bdbch
