### ISSUE TITLE
@tiptap/react is dependent on extension-bubble-menu and extension-floating-menu

### ISSUE THREAD

**Issue by githubbob42** [ueberdosis/tiptap#3693]
### What’s the bug you are facing?

I just updated my libraries (updated to `beta.211`) and now I get the following error:
```
ERROR in ./node_modules/@tiptap/extension-bubble-menu/dist/index.js 11:0-39
Module not found: Error: Can't resolve 'lodash/debounce' in '/Users/Bob.Roth/projects/svmx-dg-template-editor/node_modules/@tiptap/extension-bubble-menu/dist'
Did you mean 'debounce.js'?
BREAKING CHANGE: The request 'lodash/debounce' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

It seems to be a bug within tiptap that started with: https://github.com/ueberdosis/tiptap/pull/3501/files

I'm using `@tiptap/react`

### Which browser was this experienced in? Are any special extensions installed?

All

### How can we reproduce the bug on our side?

Remove your `node_modules` and `package-lock.json` and do an `npm install`?

### What did you expect to happen?

`@tiptap/react` NOT to be dependent on either `extension-bubble-menu` nor `extension-floating-menu`

### Anything to add? (optional)

No

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by githubbob42** [comment]
Hmmm, possible duplicate or at least related to https://github.com/ueberdosis/tiptap/issues/3689

**Comment by bdbch** [comment]
Hey! Yes it's related to that issue. The dependency being that hard is actually correct since the react and vue packages also deliver ready-to-use components for bubble & floating menus. I think we'll mostly will fix the issue regarding lodash and keep those included in the react/vue packages.

**Comment by RouvenGonzalez** [comment]
Hi, I'm facing the same issue.
Is there a version without the dependencies using @tiptap/pm till this is fixed?
I tried setting all back to beta-205 but extension-bubble-menu or extension-floating-menu still want tiptap/pm

**Comment by githubbob42** [comment]
Thanks @bdbch, I figured that was the reasoning behind the dependencies.

Unfortunately tiptap is using semantic versioning in their package.json files across packages.  

Perhaps now that tiptap has started using consistent package versioning ([#3197 New versioning & release approach](https://github.com/ueberdosis/tiptap/discussions/3197)), maybe the versions specified should be specific versions for the package/release and not semantic.  That way, when you install `@tiptap/react@2.0.0-beta.206` you get version `206` of the package and all of it's dependencies at 206 and not 206 of the package and 211 of the dependencies (where the dependency has the bug).

**Comment by wulibaibao** [comment]
fast fix this

`pnpm add lodash.debounce -D`

webpack resolve alias 
`
alias: {
    "lodash/debounce": "lodash.debounce"
}
`

**Comment by wulibaibao** [comment]
fast fix this

`pnpm add lodash.debounce -D`

webpack resolve alias 
`
alias: {
    "lodash/debounce": "lodash.debounce"
}
`

**Comment by bdbch** [comment]
This should work with version `beta.217` again.

Feel free to reopen if you still have issues with lodash.

**Comment by earvinLi** [comment]
> This should work with version `beta.217` again.
> 
> Feel free to reopen if you still have issues with lodash.

does 216 work?

**Comment by bdbch** [comment]
I'm not sure about your setup. Some people reported that beta.216 worked fine for them - some had issues with the lodash dependency not loading correctly. With `beta.217` it should work now.
