### ISSUE TITLE
@tiptap/html missing dependencies

### ISSUE THREAD

**Issue by shustudios** [ueberdosis/tiptap#3701]
### What’s the bug you are facing?

Unable to use `@tiptap/html` because I get an error: `Cannot find module '@tiptap/pm/state'`

### Which browser was this experienced in? Are any special extensions installed?

Experiencing issue trying to load server side in my Nuxt.js app.

```const { Document } = require('@tiptap/extension-document')
const { Paragraph } = require('@tiptap/extension-paragraph')
const { Text } = require('@tiptap/extension-text')
const { Bold } = require('@tiptap/extension-bold')
const { generateHTML, generateJSON } = require('@tiptap/html')```

### How can we reproduce the bug on our side?

Please see code above.

### Can you provide a CodeSandbox?

_No response_

### What did you expect to happen?

I expect the application to build without errors.

### Anything to add? (optional)

I am trying to generateHTML on the server side.
I am using version `2.0.0-beta.212` for all tiptap packages

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by delight** [comment]
Read the 🔥 Breaking changes in
https://github.com/ueberdosis/tiptap/releases/tag/v2.0.0-beta.210

and then close the issue :)

**Comment by shustudios** [comment]
Will do, thanks

**Comment by shustudios** [comment]
Made a bit more progress moving forward but still running into issues using `@tiptap/html` on the server:

```
 ERROR  in ./node_modules/zeed-dom/dist/index.js                                                                                                                                         friendly-errors 16:10:58

Module parse failed: Unexpected token (746:42)                                                                                                                                           friendly-errors 16:10:58
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|       this.attrRe,
|       (attr, name, c2, value, c4, valueInQuote, c6, valueInSingleQuote) => {
>         attrs[name] = valueInSingleQuote ?? valueInQuote ?? value ?? true;
|       }
|     );
```

I'm assuming I don't need to edit my webpack (nuxt) config as there is no mention in the docs?

**Comment by ZhenyaMelnichuk** [comment]
Same error. Here is the code:

**Comment by ZhenyaMelnichuk** [comment]
> Same error. ![изображение](https://user-images.githubusercontent.com/95444560/216789363-b9de57eb-c6d4-4b03-a11a-4ba3bdcd6191.png)
> 
> Here is the code:
> 
> ```
> <template>
>     <pre><code>{{ output }}</code></pre>
> </template>
> 
> <script>
> // Option 1: Browser + server-side
> import Bold from '@tiptap/extension-bold'
> // Option 2: Browser-only (lightweight)
> // import { generateHTML } from '@tiptap/core'
> import Document from '@tiptap/extension-document'
> import Paragraph from '@tiptap/extension-paragraph'
> import Text from '@tiptap/extension-text'
> import { generateHTML } from '@tiptap/html'
> 
> const json = {
>     type: 'doc',
>     content: [
>         {
>             type: 'paragraph',
>             content: [
>                 {
>                     type: 'text',
>                     text: 'Example ',
>                 },
>                 {
>                     type: 'text',
>                     marks: [
>                         {
>                             type: 'bold',
>                         },
>                     ],
>                     text: 'Text',
>                 },
>             ],
>         },
>     ],
> }
> 
> export default {
>     computed: {
>         output() {
>             return generateHTML(json, [
>                 Document,
>                 Paragraph,
>                 Text,
>                 Bold,
>                 // other extensions …
>             ])
>         },
>     },
> }
> </script>
> ```

Solved the problem by adding an option to the webpack config:
`transpileDependencies: ['zeed-dom']`

**Comment by shustudios** [comment]
"Solved the problem by adding an option to the webpack config:
transpileDependencies: ['zeed-dom']"

That worked - thanks!

**Comment by tibineagu** [comment]
For anyone out there reading about this in conjunction with `nuxt 2.x` - there's the [`build.transpile` option](https://v2.nuxt.com/docs/configuration-glossary/configuration-build/#transpile) that does this part.
