### ISSUE TITLE
Add formal browser support table

### ISSUE THREAD

**Issue by davewallace** [ueberdosis/tiptap#371]
**Is your feature request related to a problem? Please describe.**
Officially supported browsers are a major consideration for any UI component we'd ever consider, I see in issue there's mentions of things being fixed for IE11, IE9 possibly too? 

**Describe the solution you'd like**
Would be great if this were right up front on your .io homepage.

**Describe alternatives you've considered**
Any UI component we'd look elsewhere if the browser compat didn't fit our requirements.

**Additional context**
Considering this plugin in a global enterprise platform, big responsibility for us to make the right decision. Also a good opportunity for this project :D

**Comment by philippkuehn** [comment]
Yeah, a list of supported browsers would be nice. I dropped IE support a while ago. So Edge and evergreen.

**Comment by davewallace** [comment]
Did you have a working branch or anything where you were supporting IE11 but then stopped? Depending on the problems you were solving that IE11 couldn't handle (particular ES6 language features? performance?) our team might be interested in seeing if it's workable for us (and anyone else who still needs IE11 support... there's sadly still quite a few of us).

**Comment by hanspagel** [comment]
Thanks for the suggestion! Added this table to the README.
