### ISSUE TITLE
The entrypoint for '@tiptap/extension-blockquote' could not successfully be resolved. The file '/turbo_modules/@tiptap/extension-blockquote@2.0.0-beta.212/dist/index.d.cjs' does not exist.

### ISSUE THREAD

**Issue by splincode** [ueberdosis/tiptap#3717]
### What’s the bug you are facing?

<img width="925" alt="image" src="https://user-images.githubusercontent.com/12021443/217267751-07a1ae95-cfc8-4122-996e-cf5e9aabcfae.png">

### Which browser was this experienced in? Are any special extensions installed?

Chrome 109, MacOS

### How can we reproduce the bug on our side?

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/12021443/217267528-4bda1d76-5cec-4985-a6cf-0c0c8f4afb1e.png">

https://stackblitz.com/edit/angular-pj96to?file=src%2Fapp%2F%40stackblitz%2Fall-taiga-modules.ts&hideExplorer=1

### What did you expect to happen?

Not error

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by splincode** [comment]
https://github.com/ueberdosis/tiptap/pull/3716

**Comment by bdbch** [comment]
I just released `2.0.0-beta.214` which uses our old build process with a few minor changes and the new PM package. Would be nice to see if this fixes the issues introduced by the esbuild builds.

**Comment by splincode** [comment]
https://github.com/Tinkoff/taiga-ui/pull/3626
Our test are failed
<img width="770" alt="image" src="https://user-images.githubusercontent.com/12021443/217517432-8dd4b5bc-d212-4ced-9c52-99378b33078c.png">

**Comment by bdbch** [comment]
Could you try again with the most recent package?

**Comment by splincode** [comment]
fixed
