### ISSUE TITLE
Extensions not showing in NextJS

### ISSUE THREAD

**Issue by codewithbernard** [ueberdosis/tiptap#3722]
### What’s the bug you are facing?

I followed the instruction in the Docs: https://tiptap.dev/installation/nextjs

But the extensions are not showing in the editor. Only the content is visible.

### Which browser was this experienced in? Are any special extensions installed?

Chrome

### How can we reproduce the bug on our side?

Just follow the instructions: https://tiptap.dev/installation/nextjs

### What did you expect to happen?

A working editor

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by jeffrafter** [comment]
Which extensions are you expecting to see and not see? When you type are the input rules working? The example is working for me in a Next 13 application. If you are expecting to see the MenuBar and MenuItem components those are separate. If you have example code we might be able to help more.

**Comment by jeffrafter** [comment]
Might also be related to https://github.com/ueberdosis/tiptap/issues/3689

**Comment by codewithbernard** [comment]
You can check out my repo: https://github.com/codewithbernard/my-tiptap-project

I expect to see everything from StarterKit. I don't see anything, only the area where I can write the content.

Not sure if it's related, but my build is not broken. Everything builds properly and I don't see any errors popping up.

**Comment by jeffrafter** [comment]
> I expect to see everything from StarterKit. I don't see anything, only the area where I can write the content.

Ah, I think there is some confusion. The extensions that TipTap offers are extensions _within_ the editor. In your example if you run it and start a line with `## Heading` you will see that the extensions are working (same with bold, italic etc). TipTap the editor does not give you the buttons for those things - that is all part of your application and user interface. In your example you only have the editor. Luckily there are quite a few examples on how to make a menu that can control the editor: 

https://github.com/ueberdosis/tiptap/blob/main/demos/src/Examples/Default/React/index.jsx#L211

**Comment by codewithbernard** [comment]
Oh. I was confused indeed. Thank you for clarifying this. Will close the issue now.
