### ISSUE TITLE
Custom Quiz Extension

### ISSUE THREAD

**Issue by RahulBansal123** [ueberdosis/tiptap#3734]
### What’s the bug you are facing?

I am trying to create a custom quiz extension in which users can add a heading and options in it, but it is not working as expected.

### Which browser was this experienced in? Are any special extensions installed?

Brave

### How can we reproduce the bug on our side?

Import the custom extension in the editor's list and paste the above code.

### Can you provide a CodeSandbox?
`
import { mergeAttributes, Node } from '@tiptap/core';

export interface QuizOptions {
  itemTypeName: string;
  HTMLAttributes: Record<string, any>;
}

declare module '@tiptap/core' {
  interface Commands<ReturnType> {
    quiz: {
      /**
       * Inserts a quiz
       */
      insertQuiz: () => ReturnType;
    };
  }
}

export const Quiz = Node.create<QuizOptions>({
  name: 'quiz',

  addOptions() {
    return {
      itemTypeName: 'quizList',
      HTMLAttributes: {},
    };
  },

  group: 'block',

  content() {
    return `heading ${this.options.itemTypeName}*`;
  },

  parseHTML() {
    return [
      {
        tag: `quiz`,
        priority: 52,
      },
    ];
  },

  renderHTML({ HTMLAttributes }) {
    return [
      'quiz',
      mergeAttributes(this.options.HTMLAttributes, HTMLAttributes, {
        class: 'tiptap-quiz',
      }),
      0,
    ];
  },

  addCommands() {
    return {
      insertQuiz:
        () =>
        ({ chain }) => {
          return chain()
            .setHeading({ level: 1 })
            .toggleQuizList()
            .focus()
            .run();
        },
    };
  },

  addKeyboardShortcuts() {
    return {
      'Mod-Shift-9': () => this.editor.commands.insertQuiz(),
    };
  },
});`

### What did you expect to happen?

It should display a heading and <li> tags for the user to add options.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Could you please create a running CodeSandbox example for this issue? Also what is not working as expected? Looking forward to help.
