### ISSUE TITLE
⚠️ The warning sign emoji is not showing up correctly, it maybe a font-family issue.

### ISSUE THREAD

**Issue by HelloBojack** [ueberdosis/tiptap#3736]
### What’s the bug you are facing?

incorrect:
<img width="486" alt="image" src="https://user-images.githubusercontent.com/39325783/218021948-e062c527-cdcd-4dbb-97cf-dfdc49167dc2.png">
correct:
<img width="344" alt="image" src="https://user-images.githubusercontent.com/39325783/218021997-42078a15-b893-408d-ad72-75fe14f5b47c.png">

### Which browser was this experienced in? Are any special extensions installed?

Macbookc Pro M1 & Chrome 110.0.5481.77

### How can we reproduce the bug on our side?

Entering the ⚠️ warning emoji into the editor may cause it to display incorrectly.

### What did you expect to happen?

I hope the warning sign emoji will display correctly.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
This seems to be an issue with your font. I just tried this in our demos - seems like `Inter` for example does include a different char for that emoji. Not sure to be honest as I'm not as deep into how fonts display specific characters.

But with the default `sans-serif` font provided by my system, the emoji was visible.

<img width="349" alt="image" src="https://user-images.githubusercontent.com/6538827/220919553-c094d46d-028f-4f9b-80e9-7386254a1292.png">
