### ISSUE TITLE
how can I disabled ol tag in ListItem

### ISSUE THREAD

**Issue by sk31park** [ueberdosis/tiptap#3740]
### What’s the bug you are facing?

how can I disabled ol tag in ListItem

I want only use 'ul' tag.
'ol' tag auto generate when I type number + '.' character

this is my code
```
import { BubbleMenu, Editor, EditorContent } from '@tiptap/vue-2'
import ListItem from '@tiptap/extension-list-item'
```

### Which browser was this experienced in? Are any special extensions installed?

.

### How can we reproduce the bug on our side?

.

### Can you provide a CodeSandbox?

.

### What did you expect to happen?

how can I disabled ol tag in ListItem

I want only use 'ul' tag.
'ol' tag auto generate when I type number + '.' character

this is my code
```
import { BubbleMenu, Editor, EditorContent } from '@tiptap/vue-2'
import ListItem from '@tiptap/extension-list-item'
```

### Anything to add? (optional)

.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Do you use the StarterKit? If so you can disable the orderedLists via this:

```
StarterKit.configure({
  orderedList: false,
})
```

if you don't use the StarterKit simply don't register the `@tiptap/extension-ordered-list` extension.
