### ISSUE TITLE
@tiptap/starter-kit needs a dependency on @tiptap/pm

### ISSUE THREAD

**Issue by Naddiseo** [ueberdosis/tiptap#3746]
### What’s the bug you are facing?

When using yarn, as of version beta-205 when the peerDependencies were added, yarn started complaining that @tiptap/starter-kit doesn't provide @tiptap/pm:
```
yarn add @tiptap/react @tiptap/pm @tiptap/starter-kit @tiptap/extension-color @tiptap/extension-text-style
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @app@workspace:. doesn't provide @tiptap/core (pe9703), requested by @tiptap/extension-color
➤ YN0002: │ @app@workspace:. doesn't provide @tiptap/core (p1d459), requested by @tiptap/extension-text-style
➤ YN0002: │ @app@workspace:. doesn't provide @tiptap/core (p5a2b6), requested by @tiptap/pm
➤ YN0002: │ @app@workspace:. doesn't provide @tiptap/core (pd2b52), requested by @tiptap/react
➤ YN0002: │ @tiptap/starter-kit@npm:2.0.0-beta.217 doesn't provide @tiptap/pm (p625a0), requested by @tiptap/core
➤ YN0002: │ @tiptap/starter-kit@npm:2.0.0-beta.217 doesn't provide @tiptap/pm (pe2f09), requested by @tiptap/extension-code-block
➤ YN0002: │ @tiptap/starter-kit@npm:2.0.0-beta.217 doesn't provide @tiptap/pm (p75487), requested by @tiptap/extension-dropcursor
➤ YN0002: │ @tiptap/starter-kit@npm:2.0.0-beta.217 doesn't provide @tiptap/pm (pfd7ed), requested by @tiptap/extension-gapcursor
➤ YN0002: │ @tiptap/starter-kit@npm:2.0.0-beta.217 doesn't provide @tiptap/pm (p17b8a), requested by @tiptap/extension-history
➤ YN0002: │ @tiptap/starter-kit@npm:2.0.0-beta.217 doesn't provide @tiptap/pm (p5659a), requested by @tiptap/extension-horizontal-rule
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
```

I had a look at [the documentation](https://yarnpkg.com/advanced/error-codes#yn0002---missing_peer_dependency) for YN0002, and it describes the issue that transient dependencies need to satisfied by the parent dependency. Since the dependencies of starter-kit have a peerDependency on `@tiptap/pm`, then starter-kit needs to have it as a dependency

### Which browser was this experienced in? Are any special extensions installed?

n/a

### How can we reproduce the bug on our side?

using yarn 3 in a blank project:
```
$ yarn add @tiptap/react @tiptap/pm @tiptap/starter-kit @tiptap/extension-color @tiptap/extension-text-style
```

### What did you expect to happen?

There should be no warnings

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by Naddiseo** [comment]
A workaround I've found for now is to add the following to my `.yarnrc.yml`
```yaml
packageExtensions:
  "@tiptap/starter-kit@*":
    peerDependencies:
      "@tiptap/pm": "*"
```

**Comment by Naddiseo** [comment]
as far as I can tell this is still an issue

**Comment by nperez0111** [comment]
Will resolve this in the next version
