### ISSUE TITLE
Newline not appearing when setting content in editor

### ISSUE THREAD

**Issue by DanishOnGit** [ueberdosis/tiptap#3754]
### What’s the bug you are facing?

**Editor is not rendering newline (\n) from the string**:
I type  my code as foll into the editor:
```
def solve(str):
  # write code here
  return -1

# driver code
str = input()
result = solve(str)
print(result)
```
------
Then I use `editor.getText( )` as payload shown below:

   payload : `"def solve(str):\n\t# WRITE CODE HERE\n\treturn '-1'\n\nN1 = input()\n\nresult = solve(N1)\nprint(result)\n"`
      
  You can see there are new line characters (\n) in the payload above.
------
I receive the exact same string in response which I sent as the payload above:
response: `"def solve(str):\n\t# WRITE CODE HERE\n\treturn '-1'\n\nN1 = input()\n\nresult = solve(N1)\nprint(result)\n"`
Now when I try to paste this response into the editor using=> editor.commands.setContent(response);
Here is where I lose the formatting. The editor pastes it as a single long string without any new-line as below:
`def solve(str): # WRITE CODE HERE return '-1' N1 = input() result = solve(N1) print(result)`

### Which browser was this experienced in? Are any special extensions installed?

Chrome Windows 10. No special extensions installed

### How can we reproduce the bug on our side?

Just try the foll:
const x = 'hello\n\nsir';
editor.commands.setContent(x);

Expected output:
`hello

sir
`

Actual output:
`hello sir`

### Can you provide a CodeSandbox?

https://codesandbox.io/s/vigorous-lake-2johof?file=/src/App.js

### What did you expect to happen?

Expected output:
`hello

sir`

hello and sir both should be on new lines

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by codemzy** [comment]
Have you tried setting `parseOptions` in the editor? https://tiptap.dev/api/editor#parse-options

```js
new Editor({
  parseOptions: {
    preserveWhitespace: 'full',
  },
});
```

You will also need to pass this setting when updating the content with `setContent`:

```js
  useEffect(() => {
    if (!editor) return;
    const x = `hello\n\nsir`;
    editor.commands.setContent(x, false, {
      preserveWhitespace: "full",
    })
  }, [editor]);
```

That should solve this I think!

> By default, whitespace is collapsed as per HTML's rules. Pass true to preserve whitespace, but normalize newlines to spaces, and "full" to preserve whitespace entirely.

**Comment by DanishOnGit** [comment]
Hey @codemzy  Thank you soooooo mucchhh!! This fixed the issue  ♥

**Comment by jiale01** [comment]
@codemzy Hey, I implemented line breaks just like you did, but I type any character in the editor and all the line breaks disappear, you know why, thank you

**Comment by izotikov** [comment]
> [@codemzy](https://github.com/codemzy) Hey, I implemented line breaks just like you did, but I type any character in the editor and all the line breaks disappear, you know why, thank you

Have you found a solution?
