### ISSUE TITLE
suggestion query is not always properly replaced when using sl-popup from shoelace with the mentions extension

### ISSUE THREAD

**Issue by iamcodemaker** [ueberdosis/tiptap#3760]
### What’s the bug you are facing?

Sometimes, when selecting an item from the mention pop up menu, the query text is not replaced. I spent some time trying to debug this and it appears that when the pop up is clicked, this messes up the range used to perform the text replacement. It's always a single position long.

### Which browser was this experienced in? Are any special extensions installed?

Both firefox and chrome exhibit this behavior.

### How can we reproduce the bug on our side?

1. Start typing a mention in the editor using the `@` key.
2. Type a few characters.
3. Click an option from the drop down menu.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/tiptap-suggestion-with-shoelace-popup-1ofs64?file=/src/my-editor.ts

### What did you expect to happen?

I expect the mention query text to be replaced by the selected mention.

### Anything to add? (optional)

My setup is perhaps a bit unorthodox. I'm trying to use tiptap inside of a web component. Additionally, the menu [popup](https://shoelace.style/components/popup) I'm using is another web component from the [shoelace](https://shoelace.style) component library. I'm not sure how these two things are interacting with the editor state, if at all. So far I've gotten everything working, except for this (I also needed the [workaround described here](https://github.com/ProseMirror/prosemirror/issues/1113)).

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by iamcodemaker** [comment]
I found the problem. I'm storing the `props.command()` callback from the `onStart()` callback, so the state associated with the mention at the `onStart()` callback is what is being used for the replacement. I've worked around it by updating the callback on each call to `onUpdate()`. That fixes the issue.

**Comment by Hrishikesh-K** [comment]
@iamcodemaker thank you so much for posting your solution. I was running into the exact same thing and I could not have figured this out myself! I was just about to open a new issue until I decided to look for existing issues!

**Comment by stefanholzapfel** [comment]
@iamcodemaker thank you so much, I encountered the same pitfall

**Comment by fernandolangaro** [comment]
@iamcodemaker you are awesome!! thanks for sharing your solution, I was facing the same thing here
