### ISSUE TITLE
The onBlur event isn't triggered on Firefox when the component is unmounted

### ISSUE THREAD

**Issue by joelbqz** [ueberdosis/tiptap#3761]
### What’s the bug you are facing?

The onBlur event isn't triggered on Firefox when the component is unmounted

### Which browser was this experienced in? Are any special extensions installed?

Firefox

### How can we reproduce the bug on our side?

**Chrome**
1. Write something
2. Press enter
3. An alert indicating the onBlur event has been fired should appear

**Firefox**
1. Write something
2. Press enter
3. No alert appears, the `onBlur` event hasn't fired

### Can you provide a CodeSandbox?

https://codesandbox.io/s/vigorous-stitch-ggrfmj?file=/src/App.js

### What did you expect to happen?

The same behavior as in Chrome

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by JanBlazejczyk** [comment]
I had similar issue, on Chrome onBlur handler is firing correctly (every time the editor is losing focus), but on Firefox (and Safari) it is not. I solved my issue by creating custom event handler for mousedown event occurring anywhere outside my component and putting the logic from onBlur there. React example here: https://stackoverflow.com/questions/32553158/detect-click-outside-react-component
