### ISSUE TITLE
Inconsistent behaviour with color and list items. Hard breaks will loose styling if executed at the end of a list item

### ISSUE THREAD

**Issue by patmifsud** [ueberdosis/tiptap#3768]
### What’s the bug you are facing?

I'm using the color and list item extensions. When I hit a hard return on a list item, I expect the next list item to have the same styling, similar to Google Docs or many other text editors. This will work if the hard return is hit before the last character (e.g. before a trailing space) but not right at the end of the line. This is contrary to the way that paragraphs work in TipTap, where hitting a hard return at the end of the element copies over styling onto the next line too.

### Which browser was this experienced in? Are any special extensions installed?

Chrome, Mac. React project

### How can we reproduce the bug on our side?

Here is an example with instructions to reproduce 
https://codesandbox.io/s/react-tiptap-editor-richt-html-forked-r8ute1?file=/src/Tiptap/MenuBar.jsx

### What did you expect to happen?

Color and other formatting should have consistent behaviour between list items and paragraphs, ideally copying over styling as with Google Docs 

### Anything to add? (optional)

I hope this is the right place to put this! I wasn't sure if this is classified as a bug, apologies if not. 

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by patmifsud** [comment]
It looks like this open and approved PR might solve my issue, only just saw it now  https://github.com/ueberdosis/tiptap/pull/3541

**Comment by bdbch** [comment]
just merged #3541 - after the next release we could test this behavior again.

**Comment by gethari** [comment]
@patmifsud can you confirm if the latest changes are working as expected for you ?
