### ISSUE TITLE
editor.isEditable is not reactive

### ISSUE THREAD

**Issue by eta-orionis** [ueberdosis/tiptap#3775]
### What’s the bug you are facing?

editor.isEditable does not reactively change after calling editor.setEditable(true)
As a result, the UI, and especially node views, cannot adapt to whether the editor is read-only or not.

### Which browser was this experienced in? Are any special extensions installed?

Chrome

### How can we reproduce the bug on our side?

Open any of your examples with editable: false

Add 
 ```<div v-if="editor.isEditable">Shown if isEditable changes</div>``` anywhere where ```editor``` is in scope

Programmatically change ```editable``` to ```true```
Verify that the above div is not shown.

### Can you provide a CodeSandbox?

https://codesandbox.io/s/laughing-lucy-xqex4f?file=/package.json

### What did you expect to happen?

I expected editor.isEditable to be reactive and to change when editable is set to true.
Alternatively, exposing the change of the "editable" property as an event would be nice.

### Anything to add? (optional)

The .beta-2xx packages after 210 seem to not work with the issue template, so I updated to the latest I could without errors.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Hey @eta-orionis.

The editor object by itself is not reacting to changes unless the editor state is updated.

You can do something like the following to handle reactivity by yourself:

```js
editor.on('update', ({ editor }) => {
  // set state via refs or whatever state management solution you are using
  this.isEditable = editor.isEditable
})
```

This will use Vue's reactivity system.
