### ISSUE TITLE
tiptap react: BubbleMenu: failed to remove child

### ISSUE THREAD

**Issue by bagindo** [ueberdosis/tiptap#3784]
### What’s the bug you are facing?

Error: Uncaught DOMException: Failed to execute 'removeChild' 

when a component with Tiptap editor using BubbleMenu is removed.

### Which browser was this experienced in? Are any special extensions installed?

Any browser. Extension: BubbleMenu.

### How can we reproduce the bug on our side?

On the codesandbox below, click the div "Hello World", then click save.

it works fine if BubbleMenu is commented out on Tiptap.tsx

### Can you provide a CodeSandbox?

https://codesandbox.io/p/sandbox/mystifying-currying-0xisdc

### What did you expect to happen?

doesn't give error failed to remove child.

### Anything to add? (optional)

might be related to https://github.com/ueberdosis/tiptap/issues/2658

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by upview** [comment]
I have the same issue here, error is triggered when component is unmounted.

**Comment by upview** [comment]
So adding a <div> around the bubble menu solved it for me.

```
        <div>
          <BubbleMenu editor={editor} tippyOptions={{ duration: 100 }}>
...
          </BubbleMenu>
        </div>
```

Similar fix than https://github.com/ueberdosis/tiptap/issues/2658 for the editor component.

**Comment by bagindo** [comment]
@upview ah yes thanks! I tried your fix wrapping div on EditorContent, and it didn't work. 
Should've tried it on the <BubbleMenu /> directly. It works.

**Comment by Rajgupta36** [comment]
thanks @upview ,working for me as well
