### ISSUE TITLE
TypeScript error: Property does not exist on type 'ChainedCommands'

### ISSUE THREAD

**Issue by songhn233** [ueberdosis/tiptap#3785]
### What’s the bug you are facing?

Same as https://github.com/ueberdosis/tiptap/issues/2867, But because this problem seems to be repeated, I launched a new issue.

### Which browser was this experienced in? Are any special extensions installed?

Chrome Latest

### How can we reproduce the bug on our side?

Although I have pin Typescipt version:

<img width="617" alt="image" src="https://user-images.githubusercontent.com/47357585/221021248-aad4d76a-823e-4536-878b-81b173ad1075.png">

But also throw type errors:

<img width="983" alt="image" src="https://user-images.githubusercontent.com/47357585/221021345-293def66-6d2f-4d5d-ab18-e0c1622601c0.png">

### What did you expect to happen?

Typescript Correctly

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Hey @songhn233 

Do you have all required extensions installed? `@tiptap/starter-kit` should provide those typings to the core command types.

Does this also happen for commands provided by other extensions?

**Comment by songhn233** [comment]
> Hey @songhn233
> 
> Do you have all required extensions installed? `@tiptap/starter-kit` should provide those typings to the core command types.
> 
> Does this also happen for commands provided by other extensions?

@bdbch My package.json:

```json
    "@tiptap/pm": "2.0.0-beta.218",
    "@tiptap/react": "2.0.0-beta.218",
    "@tiptap/extension-placeholder": "2.0.0-beta.218",
    "@tiptap/starter-kit": "2.0.0-beta.218",
```

And starter-kit will throw error:

<img width="944" alt="image" src="https://user-images.githubusercontent.com/47357585/221230627-7d13eb55-5ddb-4f18-a40c-5bd4e30c2719.png">

`Property 'toggleBold' does not exist on type 'ChainedCommands'. Did you mean 'toggleNode'?`

**Comment by bdbch** [comment]
What kind of Setup are you using / what's your tsconfig looking like? I'm quite confused as I didn't see this issue yet.

**Comment by songhn233** [comment]
> What kind of Setup are you using / what's your tsconfig looking like? I'm quite confused as I didn't see this issue yet.

Start with vite + react

My client tsconfig:

```json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "allowJs": false,
    "allowSyntheticDefaultImports": true,
    "baseUrl": ".",
    "esModuleInterop": false,
    "isolatedModules": true,
    "jsx": "react",
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "module": "ESNext",
    "noEmit": true,
    "paths": {
      "~/*": ["src/*"]
    },
    "resolveJsonModule": true,
    "skipLibCheck": false,
    "target": "ESNext",
    "types": ["vite/client"]
  }
}
```

extended tsconfig:

```json
{
  "compilerOptions": {
    "allowJs": true,
    "declaration": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "incremental": true,
    "keyofStringsOnly": true,
    "module": "ES2020",
    "moduleResolution": "node",
    "removeComments": true,
    "resolveJsonModule": true,
    "sourceMap": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "ES2019"
  },
  "exclude": ["**/node_modules/*", "**/dist/*", "scripts/*"]
}
```

**Comment by songhn233** [comment]
> What kind of Setup are you using / what's your tsconfig looking like? I'm quite confused as I didn't see this issue yet.

@bdbch Hey, I have resolved this issue. The reason was the impact of blocknote. Specifically, blocknote was using beta.217 underhood while I installed tiptap with beta.218. There might be another reason related to pnpm. After removing blocknote dependencies and using the `pnpm prune` command, I reloaded typescript project, and the type issue was resolved.

**Comment by fshafiee** [comment]
Using `@tiptap/v2.0.1` with an **ESM Typescript** project, basically all type definitions are broken due to missing extensions in import statements. Had to patch all packages (using `yarn patch`) and fix import statements by adding `.js` to get rid of this problem. I believe this needs fixing on @tiptap side since the package type has been changed to `module` in all of @tiptap packages and ESM standard requires the extensions to be specified.

**Comment by svenadlung** [comment]
@fshafiee the issue you raised is related [to this](https://github.com/ueberdosis/tiptap/issues/3488), right? 

Since the initial problem seems to be solved, I would close here and continue the other topic in the other issue.
