### ISSUE TITLE
Strange cursor issue in Firefox when draggable:true

### ISSUE THREAD

**Issue by lpellis** [ueberdosis/tiptap#379]
**Describe the bug**
When you set the draggable:true on the scheme for a component that has an input (such as the 'embeds' example) you cannot click on the input, the cursor focus goes all the way to the end of the line and behaves kinda erratic. (Firefox only, works in Chrome)

**Steps to Reproduce / Codesandbox Example**
This is just the 'embeds' example with draggable:true
https://codesandbox.io/s/vue-issue-template-swfvq

**Expected behavior**
You should be able to click on the input, works in Chrome

**Comment by laurensiusadi** [comment]
Same issue happen on the examples https://tiptap.scrumpy.io/drag-handle
Drag doesn't in Firefox.

But TodoList drag works https://tiptap.scrumpy.io/todo-list when using todo box as handle

**Comment by Inzeppelin** [comment]
@lpellis have you resolved this one yet? could you please share any suggestions?

**Comment by lpellis** [comment]
I had to work around it, couldnt find a fix :(
Basically make sure input elements are outside of contenteditable areas
