### ISSUE TITLE
Support for functional vue components

### ISSUE THREAD

**Issue by eriknygren** [ueberdosis/tiptap#380]
Hi there,

I was wondering about support for functional vue components for custom nodes.

I've had a go at creating them here https://codesandbox.io/s/tiptap-functional-view-component-4d450 but it doesn't seem to work out of the box.

```javascript
[Vue warn]: Error in nextTick: "TypeError: dom.hasAttribute is not a function"
TypeError: dom.hasAttribute is not a function`
```

Is it something that hasn't been considered yet, or are there technical constraints that makes it difficult to implement?

The reason I want them, is because I want to create a lot of custom nodes, and they don't need a unique `this` context, so the cheaper they would be to render/destroy the better!

Thanks

**Comment by kelunik** [comment]
As [functional components are basically deprecated and mostly gone from Vue 3](https://v3.vuejs.org/guide/migration/functional-components.html), it's probably fine to close this feature request, no?

**Comment by hanspagel** [comment]
Good point! Yes, I think so too.
