### ISSUE TITLE
BubbleMenu loses debounce functionality when using a custom `shouldShow` function

### ISSUE THREAD

**Issue by katerlouis** [ueberdosis/tiptap#3801]
### What’s the bug you are facing?

I want to disable my bubble menu when a horizontal rule is selected (or show a different one), but when I use `shouldShow`-prop with a function in vue 2, where I apply logic and return either `true` or `false`, the bubble menu is shown instantly. Also it shows without selecting anything. 

While it's easy to check for `if (from === to) return false`, it's not so straight forward to recreate the debounced behavior. 

### Which browser was this experienced in? Are any special extensions installed?

All browsers; No special extensions.

### How can we reproduce the bug on our side?

Add a bubble menu configured with this function as `shouldShow()` : 

```js
shouldShow: ({ editor, from, to }) => {
  if (from === to) {
    return false;
  }

  if (editor.isActive('horizontalRule')) {
    return false;
  }

  return true;
},
```
```

### Can you provide a CodeSandbox?

_No response_

### What did you expect to happen?

I expect the update logic to remain the same, just not for the `horizontalRule`

### Anything to add? (optional)

_No response_

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by xinghul** [comment]
can we reopen this please? this is a real issue that needs attention.
