### ISSUE TITLE
Failed to resolve entry for package "@tiptap/pm"

### ISSUE THREAD

**Issue by Skia69** [ueberdosis/tiptap#3803]
### What’s the bug you are facing?

Hello, I'm getting the following error every time i try to build my app

`Failed to resolve entry for package "@tiptap/pm". The package may have incorrect main/module/exports specified in its package.json: Missing "." export in "@tiptap/pm" package`

I attached a screenshot regarding my dependencies,
Also keep in mind that i'm using vite 

![Screenshot 2023-02-28 155837](https://user-images.githubusercontent.com/42115721/221878614-904b1544-2f17-4569-9af8-1a79d7e985f0.png)

For more clarity, here's the error i'm getting:
![Screenshot 2023-02-28 162721](https://user-images.githubusercontent.com/42115721/221887161-939ed8f1-c557-4157-9749-f7820660fe88.png)

### Which browser was this experienced in? Are any special extensions installed?

-

### How can we reproduce the bug on our side?

-

### What did you expect to happen?

I expected the project to build successfully

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Can you check if @tiptap/pm is in your node_modules folder? @Skia69

**Comment by bdbch** [comment]
Did you figure out a solution @Skia69?
