### ISSUE TITLE
@tiptap/react@2.0.0-beta.220" has unmet peer dependency "@tiptap/core@^2.0.0-beta.209

### ISSUE THREAD

**Issue by dd-jonas** [ueberdosis/tiptap#3805]
### What’s the bug you are facing?

It looks like the peer dependencies have not been updated since beta.209. I'm getting this warning on every tiptap package (@tiptap/react, @tiptap/pm, @tiptap/extension-*).

### Which browser was this experienced in? Are any special extensions installed?

N/A

### How can we reproduce the bug on our side?

Install any package above beta.209 that relies on @tiptap/core

### What did you expect to happen?

No peer dependency error

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by svenadlung** [comment]
Please try to use version 2.0.0 packages and be sure lock file is up to date. If this is still an issue, let me know and I'll reopen.
