### ISSUE TITLE
Program error after vite lib mode packaging:Adding different instances of a keyed plugin (plugin$) 

### ISSUE THREAD

**Issue by popdo** [ueberdosis/tiptap#3806]
### What’s the bug you are facing?

My development environment is vite4+vue3+ts
When I used tiptap 2.0.0-beta220 for secondary development and packaging, I found that the package size exceeded 500kb, so I excluded it when packaging vite lib

```ts
rollupOptions: {
  external: [
    'vue',
    '@tiptap/pm',
    '@tiptap/core',
    '@tiptap/vue-3'
  ],
}
```

The volume of the packet becomes 375kb, which is basically acceptable. But the problem is that when I introduce my lib packaged file into the project, I also install it

```sh
pnpm i @tiptap/pm @tiptap/core @tiptap/vue-3
```

The console reported an error:

```
Uncaught RangeError: Adding different instances of a keyed plugin (plugin$) 
```

What is the reason for the error? I installed the dependency of tiptap in the project, but why would I report an error?

### Which browser was this experienced in? Are any special extensions installed?

Installed most of the official extensions

### How can we reproduce the bug on our side?

None

### What did you expect to happen?

Find the root cause of the problem

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by popdo** [comment]
Moreover, I found that it is invalid to exclude only '@ tiptap/pm' alone. The volume of the package has no change at all

**Comment by bdbch** [comment]
Do you have prosemirror-state installed from somewhere else? This sounds like the `prosemirror-state` package is imported twice (Once from `@tiptap/pm` and once from somewhere else)

**Comment by popdo** [comment]
> Do you have prosemirror-state installed from somewhere else? This sounds like the `prosemirror-state` package is imported twice (Once from `@tiptap/pm` and once from somewhere else)

It has been from

```ts
import { Plugin, PluginKey } from  'prosemirror-state'
```

After upgrading to '2.0.0 beta. 220', I have changed all to:

```ts
import { Plugin, PluginKey } from '@tiptap/pm/state'
```

And all custom extensions have been checked. It is true that there is no separate introduction of 'prosemirror - *'. I cleared 'pnpm-lock. yaml' and reinstalled all dependent packages, and still reported this error message.

**Comment by popdo** [comment]
Find the reason. When I exclude and package all the dependent packages under '@ tiptap/pm', the volume of the lib package is only 230kb.

```ts
external: [
  'vue',
  '@tiptap/core',
  '@tiptap/vue-3',
  '@tiptap/pm',
  '@tiptap/pm/changeset',
  '@tiptap/pm/collab',
  '@tiptap/pm/commands',
  '@tiptap/pm/dropcursor',
  '@tiptap/pm/gapcursor',
  '@tiptap/pm/history',
  '@tiptap/pm/inputrules',
  '@tiptap/pm/keymap',
  '@tiptap/pm/markdown',
  '@tiptap/pm/menu',
  '@tiptap/pm/model',
  '@tiptap/pm/schema-basic',
  '@tiptap/pm/schema-list',
  '@tiptap/pm/state',
  '@tiptap/pm/tables',
  '@tiptap/pm/trailing-node',
  '@tiptap/pm/transform',
  '@tiptap/pm/view',
]
```

And the project can finally run normally!

**Comment by bdbch** [comment]
Great, happy to hear you figured out a solution!
