### ISSUE TITLE
Horizontal rule by input rule adds extra paragraph node above

### ISSUE THREAD

**Issue by thefinnomenon** [ueberdosis/tiptap#3809]
### What’s the bug you are facing?

When adding a horizontal rule using an input rule (--- or ___ ), it adds an empty paragraph node before the divider node.

### Which browser was this experienced in? Are any special extensions installed?

Doesn't apply.

### How can we reproduce the bug on our side?

You can recreate it in the horizontal rule playground https://tiptap.dev/api/nodes/horizontal-rule
enter ---

### What did you expect to happen?

I expect it to only add the divider

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by rfgamaral** [comment]
Yes, I use horizontal rules a lot, and this one is very annoying. Hope it gets some attentiont soon, it shouldn't be too hard to fix 😅

**Comment by rfgamaral** [comment]
Still valid.

**Comment by steven-tey** [comment]
@rfgamaral @thefinnomenon here's a patch for this that worked for me: https://github.com/ueberdosis/tiptap/pull/3859#issuecomment-1536799740

**Comment by thefinnomenon** [comment]
Thanks, yeah I have been using that patch and it works perfectly!

**Comment by rfgamaral** [comment]
Thank you, @steven-tey.
