### ISSUE TITLE
collaboration-cursor freeze on selection with dark reader extension in chrome

### ISSUE THREAD

**Issue by L0laapk3** [ueberdosis/tiptap#3818]
### What’s the bug you are facing?

The `collaboration-cursor` extension freezes as soon as anyone else in the document makes a selection in chrome (version 110.0.5481.178, 64bit on windows 11). Cannot reproduce in firefox, only chrome. Reproducing is simple as it even happens to your own example hosted at: [https://tiptap.dev/api/extensions/collaboration-cursor](https://tiptap.dev/api/extensions/collaboration-cursor).

### Which browser was this experienced in? Are any special extensions installed?

chrome 110.0.5481.178, 64bit on windows 11

### How can we reproduce the bug on our side?

1. go to [https://tiptap.dev/api/extensions/collaboration-cursor](https://tiptap.dev/api/extensions/collaboration-cursor) in the above mentioned chrome version
2. select some text
3. observe as the page freezes in an infinite loop

### Can you provide a CodeSandbox?

[https://tiptap.dev/api/extensions/collaboration-cursor](https://tiptap.dev/api/extensions/collaboration-cursor)

### What did you expect to happen?

it to not crash and work :)

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Weird - just tested it in Chrome and it seems to work for me. Do you have any extension installed or can you see console errors right before the crash occurs?

https://user-images.githubusercontent.com/6538827/222733591-0c955bd8-3091-4cc5-ba71-88674dc4a815.mp4

**Comment by L0laapk3** [comment]
Hi, it appears that you are correct in that an extension is causing the issue - I was a bit quick to assign the blame after having tried it in incognito which disables *most* of my extensions ;)

The culprit appears to be related to the "dark reader" extension, which is quite popular.

There is no error as the issue is a page freeze caused by an infinite loop. It appears to be related to CSS being applied by the extension.
![image](https://user-images.githubusercontent.com/6313423/222739965-8c99ccf8-7a52-4182-be19-ec9a331908cb.png)

**Comment by Rennix09** [comment]
@L0laapk3 hey, May I know how did you end up solving this problem?

**Comment by L0laapk3** [comment]
@Rennix09 afaik, this issue is still present in tiptap. I am however no longer part of the project where the issue occurred.

**Comment by Rennix09** [comment]
@L0laapk3  lol, thanks for the reply.

**Comment by nperez0111** [comment]
Can confirm that it is still present with the dark reader extension, strange! But I'm uncertain that it is something that is our fault or darkreader's

On top of that the cursor drawing logic is done by y-prosemirror & and the cursor plugin.

**Comment by Rennix09** [comment]
Yeah @nperez0111 , so I can only take disabling DarkReader to keep the page from crashing for the user. 

In my react app, I add the code snippet to disable DarkReader in spcific page that use tiptap. It works for me but DarkReader is not auto enabled after I leave this page until I refresh. 😢 
```
function TiptapPage () {
  ...
  useEffect(() => {
      const DARKREADER_LOCK_ID = 'custom-darkreader-lock';
      const metaSelector = `#${DARKREADER_LOCK_ID}`;
      const metaExists = document.querySelector(metaSelector) !== null;
      if (!metaExists) {
        const lock = document.createElement('meta');
        lock.name = 'darkreader-lock';
        lock.id = DARKREADER_LOCK_ID;
        document.head.appendChild(lock);
      }
      return () => {
        document.querySelector(metaSelector)?.remove();
      };
    }, []);
  ...
}
```

**Comment by nperez0111** [comment]
Looks like 2 existing issues on darkreader for this:

https://github.com/darkreader/darkreader/issues/8780
https://github.com/darkreader/darkreader/issues/12066

I can't make heads or tails of this github issue https://github.com/darkreader/darkreader/issues/2552 but it also looks like you can disable it with just a meta tag instead of having to use JS

**Comment by Rennix09** [comment]
Yep I can disable it but I want to make DarkReader work again once I removed the meta tag

**Comment by Rennix09** [comment]
@nperez0111 

From what I've seen so far, adding a meta using JS immediately disables DarkReader and my page goes from dark to light.

However, when I remove the meta, the page does not change from light to dark. 

Maybe consider having DarkReader listen to meta changes in the header to enable/disable it dynamically?

**Comment by Rennix09** [comment]
It looks like the problem is still in the DarkReader extension, and tiptap doesn't seem to be able to do anything about it.

Thanks again for the answer!
