### ISSUE TITLE
EnterKeyHint attribute support

### ISSUE THREAD

**Issue by jeeyoonhyun** [ueberdosis/tiptap#3820]
### What problem are you facing?

- When using Tiptap as a input box in mobile view, there is no option for setting the EnterKeyHint attribute.
- It will be great if we could support the EnterKeyHint attribute so that we can show different enter buttons in the mobile keyboard(Send, Search, Go, Return, ...), which leads to better UX

### What’s the solution you would like to see?

Supporting the [EnterKeyHint](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/enterkeyhint) attribute as an option, for better usability on mobile web

### What alternatives did you consider?

Tried to find a way to add the EnterKeyHint attribute with @tiptap/react but couldn't find

### Anything to add? (optional)

Thanks for maintaining tiptap!!!

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by punkpeye** [comment]
```
editorProps: {
  attributes: {
    enterKeyHint: 'send',
    role: 'textbox',
  },
},
```

This does it!
