### ISSUE TITLE
Selecting all text fails to insert suggestion

### ISSUE THREAD

**Issue by duncte123** [ueberdosis/tiptap#383]
**Describe the bug**
Doing a ctrl+a on the text in Tiptap and trying to replace it with a mention does not work.
It does, however, work when you select all text manually.

**Steps to Reproduce / Codesandbox Example**
1. Go to [the example suggestion page](https://tiptap.scrumpy.io/suggestions)
2. Remove all text and type one word
3. Press `ctrl+a` to select all text in the editor
4. Press the insert mention button
5. Double click the word
6. Press the insert mention button again

~~Fork this or create a new Codesandbox replicating your error~~

**Expected behavior**
All text should be replaced by the mention

**Environment**
 - OS: Ubuntu 18.04 and Mac OS 10.14.5
 - Browser Chrome
 - Version 75.0.3770.100
 - Mobile / Desktop: Desktop

**Comment by hanspagel** [comment]
Thanks for the report! This is (finally) going to be fixed with [tiptap v2](https://blog.ueber.io/post/our-plan-for-tiptap-2/). 😅
