### ISSUE TITLE
Collaboration cursor - Uncaught TypeError: can't access property "eq", this.members[i] is undefined

### ISSUE THREAD

**Issue by radim10** [ueberdosis/tiptap#3838]
### What’s the bug you are facing?

I'm having trouble using Collaboration cursor extension with Hocuspocus provider. I'm getting 
_Uncaught TypeError: can't access property "eq", this.members[i] is undefined_ error. Tried using different package versions without any luck. I'm using Hocuspocus provider with Sveltekit. 

Below is the code:
`let provider = new HocuspocusProvider({
      url: 'ws://localhost:1234',
      name: providerId,
      broadcast: true,
      token: $session.accessToken,
    })`

`let editor = new Editor({
        editable: false,
        element: element,
        extensions: [
          Collaboration.configure({
            document: provider.document,
          }),
          CollaborationCursor.configure({
            provider: provider,
            user: {
              name: 'Cyndi Lauper',
              color: '#f783ac',
            },
          }),
          StarterKit.configure({ history: false }),
          Placeholder.configure({
            placeholder: 'Write something',
          }),
          TextAlign.configure({
            types: ['heading', 'paragraph', 'bulletList'],
          }),
          CharacterCount.configure({}),
          Color.configure({
            types: ['textStyle'],
          }),
          Image,
        ],
      })`

Npm package version:
Frontend

`
    "@hocuspocus/provider": "^1.1.1",
    "@tiptap/core": "^2.0.0-beta.220",
    "@tiptap/extension-character-count": "^2.0.0-beta.31",
    "@tiptap/extension-collaboration": "^2.0.0-beta.220",
    "@tiptap/extension-collaboration-cursor": "^2.0.0-beta.220",
    "@tiptap/extension-color": "^2.0.0-beta.12",
    "@tiptap/extension-image": "^2.0.0-beta.30",
    "@tiptap/extension-placeholder": "^2.0.0-beta.53",
    "@tiptap/extension-text-align": "^2.0.0-beta.31",
    "@tiptap/extension-text-style": "^2.0.0-beta.26",
    "@tiptap/starter-kit": "^2.0.0-beta.189"
     "y-prosemirror": "^1.0.20",
    "yjs": "^13.5.48"
`

Backend

`
   "@hocuspocus/extension-logger": "^1.1.1",
    "@hocuspocus/server": "^1.1.1",
    "yjs": "^13.5.49"
`

### Which browser was this experienced in? Are any special extensions installed?

Collaboration + Collaboration Cursor extension

### How can we reproduce the bug on our side?

Copy the code and install packages.

### What did you expect to happen?

Working Collaboration cursor extension

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by KonnorRogers** [comment]
@radim10 I'm facing this issue when upgrading from beta 199 to 2.0.3, were you able to fix this?

**Comment by KonnorRogers** [comment]
Alright. I went back and checked history of RhinoEditor I removed the following packages:

```json
// Installed in NPM package
    "prosemirror-commands": "^1.5.1",
    "prosemirror-dropcursor": "1.5.0",
    "prosemirror-gapcursor": "^1.3.1",
    "prosemirror-history": "^1.3.0",
    "prosemirror-keymap": "^1.2.1",
    "prosemirror-model": "^1.19.0",
    "prosemirror-schema-list": "^1.2.2",
    "prosemirror-state": "^1.4.2",
    "prosemirror-transform": "^1.7.1",
    "prosemirror-view": "~1.29.0",
```

and then in the application I never installed these recommended peerDependencies:


```json

// DONT INSTALL THESE IN DEPENDENT PROJECT
    "prosemirror-model": "^1.7.1",
    "prosemirror-state": "^1.2.3",
    "prosemirror-view": "~1.30.2",
    "@tiptap/pm": "^2.0.3",
    "@tiptap/core": "^2.0.3"
```

I can't seem to pinpoint which peerDependency is causing the issue, or what prosemirror-dependency causes the fix, but heres a link to the PR on Rhino-Editor that fixed Collaboration Cursor for me:

https://github.com/KonnorRogers/rhino-editor/pull/69/files

FWIW, I'm also using PNPM.
