### ISSUE TITLE
insert html content at the current position 

### ISSUE THREAD

**Issue by reza-akbari** [ueberdosis/tiptap#385]
Hi, thank you for this great project.
I was looking for a way to insert HTML string at the current position and get it parsed automatically like when you paste the content into the editor.

currently I'm using `editor.commands` and custom methods like this:
````js
insertLinkWithText({ href }, text)
{
	const mark = this.editor.schema.marks.link.create({ href })
	const from = this.editor.state.selection.from
	const transaction = this.editor.state.tr.insertText(text + ' ')
	transaction.addMark(from, from + text.length, mark)
	this.editor.view.dispatch(transaction)
}
````
I also tried `setContent` with no luck

**Comment by ryanbliss** [comment]
Is there any reason why you aren't using the `Link()` extension in `tiptap-extensions`? You'll have a much easier time with this use case. Here is the example documentation: https://github.com/scrumpy/tiptap/tree/master/examples/Components/Routes/Links

**Comment by reza-akbari** [comment]
@ryanbliss thanks for your reply, how would I insert link with **href + text** at the current position? also I need a way to insert unknown HTML string (not just links) something like dynamically pasting content at the cursor position

**Comment by ryanbliss** [comment]
@reza-akbari I would make a custom NodeView if you are going to do that, but I imagine that use case is going to be really challenging to support. The links with text would be pretty easy just by slightly modifying the Link() node that Tiptap supports out of the box, but any generic HTML isn't really a good idea (inline vs. block, being an easy example that comes to mind).

**Comment by LordZombi** [comment]
There really isn't way to `insertHTML` at current position like `insertText`:
```
const transaction = this.editor.state.tr.insertText(body);
this.editor.view.dispatch(transaction);
```
?

**Comment by philippkuehn** [comment]
This will be in core for tiptap v2. For now here are the basics for it:

```js
import { DOMParser } from 'prosemirror-model'

function elementFromString(value) {
  const element = document.createElement('div')
  element.innerHTML = value.trim()

  return element
}

function insertHTML({ state, view }, value) {
  const { selection } = state
  const element = elementFromString(value)
  const slice = DOMParser.fromSchema(state.schema).parseSlice(element)
  const transaction = state.tr.insert(selection.anchor, slice.content)

  view.dispatch(transaction)
}
```

use it:


```js
insertHTML(edtitor, '<div>hey</div>')
```

**Comment by LordZombi** [comment]
Thanks a lot!

Works like a charm, but it adds an empty paragraph when I use it like this:
```
insertHTML(editor, '<p>Hello there</p>');
```

**Comment by jiamianmao** [comment]
insertHTML(editor, "<img src='https://www.xxxx.png' />")   is  error

**Comment by woodinteractive** [comment]
Did this ever get added?

**Comment by hanspagel** [comment]
We started to actively work on tiptap 2 in August and yes, we added insertHTML to it. :) That said, it’ll take some time until we release tiptap 2.

If you want to know more, subscribe to #547 ✌️

**Comment by tvld** [comment]
Really excellent :-)  This ``insertHtml.js`` extension seems to work for me:

```js 
import { Node } from 'tiptap'

import { DOMParser } from 'prosemirror-model'

function elementFromString (value) {
  const element = document.createElement('div')
  element.innerHTML = value.trim()
  return element
}

export default class Generic extends Node {
  get name () {
    return 'html'
  }

  get schema () {
    return {
      inline: false,
      attrs: {},
      group: 'block',
      draggable: true,
      parseDOM: []
    }
  }

  commands ({ type }) {
    return {
      insertHTML: value =>
        (state, dispatch) => {
          const { selection } = state
          const element = elementFromString(value)
          const slice = DOMParser.fromSchema(state.schema).parseSlice(element)
          const transaction = state.tr.insert(selection.anchor, slice.content)
          dispatch(transaction)
        }
    }
  }
}
``` 
And to use it:
```js
 this.editor.commands.insertHTML(myHtmlSnippet)
```

**Comment by edgar-koster** [comment]
Hi 

This is exactly what I need, but I'm missing the part how to add it (new to tiptap).  I keep getting things like can't bind to editor and so on. Can you point out how to link the extension?

> Really excellent :-) This `insertHtml.js` extension seems to work for me:
> 
> ```js
> import { Node } from 'tiptap'
> 
> import { DOMParser } from 'prosemirror-model'
> 
> export default class Generic extends Node {
>   get name () {
>     return 'html'
>   }
> 
>   get schema () {
>     return {
>       inline: false,
>       attrs: {},
>       group: 'block',
>       draggable: true,
>       parseDOM: []
>     }
>   }
> 
>   commands ({ type }) {
>     return {
>       insertHTML: value =>
>         (state, dispatch) => {
>           const { selection } = state
>           const element = document.createElement('div')
>           element.innerHTML = value.trim()
>           const slice = DOMParser.fromSchema(state.schema).parseSlice(element)
>           const transaction = state.tr.insert(selection.anchor, slice.content)
>           dispatch(transaction)
>         }
>     }
>   }
> }
> ```
> 
> And to use it:
> 
> ```js
>  this.editor.commands.insertHTML('<p>Hello <b>you</b> there </p>')
> ```

**Comment by Otto-munch** [comment]
I am sorry to bother, but can anyone provide a simple implementation of that in a vue component? 

I don't know how to use this solution. Thank you!

**Comment by Elrinth** [comment]
The project I'm using, is using: "@tiptap/vue-2": "^2.0.0-beta.196"

the project is called: "@peepi/vuetify-tiptap"

can you explain what I must do @tvld  ?

**Comment by tvld** [comment]
I really can not say it better than written in [TipTap](https://tiptap.dev/api/extensions/bubble-menu)

**Comment by Elrinth** [comment]
I tried to do something simple, I wrote an extension (Button.js):
import { Mark, markInputRule, markPasteRule, mergeAttributes, } from '@tiptap/core';
export const starInputRegex = /(?:^|\s)((?:\*\*)((?:[^*]+))(?:\*\*))$/;
export const starPasteRegex = /(?:^|\s)((?:\*\*)((?:[^*]+))(?:\*\*))/g;
export const underscoreInputRegex = /(?:^|\s)((?:__)((?:[^__]+))(?:__))$/;
export const underscorePasteRegex = /(?:^|\s)((?:__)((?:[^__]+))(?:__))/g;
export const Button = Mark.create({
    name: 'button',
    content: 'block*',
    marks: '',
    group: 'block inline',
    addOptions() {
        return {
            HTMLAttributes: {
                class: 'ma-2 img-btn v-btn v-btn--has-bg theme--light v-size--x-large'
            },
        };
    },
    addAttributes() {
        return {
            class: {
                default: this.options.HTMLAttributes.class,
            },
        };
    },
    parseHTML() {
        return [
            {
                tag: 'button',
            }
        ];
    },
    renderHTML({ HTMLAttributes }) {
        return ['button', mergeAttributes(this.options.HTMLAttributes, HTMLAttributes), 0];
    },
    addCommands() {
        return {
            setButton: () => ({ commands }) => {
                return commands.setMark(this.name);
            },
            toggleButton: () => ({ commands }) => {
                return commands.toggleMark(this.name);
            },
            unsetButton: () => ({ commands }) => {
                return commands.unsetMark(this.name);
            },
            insertButton: () => ({ commands}) => {
                return commands.insertContent(this.name);
            }
        };
    },
    addInputRules() {
        return [
            markInputRule({
                find: starInputRegex,
                type: this.type,
            }),
            markInputRule({
                find: underscoreInputRegex,
                type: this.type,
            }),
        ];
    },
    addPasteRules() {
        return [
            markPasteRule({
                find: starPasteRegex,
                type: this.type,
            }),
            markPasteRule({
                find: underscorePasteRegex,
                type: this.type,
            }),
        ];
    },
});
//# sourceMappingURL=Button.js.map

then I add that in the extensions list just like with for example: characterCount...
extensions: [
            CharacterCount,
            Button
        ]

then I try to insert it:
var elButton1 = document.createElement("button");
            elButton1.textContent = "test";
            var slice = DOMParser.fromSchema(this.theEditor.state.schema).parseSlice(elButton1);
            var transaction = this.theEditor.state.tr.insert(this.theEditor.state.selection.anchor, slice);
            this.theEditor.view.dispatch(transaction);

But it doesn't work... I tried inspecting, and I can see that the button has not been added to the this.theEditor.state.schema.nodes ... so that's probably why it doesn't work...
Now the question is... How do I get it to get added to the schema via an extension?

**Comment by paulocastellano** [comment]
> ```js
>  this.editor.commands.insertHTML
> ```

Do you have this snippet for the new tiptap version?

**Comment by paulocastellano** [comment]
> Really excellent :-) This `insertHtml.js` extension seems to work for me:
> 
> ```js
> import { Node } from 'tiptap'
> 
> import { DOMParser } from 'prosemirror-model'
> 
> export default class Generic extends Node {
>   get name () {
>     return 'html'
>   }
> 
>   get schema () {
>     return {
>       inline: false,
>       attrs: {},
>       group: 'block',
>       draggable: true,
>       parseDOM: []
>     }
>   }
> 
>   commands ({ type }) {
>     return {
>       insertHTML: value =>
>         (state, dispatch) => {
>           const { selection } = state
>           const element = document.createElement('div')
>           element.innerHTML = value.trim()
>           const slice = DOMParser.fromSchema(state.schema).parseSlice(element)
>           const transaction = state.tr.insert(selection.anchor, slice.content)
>           dispatch(transaction)
>         }
>     }
>   }
> }
> ```
> 
> And to use it:
> 
> ```js
>  this.editor.commands.insertHTML('<p>Hello <b>you</b> there </p>')
> ```

Do you have this snippet for the new tiptap version?
