### ISSUE TITLE
招聘北京全职tiptap开发人员

### ISSUE THREAD

**Issue by forkyguo** [ueberdosis/tiptap#3860]
### What problem are you facing?

我们是一家外资企业，要开发在线文档，需要会prosemirror的开发人员。请@我。

### What’s the solution you would like to see?

我们是一家外资企业，要开发在线文档，需要会prosemirror的开发人员。请@我。

### What alternatives did you consider?

我们是一家外资企业，要开发在线文档，需要会prosemirror的开发人员。请@我。

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by Cassielxd** [comment]
你好  我一直在从事 tiptap和prosemirroe 的开发 坐标西安

**Comment by forkyguo** [comment]
请加我微信guofeng9，备注tiptap开发

**Comment by svenadlung** [comment]
I would kindly ask you to reopen the issues in English so that everyone can understand them and reply to you. Thank you very much!

**Comment by thegaoqi** [comment]
> 你好 我一直在从事 tiptap和prosemirroe 的开发 坐标西安
方便聊聊吗 therealGaoQi
