### ISSUE TITLE
Cannot read properties of undefined (reading 'localsInner') at "prosemirror-view": "^1.30.2"

### ISSUE THREAD

**Issue by icode** [ueberdosis/tiptap#3869]
### What’s the bug you are facing?

update  "prosemirror-view" to "1.30.2", Tiptap version 2.0.0-beta.220, iget e error
```
index.js:3964 Uncaught TypeError: Cannot read properties of undefined (reading 'localsInner')
    at DecorationGroup.locals (index.js:3964:42)
    at iterDeco (index.js:1898:23)
    at NodeViewDesc.updateChildren (index.js:1257:9)
    at new NodeViewDesc (index.js:1162:18)
    at docViewDesc (index.js:1389:12)
    at EditorView.updateStateInner (index.js:5047:36)
    at EditorView.updateState (index.js:4998:14)
    at Editor.createView (Editor.ts:281:15)
    at new Editor (Editor.ts:84:10)
```

### Which browser was this experienced in? Are any special extensions installed?

chrome 111.0.5563.65

### How can we reproduce the bug on our side?

update "prosemirror-view" to "1.30.2"

### What did you expect to happen?

use new version prosemirror

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by leedalei** [comment]
same issue, any updates?

**Comment by Alzy** [comment]
any update on this?

**Comment by KonnorRogers** [comment]
I'm getting this in 2.1.7 specifically when I have the following plugins enabled:

Focus or Placeholder + CodeBlockLowlight

tried to reproduce in stackblitz but was unsuccessful.

**Comment by ivoneijr** [comment]
In my case, after some review of my `package.json` I realized that I was using some tiptap plugins in the beta version including tiptap core, I just upgraded all of them to the latest stable version and it worked!

**Comment by fuadsaud** [comment]
Faced the same problem recently. The trigger was the addition of the [tiptap-annotation-magic](https://github.com/luccalb/tiptap-annotation-magic) alongside the [placeholder extension](https://github.com/ueberdosis/tiptap/tree/develop/packages/extension-placeholder#tiptapextension-placeholder). They both use decorations so I'm guessing there's something in the way they interact that causes the issue.

I tried playing around a bit with the versions of each library and prosemirror-view but that didn't seem to help.

**Comment by icode** [comment]
I found that the issue is caused by the dependency on multiple versions of the prosemirror view in the project, and there are multiple versions of the prosemirror view dependency in tiptap itself, which leads to this issue. I resolved this issue by configuring the solutions configuration for package.json.

**Comment by revengemiroz** [comment]
any solution to this ? removed tiptap entirely but still the issue persist while using blocknote library

**Comment by icode** [comment]
> any solution to this ? removed tiptap entirely but still the issue persist while using blocknote library


 I resolved this issue by configuring the `solutions` configuration for package.json.

**Comment by geekruchika** [comment]
same issue with the placeholder extension, any updates?
I m using latest tiptap version.

**Comment by davidliudev** [comment]
I am having the same issue with the latest version. Need solutions too

**Comment by cnrad** [comment]
This is happening for me as well but only in production, tried messing around with package versions and can't figure it out

**Comment by tony-cocco** [comment]
I just hit this myself when going from tiptap libraries 2.1.12 -> 2.2.1.

I followed the advice to lock the prosemirror-view version since I had multiple. (I have starter-kit locked because we also use hocuspocus libraries and that version is ^2.1.12 which leads to other issues.)

```
"resolutions": {
    "@tiptap/starter-kit": "2.2.1",
    "prosemirror-view": "1.32.7",
  },
```

This seemed to resolve my problem.

**Comment by svenadlung** [comment]
This most likely has to do with the use of different ProseMirror package versions.

Please do the following:

- always use @tiptap/pm if you want to use ProseMirror functions
- update tiptap packages to version *2.2.1*, update tiptap-pro packages to version *2.6.4*
- clean up the lock file if necessary

If there are still problems, please check whether different versions of ProseMirror packages are registered somewhere, e.g. with `npm ls prosemirror-view`.

**Comment by TeemuKoivisto** [comment]
Yeah I just want to add a comment here, that even though you have no duplicate packages installed, apparently Rollup or Vite _might_ still include prosemirror into your js bundle. It's a bit absurd as I have set all devDeps and deps as external so nothing should get included. Yet it does.

This seemed to have done the trick:

```js
    rollupOptions: {
      external: [
        'prosemirror-model',
        'prosemirror-state',
        'prosemirror-transform',
        'prosemirror-view',
        'react',
        'react/jsx-runtime',
        'react-dom',
        ...Object.keys(pkg.devDependencies || {}),
        ...Object.keys(pkg.dependencies || {})
      ]
    },
```

**Comment by antonvenema-tophat** [comment]
Using `webpack` and `npm`, adding this to `webpack.config.js` resolve this for me:

```
resolve: {
    alias: {
      "prosemirror-view": require.resolve("prosemirror-view"),
    },
}
```
