### ISSUE TITLE
LocalStorage not compatible with @tiptap editor

### ISSUE THREAD

**Issue by GodsonAddy** [ueberdosis/tiptap#3871]
### What’s the bug you are facing?

I'm trying to fetch data from localStorage into my @tiptap editor in my nextjs app and seems impossible to achieve

### Which browser was this experienced in? Are any special extensions installed?

All browsers

### How can we reproduce the bug on our side?

```
const [content, setContent] = useState("");

  const editor = useEditor(
    {
      extensions: [
        StarterKit,
        Placeholder.configure({
          placeholder: "Your story starts here…",
        }),
      ],

      content: content,
      onUpdate: ({ editor }) => {
        const json = editor.getHTML();
        setContent(json);
        localStorage.setItem(`content`, json);
      },
     
    },

    []
  );

  useEffect(() => {
    const savedContent = localStorage.getItem(`content`);

    if (savedContent) {
      setContent(savedContent);
    }
  }, []);

  if (!editor) {
    return null;
  }
```

### Can you provide a CodeSandbox?

[https://codesandbox.io/p/sandbox/priceless-shtern-csi1jj](https://codesandbox.io/p/sandbox/priceless-shtern-csi1jj)

### What did you expect to happen?

To be able to fetch data from localStorage into my @tiptap editor

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by Jonne108** [comment]
Hey!

I just wanted to share my thoughts to this https://codesandbox.io/p/sandbox/example-73cugj

I hope this is helpful for you! :)

**Comment by gethari** [comment]
@Jonne108 using the same codesandbox, I could able to see the value from the localstorage in the console as well as set on the editor after hitting reload on the preview window . Am i missing something ?

![image](https://user-images.githubusercontent.com/20477956/228523106-7e0dc2bd-641a-495f-aa62-402738c9a4ff.png)

**Comment by Jonne108** [comment]
Hi @gethari!

It seems that @GodsonAddy edited his CodeSandbox based on my example and thats why it is working for you. You can check the original code provided by GodsonAddy under the title "How can we reproduce the bug on our side?".
