### ISSUE TITLE
Create a new paragraph by keypress enter and disable create new line with enter.

### ISSUE THREAD

**Issue by jordiSabartresCastillo** [ueberdosis/tiptap#391]
I am trying to create a new paragraph every time that I press enter, but i don't find the solution to do that. I want to change the function of create a new line to, create a new paragraph. Someone know if this is posible.

**Comment by philippkuehn** [comment]
I can't follow. It's the default behavior to create a new paragraph on pressing enter.

**Comment by jordiSabartresCastillo** [comment]
Sorry I haven't  explained myself well. The thing that I want is: every time that I press enter create, a new editor with an independent paragraph every time. 
something like that:

![Captura](https://user-images.githubusercontent.com/49201004/61462453-f303f700-a972-11e9-9947-3a638dc214a8.PNG)
Thank you!!

**Comment by akirarika** [comment]
> 对不起，我自己解释得不好。我想要的是：每次按enter创建，每次都有一个独立段落的新编辑器。
> 像这样的东西：
> 
> ![卡普图拉](https://user-images.githubusercontent.com/49201004/61462453-f303f700-a972-11e9-9947-3a638dc214a8.PNG)
> 谢谢！！

```html
<editor-content @keydown.enter="newYourEditor" />
```

**Comment by akirarika** [comment]
> Sorry I haven't explained myself well. The thing that I want is: every time that I press enter create, a new editor with an independent paragraph every time.
> something like that:
> 
> ![Captura](https://user-images.githubusercontent.com/49201004/61462453-f303f700-a972-11e9-9947-3a638dc214a8.PNG)
> Thank you!!

```html
<editor-content @keydown.enter="newYourEditor" />
```
