### ISSUE TITLE
[Bug]: extension-link not work

### ISSUE THREAD

**Issue by HengCC** [ueberdosis/tiptap#3915]
### Which packages did you experience the bug in?

extension-link 

### What Tiptap version are you using?

current is 2.0.0

### What’s the bug you are facing?

After setting the link. Clicking the link does not respond. The link is not opened in a new window. This is the case for my local and official website demos

### What browser are you using?

Chrome

### What did you expect to happen?

open the link normally

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by HengCC** [comment]
![image](https://user-images.githubusercontent.com/6167532/228800384-aa0223fe-52e5-43da-982e-1f9d2d660bcc.png)
What does the button mean here?

**Comment by HengCC** [comment]
I checked the information. When the button is equal to 1, it means that the middle mouse button is pressed, but when there is no mouse, the click is invalid. It can only be opened in a new window by right clicking

**Comment by bdbch** [comment]
Should be included in `2.0.1`
