### ISSUE TITLE
[Bug]: Conflicts in packages of TipTap

### ISSUE THREAD

**Issue by Srijan-Baniyal** [ueberdosis/tiptap#3926]
### Which packages did you experience the bug in?

 prosemirror-commands ,  prosemirror-dropcursor , prosemirror-gapcursor ,  prosemirror-history  ,  prosemirror-keymap ,  prosemirror-model , prosemirror-schema-list , prosemirror-state,  prosemirror-transform ,   prosemirror-view , "@tiptap/core,@tiptap/react,  @tiptap/starter-kit

### What Tiptap version are you using?

2.0.0

### What’s the bug you are facing?

There aren't like buys anywhere when I'm using the Tiptap . The issue is that it's annoying for me that I have warning to that may in the CMD which can cause troubles later on .  

THis project made in Next.js

Please find the picture attached .  

![image](https://user-images.githubusercontent.com/107460791/229130315-240c3707-9e4c-43ed-bfaa-9cc94fc08d41.png)

### What browser are you using?

Chrome

### Code example

https://codesandbox.io/p/github/Srijan-Baniyal/BlogPaurv/draft/misty-grass?file=%2Fpackage.json&workspace=%257B%2522activeFileId%2522%253A%2522clfwktb8o000jg4gkbe5s27qg%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fpages%252Findex.tsx%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clfwktfsd000x3n6ikr6uz1yf%2522%253A%257B%2522key%2522%253A%2522clfwktfsd000x3n6ikr6uz1yf%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522clfwktyvk009n3n6icxadbv3o%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522clfwktxsh005p3n6i7zn42pwq%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522clfwktfsd000x3n6ikr6uz1yf%2522%252C%2522spacesOrder%2522%253A%255B%2522clfwktfsd000x3n6ikr6uz1yf%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D

### What did you expect to happen?

Everything is ok but not the warning's that it 

### Anything to add? (optional)

In January I worked with Tiptap I don't' remember which version but at that time it was in beta. At that time, I was able to remove all the warnings but this time I'm not able to remove a single warning in it. By using the old style, you might read in the packages form you asked. 

I was trying to solve it in the old style but didn't work 

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by svenadlung** [comment]
You need to remove ProseMirror dependencies and use our @tiptap/om package instead.

**Comment by Srijan-Baniyal** [comment]
Ok , it worked Thank You so much for your .
