### ISSUE TITLE
Where is br in code blocks?

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [ueberdosis/tiptap#394]
![изображение](https://user-images.githubusercontent.com/9306996/61599475-40fe5080-ac3a-11e9-8537-12036d21210e.png)
Here no <br> from pushing enter? Why you done this? How we can fix it? Same with standart(one line) codeblock instead creating <p> on enter, you must just add <br>.

Also how we should get out inside code? 
![изображение](https://user-images.githubusercontent.com/9306996/61599500-828efb80-ac3a-11e9-9b73-3fa6787c31eb.png)
It's just creating more and more enter's, why?
2 fast enter's - exit and creating new paragraph.

@philippkuehn
Any suggestions?

**Comment by afwn90cj93201nixr2e1re** [comment]
![GIF](https://user-images.githubusercontent.com/9306996/61644333-8a3fb600-acb5-11e9-8615-2c0fdbfb1ee5.gif)

**Comment by philippkuehn** [comment]
I have no idea what you are doing. Please provide a meaningful issue description and codesandbox.

Inside of a codebox press `enter` for a new line. There is no `<br>`. Press `shift + enter` for leaving the code block.

![Jul-22-2019 17-24-21](https://user-images.githubusercontent.com/2500670/61644879-d71b9080-aca5-11e9-920e-2153b19a958d.gif)

**Comment by afwn90cj93201nixr2e1re** [comment]
How i can add <br> instead paragraph?
So im wrong, yes, but im talking 'bout oneline code.
Code not CodeBlock.

You can test it in examples page, on tables example.

**Comment by afwn90cj93201nixr2e1re** [comment]
also sometimes we can't go to tiptap.scrumpy from russia, can you fix it?


First:
word-break: break-all; add this into you content scss.

![GIF1](https://user-images.githubusercontent.com/9306996/61645776-7cd7fb00-acb8-11e9-8205-12b81198970c.gif)

**Comment by afwn90cj93201nixr2e1re** [comment]
The second, what' im talking 'bout.
![GIF4](https://user-images.githubusercontent.com/9306996/61646105-6f6f4080-acb9-11e9-984a-4013e0e320e1.gif)


@philippkuehn how i can fix it, if you don't wanna make it globaly?

**Comment by afwn90cj93201nixr2e1re** [comment]
In froala, ckeditor and other's we get something like this if use <p><code>.
![изображение](https://user-images.githubusercontent.com/9306996/61646220-d7258b80-acb9-11e9-9d0a-a5f5914b1dd4.png)

But in titap we getting another way.

**Comment by philippkuehn** [comment]
For a line break you can use `Shift + Enter`. A simple `Enter` will always create a new paragraph. This is intended behavior.

**Comment by afwn90cj93201nixr2e1re** [comment]
Thank's. Gonna test it, so, how i can rewrite it, for line Break use Enter, and for paragraph Shift Enter, xD?

**Comment by afwn90cj93201nixr2e1re** [comment]
![изображение](https://user-images.githubusercontent.com/9306996/61646386-85c9cc00-acba-11e9-800c-dcbe08b9d1ab.png)

Yeah, works. Why you don't improve doc's?)))

**Comment by philippkuehn** [comment]
Better docs are [in the works](https://tiptap.scrumpy.io/docs/api/extensions.html#hardbreak). Feel free to make a PR.

**Comment by afwn90cj93201nixr2e1re** [comment]
Very nice, i didn't seen it before, maybe you should add some div to this block?)
![изображение](https://user-images.githubusercontent.com/9306996/61646603-aa727380-acbb-11e9-8929-07423c3fe17d.png)

**Comment by afwn90cj93201nixr2e1re** [comment]
@philippkuehn 
![изображение](https://user-images.githubusercontent.com/9306996/61718343-dc471100-ad73-11e9-962b-6a8e94d7b1e8.png)
https://github.com/scrumpy/tiptap/issues/394#issuecomment-513845270
> also sometimes we can't go to tiptap.scrumpy from russia, can you fix it?

**Comment by afwn90cj93201nixr2e1re** [comment]
I can access to this ip only with DE ip.
If we 'r using non DE ip site doesn't accept connection.

**Comment by andreasvirkus** [comment]
> For a line break you can use `Shift + Enter`. A simple Enter will always create a new paragraph. This is intended behavior.

@philippkuehn is it possible this behaviour is now reversed? On the official [code-highlighting](https://tiptap.scrumpy.io/code-highlighting) example, pressing `Enter` creates a line break inside the code block, but pressing `Shift + Enter` creates a new paragraph, placing the cursor outside of the code block 🤔 

MacOS 10.15.3, Firefox 74

**Comment by philippkuehn** [comment]
@andreasvirkus this behavior hasn't changed. it's the prosemirror default.

`enter` in paragraph creates a new paragraph
`shift+enter` in paragraph creates a line break
`enter` in code block creates a line break
`shift+enter` in code block leaves the code block (and creates a paragraph)

**Comment by andreasvirkus** [comment]
Thanks for getting back to me so quick! Feels odd to me that they'd reverse this, but seems it's out of our hands

**Comment by wmf508** [comment]
how to use button click event to leave the code block?
