### ISSUE TITLE
"TypeError: Cannot read properties of undefined (reading 'schema')" when rendering data in Editor using Tittap for vue 

### ISSUE THREAD

**Issue by hvsgauravgambhir** [ueberdosis/tiptap#3942]
### Which packages did you experience the bug in?

Tittap for vue (@tiptap/vue-2)

### What Tiptap version are you using?

2.0.1

### What’s the bug you are facing?

![image](https://user-images.githubusercontent.com/128692887/230069382-80cb4438-1f19-473e-bd00-7d5acb3f8d90.png)
I am facing the above error when rendering the data again that was given as output using editor.getJSON() API. It gives me correct data but it is not able to render(The array above the "TypeError: Cannot read properties of undefined (reading 'schema')" error is the output that was given)

### What browser are you using?

Chrome

### What did you expect to happen?

It should have renderd the data

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by andremw** [comment]
@hvsgauravgambhir , how did you get this fixed?
