### ISSUE TITLE
[Bug]: custom emoji not working in emoji extension since 2.0.0-rc.2

### ISSUE THREAD

**Issue by bkempe** [ueberdosis/tiptap#3944]
### Which packages did you experience the bug in?

extension-emoji

### What Tiptap version are you using?

2.0.0

### What’s the bug you are facing?

custom emojis are not working anymore since 2.0.0-rc.2.
They were working in an earlier version, e.g. 2.0.0-rc.1.

For example, see the octocat emoji not showing up in https://tiptap.dev/api/nodes/emoji#usage

### What browser are you using?

Chrome

### What did you expect to happen?

custom emoji working

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
This should work in the most recent versions again (2.0.1 or 2.1.0-rc0)
