### ISSUE TITLE
Back compatability

### ISSUE THREAD

**Issue by Valt25** [ueberdosis/tiptap#395]
Hello. This is not feature request or bug report. I need just clearance in use case of this awesome library. 

In our company tiptat is used. For a long time we have been using version 1.14.0(that was the latest, when we started). Today I found out some error connected with tiptap and that issue was solved in one of the latest versions. For now as I see the last version is 1.23.3 and the gap in 0.9.3 versions of update seems large enough.

There is no e2e tests in our project, and this is rather hard to check that upgrading of tiptap from 1.14.0 to 1.23.3 would not lead us to new errors in unpredictable places.

So i would like to know, how back compatibility is addressed in this library?

**Comment by philippkuehn** [comment]
There should be no breaking changes since then. And yeah… e2e tests are already on my list (I'm also happy for any PR).

**Comment by hanspagel** [comment]
There is nothing we have in place that ensures backwards compatibility. That being said, we hope to get e2e tests in place for version 2.
