### ISSUE TITLE
[Bug]: @vue/devtools shows NodeView components as "Anonymous Component"

### ISSUE THREAD

**Issue by segevfiner** [ueberdosis/tiptap#3965]
### Which packages did you experience the bug in?

vue-3

### What Tiptap version are you using?

2.0.3

### What’s the bug you are facing?

All node view components under the `EditorContent` show up as "Anonymous Component" in the Vue devtools. This makes it more difficult to debug as you then have to wade around through a bunch of "Anonymous Component" to find the one you want to look at.

Steps to reproduce:
1. Install the Vue devtools extension for your browser.
2. Open the reproduction.
3. Click "Open in New Tab" (Vue devtools don't seem to work in the iframe in StackBlitz, but will work when opening in a tab).
4. Open the Vue devtools, check the components under the `EditorContent` component.

### What browser are you using?

Chrome

### Code example

https://stackblitz.com/edit/vitejs-vite-tkbxce?file=src/extensions/foo.ts

### What did you expect to happen?

The component names to appear as for regular components in dev builds.

### Anything to add? (optional)

<img width="511" alt="screenshot" src="https://user-images.githubusercontent.com/24731903/232353450-08c21ae3-9616-42bb-b51b-e503996a5ee3.png">

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by YossiSaadi** [comment]
I'm experiencing the same, seems like that was behavior since ever
