### ISSUE TITLE
[Bug]: Replaced the image src, but getHtml still gets the old src

### ISSUE THREAD

**Issue by extrastu** [ueberdosis/tiptap#3969]
### Which packages did you experience the bug in?

extension-image

### What Tiptap version are you using?

2.0.0

### What’s the bug you are facing?

 Replaced the image src, but getHtml still gets the old src

### What browser are you using?

Chrome

### What did you expect to happen?

 Replaced the image src, but getHtml still gets the old src

### Anything to add? (optional)

 Replaced the image src, but getHtml still gets the old src

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by svenadlung** [comment]
Please provide a [CodeSandbox](https://codesandbox.io/s/tiptap-react-qidlsv) and reopen once it's done 🙌
