### ISSUE TITLE
Something wrong with horizontal line

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [ueberdosis/tiptap#403]
![GIF](https://user-images.githubusercontent.com/9306996/61826093-c2d8be80-ae72-11e9-8479-22589a9b155f.gif)

**Comment by afwn90cj93201nixr2e1re** [comment]
As you can see sometimes something went wrong, xD.
@philippkuehn

**Comment by afwn90cj93201nixr2e1re** [comment]
So, maybe we should set cursor position to line end after pushing br? Then issue can't be reproduced.

**Comment by afwn90cj93201nixr2e1re** [comment]
I think it work as expected, but, can we implement this?
https://github.com/scrumpy/tiptap/issues/403#issuecomment-514787467

**Comment by gorkemcetin** [comment]
This can be reproduced for example adding a horizontal line after a H1, H2, H3... element.
