### ISSUE TITLE
[Bug]: Difference in behavior of setContent and insertContent commands

### ISSUE THREAD

**Issue by ashu12chi** [ueberdosis/tiptap#4034]
### Which packages did you experience the bug in?

core

### What Tiptap version are you using?

latest

### What’s the bug you are facing?

In our application, we are using `insertContent` and `setContent` command. The issue we are facing is the final output for the same content is different for the two commands.

Example to this:
```javascript
const content = `<h1>Welcome to your fresh Tiptap Code Sandbox</h1>
  <p>You can create a demo for your issue inside of this sandbox and share it with us.</p>`
```
For above content, output of `setContent` is:
![image](https://github.com/ueberdosis/tiptap/assets/45908393/3ce4743e-1059-4dbd-8d26-54d9d266b8c1)
But, for `insertContent` it is coming with two blank lines in-between the content
![image](https://github.com/ueberdosis/tiptap/assets/45908393/676fe983-2dbe-4855-ac2c-1c058b3e8b28)
if I pass `parseOptions` in `insertContent` command as
```javascript
editor.commands.insertContent(content, {
    parseOptions: { preserveWhitespace: false }
})
```
It will still come with one blank line like this:
![image](https://github.com/ueberdosis/tiptap/assets/45908393/cb68fc00-cc24-41d3-9ca8-939beb6d611c)

Ideally, behavior should be same for both the cases.

I have some observations regarding this:
1. If I modify my content to have no new line characters like this:
```javascript
const content = `<h1>Welcome to your fresh Tiptap Code Sandbox</h1><p>You can create a demo for your issue inside of this sandbox and share it with us.</p>`
```
Behavior will be same for both `insertContent` and `setContent`.

2. On taking a cursory at the internal implementation of the two commands, `setContent` is using [parseSlice](https://prosemirror.net/docs/ref/#model.DOMParser.parseSlice) and `insertContent` is using [parse](https://prosemirror.net/docs/ref/#model.DOMParser.parseSlice) function from Prosmirror.

Since, external content can possibly have new lines in them, we want behavior of both the commands to be same (Ideally the behavior of `setContent`)

### What browser are you using?

Chrome

### Code example

https://codesandbox.io/s/green-monad-surcnd?file=/src/App.js

### What did you expect to happen?

`setContent` and `insertContent` should produce same output for given content.

### Anything to add? (optional)

NA

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by Adonis0123** [comment]
Has anyone found a solution for this issue?

**Comment by kaikun213** [comment]
Experiencing the same issue. Even when replacing the newline characters the commands do not produce the same results for more complex html imports.

Seems like quite a core functionality that is important to have reliable import. Is it still on the roadmap? @bdbch

**Comment by bdbch** [comment]
Tanks for reporting. I'll take a look tomorrow

**Comment by Slapbox** [comment]
Could this have any relation to #4862?

**Comment by bdbch** [comment]
https://github.com/ueberdosis/tiptap/pull/4895 created a fix here which should bring setContent and insertContent in line with each other. `setContent` was using a different DOM parsing approach then insertContent.

**Comment by Nantris** [comment]
Not OP, but I did a quick test in our editor and it looks good to me. It's always possible our custom code is interfering but I think this can be closed unless someone reports otherwise.

**Comment by Nantris** [comment]
I'm a little confused about `preserveWhitespace` though. I'd expect `false` NOT to insert the empty line at the end, but instead it does insert it. Is that right?
