### ISSUE TITLE
Invisible(hidding cursor)

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [ueberdosis/tiptap#405]
write some text, or leave one empty paragraph from top

Insert image or something else, set your cursor at end of first paragraph before image.
Push right arrow on keyboard, then sometimes you gonna see coursor at end of image line(as expected), then push left and cursor gonna hide, so, as we know, cursor at image now, but we can't see it, coz seems like image in paragraph tags as code and other plugins.

![GIF](https://user-images.githubusercontent.com/9306996/61827630-1993c780-ae76-11e9-8814-5e9f20d362bb.gif)

Seem's like we should make some workaround for this situation's, for example glow or border glowing or something else if cursor on object which was inserted by plugin.

https://github.com/scrumpy/tiptap/issues/403
Seem's like this is kind of too.

**Comment by afwn90cj93201nixr2e1re** [comment]
- [ ] dfgdfg

**Comment by afwn90cj93201nixr2e1re** [comment]
@philippkuehn

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/scrumpy/tiptap/pull/399

So, i made some fix for losted Prosemirror class.
But can't find a solution for cursor hidding after 
![изображение](https://user-images.githubusercontent.com/9306996/61829875-e7d12f80-ae7a-11e9-9966-7342f78d782e.png)

**Comment by afwn90cj93201nixr2e1re** [comment]
So, seem's like prosemirror already have this class.
![изображение](https://user-images.githubusercontent.com/9306996/61831353-a6428380-ae7e-11e9-8679-9c2b3f9bc2c6.png)

Maybe caret hiding depended on this rule?

https://github.com/scrumpy/tiptap/blob/master/packages/tiptap/src/style.css#L46-L48

After this style appending, we get invisible cursor on out from node.

Also we should remove class from img fully.

But seem's like official prosemirror also have this bug: 
http://prosemirror.net/


Try to make same thing as on gift.
![GIF](https://user-images.githubusercontent.com/9306996/61831420-d9851280-ae7e-11e9-8ab2-7e9399f3108e.gif)

**Comment by afwn90cj93201nixr2e1re** [comment]
Seems it's can be reproduced on firefox only, but here some another bug with chrome.

![GIF](https://user-images.githubusercontent.com/9306996/61832134-2b2e9c80-ae81-11e9-8836-bb3c646f52dd.gif)

**Comment by afwn90cj93201nixr2e1re** [comment]
https://sticky-ferret.glitch.me

**Comment by afwn90cj93201nixr2e1re** [comment]
@philippkuehn you can close this. It's can't be fixed with css.

**Comment by ryanbliss** [comment]
Look into gap cursor and set your own styles. Gapcursor is already enabled on TipTap, so all you really need to do is set `showGapCursor: true` on the NodeView. If that doesn't fit your use case, then you should use the `selected` prop on the NodeView, using a watcher like this:

```
selected(isSelected) {
          if (isSelected) {
            // Change CSS theme for the node
            this.imageTheme = 'selected';
          } else {
            // Set CSS theme back to normal
            this.imageTheme = 'normal';
          }
 },
```
