### ISSUE TITLE
@philippkuehn - Issue with generateJSON() on Server

### ISSUE THREAD

**Issue by PiWizard3852** [ueberdosis/tiptap#4053]
@philippkuehn 
```
[2023-01-07 09:56:28.693] error: window is not defined
ReferenceError: window is not defined
    at elementFromString (C:\Users\...\...\node_modules\@tiptap\core\dist\tiptap-core.cjs.js:1563:5)
 ```

_Originally posted by @multipliedtwice in https://github.com/ueberdosis/tiptap/issues/1042#issuecomment-1374361033_

**Comment by zensh** [comment]
I have got this error from tiptap/html@2.1.0-rc.11
_a.startsWith is not a function","stack":"TypeError: _a.startsWith is not a function\n    at handleRules 
zeed-dom@0.9.26/node_modules/zeed-dom/dist/index.js:42:83
...
prosemirror-model@1.19.2/node_modules/prosemirror-model/dist/index.js:2754:22

**Comment by zensh** [comment]
> I have got this error from tiptap/html@2.1.0-rc.11 _a.startsWith is not a function","stack":"TypeError: _a.startsWith is not a function\n at handleRules zeed-dom@0.9.26/node_modules/zeed-dom/dist/index.js:42:83 ... prosemirror-model@1.19.2/node_modules/prosemirror-model/dist/index.js:2754:22

This is a issue from https://github.com/holtwick/zeed-dom/pull/8
