### ISSUE TITLE
[Bug]: extension-link is handling click events for links outside of editor and opening them in new tab

### ISSUE THREAD

**Issue by martindzejky** [ueberdosis/tiptap#4056]
### Which packages did you experience the bug in?

extension-link

### What Tiptap version are you using?

2.0.3

### What’s the bug you are facing?

I have a read-only TipTap editor wrapped in a `<a>` tag. The `extension-link` extension is handling click events when `openOnClick` is set to `true` (which is the default). However, on this line: https://github.com/ueberdosis/tiptap/blob/164eebf07ced16e29e38f13909322ce301575355/packages/extension-link/src/helpers/clickHandler.ts#LL19C46-L19C46, it is getting the `closest` `<a>` tag which in my case gets the link outside of the editor. I think that there needs to be an additional check that the `link` is inside the editor.

### What browser are you using?

Chrome

### What did you expect to happen?

TipTap ignores links outside of its editor.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Closed via #4078
