### ISSUE TITLE
[Bug]: Can't focus cursor on input element created by NodeView using react

### ISSUE THREAD

**Issue by fyrepenguin** [ueberdosis/tiptap#4063]
### Which packages did you experience the bug in?

react

### What Tiptap version are you using?

2.0.1

### What’s the bug you are facing?

I couldn't focus on the input element that's created by the nodeview. 

I tried focussing using react refs, directly updating DOM by removing focus on other elements and then focussing on the input element but both didn't work. It sometimes shows that the focussed/active element is input element but the cursor won't show up no matter what. And typing sometimes is deleting the node itself and the typed content is added toas paragraph

### What browser are you using?

Firefox

### What did you expect to happen?

To be able to focus on input element once it's created and type without having to click on it

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by svenadlung** [comment]
Could you please provide a CodeSandbox example for reproduction?

**Comment by bdbch** [comment]
Yeah a Codesandbox would be nice. From what I'm hearing it sounds like your input is inside a `contentEditable` element. Interactive elements are disabled inside editable dom elements. (similar to buttons) input elements are also disabled. Could you check if wrapping your input with an element where `contentEditable="false"` helps?

**Comment by surajmn1** [comment]
@bdbch @svenadlung 
created CodeSandbox for the issue. As you can see when we click on the add input node button, an input react node is added to the editor content but we are unable to focus the cursor on to it initially on mount, and should manually click into it to add input to it. 
https://codesandbox.io/s/tiptap-focus-input-element-issue-jsrcgs?file=/src/Tiptap.jsx

**Comment by Slapbox** [comment]
@surajmn1 I think this is because the DOM isn't ready when your `useEffect` fires, despite what the `console.log` results would suggest.

It will work if you do:

```
    window.requestAnimationFrame(() => {
      inputRef.current.focus();
    });
```

**Comment by surajmn1** [comment]
Thanks @Slapbox i tried your fix as below and it works . is this okay ?
https://codesandbox.io/s/tiptap-focus-input-element-issue-slapbox-fix-r9y3m6?file=/src/Tiptap.jsx:316-1134
```
function AutoFocusInput() {
  const inputRef = useRef(null);
  const animationIdRef = useRef(null);
  useEffect(() => {
    if (inputRef.current) {
      animationIdRef.current = window.requestAnimationFrame(() => {
        inputRef.current.focus();
      });
    }
    // Cleanup the animation frame when the component unmounts
    return () => {
      if (animationIdRef.current) {
        window.cancelAnimationFrame(animationIdRef.current);
      }
    };
  }, []);
  return (
    <NodeViewWrapper>
      <div
        style={{
          padding: "10px 25px"
        }}
      >
        <label htmlFor="myInput">Auto Focus Input:</label>
        <input type="text" id="myInput" ref={inputRef} />
      </div>
    </NodeViewWrapper>
  );
}
```

**Comment by svenadlung** [comment]
I think we can close here. Please let me know if anything is still pending and I'll open it again.

**Comment by Chandraprakash-Darji** [comment]
> Thanks @slapbox i tried your fix as below and it works.is this okay? https://codesandbox.io/s/tiptap-focus-input-element-issue-slapbox-fix-r9y3m6?file=/src/Tiptap.jsx:316-1134
> 
> ```
> function AutoFocusInput() {
>   const inputRef = useRef(null);
>   const animationIdRef = useRef(null);
>   useEffect(() => {
>     if (inputRef.current) {
>       animationIdRef.current = window.requestAnimationFrame(() => {
>         inputRef.current.focus();
>       });
>     }
>     // Cleanup the animation frame when the component unmounts
>     return () => {
>       if (animationIdRef.current) {
>         window.cancelAnimationFrame(animationIdRef.current);
>       }
>     };
>   }, []);
>   return (
>     <NodeViewWrapper>
>       <div
>         style={{
>           padding: "10px 25px"
>         }}
>       >
>         <label htmlFor="myInput">Auto Focus Input:</label>
>         <input type="text" id="myInput" ref={inputRef} />
>       </div>
>     </NodeViewWrapper>
>   );
> }
> ```

I  tried but app is crashing. Can you share about updated code
