### ISSUE TITLE
[Bug]: CodeBlockLowlight and Placeholder have conflict with Collaboration module.

### ISSUE THREAD

**Issue by aleversn** [ueberdosis/tiptap#4065]
### Which packages did you experience the bug in?

extension-collaboration, extension-collaboration-cursor, extension-code-block-lowlight, extension-placeholder

### What Tiptap version are you using?

2.1.0-rc.4

### What’s the bug you are facing?

When using Collaboration with `Y.js`. The editor can't work when importing `CodeBlockLowlight` and `Placeholder`.

the console is shown as follows:

![06845292cfefbe9623c9c0517115f65d](https://github.com/ueberdosis/tiptap/assets/30100324/29a56b8f-3568-4856-b806-c3567df2d3c0)

the errors are all about `localsInner`

### What browser are you using?

Edge

### Code example

These is some segments that how I implement the editor:

```javascript
import { WebsocketProvider } from 'y-websocket';
import * as Y from 'yjs';
import { lowlight } from './js/lowlight';

this.doc = new Y.Doc();
this.provider = new WebsocketProvider(
                `${this.$server_socket}/share-documents/`,
                token,
                this.doc,
                {
                    params: {
                        Authorization: token
                    }
                }
);

extensions: [
Collaboration.configure({
                    document: this.doc
}),
CollaborationCursor.configure({
                    provider: this.provider,
                    user: {
                        name: this.userInfo.nickName,
                        color: this.cursorColor
                    }
}),
CodeBlockLowlight.configure({
                        lowlight,
                    }),
Placeholder.configure({
                        emptyEditorClass: 'is-editor-empty',
                        placeholder: () => this.placeholder,
                    })
]
```

### What did you expect to happen?

Expect that the editor can work normally when introducing the aforementioned plugins.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by KonnorRogers** [comment]
+1. Also getting this in v2.1.7 but can't seem to reproduce in stack blitz

**Comment by aleversn** [comment]
Thank you for your email. I've received your message. If your message requires a reply, I will sooner get in touch with you. Best RegardsPeichao LaiFuzhou University

**Comment by KonnorRogers** [comment]
Solved for me by using `"overrides"` and pinning to `1.28.2` of `prosemirror-view`. Originally I was using `1.31.2` and downgraded progressively until it work. not too sure what's happening tbh.

**Comment by inaciorafael** [comment]
I had a problem using Mention in conjunction with Placeholder, I commented on the placeholder and my problem disappeared.

**Comment by bdbch** [comment]
> Solved for me by using "overrides" and pinning to 1.28.2 of prosemirror-view. Originally I was using 1.31.2 and downgraded progressively until it work. not too sure what's happening tbh.

That's really weird. Thanks for the additional info. Let's keep track of this, would like to find out what this is about.

**Comment by svenadlung** [comment]
This most likely has to do with the use of different ProseMirror package versions.

Please do the following:

- always use @tiptap/pm if you want to use ProseMirror functions
- update @tiptap packages to version 2.2.1, update @tiptap-pro packages to version 2.6.4
- clean up the lock file if necessary

If there are still problems, please check whether different versions of ProseMirror packages are registered somewhere, e.g. with `npm ls prosemirror-view`.

**Comment by dhannypramana** [comment]
im using nuxt module called `nuxt-tiptap-editor`. and the bug is still there. 
any idea about this?

**Comment by bdbch** [comment]
What Tiptap version is `nuxt-tiptap-editor` using?
