### ISSUE TITLE
How to get data into TipTap with axios?

### ISSUE THREAD

**Issue by konstantinvoronoy** [ueberdosis/tiptap#407]
Hi! I'm making a blog with vue and laravel. I use TipTap as editor for posts. So I'm a bit stuck at crud when I need to edit posts.

I have title and body of post. I get them with axios.

`      axios.get('/api/posts/' + this.postid)

            .then((response) => {
              this.title = response.data.title;
              this.body = response.data.body;              
            })`

For title I use:

`<input v-model="title">`

And I works well. But the problem with body. How do I get body into TipTap Editor?

I guess, I should do something like this:

`setContent(content) {this.editor.setContent(this.body)}`

But I don't understand where I should put it.

I recently started learning vue. And hope if someone helps with that

**Comment by afwn90cj93201nixr2e1re** [comment]
![изображение](https://user-images.githubusercontent.com/9306996/61832685-f28fc280-ae82-11e9-87ef-8667cad39a31.png)

**Comment by konstantinvoronoy** [comment]
Thanks a lot! It works! I get the data and can edit it. But now when I save it, it's saved without changes.

For posting the data I use:

`    EditPost() { 
            axios.put('/api/posts/' + this.postid, {
              title: this.title,
              body: this.body              
              })             
          }`

The saving process is working, I get the request. But the data without changes. I guess, I should add something like Update or Watch, where I put `this.editor.setContent(this.body)` , right?

**Comment by afwn90cj93201nixr2e1re** [comment]
Show your code, full.

**Comment by konstantinvoronoy** [comment]
<template>
<div>

    <div class="column is-10 is-offset-1">
        <div class="post">
            <h2>Edit</h2>
            <form @submit.prevent="EditPost()">
                <div class="editor">

                        <div class="field">
                            <input type="text" name="title" class="input" v-model="title">
                        </div>
                </div>
                <editor-content class="editor__content" :editor="editor" />
                <button type="submit" name="button" class="button is-info">Edit</button>
            </form>
        </div>
      </div>

</div>
</template>

`<script>

import {
    Editor,
    EditorContent,
} from 'tiptap';

export default {

    components: {
        EditorContent,
        Editor,
    },

    name: 'PostEdit',

    props: ['postid'],

    data: function() {

        return {
            body: '',
            title: '',
            editor: new Editor({
                content: '',
            }),
          }
    },

    beforeDestroy() {
            this.editor.destroy()
    },

    created() {
      axios.get('/api/posts/' + this.postid)
      .then((response) => {
        this.title = response.data.title;
        this.body = response.data.body;        
        this.editor.setContent(this.body)
      })
    },


    methods: {
        EditPost() {
            axios.put('/api/posts/' + this.postid, {
              title: this.title,
              body: this.body,              
              })              
        },
    },



}
</script>`

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/scrumpy/tiptap/issues/393#issuecomment-513848528

read it again.

**Comment by konstantinvoronoy** [comment]
Oh man. I forgot about it. Thanks a lot. It does work

**Comment by Sogl** [comment]
@konstantinvoronoy How did you resolve this issue? I still can’t transfer the data (tiptap body) to the POST request:

```js
methods: {
            formSubmit(e) {
                e.preventDefault();
                let currentObj = this;
                console.log(this.editor.content);

                axios.post('/manage/posts', {
                    title: this.title,
                    slug: this.slug,
                    content: this.editor.content
                })
                    .then(function (response) {
                        currentObj.output = response.data;
                    })
                    .catch(function (error) {
                        currentObj.output = error;
                    });
            }

        },
```

`this.editor.content` is `undefined` 🤔

**Comment by konstantinvoronoy** [comment]
@Sogl In data I use onUpdate function, it saves html from editor:

`data() {
    return {
        html: '',
        content: '',
        editor: new Editor({
            onUpdate: ({ getHTML }) => {
                this.html = getHTML();
                if (this.html === '<p></p>') this.content = '';
                else this.content = this.html;
            },
        })
    }
}`

In methods it can simple be retrieved:

`methods: {
	post() {
		axios.post('/manage/posts', {
			content: this.content
		})
	}
}`

**Comment by dharajiya111** [comment]
##ere# `**ththth**`
rerererere`rerererere`

**Comment by paulzay** [comment]
How can I do the same in React? Fetching data from an api and displaying it in the editor to edit it but it's delaying to show the text unless I perform a save in the codebase to trigger rerender

**Comment by pzehle** [comment]
@paulzay I have the same problem. Did you solve it?

**Comment by paulzay** [comment]
@pzehle yes i did. I added a useEffect and used `editor.commands.setContent` to populate the editor like so.  `content` here is the data already fetched and stored in state. 
```
  useEffect(() => {
    if (editor !== null && contents) editor.commands.setContent(contents, false, { preserveWhitespace: "full" });
  }, [editor, contents]);
```
