### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by codeDevStory** [ueberdosis/tiptap#4127]
### Which packages did you experience the bug in?

strike扩展渲染不正确

### What Tiptap version are you using?

2.0.2

### What’s the bug you are facing?

strike默认渲染的是s标签，但是s标签已经被弃用，应该渲染del标签

### What browser are you using?

Chrome

### What did you expect to happen?

我希望strike默认渲染del标签，并且优先级应该最低，否则会出现删除线不在文字垂直居中的情况

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by svenadlung** [comment]
I would kindly ask you to reopen the issues in English so that everyone can understand them and reply to you. Thank you very much!
