### ISSUE TITLE
How to Implement google docs like “suggest edit” mode for delete in tiptap editor using react

### ISSUE THREAD

**Issue by shilpa9608** [ueberdosis/tiptap#4131]
### Which packages did you experience the bug in?

custom extension

### What Tiptap version are you using?

2.0.0-beta.113

### What’s the bug you are facing?

We need a strike marking on text while delete the content on editor using backspace or delete button.

Example:

![Screenshot-2022-11-15-at-23 17 30](https://github.com/ueberdosis/tiptap/assets/106958957/bfae6e96-46d7-48f7-978b-f56f8544edb4)

### What browser are you using?

Chrome

### What did you expect to happen?

We need a strike marking on text while delete the content on editor using backspace or selected text removing using delete button. Give me a Tiptap extension for this using React.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by shilpa9608** [comment]
sir, @bdbch could you please give me an example for this..!

**Comment by shilpa9608** [comment]
> ### Which packages did you experience the bug in?
> custom extension
> 
> ### What Tiptap version are you using?
> 2.0.0-beta.113
> 
> ### What’s the bug you are facing?
> We need a strike marking on text while delete the content on editor using backspace or delete button.
> 
> Example:
> 
> ![Screenshot-2022-11-15-at-23 17 30](https://user-images.githubusercontent.com/106958957/245807979-bfae6e96-46d7-48f7-978b-f56f8544edb4.png)
> 
> ### What browser are you using?
> Chrome
> 
> ### Code example
> _No response_
> 
> ### What did you expect to happen?
> We need a strike marking on text while delete the content on editor using backspace or selected text removing using delete button. Give me a Tiptap extension for this using React.
> 
> ### Anything to add? (optional)
> _No response_
> 
> ### Did you update your dependencies?
> * [x]  Yes, I’ve updated my dependencies to use the latest version of all packages.
> 
> ### Are you sponsoring us?
> * [ ]  Yes, I’m a sponsor. sparkling_heart

Any example available for this feature ??

**Comment by bdbch** [comment]
Does this need to run collaborative? Thinking about how this could be solved right now but would probably need two document instances which then need to be merged together.

**Comment by shilpa9608** [comment]
> Does this need to run collaborative? Thinking about how this could be solved right now but would probably need two document instances which then need to be merged together.

Yes , We have collaborative users so we need to run collaborative..

**Comment by bdbch** [comment]
We don't have or know of a finished extension for this. Feel free to try to build one. Collaboration makes this more tricky since you need to allow User A to make suggestion edits in a separate document which can be merged with the collaborative document.

But I don't have any solid idea right now how you could easily do this.

**Comment by shilpa9608** [comment]
Is prosemirror Rebase  feature can be use to develop this suggest edit feature?..

**Comment by bdbch** [comment]
Could be used yes but we don't currently develop such feature.

But in fact I believe as soon as you go into "Suggest edit" mode you would not be able to have collaboration at the same time - only after finishing suggestions.

**Comment by shilpa9608** [comment]
@bdbch sir , Is there any another medium to make contact with you ??

**Comment by bdbch** [comment]
@shilpa9608 what do you want to know / talk about? Usually on our Discord server or via email on our Tiptap website. (see tiptap.dev)

**Comment by bdbch** [comment]
Coming back to this - take a look at `prosemirror-changset`. There are some examples on CodeSandbox:
https://codesandbox.io/examples/package/prosemirror-changeset

You could try creating your own extension for this - we don't have the resources right now to work on this but we have it planned. Can't give an ETA though.

**Comment by superredstar** [comment]
Hello
I’m currently working on a collaborative editor using wysiwyg and I’m trying to achieve an editing experience similar to google docs. Implementing comments was easy enough, however I’m a bit at a loss when it comes to implementing something like Google Doc’s “suggest edit” mode.
Implementing suggest mode for delete.
If I delete text, deleted text should be in strikethrough.
I have some problem with this point.
Do I have to customize this module?

**Comment by allen-bam** [comment]
Any further updates on a "Suggest Edits" mode Extension?
