### ISSUE TITLE
[Documentation]: Commands

### ISSUE THREAD

**Issue by wallace-yang** [ueberdosis/tiptap#4137]
### What’s the URL to the page you’re sending feedback for?

https://tiptap.dev/experiments/commands

### What part of the documentation needs improvement?

This example has a problem with using the Chinese input method. When I use the Chinese input method, onStart in the suggestion.js file is executed, but there is no props.clientRect property.

 Although this case is already filtered using “if(props.clientRect)”, it should be filtered on the first line of the function, otherwise it will cause rendering-related errors。

The problem I encountered was that I used the element-plus infinite-scroll component in the CommandsList.vue file. When I entered the full active string in Chinese, no menu appeared. When I moved the cursor one bit to the left, an error occurred.

**Cannot destructure property 'container' of 'el[SCOPE]' as it is undefined.**

please move this part to the first line of onStart function！！！
`if (!props.clientRect) {
          return
}`

### What is helpful about that part?

Reduce bugs risk for Chinese users

### What is hard to understand, missing or misleading?

 
`if (!props.clientRect) {
          return
        }`
should run at the first line of onStart Function！！！

**Comment by HariAcharya80** [comment]
```javascript

    return {
      onStart: props => {
         if (!props.clientRect) {
          return
        }

        reactRenderer = new ReactRenderer(MentionList, {
          props,
          editor: props.editor,
        })

````
is this what we are looking for ? @wallace-yang

**Comment by wallace-yang** [comment]
> ```js
>     return {
>       onStart: props => {
>          if (!props.clientRect) {
>           return
>         }
> 
>         reactRenderer = new ReactRenderer(MentionList, {
>           props,
>           editor: props.editor,
>         })
> ```
> 
> is this what we are looking for ? @wallace-yang
yes! that's right!
