### ISSUE TITLE
Get focused element

### ISSUE THREAD

**Issue by renerdias** [ueberdosis/tiptap#414]
I'm trying to make an extension, and a stalemate has arisen, how can I get the current focus element?

**Comment by philippkuehn** [comment]
I'm not sure what you try to do but there is a new [focus extension](https://tiptap.scrumpy.io/focus) which will add a class to focused nodes. Maybe this will help you already?

**Comment by renerdias** [comment]
@philippkuehn Thanks, the focus extension helped me a lot.

Another question, how to get the css class that is already in the selected node?

**Comment by Domchek** [comment]
dfsdfsdf
