### ISSUE TITLE
[Bug]: Testing error when migrate @tiptap/vue-2 to @tiptap/vue-3

### ISSUE THREAD

**Issue by maisasb** [ueberdosis/tiptap#4161]
### Which packages did you experience the bug in?

@tiptap/vue-3

### What Tiptap version are you using?

2.0.3

### What’s the bug you are facing?

I am migrating Vue 2 (2.7.10) project to Vue 3 (3.3.4) and I installed the @tiptap/vue-3 (2.0.3) package, the component works fine but all tests are breaking with @testing-library/vue.

The error I am facing:
![image](https://github.com/ueberdosis/tiptap/assets/25438419/73753437-2dc6-4d23-9eb2-e11227e7efc3)
And we can't mock and do anything to pass the tests :/

### What browser are you using?

Chrome

### Code example

https://github.com/maisasb/tiptap-error

### What did you expect to happen?

The tests pass and dont break in Editor constructor

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by guilhermebc** [comment]
same here

**Comment by will-lucena** [comment]
+1

**Comment by jaek-s** [comment]
Is there any update on this? I noticed this issue is closed, but my team just ran into a similar issue. We're using the composition API and received this error:
`TypeError: (0 , _vue.useEditor) is not a function`

**Comment by uccmen** [comment]
@maisasb I'm seeing this issue as well. Do you have any recommendation on what needs to be done to get the tests passing?

**Comment by uccmen** [comment]
@jaek-s were you able to resolve the issue?

**Comment by nperez0111** [comment]
My guess would be CJS vs ESM imports

**Comment by uccmen** [comment]
@nperez0111 thanks for your input!
I got it working with below for both runtime and testing:
```js
import * as tiptap from '@tiptap/vue-3';
const { Editor, EditorContent, FloatingMenu, BubbleMenu } = tiptap;
```
