### ISSUE TITLE
[Bug]: In safari15, tiptap editor does not have focus and text input.

### ISSUE THREAD

**Issue by glorangJohn** [ueberdosis/tiptap#4177]
### Which packages did you experience the bug in?

vuejs2, "tiptap": "^1.30.0",     "tiptap-extensions": "^1.33.2", safari 15

### What Tiptap version are you using?

1.30.0

### What’s the bug you are facing?

In safari15, tiptap editor does not have focus and text input.
<img width="403" alt="image" src="https://github.com/ueberdosis/tiptap/assets/102936372/a9e50164-6679-476d-8322-b32be57bd09a">

In chrome it works fine.

I used this example https://tiptap.dev/installation/vue2#3-create-a-new-component verbatim, but I couldn't get any input from safari15. The developer tools don't show any errors either.

### What browser are you using?

Safari

### What did you expect to happen?

it's should be input

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by glorangJohn** [comment]
no one there

**Comment by glorangJohn** [comment]
hi

**Comment by glorangJohn** [comment]
no one there

**Comment by glorangJohn** [comment]
please help me!

**Comment by glorangJohn** [comment]
help me~

**Comment by tclxdongyang-guo** [comment]
I have the same problem

**Comment by tclxdongyang-guo** [comment]
ios15  or ios14 tiptap editor does not have focus and text input,  because the -webkit-user-select  is  none,  set  auto is ok
