### ISSUE TITLE
[Bug]: splitListItem should support an `attrs` argument identical to prosemirror-schema-list@1.3.0

### ISSUE THREAD

**Issue by Nantris** [ueberdosis/tiptap#4182]
### Which packages did you experience the bug in?

core

### What Tiptap version are you using?

2.1.0-rc.9

### What’s the bug you are facing?

We need to be able to split `listItem`s, setting the desired attributes on the new `listItem`, but it appears the TipTap implementation of `splitListItem` doesn't actually mirror the ProseMirror implementation, nor does it support the second argument for `attrs` as I expected.

https://prosemirror.net/docs/ref/#schema-list.splitListItem

### What browser are you using?

Chrome

### What did you expect to happen?

Calling `editor.commands.splitListItem('listItem', { foo: true })` should result in the new node having attribute `foo="true"` specified (so long as that's been appropriately configured inside of `addAttributes`, which it has for us) 

### Anything to add? (optional)

Not being able to support this use case is majorly limiting for working with `listItems`. This limitation is important to address, but is only needed towards the end of work on `listItem`s in our project where we're addressing an edge case, so **it may not be immediately apparent just how many people actually will need this. I suspect it's a lot; especially considering it was added to ProseMirror's API too and marijnh is very cautious about increasing the surface area of the API.**

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by Slapbox** [comment]
Friendly bump. Can anyone advise on this? I've tried to work around this limitation but it doesn't seem to be possible. Support for `attrs` is required to achieve the aim here of setting attributes on the newly created item that results from the split.

**Comment by Slapbox** [comment]
Any update on this/any interest in supporting it? A week later I'm hitting this issue again and the workaround is crazy to have to use once, but much worse the second time.

**Comment by bdbch** [comment]
Hey @Slapbox - time wise i'm a bit capped right now but will try to get back to a lot of issues still open. In the meantime is it possible to maybe take a look at the splitList command yourself to see if you could provide a PR for that? Getting it merged / released would not be a big of a deal - otherwise I'd have to ask for some more time.

**Comment by Slapbox** [comment]
Thanks for your reply @bdbch; totally fair and super relatable! I've submitted a skeleton of a PR to do this in #4253, but it needs some testing/linting work which I probably won't find the time to complete unless I hit this a third time.

**Comment by nperez0111** [comment]
This is resolved with 2.6.0
