### ISSUE TITLE
[Bug]: Color Extension is Broken

### ISSUE THREAD

**Issue by towfiqi** [ueberdosis/tiptap#4189]
### Which packages did you experience the bug in?

@tiptap/react @tiptap/pm @tiptap/extension-color @tiptap/starter-kit @tiptap/extension-color @tiptap/extension-highlight @tiptap/extension-text-style @tiptap/extension-underline

### What Tiptap version are you using?

2.0.3

### What’s the bug you are facing?

I copied the Editor code from "Default text editor" doc. But when a selection is made and the color button is clicked, I get this error:

`Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name.`

You can view the issue here:
https://codesandbox.io/s/brave-ardinghelli-qzks5p?file=/src/App.tsx

### What browser are you using?

Chrome

### Code example

https://codesandbox.io/s/brave-ardinghelli-qzks5p?file=/src/App.tsx

### What did you expect to happen?

Set the color of the selected text.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
You have to remove the

```
{ HTMLAttributes: [ListItem.name] }
```

from the TextStyle configuration so it looks like this:

```
TextStyle.configure()
```

**Comment by towfiqi** [comment]
Thank You :)
