### ISSUE TITLE
[Bug]: editor.isActive returns true for all list types in nested lists/tasks 

### ISSUE THREAD

**Issue by ghost** [ueberdosis/tiptap#4190]
### Which packages did you experience the bug in?

extension-task-list, extension-task-item, core

### What Tiptap version are you using?

2.0.3

### What’s the bug you are facing?

Having different types of nested lists will check type of its parents as well when we call editor.isActive function. It should only check type of current list item where the selection is. 

Also toggling list types with buttons in nested lists will lead to different results in nested lists.

![image](https://github.com/ueberdosis/tiptap/assets/137985975/6df316d4-6326-4b71-8b99-8e93ca608287)

### What browser are you using?

Chrome

### Code example

https://codesandbox.io/s/tiptap-bug-isactive-returns-true-for-parents-as-well-in-nested-lists-tasks-fr5zhp

### What did you expect to happen?

I expect to editor.isActive function to check list type of where my cursor is, not its parents too.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by ashu12chi** [comment]
This is because of the way [isNodeActive](https://github.com/ueberdosis/tiptap/blob/develop/packages/core/src/helpers/isNodeActive.ts) is implemented, you can write your custom function which can modify the implementation of isNodeActive to give only last node.

**Comment by bdbch** [comment]
We could create a new method called `isExactNodeActive` or something like that which returns exactly what @ashu12chi talked about. Feel free to contribute if you want to build something like that!
