### ISSUE TITLE
Exception thrown when setting link url in Firefox

### ISSUE THREAD

**Issue by gregorykan** [ueberdosis/tiptap#420]
Fairly closely following the example code to create a link via some selected text, it works fine in Chrome but throws an error in Firefox.

![image](https://user-images.githubusercontent.com/10443269/62437746-a3a62f00-b798-11e9-93d4-1a0bdb6bcdae.png)

Here is a link to our implementation: https://github.com/loomio/loomio/blob/master/vue/src/components/lmo_textarea/lmo_textarea.vue#L171

**Comment by mayank-shaan** [comment]
+1

**Comment by philippkuehn** [comment]
I can't reproduce this but I've changes something in the latest update. Please test again!
