### ISSUE TITLE
[Bug]: getHTML function doesn't return all the content when using custom react nodes

### ISSUE THREAD

**Issue by surajmn1** [ueberdosis/tiptap#4204]
### Which packages did you experience the bug in?

tiptap/react 

### What Tiptap version are you using?

2.0.3

### What’s the bug you are facing?

i have created and used two custom react nodes claims and claim . passed the below as content 

```
 <claims>
   <claim id="1" order="1"></claim>
   <claim id="2" order="2"></claim>
   <claim id="3" order="3"></claim>
   <claim id="4" order="4"></claim>
  </claims>
  ```

When using custom react nodes the `getHTML` function, it doesn't return all the content as expected. However, the `getJSON` function works correctly.

### What browser are you using?

Chrome

### Code example

https://codesandbox.io/s/tiptap-gethtml-issue-jsrcgs?file=/src/Tiptap.jsx

### What did you expect to happen?

expected all the content to be returned by getHTML :
```
 <claims>
   <claim id="1" order="1"></claim>
   <claim id="2" order="2"></claim>
   <claim id="3" order="3"></claim>
   <claim id="4" order="4"></claim>
  </claims>
```

actual returned content : 
```
<claims></claims> 

```

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [x] Yes, I’m a sponsor. 💖

**Comment by QuinnStraus** [comment]
It looks like you need to add a zero into your renderHTML on line 72 to tell tiptap that content will be inserted (See this: https://tiptap.dev/guide/custom-extensions/#render-html). You did this right in the ClaimExtension, but not in ClaimsExtension.

**Comment by surajmn1** [comment]
Thank You :)
