### ISSUE TITLE
[Bug]: insertContentAt should either document that it changes selection or it should not change selection

### ISSUE THREAD

**Issue by Slapbox** [ueberdosis/tiptap#4213]
### Which packages did you experience the bug in?

core

### What Tiptap version are you using?

2.1.0-rc.11

### What’s the bug you are facing?

I find it frustrating that `insertContentAt` changes the selection. This severely limits its usefulness and this behavior is undocumented. There's no suggestion it will affect selection but it does.

### What browser are you using?

Chrome

### What did you expect to happen?

`insertContentAt` inserts content only, without changing selection.

### Anything to add? (optional)

If it's necessary to change the selection then it should come with an option to revert the selection after.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by svenadlung** [comment]
Hi @Slapbox, changing the selection after inserting content is the default behavior. Have you tried this?

```editor.commands.insertContentAt(12, '<p>Hello world</p>', { updateSelection: false })```


https://github.com/ueberdosis/tiptap/blob/6cbc2d423391c950558721510c1b4c8614feb534/docs/api/commands/insert-content-at.md#L20
