### ISSUE TITLE
[Bug]: react-dom.development.js:16305 Uncaught TypeError: Class constructor Editor2 cannot be invoked without 'new'

### ISSUE THREAD

**Issue by OkeleyeVick** [ueberdosis/tiptap#4215]
### Which packages did you experience the bug in?

Vite, React, Tailwind, Iconify,  framer motion

### What Tiptap version are you using?

2.0.3

### What’s the bug you are facing?

I installed Tiptap into my project directory just as the documentation showed. It brought out an error in the console like so: "Uncaught TypeError: Class constructor Editor2 cannot be invoked without 'new' "

I noticed Create React App was used for the documentation under installation guide for React, I am using Vite for React in place of Create React App

### What browser are you using?

Chrome

### What did you expect to happen?

I expect it to display the UI component on the web page but it keeps throwing the same error 

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Vite should work without any problems. Can you provide us with a demo or replicate your error in a CodeSandbox? We're using Vite for everything demo related and it works there.

**Comment by OkeleyeVick** [comment]
> Vite should work without any problems. Can you provide us with a demo or replicate your error in a CodeSandbox? We're using Vite for everything demo related and it works there.

Do you need a screenshot of the error log?

**Comment by bdbch** [comment]
Can you create a React+Vite Sandbox here: https://codesandbox.io/

And send me the Link of your Codesandbox so I can replicate your error?

**Comment by OkeleyeVick** [comment]
https://codesandbox.io/s/confident-vaughan-ykq686?file=/src/App.js

I was able to update and reinstall Tiptap, exactly what it shows on sandbox is what it shows on my project, just a textarea field

**Comment by svenadlung** [comment]
Can't see any issues in console? What exactly is needed to reproduce the error?

**Comment by OkeleyeVick** [comment]
Errors are no longer showing cos I updated my packages and installed Tiptap according to the documentation for react
But take a look at the codesandbox code and what it displays https://codesandbox.io/s/confident-vaughan-ykq686?file=/src/App.js

**Comment by svenadlung** [comment]
Textarea? For me everything looks just fine 😵

<img width="1036" alt="Screenshot 2023-07-15 at 21 47 44@2x" src="https://github.com/ueberdosis/tiptap/assets/11420688/fe09732e-ed85-4878-8689-6b1e5734e66e">

**Comment by OkeleyeVick** [comment]
![Screenshot (220)](https://github.com/ueberdosis/tiptap/assets/102109008/6c526333-9975-4885-a277-6407ed8c17cb)
I thought it was supposed to display this UI

**Comment by svenadlung** [comment]
Nope, Tiptap is headless and doesn't come with any UI – it has full flexibility. Feel free to use the code from the examples.
