### ISSUE TITLE
[PRO]: Details extension messes with scroll position of editor

### ISSUE THREAD

**Issue by bjgrosse** [ueberdosis/tiptap#4224]
### Which packages did you experience the bug in?

extension-details

### What Tiptap version are you using?

2.0.0

### What’s the bug you are facing?

If the user's selection/cursor position is offscreen, expanding/collapsing a detail extension causes the editor to scroll to the user's selection position. Is the detail extension doing a editor focus() command after the user's click? seems like that might cause this behavior. 

![chrome_fQ5RcGEHi2](https://github.com/ueberdosis/tiptap/assets/14151299/30928bc0-922f-42dd-b275-bb4bb13c11f6)

### What browser are you using?

Chrome

### What did you expect to happen?

Scroll position should not be affected by toggling a details extension.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bjgrosse** [comment]
Note, the task item extension which is user interactive does not have this problem, but I do see that when it does the focus command, it's doing it like this: `.focus(undefined, { scrollIntoView: false }`

**Comment by Slapbox** [comment]
@bjgrosse it does have that issue on Android. I just filed an issue: https://github.com/ueberdosis/tiptap/issues/4227

**Comment by svenadlung** [comment]
Good find. Details extension should be fixed with version 2.2.4 🙏
