### ISSUE TITLE
Why getPos() returns false in production mode? 

### ISSUE THREAD

**Issue by Auxxxxlx** [ueberdosis/tiptap#424]
The following code runs well in  development mode but not in production mode.

![image](https://user-images.githubusercontent.com/13865581/62555145-fec54800-b8a4-11e9-83ae-984c3cdc569c.png)

![image](https://user-images.githubusercontent.com/13865581/62555181-0edd2780-b8a5-11e9-98f8-8303fd4972bc.png)

```javascript
// vue.config.js
module.exports = {
  pluginOptions: {
    electronBuilder: {
      externals: ['leveldown', 'level', 'pouchdb'],
      builderOptions: {
        win: {
          target: 'nsis',
          icon: 'build/icon.png',
        },
        nsis: {
          oneClick: false,
          allowToChangeInstallationDirectory: true,
          artifactName: '${productName} ${version}.${ext}'
        }
      }
    },

  },
  runtimeCompiler: true,
  productionSourceMap: false,
  parallel: true,
}
```

**Comment by hanspagel** [comment]
I’m closing it for now, but would be good to know if you did find a solution to this! ✌️
