### ISSUE TITLE
[Bug]: typing directly after link adds to link when it should not

### ISSUE THREAD

**Issue by joshdchang** [ueberdosis/tiptap#4249]
### Which packages did you experience the bug in?

extension-link

### What Tiptap version are you using?

2.0.4

### What’s the bug you are facing?

When typing directly after a link using `extension-link`, TipTap adds the newly typed text to the preceding link, rather than adding it as normal text.

For example, if you were to add a link like [https://example.com](https://example.com)| and your cursor was where the "|" is, if you were to then keep typing, let's say you then typed " is a cool website", the new state of the editor would then be [https://example.com is a cool website](https://example.com)|

This is bad default behaviour and is difficult to find a workaround for because it is built-in to how TipTap deals with marks. This behaviour is good and makes sense for something like **bold** or _italic_, but not for links.

Thank you!

### What browser are you using?

Chrome

### What did you expect to happen?

For example, if you were to add a link like [https://example.com](https://example.com)| and your cursor was where the "|" is, if you were to then keep typing, let's say you then typed " is a cool website", the new state of the editor should then be [https://example.com](https://example.com) is a cool website| 

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by dufftie** [comment]
Had same issue, add "exitable: true" and "inclusive: false" to Mark configuration

**Comment by joshdchang** [comment]
This worked like a charm, thank you! I would still recommend to the maintainers that they make this the default behaviour, or at least add it as an option to the link configuration.

For those curious, this is what the code looks like:

```ts
Link.extend({
  inclusive: false,
  exitable: true,
})
```
