### ISSUE TITLE
[Bug]: addProseMirrorPlugins fires twice at editor initialization

### ISSUE THREAD

**Issue by Nantris** [ueberdosis/tiptap#4257]
### Which packages did you experience the bug in?

extension-link

### What Tiptap version are you using?

2.1.0-rc.12

### What’s the bug you are facing?

I am reporting this specifically for `extension-link` but it may to be more wide ranging than that.

Note the plugin keys have `1` appended to them on the second run. I can't determine if this really means the plugin is loaded twice or if it matters in practice.

# `debugger` hit 1
![image](https://github.com/ueberdosis/tiptap/assets/6835891/0d27096c-9c82-40b9-9ddb-ee50c04a592d)

# `debugger` hit 2
![image](https://github.com/ueberdosis/tiptap/assets/6835891/47c733ff-5979-43e7-acb1-08b57cbae1cd)

### What browser are you using?

Chrome

### What did you expect to happen?

`addProseMirrorPlugins` should only run one time.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by Slapbox** [comment]
This seems to affect all nodes which you use the `.extend()` functionality on. When it runs a second time the keys change from like `codeBlockVSCodeHandler$` to `codeBlockVSCodeHandler$1`. I assume that means these are being loaded twice?

**Comment by 634750802** [comment]
Maybe related to https://github.com/ueberdosis/tiptap/discussions/5136

**Comment by Nantris** [comment]
@634750802 that does seem related, but it should probably be filed as an issue, not a discussion. I guess the maintainers can probably change that though if they see fit.

**Comment by nperez0111** [comment]
This should be [fixed](https://github.com/ueberdosis/tiptap/pull/5147) with version 2.4.0, feel free to try it out!
