### ISSUE TITLE
[Bug]: Links are partially or entirely unlinked when modified

### ISSUE THREAD

**Issue by Slapbox** [ueberdosis/tiptap#4258]
### Which packages did you experience the bug in?

extension-link

### What Tiptap version are you using?

2.1.0-rc.12

### What’s the bug you are facing?

The way this problem manifests in my editor is different than it manifests on the demos, even when I reduce my code to only use `StarterKit` + `Link` with no configuration options set. **Edit: (I suspect this is due to `2.0.4` vs `2.1.0-rc.12`)**

In my environment, deleting the colon, slash, or any of the characters in `http` (but not the `s`) causes the last character to become un-marked.

https://github.com/ueberdosis/tiptap/assets/6835891/0d402fca-bbff-48d2-b507-896258812608

In the examples, deleting those characters un-marks the entire mark, which is more reasonable but still not really desirable. I can't trace where this behavior is originating from. Can anyone advise?

### What browser are you using?

Chrome

### What did you expect to happen?

Links should not be removed or mangled once set

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by Slapbox** [comment]
This appears to be due to the `autolink` option.

**Comment by Slapbox** [comment]
This also occurs when you change link text or insert a space into a link.

I view this as a rather high priority issue. This is the only issue of the many I've filed that's a deal breaker for releasing our work to production.

**Comment by Slapbox** [comment]
Interestingly, one time I loaded up the editor this did not occur.

**Comment by Slapbox** [comment]
It's caused by these lines:

https://github.com/ueberdosis/tiptap/blob/05a2edfc16e297effa86d1583fb1680be0320f25/packages/extension-link/src/helpers/autolink.ts#L61-L63

I'm not clear on their intended function so I can't provide any fix besides removal.

**Comment by bdbch** [comment]
Working on it!

**Comment by bdbch** [comment]
I can't seem to get the unlinking issue replicated on my end. Are you on chrome or some other browser? I tried to use the same `https://example.com` domain and delete the same part, but my link was kept in tact?

**Comment by Slapbox** [comment]
There's something peculiar about this particular issue. I'm in Chrome, but even when I remove our custom link logic and pare our editor down to bare bones, we still see the single letter being unlinked in this case, but on the [link demo page](https://tiptap.dev/api/marks/link) it unlinks the entire thing.

**Comment by bdbch** [comment]
That I could reproduce. Will take a look into it.

**Comment by bdbch** [comment]
I found a solution for it and pushed a fix for that. Will probably release soon.
