### ISSUE TITLE
[Bug]: setNodeSelection fails

### ISSUE THREAD

**Issue by bytedance-yinz** [ueberdosis/tiptap#4262]
### Which packages did you experience the bug in?

core

### What Tiptap version are you using?

2.0.4

### What’s the bug you are facing?

```tsx
const pos = editor.state.selection.$head.start(1);
editor.chain().setNodeSelection(pos).focus().run();
```
then get `this.dom.removeAttribute is not a function` error 

### What browser are you using?

Chrome

### Code example

https://codesandbox.io/s/wonderful-chihiro-9zpn25?file=/src/App.js

### What did you expect to happen?

select node content without error

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
I think you're trying to get the current nodeSelection of the node your in? That's why you use Level 1 I guess?

**Comment by bytedance-yinz** [comment]
@svenadlung @bdbch 

I want to select the Paragraph where the cursor is currently located

**Comment by bytedance-yinz** [comment]
Sorry, I made a mistake. I misunderstood the meaning of setNodeSelection.
