### ISSUE TITLE
How can a node (made by user-defined vue componnet) know whether it's selected?

### ISSUE THREAD

**Issue by beeplin** [ueberdosis/tiptap#427]
![image](https://user-images.githubusercontent.com/13058150/63219335-31731880-c1a2-11e9-832c-be505d133368.png)

The math formula part in the picture above is a user-defined math node (as a vue component), but when selected, it cannot change its background color just like the text parts around it. 

How can such a node know if it is being selected, so it can change its style?

**Comment by beeplin** [comment]
I noticed the self-defined vue component node accepts a `selected` prop, but it is always `false` even the math node is selected:

![image](https://user-images.githubusercontent.com/13058150/63312929-7c716500-c335-11e9-92ac-6e3363a7709f.png)

**Comment by BrianHung** [comment]
Is `atom: true` in schema? I'm not sure if its related, but `NodeSelection` only works if `atom: true` and I assume `NodeSelection` is called when the entire node is selected.
