### ISSUE TITLE
integrating into forms

### ISSUE THREAD

**Issue by iteniasim** [ueberdosis/tiptap#430]
How do i actually integrate the editor in the form, is it written in the docs? Couldn't find it. can some one help. A simple example to integrate in to form would be great.

**Comment by matt-morris** [comment]
I'd just like to give this one a bump. Tiptap looks absolutely amazing, but what's the recommended approach for tying this into a form?

**Comment by hanspagel** [comment]
Thanks! The README should give you a start. 

And a new, improved and interactive documentation that’ll be way easier to follow is already in the works. :)
