### ISSUE TITLE
[Bug]: `unsetColor`, `unsetFontFamily`, etc broken due to `removeEmptyTextStyle` mistakenly removing _all_ text styles if just first selected mark has no text styles left

### ISSUE THREAD

**Issue by sjdemartini** [ueberdosis/tiptap#4311]
### Which packages did you experience the bug in?

text-style, color, font-family

### What Tiptap version are you using?

2.0.4

### What’s the bug you are facing?

`TextStyle`'s `removeEmptyTextStyle` command will unexpectedly remove any/all text styles applied to selected marks/nodes, if the _first_ mark in the selection will end up not having any text styles. This is due to the fact that `getMarkAttributes` returns only the attributes of the first matching mark (as reported in this related issue https://github.com/ueberdosis/tiptap/issues/3481), so it does not consider whether there are still text styles in subsequent selected content:

https://github.com/ueberdosis/tiptap/blob/6cbc2d423391c950558721510c1b4c8614feb534/packages/extension-text-style/src/text-style.ts#L54-L56

**This means that commands like `unsetColor` and `unsetFontFamily` are broken and will mistakenly remove all text styles in scenarios where they should not.**

For instance, in the CodeSandbox below, if you select the first 3 lines and then `unsetFontFamily`, you'll see it also mistakenly removes the color from the second line: 

![tiptap_unsetFontFamily_bug](https://github.com/ueberdosis/tiptap/assets/1647130/711fc720-4ddc-45fc-893c-ebf4bb216887)

Or similarly if you select text and call `unsetColor` where the first mark has no styles or just has color, you'll see it mistakenly removes the font family from the third line:

![tiptap_unsetColor_bug_2](https://github.com/ueberdosis/tiptap/assets/1647130/238b2d5c-0a51-435d-81f2-0a2f499ac43a)

### What browser are you using?

Chrome

### Code example

https://codesandbox.io/s/tiptap-bug-with-removeemptytextstyle-unsetfontfamily-unsetcolor-h3rsfw?file=/src/App.js

### What did you expect to happen?

`removeEmptyTextStyle` should operate mark-by-mark so that it only removes text-style on the marks where it's appropriate, rather than across all selected marks, so that:

- `unsetColor` only removes _color_ from the selected text, without affecting any other text styles.
- `unsetFontFamily` only removes _font family_ from the selected text, without affecting any other text styles

### Anything to add? (optional)

If there were a standardized way to `getAttributes` across multiple nodes/marks (rather than just the first) as described here https://github.com/ueberdosis/tiptap/issues/3481, this may be easier to resolve.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Thanks, prioritized that high and moved it after the triage so we'll come back to it when we fill up the backlog again.
