### ISSUE TITLE
[Bug]: Focus-extension locks up browser when hitting enter

### ISSUE THREAD

**Issue by jguitarz** [ueberdosis/tiptap#4323]
### Which packages did you experience the bug in?

extension-focus

### What Tiptap version are you using?

2.0.3

### What’s the bug you are facing?

Go here: https://tiptap.dev/api/extensions/focus
In the demo, select inside any node and hit the enter key
Browser freezes up

### What browser are you using?

Chrome

### What did you expect to happen?

I expected it to start a new node after the current node, update the focus to that new node, and ... not freeze the browser

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by svenadlung** [comment]
Maybe I'm misunderstanding. Everything seems to be working for me. Can you describe the misbehavior in a little more detail or make a short video?

**Comment by jguitarz** [comment]
Sure here is a quick screen capture showing the browser freeze.  Happens right when I hit enter on the keyboard.

https://github.com/ueberdosis/tiptap/assets/3741060/28dcce51-2578-4800-96d6-15331c7b62a3

**Comment by svenadlung** [comment]
Thank you. Hm, doesn't happen on my machine though.

**Comment by bdbch** [comment]
Thanks for letting us know, glad you found a way to figure it out.
