### ISSUE TITLE
[Bug]: YouTube video pasting broken with Link extension since 2.1.0-rc.2

### ISSUE THREAD

**Issue by ahukkanen** [ueberdosis/tiptap#4347]
### Which packages did you experience the bug in?

extension-link, extension-youtube

### What Tiptap version are you using?

2.1.X

### What’s the bug you are facing?

The paste handler configured for the YouTube extension does not work when Link extension is used as well. The paste rule is defined here:
https://github.com/ueberdosis/tiptap/blob/af017d18ade9fc741c37c325b187ae344daff040/packages/extension-youtube/src/youtube.ts#L127-L133

Instead of the YouTube video being embedded automatically on paste, a link appears pointing to the YouTube URL.

This works fine with 2.0.4 but in any version 2.1.X it is broken (broken since stable release 2.1.0 and from RC release 2.1.0-rc.2).

### What browser are you using?

Chrome

### Code example

https://codesandbox.io/s/objective-edison-zxxc94

### What did you expect to happen?

I would expect the YouTube extension's paste rule to work alongside the Link extension.

### Anything to add? (optional)

Here is a working example using version 2.0.4 (the same example using 2.0.4):
https://codesandbox.io/s/reverent-dust-j9cmm5

To drill down even deeper, it seems to also work with `2.1.0-rc.1` but it is broken in `2.1.0-rc.2`.

Potentially breaking change between these releases #3975 based on the `autolink.js` change history within the `extension-link` package.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Thanks @ahukkanen – I created a fix for this in #4354

**Comment by Benny739** [comment]
Did #4354 solve the issue for anyone? I'm still having this issue in 2.1.11

**Comment by ahukkanen** [comment]
Fixed by #4354. Fix shipped in v2.1.11.
