### ISSUE TITLE
[Bug]: Link opens when clicking anything in a text selection that is not a link

### ISSUE THREAD

**Issue by yan-yanishevsky** [ueberdosis/tiptap#4364]
### Which packages did you experience the bug in?

extension-link

### What Tiptap version are you using?

2.1.6

### What’s the bug you are facing?

![image](https://github.com/ueberdosis/tiptap/assets/11583056/0ab8d228-2dda-47d7-95dd-ed096f451a3f)

### What browser are you using?

Chrome

### What did you expect to happen?

The cursor should just move in a clicked area, not open a link

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by mkreuzmayr** [comment]
I also faced this problem when I upgraded to anything above 2.1, I can confirm this problem was not happening in version 2.0.4. I just downgraded for now.

**Comment by Itsnotaka** [comment]
> I also faced this problem when I upgraded to anything above 2.1, I can confirm this problem was not happening in version 2.0.4. I just downgraded for now.
> 
> 
> 
> EDIT:
> 
> 
> 
> Only the extension for the link needs to be downgraded.
> 
> `"@tiptap/extension-link": "2.0.4"`

Experiencing the same problem and you are my savior

**Comment by aldinezi** [comment]
@yan-yanishevsky it should be fixed in the latest release 
https://github.com/ueberdosis/tiptap/releases/tag/v2.1.8

**Comment by yan-yanishevsky** [comment]
Thank you
