### ISSUE TITLE
[Bug]: Arrow up after mention and selecting mention not working

### ISSUE THREAD

**Issue by emil-daniel** [ueberdosis/tiptap#4367]
### Which packages did you experience the bug in?

extension-mention

### What Tiptap version are you using?

2.1.6

### What’s the bug you are facing?

After the cursor gets to the end of the mention, pressing arrow up stops working.
Also selecting the mention using shift + arrow left doesn't work.

### What browser are you using?

Chrome

### Code example

https://codesandbox.io/s/recursing-james-5w7v9y?file=/Demo.tsx:1776-3592

### What did you expect to happen?

The cursor to move an row up. 
Shift+ arrow left: select the mention

### Anything to add? (optional)

https://github.com/ueberdosis/tiptap/assets/74368014/c440762a-0db6-450f-9fe0-7a6c5b17ccd3

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by MtheDV** [comment]
Also experiencing this
