### ISSUE TITLE
TypeError: Cannot read property 'matchesNode' of null

### ISSUE THREAD

**Issue by gomezmark** [ueberdosis/tiptap#438]
Hi,

I've a created a separate component for the editor.

Then, I'm passing the string html to the `setContent` function.
At first it's working fine, but later on I encountered this error.

`TypeError: Cannot read property 'matchesNode' of null`

I am also aware of ssr and on setting the editor on mounted property.

On my component I have this snippet
`setContent (value) {
 let vm = this
 setTimeout( function () {
  if (value) {
   vm.editor.setContent(value, true)
   vm.$forceUpdate()
  }
 }, 3000)
}`

Any idea what I am doing wrong?

Thanks.

**Comment by hognevevle** [comment]
@gomezmark Did you ever find a solution/workaround for this? I'm running into the same error when using the `clearContent` function.

**Comment by mgomez-dev** [comment]
hi @hognevevle 

I separate the component for the editor and put it on the layout.
Then, every time I calling the open function, I just clearing the v-model.

Seperate Component
```
          <tinymce-editor 
              v-model="value"
              :init="config">
            </tinymce-editor>

....

  methods: {
    open (value, resolve) {
      const vm = this
      this.dialog = true
      vm.value = value
  }
}

```

I hope this could help you.

**Comment by gomezmark** [comment]
hi @hognevevle 

I separate the component for the editor and put it on the layout.
Then, every time I calling the open function, I just clearing the v-model.

Seperate Component
```
          <tinymce-editor 
              v-model="value"
              :init="config">
            </tinymce-editor>

....

  methods: {
    open (value, resolve) {
      const vm = this
      this.dialog = true
      vm.value = value
  }
}

```

I hope this could help you.

**Comment by hognevevle** [comment]
Hmm, AFAIK [tiptap doesn't support v-model](https://github.com/ueberdosis/tiptap/issues/133). Also your code shows you're using TinyMCE, and not tiptap. Did you switch from tiptap to TinyMCE at some point perhaps, or was the issue with TinyMCE all along?

**Comment by gomezmark** [comment]
Hi @hognevevle ,

My apologize I was lost. I switched to other plugin. 
Sorry.

**Comment by exnihilo-creatio** [comment]
@hognevevle Have you found a solution?

**Comment by Flamenco** [comment]
I have same problem using Vue.  The problem is the line
```js
  var updateDoc = redraw || !this.docView.matchesNode(state.doc, outerDeco, innerDeco);
```
where `this.docView` is null

I am conditionally showing and hiding the component, and creating/destroying the editor, so perhaps that is the issue.

**Comment by nc** [comment]
+1

**Comment by santhosh-ps** [comment]
+1
