### ISSUE TITLE
[Bug]: I can't focus other input in a form

### ISSUE THREAD

**Issue by hongvanpc10** [ueberdosis/tiptap#4406]
### Which packages did you experience the bug in?

core

### What Tiptap version are you using?

2.1.7

### What’s the bug you are facing?

 I can't focus other input in a form
when i focus other input, it auto focus tiptap editor

### What browser are you using?

Safari

### What did you expect to happen?

i can focus other input

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by yusren** [comment]
same here. for my case, the page always reloads every time I click the toolbar button

**Comment by bdbch** [comment]
Can you give more info, example code or even a codesandbox? I don't know what form you are talking about or how it's setup. I'll close this for now until there is a better explanation.
