### ISSUE TITLE
Enter key anywhere in the form focuses on tiptap

### ISSUE THREAD

**Issue by dolbex** [ueberdosis/tiptap#441]
**Describe the bug**
I have several forms that utilize tiptap. In each of the forms when I hit the "enter" key it focuses on tiptap. I have no @key events. Nada. 

**Steps to Reproduce / Codesandbox Example**
1. Create a form which includes an editor
2. Focus on any other form element (text input for sure)
3. Press enter

**Expected behavior**
Not focus on tiptap

**Environment**
 - OS: OSX
 - Browser Chrome
 - Version 76
 - Mobile / Desktop: Desktop

**Additional Info**
It does appear that when I remove all the buttons from the editor-menu-bar that it no longer happen.

**Comment by vasisouv** [comment]
@dolbex 

you changed them into what?

**Comment by vasisouv** [comment]
If anyone comes across this problem, in my case it was due to the commands in the menu-bar being button elements without `type="button"`. Adding type fixed it for me
