### ISSUE TITLE
[Bug]: Link doesnt autolink correctly (not after single space)

### ISSUE THREAD

**Issue by ioma8** [ueberdosis/tiptap#4417]
### Which packages did you experience the bug in?

extension-link

### What Tiptap version are you using?

2.1.8

### What’s the bug you are facing?

I have autolink turned on. When I type a web address I expect it to be converted into hyperlink once any whitespace is added to the end of it. Now it only makes links when either I make line-break (Enter key) or pres Space key three times. I believe this is buggy behaviour. The links should be made also inside existing paragraphs and no user will figure out on his own that he has to make 3 spaces after the link to make it active.

### What browser are you using?

Chrome

### What did you expect to happen?

Create link after making ANY single whitespace after typing out a web address. 
In essence if you try out remirror (another prosemirror editor) example on their homepage, it works as I expect it to work: https://remirror.io/ 

### Anything to add? (optional)

If this is not a bug, then I am asking if there is any workaround to solve this issue for me?

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by james-william-r** [comment]
Okay, hear me out. I was having this exact issue, autolink only working after three spaces, I tried the improvement in your PR, but still no luck. I was messing around with something else, long story short, added "white-space: pre-wrap;' to the editor, now it works perfectly. 🙃 - It's also fixed a tonne of other issues I was having. Unless I'm mistaken, this isn't mentioned anywhere in the docs, but seems pretty essential.

**Comment by bdbch** [comment]
Is this still relevant? I tried to replicate this in the most recent version of Tiptap but couldn't get it to work.
