### ISSUE TITLE
Insert text including paragraphs

### ISSUE THREAD

**Issue by bernhardh** [ueberdosis/tiptap#442]
I am trying to implement a "paste from clipboard"-button. 

```js
navigator.clipboard.readText()
    .then(text => {
        const transaction = this.editor.state.tr.insertText(text);
        this.editor.view.dispatch(transaction);
    })
    .catch(err => {
        alert("Sie müssen die Zwischenablage freigeben");
    });
```

And it works, but how to format the text correctly? For example, I have the following in my clipboard:

```
This is one paragraph.

This is the seconde one.
```

It inserts now exactly the above, without any `<p>` tags. Is there a way to insert the text formated?

**Comment by hanspagel** [comment]
With the upcoming [tiptap v2](https://blog.ueber.io/post/our-plan-for-tiptap-2/) there will be a .insertHTML() API method. 🙃
