### ISSUE TITLE
[Bug]: The result of isActive is incorrect

### ISSUE THREAD

**Issue by hoiheart** [ueberdosis/tiptap#4428]
### Which packages did you experience the bug in?

core

### What Tiptap version are you using?

2.1.8

### What’s the bug you are facing?

The result of isActive is incorrect.

### What browser are you using?

Chrome

### What did you expect to happen?

I want to know which font is active in the current selection in the following structure

![image](https://github.com/ueberdosis/tiptap/assets/25652218/5d72d609-137f-4520-88b6-1d8c8f3132a2)

```js
['Roboto', 'Lato'].map((item) => {
  console.log(item, editor.isActive({ fontFamily: item }));
});
```

### This returns the correct value

![image](https://github.com/ueberdosis/tiptap/assets/25652218/dbddde2d-959b-4ad6-903e-999769f14b51) ![image](https://github.com/ueberdosis/tiptap/assets/25652218/b9861ece-bda7-49b1-a89b-dce30715c2cb)

![image](https://github.com/ueberdosis/tiptap/assets/25652218/9fe64c15-040d-4fa4-8dfd-297182d95887) ![image](https://github.com/ueberdosis/tiptap/assets/25652218/105e0deb-6311-4559-bc64-61b1ff18318a)

![image](https://github.com/ueberdosis/tiptap/assets/25652218/89e7cfdb-8aca-4e2c-ba33-1468a7d0abde) ![image](https://github.com/ueberdosis/tiptap/assets/25652218/b9b4884f-25c4-4d3d-976f-b44abf997a44)

![image](https://github.com/ueberdosis/tiptap/assets/25652218/396481e9-ba25-4413-af39-d47791372328) ![image](https://github.com/ueberdosis/tiptap/assets/25652218/73df020d-e6a5-441b-8679-6f6a86d05cee)

### But it doesn't work consistently near the baseline
![image](https://github.com/ueberdosis/tiptap/assets/25652218/f8191a6f-5c11-4e0c-a692-f1c8d7e265a9) ![image](https://github.com/ueberdosis/tiptap/assets/25652218/6f9e703b-828d-4ce4-bf43-355275a44718)

![image](https://github.com/ueberdosis/tiptap/assets/25652218/fb331768-969a-4d65-9628-83d935235bdf) ![image](https://github.com/ueberdosis/tiptap/assets/25652218/623deb37-c697-48e9-89e4-caa9da2bfc55)
This area is actually default

![image](https://github.com/ueberdosis/tiptap/assets/25652218/ca77b246-00e3-4871-b59b-6008d821bd3e) ![image](https://github.com/ueberdosis/tiptap/assets/25652218/25a9c3e5-a694-46ba-ab2f-14eb33489240)
Other areas are also not accurate

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by svenadlung** [comment]
I assume you are using "extension-text-style". You should be able to query the active state as follows:
`editor.isActive('textStyle', { fontFamily: 'Inter' }) `
