### ISSUE TITLE
Updating menu position not enough often

### ISSUE THREAD

**Issue by usb248** [ueberdosis/tiptap#444]
Hi, i trying to modify bubble link in order to display bubble only if there is text selected (at least one letter) or if the cursor is in a link.

**Describe the bug**
Select a text (at least one letter), see correct position, place the cursor elsewhere in the bloc text (without selecting several letter in a link, just place the cursor at an other position/anchor). menu.left and menu.bottom keep old value. Menu's positions only update during a transaction. The position should be updated when we place the cursor without having to select letter

**Expected behavior**
Correct position when the editor receive the cursor (click, mousedown ?)

**Environment**
 - OS: Win 10
 - Browser last version FF
 - Mobile / Desktop: Desktop

**Comment by hanspagel** [comment]
Oops, nothing happened here. I’m closing this now. We are about to rewrite all interface components. But I keep in mind to improve this in the new version. ✌️
