### ISSUE TITLE
Command to insert a custom element like an embed

### ISSUE THREAD

**Issue by ninest** [ueberdosis/tiptap#446]
An example is shown [here](https://tiptap.scrumpy.io/embeds), but how do I make a command to insert embed.js? I figure it will be something like this:

```
export default class Iframe extends Node {
    ...
    get commands() {
        // something here?
    }
}
```
I couldn't find anything about this in the [docs](https://tiptap.scrumpy.io/docs).

**Comment by estani** [comment]
I have the same issue. I'm trying to add form elements but the commands never get registered, I'm ot fully understanding how the `editor-menu-bar` works.

I tried this for the iframe example, but it doesn't work:
```vue
<editor-menu-bar class="menu-bar" :editor="editor" v-slot="{ commands, isActive }">
  <button type="button" class="menubar-button" @click="commands.iframe">
          i
   </button>
</editor-menu-bar>
```
and in the iframe component, just added the following to the get schema:
```vue
      commands({ type, schema}) {
        return () => toggleWrap(type, schema.nodes.paragraph)
      }
```
With this config `commands.iframe` is not being defined. What am I missing?
I'm still trying to make sense of the examples, but there's little info about how this all works besides the code itself.

**Comment by estani** [comment]
ok, the commands attribute should not be defined in the schema, but one level above. I got that far.

**Comment by themindstorm** [comment]
#112 might help. I just found it, and I'll try it soon.

**Comment by estani** [comment]
I've been trying something like that for some time now, but still can't manage to put all the pieces together. Either the template can't be compiled, or is not found at all, or... I'll try a little more but I'm giving up soon enough.
How hard should it be to write a button that just adds a dome node? This looks way too complicated.
The default tiptap configuration works perfectly so I guess it's just me, I'm not following the concept behind it...
Hope you have better luck than me!

**Comment by zacharykatsnelson** [comment]
wondering this too
