### ISSUE TITLE
[Bug]: Text selection disappears on menu item select

### ISSUE THREAD

**Issue by daibhin** [ueberdosis/tiptap#4462]
### Which packages did you experience the bug in?

react

### What Tiptap version are you using?

2.1.0-rc.12

### What’s the bug you are facing?

When you select an option in the bubble menu it removes the blue background which indicates that the text is selected

https://github.com/ueberdosis/tiptap/assets/6685876/b3d74aed-7e0d-41cf-9b22-3309ab4aedf4

### What browser are you using?

Chrome

### Code example

https://codesandbox.io/s/stoic-forest-wqt6pv?file=/src/App.js

### What did you expect to happen?

The selection to remain so that it is very clear that multiple buttons in the menu can be clicked and that changes will be applied to the same text

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

**Comment by steven-qi** [comment]
@daibhin  just FYI, you could use 
```es6
editor.chain().focus().toggleMark("bold").run()
```

**Comment by daibhin** [comment]
Ah, solved my problem! Thanks :)
