### ISSUE TITLE
[Bug]: updateAttributes should only update attribute of current node, instead of all parent nodes with the same type

### ISSUE THREAD

**Issue by steven-qi** [ueberdosis/tiptap#4466]
### Which packages did you experience the bug in?

core

### What Tiptap version are you using?

2.1.8

### What’s the bug you are facing?

I'm trying to build a customized ordered list with different list item types (i.e., `a`, `A`, `i`, & `I`).

I was able to make it work by some trivial extending the default ordered list, which is great. 👍 

However, I found that when there are multiple levels of ordered lists, calling `commands.updateAttributes('orderedList', { type })` will always update the `type` attributes on both nested and parent levels.

From what I learned, this looks like a bug of `updateAttributes` itself, as it will find all nodes with the same type, and call `tr.setNodeMarkup` on each of them.

https://github.com/ueberdosis/tiptap/blob/develop/packages/core/src/commands/updateAttributes.ts#L48-L54

I was able to work around this by updating only the latest found node manually.

![image](https://github.com/ueberdosis/tiptap/assets/6123222/fe54d8d0-af0f-48d7-ae98-785a30020196)

### What browser are you using?

Chrome

### What did you expect to happen?

`updateAttributes` should only update attributes of the nearest node when it is wrapped into a node of the same type.

### Anything to add? (optional)

`resetAttributes` may have similar issue

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by nperez0111** [comment]
Should be resolved with 2.10.0
