### ISSUE TITLE
[Bug]: can't access `ref` on `EditorContent` in react

### ISSUE THREAD

**Issue by sereneinserenade** [ueberdosis/tiptap#4470]
### Which packages did you experience the bug in?

react

### What Tiptap version are you using?

2.1.11

### What’s the bug you are facing?

`<EditorContent editor={editor} ref={editorContentRef} />`

I want to access `ref` on `EditorContent` but it's not working.

### What browser are you using?

Chrome

### Code example

`<EditorContent editor={editor} ref={editorContentRef} />`

### What did you expect to happen?

I should be able to access `EditorContent`'s internal state and other things via `ref`.

### Anything to add? (optional)

fix is in #4471 

instead of 

```tsx
const EditorContentWithKey = (props: EditorContentProps) => {
  const key = React.useMemo(() => {
    return Math.floor(Math.random() * 0xFFFFFFFF).toString()
  }, [props.editor])

  // Can't use JSX here because it conflicts with the type definition of Vue's JSX, so use createElement
  return React.createElement(PureEditorContent, { key, ...props })
}
```

we can do 

```tsx
const EditorContentWithKey = React.forwardRef((props: EditorContentProps, ref: React.RefObject<any>) => {
  const key = React.useMemo(() => {
    return Math.floor(Math.random() * 0xFFFFFFFF).toString()
  }, [props.editor])

  // Can't use JSX here because it conflicts with the type definition of Vue's JSX, so use createElement
  return React.createElement(PureEditorContent, { key, ref, ...props })
})
```

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by ioma8** [comment]
I wish this to be fixed.

**Comment by Slapbox** [comment]
Related to #4632.

Both occur because the props aren't passed through at all.

**Comment by ehynds** [comment]
I opened https://github.com/ueberdosis/tiptap/pull/4396 a while back to fix this. Can this be reviewed and merged?

**Comment by HRSAndrabi** [comment]
Also hoping to see this change implemented.

**Comment by nperez0111** [comment]
Resolved with https://github.com/ueberdosis/tiptap/pull/4396
