### ISSUE TITLE
[PRO]: Issue with deploying Pro Extensions on Render.com

### ISSUE THREAD

**Issue by prabir-vora** [ueberdosis/tiptap#4487]
### Which packages did you experience the bug in?

extension-mathematics, extension-emoji, etc.

### What Tiptap version are you using?

Latest

### What’s the bug you are facing?

I am deploying my backend service on Render.com using a Docker container. I have the TipTap pro auth token in my .npmrc file. 

Here is the build logs indicating the error:

-------START-----
Sep 28 11:23:25 PM  #10 [base 4/8] RUN npm install --legacy-peer-deps && npm run postinstall
Sep 28 11:24:09 PM  #10 43.61 npm notice
Sep 28 11:24:09 PM  #10 43.61 npm notice New major version of npm available! 8.19.2 -> 10.1.0
Sep 28 11:24:09 PM  #10 43.61 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.1.0>
Sep 28 11:24:09 PM  #10 43.61 npm notice Run `npm install -g npm@10.1.0` to update!
Sep 28 11:24:09 PM  #10 43.61 npm notice
Sep 28 11:24:09 PM  #10 43.61 npm ERR! code E404
Sep 28 11:24:09 PM  #10 43.62 npm ERR! 404 Not Found - GET https://registry.npmjs.org/@tiptap-pro%2fextension-mathematics - Not found
Sep 28 11:24:09 PM  #10 43.62 npm ERR! 404
Sep 28 11:24:09 PM  #10 43.62 npm ERR! 404  '@tiptap-pro/extension-mathematics@^2.2.4' is not in this registry.
Sep 28 11:24:09 PM  #10 43.62 npm ERR! 404
Sep 28 11:24:09 PM  #10 43.62 npm ERR! 404 Note that you can also install from a
Sep 28 11:24:09 PM  #10 43.62 npm ERR! 404 tarball, folder, http url, or git url.
Sep 28 11:24:09 PM  #10 43.62
Sep 28 11:24:09 PM  #10 43.62 npm ERR! A complete log of this run can be found in:
Sep 28 11:24:09 PM  #10 43.62 npm ERR!     /root/.npm/_logs/2023-09-29T06_23_26_104Z-debug-0.log
Sep 28 11:24:09 PM  #10 ERROR: process "/bin/sh -c npm install --legacy-peer-deps && npm run postinstall" did not complete successfully: exit code: 1
Sep 28 11:24:09 PM  ------
Sep 28 11:24:09 PM   > [base 4/8] RUN npm install --legacy-peer-deps && npm run postinstall:
Sep 28 11:24:09 PM  #10 43.61 npm ERR! code E404
Sep 28 11:24:09 PM  #10 43.62 npm ERR! 404 Not Found - GET https://registry.npmjs.org/@tiptap-pro%2fextension-mathematics - Not found
Sep 28 11:24:09 PM  #10 43.62 npm ERR! 404
Sep 28 11:24:09 PM  #10 43.62 npm ERR! 404  '@tiptap-pro/extension-mathematics@^2.2.4' is not in this registry.
Sep 28 11:24:09 PM  #10 43.62 npm ERR! 404
Sep 28 11:24:09 PM  #10 43.62 npm ERR! 404 Note that you can also install from a
Sep 28 11:24:09 PM  #10 43.62 npm ERR! 404 tarball, folder, http url, or git url.
Sep 28 11:24:09 PM  #10 43.62
Sep 28 11:24:09 PM  #10 43.62 npm ERR! A complete log of this run can be found in:
Sep 28 11:24:09 PM  #10 43.62 npm ERR!     /root/.npm/_logs/2023-09-29T06_23_26_104Z-debug-0.log
Sep 28 11:24:09 PM  ------
Sep 28 11:24:09 PM  Dockerfile:7
Sep 28 11:24:09 PM  --------------------
Sep 28 11:24:09 PM     5 |     COPY package.json ./
Sep 28 11:24:09 PM     6 |
Sep 28 11:24:09 PM     7 | >>> RUN npm install --legacy-peer-deps && npm run postinstall
Sep 28 11:24:09 PM     8 |
Sep 28 11:24:09 PM     9 |     COPY prisma/schema.prisma ./prisma/
Sep 28 11:24:09 PM  --------------------
Sep 28 11:24:09 PM  error: failed to solve: process "/bin/sh -c npm install --legacy-peer-deps && npm run postinstall" did not complete successfully: exit code: 1
Sep 28 11:24:09 PM  error: exit status 1
------END------

 I am using pro extensions on both my React front-end (deployed on Vercel) and Nest.js Backend Service (deployed on Render.com). The front end deploys perfectly. However, on the backend, the build fails with unable to fetch npm packages from the private registry for all pro extensions.
 
 Here is what my .npmrc looks like:
 
 @tiptap-pro:registry=https://registry.tiptap.dev/
//registry.tiptap.dev/:_authToken=MY_AUTH_TOKEN

### What browser are you using?

Chrome

### What did you expect to happen?

The build should work perfectly.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by ccreusat** [comment]
@prabir-vora How did you solve this problem ??

**Comment by martzoukos** [comment]
I seem to be facing the same issue. Has anyone else solved this?

**Comment by OmarAlkadri** [comment]
npm config set "@tiptap-pro:registry" https://registry.tiptap.dev/
npm config set "//registry.tiptap.dev/:_authToken" ****

npm install --save @tiptap-pro/extension-unique-id
npm ERR! code E403
npm ERR! 403 403 Forbidden - GET https://registry.tiptap.dev/@tiptap-pro%2fextension-ai - Access forbidden!
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.

npm ERR! A complete log of this run can be found in: C:\Users\omara\AppData\Local\npm-cache\_logs\2024-04-03T10_22_37_771Z-debug-0.log

I am facing the same problem and I cannot solve it

**Comment by prabir-vora** [comment]
Hi @OmarAlkadri @martzoukos @ccreusat, here's how I got this to work with Docker deploy - 

You must copy your .npmrc into the Docker work directory before you run the `npm install` command.

```
FROM node:18.12.1 AS base

WORKDIR /app

COPY .npmrc ./    

COPY package.json ./
RUN npm install 

(Rest of your Dockerfile)
```

I hope this helps.

**Comment by frankdiw** [comment]
> I seem to be facing the same issue. Has anyone else solved this?

Did you solve it?

**Comment by martzoukos** [comment]
No, I've switched to Cloudflare Pages for my SPA and I build the bundle on my computer, so I don't face this issue now (but maybe once I set up CI/CD I'll need to come back to it :( )

**Comment by bdbch** [comment]
I have no experience with Render.com and can only help out with actual issues of the npmrc file. If the npmrc credentials are not passed around correctly on Render.com's side we can't really do a lot to help.

**Comment by frankdiw** [comment]
> I have no experience with Render.com and can only help out with actual issues of the npmrc file. If the npmrc credentials are not passed around correctly on Render.com's side we can't really do a lot to help.

When I execute npm install on my dev env, it will also report 403

**Comment by bdbch** [comment]
Did you setup your .npmrc correctly and is your npm installation using it?

```
npm config list
```

**Comment by frankdiw** [comment]
> 您是否正确设置了 .npmrc 并且您的 npm 安装是否使用了它？
> 
> ```
> npm config list
> ```
> 
> 或者做
> 
> ```shell
> # tiptap
> npm config get @tiptap-pro:registry
> ```
> 
> ```shell
> # hocuspocus
> npm config get @hocuspocus-pro:registry
> ```
> 
> 如果您已完成所有设置并且`//registry.tiptap.dev/:_authToken`也已设置，请检查 authToken 是否确实正确并且可以访问专业版软件包

<img width="440" alt="image" src="https://github.com/ueberdosis/tiptap/assets/17613480/2a31afed-6c01-4c65-9cb3-b2d14e77f1c5">
 npm config is correct,i copy authtoken from https://cloud.tiptap.dev/pro-extensions

**Comment by jitenderChoudhary1** [comment]
https://cloud.tiptap.dev/pro-extensions    <---  please complete that steps 
i solve this error by Global setup (for CI/CD)
