### ISSUE TITLE
Floating menu not appeared when editor creates with autofocus

### ISSUE THREAD

**Issue by starostin** [ueberdosis/tiptap#450]
**Describe the bug**
I have created editor with floating menu. Also I have added autofocus option. And it works fine. But my expectations that floating menu should appear after focus appeared in contenteditable. 

**Steps to Reproduce / Codesandbox Example**
1. Create editor with autofocus and floating menu
2. Open editor

 Fork this or create a new Codesandbox replicating your error
https://codesandbox.io/s/vue-template-3tsib?fontsize=14

**Expected behavior**
Floating menu appears when focus set in editor

**Environment**
 - OS: macOS
 - Browser chrome
 - Version 76.0.3809.100 
 - Mobile / Desktop: Desktop

**Additional context**
Also interesting, is there any method which could show floating menu?

**Comment by hanspagel** [comment]
Oops, nothing happened here. I’m closing this now. We are about to rewrite all interface components. But I keep in mind to improve this in the new version. ✌️
