### ISSUE TITLE
[Bug]: heading levels config option doesn't work properly

### ISSUE THREAD

**Issue by fridaystreet** [ueberdosis/tiptap#4503]
### Which packages did you experience the bug in?

extension-heading

### What Tiptap version are you using?

2.1.11

### What’s the bug you are facing?

The input rule always starts from a minimum of 1 # character. If you want to disable the single hash (eg when it conflicts with using hashtags) you can't.

using a config like below still matches a single # char for the input rules
 
{
   levels: [2,3,4,5]
}

The following code always matches from 1 to the max number

```
addInputRules() {
    return this.options.levels.map(level => {
      return textblockTypeInputRule({
        find: new RegExp(`^(#{1,${level}})\\s$`),
        type: this.type,
        getAttributes: {
          level,
        },
      })
    })
  },
```

It should use the minimum value in the array like below

```
addInputRules() {
    return this.options.levels.map(level => {
      return textblockTypeInputRule({
        find: new RegExp(`^(#{${Math.min(...this.options.levels)},${level}})\\s$`),
        type: this.type,
        getAttributes: {
          level,
        },
      })
    })
  },
```

### What browser are you using?

Chrome

### What did you expect to happen?

if the levels config array does not contain 1 that typing a single # doesn't get matched

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Fixed by https://github.com/ueberdosis/tiptap/pull/5890
