### ISSUE TITLE
[Bug]: `context` and `priority` supports in ParseHTML(Parse rule) 

### ISSUE THREAD

**Issue by etclub** [ueberdosis/tiptap#4509]
### Which packages did you experience the bug in?

core

### What Tiptap version are you using?

2.1.11

### What’s the bug you are facing?

I have some thing in `myTable` node:
```
    parseHTML() {
        return [{ tag: 'table', priority: 10 }, {tag: '.mytable', priority: 1000}]
    },
```
and in `myTableBody` node:
```
    parseHTML() {
        return [{ tag: 'tbody', context: 'table/' }, {tag: 'table', context: 'table/', priority: 500}]
    },
```

However,
```
<div class='mytable'>
  <table><tbody>
    <tr><th><p>...</p></th><th><p>...</p></th></tr>
  </tbody></table>
</div>
```
or  (without `body`)
```
<div class='mytable'>
  <table>
    <tr><th><p>...</p></th><th><p>...</p></th></tr>
  </tbody>
</div>
```
is still parsed into nested tables, instead of one  plain table. 

### What browser are you using?

Chrome

### What did you expect to happen?

According to the `context` and `priority`, it should result in just one `myTable` node.

### Anything to add? (optional)

Once I have used `prosemirror-tables`, now I just defined a new table schema.
And I want to make it compatible with the old one. 

The testing html code above is result of the old schema. 
I want to get it parsed into a new table node. 

I checked the doc at https://tiptap.dev/guide/custom-extensions/#parse-html.
It says to check all other properties at https://prosemirror.net/docs/ref/#model.ParseRule.
Then I came up using those properties.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Could you create a CodeSandbox for this issue? I'm having a hard time understanding exactly what's happening and what you want to achieve.

You want to have a `<table class="my-table">` that contains a `<tbody>` with your regular table tags?

**Comment by etclub** [comment]
Well, see the comments below
```
<div class='mytable'>            <!-- This is parsed into `myTable`, it is fine. -->
  <table>                                  <!-- This should be parsed into `myTableBody`, since the rule has a priority of 500, right? 
                                                          But it is now parsed into `myTable` instead.                 -->
    <tr><th><p>...</p></th><th><p>...</p></th></tr>
  </tbody>
</div>
```

**Comment by etclub** [comment]
I found it was caused by `myTableCaption`.
