### ISSUE TITLE
[Bug]: Mutation records always contains editor's first child node in addedNodes and removedNodes

### ISSUE THREAD

**Issue by aniket-qb** [ueberdosis/tiptap#4519]
### Which packages did you experience the bug in?

react

### What Tiptap version are you using?

2.0.0

### What’s the bug you are facing?

I've attached a mutation observer on contentEditable tiptap editor div. 

Let's say you two block nodes in you editor h1, p. 

When you reload and press enter at the end of node "p", you will create a new paragraph. If we check mutations of this change it will have two interesting mutation records, in one of them "h1" will be added and in another "h1" will be removed.

This behaviour will happen for very first time to see it again you will be required to reload the page.

<img width="458" alt="Screenshot 2023-10-10 at 12 13 27 PM" src="https://github.com/ueberdosis/tiptap/assets/105793425/48268b01-2968-4318-bb99-79e998402af9">

### What browser are you using?

Chrome

### Code example

https://codesandbox.io/s/mystifying-mcnulty-w7ztj2?file=/src/App.js

### What did you expect to happen?

I think the mutations record should not contain any mutations for the first node as it was never touched.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Could you check if this also happens on https://prosemirror.net to see if it's coming from upstream?

**Comment by bdbch** [comment]
Thank you @aniket-qb! I'll close this for now - could you add a link to the issue on Prosemirror so we can keep it in view for anyone coming up to the same issue?
