### ISSUE TITLE
Feature to enable line numbers

### ISSUE THREAD

**Issue by ipamaas** [ueberdosis/tiptap#453]
Currently it is not possbile to get line numbers for the editor.
It would be great to have a property to enable line numbers for the editor.
This would make sense p.e. when using the code-blocks.

Thanks for your great library!

**Comment by hanspagel** [comment]
Thanks for your suggestion!

Line numbers for the document are out of scope for ProseMirror, so we won’t have support in tiptap, see here:
https://discuss.prosemirror.net/t/line-numbers/849/2

But you’re asking for line numbers in code blocks, right? You can add something like prism.js (https://prismjs.com/) to the output of existing CodeBlocks. Hope that helps!

I don’t see us to add line numbers to code blocks as this is about rendering and tiptap is renderless. 🙃
