### ISSUE TITLE
[BUG]: Youtube Extension: pasting "https://youtube.com" is considered a valid youtube link

### ISSUE THREAD

**Issue by hadielyakhni** [ueberdosis/tiptap#4560]
### Which packages did you experience the bug in?

@tiptap/extension-youtube

### What Tiptap version are you using?

2.1.12

### What’s the bug you are facing?

We are using the YouTube extension in our React application. 

When pasting the string `https://youtube.com`, it will be matched by the [paste rule](https://github.com/ueberdosis/tiptap/blob/42039c05f0894a2730a7b8f1b943ddb22d52a824/packages/extension-youtube/src/youtube.ts#L128), however, when rendering the iframe, [getEmbedUrlFromYoutubeUrl](https://github.com/ueberdosis/tiptap/blob/42039c05f0894a2730a7b8f1b943ddb22d52a824/packages/extension-youtube/src/youtube.ts#L138C33-L138C33) returns `null` since the string `https://youtube.com` does not contain a proper src, hence the iframe is rendered without a `src` attribute, aka as an empty iframe. Please note that till this point, nothing crashes, it's just an empty iframe.

However, this behavior will cause a crash in our application because we persist the content, so when the user refreshes the browser, [parseHtml](https://github.com/ueberdosis/tiptap/blob/42039c05f0894a2730a7b8f1b943ddb22d52a824/packages/extension-youtube/src/youtube.ts#L98) will not be able to find the `src` attribute, hence, [renderHtml](https://github.com/ueberdosis/tiptap/blob/42039c05f0894a2730a7b8f1b943ddb22d52a824/packages/extension-youtube/src/youtube.ts#L137) will pass `null` to [getEmbedUrlFromYoutubeUrl](https://github.com/ueberdosis/tiptap/blob/42039c05f0894a2730a7b8f1b943ddb22d52a824/packages/extension-youtube/src/youtube.ts#L138C33-L138C33), crashing the browser with the following error: "cannot read property of null".

### What browser are you using?

Chrome

### Code example

https://codesandbox.io/s/reverent-star-ps5wc8?file=/src/App.js

### What did you expect to happen?

`YOUTUBE_REGEX_GLOBAL` not matching the string `https://youtube.com`

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by janthurau** [comment]
fixed by #4602
