### ISSUE TITLE
[Bug]: cursor blinks outside of tiptap editor (iOS safari, chrome)

### ISSUE THREAD

**Issue by gomjellie** [ueberdosis/tiptap#4571]
### Which packages did you experience the bug in?

react

### What Tiptap version are you using?

2.1.12

### What’s the bug you are facing?

https://github.com/ueberdosis/tiptap/assets/13645032/00d6d8a7-94e3-45e7-b8c7-0cc394ea0cd7

cursor blinks outside of tiptap editor box - [link](https://tiptap.dev/examples/default
)

this happens only in iOS devices

### What browser are you using?

Safari

### What did you expect to happen?

blinking cursor is not visible outside of tiptap editor box

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by tclxdongyang-guo** [comment]
Have you solved the problem

**Comment by tclxdongyang-guo** [comment]
> yes, i've solved this issue with css. you can fix this with changing container style.
> 
> @tclxdongyang-guo

Can you give me a reference answer？

**Comment by gomjellie** [comment]
@tclxdongyang-guo 

set overflow auto at .ProseMirror 

```css
.ProseMirror {
  height: 100%;
  overflow: auto;
}
```

and don't put overflow style at `<EditorContent style={{ height: Npx }} />`

**Comment by vonWolfehaus** [comment]
> set overflow auto at .ProseMirror
> 
> ```css
> .ProseMirror {
>   height: 100%;
>   overflow: auto;
> }
> ```
> 
> and don't put overflow style at `<EditorContent style={{ height: Npx }} />`
> 
> @tclxdongyang-guo does it work for you?

This worked for me, thank you! This was plaguing my iOS users (text selection was also very wonky) and now it works as well as Android/chromium browsers. Although I had `min-height` set and not `height`. `overflow :auto` is the key here.

**Comment by aehlke** [comment]
is this not documented by tiptap? it should be recommended everywhere
