### ISSUE TITLE
recalculate keep in bounds when menu changes

### ISSUE THREAD

**Issue by chrisjbrown** [ueberdosis/tiptap#458]
**Describe the bug**
some toolbar options expand the size of the toolbar. this can lead to the toolbar overflowing the parent.

**Steps to Reproduce / Codesandbox Example**
1. Go to https://codesandbox.io/embed/vue-template-6dnwg
2. Click on a word on the left "try"
3. click add link
4. See that the toolbar expands beyond the parent as it has `overflow: hidden`

 Fork this or create a new Codesandbox replicating your error
https://codesandbox.io/embed/vue-template-6dnwg

**Expected behavior**
the `keep-in-bounds` prop when true should recheck if the toolbar is outside of the parent bounds and recalculate the menu position when the menu elements change.

**Environment**
 - OS: Mac
 - Browser Brave
 - Desktop

**Comment by hanspagel** [comment]
Oops, nothing happened here. I’m closing this now. We are about to rewrite all interface components. But I added this to my notes to improve this in the new version. ✌️
