### ISSUE TITLE
How to make a Format Painter？

### ISSUE THREAD

**Issue by huangyuanyin** [ueberdosis/tiptap#4598]
### Which packages did you experience the bug in?

vue3

### What Tiptap version are you using?

2.0.0

### What’s the bug you are facing?

How to make a Format Painter？

### What browser are you using?

Chrome

### What did you expect to happen?

How to make a Format Painter？

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by aleversn** [comment]
This is exactly the function that I expect.

**Comment by bdbch** [comment]
For questions please refer to Github Discussions or use our Discord server. Closing this for now as this is not a bug.

Also please explain what you expect from something like a "Format Painter"?
