### ISSUE TITLE
[Bug]: Bubble Menu crashes React when used in conjunction with the deps argument of useEditor().

### ISSUE THREAD

**Issue by iahuang** [ueberdosis/tiptap#4619]
### Which packages did you experience the bug in?

extension-bubble-menu, react

### What Tiptap version are you using?

all are version 2.1.12

### What’s the bug you are facing?

The following React code causes `DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.` when the button labeled "Click me" is pressed. The error does not occur when the `BubbleMenu` element is omitted. [CodeSandbox link](https://codesandbox.io/s/blissful-wind-jq7d4m)

```tsx
import { BubbleMenu, Editor, EditorContent, useEditor } from "@tiptap/react";
import { StarterKit } from "@tiptap/starter-kit";
import { useState } from "react";
import { BubbleMenu as BubbleMenuExtension } from "@tiptap/extension-bubble-menu";
import ReactDOM from "react-dom/client";

export function MyEditor() {
    const [thing, setThing] = useState<string | null>(null);

    const editor = useEditor({
        extensions: [StarterKit, BubbleMenuExtension],
    }, [thing]);

    return (
        editor && <div>
            <EditorContent editor={editor as Editor} />
            <BubbleMenu editor={editor}>
                <div>
                    hi
                </div>
            </BubbleMenu>
            <button onClick={() => setThing("a")}>
                Click me
            </button>
        </div>
    );
}

const root = ReactDOM.createRoot(document.getElementById("root") as HTMLElement);

root.render(
    <MyEditor />
);
```

### What browser are you using?

Chrome

### Code example

https://codesandbox.io/s/blissful-wind-jq7d4m

### What did you expect to happen?

I expected the same behavior, with or without `BubbleMenu`, that is to say, for nothing to happen.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by svenadlung** [comment]
There is no need to import and register `BubbleMenu` from `@tiptap/extension-bubble-menu` as everything is working with using the BubbleMenu React binding from `@tiptap/react` (which is using `@tiptap/extension-bubble-menu` under the hood).

**Comment by batiyeh** [comment]
@svenadlung It looks like to me like the above example is using the react binding. We're seeing the same issue. It's posisble I am misunderstanding something, but why was this closed?

**Comment by petertoth** [comment]
This issue is still persisting. When you use dep array in `useEditor(...., [dep])` alongside with `<BubbleMenu />` the Editor crashes with following error:

```
Unhandled Runtime Error
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

However, I was able to resolve it(sorta) with moving `<BubbleMenu />` above `<EditorContent />` like:

```tsx
<div>
  <EditorBubbleMenu editor={editor} />
  <EditorContent editor={editor} />
</div>
```

**Comment by TrustyTechSG** [comment]
> ```tsx
> div
> ```

Saved my life, thank you~

**Comment by svenadlung** [comment]
@batiyeh sorry, I somehow missed this mention. At the time of my comment the code was still a bit different (see edit history). 

Were you able to solve all the problems?

**Comment by gregermendle** [comment]
I was able to fix this error by ensuring `BubbleMenu` is above `Editor` (as @petertoth said) and that both components are wrapped in an html element and not a react fragment. For me the issue was the react fragment.

**Comment by WilliamIPark** [comment]
> This issue is still persisting. When you use dep array in `useEditor(...., [dep])` alongside with `<BubbleMenu />` the Editor crashes with following error:
> 
> ```
> Unhandled Runtime Error
> NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
> ```
> 
> However, I was able to resolve it(sorta) with moving `<BubbleMenu />` above `<EditorContent />` like:
> 
> ```tsx
> <div>
>   <EditorBubbleMenu editor={editor} />
>   <EditorContent editor={editor} />
> </div>
> ```

In our case we had to move it above a few different components. This seems really fragile... Could this be re-opened @bdbch?

**Comment by andrewmartin** [comment]
Wanted to say I am also seeing this issue. Moving from a `<>` to a `<div>` didn't seem to help.

**Comment by andrewmartin** [comment]
By the way, what seemed to work in my case, was actually ensuring the `<EditorProvider />` only has one top level child. I think that's what fixed it:

Works: 

```tsx
 <EditorProvider>
      <div>
        <EditorContent computedContent={computedContent} />
        {loading ? <Loader.InlineSmall /> : null}
      </div>
</EditorProvider>
```

Breaks:

```tsx
<EditorProvider>
        <EditorContent computedContent={computedContent} />
        {loading ? <Loader.InlineSmall /> : null}
</EditorProvider>
```

**Comment by evenfrost** [comment]
Came here with the same error but with `FloatingMenu`. Adding a `div` as a top element inside `EditorProvider` fixed the error.

For the reference, the error is as follows:

```
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

**Comment by mattkindy** [comment]
This happened to me with the following
```typescript
  return (
    <EditorContext.Provider value={providerValue}>
      <div className="flex h-full" ref={menuContainerRef}>
        <Sidebar isOpen={leftSidebar.isOpen} onClose={leftSidebar.close} editor={editor} />
        <div className="relative flex flex-col flex-1 h-full">
          <EditorHeader
            characters={characterCount.characters()}
            collabState={collabState}
            users={displayedUsers}
            words={characterCount.words()}
            isSidebarOpen={leftSidebar.isOpen}
            toggleSidebar={leftSidebar.toggle}
          />
          <EditorContent editor={editor} ref={editorRef} className="flex-1 overflow-y-auto" />
          <ContentItemMenu editor={editor} />
          <LinkMenu editor={editor} appendTo={menuContainerRef} />
          <TextMenu editor={editor} />
          <ColumnsMenu editor={editor} appendTo={menuContainerRef} />
          <TableRowMenu editor={editor} appendTo={menuContainerRef} />
          <TableColumnMenu editor={editor} appendTo={menuContainerRef} />
          <ImageBlockMenu editor={editor} appendTo={menuContainerRef} />
        </div>
      </div>
    </EditorContext.Provider>
  )
}
``` 

everything worked once I moved `EditorContent` to the end of its `div`. Thanks to @petertoth for identifying this. Definitely seems like an open issue (I just started using tiptap), very tricky to know it is caused by this particular section of code based on the stacktrace.

**Comment by alexcurtis** [comment]
I had the exact same issue with it crashing when using dependencies in useEditor. Moving the Editor to the end of the hierarchy seemed to fix it. Very strange....

**Comment by bdbch** [comment]
The `Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.` error should be resolved after #5398

**Comment by nperez0111** [comment]
Adding a dep array to useEditor forces us to have to completely reinitialize the editor instance which would explain a race between a dom element removal & the editor instance it is operating on (i.e. the editor destruction happens immediately & synchronously, while the tippy destruction happens on the next tick because react is not synchronous)

**Comment by Jacky-Liu1** [comment]
Noting this in case anyone runs into a similar situation. I was using the Tiptap editor wrapped in my own `Document` component. React reuses DOM elements when their keys do not change so adding something like 
`<Document key={selectedDocumentId} docId={selectedDocumentId} />` solved my issue

**Comment by andres-dos-santos** [comment]
> This issue is still persisting. When you use dep array in `useEditor(...., [dep])` alongside with `<BubbleMenu />` the Editor crashes with following error:
> 
> ```
> Unhandled Runtime Error
> NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
> ```
> 
> However, I was able to resolve it(sorta) with moving `<BubbleMenu />` above `<EditorContent />` like:
> 
> ```tsx
> <div>
>   <EditorBubbleMenu editor={editor} />
>   <EditorContent editor={editor} />
> </div>
> ```

When we see each other I'll buy you a beer 🍺.

**Comment by heesungjang** [comment]
> This issue is still persisting. When you use dep array in `useEditor(...., [dep])` alongside with `<BubbleMenu />` the Editor crashes with following error:
> 
> ```
> Unhandled Runtime Error
> NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
> ```
> 
> However, I was able to resolve it(sorta) with moving `<BubbleMenu />` above `<EditorContent />` like:
> 
> <div>
>   <EditorBubbleMenu editor={editor} />
>   <EditorContent editor={editor} />
> </div>

Legend. Thanks

**Comment by saculNiot** [comment]
Lolol, this works. Let me get u a coffee if we meet.

**Comment by kgpatidar** [comment]
> > This issue is still persisting. When you use dep array in `useEditor(...., [dep])` alongside with `<BubbleMenu />` the Editor crashes with following error:
> > ```
> > Unhandled Runtime Error
> > NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However, I was able to resolve it(sorta) with moving `<BubbleMenu />` above `<EditorContent />` like:
> > <div>
> >   <EditorBubbleMenu editor={editor} />
> >   <EditorContent editor={editor} />
> > </div>
> 
> In our case we had to move it above a few different components. (I think it had to be above anything consuming the editor instance). This seems really fragile... Could this be re-opened [@bdbch](https://github.com/bdbch)?

Thank you.

**Comment by kgpatidar** [comment]
> This issue is still persisting. When you use dep array in `useEditor(...., [dep])` alongside with `<BubbleMenu />` the Editor crashes with following error:
> 
> ```
> Unhandled Runtime Error
> NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
> ```
> 
> However, I was able to resolve it(sorta) with moving `<BubbleMenu />` above `<EditorContent />` like:
> 
> <div>
>   <EditorBubbleMenu editor={editor} />
>   <EditorContent editor={editor} />
> </div>

Thank you king
