### ISSUE TITLE
[Bug]: `insertContentAt` doesn't work

### ISSUE THREAD

**Issue by nooblyf** [ueberdosis/tiptap#4625]
### Which packages did you experience the bug in?

core, react

### What Tiptap version are you using?

2.1.12

### What’s the bug you are facing?

Tried to insert content but it just does nothing it seems

https://tiptap.dev/api/commands/insert-content-at

```ts
editor.commands.insertContentAt(12, '<p>Hello world</p>', {
  updateSelection: true,
  parseOptions: {
    preserveWhitespace: 'full',
  }
})
```

### What browser are you using?

Chrome

### What did you expect to happen?

Being able to see `<p>Hello world</p>` at index `12`

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by nooblyf** [comment]
My bad, it is working

**Comment by SalahAdDin** [comment]
> My bad, it is working

What was the issue?

**Comment by nperez0111** [comment]
@SalahAdDin my guess would be the position (12 in this case)

**Comment by SalahAdDin** [comment]
> @SalahAdDin my guess would be the position (12 in this case)

How did you figure it out?
