### ISSUE TITLE
[Bug]: Aliases are not recognized in the editor

### ISSUE THREAD

**Issue by NorthLake** [ueberdosis/tiptap#4651]
### Which packages did you experience the bug in?

extension-code-block-lowlight

### What Tiptap version are you using?

@tiptap/vue-3: 2.1.12, @tiptap/extension-code-block-lowlight: 2.1.12, lowlight: 3.1.0

### What’s the bug you are facing?

Most languages have at least one alias baked in, and you can add additional ones yourself using `lowlight.registerAlias(...)`, but neither of these are checked when adding a codeblock in the editor.

### What browser are you using?

Chrome

### What did you expect to happen?

` ```js ` codeblocks are highlighted the same way as ` ```javascript ` codeblocks.

### Anything to add? (optional)

I tried to get the CodeSandbox to work, but I couldn't get any of them to load at all.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by NorthLake** [comment]
I did some more digging, and it gets really weird.
If I call `lowlight.registered('js')` from my own code, then everything runs fine. But when `highlight.getLanguage(aliasOrLanguage)` is called at `lowlight-plugin.ts:31`, the alias and language variables in `hightlght.js/lib/core.js` are just empty objects.
Maybe this helps with troubleshooting.

**Comment by nperez0111** [comment]
This has been released with 2.7.0-pre.0 and will be released in tiptap 2.7.0 when this beta has been tested by more users
