### ISSUE TITLE
[Documentation]: How to use the AI extension

### ISSUE THREAD

**Issue by tiavina-mika** [ueberdosis/tiptap#4660]
### What’s the URL to the page you’re sending feedback for?

https://tiptap.dev/api/extensions/ai#setting-up-tiptap-ai-for-your-team

### What part of the documentation needs improvement?

It's just about the api, there is no implementation or usage example, I do not how where or how to use it.
For exemple, where should we put the token and appId props?

### What is helpful about that part?

To facilitate the extension usage

### What is hard to understand, missing or misleading?

The implementation and usage

**Comment by mkriegeskorte** [comment]
@tiavina-mika Thanks for your feedback. An updated version of the extension and the documentation is already on the way :)

**Comment by mkriegeskorte** [comment]
In general the extension behaves like every other extension, too. You add it to your editor and set the settings into the configeration object like that:

```js
useEditor({
  extensions: [
    StarterKit.configure(),
    Ai.configure({
      appId: 'YOUR_APP_ID',
      token: 'YOUR_GENERATED_JWT',
      // ... other settings
    })
  ]
}) 
```

With that done the documented commands become available.

**Comment by tiavina-mika** [comment]
Thanks, 

I've installed it with:

`
npm install --save @tiptap-pro/extension-unique-id
`

and import it with
```javascript
import Ai from '@tiptap-pro/extension-unique-id';
```

But I got this TS error:
```
Argument of type '{ token: string; }' is not assignable to parameter of type 'Partial<UniqueIDOptions>'.
  Object literal may only specify known properties, and 'token' does not exist in type 'Partial<UniqueIDOptions>
```

**Comment by mkriegeskorte** [comment]
@tiavina-mika You’ve installed the unique-id-extension instead of the ai-extension 👀

**Comment by tiavina-mika** [comment]
Ok.
Now I got a `Access Forbidden` when running `npm install @tiptap-pro/extension-ai`.

here is my `.npmrc`
```
@tiptap-pro:registry=https://registry.tiptap.dev
//registry.tiptap.dev:_authToken=xxxxx
```

**Comment by svenadlung** [comment]
@tiavina-mika you need at least the Starter Plan for the AI extension. What plan have you got?

**Comment by tiavina-mika** [comment]
@svenadlung for now the free tier. I will try the the Starter Plan later

**Comment by svenadlung** [comment]
Yeah, it's needed. Closing for now. Please let me know if you still have issues after upgrading.

**Comment by Kuravar** [comment]
It depends on what AI extensions we are talking about. Now there are a bunch of different new things that you can use in your work. But in general, what is especially interesting to me now is [Top AI Influencers](https://topaiinfluencers.io/). More about popular AI models can be found here topaiinfluencers.io, and it’s amazing how something seemingly artificial becomes something real and can even influence the opinions and choices of other people.
