### ISSUE TITLE
Sanitize on paste?

### ISSUE THREAD

**Issue by bdrtsky** [ueberdosis/tiptap#467]
**Is your feature request related to a problem? Please describe.**
When I copy paste text from other website, the html tags are preserved. So even if I don't have ordered list or links enabled in Tiptap they are still being used in Tiptap markup.

**Describe the solution you'd like**
A more appropriate way is to use only those tags, that was declaratively imported for usage in Tiptap, or provide a way to sanitize the pasted data. Yes, I can do this on backend, but there are usecases. 

**Describe alternatives you've considered**
Strip tags.

**Comment by philippkuehn** [comment]
HTML tags should be stripped already, so maybe this is a bug. Please provide a codesandbox.

**Comment by bdrtsky** [comment]
It seems like they are not.

Here's reproduction - https://codesandbox.io/s/vue-template-unewx
If you paste text from this website (particularly, first item in list `1. Blue Light-Blocking Glasses`), then all markup is pasted - https://elisabetheden.com/my-3-work-from-home-must-haves/

For now, I thought this behavior is intended and make sanitazion using `transformPastedHTML`, but if you say they already should be stripped makes me 🤔

**Comment by chrisjbrown** [comment]
I'm also seeing this.
no need for a sandbox.

can see it in the examples here https://tiptap.scrumpy.io/
past html that should be parsed.

```html
<b>bla</b>

<strong>bold</strong>
```

the tags are inserted as strings in p tags

**Comment by philippkuehn** [comment]
yeah this will be copied as text. Try to copy some text from rendered HTML from a browser and it will work.

**Comment by chrisjbrown** [comment]
> yeah this will be copied as text. Try to copy some text from rendered HTML from a browser and it will work.

Yes, you're right. nevermind 😅
