### ISSUE TITLE
[Bug]: <input /> element is not getting parsed/rendered in editor

### ISSUE THREAD

**Issue by Tom-DK** [ueberdosis/tiptap#4685]
### Which packages did you experience the bug in?

core, react

### What Tiptap version are you using?

2.1.12

### What’s the bug you are facing?

I've created a custom extension, that should allow <input/> elements to be parsed and rendered by TipTap, but without success unfortunately.

```
import {Node, mergeAttributes} from '@tiptap/core';

export interface InputOptions {
    HTMLAttributes: Record<string, any>,
}

export const Input = Node.create<InputOptions>({
    name: 'input',
    addOptions() {
        return {
            HTMLAttributes: {},
        };
    },
    addAttributes() {
        return {
            type: {
                default: this.options.HTMLAttributes.type || '',
            },
            class: {
                default: 'input input-xs input-bordered'
            },
            value: {
                default: this.options.HTMLAttributes.value || ' ',
            },
            placeholder: {
                default: this.options.HTMLAttributes.placeholder || '',
            },
            id: {
                default: this.options.HTMLAttributes.id || '',
            },
        };
    },
    parseHTML() {
        return [{tag: 'input'}];
    },
    renderHTML({HTMLAttributes}) {
        return ['input', mergeAttributes(this.options.HTMLAttributes, HTMLAttributes), 0];
    },
});
```

### What browser are you using?

Chrome

### Code example

https://codesandbox.io/p/sandbox/input-bug-tiptap-2lym8v

### What did you expect to happen?

The input with all its attributes should be parsed and rendered into the editor.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by Tom-DK** [comment]
```typescript
import {Node} from '@tiptap/core';

export interface InputOptions {
    HTMLAttributes: Record<string, any>,
}

export const Input = Node.create<InputOptions>({
    name: 'input',
    group: 'inline',
    inline: true,
    content: 'text*',
    draggable: false,
    isolating: true,
    addOptions() {
        return {
            HTMLAttributes: {},
        };
    },
    addAttributes() {
        return {
            type: {
                default: 'text',
                parseHTML: element => element.getAttribute('type'),
            },
            class: {
                default: 'input input-sm input-bordered'
            },
            value: {
                parseHTML: element => element.getAttribute('value'),
            },
            placeholder: {
                parseHTML: element => element.getAttribute('placeholder'),
            },
            id: {
                parseHTML: element => element.getAttribute('id'),
            },
        };
    },
    parseHTML() {
        return [
            {tag: 'input'},
        ];
    },
    renderHTML({HTMLAttributes}) {
        return ['input', HTMLAttributes, 0];
    },
});

```
Okay so this issue is not a bug, I wasn't respecting the schema configurations explained in the docs, my bad...

The input is getting parsed and rendered correctly now. However, when the editor is rendered (React) and I straight click onto input and start typing I cannot use backspace. I first have focus text in the editor itself. Moreover, when I press Ctrl+A in the input, the selection is not limited to the input text itself. It selects the whole editor content.

Anyone tips, on how I can tackle these two remaining issues?

**Comment by Slapbox** [comment]
Since this isn't a bug I'd recommend asking on the Discord or opening a discussion instead.

Please consider closing this issue to reduce the strain on the maintainers.
