### ISSUE TITLE
Refactor to allow better tree shaking

### ISSUE THREAD

**Issue by jameswragg** [ueberdosis/tiptap#471]
**Is your feature request related to a problem? Please describe.**
I find I always have the (quite heavy) `posemirror-tables` in my bundle even if I don't include it from `tiptap-extensions`.

e.g. running [Webpack Bundle Analyzer](https://www.npmjs.com/package/vue-cli-plugin-webpack-bundle-analyzer) on the result of doing this, I'll always see the 85KB of `prosemirror-tables/dist`
```
import {
  Heading,
  Bold,
  Italic,
  HardBreak,
  OrderedList,
  BulletList,
  ListItem,
  History,
} from "tiptap-extensions"
```

**Describe the solution you'd like**
Only the chosen modules/extensions are bundled.

**Describe alternatives you've considered**
I tried using `from "tiptap-extensions/src"` and the build comes down a little, so I think there's some tree-shaking blockers in the tip-tap project.

Thanks (loving tiptap btw)

**Comment by philippkuehn** [comment]
Yeah I would really like to hear some tips from the community here!

**Comment by hanspagel** [comment]
That was a lot of silence. 😅  We’re about to release a complete rewrite of [tiptap 2](https://blog.ueber.io/post/our-plan-for-tiptap-2/), which will do better, so it’s time to close the issue. 👋
