### ISSUE TITLE
Add transformTransaction hook?

### ISSUE THREAD

**Issue by pju-** [ueberdosis/tiptap#472]
**Is your feature request related to a problem? Please describe.**
I have a special editor where I want to remove `hard_break` nodes if they are the first or last child of a paragraph.
They way I was going to go about this is to use prosemirror's `dispatchTransaction` prop to change each transaction's doc to re-format the nodes. I would get a copy of the transaction, then apply that new transaction:

```js
dispatchTransaction: transaction => {
    let newState = view.state.apply(transposeTransaction(transaction));
    view.updateState(newState);
}
```
However, that will not work with tiptap, as it's own dispatchTransaction handles a lot more than just updating the prosemirror view.

**Describe the solution you'd like**
I think it would be rather trivial to add an option like `transformTransaction` that takes a function to transform each transaction before it is applied. I could create a PR to show what I mean.

Something like:
```js
// In editor.js
this.defaultOptions = {
    …
    transformTransaction: transaction => transaction
}
…
dispatchTransaction(originalTransaction) {
    const transaction = this.options.transformTransaction(originalTransaction)
    const newState = this.state.apply(transaction)
    …
```

**Describe alternatives you've considered**
I'm new to tiptap/prosemirror, so I'm not sure whether my approach is even correct. Maybe it is a bad practice to change transactions and it would be better to use a follow-up transaction? I do not want the follow-up to appear in the history though.

**Comment by ssaric** [comment]
@hanspagel can you elaborate how this is done? can't find any changes in code for this issue.
