### ISSUE TITLE
[Bug]: Custom Node Keeps pushing the inserting content out 

### ISSUE THREAD

**Issue by RSI-Sakthisivaprakash** [ueberdosis/tiptap#4728]
### Which packages did you experience the bug in?

react

### What Tiptap version are you using?

2.0.3

### What’s the bug you are facing?

In TipTap Editor, we have one custom node. I tried to insert content using **insertContent** method in the commands. but custom node keeps pushing the inserted content out of the custom node, typically to the next line of the node.

Here is My configuration.

### What browser are you using?

Chrome

### Code example

**Custom Node:**

`
export default Node.create({
    name: "custom-node",

    group: "inline",

    content: "block*",

    marks: "_",

    inline: true,

    atom: false,

    selectable: true,

    draggable: false,

    allowGapCursor: false,

    spanning: true,

    addNodeView() {
        return ReactNodeViewRenderer(CustomComponent);
    },
});

`

**Method which i used in insert Function:**

`
const textToInsert = "Some Sample Text"

editor.commands.insertContent(textToInsert, {
	parseOptions: {
		preserveWhitespace: true,
	}
});
`

### What did you expect to happen?

instead of pushing the text content out of the custom node. I am expecting it to insert at the cursor position in the custom node.

### Did you update your dependencies?

- [ ] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by RSI-Sakthisivaprakash** [comment]
Even i have changed the   `content: 'block*',` facing the same issue. text content keeping pushed out of the custom node.

**Comment by semoal** [comment]
You're saying to your node that is a block;

Use this options instead:

```tsx
  group: "inline",
  inline: true,
  content: "text*",
  atom: false,
  selectable: true,
  draggable: false,
  allowGapCursor: false,
  spanning: true,
```

**Comment by RSI-Sakthisivaprakash** [comment]
> You're saying to your node that is a block;
> 
> Use this options instead:
> 
> ```tsx
>   group: "inline",
>   inline: true,
>   content: "text*",
>   atom: false,
>   selectable: true,
>   draggable: false,
>   allowGapCursor: false,
>   spanning: true,
> ```

@semoal thanks for the response, But In my scenario i want to insert block elements like div, ul, ol and table inside the custom node using this insertContent method. if i set content type to text* it was supporting only text elements inside node. 
block elements which i insert in a single shot is keeps pushing to next line of the custom node.

**Comment by RSI-Sakthisivaprakash** [comment]
Found the root cause of the issue at my end. it is due to DOM parser pushing the content out, for html structural element support.
