### ISSUE TITLE
Backticks are not removed when using Code extension 

### ISSUE THREAD

**Issue by rooflikespiggy** [ueberdosis/tiptap#4735]
Hi just to bump this issue as I am still facing a similar problem

I installed the [Code extension](https://tiptap.dev/api/marks/code).  However, in contrast to what appears in the demo, the backticks before and after the code block are not removed/hidden.

In other words, I am seeing this:

![Screenshot 2023-07-19 at 11 15 51 AM](https://github.com/ueberdosis/tiptap/assets/819213/0b5738af-d379-4040-81a7-aacbbf22a942)

Why are they appearing for me but not in the demo? How can I make them go away?

Thanks!

_Originally posted by @andersr in https://github.com/ueberdosis/tiptap/discussions/4233_

**Comment by avdept** [comment]
@ruthkangyr how did you solve it?

**Comment by avdept** [comment]
For now I solved this by adding custom CSS class like

```
Code.configure({
    HTMLAttributes: {
        class: "inline-code bg-gray-100 text-gray-800 px-1 rounded",
    },
 })
```

and then via CSS hide before/after selectors like

```
.inline-code {
  &::before {
    content: "";
  }
  &::after {
    content: "";
  }
}

```
