### ISSUE TITLE
[Bug]: publish-npm job was failed to execute

### ISSUE THREAD

**Issue by JohnNiang** [ueberdosis/tiptap#4773]
### Which packages did you experience the bug in?

none

### What Tiptap version are you using?

2.1.15

### What’s the bug you are facing?

See https://github.com/ueberdosis/tiptap/actions/runs/7475116397 and https://github.com/ueberdosis/tiptap/actions/runs/7475107477 for more.

### What browser are you using?

Other

### What did you expect to happen?

Publish tiptap 2.1.16 to NPM. 

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Thanks for bringing this up - fixed the typing error and release should be out relatively soon
