### ISSUE TITLE
[Bug]: Link parse error when inserted

### ISSUE THREAD

**Issue by stevobm** [ueberdosis/tiptap#4785]
### Which packages did you experience the bug in?

core

### What Tiptap version are you using?

2.1.15

### What’s the bug you are facing?

When a link is inserted into the document, I only get the text instead of the link, and an error below:
![image](https://github.com/ueberdosis/tiptap/assets/5198256/06fe3533-30e2-4b84-b170-63392ea47bc8)
This problem occurred when I upgraded tiptap to 2.1.15, and it also exists in 2.1.16, wish it to be solved soon.

### What browser are you using?

Chrome

### What did you expect to happen?

Link be parsed correctly.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by albingroen** [comment]
I'm running into the same issue here. Using v2.1.16

**Comment by jakebarshickf1nx** [comment]
2.1.10 is the last version that I don't experience any pasting issues FYI. Seems like 2.1.11 is where things start breaking for me maybe #4354 is the initial cause?

**Comment by stevobm** [comment]
Fixed in https://github.com/ueberdosis/tiptap/pull/4836.
