### ISSUE TITLE
[Bug]: InsertContent cannot insert whitespace characters.

### ISSUE THREAD

**Issue by SF-Simon** [ueberdosis/tiptap#4789]
### Which packages did you experience the bug in?

core

### What Tiptap version are you using?

2.1.16

### What’s the bug you are facing?

```
this.editor.commands.insertContent("   ", {
    parseOptions: {
    preserveWhitespace: true, // or "full"
}
```

We hoped to input tab and whitespace through the above code, but found that it did not work.

Upon reviewing the code, it was found that such input has been formatted and deleted due to the following reasons:
https://github.com/ueberdosis/tiptap/blob/develop/packages/core/src/utilities/elementFromString.ts#L1

### What browser are you using?

Chrome

### What did you expect to happen?

I expect removeWhitespaces to comply with the configuration, and when preserveWhitespace is true or "full", it should retain the input to whitespace.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by sarasilvaworkera** [comment]
@SF-Simon ^

**Comment by donovanlopez** [comment]
> > @SF-Simon ^
> 
> I created a JSONContent object to solve this problem.

@SF-Simon can you elaborate on your solution?

**Comment by SF-Simon** [comment]
> > > @SF-Simon ^
> > 
> > 
> > I created a JSONContent object to solve this problem.
> 
> @SF-Simon can you elaborate on your solution?

Do not insert HTML or text, inserting a JSON formatted paragraph can solve this problem.
