### ISSUE TITLE
[Bug]: Removing spaces between tags

### ISSUE THREAD

**Issue by szymekjanaczek** [ueberdosis/tiptap#4792]
### Which packages did you experience the bug in?

core, react

### What Tiptap version are you using?

2.1.16

### What’s the bug you are facing?

Let's assume we write a text and format it like below:
```html
<p>Lorem <em>ipsum <strong>dolor</strong></em> <strong>sit</strong> amet.</p>
```
When saving this somewhere and then recovering and load into tiptap again, getting text in this format:
```html
<p>Lorem <em>ipsum <strong>dolor</strong></em><strong>sit</strong> amet.</p>
```
Without space between `</em>` and `<strong>`. So the words "dolor" and "sits" connects into one word "dolorsit".

### What browser are you using?

Chrome

### Code example

[codesandbox.io - React version](https://codesandbox.io/p/sandbox/charming-rumple-tslmsj?file=%2Fsrc%2FApp.js%3A15%2C15)
```javascript
const editor = useEditor({
  extensions: [StarterKit],
  editorProps: {
    attributes: {
      class: "Editor",
    },
  },
  content: `
    <p>Lorem <em>ipsum <strong>dolor</strong></em> <strong>sit</strong> amet.</p>
  `,
});

return (
  <div className="App">
    <EditorContent editor={editor} />
  </div>
);
```

### What did you expect to happen?

Reading the text as it has been previously written - with spaces between HTML tags.
So when I save
```html
<p>Lorem <em>ipsum <strong>dolor</strong></em> <strong>sit</strong> amet.</p>
```

And then set it as a content of the TipTap editor, I want to keep original spaces - without gluing words together.

### Anything to add? (optional)

<img width="450" alt="image" src="https://github.com/ueberdosis/tiptap/assets/74879123/c12e2bfd-b9dc-4b2c-8162-5cc77bce111b">

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by andrewvasilchuk** [comment]
I'm getting the same problem. This is related to the changes made in #4767.

**Comment by andrewvasilchuk** [comment]
@szymekjanaczek yes the problem is not  seen in `2.1.15`.

**Comment by andrewvasilchuk** [comment]
Another example may be seen on the ["Mention" extension page](https://tiptap.dev/docs/editor/api/nodes/mention#usage).

```html
<span data-type="mention" data-id="Winona Ryder"></span> <span data-type="mention" data-id="Axl Rose"></span>
```

The HTML above is collapsed when parsed by the editor, but there is an empty space between these 2 mentions.

**Comment by ElHex** [comment]
This is also happening in the project I'm working on and its related to this commit (confirmed after a lot of time debugging tiptap)

https://github.com/ueberdosis/tiptap/commit/b7a2504f16f46563537c890930cb2c332c256175

**Comment by svenadlung** [comment]
Thanks for reporting. I was able to reproduce. Will be working on a fix.

**Comment by brendawon** [comment]
Hi, I am currently experiencing this same issue using version 2.4.0. When applying marks next to each other on the same line, the space is removed.

**Comment by nperez0111** [comment]
Are you still seeing this issue with 2.5.5 though? The fix landed in 2.5.0 I believe

**Comment by brendawon** [comment]
I updated to 2.5.5, but my problem still persists @nperez0111  

I wonder if my issue is slightly different. When applying marks next to each other on the same line, there is a space in the Editor UI, but the space is removed from the html. For my purposes, I am saving the html and rendering it elsewhere, and the space is removed there. If I try to edit my saved content, the space does still remain in the Editor UI. 

<img width="456" alt="Screenshot 2024-07-22 at 2 52 42 PM" src="https://github.com/user-attachments/assets/880f5337-a1c3-42bb-b23b-79b508342a7d">

As a workaround, I can apply marks including the space on either end, but it's not ideal from a UX perspective.

**Comment by brendawon** [comment]
sorry, appeared to be an issue with my HTML parser. fixing that + v2.5.5 is working for me! thanks

**Comment by masudhossain** [comment]
I'm getting this issue with `\n\`. So putting this `Can we make sure this works. Thanks!\n\n---------- Forwarded message ---------\nFrom: Jon Doe \nDate: Wed, Aug 21, 2024` into the content with below looks fine until you type any key. 
```
    parseOptions: {
      preserveWhitespace: 'full',
    },
    ```

**Comment by bdbch** [comment]
Opening this because it seems people still have issues with parsing whitespace characters.

**Comment by bdbch** [comment]
Could be that I need to revert the changes from https://github.com/ueberdosis/tiptap/pull/4767 and just let ProseMirror handle whitespaces.

That would reintroduce #2720 though and could lead to unwanted paragraph nodes being inserted back into content.

**Comment by reteps** [comment]
> This is a specific issue for our project, in which we have nodes that we want to load into the editor from disk that look like:
> 
> ```
> <my-custom-node {whitespace: `pre`}>
>   <subnode>Item 1</subnode>
>   <subnode>Item 2</subnode>
> </my-custom-node>
> ```
> 
> The whitespace is getting collapsed, so we end up with a document like:
> 
> ```
> <my-custom-node><subnode>Item 1</subnode><subnode>Item 2</subnode>
> </my-custom-node>
> ```
> 
> and a tree of
> 
> `my-custom-node`
> 
> * `subnode`
> * `subnode`
> 
> We actually want a tree like:
> 
> `my-custom-node`
> 
> * `subnode-whitespace`
> * `subnode`
> * `subnode-whitespace`
> * `subnode`

Desired behavior (this test case fails on main):

```
it('should keep newlines in pre tag between nodes', () => {
    cy.get('.tiptap').then(([{ editor }]) => {
      editor.commands.insertContent('<pre><div>foo</div>\n<code>foo\nbar</code></pre>')
      cy.get('.tiptap').should('contain.html', '<pre><div>foo</div>\n<code>foo\nbar</code></pre>')
    })
})
```

**Comment by reteps** [comment]
More generally, the correct fix for #2720 is to first parse the document with ProseMirror. Then, traverse the document tree. If you encounter an empty text node remove it. If you see a node with `whitespace: pre` set, don't traverse the children of that node.

**Comment by bdbch** [comment]
ProseMirror already comes with it's own solution to whitespace parsing. I think after we parsed content to ProseMirror we should not need to do it again in the usual cases so we avoid conflicting with the whitespace options already present across the editor.

**Comment by reteps** [comment]
@bdbch any updates here? This is still blocking us. A major release (i.e. [tiptap v4](https://github.com/ueberdosis/tiptap/discussions/7856) would be a good time to do it).
