### ISSUE TITLE
Conditional key binding

### ISSUE THREAD

**Issue by lstone** [ueberdosis/tiptap#480]
Hello, Is it possible to assign key bindings to a node (for example the code block) where the key bindings only fire off if the cursor is contained within said node? I'd like to enable the Tab key (4 spaces) only within the code block. Thanks for your input.

**Comment by deathg0d** [comment]
+1

**Comment by iannator10** [comment]
+1 update? thanks

**Comment by Chrissi2812** [comment]
This code goes into `CodeBlockHighlight.js`
This could then even be used along side `List Items` Tab behaviour

```js
keys({ type }) {
    return {
      'Shift-Ctrl-\\': setBlockType(type),
      Tab: (state, dispatch) => {
        const { selection: { $from } } = state // get current selection

        // compare the selected node type against the node type 'code_block'
        if ($from.node().type === type) {
          insertText('\t')(state, dispatch) // insert a tab or something different
          return true
        }

        return false
      },
    }
  }
```
