### ISSUE TITLE
Adding data-drag-handle doesn't always work

### ISSUE THREAD

**Issue by jasonvarga** [ueberdosis/tiptap#481]
**Describe the bug**
On a simple component, like the [drag handle example](https://tiptap.scrumpy.io/drag-handle), adding `data-drag-handle` makes dragging only work for that element.

On something more complicated, it doesn't.

**Steps to Reproduce / Codesandbox Example**

1. Go to https://codesandbox.io/embed/simplified-tiptap-editor-example-5s2k3
2. Drag one of the "Set of fields" blocks from anywhere.

**Expected behavior**

Dragging should only work when dragging from the handle (the darker box on the top right with the `=`)

**Additional context**

I know that something could probably be done using `stopEvent`, but I can't work out what.
I tried something along those lines, but it would also affect events within the nested inputs.

**Comment by jasonvarga** [comment]
Solved by adding `<div ref="content" hidden />` somewhere within the component.

**Comment by Greenscreener** [comment]
Ffs. I've been struggling with this for hours. This is far from ideal behaviour and I'd still consider it a bug. It wouldn't hurt for it to be documented somewhere at least.

**Comment by JerryKusenberger** [comment]
@Greenscreener Could you please provide a code sample? I'm struggling with this right now. I tried adding the hidden div as suggested by the OP but that did not work for me. I'm able to click and drag but when I drop the element stays in it's original position.

**Comment by Greenscreener** [comment]
@JerryKusenberger, your issue doesn't seem to be related with what I was struggling with. With my issue, I couldn't drag and drop at all, the whole element didn't register as draggable at all. If you're able to drag and drop, I'd suspect the problem might be you're dropping the element in the same place you picked it up from. The drag and drop mechanism can be quite unpredictable in determining, where the element will be dropped, so try moving it around a bit, maybe adding more elements it can interact with. For the code sample, check [this](https://github.com/ueberdosis/tiptap/blob/main/examples/Components/Routes/DragHandle/DragItem.js) out, but I'm afraid this might not solve your issue.

**Comment by JerryKusenberger** [comment]
Thank you. After a comparison the only difference I could find is that I was extending Mark and the example extends Node. After changing my element to extend node I can now drag and drop!
