### ISSUE TITLE
[Documentation]: `drag-handle-react` and `node-range` pro extensions documentation

### ISSUE THREAD

**Issue by piszczu4** [ueberdosis/tiptap#4814]
### What’s the URL to the page you’re sending feedback for?

https://tiptap.dev/docs/editor/extensions

### What part of the documentation needs improvement?

There is no description of above plugins

### What is helpful about that part?

There is no description of above plugins

### What is hard to understand, missing or misleading?

There is no description of above plugins

**Comment by emil14** [comment]
Any updates?

**Comment by carlosvaldesweb** [comment]
I also looking for drag handle docs.

**Comment by nperez0111** [comment]
Sorry we are in the middle of a huge documentation refactor and that is why it is not up yet.

Hopefully in the coming weeks we can release it

**Comment by mrowles** [comment]
How are we going with this @nperez0111 ?

**Comment by nachodeh** [comment]
Are there any updates on this?

**Comment by nperez0111** [comment]
I actually started writing this yesterday. Should be finished on monday

**Comment by nperez0111** [comment]
Here is the preliminary version:

---
title: Drag Handle extension
tags:
  - type: pro
meta:
  category: Editor
  title: Drag Handle extension | Tiptap Editor Docs
  description: Enable dragging nodes around your Tiptap Editor with the Drag Handle Extension. Learn how to set it up here in the Docs!
extension:
  name: Drag Handle
  description: You ever wanted to drag nodes around your editor? Well we too - so here is an extension for that.
  type: extension
  icon: GripVertical
  isPro: true
---

import { CodeDemo } from '@/components/CodeDemo'
import { Callout } from '@/components/ui/Callout'

You ever wanted to drag nodes around your editor? Well we too - so here is an extension for that.

The `DragHandle` extension allows you to easily handle dragging nodes around in the editor. You can define custom render functions, placement, and more.

<CodeDemo isPro path="/Experiments/DragHandle" />

## Install

<Callout title="Set up access to Tiptap's private repository" variant="info">
  Integrate this pro extension by registering for a free [Tiptap
  account](https://cloud.tiptap.dev/register) and following our [access
  guide](/guides/pro-extensions) to Tiptap’s private repository.
</Callout>

```bash
npm install @tiptap-pro/extension-drag-handle
```

## Settings

### render

Renders an element that is positioned with tippy.js. This is the element that will be displayed as the handle when dragging a node around.

```js
DragHandle.configure({
  render: () => {
    const element = document.createElement('div')

    // Use as a hook for CSS to insert an icon
    element.classList.add('custom-drag-handle')

    return element
  },
})
```

### tippyOptions

Options for tippy.js. You can pass any options that are available in the [tippy.js documentation](https://atomiks.github.io/tippyjs/v6/all-props/).

Default: `undefined`

```js
DragHandle.configure({
  tippyOptions: {
    placement: 'left',
  },
})
```

### onNodeChange

Returns a node or null when a node is hovered over. This can be used to highlight the node that is currently hovered over.

Default: `undefined`

```js
DragHandle.configure({
  onNodeChange: ({ node, editor }) => {
    if (!node) {
      selectedNode = null
      return
    }
    // Do something with the node
    selectedNode = node
  },
})
```

## Commands

### lockDragHandle()

Locks the draghandle in place and visibility. If the drag handle was visible, it will remain visible until unlocked. If it was hidden, it will remain hidden until unlocked.

This can be useful if you want to have a menu inside of the drag handle and want it to remain visible whether the drag handle is moused over or not.

```js
editor.commands.lockDragHandle()
```

### unlockDragHandle()

Unlocks the draghandle. Resets to default visibility and behavior.

```js
editor.commands.unlockDragHandle()
```

### toggleDragHandle()

Toggle draghandle lock state. If the drag handle is locked, it will be unlocked and vice versa.

```js
editor.commands.toggleDragHandle()
```

**Comment by nachodeh** [comment]
@nperez0111 thanks! Just set it up in my editor and it's mostly working.

One notable major issue happens with lists. The drag handle plugin applies to the list as a whole instead of allowing me to drag individual items. Is this a known issue? Is there a config I can apply to select list items individually?

**Comment by ori-avraham** [comment]
> @nperez0111 thanks! Just set it up in my editor and it's mostly working.
> 
> One notable major issue happens with lists. The drag handle plugin applies to the list as a whole instead of allowing me to drag individual items. Is this a known issue? Is there a config I can apply to select list items individually?

I didn't find any way of changing this behavior, [this extension](https://github.com/NiclasDev63/tiptap-extension-global-drag-handle) does have the wanted behavior, although as for my use case it also has a few problems.

**Comment by Mrdaimi** [comment]
> Here is the preliminary version:
> 
> title: Drag Handle extension tags:
> 
> * type: pro
>   meta:
>   category: Editor
>   title: Drag Handle extension | Tiptap Editor Docs
>   description: Enable dragging nodes around your Tiptap Editor with the Drag Handle Extension. Learn how to set it up here in the Docs!
>   extension:
>   name: Drag Handle
>   description: You ever wanted to drag nodes around your editor? Well we too - so here is an extension for that.
>   type: extension
>   icon: GripVertical
>   isPro: true
> 
> import { CodeDemo } from '@/components/CodeDemo' import { Callout } from '@/components/ui/Callout'
> 
> You ever wanted to drag nodes around your editor? Well we too - so here is an extension for that.
> 
> The `DragHandle` extension allows you to easily handle dragging nodes around in the editor. You can define custom render functions, placement, and more.
> 
> ## Install
> Integrate this pro extension by registering for a free [Tiptap account](https://cloud.tiptap.dev/register) and following our [access guide](/guides/pro-extensions) to Tiptap’s private repository.
> ```shell
> npm install @tiptap-pro/extension-drag-handle
> ```
> 
> ## Settings
> ### render
> Renders an element that is positioned with tippy.js. This is the element that will be displayed as the handle when dragging a node around.
> 
> ```js
> DragHandle.configure({
>   render: () => {
>     const element = document.createElement('div')
> 
>     // Use as a hook for CSS to insert an icon
>     element.classList.add('custom-drag-handle')
> 
>     return element
>   },
> })
> ```
> 
> ### tippyOptions
> Options for tippy.js. You can pass any options that are available in the [tippy.js documentation](https://atomiks.github.io/tippyjs/v6/all-props/).
> 
> Default: `undefined`
> 
> ```js
> DragHandle.configure({
>   tippyOptions: {
>     placement: 'left',
>   },
> })
> ```
> 
> ### onNodeChange
> Returns a node or null when a node is hovered over. This can be used to highlight the node that is currently hovered over.
> 
> Default: `undefined`
> 
> ```js
> DragHandle.configure({
>   onNodeChange: ({ node, editor }) => {
>     if (!node) {
>       selectedNode = null
>       return
>     }
>     // Do something with the node
>     selectedNode = node
>   },
> })
> ```
> 
> ## Commands
> ### lockDragHandle()
> Locks the draghandle in place and visibility. If the drag handle was visible, it will remain visible until unlocked. If it was hidden, it will remain hidden until unlocked.
> 
> This can be useful if you want to have a menu inside of the drag handle and want it to remain visible whether the drag handle is moused over or not.
> 
> ```js
> editor.commands.lockDragHandle()
> ```
> 
> ### unlockDragHandle()
> Unlocks the draghandle. Resets to default visibility and behavior.
> 
> ```js
> editor.commands.unlockDragHandle()
> ```
> 
> ### toggleDragHandle()
> Toggle draghandle lock state. If the drag handle is locked, it will be unlocked and vice versa.
> 
> ```js
> editor.commands.toggleDragHandle()
> ```

when I try to use this extension In my Code，it appears error like thats：GET http://localhost:3001/node_modules/.vite/deps/@tiptap-pro_extension-drag-handle.js?v=71b69e5f net::ERR_ABORTED 504 (Outdated Optimize Dep)

**Comment by nperez0111** [comment]
> @nperez0111 thanks! Just set it up in my editor and it's mostly working.
> 
> One notable major issue happens with lists. The drag handle plugin applies to the list as a whole instead of allowing me to drag individual items. Is this a known issue? Is there a config I can apply to select list items individually?

@nachodeh this extension deals with moving the outermost blocks in the editor, not sub items, we will consider this in the future as an enhancement to the current functionality but for now it is out of scope because it is complicated to implement

**Comment by Mrdaimi** [comment]
> > when I try to use this extension In my Code，it appears error like thats：GET http://localhost:3001/node_modules/.vite/deps/@tiptap-pro_extension-drag-handle.js?v=71b69e5f net::ERR_ABORTED 504 (Outdated Optimize Dep)
> 
> This is your vite dev server configuration, totally unrelated to this

Thanks, I've solved it. There are other problems. Dragging to the top or bottom of the page will not automatically scroll in the corresponding direction.

**Comment by laowangdefangjian** [comment]
> ```shell
> @tiptap-pro/extension-drag-handle
> ```

Boss, when will it be deployed to the Tiptap document

**Comment by nperez0111** [comment]
I posted the same docs that I had above.

The node-range extension is not really worth documenting since it is more of a helper function than something you would have in your editor

**Comment by NiclasDev63** [comment]
I would recommend that you take a look at my [drag handle implementation](https://github.com/NiclasDev63/tiptap-extension-global-drag-handle), which is used in several large open source projects. It has a few more features than tiptap's drag handle, as it allows you to drag individual list items, for example. Or you can directly download it via [npm](https://www.npmjs.com/package/tiptap-extension-global-drag-handle)

**Comment by codepeach** [comment]
Is there a function to handle when the paragraph is moved or dropped? ` onNodeChange()` updates for every cursor move. I want a callback for only when an item is dragged and dropped.

**Comment by nperez0111** [comment]
> Is there a function to handle when the paragraph is moved or dropped? ` onNodeChange()` updates for every cursor move. I want a callback for only when an item is dragged and dropped.

No, that is not supported

**Comment by laowangdefangjian** [comment]
Drag Handle extension 
Can you provide a version of Vue with a menu?

**Comment by nperez0111** [comment]
Drag handle vue version: https://tiptap.dev/docs/editor/extensions/functionality/drag-handle-vue

**Comment by laowangdefangjian** [comment]
> Drag handle vue version: https://tiptap.dev/docs/editor/extensions/functionality/drag-handle-vue

But I want to add a menu to the button at the same time, and I don't know how to implement your extension.

**Comment by nperez0111** [comment]
You can put any component you want as a child of the drag-handle component. This is on you, it is there

**Comment by nperez0111** [comment]
this is clearly a problem with your code. I can't help you with this

**Comment by laowangdefangjian** [comment]
我是完全按照您的https://tiptap.dev/docs/editor/extensions/functionality/drag-handle-vue vue3的示例代码直接复制过来的，依赖也都是最新的，而且是新建的页面，后来我又新启动了一个vue3的项目  同样报这个错误

**Comment by laowangdefangjian** [comment]
> this is clearly a problem with your code. I can't help you with this

I copied the example code directly from your https://tiptap.dev/docs/editor/extensions/functionality/drag-handle-vue Vue 3 page, and the dependencies are all the latest versions. It's also a newly created page. Later, I started a new Vue 3 project, and the same error occurred.

**Comment by laowangdefangjian** [comment]
> this is clearly a problem with your code. I can't help you with this

Please help me take a look; I am working on this urgent task. Thank you.

**Comment by laowangdefangjian** [comment]
> this is clearly a problem with your code. I can't help you with this

Could you please take some time to look at the issue with the handle example in Vue 3?

**Comment by nperez0111** [comment]
This is the source code for the vue-3 extension. If there is an issue with the vue 3 integration you can fix it on your own and let me know what needed to be changed.

```vue
import { Editor } from '@tiptap/vue-3'
import {
  DragHandlePlugin,
  dragHandlePluginDefaultKey,
  DragHandlePluginProps,
} from '@tiptap-pro/extension-drag-handle'
import {
  defineComponent, h, onBeforeUnmount, onMounted, PropType, ref,
} from 'vue'

type Optional<T, K extends keyof T> = Pick<Partial<T>, K> & Omit<T, K>;

export type DragHandleProps = Omit<Optional<DragHandlePluginProps, 'pluginKey'>, 'element'> & {
  class?: string;
  onNodeChange?: (data: { node: Node | null; editor: Editor; pos: number }) => void;
};

export const DragHandle = defineComponent({
  name: 'DragHandleVue',

  props: {
    pluginKey: {
      type: [String, Object] as PropType<DragHandleProps['pluginKey']>,
      default: dragHandlePluginDefaultKey,
    },

    editor: {
      type: Object as PropType<DragHandleProps['editor']>,
      required: true,
    },

    tippyOptions: {
      type: Object as PropType<DragHandleProps['tippyOptions']>,
      default: () => ({}),
    },

    onNodeChange: {
      type: Function as PropType<DragHandleProps['onNodeChange']>,
      default: null,
    },

    class: {
      type: String as PropType<DragHandleProps['class']>,
      default: 'drag-handle',
    },
  },

  setup(props, { slots }) {
    const root = ref<HTMLElement | null>(null)

    onMounted(() => {
      const {
        editor, pluginKey, onNodeChange, tippyOptions,
      } = props

      editor.registerPlugin(
        DragHandlePlugin({
          editor,
          element: root.value as HTMLElement,
          pluginKey,
          tippyOptions,
          onNodeChange,
        }),
      )
    })

    onBeforeUnmount(() => {
      const { pluginKey, editor } = props

      editor.unregisterPlugin(pluginKey as string)
    })

    return () => h('div', { ref: root, class: props.class }, slots.default?.())
  },
})
```

**Comment by laowangdefangjian** [comment]
> This is the source code for the vue-3 extension. If there is an issue with the vue 3 integration you can fix it on your own and let me know what needed to be changed.
> 
> ```vue
> import { Editor } from '@tiptap/vue-3'
> import {
>   DragHandlePlugin,
>   dragHandlePluginDefaultKey,
>   DragHandlePluginProps,
> } from '@tiptap-pro/extension-drag-handle'
> import {
>   defineComponent, h, onBeforeUnmount, onMounted, PropType, ref,
> } from 'vue'
> 
> type Optional<T, K extends keyof T> = Pick<Partial<T>, K> & Omit<T, K>;
> 
> export type DragHandleProps = Omit<Optional<DragHandlePluginProps, 'pluginKey'>, 'element'> & {
>   class?: string;
>   onNodeChange?: (data: { node: Node | null; editor: Editor; pos: number }) => void;
> };
> 
> export const DragHandle = defineComponent({
>   name: 'DragHandleVue',
> 
>   props: {
>     pluginKey: {
>       type: [String, Object] as PropType<DragHandleProps['pluginKey']>,
>       default: dragHandlePluginDefaultKey,
>     },
> 
>     editor: {
>       type: Object as PropType<DragHandleProps['editor']>,
>       required: true,
>     },
> 
>     tippyOptions: {
>       type: Object as PropType<DragHandleProps['tippyOptions']>,
>       default: () => ({}),
>     },
> 
>     onNodeChange: {
>       type: Function as PropType<DragHandleProps['onNodeChange']>,
>       default: null,
>     },
> 
>     class: {
>       type: String as PropType<DragHandleProps['class']>,
>       default: 'drag-handle',
>     },
>   },
> 
>   setup(props, { slots }) {
>     const root = ref<HTMLElement | null>(null)
> 
>     onMounted(() => {
>       const {
>         editor, pluginKey, onNodeChange, tippyOptions,
>       } = props
> 
>       editor.registerPlugin(
>         DragHandlePlugin({
>           editor,
>           element: root.value as HTMLElement,
>           pluginKey,
>           tippyOptions,
>           onNodeChange,
>         }),
>       )
>     })
> 
>     onBeforeUnmount(() => {
>       const { pluginKey, editor } = props
> 
>       editor.unregisterPlugin(pluginKey as string)
>     })
> 
>     return () => h('div', { ref: root, class: props.class }, slots.default?.())
>   },
> })
> ```

Okay, I'll give it a try first; it might be a bit difficult. Thank you!

**Comment by laowangdefangjian** [comment]
> This is the source code for the vue-3 extension. If there is an issue with the vue 3 integration you can fix it on your own and let me know what needed to be changed.
> 
> ```vue
> import { Editor } from '@tiptap/vue-3'
> import {
>   DragHandlePlugin,
>   dragHandlePluginDefaultKey,
>   DragHandlePluginProps,
> } from '@tiptap-pro/extension-drag-handle'
> import {
>   defineComponent, h, onBeforeUnmount, onMounted, PropType, ref,
> } from 'vue'
> 
> type Optional<T, K extends keyof T> = Pick<Partial<T>, K> & Omit<T, K>;
> 
> export type DragHandleProps = Omit<Optional<DragHandlePluginProps, 'pluginKey'>, 'element'> & {
>   class?: string;
>   onNodeChange?: (data: { node: Node | null; editor: Editor; pos: number }) => void;
> };
> 
> export const DragHandle = defineComponent({
>   name: 'DragHandleVue',
> 
>   props: {
>     pluginKey: {
>       type: [String, Object] as PropType<DragHandleProps['pluginKey']>,
>       default: dragHandlePluginDefaultKey,
>     },
> 
>     editor: {
>       type: Object as PropType<DragHandleProps['editor']>,
>       required: true,
>     },
> 
>     tippyOptions: {
>       type: Object as PropType<DragHandleProps['tippyOptions']>,
>       default: () => ({}),
>     },
> 
>     onNodeChange: {
>       type: Function as PropType<DragHandleProps['onNodeChange']>,
>       default: null,
>     },
> 
>     class: {
>       type: String as PropType<DragHandleProps['class']>,
>       default: 'drag-handle',
>     },
>   },
> 
>   setup(props, { slots }) {
>     const root = ref<HTMLElement | null>(null)
> 
>     onMounted(() => {
>       const {
>         editor, pluginKey, onNodeChange, tippyOptions,
>       } = props
> 
>       editor.registerPlugin(
>         DragHandlePlugin({
>           editor,
>           element: root.value as HTMLElement,
>           pluginKey,
>           tippyOptions,
>           onNodeChange,
>         }),
>       )
>     })
> 
>     onBeforeUnmount(() => {
>       const { pluginKey, editor } = props
> 
>       editor.unregisterPlugin(pluginKey as string)
>     })
> 
>     return () => h('div', { ref: root, class: props.class }, slots.default?.())
>   },
> })
> ```

Sorry, I don't have the ability to handle this issue. I hope you can help me.

**Comment by nperez0111** [comment]
No

**Comment by intel-swift** [comment]
IN drag handler when I add onNodeChange handler, the dragging simply stops working, I click on the element and it dissapears. 
This is in react 

<DragHandle 
                pluginKey={"drag-menu"}
                editor={editor}
                tippyOptions={{
                    placement: 'left',
                    onShow: (event)=>{
                      console.log("On show is called", event)
                      editor.chain().focus()
                    }
                }}
                onNodeChange={({ node, editor, pos }) => {
                    console.log("Selected node ", node);

                    //setSelectedNode(node)
                }}
            >
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="1.5" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 9h16.5m-16.5 6.75h16.5" />
            </svg>
            </DragHandle>

Any idea what is happening? It's working just fine when I remove onNodeChange handler though

**Comment by Jenish-cloudairy** [comment]
same with me , when i add onNodeChange in dragHandle then its stop working and going on top left position of my screen and if i remove it that drag handle is coming on every node when hover but still drag not working, what could be the issue?
