### ISSUE TITLE
Best way to identify type of mark

### ISSUE THREAD

**Issue by svennerberg** [ueberdosis/tiptap#482]
I'm trying to implement a menu that will appear when you click on an image in the editor. My goal is to set a class on the image to determine if it should be left-aligned, right-aligned, centered or full width. 

With the Link-example in the documentation as a starting point, I would like to show these align-controls only if it's an image that been clicked but I'm having trouble identifying it as such.

I figured that I could do something like: `getMarkAttrs('image')` or maybe `getMarkAttrs('img')` in the same way as its `getMarkAttrs('link')` in the example. But it only returns undefined. 

Any suggestions on how to do this?

**Comment by ilicmarko** [comment]
Can you please provide code inside https://codesandbox.io/ so we help you out.
