### ISSUE TITLE
[Bug]: Copy a table from a Word document with a link

### ISSUE THREAD

**Issue by kbin24** [ueberdosis/tiptap#4848]
### Which packages did you experience the bug in?

core,Vue2

### What Tiptap version are you using?

2.0.0

### What’s the bug you are facing?

Copy a table from a Word document with a link in it. But after copying it into TIptap, other text will be converted into links.
## Actual in Word Document
![企业微信截图_20240202135802](https://github.com/ueberdosis/tiptap/assets/37393946/55effbe6-d3b1-412b-a576-51130dda4b3c)
## Actual in Tiptap
![12313123213](https://github.com/ueberdosis/tiptap/assets/37393946/75afb1ca-baf0-407c-8009-65de274ae675)

## Reproduction steps
1. Add a table with links in a Word document
2. Copy Table into Tiptap (https://templates.tiptap.dev/NRmPrnCGJn)

### What browser are you using?

Chrome

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by kbin24** [comment]
This bug will only appear after the @tiptap/extension-link version is 2.1.15

**Comment by Naroh091** [comment]
We're experiencing similar issues pasting content with links from Google Docs:

Actual document:

<img width="633" alt="image" src="https://github.com/ueberdosis/tiptap/assets/2976270/fd12d78e-4ebe-44ab-ad75-710cd3e6b45c">

Result after pasting in TipTap:

![image](https://github.com/ueberdosis/tiptap/assets/2976270/70b48b51-6aa5-4ec3-8181-8ee647c4e82c)

For us, downgrading extension-link to versions prior to 2.1.15 didn't work – we ended up downgrading everything to 2.0.4 which was the latest version we knew didn't have this bug for now until we narrow down which versions are working and which versions don't.

**Comment by jakebarshickf1nx** [comment]
2.1.10 is the last version that I don't experience any pasting issues FYI. Seems like 2.1.11 is where things start breaking for me maybe #4354 is the initial cause?

**Comment by svenadlung** [comment]
Thanks! We are investigating this issue.
