### ISSUE TITLE
[Bug]: ERROR in ./node_modules/@tiptap/react/dist/index.js Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by masudhossain** [ueberdosis/tiptap#4852]
### Which packages did you experience the bug in?

react

### What Tiptap version are you using?

^2.2.1

### What’s the bug you are facing?

Getting this error when i try to use the npm package in a component. 

error: 
```
15:19:51 webpack.1 | ERROR in ./node_modules/@tiptap/react/dist/index.js
15:19:51 webpack.1 | Module parse failed: Unexpected token (72:20)
15:19:51 webpack.1 | You may need an appropriate loader to handle this file type.
15:19:51 webpack.1 | |             this.setState(({ renderers }) => ({
15:19:51 webpack.1 | |                 renderers: {
15:19:51 webpack.1 | |                     ...renderers,
15:19:51 webpack.1 | |                     [id]: renderer,
15:19:51 webpack.1 | |                 },
15:19:51 webpack.1 |  @ ./app/javascript/components/Shared/Demo.js 2:0-83
15:19:51 webpack.1 |  @ ./app/javascript/components/App.js
15:19:51 webpack.1 |  @ ./app/javascript/packs/index.jsx
15:19:51 webpack.1 |  @ multi (webpack)-dev-server/client?http://localhost:3035 ./app/javascript/packs/index.jsx
15:19:51 webpack.1 | webpack: Failed to compile.
```

```js
import React from 'react';
import { useEditor, EditorContent, FloatingMenu, BubbleMenu } from '@tiptap/react'

const Tiptap = () => {
  return (
    <div>
      TipTap file
    </div>
  )
}

export default Tiptap
```

Node version: v14.16.1
react version: "react": "^16.13.1"
"@Tiptap#9653/pm": "^2.2.1",
"@Tiptap#9653/react": "^2.2.1",
"@Tiptap#9653/starter-kit": "^2.2.1",
"@uppy/companion": "^2.3.1",

### What browser are you using?

Chrome

### What did you expect to happen?

To not have an error and show the editor. 

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by iamshubhambhola** [comment]
@masudhossain you have just shared a part of your code where there is no initialisation of tiptap editor's instance as mentioned in their official documentation.
Editor will be displayed only when you replace the _Tiptap File_ text with actual Tiptap Component `<TiptapFile/>`.
```
const TiptapFile = () => {
  const editor = useEditor({
    extensions,
    content,
  })

  return (
    <>
      <EditorContent editor={editor} />
      <FloatingMenu editor={editor}>This is the floating menu</FloatingMenu>
      <BubbleMenu editor={editor}>This is the bubble menu</BubbleMenu>
    </>
  )
}
```
I hope this finds helpful:)

**Comment by masudhossain** [comment]
> @masudhossain you have just shared a part of your code where there is no initialisation of tiptap editor's instance as mentioned in their official documentation. Editor will be displayed only when you replace the _Tiptap File_ text with actual Tiptap Component `<TiptapFile/>`.
> 
> ```
> const TiptapFile = () => {
>   const editor = useEditor({
>     extensions,
>     content,
>   })
> 
>   return (
>     <>
>       <EditorContent editor={editor} />
>       <FloatingMenu editor={editor}>This is the floating menu</FloatingMenu>
>       <BubbleMenu editor={editor}>This is the bubble menu</BubbleMenu>
>     </>
>   )
> }
> ```
> 
> I hope this finds helpful:)

The issue isn't rendering the components. The issue is that i cannot even import the components over.

**Comment by Slapbox** [comment]
I didn't look at this deeply, but it seems incredibly unlikely this is a TipTap bug.

**Comment by ethanyou725** [comment]
it look like a misconfigration about webpack

**Comment by masudhossain** [comment]
> This is generally a parser bug.
> 
> Check your dependencies and see if you have a package called "acorn"
> 
> `npm ls --pattern="acorn"`
> 
> most bundlers like Webpack will use Acorn to parse JavaScript. Chances are you have an outdated version of Acorn not accounting for new JavaScript syntax.
> 
> usually setting a "resolutions" or "overrides" (depends on your package manager) to a newer version of Acorn should make the error go away.
> 
> also make sure to delete your node_modules and reinstall after setting overrides / resolutions.

Issue resolved thanks to this guy
