### ISSUE TITLE
Upload images from clipboard

### ISSUE THREAD

**Issue by jetacpp** [ueberdosis/tiptap#486]
Hi, does tiptap editor plan to have ability to upload images from clipboard ? preferably clipboard with mixed of text and images, such as copied from Microsoft Word.

**Comment by ilicmarko** [comment]
This is two separate features. Needs more definition. Do you want to upload the image only in the upload modal or in the whole textarea like Github. Furthermore, this can be implemented by a plugin you don't need need to change the core.

**Comment by jetacpp** [comment]
Users are most likely used to pasting clipboard containing image into note editor, so yes upload in the whole textarea like Github :)

**Comment by hanspagel** [comment]
Would be a cool feature, but it’s so different how that should work in detail depending on the backend and kind of app you’re building. I don't see us to build exactly that feature, but I’ll keep it in mind. Maybe we can make that easier with [tiptap v2](https://blog.ueber.io/post/our-plan-for-tiptap-2/). 🙌
