### ISSUE TITLE
excludes: "" is not working in MarkSpec after update to 1.26

### ISSUE THREAD

**Issue by xaksis** [ueberdosis/tiptap#492]
**Describe the bug**
Specifying excludes: "" does not allow overlapping marks (with different attributes) anymore. It acts as if excludes option was not supplied at all.
for reference: http://prosemirror.net/docs/ref/#model.MarkSpec.excludes

Edit: 
@gmickel found the following commit resulted in the bug: 
https://github.com/scrumpy/tiptap/commit/7a56da631516f8e620893a63b4d34857942ea44d#diff-238892edc7df3b1cd8441964434720d2

This is breaking overlapping/nesting of same mark type with different attributes.

**Comment by xaksis** [comment]
Downgrading to the following works: 
```
    "tiptap": "1.25.0",
    "tiptap-commands": "1.11.0",
    "tiptap-extensions": "1.27.0",
    "tiptap-utils": "1.7.0",
```

**Comment by gmickel** [comment]
I just noticed this too. Our editor heavily relies on nesting a certain mark and that stops working after the releases you mention above.

**Comment by gmickel** [comment]
After some further testing, the issue starts after this commit to the updateMark command: https://github.com/scrumpy/tiptap/commit/7a56da631516f8e620893a63b4d34857942ea44d#diff-238892edc7df3b1cd8441964434720d2
I assume it's the check for existing marks in the current selected range.

**Comment by xaksis** [comment]
@philippkuehn would you have any time to look at this? I'm surprised more people haven't complained about this yet, because nesting marks have been broken for a while.
Also, happy new year!

**Comment by hanspagel** [comment]
Sorry for the silence here. Is this still an issue? Maybe @gmickel knows? 

I’m closing this here for now, because I’m assuming this won’t be an issue with the upcoming version 2 of tiptap, where we’ve completely rewritten the updateMark command.

**Comment by gmickel** [comment]
I'd have to check to be sure but as far as I can remember, I stopped using the updateMark command for anything related to nested marks.

**Comment by xaksis** [comment]
I ended up using my own version of updateMark. Not sure if this was ever fixed.

**Comment by hanspagel** [comment]
Thanks for getting back so quickly! 

Never mind! As I said, it’s a complete rewrite in v2 anyway. Just wanted to make sure you’ve somehow found a solution. 🌟
