### ISSUE TITLE
Link conflicts with Image extension

### ISSUE THREAD

**Issue by chrisjbrown** [ueberdosis/tiptap#493]
**Describe the bug**
when pasting the src value of an img element. the link extension creates an `a` tag inside of the src attribute 
eg: `<img src="<a href="myimg">...`

**Steps to Reproduce / Codesandbox Example**
1. https://codesandbox.io/embed/vue-issue-template-de7n5
2. type <img src="
3. and paste a url
4. inspect the editor and see that an anchor tag is created as the src value

**Expected behavior**
should detect it's within a src attribute and not convert the pasted input

**Environment**
 - OS: Mac
 - Browser Brave
 - Mobile / Desktop

**Comment by chrisjbrown** [comment]
better example of the issues
https://codesandbox.io/embed/vue-issue-template-de7n5

**Comment by philippkuehn** [comment]
Can’t reproduce this anymore.
