### ISSUE TITLE
[PRO]: Details persist: false causes scrolling on open and close

### ISSUE THREAD

**Issue by thefinnomenon** [ueberdosis/tiptap#4951]
### Which packages did you experience the bug in?

Details

### What Tiptap version are you using?

2.2.4

### What’s the bug you are facing?

If I don't set persist: true on the Details extension, every time I click to open or close the component, the page scrolls.

### What browser are you using?

Chrome

### Code example

I don't have a code example since it uses the PRO extension but if you remove `persist: true` in the TipTap demo it should cause the issue.

### What did you expect to happen?

I expect the component to just open and close like normal with persist set to false.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by Davron129** [comment]
Same issue when removing persist: true (

**Comment by nperez0111** [comment]
Thanks for bumping this. Got lost in everything else. I see the issue & it is now released as v2.10.10
