### ISSUE TITLE
[PRO]: Add support for chemistry equations to Mathematics extension

### ISSUE THREAD

**Issue by thefinnomenon** [ueberdosis/tiptap#4977]
### Which packages did you experience the bug in?

2.2.3

### What Tiptap version are you using?

2.2.3

### What’s the bug you are facing?

We are loving the Mathematics extension but have users who also need to write chemistry equations. It looks like support can be easily added by importing the `mhchem` package.

https://github.com/KaTeX/KaTeX/tree/main/contrib/mhchem

### What browser are you using?

Chrome

### What did you expect to happen?

I expect to be able to use chemistry equations too and have it converted into the appropriate LaTex.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by Te0SX** [comment]
Go to your main tip tap editor file. When you are using Mathematic pro extension, you also have to import the katex.css. Guess what? Just import the official mhchem package as well under the css as:

```
import 'katex/dist/katex.min.css'
import 'katex/contrib/mhchem/mhchem'; // Import the mhchem extension
```

and it works like magic!

**Comment by thefinnomenon** [comment]
> Go to your main tip tap editor file. When you are using Mathematic pro extension, you also have to import the katex.css. Guess what? Just import the official mhchem package as well under the css as:
> 
> ```
> import 'katex/dist/katex.min.css'
> import 'katex/contrib/mhchem/mhchem'; // Import the mhchem extension
> ```
> 
> and it works like magic!

So simple haha. Thanks!

I import that worked for me was `import "katex/contrib/mhchem"`
