### ISSUE TITLE
[Bug]:  Unexpected behaviour of configured extensions

### ISSUE THREAD

**Issue by yurtsiv** [ueberdosis/tiptap#4981]
### Which packages did you experience the bug in?

core

### What Tiptap version are you using?

2.2.4

### What’s the bug you are facing?

It applies to all methods in the extension config, but I'll give an example I stumbled upon with `addProseMirrorPlugins`

```typescript
const Base = Extension.create(...)

const pluginKey = new PluginKey("someKey");

const Example = Base.extend({
  addProseMirrorPlugins() {
    return [
      ...(this.parent?.() ?? []),
      new Plugin({ key: pluginKey }),
    ]
  },
})

new Editor({
   extensions: [
      Example.configure()
   ]
})
```

Crashes with ```RangeError: Adding different instances of a keyed plugin (someKey$)```.

It happens because [.configure() extends](https://github.com/ueberdosis/tiptap/commit/fda6310e7462a86724566d6630812c3ddb46a2d6#diff-5646f4773d47ddc5a0ff04bd8aa67213e7457fbac3b135e3237ffda72737b323L343), so we end up with the hierarchy `ExampleBase -> Example -> Example` instead of `ExampleBase -> Example` which results in duplicate plugins being registered.

The same problem occurs with other methods, but those that return lists are most vulnerable (e.g. `addInputRule`).

I guess  `.configure()` should copy the extension instead of extending it.

### What browser are you using?

Chrome

### What did you expect to happen?

No duplicate plugins are registered.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by yurtsiv** [comment]
Partially a duplicate of https://github.com/ueberdosis/tiptap/issues/4704

**Comment by yurtsiv** [comment]
This commit https://github.com/ueberdosis/tiptap/commit/fda6310e7462a86724566d6630812c3ddb46a2d6 seems to be the reason why it broke. Before it `.extend()`  wasn't copying the config so the last extension in the hierarchy `ExampleBase -> Example -> Example` (described above) didn't have `addProseMirrorPlugins` defined

**Comment by nperez0111** [comment]
This should be [fixed](https://github.com/ueberdosis/tiptap/pull/5147) with version 2.4.0, feel free to try it out!
