### ISSUE TITLE
[PRO]: TableOfContents `isActive` and `isScrolledOver` appear broken

### ISSUE THREAD

**Issue by fuadsaud** [ueberdosis/tiptap#4989]
### Which packages did you experience the bug in?

extension-table-of-contents

### What Tiptap version are you using?

@tiptap-pro/extension-table-of-contents@2.7.6 @tiptap/extension-collaboration-cursor@2.2.4 @tiptap/extension-collaboration@2.2.4 @tiptap/extension-heading@2.2.4 @tiptap/extension-link@2.2.3 @tiptap/extension-text-align@2.2.3 @tiptap/extension-typography@2.2.1 @tiptap/extension-underline@2.2.4 @tiptap/pm@2.2.1 @tiptap/react@2.2.3 @tiptap/starter-kit@2.2.4

### What’s the bug you are facing?

Looking at the [table of contents demo](https://tiptap.dev/docs/editor/api/extensions/table-of-contents#usage), it appears that `isScrolledOver` and `isActive` are always false and have no effect on the styling of the table of contents displayed on the top right of the screen.

I also experience that when trying to integrate into the app I'm working on: those values are never true regardless of the cursor or viewport position.

Perhaps I misunderstand how they're supposed to work. If that's the case it would be nice to get some clarifications.

### What browser are you using?

Chrome

### Code example

https://tiptap.dev/docs/editor/api/extensions/table-of-contents#usage

### What did you expect to happen?

`isActive` and `isScrolledOver` values to be `true` depending on the cursor and viewport positions.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by svenadlung** [comment]
@fuadsaud Thanks for the report. It should be fixed in 2.8.9 🙌
