### ISSUE TITLE
 setContent  may cause memory leak. 

### ISSUE THREAD

**Issue by Ryeonnie** [ueberdosis/tiptap#499]
**Describe the bug**
function `setContent`  may cause memory leak. 

The number of DOMs is normal, which will vary with the size of specific content. But the Node instance, and many prosemirror instance will not be remove from memory.

**Steps to Reproduce**
1. Just call  `setContent` function many times

**Expected behavior**
When I switch documents in editor by calling `setContent`, the memory should be steady and vary with the size of document.

**Screenshots**
<img width="958" alt="截屏2019-10-1916 44 41" src="https://user-images.githubusercontent.com/55738135/67140854-3bdc8c00-f291-11e9-8e04-f3be24264d00.png">

**Environment**
 - OS: macOS 10.15
 - Browser Chrome 76
 - Version 1.26.4
 -  Desktop

**Comment by deepaksisodiya** [comment]
any update on this

**Comment by Auxxxxlx** [comment]
Nothing new for this issue, I did not find any solution.  Maybe @philippkuehn  could help?

**Comment by alloself** [comment]
any updates?

**Comment by hanspagel** [comment]
Can be reproduced with

```js
let count = 0

this.interval = setInterval(() => {
  count++
  this.editor.setContent(`<p>${count}</p>`)
}, 1)
```

**Comment by ericpoulinnz** [comment]
We are getting this issue as well which is causing problems for our users. Is this something Tiptap 2 addresses?

**Comment by bigsee** [comment]
Hello! 👋🏾  Experiencing pretty big performance hit as a result of this issue. Does the label mean it is something which is solved in Tiptap 2? And, for those who do not have the opportunity to migrate yet, has anyone found a decent workaround?

**Comment by philippkuehn** [comment]
@bigsee I still not 100% sure what happens here. I think this is somehow related to the DOMParser (https://github.com/ueberdosis/tiptap/blob/main/packages/core/src/utilities/elementFromString.ts)

Any help is appreciated!

**Comment by hanspagel** [comment]
Hmm …
https://stackoverflow.com/a/56461938

**Comment by philippkuehn** [comment]
DOMParser was implemented bycause of https://github.com/ueberdosis/tiptap/issues/713 and https://github.com/ueberdosis/tiptap/pull/747. Not sure about changing it back.

**Comment by philippkuehn** [comment]
I tested a bit and added 10000 paragraphs

```js
for (let i = 0; i < 10000; i += 1) {
  this.editor.commands.setContent('<p>test</p>', true)
}
```

For me, this graph says that the garbage collector is working fine. Or am I interpreting this wrong?

<img width="1049" alt="Bildschirmfoto 2021-05-28 um 16 14 57" src="https://user-images.githubusercontent.com/2500670/119997362-eff6da80-bfcf-11eb-945c-86050427f00d.png">
