### ISSUE TITLE
[Bug]: @tiptap/extension-bubble-menu NPM package is core dependency of @tiptap/react

### ISSUE THREAD

**Issue by timovanderzanden** [ueberdosis/tiptap#5000]
### Which packages did you experience the bug in?

react

### What Tiptap version are you using?

2.2.4

### What’s the bug you are facing?

We're currently using the npm Tiptap React package and while optimizing our builds, we've noticed that the `@tiptap/extension-bubble-menu` and `@tiptap/extension-floating-menu` are **core** dependencies of the Tiptap React npm package.

It seems confusing that all other extensions are optional and these extensions are included by default, while we don't use any floating toolbar components for Tiptap (and don't use Tippy or PopperJS).

Can this be removed from the dependency list?

### What browser are you using?

Chrome

### What did you expect to happen?

I expected the `@tiptap/react` package to only include the absolute minimal feature set, but it appears that it has 2 (seemingly unnecessary) extensions included.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by benkroeger** [comment]
it's the same for the vuejs package - this is required because these library-specific packages also come with custom components to work with BubbleMenu and FloatingMenu.
If you're not using those custom components in your project, tree-shaking (e.g. when building with vite) would automatically NOT include `@tiptap/extension-bubble-menu` or `@tiptap/extension-floating-menu` code in your deliverables (`dist`).

**Comment by nperez0111** [comment]
There is a PR open for this. https://github.com/ueberdosis/tiptap/pull/4749

So this dupes https://github.com/ueberdosis/tiptap/issues/3170

**Comment by benkroeger** [comment]
the PR only covers react. is the intent to implement this similarly for vue?

**Comment by nperez0111** [comment]
We have not prioritized this at this time since it is a breaking change. But I'll leave a comment that we should do the same for vue. But I would not expect this any time soon

**Comment by nperez0111** [comment]
If you can figure out a way to not make this a breaking change, I'll happily accept that!

**Comment by benkroeger** [comment]
I was wondering why the build-tool doesn't tree-shake these dependencies.
I though it I wouldn't use the `BubbleMenu.vue` component, non of the related dependencies would end up in my final bundle.
