### ISSUE TITLE
[Bug]: Unable to queryselectorAll listitems 

### ISSUE THREAD

**Issue by shaileshiyer** [ueberdosis/tiptap#5003]
### Which packages did you experience the bug in?

core

### What Tiptap version are you using?

2.2.4

### What’s the bug you are facing?

if any one else also has weird query selectorAll bug with lists or is it just something specific to my build and setup that is breaking it. Since I am using tiptap inside the shadowDOM with lit-html and mobx.  Since selecting list items becomes a pain without being able to use the query selector.

```
// get a bullet list from your doc
const $bulletList = editor.$node('bulletList')

// get all listItems from your bulletList
// This query selector returns an empty array
const $listItems = $bulletList.querySelectorAll('listItem')

// get the last listItem
const $lastListItem = $listItems[0]
```

when I checked why the call was failing it turns out that because the bulletList is a block item it prevents access to the its children in the querySelector call.

### What browser are you using?

Edge

### What did you expect to happen?

Get a list of nodePositions for the list Items

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by aleversn** [comment]
Same here, it seems that only a few nodes like `paragraph`, and `codeBlock` can be found.

**Comment by shaileshiyer** [comment]
It seems like this bug was introduced with the feature to support block nodes. In 2.2.1 so rolling back the version to 2.2.0 fixed it. In case you are looking for a fix for it.

**Comment by needhourger** [comment]
querySelectorAll not support for custom node?
I defined my node using `Node.create(name:'break') `, however `editor.$doc.querySelectorAll('break')` always return empty array, and `querySelector('break')` return null
