### ISSUE TITLE
[Bug]: React DND broken when used within a NodeViewWrapper

### ISSUE THREAD

**Issue by johnsmithecon** [ueberdosis/tiptap#5018]
### Which packages did you experience the bug in?

@tiptap/react

### What Tiptap version are you using?

2.2.4

### What’s the bug you are facing?

`<NodeViewWrapper
      className="border p-4 shadow-lg rounded-lg bg-white"
      style={{ height: "500px" }}
    >
    <MyComponent />
</NodeViewWrapper>`

### What browser are you using?

Chrome

### What did you expect to happen?

When placing my custom react component (which includes react-dnd functionality) within tiptap, specifically a NodeViewWrapper, I expect the items to be draggable using react-dnd.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by Pruxis** [comment]
We had the same, I used https://dndkit.com. However it's having terrible side effects sometimes, I'd recommend to use https://github.com/atlassian/pragmatic-drag-and-drop

**Comment by nperez0111** [comment]
This is released with version: `2.11.0`
