### ISSUE TITLE
[Bug]: Not able to populate image on editor

### ISSUE THREAD

**Issue by paraslamsong** [ueberdosis/tiptap#5020]
### Which packages did you experience the bug in?

Image

### What Tiptap version are you using?

2.2.4

### What’s the bug you are facing?

```
  const editor = useEditor({
    extensions: editorExtensions,
    content: data?.content?? "",
    enablePasteRules: true,
    parseOptions: { preserveWhitespace: true },
    editorProps: {
      markViews: {},
    },
  });
```

Here I am pre populating editor with html, I am using base64 image, but while the html is rendering but any image on the content is not displaying. PS: There is also no img tag on html inspection

### What browser are you using?

Chrome

### What did you expect to happen?

I need to render all of the prepopulated data , including image and styling

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by henryStelle** [comment]
Does your `editorExtensions` include something like:

![image](https://github.com/ueberdosis/tiptap/assets/61335118/7ddfd919-fb6e-419d-92cc-3483877cf7dc)

Note: the allowBase64 is disabled by default.

**Comment by bdbch** [comment]
Could you please give us more information about your editor setup? As @henryStelle already pointed out base64 images should work fine. I'll close for now until more information is provided.

**Comment by uccmen** [comment]
what worked for me was I needed to set `allowInline: true` as well

```
Image.configure({ inline: true, allowBase64: true })
```
