### ISSUE TITLE
[Bug]: SelectAll in the new version of Google Chrome is disabled

### ISSUE THREAD

**Issue by wallace-yang** [ueberdosis/tiptap#5024]
### Which packages did you experience the bug in?

core

### What Tiptap version are you using?

2.1.12

### What’s the bug you are facing?

Today we received a lot of feedback from users, SelectionAll Function suddenly failed, after pressing ctrl a or commd a, user can see the blue style of selectionAll for a second, and then the style disappeared, and selectionAll function failed, there was no problem when using the old version of chrome, but there was a problem when upgrading to the latest version.Edge and Safari no problem, I reproduced this bug on the official taptip example, but didn't reproduced it on the official prosemirror example.
The images below are specific bug effects:
![recording](https://github.com/ueberdosis/tiptap/assets/45649432/3a9730d8-10df-49a1-a7b1-43f3c36a3bba)
Below is my windows10 chrome browser version(macos chrome is 123.0.6312.87):
![image](https://github.com/ueberdosis/tiptap/assets/45649432/2b2c992b-0131-4662-86c1-9af0ef20d33e)

### What browser are you using?

Chrome

### What did you expect to happen?

The select All function is normal

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
I can't reproduce this problem. Are you running any browser extensions that could lead to this issue?

https://github.com/ueberdosis/tiptap/assets/6538827/5f4d703c-2260-4903-ad11-e1a4d0a550ef

![image](https://github.com/ueberdosis/tiptap/assets/6538827/f6b95ec8-d240-4716-be83-b10cf85309eb)

I'll close for now - if you have any more information I'll reopen the issue.

**Comment by wallace-yang** [comment]
> I can't reproduce this problem. Are you running any browser extensions that could lead to this issue?
> 
>  Aufzeichnung.2024-04-06.172033.mp4 
> ![image](https://private-user-images.githubusercontent.com/6538827/320215347-f6b95ec8-d240-4716-be83-b10cf85309eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NTU3MDEsIm5iZiI6MTcxMjQ1NTQwMSwicGF0aCI6Ii82NTM4ODI3LzMyMDIxNTM0Ny1mNmI5NWVjOC1kMjQwLTQ3MTYtYmU4My1iMTBjZjg1MzA5ZWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDdUMDIwMzIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzllZmQyMDgyNWRjZTliNzYyZmI2MjM4NmU4YTFkNWZjZGNmYWFkYWYxZGUzMWIwYjlhMTBhYjFkZTBlNzE2MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1NlYMmiOwY2Zn1Wq4M-EAHCvNsTCaFXo8JZvwM9cx6U)
> 
> I'll close for now - if you have any more information I'll reopen the issue.

@bdbch It was the  browser extensions ’sider‘  caused the problem, thanks。

**Comment by bdbch** [comment]
Great, thanks for coming back and letting us know. 👍
