### ISSUE TITLE
[PRO]: AI selection not good

### ISSUE THREAD

**Issue by kbrin423** [ueberdosis/tiptap#5054]
### Which packages did you experience the bug in?

"@tiptap-pro/extension-ai": "^2.8.0"

### What Tiptap version are you using?

2.3.0

### What’s the bug you are facing?

Hi!
I use TitTap pro and I have a problem with pro extension  @tiptap-pro/extension-ai
I want use in my application and when select text in node and use  

props.editor.chain().focus(). AiFunction()

The function working but the initial selection is not good.

Same reaction online : https://tiptap.dev/docs/editor/ai/introduction

In your example :

**Rocking like a mobile?

Did you hear about the mobile phone that joined a rock band? Yeah, it was a real smartTONE! It rocked the stage with its gigabytes of rhythm and had everyone calling for an encore, but it couldn't resist the temptation to drop a few bars and left the audience in absolute silence. Turns out, it wasn't quite cut out for the music industry.

They say it's now pursuing a career in ringtone composition. Who knows, maybe one day it'll top the charts with its catchy melodies!**

If I select only «  **Yeah, it was a real smartTONE!** » and select Enrich with 🙂

Generate: 

**Rocking like a mobile?

Did you hear about the mobile phone that joined a rock band? 

Did you hear about the 📱 mobile phone that joined a 🎸 rock band? Yeah, it was a real smartTONE! It 🤘 rocked the stage with its gigabytes of rhythm and had everyone calling for an encore, but it couldn't resist the temptation to drop a few bars and left the audience in absolute silence. Turns out, it wasn't quite cut out for the 🎵 music industry.

It rocked the stage with its gigabytes of rhythm and had everyone calling for an encore, but it couldn't resist the temptation to drop a few bars and left the audience in absolute silence. Turns out, it wasn't quite cut out for the music industry.

They say it's now pursuing a career in ringtone composition. Who knows, maybe one day it'll top the charts with its catchy melodies!**

In the api i see all the node value

![Capture d’écran 2024-04-10 à 09 28 56](https://github.com/ueberdosis/tiptap/assets/9021128/baa8cb60-913f-4a34-8841-7f2a7b4e123b)

![Capture d’écran 2024-04-09 à 15 26 30](https://github.com/ueberdosis/tiptap/assets/9021128/8b2b2422-897a-412a-b067-04eae95087cf)

![Capture d’écran 2024-04-09 à 15 24 12](https://github.com/ueberdosis/tiptap/assets/9021128/49df2f0c-9cb2-4bd8-923b-2e424e750046)

Thx for your help!
Kévin Dev from Swello.

### What browser are you using?

Chrome

### What did you expect to happen?

 the expected result:
-> Did you hear about the mobile phone that joined a rock band?  Yeah, it was a real smartTONE 🧠🎶😎! It rocked the stage with its gigabytes of rhythm and had everyone calling for an encore, but it couldn't resist the temptation to drop a few bars and left the audience in absolute silence. Turns out, it wasn't quite cut out for the music industry.

They say it's now pursuing a career in ringtone composition. Who knows, maybe one day it'll top the charts with its catchy melodies!**

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by svenadlung** [comment]
Thx @kbrin423, we are aware of this and working on a bugfix.

**Comment by svenadlung** [comment]
@kbrin423 should be fixed in v2.8.1. Please give it a try. Thanks for your patience and the report 🙏

**Comment by kbrin423** [comment]
Thx @svenadlung great job! it works perfectly as expected 🙏🏻 😌
