### ISSUE TITLE
[Question] Decorate with component rather than class

### ISSUE THREAD

**Issue by hewIngram** [ueberdosis/tiptap#506]
Firstly - this is 100% a question and not an issue so apologies if this is the wrong place to ask.

I have a setup with tiptap where words that match certain parameters are highlighted (using decorators to add a specific class to them) which is lovely BUT I'd like them to also have a tooltip attached. Is there a way I can use a decorator to wrap a matching text node in a component rather than just adding a class to it?

Any idea super appreciated!

Thanks!

**Comment by shadrachtuck** [comment]
This might point you in the right direction.... [https://codesandbox.io/s/9x8fr](url)
