### ISSUE TITLE
[PRO]: Http 500: The registry appears to be down

### ISSUE THREAD

**Issue by chinnuu05** [ueberdosis/tiptap#5064]
### Which packages did you experience the bug in?

extension-emoji

### What Tiptap version are you using?

2.1.7

### What’s the bug you are facing?

I have my package manager set to use the private Tiptap registry along with my npmAuthToken, but I'm getting a 500 error that says "The registry appears to be down." The other pro extensions like TableOfContents install and work fine.

```
➤ YN0035: │ emoji-regex@npm:^10.0.0: The registry appears to be down (using a local cache might have protected you against such outages)
➤ YN0035: │   Response Code: 500 (Internal Server Error)
➤ YN0035: │   Request Method: GET
➤ YN0035: │   Request URL: https://registry.tiptap.dev/emoji-regex
➤ YN0035: │   Request Retry Count: 3 (can be increased via httpRetry)
➤ YN0000: └ Completed in 12s 772ms
➤ YN0000: · Failed with errors in 12s 793ms
```

### What browser are you using?

Chrome

### What did you expect to happen?

For the emoji extension to be installed correctly,  the other pro extensions like TableOfContents work fine

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by chinnuu05** [comment]
Never mind! My fault lol emoji-regex is on the public registry obviously

**Comment by junedali2614** [comment]
Can you please explain your solution?

**Comment by nperez0111** [comment]
Please follow the instructions here: https://cloud.tiptap.dev/pro-extensions

Specifically you likely have misconfigured where you should be pulling NPM extensions from, anything with `@tiptap-pro` as the namespace is our extension:

`@tiptap-pro:registry=https://registry.tiptap.dev/`
