### ISSUE TITLE
[Bug]: The active click area is limited to the top area of editor

### ISSUE THREAD

**Issue by TheBigK** [ueberdosis/tiptap#5068]
### Which packages did you experience the bug in?

core

### What Tiptap version are you using?

2.3

### What’s the bug you are facing?

Steps:
1. Go to: https://tiptap.dev/docs/editor/examples/default
2. Remove all the content from the editor
3. Now click outside the editor to remove the focus from editor (the blinking | should vanish from editor)
4. Move mouse cursor back inside the editor and click towards the bottom area. 

Expected: The editor should get into active mode and start showing the cursor blinking, where user can start typing.
Actual: Nothing happens. It's only when you click towards the top area of the editor that TipTap acknowledges the click and starts showing the pointer (indicating that editor is ready to accept input).

On my installation, I set the default height of the editor to about 96 pixels. When users click in the middle of the editor, nothing happens. Only when they click towards the top area of the editor that it becomes active. 

The user typically needs to click inside ~20 pixels from the top border to make the editor active. 

It's incredibly frustrating. 

### What browser are you using?

Chrome

### What did you expect to happen?

Expected: The editor should get into active mode and start showing the cursor blinking, where user can start typing.

### Anything to add? (optional)

None. All details have been added to the main post. 

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by codemzy** [comment]
In the docs the black border isn't the editor, it contains the editor (and the toolbar buttons). The editor is actually only this little blue highlighted bit.

---

<img width="846" alt="Screenshot 2024-04-19 at 14 24 46" src="https://github.com/ueberdosis/tiptap/assets/13764272/974a6141-e60f-44d6-9453-497cb6b836d8">

---

In the real world, if you make the actually editor bigger (say a min height of 200px or the view height) then clicking anywhere on the editor will trigger the cursor blinking.

---

<img width="1009" alt="Screenshot 2024-04-19 at 14 28 16" src="https://github.com/ueberdosis/tiptap/assets/13764272/84e15d50-a3bf-4e3d-8502-35aa4e26f6e0">

---

You can add a height in your CSS or [add a class to the editor](https://tiptap.dev/docs/editor/guide/styling#editor).

**Comment by zakwear** [comment]
You can also focus the editor when the user clicks somewhere on the wider canvas area.

**Comment by nperez0111** [comment]
Yea this is not an issue with our implementation, you can change the editor to whatever height you like, we left our editor be mostly default because we want to show that we are headless.

**Comment by doggan** [comment]
If anyone stumbles on this, I was able to implement the suggestion as such:

```
const handleContainerClick = () => {
  if (editor && !editor.isFocused) {
    editor.commands.focus('end')
  }
}

<div className={styles.contentWrapper} onClick={handleContainerClick}>
  <TipTapEditorContent editor={editor} />
</div>
```

There may be other ways but this worked well.

**Comment by QastanFIT** [comment]
For the tailwind people:

Add this to **<EditorContent />** className
` [&>div:first-child]:h-full [&>div:first-child>div:first-child]:h-full`

**Comment by jevakallio** [comment]
> For the tailwind people:
> 
> Add this to EditorContent className `[&>div:first-child]:h-full [&>div:first-child>div:first-child]:h-full`

This works, but a cleaner and less DOM-structure-dependent way to achieve this is to add the class to the Editor's `editorProps` as follows:

```ts
  const editor = useEditor({
    extensions,
    content,
    editorProps: {
      attributes: {
        class: "flex-1",
      },
    },
  });

  return <EditorContent editor={editor} className="flex-1" />;
  ```

**Comment by raves21** [comment]
> > For the tailwind people:
> > Add this to EditorContent className `[&>div:first-child]:h-full [&>div:first-child>div:first-child]:h-full`
> 
> This works, but a cleaner and less DOM-structure-dependent way to achieve this is to add the class to the Editor's `editorProps` as follows:
> 
> ```ts
>   const editor = useEditor({
>     extensions,
>     content,
>     editorProps: {
>       attributes: {
>         class: "flex-1 h-full",
>       },
>     },
>   });
> 
>   return <EditorContent editor={editor} className="flex-1 h-full" />;
> ```

thank you. This works like a charm.
