### ISSUE TITLE
Tiptap + Vuetify CSS

### ISSUE THREAD

**Issue by rogeralsing** [ueberdosis/tiptap#507]
**Is your feature request related to a problem? Please describe.**

I'm trying to use Tiptap together with Vuetify, and I see that the Vuetify styles are leaking through to the tiptap editor. e.g `v-application p` 

**Describe the solution you'd like**
I would like to load some predefined Tiptap styles which overrrides any styles defined outside of the component using Tiptap

**Describe alternatives you've considered**
Manually overriding the relevant Vuetify styles

**Comment by winhackger** [comment]
how to fix

**Comment by hopefeda** [comment]
+1

**Comment by hopefeda** [comment]
Meanwhile, there are other solutions:

1) Use tiptap-vuetify
2) Copy the css from tiptap-vuetify and apply them to your custom tiptap component

**Comment by brechtm** [comment]
This is just a warning to those who want to try and solve this using a [shadow DOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM). I tried this (and it worked) but ended up reverting it due to the limited support for shadow DOM even in recent browser versions.
