### ISSUE TITLE
[PRO]: `latestVersion` property does not exist in Collaboration History extension

### ISSUE THREAD

**Issue by soren121** [ueberdosis/tiptap#5107]
### Which packages did you experience the bug in?

extension-collaboration-history

### What Tiptap version are you using?

2.3.1

### What’s the bug you are facing?

On the documentation page for the Collaboration History extension, it refers to the `latestVersion` property in [storage](https://tiptap.dev/docs/editor/api/extensions/collaboration-history#storage) and in the [onUpdate callback](https://tiptap.dev/docs/editor/api/extensions/collaboration-history#get-version-update-data-and-save-it-into-a-variable).

However, the `latestVersion` property does not exist when using the extension. I'm assuming it may have been renamed to `version`, but that's not clear. I can't tell if this is a documentation error, or a mistake in the extension.

### What browser are you using?

Firefox

### What did you expect to happen?

The `latestVersion` property should be present in the extension storage and in the `onUpdate` callback data, as documented.

### Anything to add? (optional)

I'm using version 2.8.1 of `@tiptap-pro/extension-collaboration-history`, the latest as of writing.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [x] Yes, I’m a sponsor. 💖

**Comment by bdbch** [comment]
Hey @soren121 

I updated the documentation for the collab history extension. `latestVersion` in fact should exist on the extension storage. The only thing not correct was the `onUpdate` payload which does not have `latestVersion` but `version`.

I also added more missing storage values.
