### ISSUE TITLE
[Bug]: Not able to convert the tip-tap json to html using generateHTML on server-side

### ISSUE THREAD

**Issue by ayush-devrev** [ueberdosis/tiptap#5123]
### Which packages did you experience the bug in?

    "@tiptap/extension-link": "^2.3.1",     "@tiptap/pm": "^2.3.1",     "@tiptap/react": "^2.3.1",     "@tiptap/starter-kit": "^2.3.1",

### What Tiptap version are you using?

2.3.1

### What’s the bug you are facing?

Not able to convert the tip-tap json to html using generateHTML on server-side
![image](https://github.com/ueberdosis/tiptap/assets/115446072/234460e2-c816-4fd0-a350-50dfdb880c21)

### What browser are you using?

Chrome

### Code example

https://github.com/ayush-devrev/json-to-html

### What did you expect to happen?

Thought of getting a HTML in return.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

**Comment by dolbex** [comment]
Window isn't available on SSR. Node has no window

**Comment by ayush-devrev** [comment]
Yes, but it is coming as in the error you can see `src/pages/index.tsx`. Is there some packages that we should not be using? Like StarterKit or Link ?

**Comment by dolbex** [comment]
I'm using tiptap on the Nuxt / Vue side of things. Maybe wrap it in `if(process.client) { ... }` and have the client process it?

**Comment by ayush-devrev** [comment]
Can you try adding the Link extension which I have used in `src/pages/index.tsx` and see if it still works fine?

**Comment by nperez0111** [comment]
You are importing generateHTML from @tiptap/react when you need to import it from @tiptap/html like this demo: https://tiptap.dev/docs/editor/api/utilities/html#generate-html-from-json
