### ISSUE TITLE
Add onDelete event to mention plugin

### ISSUE THREAD

**Issue by nibytes** [ueberdosis/tiptap#515]
**Is your feature request related to a problem? Please describe.**
When delete mention, I need track what user was deleted(else what for we use id?) from post mentions, but I can't do it. If exist ready solution I will so glad. I researched extension code, and not found something what can help me.

**Comment by gjovanov** [comment]
Any plans to support this? Thanks.

**Comment by hanspagel** [comment]
Sorry for the silence here. I think that should be done in the backend. Extract all IDs when storing the content, checking if IDs are added or removed. Closing this here for now. ✌️
