### ISSUE TITLE
[Bug]: React Node Views are not rendered on the initial render, causing layout shift

### ISSUE THREAD

**Issue by Nantris** [ueberdosis/tiptap#5166]
### Affected Packages

@tiptap/react

### Version(s)

2.1.x (also 2.4.x)

### Bug Description

Upon the initial load the node view will not be rendered if it's a React node view. This causes a substantial and jarring layout shift

### Browser Used

Chrome

### Expected Behavior

There should be no delay rendering node views of any type.

### Additional Context

**This is a very significant polish problem** - the first impression is that the editor we spent a lot of time upgrading is worse than the old one due to this issue. First impressions matter.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by Nantris** [comment]
This could be worked around easily (by the maintainers, not end-developers) by providing an option to only render once things are truly ready to display.

**Comment by nperez0111** [comment]
I have some thoughts on how to improve this without resorting to flushSync, but need the time to implement it

**Comment by Nantris** [comment]
#5161 makes a huge difference in this issue.

It doesn't seem to fully resolve it, but it's so much better!

Great work @nperez0111!

**Comment by nperez0111** [comment]
I'm going to close this in favor of https://github.com/ueberdosis/tiptap/issues/4492

Which has a lot more details & approaches. I have a PR here that works but can be even faster: https://github.com/ueberdosis/tiptap/pull/5273
