### ISSUE TITLE
custom style does not preserve

### ISSUE THREAD

**Issue by vortechron** [ueberdosis/tiptap#518]
here is my html: 

`<p style="font-size:10px">Hello world</p>`

after assign it to editor on content attribute:

`<p>Hello world</p>`

**Comment by Jaromudr** [comment]
@vortechron 

you can extends original <tag> schema. Something like this:

```javascript
import { Image as TiptapImage } from 'tiptap-extensions'
import { sanitizeStyleAttr  } from 'vue-dashboard-ui/editor-extensions/sanitize'
import ImageView from 'vue-dashboard-ui/editor-extensions/ImageView.vue'

export default class Image extends TiptapImage {
  get schema() {
    return {
      inline: true,
      attrs: {
        src: {},
        alt: {
          default: null
        },
        title: {
          default: null
        },
        style: {
          default: null
        }
      },
      group: 'inline',
      parseDOM: [
        {
          tag: 'img[src]',
          getAttrs: dom => ({
            src: dom.getAttribute('src'),
            title: dom.getAttribute('title'),
            alt: dom.getAttribute('alt'),
            style: sanitizeStyleAttr(dom.getAttribute('style'))
          })
        }
      ],
      toDOM: node => ['img', node.attrs]
    }
  }

  get view() {
    return ImageView
  }
}
```

**Comment by vortechron** [comment]
what is the repo link for this? @Jaromudr

**Comment by Jaromudr** [comment]
@vortechron it's from private repo, but you can analize tiptap describe nodes in node/mark folders:

https://github.com/scrumpy/tiptap/blob/master/packages/tiptap-extensions/src/nodes/Image.js

**Comment by vortechron** [comment]
can i see santize file @Jaromudr

**Comment by Jaromudr** [comment]
@vortechron I will share it later

**Comment by Jaromudr** [comment]
@vortechron 
https://gist.github.com/Jaromudr/f46e6a08682291e6938965d6501d36e8.js

**Comment by vortechron** [comment]
@Jaromudr its not working. is there a way for me to do something like this?

`
new Editor({
     preserveStyles: true
})
`

**Comment by Jaromudr** [comment]
@vortechron I just a user, that used tiptap and customize it in a way to support style attribute. As I see from code, it does not support that, but you can customize it as I do, you need just dig deeper how Prose-mirror work. Tiptap is just an wrapper that add some useful functionality. It support only things that are described in schema. In my case I extend almost all Nodes and Marks to support style(and other) attributes.

**Comment by mlbanham** [comment]
I'm using CodeBlockHighlight and I need to extract html including the hljs classes - I tried building a custom subclass of CodeBlockHighlight based on the example above - no luck though. I ended up extracting raw html from the DOM with querySelector, which works OK but isn't in the spirit of things. Any suggestions or examples? Something like { preserveStyles: true } as suggested above would be pretty nice.

**Comment by hanspagel** [comment]
We see it as a feature that content gets cleaned up. If you want to keep certain styles it’s the best approach to allow them through custom nodes. ✌️

**Comment by newboy2006hosur** [comment]
> We see it as a feature that content gets cleaned up. If you want to keep certain styles it’s the best approach to allow them through custom nodes. ✌️

What do you mean by custom node? Can you provide example? All I want to do is preserve all `style` attribute in all the HTML elements being added. How can i do that? Why is that so complicated to do? I don't want to learn prosemirror just for that. It doesn't make sense. Even if you consider it a feature, how do I turn it off. Somebody help. This causing me so much stress.
