### ISSUE TITLE
[Bug]:Problems with bulletLists without content

### ISSUE THREAD

**Issue by Narias1999** [ueberdosis/tiptap#5205]
### Affected Packages

core

### Version(s)

2.0.0

### Bug Description

I've been experimenting with tiptap bulletlists and found this weird behavior.

If I lift a listItem that doesn't have content, it is also removing the bulletpoint from the previous listItem:

https://github.com/ueberdosis/tiptap/assets/24924906/1d8589e2-8d6b-4d24-a370-d8ae1e9f1bbd

Also If I try to replace a node of a listitem without content it gets the identation of the list:

https://github.com/ueberdosis/tiptap/assets/24924906/80658026-b312-4267-9aaa-321925b16696

Any workarounds for this?

### Browser Used

Chrome

### Expected Behavior

- If I lift a listItem without content it should just remove the indentation of that item, not remove the bulletpoint of the previous item.
- If a replace a bulletListItem without content for another node, it should remove the identation.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
We should be better about documenting it, but it is the list-keymap extension: https://embed.tiptap.dev/preview/Extensions/ListKeymap

Docs here: https://github.com/ueberdosis/tiptap/blob/7e7057ea43ce5b483ccc621a3f62bff79638ee1d/docs/api/extensions/list-keymap.md#L4-L5
