### ISSUE TITLE
[Bug]: Cannot start selection from collaborative cursor caret

### ISSUE THREAD

**Issue by SumitShrestha11** [ueberdosis/tiptap#5208]
### Affected Packages

@tiptap/extension-collaboration-cursor

### Version(s)

2.2.6

### Bug Description

It is not possible to select the content starting from collab cursor caret. It just causes the cursor to move to the new position rather than starting selection
![chrome-capture-2024-6-5](https://github.com/ueberdosis/tiptap/assets/46614425/2376e6bd-3be7-4cec-b097-5196d167049d)

### Browser Used

Chrome

### Expected Behavior

The selection should work as usual and it should be possible to start selection from collab cursor caret

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by jh-lee985** [comment]
Facing the same problem. Any solutions ?

**Comment by SumitShrestha11** [comment]
@jh-lee985 not yet did you find anything?

**Comment by nperez0111** [comment]
Could someone try this to see if it resolves it for them? https://github.com/ueberdosis/tiptap/pull/4646

**Comment by nperez0111** [comment]
This should be resolved now
