### ISSUE TITLE
[Documentation]: Your Documentation UX is very annoying

### ISSUE THREAD

**Issue by Sisableng** [ueberdosis/tiptap#5211]
### What’s the URL to the page you’re sending feedback for?

https://tiptap.dev/docs

### What part of the documentation needs improvement?

This is for sidebar menus, 

### What is helpful about that part?

Of course the sidebar is very helpful for navigational assistance in documentation

### What is hard to understand, missing or misleading?

but why do I have to switch pages just to see the child menu of the collapsible menu in the sidebar, it's very annoying in my opinion while your page speed takes 2 to 3 seconds to fully load in my country, I have no problem with the UI but please improvise more for the best User Experience.

![Screenshot (18)](https://github.com/ueberdosis/tiptap/assets/58748827/c3a9c797-736f-4796-8c74-284736902ab3)

### Anything to add? (optional)

look at this

https://github.com/ueberdosis/tiptap/assets/58748827/daa66160-69f7-41df-897a-c5b101456bde

my internet speed is 100Mb/s btw

**Comment by nperez0111** [comment]
Thank you for your feedback, we are actually in the middle of revamping our documentation. It takes some time to migrate so many files so we appreciate your patience while we are moving things around

**Comment by nperez0111** [comment]
Also, you are based in indonesia, there actually has been an internet line that has been causing significant packet loss, we are hosting in EU (where our team is) so that explains why it is so slow for you.

**Comment by Sisableng** [comment]
Yes you are right, I also think that EU and ASIA latency is too far away, I can't wait for the next surprise. Your project is amazing, I appreciate it.
