### ISSUE TITLE
[Bug]: bug in rendering double backslashes

### ISSUE THREAD

**Issue by Davron129** [ueberdosis/tiptap#5222]
### Affected Packages

react

### Version(s)

2.4.0

### Bug Description

After entering "\\" in editor it transforms it to double "\\", when passing this value as default value editor does not render anythinng instead of backslashes

### Browser Used

Chrome

### Expected Behavior

default value is: ".code\\\\with\\\\slash"
must render as : .code\with\slash

but it renders as: .codewithslash

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Can you send a codesandbox with the issue? I tried to reproduce it & I could not.
