### ISSUE TITLE
[Bug]: editor.setEditable doesn't update tabindex 

### ISSUE THREAD

**Issue by nazar-ch** [ueberdosis/tiptap#5231]
### Affected Packages

core

### Version(s)

latest

### Bug Description

Calling `editor.setEditable` doesn't affect `tabindex` attribute of the editor's container.

`tabindex` in managed by Tabindex core plugin which sets it only initially when the editor is created and doesn't update later.

The earlier issue:
https://github.com/ueberdosis/tiptap/issues/2458

The issue was fixed here: https://github.com/ueberdosis/tiptap/commit/01411f8462e8a36f96e56cdba227a9e5bb3e1812

The regression happened after: https://github.com/ueberdosis/tiptap/commit/1ebc8f8e1410ad7015ee01f2483561611ead5307#diff-8d15e2c2213d43ddfc416789f65ef8690bb3b5b7f01c7a24d296128647454312 (apparently in the attempt to fix the type error)

### Browser Used

Chrome

### Expected Behavior

`editor.setEditable(true)` sets `tabindex` to `0`
`editor.setEditable(false)` removes `tabindex`

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
I'll get this into a beta
