### ISSUE TITLE
[Bug]: Make the highlighted a blockquote

### ISSUE THREAD

**Issue by yana-norinskaya** [ueberdosis/tiptap#5233]
### Affected Packages

vue 3

### Version(s)

2.4.0

### Bug Description

Hello, help me please, I want to implement that only the highlighted text becomes a blockquote without using marks, so that it is a separate node

### Browser Used

Chrome

### Code Example URL

none

### Expected Behavior

I want to implement that only the highlighted text becomes a blockquote without using marks, so that it is a separate node

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Drop by our discord if you want help, much faster than going back and forth through github: https://tiptap.dev/discord
