### ISSUE TITLE
[Bug]: An aria-label or aria-labelledby prop is required for accessibility.

### ISSUE THREAD

**Issue by huilensolis** [ueberdosis/tiptap#5235]
### Affected Packages

starterkit

### Version(s)

2.4.0

### Bug Description

when creating lists with bullet points
```bash
- bullet point
```

the log appears on he console

### Browser Used

Chrome

### Expected Behavior

to make it more accessible for screen readers.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
I'm not able to reproduce this, is it still an issue?
