### ISSUE TITLE
Webpack error "non EcmaScript module"

### ISSUE THREAD

**Issue by joelpro2** [ueberdosis/tiptap#525]
**Describe the bug**
When i import tiptap-extensions, i get the errors listed below. i've checked your Code Sand Box with the packages im using and it works ok. There are any inconvenience in using ES6 + Babel?

Errors:

-  error  in ./node_modules/prosemirror-history/dist/index.mjs
Can't import the named export 'Mapping' from non EcmaScript module (only default export is available)

-  error  in ./node_modules/prosemirror-history/dist/index.mjs
Can't import the named export 'Plugin' from non EcmaScript module (only default export is available)

-  error  in ./node_modules/prosemirror-collab/dist/index.mjs
Can't import the named export 'Plugin' from non EcmaScript module (only default export is available)

-  error  in ./node_modules/prosemirror-history/dist/index.mjs
Can't import the named export 'PluginKey' from non EcmaScript module (only default export is available)

-  error  in ./node_modules/prosemirror-history/dist/index.mjs
Can't import the named export 'PluginKey' from non EcmaScript module (only default export is available)

-  error  in ./node_modules/prosemirror-collab/dist/index.mjs
Can't import the named export 'PluginKey' from non EcmaScript module (only default export is available)

-  error  in ./node_modules/prosemirror-collab/dist/index.mjs
Can't import the named export 'TextSelection' from non EcmaScript module (only default export is available)

-  error  in ./node_modules/prosemirror-collab/dist/index.mjs
Can't import the named export 'TextSelection' from non EcmaScript module (only default export is available)
**Screenshots**
![error](https://snipboard.io/8RgBbi.jpg)

**Environment**
 - OS: Windows 12
 - Browser chrome
 - Tiptap Version [1.26.4]
 - Tiptap-extensions Version [1.28.4]
 - Vue Version [2.6.10]
 - Vue CLI Version: [3.9.x]
 - Babel Version: [7.6.0]
 - Webpack Version: [4.33.0]

**Additional context**
```javascript
// babel.config.js
module.exports = {
  'presets': [
    [
      '@vue/app',
      {
        'useBuiltIns': 'entry'
      }
    ]
  ]
}
```

**Comment by joelpro2** [comment]
i guess that this is related with this issue
[prosemirror#1003](https://github.com/ProseMirror/prosemirror/issues/1003)

**Comment by funkfreakout** [comment]
Which version of `prosemirror-model` are you using as dependency for `tiptap-extensions`? It should be alright for version `1.8.2`

**Comment by joelpro2** [comment]
1.8.0

**Comment by funkfreakout** [comment]
Yes, that problem should be fix on the http://prosemirror.net/docs/changelog/. So, just make sure you update properly the dependency to version 1.8.2

**Comment by chkb** [comment]
Is it possible for the tip-tap project to lock the dependency versions in the package.json, it seems sort of unstable that sub-dependencies can break the build.

**Comment by chkb** [comment]
The issue was that prosemirror was trying to compole ES5 module, and was then using .mjs files instead of .js files, they have reverted this in their new commits.

https://github.com/ProseMirror/prosemirror-view/blob/master/CHANGELOG.md

**Comment by joelpro2** [comment]
@funkfreakout you should really lock the dependencies for your own version.

**Comment by funkfreakout** [comment]
@joelpro2 I do, but I guess if a problem in a particular version of the dependency is fixed in a new one, which only purpose is to fix that problem, the best option is to upgrade that dependency to the new one and manage your code so it can cope with those changes.

**Comment by chkb** [comment]
@funkfreakout this could be a recurring issue in the future, I would highly recommend to lock your package dependencies, and only use tested versions of your dependencies.

Seems like you have a CI/CD pipeline that can upgrade the sub packages, to newest version without testing the packages compatibility.

I'v submitted a pull-request to lock the dependency versions in package.json files, in the following folders:
- tiptap
- tiptap-commands
- tiptap-extensions
- tiptap-utils

The PR is here:
https://github.com/scrumpy/tiptap/pulls

Please take this into consideration.

**Comment by joelpro2** [comment]
btw, but not related to this bug (just a question), is it possible to apply css properties like color and save as JSON?

**Comment by joelpro2** [comment]
@iliyaZelenko
