### ISSUE TITLE
[Bug]: Text align is applied to a single paragraph only

### ISSUE THREAD

**Issue by svilen-ivanov-kubit** [ueberdosis/tiptap#5254]
### Affected Packages

core, extension-text-align

### Version(s)

2.5.0-beta.4

### Bug Description

If you select several paragraphs and apply an alignment, only one paragraph is updated. Here is an example from https://tiptap.dev/docs/editor/api/extensions/text-align

https://github.com/ueberdosis/tiptap/assets/92510182/387b6c8b-eb92-4e69-9d55-52038d20295b

See how _first paragraph_ never aligns.

The problem is not reproducible with 2.4.0. I was able to track the problem to a recent change of the `updateAttributes` command: https://github.com/ueberdosis/tiptap/pull/5154

### Browser Used

Chrome

### Expected Behavior

All paragraphs should align.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
I've reverted this change for now. I could not spend the time at the moment to fix the original bug

**Comment by nperez0111** [comment]
Ok, releeasing that with https://github.com/ueberdosis/tiptap/releases/tag/v2.5.0-beta.5
