### ISSUE TITLE
[Bug]: Bubble Menu Not Working with Collaboration Extension

### ISSUE THREAD

**Issue by jh-lee985** [ueberdosis/tiptap#5259]
### Affected Packages

Bubble menu

### Version(s)

2.4.0

### Bug Description

We encountered an issue where the Bubble Menu extension, which previously worked fine alongside the Collaboration extension, is no longer functioning after updating all dependencies. The Bubble Menu works correctly when the Collaboration extension is not included, but fails to work when Collaboration is enabled. No errors are indicated.

We discovered that the Bubble Menu plugin gets removed during the execution of the updatePluginViews function in prosemirror-view/dist/index.js. Specifically, in the y-prosemirror/src/plugins/sync phase, the length of this.state.plugins decreases from 76 (including Bubble Menu) to 75, effectively removing the Bubble Menu plugin.

Below is the basic code from the Tiptap example, which replicates the issue:

```js
<template>
  <div class="container">
    <div class="control-group">
      <label>
        <input type="checkbox" :checked="isEditable" @change="() => (isEditable = !isEditable)" />
        Editable
      </label>
    </div>
    <bubble-menu :editor="editor" :tippy-options="{ duration: 100 }" v-if="editor">
      <div class="bubble-menu">
        <button @click="editor.chain().focus().toggleBold().run()" :class="{ 'is-active': editor.isActive('bold') }">
          Bold
        </button>
        <button
          @click="editor.chain().focus().toggleItalic().run()"
          :class="{ 'is-active': editor.isActive('italic') }"
        >
          Italic
        </button>
        <button
          @click="editor.chain().focus().toggleStrike().run()"
          :class="{ 'is-active': editor.isActive('strike') }"
        >
          Strike
        </button>
      </div>
    </bubble-menu>
    <editor-content :editor="editor" />
  </div>
</template>
<script>
import StarterKit from '@tiptap/starter-kit';
import { BubbleMenu, Editor, EditorContent } from '@tiptap/vue-3';
import Collaboration from '@tiptap/extension-collaboration';
import * as Y from 'yjs';
export default {
  components: {
    EditorContent,
    BubbleMenu
  },
  data() {
    return {
      editor: null,
      isEditable: true
    };
  },
  watch: {
    isEditable(value) {
      this.editor.setEditable(value);
    }
  },
  mounted() {
    this.editor = new Editor({
      extensions: [
        StarterKit,
        Collaboration.configure({
          document: new Y.Doc()
        })
      ],
      content: `
        <p>
          Hey, try to select some text here. There will popup a menu for selecting some inline styles. Remember: you have full control about content and styling of this menu.
        </p>
      `
    });
  },
  beforeUnmount() {
    this.editor.destroy();
  }
};
</script>
```
![image](https://github.com/ueberdosis/tiptap/assets/126759216/798049ab-c887-463e-b355-dcceeeff2515)

### Browser Used

Chrome

### Expected Behavior

Bubble menu working with collaboration extension

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by exinnocommon** [comment]
I'm struggling with the same issue.

**Comment by neaumusic** [comment]
Having a similar issue where the BubbleMenu is breaking hot reload with create-react-app 5 (the latest). We do have collab, but I've mostly disabled it for my own local development, so I'm not sure that's the root cause. 
[bubble-menu-hot-reload-stack-trace.txt](https://github.com/user-attachments/files/15971359/bubble-menu-hot-reload-stack-trace.txt)

**Comment by jh-lee985** [comment]
We solved the problem by wrapping the bubble menu in a div tag with a specific class. This class is then assigned as an element property in the BubbleMenu extension.

Something like this 

```js
Component = 
<div class="bubble-menu">
 <bubble-menu
      :editor="editor"
      :tippy-options="{ duration: 100 }"
      v-if="editor"
    >
        <button @click="editor.chain().focus().toggleBold().run()" :class="{ 'is-active': editor.isActive('bold') }">
          Bold
        </button>
    </bubble-menu>
 </div>

extension = 
 BubbleMenu.configure({
      element: document.querySelector('.bubble-menu'),
    }),
```

**Comment by nperez0111** [comment]
Could this be because it is vue and related to this https://github.com/ueberdosis/tiptap/pull/5252 🤔

**Comment by neaumusic** [comment]
https://github.com/ueberdosis/tiptap/issues/4619#issuecomment-1869042861

this may be unrelated, but this solved my issue -- move the `<EditorContent/>` after all `<BubbleMenu/>` components

**Comment by tuanalumi** [comment]
> move the <EditorContent/> after all <BubbleMenu/> components

I've done this but it still doesn't work.

**Comment by nperez0111** [comment]
I believe it is more likely to do with it being within an actual div rather than a react fragment

**Comment by joshuakarloclaudio** [comment]
I'm also encountering a related issue where bubble menus aren't working properly with the Collaboration extension. The bubble menus are always visible regardless of the condition I set in the `shouldShow` prop. Also, they are displayed above the editor instead of following the cursor.

As soon as I remove the Collaboration extension, the bubble menus work as expected.

**Comment by nperez0111** [comment]
Can someone make a code sandbox for this then?

**Comment by lana-k** [comment]
I created a sandbox: https://codesandbox.io/p/sandbox/tiptap-issue-template-forked-rm83nw?file=%2Fsrc%2Fmain.js%3A4%2C15

When collaboration extention is not provided the menu is shown correctly:
![image](https://github.com/user-attachments/assets/d2f18c82-7126-4e5e-beee-1b823f0a013f)
When the collaboration is used, the menu is always displayed above the editor:
![image](https://github.com/user-attachments/assets/3c557648-a873-4b44-bc1f-7723bda1815b)

**Comment by alexigasse** [comment]
I'm facing the same issue and noticed that [`editor.registerPlugin`](https://github.com/ueberdosis/tiptap/blob/cf2067906f506486c6613f872be8b1fd318526c9/packages/vue-3/src/BubbleMenu.ts#L53) dosent trigger the plugin view update when using the Collaboration extension.

Here's a test plugin: when using the Collaboration extension, `console.log('update')` is never executed if the plugin is registered via `editor.registerPlugin`. However, it works fine if the plugin is registered through an Extension’s `addProseMirrorPlugins`.
```ts
import { Plugin, PluginKey } from '@tiptap/pm/state'

editor.registerPlugin(new Plugin({
  key: new PluginKey('test'),
  view: view => ({
    update: () => {
      console.log('update')
    },
  }),
}))
```

**Comment by michaeldeprospo** [comment]
I have been experiencing this as well for some time now as well.

**Comment by volarname** [comment]
same issue here
the bubble appear always or never and should-show prop callback is never called
its there from 2.4.0 and still not fixed, thats weird

**Comment by Oui-Dev** [comment]
Same issue here :
vue@3.4.38
tiptap@2.6.6

**Comment by ccarner** [comment]
Same here
vue 3.4.38

**Comment by kadiryazici** [comment]
As a tiptap-pro user this issue is preventing us to go to production.

**Comment by marforon** [comment]
same here 😟

**Comment by praznovskymartin** [comment]
Same here. Please is there any estimate on the fix?

**Comment by igorillask** [comment]
Hi, this bug is blocking our production launch. Please prioritize a fix as soon as possible.

**Comment by cjhsyc** [comment]
I temporarily solved this problem by setting `"y-prosemirror": "1.2.3"`

**Comment by svenadlung** [comment]
Sorry for the silence. We are checking, but it might take some time. It seems that the issue occurs due to changes made in `y-prosemirror` versions 1.2.4 and 1.2.5. I can confirm that the issue is present in Vue (only).

@nperez0111, it doesn't seem to be related to any recent changes in Vue on our side. I tried with Tiptap 2.0.0, and the same issue occurs.

> [editor.registerPlugin](https://github.com/ueberdosis/tiptap/blob/cf2067906f506486c6613f872be8b1fd318526c9/packages/vue-3/src/BubbleMenu.ts#L53) doesn't trigger the plugin view update

I can confirm what @alexigasse wrote; it concerns plugins registered late via `registerPlugin`. The same issue is happening with the FloatingMenu.

**Comment by kobrynovych** [comment]
is there a way to fix it?

**Comment by nperez0111** [comment]
2.7.2 resolves this issue

**Comment by kobrynovych** [comment]
thanks it works

maybe it's not related to this, but when I switch between documents it stops working. Only works the first time when the page is reloaded.

when changing the document, I change the pluginKey and it does not help


Vue3

```
        <bubble-menu
            v-if="editor"
            :pluginKey="`bubbleMenuLink${docId}`"
            :tippy-options="{ appendTo: () => $refs[`editorContentRef${docId}`], }"
            :editor="editor"
            :shouldShow="({ editor, view, state, oldState, from, to }) => {
                return from === to && editor.isActive('link');
            }"
        >
            <button>
                edit
            </button>
        </bubble-menu>
        
        
        
    import { Editor, EditorContent, BubbleMenu } from '@tiptap/vue-3';
    import StarterKit from '@tiptap/starter-kit';
    import Collaboration from '@tiptap/extension-collaboration'
    import * as Y from 'yjs'
    import { TiptapCollabProvider } from '@hocuspocus/provider'
  
    let ydoc = null
    let provider = null
    
         data() {
            return {
                editor: null,
            }
        },
        
        
         watch: {
            docId: {
                handler(value, prevValue) {
                    if (value !== prevValue) {
                        this.docIdData = value
                        ydoc?.destroy()
                        ydoc = null
                        provider?.off('synced', this.onProviderSynced)
                        provider?.off('status', this.onProviderStatus)
                        provider?.unwatchThreads(this.onUpdateThreads)
                        provider?.destroy()
                        provider = null
                        this.editor?.destroy()
                        this.editor = null
                        this.initEditor()
                    }
                },
            },
        },
        
        methods: {
           initEditor() {
                ydoc = new Y.Doc()

                provider = new TiptapCollabProvider({
                    name: `${this.docId}`,
                    appId: appId,
                    token: token,
                    document: ydoc,
                })

                provider.on('synced', this.onProviderSynced)
                provider.on('status', this.onProviderStatus)
                provider.watchThreads(this.onUpdateThreads)

                this.editor = new Editor({
                    extensions: [
                        StarterKit.configure({
                            history: false,
                        }),
                        Collaboration.configure({
                            document: ydoc,
                        }),
                        Link.configure({
                            openOnClick: false,
                        }),
                        Typography,
                        ...
                    ],
                })
            },
          },
       },
```

**Comment by tuanalumi** [comment]
I got this after upgrading to 2.7.2: https://github.com/ueberdosis/tiptap/issues/5632

**Comment by kobrynovych** [comment]
@mouricef  when I switch documents I hide the bubble-menu and after opening a new document I show the bubble-menu again and it is as if it is reinstalled

I also had several bubble-menus and I combined them all into one and already in the middle I set the condition which menu to show to the user

**Comment by abecirovic3** [comment]
Is it possible that this still might be reproducable? I'm still facing this issue, but I'm not sure what might be the cause. In my project where I'm developing the RTE I have a wrapper app and the bubble menus render fine. But when I install the package in my production app the menus are missing. If I inspect the HTML I can see the tippy is being rendered but the tippy-content div is empty.

```json
"peerDependencies": {
    "@angular/common": ">=19.0.0",
    "@angular/core": ">=19.0.0",
    "@hocuspocus/provider": "^2.15.2",
    "@tiptap-pro/extension-file-handler": "^2.17.5",
    "@tiptap-pro/extension-unique-id": "^2.17.5",
    "@tiptap/extension-bubble-menu": "^2.11.5",
    "@tiptap/extension-code-block-lowlight": "^2.11.5",
    "@tiptap/extension-collaboration": "^2.11.5",
    "@tiptap/extension-collaboration-cursor": "^2.11.5",
    "@tiptap/extension-color": "^2.11.5",
    "@tiptap/extension-dropcursor": "^2.11.5",
    "@tiptap/extension-highlight": "^2.11.5",
    "@tiptap/extension-link": "^2.11.5",
    "@tiptap/extension-placeholder": "^2.11.5",
    "@tiptap/extension-subscript": "^2.11.5",
    "@tiptap/extension-superscript": "^2.11.5",
    "@tiptap/extension-table": "^2.11.5",
    "@tiptap/extension-table-cell": "^2.11.5",
    "@tiptap/extension-table-header": "^2.11.5",
    "@tiptap/extension-table-row": "^2.11.5",
    "@tiptap/extension-text-align": "^2.11.5",
    "@tiptap/extension-text-style": "^2.2.4",
    "@tiptap/extension-underline": "^2.11.5",
    "@tiptap/pm": "^2.2.4",
    "@tiptap/starter-kit": "^2.11.5",
    "@types/katex": "^0.16.7",
    "@types/markdown-it": "^14.1.2",
    "@types/uuid": "^9.0.5",
    "katex": "^0.16.9",
    "lottie-web": "^5.12.2",
    "lowlight": "^3.1.0",
    "markdown-it": "^14.1.0",
    "ngx-lottie": "^11.0.2",
    "ngx-scrollbar": "^13.0.3",
    "ngx-tiptap": "^12.0.0",
    "uuid": "^9.0.1",
    "y-prosemirror": "^1.2.17",
    "yjs": "^13.6.24"
  },
```
