### ISSUE TITLE
[Bug]: TypeError: this.options.provider.createThread is not a function (Comment plugin with Hocuspocus)

### ISSUE THREAD

**Issue by AiltonApis** [ueberdosis/tiptap#5260]
### Affected Packages

Vue, @hocuspocus/provider, @tiptap-pro/extension-comments

### Version(s)

"@tiptap-pro/extension-comments": "^2.8.9"; @hocuspocus/common@2.13.2 @hocuspocus/provider@2.13.2

### Bug Description

Hello, dear ones!

I'm trying to use the TipTap comments extension in my application that uses Hocupocus as a provider; however, when I try to apply the setThread command the error below appears:
@tiptap-pro/extension-comments (first screenshoot).
From what I'm seeing, it's not a configuration flaw, because when I expand the commands that my TipTap editor instance has, the basic comment plugin commands appear.
Versions: "@tiptap-pro/extension-comments": "^2.8.9"; @hocuspocus/common@2.13.2
@hocuspocus/provider@2.13.2
"@tiptap/vue-3": "^2.0.0-beta.205",

I've tried add manually this createThread into provider, however is barely runs.

Could you tell me what it could be?

![image](https://github.com/ueberdosis/tiptap/assets/101409366/8bce316f-bc1d-4a7b-8af1-e76e13a92479)
![image](https://github.com/ueberdosis/tiptap/assets/101409366/4d0c04e1-2da6-40d2-9f5a-4bb17ecd3607)

### Browser Used

Chrome

### Expected Behavior

The extesion Comment pro runs.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by guarmo** [comment]
The `setThread` command, which you’re trying to use, currently only works with `@tiptap/collab-provider`, not Hocuspocus. So even though your setup recognizes the comment commands, Hocuspocus doesn’t fully support the actions needed for `setThread` to function properly.
