### ISSUE TITLE
[Bug]: `RangeError: Schema is missing its top node type ('doc')` with umijs

### ISSUE THREAD

**Issue by Redish101** [ueberdosis/tiptap#5262]
### Affected Packages

@tiptap/react

### Version(s)

2.4.0

### Bug Description

I am trying to use tiptap in a umijs project,but it threw `RangeError: Schema is missing its top node type ('doc')`,and this is my code:
```tsx
// components/MarkdownEditor.tsx
import { useEditor, EditorContent } from '@tiptap/react'

const MarkdownEditor = () => {
    const editor = useEditor()
    
    return (
        <EditorContent editor={editor} />
    )
}

export default MarkdownEditor

// page/article/create.tsx
import { PageContainer } from "@ant-design/pro-components"
import MarkdownEditor from "@/components/MarkdownEditor"

const CreateArticlePage = () => {
  return (
    <PageContainer 
      title="Create Article"
    >
      <MarkdownEditor />
    </PageContainer>
  )
}

export default CreateArticlePage
```

### Browser Used

Chrome

### Expected Behavior

I want to use tiptap with umijs.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
useEditor needs extensions installed to function. You provided none. Please read the docs: https://tiptap.dev/docs/editor/getting-started/install/react#integrate-tiptap
