### ISSUE TITLE
[Bug]: Adding different instances of a keyed plugin (plugin$)

### ISSUE THREAD

**Issue by kailiming** [ueberdosis/tiptap#5267]
### Affected Packages

"nuxt-tiptap-editor": "^1.1.2",    "@tiptap/core": "^2.4.0",    "@tiptap/pm": "^2.4.0",

### Version(s)

1.1.2

### Bug Description

**I introduced a custom extension in Nuxt and an exception occurred. Even after I removed it, I couldn't recover. I had to delete the node_modules folder and run pnpm again.**

```js
import { Extension } from '@tiptap/core'
import { Plugin, PluginKey } from '@tiptap/pm/state'

export default Extension.create({
  name: 'eventHandler',

  addProseMirrorPlugins() {
    return [
      new Plugin({  
        key: new PluginKey('eventHandler'),
        
        props: {
          handleClick(view, pos, event) { /* … */ },
          handleDoubleClick(view, pos, event) { /* … */ },
          handlePaste(view, event, slice) { /* … */ },
        },
      }),
    ]
  },
})
```

### Browser Used

Chrome

### Expected Behavior

![image](https://github.com/ueberdosis/tiptap/assets/128564436/2e9e0d58-828a-4a73-b364-bff7402af0ca)

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by kashanghori** [comment]
if you're using History extension then that is also causing the error ,  check this out https://github.com/ueberdosis/tiptap/issues/4704#issuecomment-2188421060

**Comment by nperez0111** [comment]
If deleting your node_modules resolved it then it is not an issue with tiptap, your package manager had two versions of the same deps.
