### ISSUE TITLE
[Bug]: CharacterCount extension cannot count surrogate pairs correctly

### ISSUE THREAD

**Issue by s7tya** [ueberdosis/tiptap#5286]
### Affected Packages

CharacterCount extension

### Version(s)

2.4.0

### Bug Description

The CharacterCount extension cannot count surrogate pairs correctly. For example, 🍎 is counted as a length of 2, and 👨‍👩‍👦 is counted as a length of 8. This issue is not limited to emojis; Japanese Kanji characters, such as "𩸽," also use surrogate pairs.

### Browser Used

Chrome

### Expected Behavior

🍎 and 👨‍👩‍👦,  "𩸽" should be counted as 1. 

### Additional Context (Optional)

The CharacterCount extension uses `String.prototype.length` to count the length of text. However, `String.prototype.length` does not correctly handle surrogate pairs. For example, 🍎 is counted as a length of 2, and 👨‍👩‍👦 is counted as a length of 8.

https://github.com/ueberdosis/tiptap/blob/dbc0f0941493d16a374097d3652ff098a318e985/packages/extension-character-count/src/character-count.ts#L67

To address this issue, there should be an option to change the counting algorithm. Alternatively, `[...text].length` or [Intl.Segmenter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter) could be used for more accurate character counting. Although the spread syntax does not cover all situations, it is a good starting point.

https://developer.mozilla.org/en-US/play?id=7D1pwj3fDAQdeXinZq57ELqG1euVlLGeRvz07OCWBdQj11sIeI9OIw7Z2ksc%2BBnpZTEs51%2BcU0pTWro2

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by xiaweiss** [comment]
```javascript
[...text]

// result  length 5
['👨', '‍', '👩', '‍', '👦']
```

**Comment by s7tya** [comment]
> To address this issue, there should be an option to change the counting algorithm. Alternatively, [...text].length or [Intl.Segmenter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter) could be used for more accurate character counting. **Although the spread syntax does not cover all situations, it is a good starting point.**

**Comment by s7tya** [comment]
Alright! Thank you so much. I'll send PR in a few days.

**Comment by nperez0111** [comment]
We made a new option in Tiptap v2.8.0 for configuring this

**Comment by s7tya** [comment]
Ah, nice. Thanks.
