### ISSUE TITLE
[PRO]: Fonts are cleared on enter press when Unique Ids are on

### ISSUE THREAD

**Issue by EricHasegawa** [ueberdosis/tiptap#5293]
### Affected Packages

extension-unique-ids, extension-font-family

### Version(s)

All versions of Unique ID/font family

### Description of the Bug

If I have the Unique ID extension and the Font family extension, when I have a font set and press enter, the font gets cleared (as do other styles it seems)

### Browser Used

Chrome

### Code Example (Preferred)

Can't since its a private registry

### Expected Behavior

Press enter when a font is applied; font remains applied

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by gowreesh369** [comment]
Is this issue open? Can I take it?

**Comment by nperez0111** [comment]
Hi @EricHasegawa I would need a bit more information & perhaps a reproduction to understand what could be happening here better.

Given that it works in our Next.js block editor (https://templates.tiptap.dev) I wouldn't think that this is an inherent incompatibility of the two extensions, but some sort of an integration issue.

Ideally a reproduction repo would be the quickest way to debug the issue, but if you want to have a chat, drop by our discord
https://tiptap.dev/discord

**Comment by nperez0111** [comment]
I believe we have resolved this, please let me know if you still have an issue
