### ISSUE TITLE
[Bug]: getTextContentFromNodes not handling atoms correctly

### ISSUE THREAD

**Issue by artursvonda** [ueberdosis/tiptap#5298]
### Affected Packages

core

### Version(s)

2.4.0

### Bug Description

When using input rules on content that contains atoms (like mentions), the content of the node may be longer than 1 char which causes the `getTextContentFromNodes` to calculate position / length incorrectly.
That's mitigated by returning single char from `renderText`, but it also means copy/paste is not working properly.

### Browser Used

Chrome

### Expected Behavior

Atom content should be included in full. Or we need to change how we get content for atoms.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Should be resolved now
