### ISSUE TITLE
[PRO]: transaction.steps always empty in on("transaction") handler since TableOfContents added

### ISSUE THREAD

**Issue by guillaumeguirriec** [ueberdosis/tiptap#5299]
### Affected Packages

@tiptap-pro/extension-table-of-contents

### Version(s)

2.9.1

### Description of the Bug

I added the pro extension `TableOfContents` to my setup and since then the `transaction.steps` array is always empty in my `.on("transaction", ...)` handler. I tried to only keep the `StarterKit` and `TableOfContents` extensions but the issue is still there. Also, I tried on different web browsers. 

### Browser Used

Other

### Expected Behavior

`transaction.steps` array should not be empty. 

### Additional Context (Optional)

My setup:

```
export const TiptapExtensionsKit = [
  StarterKit.configure({
    heading: {
      levels: [1, 2, 3],
    },
    horizontalRule: false,
    codeBlock: false,
    strike: false,
    code: false,
  }),
  Placeholder.configure({
    placeholder: "Type / to browse options",
  }),
  Highlight,
  Image,
  Subscript,
  Superscript,
  Table.configure({
    resizable: true,
  }),
  TableCell,
  TableHeader,
  TableRow,
  TableOfContents,
];
```

```
const editor = useEditor({
    extensions: ExtensionsKit,
    content: "",
    autofocus: true,
    injectCSS: false,
    editable: isEditOn,
  });
```

```
const onTransactionHandlerAsync = useCallback(
    async ({
      editor: updatedEditor,
      transaction,
    }: {
      editor: TiptapEditor;
      transaction: Transaction;
    }) => {
      if (transaction.steps.length > 0) {
        await onContentChangeAsync(JSON.stringify(updatedEditor.getJSON()));
      }
    },
    [onContentChangeAsync]
  );

  const debouncedOnTransactionHandlerAsync = useMemo(
    () =>
      debounce(onTransactionHandlerAsync, GeneralConstants.DEFAULT_MS_DELAY),
    [onTransactionHandlerAsync]
  );

  useEffect(() => {
    if (!editor) return;

    editor.on("transaction", debouncedOnTransactionHandlerAsync);
  }, [editor, debouncedOnTransactionHandlerAsync]);
```

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
@guillaumeguirriec I cannot reproduce this issue with your provided code. I added this to our demo and everything worked just fine (where it only shows transaction steps if the content is actually modified):

```ts
  useEffect(() => {
    if (!editor) { return }

    editor.on('transaction', ({ transaction }) => {
      console.log(transaction, transaction.steps)
    })
  }, [editor])
```

Side note: this seems to be a proxy for firing when the the document has actually been modified. This is exactly what `editor.on('update'` event is for and is even accessible on the useEditor as `useEditor({onUpdate:()=>{}})`

I saw in your code that you named your extensions variable slightly differently perhaps that is the issue:
>    extensions: ExtensionsKit,
vs.
> export const TiptapExtensionsKit = [

**Comment by nperez0111** [comment]
Actually looking at your code again, you are debouncing (thereby dropping events) before actually checking if the transaction has any steps. Definitely an integration issue on yourside. You can either use the update event (recommended) or refactor your code to check for the steps _before_ initiating the debounce (debouncing the save function not the if statement).

Definitely nothing in the table of contents extension would affect this

**Comment by guillaumeguirriec** [comment]
Indeed, debouncing was the mistake. Thank you for you help. Great lib' 🫡
