### ISSUE TITLE
Binding custom action on Enter key

### ISSUE THREAD

**Issue by loganleatch** [ueberdosis/tiptap#530]
After looking through the docs (and the ProseMirror docs) I can't seem to find a clear answer on how to override the behaviour of the Enter key (or any other specific key for that matter). Is there a simple way to handle this?

Cheers.

**Comment by Bojoofu** [comment]
I had the same issue and was able to perform a custom action on enter using the following 

https://github.com/iliyaZelenko/tiptap-vuetify/issues/100#issuecomment-557947715
