### ISSUE TITLE
[PRO]: Streaming for AI Write command

### ISSUE THREAD

**Issue by heymartinadams** [ueberdosis/tiptap#5301]
### Affected Packages

extension-ai

### Version(s)

2.9.2

### Description of the Bug

For some reason, when selecting **AI Writer**, the results don’t get streamed.

https://github.com/ueberdosis/tiptap/assets/11673745/ae339847-108c-4786-a747-7a74ba2c6efc

### Browser Used

Chrome

### Expected Behavior

I’m assuming it will stream, not load and then print the output all at once.

### Additional Context (Optional)

I’ve added `stream: true` to the codebase, but nothing changed:

```ts
export const AiWriter = Node.create({
	name: 'aiWriter',
...
	addOptions() {
		return {
			authorId: undefined,
			authorName: undefined,
			HTMLAttributes: {
				class: `node-${this.name}`
			},
			stream: true // ← Added this
		}
	},
...
})
```

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Streaming is a new feature so it is only available in the latest versions of `@tiptap-pro/extension-ai@2.9.1` and higher. Can you confirm what version you are using?

This looks like the tiptap template, which we have not gotten around to integrating just yet.

**Comment by nperez0111** [comment]
It also is not an option that would go on the AiWriter instance. It would be part of a text command that executes the AI op

**Comment by heymartinadams** [comment]
Using `2.9.2`.

**Comment by heymartinadams** [comment]
> It also is not an option that would go on the AiWriter instance. It would be part of a text command that executes the AI op

@nperez0111, how would I modify this text command to get it to stream?

**Comment by nperez0111** [comment]
We have not updated that example since it actually goes around using the ai extension. But you can see the docs for the ai extension here: https://tiptap.dev/docs/content-ai/capabilities/text-generation/built-in-commands

Particularly this demo will probably be the most useful: https://tiptap.dev/docs/content-ai/capabilities/text-generation/format

**Comment by nperez0111** [comment]
This is resolved on the templates repo
