### ISSUE TITLE
[Bug]: Markdown content not rendering correctly

### ISSUE THREAD

**Issue by noble-varghese** [ueberdosis/tiptap#5303]
### Affected Packages

2.3.0

### Version(s)

2.3.0

### Bug Description

I'm using a paid TipTap editor, but it doesn't support rendering markdown content properly. We're sending custom text from the backend that needs to be rendered on the frontend. However, the `/n` and `###` markdown syntax doesn't render correctly, forcing us to use third-party or in-house parsers. This is an inconvenient approach. Is there an alternative solution?

### Browser Used

Chrome

### Expected Behavior

The expected behavior is to have line breaks for `\n`. Instead here I have to manually add `<br>` tags in the text.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Markdown is explicitly not supported by Tiptap: https://tiptap.dev/docs/guides/output-json-html#markdown-not-an-option

You can parse your markdown into HTML and use that if you like. But JSON is going to be the best format for persistence

There are third party extensions for markdown support, but they essentially add up to adding markdown parser to the editor like: https://github.com/aguingand/tiptap-markdown
