### ISSUE TITLE
[Bug]: Multiple tags of same type being incorrectly merged

### ISSUE THREAD

**Issue by KieranP** [ueberdosis/tiptap#5317]
### Affected Packages

core

### Version(s)

2.4.0

### Bug Description

When loading in HTML thats contains nested tags of the same type (namely span), they are being incorrectly merged together.

e.g.

```html
<span style="color: red;">
  <span style="font-size: 12px;">
    Hello
  </span>
</span>
```

is being converted by Tiptap into:

```html
<span style="font-size: 12px;">Hello</span>
```

(note the color is dropped, only the most recent span is preserved)

### Browser Used

Chrome

### Code Example URL

https://codesandbox.io/p/sandbox/elastic-joana-d6pgnj

### Expected Behavior

Should merge styles properly:

```html
<span style="color: red; font-size: 12px;">Hello</span>
```

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Unfortunately this is not how prosemirror works. It expects your html to valid on input so it does not do special parsing like this.

If you need special parse rules, you'll have to parse the html first on your own.

**Comment by KieranP** [comment]
@nperez0111 Thank you for taking the time to respond. And if the spans within spans was invalid, I would agree with you, but it is actually valid HTML.

Sources:

https://www.w3.org/TR/html401/struct/global.html#h-7.5.3
> "inline elements may contain only data and other inline elements"

https://www.w3docs.com/snippets/html/is-it-possible-to-use-a-span-within-another-span.html
> According to [HTML4 specification](https://www.w3.org/TR/html401/struct/global.html#h-7.5.3), inline elements can contain only data and other inline elements. Since <span> is an inline element, using a <span> within another <span> is valid.

https://html.spec.whatwg.org/
> nesting just [div](https://html.spec.whatwg.org/#the-div-element) elements, or nesting just [span](https://html.spec.whatwg.org/#the-span-element) elements, or nesting [span](https://html.spec.whatwg.org/#the-span-element) elements inside [div](https://html.spec.whatwg.org/#the-div-element) elements all serve the same purpose

Does Prosemirror have it's own HTML parser that needs to be fixed, or it is deferring to the browser to parse the initial HTML?

**Comment by nperez0111** [comment]
It is valid HTML, but prosemirror's parser (it does have it's own) is a stricter subset derived from the nodes & marks you have.

In prosemirror, it wants all the properties to be in one element like:

```html
<span style="color: red;"font-size: 12px;">
    Hello
 </span>
```
