### ISSUE TITLE
[Bug]: Vue Editor no longer provides root app globals

### ISSUE THREAD

**Issue by renatodeleao** [ueberdosis/tiptap#5323]
### Affected Packages

`@tiptap/vue-3`

### Version(s)

2.5.0-pre.14

### Bug Description

A customised editor that renders some app ui vue components via extension. These components make use of some app context globals — these can be directives, properties, etc. By rendering them in the editor, they should still have access to the app's context as they had before (`v2.4.0`) — or have a way to provide it.

The reproduction example uses the documentation demo https://tiptap.dev/docs/editor/extensions/custom-extensions/node-views/vue and tweaks it to include an `AppButton` which accesses a global app property object — `someGlobal.x`

### Browser Used

Chrome

### Code Example URL

https://stackblitz.com/edit/vitejs-vite-nmhr7x?file=src%2FApp.vue

### Expected Behavior

In the latest stable `v2.4.0` the components render just fine and have access to the app context -> demo: https://stackblitz.com/edit/vitejs-vite-8gu77g?file=src%2FApp.vue

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by wagich** [comment]
I stumbled over the same problem, it seems that the fix should be to assign the editor's `appContext` to the constructed vNode before rendering. 

I have this working locally [with this change](https://github.com/wagich/tiptap/commit/e3c0c41afd71e09dda301c2e6cc5787e7c42f96b), but don't really know enough about Vue 3 and tiptap to know whether this is the right solution or not…

**Comment by nperez0111** [comment]
This should be resolved with 2.5.5 which added back the perf updates for vue
