### ISSUE TITLE
Unexpected editable area in custom node rendered through component view

### ISSUE THREAD

**Issue by saaso** [ueberdosis/tiptap#534]
**Describe the bug**
There is an additional unexpected editable area outside ref="content" when we create custom node with component view.

**Steps to Reproduce / Codesandbox Example**
1. Go to https://codesandbox.io/embed/vue-template-x44uw?fontsize=14&hidenavigation=1&theme=dark There is two almost the same custom nodes:
 - first with regular view
 - second with component view. 
2. There is only one editable area in first node, but we get additional editable area in second node between ref="content" and another div element.

**Expected behavior**
Only ref="content" should be editable and selectable in node rendered through component view. It seems like ProseMirror prevent editing and even selecting all elements besides node's content no matter if it has attr contenteditable="false" or not

**Screenshots**
<img width="637" alt="Снимок экрана 2019-11-29 в 03 59 45" src="https://user-images.githubusercontent.com/53089091/69838556-c0d99e80-125c-11ea-9451-9aa62688d087.png">

**Environment**
 - OS: mac os
 - Browser: Chrome
 - Version 78.0.3904.108
 - Desktop

**Comment by hanspagel** [comment]
I think that’s due to strange browser behavior and we can’t work around that. 😏
