### ISSUE TITLE
[Bug]: When the Backspace key returns to the previous line, an empty node appears

### ISSUE THREAD

**Issue by laowangdefangjian** [ueberdosis/tiptap#5345]
### Affected Packages

@tiptap/vue-3

### Version(s)

2.5.0

### Bug Description

When the Backspace key returns to the previous line, an empty node appears

### Browser Used

Chrome

### Expected Behavior

I hope to return to the end of the previous line normally

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by laowangdefangjian** [comment]
The premise is that I have modified the structure of the document:
const Document = Node.create({
name: 'doc',
topNode: true,
content: 'dBlock+'
})

**Comment by nperez0111** [comment]
a reproduction would be helpful here. It would be difficult to know what extensions you've used & how it interacts.

**Comment by laowangdefangjian** [comment]
import { Node, mergeAttributes } from '@tiptap/core'
import { VueNodeViewRenderer } from '@tiptap/vue-3'
import { stopPrevent } from '@/utils/common'
import DragHandle from './DragHandle.vue'

const DBlock = Node.create({
  name: 'dBlock',

  priority: 1000,

  group: 'dBlock',

  content: 'block+',

  draggable: true,

  selectable: false,

  inline: false,

  addOptions () {
    return {
      HTMLAttributes: {}
    }
  },

  parseHTML () {
    return [{ tag: 'div[data-type="d-block"]' }]
  },

  renderHTML ({ HTMLAttributes }) {
    return [
      'div',
      mergeAttributes(HTMLAttributes, { 'data-type': 'd-block' }),
      0
    ]
  },

  addCommands () {
    return {
      setDBlock:
        (position) =>
          ({ state, chain }) => {
            const {
              selection: { from }
            } = state

            const pos =
            position !== undefined || position !== null ? from : position

            return chain()
              .insertContentAt(pos, {
                type: this.name,
                content: [
                  {
                    type: 'paragraph'
                  }
                ]
              })
              .focus(pos + 2)
              .run()
          }
    }
  },

  addNodeView () {
    return VueNodeViewRenderer(DragHandle)
  },

  addKeyboardShortcuts () {
    return {
      'Mod-Alt-0': () => this.editor.commands.setDBlock(),
      Enter: ({ editor }) => editor.commands.setDBlock()
    }
  }
})
export default DBlock

I used the above text, and my operation is as follows:
When I press enter to start a new line and then press the Backspace key, an empty node appears on the previous line, similar to the following image:
<img width="661" alt="微信图片_20240721210217" src="https://github.com/user-attachments/assets/0411ca6e-1df4-46ac-996f-c543db65aeae">

**Comment by laowangdefangjian** [comment]
Let me add that every time I press enter, I insert a line of 'dBlock'：
chain()
  .insertContentAt($from.pos, {
    type: 'dBlock',
    content: [
      {
        type: 'paragraph'
      }
    ]
  })
  .focus($from.pos + 4)
  .run()

**Comment by nperez0111** [comment]
Just a guess, but maybe it is because of `content: 'block+'` which says there must be at least one `block` and maybe you want `content: 'block*'` which is zero or more blocks?
https://tiptap.dev/docs/editor/core-concepts/schema#how-a-schema-looks-like

**Comment by laowangdefangjian** [comment]
Thank you for your response. I have now changed "block+" to "block", but there is no longer this issue. "block * still has this problem," I don't know why? I don't see this option in your document.
However, there is currently another issue, as I have customized the carriage return event to add a dBlock to each carriage return. Therefore, when I try to jump out of a list item with an ordered or unordered carriage return, an error message appears. The error message is as follows:
When there is no content in the three list and I press enter, the following error is reported：
<img width="1202" alt="1721790026235" src="https://github.com/user-attachments/assets/5a5307a0-f315-4dd6-9c06-5145540e929a">

**Comment by laowangdefangjian** [comment]
Just to add, the following is the content of my carriage return event:
import { Extension } from '@tiptap/core'
const Keymap = Extension.create({
  name: 'KeyMap',

  // Define custom commands for the extension
  addCommands () {
    return {
      handleEnterKey: () =>
        ({ state, chain }) => {
          const { selection, doc } = state
          const { $from, $to } = selection
          // const nodeBefore = $from.nodeBefore
          if (($from.node(-1).type.name === 'dBlock') && $from.parent.type.isBlock && $to.pos === $from.pos) {
            if ($to.pos === $from.end()) {
              return chain()
                .insertContentAt($from.pos, {
                  type: 'dBlock',
                  content: [
                    {
                      type: 'paragraph'
                    }
                  ]
                })
                .focus($from.pos + 4)
                .run()
              // Create and focus on a new root block with a paragraph inside at the cursor position
            } else {
              let currentActiveNodeTo = -1

              // Iterate over document nodes to find the active node's end position.
              doc.descendants((node, pos) => {
                if (currentActiveNodeTo !== -1) return false
                if (node.type.name === 'dBlock') return

                const [nodeFrom, nodeTo] = [pos, pos + node.nodeSize]
                if (nodeFrom <= $from.pos && $to.pos <= nodeTo) { currentActiveNodeTo = nodeTo }

                return false
              })

              const content = doc
                .slice($from.pos, currentActiveNodeTo)
                ?.toJSON().content

              // Replace content from cursor to the end of the block with new content.
              return chain()
                .insertContentAt(
                  { from: $from.pos, to: currentActiveNodeTo },
                  {
                    type: 'dBlock',
                    content
                  }
                )
                .focus($from.pos + 4)
                .run()
            }
          }
          // Handle Enter key within a to-do list item

          // If conditions aren't met, use the default Enter behavior
          return false
        }
    }
  },

  // Define keyboard shortcuts for the extension
  addKeyboardShortcuts () {
    return {
      Enter: ({ editor }) => editor.commands.handleEnterKey() // Call handleEnterKey command on Enter key press
    }
  }
})

export default Keymap

**Comment by laowangdefangjian** [comment]
Just to add, the following is the content of my carriage return event:
<img width="548" alt="1721790431183" src="https://github.com/user-attachments/assets/4b0ac622-7fee-46cc-8472-bbd8b7494061">

**Comment by laowangdefangjian** [comment]
Hello, I'm sorry to bother you. I've noticed that not only the list, but also those that need to exit the current block have this issue. For example, when I press Enter twice in a row, I get the same error: blockquote
RangeError: Invalid content for node dBlock:<blockquote (paragraph), paragraph>

**Comment by nperez0111** [comment]
This is because you did not listen to me, If you specify `content: 'block'` this means your element is only allowed to have a single block element as its content. If you specify `content: 'block*'` this means your elements is allowed to have zero or more block elements as its content.

You need `'block*``.

I am not going to help you with your custom keybind, because it is doing too much for me to understand what is going on and it the problem with your code.
