### ISSUE TITLE
[Bug]: Cursor showing horizontally with a custom node view

### ISSUE THREAD

**Issue by rocher71** [ueberdosis/tiptap#5350]
### Affected Packages

"@tiptap/extension-focus": "^2.5.1",         "@tiptap/extension-hard-break": "^2.4.0",         "@tiptap/extension-image": "^2.4.0",         "@tiptap/extension-placeholder": "^2.4.0",         "@tiptap/react": "^2.4.0",         "@tiptap/starter-kit": "^2.4.0",

### Version(s)

2.5.1

### Bug Description

I'm trying to make a custom node view, which is a button and an input filed. 
I want to make something like this :
<img width="185" alt="image" src="https://github.com/user-attachments/assets/324fd984-5456-4090-8eaf-8a555445f5f4">

I added a custom node view(component), but after implying the cursor is showing horizontally - sticks to the top - which is very weird. It is acting like this.

https://github.com/user-attachments/assets/1b364f36-917d-43ef-a6d6-2acd6d83d457

It doesn't act weird if I type something on the above line,
also when if I render it with a text above the custom component.

I have found that the problem is surely with the custom node view since if I remove it, this does not happen.

This is my code. I have referred to [this official documentation.](https://tiptap.dev/docs/editor/extensions/custom-extensions/node-views/react)
```jsx
//Component, 'SignatureButton.tsx'
const SignatureButton = () => {
  const { signatures, setWriteSignatureAtom, writeSignatureAtom } = useSignatureAtom();
  const [signatureValue, setSignatureValue] = React.useState<string>('');

  React.useEffect(() => {
    if (!writeSignatureAtom) return;
    setSignatureValue(signatures[writeSignatureAtom].signature);
  }, [writeSignatureAtom, signatures]);

  return (
    <NodeViewWrapper>
      {/* <br /> */}
      <Popover>
        {/* Button and signature shown in editor */}
        <div className="flex flex-row items-center group ">
          <NodeViewContent className="content is-editable flex items-center group w-full cursor-auto">
            <PopoverTrigger asChild className="signature-button invisible group-hover:visible">
              <Button className="flex text-sm text-gray-500 items-center align bg-white hover:bg-white cursor-pointer">
                <ChevronsLeftRight className="h-4 w-4 cursor-pointer" />
              </Button>
            </PopoverTrigger>
            <input
              type="text"
              placeholder="No Signature"
              className="focus:outline-none peer cursor-auto"
              onChange={(e) => setSignatureValue(e.target.value)}
              value={signatureValue.replace(/(<([^>]+)>)/gi, '')}
            />
          </NodeViewContent>
        </div>

        {/* Signature selection modal */}
        <PopoverContent className="p-4 w-80">
          <div className="overflow-y-auto max-h-60">
            <PopoverClose asChild>
              <ul className="space-y-2">
                {signatures.map((signature) => (
                  <li
                    key={signature.key}
                    className="cursor-pointer p-2 hover:bg-gray-100 flex items-center"
                    onClick={() => setWriteSignatureAtom(signature.key)}
                  >
                    {signature.signature.replace(/(<([^>]+)>)/gi, '')}
                  </li>
                ))}
              </ul>
            </PopoverClose>
          </div>
        </PopoverContent>
      </Popover>
    </NodeViewWrapper>
  );
};
```

```ts
// Extension, 'editorExtension.ts'
import SignatureButton from '@/renderer/src/components/mail/compose/SignatureButton';
import { mergeAttributes, Node } from '@tiptap/core';
import { ReactNodeViewRenderer } from '@tiptap/react';

export default Node.create({
  name: 'reactComponent',

  group: 'block',

  atom: true,
  content: 'inline*',

  addAttributes() {
    return {
      count: {
        default: 0
      }
    };
  },

  parseHTML() {
    return [
      {
        tag: 'react-component'
      }
    ];
  },

  renderHTML({ HTMLAttributes }) {
    return ['react-component', mergeAttributes(HTMLAttributes)];
  },

  addNodeView() {
    return ReactNodeViewRenderer(SignatureButton);
  }
});
```

```jsx
// index, 'text-editor.jsx'
import ReactComponent from '../../lib/editorExtension';

const RichTextEditor = ({
  value,
  onChange,
  isCompose
}: {
  value: string;
  onChange: (value: string) => void;
  isCompose?: boolean;
}) => {
  const editor = useEditor({
    editorProps: {
      attributes: {
        class:
          'min-h-[150px] max-h-[300px] w-full rounded-md rounded-br-none rounded-bl-none border border-input bg-transparent px-3 py-2 border-b-0 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none disabled:cursor-not-allowed disabled:opacity-50 overflow-auto'
      }
    },
    extensions: [
      ReactComponent,
      StarterKit.configure({
        orderedList: {
          HTMLAttributes: {
            class: 'list-decimal pl-4'
          }
        },
        bulletList: {
          HTMLAttributes: {
            class: 'list-disc pl-4'
          }
        }
      })
    ],
    content: value, 
    onUpdate: ({ editor }) => {
      onChange(editor.getHTML()); 
    }
  });

  useEffect(() => {
    if (editor && editor.getHTML() !== value) {
      setTimeout(() => {
        editor
          .chain()
          .setContent(value + (isCompose ? `<react-component></react-component>` : ''))
          .focus('start') //also the focus('start') here doesn't work :'(
          .createParagraphNear()
          .run();
      });
    }
  }, [editor, value]);

  return (
    <>
      <EditorContent className="min-h-[150px]" editor={editor} />
      {editor ? (
        <RichTextEditorToolbar editor={editor} isCompose={isCompose} />
      ) : (
        <div className="h-[40px]"></div>
      )}
    </>
  );
};
```

There was a [similar issue created last year](https://github.com/ueberdosis/tiptap/issues/4322), but since I couldn't find out any solutions,
I have made a new one.

### Browser Used

Chrome

### Code Example URL

https://github.com/woozlabs/echo-desktop

### Expected Behavior

https://github.com/user-attachments/assets/e54126cd-4525-4500-9b32-d32961442587

I am trying to add the signature field ( a whole line) as custom component.
(And additionally like in the video, I want it to be fixed at the bottom of the editor and the user not being able to write below that, but I'm struggling for this feature too🥲)

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by bdbch** [comment]
Hey @rocher71 

That's the `GapCursor` plugin and is expected if used. You can disable it in the StarterKit or just remove it from your extensions.

If you want to keep the functionality I think you could change the styling of the horizontal cursor to not being shown.

The reason this is used by default is to allow users to get the cursor between two node views / atoms or a document edge (start or end)

**Comment by rocher71** [comment]
Wow @bdbch,
thank you so much I couldn't find out that the problem is being triggered from `GapCursor`, 
was struggling too much and finally! 

To anyone looking for the solutions in the future, I disabled the `gapcursor` plugin and it is working fine!
```jsx
StarterKit.configure({
        orderedList: {
          HTMLAttributes: {
            class: 'list-decimal pl-4'
          }
        },
        bulletList: {
          HTMLAttributes: {
            class: 'list-disc pl-4'
          }
        },
        gapcursor: false // I added this line
      })
```

**Comment by bdbch** [comment]
> Wow @bdbch,
> thank you so much I couldn't find out that the problem is being triggered from `GapCursor`, 
> was struggling too much and finally! 
> 
> To anyone looking for the solutions in the future, I disabled the `gapcursor` plugin and it is working fine!
> ```jsx
> StarterKit.configure({
>         orderedList: {
>           HTMLAttributes: {
>             class: 'list-decimal pl-4'
>           }
>         },
>         bulletList: {
>           HTMLAttributes: {
>             class: 'list-disc pl-4'
>           }
>         },
>         gapcursor: false // I added this line
>       })
> ```

Just be cautious as your users could maybe not be able to put their cursor between custom nodes or atoms as prosemirror struggles there a bit.

Glad I could help
