### ISSUE TITLE
[Bug]: `splitBlock` returns `true` when it was unsuccessful

### ISSUE THREAD

**Issue by mgreystone** [ueberdosis/tiptap#5363]
### Affected Packages

core, extension-document, extension-paragraph, extension-text

### Version(s)

2.5.4

### Bug Description

The `splitBlock` command returns `true` even when it was unsuccessful.

If we have a `Document` with a content expression that only allows a single node, that node can never be split, as expected. However, the `splitCommand` still returns true even though the command failed. This causes `commands.first` not to attempt the next command in the list.

```ts
editor.commands.first(({ commands }) => [
  () => commands.splitBlock(), // always returns true
  () => commands.setHardBreak(), // we will never reach here, even if `splitBlock` fails
])
```

We can inspect the transaction & assert that the block was not split, even though the command returns true.
```ts
editor.commands.command(({ commands, tr }) => {
  const result = commands.splitBlock() // always true

  // If `splitBlock` was successfull, then `tr.steps` is
  // an array with a single `ReplaceStep`.
  // If `splitBlock` was unsuccesful, then `tr.steps` is
  // an empty array.
  console.log(tr.steps)

  return result
})
```

### Browser Used

Chrome

### Code Example URL

https://codesandbox.io/s/dank-flower-6scjk3?file=/src/index.js

### Expected Behavior

If `splitBlock` does not succeed in splitting a block, then it should return `false`.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
It would be helpful to know what branch you are hitting here to see what was incorrect: https://github.com/ueberdosis/tiptap/blob/b941eea6daba09d48a5d18ccc1b9a1d84b2249dd/packages/core/src/commands/splitBlock.ts#L1-L123

**Comment by mgreystone** [comment]
It looks like `canSplit` returns `false` [here](https://github.com/ueberdosis/tiptap/blob/b941eea6daba09d48a5d18ccc1b9a1d84b2249dd/packages/core/src/commands/splitBlock.ts#L84)

The [following conditional](https://github.com/ueberdosis/tiptap/blob/b941eea6daba09d48a5d18ccc1b9a1d84b2249dd/packages/core/src/commands/splitBlock.ts#L86-L90) is false and is skipped.

We also [skip this conditional](https://github.com/ueberdosis/tiptap/blob/b941eea6daba09d48a5d18ccc1b9a1d84b2249dd/packages/core/src/commands/splitBlock.ts#L102) and make no changes to the transaction.

[And then we return true](https://github.com/ueberdosis/tiptap/blob/b941eea6daba09d48a5d18ccc1b9a1d84b2249dd/packages/core/src/commands/splitBlock.ts#L122). Maybe it's as simple as returning `can`.

**Comment by nperez0111** [comment]
@mgreystone fantastic sleuthing, I think we should return `can` would you mind sending up a PR with that?

**Comment by mgreystone** [comment]
@nperez0111 It would be my pleasure. ⏳
