### ISSUE TITLE
[Bug]:  draggable  event

### ISSUE THREAD

**Issue by Criska9527** [ueberdosis/tiptap#5382]
### Affected Packages

"@tiptap/core": "^2.2.4",

### Version(s)

"@tiptap/core": "^2.2.4",

### Bug Description

I'm using draggable: true, to drag my node, and now I want to know the events related to dragging, such as what's being dragged to, where it's going to be dragged to, and so on, but I can't find what I'm looking for in the documentation

### Browser Used

Edge

### Code Example URL

1

### Expected Behavior

draggabledraggable

### Additional Context (Optional)

draggabledraggabledraggable

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
You can look at this for an implementation that we haven't gotten around to merging https://github.com/ueberdosis/tiptap/pull/4843
