### ISSUE TITLE
[Bug]: vercel build fail with 2.5.5 version

### ISSUE THREAD

**Issue by nakedfool** [ueberdosis/tiptap#5383]
### Affected Packages

@tiptap/core, @tiptap/extension-image, @tiptap/extension-link, @tiptap/extension-placeholder, @tiptap/pm, @tiptap/react, @tiptap/starter-kit

### Version(s)

2.5.5

### Bug Description

![image](https://github.com/user-attachments/assets/55952ffa-bece-40a5-b671-ebe9996812a0)
![image](https://github.com/user-attachments/assets/fde5eaef-5a50-4e50-8243-fb72302f7ae1)

Build failing on Vercel with tiptap v2.5.5. 

Steps to reproduce:
1. Use tiptap v2.5.5 in project
2. Deploy to Vercel

### Browser Used

Chrome

### Expected Behavior

Successful build and deployment.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
It looks to me that you have two versions of prosemirror-model installed. One in the root of your repo & one via the @tiptap/pm module. We obviously only support you pulling this package in via the @tiptap/pm module & not separately. So you will need to remove the other reference to prosemirror-model that you have.

You can see why it was included by running: `npx npm-why prosemirror-model`
