### ISSUE TITLE
[Bug]: deleting list items is buggy

### ISSUE THREAD

**Issue by maximehaaaaa** [ueberdosis/tiptap#5388]
### Affected Packages

core, vue, react

### Version(s)

all versions

### Bug Description

when adding some list elements in different indentations and trying to to delete a listentry that is the only one in its intendation,
its not possible to delete it and the curser jumps to the previous entry. this can also be seen on the official tiptap.dev site

### Browser Used

Chrome

### Expected Behavior

list item gets deleted and the rest of the list gets sinked on indent

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
You probably want to use the list keymap ext, we have not made it default for backwards compat reasons: https://tiptap.dev/docs/editor/api/commands/lists#list-keymap-extension
