### ISSUE TITLE
[Bug]: Maximum call stack size exceeded when use jest `.toMatchObject`

### ISSUE THREAD

**Issue by luckrnx09** [ueberdosis/tiptap#5389]
### Affected Packages

core

### Version(s)

2.5.4

### Bug Description

I want to assert two object has same shape, so here is my unit test code. How can I resolve this?  

```
describe('Example', () => {
  it('toMatchObject', () => {
    const obj1 = {
      name: 'hello',
      editor: new Editor({
        content: `<p>hello</p>`,
        extensions: [Document, Paragraph, Text],
      }),
    };
    const obj2 = {
      name: 'hello',
      editor: new Editor({
        content: `<p>hello</p>`,
        extensions: [Document, Paragraph, Text],
      }),
    };
    expect(obj1).toMatchObject(obj2); // RangeError: Maximum call stack size exceeded
  });
});
```
Here are the runtime info I can provided:
- jest: 27.3.1
- node: 20.10.0
- tiptap: 2.5.4

### Browser Used

Other

### Expected Behavior

Expected the `.toMatchObject` not throw exception

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
The editor is going to have properties that are recursive so I think jest is choking on that.

But the call itself does not make sense, you are comparing to instances of the editor? Why would do that?

If you want to compare the contents of the editor you can do `editor.getJSON()` or `editor.getHTML()` but comparing object instances are always going to be different?

**Comment by luckrnx09** [comment]
Thank you so much  @nperez0111 - I will try comparing them from .getJSON()
