### ISSUE TITLE
On writing in mobile iPhone, it should automatically scroll up like gmail compose mail does

### ISSUE THREAD

**Issue by deepaksisodiya** [ueberdosis/tiptap#539]
**Describe the bug**
When we write something on mobile. then text goes behind the keyboard panel. It should scroll up the text in that case.

**Steps to Reproduce / Codesandbox Example**
1. Go to https://deepaksisodiya.github.io/tiptap-editor/ in mobile chrome
2. White something in mobile
3. Text is hiding behind the keyboard

**Expected behavior**
It should scroll the text like gmail compose mail does

**Environment**
 - Browser [e.g. chrome]

**Comment by deepaksisodiya** [comment]
on android it works fine. But on iPhone is not.

**Comment by philippkuehn** [comment]
Can’t reproduce this in the latest version. Closing this.
