### ISSUE TITLE
[Bug]: Fails to resolve a value via `provide/inject` in Vue node view components

### ISSUE THREAD

**Issue by romansp** [ueberdosis/tiptap#5394]
### Affected Packages

@tiptap/vue-3

### Version(s)

2.5.6

### Bug Description

Attempting to resolve a value via `provide/inject` in Vue node view components produces `undefined` result. 

[Vue will keep parent's provides on object's prototype if current component itself has its own `provide` call](https://github.com/vuejs/core/blob/91112520427ff55941a1c759d7d60a0811ff4a61/packages/runtime-core/src/apiInject.ts#L19-L28). It's achieved by using `Object.create()`. When `EditorContent` constructs `appContext` it uses spread to forward parent chain provides. Spread operator won't copy prototype resulting in missing provided parent values.
https://github.com/ueberdosis/tiptap/blob/b0124717559071729a365d67b9d4747c5fb2a1cf/packages/vue-3/src/EditorContent.ts#L47-L54

Related to #5323, #5373.

`2.4.0` is not affected.

### Browser Used

Edge

### Code Example URL

https://stackblitz.com/edit/vitejs-vite-f212pf?file=src%2FApp.vue

### Expected Behavior

All `provide/inject` values should be properly available in editor component node views.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
@romansp since you seem to have good context on what the issue is, would you mind submitting a PR to resolve it?

**Comment by romansp** [comment]
@nperez0111 will try to tackle this later today. 

I also don't mind if @Rirax would like to give it a shot before I can get to it. Seems like they originally worked on the perf improvements PR.

**Comment by Rirax** [comment]
Hi @nperez0111  @romansp ,
@romansp thank you for your message.
I fixed with [this MR](https://github.com/ueberdosis/tiptap/pull/5396) to access `appProvidedValue` from `Editor`.
I see in your example that you also want to access `editorProvidedValue` from `App`. Do we agree that this isn't possible given that provides only provides data to child components?

**Comment by nperez0111** [comment]
Just merged, will go out in the next release. Thanks @Rirax  and appreciate the report @romansp

**Comment by romansp** [comment]
Thanks @Rirax but I'm afraid this issue needs to be reopened. I just tried running tiptap demos with #5396 and `provide/inject` values are still lost.

`Object.assign` actually won't copy properties on object prototype. I was thinking we use `Object.create` but let me do some more testing if that's needed at all. It seems we can just pass `provides` of the current instance further to appContext.

@nperez0111 I haven't contributed to TipTap before and if I were to add tests to cover this behavior what would be the spot for it? Thanks!

**Comment by nperez0111** [comment]
Each example has associated tests https://github.com/ueberdosis/tiptap/blob/eaee9c7177ccd86796b8c051b525acf70fb72034/demos/src/Examples/Savvy/Vue/index.spec.js#L1 but I don't see an existing one that would be "natural" for this. Maybe just a new folder in `Examples/Integrations/Vue` that copies one of the other instances maybe?

**Comment by Matqo** [comment]
Hi folks, is there a way for embedded components to pass the 'provide' to their child embedded components? It appears the child component loses context of parent, for example using the `.insertContent(`<component-a><component-b></component-b></component-a>`)` command to add parent component a, with child component b. Component a contains a provide, component b on other hand injects. Thanks in advance

**Comment by Matqo** [comment]
Hi @romansp @nperez0111 @Rirax , is there a way for embedded components to pass the 'provide' to their child embedded components? It appears that the child component loses context of parent, for example using the `.insertContent('<component-a><component-b></component-b></component-a>')` command to add parent component A, with child component B. Component A contains a provide, component B on other hand injects. Thanks in advance

**Comment by romansp** [comment]
@Matqo afaik it should just work. Please provide minimal repro - I will take a look.

**Comment by KazimirPodolski** [comment]
@romansp @nperez0111 It still doesn't work, Vue view nodes down the tree doesn't see parent context. The simplest repro I came up with: https://codesandbox.io/p/devbox/boring-zhukovsky-8yhzhv.
