### ISSUE TITLE
[Bug]: Bold Markdown input is broken when adding '__' at the beginning of a word (even in official demos) 

### ISSUE THREAD

**Issue by iafan** [ueberdosis/tiptap#5405]
### Affected Packages

react, starter-kit

### Version(s)

2.5.7

### Bug Description

It looks like adding two underscore symbols at the beginning of the line or two asterisks to mark text as bold is broken.

Verified on a macOS on latest Chrome and Safari.

Steps to reproduce:
1. Go to https://tiptap.dev/docs/examples/basics/markdown-shortcuts or sandbox created from the official React template with no changes: https://codesandbox.io/s/tiptap-react-qidlsv
2. Put caret at the beginning of the document, before the first word.
3. Type `_`, then `_` again.
Expected: both underscore symbols (`__`) stays at the beginning of the word.
Observed: the second `_` disappears. In the console, there's an error: `RangeError: Position -1 out of range`, and the editor behaves erratically as you continue pressing `_`.

I recorded a video of the bug in action.
https://github.com/user-attachments/assets/6970cff8-5871-4f3c-8816-b4817d133516

### Browser Used

Chrome

### Code Example URL

https://codesandbox.io/s/tiptap-react-qidlsv

### Expected Behavior

I would expect for both underscores to stay at the beginning of the word so that I could then go to the end of the word, add two underscores there and auto-apply the bold style to the word.

### Additional Context (Optional)

Interestingly, the bug does not reproduce on the main playground (https://templates.tiptap.dev/).

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Thank you for the bug report, I found the bug & it will be resolved by: https://github.com/ueberdosis/tiptap/pull/5407
