### ISSUE TITLE
[safari] On click of button inside floating menu, it hides the button

### ISSUE THREAD

**Issue by deepaksisodiya** [ueberdosis/tiptap#541]
**Describe the bug**
When user clicks on button inside floating menu. It hided the button for mobile. on desktop it is working fine.

**Steps to Reproduce / Codesandbox Example**
1. Go to https://deepaksisodiya.github.io/tiptap-editor/ on mobile chrome
2. Click on plus icon

 **Expected behavior**
It should show the floating menu on click of plus icon

**Environment**
Chrome

**Comment by hanspagel** [comment]
Thanks for the report! And sorry for the silence here. Unfortunately, the floating menu seems pretty broken. We won’t take time to fix it, but we are about completely rewrite all interface components. I’m closing this here for now.
