### ISSUE TITLE
[Bug]: why change isNodeEmpty behavior on a patch version?

### ISSUE THREAD

**Issue by tdawn0-0** [ueberdosis/tiptap#5415]
### Affected Packages

core

### Version(s)

2.5.7

### Bug Description

the helper function isNodeEmpty behavior is change on the 2.5.7.
this will cause the editor isEmpty return true when the editor is only contain a image content.
https://github.com/ueberdosis/tiptap/pull/5393

### Browser Used

Chrome

### Expected Behavior

isNodeEmpty behavior as usual on 2.5.x.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by romansp** [comment]
Also noticed that due to this change placeholder is now displayed unexpectedly. For example, if paragraph consists of just a single mention or an emoji node paragraph is now considered to be empty.

**Comment by nperez0111** [comment]
Sorry this was an oversight in the test cases, surprisingly it is not easy to know what is considered "empty"

**Comment by tdawn0-0** [comment]
> Sorry this was an oversight in the test cases, surprisingly it is not easy to know what is considered "empty"

I understand that this is not a simple task. just changing a fundamental function in a patch version should be approached with more caution.

**Comment by nperez0111** [comment]
> I understand that this is not a simple task. just changing a fundamental function in a patch version should be approached with more caution.

Obviously I did not intend to change the behavior of it. Mistakes can happen. Please reconsider berating maintainers of free OSS software.

**Comment by arendjantetteroo** [comment]
We add our own components to the page, which tiptap now considers empty since version 2.5.7. 
This caused it to sent empty page data to our backend, basically deleting all content of our customers on this page, leading to data loss for these customers. 

How can i test the new version works correctly for our usecase?

**Comment by tdawn0-0** [comment]
> > I understand that this is not a simple task. just changing a fundamental function in a patch version should be approached with more caution.
> 
> Obviously I did not intend to change the behavior of it. Mistakes can happen. Please reconsider berating maintainers of free OSS software.

I'm here to discuss a matter. Please accept my apologies if it appeared that I was criticizing you. However, the changes in question are not insignificant.

**Comment by nperez0111** [comment]
This is now released with v2.5.9
