### ISSUE TITLE
Support Spellchecking

### ISSUE THREAD

**Issue by conloos** [ueberdosis/tiptap#542]
Hi ,

I often use Nextcloud - Text which is based on TipTap.

Is it possible to integrate support for the Langagetool spell checker? It would be good if the Langagetool server is set by defaut and can be replaced by its own.

**Comment by stefnotch** [comment]
The demo disabled the spell checking feature. You can enable it using your browser dev-tools and setting `spellcheck=true`
![image](https://user-images.githubusercontent.com/10220080/85000610-f12e4f00-b152-11ea-962e-5df8ea0be43b.png)

[Prosemirror](https://github.com/ProseMirror/prosemirror) mostly handles spell checking correctly.

**Comment by sereneinserenade** [comment]
For anyone who lands on this thread, I've made a Tiptap Extension that integrated spellchecking to Tiptap using ProseMirror decorations and Tiptap BubbleMenu.

Here's the Repository: https://github.com/sereneinserenade/tiptap-languagetool
Here's a demo: https://tiptap-languagetool.vercel.app/

**Comment by jshaptala** [comment]
For context, this limitation still explains why spellcheck isn’t handled at the editor core level.

In practice today, teams usually handle spelling and grammar outside of Tiptap itself by integrating proofreading logic via custom extensions, mapping results to decorations and custom suggestion UI. This avoids browser inconsistencies and allows finer control over languages and dictionaries.

For anyone interested in a concrete example, here’s a minimal demo showing how this can work with Tiptap: https://demos.webspellchecker.com/wproofreader-tiptap.html
