### ISSUE TITLE
[Documentation]: China has a huge market, why isn't there an official website with Chinese translation? 中国有着巨大市场，为何没有中文文档？

### ISSUE THREAD

**Issue by zhouchangmin** [ueberdosis/tiptap#5423]
### What’s the URL to the page you’re sending feedback for?

https://tiptap.dev/

### What part of the documentation needs improvement?

China has a huge market, why isn't there an official website with Chinese translation?
中国有着巨大市场，为何没有中文文档？

### What is helpful about that part?

China has a huge market, why isn't there an official website with Chinese translation?
中国有着巨大市场，为何没有中文文档？

### What is hard to understand, missing or misleading?

China has a huge market, why isn't there an official website with Chinese translation?
中国有着巨大市场，为何没有中文文档？

### Anything to add? (optional)

China has a huge market, why isn't there an official website with Chinese translation?
中国有着巨大市场，为何没有中文文档？

**Comment by xiaweiss** [comment]
如果你愿意的话，可以自己汉化。知名的库，Vue、React 等等，官方都没有提供中文文档。都是社区贡献者汉化的。

**Comment by xiaweiss** [comment]
@zhouchangmin 你说的中国巨大市场，能展开说说吗？

据我所知，中国头部互联网公司，腾讯文档、飞书文档、石墨文档等，都是闭源自研，且没有给社区任何赞助。

**Comment by nperez0111** [comment]
I don't think we are at the pointing of supporting multiple translations of our docs. Translation services & even LLMs are really good at it, I would suggest to use that instead
