### ISSUE TITLE
No space after programmatically inserted mention

### ISSUE THREAD

**Issue by tcitworld** [ueberdosis/tiptap#543]
**Describe the bug**
When adding a mention through the `@` matcher, an extra space is added after the mention `<span>` so that the cursor is located after. When adding a mention programmatically, a `<br>` element follows the mention `span` and is replaced with content when some is entered.

**Steps to Reproduce / Codesandbox Example**
1. Go to https://tiptap.scrumpy.io/suggestions
2. Click on 'Insert Mention'
3. Select and validate a name and continue to type extra characters
4. The extra characters are not separated from the mention

**Expected behavior**
Same behaviour by triggering the `@` matcher and adding a mention programmatically. 

**Environment**
 - Browser Firefox
 - Version 71
 - Mobile / Desktop: Desktop

**Comment by therealwolf42** [comment]
I'm trying to **prevent** the extra space being created. Do you know where in the code it's being added?

**Comment by philippkuehn** [comment]
At the moment this is defined in the mention node. https://github.com/scrumpy/tiptap/blob/master/packages/tiptap-extensions/src/nodes/Mention.js#L62
