### ISSUE TITLE
[Bug]: Missing <colgroup> Tag When Extending Tiptap Table with addNodeView Method Causes Resize Issue

### ISSUE THREAD

**Issue by MohamedElGhandour** [ueberdosis/tiptap#5431]
### Affected Packages

@tiptap/extension-table

### Version(s)

2.5.7

### Bug Description

When extending the Tiptap table and using the `addNodeView` method, the `<colgroup>` tag is not rendered in the resulting table. This omission causes the table resize functionality to break. The `<colgroup>` tag is essential for handling column widths and enabling resizing capabilities.

#### Steps to Reproduce
1. Extend the Tiptap table in your editor configuration.
2. Use the `addNodeView` method to customize the table node view.
3. Insert a table into the editor.
4. Attempt to resize the table columns.

### Browser Used

Chrome

### Expected Behavior
The table should include a `<colgroup>` tag in its HTML structure, enabling proper column resizing functionality.

#### Actual Behavior
The `<colgroup>` tag is missing from the table's HTML structure, causing the column resizing functionality to fail.

#### Environment
- Tiptap Version: 2.5.7
- Browser: Google Chrome Version 127.0.6533.88

#### Additional Information
- Screenshots demonstrating the issue
when use addNodeView method
![image](https://github.com/user-attachments/assets/52e5325c-fa60-42e1-8e85-9d226bd218a0)
when remove addNodeView method
![image](https://github.com/user-attachments/assets/72901e38-6258-4c96-a3a6-d28832d57bd0)

- Code snippets of the table extension and `addNodeView` method
table.ts
```ts
import Table from "@tiptap/extension-table";
import { VueNodeViewRenderer } from "@tiptap/vue-3";
import TiptapTable from "./TiptapTable.vue";

export const CustomTable = Table.extend({
  name: "table",

  addOptions() {
    return {
      ...this.parent?.(),
    };
  },

  addAttributes() {
    return {
      ...this.parent?.(),
    };
  },

  addNodeView() {
    return VueNodeViewRenderer(TiptapTable);
  },
});
```
TiptapTable.vue
```vue
<script setup lang="ts">
import { defineProps } from "vue";
import { NodeViewWrapper, NodeViewContent, nodeViewProps } from "@tiptap/vue-3";

// Define props from NodeViewProps
const props = defineProps({
  ...nodeViewProps,
});
</script>

<template>
  <NodeViewWrapper>
    <table>
      <NodeViewContent as="tbody" />
    </table>
  </NodeViewWrapper>
</template>
```

### Additional Notes

If the `<colgroup>` is generated, the actual size of the table columns will render correctly, but the resize functionality may still not work as expected. This could be due to additional CSS or JavaScript required to handle the resizing of table columns.

```vue
<script setup lang="ts">
import { defineProps } from "vue";
import { NodeViewWrapper, NodeViewContent, nodeViewProps } from "@tiptap/vue-3";
import { createColGroup } from "@tiptap/extension-table";

// Define props from NodeViewProps
const props = defineProps({
  ...nodeViewProps,
});

const colGroupData = computed(() => createColGroup(props.node, 25));

const visibleColumns = computed<Column[]>(() => {
  const colGroup = colGroupData.value.colgroup;
  return colGroup ? colGroup.slice(2) : [];
});

const columnStyles = computed<(string | undefined)[]>(() =>
  visibleColumns.value.map(([_, { style }]) => style)
);
</script>

<template>
  <NodeViewWrapper>
    <table>
      <colgroup>
       <col v-for="(style, index) in columnStyles" :key="index" :style="style" />
      </colgroup>
      <NodeViewContent as="tbody" />
    </table>
  </NodeViewWrapper>
</template>
```

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
If you extended the table with addNodeView, you are completely overriding the table's rendering, so you would have to implement colgroup yourself
