### ISSUE TITLE
[Bug]: Typography extension's smart quotes are now broken

### ISSUE THREAD

**Issue by vonWolfehaus** [ueberdosis/tiptap#5433]
### Affected Packages

@tiptap/extension-typography

### Version(s)

2.5.6 and up

### Bug Description

I upgraded to 2.5.6 (from 2.5.1) and now smart quotes (openSingle/DoubleQuotes) no longer work. The opening quote prints "true" into the editor (pressing backspace will delete the whole word if you just added it) while the closing smartquote works.

This is ONLY if I specifically configure the typography extension to allow smart quotes. If I don't configure the extension (even if the config is empty), it works fine.

### Browser Used

Chrome

### Code Example URL

https://github.com/vonWolfehaus/tiptap-char-count-bug

### Expected Behavior

When the Typography extension is configured to allow smart quotes (openDoubleQuote, closeDoubleQuote, openSingleQuote, closeSingleQuote set to 'true') the editor should start inserting smart quotes properly. Likewise, if they are set to 'false', they should not use smart quotes.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Based on the typings and implementation, it sounds like you are using it wrong, `true` is not a valid value for an `openSingleQuote` (etc.)

`false` would disable the quote: https://github.com/ueberdosis/tiptap/blob/b941eea6daba09d48a5d18ccc1b9a1d84b2249dd/packages/extension-typography/src/typography.ts#L300
`undefined` (i.e. not provided) would fallback to the correct value https://github.com/ueberdosis/tiptap/blob/b941eea6daba09d48a5d18ccc1b9a1d84b2249dd/packages/extension-typography/src/typography.ts#L268
Anything else is treated as though you are substituting the quote with that value (so you are substituting with the value `true` which gets coerced to `"true"`)


This is described in the documentation: https://tiptap.dev/docs/editor/extensions/functionality/typography#disabling-rules
