### ISSUE TITLE
[Bug]: <col> element missing min-width (or width) style when column hasn't been resized

### ISSUE THREAD

**Issue by Ragnar-Oock** [ueberdosis/tiptap#5435]
### Affected Packages

@tiptap/extension-table, @tiptap/extension-table-cell, @tiptap/extension-table-header, @tiptap/extension-table-row

### Version(s)

2.5.8

### Bug Description

The generated `<col>` elements don't have a width or min-width set on them unless the corresponding column is manually resized. For columns with wrapping text that can lead to layout jump when other column are resized (you can try resizing an empty column in the repro to provoke it) and columns can end up with a width smaller than the configured `cellMinWidth` (both in the editor and in the HTML output)

While the "in editor" `<col>` are controled by `prosemirror-table` (I will open an issue there and link it to this one later), the output is handled by tiptap and it can easily be fixed by changing this line :
https://github.com/ueberdosis/tiptap/blob/84ebd511d29db566e66e8f9b617179cf19ed2531/packages/extension-table/src/utilities/createColGroup.ts#L40
into :
```ts
cols.push([
  'col', 
  { style: hasWidth ? `width: ${ hasWidth }px` : `min-width: ${ cellMinWidth }px` }
]);
```

### Browser Used

Firefox

### Code Example URL

[reproduction](https://codesandbox.io/p/sandbox/vibrant-lichterman-t5f8jq?file=%2Fsrc%2Findex.js%3A25%2C5&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzcqk0sc00062a69d0ag7w73%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzcqk0sc00022a69u2khcve3%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzcqk0sc00032a69x176biyn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzcqk0sc00052a697vqtrba1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B49.40234004166828%252C50.59765995833172%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzcqk0sc00022a69u2khcve3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzcqk0sc00012a69vdfrjh96%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A25%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A25%252C%2522endColumn%2522%253A5%257D%255D%257D%255D%252C%2522id%2522%253A%2522clzcqk0sc00022a69u2khcve3%2522%252C%2522activeTabId%2522%253A%2522clzcqk0sc00012a69vdfrjh96%2522%257D%252C%2522clzcqk0sc00052a697vqtrba1%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzcqk0sc00042a693pppogfn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clzcqk0sc00052a697vqtrba1%2522%252C%2522activeTabId%2522%253A%2522clzcqk0sc00042a693pppogfn%2522%257D%252C%2522clzcqk0sc00032a69x176biyn%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clzcqk0sc00032a69x176biyn%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Expected Behavior

The `<col>` should always have either `width` or `min-width` set on them to prevent column from going below the configured minimum width.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by Ragnar-Oock** [comment]
I'm not sure if I should open an other issue for this detail or not but it might be interesting to point out in the doc that table cells `<td>` and `<th>` should have both `word-break: break-word` and `width: min-content` to avoid layout jumps when resizing columns in table that don't have a `width: 100%` (like is the case in the above repro or my application)

**Comment by nperez0111** [comment]
Would be happy to accept a PR for the original issue.

For the second doc recommendation, I think that is out of scope since it is a styling question & there are multiple solutions to it
