### ISSUE TITLE
[Bug]: BubbleMenu not working, seemingly due to Tippy.js

### ISSUE THREAD

**Issue by drkirkham** [ueberdosis/tiptap#5438]
### Affected Packages

BubbleMenu

### Version(s)

2.58

### Bug Description

When running this plugin, it crashes my app with the error 
validation.ts:46 Uncaught ReferenceError: process is not defined
    at validation.ts:46:1

Having looked at the code, it is probably to do with Tippy that's underneath it. I am using a Vite development server and apparently has a nasty feature of requiring people to mess around with ENV variables in respect of Rollup. (https://atomiks.github.io/tippyjs/v5/faq/#im-getting-uncaught-referenceerror-process-is-not-defined). 

The error is as clear as mud - the fix would seem to be to remove Tippy, or at least put a proper debug message in. 

### Browser Used

Chrome

### Expected Behavior

The app not to crash with that error. 

### Additional Context (Optional)

See above. 

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
This is not a tiptap problem per se but what you can do is in your vite config:
```
import { defineConfig } from 'vite'
// ...
export default defineConfig({
  // ...
  define: {
    'process.env.NODE_ENV': 'production'
  }
})
```

Which should add a definition for the variable it is looking for.
