### ISSUE TITLE
Markdown Preview

### ISSUE THREAD

**Issue by innocenzi** [ueberdosis/tiptap#545]
Hey,

So I've seen that this package has support for markdown shortcuts. 
I believe it would be possible to add support for implementing markdown preview by modifying the Input Rules, but I didn't manage to. 

The closest I could get is the following, with the last character being removed for some reason:

![](https://i.imgur.com/FekUbWk.gif) 

I just copied the `markInputRule`, and removed the `tr.delete` calls (and adjusted the mark start/end). But even if I managed to do it this way, I wouldn't be able to escape the formatting. 

What I want is a similar implementation to the new Discord rich text: 

![](https://i.imgur.com/jqnlgl7.gif)

Is there any way to do so? Or do you have any idea on how to implement this?

**Comment by BrianHung** [comment]
To add onto this thread, Discord uses for its markdown highlighting the library [Slate.js](www.slatejs.org), which supports [markdown decorations out of the box](https://www.slatejs.org/examples/markdown-preview). We can check this by inspecting the input box, and noticing that there are `data-slate-*` attributes in the decorations.

The implementations of markdown decorations on the Slate homepage and on Discord are slightly different:
- Slate simply wraps a decorated node as one, e.g. **bold** is `<span>**bold**</span>`.
- Discord separates the decorations from the content, e.g. **bold** is `<span>**</span><span>bold</span><span>**</span>`. That's how the decorations in the gif above are subtly styled different than the text.

The Slate implementation seems easier to implement in TipTap: we would not remove the decorations when adding a Mark to the TextNode; and we would remove a mark when decorations are modified. The last part can probably be done by monitoring transactions and checking if the new TextNode still conforms to the Mark regex pattern, converting it back if it doesn't. An approach similar to this is documented in the ProseMirror discuss forum [here](https://discuss.prosemirror.net/t/how-to-create-non-editable-text-segments-in-the-document/1154/9).

**Comment by Slapbox** [comment]
Did this ever happen?
