### ISSUE TITLE
[Bug]: Ellipsis input rule deletes previous character if triggered before a period

### ISSUE THREAD

**Issue by fuadsaud** [ueberdosis/tiptap#5453]
### Affected Packages

extension-typography

### Version(s)

2.5.5

### Bug Description

https://github.com/user-attachments/assets/1e095efe-b96a-4560-b7ca-9842279a6116

Entering 2 dots before an already existing dot will trigger the ellipsis input rule but will also delete the previous character

### Browser Used

Chrome

### Code Example URL

https://tiptap.dev/docs/examples/basics/markdown-shortcuts

### Expected Behavior

Ellipsis rule is triggered but the previous character is unchanged.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
I will close this issue, since you already opened one. Highly doubt that they aren't related
