### ISSUE TITLE
[Bug]: Strikethrough doesn't respect font color

### ISSUE THREAD

**Issue by bbonczek** [ueberdosis/tiptap#5461]
### Affected Packages

core

### Version(s)

latest

### Bug Description

Strikethrough color remains black, even if font has different color. To reproduce:
1. Go to https://demos.tiptap.dev/
2. Add some text
3. Change text's color to something else than black
4. Apply strikethrough

### Browser Used

Chrome

### Expected Behavior

Strikethrough should have the same color as text.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
This was actually just fixed recently, it has not been released yet but thank you for the report

https://github.com/ueberdosis/tiptap/pull/5457

**Comment by bbonczek** [comment]
Great!
