### ISSUE TITLE
[Bug]: `onUpdate` called twice for each change

### ISSUE THREAD

**Issue by quintstoffers** [ueberdosis/tiptap#5463]
### Affected Packages

react

### Version(s)

2.5.9

### Bug Description

It appears that each keystroke is reported twice in `onUpdate`. This also seems to affect other events, such as `onBlur`.

In my reproduction I'm logging the number of keystroke events and the number of update events. For each keystroke two updates are triggered.

![Kapture 2024-08-09 at 17 46 38](https://github.com/user-attachments/assets/1c07f694-1361-4b4e-85ae-8a95f60b1586)

The `onBlur` event can also be triggered twice, but it takes a few tries to trigger.

### Browser Used

Chrome

### Code Example URL

https://codesandbox.io/p/sandbox/hungry-framework-4dwjgc

### Expected Behavior

`onUpdate` and other events are called _once_ per actual change/event.

### Additional Context (Optional)

We were previously on `2.4.0`, which did not exhibit this behaviour.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Good catch!
This was a bug in the useEditor implementation where it was incorrectly registering event listeners twice. I have a solution for it

**Comment by quintstoffers** [comment]
Great, thanks!

This came up in a unit test on our end that expected the event to be called exactly once. I wouldn't have noticed otherwise.

**Comment by nperez0111** [comment]
This is resolved with 2.6.0
