### ISSUE TITLE
[Bug]: useEditor returns the Editor from @tiptap/core, but the component receives the Editor from @tiptap/react.

### ISSUE THREAD

**Issue by rmagur1203** [ueberdosis/tiptap#5478]
### Affected Packages

react

### Version(s)

2.6.0

### Bug Description

at [c7fd0f](https://github.com/ueberdosis/tiptap/commit/c7fd0f80afa5e4cd7b855514571be02111b9d358)
 useEditor has been changed to return the Editor of @tiptap/core, and all components of @tiptap/react use the Editor of @tiptap/react.
 Because of this, if you use the existing code (e.g. example code in the documentation), an error will occur during build.
 
 
![image](https://github.com/user-attachments/assets/c5ed75a8-4bdd-47a7-82eb-18151850e010)

```
./components/Tiptab.tsx:12:25
Type error: Type 'import("/home/projects/stackblitz-starters-mp7yk6/node_modules/@tiptap/core/dist/packages/core/src/Editor").Editor | null' is not assignable to type 'import("/home/projects/stackblitz-starters-mp7yk6/node_modules/@tiptap/react/dist/packages/react/src/Editor").Editor | null'.
  Property 'contentComponent' is missing in type 'import("/home/projects/stackblitz-starters-mp7yk6/node_modules/@tiptap/core/dist/packages/core/src/Editor").Editor' but required in type 'import("/home/projects/stackblitz-starters-mp7yk6/node_modules/@tiptap/react/dist/packages/react/src/Editor").Editor'.

  10 |   });
  11 | 
> 12 |   return <EditorContent editor={editor} />;
     |                         ^
  13 | };
  14 | 
  15 | export default Tiptap;
```

### Browser Used

Chrome

### Code Example URL

https://stackblitz.com/edit/stackblitz-starters-mp7yk6?file=components%2FTiptab.tsx

### Expected Behavior

If you build as you would for builds prior to 2.6.0 (2.5.9, etc.), it should proceed successfully.
However, the build failed due to the difference in types between useEditor and EditorContent.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Ah, this is my bad, I have just made a PR for it here: https://github.com/ueberdosis/tiptap/pull/5479

**Comment by nperez0111** [comment]
Alright, releasing 2.6.1 with this fix, should be available in a couple minutes
