### ISSUE TITLE
[Bug]: Enter key does not generate a new line and causes console errors

### ISSUE THREAD

**Issue by nibl** [ueberdosis/tiptap#5485]
### Affected Packages

core, starter-kit

### Version(s)

2.6.2

### Bug Description

To reproduce:

1) Run the code in the Getting Started CDN example at:

https://tiptap.dev/docs/editor/getting-started/install/cdn

2) Place the cursor at the very end of the pre-loaded text (behind the "!" in "Hello World!"), then press The Enter key. The console error below is output (same error twice).

A further example: place the cursor behind the "o" in Hello.The first time the enter key will work as expected and create a new line. Repeat by placing the cursor back behind the "o" in Hello, and press Enter again. The second time it causes the same console error. However, place the cursor before the o in "Hello", and it creates a new line.

Reproduced in multiple browsers: mobile Safari (iOS latest versions), Chrome, Brave, Firefox on Mac OS (older version, but all produce same errors).

----
Errors in console (same output twice):

```
index.js:354 Uncaught RangeError: Can not convert <> to a Fragment (looks like multiple versions of prosemirror-model were loaded)
    at s.from (index.js:354:15)
    at s.create (index.js:2171:66)
    at ve (index.js:1139:58)
    at E.split (index.js:2043:9)
    at splitBlock.ts:103:10
    at Object.splitBlock (CommandManager.ts:137:64)
    at Array.<anonymous> (keymap.ts:59:22)
    at first.ts:22:16
    at Object.first (CommandManager.ts:39:43)
    at Enter (keymap.ts:55:52)
from @ index.js:354
create @ index.js:2171
ve @ index.js:1139
split @ index.js:2043
(anonymous) @ splitBlock.ts:103
(anonymous) @ CommandManager.ts:137
(anonymous) @ keymap.ts:59
(anonymous) @ first.ts:22
(anonymous) @ CommandManager.ts:39
Enter @ keymap.ts:55
(anonymous) @ ExtensionManager.ts:191
(anonymous) @ index.js:99
(anonymous) @ index.js:3096
someProp @ index.js:5440
M.keydown @ index.js:3096
Mo.t.dom.addEventListener.t.input.eventHandlers.<computed> @ index.js:3018
index.js:354 Uncaught RangeError: Can not convert <> to a Fragment (looks like multiple versions of prosemirror-model were loaded)
    at s.from (index.js:354:15)
    at s.create (index.js:2171:66)
    at ve (index.js:1139:58)
    at E.split (index.js:2043:9)
    at splitBlock.ts:103:10
    at Object.splitBlock (CommandManager.ts:137:64)
    at Array.<anonymous> (keymap.ts:59:22)
    at first.ts:22:16
    at Object.first (CommandManager.ts:39:43)
    at Enter (keymap.ts:55:52)
from @ index.js:354
create @ index.js:2171
ve @ index.js:1139
split @ index.js:2043
(anonymous) @ splitBlock.ts:103
(anonymous) @ CommandManager.ts:137
(anonymous) @ keymap.ts:59
(anonymous) @ first.ts:22
(anonymous) @ CommandManager.ts:39
Enter @ keymap.ts:55
(anonymous) @ ExtensionManager.ts:191
(anonymous) @ index.js:99
(anonymous) @ index.js:4952
someProp @ index.js:5440
wo @ index.js:4952
(anonymous) @ index.js:5227
flush @ index.js:4649
observer @ index.js:4493
```

### Browser Used

Other

### Code Example URL

https://tiptap.dev/docs/editor/getting-started/install/cdn

### Expected Behavior

Enter key should generate a new line without errors.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Unfortunately prosemirror is not built in a way that it can be imported multiple times so this is kind of at odds with an ESM CDN build since each package will try to declare it's own version.

**Comment by nperez0111** [comment]
Please track progress here instead
https://github.com/ueberdosis/tiptap/issues/4873
