### ISSUE TITLE
[Bug]: Tab characters are stripped in useEditor content prop

### ISSUE THREAD

**Issue by Nantris** [ueberdosis/tiptap#5486]
### Affected Packages

core

### Version(s)

2.5.9

### Bug Description

Related to #4862 - I noticed I had one test marked as `skip` with a TODO to re-enable once #4862 was resolved. Unfortunately this test continues to fail as `setContent` strips `\t` characters out unexpectedly.

`\t` is being preserved inside codeblocks, but it should be preserved everywhere

### Browser Used

Chrome

### Expected Behavior

`\t` is preserved

### Additional Context (Optional)

These are also lost when setting the initial content of the editor.

Our old editor had `\t` support everywhere and this makes it impossible for us to move users to the new editor because their content would be irreversibly modified.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Can you share what specifically you are testing, because from my understanding setContent should preserve tabs now:
https://github.com/ueberdosis/tiptap/blob/81d3b8a6719098b719b4454462e7283f5745f4c3/demos/src/Commands/InsertContent/React/index.spec.js#L45-L50

**Comment by nperez0111** [comment]
Ah yea so this was the compromise for preserving backwards compatibility. So for setContent you need to set a flag on preserveWhitespace for the whitespace to be respected. Looking at the source code it will be obvious what you will need to change if you set preserveWhiteSpace to "full" you'll get the same behavior as insertContentAt 

https://github.com/ueberdosis/tiptap/blob/develop/packages/core/src/commands/setContent.ts

**Comment by nperez0111** [comment]
I think that you should be able to `preserveWhitespace` by setting `parseOptions` on the editor options: https://github.com/ueberdosis/tiptap/blob/e31673d347bf764b8c2748eca50267eef6c66734/packages/core/src/Editor.ts#L298

So it should look like this:

```js
const editor = useEditor({
    parseOptions:{
      preserveWhitespace: 'full',
    },
    content: 'content'
 ```

**Comment by Nantris** [comment]
Thank you so much for the tip @nperez0111 and apologies for overlooking it in the docs. It works great.
