### ISSUE TITLE
[Bug]: The "clearDocument" plugin in the core keymap extension can cause issues with custom node change commands.

### ISSUE THREAD

**Issue by AlansCodeLog** [ueberdosis/tiptap#5490]
### Affected Packages

core

### Version(s)

2.6.2

### Bug Description

I'm writing a block based with a list like schema. The blocks can be different types and I've written a command to switch between them while preserving content. Now, some of the blocks have content and other are contentless.

The command works fine *except* if there is only one contentless node in the document and it's empty. Instead of turning into the block type I want, it turns into a paragraph.

It took some digging to find out why this was, my transaction doc was showing the change but the document wasn't. Turns out there's a clearDocument plugin in the Keymap core extension that was doing this. It can't tell the difference between a transaction that changes the node type like I'm doing and the clearing of the document (am not sure if it's possible) so it clears the document.

https://github.com/ueberdosis/tiptap/blob/da76972998e36a7c13c085d5cd1957f6e0ad8a90/packages/core/src/extensions/keymap.ts#L104

I don't really think this should be core behavior (no other core plugin appends transactions), but if it must be, could it be possible to have the plugin check for some ignore meta key to ignore certain transactions? 

I've gotten around this by disabling core extensions and then re-adding all except a modified version of the Keymap extension without the plugin, but that's a bit messy and annoying. If I published the extensions that make up my editor as a library, downstream users would have to do this as well. 

### Browser Used

Chrome

### Code Example URL

https://codesandbox.io/p/sandbox/tiptap-issue-v7mm9r

### Expected Behavior

In the reproduction I've recreated a tiny bit of my schema and onMounted it tries to change the contentless block to a code block, but instead it's a paragraph. 

If you uncomment the fix part that disables core extensions and adds all except the keymap, you can see it properly changes to a code block like I would expect.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
> but if it must be, could it be possible to have the plugin check for some ignore meta key to ignore certain transactions?

I have to be honest, in most situations, I would think that the behavior of how it works now is ideal (most people wouldn't clear the doc just to have a codeblock stick around.

That said, I think your alternate solution of having a meta key to disable this is a good compromise & I'd be happy to accept a PR for that

**Comment by nperez0111** [comment]
https://github.com/ueberdosis/tiptap/blob/c52a6026fcdd6e3e0867a395ef85a28aa91cd90e/packages/core/src/extensions/keymap.ts#L122
And now that I'm looking at this code, this is expensive to check, we should use `isNodeEmpty` instead, would love for that change to be included in the PR

**Comment by AlansCodeLog** [comment]
I just found it a bit weird that it's part of the minimal core behavior, but so long as I can easily avoid it, that's fine.

Does `preventClearDocument` sound okay for the key?

I can make a PR with both changes.

**Comment by nperez0111** [comment]
Yea that name works. Thanks. 

Yea I understand there is a fine line between making something a user would expect and a headless core.

**Comment by nperez0111** [comment]
Oh and maybe you could disable the plugin altogether with coreExtensionOptions:
https://github.com/ueberdosis/tiptap/blob/5283a51931a0ba71a5ae4a155a7814532fa31277/packages/core/src/types.ts#L75-L79

**Comment by AlansCodeLog** [comment]
I saw `coreExtensionOptions`, but didn't see any options to disable the plugin... only `enableCoreExtensions` which disables all. Or do you mean add an option to do that in the PR?

I did think about suggesting more fine-grained control over the core extensions, but so far only this one has caused me any issues and I did think the easier fix was the meta flag.

**Comment by nperez0111** [comment]
I meant to add an option.

**Comment by nperez0111** [comment]
This has been released with 2.7.0-pre.0 and will be released in tiptap 2.7.0 when this beta has been tested by more users

**Comment by nperez0111** [comment]
This is released with v2.7.0 https://github.com/ueberdosis/tiptap/releases/tag/v2.7.0
