### ISSUE TITLE
[Bug]: Collaboration cursor flickering

### ISSUE THREAD

**Issue by tehbelinda** [ueberdosis/tiptap#5492]
### Affected Packages

extension-collaboration-cursor, react

### Version(s)

2.6.0

### Bug Description

When a user focuses on the editor in a way that makes the user's cursor visible, other users will see their cursor flickering rapidly. The behaviour is like that seen in https://github.com/ueberdosis/tiptap/issues/4482 (and potentially also https://github.com/ueberdosis/tiptap/issues/4993)

### Browser Used

Chrome

### Code Example URL

https://codesandbox.io/p/devbox/condescending-galileo-9djp46

(I forked the sandbox from https://github.com/ueberdosis/tiptap/issues/4482 but updated the packages to 2.6.0)

### Expected Behavior

The cursor should be stable, not flickering

### Additional Context (Optional)

Here is a video of it flickering:
https://github.com/user-attachments/assets/fd2ffb8c-243b-4337-9285-9f04067a736e

I tried turning off strict mode (inspired by what happened previously in https://github.com/ueberdosis/tiptap/issues/4482) and the flickering stopped

I noticed there were a bunch of editor lifecycle updates in the react package in 2.5.0+, so I reverted to 2.5.0 - confirmed the flickering still persisted. Then I tried 2.4.0, and the flickering stopped (see https://codesandbox.io/p/devbox/determined-hawking-ts6gfp).

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Thank you for the reproducible example, it was indeed strict mode handling again. StrictMode has weird behaviors, luckily this was not in issue in production or in normal react rendering. StrictMode should be handled correct with `2.6.4` now

**Comment by tehbelinda** [comment]
thank you! appreciate the quick turnaround
