### ISSUE TITLE
[Bug]: Cmd + U not toggling underline

### ISSUE THREAD

**Issue by Ericlm** [ueberdosis/tiptap#5493]
### Affected Packages

extension-underline

### Version(s)

2.6.3

### Bug Description

On the [underline extension doc](https://tiptap.dev/docs/editor/extensions/marks/underline#page-title), it's not possible to toggle underline using the Cmd+U keyboard shortcut.

### Browser Used

Safari

### Code Example URL

https://tiptap.dev/docs/editor/extensions/marks/underline

### Expected Behavior

Expected the shortcut to toggle the underline.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
I just checked and it is working for me?

**Comment by nperez0111** [comment]
I even checked safari... @Ericlm

**Comment by Ericlm** [comment]
Actually, it's stranger than that:
1. Doesn't work
2. Trying Cmd+shift+u works!
3. Also with Cmd+U now, and even when closing/reopening the browser

I think I saw that because it's the very first time I launched tiptap on Safari (I reinstalled my mac). It was the same with Firefox.
I'm gonna try to reinstall Firefox to see if it only occurs on initial launch 🙂

**Comment by nperez0111** [comment]
Not sure what to do about that then...

Let me know if it is reproducible, but it works on chrome & safari for me & we have tests for the shortcut so I expect it to work everywhere 
https://github.com/ueberdosis/tiptap/blob/614fc8082c376bf3c40a05c23ceda6b4a6fbf8d0/demos/src/Marks/Underline/React/index.spec.js#L45-L50

**Comment by Ericlm** [comment]
I couldn't reproduce it, maybe I was in a strange temporal rift 😄
Anyway, thank you!
