### ISSUE TITLE
[Bug]: Lost focus after editor.commands.setImage

### ISSUE THREAD

**Issue by yyyyyyyysssss** [ueberdosis/tiptap#5502]
### Affected Packages

react

### Version(s)

2.6.3

### Bug Description

editor.commands.setImage after focus is lost, the cursor is on the second line and is horizontal after the mouse is clicked again
<img width="698" alt="微信图片_20240816122959" src="https://github.com/user-attachments/assets/d110fea0-7001-4671-8c2b-494979cc8870">

### Browser Used

Chrome

### Expected Behavior

The focus is at the end of the image after insertion

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
I'm sorry but you are going to need to share more info of what happened here. This is not enough information to even know what the problem even is
