### ISSUE TITLE
[Bug]: editor.commands.selectAll() does in fact not select all

### ISSUE THREAD

**Issue by Edunity-Learning** [ueberdosis/tiptap#5516]
### Affected Packages

core

### Version(s)

2.6.4

### Bug Description

Pressing Mod-a in the editor does not select the entire table if its the first node, and therefore Mod-a delete deletes everything except the first table cell. The video below shows the bug. This behaviour can be reproduced by dragging a table to the first position in the [tiptap showcase editor](https://templates.tiptap.dev/zmJJKNRTrz) (or any other tiptap editor)

https://github.com/user-attachments/assets/b3280e7e-75be-4efb-a99f-34861974fb1d

### Browser Used

Chrome

### Expected Behavior

Pressing Mod-a and deletion afterwards should delete all nodes

### Additional Context (Optional)

I fixed the problem by manually creating a text selection instead of using editor.commands.setTextSelection(), so the problem is caused by the implementation of "setTextSelection".
The commented out version does not work
![image](https://github.com/user-attachments/assets/79d510ac-4e60-4986-8ed3-6d40d73c3744)

https://github.com/user-attachments/assets/97ae1183-18c0-4611-8e80-6090ea99579b

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by Nantris** [comment]
I don't understand your video. It appears to show it working fine? And it seems to work fine in my project.

**Comment by Nantris** [comment]
What's the `state.selection.from` after `commands.selectAll`?

**Comment by Edunity-Learning** [comment]
@Nantris what do you mean ? Where does it says "state.selection.from" ?

**Comment by Nantris** [comment]
It's a property of the editor object.

**Comment by Edunity-Learning** [comment]
oh i misread you message. I think it was 4, if i remember it correctly

**Comment by nperez0111** [comment]
This is released with version: `2.11.0`
