### ISSUE TITLE
Drag and Drop. How to claim first the image to the database, and then show it in the editor when image is dragged inside the editor?

### ISSUE THREAD

**Issue by MisterJ936** [ueberdosis/tiptap#552]
I've seen issues like #138, #129, and #89. But none satisfied my longings.

I would like to ask how to upload first in database then returns the images url.
I dont need any modal, or a another page, or an input field.

or is their any function that would replace or override the function for drag and drop image. just like this. I don't know if this, works. I tried it but doesn't work or I have a wrong way doing it:
```
imageCommand(command) {
      let src = '';
      axios.post('url',function(response){
           src = response.imageUrl;
       });

      if (src !== null) {
        command({ src })
      }
}
```

Expected:
When I drag the image, just like here(https://tiptap.scrumpy.io/images)
the image will upload to database then returns the src then add the img tag in the editor in the correct line.

Thanks a lot ? thanks a lot for your help!. 

p.s. This tiptap is really the best editor I have even seen in my entire life of coding, its really good and really creative. :)

**Comment by BrianHung** [comment]
What’s the issue with Slava’s approach at https://github.com/scrumpy/tiptap/issues/138#issuecomment-545894249

**Comment by MisterJ936** [comment]
@BrianHung , oh, yes I've seen it. Do I really need to copy those codes?. But anyway, thanks thanks :)
