### ISSUE TITLE
[PRO]: Changing Heading Level Changes UniqueID

### ISSUE THREAD

**Issue by jan-schweiger** [ueberdosis/tiptap#5522]
### Affected Packages

@tiptap-pro/extension-unique-id

### Version(s)

2.10.11

### Description of the Bug

I have added a unique-id to my headings using the @tiptap-pro/extension-unique-id extension.

```
UniqueID.configure({ types: ['heading'] }),
```

Whenever I change the heading level via my dropdown (see image below) the heading gets a new id. This is in my opinion the wrong behavior, as changing an attribute (level) should definitely not generate new id. Unfortunately, this behavior causes a huge problem in our production application right now, as we use the id of headings to reference headings across documents.

![image](https://github.com/user-attachments/assets/792bac65-8af0-465f-b246-eada47f5fd0f)

I need to use the toggleHeading function for changing the heading level. Simply updating the level attribute instead doesn't work, as it could be the case that the user has selected one or multiple paragraphs that need to become a heading.
```
editor.chain().focus().toggleHeading({ level: newLevel }).run()
```

Here is Tiptap's source code: https://github.com/ueberdosis/tiptap/blob/4ff2a4eaa173f7113e5625c426cebef5913ef628/packages/extension-heading/src/heading.ts#L98

I tried to extend the Heading extension and write me own toggleHeading, however I was not able to fix the issue.

Thank you for your support in advance!!

### Browser Used

Chrome

### Expected Behavior

I want the UniqueId to stay the same for a heading, when the user changes the heading level.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nero-nazok** [comment]
I face the same problem. Can someone look into this?

**Comment by nperez0111** [comment]
So the core of the issue here is that the attributes (the unique id) is not being preserved & therefore it is generating a new unique id.

toggleNode goes through a long chain of prosemirror commands that eventually ends up being a replaceAroundStep (thereby completely replacing the existing node & it's attributes with a new one).

It is funny that you should bring this up because I was working on this sometime last week: https://github.com/ueberdosis/tiptap/pull/5489

**Comment by jan-schweiger** [comment]
Thanks a lot for your support @nperez0111!!

**Comment by nperez0111** [comment]
I haven't got the time to work on this today, but I think that should resolve your problem. Ideally I would add some tests that proves that it works.

**Comment by tanja-kovakic** [comment]
Thank you for working on this one @nperez0111. Do you already have any information for us when this fix will be available?

**Comment by nperez0111** [comment]
We have a lot of changes queued up, so we are planning a beta release next week & see how it goes from there.

**Comment by rosenbauerwillbacker** [comment]
Also looking forward to fix for this issue.

**Comment by nperez0111** [comment]
There is a beta release for 2.7.0 that has this fix.

**Comment by rosenbauerwillbacker** [comment]
Amazing @nperez0111 Thank you so much!

**Comment by rosenbauerwillbacker** [comment]
As the Unique-ID is a pro-plugin, I currently install it by using an .npmrc and running `npm install @tiptap-pro/extension-unique-id` which gives me version 2.11.1. But as this is a pre-release this will not give me the version with the fix right?

Is there another way of accessing a pre-release for a pro-plugin? When will this approximately become a full release?

**Comment by nperez0111** [comment]
The problem was in the oss core not the pro extension so installing the pre release of tiptap should work. Depending on your bundled and package manager it may result in the core being installed raise since the dep range may not match but package managers have ways to override these deps to force resolution to a single version

**Comment by rosenbauerwillbacker** [comment]
Thank you @nperez0111. In our prod environment we can only install full releases of Tiptap core. Thus, we are eagerly looking forward to the official npm release.

**Comment by tanja-kovakic** [comment]
Awesome!! This is really great that this issue is finally resolved.

I tried to install it via npm by adding the following line to my package.json and running `npm install`:
`"@tiptap/react": "git+https://github.com/ueberdosis/tiptap.git#v2.7.0-pre.0"`

Although the package was installed, I cannot run my instance:

```X [ERROR] Failed to resolve entry for package "@tiptap/react". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]```

When will this be a full release? I really hope this will be available soon.

**Comment by jan-schweiger** [comment]
This is really great news @nperez0111. As we use Tiptap in production, it would be good to know when we have the full 2.7.0 release on npm. Hopefully soon :)

**Comment by jan-schweiger** [comment]
It would be good to know how long it takes for fixes to be rolled out to final releases for pro-extensions. If it takes too long we have to find alternative solutions, as we use Tiptap in production. Will 2.7.0 be ready any time soon?

**Comment by nperez0111** [comment]
This is released with v2.7.0 https://github.com/ueberdosis/tiptap/releases/tag/v2.7.0

**Comment by jan-schweiger** [comment]
Amazing, thank you so much Nick! I will try out the new release later today.

**Comment by jan-schweiger** [comment]
Hi @nperez0111,

Thank you for your effort. 2.7.0 has some great fixed 🙂.

Unfortunately this update doesn't resolve this issue.

I updated all tiptap packages to the latest version (2.7+) including the @tiptap-pro/extension-unique-id (2.11.2) pro-extension:
```
"@tiptap/core": "^2.7.2",
    "@tiptap/extension-color": "^2.7.2",
    "@tiptap/extension-highlight": "^2.7.2",
    "@tiptap/extension-image": "^2.7.2",
    "@tiptap/extension-link": "^2.7.2",
    "@tiptap/extension-list-item": "^2.7.2",
    "@tiptap/extension-ordered-list": "^2.7.2",
    "@tiptap/extension-placeholder": "^2.7.2",
    "@tiptap/extension-table": "^2.7.2",
    "@tiptap/extension-table-cell": "^2.7.2",
    "@tiptap/extension-table-header": "^2.7.2",
    "@tiptap/extension-table-row": "^2.7.2",
    "@tiptap/extension-task-item": "^2.7.2",
    "@tiptap/extension-task-list": "^2.7.2",
    "@tiptap/extension-text-align": "^2.7.2",
    "@tiptap/extension-text-style": "^2.7.2",
    "@tiptap/extension-underline": "^2.7.2",
    "@tiptap/pm": "^2.7.2",
    "@tiptap-pro/extension-unique-id": "^2.11.2",
    "@tiptap/react": "^2.7.2",
    "@tiptap/starter-kit": "^2.7.2",
```

Changing the heading level `editor.chain().focus().toggleHeading({ level: 2 }).run()` still regenerates a new id.

Did the fix work for you @rosenbauerwillbacker @tanja-kovakic @nero-nazok?

**Comment by jan-schweiger** [comment]
Everything works as expected, I made a mistake on the update. Thank you so much!! @nperez0111.

**Comment by rosenbauerwillbacker** [comment]
This was a really important fix for me. Thank you!!
