### ISSUE TITLE
How to achieve color highlighting when the user enters certain characters, for example, when entering {{xx}}, the curly brackets and the content in the curly brackets are highlighted

### ISSUE THREAD

**Issue by yrang** [ueberdosis/tiptap#5524]
### Affected Packages

How to achieve color highlighting when the user enters certain characters, for example, when entering {{xx}}, the curly brackets and the content in the curly brackets are highlighted

### Version(s)

How to achieve color highlighting when the user enters certain characters, for example, when entering {{xx}}, the curly brackets and the content in the curly brackets are highlighted

### Bug Description

How to achieve color highlighting when the user enters certain characters, for example, when entering {{xx}}, the curly brackets and the content in the curly brackets are highlighted

### Browser Used

Chrome

### Expected Behavior

How to achieve color highlighting when the user enters certain characters, for example, when entering {{xx}}, the curly brackets and the content in the curly brackets are highlighted

### Additional Context (Optional)

How to achieve color highlighting when the user enters certain characters, for example, when entering {{xx}}, the curly brackets and the content in the curly brackets are highlighted

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
This should not be an issue, you already made a discussion, I answered it there.
