### ISSUE TITLE
Feature suggestion: Add support for liquid tags

### ISSUE THREAD

**Issue by connecteev** [ueberdosis/tiptap#553]
[Liquid Tags](https://shopify.github.io/liquid/) were introduced by shopify and have been widely adopted in a lot of editors, CMS's and comment editors online. Liquid tags allow for a really rich publishing and consumption experience.

I think I speak for a lot of devs when I say that this would be a killer feature that would get a lot more of us using TipTap. Common use cases involve embedding other articles from our sites, embedding user profiles, embedding external content (YouTube videos, StackOverflow questions, etc). A couple of examples on how to do this and build on the core library would be great.

To that end, it would be really cool if TIpTap was able to do something like this:
https://dev.to/new#liquidtags (make sure you click on the '?' icon on the bottom to see the liquid tags guide, where this is adopted from)

The goal being to be able to allow embeds of any of the following:
### Internal:
1. Article/Posts (Ex: [here](https://dev.to/devteam/medium-was-never-meant-to-be-a-part-of-the-developer-ecosystem-25a0))
2. Comments.(Ex: https://dev.to/rhymes/comment/e07o)
3. Tags
4. Topics
5. Users (ex: https://dev.to/devteam/expanding-the-dev-core-team-5b0g)

### External:
(popular ones only listed below)
1. Videos like Youtube
2. Twitter posts
3. Medium posts
4. Slideshare slides
5. Soundcloud audio snippet
6. Spotify song or audio snippet

## Internal:
1. Article/Post Embeds (Ex: https://dev.to/devteam/medium-was-never-meant-to-be-a-part-of-the-developer-ecosystem-25a0)
```
using the full link of the article:

{% link https://www.mydomain.com/kazz/boost-your-productivity-using-markdown-1be %}

using the slug like this:

{% link kazz/boost-your-productivity-using-markdown-1be %}
```

2. Comment Embeds (example: https://dev.to/rhymes/comment/e07o)
```
All you need is the ID at the end of a comment URL. To get the comment link, click either the timestamp or the menu button in the top right corner on a comment and then click "Permalink". Here's an example:

{% devcomment 2d1a %}
```

4. Tag Embeds
```
All you need is the tag name:

{% tag git %}
```

5. Topic Embeds
```
All you need is the topic name:

{% topic ux %}
```

6. User Embeds: Example [here](https://dev.to/devteam/expanding-the-dev-core-team-5b0g)
```
All you need is the username:

{% user jess %}
```

## External:
(I took the most popular ones that made sense to me):

1. Video Embeds
```
All you need is the id from the URL.

YouTube: {% youtube dQw4w9WgXcQ %}
Vimeo: {% vimeo 193110695 %}
```

2. Twitter Embeds
```
Using the Twitter Liquid tag will allow the tweet to pre-render from the server, providing your reader with a better experience. All you need is the tweet id from the url.

{% twitter 834439977220112384 %}
```

3. Medium Embeds
```
Just enter the full URL of the Medium article you are trying to embed.

{% medium https://medium.com/s/story/boba-science-how-can-i-drink-a-bubble-tea-to-ensure-that-i-dont-finish-the-tea-before-the-bobas-7fc5fd0e442d %}

```

4. SlideShare Embed
```
All you need is the SlideShare key

{% slideshare rdOzN9kr1yK5eE %}
```

5. Soundcloud Embed
```
Just enter the full URL of the Soundcloud track you are trying to embed.

{% soundcloud https://soundcloud.com/user-261265215/dev-to-review-episode-1 %}
```

6. Spotify Embed
```
Enter the Spotify URI of the Spotify track / playlist / album / artist / podcast episode you are trying to embed.

      {% spotify spotify:episode:5V4XZWqZQJvbddd31n56mf %}
```

**Comment by calumk** [comment]
Hey, 
Aware this is very very out of date now, but this is marked as "completed" and yet i cant find any reference to this ever being implemented.

Was it implemented and then scrapped? or was it never included.

**Comment by nperez0111** [comment]
This definitely is not in scope for Tiptap to implement

**Comment by calumk** [comment]
Fair. 
Would it be possible to implement via plugin? 

Is there any existing plugin your aware of that does something similar that I could look at to build upon?
