### ISSUE TITLE
How to block multiple spaces between text?

### ISSUE THREAD

**Issue by m7rlin** [ueberdosis/tiptap#554]
Basically is it possible to block user from entering multiple spaces between text and on the end of the line? Now you can add as many spaces as you want but I was wondering if it cound be changed like in the Medium.com editor you can't type multiple spaces.

Allowed:
```
text<space>text
```
Disallowed:
```
text<space><space>text
text text<space><space><space><space>
```

**Comment by andreasvirkus** [comment]
Related: is there an easy way to trim the value that tiptap exposes? The simplest example is `<p>     Some text      </p>`. Vue provides us with `v-model.trim` and it'd be lovely if tiptap could expose an interface for this/handle it editor-side 🙏

**Comment by philippkuehn** [comment]
You can build a ProseMirror Plugin with a [filterTransaction](https://prosemirror.net/docs/ref/#state.PluginSpec.filterTransaction) hook for that.
