### ISSUE TITLE
[Bug]: How do I display svg and child elements

### ISSUE THREAD

**Issue by ls-v** [ueberdosis/tiptap#5543]
### Affected Packages

core

### Version(s)

2.6.5

### Bug Description

How do I retain display svg elements

### Browser Used

Chrome

### Code Example URL

https://codesandbox.io/p/sandbox/young-cache-xj3322?file=%2Fsrc%2Findex.js%3A19%2C35

### Expected Behavior

Display svg elements

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Tiptap is based on Prosemirror, and it is not an arbitrary HTML editor, it is a rich text editor that needs to have full control of the HTML that it is editing to make changes to it. Prosemirror does this by attempting to parse the content in such a way that it conforms to a schema (which is derived from the nodes & marks that you specify as Tiptap extensions), this means content which does not conform to the schema WILL BE LOST. This is a tradeoff, Prosemirror can accept a fair amount of HTML content & parse it into a structured format but it cannot reliably do so with arbitrary HTML (liberal in what it accepts, strict in what it outputs).

SVG is not supported as content.
