### ISSUE TITLE
[Bug]: warning when using multiple mention extensions

### ISSUE THREAD

**Issue by sezaru** [ueberdosis/tiptap#5549]
### Affected Packages

extension-mention

### Version(s)

2.6.6

### Bug Description

I want to have multiple instances using the mention plugin for different purposes in the same editor.

To achieve that, I just need to set the `pluginKey: new PluginKey('user'),` option in the suggestion attribute.

As far as I can see, it does works fine, but the console will give me the following warning:

```
[tiptap warn]: Duplicate extension names found: ['mention']. This can lead to issues.
```

This is because the mention extension has its name set to `'mention'` without any wait to customize it.

### Suggestion of a fix

Allow the user to override the mention extension name by setting their own custom name.

### Browser Used

Firefox

### Expected Behavior

The warning is correct, so the behavior is expected, but that means that currently there is no good/supported way to have more than one mention extension in the same editor. Allowing the use to customize that extension name should fix the warning and keep everything working.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
`.extend({ name: 'custom-mention-name' })`
