### ISSUE TITLE
[Bug]: Needs to replace HTML into TrustedHTML in elementFromString function.

### ISSUE THREAD

**Issue by rafaelhovhannisyan24** [ueberdosis/tiptap#5559]
### Affected Packages

core

### Version(s)

2.6.6

### Bug Description

 const policy = window.trustedTypes.createPolicy('tiptap', {
    createHTML: (input) => input,
    createScript: (input) => input,
    createScriptURL: (input) => input,
  });

export function elementFromString(value: string): HTMLElement {
  // add a wrapper to preserve leading and trailing whitespace
  const wrappedValue = policy.createHTML(`<body>${value}</body>`)

  const html = new window.DOMParser().parseFromString(wrappedValue, 'text/html').body

  return removeWhitespaces(html)
}

### Browser Used

Chrome

### Expected Behavior

While using it on platform which has Trusted Types security concerns, Tiptap throughs following issue:

`index.js:60354 This document requires 'TrustedHTML' assignment.`

`TypeError: Failed to execute 'parseFromString' on 'DOMParser': This document requires 'TrustedHTML' assignment. at elementFromString`

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by rafaelhovhannisyan24** [comment]
Also in VueJS there is an update referring to issue described:

`runtime-dom: Trusted Types compatibility` [3.5.0-beta.1](https://github.com/vuejs/core/compare/v3.4.37...v3.5.0-beta.1)

**Comment by nperez0111** [comment]
This would need to be changed by prosemirror, our base library.

This looks like a lot of work to implement, I have no plans on supporting this at this time unless it is actually supported by other browsers.

**Comment by rafaelhovhannisyan24** [comment]
TipTap doesn't work in environments where a Trusted Types policy is enforced. It has nothing to do with browser support.

**Comment by nperez0111** [comment]
<img width="781" alt="image" src="https://github.com/user-attachments/assets/dfe60a4d-6659-4192-b00e-d26e47505f64">

If it isn't implemented by other browsers, it does have to do with browser support.

If this is a requirement for you, feel free to contribute a PR for it. But I don't think that this is an issue with Tiptap so much as chrome making up APIs

**Comment by nperez0111** [comment]
It is also [only a draft W3C spec](https://w3c.github.io/trusted-types/dist/spec/), so I'm not going to spend the time on a non web standard just because you ask for it

**Comment by rafaelhovhannisyan24** [comment]
https://github.com/ueberdosis/tiptap/pull/5561. I fixed it. I didn't take much time to fix. I guess there will be some code clean up. Hope you'll do that easily.

**Comment by llusinepetrosyan** [comment]
@nperez0111  I also had same issue and seems @rafaelhovhannisyan24(thank you) fixed it on this pr - https://github.com/ueberdosis/tiptap/pull/5561
Can we speed up review/merge process please @nperez0111 ?

**Comment by matt-lohkamp-pa** [comment]
I was excited to roll Tiptap into our ui, and it's somewhat disappointing to see this has been a known issue for a year and a half - 

> I don't think that this is an issue with Tiptap so much as chrome making up APIs

support has broadened considerably since this issue was first logged - FF is the only straggler, and even then, if it's already in nightly builds, it's pretty likely a full release comes soon (and spreading awareness and support is a good push in that direction)

<img width="788" height="678" alt="Image" src="https://github.com/user-attachments/assets/8596dd39-8b26-441e-a01f-ae688c16f4f3" />

> It is also [only a draft W3C spec](https://w3c.github.io/trusted-types/dist/spec/), so I'm not going to spend the time on a non web standard just because you ask for it

the w3c working draft has also progressed as of last month: https://www.w3.org/TR/trusted-types/

Are Trusted Types policies at a point where support is a reasonable request yet?
