### ISSUE TITLE
[PRO]: Cannot use multiple math delimiters at the same time

### ISSUE THREAD

**Issue by felixgabler** [ueberdosis/tiptap#5565]
### Affected Packages

extension-mathematics

### Version(s)

2.11.1

### Description of the Bug

We need to support `$ ... $`, `\[ ... \]`, and `\( ... \)` to delimit math.

Here is the regex that should detect them all:

`/\$([^$]*)\$|\\\[(.*)\\\]|\\((.*)\\)/g`

In fact, it will always detect the delimiters that are mentioned first, so I know that they work individually. There must be an issue in how the matches are processed that leads to only the first group being accepted for each match

### Browser Used

Chrome

### Expected Behavior

I expect this:

```
\[1 + 3\]
<br>
\(1+2\)
<br>
$1 + 4$
```

to render all in maths mode but I get

![image](https://github.com/user-attachments/assets/bf38eda3-8c72-4cb6-96b6-96efe14e815d)

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
The docs should be better around this but you would need to capture group of your reflex to match only the content you want to be rendered as math. So the reflex you have now is not sufficient

**Comment by felixgabler** [comment]
Sorry, I think I don't understand. Why does it work if I take each individual part? Also if I take the "official", default regex into regex101, it will correctly identify the content inside the dollar signs. If I extend it with my regex, it will do the same for `\[` and `\(` too, i.e., exactly the same characters are in the group, without the delimiters. What would I need to change to make it work?

**Comment by nperez0111** [comment]
I think you should look into capture groups and how they work. 

Capture groups are the ( ) which denote a grouping of content to be matched. In your Regex you have 3 separate ones. As I said, we only pull from the first. Not the first "matching" group. 

Your regex can be rewritten such that there is only a single Regex capture group. You can do this by making your delimiters be ORs on either side of your capture group.

**Comment by felixgabler** [comment]
Great! I rewrote the regex to `/(?:\$|\\\(|\\\[)([^$\\)\]]*)(?:\$|\\\)|\\\])/g`, and it now works. However, it does introduce a potential issue because it will also match things like `$ 1 + 2 \)`, which isn’t ideal and could lead to unexpected behavior in certain cases.

Given this, how reasonable would it be to allow drawing from multiple capture groups? This would make the regex cleaner and more accurate. Alternatively, it would be really helpful if the documentation could mention this limitation and perhaps suggest the regex above as a workaround.

**Comment by nperez0111** [comment]
Well to be honest having multiple ways to trigger it is not really what the regex is for.

**Comment by felixgabler** [comment]
Actually, it seems like the new regex does not work after all. Without support for multiple capture groups, I am not sure how we can enforce same opening and closing delimiters. E.g., there are now issues with `... \[ 1 + 3 \] can be simplified to $4$ ...` not being parsed correctly and ending up as 
![Screenshot 2024-08-29 at 16 33 18](https://github.com/user-attachments/assets/c6010fe8-546c-4228-9a89-753d59b215df)

How would you solve this without multiple capture groups?

**Comment by nperez0111** [comment]
I updated the extension to support multiple capture groups, it will only ever match the first one that is matched. You can use a regex like: `/\$([^$]*)\$|\\\(([^)]*)\\\)|\\\[([^\]]*)\\\]/gi` to achieve what you were looking for
