### ISSUE TITLE
[Bug]: incorrect createParagraphNear

### ISSUE THREAD

**Issue by evskorobogatij** [ueberdosis/tiptap#5566]
### Affected Packages

core

### Version(s)

2.3.1

### Bug Description

We need create new paragraph anter current node (paragraph, list, image etc.)

We detect current cursor pos:

```
 const coordinates = view.posAtCoords({
          left: e.clientX,
          top: e.clientY,
        });
```

and then try create new paragraph
```
editor
          .chain()
          .focus(coordinates.pos)
          .createParagraphNear()
          .insertContent('info....')
          .run();
```

But paragraph creates before node under cursor. How to fix them?

### Browser Used

Edge

### Expected Behavior

New paragraph created after active node

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
createParagraphNear does what it says. It does not guarantee ordering of the position. You probably want to do an insertContentAt instead to pick the position and insert it.

**Comment by evskorobogatij** [comment]
editor.chain().focus().insertContentAt(nodePos, '/').run();

Creates paragraph before current paragraph.  Why?
