### ISSUE TITLE
[PRO]: Editor content not updated with response from AI

### ISSUE THREAD

**Issue by OlaAlsaker** [ueberdosis/tiptap#5568]
### Affected Packages

extension-ai

### Version(s)

2.11.1

### Description of the Bug

Content in editor is not replaced with the AI's response. Even though Tiptap's API responds with a response, the content in the editor is not updated. Also, setting `stream: true`, just makes the content go blank.

This happens in Vue 3.

Weird thing is that is "suddenly" started to happen. The AI has worked perfectly fine earlier.

This is my current code:

```vue
<template>
	<PageBody>
		<Section>
			<button @click="editor.chain().focus().aiFixSpellingAndGrammar().run()">
				AI fix grammar
			</button>
			<button @click="editor.chain().focus().aiTranslate('de').run()">
				AI translate to german
			</button>
			<editor-content :editor="editor" />
		</Section>
	</PageBody>
</template>
<script setup lang="ts">
import Ai from '@tiptap-pro/extension-ai';
import StarterKit from '@tiptap/starter-kit';
import { Editor, EditorContent, useEditor } from '@tiptap/vue-3';
import { ShallowRef } from 'vue';

const editor = useEditor({
	content: `
      <p>
        Rocking like a mobile?
      </p>
      <p>
        Did you hear about the mobile phone that joined a rock band? Yeah, it was a real smartTONE!
        It rocked the stage with its gigabytes of rhythm and had everyone calling for an encore, but
        it couldn't resist the temptation to drop a few bars and left the audience in absolute silence.
        Turns out, it wasn't quite cut out for the music industry.
      </p>
      <p>
        They say it's now pursuing a career in ringtone composition. Who knows, maybe one day it'll top
        the charts with its catchy melodies!
      </p>
      <p></p>
    `,
	extensions: [
		StarterKit.configure({
			history: false,
		}),
		Ai.configure({
			appId: '<removed>',
			token: '<removed>',
		}),
	],
}) as ShallowRef<Editor>;
</script>
```

I select the text, but none of the buttons actually do anything to the content. They send an API request to Tiptap's backend:

<img width="291" alt="image" src="https://github.com/user-attachments/assets/7e64e835-4a91-456a-ba80-8e69e19a3c87">

-

<img width="483" alt="image" src="https://github.com/user-attachments/assets/a14e8595-7295-4781-834d-2eec4a3dfec3">

And the backend responds correctly:

<img width="501" alt="image" src="https://github.com/user-attachments/assets/fa6501a9-da71-45c6-80dd-92147e8b8c07">

However, the content in the editor is not updated:

<img width="1578" alt="image" src="https://github.com/user-attachments/assets/055dccfc-9a79-47fc-b4fd-75bde5b54220">

### Browser Used

Chrome

### Expected Behavior

I expect the editor's content to be replaced with the response from your AI-service.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Sorry @OlaAlsaker, I did not see this because I was on vacation, are you still having this issue?

**Comment by OlaAlsaker** [comment]
Actually, it works now! We have not made any changes, but it works. So probably something related to TipTap's AI API 😄

**Comment by nperez0111** [comment]
Oh alright great! That response did look a bit strange. I'll close this then
