### ISSUE TITLE
Allow cropping (and other transformations) of uploaded images

### ISSUE THREAD

**Issue by connecteev** [ueberdosis/tiptap#557]
Allow cropping (and other transformations) of uploaded images in tiptap-core.
See the examples here: https://www.tiny.cloud/docs/demo/full-featured/
In the case of TinyMCE, when you click on an image, you are shown icons to flip image horizontally / vertically, and to edit the image. If you click the 'Edit Image' button, you are further given options to crop, resize image, rotate, change brightness, blur /sharpen, contrast, color, gamma, invert.

**Comment by brandonjoyce2** [comment]
@hanspagel Could you provide a link to the documentation of this feature?
