### ISSUE TITLE
[Bug]: Dragging Only A Part Creates Duplicate Unique-ID

### ISSUE THREAD

**Issue by rosenbauerwillbacker** [ueberdosis/tiptap#5578]
### Affected Packages

@tiptap-pro/extension-unique-id, @tiptap-react

### Version(s)

2.10.11

### Bug Description

**Simple steps to reproduce:**
1. Visit the official Tiptap demo: https://tiptap.dev/docs/editor/extensions/functionality/uniqueid
2. Select a small text part of the heading. (e.g. "very")
![image](https://github.com/user-attachments/assets/248617fe-1406-4213-a50e-ae359b247d30)
3. Drag it to an empty space, so that it creates a new node.
![image](https://github.com/user-attachments/assets/f4cb058c-7d16-4980-8d77-c035b12284d6)

As you can see we have now created two nodes with a duplicate id. I have also reproduced that locally with the latest packages.

**Quick-Fix**
We have fixed it by automatically forcing the user to select the whole heading.

```
addProseMirrorPlugins() {
    return [
      new Plugin({
        props: {
          // Select the entire heading nodes when they are dragged
          handleDOMEvents: {
            dragstart(view, event) {
              const { state, dispatch } = view;
              const { doc, selection } = view.state;
              const { from, to} = selection;

              let minFrom = from;
              let maxTo = to;
              doc.nodesBetween(from, to, (node, pos) => {
                if (node.type.name === 'heading') {
                  minFrom = Math.min(minFrom, pos);
                  maxTo = Math.max(maxTo, pos + node.nodeSize);
                }
              });
              if (minFrom !== from || maxTo !== to) {
                const tr = state.tr.setSelection(
                  TextSelection.create(state.doc, minFrom, maxTo)
                );
                dispatch(tr);
              }
            }
          }
        }
      })  
    ];
  },
```

**Info**
Our team would really like to use this pro extension in production. However, this is the third bug we have encountered after testing it for two days. Is this extension considered stable or is it experimental?

It would be great if some additional logic or automated tests would be added that ensures the stability of this great plugin. We have a business-critical application and having suddenly two nodes with duplicate ids poses a big threat to us.

Thank you very much in advance for your help.

### Browser Used

Chrome

### Expected Behavior

Unique-ids should be unique as the name suggests.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Hm that is strange because it should be rewriting if there is every a duplicate ID valid bug on our side that @bdbch could help with

**Comment by marciaterzo** [comment]
Any updates on this one @bdbch @nperez0111? This is actually a huge problem, because I expect ids to be unique as they should.

Unfortunately, the Unique-ID is a pro plugin, so the code is obfuscated.

Thank you in advance!!

**Comment by marciaterzo** [comment]
Thank you @bdbch!

**Comment by bdbch** [comment]
@guarmo looked into it and pushed a fix for this. :) Should hit live soon.

**Comment by markbulingit** [comment]
So for this bug to disappear we have to purchase PRO?

**Comment by nperez0111** [comment]
> So for this bug to disappear we have to purchase PRO?

The bug is in the PRO extension so not sure what you are referencing here?
