### ISSUE TITLE
[Bug]: isEditable in Vue3 is not reactive

### ISSUE THREAD

**Issue by litingyes** [ueberdosis/tiptap#5591]
### Affected Packages

@tiptap/vue-3

### Version(s)

latest

### Bug Description

`isEditable` is not change when run `setEditable`

### Browser Used

Chrome

### Code Example URL

https://stackblitz.com/edit/tiptap-vue3-is-editable?file=src%2Fcomponents%2FEditor.vue

### Expected Behavior

`isEditable` is reactive

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by litingyes** [comment]
I think more responsive properties need to be exposed

**Comment by nperez0111** [comment]
Feel free to open a PR to fix this. But we do not have plans to implement this ourselves

**Comment by litingyes** [comment]
> Feel free to open a PR to fix this. But we do not have plans to implement this ourselves

i will try
