### ISSUE TITLE
[Bug]: 2.7.0-pre.0 breaks some input rules and breaks undoing many more of them

### ISSUE THREAD

**Issue by Nantris** [ueberdosis/tiptap#5598]
### Affected Packages

core

### Version(s)

2.7.0-pre.0

### Bug Description

Input rule no longer behaves as it had, and even apparently unaffected rules cannot be undone.

### Browser Used

Chrome

### Expected Behavior

Upgrade does not break existing input-rule

### Additional Context (Optional)

Also ran `yarn upgrade` in case it was a ProseMirror dependency that needed upgrading, but no change.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by Nantris** [comment]
Actually, also breaks the inability to undo the broken logic caused by this input rule. It instantly reverts after `Ctrl+Z`.

**Comment by Nantris** [comment]
The `InputRule` is lengthy with a lot of custom logic that would need to be explained, but fortunately I think the issue is the args it's receiving which hopefully will help to get this resolved.

## Functional:
![image](https://github.com/user-attachments/assets/aabddc4e-2c70-409b-81f2-7e2db0cf2e2e)


## Broken:
![image](https://github.com/user-attachments/assets/ba3854bb-e36a-4ba4-8df1-c2af7fb08a33)

**Comment by Nantris** [comment]
I've ruled out recent changes to `prosemirror-view` as candidates for the cause of this.

Any ideas for the cause @nperez0111? Or any more info I can provide? I'm not sure why the state's `scrollToSelection` and the `range` would be different in `2.7.0` versus `2.6.6`.

**Comment by Nantris** [comment]
I guess maybe it's related to #5261. Assuming that's the cause, I do see value in that PR, but I'm not sure how we could modify our existing logic to function alongside it.

**Comment by Nantris** [comment]
Confirmed #5261 is the cause, sadly.

**Comment by nperez0111** [comment]
Can you give more information to what has changed between the two? I had a lot of hesitation around that change which is why I made the pre version.

Just saying that the values of arguments changed between the two is not enough to warrant a rollback. Since, I did not see an issue with it in my testing of it.

re: breaking undo, input rules seem to have always had this behavior, I checked before this change was introduced and on 2.4.0 and it always had that, so that would warrant a separate issue than this.

**Comment by Nantris** [comment]
Unfortunately I can't share the code for the actual input rules, and if I could they'd not be very helpful since they use some custom helpers which I also can't share the code for.

I can at least share the regex, though I doubt that's much help.

```js
const bulletListMarkdownRegex = /^(-) $/;
const orderedListMarkdownRegex = /^(\d+)\. $/; // Based on TipTap but only accept space as trigger, not enter: https://github.com/ueberdosis/tiptap/blob/43a6a865c80d36cf9ea83f19ef650806cfb440d6/packages/extension-ordered-list/src/ordered-list.ts#L24
```

> re: breaking undo, input rules seem to have always had this behavior,

I'm not sure what behavior you mean. I haven't seen this issue personally, but I did confirm that that PR specifically was what was causing the undo issues in our case.
