### ISSUE TITLE
[Bug]: Performance Issue when documents have ReactNodeViewRenderer

### ISSUE THREAD

**Issue by rajatkulkarni95** [ueberdosis/tiptap#5599]
### Affected Packages

core, react

### Version(s)

2.6.2

### Bug Description

Attaching two videos, one with `ReactNodeViewRenderer` used for `Table` / `Image` and `CodeBlock`, and the other without them.

The doc has 10k words in it, and you can see via the FPS Counter that the former causes huge drops.

With `ReactNodeViewRenderer`

https://github.com/user-attachments/assets/bb410740-3dfb-4659-8bb7-6842fac1497b

Without it

https://github.com/user-attachments/assets/49e1539b-8430-4dd8-8346-a3b5a41103e0

### Browser Used

Safari

### Expected Behavior

It shouldn't have this stark of a difference in performance.

### Dependency Updates

- [x] Yes, I've updated all my dependencies.

**Comment by Nantris** [comment]
Your initial video shows both much higher and much lower values than the second video - but I wouldn't expect to see substantially higher values at any time. Just a bit odd.

I wonder if your results change if the cursor isn't hovering the page. Perhaps there's some interaction with mouse handler logic that could be addressed.

**Comment by rajatkulkarni95** [comment]
> Your initial video shows both much higher and much lower values than the second video - but I wouldn't expect to see substantially higher values at any time. Just a bit odd.
> 
> 
> 
> I wonder if your results change if the cursor isn't hovering the page. Perhaps there's some interaction with mouse handler logic that could be addressed.

The FPS fluctuates, but there's a huge drop when react node views are used compared to not. Like scrolling becomes an actual problem even if there's like a few custom tables vs the default ones.

**Comment by nperez0111** [comment]
I think @Nantris is right here, scrolling should have no effect on re-rendering so you must have some logic that has to do with mouse hovering or scroll events or something. 

React does incur a cost per render, but I've spent a lot of time recently to make it as fast as possible with Tiptap 2.5 and further updates. So it is as fast as could possibly be. 

So there is likely something wrong in your application not necessarily running things in React.
