### ISSUE TITLE
Support Text alignment (left, right, center, justify)

### ISSUE THREAD

**Issue by connecteev** [ueberdosis/tiptap#562]
Support Text alignment (left, right, center, justify)
As seen here:
https://ckeditor.com/ckeditor-5/demo/#document
Once again, I would add support for this in core, so the dev can enable it if need be, and an example to the example repo that makes use of the core repo.
Note: this is an attempt to reopen https://github.com/scrumpy/tiptap/pull/84

**Comment by tszulc** [comment]
Possible solution: scrumpy/tiptap#544

**Comment by connecteev** [comment]
@tszulc thanks for responding. Would love to see this merged in (or the feature built) by the core team.

**Comment by hanspagel** [comment]
Good news here too: This will be supported in [tiptap v2](https://blog.ueber.io/post/our-plan-for-tiptap-2/). 👍
