### ISSUE TITLE
[Bug]: Regression 2.7

### ISSUE THREAD

**Issue by splincode** [ueberdosis/tiptap#5625]
### Affected Packages

all

### Version(s)

2.7.0

### Bug Description

<img width="1302" alt="image" src="https://github.com/user-attachments/assets/9d187ec9-4ca6-4278-b20e-0462b51ecea4">

Upgrade to 2.7

### Browser Used

Chrome

### Code Example URL

https://github.com/taiga-family/editor/pull/1395

### Expected Behavior

Works as well

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
You will have to update your typings to the new implementation. You were assuming the NodeViewProps corresponds 1-1 with NodeView's constructor which is not actually the case. Functionality is all the same, it is the types that are different and more correct now so we do not see this as a regression
