### ISSUE TITLE
Support Multiple font families

### ISSUE THREAD

**Issue by connecteev** [ueberdosis/tiptap#563]
As seen here:
https://ckeditor.com/ckeditor-5/demo/#document
Once again, I would add support for this in core, so the dev can enable it if need be, and an example to the example repo that makes use of the core repo.
Note: this is an attempt to reopen https://github.com/scrumpy/tiptap/pull/84

**Comment by hanspagel** [comment]
Good news, this will be part of the core with [tiptap v2](https://blog.ueber.io/post/our-plan-for-tiptap-2/). Thanks for the suggestion! 🙌
