### ISSUE TITLE
Better support for tables

### ISSUE THREAD

**Issue by connecteev** [ueberdosis/tiptap#564]
Add Better support for tables

There is absolutely no comparison between https://tiptap.scrumpy.io/tables
and the tables feature of CK Editor here: https://ckeditor.com/ckeditor-5/demo/#document
CKEditor kills it in this domain - adding / deleting rows or columns, merging cells / columns up/down works seamlessly, and the result is beautifully clean.
So once again, I would add support for this in the extensiond repo, so the dev can enable it if need be, and an example to the example repo that makes use of it.

**Comment by Alecyrus** [comment]
By calling the APIs of `Table Cell` Node and rendering the `bubblemenu` Conditionality， the feature like CK editor is very easy to implement.  Tiptap is more like a high-level wrapper for Prosemirror, which is a toolkit for building rich-text editors. So you'd learn to build your own text-editor based on tiptap.  Enjoy!

**Comment by khash** [comment]
Two questions regarding your comment @Alecyrus 

1. I can't find any examples of rendering a bubble menu conditionally, can you please shed some light on how?
2. Does this mean for table / cell relation actions, the user should first make a selection inside of the table so the bubble menu shows up?
