### ISSUE TITLE
[Bug]: Vue 3 - editor destroyed before transitioning out is done 

### ISSUE THREAD

**Issue by Ericlm** [ueberdosis/tiptap#5646]
### Affected Packages

@tiptap/vue-3

### Version(s)

2.6.6^

### Bug Description

When using the Vue package, and wrapping the editor within a Transition with v-if makes the editor disappear before the end of the transition. The onDestroy hook is called before unmounting other Vue components.

### Browser Used

Firefox

### Code Example URL

https://codesandbox.io/p/devbox/dazzling-kate-rczsdc

### Expected Behavior

The editor should be destroyed only when the transition has ended.

### Additional Context (Optional)

Linked issue : #2296

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
I would totally accept a patch here, I don't have enough knowledge of vue to know what the right solution is here

**Comment by nperez0111** [comment]
This is released with v2.9.0
