### ISSUE TITLE
Extension to support Chart.js / data visualizations

### ISSUE THREAD

**Issue by connecteev** [ueberdosis/tiptap#565]
Add Extension to support Chart.js / data visualizations

(this would be an extension of the core), similar to what is seen in the demo here: https://nhn.github.io/tui.editor/latest/tutorial-example03-editor-extensions . For the charting library, I would support the best ones out there:

Chart.js: https://www.chartjs.org/ (most popular, see https://github.com/apertureless/vue-chartjs/)

and  I should be able to do something like this in the editor:
```
```chart
,category1,category2
Jan,21,23
Feb,31,17
Mar,22,37

type: column
title: Monthly Revenue
x.title: Amount
y.title: Month
y.min: 1
y.max: 40
y.suffix: $
```
Btw, this editor experience to copy and paste from excel is amazing: https://uicdn.toast.com/tui-editor/tui-editor-preview-1520325258239.gif

**Comment by Alecyrus** [comment]
The node based on Vue component(node view) is a good solution for this feature.

**Comment by btbritz** [comment]
What ended up happening with this?

**Comment by hanspagel** [comment]
Nothing. I don’t see us add that to the core somehow, it’s just too different what people like to do, where the data comes from and so on.

You can use node views to mount Chart.js on your own though.

https://www.tiptap.dev/guide/node-views

**Comment by SawkaDev** [comment]
Does anyone have an example that implements this?
