### ISSUE TITLE
[Bug]: Memory leak when discarding used editors

### ISSUE THREAD

**Issue by schontz** [ueberdosis/tiptap#5654]
### Affected Packages

pm, react, starter-kit, extension-color, extension-list-item, extension-list-style

### Version(s)

2.7.2

### Bug Description

I have observed Editor memory leaks when the editor instance is re-created. I create a repro that simply uses the demo app.

### Browser Used

Chrome

### Code Example URL

https://github.com/schontz/tiptap-react-leak

### Expected Behavior

There should only be a single editor in memory, while instead there are many.

### Additional Context (Optional)

![Screenshot 2024-09-24 at 4 46 54 PM](https://github.com/user-attachments/assets/18acc0ad-43f7-4218-b435-a040bd4b7e53)

![Screenshot 2024-09-24 at 4 45 45 PM](https://github.com/user-attachments/assets/e619277b-f318-447d-a0df-20498f337eb1)

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Would this tell you where the memory is still being referenced from?

It is detached from the DOM so I'm not terribly concerned to be honest

**Comment by schontz** [comment]
For our application, we are seeing memory balloon over time. As soon as we stopped the editor from being re-created, memory stabilized.

**Comment by schontz** [comment]
It should be noted that detached DOM nodes in a memory snapshot are ones that are referenced and cannot be cleaned up by the garbage collector. GC is forced before each snapshot.

**Comment by nperez0111** [comment]
Alright, well then this will need some research into what is actually keeping these references around. Unfortunately, a pretty broad surface area to look into.

I would be willing to take a patch that resolves this

**Comment by schontz** [comment]
Tested and that works. I suggest assigning and destroying in EditorView instead of Editor, where it is currently assigned.

**Comment by schontz** [comment]
I submitted a PR, but I think it would be better to [detect Cypress](https://docs.cypress.io/faq/questions/using-cypress-faq#Is-there-any-way-to-detect-if-my-app-is-running-under-Cypress) instead. I can't get tests to run, but it would just look like this:

```javascript
if (typeof window !== 'undefined' && window.Cypress) {
  dom.editor = this;
}
```

I'd much prefer this over my PR.

**Comment by schontz** [comment]
I posted a CR that only runs the code in Cypress. I can't get tests to run, so you'll need to verify that they work. The alternative is to deref on destroy, but if any errors occur that prevent a clean destroy, the leak would persist. As the code is test-only, it is best if it just runs there.

**Comment by nperez0111** [comment]
I do prefer just de-referencing it in the `destroy` method because I personally have found it quite useful to inspect the editor and issue commands from the dom element. This also could be relied upon by users.

The PR you made was into your own repo, but I'll make one into here
