### ISSUE TITLE
[Bug]: insertContent doesn't update the DOM properly when using a custom node view

### ISSUE THREAD

**Issue by Anfang2580** [ueberdosis/tiptap#5655]
### Affected Packages

core, react

### Version(s)

2.7.2

### Bug Description

`insertContent` doesn't update the DOM properly when using a custom node view. For example,
```js
insertContent([
            {
              type: "customNode",
              content: [
                {
                  type: "paragraph",
                  content: [
                    {
                      type: "text",
                      text: "Custom text",
                    },
                  ],
                },
              ],
            },
          ])
```
inserts only a customNode wrapper div but not the paragraph child. See codesandbox for full example. ((Ctrl + q) is bound to new custom node). Not sure if this is how its supposed to work? The documentation calls `insertContent` very flexible so I imagine this should work. `customNode` has `"paragraph"` as content schema.

### Browser Used

Chrome

### Code Example URL

https://codesandbox.io/p/sandbox/friendly-hawking-56fxvl

### Expected Behavior

`insertContent` should generate all the HTML that the input JSON requires.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Your nodeview does not have a `NodeViewContent` defined. Please refer to these docs for more info. https://tiptap.dev/docs/editor/extensions/custom-extensions/node-views/react#adding-a-content-editable
