### ISSUE TITLE
Add Extension to support UML diagrams

### ISSUE THREAD

**Issue by connecteev** [ueberdosis/tiptap#566]
Add Extension to support UML diagrams

as seen here: https://nhn.github.io/tui.editor/latest/tutorial-example03-editor-extensions
and  I should be able to do something like this in the editor:
```uml
partition Conductor {
  (*) --> "Climbs on Platform"
  --> === S1 ===
  --> Bows
}

partition Audience #LightSkyBlue {
  === S1 === --> Applauds
}

partition Conductor {
  Bows --> === S2 ===
  --> WavesArmes
  Applauds --> === S2 ===
}

partition Orchestra #CCCCEE {
  WavesArmes --> Introduction
  --> "Play music"
}
```

**Comment by Alecyrus** [comment]
The node based on Vue component(node view)  is a good solution for this.

**Comment by laurensiusadi** [comment]
I think this feature shouldn't be included in this main repo, more like third party plugin

**Comment by Cloud-Iris** [comment]
Oh, god, Page not found. QAQ
Could you please give me more information about UML in tiptap?
