### ISSUE TITLE
Cdn for tiptap

### ISSUE THREAD

**Issue by hirenkeraliya** [ueberdosis/tiptap#567]
Can you build cdn for this tip tap?

Thanks

**Comment by buddyfavors** [comment]
tiptap is on npm, and there is already a cdn wrapper for npm so you can just use that.  https://unpkg.com

**Comment by jodinathan** [comment]
Would be nice to have a common CDN example. We can't use Skypack.

**Comment by philippkuehn** [comment]
There is still an issue with skypack: https://github.com/skypackjs/skypack-cdn/issues/159
There is still an issue with esm.sh: https://github.com/alephjs/esm.sh/issues/165

:(
