### ISSUE TITLE
[Bug]: Inserted mentions don't retain styling

### ISSUE THREAD

**Issue by aoleksyshyn-spscommerce** [ueberdosis/tiptap#5673]
### Affected Packages

core, extension-mention, extension-text-style, extension-font-family, suggestion, react

### Version(s)

2.7.4

### Bug Description

1. When you apply some styles (font family, font size, etc.) to entered text and try to add mention it creates `<span>` outside of styled one.
2. Text entered after "mention" block doesn't keep initial styling. Extra space is added after "mention" block.
3. When you select font family and start typing @ you still have selected font family but as soon as you select an item from suggestion list styled `<span>` is replaced with another one.

https://github.com/user-attachments/assets/c2e420cb-2c8f-4b5d-9ab2-af230718a16e

https://github.com/user-attachments/assets/75d9ce27-ff7d-4a93-9845-e9829e6d0dc8

https://github.com/user-attachments/assets/195e46cb-97d9-46de-b986-35ddfa25a152

### Browser Used

Chrome

### Code Example URL

https://codesandbox.io/p/sandbox/kc4zc8

### Expected Behavior

1,2. "Mention" `<span>` should be inserted inside current styled one, not outside.

_Actual HTML output:_
```html
<p>
  <span style="font-family: Comic Sans MS, Comic Sans">test </span>
  <span class="mention" data-type="mention" data-id="Tom Cruise">@Tom Cruise</span>
  <span style="font-family: Comic Sans MS, Comic Sans">test</span>
</p>
``` 
_Expected HTML output:_
```html
<p>
  <span style="font-family: Comic Sans MS, Comic Sans">test <span class="mention" data-type="mention" data-id="Tom Cruise">@Tom Cruise</span> test</span>
</p>
``` 

3. Separate `<span>` should be created for each "mention", it should not replace existing styled text block but should be inside.

_Actual HTML output:_
```html
<p>
  <span class="mention" data-type="mention" data-id="Tom Cruise">@Tom Cruise</span>
</p>
``` 
_Expected HTML output:_
```html
<p>
  <span style="font-family: Comic Sans MS, Comic Sans">
    <span class="mention" data-type="mention" data-id="Tom Cruise">@Tom Cruise</span>
  </span>
</p>
``` 

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by ryanmunger** [comment]
I am also seeing the same thing on my end. All inline styles get stripped in the editor. Is this something that needs to be updated in the schema?

**Comment by aoleksyshyn-spscommerce** [comment]
@bdbch @svenadlung hi guys, could you please check this issue? maybe there's possible workaround for such behaviour?

**Comment by nperez0111** [comment]
A mention is an inline node, so it splits marks and does not have the marks applied to them. This is how Tiptap works.

A mention is not just text, it is treated as being semantically different. Please don't @ people for attention on issues, it is a lot of work to maintain such a used project. If you want this fixed, please look into it, and contribute back a PR. This is open source, not free labor

**Comment by bdbch** [comment]
Styles not being applied to a Mention is normal - the mention is not part of the normal text content as nperez0111 said.

Regarding the mentions splitting of the styles of the mark after here's the logic where the insertion happens:

https://github.com/ueberdosis/tiptap/blob/6834a7f7d620c1706aaa5220db3ffcfebef946b7/packages/extension-mention/src/mention.ts#L110

We just do a very simple content insertion there - so in theory you could also provide your own suggestion options where you store the marks at the position and apply it to the split content.

Not having the time right now to fix this issue so if anyone wants to pick it up I'd be happy to check a PR for it.
