### ISSUE TITLE
[Bug]: Can't move cursor to left-side of mention when mention is the first thing in the editor

### ISSUE THREAD

**Issue by rfgamaral** [ueberdosis/tiptap#5683]
### Affected Packages

mention

### Version(s)

2.7.4

### Bug Description

Using the official [mentions example](https://tiptap.dev/docs/examples/advanced/mentions), delete all editor contents and insert a mention with `@`. Then try to use the `LeftArrow` key to place the cursor **before** the mention. You'll realize that this is not possible. However, if you type some text, then the mention, you can use `LeftArrow` to move the cursor freely.

### Browser Used

Firefox

### Expected Behavior

Arrow keys should work all the times, allowing a user to place the cursor before/after any node/mark, such as mentions.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Hey @rfgamaral, this is a known issue with Prosemirror editors, the official solution is to use the Gapcursor extension to allow going before content.  I modified the mention demo and it works after this extension is added:
<img width="668" alt="image" src="https://github.com/user-attachments/assets/e3cbdbe9-efef-4c41-b7a9-13b6b325e86c">


https://github.com/user-attachments/assets/47e4acec-2525-42cb-a0a2-8a4e8847646e

**Comment by nperez0111** [comment]
@rfgamaral, we use gap cursor straight from prosemirror, [it looks like this was touched relatively recently for firefox](https://github.com/ProseMirror/prosemirror/issues/1466) (may 30, 2024) so maybe you haven't updated prosemirror-view (1.34.3 I think patches it)

If you still have issues with this, then you'll have to upstream this to prosemirror as we only wrap that plugin

**Comment by rfgamaral** [comment]
@nperez0111 I use `@tiptap/pm`, I'm guessing you need to update that first?

**Comment by nperez0111** [comment]
`@tiptap/pm` declares prosemirror-view as a peer dep, allowing a range of versions to match: 
<img width="1257" alt="image" src="https://github.com/user-attachments/assets/21f5e6b7-cd37-45c4-aae8-d6851c3bad9a">
Right now it is defined here: https://github.com/ueberdosis/tiptap/blob/develop/packages/pm/package.json#L146C6-L146C35

You can update your package-lock to a newer version of prosemirror-view and it should update to a newer version. If you re-generate your package-lock completely without any installed node_modules, then NPM would fetch the latest matching version.

So this allows us to not have to constantly bump versions and gives you the flexibility to pull in newer versions of prosemirror without having to wait on us

**Comment by rfgamaral** [comment]
@nperez0111 Unfortunately, using `prosemirror-view@1.34.3` doesn't fix the issue for Firefox.

I've tried the [basic example](https://prosemirror.net/examples/basic/) on ProseMirror's website, inserted an image (the closest node type I could get to a mention), and I can use arrow keys on Firefox without issues to place the cursor on both sides of the image. Could there be something on Tiptap preventing this behaviour?

**Comment by nperez0111** [comment]
@rfgamaral I can't think of anything in particular. Our NodeView class does quite a bit, but does not do anything with selection movements. I'll reopen this but I probably won't look into it further than this

**Comment by gethari** [comment]
@rfgamaral am I missing something ? I don't see the cursor in ProseMirror's site as well in Firefox for mac 130.0.1 (64-bit)


https://github.com/user-attachments/assets/da386b74-5d13-40f5-9471-74098938fe32

**Comment by rfgamaral** [comment]
@gethari The cursor is not visible, yes (probably a CSS thing), but you can still move it to the left-side of the image (as you demonstrated by typing). Whereas on Tiptap, you can't move the cursor to the left-side of a mention at all.

**Comment by gethari** [comment]
@rfgamaral I am still confused !

https://github.com/user-attachments/assets/3f3f33f9-012c-4497-8f32-ec484e487d13

**Comment by rfgamaral** [comment]
@gethari That doesn't work for me. I even tried to disable all extensions, and it still doesn't work. Which Firefox version are you using?

**Comment by nperez0111** [comment]
OS might be important here too 🤔

**Comment by gethari** [comment]
> @gethari The cursor is not visible, yes (probably a CSS thing), but you can still move it to the left-side of the image (as you demonstrated by typing). Whereas on Tiptap, you can't move the cursor to the left-side of a mention at all.

<img width="714" alt="image" src="https://github.com/user-attachments/assets/034ef943-7d8e-46ab-a07b-2e6e8e2d672e">

**Comment by rfgamaral** [comment]
I'm on 132.0b2, shouldn't make that much of a difference, especially since I've been noticing this issue for a while now (so I'm certain I've had the issue when I was at 130). I guess this is a _me_ problem, I just don't know what could possibly be the culprit.

**Comment by nperez0111** [comment]
I just installed Firefox to test it out, I'm on macOS and it works just like the video:
<img width="752" alt="image" src="https://github.com/user-attachments/assets/f0e1a5f1-8e62-40b7-8adc-ce333b48a5c3">

Maybe an extension, but I'm going to close this out
