### ISSUE TITLE
Multiple (synced) EditorContents

### ISSUE THREAD

**Issue by hyvyys** [ueberdosis/tiptap#569]
I'm trying to implement an editable waterfall view for previewing fonts:
![obraz](https://user-images.githubusercontent.com/20814638/71559399-a3674280-2a5d-11ea-8c9a-27503a8c5e80.png)

I was able to get it work fine with my custom components, and now I wanted to replace it with TipTap to achieve an easier and more reliable approach to formatting. However only one EditorContent can be bound to a single editor, as doing otherwise causes errors like this:

```
[Vue warn]: Error in nextTick: "TypeError: Argument 1 of Node.appendChild is not an object."
found in
---> <EditorContent>
       <FontSample> at src/components/FontSample.vue
         <FontTester> at src/views/FontTester.vue
           <App> at src/App.vue
             <Root> vue.runtime.esm.js:619

TypeError: "Argument 1 of Node.appendChild is not an object."
    handler tiptap.esm.js:1563
    VueJS 2
```

**Describe the solution you'd like**
I would love to be able to bind a single editor to multiple EditorContent instances, and have them all synced up so that edits can be made in any instance and are propagated to the other ones, without losing focus and selection etc.

**Describe alternatives you've considered**
I considered simply replicating the editor object and propagating changes myself, but I deemed that solution unfeasible because the number of instances is variable as are the contents of the editor (I have tabs that can be switched between, and I simply replace the editor contents when a tab is switched).

**Comment by disarticulate** [comment]
I believed I accomplished this with https://github.com/yjs/yjs as follows:
```
### top level vue ###
<template>
  <slot v-bind:getEditor="getEditorFn"/>
<template>
<script>
import * as Y from 'yjs'
import {
    ySyncPlugin
} from 'y-prosemirror'
...
  methods: {
    getYDoc () {
      const ydoc = new Y.Doc()
      const type = ydoc.getXmlFragment('prosemirror')
      return { ydoc, type }
    },
    getEditorFn (child) {
        let { type, ydoc } = vm.getYDoc()
        let editor = new Editor()
        this.$nextTick(() => {
            editor.registerPlugin(ySyncPlugin(type))
            if (this.rootEditor) {
                 const rootState = Y.encodeStateAsUpdate(vm.rootEditor.ydoc)
                Y.applyUpdate(ydoc, rootState)
                this.rootEditor.ydoc.on('update', (update, origin) => {
                  Y.applyUpdate(ydoc, update)
                })
                ydoc.on('update', (update, origin) => {
                  Y.applyUpdate(vm.rootEditor.ydoc, update, child.$options.nam)
                })
          }
        })
    },
    mounted () { this.rootEditor = this.getEditorFn(vm) }
  }
```
then a child component can:
```
<template>
  <slot v-bind:editor="editor"/>
</template>
mounted () {
    let { type, ydoc, editor } = vm.getEditor(this)
    this.editor = editor
}
```
and the layout component, then looks like tiptap's setup:
```
<parent v-slot:default="{getEditor}">
  <child :getEditor="getEditor">
     <template v-slot:default="{ editor }">
       ...
    </template>
  </child>
<parent>
```
yjs then uses the root editor (with no ui interface to sync up all the other editors. It's not perfect, but if you want multiple editors, it works.

**Comment by hanspagel** [comment]
Thanks @disarticulate, that’s a great solution! We’ll make sure that gets easier with [tiptap v2](https://blog.ueber.io/post/our-plan-for-tiptap-2/).

**Comment by linuz90** [comment]
Hi, since TipTap 2 beta is out now, what's the official way of syncing multiple editors?

**Comment by linuz90** [comment]
For context, we're working on a typefully.com update that uses TipTap (🎊 ) and we'd like to try and have a TipTap editor and a TipTap thread preview that stay in sync, and letting the user edit the text in both.

**Comment by philippkuehn** [comment]
Hey, @linuz90! Great to see Tiptap maybe soon at typefully! :)

The idea is to watch for changes and update the other editor instance without triggering a new update event (this is what the `false` in `setContent` stands for). This is a very simple example using plain JS:

```js
const content = '<p>some content</p>'

const editor1 = new Editor({
  content,
  extensions: [
    // ...
  ],
  onUpdate() {
    console.log('editor 1 updated')
    editor2.commands.setContent(editor1.getJSON(), false)
  }
})

const editor2 = new Editor({
  content,
  extensions: [
    // ...
  ],
  onUpdate() {
    console.log('editor 2 updated')
    editor1.commands.setContent(editor2.getJSON(), false)
  }
})
```

**Comment by linuz90** [comment]
Amazing, will give it a shot, seems very straightforward!

We're very excited about the update, it's a pretty big change and using TipTap has been great. Also we have collaboration on our roadmap, so switching to a real rich text editor was a must.

**Comment by philippkuehn** [comment]
Great! But if you should use collab at some point, then this problem will have to be solved quite differently.

**Comment by linuz90** [comment]
> Great! But if you should use collab at some point, then this problem will have to be solved quite differently.

Oh makes sense. I'm just experimenting with this side by side thing though and we'll probably just commit to the new WYSIWYG editor. Sent you a preview by email 👌

**Comment by aehlke** [comment]
Is there an update on this within collab context?
