### ISSUE TITLE
[Bug]: Block Code, Paragraph and Headings does not trigger selectionUpdate

### ISSUE THREAD

**Issue by SalahAdDin** [ueberdosis/tiptap#5699]
### Affected Packages

core, react

### Version(s)

2.8.0

### Bug Description

We are using a [select component](https://github.com/konstantinmuenster/strapi-plugin-rich-text/blob/f3367082270e8d6a04950a82163db71469c9a82a/packages/strapi-plugin-rich-text/admin/src/components/RichText/Toolbar.tsx#L131) to handle some of the node types in the editor. This component should update its value automatically when changing the selected node type:
```ts

  const setActiveType = useCallback(() => {
    if (editor.isActive("heading", { level: 1 })) setSelectedType("h1");
    if (editor.isActive("heading", { level: 2 })) setSelectedType("h2");
    if (editor.isActive("heading", { level: 3 })) setSelectedType("h3");
    if (editor.isActive("heading", { level: 4 })) setSelectedType("h4");
    if (editor.isActive("heading", { level: 5 })) setSelectedType("h5");
    if (editor.isActive("heading", { level: 6 })) setSelectedType("h6");
    if (editor.isActive("alert")) setSelectedType("alert");
    if (editor.isActive("paragraph")) setSelectedType("paragraph");
    if (editor.isActive("codeBlock")) setSelectedType("codeBlock");
    if (editor.isActive("blockquote")) setSelectedType("blockquote");
    if (editor.isActive("orderedList")) setSelectedType("orderedList");
    if (editor.isActive("bulletList")) setSelectedType("bulletList");
  }, []);

  useEffect(() => {
    editor.on("selectionUpdate", setActiveType);

    return () => {
      editor.off("selectionUpdate", setActiveType);
    };
  }, [editor]);

```

And it happens for a fistful of nodes, but not for Headings, Paragraph, Block Code, and [other custom extensions](https://github.com/SalahAdDin/strapi-plugin-rich-text/blob/feat/extension-alert/packages/strapi-plugin-rich-text/admin/src/extensions/extension-alert/src/Alert.ts):

https://github.com/user-attachments/assets/e2f9d68b-71a8-45a8-9718-cbe02b1572e3

As you can see, changing the node the selector value is not automatically updated, but when you move to another node and come back late, you will see it changes.

But when you use **markdown** text (like prefixing and suffixing with `#` for headings, the selected value updates in real-time:

https://github.com/user-attachments/assets/85e123b1-f2f2-43b5-b035-f1285e6d2a29

### Browser Used

Chrome

### Expected Behavior

Updating the node type by using the selector component should work for all the node types and not only for a set of them, or, the way `selectionUpdate` event should be better explained.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
I think that the approach you are taking here is flawed, selection updates are to do with the cursor and the content it is selecting. Whereas you are trying to derive from the selection what the current content type is.

Try doing something like:

```ts
import { useEditorState } from '@tiptap/react'


const selectedType = useEditorState({
    editor,
    selector: ctx => {
	if (ctx.editor.isActive("heading", { level: 1 })){
		return 'h1'
	}
	if (ctx.editor.isActive("heading", { level: 2 })){
		return 'h2'
	}
/// etc.
    },
  })
```

This will accurately pull the current state from the editor in an efficient way.

**Comment by SalahAdDin** [comment]
> I think that the approach you are taking here is flawed, selection updates are to do with the cursor and the content it is selecting. Whereas you are trying to derive from the selection what the current content type is.
> 
> Try doing something like:
> 
> ```ts
> import { useEditorState } from '@tiptap/react'
> 
> 
> const selectedType = useEditorState({
>     editor,
>     selector: ctx => {
> 	if (ctx.editor.isActive("heading", { level: 1 })){
> 		return 'h1'
> 	}
> 	if (ctx.editor.isActive("heading", { level: 2 })){
> 		return 'h2'
> 	}
> /// etc.
>     },
>   })
> ```
> 
> This will accurately pull the current state from the editor in an efficient way.

Yeah, It worked: https://github.com/konstantinmuenster/strapi-plugin-rich-text/pull/31, thank you.
