### ISSUE TITLE
Floating menu does not work with clear content

### ISSUE THREAD

**Issue by sebastian-walter** [ueberdosis/tiptap#570]
**Describe the bug**
The `menu.isActive` is not working nicely when changing the content programmatically. In this example, I am clearing the content and would expect the floating menu to disappear.

**Steps to Reproduce / Codesandbox Example**
1. Add some content to the first line
2. Press Enter (so that the Floating Menu appears)
3. Click "Clear"

https://codesandbox.io/s/vue-issue-template-n161r

**Expected behavior**
The floating menu should disappear, since the editor lost focus.

**Screenshots**

**Environment**
 - OS: Linux 
 - Version 78.0.3904.70 (Official Build) (64-bit)
 - Desktop

**Comment by saulortega** [comment]
It doesn't even work in the live demo: https://tiptap.scrumpy.io/floating-menu

**Comment by Mach12** [comment]
Floating menu doesn't seem to work at all really. As stated above even the live demo is non-functional. It would seem `menu.isActive` is never set to `true` in the floating menu props.

**Comment by hanspagel** [comment]
Oh. What a shame! It seems to be broken for way too long. 😬  

We are about to rewrite all the interface components for [tiptap v2](https://blog.ueber.io/post/our-plan-for-tiptap-2/), we’ll make them way more robust.
