### ISSUE TITLE
[Bug]: getMarkRange returned an incorrect value

### ISSUE THREAD

**Issue by guanriyue** [ueberdosis/tiptap#5715]
### Affected Packages

core

### Version(s)

2.8.0

### Bug Description

I recorded a video to demonstrate this bug.

https://github.com/user-attachments/assets/b0cfbcec-0da6-4920-8f1a-7400bc31e70e

As shown in the figure, clicking the link icon will select the entire link. This is achieved by using `editor.commands.extendMarkRange('link')`

<img width="544" alt="截屏2024-10-10 11 52 33" src="https://github.com/user-attachments/assets/54bf764c-efcf-4796-bc63-33a5f0d25093">

It works as expected

<img width="481" alt="截屏2024-10-10 11 55 04" src="https://github.com/user-attachments/assets/77328439-43be-44e8-a586-b86b299c1786">

But if the selection is like the one below, it will not work as expected

<img width="520" alt="截屏2024-10-10 12 02 10" src="https://github.com/user-attachments/assets/0beb6568-d0a8-4774-8f28-c28b81040a3c">

This problem only occurs when the `$from` of the selection is at the beginning of the link
After debugging I found out that this is because `getMarkRange` returns undefined

<img width="581" alt="截屏2024-10-10 12 04 31" src="https://github.com/user-attachments/assets/9c6611c7-9856-4fc5-aa2d-f00b14b823cb">
<img width="183" alt="截屏2024-10-10 12 05 08" src="https://github.com/user-attachments/assets/58e393c2-eecf-441c-9d1d-75bf517f0da3">

And if I change the first parameter of `getMarkRange` from `$from` to `$to` I can get it to work correctly.

I use the following code to meet my needs. But I prefer the simple `editor.commands.extendMarkRange('link')`

```js
      const range = getMarkRange(
        editor.state.selection.$to,
        editor.schema.marks.link,
      );

      if (range) {
        editor.commands.setTextSelection(range);
        setPopover('link');
      }
```

Hope this problem can be solved

### Browser Used

Chrome

### Expected Behavior

`getMarkRange` returns correct range.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
This is released with v2.9.0
