### ISSUE TITLE
[Bug]: Nested marks with styling are stripped by default

### ISSUE THREAD

**Issue by bdbch** [ueberdosis/tiptap#5720]
### Affected Packages

core

### Version(s)

2.8.0

### Bug Description

To give this issue a bit more context - see this discussion:

#1815 

Prosemirror seems to strip out font styles from nested text elements by default which causes a loss of text stylings when content is parsed into the editor that is structured like this:

```html
<span style="font-size: 10px;">
  <span style="color: red;">This is red</span>
  <span style="color: blue;">This is blue</span>
</span>
```

Afaik this would lead to parsed HTML of

```html
<span style="font-size: 10px; color: null;">This is redThis is blue</span>
```

### Browser Used

Chrome

### Expected Behavior

Spans should be kept to preserve attributes with context on specific text elements.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
We've got a fix for this https://github.com/ueberdosis/tiptap/pull/5897
