### ISSUE TITLE
[Bug]: lost peerDependency when pnpm add @tiptap/pm

### ISSUE THREAD

**Issue by dingshaohua-com** [ueberdosis/tiptap#5723]
### Version(s)

2.8.0

### Bug Description

[Bug]: lost peerDependency when pnpm add @tiptap/pm
![QQ20241013-174652](https://github.com/user-attachments/assets/5dd7f64c-2e5b-435c-9e87-5a76d9382e70)

**Comment by dingshaohua-com** [comment]
i resolve this problom: pnpm install --shamefully-hoist

**Comment by Nantris** [comment]
This report isn't clear.
