### ISSUE TITLE
Editor removes span tags

### ISSUE THREAD

**Issue by konstantinvoronoy** [ueberdosis/tiptap#574]
Hey, I got stuck with a small issue. I've been using TipTap with html pasted, something like: 

`this.html = myhtml` And then `this.editor.setContent(this.html)`

It always worked pretty good.

But now I found out that the editor removes all span tags.

Like in the beginning it would be `<p>Some text <span class="someclass">some text</span></p>` 

But after I got only `<p>Some text <span class="someclass">some text</span></p>`

Could anyone tell me how I can solve this, please?

**Comment by zachzoup** [comment]
I believe you would need to create a custom `Mark` with a span tag. Something like this would work - https://gist.github.com/zachzoup/18536f5cf99c18f63e28428f3e01e2d5

**Comment by konstantinvoronoy** [comment]
Thank you! How did you learn to make this? :) I'm new to this thing. Actually I started learning JS about 7-8 months ago. Maybe you have some links for tutorials or something like that. Thank you!

**Comment by zachzoup** [comment]
I just looked at the source for the link `Mark` and altered it to change the `href` attribute to `class`.

**Comment by samyarkd** [comment]
how to do the same in react
