### ISSUE TITLE
[Bug]: Dropping an image in a list bullet list get stucked (Premium template)

### ISSUE THREAD

**Issue by ferreiro** [ueberdosis/tiptap#5743]
### Affected Packages

extensions

### Version(s)

latest

### Bug Description

I noticed a bug in the notion template. If I upload an image and try to drop in the middle of a bullet list, it gets stuck, and makes the whole editor non being able to move the image around, which it's a big pain.

https://www.loom.com/share/3462121e42e8488ba0379105952d865d 

Any ideas to fix this?

### Browser Used

Chrome

### Expected Behavior

It should either block dropping an image into the bullet list or once I drop the image, it should let me reorder and move the image around.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by guarmo** [comment]
Hi @ferreiro, I would assume this is the intended behavior. Since the image becomes part of a list item, which is not meant to be draggable, it cannot be dragged around any longer.
