### ISSUE TITLE
[Bug]: TipTap always destroy the last useEditor.

### ISSUE THREAD

**Issue by BlackyUmbreon** [ueberdosis/tiptap#5747]
### Affected Packages

react

### Version(s)

2.8.0

### Bug Description

The main issue is when I use `useEditor` more than one in one view.
I have content array which is contains content who set from the Tiptap Editor.
Each element in the array will render a component, and each component will have invoke `useEditor` before rendering the html.

I should look like this.
![image](https://github.com/user-attachments/assets/4c83f99c-1e2b-43dd-a638-e6485d446c2a)

However, when I remove the first element which is "Text 1" as content.
It should remove the first editor like only [Text 2 and Text 3] remain, but the `onDestroy` invoked on the third editor (Last editor).
It will become like this picture.
![image](https://github.com/user-attachments/assets/003f112d-4db3-4d5f-9106-3b840db8926c)

But the funny things is, the content array shows ["Text 2", "Text 3"] which is exactly remove the "Text 1", but the Editor doesn't follow the new content array.
When I press F5 on browser, it will render the correct content on each Editor.
![image](https://github.com/user-attachments/assets/67f5c82c-3b24-4ceb-b876-903b3521d5b0)

Does anyone have this issue, or having some solution to handle `onDestroy` editor problem?
I use Reactjs with Nextjs.

### Browser Used

Chrome

**Comment by nperez0111** [comment]
This is likely an integration issue on your end. I'd suggest using a `key` on each component that you are rendering. I would try to help more but you did not share any code for this.

But it should look like this:


```tsx
function Renderer(){
 return ['A', 'B', 'C'].map((text) => <Component text={text} key={text} />)
}

function Component({text}){
 const editor = useEditor({content: text})
}
```

**Comment by BlackyUmbreon** [comment]
I don't think it's worked. It still problem.
I think I show you the code

App.js
```javascript
const textArray = [ TextElement(), TextElement(), TextElement(), ...];

return <div>
	{
		textArray.map((text, index)=>{
			return text.renderEditElement(index);
		})
	}
	</div>
``` 

TextElement.jsx
```javascript
export class TextElement extends BaseModel{
	constructor(props){
		super(props);
		this.content = props.content ?? "";
		...
	}

	renderEditElement(index) {
		return <Text model={this} index={index} edit={true} />
	}
}

const Text = forwardRef(({model, index, edit}) => {
	const editorRef = useRef(null);

	const Editor = useEditor({
		extensions: [...ExtensionsList],
		editable: true,
		content: model.content,
		onUpdate: ({editor}) => {
			// Update Action to Backend
		}
	});

	return (
		<div key={index}>
			<EditorContent
				editor={Editor}
				ref={editorRef}
			/>
			
			{/* Toolbar for text editor */}
			<TextToolbar />
		</div>
	)
}
```
