### ISSUE TITLE
Link menu doesn't open automatically

### ISSUE THREAD

**Issue by sanyaches** [ueberdosis/tiptap#575]
How handle onselect event in Editor?? I added the links addition component from this [example](https://github.com/scrumpy/tiptap/blob/master/examples/Components/Routes/Links/index.vue).

But the `<editor-menu-bubble>` doesn't activate automatically when `onselect`

I found 1 solution for Double Click Event [here](https://prosemirror.net/docs/ref/#view.EditorProps.handleDoubleClick).

Help me find a solution for onselect event handling.

My code from editorProps:

```
handleDoubleClick: () => {
    this.$emit('textSelectedEditor');
    this.onSelect();
}
```
My method onSelect:

```
onSelect() {
   this.linkMenuIsActive = true
}
```
The menu is now activated by component property `linkMenuIsActive`.

**Comment by laurensiusadi** [comment]
Editor menu bubble shows when you select something inside editor automatically.
See https://github.com/scrumpy/tiptap/blob/master/packages/tiptap/src/Plugins/MenuBubble.js
I think what you're asking is: how to make menu bubble appears programmatically on double click event?

Also you should provide sandbox replicating the bug.

**Comment by arthabus** [comment]
@laurensiusadi I'm wondering how to make menu bubble appears programmatically on double click event?

**Comment by laurensiusadi** [comment]
> 
> 
> @laurensiusadi I'm wondering how to make menu bubble appears programmatically on double click event?

Custom menu plugin.
I'd say start with duplicating the MenuBubble Plugin and changing the handler on this line, currently it's using `mousedown` https://github.com/ueberdosis/tiptap/blob/01ec8b2bf4c3ac0fb6a31992656f5c8d4ed0f25e/packages/tiptap/src/Plugins/MenuBubble.js#L73
