### ISSUE TITLE
[Bug]: Tables are not correctly converted to Markdown in TipTap

### ISSUE THREAD

**Issue by rossanodr** [ueberdosis/tiptap#5750]
### Affected Packages

core, extension-table, react

### Version(s)

 "^2.8.0",

### Bug Description

The issue occurs when trying to export a table created in the editor to Markdown. While the HTML output is correct, the corresponding Markdown output does not properly convert the table. Instead of generating Markdown table syntax, it only shows [table]. This makes it difficult to handle tables in Markdown format.

### Browser Used

Chrome

### Expected Behavior

When a table is created in the editor, it should be converted to proper Markdown syntax (e.g., using pipes | for rows and columns) instead of showing [table].

### Additional Context (Optional)

The HTML output for the table is correct, but the Markdown export does not include the table structure. This behavior makes it challenging to work with Markdown when tables are involved.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by aldrinjenson** [comment]
+ 1 to the above.
is there any update/fix?

**Comment by nperez0111** [comment]
Tiptap does not support markdown. So I'm not sure how it is you are even trying to generate markdown. Maybe you are using the tiptap-markdown extension which we don't support? https://github.com/aguingand/tiptap-markdown

**Comment by andreasvirkus** [comment]
While I get what you mean by "Tiptap does not support markdown", if someone just visits the doc and searches for markdown, some pages are highly contradicting to this claim (https://tiptap.dev/docs/examples/basics/markdown-shortcuts)
