### ISSUE TITLE
[Bug]: If EditorContent is empty, no onPaste event occurs

### ISSUE THREAD

**Issue by miridih-jhkim06** [ueberdosis/tiptap#5762]
### Affected Packages

core, react

### Version(s)

2.9.1

### Bug Description

I want to prevent bubbling the paste event that occurred inside EditorContent.

``` typescript
// root component
function App() {
  useEffect(() => {
    const filePasteHandler = (event: ClipboardEvent) => {
      console.log("root");
    };

    window.addEventListener("paste", filePasteHandler);

    return () => {
      window.removeEventListener("paste", filePasteHandler);
    };
  }, []);
  return (
    <div className="card">
      <Tiptap />
    </div>
  );
}

// in Tiptap component
<EditorContent
  ref={ref}
  editor={editor}
  onPaste={(e) => {
    e.stopPropagation();
    console.log("element paste");
  }}
  onPasteCapture={(e) => {
    // e.stopPropagation();
    console.log("element pasteCapture");
  }}
/>
```

I wrote an e.stoppropagation for onPaste,
When the editor is not empty, it works as intended, but when the editor is empty, the window still detects a paste event.

This can be blocked through onPasteCapture, but I don't know why it works like this.

In events detected when the editor is empty in the root, the target is detected as a `p`, but when the empty editor detects events, it is detected as` br.ProseMirror-tracingBreak`

<img width="648" alt="image" src="https://github.com/user-attachments/assets/55f248b9-0c79-4c93-82f6-7eb5e91f16ed">

![image](https://github.com/user-attachments/assets/ac02b288-1426-402e-9c03-0292cb29aa0c)

I prepared a demo with a code sandbox

### Browser Used

Chrome

### Code Example URL

https://codesandbox.io/p/devbox/qytkhr?file=%2Fsrc%2FApp.tsx%3A5%2C1-22%2C2

### Expected Behavior

The onPaste event should also operate normally with an empty EditorContent.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by guarmo** [comment]
Adding a check for `event.defaultPrevented` within your root's `filePasteHandler` would be a good approach here. This way, if the `onPasteCapture` or `onPaste` events on your editor prevent the default behavior, the root handler will respect that, and you won’t see a redundant paste event in the root.

```ts
const filePasteHandler = (event: ClipboardEvent) => {
    if (event.defaultPrevented) {
      console.log("root");
    }
};
```
