### ISSUE TITLE
[Bug]: how to defined async commands

### ISSUE THREAD

**Issue by dingshaohua-com** [ueberdosis/tiptap#5763]
### Affected Packages

core

### Version(s)

2.8.0

### Bug Description

this dispatch is not execute,why?
how to defined async commands?
![dcdc9be54e27c0a261262f121140b251](https://github.com/user-attachments/assets/1cd15079-58c1-45e8-9599-5952c85e7a56)

### Browser Used

Chrome

### Expected Behavior

nomal

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Please don't cross-post. You asked this in Github issues, discussions and Discord.

So the issue here is that you're trying to dispatch in a Promise and Tiptap's chain runs synchronously, therefore your dispatch is not executed.

The solution would be to do something like this:

```ts
addCommands() {
  return {
    uploadImg: () => (arg) => {
      openFileWindow().then(async (imgFile) => {
        ...
        editor.chain().insertContentAt(0, paragraphNode).run();
      })
    }
  }
}
```
