### ISSUE TITLE
[Bug]: Tailwind Break-Words not respected in editorProds.attributes.class

### ISSUE THREAD

**Issue by churbis** [ueberdosis/tiptap#5767]
### Affected Packages

react

### Version(s)

2.1.5

### Bug Description

Combo of tailwind `break-words`, `whitespace-normal`, `overflow-y-auto` passed to the editor config `class `did not stop holding down one letter from breaking the EditorContent component out of its containing div. Had to style .ProseMirror class directly in `global.css` to get the text from breaking out of the parent container on the horizontal axis.

### Browser Used

Chrome

### Expected Behavior

I want the styling of the text wrapping Tailwind classes to be applied to the EditorContent component

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by guarmo** [comment]
Hey @churbis, would you mind providing a code sandbox for the issue? I don't seem to be able to reproduce it
