### ISSUE TITLE
[Bug]: The editor doesn't preserve text alignment when changing to a paragraph node

### ISSUE THREAD

**Issue by anarakhlina** [ueberdosis/tiptap#5775]
### Affected Packages

react, extension-text-align

### Version(s)

2.9.1

### Bug Description

`setParagraph` changes text alignment to left, ignoring the alignment set before.
The same issue was mentioned [here](https://github.com/ueberdosis/tiptap/issues/3644), but was resolved for **heading only**

### Browser Used

Chrome

### Code Example URL

https://codesandbox.io/p/sandbox/quirky-julien-hh43ry

### Expected Behavior

When changing text to paragraph node, the text alignment should be preserved.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by deki23** [comment]
This doesn't work for a range selection that has two or more nodes inside. It won't preserve attributes for any of contained nodes.

**Comment by nperez0111** [comment]
> This doesn't work for a range selection that has two or more nodes inside. It won't preserve attributes for any of nodes from selection.

Changing a paragraphs alignment is only a single node op. 

It isn't really expected that attributes would be copied over anything within the range. If you need that behavior you can implement yourself in other ways. But setNode is ambiguous to begin with
