### ISSUE TITLE
[Bug]: Server generateHTML causes "attempted to call map" error using next

### ISSUE THREAD

**Issue by churbis** [ueberdosis/tiptap#5779]
### Affected Packages

 @tiptap/html

### Version(s)

2.9.1

### Bug Description

Next route using `import { generateHTML } from "@tiptap/html"` throws an Unhandled Runtime Error: `Error: Attempted to call map() from the server but map is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.` despite being [advertised as SSR ready in the docs](https://tiptap.dev/docs/editor/api/utilities/html#source-code)

### Browser Used

Chrome

### Expected Behavior

Renders HTML server side w/o error

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
`@tiptap/html` definitely does work on the server, many are using it.

It looks like you did not invoke your function correctly. Next.js is out of scope of this project. You likely need to specify 'use server' for whatever this map function is.
