### ISSUE TITLE
Menu bubble with link input active won't hide

### ISSUE THREAD

**Issue by laurensiusadi** [ueberdosis/tiptap#578]
**Describe the bug**
If you use link input within menu bubble, after clicking the input, menu bubble won't hide when clicking outside the menu bubble like usual.

**Steps to Reproduce / Codesandbox Example**
1. Go to https://tiptap.scrumpy.io/links
2. Select some text without links
3. Menu bubble appears, click Add Link
4. Input for link will appear on menu bubble
5. Click outside of editor, menu bubble won't hide

**Expected behavior**
Menu bubble hide if click outside editor

**Screenshots**
After link input active, click outside editor trying to dismiss menu bubble (mark with red arrow), but it won't close. Only able to close after placing cursor or selecting on other text.
![Annotation 2020-01-09 105134](https://user-images.githubusercontent.com/5661040/72036641-09f62700-32ce-11ea-87bf-53dd872e79f9.png)

**Environment**
 - OS: Windows 10 build 19041.1
 - Browser: Mozilla Firefox
 - Version: 71.0
 - Desktop

**Comment by hanspagel** [comment]
Thanks @laurensiusadi! We’re in the process of rewriting the whole interface for tiptap v2 and I added this to the list of things we need to consider! 🙌

**Comment by cairon666** [comment]
I have the same problem, is there a plan to solve it?

**Comment by nperez0111** [comment]
Feel free to investigate @cairon666
