### ISSUE TITLE
Check if content is empty (empty html tags)

### ISSUE THREAD

**Issue by kikky7** [ueberdosis/tiptap#580]
As mentioned in title, empty content keeps empty html tags (p, h1, h2, ...), but through Placeholder extension class is added to content container when it's empty. Is there any method on Editor which can check for empty content which returns true/false or at least get content (there are only getHtml and getJSON methods mentioned in docs); based on this I could just update data to an empty string instead of empty html tags.
I can write custom method in my code which checks for content using getJSON result; I was wondering if there is already method for that, but it's missing from docs.

**Comment by tguelcan** [comment]
My temporary workaround
```javascript
      .....
      onUpdate: ({ getHTML, getJSON }) => {
        if (!('content' in getJSON().content[0])) {
          this.context.model = null
          return
        }
        this.context.model = getHTML()
      },
```

**Comment by hanspagel** [comment]
Thanks for the suggestion @kikky7! And thanks for sharing @tguelcan!

We added `editor.isEmpty()` to the upcoming tiptap v2 for that purpose. 🙌

**Comment by Tukizz** [comment]
> Thanks for the suggestion @kikky7! And thanks for sharing @tguelcan!
> 
> We added `editor.isEmpty()` to the upcoming tiptap v2 for that purpose. 🙌

how to implement this now in tiptap v2? cause i get error like this

```js
TypeError: this.editor.isEmpty is not a function
```

i implement ```this.editor.isEmpty``` in watch function

```js
watch: {
    value(value) {
      const isSame = this.editor.getHTML() === value

      if (this.editor.isEmpty()) {
        this.isEmptyEditor(true)
      } else {
        this.isEmptyEditor(false)
      }

      if (isSame) {
        return
      }

      this.editor.commands.setContent(this.value, false)
    },
  },
```

if i wrong to implement ```editor.isEmpty()``` let me know and maybe give me some example to use this, thanks

**Comment by Tukizz** [comment]
> > Thanks for the suggestion @kikky7! And thanks for sharing @tguelcan!
> > We added `editor.isEmpty()` to the upcoming tiptap v2 for that purpose. 🙌
> 
> how to implement in tiptap v2 now? cause i get error like this
> 
> ```js
> TypeError: this.editor.isEmpty is not a function
> ```
> 
> i implement `this.editor.isEmpty` in watch function
> 
> ```js
> watch: {
>     value(value) {
>       const isSame = this.editor.getHTML() === value
> 
>       if (this.editor.isEmpty()) {
>         this.isEmptyEditor(true)
>       } else {
>         this.isEmptyEditor(false)
>       }
> 
>       if (isSame) {
>         return
>       }
> 
>       this.editor.commands.setContent(this.value, false)
>     },
>   },
> ```
> 
> if i wrong to implement `editor.isEmpty()` let me know and maybe give me some example to use this, thanks

it's solve, this my watch now
```js

watch: {
    value(value) {
      const isSame = this.editor.getHTML() === value

      if (this.editor.isEmpty) {
        this.isEmptyEditor(true)
      } else {
        this.isEmptyEditor(false)
      }

      if (isSame) {
        return
      }

      this.editor.commands.setContent(this.value, false)
    },
  },
```

use ```this.editor.isEmpty```, thanks :)

**Comment by kikky7** [comment]
I think this new isEmpty function still doesn't work as expected, it only works for paragraphs.

Here is console.log of getHtml() and isEmpty methods:

![image](https://user-images.githubusercontent.com/57031667/115990535-03271c80-a5c4-11eb-91e0-a378e90ebb4c.png)

Any other tag expect <p> is considered not empty even when it has no content so the actual content is just empty tags.

My current v2 implementation of checking for empty content is this (similar to what I did with v1, with small changes):

Trigger it on editor event onUpdate:
```
onUpdate: () => {
  this.setContent();
},
```

setContent custom vue method:
```
let content = this.editor.getHTML(),
  json = this.editor.getJSON().content;

if (
  Array.isArray(json) &&
  json.length === 1 &&
  !json[0].hasOwnProperty("content")
) {
  content = "";
}

this.$emit("input", content); // update v-model
// this.editor.commands.setContent(content); // Works without this line too
```

**Comment by philippkuehn** [comment]
@kikky7 The current implementation checks if the content matches the default [content](https://www.tiptap.dev/api/schema/#content) of your schema. So a doc content of `block+` ([which is the default](https://github.com/ueberdosis/tiptap/blob/35c9cecefca0bd434b668772bea763f2506e6354/packages/extension-document/src/document.ts#L6)) looks for the first block node which is in most cases a paragraph (because it has a higher [priority](https://www.tiptap.dev/guide/extend-extensions/#priority) than other block nodes).

You can use a different approach based on text length:
```js
const isEmpty = editor.state.doc.textContent.length === 0
```

But this will fail if your document contains only atom nodes like images or [mentions](https://www.tiptap.dev/api/nodes/mention) for example.

**Comment by kikky7** [comment]
Yes, I understand, but the naming is confusing then - if it checks content matching, better name would be isMatch or something like that, not isEmpty.

I will try this approach/example you sent to reduce my code for checking the actual empty content.
I don't use images or mentions so it shouldn't be an issue.

**Comment by noook** [comment]
If you don't have access to the editor, this function should do the trick:

```ts
import type { Content } from '@tiptap/vue-3'

export function isContentEmpty(content: Content): boolean {
  if (content === null) {
    return true
  }

  if (typeof content === 'string') {
    return content === ''
  }

  if (Array.isArray(content)) {
    return content.every(item => isContentEmpty(item))
  }

  if (!content.content) {
    return true
  }

  return content.content.every(item => isContentEmpty(item))
}
```

**Comment by noook** [comment]
For those who don't have access to the editor, I managed to check emptyness with this function:

```ts
import type { Content } from '@tiptap/vue-3'

export function isContentEmpty(content: Content): boolean {
  if (content === null) {
    return true
  }

  if (typeof content === 'string') {
    return content === ''
  }

  if (Array.isArray(content)) {
    return content.every(item => isContentEmpty(item))
  }

  if (!content.content) {
    return true
  }

  return content.content.every(item => !item.content)
}
```
