### ISSUE TITLE
[Bug]: export 'objectProp' (imported as 'objectProp') was not found in 'vue-ts-types' (module has no exports)

### ISSUE THREAD

**Issue by extrastu** [ueberdosis/tiptap#5803]
### Affected Packages

@tiptap/vue-2

### Version(s)

2.9.1

### Bug Description

依赖的 vue-ts-types 最新版本1.7.0 有问题，需要调整到 1.6.1 即可，vue-ts-types 已经确认是 bug，还没修复https://github.com/FloEdelmann/vue-ts-types/issues/706

### Browser Used

Chrome

### Expected Behavior

安装最新版本就有这个问题

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by FloEdelmann** [comment]
Should be fixed by updating to https://github.com/FloEdelmann/vue-ts-types/releases/tag/v1.7.1.

**Comment by guarmo** [comment]
> Should be fixed by updating to https://github.com/FloEdelmann/vue-ts-types/releases/tag/v1.7.1.

Cheers @FloEdelmann

@extrastu closing this one up.
