### ISSUE TITLE
[Bug]: Invalid prop `id` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.

### ISSUE THREAD

**Issue by gr3enk** [ueberdosis/tiptap#5806]
### Affected Packages

react

### Version(s)

2.9.1

### Bug Description

Invalid prop `id` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.

I encountered this Bug when using TipTap React useEditor Hook with Next.js 15 & React 19. 
I previously used the same code with Next.js 14 & React 18 and everything was working fine.

Error Snippet:
```
intercept-console-error.ts:46  Invalid prop `id` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.
error @ intercept-console-error.ts:46
(anonym) @ react-dom-client.development.js:4383
runWithFiberInDEV @ react-dom-client.development.js:543
validateFragmentProps @ react-dom-client.development.js:4380
reconcileChildFibersImpl @ react-dom-client.development.js:5135
(anonym) @ react-dom-client.development.js:5389
reconcileChildren @ react-dom-client.development.js:7713
updateForwardRef @ react-dom-client.development.js:7753
beginWork @ react-dom-client.development.js:9988
runWithFiberInDEV @ react-dom-client.development.js:543
performUnitOfWork @ react-dom-client.development.js:14987
workLoopSync @ react-dom-client.development.js:14817
renderRootSync @ react-dom-client.development.js:14795
performWorkOnRoot @ react-dom-client.development.js:14289
performSyncWorkOnRoot @ react-dom-client.development.js:15858
flushSyncWorkAcrossRoots_impl @ react-dom-client.development.js:15720
processRootScheduleInMicrotask @ react-dom-client.development.js:15754
(anonym) @ react-dom-client.development.js:15874
setTimeout
Editor @ Editor.ts:117
createEditor @ useEditor.ts:155
refreshEditorInstance @ useEditor.ts:247
(anonym) @ useEditor.ts:212
react-stack-bottom-frame @ react-dom-client.development.js:22421
runWithFiberInDEV @ react-dom-client.development.js:543
commitHookEffectListMount @ react-dom-client.development.js:10738
commitHookPassiveMountEffects @ react-dom-client.development.js:10858
commitPassiveMountOnFiber @ react-dom-client.development.js:12628
recursivelyTraversePassiveMountEffects @ react-dom-client.development.js:12602

```

Full Log:
[localhost-1730878086382.log](https://github.com/user-attachments/files/17643303/localhost-1730878086382.log)

### Browser Used

Edge

### Expected Behavior

The Bug is not critical. The Editor works fine and React shouldn't flood the console with these errors.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
I just set up a next project with React 19 and did not see this issue. Can you share the code that you used to have this error?

Are you sure your app does not set this fragment? There isn't anywhere in our codebase that even set `id=` to something

**Comment by gr3enk** [comment]
I had the Editor and some other stuff warpped in a Fragment way higher up in the node tree. I changed this to a div and now it works fine. Although I hadn't set an id prop to the Fragment. Seems like a react bug. 

I thought is was caused by the TipTap Hook, because the Error message pointed it out.
