### ISSUE TITLE
Edit image alternative attributes

### ISSUE THREAD

**Issue by justLbee** [ueberdosis/tiptap#581]
Hello! 

I have some problems with customizing image alternative attributes.

After adding image into editor, i found how to get selected image or element node: 
```
const { selection, state } = this.editor
const { from, to } = selection
state.selection.node.attrs
```
But there is no documentation or information, how to edit already added nodes with image. If I try to change its attrs, html doesn't change. May be I need to rerender editor or node, but I don't know how.

Any help would be appretiated:)

**Comment by BrianHung** [comment]
Use setNodeMarkup [1]. For this you have to create and dispatch a transaction, which can be accessed through view.state.tr.




[1] https://prosemirror.net/docs/ref/#transform.Transform.setNodeMarkup

**Comment by laurensiusadi** [comment]
You can use custom node then use `updateAttrs` function like this
https://github.com/scrumpy/tiptap/blob/ee0750f128bf788ac3668c6576c341de41039761/examples/Components/Routes/Embeds/Iframe.js#L41-L43
