### ISSUE TITLE
[Bug]: editor.commands.setContent does not set attributes on Document node

### ISSUE THREAD

**Issue by StephanMeijer** [ueberdosis/tiptap#5813]
### Affected Packages

core

### Version(s)

2.91

### Bug Description

On the Document Node, attributes were not set properly when using `editor.commands.setContent`.

### Browser Used

Chrome

### Code Example URL

https://codesandbox.io/p/sandbox/adoring-elion-vvydqz

### Expected Behavior

Attributes on Document to be set, like it was set on Paragraph.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by Manaskhurana** [comment]
some times bug heppen with new React and React-Dom version

1. try to downgrade react virsion and if your working with next.js try to downgrade it also to fix the issue
2. due new updates of the frame works make difficult solve the issue
3. delete node_modules and reinstall may fix this issue
4. install latest version of tiptap

**Comment by StephanMeijer** [comment]
> some times bug heppen with new React and React-Dom version
> 
> 1. try to downgrade react virsion and if your working with next.js try to downgrade it also to fix the issue
> 2. due new updates of the frame works make difficult solve the issue
> 3. delete node_modules and reinstall may fix this issue
> 4. install latest version of tiptap

Not the case.

**Comment by StephanMeijer** [comment]
Closed. See https://github.com/ueberdosis/tiptap/pull/5814
