### ISSUE TITLE
"[ ] " creates list item and newline

### ISSUE THREAD

**Issue by wfischer42** [ueberdosis/tiptap#582]
**Describe the bug**
Typing "[ ] " at the beginning of a text line creates a new empty list item and a new line

**Steps to Reproduce / Codesandbox Example**
1. Open tiptap editor (https://tiptap.scrumpy.io/)
2. Type '[ ] ' on a new line (open bracket, space, close bracket, space)

**Expected behavior**
The line should show [ ] (or maybe make a new todo item)

**Environment**
 - OS: OSX 10.15.2
 - Browser: Chrome
 - Version: 79.0.3945.117
 - Mobile / Desktop: Desktop

Sidenote: Tiptap is great - thanks for making it!

**Comment by hanspagel** [comment]
Thanks for the report @wfischer42! Unfortunately I can’t reproduce the issue. 

As it has been silent for very long, it has probably been fixed in the meantime, so I guess I can close this here for now. ✌️
