### ISSUE TITLE
[Bug]: Cannot add links like "google.com/images"

### ISSUE THREAD

**Issue by mweidner037** [ueberdosis/tiptap#5824]
### Affected Packages

extension-link

### Version(s)

2.9.1

### Bug Description

If I try to add a link with `editor.command.setLink({ href: "google.com/images"} )`, the link is rendered as an HTML anchor with `href=""`, making the link unusable. I'm guessing the URL is not passing the validation [here](https://github.com/ueberdosis/tiptap/blob/942fd07b7642b9d8df85a5704efd0dce55c77d75/packages/extension-link/src/link.ts#L302).

The more complete URL `https://google.com/images` does work. I set `defaultProtocol: "https"` in the config, which I thought would add the `https://` automatically, but perhaps I misunderstood. (In my app, the URLs are coming from user input, so I don't expect them to always contain a protocol.)

All settings:
```ts
Link.configure({
  autolink: true,
  defaultProtocol: "https",
  linkOnPaste: true,
  openOnClick: true,
}),
```

### Browser Used

Firefox

### Expected Behavior

The link renders as an anchor with `href="google.com/images"` or `href="https://google.com/images"`.

### Additional Context (Optional)

Here is the complete generated tag, according to Firefox inspector:
```html
<a target="_blank" rel="noopener noreferrer nofollow" href="">inner text</a>
```

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
In the docs: https://tiptap.dev/docs/editor/extensions/marks/link#default-protocol it says that the defaultProtocols option is only valid for pasting links and autolinks.

If you set an href, it will respect it
