### ISSUE TITLE
Wrong menu bubble position with RTL text

### ISSUE THREAD

**Issue by reza-akbari** [ueberdosis/tiptap#583]
**Describe the bug**
bubble menu position is incorrect when selecting a mark in RTL languages (Persian and Arabic tested)

**Steps to Reproduce / Codesandbox Example**
1. Go to 'https://tiptap.dev/menu-bubble'
2. Add this (or any other RTL text)
`سلام ، سعی کنید متن را در اینجا انتخاب کنید. منو برای انتخاب برخی از سبک های درون خطی ظاهر خواهد شد. به یاد داشته باشید: شما کنترل کاملی در مورد محتوا و سبک این منو دارید.`
4. Select a word and make it bold
5. Menu moves to left or right

**Expected behavior**
Menu should stay above the text

**Screenshots**
![image](https://user-images.githubusercontent.com/35025677/72661810-15470200-39f4-11ea-9400-502ea40eb600.png)

**Environment**
 - OS: windows 10
 - Browser: Chrome
 - Version: 79
 - Mobile / Desktop: Desktop

**Comment by reza-akbari** [comment]
is there a workaround for this?

**Comment by hanspagel** [comment]
Thanks for reporting @reza-akbari! We’re in the process of rewriting the whole interface components and I added this to the list of things we need to consider. 🙌

**Comment by reza-akbari** [comment]
Thank you @hanspagel but I think this is not fixed in v2:

![image](https://user-images.githubusercontent.com/35025677/120265176-abf82400-c2b4-11eb-817d-f3d21f0a1d00.png)

**Comment by philippkuehn** [comment]
the applied fix should improve RTL support.
