### ISSUE TITLE
[Bug]: React `useEditor` does not react when option value changes

### ISSUE THREAD

**Issue by drewzemke-rss** [ueberdosis/tiptap#5831]
### Affected Packages

react

### Version(s)

2.9.1

### Bug Description

I'm calling `useEditor` and passing a value of the `editable` option that changes depending on app state. But when that value changes, the editor itself does not change to/from an editable state. See the code sandbox example.

### Browser Used

Chrome

### Code Example URL

https://codesandbox.io/p/sandbox/nameless-cookies-9fwhgc

### Expected Behavior

When I change the value of `editable` (or other options, I didn't check) that's passed into `useEditor`, the component should update accordingly.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
useEditor has a second parameter that takes a dependency array, by default it does not react to state changes
