### ISSUE TITLE
[Help Needed] Position Menu bubble with popper.js and vue-portal

### ISSUE THREAD

**Issue by Neophen** [ueberdosis/tiptap#584]
**Menu bubble how to use something like vue-portal + popper.js**

I have a page builder with rich text editor with TipTap. I'm having layout problems like the following:
---
![Screenshot 2020-01-21 at 12 23 33](https://user-images.githubusercontent.com/6092928/72798491-e32fdd00-3c4b-11ea-887b-07834062582d.png)
---

Is there a way to put the menu bubble in a portal so that i could avoid issues like this? 
also to use popper.js to position the bubble, as now if the content is at the bottom of the page, it is positioned below the view.

Any help is greatly appreciated.

**Comment by velentZ** [comment]
> **Menu bubble how to use something like vue-portal + popper.js**
> 
> ## I have a page builder with rich text editor with TipTap. I'm having layout problems like the following:
> ## ![Screenshot 2020-01-21 at 12 23 33](https://user-images.githubusercontent.com/6092928/72798491-e32fdd00-3c4b-11ea-887b-07834062582d.png)
> Is there a way to put the menu bubble in a portal so that i could avoid issues like this? also to use popper.js to position the bubble, as now if the content is at the bottom of the page, it is positioned below the view.
> 
> Any help is greatly appreciated.

Hi，have you fixed this issue
