### ISSUE TITLE
[Bug]: Link.extend does not work with LinkOptions

### ISSUE THREAD

**Issue by unachang113** [ueberdosis/tiptap#5845]
### Affected Packages

core, extension-link, react

### Version(s)

2.9.1

### Bug Description

When extending the Link extension using Link.extend, options such as openOnClick and linkOnPaste do not work. If anyone has a solution, please let me know.

When configured via configure within useEditor, as shown below, these options work properly. However, they stop functioning when using Link.extend.

## 🟢 Working Example:
```
const editor = useEditor({
    editable: true,
    extensions: [
        Link.configure({
            openOnClick: false,
            linkOnPaste: false,
        })
    ],
    ...
});
```

## ❌️ Not Working Example:
```
export const LinkExtension = Link.extend({
    openOnClick: false,
    linkOnPaste: false,
});
```

### Browser Used

Chrome

### Code Example URL

https://codesandbox.io/p/sandbox/ecstatic-neumann-gc8wz8

### Expected Behavior

The specified LinkOptions should function correctly as configured.

### Additional Context (Optional)

https://github.com/user-attachments/assets/3dcb72a9-41a9-4d3c-9e61-2bdca976cc00

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
@unachang113, the `.extend` API is for extending the extension (in this case a mark) settings. Whereas `.configure` is for setting the extension's options. They do different things.

`.configure` controls `this.options` within the extension. `.extend` controls the extension itself. Please read the docs for more information: https://tiptap.dev/docs/editor/extensions/custom-extensions/extend-existing
