### ISSUE TITLE
[Bug]: React 19 messes with "Mentions" example

### ISSUE THREAD

**Issue by CHE1RON** [ueberdosis/tiptap#5846]
### Affected Packages

extension-mention

### Version(s)

2.9.1

### Bug Description

When React v19 is installed, the example over at https://tiptap.dev/docs/editor/extensions/nodes/mention stops working (= `ref` not being passed correctly) due to changes to the way refs are handled in general it would seem - and `ref` cannot be passed to `ReactRenderer` 🤔 

When using `forwardRef` everything works as expected though.

### Browser Used

Chrome

### Expected Behavior

Example works just as before

### Additional Context (Optional)

Clicking on a list entry still works

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Thanks for pointing this out @CHE1RON I think I've resolved it & will push a new release

**Comment by CHE1RON** [comment]
That's great to hear, and let me say I'm really impressed by your speed ⚡ 🏆

**Comment by nperez0111** [comment]
Released with 2.10.0

**Comment by CHE1RON** [comment]
I will test & report back!
