### ISSUE TITLE
How to get distance from cursor to top of the document?

### ISSUE THREAD

**Issue by akirarika** [ueberdosis/tiptap#585]
**Is your feature request related to a problem? Please describe.**
I need a floating element like menu bubble, difference is that it always float on cursor

**Describe the solution you'd like**
I am a novice.. is there a function to get position(x and y) of cursor?

**Describe alternatives you've considered**
```javascript
getCursorTop() {
    let range, rects, rect;
    let document = window.document;
    let selection = document.selection;
    let top = 0;

    selection = window.getSelection();
    if (selection.rangeCount) {
        range = selection.getRangeAt(0).cloneRange();
        if (range.getClientRects) {
            range.collapse(true);
            rects = range.getClientRects();
            if (rects.length > 0) rect = rects[0];
            if (rect) top = rect.bottom;
        }
    }
    return top;
}
```

**Comment by Mansehej** [comment]
Get the prosemirror state of the editor using editor.state, and access the selection inside it to get the head and anchors of the cursor, instead of using the window selection. 

Check out the documentation of Prosemirror-State to get a better understanding.
