### ISSUE TITLE
[Bug]: AI autocomplete is called when using the table's Tab shortcut

### ISSUE THREAD

**Issue by kart-c** [ueberdosis/tiptap#5850]
### Affected Packages

@tiptap/extension-table

### Version(s)

2.7.2 (as per tiptap template)

### Bug Description

The `Tab` key is the default trigger for AI autocomplete. This is called every time `Tab` is pressed inside the table extension.

Increasing the priority of the table extension to 101 does stop the API call when `Tab` is pressed. But the issue still persists, if the user is in first cell in the first row and `Shift-Tab` is pressed.

https://github.com/user-attachments/assets/e0d3b476-95ea-49c8-b49d-7d8629dedffc

### Browser Used

Chrome

### Expected Behavior

Pressing `Tab` or `Shift-Tab` should not trigger autocomplete. 

I am not entirely sure if other devs would have this requirement, but if the `autocomplete` option had some sort of callback function with access to the editor instance then it can be toggled true / false based on conditions like `editor.isActive('table')`. It can be either boolean or callback.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by alexvcasillas** [comment]
<img width="950" alt="Captura de pantalla 2024-11-26 a las 10 47 34" src="https://github.com/user-attachments/assets/71201730-0005-4202-bd08-ff8dee54f5ab">

Not only happens within the `@tiptap/extension-table` but under any other node whenever you press tab.

We're looking into it 👀

**Comment by alexvcasillas** [comment]
Looking into the interaction with `@tiptap-pro/extension-ai` as this is the one that causes the trouble 👀

**Comment by kart-c** [comment]
Thanks Alex 🙌🏻. Will close the issue.
