### ISSUE TITLE
[Bug]: While setting `content` directly while using CharacterCount with limit is not obeyed

### ISSUE THREAD

**Issue by gethari** [ueberdosis/tiptap#5851]
### Affected Packages

core,extension-character-count,react

### Version(s)

2.10.x

### Bug Description

I thought I messed up something, my editor was not recognizing the content, it was just white screen. After investigating I found out that, I was using `CharacterCount` extension with limit set to `1000`, my content length was longer than that.

- Can we have a console warning or something to solve the above nightmare for future users ?

Now there's another bug that I found is, my setup use the below way to set the content,

```ts
const handleCreate = React.useCallback(
		(editor: Editor) => {
			if (content && editor.isEmpty) {
				editor.commands.setContent(content);
			}
		},
		[content],
	);
```

```ts
	onCreate: ({ editor }) => handleCreate(editor),
```

While the limit is obeyed and no content is set in the above way, but by directly passing the `content` to the `useEditor` hook sets the content in the editor bypassing the limit.

I have added a [CodeSandbox](https://codesandbox.io/p/sandbox/tiptap-react-qidlsv) to reproduce this issue, please let me know if I can be of help

### Browser Used

Firefox

### Code Example URL

https://codesandbox.io/p/sandbox/tiptap-react-qidlsv

### Expected Behavior

The `content` should not be set when the `limit` is set & the size of the content is longer than the allowed limit.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
v2.10.3 resolves this
