### ISSUE TITLE
[Bug]: Type error in `addOptions` when extending extension (regression introduced in 2.10.0)

### ISSUE THREAD

**Issue by Mathias-S** [ueberdosis/tiptap#5852]
### Affected Packages

@tiptap/extension-link

### Version(s)

2.10.0

### Bug Description

When trying to extend certain extensions, such as `@tiptap/extension-link`, using `addOptions` and `...this.parent?.()`, v2.10.0 has introduced an error in code that previously worked fine:

```ts
import Link from "@tiptap/extension-link";

const MyLink = Link.extend({
  addOptions() { // TypeError here
    return {
      ...this.parent?.(),
    };
  },
});
```

### Browser Used

Chrome

### Expected Behavior

Since this is very similar to [code in the docs](https://tiptap.dev/docs/editor/extensions/custom-extensions/extend-existing#settings), I expect this to work without any errors. Alternatively, there should be another way to extend Link without having to provide all options.

### Additional Context (Optional)

Probably a regression caused by the commits related to #5768

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Thanks for pointing this out. Resolved with: https://github.com/ueberdosis/tiptap/releases/tag/v2.10.1
