### ISSUE TITLE
[Bug]: node_modules/@tiptap/core/dist/NodeView.d.ts:31:5 - error TS2416: Property 'ignoreMutation' in type 'NodeView<Component, NodeEditor, Options>' 

### ISSUE THREAD

**Issue by seybi79** [ueberdosis/tiptap#5867]
### Affected Packages

tip tap core

### Version(s)

2.10.2

### Bug Description

When I build my application getting below error
node_modules/@tiptap/core/dist/NodeView.d.ts:31:5 - error TS2416: Property 'ignoreMutation' in type 'NodeView<Component, NodeEditor, Options>' is not assignable to the same property in base type 'NodeView'.
  Type '(mutation: MutationRecord | { type: "selection"; target: Element; }) => boolean' is not assignable to type '(mutation: ViewMutationRecord) => boolean'.
    Types of parameters 'mutation' and 'mutation' are incompatible.
      Type 'ViewMutationRecord' is not assignable to type 'MutationRecord | { type: "selection"; target: Element; }'.
        Type '{ type: "selection"; target: Node; }' is not assignable to type 'MutationRecord | { type: "selection"; target: Element; }'.
          Type '{ type: "selection"; target: Node; }' is not assignable to type '{ type: "selection"; target: Element; }'.
            Types of property 'target' are incompatible.
              Type 'Node' is missing the following properties from type 'Element': attributes, classList, className, clientHeight, and 118 more.

31     ignoreMutation(mutation: MutationRecord | {
       ~~~~~~~~~~~~~~



### Browser Used

Chrome

### Code Example URL

_No response_

### Expected Behavior

Build without fail..

### Additional Context (Optional)

_No response_

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Yep changed here: https://github.com/ProseMirror/prosemirror-view/commit/cebd804782228f235aa972ea204b22045bde2132

**Comment by gasfab999** [comment]
I also faced this issue when integrating it into my angular repo. I could also reproduce it in a newly created angular repo on stackblitz https://stackblitz.com/edit/stackblitz-starters-3n6y2x?file=src%2Fmain.ts

**Comment by nperez0111** [comment]
> I also faced this issue when integrating it into my angular repo. I could also reproduce it in a newly created angular repo on stackblitz [stackblitz.com/edit/stackblitz-starters-3n6y2x?file=src%2Fmain.ts](https://stackblitz.com/edit/stackblitz-starters-3n6y2x?file=src%2Fmain.ts)

I fixed your sandbox with `"skipLibCheck": true,` see it here: https://stackblitz.com/edit/stackblitz-starters-pyzqxr?file=tsconfig.json

Really should not be type checking library code, not just for perf but minor incompatibilities like this.

**Comment by gasfab999** [comment]
@nperez0111 I get you point. But it seems in angular repos for example this seem to be enabled by default.

Can confirm that `"skipLibCheck": true` also fixed it for me in my repo, thx :+1:
