### ISSUE TITLE
[Bug]: useLayoutEffect ssr react warning

### ISSUE THREAD

**Issue by frattaro** [ueberdosis/tiptap#5872]
### Affected Packages

react

### Version(s)

latest

### Bug Description

The latest version of tiptap uses `useLayoutEffect`, and in an ssr site react throws hundreds of warnings about using `useLayoutEffect` on ssr. Can you use useIsomorphicLayoutEffect?

![image](https://github.com/user-attachments/assets/6ff41654-39d8-45b1-b6c5-8868d02e774f)

### Browser Used

Chrome

### Expected Behavior

avoid the warnings if possible. they're dumb warnings and people have complained to the react team about them but they haven't done anything

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Ah, fair. Yea I can

**Comment by nperez0111** [comment]
v2.10.3 resolves this
