### ISSUE TITLE
[PRO]: React 19 Compatibility: Request to Resolve tippyjs-react Dependency Issue in @tiptap-pro/extension-drag-handle

### ISSUE THREAD

**Issue by CastaChick** [ueberdosis/tiptap#5876]
### Affected Packages

extension-drag-handle

### Version(s)

2.15.0

### Description of the Bug

Thank you for releasing a version of tiptap 2.10 compatible with React 19.

However, the @tiptap-pro/extension-drag-handle extension depends on tippyjs and tippyjs-react, which were archived on November 9 without being updated for React 19. As a result, the following error occurs when opening the editor:

```
Accessing element.ref was removed in React 19. ref is now a regular prop. It will be removed from the JSX Element type in a future release.
```

According to the [tippyjs-react repository](https://github.com/atomiks/tippyjs-react), it is recommended to migrate to Float UI. Would it be possible to address this issue?

### Browser Used

Chrome

### Expected Behavior

To be able to use this extension without any errors.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Removing tippy would be a major breaking change so we cannot make this change at this time. 

With Tiptap v3 we have already merged a PR for moving to floating UI but the v3 version tends to lag behind as we don't have the time to keep everything up to date. 

This is a warning, but does it not work?

If just a warning, then I cannot support such a change right now and React 19 is still just a beta

**Comment by CastaChick** [comment]
@nperez0111 Thank you for reply. 

> If just a warning, then I cannot support such a change right now and React 19 is still just a beta

Just a warning is displayed, but since it doesn't affect the actual behavior, I think I'll wait for the release of V3. Thank you!

**Comment by jogilvyt** [comment]
We have also just hit this issue after upgrading to React 19 - is there a timeline for when this migration away from tippy.js will be done now that React 19 is out of beta? 

The main issue is that we have to install dependencies with the `--legacy-peer-deps` flag now, as `@tiptap-pro/extension-drag-handle` only supports React 18, which isn't ideal.

**Comment by nperez0111** [comment]
> We have also just hit this issue after upgrading to React 19 - is there a timeline for when this migration away from tippy.js will be done now that React 19 is out of beta?

Not unless an actual issue occurs (i.e. an error), or v3 is ready, whichever comes first.

> The main issue is that we have to install dependencies with the `--legacy-peer-deps` flag now, as `@tiptap-pro/extension-drag-handle` only supports React 18, which isn't ideal.

This seems orthogonal to the issue, I can bump the dep range for this package now

**Comment by linhtrinh18** [comment]
Any update on this issue. I got an an console error with react 19:

Console Error

Accessing element.ref was removed in React 19. ref is now a regular prop. It will be removed from the JSX Element type in a future release.

Can we fix it? or at least turn off the warning, it's kind of annoying as it always pop up in development
