### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'isDestroyed')

### ISSUE THREAD

**Issue by ownerdelmee** [ueberdosis/tiptap#5881]
### Affected Packages

core

### Version(s)

2.10.3

### Bug Description

this issue occurs when blocknote and tiptap is launched with typescript and nextjs it seems to be a problem of tiptap/core reading a value of undefined. the call stack points that the error occured at tiptap/core. here is the error : Unhandled Runtime Error

TypeError: Cannot read properties of undefined (reading 'isDestroyed')

Call Stack
_e.createNodeViews
node_modules/@tiptap/core/dist/index.js (4548:1)
eval
node_modules/@blocknote/react/dist/blocknote-react.js (2517:1)

### Browser Used

Chrome

### Expected Behavior

the editor to work perfectly fine.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by ownerdelmee** [comment]
"Oops! Here's the stack trace for reference:

- _e.createNodeViews at node_modules/@tiptap/core/dist/index.js (line 4548)

- eval at node_modules/@blocknote/react/dist/blocknote-react.js (line 2517)"

Let me know if there's anything else you'd like help with! 😊.

**Comment by ownerdelmee** [comment]
Hey, I think I’ve figured out the root cause! It looks like either Next.js or Tiptap gets a bit confused when there’s a useEffect with no dependencies. Since that makes it run after the component is mounted (onMount), it doesn’t append a value to isDestroyed, which ends up causing this error.

Just wanted to share this insight, and thank you so much for your time and effort—it’s really appreciated! 😊

**Comment by nperez0111** [comment]
Wait so what was the resolution here? Is there anything in the lib we need to change?

**Comment by sarthak-kumar-shailendra** [comment]
Could anyone kindly mention what was the resolution here?
