### ISSUE TITLE
[Bug]: linkOnPaste does not work on Linux + Firefox

### ISSUE THREAD

**Issue by Leviob** [ueberdosis/tiptap#5883]
### Affected Packages

core

### Version(s)

2.10.3

### Bug Description

Links pasted into the editor typically automatically have the hyperlink created. If text is highlighted when a link is pasted, the text becomes a hyperlink to the copied link. This works for me on Windows in both Firefox and Chrome, and in Chrome on Linux.

However, in the latest **Firefox**, on **Ubuntu Linux**, this does not work. Pasting a link just pastes the text and it does not turn into a hyperlink automatically. Highlighting text and pasting a link just replaces the originally highlighted text.

I have tried launching Firefox in safe mode with all extensions disabled, disabling Firefox's enhanced tracking protection, and it still behaves as described above.

### Browser Used

Firefox

### Code Example URL

https://templates.tiptap.dev/

### Expected Behavior

- On Linux+Firefox, paste a link, such as https://templates.tiptap.dev/ into this demo block text editor. In other browsers, such as Chrome, this creates a link automatically. In Firefox, it pastes the text, but does not create a link.
- on Linux+Firefox, highlight some text, and paste a link. In other browsers, this adds a link to the selected text. In Firefox, this replaces the text with the copied link.

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
Link pasting seemed to work for me on Firefox on macOS. Can you send a screen recording? Could this be due to clipboard handling on linux?

**Comment by nperez0111** [comment]
I don't know what the problem here could be. That feels like a browser bug since I got it to work on macOS firefox 🤷  I'm not sure there is much we can do here
