### ISSUE TITLE
[PRO]: Drag Handle vue

### ISSUE THREAD

**Issue by SunHengX** [ueberdosis/tiptap#5896]
### Affected Packages

extension-drag-handle-vue-3

### Version(s)

2.16.3

### Description of the Bug

I copied the examples from the official website of tiptap and then ran them locally, but they didn't work properly. I'm currently using Vue 3. Could any expert please help me solve this problem?
![image](https://github.com/user-attachments/assets/2671cd8b-f589-4123-b415-1cfb60bf1b40)

### Browser Used

Chrome

### Expected Behavior

An error will occur when I use `<drag-handle :editor="editor"> I hope it can be solved. 

### Additional Context (Optional)

![image](https://github.com/user-attachments/assets/6a34306d-181f-4de2-80fa-100a748b9cb1)

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by nperez0111** [comment]
More information on your integration would be needed to help you with this

**Comment by SunHengX** [comment]
> 需要更多有关您的集成的信息来帮助您实现这一点
I am using the official Tiptap demo from the Tiptap website.
![image](https://github.com/user-attachments/assets/3245f6d1-cae7-4630-b24b-088908e6fd6a)
![image](https://github.com/user-attachments/assets/e6ea9abe-28f7-4eac-b5e7-ff76a347cea3)

**Comment by KevinvOosterhout** [comment]
I'm experiencing the same with a Nuxt project. I've tried it with pure Vue too. See repo for reproduction: https://github.com/KevinvOosterhout/tiptap-draghandle-vue-bug

**Comment by KevinvOosterhout** [comment]
![Screenshot 2024-12-05 at 9 10 26 PM](https://github.com/user-attachments/assets/0f79f27f-1dfe-4dd9-8447-d73f61895672)

**Comment by SunHengX** [comment]
@nperez0111 Please help us resolve this issue, experts.

**Comment by nperez0111** [comment]
I don't have the time to look into this, but here is what the source is doing, perhaps you can figure it out yourselves from there:

```vue
import { Editor } from '@tiptap/vue-3'
import {
  DragHandlePlugin,
  dragHandlePluginDefaultKey,
  DragHandlePluginProps,
} from '@tiptap-pro/extension-drag-handle'
import {
  defineComponent, h, onBeforeUnmount, onMounted, PropType, ref,
} from 'vue'

type Optional<T, K extends keyof T> = Pick<Partial<T>, K> & Omit<T, K>;

export type DragHandleProps = Omit<Optional<DragHandlePluginProps, 'pluginKey'>, 'element'> & {
  class?: string;
  onNodeChange?: (data: { node: Node | null; editor: Editor; pos: number }) => void;
};

export const DragHandle = defineComponent({
  name: 'DragHandleVue',

  props: {
    pluginKey: {
      type: [String, Object] as PropType<DragHandleProps['pluginKey']>,
      default: dragHandlePluginDefaultKey,
    },

    editor: {
      type: Object as PropType<DragHandleProps['editor']>,
      required: true,
    },

    tippyOptions: {
      type: Object as PropType<DragHandleProps['tippyOptions']>,
      default: () => ({}),
    },

    onNodeChange: {
      type: Function as PropType<DragHandleProps['onNodeChange']>,
      default: null,
    },

    class: {
      type: String as PropType<DragHandleProps['class']>,
      default: 'drag-handle',
    },
  },

  setup(props, { slots }) {
    const root = ref<HTMLElement | null>(null)

    onMounted(() => {
      const {
        editor, pluginKey, onNodeChange, tippyOptions,
      } = props

      editor.registerPlugin(
        DragHandlePlugin({
          editor,
          element: root.value as HTMLElement,
          pluginKey,
          tippyOptions,
          onNodeChange,
        }),
      )
    })

    onBeforeUnmount(() => {
      const { pluginKey, editor } = props

      editor.unregisterPlugin(pluginKey as string)
    })

    return () => h('div', { ref: root, class: props.class }, slots.default?.())
  },
})

```

**Comment by KevinvOosterhout** [comment]
For some strange reason i've got it to function when using the pasted code above inside of a component with just a script tag around it, and changing the import to `import { DragHandle } from '~/components/DragHandle.vue' `.

**Comment by nperez0111** [comment]
Perhaps it was built incorrectly? This project does have both vue 2 & vue 3 maybe it chose the wrong one?

**Comment by nperez0111** [comment]
I'm releasing a new version, it looks like it was being bundled with the entire vue package because I did not declare it as a peer dep. Try this version: 2.16.5-beta.0

**Comment by KevinvOosterhout** [comment]
I've just tested the beta and it works like a charm. Thanks for the quick response.
