### ISSUE TITLE
Allow floating menu for nested nodes

### ISSUE THREAD

**Issue by franzwilding** [ueberdosis/tiptap#590]
I'm trying to build a page bulder with tiptap, at the moment I'm working on a row / column grid system and until now, everything is working quit well. 

However I am facing one problem, when trying to use the FloatingMenu: It only works for the root elements, but not for my nested grid blocks, because of this check here: 

https://github.com/scrumpy/tiptap/blob/ec9c2f3e1f6c8d72421307978600141ed0418307/packages/tiptap/src/Plugins/FloatingMenu.js#L37

So my question is: Is this check required? I don't see why we need it. I tested the floating menu without this check, and everything is working as expected.

**Comment by hanspagel** [comment]
Thanks for the report @franzwilding! I’ve added this to the list of things we need to consider when rewriting the components for [tiptap v2](https://blog.ueber.io/post/our-plan-for-tiptap-2/).
