### ISSUE TITLE
Marks are applied only when we insert prefix -> body -> suffix, strictly in this order

### ISSUE THREAD

**Issue by christosnc** [ueberdosis/tiptap#592]
### **Current situation**
For any mark to be activated, we need to input the prefix (ex. \`), **then** the body (ex. hello), and **then** the suffix (ex. \`).

### **Problem**
If we have \`\` somewhere in our document and then we add "hello" in between the backticks, it won't be interpreted as code.

### **Suggestion**
We should be able to do this:
1. Type: ``
2. Put the caret between the two backticks (left arrow or click)
3. Write something and (when we input the first character) transform into code
<br>
<br>
By the way, this problem applies to all marks, not just code, I just used `` as an example.

**Comment by hanspagel** [comment]
Thanks for reporting @christosnc! I think that’s more like a feature than a bug though.

Imagine you'd want to type literally \*foobar\*. With the current behaviour you can do this, with your suggested behaviour that wouldn’t work. It would always apply the Mark. 😏

I’m closing this here for now, but I’ll keep it in my notes to consider. ✌️
