### ISSUE TITLE
[Bug]: Negative lookahead prevents loading on Safari on iOS 15.7

### ISSUE THREAD

**Issue by Nantris** [ueberdosis/tiptap#5948]
### Affected Packages

extension-code

### Version(s)

2.10.4

### Bug Description

These lines cause Safari to fail to load the page on these older versions:

https://github.com/ueberdosis/tiptap/blob/d735cf3c758d52ecb2273e45cc0c9727dbf6eccd/packages/extension-code/src/code.ts#L45-L51

### Browser Used

Chrome

### Expected Behavior

Safari on iOS 15.7 is supported.

I'm not sure what version last worked at the moment - but it definitely used to work.	

### Additional Context (Optional)

Presumably first broken here: https://github.com/ueberdosis/tiptap/commit/f79c05edd40a43531752e90db9ce9f814d124272

This can be worked around for a "best of both worlds" approach - but it's probably best done one a project-wide level rather than locally in the file so I'm not sure how the team will want to handle this.

**We use an approach like this:**

**checkLookBehindSupport.js**
```js
function checkLookBehindSupport() {
  try {
    new RegExp('(?<=<kbd>)[sS]+(?=</kbd>)');
    return true;
  } catch {
    return false;
  }
}

export const supportsLookBehind = checkLookBehindSupport();
```

and then wherever else in the project:

```js
import { supportsLookBehind } from './supportsLookBehind';

export const matcherRegex = supportsLookBehind
  ? // eslint-disable-next-line prefer-regex-literals -- iOS 15.x support
    new RegExp('our-advanced-regex')
  : /our-basic-regex/;
```

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

**Comment by Nantris** [comment]
@nperez0111 sorry to ping - this is a blocker for us and patching is not so easy in our setup so I'm hoping to avoid it. Any thoughts on the approach outlined above?

**Comment by Nantris** [comment]
Accidental duplicate of #5889.

**Comment by nperez0111** [comment]
Yes, this is a dupe

**Comment by Nantris** [comment]
You're absolutely right. I thought that iOS 15.x still had an additional issue to resolve but I was mistaken. Sorry for the noise/clutter.
