### ISSUE TITLE
NuxtJS Custom Node Issue

### ISSUE THREAD

**Issue by Dyceman** [ueberdosis/tiptap#602]
I am getting the below error for my custom Iframe Node while my NuxtJS server is ran in production. (NuxtJs is just VueJS serverside rendering)
The custom Node works in development.
Can someone help me solve this issue?

`TypeError: "e is undefined"
    NuxtJS 14
        Rr
        he
        Mr
        T
        T
        T
        Co
        _update
        r
        get
        run
        _n
        ue
        ie
c221072b075b9cf53795.js:2:12604
    NuxtJS 5
`

[File Gist](https://gist.github.com/Dyceman/41826acf8d0946d00caf9d738f31d6c1)

**Comment by Dyceman** [comment]
Is this project dead?

**Comment by philippkuehn** [comment]
@Dyceman nope. tiptap v2 is still in planning for the next months.

**Comment by tvld** [comment]
@Dyceman  Not sure if this is the issues, but you need to initiated the Editor on mounted in Nuxt to make sure it has a place to mount...  I use Nuxt and it works fine

```js
mounted () {
    this.editor = new Editor({
      extensions: [
        new Bold(),
        new Italic(),
       // ...
      ],
      //...
    })
  },
```
