### ISSUE TITLE
Cursor Stuck with NodeView

### ISSUE THREAD

**Issue by BrianHung** [ueberdosis/tiptap#608]
**Describe the bug**
Cursor gets stuck below a `contenteditable=false` element when `get view()` is defined and rendered with Vue. This issue is similar to #296 in that there's a cursor issue related to a custom NodeView with a code element.

![Screen Recording 2020-02-15 at 2 40 33 AM 2020-02-15 02_49_02](https://user-images.githubusercontent.com/15721634/74586632-37558500-4f9e-11ea-9ec8-1c14a69c2de4.gif)

**Steps to Reproduce**

1. Add the following extension to a TipTap editor.
2. Create a paragraph node.
3. At the beginning of a new line, create a MathBlock node by typing `$$$`.
4. Navigate from paragraph node down to the MathBlock node with the arrow-down key.
5. Navigate from MathBlock node up to paragraph with the arrow-up key.

The last step fails due to the cursor unable to move from the inner `code` to the `p` element.

```js
// MathBlock.js
import { Node } from 'tiptap'
import { toggleBlockType, setBlockType, textblockTypeInputRule } from 'tiptap-commands'

/*
 * Defines a ComponentView for MathBlock.
 */
export default class MathBlock extends Node {

  get name() {
    return "mathblock";
  }

  get schema() {
    return {
      content: "text*",
      marks: "",
      group: "block",
      code: true,
      defining: true,
      draggable: false,
      parseDOM: [{ tag: "div", class: "MathBlock"}],
      toDOM: (node) => ["div",{class: "MathBlock"} ,
        ["div", {class: "katex-render" , contenteditable: 'false'}],
        ["pre", {class: "katex-editor"}, ["code", 0]]
      ],
    };
  }

  get view() {
    return {
      template: `
        <div class="MathBlock">
          <div class="katex-render" :contenteditable="false"></div>
          <pre class="katex-editor"><code ref="content"></code></pre>
        </div>`
    }
  }

  commands({ type, schema }) {
    return () => toggleBlockType(type, schema.nodes.paragraph)
  }

  keys({ type }) {
    return {
      "Shift-Ctrl-\\": setBlockType(type),
    }
  }

  inputRules({ type }) {
    return [
      textblockTypeInputRule(/^\$\$\$$/, type),
    ];
  }
```

In HTML, the editor is given by
```html
<div contenteditable="true" tabindex="0" class="ProseMirror">
   <p class=""><br></p>
   <div class="MathBlock">
      <div class="katex-render" contenteditable="false"></div>
      <pre class="katex-editor"><code>mathblock</code></pre></div>
   <p class=""><br></p>
</div>
```

**Expected behavior**
Cursor should be able to move from and to the paragraphs and codeblocks.

![Screen Recording 2020-02-15 at 2 41 35 AM 2020-02-15 02_51_57](https://user-images.githubusercontent.com/15721634/74586629-34f32b00-4f9e-11ea-9acd-7ec0be1e658a.gif)

**We can achieve the expected behavior by commenting out the `get view()` function.** However, this is not ideal as later we want to update the`katex-render` div with content from the editor by making hte MathBlock a Vue component. The outputted HTML when `get view()` is commented out stays the same, so this suggests an issue with TipTap or Vue.

```js
import { Node } from 'tiptap'
import { toggleBlockType, setBlockType, textblockTypeInputRule } from 'tiptap-commands'

/*
 * Defines a ComponentView for MathBlock.
 */
export default class MathBlock extends Node {
  ...
  /*
  get view() {
    return {
      template: `
        <div class="MathBlock">
          <div class="katex-render" :contenteditable="false"></div>
          <pre class="katex-editor"><code ref="content"></code></pre>
        </div>`
    }
  }
  */
  ...
  }
```

**Comment by BrianHung** [comment]
After looking at the [TodoItem](https://github.com/scrumpy/tiptap/blob/master/packages/tiptap-extensions/src/nodes/TodoItem.js) extension for inspiration (both the MathBlock and TodoItem mixes editable and un-editable content together; with TodoItem, the cursor is able to seamlessly move up an down), I found that the expected behavior can be achieved with a few CSS tweaks.

```css
.MathBlock {
  display: flex;
}
.katex-render {
  flex: 0 0 100%;
}
.katex-editor {
  flex-grow: 1;
}
```

I don't have a good reason for why `display: flex` with `get view()` defined works, while `display: block` with `get view()` defined doesn't work. Nor a reason why `display: block` with `get view()` not defined works, since it's `display block` in that case too.

**Comment by BrianHung** [comment]
**Describe the bug**
There's a follow-bug related with the NodeView: when the last character within the `code` block is deleted, instead of the schema and content node being kept, it deletes the `code` block entirely but keeps the `pre` element.

**Steps to Reproduce**
1. Create a new MathBlock with the `display: flex` css
2. Type characters into the code block
3. Delete the characters using your _keyboard_. Note that the bug doesn't occur if you select with mouse and then delete.

```html
<div class="MathBlock">
  <div contenteditable="false" class="katex-render"></div> 
  <pre class="katex-editor"><code>Before delete.</code></pre>
</div>
```
```html
<div class="MathBlock">
  <div contenteditable="false" class="katex-render"></div> 
  <pre class="katex-editor"><br></pre>
</div>
```

**Expected behavior**
The `code` block should be contain a line break inside and be empty otherwise.

```html
<div class="MathBlock">
  <div contenteditable="false" class="katex-render"></div> 
  <pre class="katex-editor"><code>Before delete.</code></pre>
</div>
```
```html
<div class="MathBlock">
  <div contenteditable="false" class="katex-render"></div> 
  <pre class="katex-editor"><code><br></code></pre>
</div>
```

Again, this bug only occurs with `get view()` defined.

**Comment by hanspagel** [comment]
Thanks for sharing! Closing this here for now. 👍 Add this to my notes for the upcoming documentation on Node Views.
