### ISSUE TITLE
Content Node Deleted with Custom NodeView

### ISSUE THREAD

**Issue by BrianHung** [ueberdosis/tiptap#609]
**Describe the bug**
When the last character within the `code` block is deleted, instead of the schema and content node being kept, it deletes the `code` block entirely but keeps the `pre` element. This bug is similar to #296 and was found debugging #608.

**Steps to Reproduce**
1. Create a new CodeBlock with a custom NodeView.
2. Type characters into the code block.
3. Delete the characters using your _keyboard_. Note that the bug doesn't occur if you select with mouse and then delete.

```html
<div class="CodeBlock">
  <pre><code>Before delete.</code></pre>
</div>
```
```html
<div class="CodeBlock">
  <pre><br></pre>
</div>
```

```js
import { Node } from 'tiptap'
import { toggleBlockType, setBlockType, textblockTypeInputRule } from 'tiptap-commands'

/*
 * Defines a ComponentView for CodeBlock.
 */
export default class CodeBlock extends Node {

  get name() {
    return "codeblock";
  }

  get view() {
    return {
      name: "codeblock",
      props: ['node', 'view', "getPos"],
      template: `
        <div class="CodeBlock ">
          <pre><code ref="content"></code></pre>
        </div>`
    };
  }

  get schema() {
    return {
      content: "text*",
      marks: "",
      group: "block",
      code: true,
      defining: true,
      draggable: false,
      parseDOM: [{ tag: "div", class: "CodeBlock "}],
      toDOM: (node) => ["div",{class: "CodeBlock "} ,
        ["pre", ["code", 0]]
      ],
    };
  }

  inputRules({ type }) {
    return [
      textblockTypeInputRule(/^```$/, type),
    ];
  }
}

```

**Expected behavior**
The `code` block should be contain a line break inside and be empty otherwise.

```html
<div class="CodeBlock">
  <pre><code>Before delete.</code></pre>
</div>
```
```html
<div class="CodeBlock">
  <pre><code><br></code></pre>
</div>
```

This bug only occurs with the custom NodeView defined via `get view()`. If the NodeView is not defined, then the `code` node works as expected.

**Comment by BrianHung** [comment]
This is the weirdest bug I've encountered. Again, with #608, a partial solution is a weird CSS fix: if we add change `display: block` to `display: flex` for the `pre` element, we get the expected behavior of
```html
<div class="CodeBlock">
  <pre><code><br></code></pre>
</div>
```
```css
.CodeBlock pre {
  display: flex;
}
```

**Comment by hanspagel** [comment]
Thanks for reporting @BrianHung! There seems to be a lot of strange behaviour around this, everything I’ve debugged until now was rooted in browsers handling it incorrect. I assume it’s the same here, when CSS does help. 😏
