### ISSUE TITLE
IE11"TypeError: Object doesn't support property or method 'entries'"

### ISSUE THREAD

**Issue by avner-hoffmann** [ueberdosis/tiptap#610]
When running on IE11, i get the following error:
"TypeError: Object doesn't support property or method 'entries'"

stack
"TypeError: Object doesn't support property or method 'entries'
   at setActiveNodesAndMarks (http://localhost:8080/app.js:231519:40)
   at init (http://localhost:8080/app.js:231133:12)
   at Editor (http://localhost:8080/app.js:231104:54)
   at Anonymous function (http://localhost:8080/app.js:52766:3)
   at Anonymous function (http://localhost:8080/app.js:318144:26)
   at flushCallbacks (http://localhost:8080/app.js:318065:9)"

tried to run it without any extenstion - still failed

my init:

this.$nextTick(() => {
        this.editor = new Editor({
            // autoFocus: true,
            editorProps: {
                handleTextInput: view => {
                    if (this.maxTextLength && view.state.doc.textContent.length >= this.maxTextLength && view.state.selection.empty) {
                        return true;
                    }
                    return false;
                },
                handlePaste: (view, event, slice) => {
                    if (this.maxTextLength && view.state.doc.textContent.length + slice.size > this.maxTextLength) {
                        return true;
                    }
                    return false;
                }
            },
            editable: this.isMessagingEnabled,
            extensions: [
            ],
            content: this.message,
            onUpdate: ({ getHTML }) => {
                this.message = getHTML();
            },
            onFocus: () => {
                this.onTextInputFocus();
            },
            onBlur: () => {
                this.onTextInputBlur();
            },
            onInit: () => {
                this.calcRtl();
            }
        });
    });
  },

**Comment by hanspagel** [comment]
Thanks for reporting! We are not able to support IE though, we’re just using too much modern features (e. g. proxies).
