### ISSUE TITLE
How do I add a new page when the current and first page ist full of content

### ISSUE THREAD

**Issue by Camelxxl** [ueberdosis/tiptap#611]
I need to add a new page when the user reaches the end of the page. In the current state you can write as much as you want and it gets cut at the top. Is there a way to implement this behaviour with tiptap? I looked everywhere and it didn't get mentioned. thanks

**Comment by BrianHung** [comment]
What is a "page"? You could probably implement this behavior with a plugin similar to the [trailing paragraph](https://tiptap.scrumpy.io/trailing-paragraph).

**Comment by Camelxxl** [comment]
I don't think that solves my problem. What I need is the possibility to write a document with more than one page. When the first page of the editor is full of content a new document gets added so the user can write an infinitely amount of pages. is this possible with tiptap?

**Comment by rasliche** [comment]
I don't think "pages" is a concept that TipTap is responsible for. Are you using another framework/library? Are you using an application that *uses* TipTap?
