### ISSUE TITLE
Copy copies more then just the text, it copies the element

### ISSUE THREAD

**Issue by NitzanShifrin** [ueberdosis/tiptap#612]
When ctrl +a, then ctrl + c, then ctrl + v over a text it the text editor, it copies the outer `<p>` tags as well, so now there are 2` <p>` instead of 1.

lets assume my editor is `<p>Hello<p>`
When following the commands I said, I get :` <p>Hello<p>  <p>Hello<p>`, instead of  `<p>HelloHello<p>`

Any fix for this? Is it on purpose?
Thanks

**Comment by NitzanShifrin** [comment]
For now I did a quickfix that works, but not sure this is the best behaviour:
```
 onUpdate: ({ getHTML, getJSON }) => {
                this.message = getHTML();
                const jsonElement = getJSON();
                if (jsonElement.content.length > 1) {
                    for (let i = 1; i < jsonElement.content.length; i++) {
                        jsonElement.content[i].content.forEach(innerElem => jsonElement.content[0].content.push(innerElem));
                    }
                    this.editor.setContent(jsonElement.content[0]);
                }
            },
```

**Comment by hanspagel** [comment]
I think that’s a feature. You can decide to select `Hello` and copy only that or copy **all** including the paragraph/headline/code block/whatever.

Thanks for sharing your workaround to get the desired behaviour though! ✨
