### ISSUE TITLE
Vue component based mark renders several extra component instances

### ISSUE THREAD

**Issue by ghubika** [ueberdosis/tiptap#613]
**The Problem**
I have a custom Mark, that renders with a Vue component, and it produces a rather esoteric error. 

The component commits a state to a vuex store on mouseover and mouseout events, based on which the classes of the component itself (and all other mark components, with the same observationId attr), and another component, outside of the editor are synchronized.

However, when I have **multiple** mark components, **with the same observationId** on mouseover and mouseout, **several extra instances of the components are created** - which is problematic, as the mark component also emits events to the outside, and this bug leads to multiple events being emitted, ruining the functionality.

It does not seem to happen, when I mouseover a mark, that does not have any other marks with the same observationId.

Pleases, see attached a picture of a highlight, that spans two paragraphs, therefore results in 2 component instances created, with the same observationId.

<img width="766" alt="Screenshot 2020-02-21 at 20 02 10" src="https://user-images.githubusercontent.com/24611852/75063513-5e074480-54e5-11ea-8dc0-4d18acb3002c.png">

On the second picture, you can see the message in the console written by the created hook of the component, while I keep hovering over one of the two marks, the created hook is constantly called - therefore new components are being created.

<img width="1674" alt="Screenshot 2020-02-22 at 8 27 42" src="https://user-images.githubusercontent.com/24611852/75088438-84f96100-554d-11ea-998a-de9837588cb0.png">

**UPDATE**

After examining it closer, I found, that the main issue might not be, that new components are created - although, that is not desirable either - but rather that **the old ones are not destroyed**, therefore several instances will exist at once.

**The Code**

the mark
```
import {Mark} from 'tiptap'
import {toggleMark} from 'tiptap-commands';
import HighlightComponent from "./Highlight";



export default class Highlight extends Mark {

          get name() {
            return 'highlight'
          }

          get schema() {
            return {
              attrs: {
        observationId: {
          default: null
        }
      },
      draggable: false,
      parseDOM: [
        {
          tag: "span[data-id]",
          class: "highlight",
          getAttrs: dom => ({
            observationId: dom.getAttribute('data-id')
          }),
        },
      ],
      toDOM: node => {
        return ["span", {class: "highlight", "data-id": node.attrs.observationId}, 0]
      }
    }
  }

  get view() {
    return HighlightComponent;
  }

  commands({type, schema}) {
    return attrs => toggleMark(type, attrs)
  }

}
```

The vue component
```
<template>
    <span @mouseover.stop="hoverHighlight(true)" @mouseout.stop="hoverHighlight(false)" class="highlight"
          :data-id="observationId" :class="{hovered: hoveredHighlightId === observationId}">
        {{node.textContent}}
    </span>
</template>

<script>
  export default {
    name: "Highlight",
    props: ["node"],
    data() {
      return {
        hovered: false
      }
    },
    created() {
      console.log("created " + this.node.attrs.observationId);
    },
    beforeDestroy() {
      console.log("destroyed " + this.node.attrs.observationId);
      this.$events.$off("request-highlight-pos");
    },
    computed: {
      observationId() {
        return this.node.attrs.observationId
      },
      hoveredHighlightId() {
        return this.$store.state.note.hoveredHighlightId;
      },
      highlightPositionUpdater() {
        return this.$store.state.note.highlightPositionUpdater;
      }
    },
    methods: {
      emitPos() {
        this.$nextTick(() => {
          this.$events.$emit("highlight-pos",
            {id: this.observationId, top: this.$el.getBoundingClientRect().top})
        });
      },
      hoverHighlight(hovered) {
        this.$store.commit("note/setHoveredHighlightId", hovered ? this.observationId : null)
      }
    },
    watch: {
      highlightPositionUpdater(newVal) {
        console.log("highlightPositionUpdater updated " + newVal + " for id " + this.node.attrs.observationId);
        this.emitPos();
      }
    }
  }
</script>

<style scoped>

</style>
```

**Comment by mathisdemos** [comment]
Is there any progress on this? We are seeing the same behaviour in a similar setup.

Would be great if this could be fixed.

**Comment by hanspagel** [comment]
Sorry for the silence here. I think it’s related to #372, which reports that multiple instances of components are created.

**Comment by philippkuehn** [comment]
nodeviews for marks are not well supported in prosemirror :( https://discuss.prosemirror.net/t/there-is-a-bug-in-marks-nodeview/2722/2

**Comment by philippkuehn** [comment]
Since this is [not official supported by ProseMirror](https://discuss.prosemirror.net/t/there-is-a-bug-in-marks-nodeview/2722/2), we removed that feature in tiptap v2.
