### ISSUE TITLE
Custom Floating Menu trigger.

### ISSUE THREAD

**Issue by prashant1k99** [ueberdosis/tiptap#616]
**I want to activate the floating menu after executing a function or after button click**
The floating menu automatically activates on the new line. I want it to activate on button click or using custom function...

**The Required Solution:**
I want it to activate the floating menu using another function that can be triggered either button or any other way....
**Like using regex, if the entered character is "/" then only it should be visible...**

**Comment by chanlito** [comment]
@prashant1k99 have you found a solution?

**Comment by prashant1k99** [comment]
Nope

**Comment by Simon-Renault** [comment]
That would be extremely helpful, I was also wondering how it could be possible. Have you found a solution to do this ?

**Comment by hanspagel** [comment]
Thanks for the suggestion! I add this to my notes, so we can take it into account when we rewrite all the toolbar components for [tiptap v2](https://blog.ueber.io/post/our-plan-for-tiptap-2/). 🙌
