### ISSUE TITLE
Drag Image or Handle will lead to popup new page in Firefox

### ISSUE THREAD

**Issue by sidian123** [ueberdosis/tiptap#617]
In Firefox, Drag a image file from desktop to tiptap editor, will lead to open a new page to dispaly it. 
it's same with drag a handle.

# drag image

You can see, I'm drag a image
![无标题](https://user-images.githubusercontent.com/44724649/75412765-7997a280-595e-11ea-8bc5-9575207b5c81.png)

then , it popup a new page
![无标题](https://user-images.githubusercontent.com/44724649/75412852-bfed0180-595e-11ea-9386-a227e9921929.png)

# drag handle
It's same with Handle, you can try it yourself in Firefox, go to https://tiptap.scrumpy.io/drag-handle

**Comment by sidian123** [comment]
I've sovled it. Due to Firefox's default behave, when a drag event propagate out to Firefox , it will open a new page to display the dragged data.

So, the solution is to stop event propagation. the code is show as follow:

1. html

   ```html
   <div class="rich-editor" @drop="stopEventPropagation">
       <menu-container class="menu-group" :editor="editor"></menu-container>
       <editor-content class="editor-content editor__content" :editor="editor" />
   </div>
   ```

2. the `stopEventPropagation` function

   ```javascript
   stopEventPropagation(event){
       event.stopPropagation();
   }
   ```

**Comment by hanspagel** [comment]
Thanks for sharing @sidian123! 🙌
