### ISSUE TITLE
Default enter behavior when holding ctrl, cmd or shift and enter

### ISSUE THREAD

**Issue by kodekaiju** [ueberdosis/tiptap#628]
Hi!

Thank you so much for a great editor! I really enjoy working with it :)

Unfortunately I have hit a roadblock and cannot figure out how to proceed from here. 

I'm making a comment field using TipTap and I want the user to be able to submit the comment by pressing enter. Therefore, I have made this extension (inspired by a post in another issue):

```
import { Extension, Plugin } from "tiptap";

export default class EnterHandler extends Extension {
  get name() {
    return "enter_handler";
  }

  get plugins() {
    return [
      new Plugin({
        props: {
          handleKeyDown: (view, event) => {
            if (event.key === "Enter" && (event.shiftKey || event.ctrlKey || event.metaKey)) return false; //This does not create a new line
            else if (event.key === "Enter") {
              this.options.addComment();
              return true;
            } else return false;
          }
        }
      })
    ];
  }
}
```
Since the user submits the comment by pressing enter I want the default enter behavior to trigger, when `ctrl`, `cmd` or `shift` is held down and enter is pressed. I know this can be done with the `HardBreak` extension, but then it's not possible to use `OrderedList` or `BulletList`, as they will not create a new `li` element.

Have anyone faced a similar problem? :)

**Comment by andreasvirkus** [comment]
I think you can always return `true`, but only call `this.options.addComment()` when modifier keys aren't pressed?

**Comment by andreasvirkus** [comment]
```
data() {
  return {
    editor: new Editor({
      extensions: [
        new (class extends Extension {
          keys() {
            return {
              'Shift-Enter'() {
                // TODO: Return true only if inside code block?
                console.info('quack')
                return true
              },
            }
          }
        })(),

**Comment by hemocy** [comment]
apprecitate very much!
