### ISSUE TITLE
Chars limit / chars count

### ISSUE THREAD

**Issue by NitzanShifrin** [ueberdosis/tiptap#629]
Is there any way to get the number of chars in the editor?
Not working well when adding elements (`<span> aaa </span>`) into it

**Comment by BrianHung** [comment]
Find the highest-most node, and get the length of its [textContent](https://prosemirror.net/docs/ref/#model.Node.textContent).

**Comment by Leecason** [comment]
https://github.com/Leecason/element-tiptap/blob/master/src/components/ElementTiptap.vue#L116

**Comment by andreasvirkus** [comment]
Is there an easy way to enforce a character limit for the editor?

**Comment by BrianHung** [comment]
Did you try this solution mentioned in that thread? https://github.com/scrumpy/tiptap/issues/293#issuecomment-578231063

What's being proposed there is to create a plugin which [handlesTextInput](https://prosemirror.net/docs/ref/#view.EditorProps.handleTextInput) and overrides the default behavior by returning true.

**Comment by andreasvirkus** [comment]
Thanks @BrianHung. Do you happen to know of a way to cut the pasted text to keep everything that fits within the character limit? Couldn't find anything related to ProseMirror on that subject

**Comment by BrianHung** [comment]
@andreasvirkus

On a paste event, use the length of text being pasted and the current document length to create a cutoff number. 

Then use that cutoff number to slice into the pasted text, followed by inserting the remaining text via a ProseMirror transaction.

**Comment by andreasvirkus** [comment]
@BrianHung Thanks! I still have a hard time figuring out how to cut the `slice` parameter to size, since it's filled with nested Nodes/fragments of its own. This is where I'm at so far:

```handlePaste(view, _event, slice) {
  if (view.state.doc.textContent.length + slice.size > editorMaxLength) {
    const sliceSize = slice.content.content
      .map((n) => n.content.size)
      .flat()
      .reduce((acc, a) => acc + a, 0)

    if (sliceSize > editorMaxLength) {
      slice.content = new DocumentFragment()
    }
  }
}
```

I propose that
a) a `contentLimit` prop or similar would be provided by tiptap
b) a guide on how to implement it, since it's quite cumbersome to figure out (the edge cases you mentioned don't need a solution, but could be mentioned in the guide as thinking points)

I'm willing to help write up the guide (if that's acceptable) once I have a solution to share

**Comment by philippkuehn** [comment]
I had once built such an extension. Maybe this helps you?

```js
import { Extension, Plugin } from 'tiptap'

export default class MaxSize extends Extension {

  get name() {
    return 'maxSize'
  }

  get defaultOptions() {
    return {
      maxSize: null,
    }
  }

  get plugins() {
    return [
      new Plugin({
        filterTransaction: transaction => {
          if (!transaction.docChanged || !this.options.maxSize) {
            return true
          }

          const size = transaction.doc && transaction.doc.textContent.length
          const maxSizeReached = size > this.options.maxSize
          return !maxSizeReached
        }
      }),
    ]
  }

}
```

Use it: `new MaxSize({ maxSize: 140 })`

**Comment by andreasvirkus** [comment]
@philippkuehn thank you, currently your code errors out for me with
```
TypeError: Illegal constructor
    at MaxSize.get plugins [as plugins] (QCommentEditor.vue:101)
    at tiptap.esm.js:771
    at Array.filter (<anonymous>)
    at ExtensionManager.get (tiptap.esm.js:770)
    at Editor.createPlugins (tiptap.esm.js:1091)
    at Editor.init (tiptap.esm.js:1048)
    at new Editor (tiptap.esm.js:1026)
    at VueComponent.data (QCommentEditor.vue:173)
    at getData (vue.runtime.esm.js:4748)
    at initData (vue.runtime.esm.js:4705)
```

**Comment by simpsonphile** [comment]
same problem, any solutions?

**Comment by andreasvirkus** [comment]
@simpsonphile this is the way we've currently handled it

```
new Editor({
  editorProps: {
    handleTextInput(view) {
      if (view.state.doc.textContent.length >= editorMaxLength && view.state.selection.empty) {
        return true
      }
    },
    handlePaste(view, event, slice) {
      if (view.state.doc.textContent.length + slice.size > editorMaxLength) {
        slice.content = new DocumentFragment()
      }
    },
  }
})
```

The paste experience isn't the greatest (we don't handle the edge cases mentioned in https://github.com/ueberdosis/tiptap/issues/629#issuecomment-605609701), but it suffices for now

**Comment by simpsonphile** [comment]
Ok I think I have found a solution. It also support pasting

```javascript
import { Extension, Plugin } from 'tiptap'

export default class MaxSize extends Extension {
  get name () {
    return 'maxSize'
  }

  get defaultOptions () {
    return {
      maxSize: null
    }
  }

  get plugins () {
    return [
      new Plugin({
        appendTransaction: (transactions, oldState, newState) => {
          const max = this.options.maxSize
          const oldLength = oldState.doc.content.size
          const newLength = newState.doc.content.size

          if (newLength > max && newLength > oldLength) {
            let newTr = newState.tr
            newTr.insertText('', max + 1, newLength)

            return newTr
          }
        }
      })
    ]
  }
}
```

**Comment by hanspagel** [comment]
Thanks for sharing!

**Comment by denis3509** [comment]
Size limit (not text length) of root node. It counts not only text symbols, but supports cutting pasted content if it doesnt fits. 
 ```
import { Extension, Plugin, TextSelection } from 'tiptap';

export default class MaxSize extends Extension {
  get name() {
    return 'maxSize';
  }

  get defaultOptions() {
    return {
      maxSize: 200
    };
  }

  get plugins() {
    return [
      new Plugin({
        appendTransaction: (transactions, oldState, newState) => {


          let max = this.options.maxSize || this.defaultOptions.maxSize;
          max = max +2;
          const oldDocSize = oldState.doc.content.size;
          const newDocSize = newState.doc.content.size;

          const newResPos = newState.selection.$head;

          if (newDocSize > oldDocSize && newDocSize > max) {

            const overPaste = newDocSize - max;
            const newTextSelection = TextSelection.create(
              newState.doc,
              (newResPos.pos - overPaste) > 0
                ? newResPos.pos - overPaste
                : 0,
              newResPos.pos);
            let newTr = newState.tr;
            newTr.setSelection(newTextSelection);
            newTr.deleteSelection();
            return newTr;
          }

        }

      })
    ];
  }
 }
```

**Comment by hanspagel** [comment]
I’m closing this here for now. This issue is added to #819 and we’ll consider to add it to tiptap v2. Thanks everyone!

**Comment by hanspagel** [comment]
Just wanted let you know that we added a `CharacterCount` extension to tiptap 2. Thanks again for sharing! 🙌
