### ISSUE TITLE
getHTML() removes highlighted span tags when using with CodeBlockHighlight

### ISSUE THREAD

**Issue by christopher4lis** [ueberdosis/tiptap#630]
**Describe the bug**
Calling getHTML() on an editor that contains a highlighted codeblock will remove all span tags and classes that give that codeblock highlighted lines.

**Steps to Reproduce / Codesandbox Example**
1. Insert the following into a tip tap editor with codeblock highlighting:

```javascript
import { Editor, EditorContent, EditorMenuBar } from 'tiptap'
import javascript from 'highlight.js/lib/languages/javascript'
import css from 'highlight.js/lib/languages/css'
```

2. Call `getHTML()` on that editor

3. Retrieved HTML will only contain `<pre>` and `<code>` tags, not any of the span tags used for highlighting purposes:

![image](https://user-images.githubusercontent.com/7675752/76673192-1f5f2a00-6579-11ea-916a-c6a84ad9be70.png)

**Expected behavior**
`getHTML()` should return the inputted code being used in step one with the corresponding span tags and classes:

![image](https://user-images.githubusercontent.com/7675752/76673189-15d5c200-6579-11ea-9e8b-ddac45ad8b6f.png)

**Comment by hanspagel** [comment]
I’m not sure about that! With getHtml you want to have the structured content, and only that. The syntax highlighting is a question of the desired rendering.

Imagine you’d want to render text in your paragraphs in grey, you wouldn’t expect tiptap to store that color. You’d just apply the color and styling where it’s needed. Same applies to syntax highlighting. It’s important to store the content, but the same styling can be applied again and again without the need to store the spans.

**Comment by kbellpostman** [comment]
> **Describe the bug**
> Calling getHTML() on an editor that contains a highlighted codeblock will remove all span tags and classes that give that codeblock highlighted lines.
> 
> **Steps to Reproduce / Codesandbox Example**
> Steps to reproduce the behavior:
> 
> 1. Insert the following into a tip tap editor with codeblock highlighting:
> 
> ```js
> import { Editor, EditorContent, EditorMenuBar } from 'tiptap'
> import javascript from 'highlight.js/lib/languages/javascript'
> import css from 'highlight.js/lib/languages/css'
> ```
> 
> 1. Call `getHTML()` on that editor
> 2. Retrieved HTML will only contain `<pre>` and `<code>` tags, not any of the span tags used for highlighting purposes:
> 
> ![image](https://user-images.githubusercontent.com/7675752/76673192-1f5f2a00-6579-11ea-916a-c6a84ad9be70.png)
> 
> **Expected behavior**
> `getHTML()` should return the inputted code being used in step one with the corresponding span tags and classes:
> 
> ![image](https://user-images.githubusercontent.com/7675752/76673189-15d5c200-6579-11ea-9e8b-ddac45ad8b6f.png)

Chris, did you figure it out?

**Comment by rosnaib11** [comment]
+1. Can't find alternative.  So basically, we can just see the syntax highlights during editing and can't preserve its output. So what is the sense of this syntax highlighting.

**Comment by Benbinbin** [comment]
@christopher4lis @kbellpostman  @rosnaib11 you can use highlight.js [function `hljs.highlightAll()`](https://highlightjs.readthedocs.io/en/latest/api.html#highlightall) to get the `span` tags again

```js
<template>
  <div>
    <p>some code</p>
    <pre>
      <code>console.log('hello tiptap')</code>
    </pre>
 </div>
</template>

<script>
// import highlight.js
import hljs from 'highlight.js';
// import style 
import 'highlight.js/styles/googlecode.css'; 

export default {
  //...
  // run the highlightAll() when dom mounted or update
  updated() {
    hljs.highlightAll();
  },
  mounted() {
    hljs.highlightAll();
  }, 
}
</script>
```

**Comment by BroJenuel** [comment]
It would be awesome if this is an option to, preseved the highlighted code,, So that when rendering the content we dont have to call the hljs highlight function instead, we can just use css only.

**Comment by daiwanxing** [comment]
Does anyone has good solution in 2025? My blog used the tiptap editor, and I want to synchronize the technical articles on my blog to wechat, but `getHTML()` can't get me the highlighted span tags, so I lose my span style when published to wechat. that's awful.
