### ISSUE TITLE
Additional extensions, also as examples on how to extend even further

### ISSUE THREAD

**Issue by onyx-blackbird** [ueberdosis/tiptap#634]
**Is your feature request related to a problem? Please describe.**
Some basic features of an RTE are missing and you have to implement them yourself. Some seem easy but need good understanding of the ProseMirror API and some additional examples would help to create more complex cases which are then really something very use case specific.

**Describe the solution you'd like**
One feature I'm trying to implement and struggling with the API is text-align for paragraphs. 
I would put the cursor somewhere within a paragraph and then select its alignment.

**Additional context**
![rte](https://user-images.githubusercontent.com/44765479/76862151-ed421680-685d-11ea-9dac-1ac6c96abdd5.png)

If someone can provide a way to do this even if it doesn't make it into the default extensions, I'd appreciate it.

**Comment by onyx-blackbird** [comment]
After almost a day of try and error and looking at some ProseMirror JavaScript code, I found a working solution (mostly struggling with `content` and `group`). This is just the right alignment one, but center and justify are almost the same, and maybe it would be possible to have it generic in one, but as I said, I am new to this API:

```
import { Node } from 'tiptap';
import { toggleBlockType } from 'tiptap-commands';

export default class AlignRight extends Node {

	get name(): string {
		return 'align_right';
	}

	get schema() {
		return {
			content: 'inline*',
			group: 'block',
			defining: true,
			draggable: false,
			parseDOM: [
				{
					tag: 'p',
					style: 'text-align=right',
				},
			],
			toDOM: () => ['p', {style: 'text-align: right;'}, 0],
		}
	}

	public commands({ type, schema }: any) {
		return () => toggleBlockType(type, schema.nodes.paragraph);
	}

}
```

**Comment by Leecason** [comment]
you can see this pr https://github.com/scrumpy/tiptap/pull/544 and the comment https://github.com/scrumpy/tiptap/pull/544#issuecomment-570061550

**Comment by hanspagel** [comment]
Thanks @onyx-blackbird! We’ve added a `TextAlign` extension to the upcoming [tiptap v2](https://blog.ueber.io/post/our-plan-for-tiptap-2/). And there will be a huuuge documentation for v2 with a lot of examples. 👍  I’m closing this here already.
