### ISSUE TITLE
Dump schema on server side?

### ISSUE THREAD

**Issue by brechtm** [ueberdosis/tiptap#640]
Is it possible to somehow dump the schema using a server-side script? Instantiating Editor requires the `document` global to be available, so this is not possible on Node (though it might be possible to work around this using jsdom).

Next, I tried to create an ExtensionManager instance instead of a full Editor, but it is not being exported by tiptap.

**Comment by brechtm** [comment]
For reference, this is how I handled it for now:

```
import fs from 'fs'
import { JSDOM } from 'jsdom'
import { createEditor } from './editor/editor.js'

const { window } = new JSDOM('')
global.window = window
global.document = window.document

let editor = createEditor({type: 'doc'}, [])

fs.writeFile('nodes.json', JSON.stringify(editor.extensions.nodes), (err) => {
  if (err) throw err;
  console.log('Saved!');
}); 

fs.writeFile('marks.json', JSON.stringify(editor.extensions.marks), (err) => {
  if (err) throw err;
  console.log('Saved!');
}); 

```

**Comment by philippkuehn** [comment]
you are right. that would be great!

btw there is `editor.getSchemaJSON()`

**Comment by hanspagel** [comment]
Thanks for the suggestion! We added an utility to v2 to do exactly that. 🙌
