### ISSUE TITLE
Shortcode generator

### ISSUE THREAD

**Issue by pmanikas** [ueberdosis/tiptap#641]
I'm trying to build a custom extension that, like the way Link extension does, gives you the ability to add shortcode on a specific text portion. The inspiration is the wordpress shortcode that looks like:
**[shortcodename id="ID"] Some Text [/shortcodename]**

Currently I've stuck to the parseDOM which looks like it gives you the ability to select a specific dom tag but I can't find a way to select something from the DOM based on String. Eg with regEx.

```
parseDOM: [
    {
        tag: "shortCode",
        getAttrs: dom => ({
            src: dom.getAttribute("id")
        })
    }
],
```

What I actually need, is a way to parse DOM with regex or, worst case scenario, find a way to temporarily convert before parsing:

**[shortcodename id="ID"] Some Text [/shortcodename]** 

to

**`<shortcodename id="ID"> Some Text </shortcodename>`**

and after parsing convert it to its initial state again.

If anyone knows or can think of any workaround, it would be appreciated. Let me know if I've missed something.
Would be more than happy to contribute the extension and share the final working results here.

**Comment by BrianHung** [comment]
> Currently I've stuck to the parseDOM which looks like it gives you the ability to select a specific dom tag but I can't find a way to select something from the DOM based on String. Eg with regEx.

To debug and see what methods are available with dom, I would suggest logging it
```js
parseDOM: [
    {
        tag: "shortCode",
        getAttrs: dom => {
           console.log(dom);
           return {id: dom.getAttribute("id")}
        },
    }
],
```

**Comment by hanspagel** [comment]
Thanks @BrianHung for helping here!
