### ISSUE TITLE
Question: How to create styling options such as color, font-size, etc.

### ISSUE THREAD

**Issue by joelpro2** [ueberdosis/tiptap#642]
I've been digging in documentation, but theres a lot of thing missing there.

I need to enable styling options in the editor. I found somewhere, an exemple for font-size, but i'm still missing some control.

What is the best way to manipulate tags css? And if theres already exemples for stylings, where can i found them?

**Comment by BrianHung** [comment]
If you want inline-styling, I'd recommend creating a custom [mark ](https://prosemirror.net/docs/ref/#model.Mark) to handle font-size, color, etc. A good example of this is the [czi-prosemirror library](https://github.com/chanzuckerberg/czi-prosemirror) which has a demo of that. I would also look at how marks are implemented in tiptap-extensions.
