### ISSUE TITLE
Limit character count and disable styling in title block

### ISSUE THREAD

**Issue by deathg0d** [ueberdosis/tiptap#644]
Issue type: support (unable to find information in the documentation)
I am using the title node as shown in the example here: [title example](https://tiptap.scrumpy.io/title) + the bubble menu. I am trying to customize it but I came across a couple of issues:

1. I am unable to make the title **text only** (disabling format options like bold, italic and so on). Couldn't find much in the documentations. I did manage to disable the bubble menu when title is selected by using ```<div class="menububble" :class="{ 'is-active': menu.isActive && !isActive.title() }" :style="`left: ${menu.left}px; bottom: ${menu.bottom}px;`">```. It seems to be partially working, however if I press 'ctrl + a' to select all text, the bubble menu shows up again. Plus I still can set the styles using shortcuts ('ctrl+b' for example).

2. Cannot seem to limit character count in only the title field. Can do it for the whole document but having separate option for the title node could be useful.

These are not bugs but missing information in the documentation I believe? Any direction is much appreciated.

**Comment by BrianHung** [comment]
1. You can disable marks on nodes by setting [marks: ""](https://prosemirror.net/docs/ref/#model.NodeSpec.marks) in the schema.

2. To character limit the title node, I would watch the textContent and dispatch a transaction which only keeps text below a set limit using [setNodeMarkup](https://prosemirror.net/docs/ref/#transform.Transform.setNodeMarkup).

```js
  get view() {
    return {
      name: "title-heading",
      props: ["node", "view", "getPos"],
      template: `<h1 class="title" ref="content"></h1>`,
      watch: {
        "node.textContent": async function(text) {
           if (node.textContent.length > limit)
              this.view.dispatch(this.view.state.tr.setNodeMarkup(this.getPos(), ...)) // You would slice here
        }
      },
    };
  }
```
