### ISSUE TITLE
Wrap Images in div with class

### ISSUE THREAD

**Issue by pmaxwellward** [ueberdosis/tiptap#645]
I want to wrap uploaded images in a div that is assigned custom class so I can have more control over styling. I have looked at [this](https://github.com/scrumpy/tiptap/issues/96#issuecomment-441203743), but the solution isn't quite there. I have looked throug the Prose Mirror forums without much luck too. Thanks.

**Comment by neelay92** [comment]
I think you can use [this](https://github.com/scrumpy/tiptap/issues/573). 
You'll have to create a Schema for the wrapper div and if you want to add classes, do it in 
`toDOM: node => ["div", {class: 'image-wrapper'}, 0],`
