### ISSUE TITLE
injectCSS option cause <style> tag to be injected every time editor is initialized

### ISSUE THREAD

**Issue by xelblch** [ueberdosis/tiptap#647]
Every time tiptap editor is loaded, it will call `injectCSS` because `options.injectCSS` default is `true`. This leads to situation, when you have tons of `<style>` tags inside your page `<head>`. Pretty sure that it should happen only once.

You can see such behavior on demo page: https://tiptap.scrumpy.io/

![bug](https://user-images.githubusercontent.com/584349/77918710-ec20d880-72a4-11ea-98a2-ff95b510644f.gif)

**Comment by hanspagel** [comment]
Thanks for reporting! We fixed this for version 2, which will still take a while to be released though.
