### ISSUE TITLE
Disable and hide menu buttons

### ISSUE THREAD

**Issue by brechtm** [ueberdosis/tiptap#649]
I don't think the EditorMenuBar supports disabling or hiding menu items, does it? I'm in the process of porting a project from ProseMirror to tiptap and I haven't been able to figure out how to do this.

When you look at the basic example at https://prosemirror.net/, you'll see that the mark buttons are disabled when the cursor is inside a code block. Also, the list buttons are only shown when the cursor is in a paragraph.

Is this functionality provided by tiptap? If not, what would be the best way to implement it?

**Comment by BrianHung** [comment]
Yes, there's a good example of hiding the menu bar when the editor's not focused [here](https://tiptap.scrumpy.io/hiding-menu-bar). If you look at the [plugin source code](https://github.com/scrumpy/tiptap/blob/master/packages/tiptap/src/Components/EditorMenuBar.js), you can see that this is implemented by having a `focused` prop. You could probably modify that plugin with additional props that do what you want using ProseMirror API, e.g. check if the cursor is within a codeblock or within a paragraph. The way I would approach marks within codeblock would be to check which marks are allowed via [allowsMarkType](https://prosemirror.net/docs/ref/#model.NodeType.allowsMarkType).

**Comment by brechtm** [comment]
Thanks @BrianHung. I've implemented active/disabled status for the menu buttons by creating a custom MenuBarButton component and "connecting" the _v-btn_'s _disabled_ and _classes_ props to computed values. However, these values are computed on every character input. With 10+ menu bar buttons, this noticably slows down text entry.

I'm not very experienced with Vue (or even web development in general), so I'm not sure how to fix this. Any suggestions are appreciated! I'll update this ticket if I manage to find a proper solution.

**Comment by brechtm** [comment]
I've transitioned my app to use Vuex for managing state. My Vuex store object is now providing getters that provide the list of (names of) the active marks and the current node (under the cursor). These are only updated twice (instead of once, for an unknown reason) on each character entry. The menu buttons use these getters these to determine their active/disabled status.

This helps reduce the slowdown, however not as much as I hoped. Note that I have 20 menu buttons (corresponding to inline and body elements in the schema).

**Comment by brechtm** [comment]
I should mention that the slowdown is most really only significant on Firefox when I disable Turbo Boost on my 4770HQ i7 (MacOS). Chrome and Safari seem to handle this better. Still, an editor should run smoothly, even on slower hardware.

**Comment by hanspagel** [comment]
Thanks! There will be an API to test commands without actually executing them in [tiptap v2](https://blog.ueber.io/post/our-plan-for-tiptap-2/). :)

`editor.can().toggleBold()` => true/false
