### ISSUE TITLE
Text Anchor Extension For Jump Marks

### ISSUE THREAD

**Issue by ramimassoud** [ueberdosis/tiptap#662]
**Is your feature request related to a problem? Please describe.**
I would love to be able to select text or a heading and mark it with an anchor that can be linked to. 

**Describe the solution you'd like**
It would be great to have an extension/mark similar to [Link](https://github.com/scrumpy/tiptap/blob/master/packages/tiptap-extensions/src/marks/Link.js) that would allow selected text to have a specified `id` so it can be [directly linked to](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Linking_to_an_element_on_the_same_page).

**Describe alternatives you've considered**
N/A

**Additional context**
This might have some crossover with #621, but I'm not 100% sure

**Comment by jmartsch** [comment]
This is desperately needed

**Comment by hanspagel** [comment]
I think you can add the code from #621 ad a custom extension (instead of the default heading extension) and then add links to the ids (href="#6372727").

You would probably want to loop through the JSON (editor.getJSON()) to get a list of existing IDs in your document.

Hope that helps!

**Comment by wiwat-p** [comment]
Are we have example

**Comment by mackmm145** [comment]
here's a quick and dirty jump anchor extension that creates a span with an id in case anyone runs into a similar situation.

https://gist.github.com/mackmm145/f100a62de841464872785e3d041be13f

**Comment by Henxed** [comment]
> mackmm145 https://gist.github.com/mackmm145/f100a62de841464872785e3d041be13f

New version https://gist.github.com/Henxed/e04593b854397347557622d4669d316e
For those who are reading and want to implement it.

I implemented a makeshift solution. Add this to your JavaScript plugin.
```js
unsetJumpAnchor: () => ({ chain }) => {
    const regex = /<span data-type="jump-anchor" id="[^"]+">([^<]+)<\/span>/g;
    const content = this.editor.getHTML();
    const newContent = content.replace(regex, '$1');

    return chain().setContent(newContent).run();
}
```
Here's the function that is called from the menu on click.
```js
import { jumpAnchor } from '../Anchor';


/*-- ... --*/


new Editor({
    extensions: [
      // ...
      jumpAnchor,
      // ...
    ],
    // ...
  });


/*-- ... --*/


setAnchor() {
            const previousAnchor = this.editor.commands.getJumpAnchor();
            const anchor = window.prompt('Enter the anchor name...', previousAnchor);

            if (anchor === '') {
                this.editor
                .chain()
                .focus()
                .extendMarkRange('jumpAnchor')
                .unsetJumpAnchor()
                .run();

                return;
            }

            if (anchor) {
                this.editor
                .chain()
                .focus()
                .extendMarkRange('jumpAnchor')
                .setJumpAnchor({ id: anchor })
                .run();
            }
 }
```
