### ISSUE TITLE
Add css class attribute to Image node

### ISSUE THREAD

**Issue by Coolkop** [ueberdosis/tiptap#663]
When insert image it will be great to have also class attribute
```
this.editor.commands.image({
  src: image.attr('src'),
  alt: image.attr('alt'),
  class: image.attr('class'),
});
```

Maybe it could be common property for all nodes which merged with custom attributes?

**Comment by frangte** [comment]
Try this.

```
```

**Comment by woodinteractive** [comment]
@frangte Can you expound on your suggestion or give a code example?

**Comment by frangte** [comment]
Docs of prosemirror. [here](https://prosemirror.net/docs/ref/#model.NodeSpec.toDOM)
```
toDOM: ?⁠fn(node: Node) → DOMOutputSpec
Defines the default way a node of this type should be serialized to DOM/HTML (as used by DOMSerializer.fromSchema). Should return a DOM node or an array structure that describes one, with an optional number zero (“hole”) in it to indicate where the node's content should be inserted.

For text nodes, the default is to create a text DOM node. Though it is possible to create a serializer where text is rendered differently, this is not supported inside the editor, so you shouldn't override that in your text node spec.
```
My example code just do before prosemirror render image node i inject attribute `class` to this node with value `image-wrapper`, and you need to style `image-wrapper` class in you css (scss).

**Comment by woodinteractive** [comment]
@frangte I'm still a little unclean. Are you injecting this from your Vue application using the editor object or are you modifying the core code?

**Comment by frangte** [comment]
@woodinteractive  modifying the core code

**Comment by hanspagel** [comment]
This will get reeaally easy with tiptap v2. 🙃 So I’m closing this here for now.
