### ISSUE TITLE
How to add Vue component through editor menu bar

### ISSUE THREAD

**Issue by JCqiu** [ueberdosis/tiptap#667]
**Is your feature request related to a problem? Please describe.**
https://tiptap.scrumpy.io/embeds
How to add Vue component through editor menu bar
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by BrianHung** [comment]
If you look at how the editor menu is [implemented](https://github.com/scrumpy/tiptap/blob/master/examples/Components/Routes/MenuBubble/index.vue), you can see that it calls `editor.commands.node`. So to add [embeds](https://github.com/scrumpy/tiptap/blob/master/examples/Components/Routes/Embeds/Iframe.js) to the editor menu, you would have to a `commands` function within the node.

**Comment by JCqiu** [comment]
@BrianHung thank you ,But I refer to https://github.com/scrumpy/tiptap/issues/613
![image](https://user-images.githubusercontent.com/16211027/79405590-76687c80-7fc7-11ea-88e7-9e8af4f1dc02.png)
![image](https://user-images.githubusercontent.com/16211027/79405614-82ecd500-7fc7-11ea-9d4f-9e4c10b60217.png)
![image](https://user-images.githubusercontent.com/16211027/79405628-884a1f80-7fc7-11ea-8bc0-28ffa4829085.png)
I added a picture by clicking the event, but it had no effect, nor could I debug the breakpoint, nor could I print the output from the console

**Comment by BrianHung** [comment]
@JCqiu. I'm not sure how 613 is related. Because `NewImage` is a Node, you shouldn't be using `updateMark` in its commands function. Instead, you want to insert a Node at the current selection. An example of how to do this is:
```js
  commands({ type }) {
    return attrs => (state, dispatch) => {
      const { selection } = state
      const position = selection.$cursor ? selection.$cursor.pos : selection.$to.pos
      const node = type.create(attrs)
      const transaction = state.tr.insert(position, node)
      dispatch(transaction)
    }
  }
```

**Comment by JCqiu** [comment]
@BrianHung thank you,I added components by referring to the example of 613, I want to add the LocalImg component,
ex:613
![image](https://user-images.githubusercontent.com/16211027/79406466-c3e5e900-7fc9-11ea-8bdf-5056aa568e13.png)
![image](https://user-images.githubusercontent.com/16211027/79406513-e8da5c00-7fc9-11ea-9a50-005225d23d7b.png)

**Comment by BrianHung** [comment]
@JCqiu I notice you're trying to make an image node. Why not use the [image node](https://github.com/scrumpy/tiptap/blob/master/packages/tiptap-extensions/src/nodes/Image.js) featured on the [tiptap website](https://tiptap.scrumpy.io/images). There's an [example code](https://github.com/scrumpy/tiptap/blob/master/examples/Components/Routes/Images/index.vue) of how to integrate that into the editor menu as well.

**Comment by JCqiu** [comment]
@BrianHung thank you,But I want to add another <br> node to the <image> node
![image](https://user-images.githubusercontent.com/16211027/79410473-18419680-7fd3-11ea-8b32-4bea3ffc8c3d.png)

**Comment by BrianHung** [comment]
@JCqiu Still try to use the image node to base your implementation of `LocalImg` off of, instead of 613 because you want a [Node](https://prosemirror.net/docs/ref/#model.Node) not a [Mark](https://prosemirror.net/docs/ref/#model.Mark). I would try copying the tiptap image node, and adding the `get view() { return LocalImg; }`. Best of luck!

**Comment by hanspagel** [comment]
Thanks for helping here @BrianHung! I’m closing this for now.
