### ISSUE TITLE
How to add content in the schema like paragraph and heading

### ISSUE THREAD

**Issue by deepaksisodiya** [ueberdosis/tiptap#669]
For my custom nodes, I want to have schema like below

any way to get this type of JSON out from custom blocks/nodes

```
{
      "type": "embeds",
      "attrs": {
          widht: 200,
          height: 200,
       },
      "content": [
        {
          "type": "html",
          "html": "<div>something</div>"
        }
      ]
    }
```

**Comment by deepaksisodiya** [comment]
@philippkuehn

**Comment by hanspagel** [comment]
Sorry for the silence here! That’s not so easy. You can only control what’s in `attrs`.  So there’s no way to add the `html` key on the same level as `type` as far as I know.

I’m closing this here for now. ✌️
