### ISSUE TITLE
Support for different types of ListItem

### ISSUE THREAD

**Issue by chapuzzo** [ueberdosis/tiptap#671]
I've been looking through all of the documentation but couldn't find anything related to `li` types.
Currently the only supported types are the default ones, I see these are the available ones: 

for ol:
- 1: It is the default value. It is used to specify the numerical ordered list.
- a: It arranged the list items in lower case letters.
- A: It arrange the list items in the form of upper case.
- i: It arrange the list items in the roman numbers in the form of lower case letters.
- I: It arranged the list in roman numerals in the form of uppercase letters.

for ul:
- disc: It is the default value. It creates a filled circle.
- circle: It creates an unfilled circle.
- square: It creates an filled square.

Is there any option to change them or a plan for this to be enabled?

**Comment by philippkuehn** [comment]
I don't understand. Isn't that just CSS?

**Comment by chapuzzo** [comment]
Yes and no. They can be set by CSS but they are also a deprecated attribute https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li 😞 
How could they have custom CSS just like the heading (1,2,3) examples?
