### ISSUE TITLE
插入一张图片后 拼音输入汉字有bug

### ISSUE THREAD

**Issue by desonyuan** [ueberdosis/tiptap#674]
比如我输入 '你好' 编辑器会出现 'n你好' 第一个拼音字母会出现在编辑框,反复测试确认是bug

**Comment by philippkuehn** [comment]
english please!

**Comment by wkcole** [comment]
@desonyuan This is probably your problem, I cannot reproduce in https://tiptap.scrumpy.io/images, this issue should have nothing to do with tiptap
