### ISSUE TITLE
paste rule implementation in italic/font-size/font-color

### ISSUE THREAD

**Issue by DebaPrasad14** [ueberdosis/tiptap#680]
I am facing problem while implementing paste rule for font-color, italic texts. My use case if I paste some texts which are italic or have some font-color then in tiptap, it is not showing what they were before. But if I copy some bold texts from any other place and paste in tiptap editor then texts are showing in bold which is correct behavior.

For that, I'm trying to implement paste rule but not getting any success.
Any help is highly appreciated. :)

**Comment by philippkuehn** [comment]
pasterules are for converting text to nodes (`**text**` to `<strong>text<strong/>`).

pasting html (espacially bold) should work out of the box. can you provide a codesandbox or something?

**Comment by DebaPrasad14** [comment]
what I have done so far is -
import { Mark } from "tiptap";

export default class TextColor extends Mark {
  get name() {
    return "TextColor";
  }

  get defaultOptions() {
    return {
      color: ["#FF0000", "#000000", "#00FF00", "#C94C4C", "#0000FF", "#84B84C"]
    };
  }

  get schema() {
    return {
      attrs: {
        color: {
          default: "#000000"
        }
      },
      parseDOM: [
        {
          tag: "font"
        },
        {
          style: "color",
          getAttrs: value => ({
            color: value
          })
        }
      ],
      toDOM: mark => {
        return [
          "span",
          {
            style: `color:${mark.attrs.color}`
          },
          0
        ];
      }
    };
  }

  commands({ type }) {
    return attrs => updateMark(type, attrs);
  }
}

**Comment by hanspagel** [comment]
This looks good to me on a quick glance. If you still looking for a solution, would you mind to provide a CodeSandbox or at least an example.of the HTML you’re trying to paste?

BTW we described that in the upcoming v2 documentation
