### ISSUE TITLE
How do I not hide the Keyboard when I click the button? (like Tiptap Menubar Button)

### ISSUE THREAD

**Issue by akirarika** [ueberdosis/tiptap#681]
![Video_20200426_043115_586-min](https://user-images.githubusercontent.com/33272184/80302403-6aa56300-87dc-11ea-9a6d-6bb8895a21fb.gif)

I'm using `v-show` to implement a button that displays more buttons,

But, When I click this new button, the Keyboard will be hidden.

What's the way to not hide my Keyboard like Tiptap button?

(Android 9, Webview 80)

**Comment by akirarika** [comment]
That's because Tiptap lost focus, I solved it:

```html
<button @mousedown="clickMe">
  <i class="ri-more-line"></i>
</button>
```

```javascript
methods: {
  clickMe(e) {
    e.preventDefault();
  }
}
```

**Comment by WeMadeCode** [comment]
<button
        style={{ position: 'fixed', height: 44, width: 44, backgroundColor: 'red', bottom: 0, right: 10 }}
        onClick={(e) => {
          e.preventDefault();
          e.stopPropagation();
        }}
 ></button>

In a React project, this approach doesn't work
