### ISSUE TITLE
Mentions - using a different html tag/template

### ISSUE THREAD

**Issue by EternalBlack** [ueberdosis/tiptap#683]
I pretty much used the suggestions template provided here:
https://github.com/scrumpy/tiptap/blob/master/examples/Components/Routes/Suggestions/index.vue

I'm wondering though on how use something different than a span. I'd rather have a a for this pointing the users page.

**Comment by BrianHung** [comment]
The [`Matcher`](https://github.com/scrumpy/tiptap/blob/master/packages/tiptap-extensions/src/nodes/Mention.js) node is a good starting place. Notice how it replaces the matched content with a matcher node on this line
https://github.com/scrumpy/tiptap/blob/92eb2c61ccf2780c51212724fd879ba343436bd3/packages/tiptap-extensions/src/nodes/Mention.js#L61

If you want to replace the matched content with an anchor tag or a link, you would use something like [`setNodeMarkup`](https://prosemirror.net/docs/ref/#transform.Transform.setNodeMarkup) to create a text node with a link mark.

**Comment by tobischulz** [comment]
A quick way would be to get all span elements inside the content that has the data-mention-id attribute and add click listeners manually to redirect to the users profile. 

Not on editing the content but on showing it (after save).

This works pretty good and is a fast solution for this problem. But the setNodeMarkup, that @BrianHung mentioned, would work maybe cleaner, if you would like to have links in your html.
