### ISSUE TITLE
removing matcher text after insterting custom node

### ISSUE THREAD

**Issue by djixadin** [ueberdosis/tiptap#684]
**Is your feature request related to a problem? Please describe.**
is it possible to remove matcher content after inserting custom node?

```
get defaultOptions() {
        return {
            matcher: {
                char: ':',
                allowSpaces: false,
                startOfLine: false
            }
        };
    }
```

lets say i want to remove matcher char and everything after like for example :**

**Comment by BrianHung** [comment]
Use [`replaceRangeWith`](https://prosemirror.net/docs/ref/#transform.Transform.replaceRangeWith) to remove the matcher content and insert the custom node.

**Comment by djixadin** [comment]
how do i use that function? thats not a tiptap export.

**Comment by JavierMartinz** [comment]
@djixadin https://github.com/ueberdosis/tiptap/discussions/1259
