### ISSUE TITLE
PasteRule does not work for nodes

### ISSUE THREAD

**Issue by kfirba** [ueberdosis/tiptap#689]
**Describe the bug**
When attempting to add a `pasteRule` for a `Node`, it does not work as the `pasteRule` helper function have a call to a `Mark` node (note how we call `addToSet` on the created node, which may not be a mark but a node):

```js
nodes.push(child.cut(start, end).mark(type.create(attrs).addToSet(child.marks)));
```

**Steps to Reproduce / Codesandbox Example**
1. Add a paste rule to any node such as a media embed
```js
pasteRules({type}) {
  return [pasteRule(/SOME_YOUTUBE_REGEX/g, type, (url) => ({src: url}))]
}
```
2. try to paste a heading: `https://www.youtube.com/watch?v=H08tGjXNHO4`
3. See error in console: `Uncaught TypeError: type.create(...).addToSet is not a function`

**Expected behavior**
a new MediaEmbed node should be created with the given `attrs`

**Comment by kfirba** [comment]
@philippkuehn I've created a simple helper function to solve that:

```js
export function nodePasteRule(regexp, type, getAttrs) {
  const handler = fragment => {
    const nodes = [];

    fragment.forEach(child => {
      if (child.isText) {
        const {text} = child;
        let pos = 0;
        let match;

        // eslint-disable-next-line
        while ((match = regexp.exec(text)) !== null) {
          if (match[1]) {
            const start = match.index;
            const end = start + match[0].length;
            const textStart = start + match[0].indexOf(match[1]);
            const textEnd = textStart + match[1].length;
            const attrs = getAttrs instanceof Function ? getAttrs(match) : getAttrs;

            // adding text before markdown to nodes
            if (start > 0) {
              nodes.push(child.cut(pos, start));
            }

            // create the node
            nodes.push(type.create(attrs));

            pos = end;
          }
        }

        // adding rest of text to nodes
        if (pos < text.length) {
          nodes.push(child.cut(pos));
        }
      } else {
        nodes.push(child.copy(handler(child.content)));
      }
    });

    return Fragment.fromArray(nodes);
  };

  return new Plugin({
    props: {
      transformPasted: slice => new Slice(handler(slice.content), slice.openStart, slice.openEnd),
    },
  });
}
```

Basically it is exactly the same as the `markPasteRule` but it just creates the node with the given attribute instead of trying to add a mark.

I guess that if you want you could extract the common logic between those 2 methods and just pass a handler to create the node/mark.

What do you think?

**Comment by Alecyrus** [comment]
@kfirba Nice shot！

**Comment by Alecyrus** [comment]
Is it possible  to show some examples about nodePasteRule ?

**Comment by kfirba** [comment]
@Alecyrus The same as the regular `markPasteRule`:

```js
pasteRules({type}) {
    return [
      nodePasteRule(
        SOME_REGEX_TO_MATCH_THE_NODE,
        type,
        match => {
          // return some attrs, if any.
        },
      ),
    ];
  }
```

**Comment by Alecyrus** [comment]
@kfirba  Hi dude, I need some help.

I want to supper paste `Heading` node by matching string like `# asdasda \n## asdasd`. and some errors occurs. If I use the following code, there will be endless output.
```javascript
while ((match = regexp.exec(text)) !== null) {
          if (match[0]) {
            const start = match.index;
            const end = start + match[0].length;
            // match[1].length is for parsing the level of Heading node
            const attrs = getAttrs instanceof Function ? getAttrs(match, match[1].length) : getAttrs;

            // adding text before markdown to nodes
            if (start > 0) {
              nodes.push(child.cut(pos, start));
            }

            // create the node
            nodes.push(type.create(attrs));

            pos = end;
          }
        }
```

If I change `while` to `if`, it seems to work, but the nodes inserted into document are not as i expect. the nodes(Fragment) returned by `handler`  are wrapped by a `Paragraph` Node. 
```javascript
 //... Heading.js
 pasteRules({ type }) {
    return [
      nodePasteRule(new RegExp(`^(#{1,3})(.*)`), type, (match, level) => ({
        level,
      }))]
  }

```




```javascript
 //... nodePasteRule.js
import { Plugin } from 'prosemirror-state'
import { Slice, Fragment } from 'prosemirror-model'
export function nodePasteRule(regexp, type, getAttrs) {
    const handler = fragment => {
        const nodes = [];

        fragment.forEach(child => {
            if (child.isText) {
                const { text } = child;
                let pos = 0;
                let match;

                console.log("text", text)
                console.log("regexp", regexp)
                console.log("res", regexp.exec(text))

                // eslint-disable-next-line
                while ((match = regexp.exec(text)) !== null) {

                    console.log(match[0])
                    if (match[0]) {
                        const start = match.index;
                        const end = start + match[0].length;
                        const attrs = getAttrs instanceof Function ? getAttrs(match[0], match[1].length) : getAttrs;

                        // adding text before markdown to nodes
                        if (start > 0) {
                            nodes.push(child.cut(pos, start));
                        }

                        console.log(type)

                        // create the node
                        nodes.push(type.create(attrs));

                        pos = end;
                    }
                }

                // adding rest of text to nodes
                if (pos < text.length) {
                    nodes.push(child.cut(pos));
                }
            } else {
                nodes.push(child.copy(handler(child.content)));
            }
        });
        console.log(nodes)
        return Fragment.fromArray(nodes);
    };

    return new Plugin({
        props: {
            transformPasted: slice => new Slice(handler(slice.content), slice.openStart, slice.openEnd),
        },
    });
}
```

**Comment by kfirba** [comment]
@Alecyrus I think you get an endless loop as you didn't provide the `g` flag for your regex. Try replacing your regex to this:

```js
new RegExp(`^(#{1,3})(.*)`, 'g')
```

Can you show some input => output example? 

Also, if you could provide a reproduction it would be best.

**Comment by Alecyrus** [comment]
@kfirba The first problem is solved, but the second problem is .... uh.. I don't know how to describe.  If possible, could you please show me how to implement the following feature:
### Copy from other editor
content:
```
# Heading 1
## Heading 2
```
Then pasting these text in our own editor, which could render two nodes (Heading Node with level 1 and 2):

>  # Heading1
> ## Heading2

**Comment by Alecyrus** [comment]
I notice the following code
```
// adding text before markdown to nodes
                        if (start > 0) {
                            nodes.push(child.cut(pos, start));
                        }
```

In my case, the output is:
<img width="754" alt="截屏2020-05-06 10 02 44" src="https://user-images.githubusercontent.com/13865581/81132360-bdbbaa80-8f80-11ea-92ac-0f0d082b34be.png">

The value of start is 0.  And this rule seems not handle something line-wrapped markdown or tight lists.

**Comment by Alecyrus** [comment]
@kfirba I am considering another solution by using `handlePaste` . The markdown text (mainly block types) in clipboard could be transformed to` HTML` content with style, which could be handled by current editor （ParseRule）

**Comment by kfirba** [comment]
@Alecyrus Hey.

I tried solving this but I just don't know how to create a node and append a text node to it. I got close, but could not find how to glue the last part.

The code I used: (I've slightly modified the regex and extracted the correct heading level)

```js
 nodePasteRule(
        /^#{1,3} ?(.*)/g,
        type,
        match => {
          let level = 0;

          for (let i = 0; i < match[0].length; i++) {
            if (match[0][i] !== '#') break;
            level++;
          }

          return {level}
        },
      )
```

As for the `nodePasteRule` code, I've modified it a bit to get close. I create the node type (`type.create(attrs)`) and then create a text node containing the text:

```js
// ...
const node = type.create(attrs);
const textNode = child.cut(start, end);
// How do I set the `textNode` as the `node` content? No idea :/
// ...
```

I just don't know how to glue the last piece of the puzzle. If you know how to do it it would be great if you share it with me :)

Maybe you can open a thread in ProseMirror forums? The maintainer is very quick to answer!

**Comment by Alecyrus** [comment]
There is already a thread about supporting markdown paste, [Support pasting markdown](https://discuss.prosemirror.net/t/support-pasting-markdown/699).

**Comment by Alecyrus** [comment]
And I have another idea about this feature.  You know, when you select heading texts ( <h1>, etc) in a blog post or something like that, and then paste these texts into an editor(tiptap, precisely Prosemirror), you will see,  a Heading node is inserted. 

So I am wondering... how about transforming  text  to special text with styles, not just pasting plain text. And the prosemirror can handle these styled text. The work we need to do  is  implementing the transformation algorithm. 

I don't know whether it could do work, but I will give a try later.

**Comment by kfirba** [comment]
@Alecyrus It seems a bit like overkill, in my opinion. There HAS to be a way to create a node with a text node in it. Had it been a transaction you could run `insertText` on the transaction. I wonder how it can be achieved during paste?

**Comment by kfirba** [comment]
@Alecyrus Got it working?

**Comment by Alecyrus** [comment]
I am a little busy these days, but I will figure it out.

**Comment by Alecyrus** [comment]
@kfirba It does works.

**Comment by Alecyrus** [comment]
Check ![this thread](https://discuss.prosemirror.net/t/clipboardtextparser-text-context/970), I am sure that you will find a solution when you open that thread.

**Comment by QuadDepo** [comment]
Facing the same issue currently, did you ever got it to work @kfirba ?

**Comment by jamilabreu** [comment]
@hanspagel any direction on where to look if one wants to implement embeds on paste? thanks!

**Comment by jeissler** [comment]
I’m also facing issue w/ implementing a nodePasteRule and wondered if anyone has gotten something similar to @kfirba solution working w/ TipTap 2 and the addPasteRules method? So far I've tried altering the code shown to accept a config object rather than just arguments to be closer to the TipTap nodeInputRule, but I’m getting `Uncaught TypeError: find is not a function`.  Thanks for making TipTap and any further suggestions.

```
Uncaught TypeError: find is not a function
    at pasteRuleMatcherHandler (tiptap-core.esm.js:2452:1)
    at tiptap-core.esm.js:2485:1
    at Fragment.nodesBetween (index.es.js:80:1)
    at Node.nodesBetween (index.es.js:1071:1)
    at run (tiptap-core.esm.js:2478:1)
    at Plugin.appendTransaction (tiptap-core.esm.js:2571:1)
    at EditorState.applyTransaction (index.es.js:842:1)
    at EditorState.apply (index.es.js:807:1)
    at Editor.dispatchTransaction (tiptap-core.esm.js:3448:1)
    at EditorView.dispatch (index.es.js:5247:29)
```

**Comment by bdbch** [comment]
@jamilabreu I added this behaviour in the `extension-youtube` package - [see here](https://github.com/ueberdosis/tiptap/blob/main/packages/extension-youtube/src/youtube.ts#L93).

**Comment by bdbch** [comment]
We now also have a `nodePasteRule` that returns a new PasteRule handling the creation of a node via type including attributes you can paste via the `getAttributes` handler. That way you can create a youtube embed paste rule similar to how I did it in this example:

https://github.com/ueberdosis/tiptap/blob/main/packages/extension-youtube/src/youtube.ts#L93

**Comment by bdbch** [comment]
I'll close this issue as it's quite old and I think the solution I added as an example for adding embeds on paste should help you out.

If you don't think this is correct - feel free to reopen this issue and let me know! :) Thanks
