### ISSUE TITLE
'Select All' broken in Title Example

### ISSUE THREAD

**Issue by bynormous** [ueberdosis/tiptap#690]
**Describe the bug**

Go to https://tiptap.scrumpy.io/title and enter a title... then perform a 'Select All' using your keyboard and try typing a new title. Notice that it will only ever let you enter one character in the Title Node.

**Expected behavior**
I expect a 'Select All' + typing to move the cursor at the beginning at the Title Node and let me type in a new title

**Environment**
 - OS: Mac OS X Catalina
 - Browser: Chrome Version 81.0.4044.138

**Comment by hanspagel** [comment]
(Finally) fixed in the upcoming v2. 👍
