### ISSUE TITLE
Please offer 'isUnble' like 'isActive'

### ISSUE THREAD

**Issue by artiely** [ueberdosis/tiptap#692]
Could you please provide the 'isUnable' attribute to mark the current menu button as unavailable

**Comment by AbrahemAlhofe** [comment]
Man add ! sign after isActive like 
`
      // Horizontal Rule
        button.texteditor__command( :class="{ 'texteditor__command--is-not-active': !isActive.horizontal_rule() }" @click="commands.horizontal_rule" )
          span(v-html='icons.LineIcon')
`
