### ISSUE TITLE
Math Support

### ISSUE THREAD

**Issue by srikanth-k-github** [ueberdosis/tiptap#698]
Hi, do you have plans to include new Math feature support. It would be great and helpful to help type Math Equations or Chemical Formula for lesson preparation. In case you have already included kindly let me know where and how I can try. Thank you.

**Comment by thelehhman** [comment]
You can create a custom node which is rendered using Katex.

**Comment by AbidKhairyAK** [comment]
@thelehhman  would you mind to show us some example? :)

**Comment by samarsault** [comment]
Check https://github.com/ueberdosis/tiptap/issues/179#issuecomment-557838698
