### ISSUE TITLE
How to leaves code block in mobile?

### ISSUE THREAD

**Issue by wmf508** [ueberdosis/tiptap#701]
we can use cmd+enter to leaves code block in mac. but how about mobile? in addition, I want to use button click event to leave code block.

**Comment by ninest** [comment]
One possible solution is to leave a [trailing paragraph](https://tiptap.scrumpy.io/trailing-paragraph) so users can tap below the code block to leave it

**Comment by hanspagel** [comment]
Thanks for sharing! Closing this here for now.
