### ISSUE TITLE
USE TIPTAP via a direct script include

### ISSUE THREAD

**Issue by hatemjaafar** [ueberdosis/tiptap#704]
Hello,
how to use tiptap via direct include script?

thanks

**Comment by Alecyrus** [comment]
。。。。[jsdelivr](https://www.jsdelivr.com/package/npm/tiptap)

**Comment by pshah123** [comment]
The JSDelivr CDN version of tiptap doesn't seem to be packed/built correctly, for now a workaround is to use this [repository](https://github.com/zakariamouhid/tiptap-build) which has built versions of tiptap (under the global variable `tiptapBuild`, and camel-cased i.e. `tiptapBuild.tiptapCommands`)
