### ISSUE TITLE
tiptap-extensions is using tiptap-utils package without specifying it as dependency

### ISSUE THREAD

**Issue by Demivan** [ueberdosis/tiptap#709]
**Describe the bug**
When using yarn v2 (berry) you get error when using `tiptap-extensions` package.

**Steps to Reproduce / Codesandbox Example**
1. Use yarn v2 as your package manager
2. Add tiptap-extensions package
3. Try building project (I'm using webpack)
4. See error:

```
Module not found: Error: A package is trying to access another package without the second one being listed as a dependency of the first one

Required package: tiptap-utils (via "tiptap-utils")
Required by: tiptap-extensions
```

**Expected behavior**
No errors should be produced.

**Environment**
 - OS: Windows
 - Package manager: yarn v2 (berry)

**Additional context**
Yarn v2 is now much stricter about dependencies and does not allow for package to access another package if it is not specified in package.json

**Comment by hanspagel** [comment]
Thanks for reporting! Fixed with the latest version of `tiptap-extensions`.
