### ISSUE TITLE
Search and Replace edge case bug?

### ISSUE THREAD

**Issue by JamesMckenna** [ueberdosis/tiptap#710]
Please excuse me as I am an amateur and this is the first post/bug report I have submitted. I believe I have found an edge case bug in the Search and Replace Extension.   

1) Have multiple p tags/node extensions in the same Editor instance with the same sentence/words.
Example: 
 I am test search and replace functionality
 I am test search and replace functionality
 I am test search and replace functionality
 I am test search and replace functionality

2) Enter "test" as a search term. 
3) Click the Find button. A mark node with class="find" will be inserted and wrap each instance of the word "test".
4) Enter "testing" in the replace input field.
5) Click the Replace button. The first instance of "test" is replaced with "testing"
6) Click the Replace button again. The first instance of "test" becomes "testinging"
7) Click the Replace button a third time. The first instance of "test" becomes "testinginging"

**Expected behavior**
I would expect the first instance of "test" to become "testing" and increment to the next instance of the word "test". Where I could click the replace button to replace the second instance of the word "test"

**Environment**
 - OS: [Windows 10]
 - Browser: chrome, firefox, edge
 - Version: 1.27.1
 - Mobile / Desktop: [Desktop]

**Comment by hanspagel** [comment]
Thanks for the report! Yes, that would be a better behaviour.
