### ISSUE TITLE
Example for TrackState

### ISSUE THREAD

**Issue by tvld** [ueberdosis/tiptap#714]
One of the sublime advantages of ProseMirror is to [track changes](https://prosemirror.net/examples/track/).  Being inexperienced, it's not so easy to turn that example in a TipTap plugin.

Anybody who can show how?

**Comment by hanspagel** [comment]
I’ve added this to the things we might add to tiptap v2. Thanks for the suggestion! I’m closing this here though. ✌️

**Comment by tvld** [comment]
@hanspagel Great - looking forward ))... This would make TipTap stands head and shoulders above the others ))) :-)

**Comment by lumenwrites** [comment]
Hi! Are there any updates on that? I'd **really** love this feature.
