### ISSUE TITLE
Conflicting versions of prosemirror-model installed

### ISSUE THREAD

**Issue by dougalg** [ueberdosis/tiptap#720]
**Describe the bug**
When using vanilla tiptap, errors are thrown because of conflicting versions of prosemirror-model.

**Steps to Reproduce / Codesandbox Example**
1. New project
2. `yarn add tiptap`
3. Create a minimal build
4. Type in the editor
5. Go to the end of the last line and hit enter
6. See error

**Codesandbox**

https://codesandbox.io/s/vue-issue-template-m4u2j

**Expected behavior**
There should be no errors

**Screenshots**

![image](https://user-images.githubusercontent.com/210433/83398798-44ea2a00-a42a-11ea-9c91-b6e2d566c4a5.png)

**Environment**
 - OS: Mac OS
 - Browser All
 - Version 1.27.1
 - Mobile / Desktop: Desktop

**Additional context**
`yarn why` provides some information on the conflicts:

```
> yarn why prosemirror-model
=> Found "tiptap#prosemirror-model@1.9.1"
=> Found "tiptap-commands#prosemirror-model@1.9.1"
=> Found "tiptap-utils#prosemirror-model@1.9.1"
=> Found "tiptap#prosemirror-view#prosemirror-model@1.10.0"
```

Adding resolutions to my package.json solves the issue:

```
	"resolutions": {
		"prosemirror-model": "1.10.0"
	},
```

**Comment by MaksOta** [comment]
I was also having this problem. Same version, Linux OS.

The provided solution fixed the problem but now yarn is saying other packages are requesting a different version of prosemirror-model. I am afraid this might cause other conflicts

**Comment by jscaux** [comment]
See #577 which also remains unsolved. I'm afraid the "resolutions" solution isn't a proper solution.

**Comment by dougalg** [comment]
Sorry, I should have been clearer. What I meant is "adding resolutions to my package.json acts as a functional workaround for now."

**Comment by dkotik** [comment]
I have the same problem. Your solution worked!

**Comment by jnguyen32** [comment]
The resolution that worked for me:

delete package-lock.json
delete node_modules
npm install && rebuild (npm run dev for me)

**Comment by lehni** [comment]
I'm fairly certain this is a duplicate fo #577 and can probably be closed

**Comment by hanspagel** [comment]
Thanks for sharing the workarounds! Closing this here, as it’s a duplicate with #577.
