### ISSUE TITLE
getHTML function does not return colgroup for tables

### ISSUE THREAD

**Issue by MichalKrakow** [ueberdosis/tiptap#721]
getHTML function does not return colgroup for tables

1.Create table,
2. Adjust width
3. Check onUpdate => state.getHTML() for colgroup - its not there

The provided HTML should consist of colgroup to define proper column widths

**Comment by philippkuehn** [comment]
For tables we use `prosemirror-tables`, which unfortunately is currently not maintained anymore. Maybe we will do a re-write ourselves someday, but this is a huge project and will take a long time. Until then, this is not supported.
