### ISSUE TITLE
Bullet list getting rendered to DOM but not working

### ISSUE THREAD

**Issue by arrpitsharrma** [ueberdosis/tiptap#731]
I am working on tiptap integration with Vue where Bold, Ordered List, Italics and Underline is working.
But Bullet-List is not working.

As soon as I remove the list-style: none from CSS, bullet-list shows up. But I am not able to change the CSS with my custom code.
![image](https://user-images.githubusercontent.com/21288210/84489814-1dc7ff80-ac57-11ea-859f-e32ddd829b59.png)

![image](https://user-images.githubusercontent.com/21288210/84489848-2ae4ee80-ac57-11ea-8f72-06e9362e7dc1.png)
![image](https://user-images.githubusercontent.com/21288210/84489862-30423900-ac57-11ea-83af-7a3cc5658025.png)

**Comment by hanspagel** [comment]
I tried this:

```css
ul {
  list-style: none;
  border: 10px solid red;
}
```

https://codesandbox.io/s/vue-issue-template-ovpou?file=/src/App.vue

But couldn’t find an issue with tiptap. Would you please provide a code sandbox with your code? Here is a starting point: https://codesandbox.io/s/vue-issue-template-h0g28

I’ll reopen it then.

**Comment by tsangaris** [comment]
Hey guys,

Any news on this one?

**Comment by philippkuehn** [comment]
We need a demo that reproduces this issue.

**Comment by Sumis34** [comment]
If you are working with Tailwind you have to add the [typography plugin](https://tailwindcss.com/docs/typography-plugin )for Lists to render correctly.

**Comment by mmohades** [comment]
If you're using TailwindCSS, you need to style your lists as they're defaulted to no style. Here's an example:
```
  const editor = useEditor({
    extensions: [
      StarterKit, BulletList.configure({
        HTMLAttributes: {
          class: 'list-disc'
        }
      })
    ],
    content: ''
  });
```
Read more about [Tailwind list styles](https://tailwindcss.com/docs/list-style-type).

**Comment by OkeleyeVick** [comment]
> If you are working with Tailwind you have to add the [typography plugin](https://tailwindcss.com/docs/typography-plugin) for Lists to render correctly.

For anybody coming here to check this, this is the best solution that works without any issue

**Comment by Ansub** [comment]
Thanks @OkeleyeVick that was a quick fix!

**Comment by kravenhunter** [comment]
I wanted to add my five cents also.  Or  you use base  configure  like StarterKit and  configure extensions inside  of it  as  : 
      StarterKit.configure({
        bulletList:{
          class: "bullet_class",
        },
        orderedList:{
          class: "order_class",
        },

        heading: {
          HTMLAttributes: {
            class: "headers_class",
          },
        },})
 or  you customize  editor  by adding  extension   into  extensions: [ BulletList, OrderedList] but  before you need to remove  StarterKit.   When  I'm  adding   all extensions with StarterKit  in nuxt project I'm getting  the error  => @tiptap_vue-3.js:3262  [tiptap warn]: Duplicate extension names found: ['bulletList', 'orderedList', 'listItem']. This can lead to issues.

**Comment by hadiqaiser** [comment]
> > If you are working with Tailwind you have to add the [typography plugin](https://tailwindcss.com/docs/typography-plugin) for Lists to render correctly.
> 
> For anybody coming here to check this, this is the best solution that works without any issue

Yes this do return default style but it also add additonal margins which we then need to manually handle.

**Comment by geovanygameros** [comment]
I'm also using Tailwind with Nextjs and I found a simpler solution without modifying the main Tailwind theme. Just add `list-style: revert` to your editor styles file:
```scss
// ... rest of your editor styles
  ul, 
  ol {
    list-style: revert; // <------- Just add this line for both ordered and unordered lists
  }
```

**Comment by HugoDerigny** [comment]
> HTMLAttributes: {
>           class: 'list-disc'
>         }

When adding `list-inside` to class, it's breaking the inline style. 

A potential fix is to add a left padding to it.

```js
StarterKit.configure({
		bulletList: {
			HTMLAttributes: {
				class: 'list-disc pl-4'
			}
		},
		orderedList: {
			HTMLAttributes: {
				class: 'list-decimal pl-4'
			}
		},
})
```

**Comment by MatheusMRafino** [comment]
@tsangaris The code you wrote with css in <style> saved me, it worked perfectly for me. Thank you very much!
