### ISSUE TITLE
What is filename

### ISSUE THREAD

**Issue by shellus** [ueberdosis/tiptap#734]
https://github.com/scrumpy/tiptap/blob/master/examples/main.js
```
const __svg__ = { path: './assets/images/icons/*.svg', name: 'assets/images/[hash].sprite.svg' }
svgSpriteLoader(__svg__.filename)
```
filename is undefine ?

**Comment by hanspagel** [comment]
That’s the name of the generated SVG sprite. But that’s the code for the rendering of the examples, nothing you should need to copy. 

tiptap is renderless, so the bad thing: you **need** to come up with your own rendering (HTML/CSS, icons …), the good thing: you **can** come up with your own rendering. 

We consider to add a “default” style (and documentation for it) in the future though.
