### ISSUE TITLE
Support Vue 3

### ISSUE THREAD

**Issue by stefnotch** [ueberdosis/tiptap#735]
**Is your feature request related to a problem? Please describe.**
As [Vue 3](https://github.com/vuejs/vue-next/) is getting closer to being released, it would be worthwhile to consider supporting it. Currently, tiptap already fails when importing Vue 3, because it does not have a default export anymore.

**Describe the solution you'd like**
Being able to use the current version of tiptap with Vue 3 would be great. Maybe it would be possible to release a different package with Vue 3 support?

**Additional context**
If I'm not mistaken, with [tiptap v2](https://github.com/scrumpy/tiptap/issues/547), supporting different Vue.js versions should become much easier.

**Comment by akirarika** [comment]
At present, the official website does not have the documentation of vue3. I don't think this is a good time to support it.

Tiptap V2 is no longer limited by JavaScript framework. You can consider using it in the future.

**Comment by djixadin** [comment]
> I don't think this is a good time to support it.

LOL

**Comment by Septias** [comment]
isn't this the official documentation? https://v3.vuejs.org/

**Comment by rossunger** [comment]
+1. Beautiful editor. would love to use for our project, but we're using Vue 3 :(

**Comment by hanspagel** [comment]
We started the work on tiptap 2, which will likely be compatible with Vue.js 3. 🌿

**Comment by CaptainYouz** [comment]
Hi ! 
Any news on this one ?

**Comment by hanspagel** [comment]
Thanks for asking! We use Gridsome for the new (and really awesome) documentation and are waiting until they are compatible with Vue.js 3, but they wait for the new version of vue-meta. [1]

When vue-meta is upgraded, and Gridsome follows, we will start to work on the Vue parts of tiptap 2 and hope to give access to more and more people soon after.

Let me know if you have further questions!

[1] https://github.com/nuxt/vue-meta/issues/558

**Comment by KevinNTH** [comment]
@hanspagel I do not understand why is Tiptap waiting for Gridsome to upgrade to support Vue3 (I don't see any relation)?

Besides, Nuxt 3 will be using https://github.com/vueuse/head and not vue-meta anymore.

**Comment by hanspagel** [comment]
Thanks for asking @KevinNTH! We decided to go with a huge monorepo that includes the code of all packages, including tests and documentation. 

For the documentation we’re using Gridsome. Installing Vue 3 in the repository would conflict with Gridsome, which is used to render the documentation, all interactive demos and to serve the code for all tests.

We have a long backlog of amazing things we’d like to add to tiptap and don’t see us switching to Nuxt.js to hurry the upgrade to Vue 3. But we’re following the development all of the mentioned projects, Gridsome, Nuxt.js, vue-meta and vueuse/head. ✌️

**Comment by EugeneHerasymchuk** [comment]
Amazing to hear that you're on top of the news about related packages.

Vue 3 upgrade would be awesome!

**Comment by hanspagel** [comment]
The new tiptap 2 beta (currently available for sponsors only) has support for Vue 3. 🎉 

https://blog.ueber.io/post/tiptap-2-0-beta/

BTW: We’ll keep supporting Vue 2, too.

**Comment by ayophanz** [comment]
great

**Comment by nicolidin** [comment]
Does someone know when the stable tip-tap v2 will be available to use?

**Comment by hanspagel** [comment]
tiptap v2 is merged in to `main`. 👀  Time to close the issue.

https://www.tiptap.dev/installation/vue3
