### ISSUE TITLE
Is there a way to create snippts?

### ISSUE THREAD

**Issue by CavalcanteLeo** [ueberdosis/tiptap#737]
something like:
If I type **ttyl** will show **talk to you later** instead

then i can create as many snippets as i want

and if i type an special char (something like **&**) will show all my snippets like mention is shown (tooltip)

**Comment by hanspagel** [comment]
Thanks for your suggestion! It’s on our list to add that to [tiptap v2](https://blog.ueber.io/post/our-plan-for-tiptap-2/) at some point. But I’m closing this for now.
