### ISSUE TITLE
Editor MenuBar buttons are not reactive

### ISSUE THREAD

**Issue by Cwhite534** [ueberdosis/tiptap#738]
The editor-menu-bar buttons are not reactive.

We have an app that contains multiple pages, navigating to a page creates a TipTap editor and populates the content based off query string of the desired page. When the first page containing an editor is loaded, everything works as expected, Upon loading another page the menuBar will not highlight the buttons correctly. Eg clicking bold will correctly bold the selected text, but the toolbar button will not be highlighted unless you click outside the editor. Using vue dev tools we can see that 'IsActive.bold()' value is correctly being updated.

It should be noted keeping all things the same, but changing `editor-menu-bar` to `editor-menu-bubble` fixes this issue entirely.

This occurs in Edge (Chromium), Edge Legacy, Chrome, and Firefox on Windows and Linux operating systems. 

I am unsure if the reason is because when changing pages another editor is instantiated, but any input would be appreciated.

**Comment by cliftonscott** [comment]
I'm seeing the same problem.

**Comment by lahdekorpi** [comment]
I can confirm this.

If you update the view manually, then it will work. I created a test counter in the toolbar view that increments every second. Every time the view updates, the buttons change state correctly.

**Comment by gregveres** [comment]
I am seeing the same problem. I thought I was going crazy. :) The strange thing is that things work fine in the demo and my code looks very similar to the demo - I was comparing to the tables demo. 
Its like the menu bar doesn't re-render when isActive changes.

**Comment by gregveres** [comment]
The strange thing is that it must work some times. I have been looking at [tiptap-vuetify](https://iliyazelenko.github.io/tiptap-vuetify-demo/#/custom-toolbar) and their demo works properly. Also all the tiptap demos work properly. There must be something we are doing that is messing up the updating.

**Comment by gregveres** [comment]
And just to be clear to anybody else who runs across this, the work around is to just replace "editor-menu-bar" with "editor-menu-bubble". You can still use your normal toolbar without having to adopt the bubble style menu.

**Comment by gregveres** [comment]
I can confirm that this bug was introduced somewhere between 
    "tiptap": "^1.26.6",
    "tiptap-extensions": "^1.28.6",

and
    "tiptap": "^1.29.6",
    "tiptap-extensions": "^1.32.6",

I am using 1.29.6 and I have this problem.
[Element-tiptap](https://github.com/Leecason/element-tiptap/blob/master/package.json) is using 1.26.6 and doesn't have the problem. I just wasted a couple hours on this again before I remembered this issue exists. :(

**Comment by gregveres** [comment]
I can confirm this is still an issue in v1.30.0 - although that version did fix the blockquote issue!

**Comment by hanspagel** [comment]
Thanks for reporting @Cwhite534! And thanks @gregveres for sharing all the details! I’m closing this issue in favor for #700, which seems to report the same bug. ✌️

**Comment by empflow** [comment]
None of the proposed solutions worked for me, so I've some up with this: after you use, for example, run `editor.chain().focus().toggleStrike().run()`, you also have to force a re-render of the toolbar item or whatever is reflecting the state of `editor.isActive("...")`. I just created a hook called `useRerender`:
```
import { useState } from "react";

export default function useRerender() {
  const [_rerenderState, setRerenderState] = useState(false);

  function rerender() {
    setRerenderState((prev) => !prev);
  }

  return rerender;
}
```

and then I call the function returned by the `useRerender` hook whenever I toggle italic, bold, etc:
```
  function toggleStrikethrough() {
    editor?.chain().toggleStrike().focus().run();
    rerender();
  }

  <ToolbarItem
    tooltipText={t("strikethrough")}
    icon={<StrikethroughIcon />}
    onClick={toggleStrikethrough}
    disabled={!editor?.can().chain().toggleStrike().focus().run()}
    isActive={editor?.isActive("strike")}
  />
```

**Comment by TigranWA** [comment]
It's still actual for the latest Editor version.
Toolbar is not re-rendering, when editor state changes. 
Only this "workaround" is working for me.
```
  const editorState = useEditorState({
    editor,
    // This function will be called every time the editor state changes
    selector: ({ editor }: { editor: Editor }) => ({
      // It will only re-render if the bold or italic state changes
      isBold: editor.isActive("bold"),
      isItalic: editor.isActive("italic"),
    }),
  });

  return (
    <>
      <button
        onClick={() => editor.chain().focus().toggleBold().run()}
        className={editorState.isBold ? "is-active" : ""}
      >
        Bold
      </button>
      <button
        onClick={() => editor.chain().focus().toggleItalic().run()}
        className={editorState.isItalic ? "is-active" : ""}
      >
        Italic
      </button>
      <EditorContent editor={editor} />
    </>
```

Only if I have useEditorState (with all related things) - my toolbar is re-rendering

**Comment by bekiomonov** [comment]
Whoever is facing this issue (i.e. toolbar buttons remain inactive) just use tiptap version 2.22.3

**Comment by Tratt0re** [comment]
If you're still encountering this error and want to resolve it using Tiptap version 3.*, you can enable `"shouldRerenderOnTransaction: true"` in the editor configuration.
