### ISSUE TITLE
Pasting "shortened link" is not recognized as a link (incorrect regex)

### ISSUE THREAD

**Issue by Novusphere** [ueberdosis/tiptap#745]
**Describe the bug**
See the rule: https://github.com/scrumpy/tiptap/blob/master/packages/tiptap-extensions/src/marks/Link.js#L53
It requires the domain before the TLD name to be at least 2 characters, but for example, Telegram style links are not

**Steps to Reproduce / Codesandbox Example**
Try the string `https://www.google.com https://t.me/eosgo/9258` on regexpal, it fails to notice the `t.me` link

**Fix**
by changing `{2,256}` to `{1,256}` in the existing regex, this problem is resolved.

Additionally, until this is patched in the main branch, you can use `Link2` in place of `Link`

```js
import { pasteRule } from 'tiptap-commands';
import {
    Link,
} from "tiptap-extensions";

export default class Link2 extends Link {

    pasteRules({ type }) {
        return [
            pasteRule(
                /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._+~#=]{1,256}\.[a-zA-Z]{2,}\b([-a-zA-Z0-9@:%_+.~#?&//=]*)/g,
                type,
                url => ({ href: url }),
            ),
        ]
    }

}
```

**Comment by Novusphere** [comment]
Another follow up to this is that it doesn't recognize non-lowercase links, i.e. `HTTP://www.GOogle.cOM` which can easily be fixed by modifying the pasteRule regex to have the `i` flag. `/gi`

**Comment by hanspagel** [comment]
Thanks! Fixed.
