### ISSUE TITLE
Delete key (forward delete) doesn't work on `display: block;` elements

### ISSUE THREAD

**Issue by jnguyen32** [ueberdosis/tiptap#753]
**Describe the bug**
When creating a mark as so: 

`<span style="text-align:center; display:block;">Your Content</span>`

Using forward delete from the preceding element fails to delete the element. Removing the `display:block;` resolves the problem. 

**Steps to Reproduce / Codesandbox Example**

1. Add a mark that alters an element to: `<span style="text-align:center; display:block;">Test</span>`
2. Using the editor, go the paragraph before it and start using the Delete key (not backspace)
3. It will stop when it reaches the centered block element

**Expected behavior**
It should properly delete

**Environment**
 - OS: Windows 10
 - Browser Chrome (Latest)
 - Desktop

**Comment by hanspagel** [comment]
Thanks for reporting @jnguyen32!

Not sure we can resolve this though. Extensions that are rendered as block elements should be Nodes (instead of Marks). I think that’s needed to get the behaviour right. 😏  

I’m closing this here for now.
