### ISSUE TITLE
Replacing nbsp; to regular space

### ISSUE THREAD

**Issue by MrAtiebatie** [ueberdosis/tiptap#754]
I've been trying to automatically replace `&nbsp;` to a normal space when someone is pasting in some text or HTML. The preserveWhitespace option doesn't do much for me.

I've asked this question on [StackOverflow](https://stackoverflow.com/questions/62596125/prosemirror-vue-tiptap-replace-nbsp-to-space) as well but received 0 reactions.

Does anyone have an idea how to automatically replace `&nbsp;` with ProseMirror/vue-tiptap?

**Comment by hanspagel** [comment]
Hi @MrAtiebatie! Sorry for the silence here. I think you can control this with the parserOptions, see also #168 and #254. 👍
