### ISSUE TITLE
Table/GapCursor Plugin Order

### ISSUE THREAD

**Issue by rmckayfleming** [ueberdosis/tiptap#756]
The current plugin order in tiptap/Editor.js has all Extension defined plugins coming before gapCursor. This causes issues with prosemirror-tables since the documentation notes that the tableEditing() plugin should come after the gapCursor. This causes subtle issues with keyboard selection navigation between back to back tables.

Here's what navigating between tables looks like now:
![Screen Recording 2020-07-08 at 10 30 07 AM](https://user-images.githubusercontent.com/2660301/86931876-a1fe8d00-c106-11ea-90be-430bde354e33.gif)

Here's how it should work (with gapCursor coming before tables):
![Screen Recording 2020-07-08 at 10 28 51 AM](https://user-images.githubusercontent.com/2660301/86931947-b93d7a80-c106-11ea-9053-7e806dae6b8a.gif)

I'd issue a pull request, but I'm not sure how to best address this issue.

**Comment by hanspagel** [comment]
Hi @rmckayfleming! Thanks for reporting this issue! Unfortunately I can’t reproduce that behaviour. Here is a screen recording of the Tables example (https://tiptap.dev/tables).

![Sep-01-2020 13-56-50](https://user-images.githubusercontent.com/1577992/91848745-309d0f80-ec5b-11ea-8597-4cc77702f5b8.gif)

What can I try to reproduce the issue?
