### ISSUE TITLE
blockquote does not work for custom document

### ISSUE THREAD

**Issue by mvind** [ueberdosis/tiptap#758]
When having a custom document using the blockquote, and codeblock does not work. 

I have recreated the problem in this sandbox: https://codesandbox.io/s/vue-issue-template-zsujf?file=/src/App.vue. There is a custom document with two paragraphs, front and back. You can see that trying to apply the blockquote does not work. 

Custom doc as: 
```javascript
import { Doc } from 'tiptap'

export default class CustomDoc extends Doc {
	get schema() {
		return {
			content: 'front back'
		}
	}

}
```
where the ```front```and ```back```nodes are
```javascript
import { Node } from 'tiptap'

export default class Back extends Node {

  get name() {
    return 'back'
  }

  get schema() {
    return {
      content: 'paragraph+',
      toDOM: () => ['back', 0]
    }
  }

}
```
```javascript
import { Node } from 'tiptap'

export default class Front extends Node {

  get name() {
    return 'front'
  }

  get schema() {
    return {
	  content: 'paragraph+',
	  toDOM: () => ['front', 0]
    }
  }
}
```
In my project I have only tested for multiple custom documents and so far blockquote, codeblock, and code does not toggle any wrapping. 

I have only tested this in Chrome. 

I have tried to debug this but I can't really figure out a way of seeing the core problem. I walked through the debugger on the menubar command, i.e:
```javascript
    <button
          class="menubar__button"
          :class="{ 'is-active': isActive.blockquote() }"
          @click="debugger; commands.blockquote"
        >
          <span>quote</span>
        </button>

```
But found no concrete problems. I hope this bug is clear enough to understand :)

/Mvind

**Comment by mvind** [comment]
Changing the ```front```and```back```to block instead of paragraphs fixes the problem.

**Comment by hanspagel** [comment]
Thanks for sharing the solution!
