### ISSUE TITLE
Subtitle option

### ISSUE THREAD

**Issue by pexpert** [ueberdosis/tiptap#763]
I followed the example provided for the Title component and I was very pleased with the final layout. But, for the purposes of my app, I still need to have a subtitle camp, which I am having trouble finding a way to incorporate. I think it would be a great addition to provide the option to display and write a subtitle. :)

<img width="674" alt="Captura de Tela 2020-07-16 às 22 52 27" src="https://user-images.githubusercontent.com/66281612/87740165-e5689380-c7b7-11ea-894a-2b65ec98e383.png">

**Comment by hanspagel** [comment]
Thanks for the suggestion! I added it to our list of considered extensions for [tiptap v2](https://blog.ueber.io/post/our-plan-for-tiptap-2/). For now, I’m closing this here. ✌️
