### ISSUE TITLE
Blockquote is not changing anything

### ISSUE THREAD

**Issue by janswist** [ueberdosis/tiptap#773]
**Describe the bug**
Blockquote does nothing.

**Steps to Reproduce / Codesandbox Example**
1. Select text
2. Click blockquote from menu
3. Nothing happens (in source code I can see it's enabled though, see screenshot below)

**Expected behavior**
When enabling (or having it already in initial content) blockquote I expect text to go little gray and have vertical line in front of it on the left.

**Screenshots**
![image](https://user-images.githubusercontent.com/5583954/88541991-f7e39800-d015-11ea-9f2b-f22148fd4b01.png)

**Environment**
 - OS: MacOS
 - Browser: Chrome
 - Version: "tiptap": "^1.29.1",  "tiptap-extensions": "^1.31.1",
 - Mobile / Desktop: Desktop

**Additional context**

**Comment by Chrissi2812** [comment]
As tiptap is a [renderless](https://github.com/ueberdosis/tiptap#what-does-renderless-mean) editor component the styling is not part of tiptap, it's up to you.

Here ist the style used in the examples:
https://github.com/ueberdosis/tiptap/blob/5cb2bfeacc604150183b934b44b80bdc392a8da6/examples/assets/sass/editor.scss#L53-L62

Hope this helps.
