### ISSUE TITLE
Paste from notepad

### ISSUE THREAD

**Issue by glavdir** [ueberdosis/tiptap#775]
When I copy and paste blank text from notepad, divided into paragraphs, blank lines are lost.

Example. The text I'm copying:
111111
222222

333333

Text after pasting:
111111
222222
333333

Perhaps there is an extension that can solve this problem?

**Comment by danrice01** [comment]
This is a big issue for us as well, any tips on how to patch in the current version?

**Comment by hanspagel** [comment]
Currently, I don’t have an idea, not even for the new version. 😕 Open for suggestions!

**Comment by glavdir** [comment]
Here's a bad solution, but it worked:

```
import {Slice, Fragment, Node} from 'prosemirror-model'

function clipboardTextParser(text, context, plain)
{
    const blocks = text.replace().split(/(?:\r\n?|\n)/);
    const nodes = [];

    blocks.forEach(line => {
        let nodeJson = {type: "paragraph"};
        if (line.length > 0) {
            nodeJson.content = [{type: "text", text: line}]
        }
        let node = Node.fromJSON(context.doc.type.schema, nodeJson);
        nodes.push(node);
    });

    const fragment = Fragment.fromArray(nodes);
    return Slice.maxOpen(fragment);
}
```

```
....
      tipTapEditor: new Editor({
          editorProps: {
              clipboardTextParser: clipboardTextParser,
          },
      })
....
```

**Comment by maelpetit** [comment]
Hi, I'm having no luck with your solution.

The problem I'm trying to solve is I don't want tiptap to add a `<p>` per line when I'm pasting

I'm trying to redefine `clipboardTextParser` as you did but the method is never called. I've checked with `console.logs` and `debugger`.

It seems that the editorProp `clipboardTextParser` is not set to the editor, but `handlePaste` or `handleClick` are set and I can modify them.

Thanks for your help :smile:

**Comment by eomttt** [comment]
Why tiptap does not maintain blank lines??

@glavdir

**Comment by mmachatschek** [comment]
@eomttt actually this is already a problem on prosemirror side see: https://discuss.prosemirror.net/t/new-lines-change-when-pasting-and-copying/2157

**Comment by philippkuehn** [comment]
Closing this because I don't want to change the [default behavior](https://discuss.prosemirror.net/t/new-lines-change-when-pasting-and-copying/2157) of ProseMirror.
