### ISSUE TITLE
Space is not properly rendering

### ISSUE THREAD

**Issue by janswist** [ueberdosis/tiptap#776]
**Describe the bug**
When I hit the spacebar there is not space displayed even though on the left in Vue dev tools you can see that space event was recorded. 

**Steps to Reproduce / Codesandbox Example**
Put space in whatever place. When cursor is not in the end then it creates proper space and jumps at the end of the paragraph.

**Expected behavior**
Normal space, nothing fancy.

**Environment**
 - OS: MacOS
 - Browser: Chrome 83
 - Version: 1.29.1
 - Mobile / Desktop: Desktop

**Screenshots**
![bez nazwy](https://user-images.githubusercontent.com/5583954/88682121-9c3b0c80-d0f2-11ea-969f-c664086fbb32.gif)

**Comment by hanspagel** [comment]
That’s not how the examples behave: https://tiptap.dev/ 

Seems to be a problem with your code, especially your styling. Please provider a codesandbox, so others can help here.

**Comment by janswist** [comment]
Here is the reproduction code: https://codesandbox.io/s/bootstrap-vue-sandbox-h6dmy

From what I found is that `.ProseMirror` class has `white-space: pre-wrap` which when disabled in Chrome console it make it work again.

**Comment by Chrissi2812** [comment]
The Problem seems to be the watcher, it triggers the `onUpdate` callback again.
The second argument in `setContent`allows to not emit the onUpdate event.

```js
  watch: {
    value(val) {
      this.editor.setContent(val, false);
    },
  },
```

**Comment by janswist** [comment]
It still works the same, unfortunately. I found another issue though: whenever I make a change within text then cursor moves to the last position. Maybe that will help finding what' going on there.

**Comment by Chrissi2812** [comment]
Okay the prblem is that the watcher will get fired when you type in the editor. So this will check if the editor has focus an will only update the editor content if that's not the case. 

```js
  watch: {
    value(val) {
      if (!this.editor.focused) {
        this.editor.setContent(val, false);
      }
    }
  },
```

https://codesandbox.io/s/bootstrap-vue-sandbox-zl2pk

**Comment by janswist** [comment]
Brilliant! Now it's working - thanks a lot. It might be a good idea to show it in documentation as a v-model example implementation for others :)

Cheers!

**Comment by AzadAnsari35** [comment]
@Chrissi2812 How to do the same in reactjs? I am using tiptap v2.

**Comment by earvinLi** [comment]
> @Chrissi2812 How to do the same in reactjs? I am using tiptap v2.

the following works for me and for anyone who uses React:
```
onBlur: ({ editor }) => {
  onChange(editor.getHTML());
},
```

**Comment by JahnoelRondon** [comment]
> 

I tried doing that and nothing happened. I even console.logged when there was an onblur and got nothing, also what on onChange because React or tiptap doesnt Recognize it.


```js
    onBlur: ({ editor }) => {
      const cleanText = profanity.clean(editor.getHTML());
      console.log(cleanText);
      onchange(cleanText);
    },
```

**Comment by paulzay** [comment]
@JahnoelRondon thank you so much for this, just solved the same issue for me in nextjs

**Comment by l1m2e** [comment]
> > 
> 
> ### React solution
> I tried doing that and nothing happened. I even console.logged when there was an onblur and got nothing, also what on onChange because React or tiptap doesnt Recognize it.
> 
>     onBlur: ({ editor }) => {
>       const cleanText = profanity.clean(editor.getHTML());
>       console.log(cleanText);
>       onchange(cleanText);
>     },
> Edit >
> 
> This is the actual solution perscribed by the tiptap setContent Options
> 
> editor.commands.setContent(cleanText, false, {preserveWhitespace: "full"});
> you can alternatively set it to true but full covers all spaces

Thank you!  This works well with Vue too.
