### ISSUE TITLE
Auto Link when click Enter

### ISSUE THREAD

**Issue by cristianpoleyJS** [ueberdosis/tiptap#783]
When I type a link in the content and click the **Enter button**, it is not detected as a link and the `<p>` element remains, but if I click the space tab it is detected.

```javascript
import { markInputRule } from 'tiptap-commands'
import { Link } from 'tiptap-extensions'

export class CustomLink extends Link {
  get schema () {
    return {
      attrs: {
        href: {
          default: null
        },
        'data-link-type': {
          default: 'link'
        },
        target: {
          default: null
        },
        rel: {
          default: null
        },
        class: {
          default: 'oct-a'
        }
      },
      inclusive: false,
      parseDOM: [
        {
          tag: 'a[href]',
          getAttrs: dom => {
            return {
              href: dom.getAttribute('href'),
              target: dom.getAttribute('target'),
              rel: dom.getAttribute('rel'),
              'data-link-type': dom.getAttribute('data-link-type')
            }
          }
        }
      ],
      toDOM: node => {
        return [
          'a',
          {
            ...node.attrs,
            target: '__blank',
            class: 'oct-a',
            rel: 'noopener noreferrer nofollow'
          },
          0
        ]
      }
    }
  }

  inputRules ({ type }) {
    return [
      markInputRule(
        /(https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\\+.~#?&//=]*))\s$/g,
        type,
        (url) => ({ href: url[0] })
      )
    ]
  }
}

```
When paste link
![](https://media2.giphy.com/media/SvFnv4xcjguAQl11cv/giphy.gif)

When write link and click space tab:
![](https://media1.giphy.com/media/Yq8sU1EeQKD0HigVEA/giphy.gif)

When write link and click Enter:
![](https://media1.giphy.com/media/XBuiGm8MwkNAH5Vdlb/giphy.gif)

**Comment by BrianHung** [comment]
ProseMirror input-rules by default do not span between paragraphs: https://discuss.prosemirror.net/t/trigger-inputrule-on-enter/1118. To implement this behavior, try creating a custom subclass of https://github.com/ProseMirror/prosemirror-inputrules which looks between paragraphs.

**Comment by cristianpoleyJS** [comment]
I guess it will be studied to be added in Tiptap version 2 @hanspagel.
Looking forward to it! I close the PR.

**Comment by daniellokato** [comment]
@cristianpoleyJS I have the same problem. Were you able to find a solution?
