### ISSUE TITLE
Code discrepancy between dist and src

### ISSUE THREAD

**Issue by chrisjbrown** [ueberdosis/tiptap#797]
**Describe the bug**
I see that there is code missing in the dist directory compared to src

specifically `dist/tiptap.esm.js`

**Steps to Reproduce / Codesandbox Example**
1. Install tiptap as dependency
2. compare dist to src `dist/tiptap.esm.js` to `src/Editor.js`

**Screenshots**

`src/Editor.js`
![Screenshot 2020-08-12 at 11 20 55](https://user-images.githubusercontent.com/1250638/89998498-f066f480-dc8d-11ea-94ff-0b2a5a870ee9.png)

vs:

`dist/tiptap.esm.js`
![Screenshot 2020-08-12 at 11 21 50](https://user-images.githubusercontent.com/1250638/89998610-1391a400-dc8e-11ea-8953-11d6de8f8acc.png)

**Comment by hanspagel** [comment]
Oh, that‘s very strange. I have no idea how this can happen. Need to investigate here, thankful for every hints.

**Comment by hanspagel** [comment]
I deleted the build locally and tagged a new version, the issue seems fixed now. Can you try to update to the latest version?

**Comment by chrisjbrown** [comment]
Yup looks good now
