### ISSUE TITLE
Missing repository Icons in https://github.com/Studapart

### ISSUE THREAD

**Issue by phpclub** [ueberdosis/tiptap#800]
**Describe the bug**
Missing
https://github.com/Studapart/design-system/tree/master/packages/components/icon

**Steps to Reproduce / Codesandbox Example**
Try example
import Icon from 'Components/Icon'

**Environment**
 - OS: Ubuntu

**Comment by hanspagel** [comment]
Thanks for filing this issue. 

Tiptap is renderless, so it doesn’t come with styling (and icons), that’s intended. We see that this is not very intuitive and we’re working on a starter kit that includes a few more basics.

For now, the solution is to 1) remove the `<Icon />` in your project or 2) register an own `<Icon />` component. Hope that helps!

**Comment by phpclub** [comment]
Please correct example
https://github.com/ueberdosis/tiptap/blob/main/examples/Components/Routes/Basic/index.vue
