### ISSUE TITLE
Collaborative editing example broken

### ISSUE THREAD

**Issue by ianjaku** [ueberdosis/tiptap#801]
**Describe the bug**
The collaborative editing example has been broken for a while. The text just doesn't update at all. This doesn't give a great first impression to users who are checking out the examples.

**Steps to Reproduce / Codesandbox Example**
1. Go to https://tiptap.dev/collaboration
2. Type anything
3. Reload
4. Your changes didn't save

You can also open 2 browser windows to test, same issue.

**Environment**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 79
 - Mobile / Desktop: Desktop

**Comment by hanspagel** [comment]
Thanks for pointing this out! We’re using a Glitch demo where we regularly exceed some limits. We reset the database there, now the example works again. ✨
