### ISSUE TITLE
Can't remove Blockquote

### ISSUE THREAD

**Issue by lao9s** [ueberdosis/tiptap#803]
Can't remove Blockquote mark. Even on demo site not working.
![ezgif-4-28a75fac8dbb](https://user-images.githubusercontent.com/3392129/90629296-cb432a80-e227-11ea-970b-605532b4de5b.gif)

**Comment by nagbg** [comment]
I have the same problem

**Comment by hanspagel** [comment]
Thanks for reporting! That seems to be an issue for a while now.

I tried to debug the issue, all I know for now is that those two lines (findSelectedNodeOfType, findParentNode) don’t work for the blockquote:
https://github.com/ueberdosis/tiptap/blob/128c9077ad6966d0f37d041eaf32fc253a6c1072/packages/tiptap-utils/src/utils/nodeIsActive.js#L8-L9

**Comment by lahdekorpi** [comment]
Any workarounds for this for the time being?
