### ISSUE TITLE
Improve the Nuxt.js integration

### ISSUE THREAD

**Issue by hanspagel** [ueberdosis/tiptap#821]
We see that a lot of you are using tiptap with Nuxt.js, so we want to improve the experience with that.

## Client Side Rendering for the Editor
It’s not obvious that tiptap needs to be executed on the client side. It’s required to wrap the editor in an `<client-only />` component, but it’s easy to forget.

* [ ] Throw a helpful exception if tiptap is rendered on the server

Source: #131 

## Server Side Rendering for the Content
It’s already possible to render the tiptap content in a read-only instance, that should help for the use in apps. If you’re using tiptap to write a blog post, you’d want to render the content on the server side to deliver plain HTML to user. Plain HTML can be easily indexed by Google and others, viewed without JavaScript and so on.

* [ ] Provide an easy way to render the content on the server side 

Source: https://github.com/ueberdosis/tiptap/issues/547#issuecomment-685251674

## Nuxt.js Integration Guide
There are a few issues using tiptap with Nuxt.js for the first time. You need to understand the difference between client side and server side rendering, you shouldn’t create the instance in the `data()` method (see below) and probably more. A short guide would probably help to get things right easier.

* [ ] Add a Nuxt.js Integration Guide to the documentation

## What else?
I don’t have much experience with Nuxt.js. Is there anything that you have been missing? 

Would love to hear your ideas how we can improve the integration.

**Comment by ludo237** [comment]
Let's heat up the discussion with my personal experience.

I use TipTap on client side rendering and I would like to share one strange issue that occurs.

I don't know if this can be labelled as a problem or not but I found that if you spawn an editor instance inside `data` out of 100 automated tests a dozen fails to create the instance.

In other words, avoid this:

```
 data: () => ({
    editor: new Editor(....),
  }),
```

Instead do this:

```
 data: () => ({
    editor: null,
  }),

mounted () {
    this.editor = new Editor(...);
  },
```

Again I'm not sure what the root cause is for this I need to dig a little big further.

For the SSR issue I will try that as soon as I have some free time later this week

**Comment by hanspagel** [comment]
Good point! We should probably write a dedicated guide on Nuxt.js. I added this to the original post above. ✌️

**Comment by ludo237** [comment]
> Good point! We should probably write a dedicated guide on Nuxt.js. I added this to the original post above. ✌️

I can totally look into that

**Comment by bmkubia** [comment]
@hanspagel for rich integration with Nuxt.js I would assume that tiptap could easily out of the box achieve the following:

- SSR support for rendering editor content on the server without having access to document (the #1 problem I have run into, I use a similar approach to @ludo237 )
- Maybe additional documentation and support for Tiptap as a Nuxt plugin
- Configuration within nuxt.config.js

Thanks again for listening to the feedback. Been using tiptap for a few weeks now and it is great! Look forward to v2

**Comment by connecteev** [comment]
@hanspagel I largely agree with @bmkubia here. Couldn't have said it any better.

**Comment by ludo237** [comment]
What would be the benefits of having a `nuxt-tiptap` plugin? I'm genuinely curious.

**Comment by hanspagel** [comment]
Just wanted to chime in and say that I got the rendering working in tiptap 2. It looks like that:

```js
import { generateHtml } from '@tiptap/core'

const document = {
    'type': 'document',
    'content': [{
      'type': 'paragraph',
      'attrs': {
        'align': 'left'
      },
      'content': [{
        'type': 'text',
        'text': 'My sample text'
      }]
    }]
  }
}

const html = generateHtml(this.doc, extensions)
```

That makes it possible to render the HTML without an actual tiptap instance. The current implementation still needs a `document`, but I’m going to add JSDOM support (needed when there is no actual window). That’ll bring this feature to the server side, e. g. for Nuxt.js.

Hope you’re all as hyped about tiptap 2 as I am. 😅

**Comment by bmkubia** [comment]
Amazing work @hanspagel this is fantastic news!

**Comment by hanspagel** [comment]
Closing this here for now, as we improved a lot of that in tiptap 2 already. Feel free to comment though!

**Comment by timhanlon** [comment]
I'm getting `ReferenceError: window is not defined` when trying to use `generateHTML` on the client side with Nuxt based on [these docs](https://next.tiptap.dev/guide/output/#option-2-generate-html-from-prosemirror-json).

**Comment by stetim94** [comment]
Is this feature already available in the beta? I get a document is not defined error. 

Maybe I missed something, is there additional documentation on how to do this server side rendering?
