### ISSUE TITLE
Suggestions with allowSpaces improvements

### ISSUE THREAD

**Issue by emzet93** [ueberdosis/tiptap#823]
**Is your feature request related to a problem? Please describe.**
When using Mention/Suggestion plugin with `allowSpaces` option enabled I faced a few problems:

1. When there is some content after suggestion beginning, it always matches everything to the end of the editor, including non-text nodes (such as over suggestion) which leads to unexpected value of the query string
2. There is no way to programmatically end mentioning process (or I just didn't find one). When using it with `allowSpaces` disabled it is quite straightforward - mentioning process is ended when you either select suggested mention or remove `@` char from the text. With spaces allowed it's much more complex and it would be great if developer could quit mentioning process e.g. when there is no matching results or when user typed two spaces one after another. By ending mentioning process I mean to close suggestion box and remove text decorator like it happens when you press space with `allowSpaces` disabled

**Describe the solution you'd like**

1.  I think the best solution would be to trim suggestion match to the current position of the cursor or to the first non-text node depending what occurs first
2. It would be great if some exiting command reference would be passed as an argument to `onEnter` callback, similar how it works for command for inserting mention in your example:
![image](https://user-images.githubusercontent.com/15943146/92102113-71716180-edde-11ea-83ca-4129d91b1b3c.png)

Another solution would be to allow developers to override suggestion matcher function without forking `Mention.js` and `Suggestions.js` files, like proposed in #593 

When searching for possible solutions I found a few related issues and PRs, but some of them are already closed and not resolved:
#732 
#214 
#571 
#572 
#593

**Comment by hanspagel** [comment]
Thanks for your feedback! ✌️ 

We fixed all of that in the upcoming tiptap version 2. 😊
