### ISSUE TITLE
HardBreak on the last paragraph doesn't move the caret on Firefox

### ISSUE THREAD

**Issue by agazso** [ueberdosis/tiptap#825]
**Describe the bug**
If you are on the last paragraph with some text in it, pressing Shift-Enter does not move the caret to the new line on Firefox. It creates a new line and you can move the caret to the new line if you press down or if you start typing it appears on the new line.

**Steps to Reproduce / Codesandbox Example**
1. Go to the Trailing paragraph test on [tiptap.dev](https://tiptap.dev/trailing-paragraph) (it can be reproduced in any demos, but it's just easier in that one)
2. Go to the last paragraph
3. Type in some text
4. Press Shift-Enter

**Expected behavior**
Pressign Shift-Enter should move the caret to the newly created line.

**Environment**
 - OS: macOS
 - Browser: Firefox only, I could not reproduce in Chrome or Safari
 - Version 80

I cannot reproduce it in Prosemirror either, only in Tiptap editor.

**Comment by hanspagel** [comment]
Thanks for reporting @agazso! Unfortunately, I can’t reproduce this in Firefox 84 on macOS. Would you mind to give it a try again?

If you still encounter the issue, would you mind to try it in a new private window (without browser extensions)? I’m closing this for now, but I’ll reopen it, when we manage to reproduce the issue. ✌️

**Comment by agazso** [comment]
Indeed, this seems to be working well in Firefox 84.

**Comment by hanspagel** [comment]
Cool, thanks for getting back! 🙌
