### ISSUE TITLE
Failed IE 11

### ISSUE THREAD

**Issue by usb248** [ueberdosis/tiptap#826]
Hi,

  Last release causes script fail in IE11, just see (after my upgrade) :
![image](https://user-images.githubusercontent.com/7659927/92409453-f5aa4880-f140-11ea-817f-60c1519e6309.png)

Have you an idea of what can cause this ?
Thanks

**Comment by usb248** [comment]
More information:
![image](https://user-images.githubusercontent.com/7659927/92409660-a57fb600-f141-11ea-942d-017f79914ed1.png)

highlight.js@10.1.2 dependency seems to be written in ES6...

**Comment by hanspagel** [comment]
We don’t support IE11. We’re using too many modern technologies. Sorry about that!

**Comment by usb248** [comment]
@hanspagel any workaround/tips to keep support for IE ?

**Comment by hanspagel** [comment]
None I know of. You can stick with the version that worked for you though. 😏

**Comment by hanspagel** [comment]
Maybe you can use something like babel in your project, but that depends very much on your setup.

**Comment by usb248** [comment]
@hanspagel  already tried to transpil the dependency which causes the problem... I get another error... :(

**Comment by Chrissi2812** [comment]
@usb248 What error do you get? 

I have a Laravel Project with old Laravel mix (v2.1.11) installed an got the latest Tiptap working in IE 11. Maybe this is of help for you.

<details>

Snippet from `package.json`
```json
    "@babel/core": "^7.1.2",
    "@babel/plugin-proposal-object-rest-spread": "^7.0.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/polyfill": "^7.0.0",
    "@babel/preset-env": "^7.1.0",
    "babel-eslint": "^8.2.6",
    "babel-loader": "^8.0.4",
```

Snippet from `webpack.mix.js`
```js
{
  test: /\.js$/,
  // exclude: /(node_modules|bower_components)/, I had to remove this.
  use: {
    loader: 'babel-loader',
    options: {
      presets: [
        [
          '@babel/preset-env',
          {
            useBuiltIns: 'entry',
          },
        ],
      ],
      plugins: [
        require('@babel/plugin-proposal-object-rest-spread').default,
        require('@babel/plugin-syntax-dynamic-import').default,
      ],
    },
  },
},
```

</details>

**Comment by usb248** [comment]
The error isn't very meaningful ... More in a compressed file in production. Dev mode doesn't work at all.
I use tiptap in nuxt, so i have last 2 version + IE11 in browserlist but still doesn't work.
I haven't a custom webpack config like you.
Can you explain your config ?
@Chrissi2812 

Thanks for your help

**Comment by Chrissi2812** [comment]
@usb248 As I never worked with nuxt.js this is just based on [documentation](https://nuxtjs.org/api/configuration-build/#babel) and this [Comment](https://github.com/nuxt/nuxt.js/issues/1776#issuecomment-395978778)

Example `nuxt.config.js`, I have **not** tested this however:
```js
export default {
  build: {
    babel: {
      presets: ['es2015', 'stage-2'],
      plugins: [
        "transform-dynamic-import", 
        "transform-runtime", 
        "transform-object-rest-spread"
      ],
    },
    extend (config, { isDev, isClient }) {
      config.module.rules.push(
      {
        test: /\.js$/,
        loader: 'babel-loader',
        // exclude: /(node_modules)/
      })
    },
  },
}
```

**Comment by usb248** [comment]
Thanks @Chrissi2812 , It works now. I just need to add highlight.js to transpile package list because this package has been updated to 10.X which dropped the ES5 syntax

![image](https://user-images.githubusercontent.com/7659927/92571513-89842d80-f283-11ea-929a-05c221a051ab.png)

hard hard to maintain code for IE ...
