### ISSUE TITLE
ProseMirror class is ignored when used in <style scoped> 

### ISSUE THREAD

**Issue by ludo237** [ueberdosis/tiptap#829]
**Describe the bug**
When you want to customize the editor you can pass classes to `EditorContent` but that will style the container itself. When you want to style the editable div you have to work with `.ProseMirror` CSS class. That's fine until you try to edit and tweat that class inside a `<style scoped>` tag on a Vue SFC.

**Steps to Reproduce / Codesandbox Example**
1. Go to `App.vue`
2. Toggle scoped from `<style>`
3. See error

Fork this or create a new Codesandbox replicating your error
https://codesandbox.io/s/tiptap-scoped-style-bug-rnlhs

**Expected behavior**
`.ProseMirror` classes should behave equally regardless of the style scope (at least this is what I think it should happen)

**Screenshots**
Codesanbox is enough

**Environment**
 - OS: Windows 10
 - Browser Firefox
 - Version Latest Dev Edition
 - Mobile / Desktop: Desktop

**Comment by Chrissi2812** [comment]
This is expected behaviour of Vue. 
To style child components in scoped style tags you would have to use deep selectors ([Link to Docs](https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors))

```html
<style scoped>
>>> .ProseMirror { /* ... */ }
/deep/ .ProseMirror { /* ... */ }
::v-deep .ProseMirror { /* ... */ }
</style>


For me only the first one worked in your Codesandbox example.
hope this helps :)

**Comment by ludo237** [comment]
That's actually pretty neat. Shame on me on the missing doc part, that happens when you use tools without instructions (vue-loader in this case) 😅
