### ISSUE TITLE
Highlight issue with Internet Explorer

### ISSUE THREAD

**Issue by mcmanussean** [ueberdosis/tiptap#833]
In Internet Explorer, when I have text highlighted and I click any of several buttons (ex: bold, italic, underline) the text is unselected (no longer highlighted).

1. Type some text in the editor using IE
2. Highlight the text
3. click one of the buttons (
4. See error (ex: bold, italic, underline) 

**Expected behavior**
In other browsers, the text remains highlighted, but in IE it is unselected

**Environment**
 - OS: Windows 10
 - Browser: Internet Explorer

 - Mobile / Desktop: Desktop

**Additional context**
Something else I noticed, the tiptap.dev website won't even load on my computer with internet explorer

**Comment by hanspagel** [comment]
Oh, we don’t support IE. That said, according to #826 it seems possible to get tiptap working with IE. Hope that helps!
