### ISSUE TITLE
setSelection() doesn't return the Transaction

### ISSUE THREAD

**Issue by douglance** [ueberdosis/tiptap#836]
`setSelection()` in ProseMirror is meant to return the Transaction (relevant link to [docs](https://prosemirror.net/docs/ref/#state.Transaction.setSelection)). tiptap returns nothing. It seems to me that the tiptap API should mirror the ProseMirror API and it's surprising to me that it seems not be behaving in the same manner.

**Comment by hanspagel** [comment]
Thanks! Would you mind to explain what you’d need the transaction for in your case?

**Comment by douglance** [comment]
I want to use the Transaction to chain `.scrollIntoView()` after setting a selection, which the docs suggest doing: 

>Finally, the scrollIntoView method can be used to ensure that, the next time the state is drawn, the selection is scrolled into view. **You probably want to do that for most user actions.** [[source](https://prosemirror.net/docs/guide/#state.transactions:~:text=Finally%2C%20the%20scrollIntoView%20method%20can%20be,do%20that%20for%20most%20user%20actions.)]

It seems like there are many other things someone would want to do with the Transaction after setting a selection.

**Comment by douglance** [comment]
@hanspagel Is this a change that you would expect could be made in tiptap? Is the goal to match ProseMirror's API, in general?

**Comment by hanspagel** [comment]
Actually, I’m not sure! I have to think about that. Chances are we won’t change that in version 1, as we are already actively developing a completely rewritten tiptap 2. 🤓

Anyway, did you try the `onTransaction` hook or the `transaction` event? Let me know if that helps!
https://tiptap.dev/docs/guide/events.html
