### ISSUE TITLE
CodeBlockHighlight highlighting issue

### ISSUE THREAD

**Issue by pawel-miczka** [ueberdosis/tiptap#843]
**Describe the bug**
Today I noticed that tiptap have big problem with syntax highlighting for Lua language (meybe it's working also on other languages, don't know). I imported Lua language from highlight.js lib 
```js
import lua from 'highlight.js/lib/languages/lua'
```
also imported VS styles:
```js
import 'highlight.js/styles/vs2015.css'
```
and initialized extension:
```js
new CodeBlockHighlight({
   languages: { lua }
})
```

**Screenshots**
and here's how it looks like:
![Zrzut ekranu 2020-09-26 o 00 04 04](https://user-images.githubusercontent.com/5631954/94320627-b9267b80-ff8d-11ea-9046-09f326750ef0.png)
here's how it looks like on highlight.js demo page:
![Zrzut ekranu 2020-09-26 o 00 12 06](https://user-images.githubusercontent.com/5631954/94320653-d0fdff80-ff8d-11ea-892b-acf1367c380d.png)
It only doesn't work for now on **function** keyword

**Environment**
I'm using newest Nuxt btw. Nothing more.

**Comment by pawel-miczka** [comment]
I have highlight.js in 10.2 btw. and it was installed by lowlight and lowlight was installed by tiptap-extensions

**Comment by pawel-miczka** [comment]
Ok so I copied demo code and it looks like this on tiptap:
![Zrzut ekranu 2020-09-26 o 00 29 41](https://user-images.githubusercontent.com/5631954/94321296-7a91c080-ff8f-11ea-9794-1d5c68c77e88.png)

**Comment by hanspagel** [comment]
The CodeHighlight extension tries to guess the language (using highlight.js), probably it doesn’t recognize it’s lua. But I don’t know what we can do to improve that with tiptap. The whole extension is basically highlight.js. 😏
