### ISSUE TITLE
Can't remove empty code-block

### ISSUE THREAD

**Issue by DenisPolyarush** [ueberdosis/tiptap#856]
Can't remove empty Code block if before it empty place. 

Example from demo site
![ezgif com-gif-maker](https://user-images.githubusercontent.com/34160625/96003571-071ef880-0e43-11eb-9dac-26be8ed48b37.gif)

**Comment by hanspagel** [comment]
Thanks! You added the code block with the button and can remove the code block with the button. What would you expect differently?

**Comment by DenisPolyarush** [comment]
Thanks for your reply! I expected deleting code clock immediately by pressing the backspace button if it's empty. The same behavior when you add H1 or other headings. 

In my project, I have only floating, bubble menus. I don't have static menu. So when user create code block by pressing button `<>` in the floating menu, this menu disappear(it's normal behavior) and user cant removes this code block. 

Similarly to the demo site, in the `Floating Menu` tab, you can create a code block or a heading(H1, H2, H3), but you cannot remove it, because of menu is closed. 

Maybe you have any ideas that can help me? Thanks!

**Comment by BrianHung** [comment]
> Maybe you have any ideas that can help me? Thanks!

Write a custom keymap for backspace that checks whether you're in a codeblock and if its empty, delete the codeblock and replace it with a paragraph.

**Comment by philippkuehn** [comment]
this is fixed in v2
