### ISSUE TITLE
Table cell background color with tiptap extensions

### ISSUE THREAD

**Issue by Drabble** [ueberdosis/tiptap#862]
I have made a button to change the `background-color` style attribute of a table cell. I am using `setCellAttr('background','#F100F1')` to change the color, but nothing happens.

Here is an example with my button on the top left of the page. When you select a cell and click on the button, nothing happens.

https://codesandbox.io/s/vue-issue-template-forked-z22wj?file=/src/App.vue

Am I using `setCellAttr` wrong? Thank you!

**Comment by inarendran** [comment]
Same issue here.. Please give solution

**Comment by inarendran** [comment]
Yes there is an issue with `setCellAttr` however you can write your own custom command to do this. refer `node_modules/prosemirror-tables/src/commands.js`

**Comment by Drabble** [comment]
In order to set the color now (with the changes in the pull request), I can use the following code to change the background-color of a cell:

```
<chrome
  value="#000000"
  @input="
    commands.setCellAttr({
      name: 'background',
      value: $event.hex,
  })">
</chrome>
```

**Comment by kevinmelo** [comment]
After the merge i had to extends the TableCell extension

``` javascript
const TipTapExtensionTableCell = TableCell.extend({
	addAttributes() {
		return {
			...this.parent?.(),
			backgroundColor: {
				default: null,
				renderHTML: (attributes) => {
					if (!attributes.backgroundColor) {
						return {}
					}

					return {
						style: `background-color: ${attributes.backgroundColor}`,
					}
				},
				parseHTML: (element) => {
					return element.style.backgroundColor.replace(/['"]+/g, '')
				},
			},
		}
	},
})
```

And when user cluck my button and select an color i use this command
``` javascript
this.editor.chain().focus().setCellAttribute('backgroundColor', color).run()
```
