### ISSUE TITLE
Nested content islands using Vue component slots and Prosemirror Sub-views

### ISSUE THREAD

**Issue by enjibby** [ueberdosis/tiptap#868]
**Is your feature request related to a problem? Please describe.**
While the document-schema structure of ProseMirror provides excellent flexibility and Vue components allow visual and interactive customisation, there is little to support a rich Vue-component tree structure due to the limitations of prosemirror's contenteditable implementation. @marijnh articulated this in [this comment](https://github.com/ProseMirror/prosemirror/issues/745#issuecomment-372384609) when he said that ProseMirror could not support contenteditable islands.

He does, however, point to [an example](https://prosemirror.net/examples/footnote/) where content inside a descendant element of a ineditable section could be made editable using a new instance of prosemirror-view along with a dispatch function to proxy events between the parent and child view.

**Describe the solution you'd like**
I would really like if TipTap could leverage this functionality, along with Vue component slot elements, to allow Vue component editing to result in a rich, nested document indicative of a traditional SGML structure.

I have done some precursor work (which I will soon PR) to pull in the code from the aforementioned example into the `ComponentView` class to instantiate a prosemirror-view instance inside an element of the component (similar to how $refs.content currently works) but ultimately it needs to work much better.

I imagine the `ComponentView` instantiation could detect the slot elements in the new `vm` instance and hook each of them up as a special slot Node, containing a `prosemirror-view` instance with the content provided by the component node's parseDOM().

E.g. the Tiptap Node will expect the DOM input and output to be in a format:

```vue
<staff-list>
  <template v-slot:default="slotProps">
    <h3>Our Staff</h3>
    <p>We are all beautiful!</p>
  </template>
  <template v-slot:staff-members="slotProps">
    <staff-member name="Mr En Jibby" avatar="enjibby-grinning.jpg">
      <template v-slot:default="slotProps">
        <p>Chief Speculative Programming Officer<p>
      </template>
    </staff-member>
  </template>
</staff-list>
```

Perhaps the document schema would have to include:

```javascript
...
stafflist: {
  content: "defaultblockslot staffmemberslot",
  group: "block",
  selectable: true,
  draggable: true,
  parseDOM: [{ tag: "staff-list", }],
  toDOM:() => [ "staff-list"', 0 ],
},
defaultblockslot: {
  content: "block*",
  group: "slot",
  attrs: {
    "v-slot:default": { default: "slotProps", },
  },
  selectable: false,
  draggable: false,
  parseDOM: [{
    tag: "template[v\-slot\:default]",
    getAttrs:(dom) => ({
      "v-slot:default": dom.getAttribute("v-slot:default"),
    }),
  }],
  toDOM:(node) => [ "template", node.attrs, 0 ]
},
staffmemberslot: {
  content: "staffmember*",
  group: "slot",
  attrs: {
    "v-slot:staff-members": { default: "slotProps", },
  },
  selectable: false,
  draggable: false,
  parseDOM: [{
    tag: "template[v\-slot\:staff-members]",
    getAttrs:(dom) => ({
      "v-slot:staff-members": dom.getAttribute("v-slot:staff-members"),
    }),
  }],
  toDOM:(node) => [ "template", node.attrs, 0 ],
},
staffmember: {
  content: "defaultblockslot",
  attrs: {
    name: {},
    avatar: {},
  },
  selectable: true,
  draggable: true,
  parseDOM: [{
    tag: "staff-member",
    getAttrs:(dom) => ({
      name: dom.getAttribute('name'),
      avatar: dom.getAttribute("avatar"),
    }),
  }],
  toDOM:(node) => [{ "staff-member", node.attrs, 0 }],
},
...
```
whether any or all parts of these Node definitions could be automated I am unsure, and defining them may be inconvenient, but the level of editability is greatly increased.

**Describe alternatives you've considered**
I have considered trying to simplify our system and just rely on the existing `ref="content"` / `contentDOM` features of Tiptap, but once I start trying to combine content with Vue component selectability and dragability, this becomes quite impossible and difficult to predict.

**Additional context**
At this point I understand that this feature doesn't feel fully fleshed out, particularly how Vue components themselves will have to be updated to support this design-time editability, but I'm pretty sure this suggestion has legs and has the potential to make Tiptap really powerful.

**Comment by philippkuehn** [comment]
I mark this as out of scope for now.
