### ISSUE TITLE
isActive doesn't work properly for marks with attributes

### ISSUE THREAD

**Issue by benmandr** [ueberdosis/tiptap#877]
**Describe the bug**
isActive does not work for marks with attributes

**Steps to Reproduce / Codesandbox Example**
Everything is outlined in https://github.com/ueberdosis/tiptap/issues/322 and https://github.com/ueberdosis/tiptap/issues/157. These issues were closed because of found "workarounds", but those workarounds found another common bug: `isActive` not working for marks with attributes (for ex., a mark for text align, when toggled, shows all alignment options active)

**Expected behavior**
isActive should return true only on the mark with the corresponding attribute

**Comment by hanspagel** [comment]
Thanks for reporting @benmandr! 

Currently, there is no text align extension provided. If you have built your own, consider to add a custom markIsActive command, which takes attributes into account. Hope that helps!

Also, we do provide text alignment with the (not yet released) tiptap 2 and revamped the whole isActive command and everything related. In other words: It’ll get better soon! ✌️

**Comment by benmandr** [comment]
> Thanks for reporting @benmandr! 
> 
> Currently, there is no text align extension provided. If you have built your own, consider to add a custom markIsActive command, which takes attributes into account. Hope that helps!
> 
> Also, we do provide text alignment with the (not yet released) tiptap 2 and revamped the whole isActive command and everything related. In other words: It’ll get better soon! ✌️

Thank you for the response!

Yes, for now, that is exactly what I did by adding custom command. Can't wait for tiptap2!

**Comment by hanspagel** [comment]
Thanks! Would you mind to share your custom command here? That could be very helpful for others landing here!

**Comment by benmandr** [comment]
Well, dunno if this is the best solution, but I rather used the `getMarkAttrs` function instead of a custom command (used this for my `letterCase` mark extension):
```
UsageOfLettercase.js

	<EditorMenuBubble v-slot="{ commands, getMarkAttrs }" :editor="editor">
		<button
			v-for="letterCase in letterCases"
			:key="letterCase"
			@click="commands.letterCase(isMarkActive(getMarkAttrs, letterCase) ? {} : { letterCase })"
		>
			<CustomIconComponent
				v-if="isMarkActive(getMarkAttrs, letterCase)"
				name="check-mark"
			/>
		</button>
		</EditorMenuBubble>

...
...
...

methods: {
	isMarkActive(getMarkAttrs, letterCase) {
		return getMarkAttrs('letterCase').letterCase === letterCase;
	},
},

...
...
...

LetterCase.js command function:

commands({ type }) {
		return (attrs) => (attrs.letterCase ? updateMark(type, attrs) : removeMark(type));
}
```

This updates the mark isActive status appropriately.
Also, I pass empty payload and do either `updateMark` or `removeMark` depending on the status of isActive. If I don't do this, then, when A is active, pressing on B just deactivates A, and only the second click actives B. This way I solved my issues.

**Comment by hanspagel** [comment]
Thanks for sharing @benmandr! I’m closing this here for now. ✌️
