### ISSUE TITLE
Link plugin doesn't recognise comma or parenthesis as valid part of a URL

### ISSUE THREAD

**Issue by barryspearce** [ueberdosis/tiptap#881]
**Describe the bug**
When pasting in links such as :

https://en.wikipedia.org/wiki/The_Lute_Player_(Caravaggio)

The link stops at the ( and the rest is considered normal text. The same occurs with commas.
This also fails on the demo. 

**Steps to Reproduce / Codesandbox Example**
Copy above link.
Paste using CTRL-V into tip-tap DEMO.

**Expected behavior**
Both commas and parenthesis () should be accepted as URL as they are exceedingly common in their use.

**Environment**
 - OS: Manjaro
 - Browser: Chrome
 - Version: 86.0.4240.111 (Official Build) Arch Linux (64-bit)
 - Mobile / Desktop: Desktop

**Comment by hanspagel** [comment]
Thanks for reporting! A fix will be part of the next release. 👍
