### ISSUE TITLE
Option for paragraph line height 

### ISSUE THREAD

**Issue by PeterDias55** [ueberdosis/tiptap#887]
Implementing a button menu bar that would have options to line height would solve my problem.
[check this out](https://images.app.goo.gl/ohWJxuVDRJmipUvr7)
[and this](https://images.app.goo.gl/KJAjewsUj2crQSJc9)

**Comment by hanspagel** [comment]
You’ll like what we’ve built with the unreleased tiptap 2. There is an extension for TextAlign, which is technically the same as adding line-height support.

That said, we don’t expect a release before end of year, so you’ll still have to wait a while.

Anyway, for tiptap 1 that link points you to an existing line height extension:
https://github.com/Leecason/element-tiptap/blob/master/src/utils/line_height.ts

Hope that helps!

**Comment by akirarika** [comment]
@hanspagel  Will there be a rc version by March next year?

**Comment by hanspagel** [comment]
Yes! We try to hold the following timeline: early access for some sponsors this week, early access for all sponsors end of November, public release candidate in January, stable release in February. 👀

**Comment by hanspagel** [comment]
Closing this here for now, as I consider it as done in tiptap [v2](https://blog.ueber.io/post/our-plan-for-tiptap-2/). 🌿

**Comment by zacharykatsnelson** [comment]
> You’ll like what we’ve built with the unreleased tiptap 2. There is an extension for TextAlign, which is technically the same as adding line-height support.
> 
> That said, we don’t expect a release before end of year, so you’ll still have to wait a while.
> 
> Anyway, for tiptap 1 that link points you to an existing line height extension: https://github.com/Leecason/element-tiptap/blob/master/src/utils/line_height.ts
> 
> Hope that helps!

Hi @hanspagel. Would you mind elaborating further on this :pray: ? If I want to change the line height would I build a file such as this or go into the source code and change something?

**Comment by gregveres** [comment]
Hi, I am adopting v2 right now and I don't see this availble in V2. Yes, there is TextAlign, but that is just for horizontal alignment. This was asking for line height support, which I don't see in V2. Maybe I am missing something.

**Comment by RomikMakavana** [comment]
Also I am integrating line-height feature, but cant find extension in V2.
