### ISSUE TITLE
Copy image relative address link

### ISSUE THREAD

**Issue by daiyang123456** [ueberdosis/tiptap#892]
Upload pictures using relative addresses

1. Upload pictures using relative addresses
2. Select the content of the article that contains images
3. Paste into the word document, the picture does not use the absolute address to display
4. Picture display failed

**Comment by hanspagel** [comment]
Thanks for reporting @daiyang123456! It’s totally up to you if you pass a relative or an absolute URL. For the reason you're mentioning I’d recommend to use absolute URLs in tiptap. But unfortunately that’s nothing we can configure in tiptap, it’s up to you to integrate it with your backend and add absolute URLs. 😏
