### ISSUE TITLE
multiple mentions are not working in suggestions

### ISSUE THREAD

**Issue by DebaPrasad14** [ueberdosis/tiptap#896]
**Describe the bug**
when trying to mention multiple users in the same line it's not working.

**Example**
Can check here in example site: https://tiptap.dev/suggestions

**Expected behavior**
we should able to mention multiple users in one line.

**Comment by ironshu** [comment]
On a related note (I hope this is from the same cause) inserting a mention in an empty editor does not work. **However** it does work if the editor loads with content, and you then delete all the content before inserting a mention.

**Comment by jonathanmach** [comment]
Duplicate of #874

**Comment by hanspagel** [comment]
Thanks for reporting @DebaPrasad14! As Jonathan said, there is already an issue to follow, so I’m closing this here for now.
