### ISSUE TITLE
Extra break appears in code_block, when the last line is an empty new line.

### ISSUE THREAD

**Issue by rajatsingla** [ueberdosis/tiptap#899]
**Describe the bug**
When you remove the last character in the last line, an extra visible break `<br>` is added in the HTML.

**Steps to Reproduce / Codesandbox Example**
This can be reproduced here [https://tiptap.dev/code-highlighting](https://tiptap.dev/code-highlighting)
1. Go to the first code block.
2. Add a new line at the end by pressing Enter.
3. Add a space.
4. Delete the space.
5. You should notice an extra `<br>` added automatically.

**Screenshots**
  ![screenshot](https://i.ibb.co/PmBdFMp/ezgif-com-gif-maker.gif)

**Environment**
 - OS: macOS
 - Browser chrome
 - Mobile / Desktop: Desktop

**Comment by hanspagel** [comment]
Thanks for the report! Fixed in [tiptap v2](https://blog.ueber.io/post/our-plan-for-tiptap-2/). ✌️
