### ISSUE TITLE
Drag handle on mobile

### ISSUE THREAD

**Issue by marctaule** [ueberdosis/tiptap#901]
**Describe the bug**
Drag handle does not work in mobile. It's not compatible with touch devices.

**Steps to Reproduce / Codesandbox Example**
1. Go to https://tiptap.dev/drag-handle with a mobile
2. Try to drag elements
3. You won't be able, 

**Environment**
 - OS: iOS
 - Mobile

**Comment by philippkuehn** [comment]
tiptap uses the underlying drag and drop functionality of prosemirror which uses the native drag and drop API. this API is still not supported on iOS.

so I'm not sure if we can ever support drag and drop for all devices.

**Comment by DenysPoliarush** [comment]
Hi @marctaule, try to add this([https://github.com/timruffles/mobile-drag-drop](https://github.com/timruffles/mobile-drag-drop)) polyfill.
It works for me.

**Comment by hanspagel** [comment]
Thanks for sharing the Polyfill! Looks good to me. :) I’m closing this here for now, but I made a note to add the polyfill to the documentation of [tiptap 2](https://blog.ueber.io/post/our-plan-for-tiptap-2/). 🙌

**Comment by vc-ca** [comment]
Can you elaborate on how you were able to get the polyfill working? Thanks

**Comment by jeromevvb** [comment]
> Hi @marctaule, try to add this(https://github.com/timruffles/mobile-drag-drop) polyfill. It works for me.

Would you please share how you were able to make the polyfill work? Having the same issue here.
Thank you

**Comment by oskarscholander** [comment]
Any news on how to make this feature work on mobile?
