### ISSUE TITLE
Suggestions demo popup problem

### ISSUE THREAD

**Issue by dkrym** [ueberdosis/tiptap#903]
**Describe the bug**
When you type @ sign, popup opens and you can select from the names. If you type some letter, the suggestion content is filtered. At this point, if you decide to delete the letter/letters and the @ sign as well, the popup with suggestions jumps to left top corner and can not be closed/destroyed.

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Go to https://tiptap.dev/suggestions
2. On a new line, type: @, p, backspace, backspace (trigger the suggestion filtering and then delete the letter and the @)
3. The suggestion popup detach from cursor and jumps to the left top corner

**Expected behavior**
When you do not select any suggestion and you delete @ sign, popup disappears completely

**Screenshots**
![git1](https://user-images.githubusercontent.com/9148471/100292490-bf0ffb80-2fd4-11eb-9d25-0b135523b16f.png)
![git2](https://user-images.githubusercontent.com/9148471/100292496-c1725580-2fd4-11eb-8148-37184d4a4a32.png)

**Environment**
 - OS: Win10
 - Browser chrome 87, firefox 83
 - Desktop

**Additional context**
I guess it is bug with demo rather then with the extension itself but if anyone is able to fix it?

Edit:
I have actually noticed that this bug doesn't happen if you delete the letter and @ sign slowly (means, if you let the suggestion list filter), it happens if you press backspace twice fast.

When all works fine and you can't see the bug:
1. Type @, p <wait for suggestion content to be filtered>
2. Press backspace <wait for suggestion content to be filtered>
3. Press backspace again to delete the @ sign - all works as it should

**Comment by zhoujinfu** [comment]
i meet it also. after *debugging* into the demo. `getReferenceClientRect: node.getBoundingClientRect` get x, y dimenssions to zero.
A non-graceful workaround for temporary that do not deep into this library codes:

```javascript
// renders a popup with suggestions
    // tiptap provides a virtualNode object for using popper.js (or tippy.js) for popups
    renderPopup(node) {
      const { x, y, } = node.getBoundingClientRect()
      if (x === 0 && y === 0) {
        return
      }
      node.cachedRect = node.getBoundingClientRect()
      if (this.popup) {
        return
      }

      // ref: https://atomiks.github.io/tippyjs/v6/all-props/
      this.popup = tippy('.page', {
        getReferenceClientRect: () => node.cachedRect,
        appendTo: () => document.body,
        interactive: true,
        sticky: true, // make sure position of tippy is updated when content changes
        plugins: [sticky],
        content: this.$refs.suggestions,
        trigger: 'mouseenter', // manual
        showOnCreate: true,
        theme: 'dark',
        placement: 'top-start',
        inertia: true,
        duration: [400, 200],
      })
    },
```

**Comment by hanspagel** [comment]
Thanks for the report @dkrym  and thanks for the suggested fix @zhoujinfu! I’ve added the fix to the demo. ✌️

**Comment by Rokixy** [comment]
This problem reappeared after the commit [51259c7b8b10eefb3e60e07e3624e777b7ae22c4](https://github.com/ueberdosis/tiptap/commit/51259c7b8b10eefb3e60e07e3624e777b7ae22c4)
