### ISSUE TITLE
Update prosemirror-view to version 1.16.4

### ISSUE THREAD

**Issue by DenysPoliarush** [ueberdosis/tiptap#910]
Hello guys, is it possible to update `prosemirror-view` package to version 1.16.4 instead of 1.15.7.

Here was fixed one bug important for me and I think for everyone.

https://discuss.prosemirror.net/t/unexpected-behavior-when-pressing-enter-safari-mobile/3226

Thanks!

**Comment by hanspagel** [comment]
Thanks for the PR! 👍 I started to prepare the next release and updated all dependencies, including `prosemirror-view`. 

Recent releases introduced too many bugs, so I’ll take some time before I publish a new version, but expect it to happen in the first two weeks of January.
