### ISSUE TITLE
Blinking cursor (caret) doesn't appear in Firefox when in focus

### ISSUE THREAD

**Issue by orvn** [ueberdosis/tiptap#911]
**Describe the bug**
The blinking | cursor (caret), doesn't appear in Firefox when the element is in focus. Once you start typing, it appears, but when the content is empty, it's not visible at all. If you delete the text, the cursor disappears (even if the element is still focused).

**Steps to reproduce**
1. Click on editor in Firefox
2. Don't type anything
3. Cursor does not appear _until_ you type something
4. If you delete all the text, but the element is still in focus, the cursor disappears once again

**Expected behavior**
Caret cursor should appear and blink when in focus, even if there's no text

**Screenshots**
Video of the issue [on Streamable](https://streamable.com/a797e0) _(14 seconds)_

**Environment**
 - OS: MacOS Catalina
 - Browser: Firefox 83.0
 - Version: Tiptap 1.30
 - Mobile / Desktop: Desktop

**Comment by hanspagel** [comment]
Thanks for the report @orvn! Unfortunately, I can’t reproduce the issue on our demo page. Would you mind to provide a CodeSandbox?  Happy to reopen it, when you add additional information to reproduce the issue. 🙌

Here is a video of me using the tiptap.dev demo site with an initially empty content:
https://user-images.githubusercontent.com/1577992/103662581-6a1aba00-4f70-11eb-9c22-68cef49c7fd8.mp4

**Comment by mrfrase3** [comment]
For those that come across this in the future, I was having the same issue but found the problem.

I had a style that was like this:
```css
.ProseMirror p {
  margin: 0;
  display: inline-block;
}
```

This causes the p tag to have a width of 0 if there is no content in it, and thus not display the cursor. To fix this, either remove the display override or set a `min-width: 1px;`

**Comment by bkyerv** [comment]
@mrfrase3 Thank you sharing this workaround. I couldn't apply it as tailwind seems to overwrite all styles. I am wondering what the best way to do the same in the project that uses tailwind?

**Comment by mrfrase3** [comment]
`min-width: 1px !important;` ?

I don't use tailwind, so Im not sure I'd be of much help
