### ISSUE TITLE
Dragging doesn't work when combined with another draggable library

### ISSUE THREAD

**Issue by jasonvarga** [ueberdosis/tiptap#918]
**Describe the bug**

When using `shopify/draggable`'s `Sortable` around a tiptap instance, the draggable feature _within_ the editor no longer works.

I'm aware this might be an issue with `shopify/draggable`, and I'll cross post this over there.
It might also just be a Prosemirror issue.

**Steps to Reproduce / Codesandbox Example**

Here's a screencast of the issue. https://d.pr/v/AqYC6r
You can see me successfully dragging and moving text in the first standalone editor, but failing in the second which is wrapped by sortable. 

Here's the codesandbox where you can try it yourself:
https://codesandbox.io/s/tiptap-prosemirror-draggable-issue-1f34o

**Expected behavior**
The dragging should work. 😄 

**Environment**
 - OS: MacOS 11.1
 - Browser: Firefox 83, Chrome 87, Safari 14.0.2
 - Mobile / Desktop: Desktop

**Comment by philippkuehn** [comment]
I don’t think tiptap does anything that prevents dragging. I think that `shopify/draggable` does not support that but I’m not sure.

Btw: Have you ever tested `vuedraggable`? In my eyes it’s the most stable dragging library for Vue (and also better maintained).

**Comment by jasonvarga** [comment]
Looks like it was the draggable package doing it. We have worked around it now.

I have come across vuedraggable before. I can't remember now why we chose the shopify package over it, but we're in too deep at this point to change 😄 

Thanks for the response!

**Comment by laurensiusadi** [comment]
@jasonvarga sorry replying on a closed issue, I'm experiencing same issue. How did you solve them? Mind to elaborate? Thanks.

**Comment by jasonvarga** [comment]
I believe the fix was to prevent the event bubbling.
See https://github.com/statamic/cms/commit/9f3fa9cd0fd2a3b295e14b460f9ffb29be7e331c
