### ISSUE TITLE
Nuxt, can't mount component when there is tiptap-extensions

### ISSUE THREAD

**Issue by evanlegamer** [ueberdosis/tiptap#922]
**Describe the bug**
When i start my application, and i go to the page where there is tiptap, i get a warn and a blank screen. 

**Steps to Reproduce / Codesandbox Example**
Add tiptap extensions to your components, just one of this is enought

```
import {
  Blockquote,
  CodeBlock,
  HardBreak,
  Heading,
  HorizontalRule,
  Bold,
  Code,
  Italic,
  Link,
  Strike,
  Underline,
  History,
} from "tiptap-extensions";
```

```
  data() {
    return {
      editor: null,
    };
  },
  mounted() {
    this.editor = new Editor({
      content: this.value,
      onUpdate: ({ getHTML }) => {
        this.$emit("input", getHTML());
      },
      extensions: [
        new Blockquote(),
        new BulletList(),
        new CodeBlock(),
        new HardBreak(),
        new Heading({ levels: [1, 2, 3] }),
        new HorizontalRule(),
        new Link(),
        new Bold(),
        new Code(),
        new Italic(),
        new Strike(),
        new Underline(),
        new History(),
      ],
    });
  },
```

**Screenshots**
<img width="394" alt="Capture d’écran 2020-12-23 163051" src="https://user-images.githubusercontent.com/18480367/103041713-7c135a80-4577-11eb-98bd-3b23505cd47a.png">

**Environment**
- Nuxt 2.14.10
- tiptap 1.30.0
- tiptap-extensions 1.33.2

**Additional context**

**Comment by hanspagel** [comment]
Thanks for reporting! Did you use the `<client-only>` tag around your tiptap component?

**Comment by evanlegamer** [comment]
Hi, yes i already tried to add client-only but same thing happen, moreover i'm in an SPA. I will try to make a codesandbox :)

**Comment by ramsane** [comment]
Try putting this in the nuxt.config.js

```js
  ...
  ...
  build: {
    extend(config) {
      config.resolve.alias.vue = 'vue/dist/vue.common'
    },
  },
```

**Comment by evanlegamer** [comment]
Doesn't work :/

**Comment by philippkuehn** [comment]
please provide a codesandbox

**Comment by hanspagel** [comment]
Thanks for the report! It generally works with Nuxt.js, so there must be something specific about your setup. 

I’m starting to go through all issues and closing this here for now, but please provide a CodeSandbox so we can reopen the issue here. 🙌
