### ISSUE TITLE
Editor is forcing to pass new list of extensions as an argument.

### ISSUE THREAD

**Issue by ramsane** [ueberdosis/tiptap#927]
I wish to keep the extensions in a separate list and then use or update the list every time. But, If I save the list of extensions in a separate variable and use it, it is not working for second editor instance. Using it like this doesn't work
```js
...
  this.editor = new Editor({
      extensions: extensions_list,
      content: '<p>This is just a boring paragraph</p>',
      autoFocus: true,
    })
.....
```

if I pass the list of extensions along with the editor(like below), then it works fine as expected for all the imports of the editor. Is this is expected behaviour ?

```js
....
  this.editor = new Editor({
      extensions: [new Bold(), new Italic()],
      content: '<p>This is just a boring paragraph</p>',
      autoFocus: true,
    })
...
```

**Comment by hanspagel** [comment]
Hi @ramsane! Thanks for the report. Unfortunately I can’t reproduce the described issue. Would you mind to provide a CodeSandbox? Here is how I tested it: https://codesandbox.io/s/vue-issue-template-forked-48ojr?file=/src/App.vue

Anyway, a workaround could probably work like this (which kind of clones the list):

```js
this.editor = new Editor({
  extensions: [...extensions_list],
  content: '<p>This is just a boring paragraph</p>',
})
```

I’m closing this here for now.
