### ISSUE TITLE
Calling content property `content` yields unexpected results

### ISSUE THREAD

**Issue by Shaazaam** [ueberdosis/tiptap#929]
Housing the JSON string and object representations of editor content seems to yield strange behavior when initializing the component.

Consider the following object:

```Javascript
customer: {
  knowledge_base: {
    content: '{"type":"doc","content":[{"type":"paragraph","content":[{"type":"text","text":"some stuff"}]}]}'
  },
}
```

Where content is deserialized with `JSON.parse` then handed to the component to be used as the initial `content` value, as outlined in `created()` lifecycle hook for Vue in the block below:

```Javascript
created() {
  this.editor = new Editor({
      content: this.value, //v-model on customer.knowledge_base.content
      extensions: [
          new HardBreak(),
          new Heading({ levels: [1, 2, 3] }),
          new BulletList(),
          new OrderedList(),
          new ListItem(),
          new Bold(),
          new Italic(),
          new Link(),
          new Strike(),
          new Underline(),
          new Placeholder({
              emptyEditorClass: 'is-editor-empty',
              emptyNodeClass: 'is-empty',
              emptyNodeText: 'Type here',
              showOnlyWhenEditable: true,
              showOnlyCurrent: true,
          }),
      ],
      onInit: ({ state, view }) => {
          //
      },
      onUpdate: ({ getJSON }) => {
          this.$emit('input', getJSON())
      },
  });
},
```

Using a property name of `content` results in an object like the following:

```Javascript
{
  0: "{",
  1: """,
  2: "t",
  3: "y",
  4: "p",
  5: "e",
  6: """,
  7: ":",
  8: """,
  9: "d",
  ...etc
}
```

However naming it something else (`text` in this case) yields expected results:

```Javascript
{
  content: [
    0: {
      content: (...)
      type: (...)
    }
  type: "doc"
}
```

If I didn't know any better, I would think the plugin is recursively searching for a property called `content` to perform operations on. I did not see any documentation regarding the matter, so I thought I would bring this up as this behavior seems unintended and unexpected.

**Comment by Shaazaam** [comment]
Please close this issue I am wrong. Additional unnoticed side effects were occurring with another component on the page during initialization.

Don't try to debug before you've had your coffee folks.

**Comment by hanspagel** [comment]
Thanks for the update. 😅 I feel you.
