### ISSUE TITLE
Toggling multiple nodes creates multiple code blocks instead of one

### ISSUE THREAD

**Issue by swuecho** [ueberdosis/tiptap#931]
**Describe the bug**

select more than 1 line of text and apply code. The selected code should be in one code block instead of multiple line of code.

**Steps to Reproduce / Codesandbox Example**
1. Go to 'https://tiptap.dev/'
2. select multiple line of text
3. apply the '<>' button.

**Expected behavior**

multiple select lines should be in 1 code block instead of each code block every line.

**Screenshots**

<img width="744" alt="Screen Shot 2021-01-09 at 10 44 21 AM" src="https://user-images.githubusercontent.com/666683/104081168-e3175b80-5267-11eb-9dc2-d6f2c2b838f9.png">

<img width="744" alt="Screen Shot 2021-01-09 at 10 44 30 AM" src="https://user-images.githubusercontent.com/666683/104081148-bd8a5200-5267-11eb-8fb4-e6d46ef2c298.png">

**Environment**
 - Mobile / Desktop: [eg. Desktop]

**Additional context**

**Comment by mandrade2** [comment]
Still seeing this. Is there a workaround?

**Comment by CaledoniaProject** [comment]
Why is it closed? It's unresolved yet.
