### ISSUE TITLE
how fix error "Cannot read property 'editor' of undefined " !

### ISSUE THREAD

**Issue by sadeqsafaeian** [ueberdosis/tiptap#944]
I am using Nuxtjs and I used Tiptap Editor to create and update content posts. when I try to update a post, this error is received in the console. 
` ERROR  [Vue warn]: Error in created hook (Promise/async): "TypeError: Cannot read property 'editor' of undefined"`  

I have done this things.

```
<client-only>
    <tiptap-editor class="editor__content" v-model="content" ref="tiptap"/>
</client-only>
```

```
 async created() {
    let {data} = await this.$axios.get(`/posts/${encodeURIComponent(this.$route.params.slug)}/edit`
    // this.content = data.content;
    this.$refs.tiptap.editor.setContent(data.content);
  },
```

```
methods: {
    setContent(event) {
      this.content = event
    },
  }
```

i receive the data correctly in the editor, my only problem is that only this error in the console

please help me Thanks

**Comment by DenysPoliarush** [comment]
When the created() hook is called, the component’s template/render function has not been compiled.

That’s why at this moment, `this.$refs.tiptap` is `undefined` - the referenced component simply hasn’t been created yet.

Wrapping the this.$refs in this.$nextTick` will wait for the code render.

This should help you
```
this.$nextTick(() => {
        this.$refs.tiptap.editor.setContent(data.content);
})
```
