### ISSUE TITLE
`commands.setCellAttr` only works with background

### ISSUE THREAD

**Issue by znagadeon** [ueberdosis/tiptap#945]
Hi! I have some problems with dealing table style.

```html
<editor-menu-bar :editor="editor" v-slot="{ commands }">
    <div>
        <!-- it works fine -->
        <button @click="commands.setCellAttr('background', 'red')">Set bg color to red</button>

        <!-- but it does not -->
        <button @click="commands.setCellAttr('border, '1px solid red')">Set border color to red</button>
    </div>
</editor-menu-bar>
```

I guess it's because [TableNodes](https://github.com/ueberdosis/tiptap/blob/main/packages/tiptap-extensions/src/nodes/TableNodes.js) only parses background, especially background color(maybe `background-image` will not work).

**Comment by hanspagel** [comment]
Exactly! You need to copy the `Table` node to your project and add the attributes you want to have. 

(That’ll get waaay easier with tiptap v2.)
