### ISSUE TITLE
Tiptap doesn't work using vite@2

### ISSUE THREAD

**Issue by KevinNTH** [ueberdosis/tiptap#946]
**Describe the bug**
Tiptap cannot be used on [Vite](https://vitejs.dev/)

**Steps to Reproduce / Codesandbox Example**
1. `yarn create @vitejs/app` 
2. `yarn add tiptap`
3. `yarn dev`
4. See error:
```
(node:28071) UnhandledPromiseRejectionWarning: Error: 'default' is not exported by node_modules/vue/dist/vue.runtime.esm-bundler.js, imported by node_modules/tiptap/dist/tiptap.esm.js
```

**Expected behavior**
Tiptap can be installed.

**Screenshots**
![image](https://user-images.githubusercontent.com/1632391/105517875-dec35780-5cd7-11eb-9ff5-67932ad46d5d.png)

**Environment**
 - OS: Ubuntu @ WSL2
 - Browser: N/A

**Comment by hanspagel** [comment]
Thanks for reporting! We don’t have plans to update tiptap v1, but I tested tiptap v2 with vite and it seems to work just fine. 👍

**Comment by thejsbaguette** [comment]
do you have an example ? @hanspagel  It's not working for me

**Comment by hanspagel** [comment]
All demos in the docs are rendered with Vite, so it should work fine.

If you encounter any problems, create a new issue. Don’t forget to add the error message you get.
