### ISSUE TITLE
Titap doesn't work on a fresh Nuxt app

### ISSUE THREAD

**Issue by KevinNTH** [ueberdosis/tiptap#947]
**Describe the bug**
Titap doesn't work on a fresh Nuxt app.

**Steps to Reproduce / Codesandbox Example**
1. `yarn create nuxt-app nuxt-tiptap`
2. `cd nuxt-tiptap && yarn`
3. `yarn add tiptap`
4. [Implement Tiptap basic usage](https://tiptap.dev/docs/guide/installation.html#basic-usage)
5. `yarn dev`
6. See error: `RangeError: Adding different instances of a keyed plugin (plugin$)`

**Expected behavior**
Should work...

**Screenshots**
![image](https://user-images.githubusercontent.com/1632391/105518438-96f10000-5cd8-11eb-841a-55525cee8767.png)

**Environment**
 - OS: Ubuntu @ WSL2
 - Browser: Firefox

**Comment by KevinNTH** [comment]
I am willing to sponsor Tiptap v2 development but v1 should be working without issue... Will be v2 the same in the current stage?

**Comment by Zxibizz** [comment]
I've got the same issue on Nuxt version 2.14.12

**Comment by hanspagel** [comment]
Oh, no! Thanks for reporting! Would you mind to try the recent version and let me know if that fixes the issue?

 - tiptap@1.32.0
 - tiptap-commands@1.17.0
 - tiptap-extensions@1.35.0
 - tiptap-utils@1.13.0

**Comment by hanspagel** [comment]
It’s _working on my machine_™️, so I’m closing this for now. Happy to reopen when the issue still exists!
