### ISSUE TITLE
EditorContent fails to load in IE11

### ISSUE THREAD

**Issue by rhianvanesch** [ueberdosis/tiptap#95]
The `<editor-content>` component fails to load for me in IE11 with the following console error:
```
[Vue warn]: Error in nextTick: "TypeError: Object doesn't support property or method 'append'"
found in
---> <EditorContent>
```

It looks like [`EditorContent.js`](https://github.com/heyscrumpy/tiptap/blob/master/packages/tiptap/src/Components/EditorContent.js#L16) is using `ParentNote.append()`, which is not supported in Internet Explorer 11:
``` javascript
this.$nextTick(() => {
  this.$el.append(editor.element.firstChild)
  editor.setParentComponent(this)
})
```

I've been able to fix it by including [this polyfill](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append#Polyfill) in my code, but it would be great to either have this documented or fixed. Let me know which approach you prefer and I would be happy to help out. 🙂

**Comment by iparrabb** [comment]
Hi @philippkuehn, works on IE9+?, can you attach browser compatibility on Readme?
Thank you.
