### ISSUE TITLE
Problem with html end tags

### ISSUE THREAD

**Issue by do-web** [ueberdosis/tiptap#957]
` this.editor.setContent('<p>Test <custom-element/> 1234</p>');`

Now the content is `<p>Test <custom-element></custom-element></p>`
So 1234 is missing.

It should be `<p>Test <custom-element/> 1234</p>`

It only works if there is a extra close tag:  `this.editor.setContent('<p>Test <custom-element></custom-element> 1234</p>');`

**Comment by hanspagel** [comment]
Thanks for the report! HTML doesn’t have self-closing tags, that’s XML and we don’t have plans to support that, so I’m closing this for now.

See also:
https://discuss.prosemirror.net/t/custom-empty-element-used-as-pagebreak-visual-tab/3129
https://stackoverflow.com/questions/3558119/are-non-void-self-closing-tags-valid-in-html5
https://html.spec.whatwg.org/multipage/syntax.html#start-tags
