### ISSUE TITLE
Inappropriate loader while importing tiptap into the vue component file

### ISSUE THREAD

**Issue by tamanna-makkar** [ueberdosis/tiptap#970]
Am getting this error, while importing tiptap into vue file
```
You may need an appropriate loader to handle this file type.
|     } = this.node;
|     const pos = this.getPos();
|     const newAttrs = { ...this.node.attrs,
|       ...attrs
|     };

```
Anybody can help ?

**Comment by Fraberg** [comment]
@tamanna-makkar Hi bro, did you solve this error ? I got the same, possibly a webpack pb

**Comment by Fraberg** [comment]
see https://kimmy100b.github.io/vue/2021/01/11/vue/

**Comment by royorange** [comment]
same problem +1.
if add in babel-loader will cause other "exports" issue @frabrg

**Comment by hanspagel** [comment]
We’d recommend to use a ready-to-use setups like Vite, Vue CLI, Create React App or one of the other wonderful templates, *or* to properly set up babel. Besides that, I’m afraid we can’t do anything about this issue.
