### ISSUE TITLE
Failed to execute 'setStart' on 'Range'

### ISSUE THREAD

**Issue by homerager** [ueberdosis/tiptap#973]
Get error for ranged text on click on any extension "Failed to execute 'setStart' on 'Range': The offset 4294967295 is larger than the node's length (13)." when using EditorMenuBubble. 
Varsions:
"tiptap": "^1.32.1",
"tiptap-extensions": "^1.35.1",

**Comment by dominik-bln** [comment]
This seems to be the same issue as describe in https://github.com/ueberdosis/tiptap/issues/954
