### ISSUE TITLE
Remove a mention programmatically

### ISSUE THREAD

**Issue by panayotisk** [ueberdosis/tiptap#99]
I would like to be able to remove a custom mention (which is created as a vue component) programmatically and keep only its label (as pure text). I guess I could replace the whole content in the editor, but is this the recommended way or should I somehow use a call to the replaceText() command? Or maybe do something else entirely?

I want to say I am sorry for the continuing series of questions, but I am still trying to figure out how it all fits together. Thank you for your time.

**Comment by panayotisk** [comment]
I need the 2nd (convert mention to text) for my project.

**Comment by panayotisk** [comment]
Well, the general idea is the following: If we assume user mentions and a user deletes his account there should be no connection to the user any more (the mention is not clickable etc), but the username could be useful for future reference. 
You mean we could transform the mention to another kind of node? This could be useful in some other projects as well. Ideally if we could support both options (by somehow allowing replacing of the mention with either text or node) it would cover most cases I guess.

**Comment by hanspagel** [comment]
That sounds like a job for the backend (user deleted → transform nodes to text). I’m closing this issue for now.
