### ISSUE TITLE
回车事件

### ISSUE THREAD

**Issue by wzdfr** [ueberdosis/tiptap#991]
我想要在编辑器中回车时改变默认的DOM标签p,是标签P增加一些额外的属性,如class样式,自定义属性等

以及我想自定义扩展其它插件需要如何做?
请问tiptap支持吗

非常谢谢

**Comment by herrdu** [comment]
p 标签自定义的属性

**Comment by hanspagel** [comment]
Thanks for reporting! Unfortunately, I’m not able to translate your report. :( It looks like you’ve found a solution though, so I’m closing this for now. Feel free to follow up (in English if possible).
