### ISSUE TITLE
Updating from 1.30.0 to 1.32.1 causes compilation failures

### ISSUE THREAD

**Issue by unikitty37** [ueberdosis/tiptap#993]
**Describe the bug**
When updating from tiptap 1.30.0 to 1.32.1, dependencies seem to get broken. Before updating, the site builds correctly. After updating, the build fails with the message

```
./node_modules/tiptap-commands/node_modules/prosemirror-inputrules/dist/index.es.js
Module build failed: Error: ENOENT: no such file or directory, open '/usr/src/frontend/node_modules/tiptap-commands/node_modules/prosemirror-inputrules/dist/index.es.js'
```

**Steps to Reproduce / Codesandbox Example**
Steps to reproduce the behaviour:
1. Place the following entries in the `dependencies` section of package.json of a site built with vue-cli:
```
    "tiptap": "^1.30.0",
    "tiptap-extension-subscript": "^0.1.0",
    "tiptap-extensions": "^1.33.0",
```
2. `yarn install`
3. `yarn run serve`
4. Visit the site
4. Change the tiptap version in package.json to `1.32.1`.
5. `yarn install`
6. Visit the site

**Expected behaviour**
The site's main page displays correctly on both visits.

Updating tiptap and running `yarn install` causes any dependencies to be updated correctly.

**Actual behaviour**
The site's main page displays correctly on the first visit, and fails with the above error message on the second visit.

**Environment**
 - OS: Debian 10 (server), macOS 10.14.6 (browser)
 - Browser: Vivaldi
 - Version: 3.6.2165.40 
 - Mobile / Desktop: Desktop

**Additional context**
I tried to see what changes had been made between the versions, but the lack of a changelog or any meaningful release notes in the Releases section makes this very difficult. I know that in #97 you said that version 2 has changelogs, but please consider implementing one in this version if version 2 isn't due soon…

**Comment by unikitty37** [comment]
Hm — despite what's been said in #577, I was still getting that problem.

Adding this to package.json resolved it:

```
  "resolutions": {
    "prosemirror-model": "1.11.2"
  }
```

but I thought that wasn't necessary now?

**Comment by hanspagel** [comment]
Thanks for reporting! Yes, we weren’t able to get rid of that annoying bug. I’ll release a version with updated dependencies in this week. And I’m closing this here for now. ✌️
