### ISSUE TITLE
Can't wrap inline code in a link

### ISSUE THREAD

**Issue by MarcelloTheArcane** [ueberdosis/tiptap#994]
I want to be able to add a link with the link including an inline code segment.  This is possible with the following markdown:

```md
[some `code` link](https://tiptap.dev)
```

Renders:
[some `code` link](https://tiptap.dev)

I can't find any way to produce this html:

```html
<a href="#"><code>blah</code></a>
<a href="#"><code>blah</code> blah</a>
```

You can see this online, how the `<a>` tags avoid `<code>` tags:

![image](https://user-images.githubusercontent.com/21159570/110484443-907ce300-80e2-11eb-8af8-dcf49b92520d.png)

In fact, here's an example from the [tiptap documentation](https://tiptap.dev/docs/guide/extensions.html):

![image](https://user-images.githubusercontent.com/21159570/110502106-ccb83f80-80f2-11eb-9451-a9324d8d295a.png)

**Comment by MarcelloTheArcane** [comment]
Maybe linked with this: #959

**Comment by hanspagel** [comment]
Thanks for reporting! Yes, that seems to be related, so I’m closing this here. I hope to be able to follow up in the other issue very soon.
